plugins/ca/root-ca/src/org/apache/cloudstack/ca/provider/RootCAProvider.java
plugins/ca/root-ca/test/org/apache/cloudstack/ca/provider/RootCAProviderTest.java
systemvm/patches/debian/config/opt/cloud/bin/patchsystemvm.sh

When auth strictness is set to true, terminate SSH handshake for clients
that do not present valid or any certificates.
This uses the `setNeedClientAuth`, where if the option is set and the
client chooses not to provide authentication information about itself,
the negotiations will stop and the engine will begin its closure
procedure:
https://docs.oracle.com/javase/7/docs/api/javax/net/ssl/SSLEngine.html#setNeedClientAuth(boolean)
Pinging for review - @DaanHoogland @nvazquez @borisstoyanov @wido @mlsorensen and others

CLOUDSTACK-9993: With auth strictness stop SSL handshake for rogue clients

---

plugins/user-authenticators/saml2/src/org/apache/cloudstack/api/command/ListAndSwitchSAMLAccountCmd.java
plugins/user-authenticators/saml2/src/org/apache/cloudstack/api/response/SamlUserAccountResponse.java
ui/scripts/ui-custom/saml.js

This PR is related to the Saml2 user authentication plugin.
The user can list its domains. His/Her domains are presented as the following example:
username/subdomainA
username/subdomainB
However, if a user has two subdomains of the same name (**Dom1/subdomainA** and **Dom2/subdomainA**) the list is presented as follows:
username/subdomainA
username/subdomainA
The proposed change allows showing the full domain name to avoid such cases. Thus, the domains will be presented as follows:
username/Dom1/subdomainA
username/Dom2/subdomainA

CLOUDSTACK-10101: Present the full domain name when listing user's domains in SAML2 plugin

---

client/pom.xml
engine/schema/src/com/cloud/vm/dao/VMInstanceDao.java
engine/schema/src/com/cloud/vm/dao/VMInstanceDaoImpl.java
engine/storage/image/src/org/apache/cloudstack/storage/image/store/ImageStoreImpl.java
plugins/integrations/prometheus/pom.xml
plugins/integrations/prometheus/resources/META-INF/cloudstack/prometheus/module.properties
plugins/integrations/prometheus/resources/META-INF/cloudstack/prometheus/spring-prometheus-context.xml
plugins/integrations/prometheus/src/org/apache/cloudstack/metrics/PrometheusExporter.java
plugins/integrations/prometheus/src/org/apache/cloudstack/metrics/PrometheusExporterImpl.java
plugins/integrations/prometheus/src/org/apache/cloudstack/metrics/PrometheusExporterServer.java
plugins/integrations/prometheus/src/org/apache/cloudstack/metrics/PrometheusExporterServerImpl.java
plugins/pom.xml

This implements a CloudStack Prometheus exporter as a plugin, that serves
metrics on a HTTP port.
FS: https://cwiki.apache.org/confluence/display/CLOUDSTACK/CloudStack+Metrics+Exporter+for+Prometheus
Prometheus: https://prometheus.io/
New global settings:
1. prometheus.exporter.enable - (default: false), Enable the prometheus
exporter plugin, management server restart needed.
2. prometheus.exporter.port - (default: 9595), The prometheus exporter
server port.
3. prometheus.exporter.allowed.ips - (default: 127.0.0.1), List of comma
separated prometheus server ips (with no spaces) that should be allowed to
access the URLs.
The following list  of  metrics are provided  per pop (zone)  with  the exporter:
• Per host:
o CPU cores:  used, total
o CPU usage:  used, total (in MHz)
o Memory  usage: …

CLOUDSTACK-9998: Prometheus Exporter for CloudStack

---

plugins/ca/root-ca/src/org/apache/cloudstack/ca/provider/RootCAProvider.java
plugins/ca/root-ca/test/org/apache/cloudstack/ca/provider/RootCACustomTrustManagerTest.java
plugins/ca/root-ca/test/org/apache/cloudstack/ca/provider/RootCAProviderTest.java
server/test/org/apache/cloudstack/ca/CABackgroundTaskTest.java
server/test/org/apache/cloudstack/ca/CAManagerImplTest.java
utils/src/main/java/org/apache/cloudstack/utils/security/CertUtils.java
utils/src/test/java/org/apache/cloudstack/utils/security/CertUtilsTest.java

- Refactors V3 x509 cert generator to put basic constraint and key usage
extensions when CA cert is created
- Refactors root CA provider to use V3 generator to generate CA cert
Pinging for review - @mlsorensen @nvazquez @borisstoyanov @DaanHoogland  and others

CLOUDSTACK-9993: Have basic constraint in CA certificate

---

usage/src/com/cloud/usage/parser/StorageUsageParser.java

**Bug Description:**
In the listUsage API, the Virtual Size of Snapshot is always displayed as '0'.
**Root Cause:**
In case of snapshots, the usage is accounted for depending on the value of the global parameter, 'usage.snapshot.virtualsize.select'. If set to 'true', the usage calculation is done based on the Virtual Size, and if set to false, it is done based on the Physical size. In the Usage API, this value, (i.e. virtual or physical) is displayed as 'Size' field correctly, but the field 'VirtualSize' is always displayed as 0. This is misleading.
**Expected Output:**
Since this is a Usage API, ideally only that size should be displayed which is used for billing, depending on the value of 'usage.snapshot.virtualsize.select'.
There is another API - the ListSnapshot API that displays …

CLOUDSTACK-10060:ListUsage API always displays the Virtual size as '0' for Usage type=9 (snapshot)

---

server/src/com/cloud/network/guru/DirectPodBasedNetworkGuru.java

in case of DirectPodBasedNetworkGuru

CLOUDSTACK-10007 no isolationmethod check for basic zone

---

plugins/hypervisors/vmware/src/com/cloud/hypervisor/vmware/resource/VmwareResource.java
test/integration/smoke/test_nic.py
vmware-base/src/com/cloud/hypervisor/vmware/util/VmwareHelper.java

When VMs are deployed or nics are plugged, using a static unit number
may cause device configuration errors. This fixes a previous limitation
that more than 7 nics/networks could not be added to a VM.
Pinging for review @sureshanaparti @resmo @GabrielBrascher @PaulAngus @nvazquez @DaanHoogland @borisstoyanov and others
Per the API docs, `unitNumber` need not be set: https://www.vmware.com/support/developer/converter-sdk/conv55_apireference/vim.vm.device.VirtualDevice.html

CLOUDSTACK-10107: For VMware VMs add devices without unit number

---

python/lib/cloudutils/networkConfig.py

CloudUtils getDevInfo function will now return "bridge" instead of "dev" when the name of a ovs bridge is passed.
Bug ticket: https://issues.apache.org/jira/browse/CLOUDSTACK-10081

CLOUDSTACK-10081: getDevInfo now returns correct value

---

server/src/com/cloud/configuration/ConfigurationManagerImpl.java
server/test/com/cloud/configuration/ConfigurationManagerTest.java

https://issues.apache.org/jira/browse/CLOUDSTACK-10057

CLOUDSTACK-10057: listNetworkOfferings now returns the correct number  of offerings.

---

engine/api/src/org/apache/cloudstack/engine/orchestration/service/NetworkOrchestrationService.java
engine/components-api/src/com/cloud/network/vpc/VpcManager.java
server/src/com/cloud/network/router/VpcNetworkHelperImpl.java
server/src/com/cloud/network/vpc/VpcManagerImpl.java
server/src/org/cloud/network/router/deployment/VpcRouterDeploymentDefinition.java
server/test/org/cloud/network/router/deployment/VpcRouterDeploymentDefinitionTest.java
test/integration/plugins/nuagevsp/nuageTestCase.py
test/integration/plugins/nuagevsp/test_nuage_static_nat.py
test/integration/plugins/nuagevsp/test_nuage_vpc_internal_lb.py
test/integration/plugins/nuagevsp/test_nuage_vpc_network.py
test/integration/plugins/nuagevsp/test_nuage_vsp.py

Detail:
When the VPC offering does not contain VpcVirtualRouter as a SourceNat provider,
then we will not add the interface in the public network to the VpcVR. Thus, conserving Public IPs.
Co-Authored-By: Prashanth Manthena prashanth.manthena@nuagenetworks.net

CLOUDSTACK-9832: Do not assign public IP NIC to the VPC VR when the VPC offering does not contain VpcVirtualRouter as a SourceNat provider

---

server/src/com/cloud/server/ManagementServerImpl.java

**ISSUE**
Currently Cloudstack doesn't allow to migrate the VM's between the hosts with different versions of Hypervisors from UI, whereas using API it is possible. Hypervisor itself allows migration of VM's between different versions, like VMware allows migration of VM's from 5.1 ESXi to 5.5 ESXi. Similarly XenServer allows migration from 6.2 to 6.5.
**STEPS TO REPRODUCE**
- Create Cloudstack setup with more than one hosts of different version.
- Try to migrate a VM from lower version host to higher version host.
- On UI, it will not list the hosts with different version. Whereas using API migrateVirtualMachineWithVolume, VM from lower version of host can be migrated to higher version host.
**FIX**
Added a fix, to list hosts of same and higher version on UI while listing hosts that are …

CLOUDSTACK-10120 : Allow migration of VM's from Cloudstack UI between the hosts with different version

---

services/secondary-storage/server/src/org/apache/cloudstack/storage/resource/NfsSecondaryStorageResource.java

**ISSUE**
Upload volume from local fails when global config max.account.seconday.storage is set to -1
**STEPS TO REPRODUCE**
1. Download any volume on your local machine.
2. Change value of global configuration max.account.seconday.storage to -1.
3. Restart Management server.
4. Try to upload a volume from UI using "Upload from Local" option. Upload will fail.
**FIX**
Implementation of -1 option for unlimited secondary storage usage, which is absent in current code.

CLOUDSTACK-10085 : Upload volume from local fails when global config max.account.seconday.storage is set to -1

---

server/src/com/cloud/configuration/ConfigurationManagerImpl.java

The description of the parameter was saying that the parameter has to be bigger than 6, however, in the code we were only accepting values bigger than 10. This PR changes the validation method to accept any number >= 6. We also change other inconsistencies in error messages presented to users. in near by validations
This solves #CLOUDSTACK-10111

[CLOUDSTACK-10111] Fix validation for parameter "vm.password.length"

---

vmware-base/src/com/cloud/hypervisor/vmware/util/VmwareClient.java

[VMware] Successful migration was reported as failure when vCenter session timed out.
- When cancelling a vCenter task, Check whether the vCenter task is cancellable or not. If not, wait for the task to complete.
This closes #544

CLOUDSTACK-8599: [VMware] Successful migration was reported as failure when vCenter session timed out

---

api/src/org/apache/cloudstack/api/ApiConstants.java
api/src/org/apache/cloudstack/api/ResponseGenerator.java
api/src/org/apache/cloudstack/api/command/admin/usage/GetUsageRecordsCmd.java
api/src/org/apache/cloudstack/api/response/UsageRecordResponse.java
engine/schema/src/com/cloud/tags/dao/ResourceTagDao.java
engine/schema/src/com/cloud/tags/dao/ResourceTagsDaoImpl.java
server/src/com/cloud/api/ApiResponseHelper.java

Tags field to be included in the listusagerecords response such that it can be used in billing report. E.g.
"tags":[
{"key":"city","value":"Toronto","resourcetype":"UserVm","resourceid":"a0cca906-f985-4b56-ad11-f33e59c4c733","account":"admin","domainid":"dec39eb8-4f81-11e7-8315-067fa0000031","domain":"ROOT"}
,
{"key":"region","value":"canada","resourcetype":"UserVm","resourceid":"a0cca906-f985-4b56-ad11-f33e59c4c733","account":"admin","domainid":"dec39eb8-4f81-11e7-8315-067fa0000031","domain":"ROOT"}

CLOUDSTACK-9958:Include tags of resources in listUsageRecords API

---

ui/scripts/accounts.js
ui/scripts/instances.js
ui/scripts/network.js
ui/scripts/system.js

The following navigation filtering is supported:
- Instances connected to a network, Networks -> view instances
- View account/owner and instances from a VR, Infra -> VR -> View account (if it's not project or system), view instances, view network(s) (Network -> list of VRs/tab already exists)
- Show redundant state for VPC VRs in parenthesis at Infra -> VRs -> list of VPC VRs
Pinging for review @DaanHoogland @wido @PaulAngus @nvazquez @borisstoyanov @DagSonstebo @glennwagner @rafaelweingartner @GabrielBrascher @fmaximus @ustcweizhou @resmo @NuxRo and others

CLOUDSTACK-10129: Allow navigation from VRs to network, instances, owners etc.

---

framework/db/src/com/cloud/utils/db/GroupBy.java
framework/db/test/com/cloud/utils/db/GroupByTest.java

The GroupBy + having isn't used currently in the code but was not clean. It removes unused arguments and variables and adds a test based on a DAO to show a full example of how to use it.
Signed-off-by: Marc-Aurèle Brothier m@brothier.org

Fix GroupBy (+ having) condition and tests

---

debian/cloudstack-management.postinst
packaging/centos63/cloud.spec
packaging/centos7/cloud.spec

When reinstalling the package, cloudstack-management fails to install properly due to the `log4j.xml` already present.

CLOUDSTACK-10137: Only link log4j if not already present

---

engine/storage/src/org/apache/cloudstack/storage/RemoteHostEndPoint.java
engine/storage/src/org/apache/cloudstack/storage/endpoint/DefaultEndPointSelector.java

This fixes the following:
- Unchecked thread growth in RemoteEndHostEndPoint
- Potential NPE while finding EP for a storage/scope
Unbounded thread growth can be reproduced with following findings:
- Every unreachable template would produce 6 new threads (in a single
ScheduledExecutorService instance) spaced by 10 seconds
- Every reachable template url without the template would produce 1 new
thread (and one ScheduledExecutorService instance), it errors out quickly without
causing more thread growth.
- Every valid url will produce upto 10 threads as the same ep (endpoint
instance) will be reused to query upload/download (async callback)
progresses.
Every RemoteHostEndPoint instances creates its own
ScheduledExecutorService instance which is why in the jstack dump, we
see several threads …

CLOUDSTACK-10136: Fix RemoteHostEndPoint thread growth

---

plugins/integrations/prometheus/src/org/apache/cloudstack/metrics/PrometheusExporterImpl.java

This fixes metrics generation failures when metrics capacities are null.
Pinging for review @ustcweizhou @nvazquez @DaanHoogland @borisstoyanov and others.

CLOUDSTACK-9998: Fix metrics generation failurein prometheus exporter

---

ui/scripts/system.js

This shows the owner account and network of a VR in the VR list view,
and for VPCs shows the VPC name and redundant state of the VPC rVR.
Pinging for review @PaulAngus @borisstoyanov @resmo @nvazquez @DaanHoogland @wido @ustcweizhou @rafaelweingartner  and others

CLOUDSTACK-10129: Show account, network info in VR list view

---

api/src/com/cloud/offering/NetworkOffering.java
api/src/org/apache/cloudstack/api/command/admin/network/CreateNetworkOfferingCmd.java
engine/components-api/src/com/cloud/configuration/ConfigurationManager.java
engine/orchestration/src/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
engine/schema/src/com/cloud/offerings/NetworkOfferingVO.java
plugins/network-elements/juniper-contrail/src/org/apache/cloudstack/network/contrail/management/ContrailManagerImpl.java
plugins/network-elements/nuage-vsp/src/com/cloud/network/manager/NuageVspManagerImpl.java
server/src/com/cloud/configuration/ConfigurationManagerImpl.java
server/src/com/cloud/server/ConfigurationServerImpl.java
server/test/com/cloud/configuration/ConfigurationManagerTest.java
server/test/com/cloud/network/CreatePrivateNetworkTest.java
server/test/com/cloud/vpc/MockConfigurationManagerImpl.java
server/test/com/cloud/vpc/dao/MockNetworkOfferingDaoImpl.java
server/test/org/apache/cloudstack/networkoffering/CreateNetworkOfferingTest.java
setup/db/db/schema-41000to41100.sql
test/integration/plugins/nuagevsp/test_nuage_static_nat.py
tools/marvin/marvin/lib/base.py
ui/scripts/configuration.js

Co-Authored-By: Prashanth Manthena prashanth.manthena@nuagenetworks.net
Bug: https://issues.apache.org/jira/browse/CLOUDSTACK-9398
Design Document: https://cwiki.apache.org/confluence/display/CLOUDSTACK/Network+Offering+for+VPC+based+on+DB+flag

CLOUDSTACK-9450: Network Offering for VPC based on DB flag

---

engine/storage/snapshot/resources/META-INF/cloudstack/core/spring-engine-storage-snapshot-core-context.xml
engine/storage/snapshot/src/org/apache/cloudstack/storage/snapshot/SnapshotDataFactoryImpl.java
engine/storage/snapshot/src/org/apache/cloudstack/storage/snapshot/SnapshotServiceImpl.java
engine/storage/snapshot/src/org/apache/cloudstack/storage/snapshot/SnapshotStateMachineManagerImpl.java
engine/storage/volume/src/org/apache/cloudstack/storage/volume/VolumeDataFactoryImpl.java

Following the discussion on [1], I am proposing the removal of some unnecessary annotation and Spring configurations at cloud-engine-storage-image.
[1] http://mail-archives.apache.org/mod_mbox/cloudstack-dev/201711.mbox/%3CCAGQtxvZ1kc1EmzsMPRqUjOtcDSjr9aEAQGigBNUdVVg4ee%2BHGw%40mail.gmail.com%3E

Remove annotation and "depends-on" declaration not needed at cloud-engine-storage-image

---

server/src/com/cloud/api/ApiResponseHelper.java

Prevent NPE for querying a deleted project.

CLOUDSTACK-10144: fix possible NPE in listVlanIpRanges

---

client/conf/server.properties.in
client/pom.xml
client/src/org/apache/cloudstack/ServerDaemon.java
plugins/integrations/cloudian/pom.xml
pom.xml

Upgrading to jetty 9.4 along with:
- new gzip handler
- redirect `/` to the context path
- add session timeout configuration
- change for cloudian tests

CLOUDSTACK-10012: Jetty 9.4

---

engine/orchestration/src/com/cloud/vm/VirtualMachineManagerImpl.java
server/src/com/cloud/test/DatabaseConfig.java

Depending on the timezone you're running CS (before GMT timezones) you could experience that some jobs are marked as failed since the parent job got a null result despite its child job having successfully done the job. The child job got deleted by the `CleanupTask` ahead of time, due to a missing datetime conversion to GMT timezone.
Jobs are failing with this message: `Job failed with un-handled exception`
The fix intends to correct any datetime used in the code that should be using the GMT timezone instead of the local one since all DB datetime should be stored at GMT.

CLOUDSTACK-10123: any entity should use GMT timestamp values

---

api/src/com/cloud/vm/NicSecondaryIp.java
core/src/com/cloud/agent/api/SecurityGroupRulesCmd.java
core/test/com/cloud/agent/api/SecurityGroupRulesCmdTest.java
engine/schema/src/com/cloud/vm/dao/NicSecondaryIpDaoImpl.java
engine/schema/src/com/cloud/vm/dao/NicSecondaryIpVO.java
plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtStartCommandWrapper.java
plugins/hypervisors/xenserver/src/com/cloud/hypervisor/xenserver/resource/wrapper/xenbase/CitrixStartCommandWrapper.java
scripts/vm/hypervisor/xenserver/vmops
scripts/vm/network/security_group.py

This commit adds support for passing IPv6 Addresses and/or Subnets as
Secondary IPs.
This is groundwork for CLOUDSTACK-9853 where IPv6 Subnets have to be
allowed in the Security Groups of Instances to we can add DHCPv6
Prefix Delegation.
Use ; instead of : for separating addresses, otherwise it would cause
problems with IPv6 Addresses.

CLOUDSTACK-9853: Add support for Secondary IPv6 Addresses and Subnets

---

plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java
plugins/hypervisors/kvm/test/com/cloud/hypervisor/kvm/resource/LibvirtVMDefTest.java

The attribute for the XML element 'controller' should be 'model' and
not 'mode'.
Source: https://libvirt.org/formatdomain.html#elementsControllers
A scsi controller has an optional attribute model, which is one of
'auto', 'buslogic', 'ibmvscsi', 'lsilogic', 'lsisas1068', 'lsisas1078',
'virtio-scsi' or 'vmpvscsi'.
In the current state a regular SCSI device is attached and not a Virtio-SCSI
device.
Afterwards this is what *lspci* reports:
<pre>
root@ub-scsi:~# lspci |grep -i scsi
00:09.0 SCSI storage controller: Red Hat, Inc Virtio SCSI
root@ub-scsi:~# 
</pre>

CLOUDSTACK-10160: Fix typo in Libvirt XML definition for Virtio-SCSI

---

test/integration/smoke/test_deploy_vm_root_resize.py
test/integration/smoke/test_host_annotations.py
test/integration/smoke/test_ssvm.py
test/integration/smoke/test_volumes.py

ssvm tests: 
=== TestName: test_01_list_sec_storage_vm | Status : SUCCESS ===
=== TestName: test_02_list_cpvm_vm | Status : SUCCESS ===
=== TestName: test_03_ssvm_internals | Status : SUCCESS ===
=== TestName: test_04_cpvm_internals | Status : SUCCESS ===
=== TestName: test_05_stop_ssvm | Status : SUCCESS ===
=== TestName: test_06_stop_cpvm | Status : SUCCESS ===
=== TestName: test_07_reboot_ssvm | Status : SUCCESS ===
=== TestName: test_08_reboot_cpvm | Status : SUCCESS ===
=== TestName: test_09_destroy_ssvm | Status : SUCCESS ===
=== TestName: test_10_destroy_cpvm | Status : SUCCESS ===
deploy_vm_root_resize:
=== TestName: test_00_deploy_vm_root_resize | Status : SUCCESS ===
=== TestName: test_01_deploy_vm_root_resize | Status : SUCCESS ===
=== TestName: …

CLOUDSTACK-10154: fixing some smoketests failures

---

server/src/org/apache/cloudstack/affinity/AffinityGroupServiceImpl.java
server/test/org/apache/cloudstack/affinity/AffinityGroupServiceImplTest.java

**Issue:** when dedicating a resource (cluster or host) to a domain, the affinity group which is created is visible to everyone rather than only to the domain that the cluster is dedicated to.
**Cause:** if a resource is not dedicated to an account but a domain, the account parameter is null. The code then uses the domain id from the system account, making the affinity group visible by all accounts.
**Proposal**: if the account is null, then it should use the domain id passed as a parameter, instead of the domain id from the system account.
**Test scenario**: a cluster is dedicated to a domain with id '3'. The affinity group domain map should have '3' as its domain id.
**Before:** id '8' links affinity group '11' to domain '1' (ROOT).
```
select * from affinity_group_domain_map; …
```

CLOUDSTACK-9432: cluster/host dedicated to a domain is owned by the root domain

---

.travis.yml

This rearranges tests in travis.yml to avoid Travis test job timeout.
We can accept this once Travis passed on this PR.

CLOUDSTACK-10070: Rearrange tests to avoid timeout

---

plugins/database/quota/src/org/apache/cloudstack/api/response/QuotaResponseBuilderImpl.java
plugins/database/quota/test/org/apache/cloudstack/api/response/QuotaResponseBuilderImplTest.java

Changed method org.apache.cloudstack.api.response.QuotaResponseBuilderImpl.startOfNextDay(Date) to use the Java 8 Date and time API. I also changed the test cases to stop using JodaTime, which can cause problems sometimes.
We found this problem while checking a problem when compiling ACS 4.10 source code [1]
[1] http://mail-archives.apache.org/mod_mbox/cloudstack-users/201711.mbox/%3CCAA%2B3ouLGRPicr8oxQdaLEX01uzRJN1kwL5%3DT_a3LinTgy%2ByQBg%40mail.gmail.com%3E

[CLOUDSTACK-10184] Re-work method QuotaResponseBuilderImpl.startOfNextDay and its test cases

---

api/src/com/cloud/storage/Storage.java
api/test/com/cloud/storage/StorageTest.java

This used to work in earlier version but was broken during a earlier
refactor.
This commit restores the functionality, but is also adds a boolean
per storage pool type if it supports overprovisioning.
This removes the nasty if which hard codes it.
UnitTests are also added to this commit to verify this functionality
remains stable in future releases.

CLOUDSTACK-8313: Support overprovisioning for local storage

---

api/src/com/cloud/network/vpc/VpcOffering.java
api/src/org/apache/cloudstack/api/response/AcquireIPAddressResponse.java
api/src/org/apache/cloudstack/api/response/IPAddressResponse.java
server/src/com/cloud/vm/UserVmManagerImpl.java
test/metadata/func/flatnetwork.xml
test/metadata/func/roughflatstress.xml
test/metadata/func/securitygroups.xml

A typo that hit me in the eye on the doc.
http://cloudstack.apache.org/api/apidocs-4.10/apis/listPublicIpAddresses.html
Signed-off-by: Yoan Blanc <yoan.blanc@exoscale.ch>

doc: replace virutal by virtual (typo)

---

engine/orchestration/src/com/cloud/vm/VirtualMachineManagerImpl.java

**ISSUE :**
VM start API Job returns success for failed Job
**STEPS TO REPRODUCE :**
1. Stop VM instance.
2. Mark state of associate router as Stopping from DB
3. Execute startVirtualMachine Api from rest client.
4. VM will not start but still main job will return the status as SUCCEEDED, whereas sub-job for command VmWorkStart will return status as failed.

CLOUDSTACK-10176:VM Start Api Job returns success for failed Job

---

setup/db/db/schema-41000to41100.sql

Add XenServer 7.1 and 7.2 interoperablility
Add hypervisor to capabilities list and add guest OS mappings (copied from 7.0.0 mappings initially)
Deprecated mappings not added
links to
https://issues.apache.org/jira/browse/CLOUDSTACK-9839

Add XenServer 7.1 and 7.2 interoperablility

---

engine/schema/src/com/cloud/usage/dao/UsageStorageDaoImpl.java

When a template is copied back to zone after it is deleted. deleted field gets reset to null. delete field is added to Search on template zone mapping table to take care of the existing mapping

CLOUDSTACK-8908 After copying the template charging for that template is stopped

---

plugins/network-elements/juniper-srx/src/com/cloud/network/resource/JuniperSrxResource.java

automatic configure juniper srx/vsrx nat loopback,
constraint condition that manual configure source nat in juniper srx，allowed vm vist public network :
zone : trust to {trust,untrust}
rule : source address {0.0.0.0/0},destination address{0.0.0.0/0} ,do source nat with pool {public network getway ip}.
code change for trust to trust destination or static nat:
1. add srxCommand :CHECK_PRIVATE_IF_EXISTS. for add/delete rule to detect whether exist or not contain DestinationNatRule or StaticNatRule (ruleName_private) in trust zone .
2. add DestinationNatRule  (ruleName_private) to trust zone when ADD DestinationNatRule to untrust .
3. delete DestinationNatRule  (ruleName_private) from trust zone when DELETE DestinationNatRule from untrust.
4. add StaticNatRule (ruleName_private) to trust zone …

CLOUDSTACK-10003 automatic configure juniper srx/vsrx nat loopback,

---

server/src/com/cloud/configuration/ConfigurationManagerImpl.java

**ISSUE :**
Duplicate public VLAN for two different admin accounts.
**STEPS TO REPRODUCE :**
1. Start multiple threads for executing createVlanIpRange API.
2. Make sure multiple threads run in parallel.
3. Verify vlan table in DB, duplicate entry for same VLAN and IP address range will be encountered, just id and uuid will be different, rest all fields will have similar value.
4. Following entry will be observed in vlan table :
`mysql> select * from vlan where vlan_id like 'vlan://77' and removed is null;
+----+--------------------------------------+-----------+--------------+-----------------+---------------------------+----------------+----------------+------------+---------------------+-------------+----------+-----------+---------+---------------------+
| id | uuid …

CLOUDSTACK-10190:Duplicate public VLAN for two different admin accounts.

---

server/src/org/apache/cloudstack/affinity/AffinityGroupServiceImpl.java

Problem:
When a VM is deployed with in an Affinity group which has the cluster dedicated to a subdomain (zone is dedicated to parent domain) it is getting successful. We can also stop the vm and remove the affinity group, but if you want to add back the affinity it is failing.
Following are the steps to reproduce
1. I had created a Domain (Glass SA Parent Domain) and under it a subdomain (Glass SA Subdomain) and created an account to it.
2. Apply dedication to the zone for primary domain (Glass SA Parent Domain)
3. Apply dedication to the cluster for sub domain (Glass SA Subdomain)
4. Logged in with the Account of Subdomain.
5. Created an instance with the affinity (DedicatedGrp-domain-Glass SA Subdomain) - the dedication set with the cluster for the subdomain.
6. Powered off the VM, …

CLOUDSTACK-9875: Unable to re-apply Explicit dedication to VM

---

api/src/com/cloud/offering/ServiceOffering.java
core/src/com/cloud/agent/resource/virtualnetwork/model/VmDhcpConfig.java
engine/schema/src/com/cloud/upgrade/dao/Upgrade218to22.java
server/src/com/cloud/network/IpAddressManagerImpl.java
server/src/com/cloud/network/vpc/VpcManagerImpl.java
server/test/com/cloud/configuration/ConfigurationManagerTest.java
systemvm/patches/debian/config/opt/cloud/bin/configure.py
systemvm/patches/debian/config/opt/cloud/bin/cs/CsDhcp.py
systemvm/patches/debian/config/opt/cloud/bin/cs_dhcp.py
systemvm/patches/debian/config/opt/cloud/testdata/dhcp0001.json
test/integration/component/test_escalations_networks.py
test/systemvm/test_update_config.py

Bug is fixed. Fixed typo 'adress' to 'address' everywhere which leads to correct generation for agent communication json dhcp command.
@rhtyd
@dagsonstebo
Take a look please. Fixes the bug reported by Dag Sonstebo for Basic zone but unable to test carefully for Advanced zone VR. 
Tested in our pre-prod 4.10. 
Create / abc (x.y.z.11), cde (x.y.z.13)
Remove / abc, cde
Create / cde -> /etc/hosts (x.y.z.11 -> cde, x.y.z.13 removed)

CLOUDSTACK-10168 - VR duplicate entries in /etc/hosts when reusing VM name

---

server/src/com/cloud/network/IpAddressManagerImpl.java
test/integration/smoke/test_vpc_vpn.py

The `assignDedicateIpAddress` previously had marked the newly fetched
IP as allocated but now it does not do that. This fails for VPCs
where SNATs IP are retained as allocating and not allocated after
creation.
@yvsubhash @rafaelweingartner and please review.

CLOUDSTACK-9595: Fix regression introduced in #1762

---

systemvm/patches/debian/config/opt/cloud/bin/cs/CsNetfilter.py

We found bug in ACL rules for PrivateGateway for VPC
At a glance - rules not applied - switching Allow All or Deny All (default ACL) - showed as completed - but rules missed.
Result - traffic via PrivateGateway blocked by next DROP rule in next chains
How to reproduce:
1. Enable PrivateGateway for Cloudstack
2. Create VPC
3. Provision new PrivateGateway inside VPC with some VLAN
4. Change ACL (optional step to show that problem not in initial configuration but in config itself)
Expected:
ACL rules applied (inserted) into correspondig ACL_INBOUND/OUTBOUND chanins for PrivateGateway interface (ethX) based on ACL which user choose
Current:
No rules inserted. ACL_INBOUND/OUTBOUND_ethX - empty. Traffic blocked by next DROP rule in FORWARD chain
Affect - all our corporate customers blocked with …

Fix ACL_INBOUND/OUTBOUND rules for PrivateGateway

---

plugins/hypervisors/vmware/src/com/cloud/hypervisor/vmware/resource/VmwareResource.java
server/src/com/cloud/network/NetworkModelImpl.java

Per the following doc, VR's guest/public nic should pick up network
rate from its network offering:
http://docs.cloudstack.apache.org/projects/cloudstack-administration/en/latest/service_offerings.html#network-throttling

CLOUDSTACK-10173: VR's guest/public nic to pick network rate from offering

---

server/src/com/cloud/api/ApiResponseHelper.java
server/src/com/cloud/api/query/dao/UserVmJoinDaoImpl.java

@PaulAngus @borisroman please see if this is what is expected

CLOUDSTACK-9542 make listNics and ListUserVms return uniform NIC data

---

api/src/org/apache/cloudstack/usage/UsageTypes.java
test/integration/component/test_ss_volume_usage.py
usage/src/com/cloud/usage/StorageTypes.java
usage/src/com/cloud/usage/UsageManagerImpl.java
usage/src/com/cloud/usage/parser/StorageUsageParser.java

**Description**: For Volumes on Secondary Storage, (Uploaded Volume) the usage is not accounted for.
**The fix is implemented as follows:**
1. A new Usage Type is added for the Volume on secondary storage : VOLUME_SECONDARY (id=26)
2. A new storage type, 'Volume' is defined.
3. When a volume is uploaded and the usage server executes next,entry will be added to the usage_storage helper table for all the volumes uploaded since the  Usage server executed last.
4. When the uploaded volume is attached, the 'deleted' column in the usage_storage table is set to the time-stamp when the volume was deleted 
5. 2 entries will be added to the cloud_usage table with usage_type=26 and usage_type=6 (Volume usage on primary). One for the duration the volume was on primary and other for the duration it …

Cloudstack 10064: Secondary storage Usage for uploadedVolume is not collected

---

utils/src/main/java/com/cloud/utils/UriUtils.java

[CLOUDSTACK-9772] Template: perform a HEAD request to check file size from a URL

---

plugins/alert-handlers/snmp-alerts/src/org/apache/cloudstack/alert/snmp/SnmpHelper.java

Fix snmptrap alerts info omit to send the field of SnmpConstants.sysUpTime. 
So when standard snmptrapd  receive alerts package the field OID will dislocation

Fix snmptrap alert bug

---

server/src/com/cloud/user/AccountManagerImpl.java

This PR fixes the issue in which there's a leak when doing API call for listing VPC with domain account and projectId=-1.
**Note for reviewers**: The code formatting changed so many lines in the commit but the actual change is in line 2467-2471.

CLOUDSTACK-10175: prevent VPC list leakage

---

engine/schema/src/com/cloud/upgrade/dao/Upgrade41000to41100.java
server/src/com/cloud/vm/UserVmManagerImpl.java
server/test/com/cloud/vm/UserVmManagerTest.java

Python base64 requires that the string is a multiple of 4 characters but
the Apache codec does not. RFC says is not mandatory but the data should
not fail the VR script (vmdata.py).

CLOUDSTACK-9593: userdata: enforce data is a multiple of 4 characters

---

api/src/com/cloud/configuration/Resource.java
api/src/com/cloud/user/ResourceLimitService.java
api/src/org/apache/cloudstack/api/ApiConstants.java
api/src/org/apache/cloudstack/api/command/user/resource/ListResourceLimitsCmd.java
api/src/org/apache/cloudstack/api/response/ResourceCountResponse.java
api/src/org/apache/cloudstack/api/response/ResourceLimitResponse.java
server/src/com/cloud/api/ApiResponseHelper.java
server/src/com/cloud/resourcelimit/ResourceLimitManagerImpl.java
server/test/com/cloud/vpc/MockResourceLimitManagerImpl.java

Add resource type name in request and response.
This adds in the response a new attribute `typename` with the String value for the corresponding resource enum.
```
{
"capacitytotal": 0,
"capacityused": 0,
"percentused": "0",
"type": 19,
"typename": "gpu",
"zoneid": "381d0a95-ed4a-4ad9-b41c-b97073c1a433",
"zonename": "ch-dk-2"
}
```

CLOUDSTACK-9602: API: improve resource limits comprehension

---

server/src/com/cloud/storage/snapshot/SnapshotManagerImpl.java

**ISSUE :**
createSnapshotPolicy API create multiple entries in DB for same parameters, if multiple threads are executed in parallel.
**STEPS TO REPRODUCE :**
1. Created a new machine having root and data disk.
2. Make sure that no existing snapshot policy is present for the volume.
3. Execute multiple threads in parallel for createSnapshotPolicy API having all required parameters exactly same.
4. Verify table snapshot_policy in DB, will get multiple entries for same policy.
5. Once again execute same multiple threads, by changing any API parameter, will see that existing entries are getting modified in DB and no new entries are added.

CLOUDSTACK-10202:createSnapshotPolicy API create multiple entries in DB for same volume.

---

engine/schema/src/com/cloud/user/dao/AccountDao.java
engine/schema/src/com/cloud/user/dao/AccountDaoImpl.java
server/src/com/cloud/api/query/QueryManagerImpl.java

Ran into an issue today where we passed both the "id" and "domainid" parameters into "listAccounts" and received a response despite the account id passed not belonging to the domainid passed.
This PR aims to correct this issue, along with a few other small updates.
JIRA Issue: CLOUDSTACK-9971

CLOUDSTACK-9971: Bugfix/listaccounts parameter consistency

---

engine/storage/snapshot/src/org/apache/cloudstack/storage/snapshot/StorageSystemSnapshotStrategy.java
engine/storage/snapshot/src/org/apache/cloudstack/storage/snapshot/XenserverSnapshotStrategy.java

Added validation to check if any volume(s) are in creating state ,  before performing delete snapshot.

CLOUDSTACK-9932 snapshot is getting deleted while volume is in creating state

---

api/src/org/apache/cloudstack/api/command/user/template/DeleteTemplateCmd.java
engine/schema/src/com/cloud/vm/dao/VMInstanceDao.java
engine/schema/src/com/cloud/vm/dao/VMInstanceDaoImpl.java
server/src/com/cloud/template/TemplateManagerImpl.java
server/test/com/cloud/template/TemplateManagerImplTest.java
ui/scripts/templates.js

For complete description please refer -> [CLOUDSTACK-9607](https://issues.apache.org/jira/browse/CLOUDSTACK-9607)

CLOUDSTACK-9607: Preventing template deletion when template is in use.

---

server/src/com/cloud/api/query/dao/TemplateJoinDaoImpl.java
server/test/com/cloud/api/query/dao/TemplateJoinDaoImplTest.java
test/integration/smoke/test_templates.py

CLOUDSTACK-9599: 
problem:
Using cloudmonkey, when invoking the update template api call, it does not display the isdynamicallyscalable field as part of its template response.
fix done:
org.apache.cloudstack.api.response.TemplateResponse isdynamicallyscalable field is now populated in the server/src/com/cloud/api/query/dao/TemplateJoinDaoImpl.java.newUpdateResponse method. 
Unit test:
the Unit test server/test/com/cloud/api/query/dao/TemplateJoinDaoImplTest.java testNewUpdateResponse() verifies that the TemplateResponse is populated correctly.
Marvin test:
the Marvin nosetest integration/smoke/test_templates.py test_02_edit_template(self) confirms that the template_response.isdynamicallyscalable field gets populated with the   correct user data.
Test scenario:
Using cloudmonkey, when …

"isdynamicallyscalable" Field to UpdateTemplate Response

---

api/src/org/apache/cloudstack/api/ApiConstants.java
plugins/user-authenticators/ldap/src/org/apache/cloudstack/api/response/LinkDomainToLdapResponse.java
plugins/user-authenticators/ldap/src/org/apache/cloudstack/ldap/LdapManagerImpl.java
plugins/user-authenticators/ldap/test/groovy/org/apache/cloudstack/ldap/LinkDomainToLdapCmdSpec.groovy

the internal id is not usefull to the user. It is a bug to return it instead of a uuid.
In the process of fixing the above "name" was deprecated in favour of "ldap_domain".

CLOUDSTACK-10205 make LinkDomainToLdap return UUID instead of internal id

---

services/secondary-storage/server/test/org/apache/cloudstack/storage/resource/NfsSecondaryStorageResourceTest.java

cleaning up in the @After-method so it gets clean in case of exception as well

CLOUDSTACK-10210 cleanup testfile

---

plugins/hypervisors/vmware/src/com/cloud/hypervisor/vmware/manager/VmwareStorageManagerImpl.java

Added '-' chracter while reading Filenames so that filename match exactly with VM name.

CLOUDSTACK-9908 : Primary Storage allocated capacity goes very high after VM snapshot

---

api/src/org/apache/cloudstack/api/ApiConstants.java
api/src/org/apache/cloudstack/api/command/admin/network/CreateManagementNetworkIpRangeCmd.java
api/src/org/apache/cloudstack/api/command/admin/network/DeleteManagementNetworkIpRangeCmd.java
api/src/org/apache/cloudstack/api/response/PodResponse.java
engine/schema/resources/META-INF/db/schema-41000to41100.sql
engine/schema/src/com/cloud/dc/DataCenterIpAddressVO.java
engine/schema/src/com/cloud/dc/dao/DataCenterDao.java
engine/schema/src/com/cloud/dc/dao/DataCenterDaoImpl.java
engine/schema/src/com/cloud/dc/dao/DataCenterIpAddressDao.java
engine/schema/src/com/cloud/dc/dao/DataCenterIpAddressDaoImpl.java
server/src/com/cloud/api/ApiResponseHelper.java
server/src/com/cloud/configuration/ConfigurationManagerImpl.java
server/src/com/cloud/network/IpAddressManagerImpl.java
server/src/com/cloud/network/guru/PodBasedNetworkGuru.java
server/src/com/cloud/server/ConfigurationServerImpl.java
server/test/com/cloud/configuration/ConfigurationManagerTest.java
ui/scripts/system.js
ui/scripts/ui/widgets/multiEdit.js

JIRA Ticket: https://issues.apache.org/jira/browse/CLOUDSTACK-10126
This extends work presented on #2048 on which the ability to extend the management range is provided. 
This PR allows separating the management network subnet on which SSVM and CPVM are from the virtual routers management subnet.
PCI compliance requires that network elements are defined as ‘in scope’ or ‘out of scope’, for compliance purposes. The SSVM and CPVM are both in scope as they allow public HTTP or HTTPS connections. The virtual routers have been defined as out of scope as they have been placed entirely in a firewalled network's segment. However, all of the system VM types share management network. As SSVM and CPVM are both in scope this would bring the virtual routers into scope as well, requiring individual …

CLOUDSTACK-10126: Separate Subnet for SSVM and CPVM

---

api/src/com/cloud/hypervisor/HypervisorGuru.java
core/src/org/apache/cloudstack/storage/command/CopyCommand.java
engine/schema/src/com/cloud/host/dao/HostDao.java
engine/schema/src/com/cloud/host/dao/HostDaoImpl.java
engine/schema/src/org/apache/cloudstack/storage/datastore/db/PrimaryDataStoreDao.java
engine/schema/src/org/apache/cloudstack/storage/datastore/db/PrimaryDataStoreDaoImpl.java
engine/schema/test/org/apache/cloudstack/storage/datastore/db/PrimaryDataStoreDaoImplTest.java
plugins/hypervisors/xenserver/src/com/cloud/hypervisor/XenServerGuru.java
plugins/hypervisors/xenserver/test/com/cloud/hypervisor/XenServerGuruTest.java
pom.xml
server/src/com/cloud/hypervisor/HypervisorGuruBase.java

The first PR(#1176) intended to solve #CLOUDSTACK-9025 was only tackling the problem for CloudStack deployments that use single hypervisor types (restricted to XenServer). Additionally, the lack of information regarding the solution (documentation, test cases and description in PRs and Jira ticket) led the code to be removed in #1124 after a long discussion and analysis in #1056. That piece of code seemed logicless.  It would receive a hostId and then change that hostId for other hostId of the zone without doing any check; it was not even checking the hypervisor and storage in which the host was plugged into.
The problem reported in #CLOUDSTACK-9025 is caused by partial snapshots that are taken in XenServer. This means, we do not take a complete snapshot, but a partial one that contains …

A comprehensive solution for CLOUDSTACK-9025 and CLOUDSTACK-10128.

---

pom.xml

This upgrades bountycastle dependency to latest v1.59.
Pinging for review @DaanHoogland @borisstoyanov @rafaelweingartner @marcaurele @wido  and others

CLOUDSTACK-9632: Upgrade bountycastle to v1.59

---

plugins/hypervisors/xenserver/src/com/cloud/hypervisor/xenserver/discoverer/XcpServerDiscoverer.java
plugins/hypervisors/xenserver/src/com/cloud/hypervisor/xenserver/resource/CitrixResourceBase.java

The xentools iso has been renamed from xs-tools to guest-tools
starting from XenServer 7.0.
This PR is the follow up of #2346
@Reviewers: The main change is in `getIsoVDIByURL` method [line ~2589] the rest is autoformatting.

CLOUDSTACK-10197: Rename xentools iso for XenServer 7.0+

---

systemvm/agent/conf/log4j-cloud.xml

Jira reference: https://issues.apache.org/jira/browse/CLOUDSTACK-10215

CLOUDSTACK-10215: Excessive log4j debug level in CPVM could lead to FS overflow

---

server/src/com/cloud/server/ManagementServerImpl.java
utils/src/main/java/com/cloud/utils/ssh/SSHKeysHelper.java

SSH keys generated by the ACS are only 1024 bit (RSA). The common standard is now at least 2048 bit.
https://issues.apache.org/jira/browse/CLOUDSTACK-10213

CLOUDSTACK-10213: Allow specify SSH key lengh

---

server/src/com/cloud/vm/UserVmManagerImpl.java
server/test/com/cloud/vm/UserVmManagerTest.java

This can otherwise cause problems in Basic Networking where multiple
IPv4 ranges are configured in a POD.

CLOUDSTACK-10212: Update Netmask/Gateway when Changing IPv4 address

---

systemvm/debian/opt/cloud/bin/cs_dhcp.py

When the IPv4 address of a Instance changes we need to make sure the
old entry is removed from the DHCP lease file on the Virtual Router
otherwise the Instance will still get the old lease.

CLOUDSTACK-10217: Clean up old MAC addresses from DHCP lease file

---

plugins/storage/volume/solidfire/src/org/apache/cloudstack/storage/datastore/provider/SolidFireHostListener.java
plugins/storage/volume/solidfire/src/org/apache/cloudstack/storage/datastore/provider/SolidFireSharedHostListener.java
scripts/vm/hypervisor/kvm/setup_agent.sh
server/src/com/cloud/network/IpAddressManagerImpl.java
test/integration/smoke/test_public_ip_range.py
test/integration/smoke/test_ssvm.py

It seems a regression has come in, this PR/commit is to test what
fails/takes time on travis.
This is a stabilization PR to fix tests, included in 4.11.

CLOUDSTACK-10109: Fix regression from PR #2295

---

scripts/vm/hypervisor/xenserver/swiftxenserver

This script is used to upload snapshots to swift and is executed on dom0 of XenServer. The PR make logging from `/var/log/cloud/swiftxenserver.log` more meaningful as the below example;
```
2017-06-15 10:26:32    DEBUG [root] #### CLOUD enter  swift ####
2017-06-15 10:26:32    DEBUG [root] #### CLOUD upload begin    S-12522/d841b62a-7f83-4d5d-9e9d-2940115f7fa9.vhd to swift ####
2017-06-15 10:27:13    DEBUG [root] #### CLOUD upload complete S-12522/d841b62a-7f83-4d5d-9e9d-2940115f7fa9.vhd to swift: 0:00:40 @ 45 MB/s ####
2017-06-15 10:27:13    DEBUG [root] #### CLOUD exit   swift ####
```

CLOUDSTACK-10229: improved logging, removed usued code

---

api/src/org/apache/cloudstack/api/response/HostHAResponse.java
engine/schema/src/com/cloud/upgrade/dao/Upgrade41000to41100.java
packaging/centos63/cloud.spec
packaging/centos7/cloud.spec
server/src/com/cloud/template/HypervisorTemplateAdapter.java
server/src/org/apache/cloudstack/ha/HAManagerImpl.java
test/integration/smoke/test_hostha_simulator.py
test/integration/smoke/test_public_ip_range.py
test/integration/smoke/test_ssvm.py
test/integration/smoke/test_templates.py
test/integration/smoke/test_volumes.py
ui/scripts/templates.js
vmware-base/src/com/cloud/hypervisor/vmware/mo/HostMO.java

- Test and regression fixes
- Packaging/systemvmtemplate fixes
- DB upgrade path related fixes
- Upgrade and post-upgrade failure fixes

CLOUDSTACK-10227: Stabilization fixes for 4.11.0.0

---

test/integration/smoke/test_vm_snapshots.py

As discovered and discussed in #2376, adding some delay after stopping
the VM and reverting VM snapshot passes the
`test_change_service_offering_for_vm_with_snapshots` test case. The
suspect here is userVMDao or background vmsync that may not update
the VM state to PowerOff.
Pinging for review @mike-tutkowski @rafaelweingartner @DaanHoogland and others.
Manually verified with QA:
```
=== TestName: test_change_service_offering_for_vm_with_snapshots | Status : SUCCESS ===
ok
Ran 1 test in 501.359s
OK
```
I think since this only changes the test file, it may be accepted only with at least code reviews. It's not a blocker, but fixing this smoketest will avoid getting incorrect failures.

CLOUDSTACK-10227: Add delay before reverting VM snapshot

---

plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java

The documentation of Libvirt specifies the requirement of using an XML namespace,
when having metadata in the Domain XML. The Nuage extenstion metadata was not
adhering to this specification, and the lastest Libvirt version ignores it in that case.

CLOUDSTACK-10233: use namespace in Libvirt domain metadata.

---

systemvm/debian/opt/cloud/bin/cs/CsAddress.py

In case of isolated networks where VR is not the gateway, both self.config.is_vpc() and self.config.is_router() are false,
but self.config.is_dhcp() is true.
Moved the password server logic to the `if has_metadata` block,
as this is valid for all 3 systemvm types.

CLOUDSTACK-10245: Fix password server

---

scripts/vm/network/security_group.py

With merge of PR #2028 the separator for lines to the Security Group
Python script changed from : to ; to support IPv6 addresses.
This broke certain situations where rules were parsed improperly.
This commit fixes that

CLOUDSTACK-10242: Properly parse incoming rules to Sec Group

---

systemvm/debian/opt/cloud/bin/cs/CsDhcp.py

Delete dnsmasq's leases file when dnsmasq is restarted to avoid it
use old ip-mac-address-vm mapping leases.
Pinging for review - @DaanHoogland @borisstoyanov @nvazquez @wido @rafaelweingartner and others.

CLOUDSTACK-10252: Delete dnsmasq leases file on restart

---

engine/schema/src/com/cloud/upgrade/dao/Upgrade41000to41100.java
plugins/acl/static-role-based/src/org/apache/cloudstack/acl/StaticRoleBasedAPIAccessChecker.java
scripts/util/migrate-dynamicroles.py

- In case commands.properties file is missing, enables dynamic roles.
- Adds a new -D or --default flag to migrate-dynamicroles.py script
to simply update the global setting and use the default role-rule
permissions, without needing rules from old command.properties file.
Pinging for review - @borisstoyanov @DaanHoogland @nvazquez @wido @rafaelweingartner @PaulAngus and others.
Example, dynamic roles migration script run:
````
> python scripts/util/migrate-dynamicroles.py -d --default
Apache CloudStack Role Permission Migration Tool
(c) Apache CloudStack Authors and the ASF, under the Apache License, Version 2.0
Applying the default role permissions, ignoring any provided properties files(s).
Running SQL query: UPDATE `cloud`.`configuration` SET value='true' where …
```

CLOUDSTACK-10236: Enable dynamic roles for missing props file

---

utils/src/main/java/com/cloud/utils/StringUtils.java

We have various places were we use our own StringUtils and other where we use the Apache Commons one.
This PR removes unused functions from the StringUtills but it also makes our own isNotBlank() just a wrapper around the Apache Commons.
In the future we should remove all references we find to our own StringUtils.isNotBlank()

CLOUDSTACK-10225: Deprecate StringUtils in favor of Apache Commons

---

server/src/org/apache/cloudstack/acl/RoleManagerImpl.java

During deletion of role, set name to null. This fixes concurrent
exception issue where previously it would rename the deleted role
with a timestamp.
Pinging for review - @DaanHoogland @nvazquez @borisstoyanov and others.

CLOUDSTACK-10269: On deletion of role set name to null

---

plugins/network-elements/nuage-vsp/src/com/cloud/api/commands/AssociateNuageVspDomainTemplateCmd.java
plugins/network-elements/nuage-vsp/src/com/cloud/network/element/NuageVspElement.java
plugins/network-elements/nuage-vsp/src/com/cloud/network/guru/NuageVspGuestNetworkGuru.java
plugins/network-elements/nuage-vsp/src/com/cloud/network/manager/NuageVspManager.java
plugins/network-elements/nuage-vsp/src/com/cloud/network/manager/NuageVspManagerImpl.java
plugins/network-elements/nuage-vsp/src/com/cloud/util/NuageVspEntityBuilder.java
plugins/network-elements/nuage-vsp/src/com/cloud/util/NuageVspUtil.java
plugins/network-elements/nuage-vsp/test/com/cloud/NuageTest.java
plugins/network-elements/nuage-vsp/test/com/cloud/network/element/NuageVspElementTest.java
test/integration/plugins/nuagevsp/test_nuage_internal_dns.py

We had issues with the broadcast uri not being updated correctly when updating a network offering. This issue was introduced as part of the previous migration PR in which nuage code was added/refactored to allow the VR to take another ip then the .2 ip.

CLOUDSTACK-10218: fix for forced network update in a nuage network

---

api/src/main/java/org/apache/cloudstack/api/command/admin/acl/RoleCmd.java
api/src/org/apache/cloudstack/acl/RoleService.java
api/src/org/apache/cloudstack/api/command/admin/acl/CreateRoleCmd.java
api/src/org/apache/cloudstack/api/command/admin/acl/UpdateRoleCmd.java
api/test/org/apache/cloudstack/api/command/test/UpdateRoleCmdTest.java
server/src/org/apache/cloudstack/acl/RoleManagerImpl.java
test/integration/smoke/test_dynamicroles.py

updateRole was only returning success but one would expect it returns the updated role as json like other update APIs. I have modified the command to return result as json format and tested using cloudmonkey. The command below is an example used for testing using cloudmonkey;
updateRole id=8d06fc8b-b2b6-41cf-8551-39d31b8b9b49 name=User2 type=User description="Second user role" region=local
Ran the 2 Marvin tests successfully: test_dynamicroles.py and test_staticroles.py

CLOUDSTACK-9663 return role on updateRole

---

systemvm/debian/opt/cloud/bin/cs/CsHelper.py

This might (and does block) in certain situations on the VR as
also explained in the Python documentation:
https://docs.python.org/2/library/subprocess.html#subprocess.Popen.wait
Warning This will deadlock when using stdout=PIPE and/or stderr=PIPE
and the child process generates enough output to a pipe such that
it blocks waiting for the OS pipe buffer to accept more data.
Use communicate() to avoid that.
Using the check_output function handles most of this for us and
also provides better error handling.

CLOUDSTACK-10243: Do not use wait() on Python subprocess

---

server/src/com/cloud/network/NetworkModelImpl.java
server/src/com/cloud/network/NetworkServiceImpl.java

When trying to deploy a vm providing a project id and a L2 network id, this error is logged:
````
2018-01-18 09:04:31,749 INFO  [c.c.a.ApiServer] (qtp1310540333-17:ctx-7ff91c56 ctx-8c37c46b ctx-d58064ad) (logid:74e86028) PermissionDenied: Unable to use network with id= 5bee486a-ff20-4db2-b62e-4b4f3485cfff, permission denied on objs: []
````

CLOUDSTACK-10247: L2 network not shared on projects

---

scripts/vm/network/security_group.py

The code in security_group.py is very old.
I looked into using Libvirt network filters for this, but it's lacking functionality we require.
This is my first attempt in cleaning up this file. There is a lot more work to do.
I tested this on a local system with Basic Networking and that worked just fine in my case.
The quality of the code is still horrible though:
<pre>Your code has been rated at 3.60/10 (previous run: 3.56/10, +0.04)</pre>
A lot more work is needed, but I'm taking baby-steps so that it makes the review a bit easier and not one big bang with changes.

CLOUDSTACK-10294: PEP-8 fixes and enhancements to security_group.py

---

engine/schema/src/com/cloud/host/dao/HostDao.java
engine/schema/src/com/cloud/host/dao/HostDaoImpl.java
engine/schema/src/org/apache/cloudstack/storage/datastore/db/PrimaryDataStoreDao.java
engine/schema/src/org/apache/cloudstack/storage/datastore/db/PrimaryDataStoreDaoImpl.java
plugins/hypervisors/xenserver/src/com/cloud/hypervisor/XenServerGuru.java
plugins/hypervisors/xenserver/test/com/cloud/hypervisor/XenServerGuruTest.java
requirements.txt

@mike-tutkowski found a problem in #2315 when converting a snapshot to a template from a storage pool that has been deleted. Following his feedback in #2298 I am creating this PR to address the issue.

[CLOUDSTACK-10128] Simplify the search for host to execute command

---

tools/marvin/marvin/lib/base.py

Currently when new VM created, password property always set to 'password' even if it was auto-generated. Because of this impossible establish SSH connection to host during testing.
https://issues.apache.org/jira/browse/CLOUDSTACK-10295

CLOUDSTACK-10295 Marvin: add support for password-enabled templates

---

agent/src/com/cloud/agent/Agent.java
server/src/com/cloud/hypervisor/kvm/discoverer/LibvirtServerDiscoverer.java

This would make keystore utility scripts being executed as sudoer
in case the process uid/owner is not root but still a sudoer user.
Also fails addHost while securing a KVM host and if keystore fails to be
setup for any reason.

CLOUDSTACK-10283: Sudo to setup agent keystore, fail on host add failure

---

ui/scripts/storage.js

ISSUE
========================
Creating a snapshot from VM Snapshot generates error if hypervisor is not KVM.
STEPS TO REPRODUCE
========================
Create a cloudstack setup with hypervisor other than KVM.
Create an instance.
Take Snapshot of that VM.
Try to take volume snapshot from newly created VM snapshot.
It will throw an error as hypervisor is not KVM.
FIX
========================
As a fix, "Create Snapshot From VM Snapshot" will be hidden from UI, if hypervisor associated with VM snapshot is not KVM.
SCREENSHOT BEFORE FIX
========================
SCREENSHOT AFTER FIX
========================

CLOUDSTACK-10284:Creating a snapshot from VM Snapshot generates error if hypervisor is not KVM.

---

engine/schema/src/main/java/com/cloud/configuration/dao/ResourceCountDao.java
engine/schema/src/main/java/com/cloud/configuration/dao/ResourceCountDaoImpl.java
server/src/main/java/com/cloud/resourcelimit/ResourceLimitManagerImpl.java
test/integration/component/test_updateResourceCount.py

ACS accounts the resources when deploying VMs with custom service offerings. However, there are other methods (such as updateResourceCount) that do not execute the resource accounting properly, and these methods update the resource count for an account in the database. Therefore, if a user deploys VMs with custom service offerings, and later this user calls the “updateResourceCount” method, it (the method) will only account for VMs with normal service offerings, and update this as the number of resources used by the account. This will result in a smaller number of resources to be accounted for the given account than the real used value. The problem becomes worse because if the user starts to delete these VMs, it is possible to reach negative values of resources allocated (breaking all of …

 [CLOUDSTACK-9338] ACS is not accounting resources of VMs with custom service offering properly

---

plugins/network-elements/nuage-vsp/pom.xml
plugins/network-elements/nuage-vsp/src/com/cloud/network/guru/NuageVspGuestNetworkGuru.java
test/integration/plugins/nuagevsp/nuageTestCase.py
test/integration/plugins/nuagevsp/test_nuage_vsp_mngd_subnets.py
tools/marvin/marvin/lib/base.py

CLOUDSTACK-10298: Recreation of an earlier deleted Nuage managed isolated or vpc tier network fails
Added negative tests for feature vsd managed subnets
Added fixes for reacreation of an earlier deleted Nuage managed network
Updated Nuage Vsp CloudStack client to 1.0.8
Co-authored by: Sigert Goeminne <sigert.goeminne@nuagenetworks.net>
https://issues.apache.org/jira/browse/CLOUDSTACK-10298

CLOUDSTACK-10298: fix for recreation of an earlier deleted Nuage managed network

---

deps/install-non-oss.sh
pom.xml

Upgrade to VMware 6.5 vim jar dependency.
Non-oss repo updated with the jar as well - https://github.com/rhtyd/cloudstack-nonoss.

CLOUDSTACK-10306: Upgrade to VMware 6.5 vim jar dependency

---

core/src/main/java/com/cloud/storage/template/IsoProcessor.java
core/src/main/java/com/cloud/storage/template/OVAProcessor.java
core/src/main/java/com/cloud/storage/template/Processor.java
core/src/main/java/com/cloud/storage/template/QCOW2Processor.java
core/src/main/java/com/cloud/storage/template/RawImageProcessor.java
core/src/main/java/com/cloud/storage/template/TARProcessor.java
core/src/main/java/com/cloud/storage/template/VhdProcessor.java
core/src/main/java/com/cloud/storage/template/VmdkProcessor.java
core/src/main/java/org/apache/cloudstack/storage/command/TemplateOrVolumePostUploadCommand.java
plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/guru/VMwareGuru.java
plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/manager/VmwareManager.java
plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/manager/VmwareManagerImpl.java
plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/manager/VmwareStorageManager.java
plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/manager/VmwareStorageManagerImpl.java
plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareSecondaryStorageResourceHandler.java
plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageSubsystemCommandHandler.java
server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
services/secondary-storage/server/src/main/java/org/apache/cloudstack/storage/resource/HttpUploadServerHandler.java
services/secondary-storage/server/src/main/java/org/apache/cloudstack/storage/resource/NfsSecondaryStorageResource.java
services/secondary-storage/server/src/main/java/org/apache/cloudstack/storage/template/DownloadManagerImpl.java
services/secondary-storage/server/src/main/java/org/apache/cloudstack/storage/template/UploadEntity.java
utils/src/main/java/com/cloud/utils/script/Script.java

Problem Statement -
When tried to download a volume of type Vmware with large size, it fails in an hour before generating the URL.
It can be seen in the ssvm logs that ova generation tar command fails/timed out in an hour. The volume is of 800GB and we should be able to increase the timeout. Unfortunately there is not method to do that. There is no global parameter to update the timeout for this operation.
Solution
Add a global parameter 'vmware.package.ova.timeout' for all the tar commands(commands taking long time)

CLOUDSTACK-10054:Volume download times out in 3600 seconds

---

ui/scripts/network.js

Statically passing account (and domainid) results in a conflict when in project view because projectid and account can not be used together. 
Removing the 2 params. fixes the issue. (some whitespace fixes along)

[4.11] CLOUDSTACK-10299: UI: fix error in network listing in project mode

---

utils/src/main/java/com/cloud/utils/DateUtil.java
utils/src/test/java/com/cloud/utils/DateUtilTest.java

Hey, I've stumbled upon a case were I had to jump into the Java code to understand my mistake. When listing an async job, the timestamp is formated in a way that is incompatible with the parameter `startdate`. Notice the `Z` that is required to work.
```console
$ cs listAsyncJobs | jq ".asyncjobs[].created"
"2018-01-08T08:06:20+0100"
"2018-01-08T08:11:52+0100"
```
```
$ cs listAsyncJobs startdate="2018-01-08T08:10:00+0100" | \
jq ".listasyncjobsresponse.errortext"
Cloudstack error: HTTP response 431
"Unable to parse date 2018-01-08T08:10:00+0100 for command
listasyncjobs, please pass dates in the format mentioned in
the api documentation"
```
```
$ cs listAsyncJobs startdate="2018-01-08T08:10:00Z+0100" | jq ".asyncjobs[].created"
"2018-01-08T08:11:52+0100"
```

dateutil: constistency of tzdate input and output

---

api/src/main/java/com/cloud/configuration/Resource.java
api/src/main/java/org/apache/cloudstack/api/response/AccountResponse.java
api/src/main/java/org/apache/cloudstack/api/response/DomainResponse.java
api/src/main/java/org/apache/cloudstack/api/response/ProjectResponse.java
api/src/main/java/org/apache/cloudstack/api/response/ResourceLimitAndCountResponse.java
server/src/main/java/com/cloud/api/query/dao/AccountJoinDaoImpl.java
server/src/main/java/com/cloud/api/query/dao/DomainJoinDaoImpl.java

There is a non-floating points division that is missing the floating part of the secondary storage usage. This will affect methods that use the following SET method org.apache.cloudstack.api.response.AccountResponse.setSecondaryStorageLimit(String).
It affects the listAccounts API method, making it differ from the updateResource count method, which is presented in bytes.

[CLOUDSTACK-10259] Missing float part of secondary storage data in listAccounts method

---

ui/scripts/vpc.js

There is a bug on ACL rules list when a user creates more than 10 rules.
Steps to reproduce this issue:
- Create more than 10 ACL rules.
- Access the ACL rules list page.
- You will see that they are not sorted as they should by the ACL rule number

[CLOUDSTACK-10318] Bug on sorting ACL rules list in chrome

---

plugins/network-elements/vxlan/src/com/cloud/network/guru/VxlanGuestNetworkGuru.java

JIRA Ticket: https://issues.apache.org/jira/browse/CLOUDSTACK-10274
Issue reported by @NuxRo while trying to add an L2 network on a VXLAN physical network:
````
2018-02-06 11:20:27,748 DEBUG [c.c.n.NetworkServiceImpl] (qtp788117692-390:ctx-f1a980be ctx-61be30e8) (logid:0ca0c866) Found physical network id=201 based on requested tags mellanoxvxlan
2018-02-06 11:20:27,749 DEBUG [c.c.n.NetworkServiceImpl] (qtp788117692-390:ctx-f1a980be ctx-61be30e8) (logid:0ca0c866) Found physical network id=201 based on requested tags mellanoxvxlan
2018-02-06 11:20:27,766 DEBUG [c.c.n.g.BigSwitchBcfGuestNetworkGuru] (qtp788117692-390:ctx-f1a980be ctx-61be30e8) (logid:0ca0c866) Refusing to design this network, the physical isolation type is not BCF_SEGMENT
2018-02-06 11:20:27,766 DEBUG …
```

CLOUDSTACK-10274: L2 network refused to be designed on VXLAN physical network

---

.travis.yml
api/src/main/java/org/apache/cloudstack/api/command/admin/storage/FindStoragePoolsForMigrationCmd.java
api/src/test/java/org/apache/cloudstack/api/command/admin/storage/FindStoragePoolsForMigrationCmdTest.java
engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
engine/orchestration/src/test/java/com/cloud/vm/VirtualMachineManagerImplTest.java
engine/schema/src/main/java/com/cloud/hypervisor/dao/HypervisorCapabilitiesDaoImpl.java
engine/schema/src/main/java/org/apache/cloudstack/storage/datastore/db/PrimaryDataStoreDaoImpl.java
engine/storage/src/main/java/org/apache/cloudstack/storage/allocator/ClusterScopeStoragePoolAllocator.java
server/src/main/java/com/cloud/server/ManagementServerImpl.java
server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
server/src/test/java/com/cloud/storage/VolumeApiServiceImplTest.java
setup/db/hypervisor_capabilities.simulator.sql
test/integration/smoke/test_primary_storage.py

CloudStack is logically restricting the migration of local storages to shared storage and vice versa. This restriction is a logical one and can be removed for XenServer deployments. Therefore, we will enable migration of volumes between local-shared storages in XenServers independently of their service offering. This will work as an override mechanism to the disk offering used by volumes. If administrators want to migrate local volumes to a shared storage, they should be able to do so (the hypervisor already allows that). The same the other way around.
Extra information for reviewers:
This PS is introducing an overriding mechanism for volumes placement. We are providing a way for root administrators to override service/disk offering definitions by allocation volumes in storage pools that …

[CLOUDSTACK-10240] ACS cannot migrate a local volume to shared storage

---

systemvm/debian/opt/cloud/bin/cs/CsAddress.py

This allows networks with additional public nics to have correct SNAT iptables rules applied on configuration.
Pinging for review - @ustcweizhou @PaulAngus @DagSonstebo and others.

CLOUDSTACK-10317: Fix SNAT rules for additional public nics

---

plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/discoverer/XcpServerDiscoverer.java
plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/CitrixResourceBase.java
plugins/hypervisors/xenserver/src/test/java/com/cloud/hypervisor/xenserver/discoverer/XcpServerDiscovererTest.java
plugins/hypervisors/xenserver/src/test/java/com/cloud/hypervisor/xenserver/resource/CitrixResourceBaseTest.java
plugins/hypervisors/xenserver/src/test/java/com/cloud/hypervisor/xenserver/resource/XcpOssResourceTest.java
plugins/hypervisors/xenserver/src/test/java/com/cloud/hypervisor/xenserver/resource/XcpServerResourceTest.java
plugins/hypervisors/xenserver/src/test/java/com/cloud/hypervisor/xenserver/resource/XenServer56FP1ResourceTest.java
plugins/hypervisors/xenserver/src/test/java/com/cloud/hypervisor/xenserver/resource/XenServer56ResourceTest.java
plugins/hypervisors/xenserver/src/test/java/com/cloud/hypervisor/xenserver/resource/XenServer56SP2ResourceTest.java
plugins/hypervisors/xenserver/src/test/java/com/cloud/hypervisor/xenserver/resource/XenServer600ResourceTest.java
plugins/hypervisors/xenserver/src/test/java/com/cloud/hypervisor/xenserver/resource/XenServer625ResourceTest.java
plugins/hypervisors/xenserver/src/test/java/com/cloud/hypervisor/xenserver/resource/XenServer650ResourceTest.java

Changes here were suggestions made to #2365, but for some reason, the PR was merged without considering them. Both the update of the ‘displayText’  value and unit test cases were suggested as improvements in that PR.
After coding, I also when through those classes and removed unused variables.
@khos2ow can you take a look here?

[CLOUDSTACK-10197] Update DisplayText of XenServer tools ISO entry in the database when it already exists

---

tools/appliance/systemvmtemplate/template.json

The new Debian 9.4.0 just released (March 10th).

Bump the version of Debian net-installer to 9.4.0

---

api/src/main/java/org/apache/cloudstack/api/command/user/network/CreateNetworkACLCmd.java

`number` contains the doc from another field.
http://cloudstack.apache.org/api/apidocs-4.11/apis/createNetworkACL.html

createNetworkACL: number has the wrong doc

---

server/src/main/java/com/cloud/deploy/DeploymentPlanningManagerImpl.java

ENVIRONMENT 
===================== 
XenServer Version : 6.2 , 7
ISSUE 
================== 
Disabled Xenserver Cluster can still deploy VM's , hosts in the cluster are still active
Repro. steps followed 
================== 
Disabled Cluster from UI. 
Deploy a new VM
Expected Behavior 
After disabling the cluster , the hosts should be disabled. and no VM's can be deployed
Note:
it's the same results for XenServer or simulator, can't deploy on disabled hosts, but can deploy on disabled cluster
Solution:
Added a check to skip disabled clusters when selecting a host to deploy on.
Deploying on a disabled cluster will now result in a InsufficientServerCapacityException, if no enabled clusters are found.
i didn't want to propagate disabling a cluster down to the hosts, because …

CLOUDSTACK-10147 Disabled Xenserver Cluster can still deploy VM's

---

api/src/com/cloud/agent/api/to/VirtualMachineTO.java
plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java
plugins/hypervisors/kvm/test/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java
server/src/com/cloud/hypervisor/KVMGuru.java
server/test/com/cloud/hypervisor/KVMGuruTest.java
test/integration/smoke/test_service_offerings.py

JIRA Ticket: https://issues.apache.org/jira/browse/CLOUDSTACK-10321
Libvirt has the concept of a 'period' and a 'quota'. If the period is 10000 microseconds, a quote can be set, say 5000 and the VM CPU will be limited to only using 5000 microseconds of CPU every 10000 microseconds. 
This patch basically looks at the host CPU MHz (say 2000 MHz), looks at the VM's configured MHz (say 500 MHz), comes up with a percent (25%), then uses that against the period to come up with a quota number (2500). Additionally, it only applies appropriately when the service offering has the CPU cap option set/checkmarked.
These changes are restricted to the KVM hypervisor plugin, where creation of a VM (spec) will consider CPU cap (max speed) defined in the service offering to define and set quota/limits in …

CLOUDSTACK-10321: CPU Cap for KVM

---

systemvm/debian/opt/cloud/bin/checkrouter.sh
systemvm/debian/opt/cloud/templates/check_heartbeat.sh.templ

This fixes a difference issue in rVR heartbeat check script raised
recently on dev@.

CLOUDSTACK-10296: Find time different from last timestamp

---

PULL_REQUEST_TEMPLATE.md

This adds a pull request template. That would look like below:
This adds a pull request for future CloudStack PRs.
Tested on Github.

CLOUDSTACK-10330 PULL_REQUEST_TEMPLATE: Add pull request template

---

agent/src/com/cloud/agent/direct/download/DirectTemplateDownloaderImpl.java
agent/src/com/cloud/agent/direct/download/HttpDirectTemplateDownloader.java
agent/src/com/cloud/agent/direct/download/HttpsDirectTemplateDownloader.java
agent/src/com/cloud/agent/direct/download/MetalinkDirectTemplateDownloader.java
api/src/com/cloud/event/EventTypes.java
api/src/org/apache/cloudstack/api/command/admin/direct/download/UploadTemplateDirectDownloadCertificate.java
core/src/com/cloud/storage/template/MetalinkTemplateDownloader.java
core/src/org/apache/cloudstack/agent/directdownload/DirectDownloadAnswer.java
core/src/org/apache/cloudstack/agent/directdownload/DirectDownloadCommand.java
core/src/org/apache/cloudstack/agent/directdownload/HttpDirectDownloadCommand.java
core/src/org/apache/cloudstack/agent/directdownload/HttpsDirectDownloadCommand.java
core/src/org/apache/cloudstack/agent/directdownload/MetalinkDirectDownloadCommand.java
core/src/org/apache/cloudstack/agent/directdownload/NfsDirectDownloadCommand.java
framework/direct-download/src/org/apache/cloudstack/framework/agent/direct/download/DirectDownloadService.java
plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java
server/src/com/cloud/vm/UserVmManagerImpl.java
server/src/org/apache/cloudstack/direct/download/DirectDownloadManagerImpl.java
utils/src/main/java/com/cloud/utils/UriUtils.java

Several fixes addressed:
- Dettach ISO fails when trying to detach a direct download ISO
- Fix for metalink support on SSVM agents (this closes CLOUDSTACK-10238)
- Reinstall VM from bypassed registered template (this closes CLOUDSTACK-10250)
- Fix upload certificate error message even though operation was successful
- Fix metalink download, checksum retry logic and metalink SSVM downloader

CLOUDSTACK-10231: Asserted fixes for Direct Download on KVM

---

scripts/installer/windows/client.wxs
ui/index.html

CloudStack main page requests a script "client/scripts/vm_snapshots.js", which does exist since ACS 4.10, causing a HTTP 404 error.
This commit remove the references to this deleted file (deleted in commit a2428508e29)
Run CloudStack and access to UI.

CLOUDSTACK-10331: Remove reference to deleted script vm_snapshots.js

---

engine/schema/src/com/cloud/vm/VMInstanceVO.java

This adds a missing setter to set hypervisorType in VMInstanceVO. The consumer is a 3rd party network plugin that may require the method for integration.

CLOUDSTACK-10340: Add setter to hypervisorType in VMInstanceVO

---

framework/db/src/main/java/com/cloud/utils/db/GenericDaoBase.java

Under some circumstances, the API is returning an invalid response, for simplicity I will expose the JSON case. The API response on a `listVirtualMachines` can be this string:
```
{ "listvirtualmachinesresponse" :  ] } }
```
To understand how this is possible, assume you have more than one management server and one is processing the destroy of a virtual machine in the account X which is the only one it has. Another process is returning the result of `listVirtualMachines` for that same account X. During the listVM command, the result set is fetch with a `searchAndDistinctCount` due to the view (https://github.com/apache/cloudstack/blob/master/server/src/main/java/com/cloud/api/query/QueryManagerImpl.java#L1024). This is done through 2 queries in the GenericDao …

CLOUDSTACK-10320 - Invalid pair for response object breaking response parsing

---

client/conf/java.security.ciphers.in
utils/src/main/java/org/apache/cloudstack/utils/security/SSLUtils.java
utils/src/test/java/com/cloud/utils/security/SSLUtilsTest.java

This reverts changes from #2480, instead moves TLS settings to
java ciphers settings config file. It should be sufficient to enforce
TLS v1.2 on public facing CloudStack services:
- CloudStack webserver (Jetty based)
- Apache2 for secondary storage VM
- CPVM HTTPs server

CLOUDSTACK-10319: Allow TLSv1, v1.1 for XenServer, Vmware

---

plugins/hypervisors/xenserver/src/com/cloud/hypervisor/xenserver/resource/CitrixResourceBase.java
systemvm/debian/opt/cloud/bin/setup/cloud-early-config

Publishing boot args both to grub and xenstore-data and let
cloud-early-config decides if the VM is in PV or HVM mode
to read from correct source.

CLOUDSTACK-10232: SystemVMs and VR to run as HVM on XenServer

---

engine/schema/src/main/java/com/cloud/host/dao/HostDao.java
engine/schema/src/main/java/com/cloud/host/dao/HostDaoImpl.java
server/src/main/java/com/cloud/hypervisor/CloudZonesStartupProcessor.java

Remove unnecessary annotation of HostDaoImpl. While removing this annotation I noticed that one of the methods were not necessary. While removing it, I found some code in CloudZonesStartupProcessor that was also not used, and removed it.

[CLOUDSTACK-10307] Remove unused things from HostDaoImpl

---

packaging/centos63/cloud.spec
packaging/centos7/cloud.spec

This fixes the mkdir path `/usr/bin` for el6/7 rpms.

packaging: Fix mkdir path for centos rpms

---

systemvm/debian/opt/cloud/bin/checkrouter.sh
test/integration/smoke/test_vpc_redundant.py
tools/appliance/build.sh
tools/appliance/systemvmtemplate/http/preseed.cfg
tools/appliance/systemvmtemplate/scripts/apt_upgrade.sh
tools/appliance/systemvmtemplate/scripts/cleanup.sh
tools/appliance/systemvmtemplate/scripts/install_systemvm_packages.sh
tools/appliance/systemvmtemplate/template.json

This reduces systemvmtemplate size by 600MB and installs nftables,
updates iptables.
Manually built using packer and tested locally by running smoketests.

CLOUDSTACK-10341: Reduce systemvmtemplate size, install nftables

---

engine/schema/resources/META-INF/db/schema-41000to41100.sql

this script has been modified to add a stored procedure that allows a developer to call it in order to add a column in an idempotent manner to a table. This means that running the same script more than once will not cause an error trying to add the same column again. It will have not effect. The script needs to tested by running an upgrade from 410 to 411 and then re-run the upgrade to test if it is idempotency.

CLOUDSTACK-10278 idempotent column addition

---

api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
api/src/main/java/org/apache/cloudstack/api/command/user/network/UpdateNetworkACLItemCmd.java
server/src/main/java/com/cloud/network/vpc/NetworkACLServiceImpl.java
server/src/test/java/com/cloud/network/vpc/NetworkACLServiceImplTest.java
ui/scripts/vpc.js

Users should be able to edit an ACL rule completely. Therefore, they must be able to change the protocol type and others configs of an ACL rules.
In addition, it is not just the protocol that users are not able to change. For instance, after defining ports, or reason/description for the rule, users are not able to set those values back to null. The same happens for ICMP code and type.
We will introduce a new parameter called "partialUpdate", which will have its default value as true to maintain backward compatibility. When this parameter is set to false, we will consider only the parameters sent, and not the parameters we already have in the database to change and validate the ACL rule data. This allows us to update parameters already set back to null, and to completely change an ACL …

[CLOUDSTACK-10332] Users are not able to change/edit the protocol of an ACL rule 

---

engine/schema/src/main/java/com/cloud/dc/VlanVO.java
engine/schema/src/main/resources/META-INF/db/schema-41100to41200.sql
server/src/main/java/com/cloud/test/PodZoneConfig.java

Fix the name of the column used to hold IPv4 range in 'vlan' table.

---

engine/storage/datamotion/src/org/apache/cloudstack/storage/motion/StorageSystemDataMotionStrategy.java
engine/storage/snapshot/src/org/apache/cloudstack/storage/snapshot/StorageSystemSnapshotStrategy.java

Update the StorageSystemSnapshotStrategy and StorageSystemDataMotionStrategy classes to only leverage a host when its Resource State is Enabled.
https://issues.apache.org/jira/browse/CLOUDSTACK-10345
Checked to see if a host in maintenance mode is avoided

Only use the host if its Resource State is Enabled.

---

plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/CitrixResourceBase.java
plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/Xenserver625StorageProcessor.java
plugins/hypervisors/xenserver/src/test/java/com/cloud/hypervisor/xenserver/resource/XenServer625ResourceTest.java
plugins/hypervisors/xenserver/src/test/java/com/cloud/hypervisor/xenserver/resource/Xenserver625StorageProcessorTest.java

Due to a race condition between multiple management servers, in some rare cases, CloudStack is creating multiple file SRs to the same secondary folder. This causes a problem when introducing the SR to the XenServer pools, as “there will be VDIs with duplicated UUIDs“. The VDIs are the same, but they are seen in different SRs, and therefore cause an error.
The solution to avoid race conditions between management servers is to use a deterministic srUuid for the file SR to be created (we are leaving XenServer with the burden of managing race conditions). The UUID is based on the SR file path and is generated using  `UUID.nameUUIDFromBytes`. Therefore, if there is an SR with the generated UUID, this means that some other management server has just created it. An exception will occur and it …

[CLOUDSTACK-10241] Duplicated file SRs being created in XenServer pools

---

ui/scripts/instances.js

As an admin /me wants to have easy access the broadcast uri ad the isolation uri used for a nic. these fields were missing in the UI while available in the API.
This can be argued to not be a bug, but it is a trivial fix of an old ommision, so feel free to argue it should't go in 4.11.
tested this by creating a user in the simulator and let it create a VM. Next view the NICs tab of the VM as normal user and as admin. The proof is in the screenshots.

make Broadcast- and IsolationURI visible to admin

---

debian/cloudstack-usage.preinst

This removes old cloudstack-usage jars during upgrade as part of
the pre-install step of cloudstack-usage deb package.
This fixes #2542
Testing

debian: remove old usage jars during upgrade

---

plugins/user-authenticators/ldap/src/org/apache/cloudstack/ldap/ADLdapUserManagerImpl.java
plugins/user-authenticators/ldap/src/org/apache/cloudstack/ldap/LdapAuthenticator.java
plugins/user-authenticators/ldap/test/org/apache/cloudstack/api/command/LdapConfigurationChanger.java
plugins/user-authenticators/ldap/test/org/apache/cloudstack/ldap/ADLdapUserManagerImplTest.java
plugins/user-authenticators/ldap/test/org/apache/cloudstack/ldap/LdapAuthenticatorTest.java

ldap accounts that where not automatically imported but mapped manually were not able to login. fixed.
see https://lists.apache.org/thread.html/43ef6cc4bcf12340f8ac1c05fbcb7bf3afc3d6ed3b05ff509b9c6152@%3Cusers.cloudstack.apache.org%3E
this has only unit tests as an integration test requires an external system
it was tested manually using an openldap and a microsoft ad implementation

manual mapped ldap fix

---

engine/schema/resources/META-INF/db/schema-41100to41110-cleanup.sql
engine/schema/resources/META-INF/db/schema-41100to41110.sql
engine/schema/src/com/cloud/upgrade/DatabaseUpgradeChecker.java
engine/schema/src/com/cloud/upgrade/dao/Upgrade41100to41110.java
engine/schema/test/com/cloud/upgrade/DatabaseUpgradeCheckerTest.java

Jira ticket: https://issues.apache.org/jira/browse/CLOUDSTACK-10325
Also, add the missing 'VMWare version to OS mappings' SQL in the schema-41100to41110.sql file. This fixes an upgrade failure for certain guest OSs where the Virtual Router fails to start when these version mappings are missing.
Dev Tested the schema-41100to41110.sql file by executing it with the com/cloud/utils/db/ScriptRunner.java class. Before and after data samples confirm a test pass status.

Create database upgrade from 4.11.0.0 to 4.11.1.0 & VMWare version to OS mappings

---

api/src/main/java/com/cloud/network/vpc/NetworkACLService.java
api/src/main/java/org/apache/cloudstack/api/command/user/network/UpdateNetworkACLListCmd.java
engine/schema/src/main/java/com/cloud/network/vpc/NetworkACLVO.java
server/src/main/java/com/cloud/network/vpc/NetworkACLServiceImpl.java
server/src/test/java/com/cloud/network/vpc/NetworkACLServiceImplTest.java
ui/l10n/ar.js
ui/l10n/ca.js
ui/l10n/de_DE.js
ui/l10n/en.js
ui/l10n/es.js
ui/l10n/fr_FR.js
ui/l10n/hu.js
ui/l10n/it_IT.js
ui/l10n/ja_JP.js
ui/l10n/ko_KR.js
ui/l10n/nb_NO.js
ui/l10n/nl_NL.js
ui/l10n/pl.js
ui/l10n/pt_BR.js
ui/l10n/ru_RU.js
ui/l10n/zh_CN.js
ui/scripts/ui/widgets/detailView.js
ui/scripts/vpc.js

Currently, it is not possible to update the Network ACL name or Description of an ACL after it has been created. It might be interesting to expose this option via API and to add this feature to the UI.
The Screenshot shows the fields that this PR will allow updating.

[CLOUDSTACK-10301] Allow updating the network ACL list name and Description

---

plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/CitrixResourceBase.java
plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/XenServer56Resource.java
plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/Xenserver625StorageProcessor.java
plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/XsHost.java
plugins/hypervisors/xenserver/src/test/java/com/cloud/hypervisor/xenserver/resource/CitrixResourceBaseTest.java
plugins/hypervisors/xenserver/src/test/java/com/cloud/hypervisor/xenserver/resource/XcpOssResourceTest.java
plugins/hypervisors/xenserver/src/test/java/com/cloud/hypervisor/xenserver/resource/XcpServerResourceTest.java
plugins/hypervisors/xenserver/src/test/java/com/cloud/hypervisor/xenserver/resource/XenServer56FP1ResourceTest.java
plugins/hypervisors/xenserver/src/test/java/com/cloud/hypervisor/xenserver/resource/XenServer56ResourceTest.java
plugins/hypervisors/xenserver/src/test/java/com/cloud/hypervisor/xenserver/resource/XenServer56SP2ResourceTest.java
plugins/hypervisors/xenserver/src/test/java/com/cloud/hypervisor/xenserver/resource/XenServer600ResourceTest.java
plugins/hypervisors/xenserver/src/test/java/com/cloud/hypervisor/xenserver/resource/XenServer650ResourceTest.java
server/src/main/java/com/cloud/server/ManagementServerImpl.java
server/src/main/java/com/cloud/storage/StorageManagerImpl.java
server/src/test/java/com/cloud/storage/StorageManagerImplTest.java

CloudStack is importing as Local storage any XenServer SR that is of type LVM or EXT. This causes a problem when one wants to use both Direct attach storage and local storage. Moreover, CloudStack was not importing all of the local storage that a host has available when local storage is enabled. It was only importing the First SR it sees.
To fix the first problem we started ignoring SRs that have the flag shared=true when discovering local storages. SRs configured to be shared are used as direct attached storage, and therefore should not be imported again as local ones.
To fix the second problem, we started loading all Local storage and importing them accordingly to ACS.
Tip for reviewers: the code changes is mainly in `CitrixResourceBase`, method `initializeLocalSR`

[CLOUDSTACK-10226] CloudStack is not importing Local storage properly

---

python/lib/cloud_utils.py
python/lib/cloudutils/serviceConfig.py

debian: Use only `-l` for libvirtd default file on debian

---

server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
server/src/test/java/com/cloud/vm/UserVmManagerTest.java
server/test/com/cloud/vm/UserVmManagerImplTest.java

Users are able to change the OS type of VMs to a “Guest OS type” that has been removed. This becomes a security issue when we try to force users to use HVM VMs (Meltdown/Spectre thing). A removed “guest os type” should not be usable by any users in the cloud.

[CLOUDSTACK-10230] User should not be able to use removed “Guest OS type”

---

PULL_REQUEST_TEMPLATE.md

Added GitHub issue section to `PULL_REQUEST_TEMPLATE.md` with `Fixes: #<issue_id>` format. With this addition, the referenced issue will automatically be closed when PR gets merged.
Testing

Add "Fixes: number" to PR template for auto-closing issues

---

api/src/main/java/com/cloud/storage/StorageService.java
server/src/main/java/com/cloud/storage/StorageManagerImpl.java

When enabling the use of local storage ACS will automatically load all local storage configured in the Host and start using them as primary storage to deploy user VMs (if the service offering allows to do so). However, if the operator wants to remove the local storage ACS will throw an exception saying that the removal of local storage is not allowed.Therefore, if one wants to remove a local storage, he/she needs to do a manual intervention in the database and hosts.
This limitation was removed as it was only a logical restriction.

[CLOUDSTACK-10214] Unable to remove local primary storage

---

ui/scripts/accounts.js
ui/scripts/accountsWizard.js
ui/scripts/cloudStack.js
ui/scripts/installWizard.js
ui/scripts/sharedFunctions.js

We no longer hash password in the user side. All of the password processing is executed in the server side according to the priority of hashing mechanism defined by the administrator.
Mailing list discussion thread: https://lists.apache.org/thread.html/75f0d8910a70c1f81952a0db023d4111e1d3164eb00a159c51f7b719@%3Cdev.cloudstack.apache.org%3E
Locally.
Testing

Remove 'md5Hashed' variable from Javascript.

---

systemvm/debian/etc/apache2/conf-enabled/security.conf
systemvm/debian/opt/cloud/bin/setup/common.sh

This turns off apache2 server version signature/token in headers.
This is after the fix, apache version is not seen in http response/headers:
```
> curl -I http://192.168.1.50    
HTTP/1.1 403 Forbidden
Date: Wed, 11 Apr 2018 21:24:38 GMT
Server: Apache
Content-Type: text/html; charset=iso-8859-1
```
Testing

CLOUDSTACK-10304: turn off apache2 server tokens and signature in systemvms

---

api/src/com/cloud/agent/api/storage/OVFHelper.java

OVF files contained on OVA template files, with missing 'ovf:populatedSize' attribute fail the post download installation.
After template is downloaded, installation fails with error:
````
2018-04-12 13:36:47,959 INFO  [storage.template.OVAProcessor] (pool-1-thread-6:null) The ovf file /mnt/SecStorage/3544cb8f-d19d-3ebb-b8f2-bdc7ee4b7a4c/template/tmpl/2/206/3283498e6608-10f2-34c0-9ad4-808f
f593bea9.ovf is invalid
java.lang.NumberFormatException: For input string: ""
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.lang.Long.parseLong(Long.java:601)
at java.lang.Long.parseLong(Long.java:631)
at com.cloud.agent.api.storage.OVFHelper.getOVFVolumeInfo(OVFHelper.java:116)
at com.cloud.storage.template.OVAProcessor.process(OVAProcessor.java:105)
at …
```

[Vmware] Fix for OVF parsing error

---

systemvm/debian/opt/cloud/bin/cs/CsHelper.py

While debugging some problems in our VRs, we noticed that the result of commands (e.g. iptables) was not being logged. It is interesting to log these information (at least in debug level) to facilitate troubleshooting. 
This PR enables `CsHelper.execute` to log DEBUG level the result of commands being executed.
Locally
Testing

Log command output in CsHelper.execute command

---

api/src/main/java/com/cloud/network/vpc/NetworkACLService.java
api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
api/src/main/java/org/apache/cloudstack/api/command/user/network/MoveNetworkAclItemCmd.java
engine/schema/src/main/java/com/cloud/network/vpc/NetworkACLItemDao.java
engine/schema/src/main/java/com/cloud/network/vpc/dao/NetworkACLItemCidrsDaoImpl.java
engine/schema/src/main/java/com/cloud/network/vpc/dao/NetworkACLItemDaoImpl.java
engine/schema/src/main/resources/META-INF/db/schema-41110to41200.sql
server/src/main/java/com/cloud/network/vpc/NetworkACLServiceImpl.java
server/src/main/java/com/cloud/server/ManagementServerImpl.java
server/src/test/java/com/cloud/network/vpc/NetworkACLServiceImplTest.java
ui/scripts/vpc.js

An error is happening in certain conditions, such as when you have only 2 ACL rules and you move the last one to the top. There are other conditions, for instance, when moving ACLs that are in a sequence of numbers without gaps.
Example, rules:
number | rule
1 - rule A
2 - rule D
3 - rule B
4 - rule C
5 - rule E
It is not possible to move "rule C" in position 2, 1, and 3.
Locally in my development environment. I also wrote unit tests for all of the new methods created.
100% coverage on new code ;)

[CLOUDSTACK-10344] bug when moving ACL rules (change order with drag and drop)

---

agent/bindir/libvirtqemuhook.in

This allows logging to the default libvirt qemu hook and cleans up the script.
Installed the hook script on centos6 and xenial/16.04 based kvm hosts, changes the logging scope to `DEBUG`, performed VM migration, which caused the following logs:
```
16:57:25,61 qemu-hook DEBUG Executing qemu-hook with args: ['/etc/libvirt/hooks/qemu', 'i-2-39-VM', 'stopped', 'end', '-']
16:57:25,275 qemu-hook DEBUG Executing qemu-hook with args: ['/etc/libvirt/hooks/qemu', 'i-2-39-VM', 'release', 'end', '-']
16:57:34,685 qemu-hook DEBUG Executing qemu-hook with args: ['/etc/libvirt/hooks/qemu', 'i-2-39-VM', 'migrate', 'begin', '-']
16:57:34,904 qemu-hook DEBUG Executing qemu-hook with args: ['/etc/libvirt/hooks/qemu', 'i-2-39-VM', 'prepare', 'begin', '-']
16:57:36,880 qemu-hook DEBUG Executing qemu-hook …
```

agent: Add logging to libvirt qemu hook and cleanup

---

core/src/com/cloud/info/ConsoleProxyInfo.java
server/src/com/cloud/consoleproxy/ConsoleProxyManagerImpl.java

This allows CloudStack to use a console proxy domain instead of public
IP address even when ssl is not enabled but console proxy url/domain
is defined in global settings.
This allows use of domain url for console proxy endpoint, without needing to have
SSL certificates setup.
I was trying to setup a lab for testing CloudStack, this lab is in my home. To make it
publicly accessible, I've a DO machine to which one of my machines does autossh
and port forwards to it. The DO machine has apache2 running that reverse proxies
to only certain paths on the forwarded port. The DO endpoint is secured by letsencrypt
certs. With this change, a user/admin will be able to run console proxy via a URL/domain
but on http instead of https internally. Externally, such as my setup, one can secure
urls/paths …

consoleproxy: use consoleproxy.domain for non-ssl enable env

---

systemvm/debian/opt/cloud/bin/configure.py
systemvm/debian/opt/cloud/bin/cs/CsProcess.py
systemvm/debian/opt/cloud/bin/cs/CsRedundant.py
systemvm/debian/opt/cloud/bin/line_edit.py
systemvm/debian/opt/cloud/bin/update_config.py
systemvm/debian/opt/cloud/bin/vmdata.py
systemvm/test/TestCsAddress.py
systemvm/test/TestCsApp.py
systemvm/test/TestCsCmdLine.py
systemvm/test/TestCsConfig.py
systemvm/test/TestCsDatabag.py
systemvm/test/TestCsDhcp.py
systemvm/test/TestCsFile.py
systemvm/test/TestCsGuestNetwork.py
systemvm/test/TestCsHelper.py
systemvm/test/TestCsInterface.py
systemvm/test/TestCsNetfilter.py
systemvm/test/TestCsProcess.py
systemvm/test/TestCsRedundant.py
systemvm/test/TestCsRoute.py
systemvm/test/TestCsRule.py
systemvm/test/runtests.sh
tools/travis/before_install.sh

I noticed a failure in travis for PR #2574 relating to Python code check style. While investigating that error, I found out that when running `cloudstack/systemvm/test/runtests.sh` I was receiving the following errors:
```
[root@AcsBuildVm test]# ./runtests.sh
Running pep8 to check systemvm/python code for errors
../debian/opt/cloud/bin/configure.py:199:33: E126 continuation line over-indented for hanging indent
../debian/opt/cloud/bin/configure.py:207:37: E126 continuation line over-indented for hanging indent
../debian/opt/cloud/bin/configure.py:210:28: E121 continuation line indentation is not a multiple of four
../debian/opt/cloud/bin/configure.py:817:17: E121 continuation line indentation is not a multiple of four
../debian/opt/cloud/bin/configure.py:818:17: E121 continuation line …
```

Fix Python code checkstyle execute by "systemvm\test\runtests.sh"

---

systemvm/debian/opt/cloud/bin/setup/common.sh

While debugging the VR for  #2579, I noticed that one of the scripts were breaking. The variable `RROUTER` was not set and this broke a conditional.
Locally 
Testing

Use double quotes with 'RROUTER' variable in "common.sh" script

---

agent/src/main/java/com/cloud/agent/resource/consoleproxy/ConsoleProxyResource.java
engine/schema/src/main/java/com/cloud/vm/dao/UserVmDaoImpl.java
plugins/dedicated-resources/src/main/java/org/apache/cloudstack/dedicated/DedicatedResourceManagerImpl.java
plugins/hypervisors/baremetal/src/main/java/org/apache/cloudstack/api/DeleteBaremetalRctCmd.java
plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java
plugins/integrations/cloudian/src/main/java/org/apache/cloudstack/cloudian/client/CloudianClient.java
plugins/network-elements/netscaler/src/main/java/com/cloud/network/resource/NetScalerControlCenterResource.java
plugins/network-elements/nuage-vsp/src/main/java/com/cloud/network/resource/NuageVspResource.java
server/src/main/java/com/cloud/network/NetworkModelImpl.java
server/src/main/java/com/cloud/network/as/AutoScaleManagerImpl.java
vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/HostDatastoreBrowserMO.java
vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/VirtualMachineMO.java

There are some possible copy and paste errors in the log messages (The logging statement was copied from an old place to a new place, but the message wasn't changed to adapt to the function of new place).
Here's a list of this kind of problems I found, which contains the original place that the logging statement possibly be copied from, and the new place that the log be copied to (the log message is not suitable for the new place and should be changed):
https://issues.apache.org/jira/browse/CLOUDSTACK-10357
Testing

CLOUDSTACK-10357 Improve log messages that do not match with their method function

---

PULL_REQUEST_TEMPLATE.md

Remove the packaging job invocation from the PR description as when closing/merging a PR, an extra packaging job is executed.
Testing

Remove packaging job from pull request template

---

systemvm/debian/opt/cloud/bin/configure.py
systemvm/debian/opt/cloud/bin/cs/CsAddress.py
systemvm/debian/opt/cloud/bin/cs/CsRoute.py

This fixes python code that applies NAT/address rules. This fixes routing rules based on ip addresses received to ensure that marked packets will have a routing rule. Thereby, this fixes the issue of
public IP NAT access from other VMs in the VPC.
- Create a VPC and deployed two VMs in a single tier in 10.1.1.1/24, allow_all policy (egress/ingress)
- Added a public IP for the VPC enabled SNAT of that public IP to the VM1, similarly for VM2
- Before the fix, I was unable to SSH from VM1 to VM2's public SNAT IP
- After the fix ssh/ping/access via public IP works
Testing

router: fix routing table for marked packets

---

server/src/com/cloud/agent/manager/allocator/impl/FirstFitAllocator.java

When starting an existing VM and trying to prioritize hosts, if Guest OS mapping has been removed from that host, there will be a NullPointerException which prevents the VM to be started successfully.
Testing

Prevent NPE if guest OS mapping is missing while prioritizing hosts

---

engine/schema/resources/META-INF/db/schema-41000to41100.sql
engine/schema/resources/META-INF/db/schema-452to460.sql
engine/schema/resources/META-INF/db/schema-4930to41000.sql

This fixes a database error that occurs when upgrading from 4.5 to 4.11. A 'table already exists' SQL error is encountered during the upgrade.
If a table already exists in the database, it should only attempt to create a table if it does not exist.
The fix adds SQL syntax create a table only if not exists and also removes the drop table statements since there may be users that already have such a table with data in their database.
Expected behaviour: when upgrading from an older version of cloudstack, it should upgrade the database without producing any SQL errors. Specifically, the SQL upgrade scripts should not attempt to create a table if it already exists. It should also not attempt to drop existing tables unless it is in the cleanup scripts. 
Actual behaviour: a database error that …

cs-45to411-ugrade-fix: database errors during upgrade to 4.11

---

scripts/vm/network/security_group.py
test/integration/smoke/test_routers.py

On RHEL/CentOS/Fedora the bridge related sysctl rules are enabled
in kernel by default but can only be disabled. Enabling those keys
will fail, causing iptables/ebtables tables to not be created
and fails SG on CentOS. Therefore, SG does not work on CentOS.
This also fixes an integration test case, which assumes first few
tests complete within 3 minutes. In nested env the value may be large,
this increases the value to 20 minutes.
Testing

network: Fix security groups for CentOS

---

api/src/main/java/org/apache/cloudstack/api/command/admin/offering/CreateServiceOfferingCmd.java
server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java

The two methods are named "getXXX".
The two method are checking the status of variables.
"getCustomized" is not as intuitive as "isCustomized".
"getIsSystem" is not as intuitive as "isSystem" as well.

CLOUDSTACK-10359: Change the inconsistent method names.

---

api/src/main/java/com/cloud/exception/UnavailableCommandException.java
plugins/acl/dynamic-role-based/src/org/apache/cloudstack/acl/DynamicRoleBasedAPIAccessChecker.java
plugins/acl/static-role-based/src/org/apache/cloudstack/acl/StaticRoleBasedAPIAccessChecker.java
server/src/com/cloud/api/ApiServer.java
utils/src/main/java/com/cloud/utils/SerialVersionUID.java

CloudStack SSO (using `security.singlesignon.key`) does not work anymore with CloudStack 4.11, since commit 9988c26, which introduced a regression due to a refactoring: every API request that is not "validated" generates the same error (401 - Unauthorized) and invalidates the session.
However, CloudStack UI executes a call to `listConfigurations` [in method `bypassLoginCheck`](https://github.com/apache/cloudstack/blob/1c99fd73881938/ui/scripts/cloudStack.js#L172). A non-admin user does not have the permissions to execute this request, which causes an error 401:
```
{"listconfigurationsresponse":{"uuidList":[],"errorcode":401,"errortext":"unable to verify user credentials and/or request signature"}}
```
The session (already created by SSO) is then invalidated and the user cannot access to …

CLOUDSTACK-10327: Do not invalidate the session when API command not found

---

api/src/main/java/org/apache/cloudstack/api/command/admin/user/UpdateUserCmd.java

`usersecretkey` says it should be used with `usersecretkey` when it meant to be `userapikey`
http://cloudstack.apache.org/api/apidocs-4.11/apis/updateUser.html
Testing

UpdateUserCmd: apiSecretKey refers to itself

---

ui/scripts/network.js

fix typo c&p bug in externalId feature UI

---

server/src/main/java/com/cloud/api/response/ApiResponseSerializer.java
test/integration/smoke/test_hostha_simulator.py

It changes the JSON output from: 
```json
{"success": "true"}
```
to 
```json
{"success": true}
```

CLOUDSTACK-10253: JSON response for SuccessResponse as boolean instead of string

---

framework/config/src/main/java/org/apache/cloudstack/framework/config/ConfigKey.java
framework/config/src/main/java/org/apache/cloudstack/framework/config/impl/ConfigDepotImpl.java

The method is named as "scoped" that seems to whether the variable config is scoped in _scopedStorages or not.
Actually, the method tries to find a storage of which scope equals to the scope of config.
So that, the method name "findStorage" should be more clear than "scoped".

CLOUDSTACK-10360: Change the method name.

---

framework/jobs/src/main/java/org/apache/cloudstack/framework/jobs/impl/AsyncJobManagerImpl.java
plugins/network-elements/ovs/src/main/java/com/cloud/network/ovs/OvsTunnelManagerImpl.java
plugins/network-elements/ovs/src/main/java/com/cloud/network/ovs/dao/OvsTunnelNetworkDao.java
plugins/network-elements/ovs/src/main/java/com/cloud/network/ovs/dao/OvsTunnelNetworkDaoImpl.java
services/secondary-storage/controller/src/main/java/org/apache/cloudstack/secondarystorage/PremiumSecondaryStorageManagerImpl.java

…findXXX".
These three methods are not direct getter or list.
They try to find the target objects with the related arguments.
So that, renaming them as "findXXX" should be more intuitive.

CLOUDSTACK-10363: Change method names.

---

api/src/main/java/org/apache/cloudstack/acl/RoleService.java
api/src/main/java/org/apache/cloudstack/api/command/admin/acl/ListRolesCmd.java
server/src/main/java/org/apache/cloudstack/acl/RoleManagerImpl.java
server/src/test/java/org/apache/cloudstack/acl/RoleManagerImplTest.java

Domain admins should not be able to assign the role of root admin to new users. Therefore, the role ‘root admin’ (or any other of the same type) should not be visible to domain admin accounts.
I created unit test that cover all of the modified code. Moreover, I tested locally.
Testing

When creating a new account (via domain admin) it is possible to select “root admin” as the role for the new user

---

api/src/main/java/org/apache/cloudstack/api/response/UserVmResponse.java
server/src/main/java/com/cloud/api/query/dao/UserVmJoinDaoImpl.java

I think it's the last entity represented as a `Long` in the API which hasn't been yet moved to an `UUID`. It will be painful for API tools to move from int to String but changing the attribute name looks weird too. Let's do this last change of attribute type and we should be able to close the story of ID -> UUID for good.
Fixes #2528
Testing

API: move ostypeid from DB id to DB uuid

---

engine/schema/src/com/cloud/upgrade/dao/Upgrade41000to41100.java
engine/schema/src/com/cloud/upgrade/dao/Upgrade41100to41110.java
plugins/ca/root-ca/src/org/apache/cloudstack/ca/provider/RootCAProvider.java
plugins/storage/volume/solidfire/src/org/apache/cloudstack/storage/datastore/provider/SolidFireHostListener.java
plugins/user-authenticators/saml2/src/org/apache/cloudstack/saml/SAML2AuthManagerImpl.java
plugins/user-authenticators/saml2/src/org/apache/cloudstack/saml/SAMLUtils.java
plugins/user-authenticators/saml2/test/org/apache/cloudstack/SAMLUtilsTest.java
scripts/util/keystore-setup
systemvm/debian/opt/cloud/bin/configure.py
systemvm/debian/opt/cloud/bin/setup/cloud-early-config
systemvm/debian/opt/cloud/bin/setup/patchsystemvm.sh
test/integration/smoke/test_service_offerings.py
test/integration/smoke/test_vm_life_cycle.py
tools/appliance/systemvmtemplate/scripts/configure_systemvm_services.sh
tools/appliance/systemvmtemplate/scripts/install_systemvm_packages.sh
ui/index.html
utils/src/main/java/org/apache/cloudstack/utils/security/CertUtils.java

This includes several (smoke) test, stabilization fixes and blocker fixes towards 4.11.1.0 milestone. Please review individually melded commits.
This should be merged when we've near 100% smoke test pass.
Fixed issues list:
#2530 (kvm blocker)
#2561 (xenserver blocker)
#2548 (saml2 blocker)
#2541 
SystemVM templates used: https://lab.yadav.cloud/systemvmtemplates/4.11/
Testing

4.11.1.0: Stabilization and blocker/issues fixes

---

ui/scripts/autoscaler.js
ui/scripts/configuration.js
ui/scripts/sharedFunctions.js
ui/scripts/storage.js

After using the feature introduced by #2486 in production, we felt the need for an improvement in the UI.  It is interesting to filter the displayed disk offerings according to the type of storage selected (local/shared) to migrate the volume to.
Locally
Testing

[migrateVolume API method] Filter disk offerings based on target storage pool selected

---

engine/schema/src/com/cloud/upgrade/DatabaseUpgradeChecker.java

When CloudStack 4.9.3.1 was releases, the upgrade path from this version to 4.11 was not created.  This PR is introducing the aforementioned upgrade path.
Testing

Create upgrade path from 4.9.3.1 to 4.11.1.0

---

plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/storage/LibvirtStorageAdaptor.java

fix issue where kvm / ceph cannot create volumes #2611
This hard codes the disk format to RAW in the case of RBD
Fixes: #2611
This was tested in a centos 7 based lab on kvm with ceph primary storage.  
Testing

fixes #2611

---

debian/control
plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/LibvirtDomainXMLParser.java
plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java
plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtStopCommandWrapper.java
ui/scripts/system.js

This adds and allows Ubuntu 18.04 to be used as KVM host. In addition,
on the UI when hypervisor version key is missing, this adds and display
the host os and version detail which is useful to show the KVM host
os and version.
I've tested and blogged about using 18.04 here: http://rohityadav.cloud/blog/cloudstack-kvm/
Testing

bionic: allow Ubuntu 18.04 to be added as KVM host

---

server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
server/src/test/java/com/cloud/storage/VolumeApiServiceImplTest.java

Currently, users are not able to change the disk offering of VMs' root volumes. It might be interesting to allow such changes, so users would be able to move a VM initially deployed in shared storage to local storage and vice versa. It is also interesting to enable changing the quality of service offered to root disks.
We are allowing only administrators to execute the change of root volumes disk offerings during volume migration between storage. Therefore, we perform all at once, the migration of storage and the disk offering to reflect the new place.
This is a continuation of work #2486. After using that feature for a while we felt the need to change the disk offering of VM's root volume.
Compute offerings (system VM service offerings as well) are “linked”/bound to a disk offering. …

Allow changing disk offering of VMs' root volume during volume migration

---

api/src/org/apache/cloudstack/api/response/GuestOSResponse.java
server/src/com/cloud/api/ApiResponseHelper.java

This returns the boolean value of the `isuserdefined` key than
converting it to string. Fixes #2529.
Testing

listostypes: Fixes #2529 return boolean than string in response

---

engine/orchestration/src/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
engine/orchestration/test/org/apache/cloudstack/engine/orchestration/NetworkOrchestratorTest.java
server/src/com/cloud/network/NetworkModelImpl.java
server/src/com/cloud/network/guru/GuestNetworkGuru.java
ui/scripts/configuration.js
ui/scripts/docs.js

This provides the ability to create L2 network providing ConfigDrive service.
- Create an L2 network offering using 'User Data' checkbox
- Enable network offering
- Create L2 network from the network offering
- Deploy VM on network, verify ConfigDrive can be used
Testing

config-drive: support user data on L2 networks

---

packaging/package.sh

This PR is going to:
- fail the build early if `--use-timestamp` is provided and working directory is *not* clean.
- catch any potential error and fail the build (fix the regression added in 1708838518 (#2433))
Testing

Catch error in packagin script and fail the build

---

api/src/main/java/org/apache/cloudstack/api/command/admin/offering/CreateServiceOfferingCmd.java
api/src/main/java/org/apache/cloudstack/api/command/admin/vlan/ListVlanIpRangesCmd.java
api/src/main/java/org/apache/cloudstack/api/command/admin/vpc/UpdateVPCCmdByAdmin.java
api/src/main/java/org/apache/cloudstack/api/command/user/address/ListPublicIpAddressesCmd.java
api/src/main/java/org/apache/cloudstack/api/command/user/network/ListNetworksCmd.java
api/src/main/java/org/apache/cloudstack/api/command/user/vm/DeployVMCmd.java
api/src/main/java/org/apache/cloudstack/api/command/user/vpc/UpdateVPCCmd.java
api/src/main/java/org/apache/cloudstack/api/response/HostResponse.java
api/src/main/java/org/apache/cloudstack/api/response/ServiceOfferingResponse.java
api/src/main/java/org/apache/cloudstack/api/response/SnapshotPolicyResponse.java
api/src/main/java/org/apache/cloudstack/api/response/VolumeResponse.java
plugins/database/quota/src/main/java/org/apache/cloudstack/api/command/QuotaSummaryCmd.java
plugins/storage/volume/nexenta/src/main/java/org/apache/cloudstack/storage/datastore/lifecylce/NexentaPrimaryDataStoreLifeCycle.java
plugins/storage/volume/nexenta/src/main/java/org/apache/cloudstack/storage/datastore/util/NexentaStorAppliance.java
plugins/storage/volume/nexenta/src/main/java/org/apache/cloudstack/storage/datastore/util/NexentaUtil.java
plugins/storage/volume/nexenta/src/test/java/org/apache/cloudstack/storage/datastore/util/NexentaUtilTest.java
server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
server/src/main/java/com/cloud/network/NetworkServiceImpl.java
server/src/main/java/com/cloud/server/ManagementServerImpl.java
server/src/main/java/com/cloud/storage/TemplateProfile.java
server/src/main/java/com/cloud/template/TemplateAdapterBase.java
server/src/main/java/com/cloud/vm/UserVmManagerImpl.java

These Boolean-return methods are named "getXXX",
but other Boolean-return methods are named "isXXX", such as the following two methods.
They will return boolean values, rename them as "isXXX" should be more clear than "getXXX".
api/src/main/java/org/apache/cloudstack/api/command/admin/vlan/ListVlanIpRangesCmd.java
```
public Boolean getForVirtualNetwork() {
return forVirtualNetwork;
}
```
api/src/main/java/org/apache/cloudstack/api/command/user/address/ListPublicIpAddressesCmd.java
```
public Boolean isForVirtualNetwork() {
return forVirtualNetwork;
}
```

CLOUDSTACK-10362: Change the "getXXX" method names to "isXXX".

---

api/src/com/cloud/network/Network.java
api/src/com/cloud/network/NetworkProfile.java
api/src/com/cloud/network/NetworkService.java
api/src/com/cloud/network/router/VirtualRouter.java
api/src/com/cloud/network/vpc/Vpc.java
api/src/org/apache/cloudstack/api/ApiConstants.java
api/src/org/apache/cloudstack/api/command/user/network/RestartNetworkCmd.java
api/src/org/apache/cloudstack/api/command/user/vpc/RestartVPCCmd.java
api/src/org/apache/cloudstack/api/response/NetworkResponse.java
engine/api/src/org/apache/cloudstack/engine/orchestration/service/NetworkOrchestrationService.java
engine/orchestration/src/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
engine/schema/src/com/cloud/network/dao/NetworkDaoImpl.java
engine/schema/src/com/cloud/network/dao/NetworkVO.java
engine/schema/src/com/cloud/network/vpc/VpcVO.java
engine/schema/src/com/cloud/vm/DomainRouterVO.java
server/src/com/cloud/api/ApiResponseHelper.java
server/src/com/cloud/api/query/dao/DomainRouterJoinDaoImpl.java
server/src/com/cloud/network/NetworkServiceImpl.java
server/src/com/cloud/network/element/VirtualRouterElement.java
server/src/com/cloud/network/vpc/VpcManagerImpl.java
server/src/org/cloud/network/router/deployment/RouterDeploymentDefinition.java
server/src/org/cloud/network/router/deployment/VpcRouterDeploymentDefinition.java
server/test/com/cloud/vpc/MockNetworkManagerImpl.java
systemvm/debian/opt/cloud/bin/cs/CsAddress.py
systemvm/debian/opt/cloud/bin/setup/common.sh
systemvm/debian/opt/cloud/bin/setup/postinit.sh
systemvm/debian/opt/cloud/templates/keepalived.conf.templ
ui/scripts/network.js

Every time there is a major CloudStack version that requires a new systemvmtemplate, admins need to restart VRs which can take few (sometimes several) minutes. The aim is to make it easier to perform a rolling restart (or blue-green deployment) of the network with acceptable downtime. In this strategy, a new VR is provisioned before the old VR is destroyed/cleaned for non-redundant isolated VRs. For redundant networks, a rolling replacement of routers is performed.
The network downtime is usually the short-time (less than 10s) after the new VR starts (nics are up) and old VR is destroyed. The downtime may be affected by several factors as the new VR has a different mac address, stale ARP cache may take upto 30seconds (default `gc_timeout` on Linux) to renew in guests making egress traffic …

CLOUDSTACK-9114: Reduce VR downtime during network restart

---

engine/schema/resources/META-INF/db/schema-41100to41110-cleanup.sql
plugins/hypervisors/vmware/src/com/cloud/hypervisor/vmware/manager/VmwareManagerImpl.java
server/src/com/cloud/configuration/Config.java
vmware-base/src/com/cloud/hypervisor/vmware/mo/HypervisorHostHelper.java

This deprecates the vmware.ports.per.dvportgroup global setting.
The vSphere Auto Expand feature (introduced in vSphere 5.0) will take
care of dynamically increasing/decreasing the dvPorts when running out
of distributed ports . But in case of vSphere 4.1/4.0 (If used), as this
feature is not there, the new default value (=> 8) have an impact in the
existing deployments. Action item for vSphere 4.1/4.0: Admin should
modify the global configuration setting "vmware.ports.per.dvportgroup"
from 8 to any number based on their environment because the proposal
default value of 8 would be very less without auto expand feature in
general. The current default value of 256 may not need immediate
modification after deployment, but 8 would be very less which means
admin need to update immediately …

CLOUDSTACK-9184: Fixes #2631 VMware dvs portgroup autogrowth

---

systemvm/debian/opt/cloud/bin/cs/CsRedundant.py

This fixes #2544, ensure that password reset script works in redudant networks.
This ensures that password server runs on the dhcpserver identifier
IP which is the not the VRRP virtual (10.1.1.1) IP by default but
the actual ip of the interface. When dhcp client discovery is made,
the `dhcp-server-identifier` contains the non VIP address that is
used by password reset script to query guest VM password.
Deployed a guest VM in redundant VR network, with a password enable template (macchinina). Verified on master VRs (and also on switching) that password server runs on the guest nic IP than the VIP and the password script is able to consume the nonVIP address from `dhcp-server-identifier`.
Testing

router: Fixes #2544 run passwd server on dhcpserver IP on rVR

---

packaging/centos7/cloud.spec

As part of working on another PR I noticed running maven tests are skipped while packaging CentOS7. This is to make sure running tests on packaging is consistence everywhere (they are already running on debian and centos63)
This is essentially important because one specific test is failing but centos7 packaging job wasn't able to see that. 
Testing

Don't skip tests while packaging Centos7

---

api/src/com/cloud/network/NetworkModel.java
engine/orchestration/src/com/cloud/vm/VirtualMachineManagerImpl.java
server/src/com/cloud/network/NetworkModelImpl.java
server/src/com/cloud/network/element/ConfigDriveNetworkElement.java
server/src/com/cloud/vm/UserVmManagerImpl.java
server/test/com/cloud/network/MockNetworkModelImpl.java
server/test/com/cloud/network/element/ConfigDriveNetworkElementTest.java
server/test/com/cloud/vpc/MockNetworkModelImpl.java

This fixes config drive to use VM's user provided host-name instead of
the internal VM instance ID for hostname related config in both
cloudstack and openstack metadata bundled in the ISO.
I created a L2 network and deployed a VM, and checked contents in the mounted iso:
The openstack metadata folder:
The cloudstack metadata folder:
As confirmed via the unit test and above, the internal `i-x-y` is not longer seen in the iso metadata.
Testing

config-drive: use hostname of VM instance of internal VM id

---

agent/src/com/cloud/agent/Agent.java

When agent loses connection with management server, the reconnection
logic waits for any pending tasks to finish. However, when such tasks
do finish they fail to send an `Answer` back to managements server.
Therefore from a management server's perspective such pending
operations are stuck in a FSM state and need manual removal or fixing.
This is by design where management server's side cmd-answer request
pattern is code/execution dependent, therefore even if the answer
were to be sent when management server came back up (reconnects)
the management server will fail to acknowledge and process the answer
due to missing listeners or being in the exact state to handle answers.
Historically, the Agent would wait to reconnect until the internal
tasks complete but I found no reason why it should …

agent: Fixes #2633 don't wait for pending tasks on reconnection

---

api/src/com/cloud/deploy/DataCenterDeployment.java
api/src/com/cloud/deploy/DeploymentPlan.java
client/pom.xml
core/resources/META-INF/cloudstack/core/spring-core-registry-core-context.xml
plugins/affinity-group-processors/host-affinity/pom.xml
plugins/affinity-group-processors/host-affinity/resources/META-INF/cloudstack/host-affinity/module.properties
plugins/affinity-group-processors/host-affinity/resources/META-INF/cloudstack/host-affinity/spring-host-affinity-context.xml
plugins/affinity-group-processors/host-affinity/src/org/apache/cloudstack/affinity/HostAffinityProcessor.java
plugins/affinity-group-processors/host-affinity/test/org/apache/cloudstack/affinity/HostAffinityProcessorTest.java
plugins/pom.xml
server/src/com/cloud/deploy/DeploymentPlanningManagerImpl.java
server/test/com/cloud/vm/DeploymentPlanningManagerImplTest.java
test/integration/smoke/test_affinity_groups.py

Introduce a new affinity group type: Host affinity.
VMs belonging to a host affinity group are on the same host, and new deployments using the affinity group are expected on the same host.
There is room for improvement by adding scope level which should be: host, cluster or pod
- 2 KVM hosts
- Create new host affinity group
- Deploy VM selecting the created affinity group
- Deploy another VMs selecting the same affinity group.
- Created VMs are all on the same host
Testing

Host Affinity plugin

---

engine/orchestration/src/com/cloud/vm/VirtualMachineManagerImpl.java

When a user shuts down their VM from the guest OS (and VM HA is enabled), the VM just powers itself back on.  Our environment is on KVM hosts.
CloudStack does not know the difference between a VM failing or being shutdown from within the guest OS.
This is a major pain point for all our users - especially since they don't pay for VMs when they are shutoff.  It is not intuitive for end-users to understand why they can't shutdown VMs from within the guest OS.  Especially when they all come from (non-cloudstack) VMware and Hyper-V environments where this is not an issue.
However, if a host fails, we need VM HA to still work.
This PR that creates a configuration option "ha.vm.restart.hostup".  With this option set to false, if CloudStack sees a VM shutdown out-of-band, but the host it was on …

CLOUDSTACK-10309 Add option on if to VM HA power-on a OOB-shut-off-VM

---

api/src/com/cloud/network/element/UserDataServiceProvider.java
client/pom.xml
core/src/com/cloud/agent/api/HandleConfigDriveIsoCommand.java
engine/api/src/com/cloud/vm/VirtualMachineManager.java
engine/orchestration/src/com/cloud/vm/VirtualMachineManagerImpl.java
engine/pom.xml
engine/storage/configdrive/pom.xml
engine/storage/configdrive/src/org/apache/cloudstack/storage/configdrive/ConfigDrive.java
engine/storage/configdrive/src/org/apache/cloudstack/storage/configdrive/ConfigDriveBuilder.java
engine/storage/configdrive/test/org/apache/cloudstack/storage/configdrive/ConfigDriveBuilderTest.java
packaging/centos63/cloud.spec
packaging/centos7/cloud.spec
plugins/hypervisors/kvm/pom.xml
plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtHandleConfigDriveCommandWrapper.java
plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/storage/KVMStoragePoolManager.java
server/pom.xml
server/src/com/cloud/network/element/ConfigDriveNetworkElement.java
server/src/com/cloud/vm/UserVmManagerImpl.java
server/test/com/cloud/network/element/ConfigDriveNetworkElementTest.java
services/secondary-storage/server/pom.xml
services/secondary-storage/server/src/org/apache/cloudstack/storage/resource/NfsSecondaryStorageResource.java

This introduces a new global setting `vm.configdrive.primarypool.enabled` to toggle creation/hosting of config drive iso files on primary storage, the default will be `false` causing them to be hosted on secondary storage. The support is limited from hypervisor resource side and in current implementation limited to KVM. The next big change is that config drive is created at a temporary location by management server and shipped to either KVM or SSVM agent via cmd-answer pattern, the data of which is not logged in logs. This saves us from adding `genisoimage` dependency on cloudstack-agent pkg.
The APIs to reset ssh public key, password and user-data (via update VM API) requires that VM should be shutdown. Therefore, in the refactoring I removed the case of updation of existing ISO. If …

CLOUDSTACK-10290: Introduce option to have config drives on primary storage

---

server/src/com/cloud/vm/UserVmManagerImpl.java
server/test/com/cloud/vm/UserVmManagerImplTest.java

Look for the next available MAC address if the given MAC address in command addNicToVirtualMachine is invalid (null, empty, blank)
This PR addresses discussion raised on issue [#2540]( https://github.com/apache/cloudstack/issues/2540) 
> Issue 2540: problem adding new shared network NIC to VM "A NIC with this MAC address exits for network:"
Testing

Generate MAC address if the MAC in command addNicToVirtualMachine is invalid

---

api/src/org/apache/cloudstack/api/command/admin/volume/ListVolumesCmdByAdmin.java
api/src/org/apache/cloudstack/api/command/user/volume/ListVolumesCmd.java
server/src/com/cloud/api/query/QueryManagerImpl.java

When configuring a pre-setup primary storage we can enter the name-label of the storage that is going to be used by ACS and is already set up in the host. The problem is that we can use any String of characters there, and this String does not need to be a UUID. When listing volumes from a primary storage that has such conditions, the list will return all of the volumes in the cloud because the “API framework” will ignore that value as it is not a UUID type.
Locally
Testing

[CLOUDSTACK-10276] listVolumes not working when storage UUID is not a UUID

---

test/integration/component/test_configdrive.py
test/integration/plugins/nuagevsp/test_nuage_configdrive.py

Some fixes to the marvin tests were still ongoing, when PR #2566 was merged.
Ran regression on Nuage setup.
Testing

Fix test_configdrive.py and test_nuage_configdrive

---

engine/storage/configdrive/src/org/apache/cloudstack/storage/configdrive/ConfigDrive.java
engine/storage/configdrive/src/org/apache/cloudstack/storage/configdrive/ConfigDriveBuilder.java
engine/storage/configdrive/test/org/apache/cloudstack/storage/configdrive/ConfigDriveBuilderTest.java
engine/storage/configdrive/test/org/apache/cloudstack/storage/configdrive/ConfigDriveTest.java
server/test/com/cloud/network/element/ConfigDriveNetworkElementTest.java
services/console-proxy-rdp/rdpconsole/src/test/java/rdpclient/MockServerTest.java
services/secondary-storage/server/src/org/apache/cloudstack/storage/resource/NfsSecondaryStorageResource.java

@rhtyd, @DaanHoogland, @wido, and @mike-tutkowski here is the unit tests to remove the dependency of "genisoimage" when building ACS in other operating systems (running maven).
This solves #2671 
Also solves #2665
Fixes #2677
Testing

Create unit test cases for 'ConfigDriveBuilder' class

---

api/src/com/cloud/vm/VirtualMachineProfile.java
engine/components-api/src/com/cloud/vm/VirtualMachineProfileImpl.java
plugins/network-elements/nuage-vsp/src/com/cloud/network/element/NuageVspElement.java
plugins/network-elements/nuage-vsp/src/com/cloud/network/guru/NuageVspGuestNetworkGuru.java
plugins/network-elements/nuage-vsp/test/com/cloud/network/guru/NuageVspGuestNetworkGuruTest.java
server/src/com/cloud/network/element/VirtualRouterElement.java
server/src/com/cloud/network/element/VpcVirtualRouterElement.java
test/integration/plugins/nuagevsp/test_nuage_vpc_network.py
test/integration/plugins/nuagevsp/test_nuage_vsp.py

Changes in PR #2508 have caused network restart to fail in a Nuage setup,
as the new VR takes the same IP as the old one, and the old VR is still running.
Nuage doesn't support multiple VM's having the same IP.
We delay provisioning the interfaces in VSD until the old VR interface is released.
Testing

CLOUDSTACK-10377: Fix Network restart for Nuage

---

setup/bindir/cloud-get-vm-data-configdrive.in

Fix file locations and lookup.
Cleanup of code - requires bash v4.
Testing

CLOUDSTACK-10382: Fix cloud-get-vm-data-configdrive.in

---

engine/storage/configdrive/src/org/apache/cloudstack/storage/configdrive/ConfigDriveBuilder.java
ui/scripts/configuration.js

Prevent creation of L2 network offerings with conserve mode = false. As conserve mode is irrelevant for L2 networks as there are no resources to conserve, we do not send the Conserve mode parameter to network offering creation, as it will be True by default. Conserve mode = false caused that L2 network offerings in a zone were not listed, as described in the issue below.
This fixes the issue #2690 
No Conserve mode checkbox when L2 is selected:
List zone L2 network offerings:
Create an L2 network offering (check that Conserve mode checkbox is not visible). Check that conserve mode is true for the created offering
Testing

Do not send conserve mode param on L2 network offering creation from the UI

---

plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/storage/LibvirtStorageAdaptor.java

I fixed createNetfsStoragePool() function in LibvirtStorageAdaptor.java.
The current implementation of createNetfsStoragePool() does not unmount already mounted pool in non-English environment so I edited it to check the pool is already mounted using mountpoint command and unmount the pool if already mounted.
I got the following output in agent.log in a KVM hypervisor host:
```
2018-06-06 19:51:26,059 INFO  [kvm.storage.LibvirtStorageAdaptor] (agentRequest-Handler-5:null) (logid:293e0c5c) Attempting to unmount old mount at /mnt/00ec8deb-14b2-3264-bd61-4bf38f4bccc5
2018-06-06 19:51:26,090 INFO  [kvm.storage.LibvirtStorageAdaptor] (agentRequest-Handler-5:null) (logid:293e0c5c) Succeeded in unmounting /mnt/00ec8deb-14b2-3264-bd61-4bf38f4bccc5
```
This output indicates already-mounted …

Fix LibvirtStorageAdaptor.java

---

server/src/com/cloud/network/guru/DirectNetworkGuru.java

Not possible to deploy an Advanced zone with Security Groups, and VXLAN isolation method on KVM.
Exception: "Unable to convert network offering with specified id to network profile" is logged.
Tested on KVM. Deploy an Advanced zone, enabling Security Groups, VXLAN isolation for Guest traffic
Testing
Fixes: #2701

Fix to enable Advanced zones with Security groups and VXLAN isolation type

---

ui/scripts/network.js

This fixes a case where at least the create VPC dialog/form is shown.
Fixes https://github.com/apache/cloudstack/issues/2698
Before the fix, the create VPC form does not show up. After the fix, the following is seen:
Note: SG + Adv zone does not allow VPC (at least from what I saw/found today).
Deployed a KVM+SG zone and tried the fix with clicking on create VPC button. This shows up the form.
Testing

ui: fix create VPC dialog box failure when zone is SG enabled

---

packaging/centos63/cloud.spec
packaging/centos7/cloud.spec
tools/appliance/systemvmtemplate/scripts/install_systemvm_packages.sh

This forces the rpm cloudstack-common package to install libuuid x86_64 pkg instead of the i686 package.
Testing

packaging: use libuuid x86_64 package for cloudstack-common

---

systemvm/debian/opt/cloud/bin/configure.py
systemvm/debian/opt/cloud/bin/cs/CsAddress.py

Using Source NAT option on Private Gateway does not work
This fixes #2680 
When you use the Source NAT feature of Private Gateways on a VPC.  This should Source NAT all traffic from CloudStack VMs going towards IPs reachable through Private Gateways.
This change in this PR, stops adding the Source CIDR to SNAT rules.  This should be discussed/reviewed, but i can see no reason why the Source CIDR is needed.  There can only be one SNAT IP per interface, except for Static (one-to-one) NATs, which still work with this change in place.  The outbound interface is what matters in the rule.
There is a bug in the Private Gateway functionality, when Source NAT is enabled for the Private Gateway.  When the SNAT is added to iptables, it has the source CIDR of the private gateway subnet.  Since no VMs …

Source NAT option on Private Gateway

---

engine/storage/configdrive/src/org/apache/cloudstack/storage/configdrive/ConfigDrive.java
engine/storage/configdrive/src/org/apache/cloudstack/storage/configdrive/ConfigDriveBuilder.java
engine/storage/configdrive/test/org/apache/cloudstack/storage/configdrive/ConfigDriveTest.java
plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtHandleConfigDriveCommandWrapper.java
server/src/com/cloud/network/element/ConfigDriveNetworkElement.java
services/secondary-storage/server/src/org/apache/cloudstack/storage/resource/NfsSecondaryStorageResource.java

In the current implementation, for any config drive on a VM it creates a mount point specific to the parent directory `i-x-y-VM` on a host. This means, for each config drive enabled VM there will be a separate mount point per VM per host. The legacy code that points ISOs mounts based on the isopath's parent directory, to workaround this the config drive layout has been changed to: `<sr or mount point>/configdrive/i-x-y-VM.iso`.
This ensures that fewer mount points are made on hosts for either primary storagepools or secondary storagepools.
Created a L2 config drive enabled network, then deployed a VM to see config drive created and attached and then stopped VM to see config drive iso removed. Also confirmed that only one mount point is made specific to the configdrive directory. Performed …

configdrive: make fewer mountpoints on hosts

---

engine/schema/src/com/cloud/vm/dao/VMInstanceDao.java
engine/schema/src/com/cloud/vm/dao/VMInstanceDaoImpl.java
server/src/com/cloud/resource/ResourceManagerImpl.java
server/src/com/cloud/servlet/ConsoleProxyServlet.java
server/test/com/cloud/resource/ResourceManagerImplTest.java

JIRA Ticket: https://issues.apache.org/jira/browse/CLOUDSTACK-10326
This issue was discovered, fixed and tested on KVM, but applies for every hypervisor.
When enabling maintenance mode in a host, host state is put into 'PrepareForMaintenance' and running VMs are migrated into another host. After every VM is migrated, host goes to 'Maintenance' state.
Checks are performed on `ResourceManagerImpl.checkAndMaintan()` method:
- List VMs with host_id = HOST_ID
- List VMs with last_host_id = HOST_ID and state=Migrating
When both queries are empty, then the host can be put into Maintenance.
When a VM is being migrated to DEST_HOST, its host_id column is set to DEST_HOST, last_host_id = ORIGIN_HOST and state = Migrating. If then migration fails, host_id = last_host_id = ORIGIN_HOST 
This sequence: …

CLOUDSTACK-10326: Prevent hosts fall into Maintenance when there are running VMs on it

---

test/integration/smoke/test_vm_life_cycle.py

This fixes intermittently failing secure live VM migration tests on KVM.
After fixing smoketest, ran the tests several times against two KVM CentOS7 monkeyboxes against which they passed.
```
Test secure VM migration ... === TestName: test_01_secure_vm_migration | Status : SUCCESS ===
ok
Test Non-secured VM Migration ... === TestName: test_02_unsecure_vm_migration | Status : SUCCESS ===
ok
Test destroy Virtual Machine ... === TestName: test_03_secured_to_nonsecured_vm_migration | Status : SUCCESS ===
ok
Test Non-secured VM Migration ... === TestName: test_04_nonsecured_to_secured_vm_migration | Status : SUCCESS ===
ok
Ran 4 tests in 579.830s
OK
```
Testing

smoketest: Fix test_vm_life_cycle secure migration tests

---

core/src/com/cloud/resource/RequestWrapper.java
plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtRequestWrapper.java
plugins/hypervisors/kvm/test/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java

A pokemon catch was handling all errors in the agent with libvirt resource loaded. 
Testing

send unsupported answer only when applicable

---

server/src/com/cloud/network/router/NicProfileHelperImpl.java
test/integration/smoke/test_privategw_acl.py
test/integration/smoke/test_vpc_redundant.py
test/integration/smoke/test_vpc_router_nics.py

As rolling restart does not deallocate an IP before configuring it on a new VR,
the code must allow it to be reused on a non-redundant VPCs gateway nic.
removed the condition to only look for reuse of IP on redundant VPCs
Testing

reuse ip for non redundant VPC

---

engine/schema/src/main/java/com/cloud/storage/dao/SnapshotDao.java
engine/schema/src/main/java/com/cloud/storage/dao/SnapshotDaoImpl.java

removed unused code in snapshotDao

---

packaging/build-deb.sh

This PR is going to:
- fail the build early if `--use-timestamp` is provided and working directory is not clean.
- catch any potential error and fail the build (fix the regression added in 1708838 (#2433))
Testing

Catch error in Debian packaging script and fail the build

---

.travis.yml
api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
api/src/main/java/org/apache/cloudstack/api/command/admin/diagnostics/RunDiagnosticsCmd.java
api/src/main/java/org/apache/cloudstack/api/response/RunDiagnosticsResponse.java
api/src/main/java/org/apache/cloudstack/diagnostics/DiagnosticsService.java
api/src/main/java/org/apache/cloudstack/diagnostics/DiagnosticsType.java
core/src/main/java/com/cloud/agent/resource/virtualnetwork/VRScripts.java
core/src/main/java/com/cloud/agent/resource/virtualnetwork/VirtualRoutingResource.java
core/src/main/java/org/apache/cloudstack/diagnostics/DiagnosticsAnswer.java
core/src/main/java/org/apache/cloudstack/diagnostics/DiagnosticsCommand.java
plugins/hypervisors/simulator/src/main/java/com/cloud/agent/manager/MockAgentManager.java
plugins/hypervisors/simulator/src/main/java/com/cloud/agent/manager/MockAgentManagerImpl.java
plugins/hypervisors/simulator/src/main/java/com/cloud/agent/manager/SimulatorManagerImpl.java
server/src/main/java/org/apache/cloudstack/diagnostics/DiagnosticsServiceImpl.java
server/src/main/resources/META-INF/cloudstack/core/spring-server-core-managers-context.xml
server/src/test/java/org/apache/cloudstack/diagnostics/DiagnosticsServiceImplTest.java
systemvm/debian/opt/cloud/bin/diagnostics.py
test/integration/smoke/test_diagnostics.py
tools/apidoc/gen_toc.py

This feature introduces a new API command that will improve troubleshooting of network issues on CloudStack hosted networks by executing network-utility commands (ping, traceroute, arping) remotely on system VMs. 
For troubleshooting purposes, CloudStack administrators may wish to execute network utility commands remotely on system VMs, or request system VMs to ping/traceroute/arping to specific addresses over specific interfaces. An API command to provide such functionalities is being developed without altering any existing APIs. The targeted system VMs for this feature are the Virtual Router (VR), Secondary Storage VM (SSVM) and the Console Proxy VM (CPVM).
FS: https://cwiki.apache.org/confluence/display/CLOUDSTACK/CloudStack+Remote+Diagnostics+API
ML discussion: …

api: Introducing a new diagnostics API command for system VMs for CloudStack admins

---

engine/storage/datamotion/src/main/java/org/apache/cloudstack/storage/motion/StorageSystemDataMotionStrategy.java
plugins/api/solidfire-intg-test/src/main/java/org/apache/cloudstack/api/command/admin/solidfire/GetSolidFireVolumeAccessGroupIdsCmd.java
plugins/api/solidfire-intg-test/src/main/java/org/apache/cloudstack/api/response/solidfire/ApiSolidFireVolumeAccessGroupIdsResponse.java
plugins/api/solidfire-intg-test/src/main/java/org/apache/cloudstack/api/solidfire/ApiSolidFireIntegrationTestServiceImpl.java
plugins/api/solidfire-intg-test/src/main/java/org/apache/cloudstack/solidfire/SolidFireIntegrationTestManager.java
plugins/api/solidfire-intg-test/src/main/java/org/apache/cloudstack/solidfire/SolidFireIntegrationTestManagerImpl.java
plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageProcessor.java
plugins/storage/volume/solidfire/src/main/java/org/apache/cloudstack/storage/datastore/driver/SolidFirePrimaryDataStoreDriver.java
plugins/storage/volume/solidfire/src/main/java/org/apache/cloudstack/storage/datastore/lifecycle/SolidFireSharedPrimaryDataStoreLifeCycle.java
plugins/storage/volume/solidfire/src/main/java/org/apache/cloudstack/storage/datastore/provider/SolidFireHostListener.java
plugins/storage/volume/solidfire/src/main/java/org/apache/cloudstack/storage/datastore/provider/SolidFireSharedHostListener.java
plugins/storage/volume/solidfire/src/main/java/org/apache/cloudstack/storage/datastore/util/SolidFireUtil.java
test/integration/plugins/solidfire/TestAddRemoveHosts.py
test/integration/plugins/solidfire/TestCapacityManagement.py
test/integration/plugins/solidfire/TestSnapshots.py
test/integration/plugins/solidfire/TestUploadDownload.py
test/integration/plugins/solidfire/TestVMMigrationWithStorage.py
test/integration/plugins/solidfire/TestVMSnapshots.py
test/integration/plugins/solidfire/TestVolumes.py

Previously, the SolidFire storage plug-in for managed storage had a 1:1 mapping between a compute cluster and a volume access group (VAG). A VAG is a type of ACL in the SolidFire cluster.
This PR expands that support to be 1:M.
I confirmed after the code changes that you can now have multiple volume access groups support a single compute cluster. Also, you can still have a single volume access group support a compute cluster.

Support multiple volume access groups per compute cluster

---

server/src/com/cloud/network/element/ConfigDriveNetworkElement.java

When querying for a storage pool to create a config drive on, only pools for those volumes that have the right state should be considered.
Testing

check volumes for state when retrieving pool for configDrive creation

---

engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
engine/orchestration/src/test/java/com/cloud/vm/VirtualMachineManagerImplTest.java

This PR refactors a duplicated field vmDetailsDao and _uservmDetailsDao into userVmDetailsDao.
vmDetailsDao, uservmDetailsDao --> userVmDetailsDao
It also removes several unused injected vars as well i.e.;
_domainDao, rulesMgr, _vguTypesDao, _configDepot
I have recompiled CloudStack in my local environment and ran the virtual machine related Marvin smoke tests.
Testing

Refactor userVmDetailsDao field and remove unusued fields

---

api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
api/src/main/java/org/apache/cloudstack/api/command/user/network/MoveNetworkAclItemCmd.java
server/src/main/java/com/cloud/network/vpc/NetworkACLServiceImpl.java
server/src/test/java/com/cloud/network/vpc/NetworkACLServiceImplTest.java
ui/scripts/vpc.js

There was a concurrency problem with the “moveNetworkAclItem” API method. If two users were changing the ACL rules order at the same time, this could lead to inconsistent actions.
To solve the problem we added a “consistency check ” parameter, which is used to hold the consistency hash. This hash is created using an MD5 hash function on a String that is created with all ACL rules UUIDs concatenated in their order, which is defined via the ‘number’ field.
We also lock the editing of the ACL while executing the upgrade. This allows us to handle race conditions nicely, and present a good feedback for the user.
We are not forcing users to send the consistency hash variable. Therefore, they can use the API call without the hash parameter. Therefore, they assume the risk of problems that may …

Fix concurrency problem when moving ACL rules with drag&drop

---

engine/orchestration/src/main/java/com/cloud/agent/manager/ClusteredAgentManagerImpl.java

This PR fixes NPE with the provisionCertificateCmd when reconnect is set to True.
Also fixes the following Marvin test failures:
- test_certauthority_root.py
Fixes: #2753 
With cloudmonkey, see screenshot
Dev environment components:
- Platform: ACS-4.12
- Management OS: Ubuntu 18.04 LTS
- Hypervisor: 1 Host running KVM with CentOS 7
Testing

fix provisionCertificate api returns NPE when 'reconnect' parameter is true

---

scripts/vm/network/security_group.py

In 6233a77d15adde86302a11b2bcda604313833e91 as a part of PR #2432 the
bash() function was replaced by the execute() function.
Somehow this last calling of the bash() function was not caught by testing
and is still in there.
This causes Exceptions to be thrown by the Security Group script.

security_group: Use execute() function instead of non-existing bash()

---

ui/scripts/templates.js

On the 'Register Template From URL' screen, when a user selects the KVM option from the Hypervisor dropdown:
1) It incorrectly displays the 'Original XS Version is 6.1' checkbox. This checkbox should be hidden in the KVM context.
2) The 'Root Disk Controller' dropdown should display the default option of 'osdefault' instead of a blank default option.
Go to the 'Register Template From URL' screen by clicking the 'Templates' tab on the lefthand side.
On the 'Templates' screen click the 'Add' button to display the  the 'Register Template From URL' screen.
On the 'Register Template From URL' screen, select the KVM option from the Hypervisor dropdown:
1) It incorrectly displays the 'Original XS Version is 6.1' checkbox. This checkbox should be hidden in the KVM context.
2) The 'Root Disk …

register template kvm context ui fix

---

api/src/main/java/org/apache/cloudstack/api/response/ExtractResponse.java
api/src/main/java/org/apache/cloudstack/api/response/ZoneResponse.java

Remove response parameters missing a description, and which are not used, creating an empty entry in `listApis` call (see the empty `{}` below):
```json
"related": "listZones,createZone",
"response": [
{
"description": "the allocation state of the cluster",
"name": "allocationstate",
"type": "string"
},
{},
{
"description": "the first DNS for the Zone",
"name": "dns1",
"type": "string"
},
```
Testing

api: remove empty response parameters

---

api/src/main/java/com/cloud/storage/VolumeApiService.java
server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
server/src/test/java/com/cloud/storage/VolumeApiServiceImplTest.java

When the feature to enable disk offering replacement during volume migration was created, we were forcing the tags of the new disk offering to exact the same as the tags of the target storage poll. However, that is not how ACS manages volumes allocation. This change modifies this validation to make it consistent with volume allocation.
The idea is to make the validation consistent with the mechanism used to select a storage pool to deploy a volume when a virtual machine is deployed or when a new data disk is allocated. The scenarios when this method returns true or false is presented in the following table.
<table border="1">
<tr>
<th>#</th><th>Disk offering tags</th><th>Storage tags</th><th>Does the storage support the disk offering?</th>
</tr>
<body>
<tr> …

Fix limitation on tag matching in 'migrateVolume' with disk offering replacement

---

ui/scripts/ui-custom/zoneWizard.js

In the Add Zone Wizard, when a user lands on the Physical Network page, by default the first Physical Network gets initialized with the 3 Traffic Types: Guest, Management and Public. When a user drags the Management or Public Traffic Types from the first Physical Network to a second or nth Physical Network and then clicks the next button to go to the next screen, and then decides to click the previous button to go back to the Physical Network screen, the UI initializes the physicalNetwork again and thus moves these Traffic Types back to their original position in the first Physical Network as if it is the first time the user navigated to this page. 
A fix was made so that when a user clicks the previous button to go back to the Physical Network screen, it does not initialize the …

storage traffic type reset ui fix 

---

core/src/com/cloud/info/ConsoleProxyInfo.java

Ensures we have a valid console proxy domain for protocol http even a `*` setting is used. See #2733 
- Bug fix (non-breaking change which fixes an issue)
Fixes #2733 
after fix 
Manually in simulator setup
Testing

Fix invalid consoleproxy url after upgrade

---

plugins/hypervisors/vmware/src/com/cloud/hypervisor/vmware/resource/VmwareResource.java

Fixing capitalized 'ConfigDrive' iso path to lowercase 'configdrive'
Fixes: #2759
Testing

Fix config drive iso path on Vmware

---

ui/scripts/instances.js

In the UI, on the Instances screen, the Quickview popup window and the Details window do not display the 'Reset SSH Key Pair' button for VMs in a running state. They only display when the VM is in a stopped state. This is inconsistent with the 'Reset Password' button behaviour, where it displays in both VM states: running and stopped. This fixes the issue so that the 'Reset SSH Key Pair' button also displays in both VM states.
In the UI, on the Instances screen, the Quickview popup window and the Details window must display the 'Reset SSH Key Pair' button in both VM states: running and stopped. When a user clicks on the 'Reset SSH Key Pair' button and a VM is in a running state, it will display a message "Vm xxx should be stopped to do SSH Key reset". …

reset ssh key pair visibility

---

tools/appliance/builtin/template.json

The correct ISO url is http://mirror.nbrc.ac.in/centos/7/isos/x86_64/CentOS-7-x86_64-Minimal-1804.iso and not ends with `1808`.
Testing

Fix typo in ISO url

---

ui/scripts/templates.js

On the 'Register Template From URL' screen, when a user selects the VMware option from the Hypervisor dropdown:
It incorrectly displays the 'HVM' checkbox. 
This checkbox must be hidden in the VMware context.
This checkbox must still be visible in any other hypervisor context.
To Reproduce:
Go to the 'Register Template From URL' screen by clicking the 'Templates' tab on the lefthand side.
On the 'Templates' screen click the 'Add' button to display the 'Register Template From URL' screen.
On the 'Register Template From URL' screen, select the VMware option from the Hypervisor dropdown:
It incorrectly displays the 'HVM' checkbox. 
Expected behaviour:
This checkbox must be hidden in the VMware context.
This checkbox must still be visible in any other hypervisor context. …

hvm checkbox visibility

---

systemvm/debian/opt/cloud/bin/cs/CsDhcp.py

Without this patch, the VR uses the netmask of the primary network for all assigned cidrs.
This patch correctly applies the corresponding netmask.
No issue has yet been reported. We came across this today.
I've live patched the virtual router and rebooted it. Before, `/etc/dnsmasq.d/cloud.conf` had wrong netmasks for several networks. After, the networks were set correctly.
Testing

Fix issue when multiple cidrs with different sizes are assigned on a VR

---

server/src/com/cloud/api/ApiResponseHelper.java
systemvm/debian/opt/cloud/bin/cloud-nic.sh
systemvm/debian/opt/cloud/bin/cs/CsNetfilter.py
systemvm/debian/opt/cloud/bin/cs/CsRoute.py
systemvm/debian/opt/cloud/bin/cs/CsRule.py
systemvm/debian/opt/cloud/bin/ipassoc.sh
systemvm/debian/opt/cloud/bin/update_config.py
test/integration/smoke/test_deploy_virtio_scsi_vm.py
test/integration/smoke/test_vm_life_cycle.py

Previously, the ethernet device index was used as `rt_table` index and
packet marking id/integer. With eth0 that is sometimes used as link-local
interface, the rt_table index `0` would fail as `0` is already defined
as a catchall (unspecified). The fwmarking on packets on eth0 with 0x0
would also fail. This fixes the routing issues, by adding 100 to the
ethernet device index so the value is a non-zero, for example then the
relationship between rt_table index and ethernet would be like:
100 -> Table_eth0 -> eth0 -> fwmark 100 or 0x64
101 -> Table_eth1 -> eth1 -> fwmark 101 or 0x65
101 -> Table_eth2 -> eth2 -> fwmark 102 or 0x66
This would maintain the legacy design of routing based on packet mark
and appropriate routing table rules per table/ids. This also fixes a
minor NPE issue around …

router: Fixes #2789 fix proper mark based packet routing across interfaces

---

ui/scripts/instances.js

On the 'NICs' tab, when a user clicks the 'Add network to VM' button to add a network to a VM, the 'Add network to VM' popup screen does not have an IP Address input field to allow a user to define a specific IP Address for a NIC. A user can specify the IP address for the first NIC when creating a VM instance, but cannot do that for subsequent NICs when adding a network to a VM.
To Reproduce:
Go to the 'Instances' screen by clicking the 'Instances' tab on the lefthand side.
On the 'Instances' screen click on a specific VM instance name. 
This will open the 'Details' tab for the specific VM instance.
Click on the 'NICs' tab and then click on the 'Add network to VM' button to add a network to a VM. 
The 'Add network to VM' popup screen will display.
The 'Add network to VM' …

add ipaddress input field to 'Add network to VM' form

---

ui/scripts/plugins.js

In the index.html file, the reference to the custom.css file is made on the last line of the \<head\> tag. 
The plugins.js file appends a list of CSS files to the \<head\> tag dynamically, consequently placing them after the custom.css file and overriding it.
The plugins.js file must insert the list of CSS files before the custom.css file so that it does not get overridden.
The plugins.js file appends a list of CSS files to the \<head\> tag dynamically, consequently placing them after the custom.css file and overriding it.
To Reproduce:
Log in to the Cloudstack UI using your favourite browser.
Use your browser's development tool to view the HTML elements of the index.html loaded in memory.
Expand the \<head\> element and review the list of CSS …

insert plugin css files before custom.css file

---

ui/css/cloudstack3.css

When a regular user navigates to the Dashboard screen and hovers over the 'Latest events' entries, the mouse cursor changes to a hand pointer, but it cannot select any of these entries.
When a user navigates to the Dashboard screen and hovers over the 'Latest events' entries, the mouse cursor must not change to a hand pointer. This will allow the user to make the correct interpretation that the 'Latest events' entries are not selectable.
When a user navigates to the Dashboard screen and hovers over the 'Latest events' entries, the mouse cursor changes to a hand pointer. This causes a user to incorrectly interpret that the entries are selectable.
To Reproduce:
Log in to the Cloudstack UI as a regular User.
On the Dashboard screen, hover the mouse over …

change dashboard events cursor to default to prevent user confusion

---

ui/css/cloudstack3.css
ui/scripts/ui/widgets/listView.js

In the UI, when a user navigates to a screen that displays a table of data and hovers the mouse over a sortable column header, the cursor does not change to a hand pointer, indicating to the user that it can be clicked on, in order to sort the table's data rows according to that column. 
When the mouse hovers over the non-sortable 'Quickview' column header, it incorrectly displays a hand pointer cursor instead of a default cursor.
When the mouse hovers over a column header, it also does not display the column header's value as a tooltip. 
The cursor type for a sortable column header must display a hand pointer.
The cursor type for the non-sortable 'Quickview' column header must display a default pointer.
When the mouse hovers over a column header it must display the …

data table header cursor type and title

---

ui/css/cloudstack3.css

In the UI, when a VM instance has more than one NIC, the NICs screen does not display all the details of the first NIC. The last few rows of text overlap with the second NIC's text. This is due to the incorrect placement of the second NIC's bar. The default height sizing does not allow enough head space to display all the details of the first NIC before displaying the second NIC's details.
When a VM instance has more than one NIC, the NICs screen must allow enough height size to display all the details of the first NIC before displaying the second NIC's details. The last few rows of text must not overlap with the second NIC's text.
Current Behaviour:
When a VM instance has more than one NIC, the NICs screen does not allow enough height size to display all the details …

add height sizing to detail view so that it renders all detail items

---

plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtStartCommandWrapper.java
plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java

When a Instance is (attempted to be) started in KVM Host the Agent
should not worry about the allocated memory on this host.
To make a proper judgement we need to take more into account:
- Memory Overcommit ratio
- Host reserved memory
- Host overcommit memory
The Management Server has all the information and the DeploymentPlanner
has to make the decision if a Instance should and can be started on a
Host, not the host itself.

kvm: Agent should not check if remaining memory on host is sufficient

---

server/src/com/cloud/consoleproxy/ConsoleProxyManagerImpl.java
systemvm/debian/opt/cloud/bin/setup/router.sh
ui/scripts/instances.js
ui/scripts/system.js

This re-introduces the rebooting of VR after setup of nics/macs in
case of VMware. It also adds a minor enhancement to show the console
esp. for root admins when VRs and systemvms are in starting state.
The issue seen was in Vmware 5.5u3 and older environments where VR does not work unless they are rebooted (reset). In 4.9 systemvm code, it used to reboot after setup of router nic-mac addresses:
https://github.com/apache/cloudstack/blob/4.9/systemvm/patches/debian/config/etc/init.d/cloud-early-config#L914
This PR reintroduces rebooting only in case of VMware where the issue was seen with older hypervisors/vcenter versions. The other change this PR bring is to allow at least the root admins to show console for VMs in starting state.
On a VMware + ACS 4.9 env, upgraded to ACS 4.11.1.0 it is …

vmware: reboot VR after mac updates

---

engine/schema/src/main/java/com/cloud/storage/dao/VolumeDao.java
engine/schema/src/main/java/com/cloud/storage/dao/VolumeDaoImpl.java
server/src/main/java/com/cloud/storage/snapshot/SnapshotManagerImpl.java

After domain deletion, snapshot taken by the domain remains undeleted.
-----------------------------------------------
1. Create a test domain
2. Create test account with admin privileges.
3. Login as "test" acoount.
4. Create 3 instances - few having root disk and rest with root and data disks both.
5. For 2 instances take snapshots of root and data disks
6. Expunge above instances from ACP UI.
7. Make sure that those vm's should not be shown in ACP UI.
8. Login as root user again
9. Delete the test account
10. Delete the test domain
Snapshots taken for root volume in step 5 are not deleted.
Added the code to remove the snapshots when the domain is deleted.

CLOUDSTACK-10223 delete snapshots when deleting domain

---

core/src/test/java/com/cloud/info/ConsoleProxyInfoTest.java

follow up of #2734
#2734
Testing

tests: add unit tests for console proxy url

---

test/integration/smoke/test_volumes.py

Adds a livemigrate = True to vmware and xenserver test execution, since it was reported in the latest failures
`The volume Vol[254|vm=233|DATADISK]is attached to a vm and for migrating it the parameter livemigrate should be specified'`
NA
Trillian smoketests
Testing

Fix migrate vol xen vmware test

---

engine/schema/src/main/java/org/apache/cloudstack/storage/datastore/db/SnapshotDataStoreDao.java
engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/snapshot/SnapshotDataFactoryImpl.java
engine/storage/snapshot/src/test/java/org/apache/cloudstack/storage/snapshot/SnapshotDataFactoryImplTest.java
engine/storage/src/main/java/org/apache/cloudstack/storage/image/db/SnapshotDataStoreDaoImpl.java

While checking a problem with @mike-tutkowski at PR #1740, we noticed that the method `org.apache.cloudstack.storage.snapshot.SnapshotDataFactoryImpl.getSnapshots(long, DataStoreRole)` was not loading the snapshots in `snapshot_store_ref` table according to their storage role. Instead, it would return a list of all snapshots (even if they are not in the storage role sent as a parameter) saying that they are in the storage that was sent as parameter.
Manually and unit tests
Testing

Fix the problem at #1740 when it loads all snapshots in the primary storage

---

ui/scripts/ui-custom/projectSelect.js

In the UI, the 'Project' drop-down displays all the projects that the logged in user is a member of.
A regular user can add other accounts to a project when creating the project. 
An Admin user can also add other accounts to an existing project.
When user 'x' adds account 'y' to a project 'z' and user 'y' is logged in to another session at the same time, the 'Project' drop-down in user 'y' session does not display project 'z' to which he/she has just been added as a member in the other session. 
The latest project addition will only display in the drop-down if the user refreshes the HTML page.
Whenever user 'y' clicks on the drop-down to display the projects, it must include the newly added project 'z' without having to refresh the HTML page.
Whenever a user clicks on …

Project drop-down refresh data fix

---

ui/index.html

fixes #2575 
In the dictionary internationalization javascript files there are certain label translation descriptions that contain HTML markup to help format the text when it is rendered in the UI. 
These HTML markup tags must be rendered as HTML instead of plain text.
These HTML markup tags are currently rendering as plain text instead of HTML.
For example, the HTML line break tag renders as plain text: '\<br/\>' instead of rendering an actual HTML line break.
To Reproduce:
Create a Zone. In the UI, in the left-hand pane, click on the Infrastructure link and click on Zones.
On the Zones screen, click on the 'Create Zone' button to create a Zone. Follow the Zone creation wizard steps up until the 'HOST' step. Notice that the description contains the …

display translation labels as html instead of plain text

---

plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/KVMHABase.java
plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/KVMHAMonitor.java
scripts/vm/hypervisor/kvm/kvmheartbeat.sh

Rebase of #2472 onto 4.11
If the KVM heartbeat file can't be written to, the host is rebooted, and thus taking down all VMs running on it. The code does try 5x times before the reboot, but the there is not a delay between the retires, so they are 5 simultaneous retries, which doesn't help. Standard SAN storage HA operations or quick network blip could cause this reboot to occur.
Some discussions on the dev mailing list revealed that some people are just commenting out the reboot line in their version of the CloudStack source.
A better option would be have it sleep between tries so it isn't 5x almost simultaneous tries. Plus, instead of rebooting, the cloudstack-agent could just be stopped on the host instead. This will cause alerts to be issued and if the host is disconnected long-enough, …

CLOUDSTACK-10310 Fix KVM reboot on storage issue

---

ui/scripts/ui/dialog.js

The error fixed by this PR happens when we have a Pop-up modal with an error message in the latest master. When we close the modal, the overlay div is not being hidden. Therefore, the screen gets locked. 
The solution is quite simple, we should hide the overlay div when closing the modal pop-up.
Manually
Testing

Fix Div overlay problem when PopUp modal with error message is closed

---

api/src/main/java/com/cloud/storage/snapshot/SnapshotApiService.java
api/src/main/java/org/apache/cloudstack/api/command/user/snapshot/ArchiveSnapshotCmd.java
engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/snapshot/SnapshotServiceImpl.java
engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/snapshot/SnapshotStateMachineManagerImpl.java
server/src/main/java/com/cloud/server/ManagementServerImpl.java
server/src/main/java/com/cloud/storage/snapshot/SnapshotManagerImpl.java
server/src/test/java/com/cloud/storage/snapshot/SnapshotManagerTest.java

This PR adds an API call named `archiveSnapshot` which takes in a snapshot residing on primary storage and moves it to secondary storage. The main use case for this relates to the use in Managed storage where the storage supports native snapshots. Because of cost and availability reasons, it is useful to move snapshots that are taken on primary storage (native snapshots) to secondary storage. 
The API takes in a `snapshotid` , creates a new snapshot on secondary storage and deletes the snapshot on primary storage. 
Tested on a local storage cluster (SolidFire) and also added unit tests.
Testing

Add ability to archive snapshots on primary storage

---

agent/bindir/libvirtqemuhook.in

KVM utilised under CloudStack uses the standard libvirt hook script behaviour. During the install of the KVM CloudStack agent the script "/etc/libvirt/hooks/qemu" is populated based on the CloudStack-provided file "libvirtqemuhook.in". This is a python script that carries out network management every time a VM is started, stopped or migrated (as per the qemu script specification). Please note that CloudStack does not provide any scripts for other libvirt actions – and the scope of this feature request is limited to the "qemu" script itself.
Design Document page:
https://cwiki.apache.org/confluence/display/CLOUDSTACK/KVM+hook+script+include
Regression and Functional Tests.
Preconditions:
* Advanced zone configuration with 1 zones, 1 pods
* 2x hosts running KVM CentOS 6.9 
* Create custom …

KVM hook script include

---

tools/appliance/shar_cloud_scripts.sh
tools/appliance/systemvmtemplate/http/preseed.cfg
tools/appliance/systemvmtemplate/template.json

build.sh systemvmtemplate failed while pulling updates. Reason was ‘No Space Left on Device’ Error on the root partition.
So I went on and increased the partition size and it built succesfully.
Testing revealed, that the boot partition has to be bigger than 60MB to allow installing updates.
Also I had bash ambiguous redirect error in shar_cloud_scripts.sh wich I fixed by placing quotes
Built successfully via:
bash build.sh systemvmtemplate
Testing

Bigger partiton table for SVM & ambigous redirect bugfix

---

engine/orchestration/src/com/cloud/vm/VirtualMachineManagerImpl.java

In integration work for CCS I found that the service call UserVmService.destroyVm(long uuid, boolean expunge) does not honour the expunge flag. I traced it down to the implementation VirtualMachineManagerImpl.destroy(String vmUuid, boolean expunge)
manual testing so far, testing will pose some crosscutting challanges as the behaviour and implementation are seperated by about five layers of abstraction.
Testing

expunge if flag is set

---

ui/index.html

In the UI, when Setting up a recurring snapshot for a volume and clicking 'Add', the newly added scheduled snapshot entry is not displayed in the 'Scheduled Snapshots' table. Also, the 'Keep' input field does not limit the length of a number that can be added. This causes the API not return an error that the value is invalid.
After adding a recurring snapshot, it must display in the 'Scheduled Snapshots' table. The 'Keep' input field must restrain a user from entering too large of a number.
Fixes: #2831
Manually
In the UI, click on the 'Instance' button. Click on an instance. Click the 'View Volumes' button. Click on a specific volume.  Click the 'Set up Recurring Snapshot' button.  Add a Recurring Snapshot and observe that it now does display the newly added schedule. Also when adding a …

Volume snapshot recurring schedule not showing

---

systemvm/debian/opt/cloud/bin/setup/cloud-early-config

Set hypervisor to xen-hvm when virt-what detects both HyperV cpuid and xen-domU
Fixes: #2760 
Tested on Cloudstack 4.11.1 + XenServer 7.1.1 with a patched systemvm template.
Testing

Fix SystemVMs running in Xen HVM mode are not configured (#2760)

---

engine/components-api/src/com/cloud/storage/StorageManager.java
server/src/com/cloud/storage/StorageManagerImpl.java
server/src/com/cloud/storage/VolumeApiServiceImpl.java

This was previously opened as PR but prematurely closed:
https://github.com/apache/cloudstack/pull/1931
https://github.com/apache/cloudstack/pull/1932
Issue: https://issues.apache.org/jira/browse/CLOUDSTACK-9473
Storage pool checker is not being called on resize and migrate volume.
This may lead to allocated percentage of storage above 100%.
Setup:
1 VMware cluster with 2 Hosts.
Executed Steps:
Applied the following global settings:
storage.overprovisioning.factor = 1
pool.storage.allocated.capacity.disablethreshold = 1
pool.storage.capacity.disablethreshold = 1
Restarted management server
Executed Resize and migrate pool and Observed that Storage pool checker is not performed on resizeVolume and migrateVolume.
Result:
Root cause analysis shows storage pool checker is not called when …

CLOUDSTACK-9473: storage pool capacity check when volume is resized or migrated

---

engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
engine/orchestration/src/test/java/com/cloud/vm/VirtualMachineManagerImplTest.java

Mike discovered that when PR https://github.com/apache/cloudstack/pull/2425/ was merged, we created a bug with managed storage. The following constraints needed to be added to ACS:
* If I want to migrate a VM across clusters, but if at least one of its volumes is placed in a cluster-wide managed storage, the migration is not allowed. On the other hand, if the VM is placed in a managed zone-wide storage, the migration can be executed;
* A volume placed in managed storage can never (at least not using this migrateWithVolume method) be migrated out of the storage pool it resides; 
* When migrating a VM that does not have volumes in managed storage, it should be possible to migrate it cross clusters. Therefore, we should try to use the volume allocators to find a suitable storage pool for its …

Add managed storage pool constraints to MigrateWithVolume API method

---

engine/schema/resources/META-INF/db/schema-41110to41120-cleanup.sql
engine/schema/resources/META-INF/db/schema-41110to41120.sql
engine/schema/src/com/cloud/upgrade/DatabaseUpgradeChecker.java
engine/schema/src/com/cloud/upgrade/dao/Upgrade41100to41110.java
engine/schema/src/com/cloud/upgrade/dao/Upgrade41110to41120.java
systemvm/debian/opt/cloud/bin/setup/cloud-early-config
systemvm/debian/opt/cloud/bin/setup/common.sh
systemvm/debian/opt/cloud/bin/setup/postinit.sh
systemvm/debian/opt/cloud/bin/setup/router.sh
systemvm/debian/opt/cloud/bin/setup/vpcrouter.sh
tools/appliance/systemvmtemplate/scripts/apt_upgrade.sh

This adds upgrade path for a new 4.11.2 systemvmtemplate that will include latest
ca certs, linux kernel and strongswan security fixes. This also adds support for XS 7.5 release.
VMware router will be rebooted based on #2794, per current config
the VRs on reboot will go through fsck checks slowing down the deployment
process by few seconds. This will ensure that fsck checks are done
on every 3rd boot of the VR. The `4` is used because 1st boot is done
during the build of systemvmtemplate appliance.
Testing

systemvmtemplate: new 4.11.2 template and fixes

---

engine/orchestration/src/org/apache/cloudstack/engine/orchestration/VolumeOrchestrator.java
engine/schema/resources/META-INF/db/schema-41110to41120.sql
engine/schema/src/com/cloud/vm/UserVmCloneSettingVO.java

The use of full/linked clones on Vmware caused some VMs not starting due to ArrayIndexOutOfBoundsException
#2838 BLOCKER: 4.11.1: VMware: VM start fails with ArrayIndexOutOfBoundsException
On Vmware environment:
- Set configuration vmware.create.full.clone = true
- Create VM
- Set configuration vmware.create.full.clone = false
- Stop/start the same VM 
Testing

Fix for Vmware full clones update

---

engine/orchestration/src/com/cloud/vm/VirtualMachinePowerStateSyncImpl.java

Fallback to update (and creating) time when power state update time is null.
Follow up of CLOUDSTACK-8848 
(also see https://github.com/apache/cloudstack/commit/542880ae76c5e6eefbf61d42364e881495e6f3af#diff-dd162c545fd70c5cf2c4b2fa599c13c9L114)
Fixes #2845 
N/A
Needs testing
Testing

Fix PowerReportMissing for new VRs

---

engine/schema/src/com/cloud/upgrade/dao/Upgrade41110to41120.java
systemvm/debian/opt/cloud/bin/setup/cloud-early-config
systemvm/debian/opt/cloud/bin/setup/postinit.sh
tools/appliance/systemvmtemplate/scripts/configure_systemvm_services.sh

This fixes a regression introduced in #2799, by exporting $TYPE
before the `patch` is called to patch/extract archives for ssvm/cpvm.
See comment: https://github.com/apache/cloudstack/pull/2799/files#r218825730
Note: the fix is in cloud-early-config, so we can simply rebuild a new 4.11.2 systemvmtemplate and still continue testing 4.11.2.0 RC1 for end of the week if there are more issues/bugs and try to cut RC2 next week. /cc @PaulAngus 
Testing

systemvm: export $TYPE before patching ssvm/cpvm

---

agent/src/com/cloud/agent/Agent.java

This fixes the issue that on reconnection, agent LB feature will fail
and only the first ms-host will be tried reconnection again and again.
Testing

agent: Fixes #2858 agent LB not working

---

engine/orchestration/src/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
engine/schema/src/com/cloud/vm/dao/UserVmDaoImpl.java
engine/schema/src/org/apache/cloudstack/resourcedetail/ResourceDetailsDao.java
engine/schema/src/org/apache/cloudstack/resourcedetail/ResourceDetailsDaoBase.java
server/src/com/cloud/network/element/VirtualRouterElement.java
server/src/com/cloud/vm/UserVmManagerImpl.java
test/integration/component/test_configdrive.py
test/integration/plugins/nuagevsp/nuageTestCase.py
test/integration/plugins/nuagevsp/nuage_lib.py
test/integration/plugins/nuagevsp/test_nuage_configdrive.py
test/integration/plugins/nuagevsp/test_nuage_extra_dhcp.py
test/integration/plugins/nuagevsp/test_nuage_internal_dns.py
test/integration/plugins/nuagevsp/test_nuage_network_migration.py
test/integration/plugins/nuagevsp/test_nuage_password_reset.py
test/integration/plugins/nuagevsp/test_nuage_source_nat.py
test/integration/plugins/nuagevsp/test_nuage_static_nat.py
test/integration/plugins/nuagevsp/test_nuage_vpc_internal_lb.py
test/integration/plugins/nuagevsp/test_nuage_vpc_network.py
test/integration/plugins/nuagevsp/test_nuage_vsp_domain_template.py
test/integration/plugins/nuagevsp/test_nuage_vsp_mngd_subnets.py
tools/marvin/marvin/lib/base.py
tools/marvin/marvin/lib/common.py
tools/marvin/setup.py

* When password reset is called, and VR accepts it, set vm updateParameters to false.
* When password reset is called, and SSH key is set, make sure the password isn't removed again.
* Fix Marvin tests
* Make sure saveDetails keeps the display value of the existing details.
- Manual 
- automated marvin pugins nuagevsp tests on ACS + NuageVsp
- automated marvin component test for config drive
Testing

CLOUDSTACK-10380: Fix startvm giving another pw after pw reset

---

systemvm/debian/opt/cloud/bin/baremetal-vr.py

We see a suspicious continuous increase in memory usage. Kind of looks like a memory leak. 
One thing noted during debugging  is that flask is started in debug mode. This is not best practice for a production system.  
Testing

systemvm: baremetal-vr: reduce memory usage

---

utils/src/main/java/org/apache/cloudstack/utils/security/CertUtils.java

This makes openssl rsa -in <file> -check pass, due to "RSA" string the
validate of private key (pem file) by openssl fails. Also removes
a commented import.
Without this fix, in some systems the key/crt could not be reused. Following error was observed in openssl:
$ openssl rsa -in <private key pem file> -check
RSA key ok
139832889164824:error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag:tasn_dec.c:1220:
139832889164824:error:0D06C03A:asn1 encoding routines:ASN1_D2I_EX_PRIMITIVE:nested asn1 error:tasn_dec.c:788:
139832889164824:error:0D08303A:asn1 encoding routines:ASN1_TEMPLATE_NOEXP_D2I:nested asn1 error:tasn_dec.c:720:Field=n, Type=RSA
139832889164824:error:04093004:rsa routines:OLD_RSA_PRIV_DECODE:RSA lib:rsa_ameth.c:121:
With this fix, the private key pem file will pass. …

CertUtils: export private key to pem format correctly

---

scripts/storage/qcow2/resizevolume.sh

Fixed for https://github.com/apache/cloudstack/issues/2868
Incorrect diskpath information was being sent to virsh blockresize, so the block device size was never refreshed to reflect the new disk size.
Fixes: #2868 
This was tested on Centos 7 with Ceph backend storage. Virtio-blk driver was used in the VM. Ubuntu 16.04 and Centos 7 VMs were tested.
Disk was 106GB:
Resize was used via the ACS GUI to resize the block device on ceph to 150GB.
The VM picks up the change immediately:
Yes, see above.
Testing

Fixed Issue 2868, libvirt resize notify failure

---

plugins/ca/root-ca/src/org/apache/cloudstack/ca/provider/RootCAProvider.java
utils/src/main/java/com/cloud/utils/net/NetUtils.java
utils/src/test/java/com/cloud/utils/net/NetUtilsTest.java

This fixes the default RootCA provider implementation to initiate
and issue certificate for mgmt server on startup for all the IP addresses
on the default nic of that host.
Fixes #2877

ca: Fixes #2877 mgmt server cert should have all addrs of default nic

---

usage/conf/log4j-cloud_usage.xml.in

When logging operations of the usage server, a timestamp is not included, making the usage logs hard to interpret.
The same timestamp as used by them management log has been added to the usage server logging output.
Timestamp added to the log4j.xml description of output.
Output now looks like:
2018-10-07 00:15:00,001 INFO  [cloud.usage.UsageManagerImpl] (Usage-Job-1:null) (logid:) starting usage job...
2018-10-07 00:15:00,016 INFO  [cloud.usage.UsageManagerImpl] (Usage-Job-1:null) (logid:) Parsing usage records between Sat Oct 06 00:00:00 UTC 2018 and Sat Oct 06 23:59:59 UTC 2018
2018-10-07 00:15:00,151 DEBUG [event.dao.UsageEventDaoImpl] (Usage-Job-1:null) (logid:) no recent event date, copying all events
This has been tested by building RPMs, installing the usage service and checking …

  add date to usage server logs

---

api/src/com/cloud/network/Network.java
plugins/network-elements/nuage-vsp/test/com/cloud/network/element/NuageVspElementTest.java

Network.Service and Network.Provider were missing a toString() method.
Added toString() methods so appending instances, or a collection of instances 
to a String, will result in an understandable String.
com.cloud.network.Network$Provider@11763e57 requires services: [com.cloud.network.Network$Service@4f9871a2]
Provider Network.Provider[name=NuageVsp] requires services: [Network.Service[name=Connectivity]]
Fixes: #2881
Manually, added Unit Test to validate exception message.
Testing

Fixes: #2881 Improve Exception message

---

api/src/com/cloud/network/NetworkProfile.java
engine/schema/src/com/cloud/vm/dao/NicDao.java
engine/schema/src/com/cloud/vm/dao/NicDaoImpl.java
server/src/com/cloud/network/router/VpcVirtualNetworkApplianceManagerImpl.java
systemvm/debian/opt/cloud/bin/cs_ip.py
utils/src/test/java/com/cloud/utils/net/NetUtilsTest.java

This fixes #2719 where private gateway IP might be incorrectly
programmed on a guest network nic. The VR would now check ipassoc
requests by mac addresses than provided nic/device id in case they are
wrong.
The root cause is that the device id information is lost when aggregated
commands are created upon starting of a new VPC VR, without the correct
device id in ip_associations json it mis-programs the VR.
#2719 
Deploy VPC
Deploy a guest VM on a tier
Add a private gateway
Restart the VPC with cleanup=true
The private gateway should be on correct dev idx (previously both guest network and private gw would be on eth2, eth3 will not have any ip)
/cc @PaulAngus @borisstoyanov 

router: Fixes #2719 program VR nics by device id order for VPC

---

plugins/hypervisors/baremetal/src/com/cloud/baremetal/networkservice/BaremetalKickStartServiceImpl.java
systemvm/debian/etc/sysctl.conf
systemvm/debian/etc/systemd/journald.conf
systemvm/debian/etc/systemd/system/baremetal-vr.service
systemvm/debian/etc/systemd/system/cloud-postinit.service
systemvm/debian/opt/cloud/bin/setup/postinit.sh

This tries to provide a threshold based fix for #2873 where swappinness of VR is not used until last resort. By limiting swappiness unless actually needed, the VR system degradation can be avoided for most cases. The other change is around not starting `baremetal-vr` by default on all VRs, according to the spec https://cwiki.apache.org/confluence/display/CLOUDSTACK/Baremetal+Advanced+Networking+Support only vmware VRs need to run it and that too only as the last step of the setup/completion, so we don't need to run it all the time.
The default swapiness on VRs is 60, by reducing the value swapiness it is anticipated that swappiness will not be normally seen. I could not reproduce the swapping so could not test it.

vr: memory and swap optimizations

---

packaging/systemd/cloudstack-agent.default
packaging/systemd/cloudstack-agent.service

The idea is to create a property in /etc/defaults/cloudstack-agent that can be enabled/disabled (uncommented/commented) to control the enabling of Java remote debug in CloudStack's JVM.
This PR is analogous with #2535, which created an easy way to enable Java remote Debug on the CloudStack management; however, this PR creates a variable (JAVA_DEBUG) that helps on enabling remote debug in the CloudStack agent service.
Testing

Allow enable the Java remote Debug for CloudStack Agent

---

agent/src/com/cloud/agent/Agent.java

When agent is stopped, don't allow reconnection. Previously this would
send a shutdown command to the management server which would put the
host state to Disconnected but then agent's reconnection logic may kick
in sometimes which would connect the agent to the management server
but then the agent process would terminate causing the host to be
put in Alert state (due to ping timeout or it waiting too long).
This fixes the issue by ensuring that when the agent is stopped, it
does not reconnect to the management server.
With a KVM env, just stop the kvm agent the host previously was put in Alert state sometimes. Now, it is put in disconnected state.

agent: Fixes #2899 on shutdown don't allow server reconnection

---

engine/api/src/org/apache/cloudstack/engine/orchestration/service/NetworkOrchestrationService.java
engine/orchestration/src/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
server/src/com/cloud/network/vpc/VpcManagerImpl.java

This adds a global setting for admins who may want the lebacy behaviour of network restart with cleanup=true. In future, this setting may be removed.
The examples of error are in #2880, by having this toggle switch a temporary relief may be possible for such environments.
The global settings ships as 'true', so rolling restart feature is shipped as the default behaviour. If somebody wants legacy behaviour they can set the value to false and try to restart an isolated network or redundant network with cleanup enabled.

network: Allow ability to disable rolling restart feature

---

server/src/com/cloud/api/query/dao/TemplateJoinDaoImpl.java
utils/src/main/java/org/apache/cloudstack/utils/security/DigestHelper.java
utils/src/test/java/org/apache/cloudstack/utils/security/DigestHelperTest.java

Unify checksum API output for templates and ISOs: not list the checksum algorithm on:
- KVM direct downloads
- On in progress normal template downloads. The algorithm is shown on the `listtemplates` API, but after it is downloaded it is not shown anymore:
````
(qa11) 🐵 > list templates id=0699767e-ce21-4967-a53a-3c0f37fe9154 templatefilter=all filter=status,checksum
{
"count": 1,
"template": [
{
"checksum": "{SHA-256}ae490ce8b7a55fa92365f72e7581c3eed651da710794989f263f3816b9dc2ea9",
"status": "50% Downloaded",
}
]
}
(qa11) 🐵 > list templates id=0699767e-ce21-4967-a53a-3c0f37fe9154 templatefilter=all
{
"count": 1,
"template": [
{
"checksum": "ae490ce8b7a55fa92365f72e7581c3eed651da710794989f263f3816b9dc2ea9",
"status": "Download Complete",
}
]
}
````
- KVM direct downloads:
````
(local) …
```

Unify templates/ISOs checksum API output

---

plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtPostCertificateRenewalCommandWrapper.java

Debian does not have libvirt-bin package. Therefore, only for Ubuntu host distro process name libvirt-bin is used, otherwise libvirtd will be used
As discussed in #2909 libvirt-bin is not resent in Debian but it is in Ubuntu. Host check should only be for Ubuntu and not for Debian.
cloudstack/plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtPostCertificateRenewalCommandWrapper.java is changed to fix this.

kvm: Use libvirtd as service name for libvirt for Debian (#2909)

---

client/conf/server.properties.in
client/src/org/apache/cloudstack/ServerDaemon.java

This makes the management server listen 0.0.0.0 by default as we cannot
always assume that the host where management server will be installed
will have ipv6 enabled.

client: mgmt server listen default to 0.0.0.0

---

tools/build/setnextversion.sh

maven command for finding current version might need to download packages and without batch mode it will end in variable. Added '-B' to enable batch mode.
Added '-B' to enable batch mode in maven command for find current version maven command in cloudstack/tools/build/setnextversion.sh shell script.

tools: Added '-B' flag for mvn current version cmd (#2910)

---

systemvm/debian/etc/systemd/system/cloud-postinit.service
systemvm/debian/etc/systemd/system/cloud.service

This fixes an issue for systemvms (CPVM and SSVM) on VMware, as eth0
is not programmed (link-local) the networking.service fails to start
which is a dependency for cloud-postinit service. When cloud-postinit
service fails to start/run, it fails to start the agent (cloud) process.
This fixes the smoketest failures we saw in case of VMware 6.5 with
4.11.
On a VMware 6.5 env, restart any SSVM/CPVM. Post restart, the agent will never connect.
With the changes, once systemvm is restarted the agent will reconnect.

systemvm: Ensure cloud service reboots after failure

---

api/src/main/java/org/apache/cloudstack/api/BaseUpdateTemplateOrIsoCmd.java
api/src/main/java/org/apache/cloudstack/api/command/user/template/CreateTemplateCmd.java
server/src/main/java/com/cloud/template/TemplateManagerImpl.java

Added sshKeyEnabled key in createTemplate and updateTemplate API.
Fixes #2822

template: create/updateTemplate should allow to set/change sshKeyEnabled

---

packaging/centos63/cloud.spec
packaging/centos7/cloud.spec

Install any additional plugin jars in the lib directory to be picked up
by the classpath builder, otherwise one has to manually add the jar
to /etc/default/cloudstack-management after installation. This fixes
the issue for `mysql-ha` plugin.

packaging: install plugins at /usr/share/cloudstack-management/lib

---

engine/orchestration/src/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
server/src/com/cloud/network/vpc/VpcManagerImpl.java

This force stops old VRs when performing rolling restart with
cleanup=true. This will ensure that VRs are powered off quickly than
wait longer for the normal ACPI shutdown. During testing, it was found
on VMware where VM stops are slow compared to XenServer and KVM.
This could likely fix #2880 /cc @resmo 
Restart an isolated network or VPC with cleanup=true, see actions in vCenter. With this changes, it should now refer to powering off the VR.

network: on rolling restart force stop old routers

---

server/src/com/cloud/resourcelimit/ResourceLimitManagerImpl.java

This fixes unwanted transaction commit warning messages such:
txn: Commit called when it is not a transaction:
The code does not need to be in a transaction following the eventually
consistent design. Fixes #2642.
Run the `update resourcecount` API for an account, it should no longer produce annoying logs.

server: fix unwanted txn commit warning messages

---

systemvm/debian/opt/cloud/bin/update_config.py

After upgrade from CS 4.10 to CS 4.11, multiple VRs did not start through.
It did not properly defer the finalize config in update_config.py.
Apparently, the json files are now called differently: where it used to
be vm_dhcp_entry.json it now has a uuid added, for example
vm_metadata.json.4d727b6e-2b48-49df-81c3-b8532f3d6745.
The if statement that checks if the finalize can be safely deferred
therefore no longer matches. This PR contains a fix so finalize is
defered again.
Rohit: I made a boo-boo by force pushing and trying to rebash on @RPDiep 's repo/branch. Submitting his commit on his behalf against 4.11 branch. Sorry @RPDiep /cc @wido.

vr: defer was broken in VR because of json name change

---

tools/docker/docker-compose.yml
tools/docker/mariadb-docker/cloudstack-docker.cnf

A docker-compose file to setup quickly the database for CS. This helps during local development and remove the need to install a local MariaDB/MySQL.
None
`docker-compose up` starts the MariaDB 10.0 database for local development.
Testing

docker: add compose file for database

---

plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/KVMHABase.java
scripts/vm/hypervisor/kvm/kvmheartbeat.sh

On actual testing, I could see that kvmheartbeat.sh script fails on NFS
server failure and stops the agent only. Any HA VMs could be launched
in different hosts, and recovery of NFS server could lead to a state
where a HA enabled VM runs on two hosts and can potentially cause
disk corruptions. In most cases, VM disk corruption will be worse than
VM downtime. I've kept the sleep interval between check/rounds but
reduced it to 10s. The change in behaviour was introduced in #2722.
See comment: https://github.com/apache/cloudstack/issues/2890#issuecomment-434207830

kvm: reset KVM host on heartbeat failure

---

server/src/com/cloud/network/guru/DirectNetworkGuru.java
server/test/com/cloud/network/guru/DirectNetworkGuruTest.java

Fixes: #2989 
In upgrade to 4.11 RC4 from 4.9.3 it was found that Shared networks could not be created after the upgrade, failing with: 
The DirectNetworkGuru refused to design the network due to the isolation method from the physical network was "vlan" and the guru expected "VLAN"
````
2018-11-06 16:21:37,396 TRACE [c.c.n.g.DirectNetworkGuru] (qtp1096283470-28:ctx-bdc0f3b5 ctx-dacb5ddd) (logid:f3094acc) We only take care of Guest networks of type Shared
````

Fix DirectNetworkGuru canHandle checks for lowercase isolation methods

---

agent/conf/agent.properties
api/src/main/java/com/cloud/agent/api/to/NicTO.java
api/src/main/java/com/cloud/agent/api/to/VirtualMachineTO.java
api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
api/src/main/java/org/apache/cloudstack/api/command/user/vm/DeployVMCmd.java
api/src/main/java/org/apache/cloudstack/api/command/user/vm/UpdateVMCmd.java
engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/BridgeVifDriver.java
plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/DirectVifDriver.java
plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/IvsVifDriver.java
plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtDomainXMLParser.java
plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java
plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/OvsVifDriver.java
plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/VifDriver.java
plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/VifDriverBase.java
plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtPlugNicCommandWrapper.java
plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtPrepareForMigrationCommandWrapper.java
plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtReplugNicCommandWrapper.java
plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtStartCommandWrapper.java
plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java
plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/OvsVifDriverTest.java
server/src/main/java/com/cloud/vm/UserVmManagerImpl.java

Enable DPDK support on KVM in conjunction with Open VSwitch.
New properties can be set on `agent.properties` file to enable ports created with dpdkvhostuser type on KVM hosts:
````
openvswitch.dpdk.enabled=true
openvswitch.dpdk.ovs.path=OVS_PATH
````
DPDK guest VMs can be set by sending extra configurations as part of the 'deployVirtualMachine' or 'updateVirtualMachine' API methods. Extra configurations are controlled by a new global setting 'enable.additional.vm.configuration'.
Extra configurations are parts of XML data which are appended to the domail XML of the VM. CloudStack expects an UTF-8 URL encoded string as 'extraconfig' parameter on the mentioned API methods.
Documentation PR: https://github.com/apache/cloudstack-documentation/pull/6 & …

Enable DPDK support on KVM

---

server/src/com/cloud/configuration/ConfigurationManagerImpl.java
ui/scripts/system.js

Fix initial reservation on public IP range addition. Also, if the range is dedicated for system VMs do not allow dedicating it to any account
Fixes: #2929 
- Set reservation to a domain, add range. Verify domain is set to the domain.

[4.11] Fix set initial reservation on public IP ranges

---

engine/schema/src/main/resources/META-INF/db/schema-41120to41200.sql

I need to add three new settings into cloud.configuration. These settings support features that went into 4.11; however, these settings were not themselves automatically placed in cloud.configuration (it required manual work to do so).
I have rebuilt the code and run mvn -P developer -pl developer -Ddeploydb. The new settings
appear in cloud.configuration now.

Adding three new settings into cloud.configuration.

---

ui/scripts/domains.js

When the “deleteDomain” command is sent via UI, the HTML is already updated assuming that the “deleteDomain” command will actually delete it. However, there are cases (domain with allocated resources) that will not allow ACS to remove the command; as a consequence, the UI will not be in sync with ACS state, which can lead to misunderstandings.
Manually

Fix delete domain button in the UI to update only after deleteDomain job finishes

---

server/src/com/cloud/network/NetworkModelImpl.java
server/src/com/cloud/network/NetworkServiceImpl.java
server/test/com/cloud/network/NetworkModelTest.java

After upgrade existing environments to 4.11, ConfigDrive cannot be enabled for existing zones due to missing entry on 'physical_network_service_providers' table.
The UI shows:

Add missing ConfigDrive entries on existing zones after upgrade

---

engine/schema/src/main/java/com/cloud/host/dao/HostDao.java
engine/schema/src/main/java/com/cloud/host/dao/HostDaoImpl.java
plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/VmwareDatacenterService.java
plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/manager/VmwareManagerImpl.java
plugins/hypervisors/vmware/src/main/java/org/apache/cloudstack/api/command/admin/zone/UpdateVmwareDcCmd.java
plugins/hypervisors/vmware/src/test/java/com/cloud/hypervisor/vmware/VmwareDatacenterApiUnitTest.java
plugins/hypervisors/vmware/src/test/java/com/cloud/hypervisor/vmware/manager/VmwareManagerImplTest.java
ui/css/cloudstack3.css
ui/l10n/en.js
ui/scripts/system.js

This adds a new API `updateVmwareDc` that allows admins to update the
VMware datacenter details of a zone. It also recursively updates
the cluster_details for any username/password updates
as well as updates the `url` detail in cluster_details table and `guid`
detail in the host_details table with any newly provided vcenter
domain/ip. The update API assumes that there is only one vCenter per
zone. And, since the username/password for each VMware host could be different
than what gets configured for vcenter at zone level, it does not update the 
username/password in host_details.
Previously, one has to manually update the db with any new vcenter details for the zone.
This also adds a UI button to perform the update operation:
For an existing Vmware setup, tried the API to see that values …

vmware: updateVmwareDc API for updating vmware datacenter details

---

server/src/main/java/com/cloud/capacity/CapacityManagerImpl.java

This should not be in DEBUG as people would want to know that the host was skipped
because it didn't have enough slots available to run the VM.

Print log on INFO if Host reached Max Guests Limit

---

agent/conf/agent.properties

documented "host.reserved.mem.mb" parameter in agent.properties, which exists, but was never documented so far.

documented host.reserved.mem.mb parameter

---

tools/appliance/systemvmtemplate/template.json

This fixes the failing systemvmtemplate build due to 404 on old ISO url.

systemvmtemplate: update debian 9.6 iso url and checksum

---

test/integration/smoke/test_migration.py

Avoid exception when hypervisor not supported:
````
2018-11-10 11:04:17,858 - CRITICAL - EXCEPTION:
...in setUpClass\n    raise unittest.SkipT est("This feature is supported "\n', 'SkipTest: This feature is supported only on Vmware and KVM\n']
````

Skip network migration tests for not supported hypervisors instead of failing

---

engine/api/src/main/java/org/apache/cloudstack/engine/subsystem/api/storage/StrategyPriority.java
engine/storage/src/test/java/org/apache/cloudstack/engine/subsystem/api/storage/StrategyPriorityTest.java

Remove unused `StrategyPriority.PLUGIN` enum. The **PLUGIN** Strategy priority is not used, except by three JUnit test methods.

Remove unused StrategyPriority.PLUGIN

---

pom.xml

Due to issue described in Surefix bug:
https://issues.apache.org/jira/browse/SUREFIRE-1588
Debian-based users/developers can no longer build CloudStack 4.11+
branches. The other workaround is to have the following jvm property:
jdk.net.URLClassPath.disableClassPathURLCheck=true
The other workaround is to skipTests (not ideal). Developers can continue to use
-Djdk.net.URLClassPath.disableClassPathURLCheck=true with `mvn`.

surefire: ignore system classloader to make tests run

---

engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
server/src/main/java/com/cloud/network/guru/DirectNetworkGuru.java

With earlier work in Basic Networking and the security group provider IPv6 is
supported and we can allow IPv6 to be supplied in networks with SG enabled.

ipv6: Advanced Networking Security Groups are supported

---

engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
engine/orchestration/src/test/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestratorTest.java
engine/schema/src/main/java/com/cloud/dc/dao/VlanDao.java
engine/schema/src/main/java/com/cloud/dc/dao/VlanDaoImpl.java
server/src/main/java/com/cloud/network/guru/DirectPodBasedNetworkGuru.java
utils/src/main/java/com/cloud/utils/net/NetUtils.java

This pull request allows deploying VMs with a specific IPv4 address.
DirectPodBasedNetworkGuru does not support requesting a custom IP-Address while creating a new NIC/Instance, throwing the following error:
> Error 530: Does not support custom ip allocation at this time: NicProfile[0-0-null-null-null
>     Unknown macro: { "cserrorcode"} 
Some use-cases prefer the ability to request the IPv4 address which the Instance will get.
This implementation adds unit test cases to cover and it was manually tested in Basic Networking. I can perform more tests if requested.
Testing

CLOUDSTACK-10199: Support requesting a specific IPv4 address

---

api/src/main/java/org/apache/cloudstack/api/command/user/iso/RegisterIsoCmd.java
api/src/main/java/org/apache/cloudstack/api/command/user/iso/UpdateIsoCmd.java
server/src/main/java/com/cloud/api/query/dao/TemplateJoinDaoImpl.java
server/src/main/java/com/cloud/template/TemplateAdapterBase.java
test/integration/smoke/test_iso.py

Both register and update iso commands can allow for allowing password enabled.
Fixes: #2745 
Ran register iso and update iso API through cloudmonkey. Also added passwordenabled field changes to true after update iso api call through test_iso.py#test_02_edit_iso

Allow password enabled for iso (#2745)

---

test/integration/smoke/test_scale_vm.py

Adds a skip if the exception is related to licensing of the particular host
Locally on a XenServer env

Adding a try catch for Xen licensing issue

---

framework/config/src/main/java/org/apache/cloudstack/framework/config/impl/ConfigDepotImpl.java
framework/config/src/test/java/org/apache/cloudstack/framework/config/impl/ConfigDepotImplTest.java

A null pointer is thrown if a `ConfigKey.Scope.ManagementServer` is used for configuring a ConfigKey.
The null pointer happens because the map `_scopeLevelConfigsMap` does not contain the `ConfigKey.Scope.ManagementServer` as a key.
Fixed by adding `ConfigKey.Scope.ManagementServer` in the map `_scopeLevelConfigsMap`.

Fix null pointer exception when using ConfigKey.Scope.ManagementServer

---

scripts/vm/network/security_group.py

Currently secondary ipv6 addresses are added to the ipv4 ipset in security_group.py.
This doesn't work, so this patch adds a function to split a set of ips in ipv4 and ipv6 addresses.
Both the `default_network_rules` and `network_rules_vmSecondaryIp` functions now utilise this function and add the ips to the appropriate ipsets.
Tried on a 4.11 hypervisor. Results were as expected

Security Group: add secondary ips to the correct ipset based on ip family (4.11)

---

plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/BridgeVifDriver.java
plugins/hypervisors/kvm/test/com/cloud/hypervisor/kvm/resource/BridgeVifDriverTest.java

When vxlan://untagged is used for public (or guest) network, use the
default public/guest bridge device same as how vlan://untagged works.
Note: currently its possible to use vlan://untagged in the public IP address range for a zone with `vxlan` isolation, which will trick cloudstack-agent (bridge driver) to think the vif/nic to plug is of vlan type and allows `untagged` plugging into the default public/guest bridge device (by default cloudbr0/br1).
Deploy a KVM advance zone with VXLAN isolation for guest+management+public physical nics/network and pass vxlan://untagged for the public address/range. Agent logs will have exceptions on incorrect `untagged` vnet ID passed error.

kvm: when untagged vxlan is used, use the default guest/public bridge

---

api/src/org/apache/cloudstack/api/response/UserVmResponse.java
server/src/com/cloud/api/query/dao/UserVmJoinDaoImpl.java

This is a backport to 4.11 of #2528 
Locally

API: move ostypeid from DB id to DB uuid, backports #2528

---

packaging/centos7/cloud.spec
packaging/systemd/cloudstack-management.service

There are only two small, small, small really small fixes.
Install CentOS 7 e.g. Build 1804 and Java build 1.8.0_181
if you inspect systemd in debug mode you will see some errors
1.
permission of the cloudstack-managment.service are not corretly set
2.
invalid classpath specified. it seems the string which is used will be divided... we now we use ${..} like the lines above ... :confused:
We tested it on our test environment! We create own build with our test pipeline.
CentOS 7 Build 1804, Cloudstack 4.11, Java Build 1.8.0_181, systemd Build 219-57.el7_5.3

correct permissions in spec file and fix class path specified variable

---

agent/src/com/cloud/agent/Agent.java
core/src/com/cloud/agent/resource/virtualnetwork/VirtualRoutingResource.java

This increases and uses a default 15mins timeout for VR scripts and for
KVM agent increases timeout from 60s to 5mins. The timeout can
specifically occur when keystore does not get enough entropy from CPU
and script gets killed due to timeout. This is a very specific corner
case and generally should not happen on baremetal/prod environment, but
sometimes seen in nested/test environments.
/cc @PaulAngus @DagSonstebo

security: increase keystore setup/import timeout

---

plugins/api/discovery/src/org/apache/cloudstack/api/response/ApiDiscoveryResponse.java
plugins/api/discovery/src/org/apache/cloudstack/api/response/ApiResponseResponse.java
plugins/api/discovery/src/org/apache/cloudstack/discovery/ApiDiscoveryServiceImpl.java
plugins/api/discovery/test/org/apache/cloudstack/discovery/ApiDiscoveryTest.java

Updated `ApiServiceDiscoveryImpl` to check superclasses of API responses for fields.
Fixes: #3002 
- [x ] Bug fix (non-breaking change which fixes an issue)
Additional unit test and tested locally to verify the tags field was present in the output of listApis response for listVirtualMachines API.

Discover tags field on superclass of API responses

---

plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java

If a host has many routes this can be a magnitude faster then printing
all the routes and grepping for the default.
In some situations the host might have a large amount of routes due to
dynamic routing being used like OSPF or BGP.
In addition fix a couple of loglines which were throwing messages on
DEBUG while WARN and ERROR should be used there.

kvm: Use 'ip route show default 0.0.0.0/0' to find the default gateway

---

tools/travis/before_install.sh
tools/travis/script.sh

This fixes issue with recent Travis runs which gave incorrect results
around smoketests with simulator where each test run failed with an
error like "nosetests: error: no such option: --with-marvin".
We can merge this is Travis actually runs the tests and passes. See all recent travis test runs, they all silently fail.

travis: fail fast if --with-marvin fails with nose

---

api/src/main/java/com/cloud/agent/api/to/VirtualMachineTO.java
api/src/main/java/com/cloud/vm/DiskProfile.java
core/src/main/java/com/cloud/agent/api/MigrateCommand.java
engine/storage/datamotion/src/main/java/org/apache/cloudstack/storage/motion/KvmNonManagedStorageDataMotionStrategy.java
engine/storage/datamotion/src/main/java/org/apache/cloudstack/storage/motion/StorageSystemDataMotionStrategy.java
engine/storage/datamotion/src/main/resources/META-INF/cloudstack/storage/spring-engine-storage-datamotion-storage-context.xml
engine/storage/datamotion/src/test/java/org/apache/cloudstack/storage/motion/KvmNonManagedStorageSystemDataMotionTest.java
engine/storage/datamotion/src/test/java/org/apache/cloudstack/storage/motion/StorageSystemDataMotionStrategyTest.java
plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/MigrateKVMAsync.java
plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtCreateCommandWrapper.java
plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtMigrateCommandWrapper.java
plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/IscsiAdmStorageAdaptor.java
plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStoragePoolManager.java
plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java
plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtMigrateCommandWrapperTest.java
plugins/storage/volume/default/src/main/java/org/apache/cloudstack/storage/datastore/driver/CloudStackPrimaryDataStoreDriverImpl.java
server/src/main/java/com/cloud/hypervisor/HypervisorGuruBase.java

This PR proposes a new `DataMotionStrategy` `KvmNonManagedStorageDataMotionStrategy` that extends the `StorageSystemDataMotionStrategy`. This strategy allows migrating KVM VMs with the ROOT volume in  a primary local file system storage (volumes on path /var/lib/libvirt/images/).
This design also aims to ease the development of any non-managed KVM volume migration, such as the implementation of @nvazquez in PR #2983 (NFS to NFS).

Allow KVM VM live migration with ROOT volume on file storage type

---

api/src/main/java/org/apache/cloudstack/api/command/admin/network/CreateNetworkCmdByAdmin.java
engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
ui/l10n/en.js
ui/scripts/sharedFunctions.js

This PR adds the possibility to select a checkbox for the parameter _bypassvlanoverlapcheck_ to the ajax request [createNetwork](http://cloudstack.apache.org/api/apidocs-4.11/apis/createNetwork.html). The checkbox was added for _Guest Network_ as well as for the _L2 Guest Network_. For _L2 Guest Network_ a backend check for the existence of the flag _bypassvlanoverlapcheck_ was added.
- [x ] Enhancement (improves an existing feature and functionality)
New checkbox _L2 Guest Network_
New checkbox for _Guest Network_ 
Tested locally to verify the parameter _bypassVlanOverlapCheck_  was pushed to the ajax request [createNetwork](http://cloudstack.apache.org/api/apidocs-4.11/apis/createNetwork.html).

Enhance bypass vlan overlap check

---

server/src/main/java/com/cloud/network/element/VirtualRouterElement.java
server/src/test/java/com/cloud/network/element/VirtualRouterElementTest.java

There is no reason to not send userdata+password to the VR as all Instances in CloudStack are Dual-Stacked. They have IPv4 and IPv6 so they can query their metadata over IPv4 at the VR.
Tested on a local testing environment with IPv6 enabled.

ipv6: Send userdata to Virtual Router if IPv6 is enabled

---

test/integration/smoke/test_service_offerings.py
tools/marvin/marvin/config/test_data.py

Adds missing test data for test/integration/smoke/test_migration.py
This is fixed in Trillian codebase but not in cloudstack's test_data.py. Test run result:
```
=== TestName: test_01_native_to_native_network_migration | Status : SUCCESS ===
=== TestName: test_02_native_to_native_vpc_migration | Status : SUCCESS ===
===final results are now copied to: /tmp//MarvinLogs/test_migration_3B7NX2===
```

marvin: add missing test data for test_migration smoketest

---

server/src/main/java/com/cloud/api/dispatch/ParamProcessWorker.java

This is important because it helps in communicating back the exact
error to the API callee.
Current behavior is that ParamProcessWorker#processParameters catches
the exception and returns an incorrect type exception without the
proper message.
Use Cloudmonkey to call an API which has ApiArgValidator set for params. This does not return the proper exception message but sends an internal error occured with no information.

Throw InvalidParameterValueException for failing ApiArgValidator

---

engine/components-api/src/com/cloud/resource/ResourceManager.java
server/src/com/cloud/resource/ResourceManagerImpl.java
server/test/com/cloud/resource/MockResourceManagerImpl.java
server/test/com/cloud/resource/ResourceManagerImplTest.java

A corner case was found on 4.11.2 for #2493 leading to an infinite loop in state `PrepareForMaintenance`
To prevent such cases, in which failed migrations are detected but still running on the host, this feature adds a new cluster setting `host.maintenance.retries` which is the number of retries before marking the host as `ErrorInMaintenance` if migration errors persist.
- 2 KVM hosts, pick one which has running VMs as H
- Block migrations ports on H to simulate failures on migrations:
`
iptables -I OUTPUT -j REJECT -m state --state NEW -m tcp -p tcp --dport 49152:49215 -m comment --comment 'test block migrations'
iptables -I OUTPUT -j REJECT -m state --state NEW -m tcp -p tcp --dport 16509 -m comment --comment 'test block migrations
`
- Put host H in Maintenance
- Observe that host is …

Prevent corner case for infinite PrepareForMaintenance

---

api/src/main/java/org/apache/cloudstack/api/command/user/project/CreateProjectCmd.java

Create project command should have an Apiarg validator.
Fixes: #3097 
When create project is called with empty name or displaytext or both the call fails as it should.

Add api arg validator for create project api (#3097)

---

plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java
plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDefTest.java

The additional queues can enhance the performance of the VirtIO SCSI disk
and it is recommended to set this to the amount of vCPUs a Instance is assigned.
The optional queues attribute specifies the number of queues for the
controller. For best performance, it's recommended to specify a value matching
the number of vCPUs. Since 1.0.5 (QEMU and KVM only)
Source: https://libvirt.org/formatdomain.html#elementsVirtio
Tested on local Cloud and Unit Tests have been extended.

kvm: Set amount of queues for Virtio SCSI driver to vCPU of Instance

---

core/pom.xml
core/src/main/java/com/cloud/agent/api/HostStatsEntry.java
core/src/main/java/com/cloud/agent/api/VmStatsEntry.java
server/pom.xml
server/src/main/java/com/cloud/server/StatsCollector.java
server/src/test/java/com/cloud/server/StatsCollectorTest.java
utils/src/main/java/org/apache/cloudstack/utils/graphite/GraphiteClient.java

Add Support for InfluxDB on StatsCollector.
The collector is defined on the URI scheme. The _Global Settings_ configuration with the name `stats.output.uri` is used to set the URI to send StatsCollector statistics to.
Example: `graphite://graphite-hostaddress:port` or `influxdb://influxdb-hostaddress:port/dbname`. Note that the port is optional, if not added the default port for the respective collector (graphite or influxdb) will be used. Additionally, the database name `dbname` is also optional; default db name is `cloudstack`. Note that one must create and configure the database if using influxdb.
- Host stats
For the host metrics it creates an InfluxDB point with the measure `host_stats` and containing the following tags and fields:
Tags:
-- host_id
-- uuid
-- pod_id
-- data_center_id …

Add influxdb to statscollector

---

scripts/vm/network/vnet/modifyvxlan.sh

This PR refactors the modifyvxlan.sh script for VXLAN support on KVM Hypervisors.
Highlights:
- Only use iproute2 commands for all links, bridges and routes
- Use proper Bash syntax in script
- Add IPv6 underlay support
The script does not change existing functionality, running KVM hypervisors will keep functioning as they are doing right now.
This script hasn't been touched in 5 years (last commit in 2013) and needed some attention.
There are multiple commits in this PR to see how I got to the current code.
Tested on a local setup with CloudStack 4.12 (master) running.

kvm: Refactory VXLAN script and add IPv6 support

---

services/secondary-storage/server/src/main/java/org/apache/cloudstack/storage/resource/NfsSecondaryStorageResource.java

Im in process of rewriting the unit test for this class' mount method. Before I can do that, the class needed some refactoring, not just because it was fuzzy but because it was impossible to use mocks the way it was coded. Most of this PR is about transforming big chunks of code into documented methods with two exceptions:
1) I inverted the logic when checking for existing mounts within the same root location. Previously one would first create a directory if it didn't exist and then test if there was already mount there. Now it is first testing if there is a mount, if not, it creates the needed directory. (line 2376)
2) A bug was found in the unmount method. The unmount wasn't issuing the command "umount" to unmount a resource but instead was trying the "mount" command again, resulting in …

Remove unused "umount" method in NfsSecondaryStorageResource 

---

engine/schema/src/main/java/com/cloud/storage/dao/VMTemplateZoneDaoImpl.java

It's incorrect to use the findIncludingRemovedBy and
listIncludingRemovedBy for the common list and find operation. Moreover
the DAO is trying to update the `removed` attribute to null but will
failed (GenericDBaseDao.generateValue() will overwrite the null value
and set a new date.
Signed-off-by: Marc-Aurèle Brothier m@brothier.org

VMTemplateZone needs some love

---

engine/schema/src/main/java/com/cloud/offerings/NetworkOfferingVO.java

This PR attempts to fix various test failures on master:
1. Fixes #2935: This fixes the variable name to adhere to the DB framework convention
as defined by the method interceptor that creates attributes:
https://github.com/apache/cloudstack/blob/master/framework/db/src/main/java/com/cloud/utils/db/SearchBase.java#L480

Fix network GC error that's failing a smoketests on master

---

server/src/main/java/com/cloud/network/NetworkServiceImpl.java

This regression was introduced with PR #2773 (Support IPv6 address in addIpToNic). The contributor did not take into consideration that the method “addIpToNic” was designed to add/allocate other IPs to a NIC. If users did not specify an IP, ACS should generate one for the network where the NIC is plugged into.
Even though I am fixing this regression here, it is still important to highlight that for IPV6, the user is not able to allocate an IP without specifying it.
Locally

Fix “test_nic_secondaryip_add_remove” test

---

server/src/main/java/com/cloud/api/query/QueryManagerImpl.java

List resourcedetails was adding DB ID instead of UUID. This is a security risk and needs fix.
Fixes: #2527 
Manually added a resource detail for uservm and verified output has uuid and not db id.

Add resource UUID instead of resource id in resourcedetails api (#2527)

---

scripts/util/keystore-cert-import

This ensures that the systemvm agent (cloud.service) is not restarted
on certificate import. The agent has an inbuilt logic to attempt reconnection.
If the old certificates/keystore is invalid agent will attempt reconnection.
Deployed a CPU-bound environment (hypervisor host with limited CPU and 1core), saw that previously irrespective of keystore setup the restart logic would cause agent to restart (sig.kill is the reason seen in logs) and on management server side it would seem agent connects, then disconnects, then connects and is finally in `Up` state. With this fix, the reconnection attempt won't be observed on the management server side. The agent will keep attempting reconnection when certificates are invalid, the cert import script does not need to restart cloud service manually.

keystore: don't restart systemvm cloud.service post cert import

---

engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
server/src/main/java/com/cloud/network/IpAddressManagerImpl.java
server/src/main/java/com/cloud/network/Ipv6AddressManager.java
server/src/main/java/com/cloud/network/Ipv6AddressManagerImpl.java
server/src/main/java/com/cloud/network/guru/DirectNetworkGuru.java
server/src/test/java/com/cloud/network/Ipv6AddressManagerTest.java

With IPv6 we are not using DHCP to allocate addresses, but using
StateLess Address Auto Configuration (SLAAC) a Instance will calculate
it's own address based on the Router Advertisements send out by the
routers in the network.
This Advertisement contains the IPv6 Subnet in use in that subnet and
allows to calculate the stable Address the Instance will obtain based
on it's MAC Address.
The existing code is 'dead code' as it has been written, but was never
used by any production code.
SLAAC only works properly with subnets of exactly 64-bits large.
On a CloudStack test setup running from master (4.12) and trying manually.
The zone is running with Advanced Networking and Guest Networks have been provided a IPv6 64-bits subnet:
- Advanced Networking
- Shared VXLAN network
- Ubuntu 18.04 …

ipv6: Calculate IPv6 address instead of fetching one from a pool

---

server/src/main/java/com/cloud/network/Ipv6AddressManagerImpl.java
server/src/test/java/com/cloud/network/Ipv6AddressManagerTest.java
utils/src/main/java/com/cloud/utils/net/NetUtils.java
utils/src/test/java/com/cloud/utils/net/NetUtilsTest.java

When requesting a secondary IPv6 address the address specified by the requester should not be a EUI-64 (SLAAC) address.
This can be seen by looking at *ff:fe* which is always in the same position in a IPv6 address when using SLAAC/EUI-64.
<pre>2001:db8:13f:0:1c00:4aff:fe00:fe</pre>
That is an IPv6 EUI-64 address for example.
See: https://community.cisco.com/t5/networking-documents/understanding-ipv6-eui-64-bit-address/ta-p/3116953
Extended Unique Identifier (EUI), as per RFC2373, allows a host to assign iteslf a unique 64-Bit IP 
Version 6 interface identifier (EUI-64). This feature is a key benefit over IPv4 as it eliminates the need of manual configuration or DHCP as in the world of IPv4. The IPv6 EUI-64 format address is obtained 
through the 48-bit MAC address. The MAC address is …

ipv6: Do not allow Secondary IPv6 addresses to be EUI-64

---

plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtGetHostStatsCommandWrapper.java
plugins/hypervisors/kvm/src/main/java/org/apache/cloudstack/utils/linux/KVMHostInfo.java
plugins/hypervisors/kvm/src/main/java/org/apache/cloudstack/utils/linux/MemStat.java
plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java
plugins/hypervisors/kvm/src/test/java/org/apache/cloudstack/utils/linux/KVMHostInfoTest.java
plugins/hypervisors/kvm/src/test/java/org/apache/cloudstack/utils/linux/MemStatTest.java

The KVM Agent had two mechanisms for reporting its capabilities
and memory to the Management Server.
On startup it would ask libvirt the amount of Memory the Host has
and subtract and add the reserved and overcommit memory.
When the HostStats were however reported to the Management Server
these two configured values on the Agent were no longer reported
in the statistics thus showing all the available memory in the
Agent/Host to the Management Server.
This commit unifies this by using the same logic on Agent Startup
and during statistics reporting.
memory=3069636608, reservedMemory=1073741824
This was reported by a 4GB Hypervisor with this setting:
host.reserved.mem.mb=1024
The GUI (thus API) would then show:
Memory Total	2.86 GB
This way the Agent properly 'lies' to the Management Server …

kvm: Properly report available memory to Management Server

---

api/src/main/java/com/cloud/deploy/DeployDestination.java
engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
plugins/hypervisors/hyperv/src/main/java/com/cloud/hypervisor/hyperv/resource/HypervDirectConnectResource.java
plugins/hypervisors/ovm3/src/main/java/com/cloud/hypervisor/ovm3/resources/Ovm3HypervisorResource.java
server/src/main/java/com/cloud/api/ApiResponseHelper.java
server/src/main/java/com/cloud/api/ApiServer.java

LGTM has raised a number of alerts from analysis of apache/cloudstack (https://lgtm.com/projects/g/apache/cloudstack/alerts/?mode=tree).
This pull request is to fix some of the problems raised. Specifically,
- 2 `Array index out of bounds` errors in NetworkOrchestrator
- 1 `Equals method does not inspect argument type` in DeployDestination
- 1 `Equals on incomparable types` in ApiResponseHelper
- 28 `Contradictory type checks` in ApiServer, HypervDirectConnectResource and Ovm3HypervisorResource
- [ x] Enhancement (improves an existing feature and functionality)

Fix some LGTM alerts

---

client/conf/java.security.ciphers.in
packaging/systemd/cloudstack-management.default

This cleanups management server default file, the `cloud.jks` is no
longer created by the management server but instead created in-memory
by the root CA plugin on management server startup.

packaging: management default file cleanup

---

engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
server/src/main/java/com/cloud/network/guru/DirectNetworkGuru.java
server/src/test/java/com/cloud/network/guru/DirectNetworkGuruTest.java

Offerings can co-exist where on does provide Security Grouping in the
network, but other guest Networks have no Security Grouping.
In V(X)LAN isolation environments the L2 separation is handled by V(X)LAN
and protection between Instances is handled by Security Grouping.
There are multiple scenarios possible where one network has Security Grouping
enabled because that is required in that network.
In the other network, but in the same zone it could be a choice to have
Security Grouping disabled and allow all traffic to flow.
Tested on a Local KVM cloud where VXLAN isolation was being used.
Observed that VMs deployed in the first network have SG enabled and in a other network have it disabled.

network: Offerings do not have to have Security Grouping enabled

---

ui/scripts/configuration.js

Upgrade to jquery 3.3.1: $('selector').context was deprecated,
and has been removed. See: https://api.jquery.com/context/
Fixes: #3148

Fix UI bug: Create Network Offering Popup has no fields

---

ui/scripts/network.js
ui/scripts/sharedFunctions.js

Not possible to add secondary IPv4 or IPv6 address via UI. Having the following error:
```
TypeError: $.validator.methods[method] is undefined[Learn More] jquery.validate.js:777:6
check					http://<IP>:8080/client/lib/jquery.validate.js:777:6
element					http://<IP>:8080/client/lib/jquery.validate.js:492:10
onfocusout				http://<IP>:8080/client/lib/jquery.validate.js:300:5
delegate				http://<IP>:8080/client/lib/jquery.validate.js:423:6
dispatch				http://<IP>:8080/client/lib/jquery.js:5182:23
add/elemData.handler 	http://<IP>:8080/client/lib/jquery.js:4991:15
trigger 				http://<IP>:8080/client/lib/jquery.js:8249:11
simulate				http://<IP>:8080/client/lib/jquery.js:8318:7
handler					http://<IP>:8080/client/lib/jquery.js:8352:9
```
This was caused because of the ipv46address verification …

Fix issue with verification of ipv4/ipv6 address.

---

engine/api/src/org/apache/cloudstack/engine/subsystem/api/storage/SnapshotInfo.java
engine/storage/snapshot/src/org/apache/cloudstack/storage/snapshot/SnapshotObject.java
server/src/com/cloud/storage/snapshot/SnapshotManager.java
server/src/com/cloud/storage/snapshot/SnapshotManagerImpl.java

The snapshot.backup.rightafter configuration variable was removed by:
SHA: 6bb0ca2f854
This adds it back, though named snapshot.backup.to.secondary now instead.
This global parameter, once set, will allow you to prevent automatic backups of
snapshots to secondary storage, unless they're actually needed.
Fixes #3096
tested this in our 4.11 lab environment

Add back ability to disable backup of snapshot to secondary

---

engine/components-api/src/main/java/com/cloud/storage/StorageManager.java
engine/storage/datamotion/src/main/java/org/apache/cloudstack/storage/motion/AncientDataMotionStrategy.java
engine/storage/datamotion/src/main/java/org/apache/cloudstack/storage/motion/KvmNonManagedStorageDataMotionStrategy.java
engine/storage/datamotion/src/main/java/org/apache/cloudstack/storage/motion/StorageSystemDataMotionStrategy.java
engine/storage/datamotion/src/test/java/org/apache/cloudstack/storage/motion/KvmNonManagedStorageSystemDataMotionTest.java
plugins/storage/volume/default/src/main/java/org/apache/cloudstack/storage/datastore/driver/CloudStackPrimaryDataStoreDriverImpl.java
server/src/main/java/com/cloud/configuration/Config.java
server/src/main/java/com/cloud/storage/StorageManagerImpl.java

PR #2997 allowed KVM VM live migration with ROOT volume on local storage (filesystem), if the template is already on the target host, the migration will be successful; however, if the VM template is not on the target host the migration fails.
This PR fixes the bug introduced by #2997, copying the VM template to the target host if needed.
Additionally, table `template_spool_ref` is correctly updated with the template reference matching with the target storage pool.

Copy template to target KVM host if needed when migrating local <> local storage

---

plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtMigrateCommandWrapper.java
plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtMigrateCommandWrapperTest.java

When live migrating a KVM VM among local storages, the VM loses the
`<iotune> ... </iotune>` section on its XML, therefore, having no IO limitations.
```
<iotune>
<read_iops_sec>5000</read_iops_sec>
<write_iops_sec>5000</write_iops_sec>
</iotune>
```
This commit removes the piece of code that deletes the  `<iotune> ... </iotune>` section in the XML.
@rhtyd @mike-tutkowski @wido @DaanHoogland @nvazquez @kiwiflyer @rafaelweingartner do any of you guys know a reason for keeping the conditional that I removed? It looks like it can be removed without breaking anything.
**Bug:**
- Start a VM running on KVM, with local storage and service offering limiting the VM's IOPS;
- verify that the VM's XML file contains `<iotune> ... </iotune>`;
- live migrate to another host (with local storage);
- …

Keep iotune section in the VM's XML after live migration

---

packaging/systemd/cloudstack-usage.default
packaging/systemd/cloudstack-usage.service
usage/src/com/cloud/usage/UsageServer.java

This fixes regression introduced by refactoring PR #3163 where `-Dpid`
was incorrectly passed string `$$` instead of parent PID integer.
Fixes #3203

systemd: Fix -Dpid arg passing to systemd usage service

---

server/src/com/cloud/network/NetworkServiceImpl.java
ui/scripts/network.js
ui/scripts/sharedFunctions.js

Allow users of all types to create L2 guest networks
Also fixes #3081 
API

Allow users of all types to create L2 networks

---

server/src/main/java/com/cloud/hypervisor/KVMGuru.java

This references and uses an already fixed solution from
https://github.com/MissionCriticalCloud/cosmic/pull/68 to make
snapshotting on KVM non-blocking.

server: make snapshotting on KVM non-blocking

---

plugins/hypervisors/kvm/src/main/java/org/apache/cloudstack/utils/qemu/QemuImg.java

NotImplementedException from sun.reflect.generics.reflectiveObjects is not standard/guarateed by the jvm so a custom implementation is in order.

NotImplemented as a local exception

---

debian/control

Fixes jsvc/commons-daemon dependency not handled in forward merge of https://github.com/apache/cloudstack/pull/3163

debian: cleanup commons-daemon no longer needed by agent

---

ui/scripts/ui/widgets/listView.js

**How to reproduce:**
1. Select one entry in a multiSelect listView (e.g. instance list) and then deselect it again. Now click on the "select all" checkbox. The entries which were clicked previously are not displayed as selected.
2. Select at least one entry. Use the multiSelectAction buttons to trigger an action. Wait for completion. The list refreshes and no entry is selected but the multiSelectAction buttons are displayed.
**Fix:**
1. Use "checked" property instead of the attribute to select all entries. This is necessary because when you checked an entry by clicking on it the property gets set and the browser is preferably using this. So setting the attribute by clicking on the "select all" checkbox had no impact anymore on the checkBox of the previously clicked entries. 
2. Hide the …

Fix behavior of multiselect in list view

---

client/conf/java.security.ciphers.in

This fixes the issue that TLSv1 and TLSv1.1 are still used by CloudStack
management server to communicate with VMware vCenter server. With the
current defaults, the setup/deployment on VMware fails. Users/admins
can however setup the security file according to their env needs to
disable TLSv1 and TLSv1.1 for server sockets (8250/agent service for
example).

client: don't disable TLSv1, TLSv1.1 by default that breaks VMware env

---

tools/apidoc/build-apidoc.sh
tools/apidoc/generatecommands.xsl
tools/apidoc/generatetoc_header.xsl
tools/apidoc/pom.xml

Currently, the API documentation is hardcoded to _v4.9.0_. This commit makes the API documentation automatically updated to the current project version. If one wants to set another version, it is possible by just editing the `ACS_RELEASE` variable in _build-apidoc.sh_.
Prior to the changes proposed in this PR the generated API documentaion was labeled as '4.9.0':
Project API documentation page:
Example of an API command documentation page:

Make the API documentation version not *hardcoded* to v4.9.0

---

ui/scripts/instances.js

**Problem**: When reinstalling a VM, the UI only shows featured templates and not all possible list of allowed templates.
**Root Cause**: The list of templates for reinstall used `featured` as filter in ‘listTemplates’ API which did not include all available options.
**Solution**: The issue is fixed by using the `executable` template filter of the ‘listTemplates’ API to list all
possible templates that a user is allowed to use to deploy a VM.

ui: use executable template filter for users

---

server/src/main/java/com/cloud/server/StatsCollector.java

The issue was that an Incorrect iscsi path was being passed for managed storage pools when collecting volume stats. Storage pools normally have a UUID based path while managed storage pools require an IQN based path

fix incorrect iscsi path stat for managed storage

---

utils/src/main/java/com/cloud/utils/UriUtils.java

Fixes #2802
Allows URLs with ports other than 80 and 443.
As mentioned in the issue, user might be using a port for other than 80 and 443 for the server for registering template. Current changes simply removes port checking for URLs to facilitate using servers with a different port number.

utils: removed port check for url validation (#2802)

---

server/src/main/java/com/cloud/vm/snapshot/VMSnapshotManagerImpl.java
ui/scripts/storage.js

Fixes #3208 
Using db column instead of VO variable name was causing issue with SQL select statement.
This PR fixes the problem by using VO variable for adding conditional.
Additionally in UI **listAll** parameter was being sent twice in the listVMSnapshot API call. It is fixed with this PR.
Original behavior giving error,
With changes,
From UI and cmk

server: fix for vm snapshot search (#3208)

---

packaging/centos7/cloud.spec

This runs systemctl daemon-reload after cloudstack-agent is installed
or upgraded. This fixes a warning seen in el7 environments which asks
admin to perform `daemon-reload` after agent is installed or upgraded.

packaging: systemctl daemon-reload after agent install or upgrade

---

ui/scripts/templates.js

Problem: When uploading template or iso in a project, the progress is not seen
Root Cause: When users upload a template/iso in project view, the template/iso is not visible in the all filter. This creates confusion that template/iso has not been uploaded.
Solution: Since the api listtemplates with a projectid acts is a superset of list templates without a project id, we should not ignore the project id when listing templates in all filter.

ui: don't ignore ''mine" when listing "all" templates in projects

---

engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/vmsnapshot/DefaultVMSnapshotStrategy.java

**Problem**: Users are billed for destroyed VMs with VM snapshots because usage records don't get that the VM and VM snapshots are removed.
**Root Cause**: The destroyVirtualMachine and expungeVirtualMachine APIs were removing VM snapshots but not generating VMSNAPSHOT.DELETE usage event due to which the VM snapshots were not marked as removed in the usage_vmsnapshot table.
**Solution**: The issue was fixed by emitting the proper usage event for all the VM snapshots of a VM that is destroyed.

 storage: publish delete usage event for snapshot deletion

---

api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
api/src/main/java/org/apache/cloudstack/api/response/AccountResponse.java
server/src/main/java/com/cloud/api/query/dao/AccountJoinDaoImpl.java
ui/scripts/accounts.js

Fixes #2994 
This PR allows showing complete domain, ie, domain path for accounts list view and account detail.
Added a new key, domainpath, in AccountResponse for accounts API to facilitate this in UI.
Original behavior  in UI
After changes,
UI and cmk

ui: show complete domain for accounts (#2994)

---

ui/css/cloudstack3.css

**Problem**: Down arrow key of the vertical scroll bar in the VM deployment wizard does not work.
**Root Cause**: The computer diagram on the right side in the VM deployment wizard spills its margin on the left causing the arrow key to be blocked.
**Solution**: Fix the `background-position` to get the correct position than `margin-left` for the `zone-panel`. With the fix, the left size arrow keys and vertical scrollbars are no longer under the diagram image and press-able now.
Before the fix, as seen from dev tools:
The layout as seen in dev tools after the fix:

ui: fix computer diagram css margin that blocks down arrow

---

ui/css/cloudstack3.css
ui/index.html
ui/lib/jquery-ui/css/jquery-ui.css
ui/scripts/configuration.js
ui/scripts/roles.js
ui/scripts/system.js
ui/scripts/ui-custom/instanceWizard.js
ui/scripts/ui/widgets/toolTip.js
ui/scripts/vpc.js
ui/scripts/zoneWizard.js

Fixed issues occurring with [this PR](https://github.com/apache/cloudstack/pull/3069)
Added jQuery ui CSS to the project and adapt existing stylings
Removed unnecessary styling definitions from cloudstack.css
Swap no longer recommended jQuery method
We deployed the changes to our test environment and tested the UI functionality by clicking through the affected views

Improvements after jquery update

---

engine/schema/src/com/cloud/configuration/dao/ResourceCountDaoImpl.java

While update resource count of a domain, I got the following exception which should not happen
2019-03-05 08:23:43,656 DEBUG [c.c.u.d.T.Transaction] (qtp858242339-15:ctx-13652208 ctx-56fe3704) (logid:130b0537) Rolling back the transaction: Time = 10 Name =  qtp858242339-15; called by -TransactionLegacy.rollback:890-TransactionLegacy.removeUpTo:833-TransactionLegacy.close:657-TransactionContextInterceptor.invoke:36-ReflectiveMethodInvocation.proceed:174-ExposeInvocationInterceptor.invoke:92-ReflectiveMethodInvocation.proceed:185-JdkDynamicAopProxy.invoke:212-$Proxy42.countCpuNumberAllocatedToAccount:-1-ResourceLimitManagerImpl.countCpusForAccount:950-ResourceLimitManagerImpl.recalculateAccountResourceCount:910-ResourceLimitManagerImpl$3.doInTransaction:872

server: Fix exception while update domain resource count

---

server/src/main/java/com/cloud/storage/StorageManagerImpl.java

Fixes #2689 
With the current code, existing templates were not downloaded to the new secondary storage when it is added. SSVM needed to be restarted to start the download process. This PR starts templates sync for the new secondary storage when it is added.
Using KVM based monkeybox environment. New secondary storage was added and template download was verified by listing files for the storage.

server: sync templates on adding new secondary storage

---

plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
python/lib/cloudutils/networkConfig.py
python/lib/cloudutils/serviceConfig.py

This fixes three issues with ubuntu 16.04 hosts
1. fix unable to add host if cloudbrX is not configured
2. Stop service libvirt-bin.socket while add a host
3. Diable libvirt default network
Details can be found in each commit.

ubuntu16:  fix three issues with ubuntu 16.04 hosts

---

api/src/main/java/org/apache/cloudstack/api/response/VMSnapshotResponse.java
server/src/main/java/com/cloud/api/ApiResponseHelper.java

**Problem**: Tags of VM snapshots are not returned as part of the listVMSnapshots API and therefore was not shown in the UI.
**Root Cause**: The API response creator was not setting the tags in the API response.
**Solution**: The issue was fixed to return tags of a VM snapshot as part of the listVMSnapshots API response and now it is possible to list/add/remove tags using the UI. The tags are also included for VMSnapshot usage records in the listUsageRecords API response when `includetags=true` parameter is passed.

api: include tags in listvmsnapshots response

---

api/src/main/java/org/apache/cloudstack/query/QueryService.java
server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
server/src/main/java/com/cloud/api/query/dao/UserVmJoinDaoImpl.java

**Problem**: The listVirtualMachines API response displays sensitive information which should not be visible to any other user which is not Root Admin.
**Root Cause**: There are currently no restrictions in place to control what
instance settings should be visible to Root Admin only.
**Solution**: The issue has been fixed by refactoring the response to filter details based on a global setting and also honour the cloud.user_vm_details table’s display field. The global setting used to hide details that Root admin can set is called `user.vm.blacklisted.details` with the following defaults;
• memoryOvercommitRatio
• cpuOvercommitRatio
• rootdisksize
• Message.ReservedCapacityFreed.Flag

server: allow admins to blacklist vm details that users should not see

---

ui/index.html

3 years ago when we moved from JSP this translate was not wrapped in label tags and consequently the following span wasn't captured when dashboard.js mapped the data.
Fixes: #3314
Through UI

Bug fix for zone names not appearing in dashboard

---

ui/index.html
ui/scripts/instanceWizard.js

In the cloudstack UI fields get '<', '>' and '&' replaced by xml-entities
these are generic for all fields and hurt us in the case of userdata
this fix calls the existing method to reverse character replacements.
it also removes the ccs class that pretends to prevent special chars
Fixes: #3202
This has been tested by creating VMs in the simulator and checking the user_vm.user_data field contents

base64 userdata encoding fix

---

plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/manager/VmwareStorageManagerImpl.java
plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageProcessor.java

**Problem**: A VM fails to start, which has a VM snapshot after performing the extractVolume operation on the stopped VM.
**Root Cause**: While downloading a volume of a stopped VM, it creates a worker VM with the volume attached and it creates a temporary snapshot, and then it creates another worker VM cloned from that snapshot and exports an OVA file and deletes the cloned worker VM. Afterward, it deletes the initial worker VM and the temporary snapshot which merges any previous snapshot(s) to the main disk. So, while starting the VM, VMware is not able to find the snapshot disk.
**Solution**: Export the volume using a single worker VM (when VM is stopped) without creating a temporary snapshot.
**Upgrade Notes**: After the upgrade, the admin should replace the live systemvm ISO file in …

vmware: don't use redundant worker VM to extract volume

---

server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java

When creating a new compute offering over the ui, the isCustomIops parameter is null.
In this case the minIops and maxIops values of the offering gets set to 0 instead of null and when trying to change an instance to this offering an error occurs.
This was introduced in this PR https://github.com/apache/cloudstack/pull/3133/files.
I already opened an issue regarding this. (https://github.com/apache/cloudstack/issues/3332)
The marked fields were set to 0 before.
This to screenshots represent the problem.
Deployed to local environment and tested functionality.

Fix iops values when creating a compute offering

---

agent/src/com/cloud/agent/Agent.java
engine/components-api/src/com/cloud/resource/ResourceManager.java
engine/orchestration/src/com/cloud/agent/manager/AgentAttache.java
server/src/com/cloud/configuration/Config.java
server/src/com/cloud/resource/ResourceManagerImpl.java
server/test/com/cloud/resource/ResourceManagerImplTest.java
test/integration/smoke/test_host_maintenance.py

Before this fix, there were two possible scenarios when cancelling maintenance/prepare for maintenance on a KVM host:
- If global setting 'kvm.ssh.to.agent' = true, then the management server performed SSH into the host and restarted the CloudStack agent service.
- If global setting 'kvm.ssh.to.agent' = false, then the management server required that the CloudStack agent service on the host was restarted manually, for the host to become operational again. Restart was to establish a new connection between management server and the host agent, as it was closed after the host is notified to be put into maintenance
After cancelling maintenance on one-time SSH password hosts, hosts did not reconnect and were not operational unless a manual restart on the CloudStack agent service was performed. …

KVM: Fix agents dont reconnect post maintenance

---

packaging/centos7/cloud.spec

* small fix. correct the permissions on cloudstack-agent logrotate file (/etc/logrotate.d/).
tested in our prod environment

Fix correct permissions cloudstack-agent logrotate file for CentOS

---

api/src/main/java/org/apache/cloudstack/api/response/UserVmResponse.java
api/src/main/java/org/apache/cloudstack/query/QueryService.java
server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
server/src/main/java/com/cloud/api/query/dao/UserVmJoinDaoImpl.java
ui/css/cloudstack3.css
ui/l10n/en.js
ui/scripts/instances.js

**Problem**: Instance settings tab is visible only for stopped VMs but hidden otherwise. This creates confusion as users may not know that VMs need to be stopped to access settings page. Some VM details need to be read-only for the user.
**Root Cause**: The UI Code hides the settings tab for VMs that are not in stopped state. Instance setting tab should always be visible, but only changeable when VM is stopped. Required instance details are not read-only for the user.
**Solution**: The settings tab is now always visible for VMs. If VM is not in the stopped state, no interactions are allowed in the settings tab view by greying out its content and a popup is shown to advise users for stopping the VM. VM details can be made read-only in UI for the user using “user.vm.readonly.ui.details” …

[WIP DO NOT MERGE] ui: instance settings visibility

---

ui/scripts/ui/widgets/dataTable.js

This fixes the sorting of ip addresses and ip cidrs.
Currently they get evaluated as a numeric value via parseFloat and sorted as numeric values.
For example "10.32.123.123" got parsed to 10.32.  
Deployed this to our test environment and tested functionality.

Fix ip and ip cidr column sorting in tables

---

engine/storage/datamotion/src/main/java/org/apache/cloudstack/storage/motion/KvmNonManagedStorageDataMotionStrategy.java
engine/storage/datamotion/src/main/java/org/apache/cloudstack/storage/motion/StorageSystemDataMotionStrategy.java
engine/storage/datamotion/src/test/java/org/apache/cloudstack/storage/motion/KvmNonManagedStorageSystemDataMotionTest.java
engine/storage/datamotion/src/test/java/org/apache/cloudstack/storage/motion/StorageSystemDataMotionStrategyTest.java

This commit simplifies the `generateDestPath` method and fixes an issue where an extra file, named as '_null_', was created on the target storage pool during VM local storage volume migration. Without this fix, the VM is migrated and there is no data loss; however, 193 KB is allocated for the unused file named as '_null_' and the file stays on the target storage.

Remove code that generated /var/lib/libvirt/images/null on target host

---

server/src/main/java/com/cloud/vm/UserVmManagerImpl.java

Fixes #3315
Currently, the code was allowed to change service offering for VM to a deleted or inactive service offering. Added check for it to throw an exception.
Using cmk

server: fix for inactive service offering for VM

---

plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java
plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDefTest.java

When I use SandyBridge as custom cpu in my testing, vm failed to start due to following error:
```
org.libvirt.LibvirtException: unsupported configuration: guest and host CPU are not compatible: Host CPU does not provide required features: avx, xsave, aes, tsc-deadline, x2apic, pclmuldq
```
With this patch, it works with the following setting in agent.properties:
```
guest.cpu.mode=custom
guest.cpu.model=SandyBridge
guest.cpu.features=-avx -xsave -aes -tsc-deadline -x2apic -pclmuldq
```
vm cpu is defined as below:
```
<cpu mode='custom' match='exact'>
<model fallback='allow'>SandyBridge</model>
<feature policy='disable' name='avx'/>
<feature policy='disable' name='xsave'/>
<feature policy='disable' name='aes'/>
<feature policy='disable' name='tsc-deadline'/>
<feature policy='disable' …
```

kvm: disable cpu features if feature starts with '-'

---

server/src/main/java/com/cloud/tags/TaggedResourceManagerImpl.java

Fixed issue where a user cannot tag a project.
To reproduce:
in the UI:
log in as a user type
create a project
tag the new created project
Fixes: #2823
Tested from UI.
Created a new project, and tagged the project, no errors.
Tested with cloudmonkey
Tested under Ubuntu server 18.04.2 LTS using the simulator

User allowed to tag project created by him

---

plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java
ui/scripts/metrics.js

**Problem**: The metrics view for instances does not show used memory.
**Root Cause**: Used memory was not added as a column in the metrics view for instances.
**Solution**: Metrics view for instances makes ‘listVirtualMachineMetrics’ API call to gather metrics. The response of this API call contains total and free memory with the instance. These have been used to compute used memory as a percentage of total memory and displayed as a new column in UI. Also fixes
a bug for VMware, due to which incorrect memory usage was returned.

[WIP DO NOT MERGE] ui: add memory used column in instance metrics view

---

server/src/com/cloud/tags/TaggedResourceManagerImpl.java
test/integration/component/test_tags.py

see #3339: a runtime exception is thrown but it should be converted to an error return. Wrapping it in a CloudRuntimeException should do the trick.
Fixes: #3339
by ui
also a marvin test was added in component test test_tags.py

fix duplicate tag exception as CloudRuntimeException

---

server/src/com/cloud/network/router/VpcNetworkHelperImpl.java

If there are multiple IPs in different subnet assigned to a VPC, after restarting VPC with cleanup, the VRs will be FAULT state.
Step to reproduce:
(1) create vpc, source nat IP is 10.11.118.X
(2) assign two public IPs in other subnet to this VPC. 10.11.119.X and 10.11.119.Y
(3) deploy two vms in the vpc, and enable static nat 10.11.119.X and 10.11.119.Y to these two vms
(4) restart vpc with cleanup. There are more than 1 nic allocated for 10.11.119 to new VRs
Logs as below:
2019-05-10 14:12:24,652 DEBUG [o.a.c.e.o.NetworkOrchestrator] (API-Job-Executor-36:ctx-839f6522 job-652 ctx-35fb4667) (logid:1ab7aa37) Allocating nic for vm VM[DomainRouter|r-85-VM] in network Ntwk[200|Public|1] with requested profile NicProfile[0-0-null-10.11.118.157-vlan://untagged
2019-05-10 14:12:24,676 DEBUG …

VPC: Fail to restart VPC with cleanup if there are multiple public IPs in different subnets

---

ui/scripts/ui/widgets/listView.js

Enables the toolbar to reset to its initial state after any multiSelectAction completed.
Fixes: https://github.com/apache/cloudstack/issues/3337
Open Instances 
Select any instance, on the toolbar Take VM Snapshot, Destroy Instance, Stop Instance  buttons will be visible.
Follow operation path for any of these buttons.
Listview and toolbar will reset to its initial state.

Ui: Reset multiselect actions when refreshing listView in Instance page

---

ui/scripts/network.js
ui/scripts/vpc.js

When enable static nat in a vpc on UI, it only lists the primary and secondary ips of first nic of a vm, no matter which vpc tier is selected. 
The same issue happens when add a vm to load balancer.
Fixes: #3334

ui: fix enable static nat only towards first nic and not on any other interface

---

ui/config.js
ui/index.html
ui/l10n/en.js
ui/scripts/cloudStack.js
ui/scripts/postLoad.js
ui/scripts/templates.js
ui/scripts/ui/core.js
ui/scripts/ui/widgets/listView.js

We want to support hiding table columns, specifically in metrics table, through config file so that users can make the relevant bits hidden as per their organization. Current work will support the metrics table but can be extended to any table with minimal work in future.
Config file will take the key of the metrics column from metrics.js file for the sake of minimal changes and simplicity of development.
**Problem**: The keyboard list in the UI is not consistent across views such as in the instance wizard and in the register template form. There is also no way to custom about url/text and doc title and help URL in the UI.
**Root Cause**: The list is hardcoded in the UI allowing no centralised configuration.
**Solution**: Introduce a new `config.js` file installed at the …

Configurable UI branding, keyboard list and hide-able columns through a new config.js file

---

plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/guru/VMwareGuru.java

we do NOT always reserve VMware CPU/RAM resources - only when "vmware.reserve.cpu" or "vmware.reserve.mem" setting is set to TRUE - AND we do so, irelevant if overprovisioning is active or not. Verified for both system VMs and user VMs.
CPU and RAM overprovisioning was active (set to 2.0), while vmware.reserve.cpu and vmware.reserve.mem was set to TRUE or FALSE and the end result was observed in vCenter (6.5).
The same test repeated, with CPU and RAM overprovisioning set to 1.0 (no overprovisioning).

Update vmware reservations description

---

server/src/main/java/com/cloud/storage/ImageStoreUploadMonitorImpl.java

Increase POST timeout for local template upload

---

vmware-base/src/com/cloud/hypervisor/vmware/mo/VirtualMachineMO.java

This fixes potential NPE case when memory hotpluggability is checked
based on the guest OS descriptor.
Fixes #3230 NPE case.

vmware: fix potential NPE when memory hotplug capability is checked

---

server/src/com/cloud/vm/UserVmManagerImpl.java

In virtual routers, there are different dnsmasq settings for default nic and non-default nic on vm.
We need to update dhcp informations on network vrs when default nic is changed.
For example, if 172.16.1.135 is non-default nic of vm VPC1-001-001, then
root@r-22-VM:~# cat /etc/dhcphosts.txt
02:00:1d:15:00:05,set:172_16_1_135,172.16.1.135,VPC1-001-001,710h
root@r-22-VM:~# cat /etc/dhcpopts.txt
172_16_1_135,3
172_16_1_135,6
172_16_1_135,15
If it is default nic,then
root@r-22-VM:~# cat /etc/dhcpopts.txt
root@r-22-VM:~# cat /etc/dhcphosts.txt
02:00:1d:15:00:05,172.16.1.135,VPC1-001-001,757h
Fixes: #3201

server: update dhcp configurations in vrs while update default nic of running vms

---

server/src/com/cloud/configuration/ConfigurationManagerImpl.java

when we dedicate public ip range to a domain but some ips are used by an account in the domain,
the operation should be allowed but actually fails for now.
It is because cloudstack check if ips are used by same account by account name,
However, accountName is null when dedicate public ip range to a domain.
Modify the code to check account id only when dedicate ip range to account.

server: allow dedicate ip range to a domain if ips are used by an account in the domain

---

systemvm/debian/opt/cloud/bin/configure.py
systemvm/debian/opt/cloud/bin/cs/CsAddress.py
systemvm/debian/opt/cloud/bin/cs/CsRedundant.py

This PR resolves 2 issues related to Virtual Routers with multiple public interfaces, and works around a third.
1. Fixes: #3353 - Adds missing throw routes for eth0/eth1 to eth3+ when there are >1 public IPs 
2. Fixes: #3168 - Incorrect marks set on some static NAT rules (some code references were changed from `hex(int(interfacenum))` to `hex(100 + int(interfacenum))` - this change just adds the remaining ones
3. Works around #3352 - Sends Gratuitous ARP messages when a HA VR becomes master to work around the problem of the MAC address being different between HA VRs.  If that issue is fixed properly (i.e. a database entry for the subsequent interfaces so they can be static) then this is unnecessary, though should not cause any problems.
These changes form part of the ISO we are deploying …

Fix 4.11 VR Issues with Multiple Public Subnets

---

api/src/main/java/org/apache/cloudstack/api/command/user/address/ListPublicIpAddressesCmd.java
server/src/main/java/com/cloud/server/ManagementServerImpl.java

Fixes #3295 
listPublicIPAddresses API was missing **networkid** parameter and it has been used in UI to list public IP addresses while changing IP address for a VM.
_networkid_ parameter is added to listPublicIPAddresses API which would allow filtering public IP addresses based on the source network. This will help to show relevant IP addresses when users try to change assigned IP address for a VM NIC.
UI and cmk

[WIP DO NOT MERGE] server: fix public IP addresses filtering

---

plugins/network-elements/juniper-srx/src/com/cloud/network/resource/JuniperSrxResource.java

Fixed the logic for deleting static NAT rules on a Juniper SRX device.  Previously the private (trust) rule was not being removed.
Fixes: #3309 
Attached an SRX device to a simulator instance with unfixed code
Create Static NAT rule, verify that rules are added into SRX Config
Remove Static NAT rule, verify that private rule not removed
Apply fixed code
Create Static NAT rule, verify that both rules are present
Remove Static NAT rule, verify that both rules are removed

Fix removing static NAT rules with Juniper SRX

---

services/secondary-storage/server/src/org/apache/cloudstack/storage/resource/NfsSecondaryStorageResource.java

If mtu= value is defined in the parameters received by the SSVM agent
per the secstorage.vm.mtu.size setting, it applies the MTU setting on
eth1 which is the storage/management nic.
Fixes #3369

ssvm: apply MTU value on storage/management nic if available

---

systemvm/debian/opt/cloud/bin/configure.py

The VR code has provision for inserting rules at the top or bottom by specifying "front" as the second parameter to `self.fw.append`.  However, there are a number of cases where someone has been unaware of this and added a rule with the pattern `self.fw.append(["mangle", "", "-I PREROUTING"...`.  This causes the code to check for the rule already being present to fail, and duplicate rules end up being added.
This PR fixes two of these cases which apply to adding static NAT rules.  I am aware of more of these cases, but I don't have the ability to easily test the outcome of fixing them.  I'm happy to add these in if you're confident that the automated tests will be sufficient.  Searching for "-I (case sensitive) finds these.
The [code for dealing with …

Fix rule duplication with static NAT rules

---

server/src/com/cloud/network/element/VirtualRouterElement.java
systemvm/debian/opt/cloud/bin/cs/CsDhcp.py
systemvm/debian/opt/cloud/bin/cs_dhcp.py

This does not remove VM entries in dbags when hostnames match. The
current codebase already removes entry when a VM is stopped/removed so
we don't need to handle lazy removal. This will allow a VM on
multiple-tiers in a VPC to get dns/dhcp rules as expected.
This also fixes the issue of dhcp_release based on a specific interface.
Fixes #3273

router: support multi-homed VMs in VPC

---

client/conf/ehcache.xml.in
engine/schema/src/main/resources/META-INF/cloudstack/core/spring-engine-schema-core-daos-context.xml

This PR is for deactivating Ehcache in CloudStack since it is not usable. The first commit remove the default RMI cache peering configured for multicast which most of the time cannot work. It also requires to have an interface up which is not always the case while developing offline.
The second commits remove the configuration to activate caching on some DAOs.
The code in CS does not seem to fit any caching mechanism especially due to the homemade DAO code. The main 3 flaws are the following:
There is quite a lot of code with method calls passing entity IDs value as `long`, which does some object fetching. Without caching, this behavior will create distinct objects each time an entity with the same ID is fetched. With the cache enabled, the same object will be shared among those methods. …

Deactivate ehcache

---

ui/scripts/templates.js

Upload template form was missing some hypervisor specific options which can be seen on Register template form.
For XenServer, XenServer tool version added
For VMware, Root disk controller, NIC adapter type, Keyboard type added and HVM is hidden
For KVM, Root disk controller added
Fixes #3363

ui: added missing hypervisor options for upload template

---

engine/api/src/main/java/org/apache/cloudstack/engine/subsystem/api/storage/TemplateService.java
engine/storage/image/src/main/java/org/apache/cloudstack/storage/image/TemplateServiceImpl.java
engine/storage/src/main/java/org/apache/cloudstack/storage/datastore/ObjectInDataStoreManagerImpl.java
server/src/main/java/com/cloud/storage/ImageStoreUploadMonitorImpl.java

**Problem**: When a multi-disk OVA template is uploaded, only the root disk is recognized and VMs deployed using such template only get the root disk provisioned.
**Root Cause**: The template processor for multi-disk OVA was not used in the template upload processor.
**Solution**: Added support for local multi-disk OVA template upload. After a multi-disk OVA template is
uploaded, the mechanism that worked on multi-disk OVA templates registered using URL is now also used to discovers and creates data-disk templates in `cloud.vm_template` table and on the secondary storage.
To enable SSL on SSVMs :
• Upload the certificates like you usually do via the API or UI->Infrastructure tab
• Set the global settings secstorage.encrypt.copy, secstorage.ssl.cert.domain to appropriate values
along with …

[WIP DO NOT MERGE] storage: post process locally uploaded multi-disk ova template

---

systemvm/agent/js/ajaxviewer.js

On VMware Zone, hitting CTRL over Console Proxy will send a mask of Meta key as well. This makes Ctrl+A, Ctrl+E and many functionalities to not work in console.
Read https://github.com/apache/cloudstack/issues/3229 for details
For fixing ignore Meta key flag passed by SDK if Control was pressed. The Jquery implementation sets the meta key to control key to support IE browser.
Fixes #3229 
Tested the change on KVM, VMWare on Ubuntu based Chrome and MacBook based Chrome. Fix solves the problem.

Console Proxy: Ignore META key mask if control was pressed

---

server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
server/src/test/java/com/cloud/storage/VolumeApiServiceImplTest.java

The code prior to this commit was looking for the storage tags at the table `storage_pool_details`, which is empty. It should select from `storage_pool_tags`, which contains the tags from each tagged storage.
Migrated a volume with a tag 'A' to a storage pool that also has the tag 'A'. Resulted on the following exception:
```
2019-05-10 17:03:16,343 ERROR [c.c.a.ApiAsyncJobDispatcher] (API-Job-Executor-9:ctx-1255172b job-16095) (logid:3f7e0f22) Unexpected exception while executing org.apache.cloudstack.api.command.admin.volume.MigrateVolumeCmdByAdmin
com.cloud.utils.exception.CloudRuntimeException: Migration target has no matching tags for volume 'ROOT-2086(262d639d-a0b0-4f8d-9e86-01fb210ace8f)'
at com.cloud.storage.VolumeApiServiceImpl.migrateVolume(VolumeApiServiceImpl.java:2086)
at …
```

Fix: Migration target has no matching tags

---

server/src/main/java/com/cloud/api/query/dao/DomainRouterJoinDaoImpl.java

Add missing scriptsversion field to list router api call response.
Fixes: #3357
Cloudmonkey -
(local) 🐵 > list routers filter=id,name,scriptsversion
{
"count": 1,
"router": [
{
"id": "9f14131f-af82-43f0-8f08-dd15af9835e8",
"name": "r-4-VM",
"scriptsversion": "fde18f0829de6a9aef99f8bf1700b6c0\n"
}
]
}

Add to listRouters response the scriptsversion

---

ui/scripts/ui/widgets/listView.js

Fixed an issue, where the quick view tooltip title would not have been displayed properly on list views with a multiselect row.
This was because the html content of the first `td` of a row was used to render the title of the quick view tooltip, which would not work if the first columns content was a checkbox.
Now the `td` with class `first` will be used for this (this will be the second column if there is a multiselect column, otherwise it will remain the first column).
Before
After
Deployed to local environment and tested functionality.

ui: Fix quick view tooltip title on multiselect list views

---

ui/scripts/configuration.js

Fixes #2741 
Quickview widget for disk offerings list in the UI was missing offering details and action items. `cloudStack.listDiskOfferings` method call for the details view data provider was not working, therefore, it has been replaced with direct ajax API call.
Existing UI behaviour:
After changes:
UI

ui: fix for disk offering quickview details, actions

---

agent/bindir/libvirtqemuhook.in

This fixes the qemu hooks `mkdir` race condition which can happen when
too many VMs may launch on a KVM host executing the hooks script that
tries to `mkdir` for the custom directory. On exception (multiple scripts
trying to mkdir), the VM stops. When libvirtd restarts it triggers hooks, and
the issue can be reproduced, which can cause loss of running VMs. 
The custom directory need not be created if it does not exist, instead
the custom hooks should only execute when there is a custom directory.
Admins who want to use the custom scripts feature can create the directory
as per the feature documentation. 
Feature documentation:
http://docs.cloudstack.apache.org/en/4.11.2.0/adminguide/hosts.html#kvm-libvirt-hook-script-include

kvm: fix qemu hook race condition

---

ui/css/cloudstack3.css
ui/css/src/scss/components/quick-view-tooltip.scss

Fixed the styling of the quick view tooltip loading overlay. Before it would have a top offset to the quick view tooltip and stick out of the tooltip. Afterwards it just overlays the tooltip.
Before:
After:
Deployed to local environment and tested functionality.

Fix quick view tooltip loading overlay offset

---

api/src/main/java/com/cloud/network/Network.java
api/src/main/java/com/cloud/network/NetworkService.java
api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
api/src/main/java/org/apache/cloudstack/api/command/admin/network/CreateNetworkCmdByAdmin.java
api/src/main/java/org/apache/cloudstack/api/command/admin/network/UpdateNetworkCmdByAdmin.java
api/src/main/java/org/apache/cloudstack/api/command/admin/usage/ListUsageRecordsCmd.java
api/src/main/java/org/apache/cloudstack/api/command/user/network/UpdateNetworkCmd.java
api/src/main/java/org/apache/cloudstack/api/response/NetworkResponse.java
engine/schema/src/main/java/com/cloud/network/dao/NetworkDetailVO.java
server/src/main/java/com/cloud/api/ApiResponseHelper.java
server/src/main/java/com/cloud/network/NetworkServiceImpl.java
server/src/test/java/com/cloud/vpc/MockNetworkManagerImpl.java
ui/l10n/en.js
ui/scripts/docs.js
ui/scripts/sharedFunctions.js

Problem: Admins don’t want to charge for IP address usage on certain (shared) networks.
Root Cause: There is no flag or detail for admins to provide using UI or API when creating networks to specify if they want IP address usage of the network hidden.
Solution: A new boolean hideipaddressusage flag is added to the createNetwork API and a checkbox in the ‘Add guest network’ UI for the root admins to specify if they want the shared network’s IP address usage to be hidden in the listUsageRecords API response. The provided flag is saved as the ‘hideIpAddressUsage’ detail in the cloud.network_details table for the network. For existing (shared) networks, root admins can also specify the same boolean API parameter hideipaddressusage with the updateNetwork API request to configure the behaviour …

network: allow ability to specify if network's ipaddress usage need to be hidden

---

plugins/metrics/src/main/java/org/apache/cloudstack/api/ListVolumesMetricsCmd.java
plugins/metrics/src/main/java/org/apache/cloudstack/metrics/MetricsServiceImpl.java
server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
server/src/main/java/com/cloud/api/query/ViewResponseHelper.java
server/src/main/java/com/cloud/api/query/dao/VolumeJoinDaoImpl.java
ui/scripts/metrics.js
ui/scripts/ui/widgets/listView.js

Problem: The listVolumeMetrics API response does not honor the volume detail visibility restrictions set for normal users and returns sensitive information which should only be visible to the root admin.
Root Cause: The listVolumeMetrics API response extends the ListVolumesByAdmin API internally and this results in a full display view response that is only meant for the root admin.
Solution: This has been fixed by rectifying the API response to not show ‘physical size’, 'storage type', and ‘storage pool’ information. The UI has also been fixed to hide these columns for normal users.
User metrics view from the UI with  physical size, storage type, and storage pool details hideen
Admin Response contains the full display view/results

 volume: fix volume metrics view from returning sensitive info to end user

---

api/src/main/java/com/cloud/dc/DataCenter.java
api/src/main/java/org/apache/cloudstack/api/command/admin/zone/UpdateZoneCmd.java
api/src/main/java/org/apache/cloudstack/query/QueryService.java
engine/orchestration/src/main/java/org/apache/cloudstack/engine/datacenter/entity/api/db/EngineDataCenterVO.java
engine/schema/src/main/java/com/cloud/dc/DataCenterVO.java
engine/schema/src/main/resources/META-INF/db/schema-41200to41300.sql
server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
server/src/main/java/com/cloud/api/query/vo/DataCenterJoinVO.java
server/src/main/java/com/cloud/configuration/Config.java
server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
ui/scripts/cloudStack.js
ui/scripts/sharedFunctions.js
ui/scripts/system.js

*Problem*: Not able to configure a sort order for the zones that are listed in various views in the UI.
*Root Cause:* There is no mechanism to accept sort key for existing zones or UI widget, that would allow to listing zones in the UI in a certain order.
*Solution*: The order of zones in listed in various views in the UI can now be configured through the newly added “sort_key” field added for the zone. It can be set using updateZone API by providing “sort_key” parameter for a zone, or by reordering the items in the zones list in the UI. UI has been updated to show ordering controls in zones list view. Database changes include updating table “data_center” by adding “sort_key” column (containing integer values and defaults to zero).

server: add support for sorting zones in UI/API

---

api/src/main/java/org/apache/cloudstack/api/response/UsageRecordResponse.java
server/src/main/java/com/cloud/api/ApiResponseHelper.java

Problem: Network name is not part of the network usage response
Root Cause: Code does not set the network name
Solution: Set the network name for network usage type usage records in the API response

api: Set network name as part of the network usage response

---

engine/schema/src/main/java/com/cloud/event/UsageEventVO.java
server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
server/src/main/java/com/cloud/storage/listener/VolumeStateListener.java
usage/src/main/java/com/cloud/usage/parser/VolumeUsageParser.java

**Problem**: The disk offering change is not reflected in cloud_usage database table.
**Root Cause**: The resizeVolume API does not publish the volume disk offering change event to the
cloud_usage database table.
**Solution**: This issue has been fixed by refactoring the resizeVolume API to publish this disk offering change for volumes that either in Allocated or Ready state.
Moves the method that published events for volumes in Ready state from
the VolumeStateListener class to the orchestrateResizeVolume method in
the VolumeApiService.

server: publish volume resize event for volumes

---

ui/css/cloudstack3.css
ui/css/src/scss/components/install-wizzard.scss

Increase z-index for install wizard step to make buttons clickable again.
After the latest refactoring of the styles there was a slight mistake which caused that the buttons for the initial install wizard in the beginning weren't clickable anymore, because they got overlaid by another box.
Tested on local environment.

Increase z-index for install-wizard step

---

server/src/main/java/com/cloud/configuration/Config.java

Tested manually - value is in miliseconds, not seconds.
But I'm not sure how about https://github.com/apache/cloudstack/blob/1d05fead49f5c856257a741b07122f5633d2e359/engine/schema/src/main/resources/META-INF/db/schema-41000to41100.sql#L258 - since it does insert of this setting  with also wrong wording

Fix interval descrption

---

engine/schema/src/main/resources/META-INF/db/schema-41200to41300.sql
pom.xml

This adds support for VMware 6.7
Fixes #2700
Was able to deploy an advanced zone with VMware vCenter/ESXi 6.7 and see systemvms come up:

vmware: add support for VMware 6.7

---

server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
ui/scripts/storage.js

**Problem**: Volume created from a snapshot does not show its disk offering.
**Root Cause**: The volume created from a snapshot of a root disk does not have a disk offering therefore the disk offering of the created volume from the snapshot is empty.
**Solution**: Refactored createVolume API and extended UI to allow user to select a disk offering while creating a volume using a root disk volume snapshot. For creating volumes using data disk volume snapshot, the disk offering given by the snapshot will be assigned. Disk offering selection in the UI form for volume creation from snapshot is depicted in screenshot below.
From UI

server: allow disk offering selection for volume from snapshot

---

plugins/network-elements/juniper-contrail/src/test/java/org/apache/cloudstack/network/contrail/management/MockAccountManager.java
plugins/user-authenticators/ldap/src/main/java/org/apache/cloudstack/ldap/LdapAuthenticator.java
server/src/main/java/com/cloud/user/AccountManager.java
server/src/main/java/com/cloud/user/AccountManagerImpl.java
server/src/test/java/com/cloud/user/MockAccountManagerImpl.java

This fixes a potential NPE when a mapped account is not found and
moving of user to the mapped account is performed. This will now
throw a more information exception than NPE.
Fixes #2853

server: fix potential NPE while ldap authentication

---

systemvm/debian/opt/cloud/bin/cs/CsDhcp.py

In some virtual routers, 'hostname -f' returns 'localhost'. The hostname is also 'localhost' in /var/log/messages
This change can fix the issue in new VRs.
To fix the issue in running VRs, please execute following commands
```
sed -i "/^127.0.0.1/d" /etc/hosts
sed -i "/^127.0.1.1/d" /etc/hosts
echo -e "127.0.0.1\tlocalhost" >> /etc/hosts
echo -e "127.0.1.1\t$(hostname)" >> /etc/hosts
/etc/init.d/rsyslog restart
```

Fix hostname is localhost in some VRs

---

utils/src/main/java/org/apache/cloudstack/utils/imagestore/ImageStoreUtil.java

If secstorage.ssl.cert.domain does not start with '*', we should use it as host name in url when upload template/volume from local
Fixes: #3305

ssvm: use secstorage.ssl.cert.domain as hostname if it does not start with '*' when upload a template or volume from local

---

core/src/main/java/com/cloud/info/ConsoleProxyInfo.java

When checking if the console proxy URL domain starts with *, the code
does not check if the provided string is null. When domain is not
configured the IP address should be used.
Fixes #3164

console-proxy: fix potential NPE condition

---

server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java

Fixes #3291
**ENVIRONMENT**
`KVM on CentOS7`
**SUMMARY**
Added an if statement that catches the destination poolid as an invalid parameter if it is similer to the current poolid

KVM Volumes: Limit migration of volumes within the same storage pool.

---

api/src/main/java/com/cloud/vm/VmDetailConstants.java
api/src/main/java/org/apache/cloudstack/api/command/user/resource/ListDetailOptionsCmd.java
api/src/main/java/org/apache/cloudstack/api/response/DetailOptionsResponse.java
api/src/main/java/org/apache/cloudstack/query/QueryService.java
engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java
plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/CitrixResourceBase.java
server/src/main/java/com/cloud/api/ApiDBUtils.java
server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
server/src/main/java/com/cloud/capacity/CapacityManagerImpl.java
server/src/main/java/com/cloud/network/element/ConfigDriveNetworkElement.java
server/src/main/java/com/cloud/network/element/VirtualRouterElement.java
server/src/main/java/com/cloud/resource/ResourceManagerImpl.java
server/src/main/java/com/cloud/server/ManagementServerImpl.java
server/src/main/java/com/cloud/servlet/ConsoleProxyServlet.java
server/src/main/java/com/cloud/template/TemplateManagerImpl.java
server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
server/src/test/java/com/cloud/vm/UserVmManagerImplTest.java
ui/css/cloudstack3.css
ui/scripts/globalSettings.js
ui/scripts/instances.js
ui/scripts/roles.js
ui/scripts/templates.js
ui/scripts/ui-custom/granularSettings.js

Problem: Users don't know what keys/values to enter for template and VM details.
Root Cause: The feature does not exist that can list possible details and options.
Solution: Based on the possible VM and template details handled by the
codebase, those details were refactored and a list API is introduced
that can return users those details along with possible values. When
users add details now, they will be presented with a list of key details
and their possible options if any.
Introduces a new API:
```
listDetailOptions: Lists all possible details and their options for a resource type such as a VM or a template
Required params: resourcetype, 
API Params               Type     Description
==========               ====     ===========
resourceid               string   the UUID of the …
```

api: instance and template details are free text

---

api/src/main/java/com/cloud/server/ResourceTag.java
api/src/main/java/com/cloud/storage/VolumeApiService.java
api/src/main/java/org/apache/cloudstack/api/command/user/snapshot/CreateSnapshotCmd.java
api/src/main/java/org/apache/cloudstack/api/command/user/snapshot/CreateSnapshotPolicyCmd.java
api/src/main/java/org/apache/cloudstack/api/response/SnapshotPolicyResponse.java
api/src/main/java/org/apache/cloudstack/api/response/SnapshotResponse.java
api/src/test/java/org/apache/cloudstack/api/command/test/CreateSnapshotCmdTest.java
api/src/test/java/org/apache/cloudstack/api/command/user/snapshot/CreateSnapshotPolicyCmdTest.java
server/src/main/java/com/cloud/api/ApiResponseHelper.java
server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
server/src/main/java/com/cloud/storage/snapshot/SnapshotManagerImpl.java
server/src/main/java/com/cloud/storage/snapshot/SnapshotSchedulerImpl.java
server/src/main/java/com/cloud/tags/TaggedResourceManagerImpl.java
server/src/test/java/com/cloud/storage/VolumeApiServiceImplTest.java
ui/css/cloudstack3.css
ui/index.html
ui/scripts/storage.js
ui/scripts/ui-custom/recurringSnapshots.js
ui/scripts/ui/dialog.js
ui/scripts/ui/widgets/tagger.js

**Problem**: Currently tags cannot be applied to snapshot when it is being created but through separate “create tags” API calls. For snapshot policies tags cannot be set either at creation or through “create tags” API.
**Root Cause**: The “create snapshots” API does not support adding tags during creation and it can only be done through “create tags” API. Snapshot policy as a resource does not support tags and no tags can be set for them through any API.
**Solution**: Tag support for snapshot policy has been added. Snapshot policy with tags when executed will produce snapshots containing the same tags from snapshot policy.
Following APIs have been updated:
- Both “create snapshotpolicy” and “create snapshot” now accepts “tags” as a new parameter. The expected format for “tags” parameter …

api: snapshot, snapshotpolicy tag support

---

engine/schema/src/main/resources/META-INF/db/schema-41200to41300.sql

This adds hypervisor capabilities and mappings for XenServer 7.6

engine/schema: add guest-os support and mappings for XenServer 7.6

---

ui/config.js

Follow up left line from #3429 
Storage pool isn't available to users so delete it as it's confusing.

Remove additional line from config as storagepool isn't available for users

---

ui/scripts/ui/dialog.js

Some APIs consume 'tags' param as string and some consume as maps.
Since each API can have at most one 'tags' param the extraction of
map based tags should only happen when strings based tags are not
extracted from the form serialization.
Try tagging in 2 different places -
1. Snapshot , Snapshot policies
2. Disk offering creation
Both places should work. Without this patch only former would work.

Bug fix for distinting between string and map type tags in forms

---

debian/control

This install `file` package that provides the `file` tool used by
cloud-install-sys-tmplt script, as part of cloudstack-management
package installation on Ubuntu distros.
Fixes #3117

debian: install `file` as cloudstack-management dependency

---

server/src/com/cloud/network/router/NetworkHelperImpl.java

For VPC supports redundant VRs, when start the second VR, the pod/cluster/host of first VR should be added to avoid list. This provides higher availability.
The network VRs have the same process already.

RvR: VPC redundant vrs run on same hypervisor

---

systemvm/debian/opt/cloud/bin/configure.py

This fixes to avoid forking curl to save password but instead call
a HTTP POST url directly within Python code. This may reduce bottleneck
during high VM launches that require passwords.
Fixes #3182

systemvm: don't fork to curl to save password

---

ui/scripts/instances.js

When users try to list instances in project mode from Account > SSHKeyPairs > Key > View Instances, we don't need to include sshkeypairs account name into the API Param. It's redundant and causes error.
Fixes: #2895 
Manually in UI try various combinations of reproducing bug in admin/user mode and switchng between regular and project view.

ui: don't pass account name when in project mode to VMs from sshkeypair reference

---

ui/scripts/sharedFunctions.js
ui/scripts/ui/widgets/listView.js

Current master has sorting broken and the order reverses as opposed to
what is set if sortkey.algorithm is set to true. The problem lies in the
way the update APIs were being called by the UI. The code was agnostic
to a global config that backend uses to set the order of the entities
in the corresponding list APIs.
We need to make UI aware of the global config and instead of changing
sign of sort key pass proper numbers so that DB isn't confusing when
some tables have positive sortkey and some have negative.
The fix is in 2 steps-
1) Make use of sortkey name in place where it's relevant. Mere row index
is not sufficient.
2) Reverse the sortkey if we are sorting by descending (when global
config is false)
Fix is general bugfix but I also verified that #2724 is also fixed after this change …

Fix sorting order bug in UI Code with usage of sortkey.algorithm global config

---

utils/src/main/java/com/cloud/utils/net/NetUtils.java

Java methods getInterfaceAddresses()  returns ip addresses in reverse order as "ip addr show"
If there are multiple IPs assigned to a management interface, the last ip will be used as management ip in cloudstack. We need to reverse the ip addresses to get the first ip that makes more sense.
Fixes: #3311 
Add a secondary ip to management interface in kvm hypervisor, and restart cloudstack-agent
In the past the hypervisor will use the new ip in cloudstack database.
If the new ip does not work, we are not able to access the console of vm on the hypervisor.
With this change, the ip in database will not be changed. cloudstack will still use primary ip.

utils: reverse ip addresses of a nic returned by java to get the first ip address

---

ui/css/cloudstack3.css

Fix wrap text for account names on the project view, as it cannot be fully displayed
Before the fix the account column does not wrap the full text:
After the fix:
Create Project
Select Project -> Accounts

[UI] Fix wrap text for accounts on project view

---

engine/schema/src/main/resources/META-INF/db/schema-41200to41300.sql
server/src/main/java/com/cloud/api/ApiDBUtils.java
server/src/main/java/com/cloud/api/query/ViewResponseHelper.java
server/src/main/java/com/cloud/api/query/dao/ProjectJoinDao.java
server/src/main/java/com/cloud/api/query/dao/ProjectJoinDaoImpl.java
server/src/main/java/com/cloud/api/query/vo/ProjectJoinVO.java

If projects have many resource tags, it will take long time to list projects.
Remove resource tags information from project_view will fix it the issue.
Fixes: #3178
create project,
add resource tags to project,
listprojects  lists all resouce tags.

server: reduce execution time while listing project if projects have many resource tags

---

ui/scripts/sharedFunctions.js
ui/scripts/ui-custom/instanceWizard.js

Adds functionality to sort the data that is available on each in the deploy VM wizard's step by their suitable fields i.e
- templates by name
- serviceOfferings by cpuspeed
- diskOfferings by disksize
- affinityGroups by name
- sshkeyPairs by name
- network:
- vpcs by name
- networkOfferings by name
Fixes: https://github.com/apache/cloudstack/issues/3050
- sorted compute offerings
- sorted disk offerings
- sorted networks
Run client
Instances > Add Instance
See previous non sorted data in the browser's console
After sort function run see sorted data in the browser's console
See sorted results in the deploy VM wizard as well

Sort list of templates, serviceOfferings, diskOfferings etc in the deploy VM wizard

---

.travis.yml

This fixes Travis to use openjdk8 and Xenial (Ubuntu 16.04) as base
distro.
This only changes Travis config and does not require smoketests. PR may be merged solely when Travis passes.

travis: use openjdk8 and xenial (ubuntu 16.04)

---

engine/schema/src/main/java/com/cloud/vm/dao/VMInstanceDao.java
engine/schema/src/main/java/com/cloud/vm/dao/VMInstanceDaoImpl.java
plugins/deployment-planners/user-dispersing/src/main/java/com/cloud/deploy/UserDispersingPlanner.java

Consider running and starting VMs when considering load ona host for VM deployement for more accurate dispersion.
Fixes: #3442 
Deploy VMs quickly through CMK on a 2 host environment.

Count Starting along with Running VMs for user dispersing planner

---

framework/quota/src/main/java/org/apache/cloudstack/quota/constant/QuotaTypes.java

Fix issue of `QuotaType` name.
This bug causes `Quota - Summary > Statement` to show the incorrect name of `VM_DISK_BYTES_WRITE`.

quota: fix issue of QuotaType name

---

engine/schema/src/main/resources/META-INF/db/schema-41200to41300.sql

Fixes #3461
Adds upgrade path to add support for XenServer 7.1.2. A larger refactoring can be done in 4.14+ to treat all dot-releases as the same.

schema: add support for XenServer 7.1.2 (LTS)

---

api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
api/src/main/java/org/apache/cloudstack/api/command/user/vm/DeployVMCmd.java
server/src/main/java/com/cloud/vm/UserVmManagerImpl.java

Support copy tags from template/iso image to VM from deploy vm command.
Allow creation of tags from the source template/iso image to vm when deploy vm command creates virtual machine. 
Fixes: #3048 
Cloudmonkey can be used to launch a VM with template containing tags.
1) Created tags in template
2) deployed VM
3) Verify tags were present in the deployed VM
```
(local) 🐵 > deploy virtualmachine zoneid=3d0dff25-be49-487f-b7ed-ff898b4dc560 templateid=1637451e-86b9-11e9-949e-34e12d5f623e hypervisor=KVM serviceofferingid=8d60c39b-3bb4-461c-8639-5f5b5a66fe6b iptonetworklist[0].networkid=fe2e98b0-ccb2-48e9-b607-3335b4857bf8 displayname=vm1 name=vm2 copyimagetagstovm=true
{
"accountid": "16441a0f-86b9-11e9-949e-34e12d5f623e",
"cmd": "org.apache.cloudstack.api.command.admin.vm.DeployVMCmdByAdmin", …
```

Support copy tags from template/iso image to VM from deploy vm command

---

server/src/main/java/com/cloud/network/vpc/NetworkACLServiceImpl.java
server/src/test/java/com/cloud/network/vpc/NetworkACLServiceImplTest.java
utils/src/main/java/com/cloud/utils/net/NetUtils.java

This allows for icmp code range 0-16.
Type 9 Router advertisement reference:
https://www.iana.org/assignments/icmp-parameters/icmp-parameters.xhtml#icmp-parameters-codes-9/#table-icmp-parameters-ext-classes
Fixes #3349

network: allow icmp code 16 in firewall rules

---

plugins/network-elements/juniper-srx/src/main/java/com/cloud/network/resource/JuniperSrxResource.java
scripts/network/juniper/dest-nat-rule-add.xml

This PR partially fixes the logic around port forwarding rules on the Juniper SRX plugin.  The code in the plugin is based on JunOS 10, which is very old.  The changes here should not break compatibility, but should enable the plugin to be used on newer devices.  Note that an additional change to a script file is required to be able to add port forwarding rules, but as this PR was targetted for 4.11.3, I thought it best not to include this change as it might break compatibility for anyone still using JunOS 10.
I've made the logic better and consistent for adding/removing static nat and port forwarding rules - these were multi-step processes which did not check each individual step.  This would aid in manually fixing rules in case of further problems.
I've also improved the logging for …

Fix removing SRX port forwarding rules, improve add/remove logic

---

framework/db/src/main/java/com/cloud/utils/db/GenericDaoBase.java
framework/db/src/main/java/com/cloud/utils/db/GroupBy.java
framework/db/src/main/java/com/cloud/utils/db/SqlGenerator.java

The implementation of GenericBaseDao#searchAndCount() can result in incorrect count. This happens because the implementation of the GenericBaseDao#getCount method ingores the groupBy components of the search queries completely. This means the count returned will always be larger than
the actual count when not considering pagination.
The change to ignore the group by components was brought in b0ce8fd which also fails to explain the rationale. This was probably because the groupby would be executed after select count(*) has finished.
Further investigation of the getCount usage reveal they are always accompanied by search queries which include groupBy components via GenericBaseDao#searchIncludingRemoved method.
Current code diff between search and count methods is as follows -
```diff --git …
```

Fix bug in counting items for search query

---

server/src/main/java/com/cloud/template/TemplateManagerImpl.java
ui/scripts/templates.js

Removed the download icon when a template is not extractable.
Modified the api to allow a user from the same account as the template, to change the extractable attribute on the template.
Fixes: #3400
Tested using the UI.
Create a user, then login with that user. Navigate to templates, add a template.
Edit the template, click on the extractable checkbox. Save changes. 
At this point, there is no error.

Allowing template owner to download template

---

systemvm/debian/opt/cloud/bin/checkrouter.sh

If there are more than 10 vpc tiers or public ip subnets in a VPC, eth1X will be added in vpc router.
The redundant state is UNKNOWN in this case.
creaete more than 10 vpc tiers, then vpc router will be UNKNOWN
it can be fixed by this commit.

vr: Fix vpc router in UNKNOWN state

---

plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java

This change addresses #3089. There was an issue when disks were being added with bus type IDE when creating windows VMs from ISOs. It is not possible to select bus type when creating a VM with an ISO. The bus type is inferred based on the platform emulator string provided to the KVM agent. Currently when creating a VM with managed storage (ex: Solidfire) and OS type string Windows*, all disks are added as IDE. Qemu currently does not support multiple IDE controllers and this configuration results in VMs that cannot be started. This issue does not occur when using NFS as the storage provider due to logic in that KVM agent that makes all data volumes (non root) use a virtio controller for file based disk. Similar logic was added for raw physical disks so that managed storage has the same …

Use IDE as the bus type for root disks and VIRTIO for data disks on platforms without support for para virtualization when using managed storage

---

server/src/main/java/com/cloud/network/IpAddressManagerImpl.java
server/src/main/java/com/cloud/network/NetworkServiceImpl.java
server/src/test/java/com/cloud/network/IpAddressManagerTest.java

Fixes #3321 
This changes removes exception throwing while associating an IP address to a new isolated network which is in `Allocated` state. And it allows disassociating an IP address when it is used for source NAT purpose but network is in allocated state.
Refer, https://github.com/apache/cloudstack/issues/3321#issuecomment-510389806
Using cmk,
```
(localcloud) 🐱 > list networks filter=id,name,state
{
"count": 1,
"network": [
{
"id": "6838a64f-2f55-4097-af9f-c0cdff805737",
"name": "Test",
"state": "Allocated"
}
]
}
(localcloud) 🐱 > associate ipaddress networkid=6838a64f-2f55-4097-af9f-c0cdff805737 
{
"ipaddress": {
"allocated": "2019-07-12T15:29:07+0530",
"associatednetworkid": "6838a64f-2f55-4097-af9f-c0cdff805737",
"associatednetworkname": "Test", …
```

server: fix public IP association/disassociation to new network

---

ui/scripts/system.js

Fix small UI issue when dedicating public IR range for system VMs:
`Unable to execute API command createvlaniprange due to invalid value. Invalid parameter domainid value=undefined due to incorrect long value format, or entity does not exist or due to incorrect parameter annotation for the field in api cmd class.`
Fixes: #3485 
As an administrator, create a new public range, selecting System VMs option

UI: Fix SystemVMs public range dedication

---

api/src/main/java/org/apache/cloudstack/api/command/admin/direct/download/RevokeTemplateDirectDownloadCertificateCmd.java
api/src/main/java/org/apache/cloudstack/api/command/admin/direct/download/UploadTemplateDirectDownloadCertificateCmd.java
api/src/main/java/org/apache/cloudstack/direct/download/DirectDownloadCertificate.java
api/src/main/java/org/apache/cloudstack/direct/download/DirectDownloadManager.java
core/src/main/java/org/apache/cloudstack/agent/directdownload/RevokeDirectDownloadCertificateCommand.java
engine/schema/src/main/java/com/cloud/host/dao/HostDao.java
engine/schema/src/main/java/com/cloud/host/dao/HostDaoImpl.java
engine/schema/src/main/java/org/apache/cloudstack/direct/download/DirectDownloadCertificateDao.java
engine/schema/src/main/java/org/apache/cloudstack/direct/download/DirectDownloadCertificateDaoImpl.java
engine/schema/src/main/java/org/apache/cloudstack/direct/download/DirectDownloadCertificateHostMapDao.java
engine/schema/src/main/java/org/apache/cloudstack/direct/download/DirectDownloadCertificateHostMapDaoImpl.java
engine/schema/src/main/java/org/apache/cloudstack/direct/download/DirectDownloadCertificateHostMapVO.java
engine/schema/src/main/java/org/apache/cloudstack/direct/download/DirectDownloadCertificateVO.java
engine/schema/src/main/resources/META-INF/cloudstack/core/spring-engine-schema-core-daos-context.xml
engine/schema/src/main/resources/META-INF/db/schema-41200to41300.sql
framework/direct-download/src/main/java/org/apache/cloudstack/framework/agent/direct/download/DirectDownloadService.java
plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtRevokeDirectDownloadCertificateWrapper.java
server/src/main/java/com/cloud/server/ManagementServerImpl.java
server/src/main/java/org/apache/cloudstack/direct/download/DirectDownloadManagerImpl.java
test/integration/smoke/test_direct_download.py

Extend improvements on PR #2995 and #3075 
- Add an API method to revoke certificates from hosts
- Add a background task to sync missing certificates to hosts (which for some reason could not be uploaded before)

KVM: Enhancements for direct download feature

---

server/src/main/java/com/cloud/api/ApiServer.java

CloudStack provides CloudStack API Unauthenticated Access through port
8096. It should not be open to the Internet in any case.
Fixes: #3450
**Current behavior**
1. Deploy a fresh CloudStack environment
2. Assert that the port 8096 is enabled by default. 
3. Verify that `integration.api.port` is indeed configured as 8096
**WIth this PR**
1. Deploy a fresh CloudStack environment with packages from this PR
2. Assert that the port 8096 is not enabled by default.
3. Verify that `integration.api.port` is indeed configured as 0

Set integration.api.port to 0 (zero) as default.

---

plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java

During volume stats calculation, if a volume has more than one disk in
the chain-info it is not used to sum the physical and virtual size
in the loop, instead any previous entry was overwritten by the last disk.
Fixes #3416

vmware: fix volume stats logic

---

engine/schema/src/main/java/com/cloud/hypervisor/dao/HypervisorCapabilitiesDao.java
engine/schema/src/main/java/com/cloud/hypervisor/dao/HypervisorCapabilitiesDaoImpl.java
server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
server/src/test/java/com/cloud/storage/VolumeApiServiceImplTest.java

When VM is created but not started on any host, attaching a volume on it causes the maximum number of allowed volumes to be 6 (hardcoded)
- Deploy VM with startvm=false parameter
- Attach more than 6 volumes to VM (in case of KVM and VMware)

Fix hardcoded max data volumes when VM has been created but not started before

---

server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java

When adding iprange for VLANs there are 3 cases -
1) VLAN under consideration has a tag (like 101)
2) VLAN under consideration has a tag but as a range (like 101-124)
3) VLAN is untagged (i.e. id is "untagged")
Before adding iprange we have to check for possible overlaps and throw exception. This needs to be done as follows -
1) If VLAN Tag ID is numeric or a range we need to call `UriUtils.checkVlanUriOverlap`method which internally tries to expand the range as verifies if there are overlaps. If URI overlaps (i.e. there are overlapping VLAN tags) we then need to verify if the iprange being added overlaps with previously added ranges.
2) If there are no overlapping tags we simply need to test for public networks being present in the VLAN.
A Regression was introduced in …

server: fix the subnet overlap checking logic for tagged and untagged vlans when adding ipranges

---

server/src/main/java/org/apache/cloudstack/network/topology/BasicNetworkVisitor.java

CloudStack reports an error while stopping/expunging VMs on basic zones
Fixes: #3497 
VM lifecycle

Fix stop VM issue on basic zones

---

engine/schema/src/main/java/com/cloud/storage/dao/VolumeDao.java
engine/schema/src/main/java/com/cloud/storage/dao/VolumeDaoImpl.java
plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/IscsiAdmStorageAdaptor.java
server/src/main/java/com/cloud/vm/UserVmManagerImpl.java

Currently when refreshing disk usage stats all kvm agents are asked to collect stats for all volumes. In setups with multiple kvm hosts where managed storage is used, not all volumes are attached to all kvm hosts, this results in a large number of warnings in the kvm agent logs. This change introduces a filter step in case managed storage is used so that the management server only requests kvm agents for stats about volumes that are connected to each kvm host.

filter volumes by host when refreshing stats

---

plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/BridgeVifDriver.java
plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/IvsVifDriver.java
plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/OvsVifDriver.java
server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
server/src/main/java/com/cloud/network/guru/ControlNetworkGuru.java
server/src/main/java/com/cloud/server/ConfigurationServerImpl.java
server/src/main/java/com/cloud/test/IPRangeConfig.java
utils/src/main/java/com/cloud/utils/net/NetUtils.java
utils/src/test/java/com/cloud/utils/net/NetUtilsTest.java

There are certain scenarios where the 169.254.0.0/16 subnet is used for different
purposes then CloudStack on a hypervisor.
Once of such scenarios is a BGP+EVPN+VXLAN setup using BGP Unnumbered where the
169.254.0.1 address is used by Frr/Zebra BGP routing to send traffic to the
neighboring router.
The following settings can be changed in the agent.properties (default values added):
control.cidr=169.254.0.0/16
Make sure the global setting 'control.cidr' matches the values defined in the agent.propeties!
In the future the mgmt server can send this parameter to a KVM Agent on startup, but at the moment
this framework is not in place and thus these values can't be send to the Agent in a proper manner.
Fixes: #3488
Ran local test on our cloud environment and verified cloud0 now has a …

kvm/bridge: Allow Link Local Cidr (cloud0 interface) to be configured

---

client/pom.xml
plugins/pom.xml
plugins/storage/volume/datera/pom.xml
plugins/storage/volume/datera/src/main/java/org/apache/cloudstack/storage/datastore/driver/DateraPrimaryDataStoreDriver.java
plugins/storage/volume/datera/src/main/java/org/apache/cloudstack/storage/datastore/lifecycle/DateraPrimaryDataStoreLifeCycle.java
plugins/storage/volume/datera/src/main/java/org/apache/cloudstack/storage/datastore/provider/DateraHostListener.java
plugins/storage/volume/datera/src/main/java/org/apache/cloudstack/storage/datastore/provider/DateraPrimaryDataStoreProvider.java
plugins/storage/volume/datera/src/main/java/org/apache/cloudstack/storage/datastore/util/DateraObject.java
plugins/storage/volume/datera/src/main/java/org/apache/cloudstack/storage/datastore/util/DateraUtil.java
plugins/storage/volume/datera/src/main/resources/META-INF/cloudstack/storage-volume-datera/module.properties
plugins/storage/volume/datera/src/main/resources/META-INF/cloudstack/storage-volume-datera/spring-storage-volume-datera-context.xml
test/integration/plugins/datera/TestVolumes.py

Features:
1. Zone-wide and cluster-wide primary storage support
2. VM template caching automatically on Datera, the subsequent VMs can be created instantaneously by fast cloning the root volume.
3. Rapid storage-native snapshot
4. Multiple managed primary storages can be created with a single Datera cluster to provide better management of
- Total provisioned capacity
- Default storage QoS values
- Replica size ( 1 to 5 )
- IP pool assignment for iSCSI target
- Volume Placement ( hybrid, single_flash, all_flash )
5. Volume snapshot to VM template
6. Volume to VM template
7. Volume size increase using service policy
8. Volume QoS change using service policy
9. Enabled KVM support
10. New Datera app_instance name format to include ACS volume name
11. VM live migration

Datera storage plugin

---

systemvm/debian/opt/cloud/bin/setup/bootstrap.sh

* After PR #3278 there was some changes on the channels. this does not seem like the problem. if we look to the VR XML file we see the following. the qemu guest agent must be the problem because the state of the VR is "disconnected".
```xml
<channel type='unix'>
<source mode='bind' path='/var/lib/libvirt/qemu/r-1750-VM.org.qemu.guest_agent.0'/>
<target type='virtio' name='org.qemu.guest_agent.0' state='disconnected'/>
<alias name='channel0'/>
<address type='virtio-serial' controller='0' bus='0' port='1'/>
</channel>
```
after investigation of the bootstrap process i think i found this problem. there is no startup from the qemu-guest-agent. we need them in connected state for the patch.sh script.
the problems seems to be the startup of the "qemu-guest-agent". since this is not an really …

Fix VR bootstrapping/connection state in KVM

---

ui/css/cloudstack3.css

It was not possible to display the entire name of items in dropdown menus within dialogs in CloudStack, such as:
- Create compute offering
- Create network offering
- Create VPC offering
Before this fix, the entire name of the menu items were not entirely displayed:
Scrolling option is added, preserving the dialog's original width:
Test CloudStack dialogs with dropdown menus

[UI] Improve visibility of dropdown menus on dialogs

---

server/src/main/java/com/cloud/api/ApiResponseHelper.java

Add size to list usage records for VMSnapShotOnPrimary (type 27)
The size was included in description but missing from response.

Add size to list usage records for VMSnapShotOnPrimary (type 27)

---

api/src/main/java/org/apache/cloudstack/api/command/user/iso/GetUploadParamsForIsoCmd.java
api/src/main/java/org/apache/cloudstack/api/command/user/template/GetUploadParamsForTemplateCmd.java
api/src/main/java/org/apache/cloudstack/query/QueryService.java
server/src/main/java/com/cloud/api/ApiResponseHelper.java
server/src/main/java/com/cloud/api/query/dao/TemplateJoinDaoImpl.java

- This allows getUploadParamsForIso for all user role types, also fixes
authorised field for getUploadParamsForTemplate API.
- Fix global setting description to say what is used when value is empty/blank.
- For VM running/allocated usage description, use parenthesis to return the instance name and ID.
- Display template download progress when template is added to a project

Misc fixes around API permissions, global settings and template UX

---

ui/scripts/cloudStack.js
ui/scripts/sharedFunctions.js
ui/scripts/templates.js

1. Fix populating g_allowUserViewAllDomainAccounts flag. This was
implemented incorrectly and caused flag's effect to not reflect
directly after login.
2. Filter account/project names only for add operation. update
template permissions API is implemented in such a way that it allows
removal of any account that could have had permissions but allows
only adding accounts/projects which are in caller's domain.
3. Added some checks where null variable could result in crash.
Manual testing has been done on UI locally.

Misc fixes to sharing templates functionality

---

core/src/main/java/com/cloud/agent/api/MigrateCommand.java
engine/storage/datamotion/src/main/java/org/apache/cloudstack/storage/motion/StorageSystemDataMotionStrategy.java
engine/storage/datamotion/src/test/java/org/apache/cloudstack/storage/motion/StorageSystemDataMotionStrategyTest.java
plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/MigrateKVMAsync.java
plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtMigrateCommandWrapper.java

Fix regression bug that affects KVM local storage migration. Some of the desired execution flows for KVM local storage migration had been altered to allow only managed storage to execute. Fixed allowing managed and non managed storages to execute.
Fixes #3521
1. Start a VM on a KVM host with local storage;
2. Migrate the VM to another KVM host that has local storage
3. Assert that (i) ACS volumes table, (ii) the VM volume content, and (iii) the VM libvirt xml have all been updated correctly.
4. Keep migrating (repeating steps 2 and 3) the VM around hosts (also migrate back the VM to its first host)

KVM local migration issue #3521

---

ui/scripts/ui-custom/instanceWizard.js

This PR fixes range check in VM deployment wizard while using custom constrained offering.
Existing code was failing while checking user input value in the form for CPU cores and RAM size when minimum and maximum value vary in digit count.
Also, while re-selecting offerings slider position was not restored to minimum value. THis has been fixed with changes.
Entering a valid value for RAM but getting error,
Selecting custom constrained offering initially, then making changes for CPU, RAM parameters, then selecting a fixed offering and then again selecting custom constrained offering. Though text input shows minimum values but slider is not at the start.
UI

ui: fix for custom constrained offering params range check

---

engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/snapshot/CephSnapshotStrategy.java
server/src/main/java/com/cloud/network/router/CommandSetupHelper.java
server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
systemvm/debian/opt/cloud/bin/merge.py
systemvm/debian/opt/cloud/bin/setup/bootstrap.sh

Smoketests fixes. Refer health check PR https://github.com/apache/cloudstack/pull/3517
Known/Failing tests:
Test | Result | Time (s) | Test File
-- | -- | -- | --
test_reboot_router | Error | 349.14 | test_network.py
test_08_start_router | Error | 71.81 | test_routers.py
test_09_reboot_router | Error | 0.12 | test_routers.py
test_02_list_snapshots_with_removed_data_store | Error | 1.18 | test_snapshots.py
test_01_volume_usage | Error | 9.42 | test_usage.py

4.13/master stabilisation PR

---

engine/schema/src/main/java/com/cloud/dc/dao/VlanDaoImpl.java
server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java

When a network IP range is removed, the "vlan" stays mapped on `pod_vlan_map`; therefore, the method that lists the VLANs by pod id will return null VLANS.
This PR adds proper verifications to avoid null pointer exception when deploying VRs on a pod with removed VLANs. The exception was caused on [getPlaceholderNicForRouter](https://github.com/apache/cloudstack/blob/3c2af55d81dbfaf17a3bf0b6247ecd830df12996/server/src/main/java/com/cloud/network/NetworkModelImpl.java#L2306)
```
at com.cloud.network.NetworkModelImpl.getPlaceholderNicForRouter(NetworkModelImpl.java:2306)
```

Prevent NullPointer on a network with removed IP ranges/"VLANs"

---

engine/components-api/src/main/java/com/cloud/event/UsageEventUtils.java
engine/schema/src/main/java/com/cloud/event/UsageEventVO.java
engine/schema/src/main/java/com/cloud/usage/UsageSnapshotOnPrimaryVO.java
engine/schema/src/main/java/com/cloud/usage/UsageVMSnapshotVO.java
engine/schema/src/main/java/com/cloud/usage/dao/UsageVMSnapshotDaoImpl.java
engine/schema/src/main/java/com/cloud/usage/dao/UsageVMSnapshotOnPrimaryDaoImpl.java
engine/schema/src/main/resources/META-INF/db/schema-41200to41300.sql
engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/vmsnapshot/DefaultVMSnapshotStrategy.java
server/src/main/java/com/cloud/api/ApiResponseHelper.java
usage/src/main/java/com/cloud/usage/UsageManagerImpl.java
usage/src/main/java/com/cloud/usage/parser/VMSanpshotOnPrimaryParser.java
usage/src/main/java/com/cloud/usage/parser/VMSnapshotUsageParser.java

Fixes #3558
Problem: Tags are not visible on listUsageRecords type=25/27 (VM snapshots) even though there are tags on the VM snapshot
````
list usagerecords startdate=2015-01-01 enddate=2019-08-13 includetags=true type=25
{
"accountid": "29728169-ba9e-11e9-8e85-1e0050010765",
"description": "VMSnapshot on primary storage usage for VM multi-disk-asa (b73a99b1-04d6-4bd4-b6b6-dacc683efc27) with size 21743271936",
"domainid": "f89085e7-ba9d-11e9-8e85-1e0050010765",
"enddate": "2019-08-13'T'11:58:15+00:00",
"name": "i-2-21-VM_VS_20190813114616",
"rawusage": "0.198085",
"size": 21743271936,
"startdate": "2019-08-13'T'11:46:22+00:00",
"tags": [],
"usage": "0.198085 Hrs",
"usagetype": 27,
"virtualmachineid": "b73a99b1-04d6-4bd4-b6b6-dacc683efc27",
"zoneid": …
```

Display VM snapshot tags on usage records

---

server/src/main/java/com/cloud/server/ManagementServerImpl.java

Fixes NPE when trying to find suitable storage pools for a volume
when the volume is not attached to a VM, when trying to call the findStoragePoolsForMigration API.

server: fix NPE for the case where volume is not attached to a VM

---

server/src/main/java/com/cloud/network/NetworkModelImpl.java

When deploying a VM via UI, networks that have all the following characteristics are not listed on the wizard:
- advanced networking with security groups
- traffic type of "Guest"
- guest type of "Shared"
- IPv6 CIDR not null
This PR fixes it by removing the verification that counts the IPs from UserIpv6AddressVO in order to check if it can use the network for deploying new VMs in UI [1]. Table "user_ipv6_address" (UserIpv6AddressVO) is empty and will always be as it is a legacy code/table, not used in any IP 
allocation flow. Therefore, the removed verification should be removed.
[1] com.cloud.network.NetworkModelImpl.canUseForDeploy(Network)
This PR fixes #3570
The Javascript code adds the parameter `canusefordeploy=true` on the API call when the network is an advanced network with …

Unable to deploy VMs via UI in advanced networks with SG and IPv6 cidr

---

tools/appliance/systemvmtemplate/template.json

Since version 10.0.0 of Debian has become stable, the URL of the Debian 9.9.0 ISO files has changed from `current` to `archive`.
The old URL returns a 404 and crash the build of systemvm templates.
Affects: 4.11, 4.13.
I built a systemvm template without any errors with this change.

systemvmtemplate: Fix Debian 9 iso url

---

python/lib/cloudutils/utilities.py

small change to check for the right output of the system call
Fixes: #3572
manual testing on a nested env so far.

`service is-active` output check for "failed"

---

agent/conf/cloudstack-agent.logrotate.in

Logrotate should only touch security_group.log and resizevolume.log
as the agent.log is already rotated by log4j inside the Agent.
Having two systems trying to rotate agent.log leads to all kinds of
issues like having binary (compressed) data in the middle of a plain-text
log file.

kvm: Logrotate should not touch agent.log

---

server/src/main/java/com/cloud/agent/manager/allocator/impl/FirstFitAllocator.java

In case of null guest OS found for a template, don't fail prioritisation
completely (could still work based on HVM etc).

allocator: in case of null guest OS don't fail prioritisation completely

---

server/src/main/java/com/cloud/vm/UserVmManagerImpl.java

This fixes a behaviour to not cleanup DHCP and DNS rules for NICs of a
VM in the VR when it is stopped, but instead when VM is expunged because
stopped VMs in CloudStack still retain the IPs and records.

server: Cleanup dhcp and dns entries only on expunging VM

---

debian/control
packaging/centos7/cloud.spec
scripts/vm/network/security_group.py

This script only runs on the KVM Hypervisors and these all support
Python 3.
As Python 2 is deprecated at the end of 2019 we need to fix these
scripts to work under Python 3.
CentOS 7, 8 and Ubuntu 16.04 and 18.04 all have Python 3 installed
by default.
Ubuntu 20.04 will no longer have Python 2 installed and therefor
this script needs to be modified to work with Python 3.

kvm/security_group: Make Security Group Python 3 compatible

---

engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
server/src/main/java/com/cloud/network/element/VirtualRouterElement.java
server/src/main/java/com/cloud/vm/UserVmManagerImpl.java

According comment in PR #3608, dhcp and dns entries are cleaned up only when a VM is expunged.
Revert part of commit 8fb388e9312b917a8f36c7d7e3f45985a95ce773.

[do not merge] server: Do NOT cleanup dhcp and dns when stop a vm

---

utils/src/main/java/com/cloud/utils/nio/Link.java
utils/src/main/java/com/cloud/utils/nio/NioServer.java

Every time a client connects, the NioServer will retain the link against
the InetSocketAddress object. If the same agent/client reconnects, it
will grow older links over time and in case of denial of service attack
or a client/script/monitoring-service reconnecting aggressively against
port 8250 will cause the `_links` weak hashmap to grow over time and
very quickly.
The fix will ensure that only one Link gets weakly retained for an
incoming client based on its address string.
This is what is seen when only one kvm/agent connects to the management server:
When I restart the cloudstack-agent couple of times, I see the `_links` grow:

NioServer: retain links by address string to minimize resource leak

---

scripts/vm/network/security_group.py

in agent.log on a host running with cloudstack 4.14.0.0-SNAPSHOT, it gives error
```
File "/usr/share/cloudstack-common/scripts/vm/network/security_group.py", line 1272, in <module>
get_rule_logs_for_vms()
File "/usr/share/cloudstack-common/scripts/vm/network/security_group.py", line 758, in get_rule_logs_for_vms
vms = virshlist(state)
File "/usr/share/cloudstack-common/scripts/vm/network/security_group.py", line 104, in virshlist
alldomains = [d for domain in map(conn.lookupByID, conn.listDomainsID())]
File "/usr/share/cloudstack-common/scripts/vm/network/security_group.py", line 104, in <listcomp>
alldomains = [d for domain in map(conn.lookupByID, conn.listDomainsID())]
NameError: name 'd' is not defined
```

security_group.py: fix NameError: name 'd' is not defined

---

systemvm/debian/opt/cloud/bin/cs/CsDhcp.py

Lease time set to effectively infinite (36000+ days) since we fully control VM lifecycle via CloudStack.
Infinite time helps avoid some edge cases which could cause DHCPNAK being sent to VMs since
(RHEL) system lose routes when they receive DHCPNAK.
When VM is expunged, its active lease and DHCP/DNS config is properly removed (#3627 and #3608) from related files in VR, so the infinite duration of lease does not cause any issues or garbage.
There will be soon a PR which also regenerates the /var/lib/misc/dnsmasq.leases (active lease DB file) in the new VR (when restarting network with cleanup), which will help around RHEL edge cases (described above) for the VMs who are already running in productions systems with 30d lease time.

Increase DHCP lease time to infinite

---

client/src/main/java/org/apache/cloudstack/ServerDaemon.java

Related to https://github.com/apache/cloudstack/pull/2329#issuecomment-547904987 the session timeout is not taken into account. This change creates a session handler explicitly and the timeout value should be correctly taken into account.
This has not been tested yet.

client: fix for jetty session timeout

---

plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/BridgeVifDriver.java
plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/IvsVifDriver.java
scripts/vm/network/vnet/modifyvlan.sh

The command 'brctl' is deprecated and should no longer be used.
iproute2 supports all the features we need and therefor we should use
this instead of the old commands.
Feature wise this does not change anything. It just makes the code more
robust towards the future.

kvm: Use 'ip' instead of 'brctl'

---

agent/conf/agent.properties
plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtCapXMLParser.java
plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java
plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java
server/src/main/java/com/cloud/hypervisor/kvm/discoverer/LibvirtServerDiscoverer.java

KVM is supported on arm64 Linux (https://www.linux-kvm.org/page/Processor_support#ARM:). For a small (IoT) platform such as the new Raspberry Pi 4 that uses armv8 processor (cortex-a72) it's possible to run Linux host with `/dev/kvm` accleration.
This PR is from a fun weekend project where:
- I set up a Raspberry Pi 4 - 4GB RAM model with 4 CPU cores @ 1.5Ghz, 128GB SD samsung evo plus card
- Installed Ubuntu 19.10 raspi3 base image: http://cdimage.ubuntu.com/releases/19.10/release/ubuntu-19.10-preinstalled-server-arm64+raspi3.img.xz
- Build a custom Linux 5.3 kernel with KVM enabled, deb here: http://dl.rohityadav.cloud/cloudstack-rpi/kernel-19.10/ and install the linux-image and linux-module
- Then install/setup CloudStack on it (fix some issues around jna, by manually installing newer …

IoT/ARM64 support: allow cloudstack-agent on Raspberry Pi 4 (armv8) to use kvm acceleration

---

framework/jobs/src/main/java/org/apache/cloudstack/framework/jobs/impl/AsyncJobManagerImpl.java

On a Cloudstack instance with log verbosity set to INFO, there are 2 messages generated every 10 seconds about cleaning up expired async jobs.  This makes the log messages much noisier than they need to be.
This PR reduces that message to trace level, since there are actually useful messages at INFO level in that class.
Check compilation and tests

Reduce verbosity of Async Job Manager log messages

---

systemvm/debian/opt/cloud/bin/cs/CsRoute.py

While searching for existing route, don't use the throw keyword when
using the cmd with `ip route show`. This fixes unnecessary ERROR messages in the VR cloud.log and issue of re-adding an already added routing rule (which may throw RTLINK file already exists error).

systemvm: for ip route show command don't use the throw command

---

engine/storage/src/main/java/org/apache/cloudstack/storage/endpoint/DefaultEndPointSelector.java

Fixes a rare bug - in case an older SSVM is removed without changing it's state from Up
to Destroyed/Removed etc, the SSVM may be randomly selected for image
store related operations. This fix ensures that endpoints for an image
store are found only from a set of SSVM hosts that are not removed.
Needs testing and review.

storage: don't select an SSVM that is removed

---

plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtRevertSnapshotCommandWrapper.java

Fixes issue #3590 by using the last element on the array from the snapshot "path" String for retrieving the snapshot id. Additionally, it uses the `volumePath` as the volume id which should always be the correct value. The error raised on issue #3590 was related to the wrong use of variable "path" where in some cases had a different set of substrings.
The proposed change has been tested and evaluated. The values used for openning the RBD connection and executing the rollback were stable on the tests. Runned rollback on multiple snapshots and could start the VM with the content matching the ROOT reverted snapshot.

fix issue #3590 'Revert Ceph/RBD Snapshot'

---

ui/scripts/instances.js

This PR changes behaviour for VM migrate host form where currently it shows a popup on scrolling to the end of the list saying `No more hosts are available for migration`. Popup has been removed to avoid confusion cleaner user experience.
Popup,
From UI
https://screencast-o-matic.com/watch/cqXIjtUDzF

ui: fix migrate host form no host popup

---

test/integration/plugins/test_quota.py

added a classmethod to cleanup resources save in the class field list _cleanup.
N/A
Test run that would first leave an account in place in the environment that was tested against, now leaves this environment without residue.
more tests have this fault. I'll look at cleaning those and a more generic method (i.e. moving the class-method to the parent class (as well as the list)

add class cleanup method

---

core/src/main/java/com/cloud/agent/resource/virtualnetwork/facade/SetNetworkAclConfigItem.java

When add a acl rule with protocol number, the iptables rules in vpc vr is not applied correctly.
for example, when add an ingress acl rule (protocol number:50, cidr: 2.2.2.2/32), we expect to have a iptables rule: "-A ACL_INBOUND_eth2 -s 2.2.2.2/32 -p esp -j ACCEPT"
the actual rule is "-A ACL_INBOUND_eth2 -j DROP"
It is because the rules in json are not correct.
network_acl.json.a8c52dca-0278-4e1c-b72b-987ca7121f4f.gz:{"device":"eth2","mac_address":"02:00:7d:27:00:02","private_gateway_acl":false,"nic_ip":"192.168.11.12","nic_netmask":"28","ingress_rules":[{"type":"protocol","protocol":50,"cidr":"ACCEPT","allowed":false},{"type":"all","cidr":"0.0.0.0/0","allowed":true},],"egress_rules":[],"type":"networkacl"}
Fixes: #3602 
Add acl rule in VPC, then check the iptables rules in VPC VR. all …

vpc: fix acl rule with protocol number is not applied correctly in vpc vr

---

deps/install-non-oss.sh

Signed-off-by: Kai Takahashi <www.carrotsoft@gmail.com>
Without vim25.jar for vSphere 6.7, building CloudStack fails with Hypervisor VMware support.
Manually executing ` mvn install:install-file -Dfile=vim25_67.jar        -DgroupId=com.cloud.com.vmware -DartifactId=vmware-vim25    -Dversion=6.7   -Dpackaging=jar` solved the issue.

Add support for vSphere Web SDK 6.7 installation in install-non-oss.sh

---

packaging/centos7/cloud.spec

(It's already added for debian)
Signed-off-by: Kai Takahashi <www.carrotsoft@gmail.com>
Add python-setuptools as a build-time dependency package for CentOS 7.
python-setuptools is already added as a dependency package for debian from commit `4a77a799490a0cd655b1a53377c4db1bb51ddc7c`

New BuildRequires for CentOS 7: python-setuptools

---

server/src/main/java/com/cloud/network/router/VirtualNetworkApplianceManagerImpl.java

Fix VR creation issue when deploying VM on shared network using PVLAN.
Tested on KVM + Open vSwitch host
Error:
````
2019-10-28 13:37:19,217 DEBUG [c.c.a.t.Request] (Work-Job-Executor-3:ctx-522095d0 job-29/job-30 ctx-22bff2f0) (logid:6771277e) Seq 1-4072942913003192458: Received:  { Ans: , MgmtId: 32988167473142, via: 1(ref-trl-218-k-m7-nvazquez-kvm1), Ver: v1, Flags: 10, { StartAnswer, CheckSshAnswer, GetDomRVersionAnswer, NetworkUsageAnswer, Answer, Answer, Answer } }
2019-10-28 13:37:19,224 DEBUG [o.a.c.n.t.AdvancedNetworkTopology] (Work-Job-Executor-3:ctx-522095d0 job-29/job-30 ctx-22bff2f0) (logid:6771277e) SETUP DHCP PVLAN RULES
2019-10-28 13:37:19,228 DEBUG [c.c.n.r.NetworkHelperImpl] (Work-Job-Executor-3:ctx-522095d0 job-29/job-30 ctx-22bff2f0) (logid:6771277e) Router requires …
```

Fix VR creation issue while creating VM on shared network using PVLAN

---

plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java

When I add a secondary IP to a nic on shared network in advanced zone with security groups, the network rules for new IP are not applied on KVM hypervisors.
It is because "--action -A" cannot be recognized in security_group.py after commit ac73e7e671ba107830f96b9fb534eb716956e405. changing to "--action=-A" will fix it.
When add a ip (ip must to be specified see https://github.com/apache/cloudstack/pull/3635) to a nic, in advanced zone with security groups, the network rules for the ip should be added on hypervisor. However it does not work in 4.13/master.
in agent.log it gives the following error
```
root@node32:~# /usr/share/cloudstack-common/scripts/vm/network/security_group.py network_rules_vmSecondaryIp --vmname i-14-54-VM --nicsecips 192.168.116.246 --action -A
usage: …
```

kvm: fix issue that network rules for secondary IPs are not applied

---

server/src/main/java/com/cloud/network/NetworkServiceImpl.java

After commit fbf488497fb863c13fc0908281e3f4f86906df43, admin need to specify an ipv4 or ipv6 addresses when add IP to nic which breaks backward compatibity. If IP is not specified, a IPv4 address should be returned.
When I add an IP to a nic and do not specify an IP, 
Before this PR, it gives an error "Allocating ip to guest nic 111 failed"
After this PR, it succeeds.

server: acquire IPv4 address when add secondary IP to nic if IP is not specified

---

core/src/main/java/com/cloud/agent/resource/virtualnetwork/facade/SetNetworkAclConfigItem.java
plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
server/src/main/java/com/cloud/network/NetworkServiceImpl.java

4.13 forward merge

---

scripts/vm/network/security_group.py

When I add a security group rule with cidr like 1.1.1.1/24, the rule is not applied on kvm hypervisor.
Ths issue does not exist in 4.13.0.0 and previous versions.
It has been tested in advanced zone with security group.
It can be verified very easily in python3, see results below.
```
Python 3.6.7 (default, Oct 22 2018, 11:32:17)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ipaddress
>>> ipaddress.ip_network("1.1.1.1/28")
IPv4Network('1.1.1.1/28')
>>> ipaddress.ip_network("1.1.1.1/24")
File "<stdin>", line 1, in <module>
File "/usr/lib/python3.6/ipaddress.py", line 74, in ip_network
return IPv4Network(address, strict)
File "/usr/lib/python3.6/ipaddress.py", line 1519, in __init__
raise …
```

security_group.py: check cidr unstrictly to accept cidrs like 1.1.1.1/24

---

debian/control
packaging/centos7/cloud.spec
utils/src/main/java/com/cloud/utils/net/NetUtils.java

This uses `ip route` than `route` without an explicit path (/bin, /sbin
etc.) to query the default network interface on the system.
Tested on Ubuntu:
> ip route | grep default | head -1 | grep -Po '(?<=dev )(\S+)'
wlp0s20f3

utils: use iproute to get default network interface

---

server/src/main/java/com/cloud/consoleproxy/ConsoleProxyManagerImpl.java
server/src/main/java/com/cloud/server/ManagementServerImpl.java
ui/scripts/instances.js
ui/scripts/system.js

Currently vm console is not enabled if vm is in stopping or migrating.
Enabling vm console will help us 
Fixes: #3631

consoleproxy: Enable console for vms in Stopping/Migrating state

---

ui/scripts/sharedFunctions.js
ui/scripts/storage.js

the files is based on volumes and will npe (if that's a thing in javascript)
when applied in the snapshot dialog
Fixes: #3716
manually (see screenshot)

a conditional to prevent creation of a field

---

engine/schema/src/main/java/com/cloud/storage/dao/VolumeDaoImpl.java

If the volume of a VM is in "Expunged" state then it should not be
considered towards total resource count of "primarystoragetotal"
field of a domain.\
Currently, CloudStack takes into resource calculation even if the
volume is expunged. The volume itself doesn't exist in primary
storage and hence it should not be considered towards resource
calculation.
Steps to reproduce the issue:
1 . Get the resource count of "primarystoragetotal" of a particular domain.
2 . Create a VM with 5GB root disk size and stop it.
3 . Now the value of "primarystoragetotal" should be intitial value plus 5.
4 . Navigate to "volumes" of the VM and select "Download Volume" option.
5 . Once the volume is downloaded, expunge the VM.
6 . Get the resource count of "primarystoragetotal". it will be same value as in …

server: Fix resource count of primary storage/volume because of Expunged volumes

---

engine/orchestration/src/main/java/com/cloud/agent/manager/AgentAttache.java
server/src/main/java/org/apache/cloudstack/agent/lb/IndirectAgentLBServiceImpl.java

Fixes: #3581 
This PR introduces a fix for a limitation on the KVM agent load balancing feature.
When a host is in 'Disabled' state and the agent is restarted, then the host is not able to connect to the management server, staying indefinitely in 'Connecting' state
````
2019-10-04 05:23:12,242 DEBUG [c.c.r.ResourceState] (AgentConnectTaskPool-5:ctx-e3780a57) (logid:7c4cc142) Resource state update: [id = 4; name = trl-65-k-M7-nvazquez-kvm4; old state = Disabled; event = InternalCreated; new state = Disabled]
2019-10-04 05:23:12,242 DEBUG [c.c.a.m.AgentManagerImpl] (AgentConnectTaskPool-5:ctx-e3780a57) (logid:7c4cc142) Transition:[Resource state = Disabled, Agent event = AgentConnected, Host id = 4, name = trl-65-k-M7-nvazquez-kvm4]
2019-10-04 05:23:12,248 DEBUG [c.c.a.m.AgentManagerImpl] …
```

[KVM] Agent LB Fix: Connections from disabled KVM host agents are refused

---

utils/src/main/java/com/cloud/utils/ssh/SSHKeysHelper.java

Signed-off-by: Kai Takahashi <k-takahashi@creationline.com>
See #3705 
Fixes: #3705 
Created a vm with ed25519 public key and I logged into it with ssh.

Add support for ecdsa and ed25519 public keys.

---

server/src/main/java/com/cloud/vm/UserVmManagerImpl.java

See #3744 
Signed-off-by: Kai Takahashi <k-takahashi@creationline.com>
Fixes: #3744 
Checked that SSH.PublicKey in user_vm_details is updated when I call resetSSHKeyForVirtualMachine API.

Save SSH.PublicKey into user_vm_details regardless of password management.

---

server/src/main/java/com/cloud/vm/snapshot/VMSnapshotManagerImpl.java

This patch changes the behaviour of `VMSnapshotManagerImpl.orchestrateCreateVMSnapshot(Long vmId, Long vmSnapshotId, Boolean quiescevm)` to rethrow the exception when `takeVMSnapshot()` fails, instead of returning null.
If null is returned, this will lead to a NullPointerException in `VMSnapshotManagerImpl.orchestrateCreateVMSnapshot(VmWorkCreateVMSnapshot work)` in the `snapshot.getId()` call, and causes an incomplete snapshot entry to remain in the database.
Fixes: #3518
See there for more details.
This change has not been tested yet.
At this point, it is unknown if it will cause unexpected side effects.

[FIX] Rethrow takeVMSnapshot() exception

---

engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/snapshot/CephSnapshotStrategy.java
engine/storage/snapshot/src/test/java/org/apache/cloudstack/storage/snapshot/CephSnapshotStrategyTest.java
plugins/storage/volume/default/src/main/java/org/apache/cloudstack/storage/datastore/driver/CloudStackPrimaryDataStoreDriverImpl.java

When deleting volume snapshots, only records in the database are deleted, and snapshots are not deleted on the main storage.
Fixes: #3586
Configuration:
```
snapshot.backup.to.secondary =false
kvm.snapshot.enabled =true
```
1. Create snapshots stored on Ceph/RBD primary storage.
2. Delete and assert that it has been removed on the RBD pool.
I was able to reproduce the issue #3586. After applying the packages with this fix, snapshots were properly removed from DB and deleted from the RBD storage pool.

Handle Ceph/RBD snapshot delete

---

api/src/main/java/com/cloud/host/HostStats.java
api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
api/src/main/java/org/apache/cloudstack/api/response/HostResponse.java
core/src/main/java/com/cloud/agent/api/GetHostStatsAnswer.java
core/src/main/java/com/cloud/agent/api/HostStatsEntry.java
plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtGetHostStatsCommandWrapper.java
plugins/hypervisors/kvm/src/main/java/org/apache/cloudstack/utils/linux/CPUStat.java
plugins/metrics/src/main/java/org/apache/cloudstack/metrics/MetricsServiceImpl.java
plugins/metrics/src/main/java/org/apache/cloudstack/response/HostMetricsResponse.java
server/src/main/java/com/cloud/api/query/dao/HostJoinDaoImpl.java

This adds the **load average for the kvm hypervisor**. The average Load already seems to be available for Xen.
In the _listHosts_ the [averageload](https://cloudstack.apache.org/api/apidocs-4.13/apis/listHosts.html) is already present. In _listHostMetrics_ it appears as "cpuloadaverage".
It adds the 1-min load average from /proc/loadavg to the
_listHosts
listHostsMetrics_
API calls.
Built and tested in kvm cluster.
Tested manually via API calls

Load Average for KVM

---

engine/components-api/src/main/java/com/cloud/ha/HighAvailabilityManager.java
server/src/main/java/com/cloud/ha/HighAvailabilityManagerImpl.java

This pull request adds the missing configuration keys for the High Availability service for virtual machines. (https://cwiki.apache.org/confluence/display/CLOUDSTACK/High+Availability+Developer%27s+Guide)
**Added keys (missing in the global configuration):**
time.between.cleanup
max.retries
time.to.sleep
time.between.failures
**Rename keys in the confluence document:**
ha.retry.wait -> restart.retry.interval
stop.retry.wait -> stop.retry.interval
workers -> ha.workers
- [x ] Enhancement (improves an existing feature and functionality)
We tested it in production in our KVM environment.

Add missing HA config keys

---

debian/control
packaging/centos7/cloud.spec
scripts/storage/secondary/cloud-install-sys-tmplt
scripts/storage/secondary/createtmplt.sh

* cloud-install-sys-tmplt: add function to calculate the virtual size of template for managed storage like netapp solidfire so that the copy process is working from NFS to iSCSI correctly
* add qemu-img (CentOS) / qemu-utils (Debian) packages to management build dependency
* refactor cloud-install-sys-tmplt to be more verbose and user friendly help
* createtmplt.sh: remove unused chksum flag
tested manually in our production environment with different files like vhd, qcow2 and ova

Fix virtual template size for managed storage for KVM / refactor cloud-install-sys-tmplt

---

api/src/main/java/com/cloud/resource/ResourceState.java
api/src/main/java/org/apache/cloudstack/api/command/admin/host/PrepareForMaintenanceCmd.java
engine/components-api/src/main/java/com/cloud/ha/HighAvailabilityManager.java
engine/components-api/src/main/java/com/cloud/resource/ResourceManager.java
engine/orchestration/src/main/java/com/cloud/agent/manager/AgentManagerImpl.java
engine/orchestration/src/main/java/org/apache/cloudstack/engine/datacenter/entity/api/db/EngineHostVO.java
engine/schema/src/main/java/com/cloud/host/HostVO.java
engine/schema/src/main/resources/META-INF/db/schema-41300to41400-cleanup.sql
server/src/main/java/com/cloud/ha/HighAvailabilityManagerImpl.java
server/src/main/java/com/cloud/ha/dao/HighAvailabilityDao.java
server/src/main/java/com/cloud/ha/dao/HighAvailabilityDaoImpl.java
server/src/main/java/com/cloud/resource/ResourceManagerImpl.java
server/src/main/java/com/cloud/server/StatsCollector.java
server/src/main/java/com/cloud/servlet/ConsoleProxyServlet.java
server/src/test/java/com/cloud/resource/MockResourceManagerImpl.java
server/src/test/java/com/cloud/resource/ResourceManagerImplTest.java
test/integration/smoke/test_host_maintenance.py
ui/scripts/metrics.js
ui/scripts/system.js

We want to update how host enters maintenance and it's states change. There have been instances when host was stuck in PrepareForMaintenance state indefinitely because all states weren't accounted for.
Also instead of moving direct to ErrorInMaintenance state on first fail, we want to wait for all legitimate operations to complete before entering ErrorInMaintenance state. If there are errors during in PrepareForMaintenance state, and errors are encountered, we enter the host into a transitory ErrorInPrepareForMaintenance state. This allows for better clarity if the operation had failed.
There are checks added to starting prepareHostForMaintenance. We should fail the API without any migration attempts if -
1. there are VMs in Starting, Error, Shutdown state on host or
2. if there are …

Better tracking host maintanence and handling of migration jobs

---

debian/control
packaging/centos7/cloud.spec
scripts/storage/secondary/cloud-install-sys-tmplt
scripts/storage/secondary/createtmplt.sh

The original PR #3371  was merged without Trillian tests being done, so I have reverted the merge by creating (via GitHub) the PR #3771 
Then, tests were done on the original PR 3371, showing NO regression (77 tests fine, 0 failed), so it is (with all the other LGTMs) safe to merge it after all.
I'm thus creating this PR which is the revert of the revert (3771) of the original PR 3371 - i.e. same PR as the original one.
Will run tests again and ask for LGTMs before finally merging it.

Revert of the "Revert "Fix virtual template size for managed storage for KVM / refactor cloud-install-sys-tmplt""

---

ui/scripts/sharedFunctions.js
ui/scripts/storage.js

see #3723 for details. backport after merging

create template from snapshot regression (partly reverted)

---

ui/scripts/network.js

replace significant chars from string to find protocol labels
Fixes: #3252

convert protocal names to be found as labels

---

server/src/main/java/com/cloud/vm/UserVmManagerImpl.java

skip hosts to query for volume stats based on their hypervisor type.
Fixes: #3596
Fixes: #3093
As this command is send to the hypervisor by a worker thread, the only thing that needs to happen is for it to be installed and the stacktrace that was in the agent.log on the kvm hosts, to not appear anymore.
on the agent:
```
2019-12-02 14:47:52,059 WARN  [cloud.agent.Agent] (agentRequest-Handler-2:null) (logid:0221a2bf) Caught:
com.cloud.utils.exception.CloudRuntimeException: Could not fetch storage pool 16758e2d-e971-3f1e-be90-f1409ad449da from libvirt
at com.cloud.hypervisor.kvm.storage.KVMStoragePoolManager.getStoragePool(KVMStoragePoolManager.java:256)
at com.cloud.hypervisor.kvm.storage.KVMStoragePoolManager.getStoragePool(KVMStoragePoolManager.java:242)
at …
```

filter hosts to query on zone wide storage

---

api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
api/src/main/java/org/apache/cloudstack/api/response/ConfigurationResponse.java
server/src/main/java/com/cloud/api/ApiResponseHelper.java
ui/scripts/globalSettings.js

Some configurations are dynamic so it does not require restart of mgt server when we change it.
Add isdynamic in configuration response, and does not pop up dialog "restart mgt server" if config is dynamic on UI.
Fixes: #3683 
Tested with global configuration "xen.vm.vcpu.max", it works fine (no pop up dialog).

config: add isdynamic flag in configuration response

---

server/src/main/java/com/cloud/template/TemplateManagerImpl.java

This fix adds a check if the iso belongs to the zone the virtual machine is in
Fixes: #3588
This was tested using cloudmonkey using the attach iso command.
A Cloudstack installation with 2 zones is required. 
I created an instance in the first zone and then uploaded an iso to the second zone.
When trying to attach the iso to the virtual machine in the first zone this error message is returned:
(localcloud) 🐱 > attach iso virtualmachineid=e1b6b77b-df84-4d5e-998a-d7283e5f4f21 id=326c0c96-db4f-4e01-924e-2eac50e0420e 
{
"accountid": "4c71abb8-1a54-11ea-a067-000c29a1fe4f",
"cmd": "org.apache.cloudstack.api.command.admin.iso.AttachIsoCmdByAdmin",
"completed": "2019-12-09T12:02:43+0200",
"created": "2019-12-09T12:02:43+0200",
"jobid": "971ce126-7d8c-4ea0-ba3f-5cbbcdbf750f", …

Added zone check for attach iso

---

api/src/main/java/com/cloud/network/NetworkService.java
api/src/main/java/org/apache/cloudstack/api/command/user/address/AssociateIPAddrCmd.java
engine/components-api/src/main/java/com/cloud/network/IpAddressManager.java
plugins/network-elements/cisco-vnmc/src/main/java/com/cloud/network/element/CiscoVnmcElement.java
server/src/main/java/com/cloud/network/IpAddressManagerImpl.java
server/src/main/java/com/cloud/network/NetworkServiceImpl.java
server/src/test/java/com/cloud/vpc/MockNetworkManagerImpl.java
test/integration/component/test_acquire_specified_public_ip.py
tools/marvin/marvin/lib/base.py
ui/scripts/network.js

Currently in cloudstack, when we click on "Acquire New Ip", it will
randomly acquire IP from the pool. With this enhancement, it is
possible to select the IP from the drop down IP list of that network.
Same thing applies for a VPC as well.
1 . Navigate to "Networks" section in the main UI
2 . Select any network from the list.
3 . Click on "View IP address" button.
4 . Now click on "Acquire New IP" button on the top right. This will open up a new pop up window with drop down list of all IP address belonging to that network
5 . Select any of the IP address.

New feature: Acquire specific public IP for network

---

engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java

When remove a nic from vm, the dhcp/dns entries should be removed from virtual routers.
this fixes : #3706 
The dhcp/dns entries are applied in virtual routers when 
(1) deploy a vm
(2) add a new nic to vm
(3) remove nic from vm
(4) expunge vm
above all are tested ok

network: cleanup dhcp/dns entries while remove a nic from vm

---

ui/css/cloudstack3.css

Fixes truncated name for accounts in project details UI
Existing behaviour,
While Accounts page table showed the complete name,
UI after changes,
UI

ui: fix for truncated name for project accounts

---

plugins/hypervisors/simulator/src/main/java/com/cloud/agent/manager/MockVmManagerImpl.java

Before this change, when creating a HA network in the Simulator, both Routers would be in BACKUP mode.  Many years ago in f0c3b4c62a7a1a440d723696d61b42dad58f6faf, logic was added to allow the line "router_pr=100" to be added to the bootargs field of mockvm in the Simulator database to allow a VR to become MASTER.  This doesn't work automatically (nowhere sets it) and actually fails because the field is too short, and no other statuses can be simulated.
With this PR, Redundant State now comes from the "redundate_state=MASTER" part in bootargs, which is already populated.  
Additionally, the Start/Reboot/Stop VM code of the simulator now incldues logic to change the redundant state:
* When Starting a VR, if no other VRs are Running and MASTER on this network, become MASTER
* When Stopping …

Simulator: Better VR Redundant Status Behaviour

---

debian/control
packaging/centos7/cloud.spec
scripts/vm/systemvm/injectkeys.sh

Signed-off-by: Kai Takahashi <k-takahashi@creationline.com>
Extract systemvm.iso using bsdtar in injectkeys.sh if available.
With bsdtar, injectkeys.sh doesn't need to mount systemvm.iso and works even on unprivileged containers.
Checked that a new key is injected to systemvm.iso by running injectkeys.sh manually.

Extract systemvm.iso using bsdtar

---

engine/orchestration/src/main/java/com/cloud/agent/manager/AgentManagerImpl.java
engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
engine/orchestration/src/main/java/com/cloud/vm/VirtualMachinePowerStateSyncImpl.java
engine/schema/src/main/java/com/cloud/vm/dao/VMInstanceDao.java
engine/schema/src/main/java/com/cloud/vm/dao/VMInstanceDaoImpl.java
plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java

On update powerstate check if we have the latest knowledge before doing so.
When report is missing don't try to stop the VM on the host that doesn't know the VM.
Fixes: #3741 
This is purely based on log- and code analysis. intensiove review is requested. Also advise on environmental consequences is welcomed.
HA may be impacted do I suspect not in a negative way.

only update powerstate if sure it is the latest

---

plugins/hypervisors/simulator/src/main/java/com/cloud/agent/manager/MockVmManagerImpl.java

Reverts apache/cloudstack#3313
@richardlawley it seems your PR gives unexpected CI problems, we have to revert. can you investigate and re-submit?

Revert "Simulator: Better VR Redundant Status Behaviour"

---

api/src/main/java/org/apache/cloudstack/api/command/user/securitygroup/AuthorizeSecurityGroupIngressCmd.java
scripts/vm/network/security_group.py
server/src/main/java/com/cloud/network/security/SecurityGroupManagerImpl.java
test/integration/component/test_protocol_number_security_group.py
ui/scripts/network.js

Currently while creating ingress/egress rule for a security group,
we can specify only TCP/UDP/ICMP. Sometimes we need to add rules
for different protocol numbers or rules for all the above three
mentioned protocols.
In this new feature, users can specify the protocol number or select
"ALL" option which will apply rules for TCP/UDP/ICMP in one shot
Navigate to "Networks" and select "Security groups" from the drop-down menu on the top left
Select any security group name and click on either "ingress" or "egress" tab
Adding a rule for a particular protocol number
1. Create a VM and note down the security group name to which it belongs to
2. Navigate to "Network" and select "Security groups" from the drop-down menu on the top left.
3. Select the security group which is obtained from step 1. …

Add protocol number support for security group rules

---

debian/control
packaging/centos7/cloud.spec
scripts/vm/systemvm/injectkeys.sh

This reverts commit 8a55c931e806a64f7f00153d4a58c4463caa7a47.

Revert "Extract systemvm.iso using bsdtar (#3536)"

---

api/src/main/java/com/cloud/vm/VirtualMachine.java
engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
engine/schema/src/main/resources/META-INF/db/schema-41300to41400.sql
plugins/network-elements/juniper-contrail/src/main/java/org/apache/cloudstack/network/contrail/model/VirtualMachineModel.java
server/src/main/java/com/cloud/consoleproxy/ConsoleProxyManagerImpl.java
server/src/main/java/com/cloud/storage/snapshot/SnapshotManagerImpl.java
ui/scripts/instances.js
ui/scripts/metrics.js

Fix typo: the past tense of shutdown is shutdown, not shutdowned

---

server/src/main/java/org/apache/cloudstack/agent/lb/IndirectAgentLBServiceImpl.java

If a host is not in the list of hosts and an agent load balancing list is required for it, add it to the list to get a valid MSlist.
Fixes: #3722

Agent lb on svm

---

scripts/vm/systemvm/injectkeys.sh
server/src/main/java/com/cloud/server/ConfigurationServerImpl.java

When the injectkeys.sh script runs, if the public ssh key is the same as the authorized_keys file inside the extracted systemvm.iso - then the public ssh key files is NOT copied over and the systemvm.iso is not modified - message added to explain just that.
Also, after the injectkeys.sh is run/finished, from the Java code we currently generate a wrong message that the private key has also been injected (we don't inject it, only the public key) - and in general sometimes NOTHING is injected - so changed the messages accordingly.
Restarted the mgmt server for an existing installation, injectkeys.ssh was run, and confirmed that the systemvm.iso is NOT modified, same modification date, same md5sum as before.
Message properly logged in the mgmt logs, as follows:
> 2020-01-09 22:28:08,777 DEBUG …

Update message when keys are NOT being injected

---

ui/scripts/network.js

Instead of "SSL" being set as a default LB protocol when configuring a LB rule, set TCP as the default one - move SSL to the bottom of the list.
Reason: SSL is supported only with NetScaller and should not even be there if VPC is not using NetScaller for LB services... so stop offering it as the default protocol and confusing VPC VR (i.e. non-NesScaller) users
Old setup:
New setup:

set TCP as default protocol in lb list

---

server/src/main/java/com/cloud/vm/UserVmManagerImpl.java

(1) create an account (test)
(2) create a vm with the account (test)
(3) login with admin, and upgrade the vm to another offering
(4) the resource count (cpu,memory) of admin increases, not the account (test).

server: fix resource count error when upgrade a vm

---

test/integration/smoke/test_global_settings.py

Causes failure in travis. The incorrect param was returning no value back and causing test to fail.
Ran the Marvin test locally on CentOS based monkeybox env and verified test failed without change and succeeded with change.

Incorrect param name caused global setting test to fail

---

systemvm/debian/etc/apache2/vhost.template
systemvm/debian/opt/cloud/bin/configure.py
systemvm/debian/opt/cloud/bin/cs/CsAddress.py
systemvm/debian/opt/cloud/bin/cs/CsApp.py
systemvm/debian/opt/cloud/bin/cs/CsDhcp.py
systemvm/debian/opt/cloud/bin/cs/CsFile.py
systemvm/debian/opt/cloud/bin/cs/CsHelper.py
systemvm/debian/opt/cloud/bin/cs/CsRedundant.py
systemvm/debian/opt/cloud/bin/passwd_server_ip.py
systemvm/debian/opt/cloud/bin/setup/secstorage.sh

When we create a vm in the network with redundant VRs, the lease file in the vm (for example /var/lib/dhcp/dhclient.eth0.leases) shows the dhcp-server-identifier is the guest ip (not vip/gateway) of master VR. That's the ip ipaddress where the vm fetch password and metadata from.
if we stop the master VR (then backup will be master) or restart the network with cleanup (VRs will be created), the guest ip of master VR changes so vm are not able to get metadata/ssh-key using the ips in dhcp lease file.
Setting up metadata/password/dhcp server on gateway instead of guest IP in redundant VRs will fix the issues.
FIxes: #3409

RvR: Set up metadata/password/dhcp server on gateway IP instead of guest IP in RVR

---

engine/schema/src/main/java/com/cloud/vm/dao/VMInstanceDaoImpl.java
server/src/main/java/com/cloud/capacity/CapacityManagerImpl.java

When we calculate a resource consumption of a host, we need to take the vms in following states into calculation: Running, Starting, Stopping, Migrating (to the host), and vms are Migrating from the host. Because, when stop a vm, the resource on host will be released when vm is stopped. When migrate a vm, the resource on destination host will be increased before migration starts, and resource on source host will be decreased after migraiton succeeds. 
In cloudstack, there is a task named CapacityChecked which run every 5 minutes (capacity.check.period =300000 ms by default). It recalculates capacity of all hosts. However, it takes only vms in Running and Starting into consideration. We have faced some issues in host maintenance due to it.
(1) migrate N vms …

server: Capacity check should take vms in Migrating state into calculation

---

engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
server/src/main/java/com/cloud/capacity/CapacityManagerImpl.java

When start a vm or migrate a vm (away from a host in host maintenance), cloudstack will check capacity of all hosts and choose one. If there are hundreds of hosts on the platform, it will take some seconds. When cloudstack choose a host and start/migrate vm to it, the resource consumption of the host might have been changed. This normally happens when we start/migrate multiple vms.
It would be better to double check the host capacity when start vm on a host.
This PR includes the fix for cpucore capacity when start/migrate a vm.
start multiple vms on a host
put a host to maintenance so multiple vms will be migrated at same time
check the resource count of cpucore, all looks good.

server: double check host capacity when start/migrate a vm

---

server/src/main/java/com/cloud/vm/UserVmManagerImpl.java

(1) create a custom service offering
(2) create a vm with the offering
(3) update vm with displayvm=false, returns an error
(local) > update virtualmachine id=f33fd06a-7643-40d1-833f-272845d9ba09 displayvm=false
Error 530: {"updatevirtualmachineresponse":{"uuidList":[],"errorcode":530,"cserrorcode":9999}}

server: Fix NPE while update displayvm on vm with dynamic service offering

---

server/src/main/java/com/cloud/vm/snapshot/VMSnapshotManagerImpl.java

Backport of #3546 to 4.13: Rethrow takeVMSnapshot() exception instead of returning null in VMSnapshotManagerImpl.
Contributes to: #3518
The change has been tested on the master branch for 4.14. See #3546.

[FIX] [BACKPORT] [4.13] Rethrow takeVMSnapshot() exception

---

engine/schema/src/main/resources/META-INF/db/schema-41300to41400-cleanup.sql

Stop asking user (in the upgrade documentation) to remove a trailing slash for local KVM pool - do it here in upgrade path - so not needed in DOC for the upgrade to 4.14 and onwards.

kvm-local-pool-trailing-slash

---

tools/docker/README.md

Fix typo in the Docker README file

Update Docker README file

---

tools/travis/before_install.sh

Travis has been failing lately as it requires that repositories use
https:// URLs.
Reference:
https://blog.sonatype.com/central-repository-moving-to-https
Without this fix all PRs are blocked from testing for 4.11+ branches.

travis: use https based maven repo mirror

---

ui/css/cloudstack3.css

This pull request adds a scroll bar to the domain settings page that will allow a user to scroll to the right to change settings.
Fixes: #3032
From the UI click on domain and then navigate to the settings tab. You are now able to scroll right to change the settings.

Fix for "Impossible to edit domain settings in UI"

---

systemvm/debian/opt/cloud/bin/cs/CsLoadBalancer.py

since 4.11.3, haproxy is always restarted when add/delete a lb rule.
When haproxy is started, the processes are
```
root@r-854-VM:~# ps aux |grep haproxy
root     22272  0.0  0.2   4036   668 ?        Ss   07:52   0:00 /usr/sbin/haproxy-systemd-wrapper -f /etc/haproxy/haproxy.cfg -p /run/haproxy.pid
haproxy  22274  0.0  2.3  38444  5856 ?        S    07:52   0:00 /usr/sbin/haproxy-master
haproxy  22275  0.0  0.3  38444   880 ?        Ss   07:52   0:00 /usr/sbin/haproxy -f /etc/haproxy/haproxy.cfg -p /run/haproxy.pid -Ds
```
When haproxy is reload, the processes are
```
root@r-854-VM:~# ps aux |grep haproxy
root     22272  0.0  0.2   4168   632 ?        Ss   07:52   0:00 /usr/sbin/haproxy-systemd-wrapper -f /etc/haproxy/haproxy.cfg -p /run/haproxy.pid
haproxy  22283  0.0  2.3  38444  5884 …
```

vrouter: reload haproxy when cfg file is updated

---

systemvm/debian/opt/cloud/bin/cs/CsHelper.py
systemvm/debian/opt/cloud/bin/cs/CsRedundant.py

This fixes similar issue with #3465 
Meanwhile change log level of CsHelper.execute2 from DEBUG to INFO and fix some typo

vr: fix vr in unknown state (more)

---

api/src/main/java/org/apache/cloudstack/api/response/ClusterResponse.java
api/src/main/java/org/apache/cloudstack/api/response/HostResponse.java
api/src/main/java/org/apache/cloudstack/api/response/VolumeResponse.java
api/src/main/java/org/apache/cloudstack/api/response/ZoneResponse.java
server/src/main/java/com/cloud/api/query/dao/DataCenterJoinDaoImpl.java
server/src/main/java/com/cloud/api/query/dao/HostJoinDaoImpl.java
server/src/main/java/com/cloud/api/query/dao/VolumeJoinDaoImpl.java

The metrics API has few properties missing that are present in the corresponding resource. This addressed the following issue: https://github.com/apache/cloudstack/issues/3831

Fix: The metrics view API response is not super-set of resources response keys

---

api/src/main/java/org/apache/cloudstack/api/command/admin/management/ListMgmtsCmd.java
api/src/main/java/org/apache/cloudstack/management/ManagementServerHost.java
server/src/main/java/com/cloud/api/query/QueryManagerImpl.java

The List Management Server api returns a list of all the management servers but fails when trying to list by id or name. This ensures that it fetches the details as per the parameters passed.
Fixes: #3833
Verified by testing the api with and without parameters

Fix listing management server by parameters

---

engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java

After restarting the network with or without cleanup option, the ```restart_required``` field in ```networks``` table should be reset to 0
1 . Check if the ```restart_required``` field in the ```networks``` table is 1 or not. If not you can set it to 1
2 . Restart the network with or without cleanup option.
3 . The ```restart_required``` field in the ```networks``` table should be reset to 0 once the network restarts successfully.

Bug fix : set restart_required to 0 after restarting network

---

systemvm/debian/opt/cloud/bin/configure.py

We noticed that VMs that are target of a static nat cannot use private gateways.
Investigation showed that these VMs behave differently than all other VMs in a VPC because their whole traffic gets marked and is only allowed to leave through the public ip provided by the static nat.
Could be related to: https://github.com/apache/cloudstack/pull/3366
Maybe @richardlawley @rhtyd can contribute if this is an unwanted side-effect.
To not break anything we propose a solution that does only mark the nat portion of the traffic and allow the VM use the private gateway like normal.
We built and manually tested this to check if function is restored and nothing else breaks.

Fix Policy Based Routing for private gateway static routes

---

plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/IscsiStorageCleanupMonitor.java

Previously, iscsi sessions would not be cleaned up on KVM when
* vms are crashed or rebooted on another host
* a hypervisor host crashed and ha enabled vms
This leads to to long boot times from the hypervisor host and session overloading of the netapp solidfire nodes. Each node can have a maximum of 700 iSCSI sessions. The iSCSI Daemon on the hypervisor host holds iSCSI sessions that are not cleaned up. The iSCSI Daemon tried to reconnect every time resulting in holding the unused sessions. Only a logout of the iSCSI daemon to the volume will solve the problem. This changes adds a kvm.storage.IscsiStorageCleanupMonitor class that scans for and cleans up inactive iscsi sessions.
steps to reproduce:
1. check there are a vm is running and sessions to Netapp Solidfire are there ```ìscsiadm -m …
```

Clean up inactive iscsi sessions when VMs get moved due to crashes

---

engine/storage/image/src/main/java/org/apache/cloudstack/storage/image/TemplateServiceImpl.java
server/src/main/java/com/cloud/storage/download/DownloadMonitorImpl.java
server/src/main/java/com/cloud/template/TemplateManagerImpl.java
services/secondary-storage/server/src/main/java/org/apache/cloudstack/storage/template/DownloadManagerImpl.java
utils/src/main/java/org/apache/cloudstack/utils/security/ChecksumValue.java

Fixes #3191 
When a template is registered, code stores md5sum of the downloaded file in the `vm_template` table. However, this downloaded file could be deleted after template installation if it is not an actual (`.qcow2`, `.ova`, etc.) file. When the user copies a template using copyTemplate API, the actual template file will be copied across the image stores. Matching checksum for the copied templated file and the stored value from the `vm_template` table will result in a mismatch.
Changes will set an empty checksum value for the copied template while passing to download service which allows skipping wrong checksum check for the copied while install.
However, this results in a change in checksum value for concerned template entry in `vm_template` table post template install.
cmk

template: copy md5 mismatch

---

agent/bindir/libvirtqemuhook.in

In VM migration on KVM, libvirt qemu hook script will change the bridge name to bridges for guest networks. It works for user vm. However for virtual router, it has nics on control network and public network. If control/public use different physical networks than guest network, virtual router cannot be migrated.
Fixes: #2783 
We have more than 1 physical networks and faced same issue before.
We have this change to fix the issue in old cloudstack versions. 
I did not test in latest master or 4.13 but I believe it should work as well.

kvm: Fix router migration issue when router has control/public nics onother physical network than guest

---

ui/scripts/ui/widgets/listView.js

This fixes the issue that cannot assign VMs in Internal LB in VPC.
listView is overwritten due to commit 2e2b670 (#3161)
Fixes: #3827

ui bug fix: cannot assign vms to internal lb in VPC

---

server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java

Fixes #3783
As reported in the issue, creating volumes from pure snapshot fails with NPE. This is due to order of calls where disk offering access is checked before checking disk offering value. This PR fixes the same.

server: fix checking disk offering access for snapshot volume

---

engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/VolumeOrchestrator.java

If the disk size of the VM to be created is greater
then the volume size, then the exception message should
display the numeric value instead of the variable name
Below is the exception which is thrown when error happens while creating a VM
After the fix, below is the message which is displayed
Set the global setting ```custom.diskoffering.size.max``` to lower value and try to create a vm with disk size greater the value of setting ```custom.diskoffering.size.max```

Display numeric value in exception instead of variable name

---

.travis.yml
engine/schema/src/main/java/com/cloud/network/dao/NetworkDao.java
engine/schema/src/main/java/com/cloud/network/dao/NetworkDaoImpl.java
server/src/main/java/com/cloud/network/NetworkServiceImpl.java
server/src/test/java/com/cloud/vpc/dao/MockNetworkDaoImpl.java
test/integration/smoke/test_create_network.py

Add a global setting to disable creating networks with
same name in an account
Add a global setting to disable creating network without
mentioning the start and end IPv4 or IPv6 address
By default we can create networks with the same name in the account. Sometimes we should not create the networks with same name. This change adds a global setting which prevents creating the network with same name. The default value is true and set it to false to prevent creating network with same names.
Also its possible to create a shared network without mentioning the start and the end IPv4 or IPv6 address. This change adds a global setting which prevents creating a shared network without specifying the start and the end IPv4 or IPv6 address
Creating a network with same names
1 . Set the global setting …

Enhancement: Allow creating network with duplicate name

---

server/src/main/java/com/cloud/network/rules/RulesManagerImpl.java

Associating static NAT on IP to VM fails even though the IP is not allocated.
When we try enable static NAT on second IP address to the same VM, the operation fails but the IP address is still allocated in the db and it can't be used to enable static NAT on different VM.
(1) create a vpc (vpc-001) and a vpc tier (vpc-001-001)
(2) create a vm (vm-001-001) in vpc-001-001
(3) acquire a public ip (ip-1) and enable static nat to vm-001-001,
operation succeeds.
(4) acquire a second public ip (ip-2) and enable static nat to the same vm vm-001-001.
The operation fails but the ip is still assigned to vpc tier vpc-001-001.
Note down the ip address and the id of it.
(5) create another vpc vpc-002, vpc tier vpc-001-002, and vm (vm-001-002) in the second tier
(6) enable …

Bug fix: De-associate IP address if enabling static nat fails

---

server/src/main/java/com/cloud/network/router/NetworkHelperImpl.java
server/src/main/java/com/cloud/network/router/VpcVirtualNetworkApplianceManager.java
server/src/main/java/com/cloud/network/router/VpcVirtualNetworkApplianceManagerImpl.java
server/src/test/java/com/cloud/vpc/MockVpcVirtualNetworkApplianceManager.java

When we restart the VPC after destroying the master VR, the backup VR
becomes the master and the site to site connections are not in
the connected state. The passive VPN connection will be in the connected
state but the active VPN connection will be in a disconnected state
1 . Create two VPC's. Configure VPN customer gateway and VPN connection. The steps are clearly explained in [here](https://docs.cloudstack.apache.org/projects/cloudstack-administration/en/4.8/networking/site_to_site_vpn.html#site-to-site-vpn-connection-between-vpc-networks)
2 . Once everything is setup properly make sure that the VPN state is "Connected" in both VPC.
3 . Now navigate to "Infrastructure" → "Virtual Routers"
4 . Search for the routers which belong to one of the VPC created …

Start all (instead of Disconnected) Site-to-Site VPN connections when VPC VR starts

---

server/src/main/java/com/cloud/storage/ImageStoreUploadMonitorImpl.java

After a local template is uploaded via browser, the generated usage event with type = "TEMPLATE.CREATE" is persisted with the data store ID instead of the zone ID on the zone_id column. The fix will refactor the upload monitor logic, as after the upload completes, it sets the datastore ID on the zone ID column for the created "TEMPLATE.CREATE" usage event. This refactor will query the DB for the data store and will set its associated zone ID in the usage field.
The fix produces the same behaviour as when registering a template from URL.
FIx is also for uploading VOLUME from local/via browser.

Usage event to store zone id while uploading template and volume

---

engine/schema/src/main/java/com/cloud/network/vpc/dao/VpcGatewayDao.java
engine/schema/src/main/java/com/cloud/network/vpc/dao/VpcGatewayDaoImpl.java
server/src/main/java/com/cloud/network/NetworkModelImpl.java
server/src/main/java/com/cloud/network/router/CommandSetupHelper.java

In VPC, the private gateway has traffic type as Guest not Public.
This leads to keepalived misconfiguration in VPC with redundant VRs.
There are some commits (eg 65cb22216aa1d5d6257f99d4ad84f80c319cdea9 and f4f9b3ab4ef2ef34e4d8a04c6ebfbf0784497227) for this issue, however the issue still exists in 4.13 and 4.14.
Simply setting the traffic type of ip address (of private gateway) to Public fixes the issue.
Fixes: #3402 
Before change,
In VPC master VR (redundant), IP of private gateway is added in keepalived, and gateway of private gateway is also added to ethX which is obviously wrong. 
nw_type of ethX is 'guest' in /etc/cloudstack/ips.json
```
root@r-181-VM:~# grep virtual_ipaddress /etc/keepalived/keepalived.conf -A5
virtual_ipaddress {
10.11.112.254/24 brd 10.11.112.255 dev eth6 …
```

vpc: set traffic type of private gateway IP to Public to fix keepalived misconfiguration

---

systemvm/debian/opt/cloud/bin/configure.py

When create a port forwarding rule to a vm in vpc, we cannot access the port forwarding rule from inside the vm.
Steps to reproduce
(1) create a port forwarding rule in VPC, public ip X.X.X.X to vm Y.Y.Y.Y port 22
(2) ssh to vm, or login vm console
(3) in vm, ssh X.X.X.X does not work.
Fixes: #3763
with this change, the public Ip is reachable from inside vm in step (3) above.

vr: add missing rule for port forwarding rule in vpc

---

ui/scripts/ui-custom/instanceWizard.js

This PR fixes the missing "Default" display issue on the instance wizard when selecting a network.
Fixes: #3633 
This has been tested from the UI. First make sure that there are some available networks. 
From the create instance wizard, complete all the steps until the network page. The text next to the radio button will read "Default".

Fixed default text missing from network selection on instance wizard

---

debian/control
packaging/centos7/cloud.spec

Install python-dnspython or python-dns to fix issue with cloudstack-setup-management

---

server/src/main/java/org/apache/cloudstack/storage/NfsMountManagerImpl.java
services/secondary-storage/server/src/main/java/org/apache/cloudstack/storage/resource/NfsSecondaryStorageResource.java
services/secondary-storage/server/src/main/java/org/apache/cloudstack/storage/template/DownloadManagerImpl.java

As per discussion at #3838 and proposal by @weizhouapache this PR implements the fix.
#3838 
tested manually

ISSUE-3838: Wrong SSVM behavior causes redownloading for all the templates

---

api/src/main/java/org/apache/cloudstack/api/response/SystemVmResponse.java
server/src/main/java/com/cloud/api/ApiResponseHelper.java
ui/scripts/system.js

This makes the listSystemVms API to return the host status (agent state),
version and last pinged information. This makes it possible for UIs
to call a single API to get this information.
This is largely for Primate.

systemvm: list systemvm does not return agent state and version

---

api/src/main/java/org/apache/cloudstack/api/response/SystemVmResponse.java
server/src/main/java/com/cloud/api/ApiDBUtils.java
server/src/main/java/com/cloud/api/ApiResponseHelper.java

This implements the systemvm list API response creator to find and use
the host record for a ssvm/cpvm to get the agent status and other
details like last disconnected date and agent version.
Fixes #3875

server: use host record related to a ssvm/cpvm

---

client/pom.xml
plugins/network-elements/juniper-contrail/pom.xml

[![mitm_build](https://user-images.githubusercontent.com/1323708/59226671-90645200-8ba1-11e9-8ab3-39292bef99e9.jpeg)](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Update: Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/bugbountywriteup/update-want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-d069d253fe23?source=friends_link&sk=8c8e52a7d57b98d0b7e541665688b454)
---
This is a security fix for …

[SECURITY] Use HTTPS to resolve dependencies in Maven Build

---

ui/scripts/storage.js

This PR fixes the volume resize action for a root volume from the UI.
Fixes: #3860 #3874
This has been tested by creating an instance and resizing the root volume. The root volume size is then verified in storage metrics.

Fixed root volume resize from ui

---

framework/jobs/src/main/java/org/apache/cloudstack/framework/jobs/impl/AsyncJobManagerImpl.java

This PR removes related VMWorkjob records when the async_job table is cleaned out.
Fixes: #3829 
This was tested by taking these steps:
* Create an instance.
* Check the async_job and vm_work_job table for matching rows.
* Set the job.expire.minutes global setting to 1 minute.
* Wait a minute.
* Check the async_job and vm_work_job table for matching rows to be removed.

Fixed duplicate id error when creating VM work jobs

---

plugins/hypervisors/simulator/src/main/java/com/cloud/agent/manager/MockStorageManagerImpl.java
test/integration/smoke/test_vm_life_cycle.py

simulator: fix travis failure after merging volume destroy/recover 

---

server/src/main/java/com/cloud/network/router/VirtualNetworkApplianceManagerImpl.java

When the state of the site to site vpn changes, the check
is done on all the virtual routers including the internal
load balancing vm as well. It is not needed to check the
state for internal load balancing vm
Steps to reprodcue the issue
1 . Create two VPC's. Configure VPN customer gateway and VPN connection. The steps are clearly explained [here](https://docs.cloudstack.apache.org/projects/cloudstack-administration/en/4.8/networking/site_to_site_vpn.html#site-to-site-vpn-connection-between-vpc-networks)
2 . Now navigate to networks section in main cloudstack ui. In the drop down menu select VPC. Click configure on one of the VPC
3 . Click on "Create Network" and create a tier with "DefaultisolatedNetworkOfferingForVPCNetworksWithInternalLB" network offering
4 . Once the tier is created …

Ignore site to site vpn status check on internallbvm

---

server/src/main/java/com/cloud/server/StatsCollector.java

on kvm, the 'path' of volume is the file name on primary storage. we should use 'path' instead of 'uuid' in volume statistics.
Fixes: #3878 
1. storage migration
2. volume statistics every 10 minutes (default)

kvm: fix exception in volume stats after storage migration

---

.travis.yml
api/src/main/java/com/cloud/event/EventTypes.java
api/src/main/java/com/cloud/network/security/SecurityGroupService.java
api/src/main/java/org/apache/cloudstack/api/command/user/securitygroup/UpdateSecurityGroupCmd.java
engine/schema/src/main/java/com/cloud/network/security/SecurityGroupVO.java
server/src/main/java/com/cloud/network/security/SecurityGroupManagerImpl.java
server/src/main/java/com/cloud/server/ManagementServerImpl.java
test/integration/smoke/test_update_security_group.py
ui/scripts/network.js

By default, once we create a security group we cant change its name.
In this feature, we introduce a new API command "updateSecurityGroup"
which allows us to rename the security group name. Although we can't
change the name of the "default" security group.
Navigate to "Network" section in the main window and select "Security groups" from the drop-down menu in the top left section
Click on "Add Security group" to create a new security group
Once the security group is created you can rename it using the edit button
1. Navigate to "Network" tab in the main UI.
2. Select "Security groups" from the drop-down menu in the top left.
3. Click on "Add Security group" on the top right to create a new security group.
4. Give any suitable name and create it.
5. Now select the security group you just …

Add new command to update security group name

---

server/src/main/java/com/cloud/hypervisor/KVMGuru.java

When we add new guest os, sometimes we missed the records in guest_os_hypervisor. 
However, the guest disk model (virtio/ide) is determined by record in the table.
It causes the issue that some new guest os(eg Debian 8/9) uses e1000 instead of virtio nic, and ide disk instead of virtio disk.
To fix the issue permanantly, pass the guest os name in guest_os if the record for kvm is not found in guest_os_hypervisor.
Related commit:7ac9f00eeeb4cd37ec39efeba066e799b581b1a0

kvm: Enable virtio drivers based on guest os display name

---

engine/components-api/src/main/java/com/cloud/agent/AgentManager.java
engine/orchestration/src/main/java/com/cloud/agent/manager/AgentManagerImpl.java
framework/agent-lb/src/main/java/org/apache/cloudstack/agent/lb/IndirectAgentLB.java
plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtSetHostParamsCommandWrapper.java
server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
server/src/main/java/org/apache/cloudstack/agent/lb/IndirectAgentLBServiceImpl.java
server/src/test/java/org/apache/cloudstack/agent/lb/IndirectAgentLBServiceImplTest.java
server/src/test/resources/createNetworkOffering.xml

When we change a global setting and it needs to be applied to all kvm agents, it would be nice that the new value can be propagated to all kvm agents (and save in agent.properties if needed) so we do not need to manually restart cloudstack agent or change agent.properties.
it supports only "router.aggregation.command.each.timeout" for now.
In the future, it would be good to add a new column in "configurations" table to determine whether the configuration needs to be propagated to kvm agents.
(1) change router.aggregation.command.each.timeout in global setting
(2) check agent.properties to see if the value is changed as well.

KVM: Propagating changes on host parameters to the agents

---

core/src/main/java/com/cloud/agent/api/RebootCommand.java
core/src/main/java/com/cloud/agent/api/SecurityGroupRulesCmd.java
engine/components-api/src/main/java/com/cloud/network/security/SecurityGroupManager.java
engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
engine/schema/src/main/java/com/cloud/vm/dao/NicDao.java
engine/schema/src/main/java/com/cloud/vm/dao/NicDaoImpl.java
plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtNetworkRulesVmSecondaryIpCommandWrapper.java
plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtPlugNicCommandWrapper.java
plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtRebootCommandWrapper.java
plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtSecurityGroupRulesCommandWrapper.java
plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtStartCommandWrapper.java
plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtUnPlugNicCommandWrapper.java
plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java
scripts/vm/network/security_group.py
server/src/main/java/com/cloud/network/security/SecurityGroupManagerImpl.java
server/src/main/java/com/cloud/network/security/SecurityGroupManagerImpl2.java
server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
test/integration/component/test_multiple_nic_support.py
tools/marvin/marvin/lib/utils.py
ui/scripts/instanceWizard.js
ui/scripts/instances.js
ui/scripts/network.js
ui/scripts/ui-custom/instanceWizard.js

In advanced zone with security groups, there can be multiple shared networks with security groups enabled. However, it is only possible to create vm with only one network. When we try to create vm with multiple networks, it gives error "Only support one network per VM if security group enabled".
Operations succeed if we create a vm with one network and add other networks to the vm. However, the new nics do not work as there are no network rules for them applied on hypervisor.
This PR will enable the functionality on KVM hypervisors, including the support on
(1) API to support vm with multiple networks for KVM
(2) UI to create vm with multiple networks for KVM
(3) network rules applied on all nics (when create a vm, and add/remove nics)
(4) network rules for all secondary ips on all nics …

Multiple networks support for vms in advanced zone with security group (and kvm support)

---

server/src/main/java/com/cloud/network/router/VirtualNetworkApplianceManagerImpl.java

When the network service offering of a network is changed from
"defualt deny" to "default allow", the ping from VM to outside
world is stopped even after adding egress rule.
If the default policy is allow then the ping should never stop
working
1 . Create a network offering with static nat enabled and default policy as "DENY"
2 . Create a vm in it and try to ping 8.8.8.8 from the vm
3 . Ping will fail
4. Now add an ICMP egress rule with code -1
5. Try to ping 8.8.8.8 from vm and this time ping will work
6. Add or remove any other egress rule and the ping should still work
7. Now create a new network offering with static nat enable and default egress policy as "ALLOW"
8. Change the network offering of the above created network to the newly created network …

Fix network rules issue if default egress policy is Allow

---

api/src/main/java/com/cloud/network/NetworkService.java
api/src/main/java/com/cloud/network/vpc/VpcService.java
api/src/main/java/org/apache/cloudstack/api/command/admin/vpc/CreatePrivateGatewayCmd.java
engine/api/src/main/java/org/apache/cloudstack/engine/orchestration/service/NetworkOrchestrationService.java
engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
engine/schema/src/main/java/com/cloud/network/dao/NetworkDao.java
engine/schema/src/main/java/com/cloud/network/dao/NetworkDaoImpl.java
server/src/main/java/com/cloud/network/NetworkServiceImpl.java
server/src/main/java/com/cloud/network/vpc/VpcManagerImpl.java
server/src/test/java/com/cloud/network/CreatePrivateNetworkTest.java
server/src/test/java/com/cloud/vpc/MockNetworkManagerImpl.java
server/src/test/java/com/cloud/vpc/dao/MockNetworkDaoImpl.java
test/integration/smoke/test_privategw_acl.py
tools/marvin/marvin/lib/base.py
ui/scripts/vpc.js

The vlan of private gateways in VPCs should not be same. In some edge cases, vlan of private gateways are same (for example in test_privategw_acl.py).
Similar as shared network, add bypassvlanoverlapcheck parameter when create private gateway.
This also fixes #3859 .
the root cause is https://github.com/apache/cloudstack/issues/3859#issuecomment-585608028
Run test_privategw_acl.py several times, no failure any more.

vpc: add bypassvlanoverlapcheck parameter when create private gateway

---

agent/src/main/java/com/cloud/agent/direct/download/HttpDirectTemplateDownloader.java
agent/src/main/java/com/cloud/agent/direct/download/HttpsDirectTemplateDownloader.java
agent/src/main/java/com/cloud/agent/direct/download/MetalinkDirectTemplateDownloader.java
api/src/main/java/org/apache/cloudstack/direct/download/DirectDownloadManager.java
core/src/main/java/org/apache/cloudstack/agent/directdownload/DirectDownloadCommand.java
core/src/main/java/org/apache/cloudstack/agent/directdownload/HttpDirectDownloadCommand.java
core/src/main/java/org/apache/cloudstack/agent/directdownload/HttpsDirectDownloadCommand.java
core/src/main/java/org/apache/cloudstack/agent/directdownload/MetalinkDirectDownloadCommand.java
core/src/main/java/org/apache/cloudstack/agent/directdownload/NfsDirectDownloadCommand.java
engine/api/src/main/java/org/apache/cloudstack/engine/subsystem/api/storage/TemplateService.java
engine/schema/src/main/java/com/cloud/storage/dao/VMTemplateDaoImpl.java
engine/schema/src/main/java/com/cloud/storage/dao/VMTemplateZoneDao.java
engine/schema/src/main/java/com/cloud/storage/dao/VMTemplateZoneDaoImpl.java
engine/storage/image/src/main/java/org/apache/cloudstack/storage/image/TemplateServiceImpl.java
plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java
server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
server/src/main/java/com/cloud/consoleproxy/ConsoleProxyManagerImpl.java
server/src/main/java/org/apache/cloudstack/direct/download/DirectDownloadManagerImpl.java
server/src/test/resources/createNetworkOffering.xml
services/secondary-storage/controller/src/main/java/org/apache/cloudstack/secondarystorage/SecondaryStorageManagerImpl.java

As of now provisioning of System VMs with direct download enabled template was not supported. Even after setting such templates as SYSTEM template, while provisioning SSVM and CPVM the server would return an error message like,
> System vm template is not ready at data center 1, wait until it is ready to launch secondary storage vm
This behaviour has been changed and it allows the server to provision SSVM and CPVM even with direct download system templates.
Additionally, changes have been made to make different timeouts for direct download functionality configurable using global settings. Following global configurations have been added for this,
`direct.download.connect.timeout` - Connection establishment timeout in milliseconds for direct download
`direct.download.socket.timeout` - …

Enable Direct Download for System VMs

---

api/src/main/java/com/cloud/projects/Project.java
api/src/main/java/org/apache/cloudstack/api/command/admin/cluster/ListClustersCmd.java
engine/schema/src/main/java/com/cloud/host/dao/HostDao.java
engine/schema/src/main/java/com/cloud/host/dao/HostDaoImpl.java
engine/schema/src/main/java/com/cloud/vm/dao/DomainRouterDao.java
engine/schema/src/main/java/com/cloud/vm/dao/DomainRouterDaoImpl.java
engine/schema/src/main/java/org/apache/cloudstack/storage/datastore/db/ImageStoreDao.java
engine/schema/src/main/java/org/apache/cloudstack/storage/datastore/db/ImageStoreDaoImpl.java
framework/db/src/main/java/com/cloud/utils/db/GenericDao.java
framework/db/src/main/java/com/cloud/utils/db/GenericDaoBase.java
plugins/metrics/src/main/java/org/apache/cloudstack/api/ListClustersMetricsCmd.java
plugins/metrics/src/main/java/org/apache/cloudstack/api/ListHostsMetricsCmd.java
plugins/metrics/src/main/java/org/apache/cloudstack/api/ListStoragePoolsMetricsCmd.java
plugins/metrics/src/main/java/org/apache/cloudstack/api/ListVMsMetricsCmd.java
plugins/metrics/src/main/java/org/apache/cloudstack/api/ListVolumesMetricsCmd.java
plugins/metrics/src/main/java/org/apache/cloudstack/api/ListZonesMetricsCmd.java
plugins/metrics/src/main/java/org/apache/cloudstack/metrics/MetricsService.java
plugins/metrics/src/main/java/org/apache/cloudstack/metrics/MetricsServiceImpl.java
plugins/metrics/src/main/java/org/apache/cloudstack/response/InfrastructureResponse.java
server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
server/src/main/java/com/cloud/server/ManagementServerImpl.java
server/src/main/java/com/cloud/user/AccountManagerImpl.java
server/src/test/java/com/cloud/user/MockUsageEventDao.java
ui/scripts/system.js

The count value returned in the APIs responses is incorrect
Allow listing of all resources for non-user accounts when listall=true and projectid=-1
listInfrastructure API to return count of internal LBs and Alerts in addition to the existing details returned
Addresses: https://github.com/apache/cloudstack/issues/3890

api: Fix count and item issues returned by list APIs

---

server/src/main/java/com/cloud/network/element/VirtualRouterElement.java

Currently, the cloudstack sends VM password only to the first
router in the network even if its the backup and return the result.
In some cases the first router will be back up and the second will be master.
Since password server is not running in backup, when the user resets the password,
it is sent to the first router which can be backup.
In that case, the new password is not stored in the password server and users cant log in with a new password.
This change ensures that we send the password to both the routers instead
of the first router so that a new password is stored in the master router.
1 . Create and isolated network with redundant VR and a VM in it.
2 . Note down the password of the newly created and try to ssh to it from VR
3 . Ssh works with the existing password.
4 . Now …

VR: Send VM password to all Running VRs in network/vpc

---

server/src/main/java/com/cloud/network/router/VirtualNetworkApplianceManagerImpl.java

When both router of VPC are in MASTER state
then multiple alerts are sent equal to the number of tiers in the VPC.
If the VPC has 3 tiers then 6 alerts will be sent. This is not good
if VPC has more than 10 networks in it.
Instead of checking the router status for all the tiers in the VPC,
just check the status of rotuer for one tier in a VPC so that
multiple deplicate alerts can be avoided
Alerts Dashboard when both routers are in MASTER state in VPC
After the fix, when both routers are in master state
1 . Create a VPC with redundant VR's and multiple tiers in it
2. Change the state of the BACKUP VR to MASTER.
3 . You will see multiple alerts in the Cloudstack dashboard

Avoid duplicate alerts when router state changes

---

server/src/main/java/com/cloud/server/ManagementServerImpl.java

in 4.13, list sshkeypairs with keyword will ignore the search by name if name is specifed.
Fixes an issue in #3098 
for example,
```
(local) > list sshkeypairs name=wei keyword=wei filter=name
{
"count": 3,
"sshkeypair": [
{
"name": "wei3"
},
{
"name": "wei2"
},
{
"name": "wei"
}
]
}
```
with this patch ,it gives correct result.
```
(local) > list sshkeypairs name=wei keyword=wei filter=name
{
"count": 1,
"sshkeypair": [
{
"name": "wei"
}
]
}
```

server: fix issue while list ssh keypairs by keyword

---

systemvm/debian/opt/cloud/bin/cs/CsAddress.py

The port 80/8080 in the vr of the guest network is accessible from
outisde the world. Restrict it so that only the vm's in the guest
network can access them
Before fix
$ nc -vz 10.11.118.172 8080
Connection to 10.11.118.172 port 8080 [tcp/http] succeeded!
After fix
$ nc -vz 10.11.118.172 8080
^C

Allow port 80/8080 accessible only from guest network

---

systemvm/debian/opt/cloud/bin/configure.py
systemvm/debian/opt/cloud/bin/cs/CsAddress.py
systemvm/debian/opt/cloud/bin/cs/CsRedundant.py

This fixes few issues below
(1) when add/remove a vpc tier, the keepalived is restarted on both master and backup VRs, which causes some seconds donwtime of vpc.
(2) when remove a vpc tier, the password server is not stopped.
(3) vpc tier is shutdown because no vm is running for 20 minutes, if we start a vm in the vpc tier, it will be implemented. however the guest ip in VPC VRs will be changed , and password server is still running with old guest ip in VRs.

vrouter: reload keepalived instead of restart and fix password server issues when add/remove vpc tier

---

pom.xml

Just some cleanup, these vars in the pom file are not being referenced from anywhere.
cs.axis2.version
cs.jstl-api.version
cs.rampart.version
cs.xml-apis.version
I ran a build after removing these vars and there were no issues.

Removed unused vars from pom file

---

ui/scripts/system.js

This fixes issue from merging 4d8a2da133b74f2de9ecc599eebafdfc68e6fa60
on master/4.14-snapshot which causes duplicate VRs to show up.
Fixes #3926

ui: fix merge issue that causes VR duplicates

---

core/src/main/java/com/cloud/agent/resource/virtualnetwork/VirtualRoutingResource.java
engine/components-api/src/main/java/com/cloud/agent/AgentManager.java
engine/orchestration/src/main/java/com/cloud/agent/manager/AgentManagerImpl.java
plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java

Make some changes based on @nvazquez 's comments in PR #3491 
Fix a bug in #3491

kvm: fix/optimize propogating configs

---

plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageProcessor.java
vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/VirtualMachineMO.java

This PR fixes an issue where creating instances with data volumes greater than 2.147TB on VMWare fails. This is due to an overflow error when megabytes are converted to kilobytes.
To reproduce:
Try to create an instance with a custom data volume size greater than 2200 MB using a VMWare hypervisor.
This was tested by creating a data volume greater than 2.2T from the UI using the add instance wizard.

Fixed error on data volumes lager than 2.14TB when creating instances on VMware

---

server/src/main/java/com/cloud/network/router/CommandSetupHelper.java
server/src/main/java/com/cloud/network/rules/RulesManagerImpl.java

If static nat is enabled on VM then metadata service should return
the static nat instead of gateway IP.
If static not is not enabled then it should return the gateway IP
as the public IP
Step to reproduce:
1. Create a vm
2. Ssh to vm.
3. Run the below command inside the vm
wget http://\<VR public ip\>/latest/meta-data/public-ipv4
Note down the output of the above command
4. Now acquire a new public and enable static NAT on that IP to this vm
5. Now run the same command mentioned above in the VM
This should display the static NAT ip instead of VR public IP
Output:
Before enabling static nat
wget http://10.10.10.40/latest/meta-data/public-ipv4
$ cat public-ipv4
10.10.10.29
After enabling static nat
wget http://10.10.10.40/latest/meta-data/public-ipv4
$ cat public-ipv4
10.11.10.30

Userdata to display static NAT as public ip instead of VR ip

---

engine/storage/image/src/main/java/org/apache/cloudstack/storage/image/TemplateDataFactoryImpl.java
server/src/main/java/com/cloud/template/TemplateManagerImpl.java

As previously described by PR #3929:
If vm has attached ISO, the migration fails with error message "org.libvirt.LibvirtException: Cannot access storage file /mnt/b33e5a1d-e4ea-3465-b6ac-c98dc8ff8af0/207-2-cc5fd717-2d57-3bb3-bcf6-2c930268db6c.iso"

Fix VM with ISO attached migration issue

---

server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java

This fixes db exception when network offering is searched. Found during Primate testing: https://github.com/apache/cloudstack-primate/issues/186

server: fix database exception while searching network offerings

---

tools/docker/Dockerfile

As the latest docker image in dockerhub is built from master branch, I thought it would be correct to open PR into a master branch (and not to release, if inacceptable, please suggest the correct one).
Fixes: #3397
The latest cloudstack/simulator image is not working causing issue #3397. 
The build was incomplete as mysql 5.7 is failing to start during docker build, thus DB is not deployed.
The command `find /var/lib/mysql -type f -exec touch {} \;` is a workaround for the issue which causes mysqld 5.7 to crash after start.
Putting VOLUME instruction before starting mysql also solves this problem but does not allow any other changes to the folder during build.
There are other also options that might be discussed:
1. Setting `VOLUME /var/lib/mysql` instruction in Dockerfile and importing …

Fix simulator docker db deploy issue (apache#3397)

---

server/src/main/java/com/cloud/api/query/QueryManagerImpl.java

list volumes metrics API has missing fields from list volumes API, which effects Primate UI
Addresses Issue: https://github.com/apache/cloudstack/issues/3938
```
list volumesmetrics (before fix): 
{
"count": 1,
"volume": [
{
"created": "2020-03-05T19:41:59+0530",
"deviceid": 0,
"diskiopstotal": 0,
"diskioread": 0,
"diskiowrite": 0,
"diskkbsread": 0,
"diskkbswrite": 0,
"displayvolume": true,
"domainid": "968c400b-5eea-11ea-b12b-50eb7122da94",
"id": "c4d09dc3-8864-42bd-9338-8023be187477",
"isextractable": false,
"name": "ROOT-3",
"provisioningtype": "thin",
"quiescevm": false,
"serviceofferingdisplaytext": "Small Instance",
"serviceofferingid": "dc716e01-07a7-4993-acd8-c0525956bd4b",
"serviceofferingname": "Small Instance",
"size": 2147483648,
"sizegb": …
```

Regression Fix: Allow full response view to Admin user

---

systemvm/debian/opt/cloud/bin/cs/CsAddress.py

This is regression issue of #3898 
The password server in isolated network with RVRs run with wrong parameter
```
root@r-1083-VM:~# ps -ef|grep pass
root      1070     1  0 20:58 ?        00:00:01 python /opt/cloud/bin/passwd_server_ip.py ,192.168.10.84
```
it is because the gateway is "" for eth0 in /etc/cloudstack/ips.json.
This does not impact vpc with redundant VRs.
restart network with cleanup, the new VR seems ok
```
root@r-1085-VM:~# ps -ef|grep pass
root      5468     1  0 21:37 ?        00:00:00 python /opt/cloud/bin/passwd_server_ip.py 192.168.0.1,192.168.0.28
```

vr: fix password server run with empty gateway in isolated network with RVRs

---

api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
api/src/main/java/org/apache/cloudstack/api/command/admin/offering/CreateDiskOfferingCmd.java
api/src/main/java/org/apache/cloudstack/api/command/admin/offering/CreateServiceOfferingCmd.java
api/src/main/java/org/apache/cloudstack/api/response/ServiceOfferingResponse.java
plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java
server/src/main/java/com/cloud/api/query/dao/ServiceOfferingJoinDaoImpl.java
server/src/main/java/com/cloud/api/query/vo/ServiceOfferingJoinVO.java
server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
test/integration/smoke/test_disk_offerings.py
test/integration/smoke/test_service_offerings.py
tools/marvin/marvin/lib/base.py
ui/scripts/configuration.js

Right now for the createDiskOffering  indicates that the cacheMode parameter comes back in the response but there is no equivalent parameter in the request. 
The following changes have been added:
1. "cacheMode" field has been added to the createServiceOffering endpoint
2. "cacheMode" field has been added to the createDiskOffering endpoint
3. "cacheMode" field will be returned in the listServiceOfferings and listDiskOfferings endpoints.
Wrote a python test for testing the creation of service offering with each one of the valid cache mode types : none, writeback and writethrough.
Wrote a python test for testing the creation of service offering with invalid cache mode type.
[test_service_offerings_results.txt](https://github.com/myENA/cloudstack/files/4252123/test_service_offerings_results.t …

Add cache mode param properly

---

server/src/main/java/com/cloud/vm/UserVmManagerImpl.java

After reinstall a stopped vm or reset ssh key, the password is reset, and new password is saved in virtual router (if it is running). However we do not get any password in the api response as well as cloudstack UI.
This fixes the issue above.

server: password is not displayed when reinstall a vm or reset ssh key

---

systemvm/debian/root/health_checks/iptables_check.py

Port forwarding rules not checked properly on Isolated networks (non-VPC)
Created Isolated network and added port forward rules for the Instance created in that network
Create an Instance in a tier of a VPC network and  ran the health check from UI and cmk with performfreshchecks as true
All tests passed for both the routers

Handle port forward rule check for vpc and non vpc Isolated networks

---

server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
server/src/test/java/com/cloud/configuration/ConfigurationManagerTest.java

When creating a new disk offering ('createDiskOffering' command on API) one can set _normal_ IOPS (write/read) higher than the maximum, breaking the logics on the disk offerings. Additionally, one can (by mistake) put irrealistic values for the bursting length. Example if adding few zeros by mistake and configuring **360000** seconds, which turns out to be a bursting length of **100** hours.
This PR adds verifications ensuring that either Bytes or IOPS bursts cannot be greater than a configured value of the following global settings variables.
```
vm.disk.bytes.maximum.read.length
vm.disk.bytes.maximum.write.length
vm.disk.iops.maximum.read.length
vm.disk.iops.maximum.write.length
```
The default value is 0 (zero), allows any IOPS maximum rate length; thus keeping backward compatibility …

Validate disk offering IOPS normal and maximum read/write values

---

server/src/main/java/com/cloud/server/StatsCollector.java
server/src/test/java/com/cloud/server/StatsCollectorTest.java

Did a quick check and found an operation that can result in an overflow. Additionally, I took the liberty to do a couple of code enhancements/clean ups.

Prevent overflow on StatsCollector.java

---

server/src/main/java/com/cloud/ha/HighAvailabilityManagerImpl.java

Simply rename a global setting name to a more descriptive one:
`max.retries` to `vm.ha.migration.max.retries`
Also, as it is used in global context, have changed the scope from Cluster to Global.
This setting has been introduced before 4.14, so no need to update DB on upgrade
Setting improvement as well as #3961

Rename max.retries setting

---

engine/schema/src/main/java/com/cloud/upgrade/DatabaseUpgradeChecker.java
engine/schema/src/main/java/com/cloud/upgrade/dao/Upgrade41300to41310.java

This PR adds the 4.13.0.0 to 4.13.1.0 upgrade path
This has been tested by starting up the client and checking the version table in the db.

Updated upgrade path

---

server/src/main/java/com/cloud/api/query/QueryManagerImpl.java

The listZonesMetrics does not return same keys are listZones as the
default response view is restricted. This fixes that by ensuring that
for root admin full response view is used.
This is critical to be merged for Primate tech preview.
Testing: http://primate-qa.cloudstack.cloud:8080/client/master

server: export full response view for zones response for root admin

---

plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/guru/VMwareGuru.java
plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java
server/src/main/java/com/cloud/hypervisor/HypervisorGuruBase.java

System VM's are failed to deploy on VM ware setup, due to NPE. 
Solution : Added Null check for the same and took care of respective code flow changes. 
Yet to test and update.

 NPE fix for System VM's start Command

---

pom.xml
tools/checkstyle/pom.xml

owasp dependency checker and other tools during the site build phase to be able to add them to apache jenkins. inluding updates and cleanups.
Some version discrepencies arose so version upgrades are included and `mvn dependency:tree | grep <this or that> | sort -u` gave some that need handling:
```
com.fasterxml.jackson.core:jackson-core:jar:2.1.3:compile
com.fasterxml.jackson.core:jackson-core:jar:2.9.10:compile
com.google.code.findbugs:jsr305:jar:1.3.9:compile
com.google.code.findbugs:jsr305:jar:3.0.2:compile
com.google.http-client:google-http-client:jar:1.17.0-rc:compile
com.google.http-client:google-http-client:jar:1.20.0:compile
com.unboundid:unboundid-ldapsdk:jar:3.2.0:compile
com.unboundid:unboundid-ldapsdk:jar:4.0.14:test
commons-collections:commons-collections:jar:3.2.1:compile …
```

maven quality tool plugins

---

packaging/systemd/cloudstack-agent.service
packaging/systemd/cloudstack-management.service
packaging/systemd/cloudstack-usage.service

systemd dependency on db

---

plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java
server/src/main/java/com/cloud/network/guru/ControlNetworkGuru.java
server/src/main/java/com/cloud/network/router/VirtualNetworkApplianceManagerImpl.java

With basic zone and VMware hypervisor, VR fails to start since eth1 is getting empty instead of a private IP.
Boot Args for VM[DomainRouter|r-4-VM]:  template=domP name=r-4-VM eth0ip=10.3.0.89 eth0mask=255.255.224.0 gateway=10.3.31.254 domain=cs1cloud.internal cidrsize=19 dhcprange=10.3.0.1 eth1ip=0.0.0.0 eth1mask=0.0.0.0 mgmtcidr=10.2.0.0/16 localgw=10.2.254.254 sshonguest=true type=dhcpsrvr disable_rp_filter=true extra_pubnics=2 dns1=8.8.8.8 
Though VMware does not support security groups, but in a basic zone with VMware and no isolation VMs should be able to deploy.
Fixes: #3031
1. Created a VMware basic zone
2. Created a VM and Virtual router
3. VR is in running state with private IP assigned to it
4. VM deployment is also successful

With basic zone and VMware hypervisor, VR fails to start

---

ui/scripts/instanceWizard.js

While deploy a vm from ISO on UI, the instance wizard is not working in vm overview step.
this is regression issue of #3271

UI bug fix: Cannot deploy VM from ISO

---

ui/scripts/sharedFunctions.js

When creating a template from a snapshot, the notification is not updated after the task is completed. 
This PR fixes the issue.
Fixes: #3711 
This has been tested by creating a template from a volume snapshot from the UI

Fixed create template from snapshot never returning

---

debian/control

Openjdk11 is not supported in Ubunt 16.04, we can use zulu-11 instead.
Steps to install zulu-11 on Ubuntu 16.04:
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 0xB1998361219BD9C9
sudo echo 'deb http://repos.azulsystems.com/ubuntu stable main' >/etc/apt/sources.list.d/azul.list
sudo apt update
sudo apt install zulu-11 -y

Add support for zulu-11 in cloudstack 4.14

---

debian/rules

The cloudstack-rolling-maintenance service fails on ubuntu while packaging.
Fixes: #3981 
````
~/cloudstack/packaging# ./build-deb.sh
````

Remove rolling-maintenance service from debian rules

---

engine/schema/src/main/java/com/cloud/capacity/dao/CapacityDao.java
engine/schema/src/main/java/com/cloud/capacity/dao/CapacityDaoImpl.java
engine/storage/src/main/java/org/apache/cloudstack/storage/allocator/AbstractStoragePoolAllocator.java
engine/storage/src/main/java/org/apache/cloudstack/storage/allocator/ZoneWideStoragePoolAllocator.java
server/src/main/java/com/cloud/agent/manager/allocator/impl/FirstFitAllocator.java

When vm.allocation.algorithm is set to 'firstfitleastconsumed', we are unable to create vm or volume if all storage pools are zone-wide (which have cluster_id=NULL)
1. create zone with zone-wide storage pool
2. deploy vm successfully.

server: Search zone-wide storage pool when allocation algothrim is firstfitleastconsumed

---

pom.xml

Since PR #3956 has been merged the build time has increased drastically due to the quality tools added.
This PR simply removes these tools from the default build execution and adds a new profile with name: `quality` to enable these tools.
To enable this new profile, simply append: `-P quality` to the maven build command
As a result, the default build time increases significantly, as shown in the 'How has this been tested' section
Tested on Ubuntu 19.10 laptop, 8x1.8Ghz CPU - 16GB RAM
openjdk version "11.0.6" 2020-01-14
Apache Maven 3.6.1
Default build:
````
$ mvn clean install -Dnoredist -P developer,systemvm -DskipTests -T4
[INFO] …
```

Improvement on build time and new quality profile

---

server/src/main/java/com/cloud/api/query/QueryManagerImpl.java

This PR aims to fix an issue when list affinity group, which can be reproduced by steps below
(1) dedicate a host to a domain (for example ROOT)
(2) create a vm in domain if not exist
(3) stop the vm
(4) change affinity group, affinity group cannot be listed.
(5) "cloudmonkey list affinitygroups" also fails.
This issue does not appear if there are other hosts dedicated to the account (not domain).
tested ok.
An issue remained is that listing affinity groups by pagesize/pages does not work perfectly. it will return
(1) affinity groups to the account by pagesize/page
(2) and all domain-level affinity groups.
However, I think it is not a critical bug.

server: Cannot list affinity group if there are hosts dedicated to domain

---

server/src/main/java/com/cloud/server/ManagementServerImpl.java

It is a small bug fix preventing ssh key name to be empty.
Items | FIX CloudStack API allows SSHKeyPair name to be empty
-- | --
Steps | create a sshkeypair with empty name `cloudmonkey create sshkeypair name=`
Expected Results | operation should fail
Actual results | sshkey pair is created successfully
Created a small Cloudstack environment with three hypervisor and one management server. Try to create sshKey with empty name via cloudmonkey.

FIX: prevent empty sshkey name.

---

plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtDeleteVMSnapshotCommandWrapper.java

To void qcow2 image corruption, we'd better suspend vm when delete a vmsnapshot, and resume it when vmsnapshot is removed.
Fixes: #3193 
related to: #3194 #4029

kvm: suspend/resume in deleting vm snapshot on kvm

---

plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java

Original commit, merged to 4.11.3, got mysteriously missing when merging branch 4.11 to 4.12 on the very same day that original PR was merged - so bringing back the same "suspend the VM before the KVM VM snapshot is deleted" code (we already have "resume if it's suspended, after VM snap deletion is finished"
I'm talking about the PR #3194 (the commit itself is there, but NOT the content/code - possibly a wrongly resolved merge conflicts etc)
/cc @weizhouapache  (you approved the original PR) and @rhtyd (you also approved the original PR)

Bring back vm.suspend during deleting VM snapshot

---

ui/scripts/zoneWizard.js

Fixes #4039 - Guest Vlan range will be lost when deploying ZONE
This has been tested by creating an advanced zone with the wizard and then checking if the vlan range was set for guest traffic on the physical network.

Fixed guest vlan range going missing when using zone wizard

---

client/conf/db.properties.in
utils/conf/db.properties

This would give users ability to change the timezone
The general assumption is that CloudStack infra/services would run on UTC with ntp/synchronised time. Looks like some users prefer local time in DB.

db.properties: Enforce UTC timezone by default

---

test/integration/smoke/test_kubernetes_clusters.py
test/integration/smoke/test_kubernetes_supported_versions.py

Use public links for templates and binaries iso for CKS smoke tests

cks: use public links for templates and binaries iso for smoke tests

---

plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java

Failed to delete snapashot on local filesystem due to `Operation not implemented for storage pool type of Filesystem`.
1. Snapshot a volume stored on local storage
2. delete the snapshot
3. Snapshot operation is not fully executed failing to delete on primary (local) storage.
Log on management server:
```
2020-05-04 02:17:06,719 DEBUG [c.c.s.s.SnapshotManagerImpl] (API-Job-Executor-9:ctx-59e99d59 job-167 ctx-7d1e424f) (logid:ac80ff16) Failed to delete snapshot: 1:com.cloud.utils.exception.CloudRuntimeException: Failed to remove snapshot dd3ea8b2-af27-49ec-ad6a-25e45ce158b5@bf990ccf-7272-4d7b-99af-11ba49fc6e5a
2020-05-04 02:17:06,734 ERROR [c.c.a.ApiAsyncJobDispatcher] (API-Job-Executor-9:ctx-59e99d59 job-167) (logid:ac80ff16) Unexpected exception while executing …
```

Allow deleting snapshot on local filesystem

---

systemvm/debian/opt/cloud/bin/cs/CsDhcp.py

cloudstack 4.13.1.0
When Guest VM add secondary nic,  will get wrong hostname "infiniteh" from dhcp server
infiniteh -->infinite
cat /etc/dhcphosts.txt
02:00:0b:ef:00:04,set:192_168_4_18,192.168.4.18,gumd-tes3,infiniteh

fix dhcp lease entry wrong hostname

---

pom.xml

Adding novnc license exclusion to the rat plugin

Adding novnc license exclusion

---

plugins/event-bus/rabbitmq/src/main/java/org/apache/cloudstack/mom/rabbitmq/RabbitMQEventBus.java

The handling of the exception of RabbitMQ `getConnection()` method can be improved.
Example of issues that I have noticed:
```
Failed to create a connection to AMQP server due to null
```
Not all exceptions hold a message; therefore, some exceptions might result in a `null` output instead of the Exception message/stack.
With the fix, the error message looks like:
```
Failed to create a connection to AMQP server [AMQP host:amqp.host.org, port:123] due to: java.net.UnknownHostException: amqp.host.org: Name or service not known
Failed to create a connection to AMQP server [AMQP host:null, port:null] due to: java.net.ConnectException: Connection refused (Connection refused)
```

RabbitMQ log enhancement

---

plugins/storage/volume/solidfire/src/main/java/org/apache/cloudstack/storage/datastore/driver/SolidFirePrimaryDataStoreDriver.java
plugins/storage/volume/solidfire/src/main/java/org/apache/cloudstack/storage/datastore/lifecycle/SolidFireSharedPrimaryDataStoreLifeCycle.java
plugins/storage/volume/solidfire/src/main/java/org/apache/cloudstack/storage/datastore/util/SolidFireUtil.java

Previously, volume access groups were assigned with the convention Cloudstack-RandomUUID. This change proposes that that we use Cloudstack-clusterUuId instead.
The problem addressed by this PR is that under some conditions multiple volume access groups with random uuids are created. This is illustrated in the screenshot below:
One of the scenarios in which this occurs is when upgrades are done to the hypervisor hosts by removing, re-provisioning them and re-adding them.
Steps to reproduce in test environment with two hosts:
1. - Create VMs
2. - Remove all hosts
3. - Re-Add hosts
4. - Start VMs
_Outcome before applying this patch:_
A new volume access group is created with the convention CloudStack-RandomUUID
_After applying this patch:_
If an existing volume access group with the naming …

create Volume Access Groups per cluster instead of CloudStack-RandomUUID()

---

packaging/centos7/cloud.spec

Missing python3 libvirt bindings on CentOS7 effectively break security groups. 
There are 0 firewall rules added. The agent logs report:
2020-06-02 10:58:34,346 DEBUG [kvm.resource.LibvirtComputingResource] (main:null) (logid:) Traceback (most recent call last):  File "/usr/share/cloudstack-common/scripts/vm/network/security_group.py", line 26, in <module>    import libvirtModuleNotFoundError: No module named 'libvirt'

Missing python3 libvirt bindings

---

api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
api/src/main/java/org/apache/cloudstack/api/command/user/loadbalancer/UploadSslCertCmd.java
server/src/main/java/org/apache/cloudstack/network/ssl/CertServiceImpl.java
server/src/test/java/org/apache/cloudstack/network/ssl/CertServiceTest.java

This update turns on certificate revocation checking for uploaded certificates:
- Updated `CertServiceImpl` to be able to enable revocation checking.
- Introduced a new parameter `ENABLED_REVOCATION_CHECK` for `UploadSslCertCmd`.
- Updated `CertServiceTest`.
Even if no CLRs are specified via `PKIXParameters`, the certificates
themselves may still provide info for revocation checking:
- The AIA extension may contains a URL to the OCSP responder.
- The CLRDP extension contains a URL to the CLR.
Those extensions may need to be explicitly enabled by setting the system properties `com.sun.security.enableAIAcaIssuers` and `com.sun.security.enableCRLDP` to true. See [Java PKI Programmer's Guide](https://docs.oracle.com/en/java/javase/11/security/java-pki-programmers-guide.html).
Using a revoked …

Enable revocation checking for uploaded certificates

---

scripts/vm/hypervisor/kvm/kvmvmactivity.sh

When scripts/vm/hypervisor/kvm/**kvmvmactivity.sh** is called with an incorrect file name, an error is printed which is then interpreted as output from the script. 
When an incorrect file name is passed the script prints out:
```
stat: cannot stat ‘b51d7336-d964-44ee-be60-bf62783dabc’: No such file or directory
=====> DEAD <======
```
The KVMHAVMActivityChecker.java checkingHB() process is expecting just
`=====> DEAD <======`
but gets the unexpected error message and interprets the file as alive.
This has been tested by calling the script with a correct file name and getting
`=====> ALIVE <=====`
and an incorrect file name and getting
`=====> DEAD <======`
`/usr/share/cloudstack-common/scripts/vm/hypervisor/kvm/kvmvmactivity.sh -i 1.1.1.1 -p /some/primary/storage/pool -m /some/mount/point …

Improved kvmvmactivitycheck.sh output

---

server/src/main/java/com/cloud/storage/snapshot/SnapshotManagerImpl.java

By default it is not possible to snapshot volumes from Running VMs on KVM hosts; such action launches the following exception:
```
2020-06-03 11:44:54,714 DEBUG [c.c.s.s.SnapshotManagerImpl] (qtp164332069-24:ctx-2a36c5e0 ctx-a0d2d92c) (logid:430624b7) Snapshot is not supported on host Host[-1-Routing] for the volume org.apache.cloudstack.storage.volume.VolumeObject@73c6838c attached to the vm VM[User|i-2-52-VM]
2020-06-03 11:44:54,804 ERROR [c.c.a.ApiServer] (qtp164332069-24:ctx-2a36c5e0 ctx-a0d2d92c) (logid:430624b7) unhandled exception executing api command: [Ljava.lang.String;@2e3a5424
com.cloud.utils.exception.CloudRuntimeException: KVM Snapshot is not supported
```
However, it is possible to snapshot KVM Running VMs if setting global settings `kvm.snapshot.enabled` to `True`. For …

Enhance KVM running VM snapshot exception log

---

plugins/hypervisors/kvm/pom.xml
pom.xml

This fixes issue for cloudstack-agent to make connections to libvirt
on arm64 boards.
The jna-platform provides non-default (x86_64) mappings, read more:
https://github.com/java-native-access/jna/blob/master/www/PlatformLibrary.md

kvm: bump jna version to latest

---

server/src/main/java/com/cloud/network/element/VirtualRouterElement.java

Logs:
````
2020-05-07 23:12:28,116 INFO  [c.c.v.VirtualMachineManagerImpl] (Work-Job-Executor-25:ctx-0a8703ef job-79/job-80 ctx-a3fc4a74) (logid:936f1123) Migrating VM[User|i-2-8-VM] to Dest[Zone(Id)-Pod(Id)-Cluster(Id)-Host(Id)-Storage(Volume(Id|Type-->Pool(Id))] : Dest[Zone(1)-Pod(1)-Cluster(1)-Host(2)-Storage()]
2020-05-07 23:12:28,120 DEBUG [c.c.n.NetworkModelImpl] (Work-Job-Executor-25:ctx-0a8703ef job-79/job-80 ctx-a3fc4a74) (logid:936f1123) Service SecurityGroup is not supported in the network id=210
2020-05-07 23:12:28,125 DEBUG [c.c.n.NetworkModelImpl] (Work-Job-Executor-25:ctx-0a8703ef job-79/job-80 ctx-a3fc4a74) (logid:936f1123) Service SecurityGroup is not supported in the network id=210
2020-05-07 23:12:28,127 ERROR [c.c.v.VmWorkJobHandlerProxy] …
```

[VMware] Cannot migrate VM on PVLAN shared network
