utils/src/main/java/com/cloud/utils/UriUtils.java, utils/src/test/java/com/cloud/utils/UriUtilsParametrizedTest.java
Attempts to register QCOW2 template with .img extension fails fast:
This fix allows registering a QCOW2 template with .img extension
Register templates: https://cloud-images.ubuntu.com/minimal/releases/bionic/release/ubuntu-18.04-minimal-cloudimg-amd64.img, http://dl.openvm.eu/cloudstack/macchinina/x86_64/macchinina.img with format = QCOW2
=> Allow IMG extension for QCOW2 format

ui/css/cloudstack3.css, ui/l10n/en.js, ui/scripts/templates.js
Add UI support for the existing `updateIsoPermissions` API.
Register ISO -> Update ISO permissions
=> [UI] Update ISO permissions

engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
When expunge a Running vm, vm will be stopped with forcestop=false which does not make sense. we should honor vm.destroy.forcestop in global setting, or always set forcestop=true.
=> server: Honor vm.destroy.forcestop when expunge a vm

server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
Only admins should be able to search VM by instance name
Customers should not see or serach VM's using the instance name (i-)
Login as "admin".
Note down the i- name of the customer VM.
Now login to the customer domain
Try to search for VM using the i- name
It should not display the VM. It should display only for admin
=> Disable searching by instance name for customers

scripts/vm/hypervisor/xenserver/setup_heartbeat_sr.sh
`/opt/cloud/bin/setup_heartbeat_sr.sh` line 75 tests for “XenServer release 7.” in `/etc/redhat-release` which contains “XCP-ng release 8.0.0 (xenenterprise)” in my case so the `lvcreate` statement doesn’t contain the required options
Fixes: #3281
Adding an iSCSI endpoint now succeeds with XCP-ng 8.0.0. I've left the previous XenServer logic alone just added the XCP-ng test case into the else block.  This could definitely be fine tuned by someone who's more intimate with these scripts but I just wanted the issue fixed without interfering in the logic.
=> add support for XCP-ng 7/8 to create it's heartbeat LVM properly

plugins/hypervisors/baremetal/src/main/java/com/cloud/baremetal/manager/BareMetalDiscoverer.java, plugins/user-authenticators/ldap/src/main/java/org/apache/cloudstack/api/command/LdapListUsersCmd.java, server/src/main/java/org/apache/cloudstack/vm/VmImportManagerImpl.java
Simple log fix. I have found out a few log messages that hold unused/misused arguments on their respective String.format building.
=> Fix String.format unused/misused arguments

plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtGetVolumeStatsCommandWrapper.java
When volume or storage pool are not found when LibvirtGetVolumeStatsCommandWrapper.java, CloudRuntimeException is thrown. All methods invoked by this command are throwing in most of the cases CloudRuntimeException and it's not handled in LibvirtGetVolumeStatsCommandWrapper.
For example if volume is not found, CloudStack agent throws this exception and it fills up the agent.log
DB record:
'29', '2', '1', '1', '2', NULL, NULL, 'nfsDisk', 'd644f5c6-bf70-4826-8d2b-d4bc373a9198', '5368709120', '/export/primary', 'efba7e17-dddd-4bbb-8233-347c9a5faaff', '1', '1', NULL, NULL, 'DATADISK', NULL, '3', NULL, NULL, '0', '2020-01-28 08:56:00', NULL, '2020-02-19 12:21:53', NULL, 'Ready', NULL, '21', NULL, NULL, NULL, '1', 'QCOW2', NULL, NULL, NULL, 'thin'
2020-03-06 17:38:06,775 DEBUG …
=> Fix: catch CloudRuntimeException in LibvirtGetVolumeStatsCommandWrapper.java

server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
Allow VR's to be searched using its redundant state
Under Infrastructure -> Virtual Routers -> Search box
we can search using "MASTER", "BACKUP" and this will display
the VR's matching the state.
Login to cloudstack ui
Navigate to Infrastructure -> Virtual Routers and search for state in the search box
This will display all virtual routers matching the state.
=> Search VR using redundant state

server/src/main/java/org/apache/cloudstack/vm/VmImportManagerImpl.java
I provided a fix for the error reported in issue # 3642
Details of the error can be found at: 
https://github.com/apache/cloudstack/issues/3642
**Root cause of the problem:**
The incorrect error messages were found in the lines 431, 434 and 437 of the file - 
server/src/main/java/org/apache/cloudstack/vm/VmImportManagerImpl.java
_**Line # 431:**_
` throw new ServerApiException ... CPU cores does not matches ... `
_**Line # 434:**_
` throw new ServerApiException ... memory does not matches ...`
_**Line # 437:**_
`throw new ServerApiException ... CPU speed does not matches ...`
**Changes done to fix the problem:**
I replaced the word 'matches' with 'match' inside the 3 error messages.
I compiled the code after the changes and tested whether the error messages with the updated text are shown …
=> Updated 3 error messages to replace the word 'matches' with 'match'

server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
Description
-------------
Fix to pick the max data volumes limit using the actual hypervisor version, instead of "default" version
Changes:
- Use the hypervisor version in the host table when product_version parameter in host details doesn't exist or is empty
Fixes: #4101 
- Create VM and attach disk, verified the max data disks limit is picked from hypervisor version
=> Maximum data volumes limit is picked from "default" version of hypervisor, instead of actual hypervisor version

engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/snapshot/SnapshotDataFactoryImpl.java
Fixes #4090
When trying to migrate a VM across 2 clusters, if a snapshot has been deleted and garbage collection has run to update the removed field, it is not possible to migrate the instance due to a null pointer.
This has been tested by migrating an instance to another Xenserver cluster using XCP-NG as the hypervisor in both clusters.
Process to follow:
* Create a zone with 2 clusters.
* Create an instance in 1 cluster.
* Take a root volume snapshot of the instance.
* Delete the snapshot.
* Wait for the removed field to be populated in the snapshots table.
* Migrate the instance.
=> Fixed null pointer after deleting snapshot, GC and cross cluster vm migration on XCP-NG

engine/api/src/main/java/com/cloud/vm/VirtualMachineManager.java, engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java, engine/orchestration/src/main/java/com/cloud/vm/VmWorkReconfigure.java, server/src/main/java/com/cloud/server/ManagementServerImpl.java, server/src/main/java/com/cloud/vm/UserVmManager.java, server/src/main/java/com/cloud/vm/UserVmManagerImpl.java, server/src/test/java/com/cloud/vm/UserVmManagerTest.java
Submitting multiple dynamic VM Scaling API commands for the same instance can result in two usage events in the same second causing a compound key violation in usage service
Root cause:
Even though dynamic scaling job is handled in vmworkjob queue which ensures serilizing multiple jobs but the database updating and generating usage events are out of the job queue.
Solution:
Moved all updations into the job queue
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] Cleanup (Code refactoring and cleanup, that may add test cases)
Firstly I have tested all the scenarios to check if nothing is broken
1. Scaling on a running VM with normal compute offering
2. Scaling on a stopped VM with normal compute offering
3. Scaling on a running VM with custom compute offering
4. Scaling on …
=> Multiple dynamic VM Scaling APIs can create duplicate usage events for the same time 

api/src/main/java/com/cloud/event/EventTypes.java, engine/schema/src/main/java/com/cloud/usage/dao/UsageBackupDao.java, engine/schema/src/main/java/com/cloud/usage/dao/UsageBackupDaoImpl.java, framework/db/src/main/java/com/cloud/utils/db/TransactionLegacy.java, plugins/backup/dummy/src/main/java/org/apache/cloudstack/backup/DummyBackupProvider.java, plugins/backup/veeam/src/main/java/org/apache/cloudstack/backup/VeeamBackupProvider.java, server/src/main/java/org/apache/cloudstack/backup/BackupManagerImpl.java, usage/src/main/java/com/cloud/usage/UsageManagerImpl.java
The TransactionLegacy instances are tracked by TransactionMBeanImpl in a
concurrent hashmap. Even when TransactionLegacy instances are closed,
the hashmap keep the references and makes it hard for the closed instances
to be garbage collected. This adds code to remove the TransactionLegacy
instance from the mbean when the instance is close().
NOTE: This only happens when the new B&R feature is enabled in 4.14.0.0, the sync thread seems to get stuck while performing DB query and ends up consuming most of the TransactionLegacy instances
Related: https://github.com/apache/cloudstack/issues/3987
Leaks seen by MAT:
The MBean explore shows a steady increase in  the leaks:
server: fix leak by moving backup usage updation via usage events
BackupSync task would switch between databases to update …
=> server: fix TransactionLegacy DB connection leaks due to DB switching by B&R thread

server/src/main/java/com/cloud/network/vpc/VpcManagerImpl.java
When a VPC is restarted, the networks in the VPC is not restarted, this PR will add the logic to restart the networks in the VPC that needs a restart when the VPC is restarted.
Fixes: #3816 
This was tested by manually setting the needs restart flag in the db in the networks table and then restarting the VPC.
=> Restarting all networks that needs a restart in a VPC

api/src/main/java/org/apache/cloudstack/api/ApiConstants.java, api/src/main/java/org/apache/cloudstack/api/command/user/iso/ListIsosCmd.java, api/src/main/java/org/apache/cloudstack/api/command/user/template/ListTemplatesCmd.java, server/src/main/java/com/cloud/api/query/QueryManagerImpl.java, server/src/main/java/com/cloud/api/query/dao/TemplateJoinDao.java, server/src/main/java/com/cloud/api/query/dao/TemplateJoinDaoImpl.java
Adds a new parameter `showunique` to listTemplate and listIsos to return only unique templates / isos across all zones
Fixes #4041
=> Adding showunique parameter to list templates and isos

engine/api/src/main/java/com/cloud/vm/VirtualMachineManager.java, engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java, engine/orchestration/src/test/java/com/cloud/vm/VirtualMachineManagerImplTest.java, server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
NPE occurred when dynamic scaling tried on VM and as part of this when MS tries to migrate VM if current host does not have capacity.
Repro Steps:
1. Create a VM on host1
2. Make host1 capacity full by deploying multiple VMs
3. Try Dynamic scaling on VM on host1
4. NPE occurs when MS tries to find host to migrate the VM and then scale.
2020-03-27 05:37:15,899 WARN  [c.c.v.UserVmManagerImpl] (API-Job-Executor-6:ctx-f7c76e69 job-3021 ctx-d68f535a) (logid:3189e554) Received exception while scaling
at com.cloud.deploy.DeploymentPlanningManagerImpl.planDeployment(DeploymentPlanningManagerImpl.java:255)
at com.cloud.vm.VirtualMachineManagerImpl.findHostAndMigrate(VirtualMachineManagerImpl.java:3768)
at com.cloud.vm.UserVmManagerImpl.upgradeRunningVirtualMachine(Use …
=> NPE when VM is planned to migrate to other host during dynamic scaling

plugins/metrics/src/main/java/org/apache/cloudstack/api/ListVMsMetricsCmd.java, server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
This fixes the issue of listVirtualMachinesMetrics to extend ListVMsCmd instead of ListVMsCmdByAdmin which is a potential security bug. It now only extends ListVMsCmd, so only admins can see additional details such as internal instance name, etc
No similar issue for listVolumeMetics, listStoragePoolMetrics, etc
Fixes: #4143
=> Fixing listVirtualMachinesMetrics to extend ListVMsCmd instead of ListVMsCmdByAdmin

engine/schema/src/main/java/com/cloud/vm/dao/UserVmDaoImpl.java
Fix dele shared network with no services on network offering
Fixes: #4096 
Create network offering with no services
Create network from offering
Deploy VM
Delete network
=> Fix delete network with no services

engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java, plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/CitrixResourceBase.java, plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/wrapper/xenbase/CitrixMigrateCommandWrapper.java, plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/wrapper/xenbase/CitrixStartCommandWrapper.java, server/src/main/java/com/cloud/network/element/ConfigDriveNetworkElement.java
This PR fixes an issue where an instance fails to deploy due to a null pointer when using an L2 Guest Network with DefaultL2NetworkOfferingConfigDrive on Xenserver. It also fixes migrating an instance to another host.
This has been tested by: 
- Creating an L2 Guest network, using DefaultL2NetworkOfferingConfigDrive as the network offering. 
- Deploying an instance using the L2 Guest network created.
- Migrating the instance away from the host and back
=> Fixed null pointer and deployment issue on Xenserver with L2 Guest network with configDrive

server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
Fixes wrong `count` in `listAffinityGroup` API.
API was returning the count of `AffinityGroupJoinVO` records.
With a running environment,
**Before fix** - count is equal to VM count for the affinity groups
```
(local) 🐱 > list affinitygroups 
{
"affinitygroup": [
{
"domainid": "1db59a3e-b131-11ea-94f6-645d8651f45a",
"id": "b878f4e6-fbcd-44f3-9a95-ad8102fd14da",
"name": "bvcn",
"type": "host anti-affinity",
"virtualmachineIds": [
"0c6bee5e-2d50-4b7a-b26f-30bff5818777"
]
},
{
"domainid": "1db59a3e-b131-11ea-94f6-645d8651f45a",
"id": "10b78b41-8fe4-47c1-8972-3bedd0690fd3",
"name": "hfd",
"type": "host anti-affinity",
"virtualmachineIds": [
"0c6bee5e-2d50-4b7a-b26f-30bff5818777",
"f4ca8c20-4887-4bc1-a532-b39cf140c4e4" …
```
=> server: fix for wrong affinity group count

plugins/user-authenticators/ldap/src/main/java/org/apache/cloudstack/api/command/LdapListConfigurationCmd.java, plugins/user-authenticators/ldap/src/main/java/org/apache/cloudstack/ldap/LdapManagerImpl.java, plugins/user-authenticators/ldap/src/main/java/org/apache/cloudstack/ldap/dao/LdapConfigurationDao.java, plugins/user-authenticators/ldap/src/main/java/org/apache/cloudstack/ldap/dao/LdapConfigurationDaoImpl.java
Adds the listall parameter to listLdapConfigurations.
If set to true, and no domainid specified, list all LDAP configurations irrespective of the linked domain
```
(localhost) 🐱 > list ldapconfigurations listall=true 
{
"LdapConfiguration": [
{
"domainid": "3eca21e9-b1f3-11ea-ba9c-50eb71576f75",
"hostname": "primate-qa.cloudstack.cloud",
"port": 389
},
{
"domainid": "2b660440-759f-4490-99ba-cddd9cbff2af",
"hostname": "primate-qa.cloudstack.cloud",
"port": 389
},
{
"hostname": "primate-qa.cloudstack.cloud",
"port": 389
}
],
"count": 3
}
(localhost) 🐱 > list ldapconfigurations 
{
"LdapConfiguration": [
{
"hostname": "primate-qa.cloudstack.cloud",
"port": 389
}
],
"count": 1
}
(localhost) 🐱 > list ldapconfigurations domainid=2b660440-759f-4490-99ba-cddd9cbff2af listall=true 
{ …
```
=> Adding listall to listLdapConfigurations

api/src/main/java/org/apache/cloudstack/api/ApiConstants.java, api/src/main/java/org/apache/cloudstack/api/response/DomainRouterResponse.java, api/src/main/java/org/apache/cloudstack/api/response/IPAddressResponse.java, api/src/main/java/org/apache/cloudstack/api/response/PrivateGatewayResponse.java, api/src/main/java/org/apache/cloudstack/api/response/Site2SiteVpnGatewayResponse.java, api/src/main/java/org/apache/cloudstack/api/response/SystemVmResponse.java, api/src/main/java/org/apache/cloudstack/api/response/UserVmResponse.java, api/src/main/java/org/apache/cloudstack/api/response/VpcResponse.java, server/src/main/java/com/cloud/api/ApiResponseHelper.java, server/src/main/java/com/cloud/api/query/dao/DomainRouterJoinDaoImpl.java, server/src/main/java/com/cloud/api/query/dao/UserVmJoinDaoImpl.java
Adding missing fields in the following APIs
`osdisplayname` in `listVirtualMachines`
`vpcofferingname` in `listVpcs`
`vpcname` in `listPublicIpAddresses`
`vpcname` in `listPrivateGateways`
`vpcname` in `listVpnGateways`
`templatename, podname` in `listRouters`
`templatename, podname` in `listSystemVms`
Fixes: #4161
=> Adding missing fields to API responses

server/src/main/java/com/cloud/network/router/VirtualNetworkApplianceManagerImpl.java
Fixes #4163 
Added excluded tests in the code for BACKUP router.
BACKUP Router,
Before fix,
After fix and excluding `gateways_check.py` for BACKUP router,
Executing health checks for BACKUP router
=> vr: fix backup router health check

server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
If we resize a volume of a vm running on a host which is not Up or not Enable, the job will be scheduled to another normal host. Then the volume will be resized by "qemu-img resize" instead of "virsh blockresize", the image might be corrupted after resize.
=> server: Do not resize volume of running vm on KVM host if host is not Up or not Enabled

engine/components-api/src/main/java/com/cloud/deploy/DeploymentPlanningManager.java, server/src/main/java/com/cloud/deploy/DeploymentPlanningManagerImpl.java, server/src/main/java/com/cloud/server/ManagementServerImpl.java
While migrate a vm, in the popup, the host dedicated to other accounts/domains are also 'Suitable" for migration, which is obviously wrong.
The same issue happens with api findHostsForMigration
with this PR, the hosts dedicated to other domains/accounts are marked as 'Not Suitable'.
=> server: Dedicated hosts should be 'Not Suitable' while find host for m migration

api/src/main/java/com/cloud/event/EventTypes.java, api/src/main/java/org/apache/cloudstack/acl/Role.java, api/src/main/java/org/apache/cloudstack/acl/RoleService.java, api/src/main/java/org/apache/cloudstack/api/ApiConstants.java, api/src/main/java/org/apache/cloudstack/api/ApiServerService.java, api/src/main/java/org/apache/cloudstack/api/command/admin/acl/CreateRoleCmd.java, api/src/main/java/org/apache/cloudstack/api/command/admin/acl/ImportRoleCmd.java, api/src/main/java/org/apache/cloudstack/api/command/admin/acl/ListRolesCmd.java, api/src/main/java/org/apache/cloudstack/api/command/admin/acl/RoleCmd.java, api/src/main/java/org/apache/cloudstack/api/command/admin/acl/UpdateRoleCmd.java, api/src/main/java/org/apache/cloudstack/api/response/RoleResponse.java, api/src/test/java/org/apache/cloudstack/api/command/test/CreateRoleCmdTest.java, api/src/test/java/org/apache/cloudstack/api/command/test/ImportRoleCmdTest.java, engine/schema/src/main/java/com/cloud/upgrade/dao/Upgrade41400to41500.java, engine/schema/src/main/java/org/apache/cloudstack/acl/RoleVO.java, engine/schema/src/main/java/org/apache/cloudstack/acl/dao/RoleDao.java, engine/schema/src/main/java/org/apache/cloudstack/acl/dao/RoleDaoImpl.java, engine/schema/src/main/java/org/apache/cloudstack/acl/dao/RolePermissionsDao.java, engine/schema/src/main/java/org/apache/cloudstack/acl/dao/RolePermissionsDaoImpl.java, engine/schema/src/main/resources/META-INF/db/schema-41400to41500-cleanup.sql, engine/schema/src/main/resources/META-INF/db/schema-41400to41500.sql, server/src/main/java/com/cloud/api/ApiServer.java, server/src/main/java/org/apache/cloudstack/acl/RoleManagerImpl.java, test/integration/smoke/test_dynamicroles.py, tools/marvin/marvin/lib/base.py
This PR addresses the below improvements for current Dynamic roles functionality.
- Create a role from any of the existing role, using new parameter roleid in createRole API.
- Import a role with its rules, using a new importRole API.
- New default roles for Read-Only and Support Admin & User.
- No modifications (update or delete) allowed for Default roles.
- Cleanup of old NetApp APIs from role_permissions table.
UI changes PR: https://github.com/apache/cloudstack-primate/pull/353
**Manual Tests using API**
- Create a role using existing role.
http://myms:8080/client/api?command=createRole&response=json&name=Test%20CloneUser01&description=Test%20CloneUser01&roleid=ca9871c2-8ea7-11ea-944e-c2865825b006
{"createroleresponse":{"role":{"id":"c3888c27-66b6-4a39-96ee-9883fef326ba","name":"Test …
=> Dynamic roles improvements

vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/ClusterMO.java, vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/DatacenterMO.java, vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/HypervisorHostHelper.java, vmware-base/src/test/java/com/cloud/hypervisor/vmware/mo/HypervisorHostHelperTest.java
Set the VM hardware version on new VM deployments as set by the administrator on vCenter at cluster or datacenter level by the 'Edit Default VM Compatibility' action:
On VM deployments:
- Check cluster level VM hardware version If it is set, then is used as the new VM hardware version
- If cluster level VM hardware version not set, check the datacenter VM hardware version. If it is set, then it is used as the new VM hardware version.
- If both cluster or datacenter VM hardware version not set, then VM hardware version not set for the new VM
=> [VMware] Explicitly controlling VM hardware version

server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
Enhancement for issue #2736
1. Start a VM
2. With cloudmonkey, start the same VM
3. Observe the result
Response should fail the job and say VM is already in running state.
=> Limit API from trying to start a VM that is already running

api/src/main/java/org/apache/cloudstack/backup/BackupManager.java, developer/developer-prefill.sql, server/src/main/java/org/apache/cloudstack/backup/BackupManagerImpl.java, test/integration/smoke/test_backup_recovery_dummy.py
This change will ensure that B&R APIs are not exported if the feature is not enabled globally. Make it non-dynamic to require restarting of mgmt server which is needed for the background sync task to be setup or not.
=> server: don't export B&R APIs if feature is not enabled globally

plugins/user-authenticators/saml2/src/main/java/org/apache/cloudstack/saml/SAMLUtils.java, server/src/main/java/com/cloud/api/ApiServlet.java
This will purge all the cookies on logout including multiple sessionkey
cookies if passed. On login, this will restrict sessionkey cookie
(httponly) to the /client path like the JSESSIONID cookie.
Fixes #4136
Needs manual testing
=> server: Purge all cookies on logout, set /client path on login

plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java, vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/VirtualMachineMO.java, vmware-base/src/main/java/com/cloud/hypervisor/vmware/util/VmwareHelper.java
Support to attach more than 15 data disks in VMware VM 
Fixes: #4102 
- Create a new VM and attached 25 data disks to the VM.
[cloud]> select vm.instance_name as vm_name, count(*) as volumes_count from vm_instance vm join volumes vol on vm.id = vol.instance_id where vm.id = 4 group by vol.instance_id;
+----------+---------------+
| vm_name  | volumes_count |
+----------+---------------+
| i-2-4-VM |            26 |
+----------+---------------+
=> [VMware] Support to attach more than 15 data disks in VMware VM

engine/schema/src/main/java/com/cloud/host/dao/HostDao.java, engine/schema/src/main/java/com/cloud/host/dao/HostDaoImpl.java
When a host connects to a management server, the host IP address and the certificate are stored in memory on the management server. This mapping is checked periodically to determine if any certificates are due to expire.
Before a certificate is renewed, a few checks are done to determine if the host is connected to the management server by fetching the host record from the database. The problem here is if the wrong record is fetched, the host is not checked for renewal.
This PR improves the host record fetch from the database by looking only at hosts that are not removed.
Fixes: #4129 
This has been tested by setting the ca.framework.cert.validity.period and ca.framework.cert.expiry.alert.period to the same value. This is to ensure that a certificate is up for renewal as soon as it is …
=> Fixed removal of hosts from certsmap when running certificate auto-renew

engine/schema/src/main/java/org/apache/cloudstack/storage/datastore/db/SnapshotDataStoreDao.java, engine/storage/src/main/java/org/apache/cloudstack/storage/image/db/SnapshotDataStoreDaoImpl.java, server/src/main/java/com/cloud/storage/StorageManagerImpl.java
Cleanup orphan entries for primary storage on table `snapshot_store_ref` 
Fixes: #4018 - Problem 1
=> Fix snapshots garbage collection

plugins/ca/root-ca/src/test/java/org/apache/cloudstack/ca/provider/RootCAProviderTest.java
The SSL engine defaults to "Server mode" when doing handshaking. This PR removes the check on the mode which was causing tests to fail.
This behavior was changed in OpenJDK 11.0.8
```
JDK-8245077: Default SSLEngine Created in Server Role
=====================================================
In JDK 11 and later, `javax.net.ssl.SSLEngine` by default used client
mode when handshaking.  As a result, the set of default enabled
protocols may differ to what is expected. `SSLEngine` would usually be
used in server mode. From this JDK release onwards, `SSLEngine` will
default to server mode. The
`javax.net.ssl.SSLEngine.setUseClientMode(boolean mode)` method may be
used to configure the mode.
```
This was tested by building Cloudstack and allowing the tests to run.
=> Removed check on SSLEngine client mode

api/src/main/java/org/apache/cloudstack/acl/RoleService.java, api/src/main/java/org/apache/cloudstack/api/command/admin/acl/ListRolesCmd.java, api/src/main/java/org/apache/cloudstack/api/command/user/vm/ListVMsCmd.java, api/src/main/java/org/apache/cloudstack/api/response/HostResponse.java, engine/schema/src/main/java/org/apache/cloudstack/acl/dao/RoleDao.java, engine/schema/src/main/java/org/apache/cloudstack/acl/dao/RoleDaoImpl.java, server/src/main/java/com/cloud/api/query/QueryManagerImpl.java, server/src/main/java/com/cloud/api/query/dao/HostJoinDaoImpl.java, server/src/main/java/com/cloud/api/query/dao/TemplateJoinDaoImpl.java, server/src/main/java/com/cloud/network/vpc/NetworkACLServiceImpl.java, server/src/main/java/org/apache/cloudstack/acl/RoleManagerImpl.java, server/src/test/java/org/apache/cloudstack/acl/RoleManagerImplTest.java
Adding the following fixes so primate can work without issues :
- Adding pagination for listNetworkAclLists
- Adding pagination for listRoles
- Returning mshost uuid rather than msid in list hosts response
- Allowing listVirtualMachinesMetrics to respect hostid
- Fixing return all details in template response
```
(localhost) 🐱 > list networkacllists vpcid=0dc4efc7-82f4-48c1-ae2f-74bf9127ea40 page=3 pagesize=2
{
"count": 24,
"networkacllist": [
{
"description": "test17",
"fordisplay": true,
"id": "3c99bcce-8e04-443b-9015-997a35606502",
"name": "test17",
"vpcid": "0dc4efc7-82f4-48c1-ae2f-74bf9127ea40"
},
{
"description": "test16",
"fordisplay": true,
"id": "f7e30024-08c9-42c5-81c0-ec4534c5893d",
"name": "test16",
"vpcid": "0dc4efc7-82f4-48c1-ae2f-74bf9127ea40"
}
]
}
```
```
(localhost) 🐱 > …
```
=> Bug fixes for primate

api/src/main/java/org/apache/cloudstack/api/command/user/firewall/CreateEgressFirewallRuleCmd.java, api/src/main/java/org/apache/cloudstack/api/command/user/firewall/CreateFirewallRuleCmd.java, api/src/main/java/org/apache/cloudstack/api/command/user/firewall/CreatePortForwardingRuleCmd.java, api/src/main/java/org/apache/cloudstack/api/command/user/loadbalancer/CreateLoadBalancerRuleCmd.java, api/src/main/java/org/apache/cloudstack/api/command/user/nat/CreateIpForwardingRuleCmd.java, api/src/main/java/org/apache/cloudstack/api/command/user/network/CreateNetworkACLCmd.java, api/src/main/java/org/apache/cloudstack/api/command/user/network/UpdateNetworkACLItemCmd.java, api/src/main/java/org/apache/cloudstack/api/command/user/securitygroup/AuthorizeSecurityGroupEgressCmd.java, api/src/main/java/org/apache/cloudstack/api/command/user/securitygroup/AuthorizeSecurityGroupIngressCmd.java, api/src/main/java/org/apache/cloudstack/api/command/user/vpn/CreateVpnCustomerGatewayCmd.java, api/src/main/java/org/apache/cloudstack/api/command/user/vpn/UpdateVpnCustomerGatewayCmd.java, api/src/main/java/org/apache/cloudstack/api/response/FirewallResponse.java, api/src/main/java/org/apache/cloudstack/api/response/FirewallRuleResponse.java, api/src/main/java/org/apache/cloudstack/api/response/LoadBalancerResponse.java, api/src/main/java/org/apache/cloudstack/api/response/NetworkACLItemResponse.java, api/src/main/java/org/apache/cloudstack/api/response/Site2SiteCustomerGatewayResponse.java, api/src/main/java/org/apache/cloudstack/api/response/Site2SiteVpnConnectionResponse.java
This patch adds a sentence to all CIDR_LIST and DEST_CIDR_LIST API parameter and return value annotations that documents how to pass a list of CIDRs.
This is a rarely used feature, but may be necessary for certain scenarios, such as automatic firewall rule generation/matching, VPNs with multiple routed networks, etc.
There may be other cases where the APIs accept lists, but this was out of scope for this PR.
I tested what values the API calls createFirewallRule and createLoadBalancerRule accept for the cidrlist parameter, and what is returned in listFirewallRules and listLoadBalancerRules.
Anything besides a single comma is not accepted.
Furthermore, createFirewallRule returns an error because the parameter is deprecated.
=> Document how to pass CIDRs lists API calls

api/src/main/java/org/apache/cloudstack/outofbandmanagement/OutOfBandManagement.java, client/pom.xml, engine/schema/src/main/java/org/apache/cloudstack/outofbandmanagement/dao/OutOfBandManagementDaoImpl.java, plugins/outofbandmanagement-drivers/redfish/pom.xml, plugins/outofbandmanagement-drivers/redfish/src/main/java/org/apache/cloudstack/outofbandmanagement/driver/redfish/RedfishOutOfBandManagementDriver.java, plugins/outofbandmanagement-drivers/redfish/src/main/java/org/apache/cloudstack/outofbandmanagement/driver/redfish/RedfishWrapper.java, plugins/outofbandmanagement-drivers/redfish/src/main/resources/META-INF/cloudstack/redfish/module.properties, plugins/outofbandmanagement-drivers/redfish/src/main/resources/META-INF/cloudstack/redfish/spring-redfish-context.xml, plugins/pom.xml, ui/scripts/system.js, utils/src/main/java/org/apache/cloudstack/utils/redfish/RedfishClient.java, utils/src/main/java/org/apache/cloudstack/utils/redfish/RedfishException.java, utils/src/test/java/org/apache/cloudstack/utils/redfish/RedfishClientTest.java
This PR adds support for the OOBM Redfish protocol, implementing a Java client to send HTTP requests to Redfish supported systems.
Implementation overview:
- Redfish Java client: a Java Client for Redfish that makes Redfish actions available to the HA workflow via an OOB driver.
- OOB Redfish driver: a new Out-of-band driver was created for Redfish, allowing to integrate the Redfish Client with the CloudStack Out-of-band management implementation.
Fixes: #3624
**Thanks note:** this implementation had valuable help from our friends at [Yourhosting](https://www.yourhosting.nl/).
Configure OOBM with Redfish driver
Check OOBM host tab
Test powering On and Off hosts. Host status is properly shown
We have been able to test on Dell and Supermicro machines and it works fine:
1. via the CloudStack …
=> Redfish Client & Redfish OOBM Driver

systemvm/debian/opt/cloud/bin/configure.py, systemvm/debian/root/health_checks/iptables_check.py
As discussed in https://github.com/apache/cloudstack/pull/3937#issuecomment-595459008
a rule for port forwarding in VPC router might not be needed.
This fixes the failed result of health check for network VRs.
=> vrouter: remove a POSTROUTING rule for port forwarding in VPC router

plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtStoragePoolDef.java, plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMPhysicalDisk.java, plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtStoragePoolDefTest.java, plugins/storage/volume/default/src/main/java/org/apache/cloudstack/storage/datastore/lifecycle/CloudStackPrimaryDataStoreLifeCycleImpl.java
Ceph used to use port 6789 (no need to specify it), but with the messenger v2
from Ceph it switched to port 3300 while 6789 still works.
librados/librbd/libvirt will automatically figure out the ports to use if none is
specified.
Therefor there is no need for CloudStack to explicitely define the port in the XML
passed to Libvirt or Qemu.
Leave blank if no port number has been defined by the user.
=> kvm/ceph: Only if a port number has been specified define in the XML

plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java, server/src/main/java/com/cloud/api/query/ViewResponseHelper.java, vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/DatastoreMO.java
- This fixes issues of virtual size to be twice in case the disk is a linked-clone root disk. The virtual size of root disk (first in chain) must be used.
- Fixes to report the physical size for a volume whose stat is being collected
After the fix utilisation is seen as below:
Logs also show valid values like:
```
2020-07-28 12:17:09,296 DEBUG [c.c.h.v.m.DatastoreMO] (DirectAgent-38:ctx-1a415fb5 10.10.4.235, cmd: GetVolumeStatsCommand) (logid:7c3f9cb8) File found = ROOT-3.vmdk, size=157134848
2020-07-28 12:17:09,471 DEBUG [c.c.h.v.m.DatastoreMO] (DirectAgent-38:ctx-1a415fb5 10.10.4.235, cmd: GetVolumeStatsCommand) (logid:7c3f9cb8) File found = b86db0909f7236d7acb343b0572bca65.vmdk, size=1201016832
2020-07-28 12:17:09,656 DEBUG [c.c.h.v.m.DatastoreMO] (DirectAgent-38:ctx-1a415fb5 …
```
=> vmware: volume utilisation is always zero

server/src/main/java/com/cloud/api/query/dao/HostJoinDaoImpl.java
Fixes #4221 
The findHostsForMigration api displays 0% always for
cpuallocated field which is wrong
Tested from cloudmonkey api
Before the fix
```
local) > find hostsformigration virtualmachineid=01f155-fffc-493f-95b8-85a76414 filter=cpuallocated,suitableformigration
{
"count": 221,
"host": [
{
"cpuallocated": "0%",
"suitableformigration": true
},
{
"cpuallocated": "0%",
"suitableformigration": true
},
{
"cpuallocated": "0%",
"suitableformigration": true
},
```
After the fix
```
(local) mgt01 > list hosts  virtualmachineid=95b4270f-1354-4703-99cb-a769400b2d30 filter=cpuallocated,suitableformigration,name
{
"count": 3,
"host": [
{
"cpuallocated": "2.27%",
"name": "node32",
"suitableformigration": true
},
{
"cpuallocated": "1.14%",
"name": "node33",
"suitableformigration": true
}
]
}
```
=> Fix cpuallocated value in findHostsForMIgration api

api/src/main/java/com/cloud/resource/ResourceService.java, api/src/main/java/org/apache/cloudstack/api/command/admin/cluster/UpdateClusterCmd.java, api/src/main/java/org/apache/cloudstack/api/command/admin/host/UpdateHostCmd.java, api/src/main/java/org/apache/cloudstack/api/command/admin/storage/UpdateStoragePoolCmd.java, server/src/main/java/com/cloud/resource/ResourceManagerImpl.java, server/src/main/java/com/cloud/resource/RollingMaintenanceManagerImpl.java, server/src/main/java/com/cloud/storage/StorageManagerImpl.java, server/src/test/java/com/cloud/resource/MockResourceManagerImpl.java, ui/scripts/system.js
This PR adds implementation for changing host and storage name, additionally, it fixes a Bug on cluster updateCluster API command. This PRs also enhances the UI by allowing editing field name on Host and Storage pool. Due to the fact that there is no support to editing cluster via UI, it was not edited.
TODO:  I will address Host,  Cluster, and Storage Pool name edition on CloudStack Primate once the API implementation gets merged.
**Details:** 
Prior to this PR the following API commands did not offer support for updating name:
- [updateHost](https://cloudstack.apache.org/api/apidocs-4.14/apis/updateHost.html) **(enhancement)**
- [updateStoragePool](https://cloudstack.apache.org/api/apidocs-4.14/apis/updateStoragePool.html)  **(enhancement)**
Additionally, …
=> Allow renaming cluster, host, and storage

api/src/main/java/com/cloud/vm/UserVmService.java, engine/api/src/main/java/com/cloud/vm/VirtualMachineManager.java, engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java, engine/orchestration/src/main/java/com/cloud/vm/VmWorkRestore.java, server/src/main/java/com/cloud/vm/UserVmManagerImpl.java, server/src/test/java/com/cloud/vm/UserVmManagerTest.java
When restore a Running vm twice, the vm cannot be started.
(1) deploy a vm
(2) restore the vm twice by cloudmonkey
cloudmonkey restore virtualmachine virtualmachineid=<vmid> & cloudmonkey restore virtualmachine virtualmachineid=<vmid>&
The vm cannot be restarted again as there are two ROOT volumes.
Same steps succeed with this PR (the vm will be restored twice).
=> server: Move restoreVM to vm work job queue

tools/appliance/systemvmtemplate/template.json
This way we do not depend on Debian keeping the ISO online or changing
URLs which can break our build system(s).
See also: #4243
=> Host SSVM Debian ISO on download.cloudstack.org

tools/apidoc/build-apidoc.sh
apidoc build failed in Mac OS because of sed in-place command. It is a minor change that fixed this issue. More information  [here](https://stackoverflow.com/questions/5694228/sed-in-place-flag-that-works-both-on-mac-bsd-and-linux?answertab=active#tab-top)
Fixes: #3247
Fixes: #3312
I tested this feature in Mac and Ubuntu
=> Fix sed command failure in Mac OS.

api/src/main/java/org/apache/cloudstack/api/command/user/vpc/CreateStaticRouteCmd.java, api/src/main/java/org/apache/cloudstack/api/command/user/vpc/ListStaticRoutesCmd.java, engine/schema/src/main/java/com/cloud/network/vpc/dao/StaticRouteDao.java, engine/schema/src/main/java/com/cloud/network/vpc/dao/StaticRouteDaoImpl.java, server/src/main/java/com/cloud/network/vpc/VpcManagerImpl.java, ui/scripts/vpc.js
When the static route service is not available on the VPC and a static route is created, the static route is created in a revoked state.
Currently, the UI doesn't distinguish between active or revoked static routes.
This PR adds the missing state filter to the list routes command and only lists active routes in the UI.
It also ignores revoked routes when the private gateway is being removed but clears out the inactive routes before the gateway is removed.
Fixes #2908 
This has been tested by creating a VPC with no services, adding a private gateway, adding a static route and deleting the gateway.
=> Fixed private gateway can't be deleted

server/src/main/java/com/cloud/server/ManagementServerImpl.java
I reproduced this in a production environment that had been upgraded from 4.9 to 4.11 and then to 4.13.  
If the environment has `data centers` and `VLANs` removed, sends an API request with the command `listPublicIpAddress` and allocatedOnly=false we can see this error:
```
2020-07-29 08:15:16,224 ERROR [c.c.a.ApiServer] (qtp504527234-1307:ctx-d9b6eb3f ctx-a0add444) (logid:b94eb35a) unhandled exception executing api command: [Ljava.lang.String;@6177c5d4
```
This occurs because `ManagementService.searchForIPAddresses` returns IP addresses from those deleted `data centers`. And then we have a Null Pointer exception when building the `createIPAddressResponse`.  
This PR prevents this null pointer exception by doing an `INNER_JOIN` with `data_center` table were …
=> Prevent null pointer on listPublicIpAddress cmd

server/src/main/java/com/cloud/vm/snapshot/VMSnapshotManagerImpl.java
Search VM snapshots using tags
Currently, search of VM snapshots doesn't comply with tags passed as input
tested via CLI (cmk) and UI
=> Search vm snapshots using tags

vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/HypervisorHostHelper.java, vmware-base/src/test/java/com/cloud/hypervisor/vmware/mo/HypervisorHostHelperTest.java
Multiple public networks with vlan IDs starting with the ID sequence can lead to possible conflicts and may result in associating IP to the wrong NIC. 
Addresses issue: https://github.com/apache/cloudstack/issues/4247
=> Name public network appropriately to avoid conflicts

systemvm/agent/scripts/ssvm-check.sh, test/integration/smoke/test_ssvm.py
test_ssvm fails on VMWare fixes: https://github.com/apache/cloudstack/issues/4261
Running the ssvm-check.sh script on the Secondary storage VM produces the following error message:
```
command substitution: ignored null byte in input
```
as null characters were being passed, which caused the test to fail.
=> fix test failure

framework/db/src/main/java/com/cloud/utils/db/GenericDaoBase.java, framework/db/src/test/java/com/cloud/utils/db/GenericDaoBaseTest.java
Recently I had a few DB connection/transaction issues on a test environment and one of the log messages was the following `NullPointerException`:
```
2020-08-12 22:48:33,250 WARN  [c.c.a.m.AgentManagerImpl] (AgentManager-Handler-1:null) (logid:) Caught: 
at com.cloud.utils.db.GenericDaoBase.update(GenericDaoBase.java:853)
at com.cloud.utils.db.GenericDaoBase.update(GenericDaoBase.java:809)
at com.cloud.utils.db.GenericDaoBase.update(GenericDaoBase.java:1365)
```
Looking further we can see that the null pointer was caused due to a null Object calling _equals_ method. A simple fix would be to use the static final not-null Object calling the `Object.equals` method.
This PR also extracted the duplicated code that could cause `NullPointerException` and added unit …
=> Prevent NullPointerException on GenericDaoBase

api/src/main/java/org/apache/cloudstack/api/response/VMSnapshotResponse.java, server/src/main/java/com/cloud/api/ApiResponseHelper.java
The "hypervisor" field in listvmsnapshot response will
be used in primate to enable/disable creating a snapshot
from VM snapshot functionality.
Creating snapshot from VM snapshot will be enabled only if
the hypervisor is KVM
Cloudmonkey output
```
(local) 🐵 > list vmsnapshot
{
"count": 2,
"vmSnapshot": [
{
"created": "2020-08-18T11:12:11+0000",
"current": true,
"displayname": "i-2-5-VM_VS_20200818111211",
"domainid": "f47-c10d-11ea-8715-063381",
"hypervisor": "KVM",
"id": "d34f9-df5a-4510-985a-e7f508ad",
"name": "i-2-5-VM_VS_20200818111211",
"state": "Ready",
"tags": [],
"type": "DiskAndMemory",
"virtualmachineid": "52cfd-e8d6-4c85-a7e0-f603f151",
"zoneid": "d0802-be7b-4345-8b55-1612c0b"
},
{
"created": "2020-08-17T15:48:08+0000", …
```
=> Display hypervisor type for VM snapshot

agent/src/main/java/com/cloud/agent/Agent.java, api/src/main/java/com/cloud/agent/api/PvlanSetupCommand.java, engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java, engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java, engine/schema/src/main/java/com/cloud/network/dao/NetworkDao.java, engine/schema/src/main/java/com/cloud/network/dao/NetworkDaoImpl.java, plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java, plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtPvlanSetupCommandWrapper.java, plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java, scripts/vm/network/ovs-pvlan-kvm-dhcp-host.sh, scripts/vm/network/ovs-pvlan-kvm-vm.sh, server/src/test/java/com/cloud/network/dao/NetworkDaoTest.java, server/src/test/java/com/cloud/vpc/dao/MockNetworkDaoImpl.java, test/integration/smoke/test_network.py, utils/src/main/java/com/cloud/utils/UriUtils.java, utils/src/main/java/com/cloud/utils/net/NetUtils.java, utils/src/test/java/com/cloud/utils/net/NetUtilsTest.java
This is an extention of #3732 for kvm. 
This is restricted to ovs > 2.9.2
Since Xen uses ovs 2.6, pvlan is unsupported.
This also fixes issues of vms on the same pvlan unable to communicate if they're on the same host
- Create L2 network selecting a VLAN ID and secondary VLAN ID as well as the PVLAN type. The connectivity is as expected
=> [KVM] Enable PVLAN support on L2 networks

engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
Commit e894238d904a9c49c1140371f612a51d251efc1 (#3899) allowed private
gateways to bypass vlan check while refactoring it did not cover the
case for L2 but only shared network. This fix will re-enable honouring
the bypass vlan check option for L2 guest network (in addition to the
Shared networks).
Fixes #4273
=> engine: honour bypass VLAN id/range for L2 networks

server/src/main/java/com/cloud/network/element/VpcVirtualRouterElement.java
This PR fixes the problem where restarting a network with cleanup within a VPC destroys the VR first before creating a new one.
Fixes:  #3815 
This has been tested by restarting the VPC network with cleanup and observing the behavior on the Virtual Routers page.
=> Fixed rolling restart on VPC network

api/src/main/java/org/apache/cloudstack/api/response/UsageRecordResponse.java, server/src/main/java/com/cloud/api/ApiResponseHelper.java
Adding the Os Type Id to the CloudStack Api response for listUsageRecords for running and allocated VMs. When attempting to determine what type of VM was being used for a removed VM, the listVirtualMachines Api will not return a result, as the record has been marked removed. For our purposes, the type of OS is still required for usage purposes. This change simply adds that additional element to the output.
I have been leveraging the Api for retrieving usage information for virtual machines of specific types fairly extensively.
This change simply adds an additional element to the output, and thus should be considered a non-breaking change.
=> Adding os type id to the usage record response for virtual machines

pom.xml
This PR updates the Java Rados version v0.6.0. The release artifacts are available at: https://search.maven.org/artifact/com.ceph/rados.
Fixes: #4159
CloudStack builds successfully and the java-rados v0.6.0 jar has indeed been downloaded from the public repositoy.
=> Update Java Rados from v0.5.0 to v0.6.0

client/src/main/java/org/apache/cloudstack/ServerDaemon.java, pom.xml
Fixes #4199
Latest jetty used in 4.14/master has deprecated `new SslContextFactory();` and requires use of Client|Server. This fixes that.
=> client: explicitly define SslContextFactory::Server for https

api/src/main/java/com/cloud/vm/NicProfile.java, server/src/main/java/com/cloud/network/NetworkServiceImpl.java, server/src/main/java/com/cloud/network/guru/ExternalGuestNetworkGuru.java, server/src/main/java/com/cloud/network/guru/GuestNetworkGuru.java, server/src/main/java/com/cloud/network/router/NetworkHelperImpl.java
This PR aims to fix the issue below
1. Create a network offering for isolated network, services: Dns/Dhcp/Userdata, and enable it
2. create a isolated network with the new offering
3. create a vm
4. check the guest IP of virtual router, 
5. restart network with cleanup
6. check the guest IP of new virtual router
7. The IP in step4 and step6 should be the same, but they are different actually.
tested with steps above, the IPs are same in step 7.
change network to another offering with public ip, the placeholder ip is removed from database.
tested with shared networks and L2 network as well.
=> vrouter: Save PlaceHolder nic for VR if network does not have source nat

ui/scripts/instances.js
For customer constrained offering, the cpu speed is fixed. 
Therefore the 'CpuSpeed' field should be hidden for customer constrained offering when change vm offering on UI. 
It is visible only for unconstrained offering.
This is regression issue of #3245
=> UI: Hide cpuspeed for custom constrained offering

api/src/main/java/org/apache/cloudstack/api/command/user/network/ListNetworksCmd.java, server/src/main/java/com/cloud/network/NetworkServiceImpl.java, ui/scripts/configuration.js, ui/scripts/network.js
Add extra parameter for listNetworks command to list
all networks using networkofferingid
```
(local) mgt01 > list networks networkofferingid=85051f32-93a4-4277-8895-a9232e4885f5 filter=name
{
"count": 4,
"network": [
{
"name": "tier23"
},
{
"name": "tier13"
},
{
"name": "tier22"
},
{
"name": "tier12"
}
]
}
(local) mgt01 >
```
=> List networks using networkofferingid

engine/api/src/main/java/com/cloud/vm/VirtualMachineManager.java, engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java, engine/orchestration/src/main/java/com/cloud/vm/VmWorkUpdateDefaultNic.java, server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
While remove secondary nic from a Running vm, if update the default nic to the secondary nic before the nic is removed, the vm will not have default nic (and cannot be started) when both operations are completed.
It is because UpdateDefaultNic api is not handled as a vm work job (AddNicToVMCmd and RemoveNicFromVMCmd are), it is processed before nic is removed. The result is that secondary nic becomes default nic and got removed.
1. remove secondary nic from a Running vm
2. update default nic to the secondary nic before step 1 is finished.
3. got an exception  as below.
=> server: move UpdateDefaultNic to vm work job queue

api/src/main/java/org/apache/cloudstack/api/command/admin/vm/AssignVMCmd.java, server/src/main/java/com/cloud/acl/DomainChecker.java, server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
When executing request [assignVirtualMachine](https://cloudstack.apache.org/api/apidocs-4.14/apis/assignVirtualMachine.html) with null `domainID` and a valid `projectID` then a `NullPointerException` happens at [DomainChecker.java](https://github.com/apache/cloudstack/blob/bb73bedb5511880c91abaa409462ba879cb0d7b7/server/src/main/java/com/cloud/acl/DomainChecker.java#L109).
Command example:
```
assign virtualmachine virtualmachineid=vmID projectid=projectID account=admin
```
The `NullPointerException` that is thrown at `DomainChecker` is handled at [AssignVMCmd.java#L142](https://github.com/apache/cloudstack/blob/bb73bedb5511880c91abaa409462ba879cb0d7b7/api/src/main/java/org/apache/cloudstack/api/command/admin/vm/AssignVMCmd.java#L142), resulting in the following log message: `Failed to …
=> Avoid Null pointer at DomainChecker and enhance AssignVMCmd

engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
After a vm is shutdown, the power state isn't updated immediately. This prevents changing the service offering.
This PR updates the power state immediately after the vm is confirmed to be shutdown.
Fixes: #3159 
This has been tested by starting a vm, waiting for the power state in the db to be updated to powerOn, then shutting down the vm and as soon as the vm is down, checking the power state in the db. Can also be verified by changing the service offering after stopping the vm.
=> Fixed delayed power state update after vm shutdown

pom.xml, server/src/main/java/com/cloud/server/StatsCollector.java
After a few hours running with InfluxDB configured, CloudStack hangs due to OutOfMemoryException raised. The exception happens at [com.cloud.server.StatsCollector.writeBatches(StatsCollector.java:1510)](https://github.com/apache/cloudstack/blob/1da76d27f13e045ac88e6c494d604d6133486c9c/server/src/main/java/com/cloud/server/StatsCollector.java#L1510):
```
2020-08-12 21:19:00,972 ERROR [c.c.s.StatsCollector] (StatsCollector-6:ctx-0a4cfe6a) (logid:03a7ba48) Error trying to retrieve host stats
java.lang.OutOfMemoryError: unable to create new native thread
...
at org.influxdb.impl.BatchProcessor.<init>(BatchProcessor.java:294)
at org.influxdb.impl.BatchProcessor$Builder.build(BatchProcessor.java:201)
at org.influxdb.impl.InfluxDBImpl.enableBatch(InfluxDBImpl.java:311)
at …
```
=> Manage influxDB Batches avoiding OutOfMemory Exception

python/lib/cloudutils/serviceConfig.py
libvirt-bin does not exist any more in Ubuntu 20.04, restart libvirtd instead of libvirt-bin after configuration when add a host.
in summary:
ubuntu 16.04: libvirt-bin
ubuntu 18.04: libvirt-bin and libvirtd (they are same)
ubuntu 20.04: libvirtd
=> Ubuntu 20.04: restart libvirtd instead of libvirt-bin

debian/control
error:
dpkg-checkbuilddeps: error: Unmet build dependencies: python-mysql.connector
root cause: python-mysql.connector is not valid any more in ubuntu 20.04
root@buildbox-ubuntu20:~# dpkg -l |grep connector
ii  python3-mysql.connector               8.0.15-2build1                    all          pure Python implementation of MySQL Client/Server protocol (Python3)
solution: use python3-mysql.connector instead
=> Ubuntu 20.04: Fix issue while build package on ubuntu 20.04

engine/schema/src/main/java/com/cloud/upgrade/dao/Upgrade41310to41400.java
Incorrect checksums for systemVM template along the 4.13.1 to 4.14 upgrade path, causes failure in downloading/ syncing the systemVM templates on other / newly added image stores
1. Deploy a 4.14 setup - with a single image store
2. Once the env is up and running, add another image store
3. When the template sync happens on the newly added image store, the systemVM template fails the checksum verification
```
*************************** 4. row ***************************
id: 23
store_id: 2
template_id: 3
created: 2020-07-13 10:07:49
last_updated: 2020-07-13 10:08:22
job_id: 099eeb3a-c980-4dc6-8e00-28203c59feef
download_pct: 100
size: 0
store_role: Image
physical_size: 0
download_state: DOWNLOAD_IN_PROGRESS
error_str: Download success, starting install 
local_path: …
```
=> Incorrect md5sums for systemVM templates results in failure to download templates to other image stores

api/src/main/java/org/apache/cloudstack/api/ApiConstants.java, api/src/main/java/org/apache/cloudstack/api/response/NetworkResponse.java, server/src/main/java/com/cloud/api/ApiResponseHelper.java
Display network acl name along with its id so that we
dont need to make extra api call `listNetworksAcllist`
to get acl name
Through cloudmonkey api
```
(local) mgt01 > list networks id=81f5-5f17-488a-be61-7d6ad99 filter=aclname
{
"count": 1,
"network": [
{
"aclname": "default_allow"
}
]
}
```
=> Display acl name in listNetworks response

test/integration/smoke/test_ssvm.py
On running the reboot SSVM smoke test, the health check script fails to detect the mounted NFS stores post reboot. Increasing the wait time between reboot and running of the ssvm-check.sh helps ensure there is sufficient time for the SSVM to get configured.
With a 30s wait/ sleep - there have been intermittent failures with the test:
```
nosetests --with-xunit --xunit-file=results.xml --with-marvin --marvin-config=/marvin/ref-trl-1543-v-M7-pearl-dsilva-advanced-cfg -s -a tags=xx --hypervisor=vmware /marvin/tests/smoke/test_ssvm.py 
==== Log Folder Path: /marvin/MarvinLogs/Sep_09_2020_06_07_53_TJ2GQX. All logs will be available here ====
==== …
```
=> Increase wait time before running the ssvm health check script on SSVM reboot

ui/scripts/cloudStack.js
This handle edge cases of upgrades and when legacy UI is used along with
Primate or any UI sharing cookies. The specific case it fixes involves
removal of duplicate sessionkey cookies.
Fixes #4324 
1. Logout and create a fake sessionkey cookie using `$.cookie('sessionkey', '123')`
2. Try to login, login will fail and in the request two sessionkey cookies will be seen passed: 
With the fix, when logout is called the API will clear sessionkey cookie (which is httponly so only the backend/server can remove it); and login works. This will cover issues after upgrades and when using legacy UI with Primate:
=> ui: call logout before login to clear old sessionkey cookies

plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java, plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterResourceModifierActionWorker.java
Fix for exception in logging while creating k8s cluster
=> cks: fix logging exception on create cluster

server/src/main/java/com/cloud/acl/AffinityGroupAccessChecker.java, server/src/main/java/com/cloud/acl/DomainChecker.java, server/src/main/java/com/cloud/api/query/QueryManagerImpl.java, server/src/main/java/com/cloud/network/NetworkModelImpl.java, server/src/main/java/com/cloud/projects/ProjectManagerImpl.java
1. When listAll is true, listProjects API doesn't list projects that have users as members
2. Added defensive checks to overcome NPEs
This has been verified using the cmk and UI
There exists 7 projects:
```
MariaDB [cloud]> select name, account_id, user_id, created, removed from project_view where removed is NULL;
+--------------+------------+---------+---------------------+---------+
| name         | account_id | user_id | created             | removed |
+--------------+------------+---------+---------------------+---------+
| Project2     |          4 |    NULL | 2020-09-09 10:08:52 | NULL    |
| Project2     |          5 |       6 | 2020-09-09 10:08:52 | NULL    |
| p3           |          2 |    NULL | 2020-09-09 11:43:50 | NULL    |
| p3           |          5 |       5 | 2020-09-09 …
```
=> Handle listProjects API to list projects with user as members when listAll=true

plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageProcessor.java
Creation of templates from detached data disks results in a Null Pointer Exception on VMWare, as it expects the volume to be attached to a VM.
To fix this behavior and make it consistent with other hypervisors, creation of the template from the volume in case not attached to a VM is facilitated by creating a worker VM, attaching the disk to the worker VM, creating the template from it, and then destroying the VM.
1. Create / Upload a volume
2. Attach the volume to a VM
3. Detach the volume
4. Initiate template creation from the volume
Fails with following exception:
```
2020-08-14 07:05:00,157 DEBUG [c.c.r.ResourceLimitManagerImpl] (API-Job-Executor-15:ctx-691a4a4c job-86 ctx-54b7bef5) (logid:4a57991e) Updating resource Type = template count for Account = 2 Operation = decreasing Amount = …
```
=> Create template from detached data-disks on VMWare

systemvm/debian/opt/cloud/bin/cs/CsDhcp.py
The DNS entry "data-server" was not added in /etc/hosts.
Since the VR is now considered as a "dhcpsrvr" (?), we need to apply this commit to add this DNS entry. 
**/etc/hosts** is fully rewritten by this script.
Fixes: #4308
Tried on a VMWare cluster.
Login into the VR via SSH. Apply the patch.
Deploy a new VM.
Check "data-server" is now listed in /etc/hosts:
```shell
root@r-11-VM:/opt# cat /etc/hosts |grep data-server
10.2.111.18     r-11-VM data-server
```
=> Fix "data-server" dns entry in /etc/hosts after a new deployment

client/bindir/cloud-setup-management.in, python/lib/cloudutils/serviceConfig.py, python/lib/cloudutils/syscfg.py
Disabling managing iptables on the management server since the host might be using unsupported firewall management tools
=> Disabling managing firewall - cloudstack-setup-management

scripts/vm/network/security_group.py
When use Ubuntu 20.04 as hypervisor, and create an advanced zone with security groups, the systemvms (ssvm and cpvm) are started but the cloud service is not be Up.
in /var/log/cloud.log, it says vm is unable to connect to management server on port 8250.
Later I found there is caused by a iptables rule below
```
-A BF-cloudbr0 -m physdev --physdev-out ens3: --physdev-is-bridged -j ACCEPT
```
The physical device should be "ens3" and "ens3:", which comes from
```
root@node62:~# bridge -o link show | awk '/master cloudbr0 / && !/^[0-9]+: vnet/ {print $2}' | head -1
ens3:
```
There is no issue with ubuntu 16.04
```
root@node12:~# bridge -o link show | awk '/master cloudbr0 / && !/^[0-9]+: vnet/ {print $2}' | head -1
eth0
```
=> Ubuntu 20.04: Fix systemvm cannot start up

debian/control
Changing dependency from python3-distutils to python3-distutils-extra to continue supporting Ubuntu 16.04
=> Changing dependency from python3-distutils to python3-distutils-extra

plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java, vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/VirtualMachineMO.java
In large environments, with VR having multiple nics when plugging in
nic, it must get existing nics by sorted device ID otherwise it may
cause incorrect nic plugging/order.
Fixes #4246
=> vmware: while plugging in nics get existing sorted nic devices

plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java, vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/ClusterMO.java, vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/HostMO.java, vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/VmwareHypervisorHost.java
VMware code keeps a cache of existing VMs on a hypervisor host using `cloud.vm.internal.name` property of the VM. Searching for unmanaged instances/VMs on a host might not return an expected result when this property differs from the actual name of the VM.
To reproduce:
- Deploy a VM in vCenter
- Set custom attribute for the VM with key = `cloud.vm.internal.name` and value = `Anything different than VM name`
- listUnmanagedInstance API fails when `name` parameter with name of the VM
- importUnmanagedInstance API fails for the VM
With API using cmk
VM in vcenter having a different name and custom attribute `cloud.vm.internal.name`
Both listUnmanagedInstance and importUnmanagedInstance
```
> list unmanagedinstances clusterid=5c46e61a-4f4e-478a-8479-613156747764 name=clone
{
"count": 1, …
```
=> vmware: search unmanaged instances using hypervisor name

api/src/main/java/com/cloud/network/Networks.java, engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java, engine/orchestration/src/test/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestratorTest.java
This PR sets properly Broadcast URI to `vxlan://vxlan_id` when the physical network is of VXLAN.
Fixes: #3040
Description of issue #3040:
> Advanced Network zone with VXLAN is created. When creating a guest network and setting the VNI this is set for the network:
>     broadcast_uri: vlan://1000
>     isolation_uri: vlan://1000
> 
> STEPS TO REPRODUCE
> 
>     Create a Advanced Zone with VXLAN
>     Create a guest network
>     See that broadcast is set to vlan and not vxlan
**Prior to the fix:**
**After the fix:**
1. Create a Advanced Zone with VXLAN
2. Create a guest network
3. See that broadcast uri is set to vxlan
=> Broadcast URI not set to vxlan, but vlan (Fix #3040)

test/integration/smoke/test_pvlan.py
Changing test_pvlan vlan id to prevent conflict with env config while running smoke tests
Previously failed due to intermittent errors while running smoke tests 
```
The VLAN tag 1234 is already being used for dynamic vlan allocation for the guest network in zone
```
Run the smoke tests and see :wink:
=> Changing test_pvlan vlan id to prevent conflict with smoke tests env config

packaging/systemd/cloudstack-agent.default, packaging/systemd/cloudstack-management.default
Since Java 9 the notation 'address=port' only applies to localhost.
For remote debug you have to explicitly specify that you want to listen
to all IP addresses (e.g. address=*:8000)
- [ x] Enhancement (improves an existing feature and functionality)
tested on master and 4.14
=> Binding listening socket to all address for remote debug

server/src/main/java/com/cloud/deploy/DeploymentPlanningManagerImpl.java
If vm has last host_id specified, cloudstack will try to start vm on it at first.
However, host tag is checked, but guest os preference is not checked.
for new vm, it will be deployed to the preferred host as we expect.
Fixes: https://github.com/apache/cloudstack/issues/3554#issuecomment-564001531
=> server: check guest os preference of last host when start a vm

engine/schema/src/main/java/com/cloud/storage/dao/VMTemplateDaoImpl.java, plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java, plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterDestroyWorker.java, plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterResourceModifierActionWorker.java, plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterStartWorker.java, plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/version/KubernetesVersionManagerImpl.java, plugins/integrations/kubernetes-service/src/main/java/org/apache/cloudstack/api/command/admin/kubernetes/version/AddKubernetesSupportedVersionCmd.java, plugins/integrations/kubernetes-service/src/main/java/org/apache/cloudstack/api/command/admin/kubernetes/version/DeleteKubernetesSupportedVersionCmd.java, plugins/integrations/kubernetes-service/src/main/java/org/apache/cloudstack/api/command/user/kubernetes/cluster/CreateKubernetesClusterCmd.java, plugins/integrations/kubernetes-service/src/main/java/org/apache/cloudstack/api/command/user/kubernetes/cluster/DeleteKubernetesClusterCmd.java, plugins/integrations/kubernetes-service/src/main/java/org/apache/cloudstack/api/command/user/kubernetes/cluster/ScaleKubernetesClusterCmd.java, plugins/integrations/kubernetes-service/src/main/java/org/apache/cloudstack/api/command/user/kubernetes/cluster/StartKubernetesClusterCmd.java, plugins/integrations/kubernetes-service/src/main/java/org/apache/cloudstack/api/command/user/kubernetes/cluster/StopKubernetesClusterCmd.java, plugins/integrations/kubernetes-service/src/main/java/org/apache/cloudstack/api/command/user/kubernetes/cluster/UpgradeKubernetesClusterCmd.java, scripts/util/create-kubernetes-binaries-iso.sh, test/integration/smoke/test_kubernetes_clusters.py, test/integration/smoke/test_kubernetes_supported_versions.py, tools/marvin/marvin/config/test_data.py
Fixes #4265 
Fixes for:
- template selection
- network cleanup
- capacity check
- specific patch version during deployment
=> cks: assorted fixes, test refactoring

plugins/outofbandmanagement-drivers/redfish/src/main/java/org/apache/cloudstack/outofbandmanagement/driver/redfish/RedfishOutOfBandManagementDriver.java, utils/src/main/java/org/apache/cloudstack/utils/redfish/RedfishClient.java, utils/src/test/java/org/apache/cloudstack/utils/redfish/RedfishClientTest.java
It is not common, but HTTP requests can fail due to connection issues. In order to mitigate such situations and also improve logging, this PR enhances the Redfish request handling by adding an execution flow for re-trying HTTP requests; the retry happens only if the global settings `redfish.retries` is set to 1 or more retries; default is of 2 (two). One can disable the retries by setting `redfish.retries` to 0 (zero).
Configured a test environment to ignore SSL while using HTTPS for Redfish requests. In such cases, IOExcetions will happen on a higher frequency than any other setup due to the exception `javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake`.
The following log shows GET requests that failed a couple of times, the successful request happened at the third …
=> Retry redfish requests

api/src/main/java/org/apache/cloudstack/api/command/admin/account/CreateAccountCmd.java
Updating the account parameter description to let the user know that a new account will be created rather than the user being added to an existing account
=> createaccountcmd: Improving account param description

plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/discoverer/XcpServerDiscoverer.java, plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/CitrixResourceBase.java, plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/wrapper/xenbase/XenServerUtilitiesHelper.java
=> hypervisor: Add Citrix Hypervisor 8x product name support

engine/schema/src/main/java/com/cloud/host/dao/HostDaoImpl.java, engine/schema/src/main/java/com/cloud/network/as/dao/AutoScaleVmGroupVmMapDaoImpl.java, engine/schema/src/main/java/com/cloud/vm/dao/DomainRouterDaoImpl.java, engine/schema/src/main/java/org/apache/cloudstack/storage/datastore/db/ImageStoreDaoImpl.java, framework/db/src/main/java/com/cloud/utils/db/GenericDaoBase.java, server/src/main/java/com/cloud/api/query/dao/TemplateJoinDaoImpl.java
Fixes https://github.com/apache/cloudstack/issues/4372
Ensures that the count returned by searchAndCount searchAndDistinctCount do not include removed items
Before, it would return the count of removed items  as well when the search criteria is null (since sc is created and modified in search which doesn't reflect when it tires to get the count)
Also refactored a bit to make life easieer for the next person who comes along
Before :
```
(localcloud) SBCM5> > list roles filter=
{
"count": 11,
"role": [
{},
{},
{},
{},
{},
{},
{},
{},
{}
]
}
```
After : 
```
(localcloud) SBCM5> > list roles filter=
{
"count": 9,
"role": [
{},
{},
{},
{},
{},
{},
{},
{},
{}
]
}
```
=> Fixing searchAndCount searchAndDistinctCount when sc is null

server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
Only the following offerings are accepted
(1) fixed offering:
cpunumber, memory, must be specified.
cpuspeed should be specified
example: create serviceoffering displaytext=offering-fix name=offering-fix cpunumber=1 memory=1024 cpuspeed=1000
(should not work)
create serviceoffering displaytext=offering-fix name=offering-fix cpunumber=1 memory=1024 (but works in 4.14, fixed by this commit)
(2) unconstrained offering:
cpunumber, memory must be null
cpuspeed must be null
example: create serviceoffering displaytext=offering-unconstrained name=offering-unconstrained
(should not work)
create serviceoffering displaytext=offering-unconstrained name=offering-unconstrained cpunumber=1
create serviceoffering displaytext=offering-unconstrained name=offering-unconstrained memory=1024
create …
=> server: Fix some cpuspeed issues while create service offering

api/src/main/java/org/apache/cloudstack/api/command/user/vm/ListVMsCmd.java, server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
List VMs by "security group ID" and/or "ha enabled"
Improve List VMs command allowing to list VMs filtering by security group or HA enabled.
List VMs via API with different combinations. All worked fine.
- filter vms with security group ID
`list virtualmachines filter=id,name,haenable,securitygroup listall=true securitygroupid=<SG UUID>`
- list VMs according to the HA enabled
`list virtualmachines filter=id,name,haenable,securitygroup listall=true haenable=true`
`list virtualmachines filter=id,name,haenable,securitygroup listall=true haenable=false`
- combione both added parameters
`list virtualmachines filter=id,name,haenable,securitygroup listall=true haenable=false securitygroupid=<SG UUID>`
`list virtualmachines filter=id,name,haenable,securitygroup listall=true haenable=true …
=> List VMs by Security Group & HA

plugins/integrations/prometheus/src/main/java/org/apache/cloudstack/metrics/PrometheusExporterImpl.java
We should have the metrics for the hosts which are dedicated to certain domains.
We should also be able to see cpu/memory/storage currently used per domain
Enable prometheus server
Add 127.0.0.1 as allowed Ip so that you can fetch metrics from prometheus
Now fetch the endpoint
```
cloudstack_host_is_dedicated{zone="mgt122-10",hostname="node11",ip="10.13.122.11"} 1
cloudstack_host_dedicated_to_account{zone="mgt122-10",hostname="node11",ip="10.13.122.11"} 1
```
=> Export dedicated host stats to prometheus

plugins/integrations/prometheus/src/main/java/org/apache/cloudstack/metrics/PrometheusExporterImpl.java, server/src/main/java/com/cloud/api/query/vo/HostJoinVO.java
If the resource state of hypervisor in "Maintenance" then it
should be considered as offline even though the agent state
is "Up". Since its in maintenance mode, it cant be used to
allocate VM's and hence can't be considered towards resource
allocation
Enable prometheus server
Add 127.0.0.1 as allowed Ip so that you can fetch metrics from prometheus
Now fetch the endpoint
```
cloudstack_hosts_total{zone="mgt122-10",filter="online"} 3
cloudstack_hosts_total{zone="mgt122-10",filter="offline"} 0
cloudstack_hosts_total{zone="mgt122-10",filter="total"} 3
```
=> Consider maintenance mode as offline for prometheus stats

scripts/vm/network/vnet/modifyvxlan.sh
modifyvxlan.sh script fails run as it isn't able to find the /var/run/cloud directory to create the lock file
Fixes: https://github.com/apache/cloudstack/issues/4350
- Deployed an Advanced zone with VXLAN as isolation method
- deployed a VM in an isolated network
=> Handles creation /var/run/cloud folder for creation of lock file while modifyvxlan.sh script is run

engine/api/src/main/java/com/cloud/vm/VirtualMachineManager.java, engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java, server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java, server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
…
vm.serviceoffering.cpu.cores.max and vm.serviceoffering.ram.size.max
=> Add global configuration for max cpu/ram in service offerings

debian/control
=> debian/control: add uuid-runtime to cloudstack-common, ufw/apparmor to cloudstack-agent

plugins/integrations/prometheus/src/main/java/org/apache/cloudstack/metrics/PrometheusExporterImpl.java
If hosts have multiple host tags, the total/up/down hosts in prometheus exporter are not correct.
=> Host is counted twice if it has multiple host tags in Prometheus exporter

plugins/integrations/kubernetes-service/src/main/java/org/apache/cloudstack/api/command/user/kubernetes/cluster/ScaleKubernetesClusterCmd.java
Calling scaleKubernetesCluster without passing id leads to an NPE.
This fixes it by making id a required field
```
2020-10-14 07:21:42,384 DEBUG [c.c.a.ApiServlet] (qtp1136419747-1767:ctx-891b1ffe) (logid:540851f6) ===START===  103.252.26.201 -- GET  command=scaleKubernetesCluster&response=json&sessionkey=6OIs3d7CiMpwiLGldPTTRyp6A4M
2020-10-14 07:21:42,393 DEBUG [c.c.a.ApiServer] (qtp1136419747-1767:ctx-891b1ffe ctx-6211cc7c) (logid:540851f6) CIDRs from which account 'Acct[27ef5ba2-5fe0-11ea-9a56-1e006800018c-admin]' is allowed to perform API calls: 0.0.0.0/0,::/0
2020-10-14 07:21:42,399 ERROR [c.c.a.ApiServer] (qtp1136419747-1767:ctx-891b1ffe ctx-6211cc7c) (logid:540851f6) unhandled exception executing api command: [Ljava.lang.String;@48aca284
at …
```
=> scalekubernetesclustercmd: Making id a required field [NPE Fix]

plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java
Fixes #4343 
When `config.hotPlugMemoryIncrementSize` is zero for a VM (particularly system VMs) current code throws exception,
```
2020-09-25 12:02:56,037 ERROR [c.c.v.VmWorkJobHandlerProxy] (Work-Job-Executor-7:ctx-49f0bbbf job-133/job-137 ctx-fd9070d9) (logid:89f87423) Invocation exception, caused by: com.cloud.utils.exception.CloudRuntimeException: Unable to scale vm due to Unable to execute ScaleVmCommand due to java.lang.ArithmeticException: / by zero
2020-09-25 12:02:56,037 INFO  [c.c.v.VmWorkJobHandlerProxy] (Work-Job-Executor-7:ctx-49f0bbbf job-133/job-137 ctx-fd9070d9) (logid:89f87423) Rethrow exception com.cloud.utils.exception.CloudRuntimeException: Unable to scale vm due to Unable to execute ScaleVmCommand due to java.lang.ArithmeticException: / by zero
2020-09-25 …
```
=> vmware: use hotPlugMemoryIncrementSize only for valid value

agent/src/main/java/com/cloud/agent/Agent.java, core/src/main/java/com/cloud/agent/api/ShutdownCommand.java, server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java, server/src/main/java/com/cloud/hypervisor/kvm/discoverer/LibvirtServerDiscoverer.java
Fixes #4218 
If a host is removed from cloudstack, it will be
added back if we restart the agent service on
the host. It should not be added back if manualy
removed.
Provide a global setting "add.host.on.service.restart" with
default value of true. If set to false, the zoneid,
clusterid and podid in agent.properties will be set to
null so that when service is restarted, the agent is not
added back
If true these values will not be set to null so that it
can be still added back on service restart
1. Add a host from ui. It will be successfully added
2. Now remove the host
3. Set the global setting `add.host.on.service.restart` to false
3. ssh to host and restart cloudstack-agent service
4. The host is not added back
5. Try to add host from ui again. It will be added
=> Dont add host back after agent service restart

plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
=> kvm: fix wrong VM CPU usage

server/src/main/java/com/cloud/template/TemplateManagerImpl.java
(1) change vm guest os type
(2) update vm template (guest os type is not changed)
(3) vm guest os type is reset to guest os type of template.
=> server: fix issue that vm guest os type is reset after updatetemplate

server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
Fix mistake from PR #4397 where I removed the affinity group ID when adding security group ID.
Fixes: #4397
=> Re-add affinity group

usage/src/main/java/com/cloud/usage/UsageManagerImpl.java, usage/src/test/java/com/cloud/usage/UsageManagerImplTest.java
On these days, when a VM snapshot is deleted, the `cloudstack-usage` still seeing that snapshot as active and continues billing this deleted snapshot. This PR proposes new methods to handle with `vm_snapshot_create` and `vm_snapshot_delete` events.   
Also, add some unit tests to cover those new methods.  
I don't know why the `cloudstack-usage` duplicate entries for vm_snapshot. I think this is a bug and I'll fix it in a future PR.  
To run tests,  I create a VM snapshot and used the `cloudmonkey` to list usageRecords type=25.  
**Created at 14:12**
```
() 🐱 > list usagerecords startdate=2020-08-08 enddate=2020-08-08 type=25
{
"count": 2,
"usagerecord": [
{
"description": "VMSnapshot usage Id: 1 (7b63f2f0-61fc-4034-8438-26e8989e3503)  for VM …
```
=> Handle with VM snapshot events

api/src/main/java/org/apache/cloudstack/api/command/admin/offering/UpdateDiskOfferingCmd.java, engine/schema/src/main/java/com/cloud/storage/DiskOfferingVO.java, server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java, server/src/test/java/com/cloud/configuration/ConfigurationManagerTest.java, ui/scripts/configuration.js
On this PR [#2636]((https://github.com/apache/cloudstack/pull/2636)), @rafaelweingartner proposed a consistent validation mechanism to select a storage pool to deploy a volume when a virtual machine is deployed or when a new data disk is allocated.
The following table presents the scenarios when the storage_pool supports or not a new data disk.
| #	| Disk offering tags	| Storage tags	| Does the storage support the disk offering?	|
|---| ---					| ---			| ---											|
| 1	| A,B					| A				| NO											|
| 2	| A,B,C					| A,B,C,D,X		| YES											|
| 3	| A,B,C					| X,Y,Z			| NO											|
| 4	| null					| A,S,D			| YES											|
| 5	| A						| null			| NO											|
| 6	| null					| null			| YES											|
With that in mind, this PR enables `updateDiskOfferingCmd` to edit …
=> enable update tags on disk offerings

engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/DataMigrationUtility.java, engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/StorageOrchestrator.java, engine/schema/src/main/java/org/apache/cloudstack/storage/datastore/db/SnapshotDataStoreVO.java, engine/schema/src/main/java/org/apache/cloudstack/storage/datastore/db/TemplateDataStoreVO.java, engine/schema/src/main/java/org/apache/cloudstack/storage/datastore/db/VolumeDataStoreVO.java, engine/storage/image/src/main/java/org/apache/cloudstack/storage/image/SecondaryStorageServiceImpl.java, engine/storage/src/main/java/org/apache/cloudstack/storage/image/BaseImageStoreDriverImpl.java, services/secondary-storage/controller/src/main/java/org/apache/cloudstack/secondarystorage/PremiumSecondaryStorageManagerImpl.java, services/secondary-storage/server/src/main/java/org/apache/cloudstack/storage/resource/NfsSecondaryStorageResource.java
PR attempts to fix and enhance the following:
- On Xen, there are instances when the child snapshot is basically only a database entry with the file path pointing to the parent snapshot - handle this scenario such that a new entry is created for such incremental snapshots and delete the snapshot from source datastore during data migration
- Wrt scaling down of SSVM, revised the logic to prevent quick scaling down of the SSVMs
- Conducted tests on xen of files 
Tests on xen for snapshots with child snaps having install path same as that as parent snapshot
```
Before Migration:
-----------------------
MariaDB [cloud]> select * from snapshot_store_ref where store_role = 'Image' and volume_id =11 and state <> 'Destroyed' order by parent_snapshot_id\G
*************************** 1. row …
```
=> support for data migration of incremental snaps on xen

packaging/systemd/cloudstack-management.default
The default GC algorithm G1 that is enabled by default with Java11
serves well on multiprocessor machines with large amount of memory where
GC is probablistic with low pauses, where response time is more
important than throughput and GC is kept shorter.
The CloudStack management server is largely a multi-threaded server
application that handles and orchestrates several network requests, and
has the default max. heap size of only 2G that can be considered a
small/medium application from a heap size perspective. Perhaps a more
aggresive GC algorithm such as ParallelGC as used in Java8 and before
(that is previous CloudStack releases) would serve better for throughput
and cause more aggressive GC.
This PR propose a change in default GC algorithm to avoid OOM issues.
Reference: …
=> packaging: enable Parallel Collector GC for management server

framework/jobs/src/main/java/org/apache/cloudstack/framework/jobs/impl/AsyncJobManagerImpl.java, framework/jobs/src/test/java/org/apache/cloudstack/framework/jobs/AsyncJobManagerTest.java
Added missing `\"` (from `"*****"` to `"*****\""`) at _obfuscatePassword method from AsyncJobManagerImpl.java#L485_
https://github.com/apache/cloudstack/blob/0f3f2a09370a18301db28ec3d28efe746b6437c9/framework/jobs/src/main/java/org/apache/cloudstack/framework/jobs/impl/AsyncJobManagerImpl.java#L485
The lack of `"` caused a JsonSyntaxException exception when the host response had a password (e.g. if the host has out of band enabled e.g. IPMI or Redfish).
Fixes: #4355
- JUnit test
- manual tests
=> Fix JsonSyntaxException when creating API command response #4355 

api/src/main/java/com/cloud/network/Network.java, api/src/main/java/org/apache/cloudstack/api/command/user/network/ListNetworksCmd.java
Validating the `type` parameter for the listNetworks API.
Also allowing all type to be passed
```
(localhost) 🐱 > list networks type=usolated
🙈 Error: (HTTP 431, error code 4350) Unexpected Guest type : usolated
list networks type=all
(localhost) 🐱 > list networks type=all filter=name
{
............
}
```
=> Validating type parameter and including all types

plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java, plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterStartWorker.java
When tried to downalod kubernetes cluster config,
it throws a pop up with uuid of kubernetes cluster
instead of its name. Displaying uuid isnt useful
even for domain admins.
=> Display Kubernetes cluster name instead of uuid

engine/schema/src/main/java/org/apache/cloudstack/storage/datastore/db/StoragePoolVO.java, server/src/main/java/com/cloud/server/StatsCollector.java, server/src/main/java/com/cloud/storage/StorageManagerImpl.java
Update the used_bytes for all default primary storage pools
Also, get used_bytes of storage pool from the database instead of
memory
Below sql query should return the latest used bytes of the storage pol
```
mysql> select * from storage_pool\G
id: 1
name: primary1
uuid: 74d0b-9e65-3183-8345-e749fcd0e
pool_type: NetworkFilesystem
port: 2049
data_center_id: 1
pod_id: NULL
cluster_id: NULL
used_bytes: 10363076608
capacity_bytes: 52709818368
host_address: 10.135.122.14
user_info: NULL
path: /data/primary1
created: 2020-07-10 09:27:51
removed: NULL
update_time: 2020-09-30 10:50:19
status: Up
storage_provider_name: DefaultPrimary
scope: ZONE
hypervisor: KVM
managed: 0
capacity_iops: NULL
1 row in set (0.01 sec)
```
=> server: Update use_bytes of storage pools

systemvm/debian/opt/cloud/bin/cs/CsApp.py, systemvm/debian/opt/cloud/bin/cs/CsProcess.py
This fixes the issues described in #4384 and #4386
=> systemvm: fix proc.find in CsProcess.py

api/src/main/java/org/apache/cloudstack/api/command/admin/offering/UpdateDiskOfferingCmd.java, server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java, server/src/test/java/com/cloud/configuration/ConfigurationManagerTest.java
This PR adds the ability to update the following disk offering fields
- cache-mode,
- IOPS (Read/Write) Rate, IOPS (Read/Write) Rate Max, IOPS (Read/Write) Rate Max Length
- Bytes (Read/Write) Rate,  Bytes (Read/Write) Rate Max, Bytes (Read/Write) Rate Max Length
1. Execute multiple API requests updating different combinations with the included (13) parameters.
2. Assert that all parameters got updated on DB accordingly.
3. Ensure that IOPS/Bytes validations are properly done, e.g. expected Exceptions such as `Bytes Write rate (5000) cannot be greater than Bytes Write maximum rate (3000)`.
=> Enhance UpdateDiskOfferingCmd

server/src/main/java/com/cloud/server/ManagementServerImpl.java
Fixes https://github.com/apache/cloudstack/issues/4371
In the code, all servers, and their count belonging to the same zone are returned. Then they are filtered for suitability.
This is fine except for the point where VM volumes existing on managed storage pools or hosts on which those storage pools are not suitable. In this case it removes the hosts rather than marking them as not suitable. This messes up the count. Subtracting the non suitable hosts count does not fix this since we're paginating the response so unsuitable hosts and thier count from the current page will be removed but will not fix the total count since hosts on other pages can not be filtered.
Another place is that the source host is removed from the list but the count is not adjusted
Before :
```
{
"count": 4,
"host": …
```
=> Fixing count for findHostsForMigration

plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java, plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterActionWorker.java, plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterDestroyWorker.java, plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterResourceModifierActionWorker.java, plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterScaleWorker.java, plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterStartWorker.java, plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterStopWorker.java, plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterUpgradeWorker.java, plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/utils/KubernetesClusterUtil.java
Changing log details from cluster / node UUID to name 
Add-on to https://github.com/apache/cloudstack/pull/4411
=> CKS : More log changes from uuid to name

api/src/main/java/org/apache/cloudstack/api/ApiConstants.java, plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java, plugins/integrations/kubernetes-service/src/main/java/org/apache/cloudstack/api/response/KubernetesClusterResponse.java, test/integration/smoke/test_kubernetes_clusters.py
Returning list of virtual machine nodes of a cluster rather than just their IDs. Simplifies the UI as well (Reduces API calls and checks post 4.15 release in primate for backward compatibility)
```
(kubeadmin) 🐱 > list kubernetesclusters id=3d2d10cd-db04-4c4f-87f0-7405d45333e8 
{
"count": 1,
"kubernetescluster": [
{
.....
"name": "cluster-1",
"virtualmachines": [
{
.....
"displayname": "cluster-1-master-1754f2cc2da",
.....
},
{
.....
"displayname": "cluster-1-node-1754f2cd5f1",
.....
}
],
}
]
}
```
=> Including instance details in KubernetesClusterResponse

server/src/main/java/com/cloud/capacity/CapacityManagerImpl.java, server/src/main/java/com/cloud/resource/ResourceManagerImpl.java
When a host is put into maintenance mode or its deleted from
cloud stack then delete its entries from the op_host_capacity table
Currently, only memory and CPU information is deleted from the table.
Delete a host or put a host into maintenance mode.
All the entries related to this host in op_host_capacity should be deleted
=> Remove cpu core from op_host_capacity when host is deleted 

plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java, plugins/integrations/kubernetes-service/src/main/java/org/apache/cloudstack/api/response/KubernetesClusterResponse.java
Adding public ip to listKubernetesClusterResponse to make life easier as well as enhance the UI 
```
(localcloud) SBCM5> > list kubernetesclusters 
{
"count": 1,
"kubernetescluster": [
{
..........
"ipaddress": "10.1.36.3",
"ipaddressid": "a961de46-6a77-4e20-b078-2870853286a2",
..........
}
]
}
```
=> Adding public ip to listKubernetesClusterResponse

engine/schema/src/main/resources/META-INF/db/schema-41400to41500.sql
As a best practice, it is better to drop and create a new view as opposed to altering a view. The PR addresses changing alter view to re-creation of the views after being dropped
Run upgrade test:
1. deployed a 4.14 setup
2. Created some projects, added/invites a few users
3. Upgraded to 4.15
4. listed projects, project invitations to verify that they are still intact
=> Modify alter view to drop/create view

server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java, server/src/main/java/com/cloud/resource/ResourceManagerImpl.java
Adds a new global setting set.host.down.to.maintenance which when set
to true will allow setting a host in downstate into maintenance mode
so that when the host comes back up, it will be automatically set to
maintenance mode and the resource state will not be set to Enabled.
1, Power off one hypervisor so that it enters DOWN state
2. set the global setting `set.host.down.to.maintenance` to true
3. Enable maintenance mode on that host
4. Start the hypervisor
5. When it comes back up, it will be in maintenance mode
=> Ability to put a server in Down state to maintenance

api/src/main/java/org/apache/cloudstack/api/command/user/template/UpdateTemplateCmd.java, api/src/main/java/org/apache/cloudstack/api/response/TemplateResponse.java, server/src/main/java/com/cloud/api/query/dao/TemplateJoinDaoImpl.java, server/src/main/java/com/cloud/template/TemplateManagerImpl.java, ui/scripts/templates.js
this contains other changes
(1) add isrouting field for vm templates on UI
(2) show register URL of template/iso on UI
(3) set 'Bootable' field to changable for existing ISO
this provides a easy way to upload systemvm template
(1) register template
(2) update template type from USER to SYSTEM
(3) destroy ssvm/cpvm, new systemvms will be created from the new template (latest template with type=SYSTEM)
(4) change global setting router.template.kvm (or other hypervisor) to the name of new template, new VRs will be created from the new template.
=> server: update template to another template type

usage/src/main/java/com/cloud/usage/UsageManagerImpl.java
cloudstack-usage use System.getProperty("pid") to get the process PID
System.getProperty cannot get the Pid, which will cause the service to stay in the config stage. Cannot continue to start, and there will be no log output.
This PR uses ManagementFactory instead of System.getProperty to get Pid, and throws an exception when Pid cannot be obtained
=> Fix Usage failed to get pid

server/src/main/java/com/cloud/storage/snapshot/SnapshotManagerImpl.java, server/src/test/java/com/cloud/storage/snapshot/SnapshotManagerTest.java
When tried to create snapshot from vm snapshot, we get NPE
Steps to reproduce
1. create a vm
2. Create vm snapshot
3. Try to create snapshot from vm snapshot
```
2020-10-27 12:48:29,466 INFO  [o.a.c.a.c.u.s.CreateSnapshotFromVMSnapshotCmd] (API-Job-Executor-2:ctx-b56cf1c3 job-38 ctx-3b69b2d1) (logid:00211b32) CreateSnapshotFromVMSnapshotCmd with vm snapshot id:2 and snapshot id:1 starts:1603802909463
2020-10-27 12:48:29,507 DEBUG [o.a.c.a.c.u.s.CreateSnapshotFromVMSnapshotCmd] (API-Job-Executor-2:ctx-b56cf1c3 job-38 ctx-3b69b2d1) (logid:00211b32) Failed to create snapshot
at com.cloud.storage.snapshot.SnapshotManagerImpl.backupSnapshotFromVmSnapshot(SnapshotManagerImpl.java:469)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native …
```
=> Unable to create snapshot from vm snapshot

engine/schema/src/main/resources/META-INF/db/schema-41400to41500.sql
The guest os 'Other PV Virtio-SCSI (64-bit)' has category_id as 6 ("Windows"), which should be 7 ("Other").
```
mysql> select * from guest_os where id=275\G
id: 275
category_id: 6
name: NULL
uuid: 5f080e85-c0fd-11ea-ba74-067606003392
display_name: Other PV Virtio-SCSI (64-bit)
created: 2020-07-08 09:28:24
removed: NULL
is_user_defined: 0
mysql> select * from guest_os_category;
+----+---------+--------------------------------------+
| id | name    | uuid                                 |
+----+---------+--------------------------------------+
|  1 | CentOS  | 45bfdf47-c0fd-11ea-ba74-067606003392 |
|  2 | Debian  | 45c0529b-c0fd-11ea-ba74-067606003392 |
|  3 | Oracle  | …
```
=> DB: fix wrong category id of guest os 'Other PV Virtio-SCSI (64-bit)'

server/src/main/java/com/cloud/server/ManagementServerImpl.java
If the entries for a host in host_details table are missing then we cant update the
password of the host using the cloudmonkey command
This can happen because host was removed earlier resulting in deletion
of entries in the database
This commit fixes the issue
(local) mgt01 > update hostpassword
hostid=50436ac8-b73a-4eaf-bbab-7adbd9a50870 username=root
password=cloudstack
{
"success": true
}
Now the entries should be added in host_details table as well
Using cloudmonkey api updateHost
=> Failed to update host password if username/password is not saved in db

server/src/main/java/com/cloud/network/vpn/Site2SiteVpnManagerImpl.java
When we try to reset the site 2 site vpn connection while
the VR's are being restarted, the connection enters the
PENDING state and we cant reset the connection.
So change the state from PENDING to disconnected.
1.create a VPC with a tier (vpc-001-001 in vpc-001), create a vm
2.create a VPC with a tier (vpc-002-001 in vpc-002) with different cidr, create a vm
3.create custom gateway for both vpn
4.enable site-to-site vpn on both vpn, and add vpn connection to each other. both should be "Connected"
5.restart vpc-001 with cleanup and monitor it
6.when the first router is destroyed, go to site-to-site vpn page and reset vpn connection.
7.we will get an error "Resource [DataCenter:1] is unreachable: Unable to apply site 2 site VPN configuration, virtual router is …
=> FIX s2svpn connection stuck on Pending state

server/src/main/java/com/cloud/api/query/dao/HostJoinDaoImpl.java
Before change
```
"memoryallocated": 2415919104,
"memorytotal": 7274721280,
"memoryused": 3231264768,
"memorywithoverprovisioning": "7.2747213E9",
```
after change
```
"memoryallocated": 2415919104,
"memorytotal": 7274721280,
"memoryused": 3231264768,
"memorywithoverprovisioning": "7274721280",
```
=> server: fix format error with memorywithoverprovisioning in list hosts response

engine/schema/src/main/java/com/cloud/dc/dao/ClusterDaoImpl.java, server/src/main/java/com/cloud/api/query/ViewResponseHelper.java, server/src/main/java/com/cloud/server/StatsCollector.java, server/src/main/java/com/cloud/vm/UserVmManager.java, server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
If volume is migrated between storage pools and "volume.stats.interval"
is set to more frequent interval for example 30 sec.
NullPointerException is thrown, because the hypervisor is looking for
volume on storage pool from which the volume was migrated.
The statistics did not work right - before this fix only one cluster is
lists if we have more clusters from the same type (eg. KVM), and only
one host will return volume stats. Also all volumes are sent to that
host, but they could be on another host. And the logic does not work
correctly.
Also the response was not working correctly for QCOW2 images, because
it's looking for volume's UUID, but in the statistics CS keeps the path
(because of the migrated volumes which UUIDs are changed).
We have discussed the NPE with @Spaceman1984 in PR …
=> fix NPE in volumes statistics

api/src/main/java/org/apache/cloudstack/api/command/admin/offering/CreateServiceOfferingCmd.java, api/src/main/java/org/apache/cloudstack/api/command/user/volume/ResizeVolumeCmd.java, api/src/main/java/org/apache/cloudstack/api/response/ServiceOfferingResponse.java, engine/schema/src/main/resources/META-INF/db/schema-41400to41500.sql, server/src/main/java/com/cloud/api/query/dao/ServiceOfferingJoinDaoImpl.java, server/src/main/java/com/cloud/api/query/vo/ServiceOfferingJoinVO.java, server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java, server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java, server/src/main/java/com/cloud/vm/UserVmManagerImpl.java, server/src/test/java/com/cloud/vm/UserVmManagerImplTest.java, ui/scripts/configuration.js, ui/scripts/docs.js
Service Offering allows ADMINs to set multiple parameters such as IOPS, memory, and CPU; however, we still are not able to configure the Root Disk size of a VM via service Offering.
This PR adds control over the Root disk size and therefore helps providers that want to enforce the root disk size in the same way that it is done with compute offering.
**How does it work?**
- If the Service Offering is created without setting root disk size, all operations over root volume size are done as currently.
- If a Service Offering is created with a root disk size, then there are some (intentionally) limitations under the root disk size resizing, as the following ones:
```
1. Users cannot deploy VMs with custom root disk size when using such offerings
2. Users cannot resize the VM root disk size …
```
=> Allow to configure root disk size via Service Offering (diskoffering of type Service).

server/src/main/java/com/cloud/server/ManagementServerImpl.java
This PR removes system reserved IP addresses from the options of acquiring IP addresses. Choosing any reserved IP address results in an error. The IP addresses should not have been displayed in the first place.
Fixes: #4310 
Add a public IP address range and dedicate it to system VMs. 
Acquire new IP addresses - the system VM dedicated IP addresses should not be in the list.
=> Hiding system reserved IP addresses

systemvm/debian/opt/cloud/bin/configure.py
Use both tcp protocol and module so that
vpn is enabled properly
=> FIX issue in VR if remote access vpn is enabled

systemvm/debian/etc/logrotate.d/dnsmasq
This PR adds compression to dnsmasq log files
Fixes: #3756 
Log into virtual router
Check /var/log/ directory, observe dnsmasq.log
Change system time 1 day ahead  and reboot VR
Check /var/log/ directory, observe dnsmasq.log, dnsmasq.log1
Change system time 1 day ahead  and reboot VR
There should be 3 log files now and 1 should be compressed
Check /var/log/ directory, observe dnsmasq.log, dnsmasq.log1, dnsmasq.log.2.gz
=> Added compress option to dnsmasq log files

engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/VolumeOrchestrator.java
Fix for VMware SSVM recreation using deploy-as-is system VM templates
Fixes:
- Register a new system VM template
- Recreate SSVM -> ERROR
VMware environment
- Register a new system VM template
- Recreate SSVM
=> [Bug fix] VMware: Fix for SSVM recreation on deployasis systemVM templates

api/src/main/java/org/apache/cloudstack/usage/Usage.java, engine/components-api/src/main/java/com/cloud/event/UsageEventUtils.java, engine/components-api/src/main/java/com/cloud/network/IpAddressManager.java, engine/schema/src/main/java/com/cloud/usage/UsageIPAddressVO.java, engine/schema/src/main/java/com/cloud/usage/UsageVO.java, engine/schema/src/main/java/com/cloud/usage/dao/UsageIPAddressDaoImpl.java, engine/schema/src/main/resources/META-INF/db/schema-41400to41500.sql, server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java, server/src/main/java/com/cloud/network/IpAddressManagerImpl.java, server/src/main/java/com/cloud/usage/UsageServiceImpl.java, usage/src/main/java/com/cloud/usage/UsageManagerImpl.java, usage/src/main/java/com/cloud/usage/parser/IPAddressUsageParser.java
With this commit, listUsageRecords filters out usages made on IP addresses on networks with "Hide IP Address Usage". This was previously introduced in #3235.
This requires a DB schema change, to introduce a flag `is_hidden` in table `cloud_usage.cloud_usage`.
Cf. #4193
Multiple IP addresses have been created.
- Those on shared networks without "Hide IP Address Usage" generate usages normally;
- Those on shared networks with "Hide IP Address Usage" generate usages with flag `is_hidden`, and are not returned by the API.
=> Re-enable IP address usage hiding

server/src/main/java/org/apache/cloudstack/outofbandmanagement/PowerOperationTask.java
Out of band power operations are constantly issued to assess the host power status. However, if such actions fail the Admins receive a warning message on the log. In order to help Admins to easily track such failures, this PR creates an Event each time an Out-of-band power operation fails.
=> Create Event in case of OOBM failure

plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java
Adds nic details in KubernetesClusterResponse
Needed when the cluster is created on a shared network
```
(localcloud) SBCM5> > list kubernetesclusters 
{
"count": 1,
"kubernetescluster": [
{
"name": "k8sNew",
.....
"virtualmachines": [
{
"displayname": "k8sNew-master-175b10034fe",
.....
"nic": [
{
"broadcasturi": "vlan://7",
"extradhcpoption": [],
"gateway": "10.1.63.254",
"id": "b400c7d3-0e92-4520-ad1f-2872553de4cc",
"ipaddress": "10.1.39.61",
"isdefault": true,
"isolationuri": "vlan://7",
"macaddress": "1e:00:18:00:00:29",
"netmask": "255.255.224.0",
"networkid": "6df796e2-57d5-4f14-8a66-e72b955ec749",
"networkname": "sh",
"secondaryip": [],
"traffictype": "Guest",
"type": "Shared"
}
.....
]
],
"zoneid": "2a606f6d-d56e-47a5-9d6a-c432e7c972bf",
"zonename": …
```
=> Returning nic details in KubernetesClusterResponse

plugins/user-authenticators/saml2/src/main/java/org/apache/cloudstack/saml/SAMLUtils.java, server/src/main/java/com/cloud/api/ApiServlet.java
Addresses: https://github.com/apache/cloudstack/issues/4136
Upgraded an env from 4.13 to master (4.15) and then installed primate and attempted login. Login happens successfully.
=> fix login issue post upgrade

test/integration/component/test_volumes.py, test/integration/smoke/test_accounts.py, test/integration/smoke/test_deploy_virtio_scsi_vm.py, test/integration/smoke/test_deploy_vms_with_varied_deploymentplanners.py, test/integration/smoke/test_diagnostics.py, test/integration/smoke/test_routers.py, test/integration/smoke/test_vpc_vpn.py, test/integration/testpaths/testpath_storage_migration.py, tools/marvin/marvin/cloudstackTestCase.py
In this a small change to improve the marvin framework for resource cleanup and adding examples in the test-implementations.
=> default teardown methods with reversed() handling

engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
For Basic network isolation methods are not provided, and exception is
thrown when trying to encode the Vlan id. That's why we have to check
before encoding that the list with isolation methods is not empty
Reported issue #4450 
on branch 4.13 and master
Setup CloudStack through the old UI with the installation wizard (which creates Basic network).
=> Fix IndexOutOfBoundsException when creating basic network

api/src/main/java/org/apache/cloudstack/api/command/user/project/CreateProjectCmd.java, server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
1. A few changes made to `server/src/main/java/com/cloud/api/query/QueryManagerImpl.java` were reverted by commit: `fc05d3168f14584431a1a6b3c1f88cf04999cfaa`
2. Fix a check for parameters passed
=> Fix: Listing projects comprising of only the user's on listAll=true

systemvm/agent/scripts/ssvm-check.sh
Check all mgt server connectivity
Currently ssvm checks connectivity only for one mgt server.
Since we can have multiple mgt servers using comma separated
list, make the change in script so that it checks for connectivity
for all mgt servers
Before the fix
```
root@s-172-VM:~# /usr/local/cloud/systemvm/ssvm-check.sh
================================================
Management server is 10.135.122.10,10.135.122.15,10.135.122.16. Checking connectivity.
ERROR: Cannot connect to 10.135.122.10,10.135.122.15,10.135.122.16 port 8250
2020/11/03 12:58:34 socat[4508] E parseopts(): unknown option "10.135.122.15" <<<<<<<<<<<<<<
```
After the fix
```
root@s-175-VM:~# /usr/local/cloud/systemvm/ssvm-check.sh
================================================
Management server is …
```
=> Check all mgt server connectivity

server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
Many of the searching conditions are not considered when
template id is passed but they are considered only when
template id is not passed. Move other conditions out of else
part so that they will be considered when id is passed.
Without changes
```
(local) mgt01 > list templates templatefilter=all filter=id,hypervisor, id="45be18c7-c0fd-11ea-ba74-067606003392"
{
"count": 1,
"template": [
{
"hypervisor": "KVM",
"id": "45be18c7-c0fd-11ea-ba74-067606003392"
}
]
}
(local) mgt01 >
(local) mgt01 >
(local) mgt01 > list templates templatefilter=all filter=id,hypervisor, id="45be18c7-c0fd-11ea-ba74-067606003392" hypervisor=XenServer
{
"count": 1,
"template": [
{
"hypervisor": "KVM",
"id": "45be18c7-c0fd-11ea-ba74-067606003392"
}
]
}
```
With changes
```
(local) mgt01 > list templates …
```
=> Consider other conditions while listing templates with id

engine/storage/image/src/main/java/org/apache/cloudstack/storage/image/SecondaryStorageServiceImpl.java, engine/storage/src/main/java/org/apache/cloudstack/storage/image/BaseImageStoreDriverImpl.java, engine/storage/volume/src/main/java/org/apache/cloudstack/storage/volume/VolumeObject.java, services/secondary-storage/server/src/main/java/org/apache/cloudstack/storage/resource/NfsSecondaryStorageResource.java
This PR fixes a regression that was caused due to the following commit: https://github.com/apache/cloudstack/commit/d864e9dc39b69e590e3df898a03a874a8173fcc6 - which reverted the handler for data migration introduced by #4053.
Performed data migration operation and verified the behavior - performed against all hypervisors
=> Fix: Data migration

engine/schema/src/main/java/org/apache/cloudstack/storage/datastore/db/ImageStoreDao.java, engine/schema/src/main/java/org/apache/cloudstack/storage/datastore/db/ImageStoreDaoImpl.java, engine/schema/src/main/java/org/apache/cloudstack/storage/datastore/db/TemplateDataStoreDao.java, engine/schema/src/main/java/org/apache/cloudstack/storage/datastore/db/VolumeDataStoreDao.java, engine/storage/src/main/java/org/apache/cloudstack/storage/image/db/TemplateDataStoreDaoImpl.java, engine/storage/src/main/java/org/apache/cloudstack/storage/image/db/VolumeDataStoreDaoImpl.java, plugins/storage/image/default/src/main/java/org/apache/cloudstack/storage/datastore/driver/CloudStackImageStoreDriverImpl.java, server/src/main/java/com/cloud/server/ManagementServerImpl.java, server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java, server/src/main/java/com/cloud/template/TemplateManagerImpl.java, services/secondary-storage/controller/src/main/java/org/apache/cloudstack/secondarystorage/SecondaryStorageManagerImpl.java, services/secondary-storage/server/src/main/java/org/apache/cloudstack/storage/template/UploadManagerImpl.java
1. When SSVM is destroyed the downloaded urls of
template and volumes are not cleaned and because
of that we cant download the templates/volumes
using the download_url link
2. cleanup volumes in secondary storage when ssvm is destroyed
3. It should clean up the download urls for the templates belonging to the zone where ssvm is running
Steps to test
Before the fix
(1) download template (check download_url in template_store_ref table).
(2) destroy ssvm
(3) download template again
(4) It will fail to download
After the fix
1. Download template
2. Destroy ssvm
3. This will cleanup the download_url in template_store_ref table
4. Try to download template again
5. Download will be successful
Test case 2
Before the fix
1. create a vm
2. stop a vm
3. download volume
Volume stored in …
=> Cleanup download urls when SSVM destroyed

plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterDestroyWorker.java
Deletion of K8s cluster on shared networks fails due to attempt to clear network rules, however, no network rules get added for clusters brought up on Shared networks.
```
2020-11-10 16:46:26,125 WARN  [c.c.k.c.a.KubernetesClusterActionWorker] (API-Job-Executor-7:ctx-46554d1f job-67 ctx-cf887921) (logid:ed80132a) Failed to remove network rules of Kubernetes cluster : c1
com.cloud.exception.ManagementServerException: No source NAT IP addresses found for network : shared1
at com.cloud.kubernetes.cluster.actionworkers.KubernetesClusterDestroyWorker.deleteKubernetesClusterNetworkRules(KubernetesClusterDestroyWorker.java:145)
at com.cloud.kubernetes.cluster.actionworkers.KubernetesClusterDestroyWorker.destroy(KubernetesClusterDestroyWorker.java:242)
at …
```
=> Fix destroying k8s cluster on shared networks

scripts/util/create-kubernetes-binaries-iso.sh
Downloads images int the network and dashboard yaml while creating the kubernetes binaries iso
This step was skipped, so bringing up a cluster on a node that does not have access to the internet failed since the weavenet and dashboard images were not found locally
```
./create-kubernetes-binaries-iso.sh ./ 1.11.4 0.7.1 1.11.1 https://github.com/weaveworks/weave/releases/download/latest_release/weave-daemonset-k8s-1.11.yaml https://raw.githubusercontent.com/kubernetes/dashboard/v1.10.0/src/deploy/recommended/kubernetes-dashboard.yaml
..........
Downloading docker image k8s.gcr.io/kube-apiserver-amd64:v1.11.4 ---
Downloading docker image k8s.gcr.io/kube-controller-manager-amd64:v1.11.4 ---
Downloading docker image k8s.gcr.io/kube-scheduler-amd64:v1.11.4 ---
Downloading docker image …
```
=> createkubertetesbinariesiso: Saving images in network and dashboard yaml

api/src/main/java/org/apache/cloudstack/api/response/AccountResponse.java
Fixing the description of `domainpath`
=> accountresponse: Fix domainpath description

plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterUpgradeWorker.java
Upgrade of kubernetes cluster reports as successful on a shared network, when it doesn't successfully upgrade the nodes
Prior to the fix:
Deployed a 1.16.0 k8s cluster:
```
k8s-master ~ # kubectl get nodes
NAME         STATUS                     ROLES    AGE     VERSION
k8s-master   Ready,SchedulingDisabled   master   6m23s   v1.16.0
k8s-node-1   Ready                      <none>   5m51s   v1.16.0
```
Upgraded the cluster to 1.16.3, though the upgradeKubernetesCluster API returns a successful response, it doesn't upgrade the worker nodes:
```
k8s-master ~ # kubectl get nodes
NAME         STATUS   ROLES    AGE     VERSION
k8s-master   Ready    master   8m35s   v1.16.3
k8s-node-1   Ready    <none>   8m3s    v1.16.0
```
Post fix, once the upgrade completes i.e., when the …
=> Fix k8s cluster upgrade in shared networks

systemvm/debian/opt/cloud/bin/configure.py, systemvm/debian/opt/cloud/bin/cs/__init__.py, systemvm/debian/opt/cloud/bin/update_config.py
There are no logs in /var/log/cloud.log when something are changed in VRs (for example start vms, add/remove rules).
=> VR: fix logging is not working and logs are not appended to /var/log/cloud.log

api/src/main/java/org/apache/cloudstack/api/response/HostForMigrationResponse.java, api/src/main/java/org/apache/cloudstack/api/response/HostResponse.java, server/src/main/java/com/cloud/api/query/dao/HostJoinDaoImpl.java
Fixes https://github.com/apache/cloudstack/issues/4460
Adds `memoryallocatedpercentage` & `memoryallocatedbytes` to HostsResponse as well as HostsForMigrationResponse and deprecates `memoryallocated`
```
(localhost) 🐱 > list hosts filter=cpuallocated,memoryallocated,memoryallocatedbytes,memoryallocatedpercentage, type=Routing
{
"count": 2,
"host": [
{
"cpuallocated": "6.25%",
"memoryallocated": 2415919104,
"memoryallocatedbytes": 2415919104,
"memoryallocatedpercentage": "28.12%"
},
{
"cpuallocated": "1.56%",
"memoryallocated": 536870912,
"memoryallocatedbytes": 536870912,
"memoryallocatedpercentage": "6.25%"
}
]
}
(localhost) 🐱 > find hostsformigration virtualmachineid=e3c2c89a-26b3-427e-bc4a-34caeedf466a filter=cpuallocated,memoryallocated,memoryallocatedbytes,memoryallocatedpercentage, …
```
=> Adding memoryallocatedpercentage & memoryallocatedbytes to HostsResponse & HostsForMigrationResponse

plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java
Problem:
When migrateVMwithVolumes API is tried on a VM with two volumes to migrate to a different host and tried to migrate only one volume, Cloudstack migrates both the Volumes but then marks only one of them migrated. This makes volume inaccessible due to inconsitency in path of volume in cloudstack and vsphere
Solution:
Set the target datastore in relocate spec properly for each volume
Fixes #4421 
Test cases covered (all the cases are checked at vSphere level also)
Setup has two clusters C1 and C2
Initial VM state:
VM1 having 3 volumes on a host in Cluster C1
root volume : vVols-C1 primary storage
data disk1 : NFS2-C1 primary storage
data disk2 : vVols-C1 primary storage
1. Migrate VM1 to another host in C1 and migrate only root volume to NFS1-C1 primary storage ---- successful
root …
=> Fix migrateVMwithVolumes API in case of multiple volumes on VMware

server/src/main/java/com/cloud/network/router/VpcVirtualNetworkApplianceManagerImpl.java, systemvm/debian/opt/cloud/bin/cs/CsRedundant.py, systemvm/debian/opt/cloud/bin/setup/bootstrap.sh, test/integration/component/test_multiple_subnets_in_isolated_network.py, test/integration/component/test_multiple_subnets_in_isolated_network_rvr.py, test/integration/component/test_multiple_subnets_in_vpc.py, test/integration/component/test_multiple_subnets_in_vpc_rvr.py
When vpc tiers are added/removed and public ips in different range is added/removed, the nics in VPC VRs are added/removed, it leads to inconsecutive device in VPC VRs.
When we reboot the VR, (or VR is rebooted by some other reasons like HA), the ips in VPC VRs might be assigned to wrong interfaces.
=> vpc: fix ips on wrong interfaces after rebooting vpc vrs

ui/scripts/sharedFunctions.js
Fixes: #4147 
From the front end, add RBD primary storage pool with a secrect with 2 slashes next to each other - no error.
=> Fixed double slash in secret breaking db insert

api/src/main/java/org/apache/cloudstack/api/response/NetworkResponse.java, server/src/main/java/com/cloud/api/ApiResponseHelper.java
If an isolated network is created in VPC then display
its name along with vpc id which is used for UI
Cloudmonkey result
```
(local) mgt01 > list networks filter=name,vpcid,vpcname
{
"count": 3,
"network": [
{
"name": "vpctier",
"vpcid": "d0ad3be2-9ab0-4f96-a863-2776eeb4f267",
"vpcname": "testvpc"
},
{
"name": "tier1",
"vpcid": "e49be49b-bd22-4071-89b0-c13cfb7f29d0",
"vpcname": "vpc1"
},
{
"name": "test"
}
]
}
```
=> Display VPC name to which the network belongs to

api/src/main/java/com/cloud/event/EventTypes.java, server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
This PR adds an event for VM recovery operation
Destroyed a VM without expunging it, and checked the events view - prior to the fix it didn't show any indication that a recovery operation was performed; post fix, we can see an event:
=> Add event for VM recovery operation

api/src/main/java/org/apache/cloudstack/api/response/UsageRecordResponse.java, server/src/main/java/com/cloud/api/ApiDBUtils.java, server/src/main/java/com/cloud/api/ApiResponseHelper.java
Currently vpcid is not displayed in listUsageRecords response.
Add the vpcid so that we can see to which vpc, the network belongs
list usagerecords startdate=2020-01-01 enddate=2020-08-01
```
{
"accountid": "40ec-c28e-11ea-9a43-06103377",
"description": "Bytes received by network null (324e0-ca0f-4762-9850-de5f5c411) using router r-7-VM (ef9-00d7-43e8-8819-9f23226)",
"domainid": "04c6-c28e-11ea-9a43-0613377",
"enddate": "2020-07-27'T'23:59:59+00:00",
"rawusage": "77776",
"startdate": "2020-07-27'T'00:00:00+00:00",
"tags": [],
"type": "DomainRouter",
"usage": "77776 bytes received",
"usageid": "ef96c-00d7-43e8-8819-9f236226",
"usagetype": 5,
"vpcid": "d187a-69a3-4153-88ac-3c7c2de31", >>>>>>>>>>>>>>>>>>>>>
"zoneid": "8ad-7db1-4a1a-9030-db0e62"
},
```
=> Add vpcid in usage network response

systemvm/debian/opt/cloud/bin/cs/CsHelper.py
This PR fixes #4474
before
```
root@r-27-VM:/var/cache/cloud# /opt/cloud/bin/configure.py monitor_service.json
ERROR:root:Command 'ip link show eth0 | grep 'state DOWN'' returned non-zero exit status 1
```
with this change
```
root@r-27-VM:/var/cache/cloud# /opt/cloud/bin/configure.py monitor_service.json
root@r-27-VM:/var/cache/cloud#
```
=> vr: fix python exception when configure VRs

api/src/main/java/com/cloud/agent/api/to/IpAddressTO.java, core/src/main/java/com/cloud/agent/resource/virtualnetwork/facade/IpAssociationConfigItem.java, core/src/main/java/com/cloud/agent/resource/virtualnetwork/model/IpAddress.java, server/src/main/java/com/cloud/network/router/CommandSetupHelper.java, server/src/main/java/com/cloud/network/router/VpcVirtualNetworkApplianceManagerImpl.java, server/src/main/java/com/cloud/network/rules/NicPlugInOutRules.java, server/src/main/java/com/cloud/network/rules/VirtualNetworkApplianceFactory.java, server/src/main/java/org/apache/cloudstack/network/topology/AdvancedNetworkTopology.java, systemvm/debian/opt/cloud/bin/configure.py, systemvm/debian/opt/cloud/bin/cs/CsAddress.py, systemvm/debian/opt/cloud/bin/merge.py, test/integration/component/test_multiple_subnets_in_isolated_network.py, test/integration/component/test_multiple_subnets_in_isolated_network_rvr.py, test/integration/component/test_multiple_subnets_in_vpc.py, test/integration/component/test_multiple_subnets_in_vpc_rvr.py
This PR contains 13 commits below
```
bugfix #1 vpc: fix ips on wrong interfaces after rebooting vpc vrs
bugfix #1 vr: Force a restart of keepalived if conntrackd is not running or configuration has changed
bugfix #2 vpc: Fix remove first public ip will remove all ips on the nic
bugfix #3 apply ip dessociation before unplugging a nic so ip is marked as add:false in ips.json
bugfix #2 vpc vr: fix issue if static nat is disabled but still other IP used by lb/pf
bugfix #4 vpc vr: Do NOT send Nic plug in/out command to Stopped/Stopping VR
Revert "Handle private gateways more reliably"
Revert "Add private gateway IP to router initialization config"
Revert "Fix Policy Based Routing for private gateway static routes (#3604)"
bugfix #6 vpc vr: Add iptables rules for ACL of private gateway
bugfix …
```
=> VPC: fix some issues related to multiple public IP ranges and private gateway

engine/schema/src/main/resources/META-INF/db/schema-41400to41500.sql
This PR updates sort_key to id if sort_key of all zones are 0 (including removed zones, which means sort_key is not set by customers), so zones will be ordered by id in listZones response.
Fixes: #3934
=> sql: Fix Zones are returned in a random order (#3934)

server/src/main/java/com/cloud/server/ManagementServerImpl.java
Backport of https://github.com/apache/cloudstack/pull/4375
```
(localhost) 🐱 > find hostsformigration virtualmachineid=a4dfcf94-76b5-41fc-9ceb-424f0eff5427 
{
"count": 2,
"host": [
{}
]
}
```
```
(localhost) 🐱 > find hostsformigration virtualmachineid=a4dfcf94-76b5-41fc-9ceb-424f0eff5427 
{
"count": 1,
"host": [
{}
]
}
```
=> Fix hosts for migration count

test/integration/component/test_multiple_nic_support.py
This PR fixes a failure with integration test test_multiple_nic_support.py
=> fix failures with test_multiple_nic_support.py

core/src/main/java/com/cloud/agent/resource/virtualnetwork/VirtualRoutingResource.java
This PR fixes the issue that router.aggregation.command.each.timeout on kvm host is reset to 600, when other kvm config is updated, but router.aggregation.command.each.timeout is not.
- [] Trivial
=> kvm: fix router.aggregation.command.each.timeout is reset to 600 when update other kvm configs

api/src/main/java/org/apache/cloudstack/api/response/HostForMigrationResponse.java, api/src/main/java/org/apache/cloudstack/api/response/HostResponse.java, server/src/main/java/com/cloud/api/query/dao/HostJoinDaoImpl.java
Fixes https://github.com/apache/cloudstack/issues/4488
Deprecates `cpuallocated` and adds a new field `cpuallocatedwithoverprovisoning` which considers overprovisioning.
Also adds `cpuallocatedpercentage` and `cpuallocatedvalue` to provide clearer metrics
```
(localhost) 🐱 > list hosts filter=cpuallocatedvalue,cpuallocatedpercentage,cpuallocatedwithoverprovisioning,cpuallocated, type=Routing clusterid=56d84816-7594-49ba-99fd-d5c647fb4890
{
"count": 2,
"host": [
{
"cpuallocated": "1.56%",
"cpuallocatedpercentage": "1.56%",
"cpuallocatedvalue": 500,
"cpuallocatedwithoverprovisioning": "0.78%"
},
{
"cpuallocated": "6.25%",
"cpuallocatedpercentage": "6.25%",
"cpuallocatedvalue": 2000,
"cpuallocatedwithoverprovisioning": "3.12%"
}
]
}
(localhost) 🐱 > find hostsformigration …
```
=> Adding cpuallocated percentage and value to host and hostsformigrationresponse

engine/components-api/src/main/java/com/cloud/storage/StorageManager.java, engine/storage/src/main/java/org/apache/cloudstack/storage/image/BaseImageStoreDriverImpl.java
This PR:
- makes the global setting "secstorage.max.migrate.sessions" non dynamic - as it requires a restart to take effect
- removes an hard-coded value being passed for CopyCommand: This is done so that concurrency can be achieved at the SSVM end. With executeInsequence being set to 'true' while from the MS end it attempts to send multiple copy requests for data migration, at the agent end, it still handles the requests sequentially. Hence, to mitigate this behavior, change has been made to fallback on what is configured on the GS for  executing in sequence.
Verified the behavior of global setting by changing its value and it taking effect post restart of MS
=> Make global setting "secstorage.max.migrate.sessions" non-dynamic

api/src/main/java/org/apache/cloudstack/api/response/PhysicalNetworkResponse.java, server/src/main/java/com/cloud/api/ApiResponseHelper.java
Adding zone name to physicalnetworkresponse which looks better on the UI
```
(localhost) 🐱 > list physicalnetworks 
{
"count": 1,
"physicalnetwork": [
{
"broadcastdomainrange": "ZONE",
"id": "580b516c-f1fa-4fc4-949c-42381a394287",
"isolationmethods": "VLAN",
"name": "Sandbox-pnet",
"state": "Enabled",
"vlan": "100-200",
"zoneid": "ee54cb21-c2e2-4757-bb4a-a2e16a4c2516",
"zonename": "Sandbox-simulator"
}
]
}
```
=> Adding zone name to physicalnetworkresponse

api/src/main/java/com/cloud/vm/NicProfile.java, server/src/main/java/com/cloud/network/router/NicProfileHelperImpl.java, server/src/main/java/com/cloud/network/router/VpcVirtualNetworkApplianceManagerImpl.java, test/integration/component/test_multiple_subnets_in_isolated_network.py, test/integration/component/test_multiple_subnets_in_isolated_network_rvr.py, test/integration/component/test_multiple_subnets_in_vpc.py, test/integration/component/test_multiple_subnets_in_vpc_rvr.py, tools/marvin/marvin/lib/common.py
Some issues with vpc vr have been fixed in #4484
This PR fixes the last two issues we found in our testing.
We run the the integration tests in test/integration/component/test_multiple_subnets*.py many times (>20) , all are SUCCESSFUL.
=> VPC VR: fix Conflicting device id on private gw nic when restart vpc with cleanup

server/src/main/java/com/cloud/deploy/FirstFitPlanner.java
Very complex change "atleast" --> "at least"...
=> Update log output for FirstFitPlanner

services/secondary-storage/server/src/main/java/org/apache/cloudstack/storage/resource/NfsSecondaryStorageResource.java
When there are multiple Management servers, their IPs are listed as comma separated string in /var/cache/cloud/cmdline file against the "host" parameter, and when setting up the SSVM,  SSVM fails to validate the IP of the management servers:
```
WARN  [storage.resource.NfsSecondaryStorageResource] (main:null) destIp is not a valid ip address or cidr destIp=x.x.x.x,y.y.y.y
```
In order to fix this, the IP addresses are split on the delimiter - ',' comma and then the further operations are performed.
Deployed a setup with 2 management servers, and validated the fix. No longer fails validation of IP address
=> Fix failure in validating IP address in case of multiple Management Servers

plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/discoverer/XcpServerDiscoverer.java
This will make unknown errors more readily available in log, debug flag no longer being required in this case.
Fixes #4520
=> change debug to warn for unknown exceptions

plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java, server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
This PR fixes the issue that cpu.corespersocket in vm details is not working on kvm.
=> kvm: FIX cpucorespersocket is not working on KVM

python/lib/cloud_utils.py
This PR fixes the warnings below when install/setup cloudstack-common
```
Unpacking cloudstack-common (4.15.0.0-1607306448~bionic) over (4.15.0.0-SNAPSHOT~bionic) ...
Setting up cloudstack-common (4.15.0.0-1607306448~bionic) ...
/usr/lib/python3/dist-packages/cloud_utils.py:434: SyntaxWarning: "is" with a literal. Did you mean "=="?
if e.errno is 2: raise TaskFailed("augtool has not been properly installed on this system")
/usr/lib/python3/dist-packages/cloud_utils.py:649: SyntaxWarning: "is" with a literal. Did you mean "=="?
if e.errno is 2: raise TaskFailed("cgconfig has not been properly installed on this system")
/usr/lib/python3/dist-packages/cloud_utils.py:675: SyntaxWarning: "is" with a literal. Did you mean "=="?
if e.errno is 2: raise TaskFailed("cgrulesd has not been properly …
```
=> Fix warning when setup cloudstack-common

plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/CitrixResourceBase.java, plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/wrapper/xenbase/CitrixReadyCommandWrapper.java, plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/wrapper/xenbase/CitrixSetupCommandWrapper.java
This failed to destroy systemvms patch VBDs that attaches systemvm.iso
on host setup (ready). This will ensure for upgrades old systemvm.iso
files are not cached/used.
XenServer has an file descriptor/tapdisk iso-caching issue where new systemvm.iso are not recognised and inside the VR/ssvm/cpvm file IO error is seen. This was only reproducible with XS7.1, the fix was to check and eject the systemvm.iso (old/stale/cached), then insert the new systemvm.iso and then eject it :facepalm:
=> xenserver: check and eject patch vbd for systemvms

plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
This PR fixes a regression issue in #4497 
In cloudstack 4.14 or before, the cpu topology is set only when cpucore per socket is set (to 4 or 6).
in other conditions, there is no cpu topology in vm xml definition.
with #4497, vm will have cpu topology in its xml definition, if cpucore per socket is not set.
```
<topology sockets='<vm cpu cores>' cores='1' threads='1'/>
```
Not sure if it causes any issue. I think it would be better not to add this part in vm xml definition if cpucore per socket is not set.
fyi, in https://libvirt.org/formatdomain.html#cpu-model-and-topology, it says
```
topology
The topology element specifies requested topology of virtual CPU provided to the guest. Four attributes, sockets, dies, cores, and threads, accept non-zero positive integer values. They refer to …
```
=> kvm: set cpu topology only if cpucore per socket is set

server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
This PR fixes an NPE that's noticed when we perform the following:
1. Download a volume - such that we have the download_url set in the volume_store_ref table against the respective volume
2. Perform an operation that causes the download_url to be cleared, say, destroy the SSVM
3. Post re-creation of the SSVM , re-initiate download of the same volume, it fails with an NPE
```
2020-12-10 08:56:03,164 ERROR [c.c.a.ApiAsyncJobDispatcher] (API-Job-Executor-2:ctx-ef7f5a39 job-652) (logid:169bd39d) Unexpected exception while executing org.apache.cloudstack.api.command.user.volume.ExtractVolumeCmd
at com.cloud.hypervisor.guru.VMwareGuru.getCommandHostDelegation(VMwareGuru.java:274)
at com.cloud.hypervisor.HypervisorGuruManagerImpl.getGuruProcessedCommandTargetHost(H …
```
=> extract volume: Fix NPE when Volume exists on secondary store but doesn't have a download URL

server/src/main/java/com/cloud/network/NetworkServiceImpl.java
The listPhysicalNetworks API does not consider `keyword`. This PR fixes it
Required since the UI uses keyword for searches
```
(localhost) 🐱 > list physicalnetworks filter=name, keyword=net2
{
"count": 2,
"physicalnetwork": [
{
"name": "Sandbox-pnet"
},
{
"name": "phynet2"
}
]
}
```
```
(localhost) 🐱 > list physicalnetworks filter=name, keyword=net2
{
"count": 1,
"physicalnetwork": [
{
"name": "phynet2"
}
]
}
```
=> listphysicalnetworks: Honouring keyword parameter

plugins/storage/image/default/src/main/java/org/apache/cloudstack/storage/datastore/lifecycle/CloudStackImageStoreLifeCycleImpl.java
This PR fixing a potential sensitive information disclosure  case, see[CLOUDSTACK-10423](https://issues.apache.org/jira/browse/CLOUDSTACK-10423)
=> CLOUDSTACK-10423:Potential sensitive information disclosure

engine/storage/integration-test/src/test/java/org/apache/cloudstack/storage/test/VolumeServiceTest.java, plugins/storage/volume/default/src/main/java/org/apache/cloudstack/storage/datastore/lifecycle/CloudStackPrimaryDataStoreLifeCycleImpl.java, server/src/main/java/com/cloud/storage/StorageManagerImpl.java
This PR addresses an error that appears when you try to add a new host. I don't even understand why there was a cast to String in the first place. I will assume some classes send HypervisorType and some send a string (empty or otherwise). Shouldn't this be addressed to use the same type everywhere? With this fix adding a new xenserver host works fine.
Here is the stack trace:
> WARN  [c.c.s.StorageManagerImpl] (AgentTaskPool-6:ctx-90ed1f24) (logid:77e97d5e) Unable to setup the local storage pool for Host[-4-Routing]
java.lang.ClassCastException: class com.cloud.hypervisor.Hypervisor$HypervisorType cannot be cast to class java.lang.String (com.cloud.hypervisor.Hypervisor$HypervisorType is in unnamed module of loader org.eclipse.jetty.webapp.WebAppClassLoader @3f69b166; java.lang.String is …
=> Fix hypervisor type cast to string

server/src/main/java/com/cloud/template/TemplateManagerImpl.java
This PR enhances https://github.com/apache/cloudstack/pull/3945 by ensuring that all to-be System templates are cross zone
=> template: Ensuring template is cross zone if type changed to system

systemvm/debian/opt/cloud/bin/cs/CsDhcp.py
Fixes https://github.com/apache/cloudstack/issues/3788
When a VR is deleted and a new one brought up it populates the dhcphosts.txt with all hosts in the network, but the dnsmasq.leases file is blank which can cause issues if VMs try to renew their lease.
This PR also adds an entry in the dnsmasq.leases file for each host when the dhcphosts.txt file is populated
An existing lease when a VM tries to acquire a new one doesn't seem to cause any issues
1. Create a network with a couple of VMs on them
2. Restart the network with cleanup
3. Wait for the new router to come up
4. Cat /var/log/dnsmasq.log to verify that no DHCP request has been made
5. Check out /var/lib/misc/dnsmasq.leases
```
root@r-8-VM:~# cat /var/log/dnsmasq.log
Dec 10 13:01:44 dnsmasq[928]: started, version 2.80 cachesize …
```
=> vr: Ensuring dnsmasq.leases file is populated

engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
Fixes a typo in the exception raised when trying to create a network from a disabled offering
```
(qa) 🐱 > create network networkofferingid=a529b060-2407-4085-ab44-fc35f534d6c6 name=nothing displaytext=nothing zoneid=04ccc336-d730-42fe-8ff6-5ae36e141e81 
🙈 Error: (HTTP 431, error code 4350) Can't use specified network offering id as its state is not Enabled
```
=> networkorchestrator: Fix typo in exception message

plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMPhysicalDisk.java, plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/storage/KVMPhysicalDiskTest.java
This fixes issue introduced in c3554ec31dafbdfaa0ed646afb17a6f3378571f5
which enable block of code that will double escape rados host/monitor
port.
Seen in logs:
```
2021-01-04 14:21:35,412 INFO  [kvm.storage.LibvirtStorageAdaptor] (agentRequest-Handler-4:null) (logid:c5187751) Creating volume 125a9ebb-de4c-49cf-b9a7-9249c4af53b9 from template d9eb3660-23e5-4b37-85ec-b6ad4978bf22 in pool 509bd564-b7e3-3d5f-b84b-b799055b11ca (RBD) with size (5.00 GB) 5368709120
```
=> kvm: Fix double-escape issue while creating rbd disk options

vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/HypervisorHostHelper.java
When creating an instance on a guest network where the vlan id has been set to 4095, the instance fails to start.
This PR sets the vlan id and range on the created port group to allow the instance to be created.
Fixes #4358
This has been tested by creating a guest network and setting the vlan id to 4095 and creating an instance using the specific network.
=> Fixed instance creation failure on dvswitch when using vlan id 4095

ui/src/views/AutogenView.vue
This PR attempts to fix https://github.com/apache/cloudstack/issues/4610 - wherein the last tag added to a host/storage pool doesn't get deleted
=> UI Storage Pool Tags: unable to delete last tag

server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
When changing the service offering of a VM the disk_offering_id is not
updated in volumes DB table and VM could not start
Fixes #4125
=> fix on changeServiceForVirtualMachine when updating read/write rate 

engine/schema/src/main/java/com/cloud/vm/dao/VMInstanceDaoImpl.java, server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
The fixes an issue that fails to create a vm if the name has been used by another vm.
(1) create vm-1 on network-1
(2) add vm-1 to network-2
(3) remove vm-1 from network-2
(4) create another vm with same name vm-1 on network-2
expected result: operation succeed
actual result: operation failed.
- [] Major
=> server: fix cannot create vm if another vm with same name has been added and removed on the network

server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
This PR throws an exception when update vm nic ip on L2 network. The error text is not clear now.
without this change
```
root@mgt01:~# cmk update vmnicip nicid=afab73cb-f4f4-490f-a524-365edef432b7
{
"accountid": "a27bffc1-48ee-11eb-8680-069fc4003392",
"cmd": "org.apache.cloudstack.api.command.user.vm.UpdateVmNicIpCmd",
"completed": "2020-12-28T12:55:27+0000",
"created": "2020-12-28T12:55:27+0000",
"jobid": "88af30e0-214b-4379-9c39-49648f998ff6",
"jobresult": {
"errorcode": 530,
"errortext": "Failed to update ip address on vm NIC. Refer to server logs for details."
},
"jobresultcode": 530,
"jobresulttype": "object",
"jobstatus": 2,
"userid": "a27f45f5-48ee-11eb-8680-069fc4003392"
}
🙈 Error: async API failed for job 88af30e0-214b-4379-9c39-49648f998ff6
```
with this …
=> server: throw exception when update vm nic on L2 network

engine/api/src/main/java/org/apache/cloudstack/engine/orchestration/service/NetworkOrchestrationService.java, engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java, server/src/main/java/com/cloud/vm/UserVmManagerImpl.java, server/src/test/java/com/cloud/vpc/MockNetworkManagerImpl.java
This PR fixes an issue when move a vm from an account to another account.
(1) create a vm with multiple shared networks (in  advanced zone, or advanced zone with security groups)
(2) create another account (in same domain who can also access the shared networks)
(3) move vm to new account, with a list of networkid
expected result: the vm has nics on the networks in same order as specified in API request, and nics have the same ips as before
actual result: network order is not same as specified, ips are changed.
=> server: keep networks order and ips while move a vm with multiple networks

server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
We can use cloudmonkey to scale a vm with dynamic offering, to same offering but with different cpunumber or memory.
Enable it on UI to improve user experience.
=> server: add possibility to scale vm to current custom offerings on UI

engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
This PR fixes wrong message when create isolated network without SourceNat
When I created network without sourcenat, I got message below
```
(localcloud) 🐱 > create network name=fully-isolated-noservices displaytext=fully-isolated-noservices networkofferingid=83f13c21-38fd-439f-a0fc-54d6d5233fec zoneid=70e90072-db05-42c0-a639-71d16d905406
🙈 Error: (HTTP 431, error code 4350) StartIp/endIp/gateway/netmask are required when create network of type Shared and network of type Isolated with service SourceNat disabled
```
However, when I passed StartIp/endIp/gateway/netmask, it also failed.
```
(localcloud) 🐱 > create network name=fully-isolated-noservices displaytext=fully-isolated-noservices networkofferingid=83f13c21-38fd-439f-a0fc-54d6d5233fec zoneid=70e90072-db05-42c0-a639-71d16d905406 …
```
=> server: fix wrong error message when create isolated network without SourceNat

plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
Fix #4245 
This PR uses Q35 chipset for UEFI in x86_64.
Currently this mistakenly only enabled for secure boot
Build and run a UEFI VM using OVMF firmware.
Both of Secure Boot and Legacy modes are working now
=> Fix: Use Q35 chipset for UEFI x86_64

server/src/main/java/org/apache/cloudstack/vm/VmImportManagerImpl.java
Improves logic for selecting ROOT disk for VM to be imported when VM has multiple disks.
Based on user input of parameter - datadiskofferinglist, a check will be performed if user correctly provided disk offering mapping for n - 1 disks (one less than the total number of the disks). Remaining one disk will be considered as the ROOT disk.
This will allow correct ROOT disk being selected when first disk in the list of disks of listUnmanagedInstance API or list returned by vSphere SDK is not the ROOT disk.
Fixes #4547 
CMK
Unmanaged VM
```
> list unmanagedinstances clusterid=c4ae9767-cca3-46e3-a801-3218ea8b69d1
{
"count": 1,
"unmanagedinstance": [
{
"clusterid": "c4ae9767-cca3-46e3-a801-3218ea8b69d1",
"cpucorepersocket": 1,
"cpuspeed": 0,
"disk": [
{
"capacity": 2147483648, …
```
=> server: select root disk based on user input during vm import

server/src/main/java/com/cloud/vm/UserVmManagerImpl.java, ui/scripts/instances.js
Fixes behaviour in updateVirtualMachine API by disallowing updating read-only details (details mentioned in global setting `user.vm.readonly.ui.details`) of the VM for accounts other than root-admin using API. Such read-only details will be copied from original values.
Fixes #4514 
```
(localcloud) 🐱 >  list virtualmachine id=527a92ab-f59f-45fc-abc3-abf34ca5cbad
{
"account": "user",
"cpuused": "10%",
"created": "2021-01-28T14:39:08+0530",
"details": {
"newdetail": "somethingnew"
},
"diskioread": 0,
"diskiowrite": 0,
"diskkbsread": 0,
"diskkbswrite": 0,
"displayname": "t1",
"domainid": "b4924318-6146-11eb-9c0f-a0afbd4a2d60",
"guestosid": "b48662d8-6146-11eb-9c0f-a0afbd4a2d60",
"haenable": false, …
```
=> server: prevent update vm read-only details

engine/components-api/src/main/java/com/cloud/capacity/CapacityManager.java, server/src/main/java/com/cloud/alert/AlertManagerImpl.java, server/src/main/java/com/cloud/capacity/CapacityManagerImpl.java
This PR fixes the issue that update capacity for hosts take long time if there are many service offerings.
Steps to reproduce the issue:
(1)Create 10000 service offerings (by db changes or cloudmonkey).
(2) Check the total time of periodical capacity check in cloudstack.
Without this patch, it spend 2.5 seconds (2 hosts)
```
2021-01-15 16:10:12,793 DEBUG [c.c.a.AlertManagerImpl] (CapacityChecker:ctx-5d5f3b3b) (logid:f5eb68ba) Running Capacity Checker ...
2021-01-15 16:10:15,287 DEBUG [c.c.a.AlertManagerImpl] (CapacityChecker:ctx-5d5f3b3b) (logid:f5eb68ba) Done running Capacity Checker ...
```
With this patch ,it spend 1.3 seconds (2 hosts)
```
2021-01-15 16:12:43,604 DEBUG [c.c.a.AlertManagerImpl] (CapacityChecker:ctx-a2a7f3f1) (logid:f7e0a4c5) Running Capacity Checker ...
2021-01-15 …
```
=> server: Fix update capacity for hosts take long time if there are many service offerings

server/src/main/java/com/cloud/server/StatsCollector.java
This PR fixes an issue when collect vm network or disk statistics from hosts.
If cloudstack fails to get vm statistics from a host, the whole process will be terminated, and it will not get vm statistics from remaining hosts.
With this pr, the host with problem will be ignored, and cloudstack will continue on remaining hosts.
=> server: Get vm network/disk statistics and update database per host

test/integration/smoke/test_templates.py
macchinina-vmware.ova has changed at http://dl.openvm.eu/cloudstack/macchinina/x86_64/
sha1, sha256 and m5 checksum have been updated for template file in test_template.py
Fixes failing smoke tests on VMware
```
⇒  wget http://dl.openvm.eu/cloudstack/macchinina/x86_64/macchinina-vmware.ova
--2021-02-05 14:39:52--  http://dl.openvm.eu/cloudstack/macchinina/x86_64/macchinina-vmware.ova
Resolving dl.openvm.eu (dl.openvm.eu)... 217.19.15.108
Connecting to dl.openvm.eu (dl.openvm.eu)|217.19.15.108|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 23308288 (22M) [application/x-tar]
Saving to: ‘macchinina-vmware.ova’
macchinina-vmware.ova                              100%[======================================================================================================= …
```
=> test: fix checksums for test template

test/integration/component/test_mm_domain_limits.py
With #4491, root disks of VMs will be resized while changing service offering.
On simulator this would fail and will need actual hypervisor to test.
Component test test_01_change_service_offering  in test_mm_domain_limits.py has been tagged to require hardware to address this.
This will skip run for this test on travis.
=> test: hardware required for changeserviceoffering 

systemvm/debian/opt/cloud/bin/cs_dhcp.py
This PR fixes an issue that expunging vm will remove dhcp entries of another vm in VR
(1) create two vm wei-001 wei-002, and wei-003 start them.
Assume that wei-001 has the biggest ip (order by char, not number. for example 192.168.0.99 > 192.168.0.100)
(2) check /etc/cloudstack/dhcpentry.json and /etc/dhcphosts.txt in VR
They have entries for all vms
(3) stop wei-002 and wei-003, then restart VR (or restart network with cleanup).
check /etc/cloudstack/dhcpentry.json and /etc/dhcphosts.txt in VR
They have entries for wei-001 only (as wei-002 and wei-003 are stopped)
(4) expunge wei-002. when it is done,
check /etc/cloudstack/dhcpentry.json and /etc/dhcphosts.txt in VR
The last entry ("id": "dhcpentry") is removed.
(5)  expunge wei-003, when it is done.
check …
=> VR: fix expunging vm will remove dhcp entries of another vm in VR

test/integration/smoke/test_service_offerings.py, test/integration/smoke/test_vm_snapshots.py
This PR fixes the test failures noticed on VMware test runs where in change of service offering for a VM fails with the following error:
```
2021-02-04 11:58:05,241 - CRITICAL - EXCEPTION: test_04_change_offering_small: ['Traceback (most recent call last):\n', '  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run\n    testMethod()\n', '  File "/marvin/tests/smoke/test_service_offerings.py", line 511, in test_04_change_offering_small\n    self.apiclient.changeServiceForVirtualMachine(cmd)\n', '  File "/usr/lib/python2.7/site-packages/marvin/cloudstackAPI/cloudstackAPIClient.py", line 1086, in changeServiceForVirtualMachine\n    response = self.connection.marvinRequest(command, response_type=response, method=method)\n', '  File …
```
=> marvin: fix test failures when changing service offering of a VM

server/src/main/java/org/apache/cloudstack/network/ssl/CertServiceImpl.java
Display proper error message while deleting ssl cert which is
associated with a load balancer rule
Also display account name to which lb belongs to
Before fix
After fix
=> Display lb rule name instead of uuid

ui/src/views/offering/AddDiskOffering.vue
Multiple entries were showing in tag selection dropdown of Add disk offering form.
With UI
- Add same tag in different primary stores belonging to different clusters
- Try to create a new disk offering
- Tag selection dropdown will show same tag multiple times (same number as of primary stores to which the tag was added)
=> ui: fix tags selection for add disk offering

server/src/main/java/com/cloud/user/DomainManagerImpl.java, server/src/test/java/com/cloud/user/DomainManagerImplTest.java
Cleanup domain details when domain is deleted
When domain is deleted, all the settings configured under
the domain scope still exists in domain_details table.
All the entries for the domain should be deleted as well
Before the fix
```
mysql> select name,state from domain where id=254;
+--------+--------+
| name   | state  |
+--------+--------+
| domain | Active |
+--------+--------+
mysql> select * from domain_details where domain_id=254;
+----+-----------+---------------------------------+--------------------------+
| id | domain_id | name                            | value                    |
+----+-----------+---------------------------------+--------------------------+
| 11 |       254 | allow.duplicate.networkname     | WRXXfK4XO7HPzDmQ0MGAGw== |
| 12 | …
```
=> Cleanup domain details when domain is deleted

server/src/main/java/com/cloud/agent/manager/allocator/impl/FirstFitAllocator.java
Small typo found while debugging VMs deployment. Changing from `Cusotm[UEFI]` to `Custom[UEFI]`.
=> Fix typo on FirstFitAllocator

api/src/main/java/com/cloud/domain/Domain.java, api/src/main/java/com/cloud/user/Account.java, api/src/main/java/org/apache/cloudstack/api/response/AccountResponse.java, api/src/main/java/org/apache/cloudstack/api/response/DomainResponse.java, engine/schema/src/main/java/com/cloud/domain/DomainVO.java, engine/schema/src/main/java/com/cloud/user/AccountVO.java, engine/schema/src/main/resources/META-INF/db/schema-41510to41600.sql, server/src/main/java/com/cloud/api/ApiResponseHelper.java, server/src/main/java/com/cloud/api/query/dao/AccountJoinDaoImpl.java, server/src/main/java/com/cloud/api/query/dao/DomainJoinDaoImpl.java, server/src/main/java/com/cloud/api/query/vo/AccountJoinVO.java, server/src/main/java/com/cloud/api/query/vo/DomainJoinVO.java
This PR enables the cloudstack to store the creation time of accounts and domains. We already implemented and used this feature in our platforms. We thought it might be useful for the community too. 
The changes in this PR are as small as adding some fields and the setter/getter method. Although the database changes might seem scary, they are minor changes. Except defining the `add_created_column_in_domain_and_account` procedure, I only added the following lines in `account_view` and `domain_view`. Generally speaking, in the mentioned procedure, I added the `created` column to the `account` and `domain` tables, and I ignore its creation if they have already existed.
```
`account`.`created` AS `created`,
...
`domain`.`created` AS `created`,
```
Yes, I have test it in my test environment.
=> add creation date as a value for domains and accounts.

api/src/main/java/com/cloud/network/vpc/VpcProvisioningService.java, api/src/main/java/org/apache/cloudstack/api/command/admin/network/CreateNetworkOfferingCmd.java, api/src/main/java/org/apache/cloudstack/api/command/admin/vpc/CreateVPCOfferingCmd.java, engine/components-api/src/main/java/com/cloud/configuration/ConfigurationManager.java, engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java, plugins/network-elements/juniper-contrail/src/main/java/org/apache/cloudstack/network/contrail/management/ContrailManagerImpl.java, server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java, server/src/main/java/com/cloud/network/vpc/VpcManagerImpl.java, server/src/test/java/com/cloud/vpc/MockConfigurationManagerImpl.java, server/src/test/java/org/apache/cloudstack/networkoffering/CreateNetworkOfferingTest.java
This PR allows one to enable network offering during creation
Create a network offering specifying if it has to be enabled / not and create network using that offering - verify that the offering is available in the list of available offerings
=> Network Offering: Allow enabling network and vpc offering during creation

api/src/main/java/com/cloud/network/Network.java, api/src/main/java/com/cloud/network/NetworkProfile.java, api/src/main/java/org/apache/cloudstack/api/ApiConstants.java, api/src/main/java/org/apache/cloudstack/api/command/admin/network/CreateNetworkCmdByAdmin.java, engine/api/src/main/java/org/apache/cloudstack/engine/orchestration/service/NetworkOrchestrationService.java, engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java, engine/schema/src/main/java/com/cloud/network/dao/NetworkVO.java, plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java, server/src/main/java/com/cloud/network/IpAddressManagerImpl.java, server/src/main/java/com/cloud/network/NetworkServiceImpl.java, server/src/main/java/com/cloud/network/guru/DirectNetworkGuru.java, server/src/main/java/com/cloud/network/router/NetworkHelperImpl.java, server/src/main/java/com/cloud/network/vpc/VpcManagerImpl.java, server/src/main/java/com/cloud/vm/UserVmManagerImpl.java, server/src/test/java/com/cloud/network/CreatePrivateNetworkTest.java, server/src/test/java/com/cloud/vpc/MockNetworkManagerImpl.java, test/integration/smoke/test_network.py, tools/marvin/marvin/lib/base.py, ui/public/locales/en.json, ui/src/views/network/CreateSharedNetworkForm.vue
This PR enables admins to specify IP for a VR in a shared network
=> Specify IP for VR in shared networks

plugins/api/discovery/src/main/java/org/apache/cloudstack/discovery/ApiDiscoveryServiceImpl.java
This PR addresses an issue that crops up during API discovery when we have the same API name pointing to 2 command classes, namely, xxxCmdByAdmin and xxxCmd. 
During api discovery we create a map of the apiNames and their corresponding parameters, however, in cases of api's like _createNetwork_ which point to both CreateNetworkCmd and CreateNetworkCmdByAdmin classes, though in [ManagementServerImpl](https://github.com/apache/cloudstack/blob/master/server/src/main/java/com/cloud/server/ManagementServerImpl.java#L2720) care has been taken to place the xxxCmdByAdmin classes after the regular xxxCmd classes, since we copy this list of command classes into a HashSet, is so happens, that sometimes the xxxCmdByAdmin Classes get discovered before their generic counterpart. Hence, parameters …
=> API discovery: Prevent overwrite of API parameters in cases where API names are same

systemvm/debian/opt/cloud/bin/vr_cfg.sh
A small optimisation as suggested by the user in #4449 . I'm not convinced this is actually reducing the memory usage as they suggest. the code itself seems rathrer risk-free. let's discuss.
Fixes: #4449
=> loop optimisation in bash

server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
Display network name in exception message instead of network object
=> Show network name in exception message

plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java, plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtMigrateCommandWrapper.java, plugins/hypervisors/kvm/src/main/java/org/apache/cloudstack/utils/qemu/QemuImg.java
This PRs fix issue when fails to start or migrate vm after upgrade to ubuntu 20.04, by setting backing file format of qcow2 images.
In previous cloudstack versions, qcow2 image does not have a backing file format.
however, it is required in newer qemu versions, for example qemu 4.2 on ubuntu 20.04.
(1) install cloudstack 4.14 or previous version, and ubuntu 19.04 or 18.04/16.04 LTS.
(2) create vms.
(3) upgrade to 4.15, upgrade os to ubuntu 20.04 , or install a new server with ubuntu 20.04.
(4) migrate vm from old ubuntu version to ubuntu 20.04, failed with exception below
```
2021-02-04 13:43:07,397 DEBUG [resource.wrapper.LibvirtMigrateCommandWrapper] (agentRequest-Handler-1:null) (logid:93da9385) ExecutionException : org.libvirt.LibvirtException: Requested …
```
=> Ubuntu 20.04: set Backing Format of qcow2 images in vm start and migration

INSTALL.md
`wget http://www.us.apache.org/dist/maven/maven-3/3.6.0/binaries/apache-maven-3.6.0-bin.tar.gz` gives `404`. updated new link
`http://www.us.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz`
=> updated maven download link

packaging/build-deb.sh
This PR add an option "-o" to specify the output directory of packages.
Usage:
cd packaging && ./build-deb.sh -T -o ~/packages/$BRANCH_NAME
This PR also changes the format of timestamp when create packages using "./build-deb.sh -T"
old output
```
-rw-r--r-- 1 jenkins jenkins     12509 Nov 12 22:31 cloudstack_4.14.1.0-1605219288~bionic_amd64.buildinfo
-rw-r--r-- 1 jenkins jenkins      3714 Nov 12 22:31 cloudstack_4.14.1.0-1605219288~bionic_amd64.changes
-rw-r--r-- 1 jenkins jenkins  62306764 Nov 12 22:30 cloudstack-agent_4.14.1.0-1605219288~bionic_all.deb
-rw-r--r-- 1 jenkins jenkins  61913896 Nov 12 22:30 cloudstack-common_4.14.1.0-1605219288~bionic_all.deb
-rw-r--r-- 1 jenkins jenkins     52964 Nov 12 22:30 cloudstack-docs_4.14.1.0-1605219288~bionic_all.deb
-rw-r--r-- 1 jenkins jenkins …
```
=> Packaging: new timestamp format and add output dir option

server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
KVM has a limitation to modify instances definitions while they are on running state. Therefore, it is not possible to change volumes backend location easily.
There is a problem in the `migrateVolume` API. This API command ignores that limitation and causes an inconsistence on the database. ACS processes the migrate command, copies the volume to the destination storage, modifies the database and finishes the process with success. However, the running backend is still using the "old volume file".
This PR intends to prevent KVM to perform volumes migrations while KVM instances are in the running state and inform the user of an alternative API command that enables such operation on running instances.
It has been tested locally.
=> Prevent KVM from performing volume migrations of running instances

api/src/main/java/org/apache/cloudstack/api/response/VMSnapshotResponse.java, server/src/main/java/com/cloud/api/ApiResponseHelper.java
Adds new params in listVmSnapshot API - `zonename`, `virtualmachinename`
Fixes #4603 
UI
After change zone name and VM name are shown
CMK:
Before - 
```
> list vmsnapshot vmsnapshotid=db83c1a7-7870-442d-8c27-d9d407a05f11
{
"count": 1,
"vmSnapshot": [
{
"created": "2021-01-20T17:34:35+0530",
"current": true,
"displayname": "vm-snap",
"domainid": "52611b65-5b16-11eb-b67a-645d8651f45a",
"hypervisor": "Simulator",
"id": "db83c1a7-7870-442d-8c27-d9d407a05f11",
"name": "i-2-3-VM_VS_20210120120435",
"state": "Ready",
"tags": [],
"type": "Disk",
"virtualmachineid": "3a07d2d4-18ad-4ef4-ac97-7937ba629069",
"zoneid": "5918c672-47aa-4425-9ff9-d71d79d2b304",
}
]
}
```
After-
```
> list vmsnapshot vmsnapshotid=db83c1a7-7870-442d-8c27-d9d407a05f11
{
"count": 1, …
```
=> api: add zone, vm name params in listVmSnapshot response

test/integration/smoke/test_network.py
This PR attempts to fix travis failures observed post merge of #4503. Checks have been added to skip specific tests for Simulator based envs. 
Exceptions noticed in travis:
```
2021-02-18 23:08:13,330 - CRITICAL - EXCEPTION: test_01_deployVMInSharedNetwork: ['Traceback (most recent call last):\n', '  File "/usr/lib/python2.7/unittest/case.py", line 329, in run\n    testMethod()\n', '  File "/home/travis/build/apache/cloudstack/test/integration/smoke/test_network.py", line 1988, in test_01_deployVMInSharedNetwork\n    host = self.get_router_host(router)\n', '  File "/home/travis/build/apache/cloudstack/test/integration/smoke/test_network.py", line 1944, in get_router_host\n    host.user, host.password = get_host_credentials(self.config, host.ipaddress)\n', '  File …
```
=> marvin: Bypass tests on Simulator

ui/src/views/offering/AddComputeOffering.vue
Fixes #4682
Adds systemvmtype param in API call
=> ui: fix systevmtype for create service offering form

scripts/util/create-kubernetes-binaries-iso.sh
CNI plugin release naming has changed, https://github.com/containernetworking/plugins/releases
Releases are named for host OS from 0.8.0 onwards.
This change adds check for 404 response code and attempts retry
Creating ISO for k8s 1.16.3 and 1.19.7
For k8s 1.16.3 with CNI plugin 0.7.1
```
./create-kubernetes-binaries-iso.sh ~/Desktop 1.16.3 0.7.1 1.16.0 "https://cloud.weave.works/k8s/net?k8s-version=1.16.3" "https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-rc3/aio/deploy/recommended.yaml" setup-v1.16.3 
+ set -e
+ '[' 7 -lt 6 ']'
+ RELEASE=v1.16.3
+ output_dir=/home/shwstppr/Desktop
+ start_dir=/home/shwstppr/lab/shapeblue/cloudstack/scripts/util
+ iso_dir=/tmp/iso
+ working_dir=/tmp/iso/
+ mkdir -p /tmp/iso/
+ build_name=setup-v1.16.3.iso
+ '[' -z setup-v1.16.3.iso ']'
+ …
```
=> cks: fix CNI release url returning 404

ui/tests/unit/views/AutogenView.spec.js
Fixes https://github.com/apache/cloudstack/issues/4711
For 4.15 branch
UI test
After fix:
=> UI test: Fix UI test failures in 4.15

ui/tests/unit/views/AutogenView.spec.js, ui/tests/unit/views/compute/MigrateWizard.spec.js
Fixes #4711
For Master branch
UI test
After fixes:
=> UI Test: Fix UI test failures in master

engine/schema/src/main/java/com/cloud/upgrade/DatabaseUpgradeChecker.java, engine/schema/src/main/java/com/cloud/upgrade/dao/DbUpgradeSystemVmTemplate.java, engine/schema/src/main/java/com/cloud/upgrade/dao/Upgrade41400to41500.java
Currently in upgrade cloudstack checks the systemvm template after db changes.
if user do not install systemvm template and uprgade cloudstack (for example install packages with newer version), upgrade will fail. in this case it will be very complicated to rollback the db if there is no db backup.
This pr checks the latest (only the last) systemvm template in upgrade path, and exits if required systemvm template is not registered.
=> Upgrade: check systemvm template before db changes

server/src/main/java/com/cloud/api/query/dao/TemplateJoinDaoImpl.java, server/src/main/java/com/cloud/template/HypervisorTemplateAdapter.java
This PR fixes the issue reported in :https://github.com/apache/cloudstack/issues/4613
This issue seems to have cropped up due to code revert that happened by commit - d864e9dc39b69e590e3df898a03a874a8173fcc6
1. Migrate data from one image store to another
2. Attempt deleting the store from where all data objects we migrated
=> Secondary storage: Allow store deletion after successful data migration

server/src/main/java/com/cloud/api/query/dao/TemplateJoinDaoImpl.java
This PR aims at restoring the previous level of leniency in listing templates on stores that have been marked as deleted / removed by updating the DB.
While Cloudstack doesn't allow deleting stores that have resources on them, it may so happen that users may mimic a deletion of a store by merely updating the DB. Under such a case, listing of templates is hampered due to an NPE that is caused.  (as seen in https://github.com/apache/cloudstack/issues/4606) 
Mark an image store having templates (public/private) on them as deleted by updating the DB i.e., setting the removed field to some timestamp
Try listing the templates, should list all templates as usual
=> API: Increase leniency to list templates on secondary stores that have been marked deleted by updating the db

framework/quota/src/main/java/org/apache/cloudstack/quota/QuotaAlertManagerImpl.java, framework/quota/src/main/java/org/apache/cloudstack/quota/constant/QuotaConfig.java, plugins/database/quota/src/main/java/org/apache/cloudstack/quota/QuotaServiceImpl.java
Some servers (like [microsoft](https://docs.microsoft.com/en-us/microsoft-365/compliance/prepare-tls-1.2-in-office-365?view=o365-worldwide)) are deprecating TLSv1 and TLSv1.1. 
On Quota's mailing settings, ACS uses the protocol `TLSv1`; therefore, operators do not have options to choose which version they want to use. 
This PR intends to externalize the protocol setting on Quota's mailing.
1. I had Enabled Quota's plugin on the management server and configured it to use Gmail's SMTP server.
```
server address: smtp.gmail.com
username: gmail address
password: gmail password
port (TLS): 587
```
2. On `Quota - All Accounts`, I added 10 credits to my user and set 20 as min balance.
3. I had added an gmail address to Accounts > \<account\> > Users - …
=> Externalize TLS version on Quota's mailing

ui/src/views/infra/ClusterAdd.vue
When adding a cluster from an existing host-datacenter UI should list and autofill host, DC name while making addCluster API call.
Before fix:
After the fix, vCenter cluster successfully added
UI
1. Deploy an env with VMware DC added in CloudStack zone with adv networking
2. Create a new cluster in vCenter
3. Try to add that cluster in CloudStack UI. This will return error as shown in the above screenshot. DC name and host are set to null without querying CloudStack
=> ui: fix add Vmware cluster

engine/schema/src/main/java/com/cloud/storage/dao/VMTemplateDaoImpl.java
If the template from which VR is created got deleted, the state
is set to inactive and removed to null.
Since the template is already deleted, the VR can't be created
using this template again.
If someone restarts network with cleanup then it will try to
deploy the vr from the old non existing template again.
So search only for active template which are not yet deleted.
1. Create a network and this will in turn create VR's
2. Note down the template from which the VR was created
3. Delete that template
4. Now restart the network with cleanup option
5. The new router deployment should be successful using another active template from the platform
=> Look for active templates for VR deployment

engine/api/src/main/java/org/apache/cloudstack/engine/subsystem/api/storage/StoragePoolAllocator.java, engine/schema/src/main/java/org/apache/cloudstack/storage/datastore/db/PrimaryDataStoreDao.java, engine/schema/src/main/java/org/apache/cloudstack/storage/datastore/db/PrimaryDataStoreDaoImpl.java, engine/storage/src/main/java/org/apache/cloudstack/storage/allocator/AbstractStoragePoolAllocator.java, engine/storage/src/main/java/org/apache/cloudstack/storage/allocator/ClusterScopeStoragePoolAllocator.java, engine/storage/src/main/java/org/apache/cloudstack/storage/allocator/GarbageCollectingStoragePoolAllocator.java, engine/storage/src/main/java/org/apache/cloudstack/storage/allocator/LocalStoragePoolAllocator.java, engine/storage/src/main/java/org/apache/cloudstack/storage/allocator/UseLocalForRootAllocator.java, engine/storage/src/main/java/org/apache/cloudstack/storage/allocator/ZoneWideStoragePoolAllocator.java, plugins/storage-allocators/random/src/main/java/org/apache/cloudstack/storage/allocator/RandomStoragePoolAllocator.java, server/src/main/java/com/cloud/server/ManagementServerImpl.java
While finding pools for volume migration list following compatible storages:
- all zone-wide storages of the same hypervisor.
- when the volume is attached to a VM, then all storages from the same cluster as that of VM.
- for detached volume, all storages that belong to clusters of the same hypervisor. 
Fixes #4692 
Fixes #4400 
Using cmk and UI.
Tested with a multi-cluster VMware env.
Storage Pools,
```
(localcloud) SBCM5> > list storagepools filter=id,name,scope,clustername,tags,hypervisor
{
"count": 8,
"storagepool": [
{
"hypervisor": "VMware",
"id": "53a4a81b-0271-3989-94d1-a00708fd9c32",
"name": "ps8",
"scope": "ZONE",
"tags": "tag1"
},
{
"hypervisor": "VMware",
"id": "17899b5b-1838-3e8d-b0fe-76cab34093b1",
"name": "ps7",
"scope": "ZONE"
},
{
"clustername": …
```
=> server: fix finding pools for volume migration

plugins/ca/root-ca/src/test/java/org/apache/cloudstack/ca/provider/RootCAProviderTest.java
These tests were changing the value of an attribute in a protected static object at runtime instead of mocking the object. We discovered this problem when working with the docker build containers in https://github.com/khos2ow/cloudstack-deb-builder/pull/20. They were breaking the tests when building in the docker container. 
This PR intends to improve these tests to use actual mocks, instead of change the value at runtime with reflection, keeping the same behavior.
Obs: The [DEB Builder](https://github.com/khos2ow/cloudstack-deb-builder) uses version 4.13 to test the container's building for Java8 containers, and 4.15 for Java11 containers.
The tests were been ran and the packages were built locally.
=> Adjust tests to fix a problem with the container builders (https://github.com/khos2ow/cloudstack-deb-builder)

plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/utils/KubernetesClusterUtil.java
Frobable fix for #4146 , #4637
=> cks: use HttpsURLConnection for checking api server

engine/storage/volume/src/main/java/org/apache/cloudstack/storage/volume/VolumeServiceImpl.java
Duplicated volumes after failed migration in Allocated state
Fix: Clean up the duplicate volume when the destination managed volume creation failed on migrate volume operation
Manually tested the fix with failed migration, confirmed that the duplicate volume (in Allocated state) is cleaned up.
=> Clean up the duplicate volume (after failed migration) when the destination managed volume creation failed

scripts/vm/network/security_group.py
When running [get_bridge_physdev(brname)](https://github.com/apache/cloudstack/blob/b2ffa3efa58a1569dbaa8a34f723756926e22820/scripts/vm/network/security_group.py#L152) from `security_group.py` it is returned the bridge device as `brname:` instead of the expected `brname`.
We experienced this issue on CloudStack 4.13.1.0 with _Security Groups_ enabled for _Advanced Networking_. Additionally, KVM nodes are running on Ubuntu 18.04.
PR #4303 (merged in 4.15) added support for Ubuntu 20.04 which turned out to fix `get_bridge_physdev(brname)`; however, we faced the very same issue with the previous CloudStack and Ubuntu versions.
Even though we might not get a `4.13.2`, and CloudStack `4.14.1.0` has just been released, this PR proposes merging the fix into branch `4.13` and then get it …
=> get_bridge_physdev returns "device:" instead of "device"

plugins/integrations/kubernetes-service/src/main/resources/conf/k8s-master.yml
Fixes #4742 
kubeadm init is called with `--token-ttl 0`
This will allow the token to remain valid forever.
Checked token details after k8s cluster deployment;
```
Container Linux by CoreOS stable (2303.3.0)
Update Strategy: No Reboots
core@t2-master ~ $ sudo kubadm token list
sudo: kubadm: command not found
core@t2-master ~ $ sudo kubeadm token list
TOKEN                     TTL         EXPIRES                USAGES                   DESCRIPTION                                                EXTRA GROUPS
00dec2.178dc8478dbecfc5   <forever>   <never>                authentication,signing   The default bootstrap token generated by 'kubeadm init'.   system:bootstrappers:kubeadm:default-node-token
ul9g7i.jl1ehlghm8apx634   1h          2021-03-03T12:03:15Z   <none>                   Proxy for …
```
=> cks: fix token TTL, set it to never expire

tools/build/build_asf.sh
This removes MD5 checksum created as part of release work due to ASF
infra policy to deprecate MD5:
https://infra.apache.org/release-distribution#sigs-and-sums
=> build: deprecate and remove md5 from releases

services/console-proxy/server/src/main/java/com/cloud/consoleproxy/ConsoleProxy.java, services/console-proxy/server/src/main/java/com/cloud/consoleproxy/ConsoleProxyNoVNCHandler.java, services/console-proxy/server/src/main/java/com/cloud/consoleproxy/ConsoleProxyNoVncClient.java
Fixes #4550 
This PR fixes an issue with novnc.
1. open a vm console
2. open the console in another session (other server, or different browser, or incognito window)
console will be stuck at Connecting
3. reload the page, vm console works. The console in step (1) is kicked out.
with this PR, the console in new session will work, the old session will be disconnected.
with this pr, in new windows
=> novnc: Accept new novnc client and disconnect old session

server/src/main/java/com/cloud/template/TemplateAdapterBase.java, services/secondary-storage/server/src/main/java/org/apache/cloudstack/storage/resource/NfsSecondaryStorageResource.java
This PR fixes the issue that failed to remove template/iso if upload from local fails
When upload template/iso/volume from local fails, the install_path will not be a full path of file so removing it will fail.
```
mysql> select install_path from template_store_ref;
+--------------------------------------------------------------------+
| install_path                                                       |
+--------------------------------------------------------------------+
| template/tmpl/1/3/805f4763-248e-40ec-b79a-b868cc480d0a.qcow2       |
| template/tmpl/1/4/c7e32c9e-5e72-3726-85cf-aa5ccd84118d.qcow2       |
| template/tmpl/2/201/bc4f4f08-138a-31b8-af1a-d4450eff7982.qcow2     |
| template/tmpl/2/202                                                |
| …
```
=> server: fix failed to remove template/iso if upload from local fails

api/src/main/java/com/cloud/network/VirtualNetworkApplianceService.java, api/src/main/java/org/apache/cloudstack/api/command/admin/router/RebootRouterCmd.java, api/src/main/java/org/apache/cloudstack/api/command/admin/systemvm/RebootSystemVmCmd.java, api/src/main/java/org/apache/cloudstack/api/command/user/vm/RebootVMCmd.java, engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java, plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java, server/src/main/java/com/cloud/network/router/VirtualNetworkApplianceManagerImpl.java, server/src/main/java/com/cloud/server/ManagementServerImpl.java, server/src/main/java/com/cloud/vm/UserVmManagerImpl.java, server/src/test/java/com/cloud/vpc/MockVpcVirtualNetworkApplianceManager.java, test/integration/smoke/test_routers.py, test/integration/smoke/test_ssvm.py, test/integration/smoke/test_vm_life_cycle.py, tools/marvin/marvin/lib/base.py, ui/src/config/section/compute.js, ui/src/config/section/infra/routers.js, ui/src/config/section/infra/systemVms.js
Use ACPI event to reboot VM on KVM, and Use 'forced' reboot option to stop and start the VM(s).
This PR addresses the following:
- Replaces the legacy stop/start logic to reboot VM on KVM, with libvirt's native reboot operation that will use ACPI event based rebooting.
- Introduces new 'forced' parameter in the rebootVirtualMachine API, which facilitates to stop and start the user VM.
- Introduces new 'forced' parameter in rebootSystemVm API, to stop and start the system VM.
- Introduces new 'forced' parameter in rebootRouter API, to force stop and start the Router.
Reboot Dialog with Force option in the UI:
- Deployed a VM (on KVM / VMware 6.7.0 / XenServer 7.0), and Performed normal Reboot.
- Deployed a VM (on KVM / VMware 6.7.0 / XenServer 7.0), and Performed force Reboot.
- Marvin …
=> Use ACPI event to reboot VM on KVM, and Use 'forced' reboot option to stop and start the VM(s) 

agent/src/main/java/com/cloud/agent/resource/consoleproxy/ConsoleProxyResource.java, core/src/main/java/com/cloud/agent/api/proxy/StartConsoleProxyAgentHttpHandlerCommand.java, server/src/main/java/com/cloud/api/ApiServlet.java, server/src/main/java/com/cloud/consoleproxy/AgentHookBase.java, server/src/main/java/com/cloud/consoleproxy/ConsoleProxyManager.java, server/src/main/java/com/cloud/consoleproxy/ConsoleProxyManagerImpl.java, server/src/main/java/com/cloud/servlet/ConsoleProxyClientParam.java, server/src/main/java/com/cloud/servlet/ConsoleProxyServlet.java, services/console-proxy/server/src/main/java/com/cloud/consoleproxy/ConsoleProxy.java, services/console-proxy/server/src/main/java/com/cloud/consoleproxy/ConsoleProxyClientParam.java, services/console-proxy/server/src/main/java/com/cloud/consoleproxy/ConsoleProxyHttpHandlerHelper.java, services/console-proxy/server/src/main/java/com/cloud/consoleproxy/ConsoleProxyNoVNCHandler.java
This PR adds a global setting "novnc.console.sourceip.check.enabled", it is false by default. If it is true, The source IP to access novnc console must be same as the IP in request to management server for console URL.
Open a vm console, 
view page source and get exact URL in ifram
access the URL from other server/ip
Current behavior:
succeeds.
New behavior
if novnc.console.sourceip.check.enabled is "false", succeeds.
if novnc.console.sourceip.check.enabled is "true", fails.
=> novnc: Add source IP check

api/src/main/java/org/apache/cloudstack/api/response/ProjectResponse.java
The `account` is no longer set in the listProjects API response that is
still mentioned in the API docs. API consumers should now use the
`owner` key from the listProjects API response which returns a list of
owners (accounts and users).
To generate the API docs with 4.15.1: http://cloudstack.apache.org/api/apidocs-4.15/
=> api: remove account from listProjects API response

engine/storage/datamotion/src/main/java/org/apache/cloudstack/storage/motion/KvmNonManagedStorageDataMotionStrategy.java, engine/storage/datamotion/src/main/java/org/apache/cloudstack/storage/motion/StorageSystemDataMotionStrategy.java, engine/storage/datamotion/src/test/java/org/apache/cloudstack/storage/motion/StorageSystemDataMotionStrategyTest.java
In the execution flow of the API `migrateVirtualMachineWithVolume`, there is a step that copies the volume's template to the target storage, if it is needed.   
In some cases when the volume is a `data` type, it (the volume) does not have a template; therefore, it is going to generate an NPE when it tries to get the template's ID (Long to long auto conversion).
This PR intends to validate if the volume being copied has a template, before trying to copy the template. 
It has been tested locally in a test lab.
1. I had created a VM and attached 2 volumes to it.
2. I had migrated the VM to another `host` and the volumes to different `storage` to see if it migrates accordingly.
=> Fix npe when migrating vm with volume

ui/src/components/widgets/Breadcrumb.vue
This PR aligns the breadcrumb with the info card display name
=> ui: Fix breadcrumb discrepancy

test/integration/smoke/test_vm_life_cycle.py
Fixes the wrong parameter while using listVolumes API after detached volume migration.
Current code uses an invalid `volume` parameter which leads to test failure in cases when there are other volumes in different pools.
=> test: fix listVolumes call for detach volume migration check

ui/src/views/compute/MigrateWizard.vue
This PR  adds the memory allocated percentage to the migrate wizard form, since just seeing the used memory may not be enough
=> ui: Show memory allocated percentage when migrating vm

server/src/main/java/com/cloud/api/ApiResponseHelper.java
Fixes #4770
Uses network details from nic's network instead of details from virtual machine.
With a VMware env, zone with advanced networking.
Networks:
```
(localcloud) SBCM5> > list networks id=1e9022b5-173e-43ee-81ef-6c8ad6b7322a filter=id,name,traffictype,type
{
"count": 1,
"network": [
{
"id": "1e9022b5-173e-43ee-81ef-6c8ad6b7322a",
"name": "testl2",
"traffictype": "Guest",
"type": "L2"
}
]
}
```
Before changes - both nics show same network anem, traffic type and guest type:
```
(localcloud) SBCM5> > list nics virtualmachineid=cd54a0b9-36ab-41c0-a1e5-650a5ec9ccd1 
{
"count": 2,
"nic": [
{
"broadcasturi": "vlan://1343",
"deviceid": "0",
"extradhcpoption": [],
"gateway": "10.1.1.1",
"id": "0042bd3f-8b1d-48cf-8265-b7dadb8e8fb8",
"ipaddress": "10.1.1.43",
"isdefault": true, …
```
=> server: use network details from nic network

api/src/main/java/org/apache/cloudstack/api/ApiConstants.java, api/src/main/java/org/apache/cloudstack/api/response/UsageRecordResponse.java, server/src/main/java/com/cloud/api/ApiResponseHelper.java
This fixes the ostype ID returned in listUsageRecords API response to
be uuid instead of internal DB ID and also returns the os category ID
(uuid) and name.
Original change was recently introduced in 4.15 with https://github.com/apache/cloudstack/pull/4266
=> usage: return guest OS type UUID instead of internal DB ID

server/src/main/java/com/cloud/template/HypervisorTemplateAdapter.java
While deleting a template for a specific zone, the check should be done only for secondary storages and not for storages with the available capacity threshold.
=> server: delete template on storage over capacity threshold

ui/src/components/view/DetailSettings.vue
PR #4629 made changes in updateVirtualMachine behaviour wrt readonly details.
This change updates UI wrt new behaviour.
- Deployed a VM as user.
- As admin added a new detail to the VM. Made the detail read-only by putting it in global config - `user.vm.readonly.ui.details`
- As user, tried add, edit and delete details operation on the VM.
=> ui: fix update vm details wrt backend changes

engine/schema/src/main/resources/META-INF/db/schema-41500to41510.sql
Correct copy&paste issue from lines
https://github.com/apache/cloudstack/blob/c82688a3559929fafa388192b949f4136b5d3d27/engine/schema/src/main/resources/META-INF/db/schema-41400to41500.sql#L782
=> db-schema update 4.15.0 to 4.15.1: correct some guest-os namings

ui/src/views/project/iam/ProjectRolePermissionTab.vue
This PR changes the default project role permission type to 'deny' as project role permissions are basically restrictive in nature, i.e., they are used to deny users/accounts in a project from performing certain actions that they would be allowed at the account-level, hence making sense to have the default permission to be Deny.
As shown in the screenshot above, the default permission is Deny while adding project role permissions
=> ui - Project Role Permission: Change default permission type to 'Deny'

engine/schema/src/main/java/com/cloud/projects/dao/ProjectAccountDaoImpl.java
This PR ensures to list the projects owners in the order in which they were added.
Prior to fix, listing projects didn't necessarily return a list of project owners in the order in which they were added. 
```
Added an account (ACSUser)
(admin) SBCM5> > list projects listall=true filter=owner,id,name,
{
"count": 1,
"project": [
{
"id": "a81b8ec4-fa61-4e17-9383-1083276c18df",
"name": "p1",
"owner": [
{
"account": "ACSUser"
}
]
}
]
}
Added Admin account
(admin) SBCM5> > list projects listall=true filter=owner,id,name,
{
"count": 1,
"project": [
{
"id": "a81b8ec4-fa61-4e17-9383-1083276c18df",
"name": "p1",
"owner": [
{
"account": "admin"
},
{
"account": "ACSUser"
}
]
}
]
}
Added user (u1)
(admin) SBCM5> > list projects listall=true filter=owner,id,name,
{
"count": 1,
"project": [
{
"id": …
```
=> listprojects: Maintain order of project owners added to a project

server/src/main/java/com/cloud/servlet/ConsoleProxyServlet.java, systemvm/agent/noVNC/vnc.html
This PR fixes the blank screen issue of novnc console if language is not English in some browsers.
(1) install firefox, and switch to another language other than English, for example Germany, Russian.
refer to https://support.mozilla.org/en-US/kb/use-firefox-another-language
(2) open vm console
Expected result: console works
Actual result: the first time it works, then blank screen in retries (also with other vms).
=> novnc: Fix vm console is not working on firefox if language is not English

server/src/main/java/com/cloud/capacity/CapacityManagerImpl.java
If `ramOvercommitRatio` field is missing in user_vm_details table
is missing then agent throws NPE after restarting
It is because in user_vm_details, there are 'cpuOvercommitRatio' for all
vms, but for vms the field 'ramOvercommitRatio' is missing in the table.
=> Fix NPE while cloudstack agent failed to connect to mgt server

systemvm/agent/noVNC/app/styles/base.css
Hides the fullscreen button in novnc until connected to the VM
This prevents the `UI.rfb is not initialized` error
=> novnc: Hide fullscreen button when not connected

ui/src/config/section/compute.js, ui/src/views/compute/StartVirtualMachine.vue
Adds the VM name along with the newly reset password. Useful when resetting the password of multiple VMs
=> ui: Show vm name along with password

ui/src/components/view/InfoCard.vue
This PR fixes the route to Iso tab from the respective VM's detail View (Info card) if the VM is deployed from an ISO. 
Deploy VM from an ISO and traverse to the ISO tab from the detail view
Before Fix:
Post Fix:
Successfully able to route to iso tab
=> ui: Fix route to ISO From VM's Info Card / Detail View

api/src/main/java/org/apache/cloudstack/api/command/user/snapshot/CreateSnapshotCmd.java, plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java, plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtCreatePrivateTemplateFromVolumeCommandWrapper.java, plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/IscsiAdmStorageAdaptor.java, plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java, plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/LibvirtStorageAdaptor.java, plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/ScaleIOStorageAdaptor.java, plugins/hypervisors/kvm/src/main/java/org/apache/cloudstack/utils/qemu/QemuImg.java, plugins/hypervisors/kvm/src/test/java/org/apache/cloudstack/utils/qemu/QemuImgTest.java, scripts/storage/qcow2/resizevolume.sh
`Qemu 2.10 added the requirement of a --force-share flag to 'qemu-img info' command when reading information about a disk that is in use by a guest`. After this Qemu release, to obtain the attached disk metadata, we need to use a flag to force information reading.   
This PR intends to add the required flag to the `qemu-img info` command if the qemu version is 2.10+. We can get the Qemu version in the LibvirtConnection.
Fixes: #4024
It has been tested locally.
=> Qemu 2.10 requires `-U` flag to read volume metadata

utils/src/test/java/com/cloud/utils/backoff/impl/ConstantTimeBackoffTest.java
This PR increases the timeout after interrupting a thread in the ConstantTimeBackoffTest.waitBeforeRetryWithInterrupt test, preventing intermittent failures especially in build envs with limited resources 
Builds fail for some other reason
=> tests: Extend wait time after interrupt

ui/src/views/infra/zone/ZoneWizardAddResources.vue, ui/src/views/infra/zone/ZoneWizardLaunchZone.vue
This PR fixes the issue that occurs while adding a primary store using PreSetup protocol during zone deployment for XenServer, where in, it fails to find the primary store path, as, for XenServer we provide the SR Label
Prior fix:
Post Fix:
Successfully deploys the zone
=> ui: Fix add primary store during Zone Deployment for PreSetup protocol

ui/src/views/infra/ClusterAdd.vue
Do not add null values to the API request
Before
After
=> ui: fix add cluster form for vmware

ui/src/components/view/SearchView.vue, ui/src/views/AutogenView.vue
After performing the search filter, the fields will be blank when converting the page
Back to list page:
List view page -> search filter -> go-to resource view -> back to list page
=> UI: Fill out the search filter form field after performing a filter

ui/src/components/view/InfoCard.vue
This PR fixes the UI info card by considering the overprovisioning factor while displaying the disk allocated progress bar
=> ui: Consider overprovisioning when displaying allocated progress

server/src/main/java/com/cloud/network/router/CommandSetupHelper.java, systemvm/debian/opt/cloud/bin/cs/CsGuestNetwork.py
This PR fixes the issue that dnsmasq cannot be started in VPC VR is use.external.dns is true
(1) change global setting use.external.dns to true
(2) create vpc
(3) create vpc tier and a vm
(4) restart VPC VR, or restart VPC with cleanup
(5) check VPC VR, dnasmasq is not started with error
```
Mar 12 14:15:07 r-999-VM dnsmasq[11176]: dnsmasq: bad IP address at line 5 of /etc/dnsmasq.d/cloud.conf
Mar 12 14:15:07 r-999-VM dnsmasq[11176]: bad IP address at line 5 of /etc/dnsmasq.d/cloud.conf
Mar 12 14:15:07 r-999-VM dnsmasq[11176]: FAILED to start up
```
dnsmasq config
```
root@r-999-VM:~# cat /etc/dnsmasq.d/cloud.conf
dhcp-hostsfile=/etc/dhcphosts.txt
listen-address=127.0.0.1,192.168.20.1
dhcp-range=set:interface-eth2-0,192.168.20.1,static …
```
=> vpc: dnsmasq is not started if use.external.dns is true

utils/src/main/java/org/apache/cloudstack/utils/redfish/RedfishClient.java, utils/src/test/java/org/apache/cloudstack/utils/redfish/RedfishClientTest.java
This PR adds a missing break at the HTTP request re-try loop.
It is a minor bug, but it can result in double re-try requests where one should be enough. Also, talking about corner cases, there is a small possibility of the first re-try request be successful, and the second fails, which could result in _false error_.
This PR added the break and also Test cases that cover such scenarios to ensure that now we have it all covered.
=> Add 'break' at RedifshClient request re-try loop

plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
We do not need to set backing file format of  DATADISK and ROOT disk which does not have a backing file.
=> kvm: Do not set backing file format of DATADISK in vm start/migration

engine/storage/src/main/java/org/apache/cloudstack/storage/volume/datastore/PrimaryDataStoreHelper.java, server/src/main/java/com/cloud/storage/StorageManagerImpl.java
This PR fixes the issue that new storage pool can not be used in the first few minute after adding to cloudstack.
(1) change global setting vm.allocation.algorithm to 'firstfitleastconsumed' (this allocator orders host/storage by capacity, maybe other algorithim has same issue).
(2) create a zone and enable it
(3) systemvm cannot be created, until Capacity Checker runs (it runs every 5 minutes).
=> server: create DB entry for storage pool capacity when create storage pool

api/src/main/java/org/apache/cloudstack/api/ApiServerService.java, api/src/main/java/org/apache/cloudstack/api/command/admin/acl/ImportRoleCmd.java, server/src/main/java/com/cloud/api/ApiServer.java
This PR removes the rule(s) validation with api names while importing a role. This will be in sync with the current create role permission behavior.
Manually tests:
- Import role with some random rule string
=> Remove the rule(s) validation with api names while importing a role

utils/src/main/java/org/apache/cloudstack/utils/redfish/RedfishClient.java, utils/src/test/java/org/apache/cloudstack/utils/redfish/RedfishClientTest.java
This PR adds a missing break at the HTTP request re-try loop.
It is a minor bug, but it can result in double re-try requests where one should be enough. Also, talking about corner cases, there is a small possibility of the first re-try request be successful, and the second fails, which could result in _false error_.
This PR added the break and also Test cases that cover such scenarios to ensure that now we have it all covered.
This PR has fixed the log issue caused by the misplaced `String.format` attributes at https://github.com/apache/cloudstack/pull/4846/commits/cd5fe4bf8df66893740fe3e0e507aa290d4e3b0b; merged in the context of #4846 and correctly reverted at #4861.
To make sure all is good I re-build with the fix, and also executed all unit tests.
```
$ mvn clean install
.....
[INFO] …
```
=>  Add 'break' at RedifshClient request re-try loop (fixed issue from 4846)

api/src/main/java/org/apache/cloudstack/api/response/UserVmResponse.java, server/src/main/java/com/cloud/api/query/dao/UserVmJoinDaoImpl.java
Fixes https://github.com/apache/cloudstack/issues/4566
Sets `memoryintfreekbs` to zero if it is greater than `memorykbs`. Caused by KVM returning the RSS memory of the process running the VM rather than the free memory inside the VM
```
(localcloud) SBCM5> > list virtualmachines filter=memoryintfreekbs,memorykbs,
{
"count": 2,
{
"memoryintfreekbs": 2138672,
"memorykbs": 2097152
},
{
"memoryintfreekbs": 2143292,
"memorykbs": 2097152
}
]
}
```
```
(localcloud) SBCM5> > list virtualmachines filter=memoryintfreekbs,memorykbs,
{
"count": 2,
{
"memoryintfreekbs": 0,
"memorykbs": 2097152
},
{
"memoryintfreekbs": 0,
"memorykbs": 2097152
}
]
}
```
=> uservmjoindaoimpl: Set free memory to zero if greater than total memory

README.md
fixes #4880 
The readme file had older `irc.freenode.net`, without any link.
By opening `https://webchat.freenode.net/` on the browser.
=> [REMOVED] IRC references on Readme.

ui/src/views/compute/AssignInstance.vue
Fixes the issue of displaying users in subdomains as well
Broken in the old UI as well
=> ui: assignVM: Set isrecursive to false when fetching accounts

ui/public/locales/en.json, ui/src/components/view/DetailsTab.vue, ui/src/config/section/offering.js
This PR displays the Root disk size as part of compute offering details if the offering was created with it specified.
Prior to this fix: When a compute offering is created with root disk size specified, there is not indication of this attribute in the corresponding Compute offering's details.
Post fix:
=> ui: Display root disk size in Compute offering details

server/src/main/java/com/cloud/template/TemplateManagerImpl.java
This PR fixes the issue that cross-zone templates cannot be copied to new zone.
(1) register a cross-zone template
(2) when it is done, remote it from http server
(3) create a new zone
(4) template cannot be downloaded to new zone, as it has been removed from http server
(5) copy template from first zone to new zone
Expected result: succeed
Actual result: API succeed, but nothing changed, logs: "Template 300  is cross-zone, don't need to copy"
=> server: allow copy cross-zone templates to other zone

api/src/main/java/org/apache/cloudstack/api/response/HostForMigrationResponse.java, server/src/main/java/com/cloud/api/query/dao/HostJoinDaoImpl.java
Fixes #3717 
Hosts can have multiple tags assigned to them therefore changes have been made to check for all of the host tags if they match `ha.tag` configuration value.
With a 2xKVM hosts env with advanced networking
Global config - ha.tag:
```
(localcloud) SBCM5> > list configurations name=ha.tag
{
"configuration": [
{
"category": "Advanced",
"description": "HA tag defining that the host marked with this tag can be used for HA purposes only",
"isdynamic": false,
"name": "ha.tag",
"value": "ha"
}
],
"count": 1
}
```
Before changes:
```
(localcloud) SBCM5> > list hosts type='Routing' filter=id,name,hahost,hosttags,hostha
{
"count": 2,
"host": [
{
"hahost": false,
"hostha": {
"haenable": false,
"hastate": "Disabled"
},
"id": "845ba3d4-3c28-497d-a4b5-f3918a3031b3",
"name": …
```
=> api/server: fix hahost value in listHosts

.travis.yml, engine/components-api/src/main/java/com/cloud/network/IpAddressManager.java, server/src/main/java/com/cloud/api/ApiDBUtils.java, server/src/main/java/com/cloud/api/ApiResponseHelper.java, server/src/main/java/com/cloud/network/IpAddressManagerImpl.java, server/src/main/java/com/cloud/server/ManagementServerImpl.java, test/integration/component/test_public_ip.py, test/integration/smoke/test_network.py
Public IP address dedicated to one domain should not be accessed
by other domains. Also root admin should be able to display all
public ip address in system.
Currently following issues exist
1. Public IP address assigned to one domain can be accessed by
other sibling domains
If use.system.public.ip is false then child domains should not
see public ip of ROOT domain
Before fix
```
(test1) mgt01 > list publicipaddresses listall=true fordisplay=true allocatedonly=false forvirtualnetwork=true filter=ipaddress,
{
"count": 59,
```
After fix
```
(test) mgt01 > list publicipaddresses listall=true fordisplay=true allocatedonly=false forvirtualnetwork=true filter=ipaddress,
{
"count": 10,
```
=> Bug fix in displaying public IP address of shared networks

api/src/main/java/com/cloud/network/VirtualNetworkApplianceService.java, engine/schema/src/main/java/com/cloud/vm/dao/DomainRouterDaoImpl.java, server/src/main/java/com/cloud/network/router/VirtualNetworkApplianceManagerImpl.java, server/src/main/java/com/cloud/network/rules/NicPlugInOutRules.java, server/src/main/java/com/cloud/network/rules/VirtualNetworkApplianceFactory.java, server/src/test/java/com/cloud/vpc/MockVpcVirtualNetworkApplianceManager.java, systemvm/debian/opt/cloud/bin/cs/CsAddress.py
This contains 3 main changes
(1) add NETWORK_STATS_ethX for all nics with public ips in VPC VRs (current: NETWORK_STATS_eth1)
(2) DO NOT create records in user_statistics for each VPC tier (only one record per public nic per VPC VR)
(3) send NetworkUsageCommand before unplugging a NIC with public IPs from VPC VR
=> vpc/server: Fix network statistics for vpc

systemvm/debian/etc/logrotate.conf, systemvm/debian/etc/logrotate.d/btmp, systemvm/debian/etc/logrotate.d/wtmp
logrotate in systemvms run every day. however it exits with failure.
```
root@r-100-VM:~# systemctl status logrotate
● logrotate.service - Rotate log files
Loaded: loaded (/lib/systemd/system/logrotate.service; static; vendor preset: enabled)
Active: failed (Result: exit-code) since Thu 2021-03-23 00:00:01 UTC; 2 days ago
Docs: man:logrotate(8)
man:logrotate.conf(5)
Process: 25001 ExecStart=/usr/sbin/logrotate /etc/logrotate.conf (code=exited, status=1/FAILURE)
Main PID: 25001 (code=exited, status=1/FAILURE)
Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.
```
it is because the logrotate for wtmp and btmp already exist in 4.15 systemvm template.
```
root@r-100-VM:~# cat /etc/logrotate.d/wtmp
/var/log/wtmp {
missingok
monthly
create 0664 …
```
=> systemvm: remove logrotate config for wtmp and btmp

systemvm/debian/etc/logrotate.d/rsyslog
We had critical issue with VR recently. The VRs of shared network or vpc stops working after some days.
After investigation, I found that the disk space is full
```
root@r-10-VM:~# df
Filesystem     1K-blocks    Used Available Use% Mounted on
/dev/vda5        2086316 2069932         0 100% /
```
logrotate/ryslog has compresses the log files, but space is not released. see `lsof |grep deleted`
```
root@r-10-VM:~# lsof |grep deleted
rsyslogd    960                      root   12w      REG              254,5 493060096        137 /var/log/daemon.log.1 (deleted)
rsyslogd    960                      root   13w      REG              254,5  17715200        110 /var/log/messages.1 (deleted)
rsyslogd    960                      root   16w      REG              254,5 545968128        342 …
```
=> VR: fix rsyslog compresses log files but not release disk space in VR

plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java, plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/LibvirtStorageAdaptor.java, plugins/hypervisors/kvm/src/main/java/org/apache/cloudstack/utils/qemu/QemuImg.java, plugins/hypervisors/kvm/src/test/java/org/apache/cloudstack/utils/qemu/QemuImgTest.java
Thanks @rubieHess  to point it out. 
see https://github.com/apache/cloudstack/pull/4800#discussion_r598318705
```
I detect that this code is problematic. According to the Performance (PERFORMANCE), Dm: Method invokes inefficient new String(String) constructor (DM_STRING_CTOR).
Using the java.lang.String(String) constructor wastes memory because the object so constructed will be functionally indistinguishable from the String passed as a parameter.  Just use the argument String directly.
```
=> kvm: remove unnecessary new String

server/src/main/java/com/cloud/network/router/VirtualNetworkApplianceManagerImpl.java
If the VPC has redundant VR's but doesnt have any tiers or there are no running VM's in
a VPC then disable the gateway check for VR
=> Disable VR health check for VPC without tiers

systemvm/debian/etc/vpcdnsmasq.conf, systemvm/debian/opt/cloud/bin/cs/CsDhcp.py
This PR adds the capability to VPC VR to answer "data-server" DNS queries based on the source IP of the VM.
1. Creates a new record for "data-server" translated to VR IP of newly create subnet in /etc/hosts file
2. Configure dnsmasq to send response of "data-server" query based on source IP of VM
~~~
1. Create a VPC
2. Add an isolated network with UserData service with VirtualRouter as provider
3. Create a VM in this network
4. Run "nslookup data-server" command from inside of VM
5. Run "cat /etc/hosts" command from inside of VR
~~~
~~~
Running "nslookup data-server" command returns IP address of router
Running "cat /etc/hosts" command from inside of VR shows "data-server" record and the VR NIC IP
~~~
~~~
Running "nslookup data-server" command returns "No answer"
The result of running …
=> Fix no "data-server" DNS record for VPC router

ui/src/config/section/network.js, ui/src/views/compute/InstanceTab.vue, ui/src/views/network/IpAddressesTab.vue
If a vm belongs to shared network then display the list
of ip addresses available which can be used to assign for
secondary IP addresses.
Also display "Public IP addresses" tab for shared networks
List all public ip address in shared network
Display the list of ip address while adding secondary ip instead of user input box
=> Display public ip addresses for shared network

plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/CitrixHelper.java, plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/CitrixResourceBase.java, plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/XenServerStorageProcessor.java, plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/Xenserver625StorageProcessor.java, plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/wrapper/xen610/XenServer610MigrateVolumeCommandWrapper.java, plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/wrapper/xen610/XenServer610MigrateWithStorageCommandWrapper.java, plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/wrapper/xenbase/CitrixCreateCommandWrapper.java, plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/wrapper/xenbase/CitrixDeleteStoragePoolCommandWrapper.java, plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/wrapper/xenbase/CitrixModifyStoragePoolCommandWrapper.java, plugins/hypervisors/xenserver/src/main/java/org/apache/cloudstack/storage/motion/XenServerStorageMotionStrategy.java
Fixes #4729
As reported in the issue ACP 4.7 used a normal UUID in db for a presetup primary store on Xenserver.
Later the value has been changed to store's path with '/' removed.
Current changes try to retrieve SR's name-lable from store's path if UUID doesn't match path field for a pre-setup store.
=> xenserver: retrieve correct name-label for presetup store

engine/storage/datamotion/src/main/java/org/apache/cloudstack/storage/motion/KvmNonManagedStorageDataMotionStrategy.java, engine/storage/datamotion/src/main/java/org/apache/cloudstack/storage/motion/StorageSystemDataMotionStrategy.java, engine/storage/datamotion/src/test/java/org/apache/cloudstack/storage/motion/StorageSystemDataMotionStrategyTest.java
PR #4698 was merged at the master (4.16) but it fixes an issue that is also relevant for current LTS versions.
Considering that the port is relatively straight-forward and it can benefit releases 4.14.2.0 and 4.15.1.0, this PR proposes back-porting PR #4698 into 4.14 and later forward it to 4.15.
More details at  #4698.
> In the execution flow of the API migrateVirtualMachineWithVolume, there is a step that copies the volume's template to the target storage, if it is needed.
> In some cases when the volume is a data type, it (the volume) does not have a template; therefore, it is going to generate an NPE when it tries to get the template's ID (Long to long auto conversion).
> 
> This PR intends to validate if the volume being copied has a template, before trying to copy the template.
=> [Backport] #4698 Fix npe when migrating vm with volume

ui/src/views/network/CreateSharedNetworkForm.vue
Sometimes creating shared network fails because the physical network
data is null and redereferencing it causes NPE.
Wait till the physical network data is available before accessing it
Fixes https://github.com/apache/cloudstack/issues/4664
=> Fix bug in creating shared network

server/src/main/java/com/cloud/template/TemplateManagerImpl.java
Fixes #4628
```
mysql> describe user_vm_details;
+---------+-----------------+------+-----+---------+----------------+
| Field   | Type            | Null | Key | Default | Extra          |
+---------+-----------------+------+-----+---------+----------------+
| id      | bigint unsigned | NO   | PRI | NULL    | auto_increment |
| vm_id   | bigint unsigned | NO   | MUL | NULL    |                |
| name    | varchar(255)    | NO   |     | NULL    |                |
| value   | varchar(5120)   | YES  |     | NULL    |                |
| display | tinyint(1)      | NO   |     | 1       |                |
+---------+-----------------+------+-----+---------+----------------+
5 rows in set (0.00 sec)
mysql> describe vm_template_details; …
```
=> server: filter null details during volume to template creation

test/integration/smoke/test_accounts.py, test/integration/smoke/test_affinity_groups_projects.py, test/integration/smoke/test_async_job.py, test/integration/smoke/test_hostha_simulator.py
This PR intends to make sure (in the end each of) the tests clean up their own test data.
make inventory of your cloud.
run any of the tests.
make invetory again
check the difference (should be nul
=> test cleanup

pom.xml
With 2.11 wire mock tests hanging and mvn can't execute in thread mode.
Update to 2.27.2(newest version)
Build cs with tests and multithreading in my env.
=> wiremock version 2.11 is incompatible with java 11

plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/manager/VmwareStorageManagerImpl.java, vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/HypervisorHostHelper.java, vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/VirtualMachineMO.java, vmware-base/src/test/java/com/cloud/hypervisor/vmware/mo/VirtualMachineMOTest.java
This PR fixes a small bug when explicitly setting VM hardware versions lower than version 10.
Vmware expects the hardware version in format: `vmx-DD` where DD is a two-digit representation of the virtual hardware version. For hardware version lower than 10, CloudStack was not using to digits for the hardware version number, which ended up on an error while creating worker VMs. (`vmx-8` for example instead of `vmx-08`)
=> [Vmware] Fix worker VMs hardware version small bug

server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
Since QCOW2 volumes cannot be resized to lower value in any case,
just disable it in backend.
=> Disable shrinking QCOW2 volumes

engine/components-api/src/main/java/com/cloud/capacity/CapacityManager.java, plugins/host-allocators/random/src/main/java/com/cloud/agent/manager/allocator/impl/RandomAllocator.java, server/src/main/java/com/cloud/agent/manager/allocator/impl/FirstFitAllocator.java, server/src/main/java/com/cloud/capacity/CapacityManagerImpl.java
Fixes #4517 
Adds capacity checks for RandomAllocator (host allocator)
Factors out host cpu capability and capacity check wrt serviceoffering code into CapacityManager.
1. For an env with one cluster with two hosts load the first host to max
2. Remove **RandomAllocator** from `host.allocators.exclude` and set `host.allocators.order` to **RandomAllocator,FirstFitRouting**
3. During deployment RandomAllocator will return both hosts as suitable hosts. But since the first host is not having enough capacity deployment will fail.
=> host-allocator: check capacity for suitable hosts 

test/integration/smoke/test_vm_life_cycle.py
This PR skips live migration on centos as the default installations for qemu/libvirt don't support it.
Fixes #4757
=> skip livemigration for centos

api/src/main/java/org/apache/cloudstack/api/command/admin/usage/ListUsageRecordsCmd.java, server/src/main/java/com/cloud/usage/UsageServiceImpl.java
When calling the listUasageRecords API records per domain are fetched recursively. This is not the case if you specify a domain id.
This PR adds a new parameter to enable fetching records recursively (isRecursive) when passing the domain id.
This has been tested by calling the API with different parameters. With/without a domain id, with/without isRecursive and with/without an account id.
I have tested by calling the API logged in as a root admin, domain admin, and a user.
=> Added recursive fetch of child domains for listUsageRecords API call

systemvm/debian/etc/iptables/iptables-dhcpsrvr, systemvm/debian/opt/cloud/bin/cs/CsAddress.py, systemvm/debian/opt/cloud/bin/cs/CsApp.py
There is a potential security issue with having http access to the VR from anywhere.
This PR restricts http access to the VR to the internal network only.
This was tested by creating a shared network and checking if port 80 and 443 is open on the VR based on the network you are connecting from.
=> Restricting http access on VR to internal network

core/src/main/java/com/cloud/agent/api/MigrateVmToPoolCommand.java, core/src/main/java/com/cloud/agent/api/storage/MigrateVolumeCommand.java, engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java, plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/guru/VMwareGuru.java, plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java, plugins/hypervisors/vmware/src/main/java/org/apache/cloudstack/storage/motion/VmwareStorageMotionStrategy.java, vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/HypervisorHostHelper.java, vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/VirtualMachineMO.java, vmware-base/src/main/java/com/cloud/hypervisor/vmware/util/VmwareHelper.java
Fixes #4838
For inter-cluster migration without shared storage, VMware needs a host to be specified. Fix is to specify an appropriate host in the target cluster during a stopped VM migration. Also, find target datastore using the host in the target cluster.
=> vmware: fix inter-cluster stopped vm and volume migration

server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java, server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
If VM details contain `rootdisksize`, volume entry in DB should reflect correct size when VM reset is performed.
Fixes #3957
=> server: fix root disk size on vm reset

api/src/main/java/com/cloud/vm/snapshot/VMSnapshot.java, engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/vmsnapshot/DefaultVMSnapshotStrategy.java
Fixes https://github.com/apache/cloudstack/issues/4201
This PR addresses the issue of a vm snapshot being indefinitely stuck is Expunging state in case deletion fails.
Simulated an exception  at the hypervisor end while deleting a VM snapshot and verified that the vm snapshot goes back to Ready state.
=> VM Snapshot: Prevent vm snapshots being indefinitely stuck in Expunging state on deletion failure

plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java, test/integration/smoke/test_vm_life_cycle.py, tools/marvin/marvin/lib/common.py
For backward compatibility, prior to Vmware 6.5 use EDIT operation instead of ADD when copying template vApp information
=> Fix VMware OVF properties copy from template

ui/src/api/index.js
Fixes https://github.com/apache/cloudstack/issues/4908
Specify username in the following format : xxx@domain.com and verified the login parameters being passed. Username is no longer undefined but points to the passed email address.
Without fix:
With Fix:
=> UI: fix login on UI

framework/quota/src/main/java/org/apache/cloudstack/quota/QuotaAlertManagerImpl.java, framework/quota/src/main/java/org/apache/cloudstack/quota/constant/QuotaConfig.java, plugins/database/quota/src/main/java/org/apache/cloudstack/quota/QuotaServiceImpl.java
On Quota's mailing settings, ACS has a configuration (`quota.usage.smtp.useAuth`) to inform if it will use secure SMTP authentication when sending emails.
However, this configuration only refers to use SSL or not. Operators haves no option to choose if they want to use StartTLS.
This PR intends to add support to StartTLS on Quota's mailing settings.
It is interesting to highlight that this enhancement would be able to solve issue #2625 (if it was applied in that setting as well); however, to reduce the scope of change, this one focuses only on Quota's mailing configuration.
1. I had Enabled Quota's plugin on the management server and configured it to use Gmail's SMTP server.
```
server address: smtp.gmail.com
username: gmail address
password: …
```
=> Add support to StartTLS on Quota's mailing

plugins/metrics/src/main/java/org/apache/cloudstack/response/HostMetricsResponse.java
This PR...
Fixes: #4733 
Navigating to the page is now possible.
=> Fixed hosts not displaying with incompatible locale

ui/src/components/view/SearchView.vue
Fixes the color style of the filter icon
BEFORE:
AFTER:
=> UI: Search view - Fixes the color style of the filter icon

engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/VolumeOrchestrator.java, server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
This PR  fixes: #4462
Problem Statement: 
In case of VMware, when a VM having multiple data disk is destroyed (without expunge) and tried to recover the VM then the previous data disks are not attached to the VM like before destroy. Only root disk is attached to the VM.
Root cause:
All data disks were removed as part of VM destroy. Only the volumes which are selected to delete (while destroying VM) are supposed to be detached and destroyed.
Solution:
During VM destroy, detach and destroy only volumes which are selected during VM destroy. Detach the other volumes during expunge of VM.
Test cases covered:
1. VM destroy and recover VM
- created VM with two data disks
- destroyed VM (without expunge) along with one data disk
- recovered VM, VM successfully came up with other data disk which …
=> Recover VM not able to attach the data disks which were attached before destroy

test/integration/smoke/test_diagnostics.py
Intermittent failures were seen with Trillian for `test_10_traceroute_in_vr` from `test_diagnostics.py`
Exception due to timeout,
```
2021-04-10 10:45:48,164 - DEBUG - Response : {jobprocstatus : 0, created : u'2021-04-10T10:44:47+0000', completed : u'2021-04-10T10:45:47+0000', cmd : u'org.apache.cloudstack.api.command.admin.diagnostics.RunDiagnosticsCmd', userid : u'accb47d3-99e0-11eb-ab0f-1e00f6000333', jobstatus : 1, jobid : u'663465e7-1ec4-4783-80d0-a54197ee729a', jobresultcode : 0, jobresulttype : u'object', jobresult : {stdout : u'', stderr : u'Command failed due to Exception: com.cloud.utils.ssh.SshException\nMessage: Timed out in waiting for SSH execution exit status\n', exitcode : u'-1'}, accountid : u'acca0117-99e0-11eb-ab0f-1e00f6000333'}
```
Change is to reduce the maximum …
=> test: reduce vr traceroute hops

core/src/main/java/com/cloud/agent/api/GetVmVncTicketAnswer.java, core/src/main/java/com/cloud/agent/api/GetVmVncTicketCommand.java, engine/schema/src/main/resources/META-INF/db/schema-41500to41510.sql, plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java, pom.xml, server/src/main/java/com/cloud/servlet/ConsoleProxyClientParam.java, server/src/main/java/com/cloud/servlet/ConsoleProxyServlet.java, services/console-proxy/server/pom.xml, services/console-proxy/server/src/main/java/com/cloud/consoleproxy/ConsoleProxy.java, services/console-proxy/server/src/main/java/com/cloud/consoleproxy/ConsoleProxyClientParam.java, services/console-proxy/server/src/main/java/com/cloud/consoleproxy/ConsoleProxyHttpHandlerHelper.java, services/console-proxy/server/src/main/java/com/cloud/consoleproxy/ConsoleProxyNoVNCHandler.java, services/console-proxy/server/src/main/java/com/cloud/consoleproxy/ConsoleProxyNoVncClient.java, services/console-proxy/server/src/main/java/com/cloud/consoleproxy/vnc/NoVncClient.java, services/console-proxy/server/src/main/java/com/cloud/consoleproxy/websocket/WebSocketReverseProxy.java, vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/VirtualMachineMO.java
This adds support for VMware 7.0 with a jar dependency and sql upgrade path. The jar dependency has been added to support noredist pkging here:
https://github.com/rhtyd/cloudstack-nonoss/blob/master/install-non-oss.sh#L37
Fixes #4441
Fixes #4423
=> engine: add support for VMware 7.0 dependency and hypervisor capability

ui/src/config/section/storage.js
Fixes the issue of not being able to select the diskofferingid while creating volumes from snapshots of ROOT volumes
=> ui: Show diskoffering for create volume from ROOT volume snaps

engine/components-api/src/main/java/com/cloud/resource/ResourceManager.java, server/src/main/java/com/cloud/resource/ResourceManagerImpl.java, server/src/main/java/com/cloud/vm/UserVmManager.java, server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
This PR adds a global settings parameter that configures the strategy for handling VMs in local storage when putting a host in maintenance.
Global settings name:  `host.maintenance.local.storage.strategy`
Description: _Defines the strategy towards VMs with volumes on local storage when putting a host in maintenance. The default strategy is 'Error', preventing maintenance in such a case. To migrate away VMs running on local storage choose 'Migrating' strategy. To stop VMs, choose 'Stopping' strategy._
- Strategy **Error**:
1. put a host into maintenance
2. Maintenance fails and the host gets into ErrorInMaintenance state
- Strategy **Stopping**:
1. put a host into maintenance
2. VMs with volumes on shared storage are migrated, VMs in local storage are stopped, the host gets into …
=> Migrate/Stop VMs with local storage when preparing host for maintenance

debian/rules
The cloud-agent is dependency of the KVM hypervisor plugin, don't
explicitly install/copy it again.
Fixes #4906
=> debian: remove duplicate agent jar copy

server/src/main/java/com/cloud/server/StatsCollector.java
Fixes regression introduced in 71c5dbcf492a023dbea5f8c34f8fd883c3ad653f
which would cause capacity bytes of certain pools to be update which
shouldn't get updated by StatsCollector such as solidfire.
Fixes #4911
Temporary repo builds here for testing purposes for community: http://download.cloudstack.org/testing/pr-4918/
(This will be removed after the PR is merged)
=> Stat collector solidfire capacity fix

utils/src/main/java/com/cloud/utils/exception/CSExceptionErrorCode.java
This PR proposes adding Exception UnavailableCommandException at the ExceptionErrorCodeMap.
When an API command is "blocked" due to the User's role not allowing it, an UnavailableCommandException is thrown. However, this leads to multiple logs such as:
`Could not find exception: com.cloud.exception.UnavailableCommandException in error code list for exceptions`
This escalates to a level that it gets hard to understand what is going on, especially if there have been multiple API commands refused (e.g. logging on UI with an User that has lots of API restrictions, thus failing many commands such as `list*`)
```
...
...
2021-04-15 16:00:48,454 INFO  [c.c.u.e.CSExceptionErrorCode] (qtp477376212-29347:ctx-34fbeee5 ctx-ca7a23a4) (logid:f56ab770) Could not find exception: …
```
=> Add UnavailableCommandException at ExceptionErrorCodeMap

plugins/integrations/cloudian/src/main/java/org/apache/cloudstack/cloudian/CloudianConnector.java
This PR sets cloudian.connector.enabled as not dynamic since cloudian requires the cloudianSsoLogin API which is added only once the MS is restarted
=> cloudian: Set cloudian.connector.enabled as not dynamic

plugins/outofbandmanagement-drivers/ipmitool/src/main/java/org/apache/cloudstack/outofbandmanagement/driver/ipmitool/IpmitoolOutOfBandManagementDriver.java
This PR intends to improve logging in the class `IpmitoolOutOfBandManagementDriver` to facilitate troubleshooting.
=> Improve logs on IpmitoolOutOfBandManagementDriver

engine/storage/datamotion/src/main/java/org/apache/cloudstack/storage/motion/DataMotionServiceImpl.java
When invoking `migrateVirtualMachineWithVolume` API call and a strategy isn't found the volumes are left in `Migrating` state
This PR puts back the volumes to `Ready` state 
OS - CentOS 7
Hypervisors - KVM
CS version - 4.15.1.0
manual tests with cloudmonkey and 2 couples of primary storage, which don't have DataMotionStrategy for this functionality.
Tried to migrate the VM with its volumes:
1 - between 2 Ceph primary storages
2 - between 2 StorPool primary storages
=> Fix volume state on migrate with migrateVirtualMachineWithVolume API call

engine/storage/image/src/main/java/org/apache/cloudstack/storage/image/TemplateDataFactoryImpl.java
This PR fixes an NPE obtained when CloudStack cleans up templates from primary storage.
Tested:
- Set 'storage.cleanup.interval' to a suitable low value
- Create template
- Deploy VM
- Destroy VM
- Remove template
- Wait for 'storage.cleanup.interval' to be executed
As a result the template is cleanup up from primary storage, and the entry from 'template_spool_ref' is removed. However, the process throws an NPE:
```
2021-04-22 17:33:43,442 DEBUG [c.c.s.StorageManagerImpl] (StorageManager-Scavenger-1:ctx-56d8209b) (logid:093e5adc) Storage pool garbage collector found 0 templates to clean up in storage pool: ref-trl-779-v-M7-nicolas-vazquez-esxi-pri1
2021-04-22 17:33:43,445 DEBUG [c.c.s.StorageManagerImpl] (StorageManager-Scavenger-1:ctx-56d8209b) (logid:093e5adc) Storage pool garbage …
```
=> Fix NPE on template garbage collection on primary storage

ui/src/views/iam/AddUser.vue
This PR fixes the errror thrown when trying to create a user by calling `fetchData` when the vue has not yet been created
=> ui: Fix error in adduser

ui/src/components/view/DedicateDomain.vue, ui/src/views/compute/AssignInstance.vue, ui/src/views/compute/CreateSSHKeyPair.vue, ui/src/views/iam/AddAccount.vue, ui/src/views/iam/AddUser.vue, ui/src/views/infra/network/DedicatedVLANTab.vue, ui/src/views/infra/network/IpRangesTabPublic.vue, ui/src/views/network/CreateIsolatedNetworkForm.vue, ui/src/views/network/CreateL2NetworkForm.vue, ui/src/views/network/CreateSharedNetworkForm.vue
Shows the domain path instead of the name in dropdowns
Fixes: #4947
=> ui: Show domain path instead of name

plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/CitrixResourceBase.java, server/src/main/java/com/cloud/vm/UserVmManagerImpl.java, test/integration/smoke/test_scale_vm.py
This PR fixes the scale VM failure noticed on XenServer/XCP-ng
Ran test_scale_vm.py on a XenServer / XCP-ng env :
XCP-ng: 
```
nosetests --with-xunit --xunit-file=results.xml --with-marvin --marvin-config=/marvin/ref-trl-780-x-M7-pearl-dsilva-advanced-cfg -s -a tags=advanced --hypervisor=xenserver /marvin/tests/smoke/test_scale_vm.py
/usr/lib/python2.7/site-packages/paramiko/transport.py:33: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
from cryptography.hazmat.backends import default_backend
==== Log Folder Path: …
```
=> marvin: fix test_scale_vm for xenserver/Xcp-ng

server/src/main/java/com/cloud/api/ApiDBUtils.java, server/src/main/java/com/cloud/api/query/dao/VolumeJoinDaoImpl.java
Volume can either have an associated disk offering (for DATA disks & ROOT disks for VMs created from ISO) or a compute/service offering (for ROOT disks of VMs created from templates).
This fix simplifies and fixes check to return the appropriate response keys in these cases.
Using cmk and API,
```(localcloud) SBCM5> > list virtualmachines id=6d098d2c-04e1-48eb-ada7-0b997a630a4f filter=id,name,serviceofferingid,serviceofferingname,templateid,templatename,
{
"count": 1,
{
"id": "6d098d2c-04e1-48eb-ada7-0b997a630a4f",
"name": "iso-vm1",
"serviceofferingid": "b0eac06c-95bf-4abc-91dc-3e6fd278af53",
"serviceofferingname": "Small Instance",
"templateid": "13c613ec-1f2a-4e56-b4d0-fe3021c87c70",
"templatename": "ma-iso"
}
]
}
(localcloud) SBCM5> > list isos …
```
=> api: fix disk/service offering volume response keys

ui/src/store/modules/user.js, ui/src/views/AutogenView.vue
This PR enables the 'Add LDAP Account' button to be displayed / removed immediately after the first LDAP configuration is added or the last LDAP configuration is removed respectively.
Behavior Prior to the fix:
When an LDAP configuration is added, on traversing to the Accounts Page, the 'Add LDAP Account' button isn't displayed until the page is refreshed. Same holds true in the case when the last LDAP configuration is removed.
Post Fix:
Displays the button immediately when the first LDAP configuration is added and removes the Add LDAP Account button on deletion of the last LDAP config.
=> ui: Display 'Add LDAP Account' button when LDAP configuration is added

engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/DataMigrationUtility.java, engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/snapshot/SnapshotDataFactoryImpl.java, engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/snapshot/SnapshotObject.java, framework/jobs/src/main/java/org/apache/cloudstack/framework/jobs/impl/AsyncJobManagerImpl.java, server/src/main/java/com/cloud/storage/snapshot/SnapshotManager.java, server/src/main/java/com/cloud/storage/snapshot/SnapshotManagerImpl.java
This PR makes sure no orphaned snapshot details are considered in the cleanup at startup job.
a real solution would be to implement some kind of cascading delete, but as the parent record is "only" marked as removed this would be a bit com
=> protect against stray snapshot-details without snapshot

plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterResourceModifierActionWorker.java, plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterStartWorker.java, test/integration/smoke/test_scale_vm.py
This PR prevents k8s cluster nodes' root disks from being resized on VMware if root disk size isn't provided and addresses a test regression on scale vm. 
```
2021-04-27 06:26:28,971 ERROR [c.c.k.c.a.KubernetesClusterActionWorker] (API-Job-Executor-8:ctx-8126598d job-803 ctx-9a6a3ae2) (logid:f9bfd370) Provisioning the master VM failed in the Kubernetes cluster : k8s
com.cloud.exception.InvalidParameterValueException: Going from existing size of 4756340736 to size of 0 would shrink the volume.Need to sign off by supplying the shrinkok parameter with value of true.
at com.cloud.storage.VolumeApiServiceImpl.resizeVolume(VolumeApiServiceImpl.java:1077)
at com.cloud.storage.VolumeApiServiceImpl.resizeVolume(VolumeApiServiceImpl.java:192)
at …
```
=> vmware cks: Guard k8s cluster root disk resize if no root disk size passed

api/src/main/java/org/apache/cloudstack/api/command/user/template/RegisterTemplateCmd.java, api/src/test/java/org/apache/cloudstack/api/command/user/template/RegisterTemplateCmdTest.java, server/src/main/java/com/cloud/template/TemplateAdapterBase.java, test/integration/smoke/test_kubernetes_clusters.py, test/integration/smoke/test_storage_policy.py, test/integration/smoke/test_templates.py, test/integration/smoke/test_volumes.py, tools/marvin/marvin/lib/base.py, tools/marvin/marvin/lib/common.py, ui/public/locales/en.json, ui/src/views/image/RegisterOrUploadTemplate.vue
This PR allows users and administrators whether to enable the feature to read settings from the OVA instead of providing them, or continue using the previous workflow.
Documentation PR: https://github.com/apache/cloudstack-documentation/pull/209
Register template using deploy-as-is
Register template using the usual worflow
Deploy VMs
=> [Vmware] Make deploy-as-is optional

ui/src/components/view/SettingsTab.vue
This PR fixes the issue noticed when traversing to the Settings tab on account, domain, Zone, Cluster, Storagepool Sections. On navigating to the Settings tabs, it displays all the configuration as opposed to only displaying the configuration specific to that scope as the scope specific parameter isn't passed until refreshed.
Only after refresh are we able to see the correct configuration:
Tested various views specified above
=> ui: Fix Settings Tab view

engine/schema/src/main/java/com/cloud/vm/VMInstanceVO.java
This PR adds an explicit length to `VMInstanceVO.backupVolumes`.
The default length is 255, which caused a truncation of data if the JSON object representing the backup volumes is too big.
It caused errors when backups were made on VMs with 3 volumes or more.
`vm_instance.backup_volumes` has the type TEXT, which has a maximal length of 65535 characters.
Fixes: #4965
N/A
I manually tested:
1. Build and package CloudStack with the fix
2. Reproduced the #4965 scenario (backup on a VM with 3 volumes, using Dummy B&R provider)
3. There was no issue, and the field in database is a valid JSON object.
=> Increase max length for VMInstanceVO.backupVolumes

engine/api/src/main/java/com/cloud/vm/VirtualMachineManager.java, engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java, engine/orchestration/src/test/java/com/cloud/vm/VirtualMachineManagerImplTest.java, server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
This PR addresses the issue raised at #4545 (_Fail to change Service offering from local <> shared storage_).
When upgrading a VM service offering it is validated if the new offering has the same storage scope (local or shared) as the current offering. I think that the validation makes sense in a way of preventing running Root disks with an offering that does not match the current storage pool. However, the validation only compares both offerings and does not consider that it is possible to migrate Volumes between local <> shared storage pools.
The idea behind this implementation is that CloudStack should check the scope of the current storage pool which the ROOT volume is allocated; this, it is possible to migrate the volume between storage pools and list/upgrade according to the …
=> Allow to upgrade service offerings from local <> shared storage pools

packaging/centos8/cloud.spec
Fixes: https://github.com/apache/cloudstack/issues/4969
This PR upgrades the version of libgcrypt that is required by libevirt 6.0
Successfully deployed a CentOS 8 based ACS env
=> CentOS 8: Install libgcrypt v1.8.5 required by libvirt 6.0

ui/src/views/infra/network/IpRangesTabGuest.vue
From the Zones -> Physical Network (Guest) -> Traffic Types View, when we attempt to create a network, Cancel / Creation of network operation doesn't close the form. This PR fixes the issue.
Attempted creating a network from the Zones View and observed that the form closes on completion of action
=> ui: Close Create network form from Zones -> Physical Network (Guest) -> Traffic Type view

ui/src/views/network/LoadBalancing.vue, ui/src/views/network/PortForwarding.vue
Fixes https://github.com/apache/cloudstack/issues/4974
This PR prevents port forward rule details filled, from being reset on cancelling the operation
Populated the details for adding port forward rules and cancelled the operation
=> ui: Prevent reset of port-forward rules on cancelling a form

setup/bindir/cloud-setup-databases.in
Duplicate PR of #4976 - Targeting 4.15
This PR will allow reserved Linux shell characters to be passed to the setup databases script for the database secret key.
Fixes #4925
Manual tests have been performed.
=> Fixed error when passing shell reserved characters to setup databases

ui/src/views/offering/AddComputeOffering.vue
In 4.13 it was possible to create service offerings with 0Mhz cpu speed so that se hypervisor decides how many Mhz are possible.
In 4.15 with the new UI it was not longer possible, This PR adapt the frontend check to get the same behavior  like 4.13. 
own vmware env. create service offering with 0Mhz cpu speed and build a vm.
=> allow zero as cpu speed value in service offerings

server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
This NPE may happen when a VM is marked removed in the DB but not its
nics on a shared network. This can usually happen due to a failed
expunged VM or when an admin manually marks a VM as removed in DB but
does not cleanup the nics/network resources.
=> server: NPE may cause management server to not start

api/src/main/java/com/cloud/event/EventTypes.java, api/src/main/java/com/cloud/storage/StorageService.java, api/src/main/java/org/apache/cloudstack/api/command/admin/storage/SyncStoragePoolCmd.java, core/src/main/java/com/cloud/storage/resource/StorageProcessor.java, core/src/main/java/com/cloud/storage/resource/StorageSubsystemCommandHandlerBase.java, core/src/main/java/org/apache/cloudstack/storage/command/SyncVolumePathAnswer.java, core/src/main/java/org/apache/cloudstack/storage/command/SyncVolumePathCommand.java, engine/components-api/src/main/java/com/cloud/storage/StorageManager.java, engine/schema/src/main/java/com/cloud/storage/dao/StoragePoolHostDao.java, engine/schema/src/main/java/com/cloud/storage/dao/StoragePoolHostDaoImpl.java, engine/schema/src/main/java/org/apache/cloudstack/storage/datastore/db/PrimaryDataStoreDao.java, engine/schema/src/main/java/org/apache/cloudstack/storage/datastore/db/PrimaryDataStoreDaoImpl.java, engine/storage/volume/src/main/java/org/apache/cloudstack/storage/datastore/provider/DefaultHostListener.java, plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java, plugins/hypervisors/ovm3/src/main/java/com/cloud/hypervisor/ovm3/resources/Ovm3StorageProcessor.java, plugins/hypervisors/simulator/src/main/java/com/cloud/resource/SimulatorStorageProcessor.java, plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java, plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageProcessor.java, plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/XenServerStorageProcessor.java, plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/Xenserver625StorageProcessor.java, server/src/main/java/com/cloud/server/ManagementServerImpl.java, server/src/main/java/com/cloud/storage/StorageManagerImpl.java, server/src/main/java/com/cloud/storage/StoragePoolAutomationImpl.java, tools/apidoc/gen_toc.py
Datastore cluster as a primary storage support is already there. But if any changes at vCenter to datastore cluster like addition/removal of datastore is not synchronised with CloudStack directly. It needs removal of primary storage from CloudStack and add it again to CloudStack.
Here synchronisation of datastore cluster is fixed without need to remove or add the datastore cluster.
1. A new API is introduced syncStoragePool which takes datastore cluster storage pool UUID as the parameter. This API checks if there any changes in the datastore cluster and updates management server accordingly.
2. During synchronisation if a new child datastore is found in datastore cluster, then management server will create a new child storage pool in database under the datastore cluster. If the new child …
=> VMware Datastore Cluster primary storage pool synchronisation

ui/src/config/section/offering.js
This PR displays zone name instead of zone uuid in backup offering list view
Before Fix:
After Fix:
=> ui: Display Zone Name instead of Zone UUID in list view

api/src/main/java/org/apache/cloudstack/api/command/user/template/GetUploadParamsForTemplateCmd.java, server/src/main/java/com/cloud/storage/upload/params/TemplateUploadParams.java, server/src/main/java/com/cloud/storage/upload/params/UploadParamsBase.java, server/src/main/java/com/cloud/template/TemplateAdapterBase.java
This PR fixes the upload from local using 'Read VM setting from OVA' - was not honoured if it was selected
- Upload template from local selecting 'Read VM settings from OVA' and other template without selecting it 
- Check both uploaded templates 'Read VM settings from OVA' values
=> Fix deploy-as-is not honoured on upload from local

ui/src/views/network/CreateVlanIpRange.vue
While add IP range for a basic zone, podid parameter must be passed with createVlanIpRange.
Fixes #5021 
In legacy UI:
W/o change in UI:
After change in UI:
=> ui: pass podid for basic zone createvlaniprange

ui/src/views/infra/network/IpRangesTabGuest.vue, ui/src/views/infra/network/IpRangesTabPublic.vue, ui/src/views/infra/network/TrafficTypesTab.vue
For Basic Zones, additional IP ranges can be added for the guest traffic, however, in the new UI, it isn't possible to add IP ranges.
Legacy UI:
Current UI:
Doesn't have the provision for adding additional IP range.
=> ui: Allow IP range creation for Physical Network - Guest Traffic in Basic Zones

api/src/main/java/org/apache/cloudstack/api/response/HostResponse.java, plugins/metrics/src/main/java/org/apache/cloudstack/metrics/MetricsServiceImpl.java, plugins/metrics/src/main/java/org/apache/cloudstack/response/HostMetricsResponse.java, server/src/main/java/com/cloud/api/query/dao/HostJoinDaoImpl.java
Fixes #4778
Based on the discussion on https://lists.apache.org/thread.html/r9833add572ddd7303c2a523c833a8c863e8d272db268927a7ca9b525%40%3Cdev.cloudstack.apache.org%3E, metrics responses should return values with CPU/memory overprovisioning.
Changes in listHostsMetrics response, cpu and memory values with overprovisioning. Cluster and Zone metrics get correct values with host value changes.
With cmk:
Without change:
```
(local) 🐱 > list zonesmetrics 
{
"count": 1,
"zone": [
{
"allocationstate": "Enabled",
"clusters": "2 / 2",
"cpuallocated": "0.52%",
"cpuallocateddisablethreshold": false,
"cpuallocatedthreshold": false,
"cpudisablethreshold": false,
"cputhreshold": false,
"cputotal": "192.00 Ghz",
"dhcpprovider": "VirtualRouter",
"dns1": "10.147.28.6",
"guestcidraddress": "10.1.1.0/24", …
```
=> api/server: cpu, memory values with overprovisioning in metrics response

tools/marvin/marvin/lib/base.py
Cannot migrate VM to another storage, because 'migrateto' argument is overridden.
tested with Marvin nose tests
=> Fix in Marvin - migrate_vm_with_volume

api/src/main/java/com/cloud/host/Status.java, api/src/main/java/com/cloud/vm/VirtualMachine.java, engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java, server/src/main/java/com/cloud/api/ApiResponseHelper.java
Fixes: https://github.com/apache/cloudstack/issues/4972
This PR sets systevms' agent state to disconnected when it is stopped. Currently, when a systemVM (Console Proxy VM / Secondary storage VM) is stopped, the agent state still appears to be 'Up'
When the VM is stopped (with / without force): 
When the systemVM is 'Stopped' or 'Starting' the agent state appears to be 'Up'
=> SystemVM: Set agent state to disconnected on Stopping the systemVM

api/src/main/java/org/apache/cloudstack/api/command/user/template/GetUploadParamsForTemplateCmd.java
This PR fixes the invalid ostypeid error when "Read settings from OVA" is not selected when uploading an OVA template.
Fixes: #5031
This has been tested by uploading an OVA template with and without reading settings from ova using the UI
=> Fixed invalid ostypeid when not using deployasis

server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
If the hypervisor's capabilities are null, CloudRuntimeException will be thrown;
Format the error message
tested on CS 4.15.1.0 with KVM hypervisors
=> Prevent NPE if hypervisor's capabilities are null

api/src/main/java/org/apache/cloudstack/api/command/user/job/ListAsyncJobsCmd.java
Today, I want to filter the jobs based on their `startdate` using the `listAsyncJobs` command. I noticed that the format of this parameter doesn't exist on its [API page](http://cloudstack.apache.org/api/apidocs-4.15/apis/listAsyncJobs.html). This PR will add the `startdate` formate to the API documentation.
This PR...
=> Add startdate formate to documents.

api/src/main/java/org/apache/cloudstack/outofbandmanagement/OutOfBandManagementService.java, server/src/main/java/org/apache/cloudstack/outofbandmanagement/OutOfBandManagementServiceImpl.java
On `BackgroundPollManagerImpl`, each submitted task needs to implement delay's configuration; otherwise it will assume the delay (which acts like the execution interval, not an actual delay) `4000ms` (hardcoded).
This PR intends to externalize the OOBM delay's configuration.
1. I enabled a zone;
2. i configured the OOBM in the host;
2. I observed the log. It will log in intervals according to the configuration set.
=> Externalize OOBM background task's interval

tools/marvin/marvin/lib/base.py
Fixes problems with:
* undefined params
* if we define those params when invoking the functions create_from_volume/create_from_snapshot will be created two templates
* according to the API docs and some digging into the code createTemplate command does not accept account and domainid
execute nose tests
=> fix: create template with Marvin

pom.xml
Maven 3.8.1 blocks non-secure repo connections per default.
This PR fixes the build while using Maven version >= 3.8.1
Try to build with Maven 3.8.1.
=> maven: Use https for jenkins repo, to fix build with newer maven

ui/src/views/image/RegisterOrUploadTemplate.vue
HVM is set to true if `requireshvm` param of `registerTemplate` and `getUploadParamsForTemplate` APIs if not passed (null value).
This change explicitly passes `requireshvm=false` when the checkbox is unselected in the UI form.
Using UI
Without change (`requireshvm` is not passed):
In DB
```
MariaDB [cloud]> select id,name,uuid,hvm from vm_template where uuid='af94adf5-36c8-434d-a87f-5e8c6fdfd89a'\G
id: 212
name: t31
uuid: af94adf5-36c8-434d-a87f-5e8c6fdfd89a
hvm: 1
```
With change:
In DB
```
MariaDB [cloud]> select id,name,uuid,hvm from vm_template where uuid='43b34bd5-d52a-47a5-928b-dc698bc4965c'\G
id: 213
name: t41
uuid: 43b34bd5-d52a-47a5-928b-dc698bc4965c
hvm: …
```
=> ui: pass requireshvm param for register/upload template API

services/secondary-storage/server/src/main/java/org/apache/cloudstack/storage/resource/NfsSecondaryStorageResource.java
While checking the secondary storage resource limit for the account, the size of the template directory is not set and the variable remains 0. This may lead to incorrect check as actual secondary storage usage will be higher in most cases.
=> secondary-storage: fix account template directory size

server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
When global config - vmware.root.disk.controller is set to empty and template is registered with deployasis, server will throw NPE while deploying a VM. This change fixes the problem by using default value of the config in this case.
By deploying VM with a deployasis (read settings from OVA) template.
**Without change:**
```
2021-05-28 06:41:53,503 DEBUG [c.c.a.ApiServlet] (qtp1233705144-21:ctx-18f24cbd) (logid:a0001979) ===START===  172.16.250.9 -- GET  zoneid=251398d0-707d-4e5a-9298-2a97a1eff534&templateid=888f0a52-e34b-4193-8cfb-4b7d3ce42753&startvm=true&serviceofferingid=8b28cbe8-5d57-4c3d-85d9-d92b67af13a3&affinitygroupids=&iptonetworklist[0].networkid=f3185526-afce-462d-ba75-b2ac439b9de9&name=t202&displayname=t202&command=deployVirtualMachine&response=json
2021-05-28 06:41:53,511 …
```
=> server: fixes NPE on empty vmware.root.disk.controller config

vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/HypervisorHostHelper.java
This PR fixes an issue on VMware when creating worker VMs for volume migration from/to hosts with different ESXi versions. In this case, the minimum ESXi host version is chosen for the worker VM hardware version but it is set in a wrong format ("DD" instead of "vmx-DD")
Vmware mixed environment with 2 clusters of 2 hosts each. One cluster with 5.5 hosts and other cluster with 6.5 hosts
=> [Vmware] Fix worker VM invalid numeric value

engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
This PR fixes #5047 which can be reproduced on Zones with _(I) Advanced Networks, (II) Security Groups enabled for the Zone, (III)  network offering without Security Groups_; for instance, `DefaultSharedNetworkOffering` which does not list Security Group as supported service.
The issue is due to the following code inside the method `VirtualMachineManagerImpl.orchestrateReboot`:
[VirtualMachineManagerImpl.java#L3340](https://github.com/apache/cloudstack/blob/280c13a4bb103dd748ec304bfe0714a148c24602/engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java#L3340).
```
final Answer rebootAnswer = cmds.getAnswer(RebootAnswer.class);
if (rebootAnswer != null && rebootAnswer.getResult()) {
if (dc.isSecurityGroupEnabled() && vm.getType() == VirtualMachine.Type.User) { …
```
=> FIX Network with SG Disabled still has security group script adding rules on KVM

server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
Fixes 
```
ERROR [c.c.a.ApiAsyncJobDispatcher] (API-Job-Executor-45:ctx-76ee0dfd job-787) (logid:c554bac0) Unexpected exception while executing org.apache.cloudstack.api.command.admin.volume.ResizeVolumeCmdByAdmin
java.util.UnknownFormatConversionException: Conversion = '.'
at java.base/java.util.Formatter.checkText(Formatter.java:2732)
at java.base/java.util.Formatter.parse(Formatter.java:2718)
at java.base/java.util.Formatter.format(Formatter.java:2655)
at java.base/java.util.Formatter.format(Formatter.java:2609)
at java.base/java.lang.String.format(String.java:2897)
at com.cloud.storage.VolumeApiServiceImpl.checkIfVolumeIsRootAndVmIsRunning(VolumeApiServiceImpl.java:1172)
at com.cloud.storage.VolumeApiServiceImpl.resizeVolume(VolumeApiServiceImpl.java:1013)
at …
```
=> Fix string format error

plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/CitrixResourceBase.java
This tries to separately eject and destroy cd-rom VBD for systemvms.
Doc fix also possible: https://github.com/apache/cloudstack-documentation/pull/216
=> xenserver: attempt eject and destroying patch VBD separately

systemvm/debian/opt/cloud/bin/cs_dhcp.py
This PR fixes #5058
when start a vm, the old entries in databag for the vm (with same mac addresses) should be removed then set again, to avoid duplicated records in dhcpentry databag and also /etc/dhcphosts.txt 
isolated networks
(1) stop vm, change vm ip address, start vm
vm info is updated in /etc/dhcphosts.txt and /etc/cloudstack/dhcpentry.json
(2) stop vm, expunge vm.
vm is removed from /etc/dhcphosts.txt and /var/lib/misc/dnsmasq.leases
vpc
(1) create vm in 2 vpc tiers
vm has 2 entries in /etc/dhcphosts.txt, and /etc/cloudstack/dhcpentry.json
(2) stop vm, change ip addresses, change nics order, start vm
entries are updated in /etc/dhcphosts.txt and /etc/cloudstack/dhcpentry.json
(3) remove a nic from vm (hot unplug)
vm nic is removed from /etc/dhcphosts.txt and …
=> vr: remove old ips with same mac address in dhcpentry databag

engine/schema/src/main/java/com/cloud/network/dao/NetworkDaoImpl.java
This PR fixes #5071; where it was reported an issue when creating a network with VXLAN.
Exception raised:
```
2021-06-03 11:09:55,724 ERROR [c.c.a.ApiServer] (qtp1665620686-39719:ctx-bf7efb52 ctx-c73431d6 ctx-c4105005) (logid:2252fead) unhandled exception executing api command: [Ljava.lang.String;@6b3403ea
com.cloud.utils.exception.CloudRuntimeException: VLAN requested but URI is not in the expected format: vxlan://525
at com.cloud.network.dao.NetworkDaoImpl.listByPhysicalNetworkPvlan(NetworkDaoImpl.java:784)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java …
```
=> Check for VLAN or VXLAN in NetworkDaoImpl.listByPhysicalNetworkPvlan

ui/src/components/view/DetailsTab.vue
Adds a check if ipV6Address is empty (usually before the details are fetched)
=> ui: Fix error when no ipv6 address

ui/src/config/section/compute.js
This PR removes redundant columns present in the List Virtual Machines view - for domain admin and user role
Prior Fix: Display Name column appearing twice
Post Fix:
=> ui: remove redundant columns in list VMs view

server/src/main/java/com/cloud/api/query/dao/ServiceOfferingJoinDaoImpl.java, ui/src/components/view/DetailsTab.vue
When listing service offerings it is expected to list their Root disk size in GB (see documentation [[1]](http://cloudstack.apache.org/api/apidocs-4.15/apis/listServiceOfferings.html)); however, it is returned in Bytes.
Additionally, during deployment of a VM or creation of a Service Offering the root disk size is always passed as a value in GB [[2]](https://cloudstack.apache.org/api/apidocs-4.15/apis/deployVirtualMachine.html).
This PR aims to fix this by converting the root disk size at the ServiceOffering response from Bytes to GB.
[1] http://cloudstack.apache.org/api/apidocs-4.15/apis/listServiceOfferings.html
[2] https://cloudstack.apache.org/api/apidocs-4.15/apis/deployVirtualMachine.html
N/A
List Service offerings via CloudMonkey (or any other way of calling API). Example: `list …
=> Root disk size should be listed in GB at listServiceOffering

plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java, server/src/main/java/com/cloud/template/TemplateManagerImpl.java
This PR fixes
1 - fix of attaching/detaching ISO of VM with UEFI boot type, which was introduced in #4773 
2 - if the OS type of an ISO is categorized as "Other", the bus type of the disk
will be set to "SATA" because we don't know what OS is behind "Other".
- [X ] Bug fix (non-breaking change which fixes an issue)
- [X ] Minor
manual tests with CentOS8 and Windows 10 ISOs
=> Fix of some UEFI related issues

vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/DiskControllerType.java, vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/ScsiDiskControllerType.java
This PR fixes deployment of VMs using controller `lsilogicsas` for Vmware deploy-as-is
Tested using Windows 10 template containing the following information on its OVF file: 
````
<Item>
<rasd:Address>0</rasd:Address>
<rasd:Description>SCSI Controller</rasd:Description>
<rasd:ElementName>SCSI Controller 1</rasd:ElementName>
<rasd:InstanceID>3</rasd:InstanceID>
<rasd:ResourceSubType>lsilogicsas</rasd:ResourceSubType>
<rasd:ResourceType>6</rasd:ResourceType>
<vmw:Config ovf:required="false" vmw:key="slotInfo.pciSlotNumber" vmw:value="160"/>
</Item>
````
=> [Vmware] Fix lsilogcsas controller for deploy-as-is

utils/pom.xml, utils/src/main/java/org/apache/cloudstack/utils/process/ProcessRunner.java, utils/src/test/java/org/apache/cloudstack/utils/process/ProcessTest.java
This PR intends to improve logging in the class `ProcessRunner` to facilitate troubleshooting.
=> Improve logs on ProcessRunner

engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java, plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java, server/src/main/java/com/cloud/storage/StorageManagerImpl.java
This PR fixes the problem of not updating the chain info or setting chain info to null after volume migrations.
Problem: While fetching the volume chain info, management server assumes datastore name to be a UUID (this is true only for NFS storages added by CloudStack) but datastore name can be with any name.
Solution: To fetch the volume chain info, use datastore name instead of UUID.
The fix is made in the flow of following API operations
1. migrateVirtualMachine
2. migrateVirtualMachineWithVolume
3. migrateVolume 
Created one NFS, one datastore cluster (with two child storages with names "child1", "child2") primary storages
1. Migrated a volume from NFS to datastore cluster. 'chain_info' in "volumes" table is updated
Before migration
After migration
2. Migrated volume from datastore …
=> Update chain info of the volumes after migrate operations

server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java, server/src/test/java/com/cloud/storage/VolumeApiServiceImplTest.java
When changing from a Service Offering with the root disk size enforced to another offering with the same root disk size enforced this will lead to the following error message.
On PR #4341 I covered manual tests **1, 2, & 3** as described on "**How Has This Been Tested?**"; however, none of these covered the issue discovered.
This PR addresses the test case **4** that is reported in "**How Has This Been Tested?**"
N/A
Tests:
Created the following service offerings (via API and also via UI):
0GB - default behavior with no Root Disk Size configured
5GB - 5GB Root
10GB - 10GB Root
15GB - 15GB Root
Executed following tests
1. Test root volume resize.
Expected result: not allowed to resize
Steps:
a - deploy a VM with any of the root size configured offerings (e.g. 5GB)
b - Change root volume …
=> Failed to scale between Service Offerings with the same root disk size

api/src/main/java/org/apache/cloudstack/api/command/admin/vm/ScaleVMCmdByAdmin.java, api/src/main/java/org/apache/cloudstack/api/command/admin/vm/UpgradeVMCmdByAdmin.java
Over the past years, I have seen some confusion regarding which command to use when changing a VM's offering. Users tend to choose always the API command [changeServiceForVirtualMachine](https://cloudstack.apache.org/api/apidocs-4.15/apis/changeServiceForVirtualMachine.html) and are not aware of [scaleVirtualMachine](https://cloudstack.apache.org/api/apidocs-4.15/apis/scaleVirtualMachine.html). On the best case, the user knows that both commands exist but is not sure about which one to choose.
This PR proposes some enhancements on the documentation of API commands `changeServiceForVirtualMachine` and `scaleVirtualMachine`. One of the major differences of both is that `scaleVirtualMachine` takes into account disk offerings, and also resizes the volume if necessary while …
=> Enhance docs for changeServiceForVM & scaleVirtualMachine

plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/BridgeVifDriver.java, plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/IvsVifDriver.java
when linux bridge is setup (refer to http://docs.cloudstack.apache.org/projects/archived-cloudstack-getting-started/en/latest/networking/vxlan.html#configure-product-to-use-vxlan-plugin) and used as the kvm traffic label of physical networks, the vms on different hosts cannot reach each other.
(1) does not work:
```
/usr/share/cloudstack-common/scripts/vm/network/vnet/modifyvxlan.sh -v 1001 -p eth1 -b brvx-1001 -o add
```
"bridge fdb" shows
```
00:00:00:00:00:00 dev vxlan1001 dst 239.0.3.233 via eth1 self permanent
```
(2) this works:
```
/usr/share/cloudstack-common/scripts/vm/network/vnet/modifyvxlan.sh -v 1001 -p cloudbr1 -b brvx-1001 -o add
```
"bridge fdb" shows
```
00:00:00:00:00:00 dev vxlan1001 dst 239.0.3.233 via cloudbr1 self permanent
```
=> vxlan: arp does not work between hosts as multicast group is communicated over physical nic instead of linux bridge

tools/travis/xunit-reader.py
This PR fixes error output for marvin tests not being generated if CDATA contains too much text.
the tests `test_multiple_subnets_in_isolated_network_rvr.py` and `test_multiple_subnets_in_vpc_rvr.py` from the component tests would crash `tools/xunit-reader.py` without it.
generating cli output in a component test log dir with only the failing output (of successfull tests:
without the fix:
```
Test | Result | Time (s) | Test File
--- | --- | --- | ---
File "/marvin/tools/xunit-reader.py", line 111, in <module>
main()
File "/marvin/tools/xunit-reader.py", line 40, in main
exit(parse_reports(file_path_list))
File "/marvin/tools/xunit-reader.py", line 84, in parse_reports
for event, elem in data:
File "src/lxml/iterparse.pxi", line 209, in …
```
=> allow big contents from error output in marvin tests

ui/public/locales/en.json
This PR fixes a typo on the login page :see_no_evil: 
With Fix:
=> Fix typo in error message on login page

server/src/main/java/com/cloud/server/ManagementServerImpl.java, server/src/main/java/com/cloud/vm/UserVmManagerImpl.java, server/src/test/java/com/cloud/vm/UserVmManagerImplTest.java
On API `resetSSHKeyForVirtualMachine`, ACS also regenerates VM password when it uses a template with `Password Enabled` as true; there is already anAPI to reset VM password, therefore, the reset SSH keys API should not reset the VM SSH password as well.
Besides running a meaningless process, the VM's password regeneration slows down the main process and may cause a confusion in operations due to password change in the VM without being explicity requested.
This PR intends to remove the meaningless password regeneration from `resetSSHKeyForVirtualMachine`. 
It has been tested locally in a test lab.
1. I created VM with a template with `Password Enabled` as true.
2. I logged in VM with the generated password on creation.
3. I stopped the VM and called the API.
4. I started the VM and tried …
=> Remove meaningless password regeneration on resetSSHKeyForVirtualMachine

ui/src/config/section/compute.js, ui/src/views/AutogenView.vue
Fixes: https://github.com/apache/cloudstack/issues/5127
This PR notifies the users of the changed password on VM reinstall if template is password enabled
=> ui: Notify vm password on reinstall of VM (for password enabled templates)

ui/src/views/compute/DeployVM.vue
Failed to deploy VM on UI when the offering has root disk size. This issue is caused due to PR #5085.
It was updated the API listing to keep it aligned with specifications/documentation (list in GB); however, it did not address the root disk size in the UI `DeployVM.vue`.
Without this fix deploying a VM with such an offering fails.
Change UI and re-test VM deployment
Successfully deploy via UI a VM where the offering has root disk size.
=> UI fix deployVm with rootdisk size wrongly converted

systemvm/debian/opt/cloud/bin/setup/router.sh, systemvm/debian/opt/cloud/bin/setup/vpcrouter.sh
Fixes #5117
The logrotate config says interval as hourly but it relies
on timer service to be invoked but in timer the frequency
is mentioned as 12h. So it wont be invoked every hour.
So change the frequency to hourly
=> Change logrotate interval to hourly

ui/src/config/section/compute.js
Fixes: https://github.com/apache/cloudstack/issues/5152
This PR notifies users of the new password assigned to the VM when SSH key is reset
Post Fix:
=> ui: Notify users of new VM password on resetting VM's SSH key

engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/snapshot/CephSnapshotStrategy.java, engine/storage/snapshot/src/test/java/org/apache/cloudstack/storage/snapshot/CephSnapshotStrategyTest.java
This PR fixes the deletion will be handled by DefaultSnapshotStrategy::deleteSnapshot #4797 
Manually tested: check if the snapshot is deleted from primary/secondary storage
=> Fix of delete of Ceph's snapshots from secondary storage

plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/BridgeVifDriver.java
This PR fixes: https://github.com/apache/cloudstack/issues/5077
1. On a zone with VXLAN isolation type:
- Created an Isolated network
- Created a VM 
- Deleted the VM - successfully deletes the Vxlan
```
2021-06-07 09:03:11,042 DEBUG [kvm.resource.BridgeVifDriver] (agentRequest-Handler-4:null) (logid:6f469f8f) Executing: /usr/share/cloudstack-common/scripts/vm/network/vnet/modifyvxlan.sh -o delete -v 1850 -p vx -b brvx-1850
2021-06-07 09:03:11,043 DEBUG [kvm.resource.BridgeVifDriver] (agentRequest-Handler-4:null) (logid:6f469f8f) Executing while with timeout : 1800000
2021-06-07 09:03:11,094 DEBUG [kvm.resource.BridgeVifDriver] (agentRequest-Handler-4:null) (logid:6f469f8f) Execution is successful.
```
2. Verified with VLAN isolation type to ensure no regression:
```
2021-06-07 …
```
=> vxlan: Fix failure to delete vxlan

services/secondary-storage/controller/src/main/java/org/apache/cloudstack/secondarystorage/SecondaryStorageManagerImpl.java, systemvm/debian/opt/cloud/bin/setup/common.sh
This PR configures the /etc/ntp.conf file with the list of servers set against the global setting - 'ntp.server.list' 
Set the global setting value for ntp.server.list and recreated the SSVM - logged into the SSVM and verified the following:
- the /etc/ntp.conf file has the list of ntp servers configured
- Also verified by using `ntpq -p`
=> Fix configuration of ntp server list in systemVMs

test/integration/smoke/test_persistent_network.py
Skips test_persistent_networks if the hypervisor is KVM and OVS is used as the network backend
=> tests: Skip test_persistent_networks if kvm and ovs

server/src/main/java/com/cloud/acl/DomainChecker.java
Display the proper account and other names rather than the
uuid representation of the object
```
Error: (HTTP 531, error code 4365) Account testuser does not have permission to launch instances from template testubuntu
```
=> Display proper names in error message

server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
This PR fixes #5121 - where in deletion of uploaded volumes while succeeds on the secondary store does not update the status of the volume in the 'volumes' table
Uploaded a volume and attempted deletion (on a vmware env):
- volume deleted on secondary store
- volume_store_ref updated with state set to destroyed
- volumes table has state set to Destroy
=> volume: Fix deletion of Uploaded volumes

plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterResourceModifierActionWorker.java, plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterStartWorker.java, plugins/integrations/kubernetes-service/src/main/java/org/apache/cloudstack/api/response/KubernetesClusterResponse.java, plugins/integrations/kubernetes-service/src/main/resources/conf/k8s-control-node-add.yml, plugins/integrations/kubernetes-service/src/main/resources/conf/k8s-control-node.yml, plugins/integrations/kubernetes-service/src/main/resources/conf/k8s-node.yml, ui/src/config/section/compute.js
This PR replaces some offensive words in kubernetes plugin/service with inclusive words/terms.
Manually tested API / Response.
=> Updated some offensive words in kubernetes plugin/service with inclusive words/terms.

server/src/main/java/com/cloud/hypervisor/HypervisorGuruBase.java
This PR fixes NPE noticed during removal of  VM from a network (KVM) - leading to test failures noticed in test_vpc_redundant.py
```
2021-06-23 00:17:28,726 WARN  [o.a.c.e.o.NetworkOrchestrator] (API-Job-Executor-87:ctx-86b1bf56 job-3057 ctx-cee7aba3) (logid:355b434c) Unable to complete shutdown of the network elements due to element: VpcVirtualRouter
at com.cloud.hypervisor.HypervisorGuruBase.toVirtualMachineTO(HypervisorGuruBase.java:183)
at com.cloud.hypervisor.KVMGuru.implement(KVMGuru.java:112)
at com.cloud.vm.VirtualMachineManagerImpl.orchestrateRemoveVmFromNetwork(VirtualMachineManagerImpl.java:4171)
at com.cloud.vm.VirtualMachineManagerImpl.removeVmFromNetwork(VirtualMachineManagerImpl.java:4156)
at …
```
=> Fix NPE during removal of VM from Network

server/src/main/java/com/cloud/alert/AlertManagerImpl.java
This PR fixes the NPE that's encountered when `alert.email.addresses` isn't configured i.e.,no recipient.
```
2021-06-23 04:08:46,798 ERROR [c.c.a.AlertManagerImpl] (RedundantRouterStatusMonitor-3:ctx-b0621cdd) (logid:3ad3ae67) Problem sending email alert
at com.cloud.alert.AlertManagerImpl.sendAlert(AlertManagerImpl.java:722)
at com.cloud.alert.AlertManagerImpl.sendAlert(AlertManagerImpl.java:243)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at …
```
=> Fix NPE when no recipients configured for sending alerts

ui/public/locales/en.json, ui/src/components/view/ListView.vue, ui/src/components/widgets/Status.vue, ui/src/config/section/infra/secondaryStorages.js, ui/src/views/AutogenView.vue
Fixes https://github.com/apache/cloudstack/issues/5169
=> [UI] secondary storage - Display text and change the badge color of the Read-only column

engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
A destroyed VM when attempted to be started (using the bulk action support in the UI), results in a successful operation, however, the VM doesn't actually start. This PR fixes the false positive result shown in the above mentioned condition
VM continues to remain in destroyed state - but a success response is returned
Tried starting an instance in destroyed state:
```
2021-06-29 12:57:51,609 WARN  [c.c.v.VirtualMachineManagerImpl] (Work-Job-Executor-5:ctx-da4601fa job-52/job-54 ctx-cc08e96e) (logid:08e57fcb) VM VM instance {"id": "3", "name": "i-2-3-VM", "uuid": "4213c3d9-72a8-4201-96c4-003e2c2f845b", "type"="User"} is not in a state to be started: Destroyed
2021-06-29 12:57:51,610 INFO  [c.c.v.VirtualMachineManagerImpl] (Work-Job-Executor-5:ctx-da4601fa job-52/job-54 ctx-cc08e96e) …
```
=> Prevent starting a VM in destroyed state (or any state but Stopped)

api/src/main/java/org/apache/cloudstack/api/command/user/firewall/CreateFirewallRuleCmd.java, api/src/main/java/org/apache/cloudstack/api/command/user/firewall/CreatePortForwardingRuleCmd.java
Amend the description for the cidrlist parameter in CreatePortForwardingRule and CreateFirewallRule to state that it is deprecated and shouldn't be used.
Passing this parameter will always result in an error.
Fixes: #4036 
See the original bug report for an explanation.
=> Document cidrlist parameter deprecation

tools/marvin/marvin/deployDataCenter.py
This PR fixes a compatibility issue noticed with deployDataCenter.py script when run with python3 - the script reports the following exception:
```
Exception Occurred  while persisting DC Settings: ['Traceback (most recent call last):\n', '  File "tools/marvin/marvin/deployDataCenter.py", line 76, in __persistDcConfig\n    pickle.dump(self.__cleanUp, file_to_write)\n', 'TypeError: write() argument must be str, not bytes\n']
```
And hence doesn't create the dc_entries.obj file
Ran the deployDataCenter script using python2 and python3 - it runs successfully and generates the dc_entries.obj file in human readable format (which is controlled by the protocol number passed)
=> marvin: make deployDataCenter.py script compatible with python 2 and 3

ui/src/components/view/InfoCard.vue
This PR fixes traversal to the domain's detail tab on clicking on the router link present in any resource.
Currently, on clicking the router link of a domain doesn't select any active tab
Post fix: Selects the Details tab as default active tab
=> ui: Fix traversal to domain details via domain router-link of a resource

api/src/main/java/org/apache/cloudstack/api/command/admin/acl/BaseRolePermissionCmd.java, api/src/main/java/org/apache/cloudstack/api/command/admin/acl/CreateRoleCmd.java, api/src/main/java/org/apache/cloudstack/api/command/admin/acl/ImportRoleCmd.java, api/src/main/java/org/apache/cloudstack/api/command/admin/acl/project/CreateProjectRoleCmd.java, api/src/main/java/org/apache/cloudstack/api/command/admin/acl/project/CreateProjectRolePermissionCmd.java, api/src/main/java/org/apache/cloudstack/api/command/admin/acl/project/ProjectRoleCmd.java, api/src/main/java/org/apache/cloudstack/api/command/admin/acl/project/UpdateProjectRolePermissionCmd.java, api/src/main/java/org/apache/cloudstack/api/command/admin/diagnostics/RunDiagnosticsCmd.java, api/src/main/java/org/apache/cloudstack/api/command/admin/ha/ConfigureHAForHostCmd.java, api/src/main/java/org/apache/cloudstack/api/command/admin/ha/ListHostHAProvidersCmd.java, api/src/main/java/org/apache/cloudstack/api/command/admin/network/CreateManagementNetworkIpRangeCmd.java, api/src/main/java/org/apache/cloudstack/api/command/admin/network/CreateNetworkOfferingCmd.java, api/src/main/java/org/apache/cloudstack/api/command/admin/network/DeleteManagementNetworkIpRangeCmd.java, api/src/main/java/org/apache/cloudstack/api/command/admin/outofbandmanagement/IssueOutOfBandManagementPowerActionCmd.java, api/src/main/java/org/apache/cloudstack/api/command/user/project/CreateProjectCmd.java, api/src/main/java/org/apache/cloudstack/api/command/user/resource/ListDetailOptionsCmd.java, server/src/main/java/com/cloud/api/dispatch/ParamProcessWorker.java
Addon to https://github.com/apache/cloudstack/pull/5135
Ensures that any required parameter is not empty / null
```
(localhost) 🐱 > create domain 
💩 Missing required parameters:  name
(localhost) 🐱 > create domain name= 
🙈 Error: (HTTP 431, error code 4350) Empty or null value provided for API arg: name
```
=> apiserver : Ensure required parameters are not empty

plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java
Recent forward merge of 4.15 branch accidentally brought a bug in VM relocation method for VMware while trying to find datastore for the migrated volume.
This PR fixes it by using either of available target or source host.
```
[root@pr5030-t1171-vmware-65u2-marvin marvin]# nosetests --with-xunit --xunit-file=results.xml --with-marvin --marvin-config=./pr5030-t1171-vmware-65u2-advanced-cfg -s -a tags=advanced --hypervisor=VMware tests/smoke/test_vm_life_cycle.py
==== Log Folder Path: /marvin/MarvinLogs/Jun_30_2021_10_47_36_DT690J. All logs will be available here ====
=== TestName: test_advZoneVirtualRouter | …
```
=> vmware: fix migrate vm with volume

engine/components-api/src/main/java/com/cloud/storage/StorageManager.java, engine/schema/src/main/java/com/cloud/hypervisor/dao/HypervisorCapabilitiesDao.java, engine/schema/src/main/java/com/cloud/hypervisor/dao/HypervisorCapabilitiesDaoImpl.java, engine/storage/src/main/java/org/apache/cloudstack/storage/allocator/AbstractStoragePoolAllocator.java, server/src/main/java/com/cloud/deploy/DeploymentPlanningManagerImpl.java, server/src/main/java/com/cloud/server/ManagementServerImpl.java, server/src/main/java/com/cloud/storage/StorageManagerImpl.java, server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java, server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
Refactors:
- `UserVmManagerImpl::migrateVirtualMachineWithVolume`
- `Boolean HypervisorCapabilitiesDao::isStorageMotionSupported` to `boolean HypervisorCapabilitiesDao::isStorageMotionSupported` for simplifying callers.
- `StorageManager::isStoragePoolComplaintWithStoragePolicy` to `StorageManager::isStoragePoolCompliantWithStoragePolicy`
Update log messages.
=> refactor: migrate vm with storage

server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
New NICs shouldn't be added to VM with Shared and Isolated networks from admin account, same as deployment.
Tested:
- Admin trying to add a network from its own account to a VM from a user account.
- Admin trying to deploy VM in a user account with a network from its own account.
- Admin trying to attach a volume from its own account to a VM from a user account.
Networks
```
(local) 🐧 > list networks filter=id,name,domain,account listall=true 
{
"count": 3,
"network": [
{
"id": "06fbdecb-e75d-4015-9ec1-8a08a217ad2d",
"name": "l2nw"
},
{
"id": "a99496df-aade-42d7-b315-33f69719cdd6",
"name": "isonw"
},
{
"account": "user1",
"id": "2b56b153-9b56-4cf0-b23a-ef3817f9b806",
"name": "nw"
}
]
}
``` …
=> server: fix network access for addNicToVirtualMachine API

plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java, plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java, plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java
Currently there is no disk IO driver configuration for VMs running on KVM. That's OK for most the cases; however, recently there have been added some quite interesting optimizations with the IO driver `io_uring`.
Note that IO URING requires:
- `Qemu >= 5.0`, and
- `Libvirt >= 6.3.0`.
By using `io_uring` we can see a massive I/O performance improvement within Virtual Machines running from Local and/or NFS storage.
This implementation enhances the KVM disk configuration by adding workflow for setting the disk IO drivers. Additionally, if the    Qemu and Libvirt versions matches with the required for having `io_uring` we are going to set it on the VM. If there is no support for such driver we keep it as it is nowadays, without any IO driver configured.
Fixes: #4883
Locally debugging with …
=> KVM NFS disk IO driver supporting IO_URING

plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java
On newer libvirt/qemu it seems PCI hot-plugging could be an issue as
seen in:
https://www.suse.com/support/kb/doc/?id=000019383
https://bugs.launchpad.net/nova/+bug/1836065
This was found to be true on ARM64/aarch64 platform (tested on
RaspberryPi4). As per the default machine doc, it advises to
pre-allocate PCI controllers on the machine and pcie-to-pci-bridge based
controller for legacy PCI models:
https://libvirt.org/pci-hotplug.html#x86_64-q35
This patch introduces the concept as a workaround until a proper fix is
done (ideally in the upstream libvirt/qemu projects). Until then client
code can add 32 PCI controllers and a pcie-to-pci-bridge controller for
aarch64 platforms.
Tested on RaspberryPi4+Ubuntu 20.04 with: http://download.cloudstack.org/rpi4/4.15/
Old PR: …
=> kvm: pre-add 32 PCI controller for hot-plug issue on ARM64/aarch64

engine/components-api/src/main/java/com/cloud/capacity/CapacityManager.java, engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/StorageOrchestrator.java, server/src/main/java/com/cloud/capacity/CapacityManagerImpl.java, server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java, server/src/main/java/com/cloud/server/StatsCollector.java
On StatsCollector, it limits secondary storages capacity to 90%; therefore, operators do not have option to choose which threshold they want/need. 
This PR intends to externalize the secondary storage capacity threshold configuration on StatsCollector (`secondary.storage.capacity.threshold`), validating if it is between 0 and 100% (0.00 and 1.00).
1. I enabled a zone;
2. I created a template and observed the log. It will log messages according to the configuration set.
=> Externalize secondary storage capacity threshold

api/src/main/java/com/cloud/network/Network.java, api/src/main/java/com/cloud/network/NetworkProfile.java, api/src/main/java/com/cloud/network/vpc/Vpc.java, api/src/main/java/com/cloud/offering/NetworkOffering.java, api/src/main/java/org/apache/cloudstack/api/response/NetworkResponse.java, api/src/main/java/org/apache/cloudstack/api/response/ProjectResponse.java, engine/schema/src/main/java/com/cloud/network/vpc/VpcVO.java, server/src/main/java/com/cloud/api/ApiResponseHelper.java, server/src/main/java/com/cloud/api/query/dao/NetworkOfferingJoinDaoImpl.java, server/src/main/java/com/cloud/api/query/dao/ProjectJoinDaoImpl.java
Fixes: https://github.com/apache/cloudstack/issues/5209
This PR adds 'created' field to the response of listing Networks, VPCs, Projects, NetworkOffering
=> api: Add 'created' field to API response

ui/src/utils/plugins.js
Fixes https://github.com/apache/cloudstack/issues/5172
Ensures that the page is refreshed after an async job only if it is the same / parent page being viewed
=> ui: Refresh after async job completed only on current / parent page

server/src/main/java/com/cloud/uuididentity/UUIDManagerImpl.java
This PR adds a debug facility.
=> add entity-type to message when no UUID is found for a DB ID

engine/components-api/src/main/java/com/cloud/alert/AlertManager.java, server/src/main/java/com/cloud/alert/AlertManagerImpl.java, server/src/main/java/com/cloud/projects/ProjectManager.java, server/src/main/java/com/cloud/projects/ProjectManagerImpl.java
- Some servers (such as [Microsoft](https://docs.microsoft.com/en-us/microsoft-365/compliance/prepare-tls-1.2-in-office-365?view=o365-worldwide) exchange) are deprecating TLSv1 and TLSv1.1. On alert's and project's mailing settings, ACS uses the protocol TLSv1; therefore, operators do not have options to choose which version they want to use.
- ACS has configurations (`\*.smtp.useAuth`) to inform if it will use secure SMTP authentication when sending emails; However, this configuration only refers to the use of SSL. Operators have no means to choose if they want to use StartTLS option.
This PR intends to externalize the protocol's and StartTLS settings on alert's and project's mail sending. Alert and project (also quota) send email through the class `SMTPMailSender`, inserted in PR …
=> Externalize tls version and security protocols configuration on mail sending

server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java, test/integration/component/test_rootvolume_resize.py, test/integration/smoke/test_volumes.py
Remove condition that are prevent resizing for root volumes (vmware).
Tested in own VMware Environment. Works without errors and root disk is correct resized
=> Remove condition that are prevent resizing for root volumes (vmware)

ui/src/views/infra/HostInfo.vue
This PR improves the HostView, so that only relevant information is shown.
This also fixes a small bug, when no `hosttags` or `oscategoryid` exists, that wrong (_maybe cached?_) values were shown, instead of no values.
=> UI: only display host information, if they are relevant

server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
If the volumes are in QCOW2 format, the shrinking will be handled on
the agents' side. There are cases in some storage plugins where the
volumes' format is kept in the DB in QCOW2, but the actual format is raw.
Till the current implementation, this was limiting the plugins to shrink
the volumes. Now this will be handled by the storage plugins.
manual tests with NFS/StorPool primary storages
=> Fix of shrinking volumes with QCOW2 format

server/src/main/java/com/cloud/server/ManagementServerImpl.java
Fixes: https://github.com/apache/cloudstack/issues/5229
This PR fixes the issue noticed while listing public IP addresses wrt pagination. The count is set to the number of items being returned as opposed to the total number of entities (here, public IPs)
via cmk:
Prior Fix:
```
list publicipaddresses  listall=true filter=id
{
"count": 55,
{
....
}
]
}    
list publicipaddresses  pagesize=5 page=1 listall=true filter=id
{
"count": 5,    <--- while count has to be 55, it returns 5 which is the value of pagesize
{
"id": "152f39af-1af7-4413-bbf1-1132b1708a9d"
},
{
"id": "cbd3f921-53b5-45a6-9a1b-8c5877e9be34"
},
{
"id": "425204aa-8efd-400a-bc07-98a14fae00b3"
},
{
"id": "dc5b206d-db46-4ab5-9ede-da63261648e5"
},
{
"id": …
```
=> api: Fix pagination for list PublicIPAddresses

ui/src/views/network/CreateSharedNetworkForm.vue
Fixes create shared network form for multi-zone environments.
Current behaviour (API request is made with wrong physical network ID for the zone):
After this change:
=> ui: fix create shared network with multi-zone

server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
With this commit [Fix limitation on tag matching in 'migrateVolume' with disk offering](https://github.com/apache/cloudstack/commit/756a7e89cbcec7a1aa98b3f470cbdf8181af75ad) the author changed the volume migrate API to allow operators to override the volume placement. Moreover, the tag validation would only happen if the operator changes the disk offering. However, further, but with this commit [Vmware offline migration](https://github.com/apache/cloudstack/commit/b363fd49f70ac2092ebe6226a72a3d911dc99e1f),  cloudstack started to validate the tags again when the operator executes the volume migrate command without. This broke the override mechanism that has been previously introduced into ACS.
If the operator wants to migrate volumes, without changing the disk offering, we don't need to …
=> remove the unnecessary check for tags when migrating volumes

ui/src/components/view/ActionButton.vue, ui/src/utils/plugins.js, ui/src/views/AutogenView.vue, ui/tests/mockData/ActionButton.mock.json, ui/tests/unit/views/AutogenView.spec.js, ui/tests/unit/views/compute/MigrateWizard.spec.js
Related https://github.com/apache/cloudstack/issues/5212
=> [TEST] - Test unit - Fix failing UI unit test 4.15 branch

README.md
I could not find references for the YouTube channel at the README. 
Even though the README file is not a great "marketing platform", I think that it is still worth mentioning the YT channel in the README.
=> Add YouTube channel link in the README

ui/src/views/image/TemplateZones.vue
This PR fixes: https://github.com/apache/cloudstack/issues/5280, which fixes failure in deletion of templates
Register a template and attempt deleting the template from a particular zone - It successfully deletes the template
=> ui: Fix failure in deletion of templates

ui/src/views/network/AclListRulesTab.vue, ui/src/views/network/EgressRulesTab.vue, ui/src/views/network/FirewallRules.vue, ui/src/views/network/IngressEgressRuleConfigure.vue, ui/src/views/network/LoadBalancing.vue, ui/src/views/network/PortForwarding.vue
filters do not provide reference to the global context and hence raise an error.
Fixes #5268
Original:
After fix:
=> ui: fix capitalise filter

ui/src/components/view/ListView.vue, ui/src/components/widgets/Status.vue
Matches the legacy UI of showing the host as insecure 
Fixes https://github.com/apache/cloudstack/issues/5256
=> ui: Show host as unsecure in listview

systemvm/debian/opt/cloud/bin/cs/CsRedundant.py
=> vr: restart conntrackd instead of '/usr/sbin/conntrackd -d'

engine/storage/src/main/java/org/apache/cloudstack/storage/allocator/AbstractStoragePoolAllocator.java, server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
PR #4640 added a condition validating if the VM is from hypervisor VMWare, in `AbstractStoragePoolAllocator::reorderPools(List<StoragePool>, VirtualMachineProfile, DeploymentPlan, DiskProfile)`.
https://github.com/apache/cloudstack/blob/450de92e6cdc6d5611ca4ba701660826d6c70141/engine/storage/src/main/java/org/apache/cloudstack/storage/allocator/AbstractStoragePoolAllocator.java#L188-L191
However, when creating a volume from a snapshot (without VM's id), ACS instantiates the VirtualMachineProfile without a VM:
https://github.com/apache/cloudstack/blob/75a2c0bd995abc39d02a82c96664f2aecac426d8/engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/VolumeOrchestrator.java#L434
Which cause a NPE on:
https://github.com/apache/cloudstack/blob/450de92e6cdc6d5611ca4ba70166082 …
=> Fix regression on create volume from snapshot

ui/src/views/infra/zone/IpAddressRangeForm.vue
Fixes https://github.com/apache/cloudstack/issues/5286
=> UI - Zone Wizard - Fixes the IP range form fields are too narrow

server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
I've upgraded a stage environment from an older 4.16-SNAPSHOT to the current one and found a regression bug at the VM migration.
When calling the `migrateVirtualMachineWithVolume`, the following `InvalidParameterValueException` is launched: `Unsupported hypervisor: KVM for VM migration, we support XenServer/VMware/KVM only`.
The test was executed on a cluster with KVM nodes.
At the UI, migrate a VM with a Root volume allocated in a local storage. Or, call the API command [migrateVirtualMachineWithVolume](https://cloudstack.apache.org/api/apidocs-4.15/apis/migrateVirtualMachineWithVolume.html).
=> Fix migration issue in UserVmManagerImpl.migrateVirtualMachineWithVolume

engine/components-api/src/main/java/com/cloud/template/TemplateManager.java, plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/VmwareServerDiscoverer.java, plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java, plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageProcessor.java, plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/discoverer/XcpServerDiscoverer.java, plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/CitrixResourceBase.java, plugins/hypervisors/xenserver/src/test/java/com/cloud/hypervisor/xenserver/discoverer/XcpServerDiscovererTest.java, plugins/hypervisors/xenserver/src/test/java/com/cloud/hypervisor/xenserver/resource/CitrixResourceBaseTest.java, server/src/main/java/com/cloud/api/query/QueryManagerImpl.java, server/src/main/java/com/cloud/api/query/dao/TemplateJoinDaoImpl.java, server/src/main/java/com/cloud/template/TemplateManagerImpl.java, server/src/test/java/com/cloud/api/query/dao/TemplateJoinDaoImplTest.java
=> server: skip zone check for PERHOST iso during attachIso

api/src/main/java/org/apache/cloudstack/api/command/user/vm/DeployVMCmd.java, api/src/main/java/org/apache/cloudstack/api/command/user/vm/UpdateVMCmd.java, engine/schema/src/main/java/com/cloud/vm/UserVmVO.java, server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java, server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
Currently we can send a default value of 4K/32K for GET/POST request of
user data field. Most new browsers and also nginx support till 1MB of
post data.
Added a new global setting `vm.userdata.max.length` with default value of
32KB which can be increased till 1MB.
=> Change GET/POST request max length of VM user data to 4K/1M

api/src/main/java/org/apache/cloudstack/api/response/UserVmResponse.java, engine/schema/src/main/resources/META-INF/db/schema-41510to41600.sql, plugins/metrics/src/main/java/org/apache/cloudstack/metrics/MetricsServiceImpl.java, server/src/main/java/com/cloud/api/query/dao/UserVmJoinDaoImpl.java, server/src/main/java/com/cloud/api/query/vo/UserVmJoinVO.java, ui/src/components/view/InfoCard.vue
Add a field in api response and ui to display last updated time
```
(local) mgt01 > list virtualmachinesmetrics filter=lastupdated,
{
"count": 1,
{
"lastupdated": "2021-02-10T15:43:14+0000"
}
]
}
(local) mgt01 > list virtualmachines filter=lastupdated,
{
"count": 1,
{
"lastupdated": "2021-02-10T15:43:14+0000"
}
]
}
```
=> Display last updated time for VM

api/src/main/java/com/cloud/user/AccountService.java, plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java, plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterService.java, plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterActionWorker.java, plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterStartWorker.java, plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterUpgradeWorker.java, plugins/integrations/kubernetes-service/src/main/resources/conf/k8s-control-node-add.yml, plugins/integrations/kubernetes-service/src/main/resources/conf/k8s-control-node.yml, plugins/integrations/kubernetes-service/src/main/resources/conf/k8s-node.yml, plugins/integrations/kubernetes-service/src/main/resources/script/deploy-cloudstack-secret, plugins/integrations/kubernetes-service/src/main/resources/script/deploy-provider, plugins/integrations/kubernetes-service/src/main/resources/script/upgrade-kubernetes.sh, plugins/network-elements/juniper-contrail/src/test/java/org/apache/cloudstack/network/contrail/management/MockAccountManager.java, scripts/util/create-kubernetes-binaries-iso.sh, server/src/main/java/com/cloud/user/AccountManagerImpl.java, server/src/test/java/com/cloud/user/MockAccountManagerImpl.java, test/integration/smoke/test_kubernetes_clusters.py
This PR automatically deploys the [cloudstack-kubernetes-provider](https://github.com/apache/cloudstack-kubernetes-provider) when deploying a kubernetes cluster
```
kubectl get pods -A
NAMESPACE              NAME                                         READY   STATUS    RESTARTS   AGE
kube-system            cloud-controller-manager-66d6576549-rd5zf    1/1     Running   0          44m
.......
```
=> kubernetes: Deploy kubernetes-provider when creating a cluster

ui/src/views/compute/EditVM.vue
Fixes https://github.com/apache/cloudstack/issues/5271
Prevents sending false for isdynamicallyscalable, haenable when no value is provided
=> ui: Fix sending false for isdynamicallyscalable, haenable in EditVM

plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java, server/src/main/java/com/cloud/vm/UserVmManagerImpl.java, test/integration/smoke/test_vm_life_cycle.py
Current tests (for VMware) in test_vm_life_cyle.py for migrating VM with volume only do offline migration.
Fix for format exception in `relocateVirtualMachine` method.
Ran updated `test/integration/smoke/test_vm_life_cycle.py` for a VMware env.
```
[root@pr5181-t1519-vmware-70u1-marvin marvin]# nosetests --with-xunit --xunit-file=results.xml --with-marvin --marvin-config=./pr5181-t1519-vmware-70u1-advanced-cfg -s -a tags=advanced --hypervisor=VMware tests/smoke/test_vm_life_cycle.py
==== Log Folder Path: /marvin/MarvinLogs/Aug_06_2021_20_17_52_5YIVVL. All logs will be available here ====
=== TestName: …
```
=> test/vmware: add live migratevmwithvolume test and fix

ui/src/views/infra/HostInfo.vue
Fixes #5294
Do not display host version as hypervisor version
Code in old UI was not showing host version as hypervisor version
```
dataProvider: function (args) {
$.ajax({
url: createURL("listHosts&id=" + args.context.hosts[0].id),
dataType: "json",
async: true,
success: function (json) {
var item = json.listhostsresponse.host[0];
if (item && item.outofbandmanagement) {
item.powerstate = item.outofbandmanagement.powerstate;
}
if (!item.hypervisorversion && item.details && item.details["Host.OS"]) {
item.hypervisorversion =  item.details["Host.OS"] + " " +  item.details["Host.OS.Version"];
}
```
=> ui: fix display host hypervisorversion

engine/components-api/src/main/java/com/cloud/storage/StorageManager.java, engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/VolumeOrchestrator.java, server/src/main/java/com/cloud/deploy/DeploymentPlanningManagerImpl.java, server/src/main/java/com/cloud/storage/StorageManagerImpl.java
Currently all the volumes are allocated on storage pools
based on the capacity or the algorithm selected. Sometimes
we need to deploy all volumes of particular account in a
specific storage pool and in that case its not possible.
with this change, we can specify the uuid of the preferred
storage pool, so that all volumes of the account will be
deployed in this pool
=> Global setting to select preferred storage pool

agent/conf/agent.properties, agent/src/main/java/com/cloud/agent/properties/AgentProperties.java, plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
When starting a VM on KVM, ACS sets VM's CPU topology through a calculation of CPU sockets and CPU cores per socket on VM's XML. Along the calculation, for instance, it assumes that a VM that use 12 vCPUs automatically works with 2 sockets and 6 cores, or a VM that use 16 vCPUs automatically works 4 sockets and 4 cores:
https://github.com/apache/cloudstack/blob/d6a77a72f00d01e82b536c2b9d43c00690ee96fd/plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java#L4504-L4524
This behavior is arbitrary and operators cannot choose to use it or not.
By default ([fedora - Setting KVM processor affinities](https://docs.fedoraproject.org/en-US/Fedora/13/html/Virtualization_Guide/ch25s06.html)), if we not determine the CPU topology, the hypervisor will …
=> Externalize config to enable manually setting CPU topology on KVM VM

tools/appliance/systemvmtemplate/template.json
Update version of Debian iso to 10.10.0 which is the latest available version.
Fix the template.json file to be compatible with recent version of packer, tested on `Packer v1.7.4`; file generated from `packer fix template.json` command
systemvm template build tested in our internal CI-CD. Possible this is a breaking change on non updated packer build system.
=> compatibility fix for Packer v1.7.4, update debian template to 10.10.0

server/src/main/java/com/cloud/server/ManagementServerImpl.java
This PR adds a missing command - syncStoragePool, which was reverted on main (by https://github.com/apache/cloudstack/commit/96c9c5a5e2251174da7da881ab1d0f8e1f323aac#diff-eb21dad2af4d6b0008ab4330419b8f156ac1d7176cf4ad55c246beb83296b79fL3040-R3040)
executed the command via cmk - to validate that the API exists
=> Add missing command - syncStoragePool in main branch

engine/storage/datamotion/src/main/java/org/apache/cloudstack/storage/motion/KvmNonManagedStorageDataMotionStrategy.java, engine/storage/datamotion/src/main/java/org/apache/cloudstack/storage/motion/StorageSystemDataMotionStrategy.java, engine/storage/datamotion/src/test/java/org/apache/cloudstack/storage/motion/KvmNonManagedStorageSystemDataMotionTest.java, engine/storage/datamotion/src/test/java/org/apache/cloudstack/storage/motion/StorageSystemDataMotionStrategyTest.java, plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/LibvirtStorageAdaptor.java
ACS, with KVM, cannot migrate VM's volumes from a `SharedMountPoint` to a `NFS` storage pool properly; it will not copy the volumes's template to the destination storage pool (if needed), neither update the VM's XML properly.
From a `SharedMountPoint` to a `NFS` storage pool, ACS used to interpret that it would use `localhost` as the host of the storage system; as it is a shared mount point configured in all cluster's host, as server name, but `NFS` retrieves its path from KVM, so it needs to keep the same behavior as `NFS` to `NFS`.
This PR intends to enable migration between NFS <> ISCSI (via sharedmountpoint) in KVM. 
It has been tested locally in a test lab.
1. I created a VM;
2. I configured 2 primary storages, 1 as NFS and 1 as SharedMountPoint;
3. I tried to migrate VM (with …
=> Add SharedMountPoint to KVMs supported storage pool types

api/src/main/java/org/apache/cloudstack/api/response/NetworkResponse.java, api/src/main/java/org/apache/cloudstack/api/response/UserVmResponse.java, server/src/main/java/com/cloud/api/ApiResponseHelper.java, server/src/main/java/com/cloud/api/query/dao/UserVmJoinDaoImpl.java
Display the traffic data in networks and vm api response so that we can quickly get the traffic statistics about all the vm's in that network. User can traffic data for a particular network through api as well.
Also users can monitor the traffic on individual Vm as well which was not possible earlier.
```
(local) mgt01 > list virtualmachines filter=receivedbytes,sentbytes,
{
"count": 2,
{
"receivedbytes": 187686,
"sentbytes": 99809
},
{
"receivedbytes": 189086,
"sentbytes": 90855
}
]
}
```
=> Add sent and received bytes to listNetworks and listVirtualMachines.

systemvm/debian/etc/systemd/system/baremetal-vr.service, systemvm/debian/opt/cloud/bin/baremetal-vr.py, tools/appliance/systemvmtemplate/scripts/apt_upgrade.sh, tools/appliance/systemvmtemplate/scripts/configure_systemvm_services.sh, tools/appliance/systemvmtemplate/scripts/install_systemvm_packages.sh, tools/appliance/systemvmtemplate/template.json
Debian 11 "bullseye" systemvmtemplate.
The 4.15.1 systemvmtemplate used buster-backports so likely the difference between that and Debian 11 (kernel and major packages) hopefully won't be huge.
=> systemvmtemplate: bump to Debian 11.0.0 systemvmtemplate

api/src/main/java/com/cloud/network/Site2SiteVpnConnection.java, server/src/main/java/com/cloud/network/router/VirtualNetworkApplianceManagerImpl.java, server/src/main/java/com/cloud/network/vpn/Site2SiteVpnManagerImpl.java, test/integration/smoke/test_vpc_vpn.py
Fixes https://github.com/apache/cloudstack/issues/5179
Sets the initial state of an s2svpn as connecting
```
Test Site 2 Site VPN Across redundant VPCs ... === TestName: test_01_redundant_vpc_site2site_vpn | Status : SUCCESS ===
ok
Test Site 2 Site VPN Across VPCs ... === TestName: test_01_vpc_site2site_vpn_multiple_options | Status : SUCCESS ===
ok
Test Remote Access VPN in VPC ... === TestName: test_01_vpc_remote_access_vpn | Status : SUCCESS ===
ok
Test Site 2 Site VPN Across VPCs ... === TestName: test_01_vpc_site2site_vpn | Status : SUCCESS ===
ok
```
=> s2svpn: Set initial state as Connecting

server/src/main/java/com/cloud/api/query/QueryManagerImpl.java, server/src/main/java/com/cloud/api/query/dao/TemplateJoinDaoImpl.java, server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java, server/src/main/java/com/cloud/network/vpc/VpcManagerImpl.java
For tables that use `sort_key` field, incorrect results can be returned by the list* APIs while using pagination and with the same values for `sort-key` field. (Default value for `sort_key` field remains `0`).
This change adds `id` column as secondary sort criteria in such cases.
Fixes #5316
- Created 1000 disk offerings
- Listed 500 disk offerings ids using cmk at a time for 2 pages
- Verified if there are any duplicates
- No duplicates found
[diskoffering-fix.log](https://github.com/apache/cloudstack/files/6992796/diskoffering-fix.log)
=> server: use id column as secondary sort criteria with sortKey 

ui/src/views/infra/zone/ZoneWizardAddResources.vue
Fixes https://github.com/apache/cloudstack/issues/5302
=> UI - Zone wizard - Fixes wrong add resource step with localstorageenabled

scripts/vm/network/security_group.py
In ubuntu20 the interface name contains @ synbol and
because of that even the iptable rules for brdige name
contains this symbol which causes ping issues.
Remove the @ symbol from iptable rule to fix the issue
This the output from ubuntu16
```
eth0.2999
```
And iptable rule is
```
-A BF-breth0-2999 -m physdev --physdev-out eth0.2999 --physdev-is-bridged -j ACCEPT
```
This is the output from ubuntu20
```
ens3.2999@ens3
```
And iptable rule is
```
-A BF-brens3-2999 -m physdev --physdev-out ens3.2999@ens3 --physdev-is-bridged -j ACCEPT
```
After the fix, below is the output from ubuntu20
```
ens3.1989@ens3
```
iptable rule is
```
-A BF-brens3-1989 -m physdev --physdev-out ens3.1989 --physdev-is-bridged -j ACCEPT
```
=> Fix iptable rules in ubuntu 20 for bridge name

api/src/main/java/com/cloud/storage/VolumeApiService.java, api/src/main/java/org/apache/cloudstack/api/command/user/volume/UpdateVolumeCmd.java, server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java, ui/src/config/section/storage.js
Provide an api support to update volume name by all users
UI changes ported from https://github.com/apache/cloudstack-primate/pull/920
=> Allow users to update volume name

test/integration/smoke/test_outofbandmanagement.py
This PR fixes the travis test failure noticed on the main branch - 
```
ERROR: test suite for <class 'integration.smoke.test_outofbandmanagement.TestOutOfBandManagement'>
File "/home/travis/.local/lib/python3.6/site-packages/nose/suite.py", line 210, in run
self.setUp()
File "/home/travis/.local/lib/python3.6/site-packages/nose/suite.py", line 293, in setUp
self.setupContext(ancestor)
File "/home/travis/.local/lib/python3.6/site-packages/nose/suite.py", line 316, in setupContext
try_run(context, names)
File "/home/travis/.local/lib/python3.6/site-packages/nose/util.py", line 471, in try_run
return func()
File "/home/travis/build/apache/cloudstack/test/integration/smoke/test_outofbandma …
```
=> test: Fix travis failure - test_outofbandmanagement.py

scripts/vm/network/security_group.py
Sometimes the chain reference count is 0 and in that case
proper iptables rules are not applied. Because of this, ping fails.
So check the reference count for the main chain and as well as
-IN and -OUT chain as well
**Before the fix**
**Iptable rules on NON working node**
```
BF-brbond0-94  all  --  0.0.0.0/0            0.0.0.0/0            PHYSDEV match --physdev-is-bridged
BF-brbond0-94  all  --  0.0.0.0/0            0.0.0.0/0            PHYSDEV match --physdev-is-bridged
Chain BF-brbond0-94 (2 references)
Chain BF-brbond0-94-IN (0 references) <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Chain BF-brbond0-94-OUT (0 references)
```
```
:BF-brbond0-94 - [0:0]
:BF-brbond0-94-IN - [0:0]
:BF-brbond0-94-OUT - [0:0]
-A FORWARD -o brbond0-94 -m physdev --physdev-is-bridged -j BF-brbond0-94
-A …
```
=> Fix iptable rules when chain reference count is 0

systemvm/debian/etc/cron.daily/clean_cloud_processed_files
This PR fixes #3757 
This adds a daily cron job to clean up files in /var/cache/cloud/processed older than 180 days, 179 days, ... until the disk space usage does not exceed threshold (80%). the logs in last 5 days will not be cleaned.
=> vr: cleanup files in /var/cache/cloud/processed every day

server/src/main/java/org/apache/cloudstack/vm/UnmanagedVMsManagerImpl.java
In the past, the broadcast uri was changed to an "i" for isolated, as well as c for community. 
see https://github.com/apache/cloudstack/pull/4040
However, the ingest logic has not been adjusted, which means it's no longer possible to ingest a VM with a community 
network.
For this reason I've adapted the condition and add correct pvlan type. 
**All existing community network broadcast uri's in cloudstack before 4.15.1.0 must be updated manually or new created 
because all community networks contains the letter i in the broadcast uri.**
Tested in own VMware env. 
```
import unmanagedinstance clusterid=b6dc2477-f3ec-43e2-a405-3605e29aaa42 name=ubuvtst6 displayname=ubuvtst6 projectid=fc61ebe1-6290-4100-98ca-18fb3d950af2 serviceofferingid=15b5681f-08c2-417a-a9ba-4480c229ec03 
{
"accountid": …
```
=> adapt condition to use the correct letter for pvlan types

engine/storage/datamotion/src/main/java/org/apache/cloudstack/storage/motion/StorageSystemDataMotionStrategy.java, engine/storage/datamotion/src/test/java/org/apache/cloudstack/storage/motion/StorageSystemDataMotionStrategyTest.java
In ACS, primary storages have two scopes, `ZONE` and `CLUSTER`. In KVM, when we are migrating a volume between any source storage to a non managed NFS storage, ACS validates if the destination storage is `CLUSTER` scoped and cancels the migration if it isn't. However, these scopes are just logical limitations created by ACS, they don't affect KVM.
This PR intends to remove this logical limitation created by ACS.
I added unit tests and tested locally, in a test lab.
1. I created a VM;
2. I tried to migrate a volume to a `ZONE` scoped storage;
3. Before applying this patch, it threw an exception, after applying, it was migrated;
=> Remove storage scope validation on KVM live migration

ui/src/config/section/compute.js
Fixes https://github.com/apache/cloudstack/issues/5340
=> UI - VM - hide button take vm volume snapshot for Destroyed state

api/src/main/java/org/apache/cloudstack/api/command/admin/host/AddHostCmd.java, server/src/main/java/com/cloud/api/dispatch/ParamProcessWorker.java, server/src/main/java/com/cloud/resource/ResourceManagerImpl.java
Fixes: https://github.com/apache/cloudstack/issues/5332
This PR attempts to bypass the empty string check added in ParamProcessorValidator - for username and password, so that in case of vmware, it doesn't fail during addition of hosts (where username and password is obtained from cluster details)
Added a host to a VMware cluster via UI without any issues.
=> Bypass empty string check for username and password

ui/src/config/section/infra/primaryStorages.js, ui/src/config/section/infra/secondaryStorages.js, ui/src/views/AutogenView.vue
Fixes https://github.com/apache/cloudstack/issues/5344
=> UI - Add storage name to delete primary/secondary storage dialog

scripts/vm/network/security_group.py, test/integration/component/test_multiple_nic_support.py
Fixes fetching the bridge name for c8 / suse where the result of virsh domlist contains leading spaces
Used only in component tests, so not a functionality break
```
vnet6       bridge   cloudbr1   virtio   02:00:12:b0:00:01    <- notice the leading space
bridge   <- Displays the second field
```
```
vnet6       bridge   cloudbr1   virtio   02:00:12:b0:00:01    <- notice the leading space
cloudbr1    <- Displays the bridge name
```
=> Fix security_groups for c8/suse

server/src/main/java/com/cloud/server/StatsCollector.java
CloudStack has a feature to keep and increment the VM metrics in memory. This PR intends to externalize one new configuration, `vm.stats.increment.metrics.in.memory` to allow operators to choose if they want to increment VM metrics or not.
KVM hypervisor:
- I created a VM in CloudStack and maked Network and Disk I/O operations
- I changed the value of configuration `vm.stats.increment.metrics.in.memory`
- I checked that the metrics weren't incrementing in memory
=> Externalize vm stats increment in memory

server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
This PR fixes #4902 
The testing results with this change:
- When destroy VM without expunge and when no data disk is selected for deletion
destroy vm: VM is stopped, data disk is detached from vm (in Ready state)
recover vm: vm is ready only with root disk.
- When destroy VM without expunge and when one or more data disks are selected for deletion
destroy vm: VM is stopped, Data disks marked for deletion are detached and in Destroy state . the remaining disks are detached from VM
recover vm: vm is ready only with root disk.
recover data disk in Destroy: volume is ready, and not attached to vm.
- When destroy VM with expunge and when no data disk is selected for deletion
VM is destroyed and expunged completely.
data disks are detached from vm.
- When destroy VM with expunge and few data …
=> server: detach data disks before destroying vms

server/src/main/java/org/apache/cloudstack/diagnostics/DiagnosticsServiceImpl.java
On trying to get the diagnostic data from SSVM, we face the following issue:
```
Copying /root/diagnostics_files_20210827-051515.zip from 10.0.38.15 to secondary store NFS://10.0.32.4/acs/secondary/ref-trl-1680-v-Mu20-pearl-dsilva/ref-trl-1680-v-Mu20-pearl-dsilva-sec1
2021-08-27 05:15:15,280 ERROR [o.a.c.d.DiagnosticsServiceImpl] (API-Job-Executor-27:ctx-ec0ca00b job-33 ctx-43bee1c6) (logid:8d3dba6c) Exception caught during scp from 10.0.38.15 to secondary store /var/lib/cloudstack/mnt/32987160773173.3029c5e3/diagnostics: 
java.io.FileNotFoundException: /var/cloudstack/management/.ssh/id_rsa (No such file or directory)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
at …
```
=> ubuntu: Fix failure to scp diagnostic data file from SSVM

server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
This PR fixes #5347 
Steps to reproduce the issue on KVM
(1) create a vm, and stop it
(2) stop all cloudstack-agent
(3) expunge the vm. vm is removed, but root volume is in 'Destroy' state.
(4) destroy/expunge the volume, fails.
(5) recover the volume, the volume is restored to ROOT disk and attached the removed vm, therefore we cannot attach to any other vms.
=> server: allow destroy/recover volumes which are attached to removed vms

ui/src/components/page/GlobalLayout.vue, ui/src/views/AutogenView.vue
Fixes the action bar in place to prevent scrolling during multi-select 
Fixes https://github.com/apache/cloudstack/issues/5281
Just adds an a-affix and nests elements inside it (since the diff makes it look like a mess)
=> ui: Fix action bar in place

plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageProcessor.java, vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/HypervisorHostHelper.java, vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/VirtualMachineMO.java
Worker VM tags are missed for few cloned VMs in VMware, and so these are skipped when tracking / cleaning up of Worker VMs.  Adding proper Worker VM tags to these VMs would make them trackable from CloudStack.
This PR updates the (missed) Worker VM tags for the cloned VMs (in VMware) when creating template from volume, and exporting volume to secondary storage.
Snapshot operation (for detached disk) tasks in vCenter =>
Worker VM to attach disk =>
Cloned VM to export disk to secondary storage =>
Manually verified the worker VM tags set in the cloned VMs (from vCenter) while performing the following operations.
- Take volume snapshot
- Create template from volume
=> [VMware] Added Worker VM tags for few cloned VMs while performing some volume operations.

plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java, vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/VirtualMachineMO.java
This PR fixes the deploy / start VM issue in VMware, with deploy-as-is template (OVA) having multiple controller types.
Fixes: #5111 
Manually tested deploy / start using OVA template having multiple controller types.
=> [VMware] Start VM with deploy-as-is template having multiple controller types

server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
When a VM is in the Stopped state and the host for it is not found then the server skips sending AttachCommand to the hypervisor. This creates issue with the volume operations if done immediately (without starting the VM).
Change tries to improve this case and finds a suitable host in the VM's cluster when the volume is not in a HOST scope pool.
Fixes #5372 
Using cmk on VMware env with multiple clusters:
```
(localcloud) SBCM5> > list clusters filter=id,name,hypervisortype,
{
"cluster": [
{
"hypervisortype": "VMware",
"id": "2525592f-d07c-40bc-84a3-5bfa218ba67d",
"name": "p1-c1"
},
{
"hypervisortype": "VMware",
"id": "fce17f98-abd2-4571-a875-97d787119d9f",
"name": "10.0.33.157/Trillian/p1-c2"
}
],
"count": 2
}
(localcloud) SBCM5> > list storagepools filter=id,name,clusterid,clustername
{ …
```
=> server: improve attach volume in specific cases

engine/schema/src/main/java/com/cloud/upgrade/DatabaseUpgradeChecker.java
Introduce same Db upgrade path from both 4.15.1/4.15.2 to 4.16.0
=> engine/schema: Use same upgrade path as 4.15.1-4.16.0 as for 4.15.2

engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/VolumeOrchestrator.java, engine/schema/src/main/java/org/apache/cloudstack/storage/datastore/db/SnapshotDataStoreDao.java, engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/snapshot/SnapshotDataFactoryImpl.java, engine/storage/src/main/java/org/apache/cloudstack/storage/image/db/SnapshotDataStoreDaoImpl.java, plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java, plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/LibvirtStorageAdaptor.java, plugins/storage/volume/default/src/main/java/org/apache/cloudstack/storage/datastore/driver/CloudStackPrimaryDataStoreDriverImpl.java
Fixes #4433 
- `snapshot.backup.to.secondary=false`
- Create 2 or more snapshots on Ceph/NFS
- Create volume/template from a snapshot. The snapshot first is copied to secondary storage
- Create volume/template from the second snapshot. The snapshot is not copied to secondary because the snapshot info is retrieved with the wrong SQL query. Operation fails.
The problem appears on Ceph/NFS but it probably affects other storage plugins.
Bypassing secondary storage is supported only for Ceph primary storage, but it didn't cover the functionality to create volumes from snapshots which are kept only on Ceph.
With this fix, if you create snapshots only on NFS and try to create volume/template from a snapshot first, the snapshots are copied to secondary storage. For Ceph, the snapshot will be …
=> Fix of creating volumes from snapshots without backup to secondary storage

plugins/hypervisors/xenserver/pom.xml, plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/discoverer/XcpServerDiscoverer.java, plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/CitrixResourceBase.java, plugins/hypervisors/xenserver/src/test/java/com/cloud/hypervisor/xenserver/discoverer/XcpServerDiscovererTest.java, server/src/main/java/com/cloud/agent/manager/allocator/impl/FirstFitAllocator.java, ui/src/views/compute/DeployVM.vue
Allows selecting boot type and boot mode for Xenserver/XCP-ng in UI.
XCP-ng 8.2 allows UEFI boot type for guest VMs.
Changes allow setting and updating the host's UEFI capability in DB while adding or re-connection. It allows honoring VM details while orchestrating VM start on XCP-ng hypervisor
Addresses #5204 
- Deployed ACS 4.15.1 env with 2x XCP-ng 8.1 hosts
- Deployed Windows 10, Windows Server 2019, and Windows Server 2008 R2 VMs
- Stopped VMs to upgrade XCP-ng hosts.
- Upgraded ACS and upgraded XCP-ng hosts to 8.2
- Started VMs. <- VM started fine (had to change guest_os for Windows Server 2008 R2 VM) 
Also, tested Windows Server 2019 deployment with UEFI boot type:
```
(localcloud) SBCM5> > list virtualmachines id=a5187ead-dba6-4a27-831d-4edd8cf6f9d8 …
```
=> xcp-ng: allow passing vm boot options

plugins/ca/root-ca/src/main/java/org/apache/cloudstack/ca/provider/RootCACustomTrustManager.java, plugins/ca/root-ca/src/main/java/org/apache/cloudstack/ca/provider/RootCAProvider.java, plugins/ca/root-ca/src/test/java/org/apache/cloudstack/ca/provider/RootCACustomTrustManagerTest.java, plugins/ca/root-ca/src/test/java/org/apache/cloudstack/ca/provider/RootCAProviderTest.java
This PR allows the management servers to renew certificates issued to hosts, even if ca.plugin.root.auth.strictness is false.  There is already a global setting named ca.framework.cert.automatic.renewal that should be controlling the certificate renewals.  However, ca.plugin.root.auth.strictness currently circumvents that setting.
The ca.plugin.root.auth.strictness setting is checked early in the client certificate checking method and exits the method without adding the certificate to the management server's in-memory certificate map if strictness is false.  The certificate renewal process (if enabled with ca.framework.cert.automatic.renewal) reads that in-memory certificate map to determine what certs it could renew.  Those two settings shouldn't be so closely related.
- [X ] Minor
We've …
=> Allow host cert renewals even if client auth strictness is false

ui/src/components/view/InfoCard.vue, ui/src/views/compute/DeployVM.vue, ui/src/views/compute/ScaleVM.vue, ui/src/views/compute/wizard/ComputeSelection.vue
Fixes https://github.com/apache/cloudstack/issues/5391
=> UI - Scale VM - Fix compute offering selection not working

plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/manager/VmwareManagerImpl.java
For VMware, systemvm.iso is copied from MS to secondary store. Current server checks if the desired file is present on the secondary store or not. If it is not present ISO is copied.
This change adds a check for checksum for source and destination ISO which would allow copying new ISO if there is a mismatch.
Useful in case when file is corrupted in secondary store or new systemvm.iso is generated for dev environment.
=> vmware: check checksum before copying systemvm ISO to decide if it is needed

engine/schema/src/main/java/org/apache/cloudstack/storage/datastore/db/TemplateDataStoreDao.java, engine/storage/src/main/java/org/apache/cloudstack/storage/image/db/TemplateDataStoreDaoImpl.java, server/src/main/java/com/cloud/api/query/dao/TemplateJoinDaoImpl.java
This PR filters images stores belonging to a zone while listing the download details of the template in a specific zone
```
(localcloud) 🐱 > list templates id=ef78027a-06ed-11ec-b12a-5254009b8de5 (CentOS 5.5(64-bit) no GUI (KVM)) templatefilter=all filter=name,zonename,zoneid,downloaddetails
{
"count": 2,
"template": [
{
"downloaddetails": [
{
"datastore": "nfs://172.20.0.1/export/testing/qa1-testzone415-e0bb22b0-kvm/sec1",  <--- store of zone1
"downloadPercent": "100",
"downloadState": "DOWNLOADED"
},
{
"datastore": "nfs://172.20.0.1/export/testing/qa1-testzone415-e0bb22b0-kvm/sec2",  <--- store of zone2
"downloadPercent": "100",
"downloadState": "DOWNLOAD_IN_PROGRESS"
}
],
"name": "CentOS 5.5(64-bit) no GUI (KVM)",
"zoneid": "acdaf7ed-453f-472d-be42-113f09752667",
"zonename": "z1"
},
{ …
```
=> api: List details of template download state for stores corresponding to a zone

systemvm/debian/opt/cloud/bin/configure.py
according to https://wiki.strongswan.org/projects/strongswan/wiki/Ipsecsecrets , the ID selector is optional.
Not sure if this PR fixes #4281
=> vr: ipsec/l2tp vpn secret with no ID selectors

systemvm/debian/opt/cloud/bin/configure.py
This PR...
Fixes #5365
When snat is configured on a vm in a subnet then the source
ip should be taken from the same subnet rather than from
random other subnet.
Output before the fix and steps to reproduce are mentioned in the issue
Output after the fix
```
Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination
SNAT       all  --  10.10.10.0/24        10.10.10.154         to:10.10.10.254
SNAT       all  --  10.10.10.154         0.0.0.0/0            to:10.135.122.131
SNAT       all  --  0.0.0.0/0            0.0.0.0/0            to:10.135.122.128
SNAT       all  --  0.0.0.0/0            0.0.0.0/0            to:10.135.122.131
```
=> Use source IP from same subnet for snat

server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
This PR fixes the issue that server capacity check is skipped, when start or migrate a vm with specified hostid.
=======UPDATE 2021-09-01===========
We have decided to only add capacity check. the other checks (host state, affinity group, etc) are not added.
=> server: check server capacity when start/deploy a vm

engine/schema/src/main/java/com/cloud/service/dao/ServiceOfferingDetailsDao.java, engine/schema/src/main/java/com/cloud/service/dao/ServiceOfferingDetailsDaoImpl.java, engine/schema/src/main/java/org/apache/cloudstack/resourcedetail/ResourceDetailsDao.java, engine/schema/src/main/java/org/apache/cloudstack/resourcedetail/ResourceDetailsDaoBase.java, engine/schema/src/main/java/org/apache/cloudstack/resourcedetail/dao/DiskOfferingDetailsDao.java, engine/schema/src/main/java/org/apache/cloudstack/resourcedetail/dao/DiskOfferingDetailsDaoImpl.java, server/src/main/java/com/cloud/api/query/QueryManagerImpl.java, server/src/main/java/com/cloud/api/query/dao/ServiceOfferingJoinDaoImpl.java
Fixes https://github.com/apache/cloudstack/issues/5290
Fixes incorrect count returned in listServiceOfferings and listDiskOfferings caused by filtering records in the manager rather than directly in the database
Previously, would give the wrong count
```
"count": 7,
```
Domains : `/dom1/(sub1, sub2, sub3)`
Calling listOfferings as a dom1 user
```
(dom1) 🐱 > list serviceofferings filter=name,domain listall=true
{
"count": 4,
{
"name": "Small Instance" <- common
},
{
"name": "Medium Instance" <- common
},
{
"name": "root-o1" <- parent
},
{
"domain": "dom1",
"name": "dom1-o1" <- mine
}
]
}
```
Calling listOfferings as a dom1/sub1 user
```
{
"count": 6,
{
"name": "Small Instance" <- common
},
{
"name": "Medium Instance"
},
{ …
```
=> Filter disk / service offerings by domain at DB level

usage/src/main/java/com/cloud/usage/parser/BackupUsageParser.java
when creat usage record for backup usages in a period, we need to check if vm offering is changed. if vm offering is changed, create a new cloud usage record, otherwise update existing usage record.
This PR fixes #4982
=> usage: create backup usage record for vmId-offeringId pair

engine/schema/src/main/resources/META-INF/db/schema-41500to41510.sql, engine/schema/src/main/resources/META-INF/db/schema-41510to41520.sql, ui/src/store/getters.js, ui/src/store/modules/user.js, ui/src/views/AutogenView.vue
Fixes https://github.com/apache/cloudstack/issues/5338
=> ui: Honour default.ui.page.size

engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/DataMigrationUtility.java, server/src/main/java/com/cloud/api/query/dao/TemplateJoinDaoImpl.java
This PR allows migration of public templates that are created from snapshots / volumes. Data migration across secondary stores initially excluded all public templates on the pretext that public templates are automatically synced when a new image store is added; however, this assumption isn't true for templates marked as "public" when created from snapshots / volumes. Such templates can be identified if their url is null
Initial Behavior:
1. Created a snapshot and then created a template from that snapshot and marked the template as public
2. Added another image store
3. Validated that the template doesn't get synced
4. Attempted migration of resources from one store to another - all public templates including the one created from the snapshot is left behind
New Behavior:
```
MariaDB …
```
=> Allow public templates with no url to be migrated

core/src/main/java/com/cloud/storage/JavaStorageLayer.java, core/src/main/java/com/cloud/storage/StorageLayer.java
I think there is a potential securiry issuse in createUniqDir#JavaStorageLayer
public File createUniqDir() {
String dirName = System.getProperty("java.io.tmpdir");
if (dirName != null) {
File dir = new File(dirName);
if (dir.exists()) {
String uniqDirName = dir.getAbsolutePath() + File.separator + UUID.randomUUID().toString();
if (mkdir(uniqDirName)) {
return new File(uniqDirName);
}
}
}
return null;
}
So if a user do not specify the "java.io.tmpdir",  we will use the default tmp dir "/tmp" whose mode is 777. Even users specify the "java.io.tmpdir", they may also forget to set the file mode as 700, hence the tmp dir is still worldreadable.  Our code then create create UniqDir  in tmp dir, and it is also worldreadable.
createUniqDir will be called by swiftUploadMetadataFile and …
=> CLOUDSTACK-10436:remind users to use correct permission for tmp dir and fixed an NPE

api/src/main/java/org/apache/cloudstack/api/command/user/vm/DeployVMCmd.java, ui/src/views/compute/DeployVM.vue
Fixes NPE when UEFI is used for boot mode but no boot type is passed.
```
ERROR [c.c.a.ApiServer] (qtp661543645-300:ctx-3e8b622e ctx-0499e8d9) (logid:980273bb) unhandled exception executing api command: [Ljava.lang.String;@69003076
at org.apache.cloudstack.api.command.user.vm.DeployVMCmd.getDetails(DeployVMCmd.java:296)
at com.cloud.vm.UserVmManagerImpl.createVirtualMachine(UserVmManagerImpl.java:5253)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at …
```
=> api, ui: fix NPE with deployVirtualMachine when null boottype

ui/src/components/header/HeaderNotice.vue, ui/src/utils/plugins.js, ui/src/views/AutogenView.vue, ui/src/views/compute/StartVirtualMachine.vue
Add router links to the notification list - which aids in traversing to the respective resource in case of failed jobs/ operations. This was added as part of #5034; however, during recent refactor of the UI around header notices, this minor enhancement was reverted. This PR also brings back the old behavior of showing the error description in the notification list so that one may not have to filter through events to see the reason for a failure
=> UI: Add router links to notifications and show error description

tools/marvin/marvin/cloudstackException.py
Fixes #5203
Tested marvin logs with and without changes while making ACS throw exception for an async API
```
[root@pr5201-t1929-kvm-centos7-marvin marvin]# nosetests --with-xunit --xunit-file=results.xml --with-marvin --marvin-config=./pr5201-t1929-kvm-centos7-advanced-cfg -s -a tags=advanced --hypervisor=KVM tests/smoke/test_deploy_vm_iso.py
==== Log Folder Path: /marvin/MarvinLogs/Sep_02_2021_08_56_13_EU0IU4 All logs will be available here ====
=== TestName: test_deploy_vm_from_iso | Status : EXCEPTION ===
=== Final results are now copied to: /marvin//MarvinLogs/test_deploy_vm_iso_AWJQLB === …
```
=> marvin: fix exception logging

.travis.yml
PR #5103 - https://github.com/apache/cloudstack/pull/5103/files#diff-294d96c6f789cf559c7c0b8f22ff7cb20dafba5477be4ed13ca1456c4c4e3679 renamed a test module from test_host_annotations to test_annotations leading to travis test(job 2) failure, this PR updates travis config
```
Failure: ImportError (No module named 'test_host_annotations') ... === TestName: Failure: | Status : EXCEPTION ===
ERROR
======================================================================
ERROR: Failure: ImportError (No module named 'test_host_annotations')
File "/home/travis/.local/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest
raise self.exc_val.with_traceback(self.tb)
File …
```
=> travis: Fix failing test due to change in test name

engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/VolumeOrchestrator.java
The recent changes of the main branch enable the global setting to select preferred storage pool and apply its implementation in the VolumeOrchestrator.java in the findStoragePool method
```
Optional<StoragePool> storagePool = getPreferredStoragePool(poolList, vm);
```
But the usage of it has a potential risk of null pointer exception when the vm parameter in findStoragePool is null, current implementation of getPreferredStoragePool doesn't handle such a condition and directly assumes that VM is never null.
```
String accountStoragePoolUuid = StorageManager.PreferredStoragePool.valueIn(vm.getAccountId());
```
But in one of the implementations in the same class where the findStoragePool is called, it passes vm variable explicitly as null 
*interface*
```
public VolumeInfo …
```
=> Fix potential NullPointerException in findStoragePool (VolumeOrchestrator)

server/src/main/java/com/cloud/storage/StorageManagerImpl.java
Currenly, getStoragePoolUsedStats method fetch all pools
independed if a pool have a parent. Therefore as soon
as a datastore cluster is used, the cluster and the storages it contains are calculated together
The change fetch all storages without cluster and all datastore cluster
tested in own env.
=> Prevent double counting storage pools

ui/src/components/page/GlobalLayout.vue, ui/src/components/view/Setting.vue
This PR displays the Settings widget only in development mode 
After the fix in production:
After the fix in development:
=> Hide settings button if not on development mode

ui/src/views/infra/network/IpRangesTabManagement.vue
Add management IP range form shows the same pod multiple times when the pod has multiple IP ranges.
This PR fixes the behaviour.
Before:
After:
=> ui: fix add management ip range form

api/src/main/java/org/apache/cloudstack/api/command/user/config/ListCapabilitiesCmd.java, api/src/main/java/org/apache/cloudstack/api/response/CapabilitiesResponse.java, server/src/main/java/com/cloud/server/ManagementServerImpl.java, ui/src/store/modules/user.js
listConfigurations is not available for all roles and therefore not fit to use in UI for a generic functionality.
This PR makes default ui pagesize a part for listCapabilities API response to make it available for UI across different role accounts.
=> api, ui: return default ui pagesize as part of capability response

ui/src/views/network/LoadBalancing.vue, ui/src/views/network/PortForwarding.vue
Removes the double footer in the LB and PF forms
=> ui: Remove double footer

utils/pom.xml
The same is declared at lines 128-131 in utils/pom.xml. This fixes mvn build warning.
=> utils: remove duplicate commons-lang3 dependency

ui/src/views/compute/wizard/NetworkSelection.vue
Form tries to find newly created network which belongs to the same account, created in last 30s and was not present in the networks list before opening create network dialog.
Before:
After:
=> ui: select newly created network in deploy vm

ui/src/views/compute/ScaleVM.vue
This PR fixes the failure noticed during scale VM operation when a custom offering is selected. It observed that when cpuNumber / cpu speed is provided for the selected custom compute offering, it fails to pass the args properly
Successfully scaled VM - args properly passed:
=> ui: Fix Scale VM failure - missing args when custom compute offering is selected

ui/src/views/dashboard/UsageDashboard.vue
This PR fixes https://github.com/apache/cloudstack/issues/5440 - where we notice that when logged in with a User role, and on swapping between project and default view, the resource count details on the Usage dashboard isn't properly updated
Followed the steps mentioned in https://github.com/apache/cloudstack/issues/5440 - and observed the usage dashboard properly updated.
=> ui: Refresh Usage dashboard when swapping between Project and Default view

api/src/main/java/org/apache/cloudstack/api/ApiConstants.java, api/src/main/java/org/apache/cloudstack/api/response/IpRangeResponse.java, api/src/main/java/org/apache/cloudstack/api/response/PodResponse.java, server/src/main/java/com/cloud/api/ApiResponseHelper.java, ui/src/views/infra/network/IpRangesTabManagement.vue
This PR updates the pod response, grouped the parameters: startip, endip, vlanid, forsystemvms as ip range response and added to ipranges parameter (a new parameter to hold the list of IP range details).
Manually tested the updated API response.
Before changes:
```
(cloudcmk) > list pods
{
"count": 1,
"pod": [
{
"allocationstate": "Enabled",
"endip": [
"10.0.36.60",
"10.0.36.69"
],
"forsystemvms": [
"0",
"1"
],
"gateway": "10.0.32.1",
"id": "43ffd982-8942-4c9a-88f3-002dc7f5d411",
"name": "Pod1",
"netmask": "255.255.240.0",
"startip": [
"10.0.36.41",
"10.0.36.67"
],
"vlanid": [
"vlan://untagged",
"vlan://untagged"
],
"zoneid": "be8e7d3e-2f57-433d-9c93-208949e2ec1d",
"zonename": "ref-trl-1773-k-M7-suresh-anaparti"
}
]
}
```
After changes: New parameter ipranges …
=> Updated pod response, grouped the parameters: "startip, endip, vlanid, forsystemvms" as ip range response and added to ipranges parameter.

ui/src/views/network/IngressEgressRuleConfigure.vue, ui/src/views/network/LoadBalancing.vue
This PR fixes alignment issue that occurs when an LB rule is created without specifying a protocol (which can be done via cmk)
Prior fix:
Post Fix:
=> ui: Fix Load Balancer Rules alignment issue

server/src/main/java/com/cloud/network/vpn/Site2SiteVpnManagerImpl.java
If the vpn connection is in pending state then we cant restart the
vpn connection. So manually set the state to disconnected and then
try to restart the vpn connection
This pr is needed along with https://github.com/apache/cloudstack/pull/4429/files
=> Persist vpn connection state before restarting

api/src/main/java/com/cloud/agent/api/storage/OVFHelper.java, core/src/main/java/com/cloud/storage/template/OVAProcessor.java, engine/storage/src/main/java/org/apache/cloudstack/storage/image/deployasis/DeployAsIsHelperImpl.java, engine/storage/src/test/java/org/apache/cloudstack/storage/image/deployasis/DeployAsIsHelperImplTest.java
This PR adds a "ovf" prefix check on Vmware template OVF files.
Fixes: #5415 
- Export template from Vmware, verify sections contain the prefix: "ovf", examples:
````
<ovf:File ovf:href="vwlc_harddisk.vmdk" ovf:id="file1" ovf:size="1380352" />
<ovf:File ovf:href="README-OVF.txt" ovf:id="readme-ovf" ovf:size="8740" />
<ovf:File ovf:href="C9800-CL-universalk9.17.03.03-vga.iso" ovf:id="C9800-CL-universalk9.17.03.03-vga.iso" ovf:size="1081249792" />
</ovf:References>
<ovf:DiskSection>
<ovf:Info>Virtual disk information</ovf:Info>
<ovf:Disk ovf:capacity="16" ovf:capacityAllocationUnits="byte * 2^30" ovf:diskId="vmdisk1" ovf:fileRef="file1" ovf:format="http://www.vmware.com/interfaces/specifications/vmdk.html#streamOptimized" ovf:populatedSize="293011456" />
</ovf:DiskSection> …
```
=> [Vmware] Fix for ovf templates with prefix

server/src/main/java/com/cloud/server/ManagementServerImpl.java
Currently if we try to list vlan ip range by passing
domainid then it lists for all domain. Make sure that
it lists only for that domain
Before the changes
```
(local) 🐱 > list vlanipranges domainid=4aa4c-f694-45c0-8844-8d9a129
{
"count": 14,
"vlaniprange": [
```
After the changes
```
(local) 🐱 > list vlanipranges domainid=4560c-f694-45c0-8844-8d94129
{
"count": 1,
"vlaniprange": [
```
=> Display vlan ip range for specified domainid

ui/src/views/dashboard/UsageDashboard.vue
This PR fixes: https://github.com/apache/cloudstack/issues/5475 - wherein, when a user / domain admin logs out, they see an ever increasing no. of requests being sent to the MS - rendering the browser unresponsive.
Caused by: https://github.com/apache/cloudstack/pull/5447 
log in as different user types and no issues noticed
=> UI: Fixes issue during logout as user / domain admin

client/conf/server.properties.in, client/src/main/java/org/apache/cloudstack/ServerDaemon.java, utils/src/main/java/com/cloud/utils/crypt/EncryptionSecretKeyChecker.java, utils/src/main/java/com/cloud/utils/db/DbProperties.java, utils/src/main/java/com/cloud/utils/server/ServerProperties.java, utils/src/test/java/com/cloud/utils/crypto/EncryptionSecretKeyCheckerTest.java
This PR addresses: https://github.com/apache/cloudstack/issues/4293 - facilitates a means to use encrypted password for `https.keystore.password` in `server.properties`
Based On (temporary) logs added:
With following values in server.properties:
```
https.keystore=/etc/cloudstack/management/cloud.jks
https.keystore.password=vmops.com
```
On restarting MS - following logs were seen:
```
2021-09-16 09:47:56,957 INFO  [o.a.c.ServerDaemon] (main:null) (logid:) Server configuration file found: /etc/cloudstack/management/server.properties
2021-09-16 09:47:56,969 DEBUG [c.c.u.c.EncryptionSecretKeyChecker] (main:null) (logid:) Encryption Type: null
2021-09-16 09:47:56,973 INFO  [o.a.c.ServerDaemon] (main:null) (logid:) https keystore password: vmops.com
```
server.properties content for keystore …
=> server: Add support to encrypt https.keystore.password in server.properties

engine/storage/src/main/java/org/apache/cloudstack/storage/image/db/TemplateDataStoreDaoImpl.java
This PR fixes listTemplates' API response when no stores are present. Currenty, when there are no secondary stores, listing templates leads to a DB exception.
Prior Fix:
```
(localcloud) SBCM5> > list templates templatefilter=all filter=id,downloaddetails
🙈 Error: (HTTP 530, error code 4250) DB Exception on: com.mysql.cj.jdbc.ClientPreparedStatement: SELECT template_store_ref.id, template_store_ref.store_id, template_store_ref.template_id, template_store_ref.store_role, template_store_ref.created, template_store_ref.last_updated, template_store_ref.download_pct, template_store_ref.size, template_store_ref.physical_size, template_store_ref.download_state, template_store_ref.local_path, template_store_ref.error_str, template_store_ref.job_id, template_store_ref.install_path, …
```
=> api: Fix list templates when no secondary stores present

api/src/main/java/com/cloud/configuration/ConfigurationService.java, api/src/main/java/com/cloud/event/EventTypes.java, api/src/main/java/org/apache/cloudstack/api/ApiConstants.java, api/src/main/java/org/apache/cloudstack/api/command/admin/network/UpdatePodManagementNetworkIpRangeCmd.java, api/src/org/apache/cloudstack/api/command/admin/network/UpdatePodManagementNetworkIpRangeCmd.java, engine/schema/src/main/java/com/cloud/dc/dao/DataCenterIpAddressDao.java, engine/schema/src/main/java/com/cloud/dc/dao/DataCenterIpAddressDaoImpl.java, server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java, server/src/main/java/com/cloud/server/ManagementServerImpl.java, server/src/test/java/com/cloud/vpc/MockConfigurationManagerImpl.java
This PR introduces a new API endpoint to update pod management network IP range.
Currently, pod management IP range can only be expanded under the same subnet. Editing the current pod IP management range is a challenge, especially as the list of IP ranges is greater than one. The purpose of this feature is to allow ADMINS to be able to update size of IP range of management pod, upwards or downwards.
This PR extends from #4010
- Updatepodmanagementnetworkiprange will update already existing IP ranges. Will not create a new IP range.
- Will increase/reduce available IPs within the range.
- PodID/Currentstartip/CurrentendIp are mandatory fields. Newstartip and Newendip are optional fields and one of them should be specified. When anyone is left blank, Newstartip will be set to Currentstartip …
=> New API endpoint to update pod management network IP range

setup/bindir/cloud-set-guest-sshkey-password-userdata-configdrive.in
This PR adds a bash script file that manages sshkey and password from userdata server and configdrive sources
At first, the script tries to find a configdrive CD, if it is found, it will mount the CD and search for ssh key and password.
If both ssh key and password were found, the script will try to set ssh key and password, else it will search for the userdata server.
Finding a userdata server (DHCP server) is a little bit tricky.
First of all the script tries to find the default gateway, so it can determine the default nic. It is important to find default nic because CloudStack only provides passwords from default nic.
Script test existence of different commands to figure out default gateway: ip, netstat, route (GNU & BSD)
If no default gateway was found, the script will fall back to …
=> Universal sshkey and password manager script

ui/src/views/AutogenView.vue, ui/src/views/offering/ImportBackupOffering.vue, ui/src/views/plugins/quota/EditTariffValueWizard.vue, ui/src/views/plugins/quota/QuotaTariff.vue
1. In UI, with Backup Plugin enabled, a new tab inside Service Offerings, called Backup Offerings, appears. In this tab, users can import a Backup Offering. However, regardless of what the user chooses, the `Allow User Driven Backups` parameter is always send as true
2. In UI, with Quota Plugin enabled, a new tab, called Quota, appears. In this tab there is a component called Tariff, which is responsible for displaying the tariffs of each resource. In addition, in this view there is an edit button that, when clicked, does nothing.
1.
2. 
1. I imported a Backup Offering with `Allow User Driven Backups` parameter as `false` and checked, using cloud-monkey and in the DB if this parameter as correctly set.
2. I edited a Quota Tariff, waited until the effective start day, and check if, in UI, …
=> [UI] Fixes: edit tariff quota and allow user driven backups parameter in Import Backup Offering

ui/src/views/iam/AddAccount.vue, ui/src/views/iam/AddUser.vue, ui/src/views/iam/ConfigureSamlSsoAuth.vue
Fixes #5477
Fixes #5478
Before change:
After change:
=> ui: fix create account/user with saml

ui/src/views/iam/RolePermissionTab.vue
This PR provides support to filter role permissions i.e., only list the APIs which haven't already been added to a role
Test user with 2 role permissions added - addAccountToProject & activateProject:
On listing the APIs to add further permissions - notice that the above added APIs aren't included:
Deleted one API - say, addAccountToProject:
Observed that this API is now available in the dropdown:
=> ui: Add support to filter role permissions

test/integration/component/test_public_ip.py
This PR fixes a travis test failure after merging PR #5464.
ROOT admin cannot list public ip address in the vlan ip ranges which are dedicated to other domain/user, we need to fix the issue in another PR.
=> travis: fix test/integration/component/test_public_ip.py

framework/db/src/test/java/com/cloud/utils/db/GroupByTest.java
Fixes: #5479 
- [OPENNLP-1338](https://issues.apache.org/jira/browse/OPENNLP-1338)
<hr>
- Decouple test class `GroupByExtension` from production class `GroupBy`.
- Remove the redundant test child class `GroupByExtension`
- Make testing logic more explict.
<hr>
* Created mocking object to replace test subclass `GroupByExtension`, decoupled test from production code.
* Created method that return the mocking object for code reuse.
<hr>
=> Refactor GroupByExtension to improve test logic

test/integration/smoke/test_snapshots.py
This PR fixes the intermittent failure observed in test_02_list_snapshots_with_removed_data_store of the test_snapshot.py test suite. This reason for the failure seems to be that the volume created may already be present on the store (primary store) to which it is being migrated to. 
Test fails with the following exception:
```
2021-09-20 23:10:04,870 - CRITICAL - EXCEPTION: test_02_list_snapshots_with_removed_data_store:
['Traceback (most recent call last):\n', '  File "/usr/lib64/python3.6/unittest/case.py", line 60, in testPartExecutor\n    yield\n', ' 
File "/usr/lib64/python3.6/unittest/case.py", line 622, in run\n    testMethod()\n', '  File "/usr/local/lib/python3.6/site-packages
/marvin/lib/decoratorGenerators.py", line 30, in test_wrapper\n    return test(self, *args, …
```
=> marvin: Fix intermittent failure observed in test_02_list_snapshots_with_removed_data_store

test/integration/smoke/test_snapshots.py
This PR addresses comment: https://github.com/apache/cloudstack/pull/5483#discussion_r714628413 - ensures consistency in the way resources are created and added for cleanup
Ran the test_snapshot.py test suite to validate nothing's broken
```
nosetests --with-xunit --xunit-file=results.xml --with-marvin --marvin-config=/marvin/ref-trl-1852-v-M7-pearl-dsilva-advanced-cfg -s -a tags=advanced --hypervisor=vmware /marvin/tests/smoke/test_snapshots.py 
==== Log Folder Path: /marvin/MarvinLogs/Sep_23_2021_09_41_54_FN5EED All logs will be available here ====
====Trying SSH Connection: Host:10.0.35.224 User:root …
```
=> marvin: Refactor - cleanup of resource after test run

tools/docker/Dockerfile, tools/docker/README.md, tools/docker/supervisord.conf
This PR upgrades cloudstack simulator to Ubuntu 20.04, MySQL 8 and python3, launches cloudstack UI at port 5050.
README.md is updated accordingly.
fixes #4891
How to test it
```
cd tools/docker 
docker build -f Dockerfile -t cloudstack/simulator ../..
docker run --name simulator -p 8080:5050 -d cloudstack/simulator
docker exec -it simulator python /root/tools/marvin/marvin/deployDataCenter.py -i /root/setup/dev/advanced.cfg
```
=> tools/docker: Upgrade to ubuntu 20.04 , MySQL 8 and python3

test/integration/smoke/test_vpc_redundant.py
The default value of network.gc.wait and network.gc.interval are both 600 (seconds).
in test_vpc_redundant.py, it waits 1 hour which is unnecessary.
I have run it 10 times when I tested #4224, no isues.
=> test_vpc_redundant.py: reduce sleep time from 1 hour to 21 mins

api/src/main/java/com/cloud/projects/ProjectService.java, api/src/main/java/org/apache/cloudstack/api/command/user/project/DeleteProjectCmd.java, server/src/main/java/com/cloud/projects/ProjectManagerImpl.java, server/src/test/java/com/cloud/projects/MockProjectManagerImpl.java, tools/marvin/marvin/lib/base.py, ui/src/config/section/project.js
Provide a cleanup flag so that the project will
be deleted only when there are no resources left
in the project. If users click on delete project
by mistake then everything is deleted.
Ui changes ported from https://github.com/apache/cloudstack-primate/pull/848
=> Provide option to force delete the project

server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java, server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
This PR addresses https://github.com/apache/cloudstack/issues/5508 - where in vm scale operation is not allowed even when there is no resizing required to be performed.
1. Performed scale VM operation from one compute (fixed) offering type w/o root disk size to another - successful
2. Performed scale VM operation from a compute(fixed) offering  w/o root disk size to a custom constrained / unconstrained offering without any root disk size - successful
3. performed scale VM operation from a compute offering with root disk size to a one without any root disk size  - successful
4. performed scaleVM operation from a compute offering w/o root disk size to a one with root disk size specified - fails with:
=> simulator: Add support to scale a VM

engine/schema/src/main/java/com/cloud/host/dao/HostDaoImpl.java
This PR fixes an issue in #4399 
(1) create service offering with multiple host tags (2 or more)
(2) create a vm with the service offering
expected result
vm is started or 
get error message "No suitable host found for follow compute offering tags: tag1,tag2"
actual result:
Got exception
```
com.cloud.utils.exception.CloudRuntimeException: DB Exception on: select distinct cluster_id from host join host_tags on host.id = host_tags.host_id and host_tags.tag = ?
```
=> server: cannot deploy/start vm if service offering has multiple tags

server/src/main/java/org/apache/cloudstack/diagnostics/DiagnosticsServiceImpl.java
This PR attempts to fix the permission issue observed during unmounting of secondary store(s) during the diagnostic service run (on VMware) and the Diagnostic service garbage collector:
```
2021-09-23 05:17:58,206 DEBUG [o.a.c.s.NfsMountManager] (BackgroundTaskPollManager-1:ctx-d5fcff87) (logid:779879f6) Executing while with timeout : 10000
2021-09-23 05:17:58,263 DEBUG [o.a.c.s.NfsMountManager] (BackgroundTaskPollManager-1:ctx-d5fcff87) (logid:779879f6) Execution is successful.
2021-09-23 05:17:58,267 DEBUG [o.a.c.s.NfsMountManager] (BackgroundTaskPollManager-1:ctx-d5fcff87) (logid:779879f6) Executing: sudo chmod 1777 /var/cloudstack/mnt/32989157261914.7b4126ed
2021-09-23 05:17:58,275 DEBUG [o.a.c.s.NfsMountManager] (BackgroundTaskPollManager-1:ctx-d5fcff87) (logid:779879f6) Executing …
```
=> Fix permission issue during Diagnostic service garbage collection

plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageProcessor.java, vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/VirtualMachineMO.java
This PR fixes issue #5498 where multiple volumes of a VM are exported to secondary storage upon taking snapshot of a single volume in case of VMware
Fixes: #5498 
1. Created a VM with multiple disks
2. Created snapshot of one disk (also a recurring snapshot). (before creating a snapshot, add some data to the disk)
3. Check secondary storage snapshot folder to have only one disk
4. Created a volume from the snapshot above (to check subsequent operations on that snapshot are working fine)
5. Attached the above volume to a VM and made sure it is the proper disk by checking the data created before in Step 2
=> Fix export snapshot and template to secondary storage to export only required disk

api/src/main/java/com/cloud/event/EventTypes.java, api/src/main/java/org/apache/cloudstack/api/command/admin/backup/UpdateBackupOfferingCmd.java, api/src/main/java/org/apache/cloudstack/backup/BackupManager.java, engine/schema/src/main/java/org/apache/cloudstack/backup/BackupOfferingVO.java, server/src/main/java/org/apache/cloudstack/backup/BackupManagerImpl.java, server/src/test/java/org/apache/cloudstack/backup/BackupManagerTest.java
This PR intends to create a new API to allow users to edit name and description of Backup Offerings.
- I imported a new *Backup Offering*;
- Using *cloud-monkey*, I changed the name of this *Backup Offering*, and checked, in DB, UI and listBackupOfferings API if the change was performed correctly;
- Using *cloud-monkey*, I changed the description of this *Backup Offering*, and checked, in DB, UI and listBackupOfferings API if the change was performed correctly;
Using *cloud-monkey*, I changed the name and description of this *Backup Offering*, and checked, in DB, UI and listBackupOfferings API if the change was performed correctly.
Also, I added some unit tests.
=> Create UpdateBackupOffering API

.travis.yml, plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java, plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/OvsVifDriver.java, plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtOvsFetchInterfaceCommandWrapper.java, plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/CitrixResourceBase.java, plugins/network-elements/ovs/src/main/java/com/cloud/network/guru/OvsGuestNetworkGuru.java, scripts/vm/hypervisor/xenserver/ovstunnel, scripts/vm/network/vnet/cloudstack_pluginlib.py, scripts/vm/network/vnet/ovstunnel.py, server/src/main/java/com/cloud/network/guru/DirectNetworkGuru.java, test/integration/component/test_vpc_distributed_routing_offering.py, test/integration/smoke/test_privategw_acl_ovs_gre.py, tools/marvin/marvin/lib/common.py
This PR fixes some issues with OVS/GRE
Issues with isolated networks/vpcs: #2886 #2996  #3802
Issues with shared networks: #2863 #2885
To test this PR, we need to create a zone with isolation method 'GRE' instead of default 'VLAN'.
Test results
(1) smoke test test/integration/smoke/test_privategw_acl_ovs_gre.py passed on kvm and xenserver
(2) component test test/integration/component/test_vpc_distributed_routing_offering.py passed on xenserver.
=> OVS/GRE: bug fixes

server/src/main/java/com/cloud/network/router/CommandSetupHelper.java
In ACS, when a VPC has more than one public IP and a user tries to use the non `source NAT` IP with some feature/option (like `static NAT`, `port forwarding`, `VPN` and others), ACS adds the public IP (used for the feature/option) as `source NAT` in the `iptables` of the VR.
Example:
- VPC has one public IP `192.168.0.50` and it is defined as the `source NAT`.
- If we assign another public IP `192.168.0.51` to the VPC and use it to execute `port forwarding`, ACS will automatically add `192.168.0.51` as `source NAT` too.
This PR intends to remove this inconsistency created by ACS.
I tested locally, in a test lab.
1. Created a VPC;
2. Observed VR's `iptables`;
3. Added public IPs to the VPC, assigned functions, tested and removed them;
4. Before this change, every public IP would turn into …
=> Remove logic that creates gap for multiple 'source NAT' in VR

api/src/main/java/com/cloud/vm/VmDetailConstants.java, plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java, plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java, plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java, server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
Add MV Settings for virtual GPU hardware type and memory.
The default virtual GPU hardware model type is cirrus.
KVM libvirt are support cirrus, vga, qxl and virtio.
Set the value in MV setting to override /etc/cloudstack/agent/agent.properties
video.hardware=qxl (override vm.video.hardware)
video.ram=32768 (override vm.video.ram)
I had test windows 10 and ubuntu 20.04 on CloudStack 4.15.2
In my test set "video.hardware=qxl, video.ram=32768" on windows 10 can get better performance.
And set "video.hardware=virtio, video.ram=32768" on ubuntu 20.04 can get better performance.
Windows driver "Stable virtio-win ISO" is from [here](https://github.com/virtio-win/virtio-win-pkg-scripts/blob/master/README.md).
=> kvm: add MV Settings for virtual GPU hardware type and memory

ui/src/config/section/offering.js
This PR allows users to edit a name and description of a Backup Offering
I tested in a local lab.
1. I imported a Backup Offering;
2. I edited the name of this offering;
3. I edited the description of this offering.
4. I checked, in UI and DB if changes are applied.
=> [UI] Edit backup offering

server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
This PR add empty config value for scope based config setting.
Fixes: #5545
Manually tested empty config values in 'Domain' scope.
=> Add empty config value for scope based config setting

plugins/integrations/kubernetes-service/src/main/resources/conf/k8s-control-node-add.yml, plugins/integrations/kubernetes-service/src/main/resources/conf/k8s-control-node.yml, plugins/integrations/kubernetes-service/src/main/resources/conf/k8s-node.yml, plugins/integrations/kubernetes-service/src/main/resources/script/upgrade-kubernetes.sh
This makes the CKS setup/install/upgrades architecture agnostic and
works on both amd64 and arm64 platforms.
Tested with:
AMD64 cks iso: http://download.cloudstack.org/cks/
ARM64 cks iso: https://dl.yadav.cloud/rpi-templates/cks/
=> cks: refactor code to be architecture agnostic

engine/schema/src/main/java/com/cloud/upgrade/SystemVmTemplateRegistration.java
Fixes #5641
When registering a system VM template during an upgrade, entries in `cloud.template_zone_ref` must be created for the new template.
For a cross-zones template, an entry for each zone must be added.
=> upgrade/systemvm: add template zone entries

tools/marvin/marvin/config/test_data.py
This PR fixes the test failures with test_nic.py in some trillian tests.
see errors below:
```
test_01_nic (tests.smoke.test_nic.TestNic): DEBUG: Exception during NIC test SETUP!: Execute cmd: createnetwork failed, due to: errorCode: 431, errorText:The VLAN tag to use for new guest network, 1201 is already being used for dynamic vlan allocation for the guest network in zone pr5201-t2497-vmware-70u1
```
=> Marvin: change some vlans in test_data.py

plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/LinstorStorageAdaptor.java
With diskful set to true, linstor will fail if it cannot create local
storage for the resource. Which in turn will make it impossible to have a
setup with just compute nodes on cloudstack.
This is a small bugfix that will enable to have cloudstack-agents without storage to work with Linstor volume plugin.
Before the plugin always tried to create a diskful assignment on nodes on connect, but if the node doesn't have
linstor storage, this would fail.
This was intentionally done to improve performance, as having a local disk makes write operations faster,
but there are other ways to configure diskful nodes within linstor(auto diskful, manual toggle disk).
Local cluster setup, but the change is only within the linstor plugin, so should not have any impact on other components.
=> linstor-volume-plugin: Only create diskless assignments on nodes

api/src/main/java/org/apache/cloudstack/api/command/admin/vm/ListVMsCmdByAdmin.java, engine/schema/src/main/resources/META-INF/db/schema-41520to41600.sql, server/src/main/java/com/cloud/api/query/QueryManagerImpl.java, server/src/main/java/com/cloud/api/query/vo/UserVmJoinVO.java
Add clusterid parameter in listVirtualMachines API for admin
Import-Export Instances UI relies on cluster filtering for managed instances. Without clusterid param support in `listVirtualMachines` API for admins it lists all VMs in the zone.
**Before:**
**After:**
Using cmk after changes:
```
(localcloud) 🐱 > list clusters filter=id,name,hypervisortype
{
"cluster": [
{
"hypervisortype": "VMware",
"id": "209e64fb-481f-4864-9a24-2c0a63352eee",
"name": "p1-c1"
},
{
"hypervisortype": "KVM",
"id": "681e9c6f-70db-4725-a6eb-d7979ddf4acc",
"name": "p1-c2"
}
],
"count": 2
}
(localcloud) 🐱 > list virtualmachines filter=id,name,hypervisor,hostid,hostname
{
"count": 2,
{
"hostid": "eb31f76b-bae8-404b-a0a1-3287cf827c6b",
"hostname": "10.0.34.240",
"hypervisor": "VMware",
"id": …
```
=> api,server,engine/schema: admin listvm api clusterid

engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java, engine/schema/src/main/resources/META-INF/db/schema-41520to41600.sql, framework/jobs/src/main/java/org/apache/cloudstack/framework/jobs/dao/VmWorkJobDao.java, framework/jobs/src/main/java/org/apache/cloudstack/framework/jobs/dao/VmWorkJobDaoImpl.java, framework/jobs/src/main/java/org/apache/cloudstack/framework/jobs/impl/AsyncJobVO.java, framework/jobs/src/main/java/org/apache/cloudstack/framework/jobs/impl/VmWorkJobVO.java, server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
Reverts apache/cloudstack#5541
PR is reverted as the issues is not fixed completely, another issue raised: https://github.com/apache/cloudstack/issues/5651. The fix for it introduces regressions on Travis runs: https://github.com/apache/cloudstack/pull/5658
=> Revert "parallel nic adding"

systemvm/debian/opt/cloud/bin/cs/CsDhcp.py
This PR fixes the pycodestyle check failures caused by CsDhcp.py
```
$ cd systemvm/test
$ bash -x runtests.sh
......
../debian/opt/cloud/bin/cs/CsDhcp.py:114:25: E266 too many leading '#' for block comment
+ '[' 1 -gt 0 ']'
+ echo 'pycodestyle failed, please check your code'
```
=> CsDhcp.py: fix runtests.sh error

ui/src/views/compute/InstanceTab.vue
This PR fixes https://github.com/apache/cloudstack/issues/5691
After adding a NIC to the virtual machine, continue to add the NIC by opening the "Add network to virtual machine" form again, the network field auto-selects wrong.
=> UI: Fixes incorrect auto-select in Add network to VM

ui/src/views/infra/AddPrimaryStorage.vue, ui/src/views/infra/zone/ZoneWizardLaunchZone.vue
If Linstor protocol is selected it makes no sense to show other
providers as Linstor only works with the Linstor provider.
This was removed with the fix for #5613, that probably resulted from a
bad merge resolving from my part.
Clicked through local served vui ui -> add primary storage
=> ui-primary-storage: hide provider if Linstor protocol

api/src/main/java/com/cloud/vm/NicProfile.java, engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
=> server: set network rate for additional public IPs

server/src/main/java/com/cloud/network/Ipv6AddressManager.java, server/src/main/java/com/cloud/network/Ipv6AddressManagerImpl.java, server/src/test/java/com/cloud/network/Ipv6AddressManagerTest.java
This PR fixes #5640 partially.
Ipv6-only shared network with offering "Quickcloud with no services" works with this PR.
Ipv6-only shared network with other offerings, which require VR, still does not work, as VR cannot start.
=> IPv6: fix deploy vm issue in ipv6-only networks without VR

utils/src/main/java/com/cloud/utils/exception/CSExceptionErrorCode.java
Currently OperationTimedoutException is not in the known list
and because of that, we get some annoying error messages.
```
INFO  [c.c.u.e.CSExceptionErrorCode] (StatsCollector-4:ctx-f82ba46e) (logid:e3041fe1) Could not find exception: com.cloud.exception.OperationTimedoutException in error code list for exceptions
```
=> server: Add OperationTimedoutException to known list

plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
This PR fixes an error where invalid XML definition is generated when running a virtual machine in UEFI mode on KVM.
When running a virtual machine in UEFI mode, the XML definitions are handled by LibvirtVMDef as follows, depending on the boot mode.
`````
if (_loader != null) {
if (_bootmode == BootMode.LEGACY) {
guestDef.append("<loader readonly='yes' secure='no' type='pflash'>" + _loader + "</loader>\n");
} else if (_bootmode == BootMode.SECURE) {
guestDef.append("<loader readonly='yes' secure='yes' type='pflash'>" + _loader + "</loader>\n");
}
}
`````
However, the current code has NULL assigned to boot mode, so that code doesn't apply to the XML.
This PR modifies the code to use the virtual machine settings to assign a value to the boot mode variable.
=> KVM : Fixes UEFI XML Definition Error

engine/schema/src/main/java/com/cloud/user/dao/AccountDaoImpl.java
This PR fixes an issue with findActiveAccountById in AccountDaoImpl.java
This method is used in some processes. The impact is unknown.
=> engine/schema: fix findActiveAccountById in AccountDaoImpl.java

plugins/metrics/src/test/java/org/apache/cloudstack/response/HostMetricsResponseTest.java
The unit tests of class `HostMetricsResponse` will fail when they are executed on machines with `locale` other than `en_US`. This happens because locales can have distinct decimal separators, for instance, `.` in `en_US` and `,` in `pt_BR`.
This PR solves the mentioned problem by modifying the tests to use the decimal separator character according to the Locale set on the local machine (which is running the tests), instead of using a hardcoded decimal separator.
I ran the unit tests of class `HostMetricsResponse` with locale `pt_BR` and `en_US`. In both cases, the tests passed.
=> Fix HostMetricsResponse unit test

engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
This PR removes network details when network is removed.
=> server bug fix: remove network details when network is removed

plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/manager/VmwareStorageManagerImpl.java
This PR removes redundant call for VM snapshot chain size, in VMware.
=> Removed redundant call for VM snapshot chain size, in VMware.

ui/src/config/section/infra/hosts.js
When host is in state 'ErrorInPrepareForMaintenance', the icon to cancel host maitenance is not shown on UI.
This PR fixes the issue.
=> UI: Enable cancel host maintenance when resource state is 'ErrorInPrepareForMaintenance'

server/src/main/java/com/cloud/network/NetworkServiceImpl.java
This PR fixes the issue that domain admin and normal users can list system network by id.
for example by cmk
```
cmk list networks issystem=true id=200
cmk list networks issystem=true id=201
cmk list networks issystem=true id=202
cmk list networks issystem=true id=203
```
=> server: fix non-root users are able to list system networks

ui/src/views/infra/zone/ZoneWizardPhysicalNetworkSetupStep.vue
This PR fixes https://github.com/apache/cloudstack/issues/5732
When press next button:
=> UI - Fixes the next button not working when adding more physical networks

plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java
Fixes #5706
Correctly set CPU reservation while scaling a dynamically scalable VM.
**Before fix** (CPU reservation is set using offering's CPU speed for the VM after scaling even when global setting vmware.reserve.cpu is false):
```
> deploy virtualmachine zoneid=d295b42c-c67b-4224-9ea7-4777ce3e788e templateid=a9c03b25-4c1e-11ec-b0f8-1e006d000305 serviceofferingid=cdb3674b-aab0-4d75-a09f-a1ad48046bd6 networkids=4cf8b5b5-d2a9-475f-9bd4-5d872ce66c13 name=v1
{
"cpunumber": 2,
"created": "2021-11-23T08:37:28+0000",
"details": {
"cpuOvercommitRatio": "4.0",
"dataDiskController": "osdefault",
"memoryOvercommitRatio": "1.0",
"rootDiskController": "ide"
},
"displayname": "v1",
"displayvm": true, …
```
=> vmware: fix cpu reservation during vm scale

ui/src/config/section/network.js, ui/src/role/index.js, ui/src/views/compute/KubernetesServiceTab.vue, ui/src/views/network/CreateIsolatedNetworkForm.vue, ui/src/views/network/CreateL2NetworkForm.vue, ui/src/views/network/CreateNetwork.vue, ui/src/views/network/CreateSharedNetworkForm.vue, ui/src/views/network/UpdateNetwork.vue, ui/src/views/offering/AddComputeOffering.vue, ui/src/views/offering/AddDiskOffering.vue, ui/src/views/offering/AddNetworkOffering.vue, ui/src/views/offering/AddVpcOffering.vue, ui/src/views/offering/UpdateOfferingAccess.vue
=> conditional broadcastUri

plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/guru/VMwareGuru.java, server/src/main/java/com/cloud/hypervisor/HypervisorGuruBase.java, server/src/main/java/org/apache/cloudstack/backup/BackupManagerImpl.java, server/src/test/java/com/cloud/hypervisor/KVMGuruTest.java
Using the VMWare hypervisor, and with Veeam integration enabled, a full restore of a VM using a backup in Veeam occurs correctly, but in ACS an exception is thrown: `Restore VM Backup (607c2bbf-2c23-49a1-9549-cd402441dcb5) Error during vm backup restore and import: Invalid string format`
Upon adding more logs to the restore process, it was discovered that this was because the VM being restored had no value in the `hostid` attribute.
This PR fixes this behavior, increments the logs in the restore process for VMs using backups and adds new unit tests.
It was tested in a local laboratory:
1. I have assigned one VM to a Backup Offering;
2. I backed up the VM manually;
3. I tried to perform a full VM restore using this backup;
4. Before, there was an exception in ACS, now the restore finishes …
=> [Veeam] Fix full backup VM restore exception

api/src/main/java/org/apache/cloudstack/api/BaseListDomainResourcesCmd.java, api/src/main/java/org/apache/cloudstack/api/BaseListProjectAndAccountResourcesCmd.java, server/src/main/java/com/cloud/user/AccountManagerImpl.java
Considering the reviews and discussion, I changed the scope of this PR to documentation update. I think that at least the documentation changes are mandatory as the documentation is not clear and already let to some internal issues.
Looking into the [listVirtualMachines API command documentation](https://cloudstack.apache.org/api/apidocs-4.14/apis/listVirtualMachines.html) there is the following description:
> listall: If set to false, list only resources belonging to the command's caller; if set to true - list resources that the caller is authorized to see. Default value is false
The documentation is clear about the fact that when parameter `listall=true` then `listVirtualMachines` lists resources that the caller is authorized to see. Therefore, this PR considers that the ADMIN is …
=> Update listVirtualMachines API documentation with 'projectid=-1' to list all VMs in projects.

api/src/main/java/org/apache/cloudstack/api/command/admin/network/UpdateNetworkOfferingCmd.java, api/src/main/java/org/apache/cloudstack/api/command/admin/offering/UpdateDiskOfferingCmd.java, api/src/main/java/org/apache/cloudstack/api/command/admin/offering/UpdateServiceOfferingCmd.java, api/src/main/java/org/apache/cloudstack/api/command/admin/vpc/UpdateVPCOfferingCmd.java
This PR proposes setting a length for domain id parameters that allow passing a list of UUIDs separated by a comma. Allowing to run the API command in use-cases where there are many domain admins.
Currently when calling API command with multiple domain ids (for example `updateServiceOffering`) it leads to the following API error:
```
Error: (HTTP 431, error code 9999) Unable to execute API command updateserviceoffering due to invalid value.
Value greater than max allowed length 255 for param: domainIds"
```
I am targeting this implementation at 4.16.1.0 and considering it a bug due to the fact that we could not relly on the API to execute a few critical updates. 
Admins end up either calling multiple times the API or (:warning: don't go this way) doing DB changes.
=> Increase the length for parameters that expect a list of domain IDs.

engine/storage/datamotion/src/main/java/org/apache/cloudstack/storage/motion/KvmNonManagedStorageDataMotionStrategy.java, engine/storage/datamotion/src/test/java/org/apache/cloudstack/storage/motion/KvmNonManagedStorageSystemDataMotionTest.java
When a volume is copied to another storage pool, if the template does not exist in the destination storage pool yet, it should be copied. The API `migrateVirtualMachineWithVolume` already does it; however, when migrating the volume with `migrateVolume` (VM stopped), the template is not copied, which causes inconsistencies in the database and primary storage systems. The not existence of the template in the storage pool causes an NPE when using the API `migrateVirtualMachineWithVolume`.  
This PR intends to avoid this NPE.
I tested it in a test lab.
1. I created a VM;
2. I stopped the VM;
3. I created a new primary storage;
4. With API `migrateVolume` I migrated the volume to the new primary storage;
5. Before this changes, when I tried to migrate the volume to another primary storage that …
=> Fix NPE on migrateVirtualMachineWithVolume

server/src/main/java/com/cloud/deploy/FirstFitPlanner.java
When cluster reached capacity threshold log message is:
`"capacity threshold defined at each cluster/ at global value for capacity Type : 0"`
Admins hardly remember the Capacity Type and it can take a while to look at which is the resource for the respective ID.
This PR adds a log message pointing to the capacity name (e.g. Memory / CPU) as well as global settings parameter name and value to be looked at.
Additionally, this PR also proposes to change the log message from DEBUG to Warning, as it gives relevant information in case of exceptions, and might enforce production environments to have log level at debugging instead of info.
=> Enhance log message in FirstFitPlanner

server/src/main/java/com/cloud/server/ManagementServerImpl.java
This PR fixes an issue noticed while searching for clusters based on name. When the 'name' parameter is passed, it treats it as a keyword to be searched (https://github.com/apache/cloudstack-cloudmonkey/issues/109). 
```
(localcloud) 🐱 > list clusters name=Pool1 filter=name,id,
{
"cluster": [
{
"id": "0b02dfba-27b8-4371-ad16-23d6df57ffca",
"name": "Pool1"
},
{
"id": "dc6a03fd-7d33-47cd-9bc0-a15c8fcda139",
"name": "Pool10"
}
],
"count": 2
}
```
```
(localcloud) 🐱 > list clusters name=Pool1 filter=name,id,
{
"cluster": [
{
"id": "11d536bb-7719-4c39-8ecc-eca11d2ef3bf",
"name": "Pool1"
}
],
"count": 1
}
(localcloud) 🐱 > list clusters name=Pool filter=name,id,
(localcloud) 🐱 > list clusters keyword=Pool1 filter=name,id,
{
"cluster": [
{
"id": "11d536bb-7719-4c39-8ecc-eca11d2ef3bf",
"name": …
```
=> api: Fix search cluster by name

ui/src/views/compute/DeployVM.vue
This PR Fixes issue #5765 _UI: SSH key option should not be presented if not allowed/support_.
After applying this patch, the VM deployment via UI shows the SSH Keys step only if the user/account has access to the [listSSHKeyPairs](https://cloudstack.apache.org/api/apidocs-4.15/apis/listSSHKeyPairs.html) command.
Fixes: #5765
1. Deploy VM via user that has access to listSSHKeyPairs
2. UI shows all keys the user can access
3. create role type that don't allow `listSSHKeyPairs`
4. Deploy VM via user that is not allowed to call API command `listSSHKeyPairs`
5. UI does not present the SSH keys step to the user
=> UI: show SSH keys step in VM deployment only if user can 'listSSHKeyPairs'

server/src/main/java/com/cloud/vm/UserVmManagerImpl.java, server/src/test/java/com/cloud/vm/UserVmManagerTest.java
This PR fixes the issue that new ip is not working if old ip is used in lb/pf (or dnat).
(1) create isolated network, and vm
(2) acquire 3 public ips, add firewall rules to allow port 22 (ssh)
(3) create NAT to the vm on public ip 1, load balancer to vm port 22 (ssh) on public ip 2,  port forwarding rule to vm port 22 on public ip 3
(4) verify the ssh connection to vm, all work
(5) stop vm, and update vm nic ip, start vm
(6) expected result: DNAT, LB, PF work, 
actual result without this PR : LB and PF do not work.
=> network: update ip in lb/pf/dnat tables when update vm nic ip

ui/src/views/network/PortForwarding.vue
This PR fixes #5688
After adding a new port forwarding for the first time, the user cannot add the next time because the OK button is disabled.
=> UI - Fixes cannot add new port forwarding rules after auto select VM next time

ui/src/views/network/LoadBalancing.vue
This PR fixes issue with configure Sticky Policy form in the Load Balancing Tab, where the form does not get submitted and also  resets the form fields when changing the stickiness method to prevent invalid arguments from being passed. 
Fixes: #5813
=> ui: Fix configure Sticky policy form

plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java, plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java
This would allow use of virtio disk controller with Ceph, etc or as
defined in the VM's root disk controller setting, rather than always
enforce SCSI.
On ARM64 setup, this would now allow use of virtio disk controller for nfs and ceph. With Ceph, when virtio is used rbd performance increases drastically.
=> kvm: don't always force scsi controller for aarch64 VMs

ui/src/components/view/InfoCard.vue
Tags in info card of the UI are related to tags functionality(create/delete/listTags API)
UI was incorrectly showing storage tags as these tags in the UI.
Fixes #5727
Before:
After:
Using UI
=> ui: show tags only for supported resources

ui/src/views/compute/DeployVM.vue
In the UI, when selecting a service offering that has a root disk enforced, stills show the root disk size of the template (or the custom size gave by the user). This PR fixes this issue, that thas been reported in #5777.
Fixes: #5777
Now the UI dynamically changes the root disk size according to the following variables, following the priority order:
1. Service offering size (highest priority)
2. Custom size set by the user
3. Template size
1. Build UI (npm run serve)
2. Choose a template -- root disk size matches with the template
3. Set custom root disk size to 123GB -- UI updated with the new root disk size
4. Choose an offering with root disk size set to 30 -- UI changes to the service offering root disk size
5. Change to another offering, e.g. with 50G -- again, the UI updates
=> Fix UI issue 5777 Root disk size is not shown as 'Disk Size' on VM deployment.

plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/driver/ScaleIOPrimaryDataStoreDriver.java, server/src/main/java/com/cloud/storage/StorageManagerImpl.java
* Managed volume copy was always returning first host that could see storage pools
* Fix null value in logging for ScaleIOPrimaryDataStoreDriver due to if/else logic error
Signed-off-by: Marcus Sorensen <mls@apple.com>
This PR fixes #5788 
It shuffles the list of valid host candidates that are used for processing volume migrations.  
It also fixes a logic error in debug logging that caused 'null' to be printed. Originally concatenating a static string with potentially null value and then testing to see if the result is null, which would never be true.
A more ideal solution might be to track the jobs on each host and attempt to balance the load according to how busy each host is.  This was investigated and there's currently no obvious way to look up job assignments to hosts via the DB, the …
=> Randomize managed volume copy host

server/src/main/java/com/cloud/api/query/QueryManagerImpl.java, ui/src/views/compute/wizard/ComputeOfferingSelection.vue
The service offerings matching the deployment options requirements were not listed, except unconstrained offerings. This PR fixes the listing of service offerings on VMware deployment options:
=> [VMware] Fix service offerings listing on appliances deployment options

debian/control
=> kvm: support qemu-system-x86>=5.2

api/src/main/java/org/apache/cloudstack/api/command/user/vm/ListVMsCmd.java, server/src/main/java/com/cloud/api/query/QueryManagerImpl.java, server/src/main/java/com/cloud/api/query/vo/UserVmJoinVO.java
Using the VMWare hypervisor, and with Veeam integration enabled, it is not possible, via API, list the VMs that are assigned to a Backup Offering. 
This PR extends the listVMs API to allow users to list the VMs that have particular Backup Offerings.
It was tested in a local laboratory:
1. I have assigned two VMs to a Backup Offering;
2. Using cloudmonkey, I listed the VMs that use this Backup Offering;
3. The two VMs were correctly listed;
4. I removed one of the VMs from the Backup Offering and repeated step 2.
5. Only one VM was listed;
6. Finally I removed the other VM and repeated step 2;
7. No VMs were listed.
=> Allow users to list VMs by Backup Offering Id

ui/src/views/infra/zone/ZoneWizardAddResources.vue, ui/src/views/infra/zone/ZoneWizardNetworkSetupStep.vue, ui/src/views/infra/zone/ZoneWizardPhysicalNetworkSetupStep.vue, ui/src/views/infra/zone/ZoneWizardZoneDetailsStep.vue
This PR is related to issue: `ui: Simplify code` #4956
=> simplify code using optional chaining in the zone view

ui/src/components/widgets/Console.vue
This PR fixes #5623.
Also, some more information that is not present in the issue in question:
- Although the proxy console access button does not appear in the UI, users with access permission to the VM in question have access to the console as well. Simply generate the console access link using another user, copy that link, and, on the user without access to the console button, type that link.
Its tested in a local lab, trying to reproduce the steps of the *issue* #5623.
=> [UI] Change permission to access console proxy button

ui/src/views/infra/zone/ZoneWizardLaunchZone.vue
This PR is related to issue: `ui: Simplify code` #4956
=> simplify code using optional chaining in ZoneWizardLaunchZone view

ui/src/views/infra/zone/ZoneWizardPhysicalNetworkSetupStep.vue
This PR fixes https://github.com/apache/cloudstack/issues/5705
After editing the tariff label of a network, continue to open the popup to edit the tariff label of the next network, it will still display the information of the previous network's tariff label.
Network 1 (label: cloud01):
Network 2 (label: cloud02):
Network 3 (label: null):
=> UI: Automatically refill tariff label information after editing.

core/src/main/java/com/cloud/storage/template/OVAProcessor.java
This PR handles an OVA that uses a property replacement for a disksize value
=> assume a property is one when it isn't a number

plugins/user-authenticators/ldap/src/main/java/org/apache/cloudstack/api/command/LDAPConfigCmd.java, plugins/user-authenticators/ldap/src/main/java/org/apache/cloudstack/ldap/LdapConfiguration.java, plugins/user-authenticators/ldap/src/main/java/org/apache/cloudstack/ldap/LdapContextFactory.java, plugins/user-authenticators/ldap/src/test/groovy/org/apache/cloudstack/ldap/LdapContextFactorySpec.groovy, plugins/user-authenticators/ldap/src/test/java/org/apache/cloudstack/ldap/LdapConfigurationTest.java
This PR fixes an issue where the truststore is only queried on global level and not per domain.
Fixes: #5712
=> LDAP truststore per domain

server/src/main/java/com/cloud/acl/DomainChecker.java
Fixes #5534
As pre 3.x APIs allow using internal DB IDs, even normal users can use internal IDs.
This fix removes additional information in error message when the caller doesn't have access to the resource.
*Before*
```
(local) 🐤 > list accounts id=2
🙈 Error: (HTTP 531, error code 4365) Acct[c6de2628-5a8e-4d68-a95d-2f407db1612d-user] -- Account {"id": 4, "name": "user", "uuid": "c6de2628-5a8e-4d68-a95d-2f407db1612d"} does not have permission to operate with resource Acct[54e1efd3-6951-11ec-919d-645d8651f45a-admin] -- Account {"id": 2, "name": "admin", "uuid": "54e1efd3-6951-11ec-919d-645d8651f45a"}
```
*After*
```
(local) 🐬 > list accounts id=2
🙈 Error: (HTTP 531, error code 4365) Acct[c6de2628-5a8e-4d68-a95d-2f407db1612d-user] -- Account {"id": 4, "name": "user", "uuid": …
```
=> server: do not return inaccessible entity details to normal users

engine/api/src/main/java/org/apache/cloudstack/engine/subsystem/api/storage/DataObject.java, engine/api/src/main/java/org/apache/cloudstack/engine/subsystem/api/storage/SecondaryStorageService.java, engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/DataMigrationUtility.java, engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/StorageOrchestrator.java, engine/storage/image/src/main/java/org/apache/cloudstack/storage/image/SecondaryStorageServiceImpl.java, engine/storage/image/src/main/java/org/apache/cloudstack/storage/image/store/TemplateObject.java, engine/storage/volume/src/main/java/org/apache/cloudstack/storage/volume/VolumeObject.java, server/src/main/java/org/apache/cloudstack/diagnostics/to/DiagnosticsDataObject.java
This PR fails a migrateData command if any of the files fail to migrate.
In addition it tries to calculate capacity based on the actual size on disk the template takes, and not the virtual size.
Fixes: #5654
Fixes: #5655
create a test env and add templates.
set a large size in vm_template.size in the DB to an enormous size (add 7 or 8 zeros to it)
migrate:
```
> migrate secondarystoragedata srcpool=9166e328-608a-4469-8899-4374507e2e20 destpools=e23c6295-82f4-4878-8437-4417944e1653
{
"imagestore": {
"message": "Migration completed. Not all data objects were migrated. Some were probably skipped due to lack of storage capacity.. successful migrations: 1",
"migrationtype": "COMPLETE",
"success": false
}
}
```
=> use physical size instead of virtual size for migration.

engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java, engine/schema/src/main/resources/META-INF/db/schema-41600to41610.sql, framework/jobs/src/main/java/org/apache/cloudstack/framework/jobs/dao/VmWorkJobDao.java, framework/jobs/src/main/java/org/apache/cloudstack/framework/jobs/dao/VmWorkJobDaoImpl.java, framework/jobs/src/main/java/org/apache/cloudstack/framework/jobs/impl/AsyncJobVO.java, framework/jobs/src/main/java/org/apache/cloudstack/framework/jobs/impl/VmWorkJobVO.java, server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
This PR intents to
Fixes: #5541 without regressing #5651
manual tested
create five shared networks,
create a VM in one of those
run a command line like 
```
for net in \
"5e998528-6886-4d23-aa20-d8c0c3dfd0d4"\
"759a94ac-3c36-425c-b3ef-94a2ada9f8a1"\
"a7ce3c15-8497-4e52-9530-1a1ebf2cb023"\
"8da9d26a-c139-49f0-ae64-fd38b331d48d"
do
cmk add nictovirtualmachine networkid=$net virtualmachineid=c22686c7-1ff9-4e66-afe5-348127ef7fe2 &
done
```
substituting the right IDs
create two shared networks,
create a VM in one of those
run a command line like 
```
for net in \
"5e998528-6886-4d23-aa20-d8c0c3dfd0d4"\
"5e998528-6886-4d23-aa20-d8c0c3dfd0d4"\
"5e998528-6886-4d23-aa20-d8c0c3dfd0d4"
do
cmk add nictovirtualmachine networkid=$net virtualmachineid=c22686c7-1ff9-4e66-afe5-348127ef7fe2 &
done
``` …
=> remove VmWorkJob after adding a nic to a vm

server/src/main/java/com/cloud/network/NetworkModelImpl.java, test/integration/smoke/test_storage_policy.py
This PR fixes a bug with integration test test_storage_policy.py
https://github.com/apache/cloudstack/blob/4.16.0.0/test/integration/smoke/test_storage_policy.py#L191-L208
in the test, root admin deploys a vm for another account on root admin's L2 network, it should fail but test passes.
=> network: fix vm can be deployed on L2 network of other accounts

server/src/main/java/com/cloud/network/rules/RulesManagerImpl.java
=> server: fix enable/disable static nat if userdata is not supported

ui/src/views/compute/EditVM.vue
Fixes #5743
For VMs which have service offering that does not allow HA, haenable option will be not shown in the UpdateVM UI form.
VM with offering that doesn't offer HA
VM with offering that offer HA
=> ui: update vm haenable only for supported vms

ui/public/locales/en.json, ui/src/store/getters.js, ui/src/store/modules/app.js, ui/src/views/AutogenView.vue
This PR allows listing elements that are in projects when in the Default view.
Nowadays, Admins cannot list in the UI many relevant data, unless entering in each of the projects, which can be humanly not feasible considering 10s or 100s of projects.
For example, one Admin cannot list all VMs, SSH keys, affinity groups, volumes, not even events that happen in a project in order to track all the events.
The UI tabs that are considered for this proposed PR are:
1. 'vm',
2. 'vmgroup',
3. 'ssh',
4. 'affinitygroup',
5. 'volume',
6. 'snapshot',
7. 'vmsnapshot',
8. 'guestnetwork',
9. 'vpc',
10. 'securitygroups',
11. 'publicip',
12. 'vpncustomergateway',
13. 'template',
14. 'iso',
15. 'event'
- Build and run new UI
- Log in with admin account
- check tabs on default view
- check tabs on a project …
=> Add toggle button on the UI for list including elements in projects.

engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java, server/src/main/java/com/cloud/network/NetworkServiceImpl.java
This PR fixes #5640 by disabling IPv6-only Shared network with VR provider.
=> ipv6: disable IPv6-only shared network with VR

server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
Fixes #5694
Verify custom params for VM while updating using existing CPU speed when the VM offering is of unconstrained type.
=> server: fix update vm with unconstrained offering

ui/src/config/section/account.js
=> ui: show account configure limits tab for domain-admin

engine/schema/src/main/java/com/cloud/upgrade/RolePermissionChecker.java, engine/schema/src/main/java/com/cloud/upgrade/dao/Upgrade41520to41600.java, engine/schema/src/main/resources/META-INF/db/schema-41520to41600.sql
This PR prevents upgrade failures in the specific case in which the annotations are allowed as part of the role permissions for some roles.
Fixes: #5617 
- Create a vanilla environment
- Upgrade a 4.15.2 environment without adding any role permission
=> Prevent upgrade failures if there are existing annotations permissions

ui/src/views/infra/HostAdd.vue
This PR fixes https://github.com/apache/cloudstack/issues/5864
=> UI - Fixes Pod, Cluster selected is incorrect on addHost dialog

ui/src/components/view/ResourceLimitTab.vue
When configuring domain resource limits in the UI, writing a value (but not saving) into the input field and then selecting another domain would make the value written in the previous domain resource limits tab appear for the newly selected domain as well. This bug can cause the user to unintentionally change values in the wrong domain, for example:
Setting the "Max. Memory" field in domain A, switching to domain B, setting the "Max. User Vms" field, and then clicking submit would cause both fields to be submitted for domain B.
The proposed change is to reset the fields after calling the API's `listResourceLimits`.
- The UI was tested in a local lab to verify if changes were effective.
=> [UI] Fix domain resources field not being updated with backend data

usage/src/main/java/com/cloud/usage/UsageManagerImpl.java, usage/src/main/java/com/cloud/usage/parser/VMSnapshotOnPrimaryParser.java
This PR removes the redundant parsing of VMSnapshot usage record.
Fixes #5662
=> Removed redundant parsing of VMSnapshot usage record.

core/src/main/java/org/apache/cloudstack/storage/command/UploadStatusAnswer.java, engine/storage/src/main/java/org/apache/cloudstack/storage/image/BaseImageStoreDriverImpl.java, engine/storage/src/main/java/org/apache/cloudstack/storage/image/deployasis/DeployAsIsHelperImpl.java, server/src/main/java/com/cloud/storage/ImageStoreUploadMonitorImpl.java, server/src/main/java/org/apache/cloudstack/storage/image/deployasis/DeployAsIsHelper.java, services/secondary-storage/server/src/main/java/org/apache/cloudstack/storage/resource/NfsSecondaryStorageResource.java, services/secondary-storage/server/src/main/java/org/apache/cloudstack/storage/template/UploadEntity.java
This PR adds the missing template details when combining: OVA template upload from local + Read VM settings from OVA
Fixes: #5808 
- Upload a OVA template from local
- Verify the template_deploy_as_is_details table and the VM deployment wizard
- Deploy VM and ensure properties/configurations/etc are set
=> [VMware][Deploy-as-is] OVF properties not importing when template is uploaded from local

api/src/main/java/com/cloud/storage/Snapshot.java, engine/schema/src/main/java/com/cloud/host/dao/HostDaoImpl.java, engine/schema/src/main/java/com/cloud/host/dao/HostTagsDao.java, engine/schema/src/main/java/com/cloud/host/dao/HostTagsDaoImpl.java, engine/schema/src/main/java/com/cloud/storage/SnapshotVO.java, engine/schema/src/main/java/com/cloud/storage/dao/SnapshotDaoImpl.java, engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/snapshot/SnapshotObject.java, engine/storage/src/main/java/org/apache/cloudstack/storage/snapshot/SnapshotEntityImpl.java, server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java, server/src/main/java/com/cloud/resource/ResourceManagerImpl.java, server/src/main/java/com/cloud/resource/RollingMaintenanceManagerImpl.java, server/src/main/java/com/cloud/storage/snapshot/SnapshotManagerImpl.java
Fix camel case in some methods' names.
=> Fix camel case in some methods' names

plugins/network-elements/netscaler/src/main/java/com/cloud/api/commands/AddNetscalerLoadBalancerCmd.java, ui/src/views/infra/network/providers/AddF5LoadBalancer.vue, ui/src/views/infra/network/providers/AddNetscalerLoadBalancer.vue, ui/src/views/infra/network/providers/AddNiciraNvpDevice.vue, ui/src/views/infra/network/providers/AddPaloAltoFirewall.vue, ui/src/views/infra/network/providers/AddSrxFirewall.vue
Adds placeholder text for NSPs with custom vues
TODO
=> Adding placeholders for custom NSP vues

ui/src/components/view/DetailSettings.vue
Fixes #5724
Before fix (filtering of readonly details not working properly and updateVirtualMachine is called with rootDiskController setting)
- On a VMware env, as a regular user deploy a VM, stop it after deployment. Template shouldn't have nicAdapter specified
- Try to update VM with nicAdapter from UI by adding the new setting.
- Observe updateVirtualMachine API is called with rootDiskController in the details
After fix:
=> ui: fix filtering readonly details while VM update

engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
During assignment of an IP from a secondary address range an extra NIC is created on a router. This must be allowed even though the router already has a NIC on the public network. The creation of extra NICs should only be prevented in User VMs on guest networks.
This PR...
Fixes: #5890
manual and throught the existing smoke tests.
=> Make sure other than user VMs can have multiple NICs in a network

services/secondary-storage/controller/src/main/java/org/apache/cloudstack/secondarystorage/SecondaryStorageManagerImpl.java
This PR fixes reporting of the destroy status when SSVM is destroyed.
Issue due to changes here:
https://github.com/apache/cloudstack/commit/1aef5cba666510a23f50bd24c4233fc5dd1d35d2#diff-d8fdd320d08cc4eff5dfe391d01c910c660e08ced5afcb2915c78da35f23c453R988-R996
Fixes #5895
=> Update proper destroy status when SSVM is destroyed.

plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/CitrixResourceBase.java, plugins/hypervisors/xenserver/src/test/java/com/cloud/hypervisor/xenserver/resource/CitrixResourceBaseTest.java
The 'platform' setting is retrieved after a VM is stopped with the platform parameters obtained from Xen/XCP for a certain VM. If a user added the setting 'cpu.corespersocket', it was ignored and the setting was never applied as it was mutually exclusive with the platform 'setting'.
This PR fixes the previous behavior, in the following way:
- If 'cpu.corespersocket'=X AND the 'platform' setting does not contain 'cores-per-socket' -> 'cores-per-socket:X' parameter is added to the 'platform' setting which is sent to Xen/XCP
- If 'cpu.corespersocket'=X AND the 'platform' setting contains 'cores-per-socket:Y' -> The 'platform' setting is updated, containing: 'cores-per-socket:X'
- If 'cpu.corespersocket' is not set, nothing changes
Fixes: #5695 
- Deploy a VM using an offering with 2 CPUs …
=> [XenServer/XCP-ng] Sync the 'platform' setting according to the 'cpu.corespersocket' setting

engine/schema/src/main/java/com/cloud/storage/dao/DiskOfferingDao.java, engine/schema/src/main/java/com/cloud/storage/dao/DiskOfferingDaoImpl.java, server/src/main/java/com/cloud/api/query/dao/DiskOfferingJoinDao.java, server/src/main/java/com/cloud/api/query/dao/DiskOfferingJoinDaoImpl.java, server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java, ui/src/views/storage/UploadLocalVolume.vue
Fixes #5696
- Find suitable custom disk offering for volume upload based on the zone.
- In UI, added diskoffering option in Upload volume from local.
- Deployed an env with 2 zones
- _Tested volume upload local/url without passing diskoffering_ 
- Deleted default custom disk offering, created two separate custom disk offerings for the two zones and then:
1. Tested local/url volume upload to both zones, one by one without passing offering
2. Tested local/url  volume upload to both zones, one by one while passing offering
3. Tested local/url  volume upload to first zone while passing offering offering from second zone
=> server: find suitable disk offering for volume upload

engine/schema/src/main/java/com/cloud/vm/dao/VMInstanceDao.java, engine/schema/src/main/java/com/cloud/vm/dao/VMInstanceDaoImpl.java, server/src/main/java/org/apache/cloudstack/vm/UnmanagedVMsManagerImpl.java
When the host and last host ID is not set for the VM, it may appear in the list of unmanaged instances.
This change fixes the behaviour by filtering unmanaged instances list for the host for the following three criteria:
- host is set as host_id for the VM
- host is set as the last_host_id for the VM
- pod of the host is set as the pod_id for the VM and both host_id and last_host_id is NULL
**Clusters:**
```
(localcloud) SBCM5> > list clusters filter=id,name,podid,podname
{
"cluster": [
{
"id": "3d79b022-0fd9-4f51-805d-ef71bef562c5",
"name": "p1-c1",
"podid": "c9e2eccc-9c94-4a9e-a971-fa15a0bf59c2",
"podname": "Pod1"
},
{
"id": "a5b2a7b8-f897-4d5f-889f-a9f1321e7c2b",
"name": "10.0.35.234/Trillian/p1-c2",
"podid": "c9e2eccc-9c94-4a9e-a971-fa15a0bf59c2",
"podname": "Pod1"
}
],
"count": 2
} …
```
=> vm-import: fix unmanaged instance listing

server/src/main/java/com/cloud/network/NetworkServiceImpl.java
This PR allows normal users to create isolated networks without source nat.
fixes #5897
=> server: allow normal users to create isolated network without source nat

api/src/main/java/com/cloud/agent/api/to/IpAddressTO.java, plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/guru/VmwareVmImplementer.java, plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/manager/VmwareManager.java, plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/manager/VmwareManagerImpl.java, plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java, server/src/main/java/com/cloud/network/router/CommandSetupHelper.java, server/src/main/java/com/cloud/network/router/VirtualNetworkApplianceManagerImpl.java
This PR fixes #5716 where isolated network VR failed to deploy when Vmxnet3 adapter type is used and when router.extra.public.nics is not 0. This is because of the extra nics that are reserved in the VR based on the global setting router.extra.public.nics.
To address the issue we have now implemented nic hot plugging for isolated networks because systemvm templates had open-vm-tools installed and support hot plugging which is what is already used in the case of VPC VR.
1. Set the global setting vmware.systemvm.nic.device.type to Vmxnet3 and router.extra.public.nics to some value (not 0)
2. Create an isolated network and VM in it.
3. VR will stuck in starting state
After the fix, following are the test cases that are performed
1. Set the global setting …
=> Added hot plugging of vifs in case of VMware isolated networks

ui/src/views/infra/network/IpRangesTabPublic.vue, ui/src/views/infra/network/IpRangesTabStorage.vue, ui/src/views/infra/network/providers/ProviderItem.vue, ui/src/views/network/CreateL2NetworkForm.vue
This PR is related to issue: `ui: Simplify code` #4956
=> simplify code using optional chaining in multiple views

framework/quota/src/main/java/org/apache/cloudstack/quota/QuotaManagerImpl.java, framework/quota/src/test/java/org/apache/cloudstack/quota/QuotaManagerImplTest.java
The quota calculation has been wrong for monthly tariffs (like Compute-Month, GB-Month, etc) for so much time but even when #3448 was reported it was closed without evaluation.
The wrong calculation was the price per hour, it was taking the monthly tariff and multiplying by the aggregation ratio which has no sense at all.
The right price per hour is the monthly tariff divided by the standard number of hours in a month.
Fixes #3448.
Partial execution of the component with a test vector.
Tracing the values and compared with spreadsheet.
=> Fix #3448 quota calculation for monthly tariffs

server/src/main/java/com/cloud/storage/StorageManagerImpl.java
This PR fixes #5936 - prevents registration of systemVM template for Simulator hypervisor
Deploy a simulator hypervisor with advanced zone, and observed logs during addition of secondary store - no NPE
=> Skip systemVM template registration for Simulator

api/src/main/java/org/apache/cloudstack/api/command/user/ssh/ListSSHKeyPairsCmd.java, api/src/main/java/org/apache/cloudstack/api/response/SSHKeyPairResponse.java, server/src/main/java/com/cloud/server/ManagementServerImpl.java, ui/src/components/view/InfoCard.vue
This PR adds the search by ID capability to SSH Key pairs to bring it at par with accounts
Also needed as a UI fix
In a 4.16 env, try to view the second / third sshkey. It tries to fetch it by id which does not work and leads to the first keypair always displayed
```
(localhost) 🐱 > list sshkeypairs id=5210f701-b13e-4ff7-8aab-eb24ee81526a filter=id,name
{
"count": 1,
"sshkeypair": [
{
"id": "5210f701-b13e-4ff7-8aab-eb24ee81526a",
"name": "b"
}
]
}
(localhost) 🐱 > list sshkeypairs filter=id,name
{
"count": 3,
"sshkeypair": [
{
"id": "d1348275-e203-46bf-a985-45dc2a1b331f",
"name": "c"
},
{
"id": "5210f701-b13e-4ff7-8aab-eb24ee81526a",
"name": "b"
},
{
"id": "b4430a09-5b9d-49e4-be55-156e1b7ebd72",
"name": "a"
}
]
}
```
=> Add ID search capability to sshkeypairs

test/integration/smoke/test_kubernetes_supported_versions.py
This PR fixes test failure with test_secondary_storage.py
mgmt server is restarted in cleanup of test_kubernetes_supported_versions.py as last step.
in some smoke tests, test_secondary_storage.py is run behind test_kubernetes_supported_versions.py. 
but in  test_secondary_storage.py it checks if all hosts are Up as first step.
sometimes, the mgmt server is Up, but hosts are still in Connecting state. this causes the test failure with test_secondary_storage.py
=> test: sleep 30s after restarting mgt server in test_kubernetes_supported_versions.py

ui/src/views/network/CreateIsolatedNetworkForm.vue, ui/src/views/network/CreateNetwork.vue
This PR fixes https://github.com/apache/cloudstack/issues/5897
=> UI - Add Network: shows "Offering for Isolated networks with no Source Nat service" on Network Offering for normal users

framework/db/src/main/java/com/cloud/utils/db/GenericDaoBase.java
This PR fixes the issue noticed when listing all ssh key pairs including ones owned by projects. Exception:
```
(primateqa) 🐱 > list sshkeypairs listall=true projectid=-1
🙈 Error: (HTTP 530, error code 4250) DB Exception on: com.mysql.cj.jdbc.ClientPreparedStatement: SELECT ssh_keypairs.id, ssh_keypairs.uuid, ssh_keypairs.account_id, ssh_keypairs.domain_id, ssh_keypairs.keypair_name, ssh_keypairs.fingerprint, ssh_keypairs.public_key FROM ssh_keypairs  INNER JOIN account ON ssh_keypairs.account_id=account.id  WH ORDER BY ssh_keypairs.id DESC  LIMIT 0, 500
```
```
(localcloud) 🐱 > list sshkeypairs listall=true page=1 pagesize=20 filter=name,
{
"count": 1,
"sshkeypair": [
{
"name": "ssh"
}
]
}
(localcloud) 🐱 > list sshkeypairs listall=true projectid=-1 page=1 pagesize=20 filter=name,
{ …
```
=> API: Fix listSSHKeyPairs API when listing all resources (listall=true & projectid=-1)

scripts/storage/secondary/setup-sysvm-tmplt
This PR adds missing diskspace parameter used to verify is there's sufficient space to proceed with template seeding
Logs before fix:
```
++ df -P /tmp/tmp6771972685998036544/template/tmpl/1/202
+ destcap=557805568
+ '[' 557805568 -lt ']'
/usr/share/cloudstack-common/scripts/storage/secondary/setup-sysvm-tmplt: line 115: [: 557805568: unary operator expected
++ df -P /tmp/cloud/templates/
++ awk '{print $4}'
++ tail -1
+ localcap=16374084
+ '[' 16374084 -lt ']'
/usr/share/cloudstack-common/scripts/storage/secondary/setup-sysvm-tmplt: line 118: [: 16374084: unary operator expected
+ [[ 1 == \1 ]]
```
Post Fix:
```
++ df -P /tmp/tmp18429250753127863419/template/tmpl/1/208
++ awk '{print $4}'
++ tail -1
+ destcap=861523968
+ '[' 861523968 -lt 2120000 ']'
++ df -P /tmp/cloud/templates/
++ awk …
```
=> Add disk space in systemVM template registration script

api/src/main/java/com/cloud/network/vpn/RemoteAccessVpnService.java, api/src/main/java/org/apache/cloudstack/api/command/user/vpn/AddVpnUserCmd.java, api/src/main/java/org/apache/cloudstack/api/command/user/vpn/RemoveVpnUserCmd.java, server/src/main/java/com/cloud/network/vpn/RemoteAccessVpnManagerImpl.java
Fixes #5711
- When the owner account does not have VPN access, VPN user should be added in Add state
- While removing VPN user when the owner account has no VPN, VPN user should be deleted from the database.
=> api, server: fix add-remove vpn user without vpn owner

server/src/main/java/com/cloud/storage/snapshot/SnapshotManagerImpl.java, server/src/test/java/com/cloud/storage/snapshot/SnapshotManagerTest.java
If a snapshot is taken only on Primary storage with the option "snapshot.backup.to.secondary" disabled, and after this when you enable the option the revert will fail. Added check if there isn't a snapshot on Secondary storage to check for it on Primary.
4.15 and main with KVM hypervisors
set `snapshot.backup.to.secondary` to `false`
take one or more snapshots
set `snapshot.backup.to.secondary` to `true`
try to revert the snapshot. The operation will fail with "snapshot [snapshot ID] does not exists in data store"
=> Fix of revert RBD snapshots

api/src/main/java/com/cloud/user/AccountService.java, api/src/main/java/org/apache/cloudstack/acl/APIChecker.java, api/src/main/java/org/apache/cloudstack/api/command/admin/account/CreateAccountCmd.java, api/src/test/java/org/apache/cloudstack/api/command/admin/account/CreateAccountCmdTest.java, plugins/acl/dynamic-role-based/src/main/java/org/apache/cloudstack/acl/DynamicRoleBasedAPIAccessChecker.java, plugins/acl/project-role-based/src/main/java/org/apache/cloudstack/acl/ProjectRoleBasedApiAccessChecker.java, plugins/acl/static-role-based/src/main/java/org/apache/cloudstack/acl/StaticRoleBasedAPIAccessChecker.java, plugins/api/discovery/src/main/java/org/apache/cloudstack/discovery/ApiDiscoveryService.java, plugins/api/discovery/src/main/java/org/apache/cloudstack/discovery/ApiDiscoveryServiceImpl.java, plugins/api/rate-limit/src/main/java/org/apache/cloudstack/ratelimit/ApiRateLimitServiceImpl.java, plugins/hypervisors/baremetal/src/main/java/org/apache/cloudstack/api/BaremetalProvisionDoneNotificationCmd.java, plugins/network-elements/juniper-contrail/src/test/java/org/apache/cloudstack/network/contrail/management/MockAccountManager.java, server/src/main/java/com/cloud/user/AccountManagerImpl.java, server/src/main/resources/META-INF/cloudstack/core/spring-server-core-managers-context.xml, server/src/test/java/com/cloud/user/MockAccountManagerImpl.java
This PR...
Fixes: #5781
Doc PR: https://github.com/apache/cloudstack-documentation/pull/260
=> Role escalation prevention

ui/src/config/section/domain.js
Fixes https://github.com/apache/cloudstack/issues/5973
Allows domain admins to update subdomain limits
=> ui: Allow domain admin to configure subdomain limits

plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java, vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/VirtualMachineMO.java
This PR allows updating the root disk controller type on a stopped VM via the 'rootDiskController' setting
Fixes: #5877 
- Start VM from a template with 'ide' root disk controller setting
- Stop VM
- Change the 'rootDiskController' setting to 'pvscsi'
- Start VM
- Verify the SCSI controllers on VMware Center is set to VMware Paravirtual 
- Stop VM
- Change the 'rootDiskController' setting to 'lsisas1068'
- Start VM
- Verify the SCSI controllers on VMware Center is set to LSI Logic SAS
=> [VMware] Update SCSI controllers for VMs

engine/storage/src/main/java/org/apache/cloudstack/storage/image/deployasis/DeployAsIsHelperImpl.java
This PR fixes an NPE at template installation for Vmware 'Read VM settings from OVA', in case the matches guest OS is removed from database in CloudStack
````
2022-02-06 14:46:23,651 DEBUG [o.a.c.s.i.d.DeployAsIsHelperImpl] (RemoteHostEndPoint-1:ctx-602c7d2b) (logid:5cd127a6) Persisting template details hardware-item-GraphicsController-8 from OVF properties for template 398
2022-02-06 14:46:23,659 INFO  [o.a.c.s.i.d.DeployAsIsHelperImpl] (RemoteHostEndPoint-1:ctx-602c7d2b) (logid:5cd127a6) Guest OS information retrieved from the template: windows9Server64Guest - Microsoft Windows Server 2016 or later (64-bit)
2022-02-06 14:46:23,661 INFO  [o.a.c.s.i.d.DeployAsIsHelperImpl] (RemoteHostEndPoint-1:ctx-602c7d2b) (logid:5cd127a6) Minimum hardware version vmx-15 matched to hypervisor version …
```
=> [Vmware] Prevent NPE on template registration if guest OS is removed

server/src/main/java/com/cloud/user/DomainManagerImpl.java, server/src/test/java/com/cloud/user/DomainManagerImplTest.java
This PR aims to fix the "blank domain UUID" situation, in which the user may provide an empty string as the UUID to the createDomain API. This situation can cause misleading actions in the UI (user trying to delete the wrong domain), and it also makes it impossible to remove the domain that has an empty UUID.
The createDomain API is not testing for empty strings or strings filled with whitespaces; therefore, it is allowing users to create a domain with an invalid UUID. Unless the UUID is manually changed in the DB, it is impossible to work with (or to delete) it.
The proposed solution is to generate a random valid UUID when the given one is a blank; thus,  preventing the reported problem.
Besides that, I decided to refactor a little bit the createDomain method, and added unit tests for …
=> Fix to prevent blank domain UUID

api/src/main/java/org/apache/cloudstack/api/command/user/firewall/CreateEgressFirewallRuleCmd.java, api/src/test/java/org/apache/cloudstack/api/command/user/firewall/CreateEgressFirewallRuleCmdTest.java
When creating a new firewall egress rule, the source and destination CIDRs are considered invalid if they begin or end with a white space, which might happen if the user copy and pastes the CIDRs from somewhere else. This PR aims to remove/clean white spaces from CIDRs, thus making the user experience more fluid. The proposed change is to trim the CIDRs before checking if they are valid.
I extracted the CIDR validation method and also created unit tests for it.
- New unit tests were created to test the behavior of the new method.
- It was also tested in a local lab, by creating new firewall egress rules and inputting source and destination CIDRs with leading or ending with whitespaces.
=> Source and destination CIDR trimming

server/src/main/java/com/cloud/api/query/QueryManagerImpl.java, ui/src/views/compute/DeployVM.vue
Fixes https://github.com/apache/cloudstack/issues/5932
- Adds the ability to set the boot type and mode in the template itself
- Infers the boot type and mode from the template details in the DeployVM form
=> Add option to infer boot type and mode from template

ui/src/config/section/storage.js, ui/src/views/storage/UploadVolume.vue
This PR adds two fields (account and domain) to 'upload volume from local' and 'upload volume from URL' forms. Since the API already supports this feature, only UI changes were made.
This was tested in a local lab by uploading multiple volumes to different accounts at different domains, using both forms, and checking if they were correctly assigned.
=> [UI] Added account field to upload volume

ui/src/views/iam/DomainActionForm.vue, ui/src/views/iam/DomainView.vue
When deleting a domain, the UI shows an error, but successfully deletes the domain. This happens because the UI does not refresh the domain list and requests the deleted domain's information, thus ACS would return an error. This was partially fixed on PR #5710, but the changes were insufficient.
In case there is only 2 domains, for example: 'ROOT' and 'A', when deleting 'A' the UI does not show the previous error, but it still shows the deleted domain's information. The proposed solution to this problem is to force the UI to refresh the component that shows the domain information. Therefore, this PR is intended to introduce these changes.
This was tested in a local lab:
- Make the domain list have only the ROOT and any other domain;
- Delete the domain;
- The ROOT information should be …
=> [UI] fix delete domain

plugins/storage/volume/solidfire/src/main/java/org/apache/cloudstack/storage/datastore/provider/SolidFireHostListener.java, plugins/storage/volume/solidfire/src/main/java/org/apache/cloudstack/storage/datastore/provider/SolidFireSharedHostListener.java
This PR NPE noticed on Simulator env when adding host (SSVM/CPVM) in SolidFireHostListener
Error Logs:
```
2022-02-07 13:05:43,926 ERROR [c.c.s.l.StoragePoolMonitor] (Simulator-Agent-Mgr-1:ctx-b2c1f3d4) (logid:91a7c512) hostAdded(long) failed for storage provider SolidFire
at org.apache.cloudstack.storage.datastore.provider.SolidFireHostListener.hostAdded(SolidFireHostListener.java:81)
at com.cloud.storage.listener.StoragePoolMonitor.processHostAdded(StoragePoolMonitor.java:84)
at com.cloud.agent.manager.AgentManagerImpl.notifyMonitorsOfNewlyAddedHost(AgentManagerImpl.java:551)
at com.cloud.agent.manager.AgentManagerImpl.handleDirectConnectAgent(AgentManagerImpl.java:1532)
at com.cloud.resource.ResourceManagerImpl.createHostAndAgent(ResourceManagerImpl.java:2 …
```
=> [Simulator] Fix NPE in SolidFireHostListener

engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/VolumeOrchestrator.java, server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
This PR fixes an issue attaching a volume to a VM with volume on zone-wide storage pool, for target cluster-wide storage according the disk offering
Fixes: #5916
=> Fix attach volume error for VM - different scope for VM volume and volume disk offering

engine/components-api/src/main/java/com/cloud/hypervisor/HypervisorGuruManager.java, engine/orchestration/src/main/java/com/cloud/agent/manager/AgentManagerImpl.java, server/src/main/java/com/cloud/hypervisor/HypervisorGuruManagerImpl.java
This PR fixes the CopyCommand execute in sequence issue observed in #5925 
Fixes: #5925
=> Fix: allow executing CopyCommand operations in parallel when it is set

ui/src/views/compute/DeployVM.vue
Fixes the issue of not being able to deploy a VM from a deploy-as-is template
=> ui: Pass rootdisksize only if template is not deployasis

services/secondary-storage/server/src/main/java/org/apache/cloudstack/storage/resource/HttpUploadServerHandler.java
When I was trying to upload volumes using CloudMonkey + cURL, the upload would always timeout and the SSVM would not receive the volume's data, even though it was receiving the HTTP headers. By adding this log line, it was possible to find out that cURL sends, by default, a 'Expect: 100-continue' with the HTTP request, and then wait the SSVM response, which never happens. Therefore, this PR proposes to add this log line in case any problems like that in the future happens, they would be more easily discovered by enabling the TRACE log level in the SSVM.
Uploaded volumes using CMK + cURL and read the SSVM's log files.
=> Added a log line to HttpUploadServerHandler
