apache/cloudstack

- server/src/main/java/com/cloud/resource/ResourceManagerImpl.java
This PR fixes the capacity state of cpu core when enable/disable a host.
> server: update capacity_state of host cpu core after disable/enable a host

- ui/src/views/compute/DeployVM.vue
> check security group in basic zones during deploy

- ui/src/views/compute/InstanceTab.vue
When update vm nic ipaddress, but not input an ip address on UI, got an error 'Invalid ip address'.
This PR fixes the issue.
> UI bug fix: 'Invalid ip address' when change vm ip address

- plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/manager/VmwareStorageManagerImpl.java
This PR improves the volume file search on the datastore while computing the VM snapshot chain size in VMware. The file search is now performed in the VM directory on the datastore, instead of all the directories on the datastore (which is leading to incorrect VM snapshot chain size computation when VM id has 6 digits).
Manually tested create and delete VM snapshot operations in VMware, with 6 digit VM ids (set the VM instance sequence manually using the sql: "UPDATE cloud.sequence SET value = 100000 WHERE name = ‘vm_instance_seq’").
- After Create Snapshot:
```
MariaDB [cloud]> SELECT vol.id as volume_id, vol.uuid as volume_uuid, vol.name, vol.volume_type, vol.state, vol.path, vol.size, vol.vm_snapshot_chain_size, vol.chain_info, vol.instance_id, vm.instance_name as instance_name, …
```
> [VMware] Improve volume file search on the datastore while computing the VM snapshot chain size.

- server/src/main/java/com/cloud/api/ApiResponseHelper.java
> internal ref replaced by uuid

- tools/travis/before_install.sh
This PR fixes travis failures due to missing module `setuptools`
> travis: install python3-setuptools

- ui/src/role/index.js
This PR fixes a UI bug caused by #5745 
Fixes: #5780
> UI: fix create Isolated/L2 network form

- ui/src/views/iam/DomainActionForm.vue
This PR fixes https://github.com/apache/cloudstack/issues/5709
1. Error appeared after deleting domain
2. List domain not refresh
> UI: Fixes error when delete domain

- server/src/main/java/com/cloud/vm/UserVmManager.java
- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
This PR allows force reboot VM from user account, and to start VM on the same host.
Fixes: #5742 
Manually tested force reboot VM from user account.
> Allow force reboot VM from user account, to start VM on the same host.

- test/integration/smoke/test_router_dhcphosts.py
This PR cleans up an integration  smoke test
> cleanup of unused code and cleanup of cleanup procedure

- README.md
That time of the year christmas_tree - allow me to get away by merging this PR without tests?
To all of the CloudStack contributors - Happy Christmas and holidays!
/cc alphabetically-ish @alexandremattioli @andrijapanicsb @borisstoyanov @chiradeep @DaanHoogland @davidjumani @DK101010 @Damans227 @GabrielBrascher @gsirett @GutoVeronezi @harikrishna-patnala @kiwiflyer @mlsorensen @msinhore @nathanejohnson @NuxRo @nvazquez @Pearl1594 @pdion891 @ravening @radu-todirica @rp- @shwstppr @slavkap @soreana @steveroles @SadiJr @sureshanaparti @svenvogel @swill @syed @utchoang @vladimirpetrov @weizhouapache @wido @apurv-1 @atrocitytheme @shatoboar @bicrxm @ngrosc @alexandru-bagu @kricud @edikevich @xuanyuanaosheng @tampler @div8cn and so many others! (I may have missed quite a few other handles - …
> README: again that time of the year! :christmas_tree:

- server/src/main/java/com/cloud/api/query/dao/TemplateJoinDaoImpl.java
- ui/src/config/section/image.js
This PR allows ISOs sorting from UI, and updates the Templates/ISOs API response to return in the order of sortkey.
Fixes: #5731
Manually tested the Templates/ISOs sorting from the UI.
> Provision to sort ISOs from UI, and Updated Templates/ISOs API response to return in the order of sortkey.

- ui/src/store/modules/user.js
This PR fixes https://github.com/apache/cloudstack/issues/5749
> UI: Remove unused gravatar fetch

- server/src/main/java/com/cloud/network/element/VpcVirtualRouterElement.java
Sometimes adding network to VPC fails because of libirt error.
In that case the new network wont have any VR's associated with it
and hence it will return null.
```
{ Ans: , MgmtId: 95537038070, via: 346, Ver: v1, Flags: 110, [{"com.cloud.agent.api.PlugNicAnswer":
{"result":false,"details":
" Plug Nic failed due to org.libvirt.LibvirtException: internal error: No more available PCI slots","wait":0}}] }
```
> server: Fix NPE while adding network to VPC

- server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
While deleting a domain, if vlan ip range cant be found
then this will throw NPE. Just return false if vlan ip
range cant be found
```
VLAN information for Account 'Acct[ef5d57e5-4b9d-11e3-8346-2c44fd7a3378-system]', User '1' VLAN '843' is null. This is NPE situation.
Exception deleting domain with id 562
at com.cloud.configuration.ConfigurationManagerImpl.releasePublicIpRange(ConfigurationManagerImpl.java:4660)
at com.cloud.configuration.ConfigurationManagerImpl$14.doInTransactionWithoutResult(ConfigurationManagerImpl.java:6386)
```
> server: Fix NPE while deleting a domain

- ui/src/config/section/infra/clusters.js
- ui/src/config/section/infra/hosts.js
- ui/src/config/section/infra/zones.js
This PR is related to the issue: `ui: Simplify code` #4956
> simplify code using optional chaining in multiple config files

- ui/src/utils/plugins.js
- ui/src/views/infra/network/EditTrafficLabel.vue
- ui/src/views/infra/zone/ZoneWizardLaunchZone.vue
- ui/src/views/network/CreateVpc.vue
- ui/src/views/storage/RestoreAttachBackupVolume.vue
- ui/src/views/storage/TakeSnapshot.vue
- This PR is related to the issue: `ui: Simplify code` #4956
- It uses [object shorthand notation from Javascript - ES6 ](https://alligator.io/js/object-property-shorthand-es6/)to simplify multiple javascript files.
> simplify code using object shorthand in multiple files

- server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
Fix a typo where the word "Security" is misspelled as "Secrity".
This PR fixes a typo of the word "Security".
> Fix a typo when performing network operations

- ui/public/config.json
- ui/src/layouts/UserLayout.vue
- ui/src/style/dark-mode.less
This PR fixes https://github.com/apache/cloudstack/issues/5622
> UI: Add footer text option for login screen

- ui/src/components/CheckBoxSelectPair.vue
- ui/src/views/offering/AddNetworkOffering.vue
- ui/src/views/offering/AddVpcOffering.vue
Fixes issues with form related to supported services provider and router service offering when offering to be created for VPC.
Fixes #5807
> ui: fix add network offering for vpc

- ui/src/views/project/AccountsTab.vue
- ui/src/views/project/InvitationTokenTemplate.vue
- ui/src/views/project/InvitationsTemplate.vue
- This PR is related to the issue: `ui: Simplify code` #4956
- It uses [object shorthand notation from Javascript - ES6 ](https://alligator.io/js/object-property-shorthand-es6/)to simplify JavaScript code in `project` view.
> simplify code using object shorthand in project view

- ui/src/views/compute/CreateSSHKeyPair.vue
- ui/src/views/compute/KubernetesServiceTab.vue
- ui/src/views/compute/MigrateWizard.vue
This PR is related to issue: `ui: Simplify code` #4956
> simplify code using optional chaining in compute views

- ui/src/views/storage/ResizeVolume.vue
This PR fixes https://github.com/apache/cloudstack/issues/5698
> UI - Hide shrink disk option on XCP-NG/Xenserver

- api/src/main/java/org/apache/cloudstack/api/command/admin/vm/RecoverVMCmd.java
This PR fixes the bug that users can recover vms belong to other accounts.
(1) Update global setting `allow.user.expunge.recover.vm`to `true`. restart mgt server.
(2) create domain admin , and deploy a vm
(3) stop the vm, and destroy vm. vm is in Destroyed state.
(4) create another normal user, and recover the vm by cloudmonkey
expected result: permission denied
result without this PR: vm is recovered to Stopped state.
result with this PR: permission denied, same as expected.
> server: fix vm can be recovered by other accounts

- api/src/main/java/com/cloud/storage/Volume.java
> api: fix typo Destroy volume can be recovered

- ui/src/views/offering/AddNetworkOffering.vue
- ui/src/views/offering/AddVpcOffering.vue
> ui: fix create network/vpc offering form

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java
This PR fixes #5531 
branch 4.16
hypervisor KVM
deploy a VM with data disk, the format of ROOT/DATADISK is set to RAW
> Set RAW format to RBD DATADISK

- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
This PR allows deploying VMware appliances missing default values on some properties
Fixes: #5747 
- Register template missing default values on some properties using 'Read Settings from OVA' = true
- Deploy VM
> Prevent null values on Vmware appliances details that are missing a default value

- ui/src/views/compute/DeployVM.vue
- ui/tests/unit/views/AutogenView.spec.js
This PR fixes https://github.com/apache/cloudstack/issues/5842
Fixes error found when entering the "Add Instances" page
Fixes root disk size switch being locked when changing offerings
> UI - Fix Locked "Override Root Disk Size" switch

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtGetStorageStatsCommandWrapper.java
This PR Fixes #5775
Fixes: #5775
> Storage pool absent

- ui/src/views/network/EnableStaticNat.vue
> ui: fix paging in enable static NAT form

- ui/src/views/AutogenView.vue
> ui: fix getDiagnosticsData files field

- ui/src/components/header/SamlDomainSwitcher.vue
- ui/src/store/modules/user.js
> UI: Fixes switching between domains with SAML user

- ui/src/views/compute/DeployVM.vue
Fixes error during VM deployment in a basic zone
Error
- Have a multi-zone setup with one basic zone
- Open deploy vm wizard
- Select basic zone
- Without selecting any security group, try to deploy VM
> ui: fix deploy vm in basic zone

- ui/public/config.json
- ui/src/components/page/GlobalLayout.vue
Add a setting to config.json that allows users to set theme
> UI - Add a setting to config.json that allows users to set theme

- ui/src/config/section/config.js
This PR...
Fixes: #5610 (in part)
This has been tested in the qa env, as it is only a UI change.
> Delete ldap config from UI

- server/src/main/java/com/cloud/network/NetworkServiceImpl.java
> server: fix regular user can create isolated network without sourcenat

- ui/src/components/view/ResourceLimitTab.vue
This is same as PR #5874, for 4.16 branch to fix the domain resource limit fields while accessing/updating for different domains.
Locally tested changing resource limits for different domains in the UI.
> [UI] Fix domain resources field not being updated with backend data

- engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/VolumeOrchestrator.java
This PR fills the volume attached field during the ingest. Is needed for automation purposes to get the same behavior
between ingested vm's and in cs created vm's.
Tested in own VMware env
> fill volume attached field

- ui/src/views/compute/DeployVM.vue
> ui: show password with success notification

- api/src/main/java/com/cloud/agent/api/storage/OVFHelper.java
- api/src/main/java/com/cloud/agent/api/storage/OVFParser.java
- api/src/test/java/com/cloud/agent/api/storage/OVFHelperTest.java
- core/src/main/java/com/cloud/storage/template/OVAProcessor.java
- core/src/test/java/com/cloud/storage/template/OVAProcessorTest.java
This PR refactors the OVF parsing
- Register OVA templates including templates containing prefixes
- Check each template registration is successful and deploy from them
> [Vmware][Deploy-as-is] Refactor the OVF parsing

- packaging/centos7/cloud.spec
- packaging/centos8/cloud.spec
- packaging/suse15/cloud.spec
This fixes spec files to use systemctl enable|disable instead of on|off.
> packaging: use modern systemctl enable/disable

- ui/src/views/AutogenView.vue
- ui/src/views/compute/DestroyVM.vue
This PR fixes https://github.com/apache/cloudstack/issues/5883
> UI: Fixes asynchronous when destroying wrong item VM

- ui/src/views/AutogenView.vue
- ui/src/views/compute/DestroyVM.vue
This PR fixes https://github.com/apache/cloudstack/issues/5885
- Defaults:
- Expand
- Bulk action:
> UI - Added option to allow users to select volumes when doing destroy the list of VMs

- ui/src/views/compute/AttachIso.vue
- ui/src/views/compute/CreateSnapshotWizard.vue
- ui/src/views/compute/DeployVM.vue
- ui/src/views/iam/SSLCertificateTab.vue
- ui/src/views/offering/ImportBackupOffering.vue
- This PR is related to the issue: `ui: Simplify code` #4956
- It uses [object shorthand notation from Javascript - ES6 ](https://alligator.io/js/object-property-shorthand-es6/)to simplify JavaScript code in multiple views.
> simplify code using object shorthand in multiple views

- server/src/main/java/com/cloud/template/HypervisorTemplateAdapter.java
- utils/src/main/java/com/cloud/utils/UriUtils.java
This PR, extends from #5826, allows only direct download templates from IPv6 host address.
Fixes #3047
> Allow direct download templates from IPv6 host address. 

- server/src/main/java/com/cloud/network/NetworkServiceImpl.java
- ui/src/config/section/network.js
> Do not restart VPC tiers with cleanup

- utils/src/test/java/com/cloud/utils/UriUtilsParametrizedTest.java
This PR address the `UriUtilsParametrizedTest` need for Internet connection. The unit tests of the class `UriUtilsParametrizedTest` will fail when they are executed without a connection to the Internet. That happens because of the method `getByName` from `InetAdress` class (that, given the host's name, determines its IP address). Therefore, if one executes the build in a network that does not allow Internet access, or if some DNS configuration is not resolving the configure DNS name in the tests, the tests fail. The goal of the test in that class is not to test DNS, but the validation of the accepted formats. Therefore, we should not depend on DNS, Internet connection, and others.
This PR proposes to solve that problem by mocking the object for the `InetAdress` class. That way, when the …
> Fix internet dependent test from 'UriUtilsParametrizedTest' class

- ui/src/config/router.js
Pass related key of section to route
Fixes #5928
> ui: fix related key for section

- plugins/hypervisors/kvm/src/main/java/org/apache/cloudstack/utils/linux/KVMHostInfo.java
Use lscpu to get the cpu max frequency
Fixes https://github.com/apache/cloudstack/issues/5497
> kvm: Use lscpu to get cpu max speed

- server/src/main/java/com/cloud/usage/UsageServiceImpl.java
This PR...
Fixes: #5860
tested manually:
create a simple setup with one project
enable usage
set a low aggregation time (10 minutes)
create a VPC with one tier and one VM in the project
after the first agregation:
2018 usage records in total
24 usage records for the project
> Filter usage for project

- ui/src/components/view/ListView.vue
- ui/src/views/AutogenView.vue
> ui: fix ssh keypair navigation

- api/src/main/java/org/apache/cloudstack/api/BaseCmd.java
- engine/orchestration/src/main/java/org/apache/cloudstack/engine/cloud/entity/api/VMEntityManagerImpl.java
- plugins/affinity-group-processors/explicit-dedication/src/main/java/org/apache/cloudstack/affinity/ExplicitDedicationProcessor.java
- plugins/deployment-planners/implicit-dedication/src/main/java/com/cloud/deploy/ImplicitDedicationPlanner.java
- server/src/main/java/com/cloud/deploy/DeploymentPlanningManagerImpl.java
- ui/public/locales/en.json
- ui/src/views/offering/AddComputeOffering.vue
This PR adds logging to deploment planners to clarify issues like in #5803. There are no functional changes.
> add logging to deployment planners

- pom.xml
> [issue-5943] upgrade to xerces 2.12.2

- pom.xml
> [issue-5946] upgrade to xstream 1.4.19

- pom.xml
> [issue-5939] upgrade commons-compress to 1.21

- client/pom.xml
- plugins/integrations/kubernetes-service/pom.xml
- pom.xml
- services/console-proxy/rdpconsole/pom.xml
- services/console-proxy/rdpconsole/src/main/java/streamer/bco/BcoSocketWrapperImpl.java
- utils/pom.xml
> [issue-5948] upgrade bouncycastle due to cve

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/DirectVifDriver.java
This PR is a small cleanup where to blocks in an `if ... else ` block do exactly the same.
> cleanup: Network Throttling for Additional Networks code in DirectVifDriver.java 

- pom.xml
> [issue-5952] upgrade to jetty 9.4.44.v20210927

- pom.xml
This PR...
#5943 -- issue with original fix
> [issue-5943] xerces 2.12.2

- ui/src/components/header/ProjectMenu.vue
- ui/src/components/view/BulkActionProgress.vue
- ui/src/components/view/DedicateData.vue
This PR is related to issue #4956 
It is an attempt to improve its readability using optional chaining.
Thank you.
> Optional chaining used to enhance readability

- framework/db/src/main/java/com/cloud/utils/db/GenericDaoBase.java
This PR removes duplicate import for StringUtils
> Removed duplicate import

- ui/public/locales/en.json
This PR improves a help text on dashboard.
> ui: minor change with help text on dashboard

- server/src/main/java/com/cloud/hypervisor/kvm/discoverer/LibvirtServerDiscoverer.java
- server/src/main/java/com/cloud/resource/ResourceManagerImpl.java
This PR improves the error messages displayed when adding a host fails
Fixes: #5677
Tested on KVM env:
- Add host in different scenarios: unreachable IP address, invalid credentials, valid credentials but not KVM enabled
> Improve messages on adding hosts errors

- ui/src/utils/request.js
This PR fixes an issue while trying to assign a VM withing a project into an account
Fixes: #5248
> UI: Fix move VM out of a project

- ui/src/views/network/EgressRulesTab.vue
Fixes a linting issue
Also adds the message in its own alert box
> ui : Fix linting issue

- ui/src/components/view/ListView.vue
- ui/src/components/widgets/Status.vue
Displays yes / no for a router / ilb that requires a version upgrade
> ui: Display yes / no for vm requiring upgrade

- ui/public/locales/ar.json
- ui/public/locales/ca.json
- ui/public/locales/en.json
- ui/public/locales/it_IT.json
- ui/public/locales/pl.json
> ui: add VXLAN network identifiers (VNIs) in message.guest.traffic.in.advanced.zone

- api/src/main/java/org/apache/cloudstack/api/command/user/vm/DeployVMCmd.java
- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
This PR fixes API parameter description for boottype and bootmode
> Fix API parameter description for boottype/bootmode

- plugins/hypervisors/kvm/src/main/java/org/apache/cloudstack/utils/linux/MemStat.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java
- plugins/hypervisors/kvm/src/test/java/org/apache/cloudstack/utils/linux/MemStatTest.java
Fixes maven build unit tests on osx. (Tested on M1 mac)
> Fix osx build

- server/src/main/java/com/cloud/network/ExternalLoadBalancerDeviceManagerImpl.java
- test/integration/component/test_concurrent_snapshots_limit.py
- test/integration/component/test_ip_reservation.py
- test/integration/component/test_lb_secondary_ip.py
- test/integration/component/test_persistent_networks.py
- test/integration/component/test_portable_ip.py
- test/integration/component/test_shared_networks.py
- test/integration/component/test_vpc_network.py
- test/integration/smoke/test_persistent_network.py
- test/integration/testpaths/testpath_stopped_vm.py
- tools/marvin/marvin/lib/common.py
- tools/marvin/marvin/lib/ncc.py
> Fix spelling. Change `Occured` to `Occurred`

- ui/src/views/compute/EditVM.vue
This PR provides the feature to update vm with userdata.
> UI: update vm with userdata

- services/secondary-storage/server/pom.xml
- services/secondary-storage/server/src/main/java/org/apache/cloudstack/storage/resource/HttpUploadServerHandler.java
This PR upgrades netty version to a patched version - CVE: https://github.com/advisories/GHSA-p979-4mfw-53vg
Fixes: #6058
> Upgrade netty version

- ui/src/components/view/ListView.vue
Adds a link in the list view for the role belonging to the account
> ui: Add link to account role in listview

- ui/src/components/header/UserMenu.vue
Fixes the missing user avatar in the header when no icon is present
> ui: Add user initials as avatar if no icon present

- ui/src/components/view/BulkActionProgress.vue
This PR reloads the page to reflect correct status on when a bulk operation is performed and the Progress view is closed.
> UI: Reload page on closing Bulk Action modal

- ui/src/components/view/DedicateData.vue
- ui/src/components/view/InfoCard.vue
This PR fixes router link to domain details
> UI: Fix route to domain details

- ui/src/views/compute/DeployVM.vue
Fixes issue of deploy vm with stay on page option not working
> ui: fix deploy vm stay on page

- ui/src/views/compute/DestroyVM.vue
Fixes issue of switch value not changing
> ui: fix bulk destroy vm with expunge

- ui/src/views/iam/DomainView.vue
This PR fixes https://github.com/apache/cloudstack/issues/6090
> UI: Fixes domain navigation to back

- ui/public/locales/en.json
- ui/src/views/network/EgressRulesTab.vue
This PR fixes alignment issues seen in alert message
> UI: Fix alignment of message

- ui/src/views/iam/ChangeUserPassword.vue
This PR fixes error form.getFieldValue is not a function in change user password form
BEFORE:
AFTER:
> UI - Fixes error form.getFieldValue is not a function in change user password form

- server/src/main/java/com/cloud/user/DomainManagerImpl.java
This PR fixes an error observed during creation of a domain
```
2022-03-15 09:30:04,134 INFO  [c.c.u.DomainManagerImpl] (qtp1007412025-20:ctx-a68b2766 ctx-acce7b84) (logid:c9fdb68b) Domain UUID [5180d5f9-5b60-4034-92e4-0131db9c0e70] generated for domain name [test].
2022-03-15 09:30:04,156 ERROR [o.a.c.f.m.MessageBusBase] (qtp1007412025-20:ctx-a68b2766 ctx-acce7b84) (logid:c9fdb68b) NO EVENT PUBLISH CAN BE WRAPPED WITHIN DB TRANSACTION!
com.cloud.utils.exception.CloudRuntimeException: NO EVENT PUBLISH CAN BE WRAPPED WITHIN DB TRANSACTION!
at org.apache.cloudstack.framework.messagebus.MessageBusBase.publish(MessageBusBase.java:167)
at com.cloud.user.DomainManagerImpl$1.doInTransaction(DomainManagerImpl.java:223)
at com.cloud.user.DomainManagerImpl$1.doInTransaction(DomainManagerImpl.java:21 …
```
> api: Fix issue observed with message publish on creation of domain

- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
This PR fixes: https://github.com/apache/cloudstack/issues/6131
1. Create a VM using custom constrained compute offering
2. Stop VM 
3. Update VM settings - successfully gets updated
4. Start VM - vm starts successfully
> api: Allow updating VM settings when custom constrained offering is used

- server/src/main/java/com/cloud/network/router/VirtualNetworkApplianceManagerImpl.java
> Router health check notification mail to show router name next to UUID

- ui/src/components/view/InfoCard.vue
- ui/src/components/view/ListView.vue
Fixes router links shown to users who can not access resources
NOTE : There might be a smarter way to do this so any inputs are welcome
> ui: Fix router link access

- ui/src/components/view/ListView.vue
Removes <a> tags which can appear as links and mislead users
> ui: Remove misleading anchor tags for users

- ui/src/components/view/ResourceView.vue
- ui/src/views/network/IngressEgressRuleConfigure.vue
This PR fixes the incorrect invocation of API for creation and revocation of ingress / egress security group rules - which is done based on the tab.
> ui, Adv zone + SG: Fix invocation of create/revoke APIs for ingress/egress security group rules

- ui/src/views/infra/network/IpRangesTabPublic.vue
This PR fixes the error when update public IP ranges in advanced zone.
> UI: fix update public IP ranges

- plugins/user-authenticators/saml2/src/main/java/org/apache/cloudstack/saml/SAMLUtils.java
- plugins/user-authenticators/saml2/src/test/java/org/apache/cloudstack/SAMLUtilsTest.java
> SAML: replace first number with random alphabet if request ID starts with a number

- api/src/main/java/com/cloud/network/security/SecurityGroupService.java
- api/src/main/java/com/cloud/vm/UserVmService.java
- engine/schema/src/main/resources/META-INF/db/schema-41610to41700.sql
- plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesCluster.java
- plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java
- plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterVO.java
- plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterActionWorker.java
- plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterResourceModifierActionWorker.java
- plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterStartWorker.java
- server/src/main/java/com/cloud/network/as/AutoScaleManagerImpl.java
- server/src/main/java/com/cloud/network/security/SecurityGroupManagerImpl.java
- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
This PR addresses: #6128 
Deployed a CKS cluster on an Advanced zone with security groups
> CKS: Support deployment of CKS clusters on Advanced zones with security groups

- .gitignore
This PR removes one unneeded line from `.gitignore`
The first one is here:
https://github.com/apache/cloudstack/blob/e339c4b964257c22bde238708f056bd34621446b/.gitignore#L33
> Remove duplicate entry from `.gitignore`

- test/integration/smoke/test_kubernetes_clusters.py
This PR updates test_kubernetes_clusters.py to support advanced zone with security groups
test passes with #6132
> test: update test_kubernetes_clusters.py to support advanced zone with security groups

- systemvm/debian/opt/cloud/bin/cs/CsAddress.py
This PR removes the rules for the ip addresses which are not used.
> VR: Do not add iptables rules for the revoked ip addresses

- server/src/main/java/com/cloud/server/ManagementServerImpl.java
This PR fixes the issue
(1) described in #6186, and 
(2) list reserved public ip in a project
> server: fix list reserved/free public ips in project

- server/src/main/java/com/cloud/user/AccountManagerImpl.java
This PR fixes: #6155  - updates account type to a value corresponding to the role.
Updated role and attempted to login - successfully able to login with new rolw
> api: Update account type when updating account role

- api/src/main/java/org/apache/cloudstack/api/response/NetworkACLResponse.java
- server/src/main/java/com/cloud/api/ApiResponseHelper.java
This PR fixes the vpc uuid in info card of network acls
prior to this PR:
with this PR
> api: add vpcname to networkacl response

- .github/boring-cyborg.yml
- .github/semantic.yml
This introduces two app integration allowed in the apache org:
https://probot.github.io/apps/boring-cyborg/
https://probot.github.io/apps/semantic-pull-requests/
> Probot integrations

- .github/workflows/merge-conflict-checker.yml
Adds a merge conflict checker workflow per current RM (Nicolas's)
request.
> .github: add merge conflict checker per RM request

- .github/workflows/pull-request-checks.yml
- client/pom.xml
- plugins/hypervisors/kvm/src/test/java/org/apache/cloudstack/utils/linux/KVMHostInfoTest.java
- pom.xml
This enables JaCoCo and other quality/history checks for the ASF Jenkins job. Also adds a workflow to generate coverage report for the PR.
> Support JaCoCo and other quality checks

- server/src/main/java/com/cloud/network/vpc/NetworkACLServiceImpl.java
This PR fixes the NullPointerException seen when trying to move the rules of a default ACL
```
2022-03-31 06:59:15,323 ERROR [c.c.a.ApiAsyncJobDispatcher] (API-Job-Executor-42:ctx-d9a17d05 job-53) (logid:47b12a5e) Unexpected exception while executing org.apache.cloudstack.api.command.user.network.MoveNetworkAclItemCmd
at com.cloud.user.AccountManagerImpl.checkAccess(AccountManagerImpl.java:579)
at com.cloud.user.AccountManagerImpl.checkAccess(AccountManagerImpl.java:567)
at jdk.internal.reflect.GeneratedMethodAccessor309.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at …
```
> api: Prevent modifying acl rules order for default ACLs

- ui/src/views/project/ProjectDetailsTab.vue
This PR fixes the issue observed when a normal user is unable to perform any operation in a project where they (account) is the project owner
Vs Behavior in 4.15.x
Post Fix:
> ui: Project owner (normal user) unable to perform any operations in the project

- api/src/main/java/com/cloud/agent/api/storage/OVFParser.java
This PR fixes a sonar finding: https://sonarcloud.io/project/issues?issues=AYAI9l8k5Irk9_td-cXb&open=AYAI9l8k5Irk9_td-cXb&id=apachecloudstack
> potential null pointer in condition; AYAI9l8k5Irk9_td-cXb

- ui/src/api/index.js
- ui/src/store/getters.js
- ui/src/store/modules/user.js
- ui/src/utils/request.js
- ui/src/views/auth/Login.vue
> UI: fixes login button not work and Single Sign-On tab disabled after logout

- systemvm/debian/opt/cloud/bin/configure.py
> VR: add rules for traffic between static nat and private gateway static routes

- ui/.gitignore
This PR makes local/remote env files for the ui be ignored
> local versions of .env ignored

- ui/src/views/infra/network/IpRangesTabPublic.vue
This PR fixes the UI issue that fails to dedicate vlan range to a domain.
(1) open the dedicate vlan range dialog
(2) type a word in `account` field and then remove it 
(3) click 'OK' to dedicate the ip range to a domain
expected result: vlan range is dedicated to a domain
actual result:  got error "Request Failed (431) Unable to find account by name"
> UI: fix dedicate public ip range to domain

- ui/src/views/project/AccountsTab.vue
This PR fixes the issue where in a project admin isn't able to view the action buttons in the Project Accounts tab where one can promote/demote/delete a user/account in a project.
As root admin - one cannot see the above mentioned options:
> ui: Display action buttons in Project Accounts Tab view if project Admin

- ui/src/views/AutogenView.vue
This PR adds the project switch to view k8s / CKS clusters created within a project.
> ui: Add project switch to the Kubernetes tab

- ui/src/components/view/DetailSettings.vue
This PR fixes the issue seen when attempting to update template / VM settings where in users aren't unable to change the existing value.
Post Fix:
> ui: Allow editing VM and template settings

- .github/linters/.flake8
- test/integration/plugins/storpool/MigrateVolumeToStorPool.py
- test/integration/plugins/storpool/TestStorPoolVolumes.py
- test/integration/plugins/storpool/TestTagsOnStorPool.py
- test/integration/plugins/storpool/sp_util.py
- test/integration/smoke/test_vm_snapshot_kvm.py
https://www.flake8rules.com/rules/W293.html
This PR enables flake8 rule W293 and removes some unneeded whitespace
> Enable flake8 W293 blank line contains whitespace

- server/src/main/java/com/cloud/api/ApiServer.java
- server/src/main/java/com/cloud/network/router/NetworkHelperImpl.java
This PR fixes the NPE in travis test
see https://app.travis-ci.com/github/apache/cloudstack/jobs/567879122
this includes #6305
> server: fix NPE in travis and merge #6305

- server/src/main/java/com/cloud/api/ApiResponseHelper.java
This PR removes the 'Default Egress Policy' for vpc tiers.
The ingress/egress access of vpc tiers are controlled by network acl. the default egress policy is not applicable for vpc tiers.
therefore it would be better to remove it in api/ui.
> server: do not display 'Default Egress Policy' for vpc tiers

- ui/src/views/infra/InfraSummary.vue
This PR for fixes InfraSumary screen not display. When a section is not displayed due to permissions not being accessed, an error is generated when router.resolve failed.
> UI: Fixes InfraMammary screen not display

- ui/src/views/infra/Metrics.vue
This PR for fixes the warning display when building UI
> UI: Fixes the warning display when building UI

- ui/src/utils/plugins.js
Fixes route for NetworkAcl type event resource
Before:
After:
> ui: add route for network acl event resource

- ui/src/config/section/infra/systemVms.js
This icon for migrating systemVM when it is stopped. 
Before fix:
Post fix:
> ui: Fix migrate systemVM icon when stopped

- ui/src/views/image/TemplateZones.vue
This PR fixes the issue when trying to delete a template - the pop up to delete doesnt appear at times
> ui: Fix template delete issue

- systemvm/debian/opt/cloud/bin/cs/CsRedundant.py
- systemvm/debian/opt/cloud/bin/setup/common.sh
- systemvm/debian/opt/cloud/bin/setup/init.sh
- test/integration/smoke/test_network_ipv6.py
Fixes radvd setup on VR for isolated network
> systemvm: setup radvd correctly

- plugins/user-authenticators/ldap/pom.xml
Fixes: #6346 
Move LDAP embedded server dependencies to test scope so they aren't packaged in final management server jar.
> Move apache DS dependencies to test scope

- engine/schema/src/main/resources/META-INF/db/schema-41610to41700.sql
Fixes wrong comment for column added for `cloud.event`
> schema,upgrade: fix wrong comment for new columns of cloud.event

- test/integration/smoke/test_network_ipv6.py
This PR fixes trillian test failures caused by wrong icmp type.
> test_network_ipv6.py : remove wrong icmp type

- ui/src/views/infra/Metrics.vue
This PR fixes the refresh button on DB/Usage metrics vue:
> UI: Fix refresh button on Metrics

- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
This PR update VM name, when the new name provided in updateVirtualMachine API is in different case.
```
(test-env) 🐱 > list virtualmachines id=0dd16832-5f07-402d-9238-10c69b6daeb5 filter=id,name,displayname,instancename
{
"count": 1,
{
"displayname": "TestVM02",
"id": "0dd16832-5f07-402d-9238-10c69b6daeb5",
"instancename": "i-2-7-VM",
"name": "testvm02"
}
]
}
(test-env) 🐱 > update virtualmachine id=0dd16832-5f07-402d-9238-10c69b6daeb5 name=TestVM02
{
"cpuused": "14.3%",
"created": "2022-05-11T07:18:25+0000",
"details": {
"cpuOvercommitRatio": "2.0",
"memoryOvercommitRatio": "1.0"
},
"diskioread": 0,
"diskiowrite": 4,
"diskkbsread": 0,
"diskkbswrite": 24,
"displayname": …
```
> Update VM name, when the new name provided in updateVirtualMachine API is in different case.

- ui/src/config/section/infra/managementServers.js
This PR removes a field from the ui that will always be empty
> remove unused UI field

- test/integration/smoke/test_kubernetes_clusters.py
- test/integration/smoke/test_kubernetes_supported_versions.py
- tools/marvin/marvin/config/test_data.py
This PR upgrades k8s to 1.23.3/1.24.0 in smoke test
> cks: upgrade k8s to 1.23.3/1.24.0 in smoke test

- ui/src/config/section/storage.js
- ui/src/views/storage/CreateVolume.vue
This PR fixes error when creating volume from the snapshot
BEFORE:
AFTER:
> UI: Fixes error when creating volume from the snapshot

- ui/src/views/compute/DeployVM.vue
This PR fixes the default value for the hypervisor dropdown at the Deploy VM wizard when ISO is selected
> UI: Fix hypervisor not selected by default when deploying VM from ISO

- api/src/main/java/org/apache/cloudstack/api/command/user/vmsnapshot/CreateVMSnapshotCmd.java
This PR fixes: https://github.com/apache/cloudstack/issues/6444 , where in the async job response shows the db id for the vm snapshot created rather than its uuid.
Prior fix:
Post fix:
> Specify vm snapshot uuid in response over db id in the async job response

- ui/src/store/modules/user.js
This PR for fixes https://github.com/apache/cloudstack/issues/6459
> UI: Fixes UI break with SAML authentication

- ui/src/views/network/LoadBalancing.vue
This PR fixes the issue when create tags for load balancing rules.
without this change
with this change it works.
> UI: fix create tags for LB rules

- server/src/main/java/com/cloud/network/lb/LoadBalancingRulesManagerImpl.java
This PR fixes the issue that update lb rule with new procol does not work, as it is not implemented yet in server side.
> server: update lb rule with new protocol

- ui/src/components/view/SearchView.vue
This PR for fixes error that filtered values ​​are not cleaned when reset button is pressed.
AFTER RESET:
> UI: Clear all filter values after the reset button clicked

- api/src/main/java/com/cloud/event/EventTypes.java
- server/src/main/java/com/cloud/template/TemplateManagerImpl.java
This PR allows to create events of type TEMPLATE_UPDATE for "edit image" functionality (in addition to "create image" and "delete image").
Manually tested.
> Create event TEMPLATE_UPDATE for virtual machine image update calls.

- ui/src/components/view/SearchView.vue
- ui/src/config/section/compute.js
> ui: allow instances to be filtered by group

- .github/workflows/linter.yml
https://github.com/github/super-linter#standard-image
This PR changes the Super Linter to only lint files in the pull request.
Should run much faster too.
refs #6529 
refs #6528
> Lint modified files only with Super-Linter

- framework/db/src/main/java/com/cloud/utils/crypt/EncryptionSecretKeyChanger.java
- setup/bindir/cloud-setup-databases.in
This PR fixes issue #6232 to update the error message and throw the error when updating key file is failed. This helps to find out the proper reason for failure, mainly with umask.
> Updated log message and throw error when unable to update the secret in key file

- plugins/user-authenticators/ldap/pom.xml
- utils/pom.xml
This PR fixes the issue https://github.com/apache/cloudstack/issues/6259.
We have changed the scope of the artifacts embedded-ldap-junit and commons-io as appropriate.
> Scope setting changes in ldap and utils pom.xml files

- ui/src/views/compute/DeployVM.vue
> ui: fix deploy vm override custom disk offering

- ui/src/views/network/VpcTiersTab.vue
Fixes loadbalancers listing in VPC tier UI
> ui: fix vpc loadbalancer listing for admins

- ui/src/config/section/infra/routers.js
Fixes icon in router view for migrate storage
Before
After
> ui: fix icon for vr migrate storage

- ui/src/components/view/ResourceLimitTab.vue
This PR fixes https://github.com/apache/cloudstack/issues/6602
> UI: Fixes notification error can't close when exit config limit tab

- ui/src/components/view/ListView.vue
- ui/src/main.js
- ui/src/utils/plugins.js
- ui/src/views/AutogenView.vue
- ui/tests/common/index.js
Addresses #6569
Use uuid to list SSH keypair wherever uuid is available.
> ui: use ssh keypair uuid for listing

- ui/src/views/compute/ScaleVM.vue
> ui: reset disksize param on offering change in scale vm

- ui/src/components/view/DetailsTab.vue
This PR for fixes the warning in detail tab
> UI - Fixes the warning in detail tab

- ui/src/views/offering/AddComputeOffering.vue
Fixes `gpuType` value in the add compute offering form during submit
> ui: fix gputype in add compute offering

- server/src/main/java/com/cloud/tags/TaggedResourceManagerImpl.java
- server/src/test/java/com/cloud/tags/TaggedResourceManagerImplTest.java
Fixes #6623
This PR fixes resource tag deletion behaviour. The permission check should be done only for the tags that are passed in the API call instead of checking for all the tags for the resource.
> server: fix delete resource tag permission

- ui/src/components/view/InfoCard.vue
> ui: fix resource tags visibility in infocard

- plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java
Fixes #6657 
Deployed a k8s cluster with service offering having hosttag as tag1 and the hypervisor host having tags a tag1,tag2,tag3.
Hypervisor hosts
```
> list hosts type=Routing filter=id,name,hosttags
{
"count": 2,
"host": [
{
"id": "80492e2e-017c-497e-8291-3f4baaf57501",
"name": "10.0.35.44"
},
{
"hosttags": "tag1,tag2,tag3",
"id": "8dc82fb8-ee97-4a7e-94e2-977c82a7bdd9",
"name": "10.0.33.154"
}
]
}
```
Service offering
```
> list serviceofferings id=49e553d7-a1d7-4ef3-a139-a90a5a0f3003 filter=id,name,hosttags,
{
"count": 1,
{
"hosttags": "tag1",
"id": "49e553d7-a1d7-4ef3-a139-a90a5a0f3003",
"name": "CKS Instance"
}
]
}
```
k8s Cluster with node VMs deployed on the desired host,
```
> create kubernetescluster zoneid=9a95cda0-12fa-4f98-ab4b-ad386ca4ecb0 …
```
> cks: fix k8s cluster deployment with host tagged offering

- ui/src/components/header/ProjectMenu.vue
- ui/src/components/header/SamlDomainSwitcher.vue
- ui/src/style/ant-overwrite/ant-form.less
- ui/src/style/vars.less
- ui/src/views/AutogenView.vue
This PR for fixes https://github.com/apache/cloudstack/issues/6667
> UI: Fixes suffix icon on project selector not work

- ui/src/views/network/UpdateNetwork.vue
Fixes wrong param used in the update network form
> ui: fix update network updateinsequence param

- ui/src/components/widgets/Console.vue
This PR for fixes errors in the Console.vue
> UI: fixes errors in the Console.vue

- engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/VolumeOrchestrator.java
- engine/storage/src/main/java/org/apache/cloudstack/storage/allocator/AbstractStoragePoolAllocator.java
- engine/storage/src/main/java/org/apache/cloudstack/storage/allocator/ClusterScopeStoragePoolAllocator.java
- engine/storage/src/main/java/org/apache/cloudstack/storage/allocator/GarbageCollectingStoragePoolAllocator.java
- engine/storage/src/main/java/org/apache/cloudstack/storage/allocator/LocalStoragePoolAllocator.java
- engine/storage/src/main/java/org/apache/cloudstack/storage/allocator/ZoneWideStoragePoolAllocator.java
- plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageProcessor.java
- plugins/storage-allocators/random/src/main/java/org/apache/cloudstack/storage/allocator/RandomStoragePoolAllocator.java
- vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/ClusterMO.java
- vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/HypervisorHostHelper.java
- vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/VirtualMachineMO.java
This PR improves and adds new logs to volume creation to facilitate future troubleshooting.
This was tested in a local lab, by creating volumes and checking if the logs were all correct.
> Added new logs to volume creation

- api/src/main/java/org/apache/cloudstack/api/command/user/tag/CreateTagsCmd.java
> api: fix event type and description for createTag

- usage/src/main/java/com/cloud/usage/UsageManagerImpl.java
> fix usage charging for deleted/resized volumes

- systemvm/debian/opt/cloud/bin/configure.py
- systemvm/debian/opt/cloud/bin/cs/CsAddress.py
> vr: fix packet interface mismatch

- ui/src/components/view/InfoCard.vue
This PR for fixes https://github.com/apache/cloudstack/issues/6731
> UI: Fixes login failed after session expired

- ui/src/views/infra/network/IpRangesTabGuest.vue
- ui/src/views/infra/network/IpRangesTabManagement.vue
- ui/src/views/infra/network/IpRangesTabPublic.vue
- ui/src/views/infra/network/IpRangesTabStorage.vue
This PR for fixes https://github.com/apache/cloudstack/issues/6787
> UI: Fixes UI style on Microsoft Edge browser

- server/src/test/java/com/cloud/deploy/DeploymentPlanningManagerImplTest.java
previously
```
[INFO] Running com.cloud.deploy.DeploymentPlanningManagerImplTest
at com.cloud.deploy.DeploymentPlanningManagerImpl.planDeployment(DeploymentPlanningManagerImpl.java:403)
at com.cloud.deploy.DeploymentPlanningManagerImplTest.failEncRootLastHostNotSupportingEncryptionTest(DeploymentPlanningManagerImplTest.java:644)
...
[INFO] Tests run: 27, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.407 s - in com.cloud.deploy.DeploymentPlanningManagerImplTest
```
with this PR
```
[INFO] Running com.cloud.deploy.DeploymentPlanningManagerImplTest
[INFO] Tests run: 27, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.481 s - in com.cloud.deploy.DeploymentPlanningManagerImplTest
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 27, Failures: 0, Errors: …
```
> server: fix exception in DeploymentPlanningManagerImplTest

- packaging/centos7/cloud.spec
- packaging/centos8/cloud.spec
- packaging/suse15/cloud.spec
`createtmplt.sh` will use `file`, and `setup-sysvm-tmplt` will use `which`. this is log:
```
/usr/share/cloudstack-common/scripts/storage/secondary/setup-sysvm-tmplt: line 74: which: command not found
/usr/share/cloudstack-common/scripts/storage/secondary/createtmplt.sh: line 56: file: command not found
/usr/share/cloudstack-common/scripts/storage/secondary/createtmplt.sh: line 75: file: command not found
/usr/share/cloudstack-common/scripts/storage/secondary/createtmplt.sh: line 42: file: command not found
/usr/share/cloudstack-common/scripts/storage/secondary/setup-sysvm-tmplt: line 74: which: command not found
/usr/share/cloudstack-common/scripts/storage/secondary/createtmplt.sh: line 56: file: command not found
/usr/share/cloudstack-common/scripts/storage/secondary/createtmplt.sh: …
```
> Fix: rpm dependencies: which and file

- systemvm/debian/opt/cloud/bin/cs/CsAddress.py
This PR...
Fixes: #6834
manual for now
> add ip rule for VPC extra IPs

- ui/src/views/storage/FormSchedule.vue
This PR changes the time format used in the recurring snapshot form to the 24-hour time format, as the current 12-hour time format is not the ACS standard.
Before:
After:
I applied the changes in a local lab, and checked if the time format was displayed correctly and if the time was saved and processed properly.
> Fix recurring snapshot form time format

- server/src/main/java/com/cloud/tags/TaggedResourceManagerImpl.java
- server/src/test/java/com/cloud/tags/TaggedResourceManagerImplTest.java
> Check for null volume pool ID when tagging

- plugins/affinity-group-processors/host-affinity/src/main/java/org/apache/cloudstack/affinity/HostAffinityProcessor.java
> host affinity: fix vm cannot be started if a vm is stopped in the affinity group

- plugins/hypervisors/kvm/src/main/java/org/apache/cloudstack/utils/qemu/QemuImg.java
This PR improves the javadocs of the class `QemuImg` by fixing grammatical errors, cleaning up methods that were not implemented, enhancing existing documentation and adding new. 
I built the code in a local lab and checked that there were no errors.
> Improvements and cleanup on the javadocs of QemuImg

- test/integration/smoke/test_vm_lifecycle_unmanage_import.py
Add smoke test to prevent any regression such as #6951.
Test now adds three networks to the VM, unmanages the VM and then imports the VM to verify that it returns all 3 NICs and other relevant VM details.
```
[root@pr6953-t5437-vmware-67u3-marvin marvin]# nosetests --with-xunit --xunit-file=results.xml --with-marvin --marvin-config=./pr6953-t5437-vmware-67u3-advanced-cfg -s -a tags=advanced --hypervisor=VMware tests/smoke/test_vm_lifecycle_unmanage_import.py 
/usr/local/lib/python3.6/site-packages/paramiko/transport.py:33: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
from cryptography.hazmat.backends import default_backend
==== Marvin Init Started …
```
> test: add nic validation in import vm test

- api/src/test/java/org/apache/cloudstack/api/command/test/ResetVMUserDataCmdTest.java
Similar as [6875](https://github.com/apache/cloudstack/pull/6875).
The test `org.apache.cloudstack.api.command.test.ResetVMUserDataCmdTest.testUserdataDetails`, is a [flaky tests](https://docs.gitlab.com/ee/development/testing_guide/flaky_tests.html). It can pass mvn test but when run using the tool [NonDex](https://github.com/TestingResearchIllinois/NonDex), it fails. NonDex is a tool that will introduce non-determinism in certain java collections.
The cause of failure is because the test is comparing the string format of two hashmaps, however, as per [Oracle's documentation](https://docs.oracle.com/javase/7/docs/api/java/util/HashMap.html):
> The HashMap class is roughly equivalent to Hashtable, except that it is unsynchronized and permits nulls. This class makes no guarantees as to the …
> Fixed flaky test in ResetVMUserDataCmdTest.java

- debian/control
This PR fixes the marvin build error for ubuntu
it looks there is a regression in the marvin build , related to #6889 
```
[INFO] --- exec-maven-plugin:1.2.1:exec (package) @ cloud-marvin ---
File "setup.py", line 20, in <module>
from setuptools import setup, find_packages
ImportError: No module named 'setuptools'
During handling of the above exception, another exception occurred:
File "setup.py", line 23, in <module>
from distribute_setup import use_setuptools
ImportError: No module named 'distribute_setup'
During handling of the above exception, another exception occurred:
File "setup.py", line 27, in <module>
raise RuntimeError("python setuptools is required to build Marvin") …
```
> debian build: add python3-setuptools to dependencies

- tools/git/git-pr
This PR...
commited manually on a local `main` and executed `git pr 6956 --force`
> git-pr py3 compatible

- plugins/api/rate-limit/src/main/java/org/apache/cloudstack/ratelimit/ApiRateLimitServiceImpl.java
- plugins/api/rate-limit/src/test/java/org/apache/cloudstack/ratelimit/ApiRateLimitTest.java
This PR...
Fixes: #6975 
unit test
> make api rate limit test a little more robust

- README.md
Screenshot for changes:
Hope this can be merged without packaging or smoketests before end of the year ;)
To all of the CloudStack contributors - Happy Christmas and holidays!
/cc alphabetically-ish @alexandremattioli @andrijapanicsb @borisstoyanov @BryanMLima @chiradeep @csquire @DaanHoogland @davidjumani @DK101010 @Damans227 @GabrielBrascher @gsirett @GutoVeronezi @harikrishna-patnala @jbampton @JoaoJandre @kiwiflyer @kishankavala @mlsorensen @msinhore @nathanejohnson @NuxRo @nvazquez @Pearl1594 @pdion891 @rahulbcn27 @ravening @radu-todirica @rp- @SadiJr @shwstppr @slavkap @soreana @steveroles @SadiJr @sureshanaparti @svenvogel @swill @syed @utchoang @vladimirpetrov @weizhouapache @wido @alexandru-bagu @kricud @edikevich @xuanyuanaosheng @tampler @div8cn and so many others! (may have …
> README: that time of the year! :christmas_tree:

- api/src/main/java/com/cloud/network/NetworkModel.java
- server/src/main/java/com/cloud/network/NetworkModelImpl.java
- server/src/main/java/com/cloud/network/NetworkServiceImpl.java
- server/src/test/java/com/cloud/network/NetworkModelTest.java
- test/integration/component/test_acl_sharednetwork.py
- utils/src/main/java/com/cloud/utils/StringUtils.java
> Allow root admin to deploy in VPCs in child domains

- ui/src/views/compute/DeployVM.vue
- ui/src/views/compute/wizard/NetworkConfiguration.vue
Fixes #6974
https://user-images.githubusercontent.com/153340/207843215-9c106497-e388-4ef8-8ca9-3c29d9a79010.mp4
> ui: persist networks config in deploy vm form

- test/integration/smoke/test_templates.py
This PR adds the newest checksums to the vmware version of the macchinina template.
> checksums for new macchinina ova template

- .github/linters/.flake8
Can be run locally with:
```
cloudstack % flake8 --select=E223,E224,E242,E273,E274,E901,E902,W291,W292,W293,W391 .
```
https://www.flake8rules.com/
This PR add seven more `flake8` checks.
https://flake8.pycqa.org/en/latest/index.html
> gha(linters): enable 7 more Python `flake8` checks

- debian/cloudstack-usage.postinst
- packaging/centos7/cloud.spec
- packaging/centos8/cloud.spec
- packaging/suse15/cloud.spec
- usage/src/main/java/com/cloud/usage/UsageManagerImpl.java
- usage/src/main/java/com/cloud/usage/UsageSanityChecker.java
This PR...
Fixes: #5156
- set inteval to 10 mins
- let it run for several days.
- reset last check id to 1
- run cli sanity check
- rerun cli sanity check
- let it run for several more days
-
> resolve sanity check last id file acces problems

- server/src/test/java/com/cloud/configuration/ConfigurationManagerImplTest.java
This PR fixes a broken test on `configurationManagerImplTest`.
> server: fix broken unit test in configurationManagerImplTest

- .github/workflows/ui.yml
- ui/tests/mockData/AutogenView.mock.json
- ui/tests/unit/components/view/ActionButton.spec.js
- ui/tests/unit/views/AutogenView.spec.js
This PR fixes the UI test errors.
```
$ npm run test:unit
=============================== Coverage summary ===============================
Statements   : 5.54% ( 1322/23850 )
Branches     : 5.42% ( 636/11724 )
Functions    : 2.59% ( 189/7311 )
Lines        : 5.63% ( 1304/23143 )
================================================================================
Test Suites: 4 passed, 4 total
Tests:       175 passed, 175 total
Snapshots:   0 total
Time:        16.175s
Ran all test suites.
```
> UI: fix ui test errors

- ui/tests/unit/components/view/ActionButton.spec.js
The usual command "npm run serve" is failing with below error due to extra semicolons.
error: Extra semicolon (semi) at tests/unit/components/view/ActionButton.spec.js:275:64:
273 |           }
274 |         })
> 275 |         wrapper.vm.hasOwnProperty = () => Object.hasOwnProperty;
|                                                                ^
276 |         const handleShowBadge = jest.spyOn(wrapper.vm, 'handleShowBadge')
277 |         await wrapper.setProps({ resource: null })
278 |
> local npm run failing with error

- engine/schema/src/main/resources/META-INF/db/schema-41720to41800.sql
> add index to speed up querying IPs in the network-tab

- tools/git/git-fwd-merge
This PR fixes the cli tool `git fwd-merge`
> fix merge diff display

- ui/src/views/storage/FormSchedule.vue
This PR fixes #7051 
The value of "Keep" when create snapshot policy was automatically reset to 8 if the input is greater than 8.
However, the max value of recurring snapshots is determined by global settings snapshot.max.daily / snapshot.max.hourly / snapshot.max.monthly / snapshot.max.weekly, which is 8 by default, but users can input other values greater than 8.
This PR removes this restriction on UI and cloudsack management server will check if the value is valid.
<br class="Apple-interchange-newline">
> UI: remove max value (8) of maxsnaps because it might be greater than 8

- ui/src/components/view/BulkActionProgress.vue
- ui/src/components/view/BulkActionView.vue
- ui/src/views/network/LoadBalancing.vue
This PR fixes an UI issue that LB rules cannot be listed for kubernetes cluster.
> UI: fix cannot list lb rules if cidr_list is NULL

- ui/src/views/offering/AddVpcOffering.vue
This PR fixes #7042 
no supported services
"SourceNat" is checked
> UI: support serviceofferingid when create vpc offering

- services/secondary-storage/server/src/main/java/org/apache/cloudstack/storage/resource/NfsSecondaryStorageResource.java
Use synchronised in NfsSecondaryStorageResource when adding iptables and routing rules.
> ssvm: synchorise when adding iptables and routing rules

- server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
- ui/src/views/offering/AddNetworkOffering.vue
This PR fixes some issues with network offering details
(1) on UI: the serviceofferingid and maclearning is not passed to API when create network offering
(2) when create network offering, the details are not saved except internetprotocol, including
Promiscuous mode 
MAC address changes 
Forged transmits 
MAC learning 
(3) network offering details are not removed when delete a network offering.
> server/UI: fix some issues with network offering details

- pom.xml
This PR fixes an issue in the owasp dependency checker. See https://github.com/jeremylong/DependencyCheck/issues/5220
> update owasp dep checker for 'column width bug'

- engine/schema/src/main/java/com/cloud/service/ServiceOfferingVO.java
This PR fixes #6780
The issue can be reproduced by
(1) create a unconstraint dynamic offering
(2) deploy a vm and stop it
(3) update vm settings
> server: fix cannot update vm if it uses unconstraint dynamic offering

- ui/src/views/compute/KubernetesServiceTab.vue
This PR fixes #6929
in advanced network with SG, firewall/load balancing/port forwarding are not supported. However, they are still displayed on UI.
prior to this change
with this change
> UI: do not show FW/LB/PF tabs for CKS cluster in advanced network with SG

- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
VMs are set to Expunging state if there are some errors during expunging process (e.g. network issue or storage issue, VR issue). After that, vm is not usable, but we cannot expunge it.
This PR fixes the issue above by allowing the retry of expunging process.
How to test it
(1) create a vm, stop it
(2) destory the vm
(3) update vm state to 'Expunging' by manual db change
(4) try to expung the vm. Prior to this, it fail. It works with this change
> server: allow expunging VMs in Expunging state

- plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java
> CKS: do not save cks username/password which are useless

- ui/src/components/view/InfoCard.vue
> UI: display cpu cores and speed instead of cputotal by default

- ui/src/config/section/storage.js
- ui/src/views/AutogenView.vue
This fixes #6993
- list volumes in a project with filter=User , by root admin
- list volumes in a project with filter=All , by root admin
- list volumes in a project, by domain admin (no filter)
> UI: add filter user/all to list user/all volumes

- api/src/main/java/org/apache/cloudstack/api/response/SSHKeyPairResponse.java
- server/src/main/java/com/cloud/api/ApiResponseHelper.java
- ui/src/config/section/compute.js
> api/server: add project id/name in ssh keypair response

- plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterDestroyWorker.java
This PR removes the cks cluster details from kubernetes_cluster_details table, when the cluster is removed.
> CKS: remove details when delete a cks cluster

- api/src/main/java/org/apache/cloudstack/api/command/admin/host/UpdateHostPasswordCmd.java
- api/src/test/java/org/apache/cloudstack/api/command/test/UpdateHostPasswordCmdTest.java
This PR fixes that issue new password is applied on host when update host password with update_passwd_on_host=false
prior to this change, this cmd command updated the host password
with this change, this cmd command did not update the host password.
(localcloud) 🐱 > update hostpassword hostid=cc83a7ed-8387-4d99-b1bf-4ded51e91aa7 password=password username=root update_passwd_on_host=false
{
"success": true
}
> api: fix new password is applied on host when update host password with update_passwd_on_host=false

- core/src/main/java/com/cloud/agent/api/routing/IpAssocCommand.java
- core/src/main/java/com/cloud/agent/api/routing/IpAssocVpcCommand.java
- core/src/main/java/com/cloud/agent/api/routing/NetworkElementCommand.java
- core/src/main/java/com/cloud/agent/api/routing/SetFirewallRulesCommand.java
- core/src/main/java/com/cloud/agent/api/routing/SetIpv6FirewallRulesCommand.java
- core/src/main/java/com/cloud/agent/api/routing/SetMonitorServiceCommand.java
- core/src/main/java/com/cloud/agent/api/routing/SetNetworkACLCommand.java
- core/src/main/java/com/cloud/agent/api/routing/SetPortForwardingRulesCommand.java
- core/src/main/java/com/cloud/agent/api/routing/SetStaticNatRulesCommand.java
- core/src/main/java/com/cloud/agent/api/routing/SetStaticRouteCommand.java
- core/src/test/java/com/cloud/agent/resource/virtualnetwork/ConfigHelperTest.java
> VR: fix warning Expected X answers while executing SetXXXCommand but Y

- plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterUpgradeWorker.java
- plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/utils/KubernetesClusterUtil.java
- plugins/integrations/kubernetes-service/src/test/java/com/cloud/kubernetes/cluster/utils/KubernetesClusterUtilTest.java
This PR fixes the smoke test failure test_08_upgrade_kubernetes_ha_cluster
> CKS: fix upgrade of HA cluster

- packaging/centos8/cloud.spec
Adds tar as dependency used for VMware to seed systemvmtemplate on mgmt server
> Adds tar as dependency used for VMware to seed systemvmtemplate on mgmt server 

- server/src/main/java/org/apache/cloudstack/network/topology/BasicNetworkVisitor.java
This fixes #6765
The following command (in vm) worked before acquiring IP but did not work after that 
`root$ curl http://<gateway>/latest/meta-data/public-keys`
in VR, the file is empty:
```
root@r-40-VM:/var/www/html/metadata/<VM IP># ls -l public-keys
-rw-r--r-- 1 root root 0 Jan 17 18:41 public-keys
```
> VR: fix public-key is missing in VR after acquiring public IP

- plugins/metrics/src/main/java/org/apache/cloudstack/metrics/MetricsServiceImpl.java
- plugins/metrics/src/main/java/org/apache/cloudstack/response/DbMetricsResponse.java
- server/src/main/java/com/cloud/server/StatsCollector.java
This PR fixes server statistics for long running systems
> Use long instead of int in DB statistics for Queries and Uptime.

- ui/public/locales/en.json
This PR fixes the UI not loading due to unresolved merge conflict
> Fix UI not loading after merge conflict issue

- .github/workflows/docker-cloudstack-simulator.yml
Now the images are pushed to
https://hub.docker.com/r/asfjenkins/cloudstack-simulator/tags
Need to move to apache/cloudstack-simulator
> .github: set docker repository to apache

- ui/src/views/compute/wizard/SecurityGroupSelection.vue
> UI: fix security group lists in project view

- ui/src/views/setting/ConfigurationTab.vue
This PR fixes the issue https://github.com/apache/cloudstack/issues/7187 of login after logout operation from configuration page.
- Logout from configuration page
- We should not see any error notifications regarding session
- Immediate login without refresh should work
> Fix login issue after logout from Configuration page

- .github/workflows/codecov.yml
This PR skips the coverage check instead of failing when forks are updated.
After this PR is merged and forks are updated it should skip the check.
Shows the failing check
> Skip Coverage Check when forks are updated

- .github/workflows/sonar-check.yml
This PR disables sonar jacoco check on forks.
> .github: disable Sonar check on forks as it requires crendential

- ui/public/locales/en.json
- ui/src/config/section/offering.js
This PR fixes one missing label and one edit icon
Edit Template
Edit Backup offering icon
> UI missing changes

- .github/workflows/docker-cloudstack-simulator.yml
When push a tag to repository, use the TAG name as the docker image name.
> .github: use ref name as docker image name if ref type is tag

- packaging/centos8/cloud.spec
> packaging: fix centos8/el8 upgrade

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
> cleanup: remove testing logs

- ui/src/views/network/LoadBalancing.vue
This fixes an error message when create load balancer as a normal user
> UI: fix error message when create load balancer as a normal user

- engine/schema/src/main/java/com/cloud/upgrade/dao/Upgrade41810to41900.java
Fixes wrong schema path in 419 upgrade
> Fix schema path for 419 upgrade path

- ui/public/locales/en.json
- ui/src/views/infra/HostInfo.vue
This PR fixes #7356 adds the UEFI flag like below in Host details
> [UI] UEFI support flag in host details

- api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
- api/src/main/java/org/apache/cloudstack/api/response/ManagementServerResponse.java
- server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
This PR fixes # https://github.com/apache/cloudstack/issues/7338
Added Mgmt server Service IP to listManagementServers API response
Test API response with cmk
```
(local) 🐱 > list managementservers
{
"count": 1,
"managementserver": [
{
"id": "76942b7f-00cc-4ff6-89ec-0d16bdcf2919",
"javadistribution": "Ubuntu",
"javaversion": "11.0.18+10-post-Ubuntu-0ubuntu122.04",
"lastboottime": "2023-03-25T18:14:53+0530",
"lastserverstart": "2023-03-28T14:10:19+0530",
"lastserverstop": "2023-03-28T14:02:23+0530",
"name": "KK.",
"osdistribution": "Ubuntu 22.04.1 LTS",
"serviceip": "127.0.0.1",
"state": "Up",
"version": "4.18.1.0-SNAPSHOT"
}
]
}
```
> Add Service Ip to listManagementServers API response

- ui/src/views/network/CreateL2NetworkForm.vue
This PR fixes #7377 
**************************************************************************** -->
tested the changes internally on docker simulator
> UI: fixed L2 network creation for particular account/domain

- api/src/main/java/org/apache/cloudstack/api/command/user/network/CreateNetworkCmd.java
- server/src/main/java/com/cloud/network/NetworkServiceImpl.java
To address the issue #7308, some details about the account and domain to which network will belong are added.
> Added details of account in network creation

- pom.xml
Upgrades to some dependencies that address CVEs and improvements
> pom.xml: bump only required dependencies

- ui/src/views/compute/CreateAutoScaleVmGroup.vue
> ui: show only advanced zones for vmautoscale form

- engine/components-api/src/main/java/com/cloud/storage/StorageManager.java
- engine/storage/volume/src/main/java/org/apache/cloudstack/storage/datastore/provider/DefaultHostListener.java
- server/src/main/java/com/cloud/storage/StorageManagerImpl.java
This fix ensures when datastore cluster in VMware is added as a primary storage pool in CloudStack then all the child datastores (which already exists in CS) should be in Up state.
For example:
1. Datastore Cluster DS has two child datastores A and B in vCenter. (B is already added as a storage pool in CloudStack)
2. Now try to add datastore cluster DS into CloudStack as a primary storage pool
3. CloudStack tries to add child datastores A and B in CloudStack, since B is already there in CloudStack, it will reuse the existing storagepool entry and will keep under parent Storage pool DS.
During Step 3 we are now checking if B is Up state or not.
> Adding Datastore cluster as primary storage should check if the child datastores are in Up state

- api/src/main/java/org/apache/cloudstack/acl/RoleService.java
- api/src/main/java/org/apache/cloudstack/api/command/admin/acl/ListRolesCmd.java
- engine/schema/src/main/java/org/apache/cloudstack/acl/dao/RoleDao.java
- engine/schema/src/main/java/org/apache/cloudstack/acl/dao/RoleDaoImpl.java
- plugins/metrics/src/main/java/org/apache/cloudstack/metrics/MetricsServiceImpl.java
- server/src/main/java/com/cloud/network/vpc/VpcManagerImpl.java
- server/src/main/java/com/cloud/server/ManagementServerImpl.java
- server/src/main/java/org/apache/cloudstack/acl/RoleManagerImpl.java
- server/src/main/java/org/apache/cloudstack/backup/BackupManagerImpl.java
- server/src/test/java/org/apache/cloudstack/acl/RoleManagerImplTest.java
- ui/src/views/AutogenView.vue
- ui/tests/unit/views/AutogenView.spec.js
This PR fixes #7362 and also other search criteria to use the name as an exact search where keyword is also there.
Made UI changes for roles search to make use of keyword instead of name.
> Roles search by keyword

- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
> server: rephrase error message for iso vm reinstall

- ui/src/components/page/GlobalLayout.vue
This PR ensures the shutdown header matches the ant design specs
> Fix shutdown header to match antdv design

- engine/schema/pom.xml
- engine/schema/src/test/java/com/cloud/upgrade/DatabaseVersionHierarchyTest.java
This PR fixes that tests were not run in the engine/schema project because of a mix of junit4 and junit5.
run unit tests
> engine/schema: use junit 4 (as the rest of the project tests)

- api/src/main/java/org/apache/cloudstack/api/command/admin/annotation/AddAnnotationCmd.java
This PR adds documentation to the addAnnotation api call
https://cloudstack.apache.org/api/apidocs-4.18/apis/addAnnotation.html
It basically shows all the supported entity types 
********** -->
> added the various entity types supported by the addAnnotation api call

- tools/build/setnextversion.sh
(1) on ubuntu server, run "git checkout 4.17.2.0"
(2) packaging
cd packaging/
./build-deb.sh -b test1
expected result: succeed
actual result:
[ERROR] The build could not read 1 project -> [Help 1] [ERROR]
[ERROR]   The project org.apache.cloudstack:cloud-apidoc:4.17.2.0-test1-test1 (/data/cloudstack/tools/apidoc/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.apache.cloudstack:cloud-apidoc:4.17.2.0-test1-test1: Could not find artifact org.apache.cloudstack:cloud-tools:pom:4.17.2.0-test1-test1 in central (https://repo.maven.apache.org/maven2) and 'parent.relativePath' points at wrong local POM @ line 25, column 13 -> [Help 2]
> fix tools/build/setnextversion.sh: do not update tools/apidoc/pom.xml

- ui/public/locales/en.json
- ui/src/views/compute/AutoScaleUpPolicyTab.vue
- ui/src/views/compute/ScaleVM.vue
- ui/src/views/storage/MigrateVolume.vue
Some UI actions were missing title and description in pollJob method preventing notification for them to be published.
> ui: fix action notifications

- ui/src/views/network/VpcTiersTab.vue
This PR fixes the issue that sourceIP is not passed when create internal LB on UI.
> UI: fix sourceIP is not passed when create internal LB

- services/secondary-storage/controller/src/main/java/org/apache/cloudstack/secondarystorage/SecondaryStorageManagerImpl.java
> ssvm: continue with other secondary storages if fails to program a secondary storage

- .asf.yaml
Add my username to the .asf.yml file to be able to report issue with tags, and be assigned to issues and PRs.
> Added soreana to the .asf.yml

- .github/workflows/ui.yml
package-lock.json is not removed.
> github-actions: fix ui build workflow

- tools/marvin/marvin/deployDataCenter.py
This PR fixes TypeError. The file is written in a binary format and needs to be read in binary format as well.
```
TypeError: a bytes-like object is required, not 'str'
```
> marvin: Fix deployDataCenter's cleanup

- ui/src/views/network/IngressEgressRuleConfigure.vue
> ui: fix tags for security group rules

- ui/src/components/view/InfoCard.vue
Fixes info card by showing both ISO and template where needed.
Before:
After:
> ui: fix infocard template, iso fields

- README.md
Enhancement. Modified the link in section Notice of cryptographic software.
> Modified the link in readme file

- plugins/integrations/prometheus/src/main/java/org/apache/cloudstack/metrics/PrometheusExporterImpl.java
When a host is not tagged, its maintenance status is reported in the cloudstack_hosts_total metric: maintenance_enabled is OFFLINE, maintenance_disabled is ONLINE.
When a host is tagged, its maintenance status is now also verified to ensure consistent behaviour.
This PR fixes https://github.com/apache/cloudstack/issues/7470
In prometheus exporter, maintenance status for cloudstack_hosts_total_by_tag is not checked. While it is checked for cloudstack_hosts_total metric.
Classified by_tag or not, metrics should be the same.
Fixes: #7470
Trivial change.
> Prometheus: Ensure tagged hosts maintenance status is reported consistently

- agent/src/main/java/com/cloud/agent/dhcp/DhcpProtocolParserServer.java
This PR... removed commented code.
> [Cleanup] removed commented code in DhcpProtocolParserServer.java

- CONTRIBUTING.md
This PR removes some unneeded whitespace in the contributing doc
> CONTRIBUTING.md: remove unneeded whitespace from start of code blocks

- plugins/integrations/kubernetes-service/src/main/java/org/apache/cloudstack/api/command/user/kubernetes/cluster/CreateKubernetesClusterCmd.java
- ui/src/views/compute/CreateKubernetesCluster.vue
Make the description for `createKubernetesCLuster` API optional. Similar to #7180
> ui,api: make description option for createKubernetesCluster

- debian/cloudstack-usage.postinst
This PR creates user 'cloud' in cloudstack-usage postinstall script. This ensures the chown 'cloud:cloud' command (later in the same file) is always performed with no error.
Fixes: #7507
> Create user 'cloud' in cloudstack-usage postinstall

- .github/linters/.flake8
This PR adds two more flake8 rules which run with the GitHub Super-Linter.
The codebase was already following this style so there are no code changes.
https://www.flake8rules.com/
https://flake8.pycqa.org/en/latest/
Can check locally with: 
`flake8 --select=E223,E224,E242,E273,E274,E742,E743,E901,E902,W291,W292,W293,W391 .`
> Enable two more `flake8` rules

- api/src/main/java/com/cloud/network/vpc/NetworkACLService.java
- plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java
- plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterActionWorker.java
- plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterDestroyWorker.java
- plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterResourceModifierActionWorker.java
- plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterScaleWorker.java
- plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterStartWorker.java
- plugins/integrations/kubernetes-service/src/test/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImplTest.java
- plugins/integrations/kubernetes-service/src/test/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterActionWorkerTest.java
- server/src/main/java/com/cloud/network/vpc/NetworkACLServiceImpl.java
- server/src/test/java/com/cloud/network/vpc/NetworkACLServiceImplTest.java
- test/integration/smoke/test_kubernetes_clusters.py
> cks: k8s cluster on vpc tier

- engine/schema/src/main/resources/META-INF/db/schema-41800to41810.sql
- engine/schema/src/main/resources/META-INF/db/schema-41810to41900.sql
Moves schema change from #6960 in the correct upgrade path
> engine-schema: fix schema change for #6960

- .github/workflows/build.yml
- .github/workflows/ci.yml
- .github/workflows/codecov.yml
- .github/workflows/main-sonar-check.yml
- .github/workflows/sonar-check.yml
This PR allows usage of multiple threads for running different github actions depending on the number of cores present in the system.
As per the documentation [here](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources), github runners have 2 cores. This should decrease the time it takes for github actions to run.
> Use parallel builds for github actions

- scripts/vm/hypervisor/versions.sh
This PR fixes the way /etc/redhat-release is read to return host attributes
Fixes: #7547
tested on a host manually by editting the /etc/redhat-release file and verifying different outputs.
> interpret /etc/redhat-release better

- services/secondary-storage/controller/src/main/java/org/apache/cloudstack/secondarystorage/SecondaryStorageManagerImpl.java
- services/secondary-storage/controller/src/test/java/org/apache/cloudstack/secondarystorage/SecondaryStorageManagerImplTest.java
- systemvm/agent/scripts/ssvm-check.sh
> ssvm: pass all accessible secondary storage to ssvm

- plugins/storage/volume/scaleio/src/test/java/org/apache/cloudstack/storage/datastore/driver/ScaleIOPrimaryDataStoreDriverTest.java
> scaleio: fix build error after 4.18 merge forward

- debian/changelog
This PR bumps the version to 4.18.1.0-SNAPSHOT in debian/changelog
> [4.18] Bump the version to 4.18.1.0-SNAPSHOT in debian/changelog

- debian/changelog
This PR bumps the version to 4.19.0.0-SNAPSHOT in debian/changelog
> [main] Bump version to 4.19.0.0-SNAPSHOT in debian/changelog

- tools/marvin/marvin/lib/utils.py
This PR fixes the smoke test failures when mgmt server is ubuntu.
> marvin: fix smoke test failures if mgmt server is Ubuntu and hosts are VMware

- api/src/main/java/com/cloud/configuration/ConfigurationService.java
- plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/manager/VmwareManagerImpl.java
- server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
- server/src/main/java/com/cloud/resource/ResourceManagerImpl.java
- ui/src/views/infra/zone/ZoneWizardLaunchZone.vue
This PR intents to investigate and solve problems with the zone wizard.
So far a problem found is that
Fixes: #7563 
this has been tested by using the deploy wizard in a vmware environment.
> UI: Zone wizard fix

- ui/src/views/network/CreateIsolatedNetworkForm.vue
> UI: fix wrong vpcid when create network in VPC

- .github/workflows/ci.yml
- test/integration/smoke/test_vm_schedule.py
> Fix test_vm_schedule's intermittent failures

- agent/src/main/java/com/cloud/agent/properties/AgentProperties.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/BridgeVifDriver.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/IvsVifDriver.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/OvsVifDriver.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/VifDriverBase.java
> kvm agent: get the right controll cidr

- server/src/main/java/com/cloud/server/ManagementServerImpl.java
This PR enables SVM migration on KVM local storage.
Fixes: #7651
manually, by migrating SSVMs and then testing console proxying them.
> allow migration of all VMs with local storage on KVM

- .github/workflows/codecov.yml
Code Coverage github action doesn't generate correct coverage for squashed or multiple commits. Following the recommendations from [here](https://community.codecov.com/t/unable-to-determine-a-parent-commit-to-compare-against-in-base-branch-after-squash-and-merge/2480/4), this PR increases the fetch depth (`0` means all) when checking out the repo.
> Fix codecov github action's report

- plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/datastore/driver/StorPoolPrimaryDataStoreDriver.java
- plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/datastore/driver/StorPoolStatsCollector.java
- plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/datastore/util/StorPoolUtil.java
- plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/snapshot/StorPoolConfigurationManager.java
- plugins/storage/volume/storpool/src/main/resources/META-INF/cloudstack/storage-volume-storpool/spring-storage-volume-storpool-context.xml
Added tasks for statistics of the StorPool's volumes and primary storage
> Storage and volumes statistics tasks for StorPool primary storage

- ui/src/views/infra/AddPrimaryStorage.vue
- utils/src/main/java/com/cloud/utils/UriUtils.java
- utils/src/test/java/com/cloud/utils/UriUtilsTest.java
This PR fixes the credentials of RBD pool which contains slashes.
see the test failures in PR #7671 
This fixes #7673
> utils: fix RBD URI if credentials contains slash

- ui/public/locales/en.json
- ui/src/views/compute/KubernetesServiceTab.vue
Since Kubernetes v1.24.0, there is no auto-generation of secret-based service account token due to security reason. see https://github.com/kubernetes/kubernetes/pull/108309
To access kubernetes dashboard, users need to create a service account and an optional long-lived Bearer Token for the service account.
> UI: add step to create bearer token for kubernetes dashboard

- server/src/main/java/com/cloud/network/vpc/NetworkACLManagerImpl.java
- server/src/test/java/com/cloud/network/vpc/NetworkACLManagerTest.java
This PR cleans resource tags when deleting a network acl item.
Fixes: #7744
tested by checking the DB contents for the tables `network_acl_item` vs. `resourece_tags`
> add remove tag to remove acl item method

- ui/src/components/view/SearchView.vue
This PR...
Fixes: #7753
manually
> search in (too) large result sets

- engine/schema/pom.xml
- pom.xml
> pom.xml: add property project.systemvm.template.location

- plugins/integrations/kubernetes-service/src/test/java/com/cloud/kubernetes/cluster/utils/KubernetesClusterUtilTest.java
- plugins/integrations/kubernetes-service/src/test/java/com/cloud/kubernetes/version/KubernetesVersionServiceTest.java
- plugins/integrations/kubernetes-service/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
This PR removes powermock from kubernetes plugin's tests
> Remove powermock from kubernetes plugin

- plugins/database/quota/src/test/java/org/apache/cloudstack/api/response/QuotaResponseBuilderImplTest.java
- plugins/database/quota/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
> Remove powermock from database/quota plugin

- plugins/storage/volume/storpool/pom.xml
- test/integration/plugins/storpool/MigrateVolumeToStorPool.py
- test/integration/plugins/storpool/TestStorPoolVolumes.py
- test/integration/plugins/storpool/TestTagsOnStorPool.py
- test/integration/plugins/storpool/TestVmSnapshots.py
- test/integration/plugins/storpool/sp_util.py
- removed the hardcoded endpoint of the StorPool primary storage from tests. It should be provided in the configuration file
- added the git commit information into the maven build. The information is used for monitoring
> Refactoring StorPool's smoke tests

- plugins/hypervisors/vmware/src/test/java/com/cloud/hypervisor/guru/VMwareGuruTest.java
- plugins/hypervisors/vmware/src/test/java/com/cloud/hypervisor/guru/VmwareVmImplementerTest.java
- plugins/hypervisors/vmware/src/test/java/com/cloud/hypervisor/vmware/VmwareDatacenterApiUnitTest.java
- plugins/hypervisors/vmware/src/test/java/com/cloud/hypervisor/vmware/manager/VmwareManagerImplTest.java
- plugins/hypervisors/vmware/src/test/java/com/cloud/hypervisor/vmware/resource/VmwareResourceTest.java
- plugins/hypervisors/vmware/src/test/java/org/apache/cloudstack/storage/motion/VmwareStorageMotionStrategyTest.java
- plugins/hypervisors/vmware/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
- vmware-base/src/test/java/com/cloud/hypervisor/vmware/mo/DatastoreMOTest.java
- vmware-base/src/test/java/com/cloud/hypervisor/vmware/mo/HostMOTest.java
- vmware-base/src/test/java/com/cloud/hypervisor/vmware/mo/HypervisorHostHelperTest.java
- vmware-base/src/test/java/com/cloud/hypervisor/vmware/mo/VirtualMachineMOTest.java
- vmware-base/src/test/java/com/cloud/hypervisor/vmware/util/VmwareContextTest.java
- vmware-base/src/test/java/com/cloud/hypervisor/vmware/util/VmwareHelperTest.java
- vmware-base/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
> Remove powermock from vmware-base & vmware hypervisor plugin

- api/src/main/java/com/cloud/storage/VolumeApiService.java
- api/src/main/java/com/cloud/vm/UserVmService.java
- api/src/main/java/org/apache/cloudstack/api/command/user/vm/DeployVMCmd.java
- engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
- engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/VolumeOrchestrator.java
- server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
- server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
- test/integration/smoke/test_events_resource.py
Description
deployVirtualMachine can be provided with disk offerings for data disks, and destroyVirtualMachine can be set to expunge data disks. This specific circumstance is not publishing volume delete event.
New PR instead of closed https://github.com/apache/cloudstack/pull/7714/
Create VM with Volume
Delete VM and set expunge and add Volume to be removal as well
Create VM:
Create VM auto-start:
Delete VM:
Expunge VM:
> VM.CREATE/VOLUME.DELETE/VOLUME.DESTROY not being emitted

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
This will allow for VXLAN configurations to utilize tags on the physical network of a zone
Added vni to the device list to be treated as a normal bridge slave devs
> Added VNI Devices as normal bridge slave devs

- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/dpdk/DpdkDriverTest.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/BridgeVifDriverTest.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtDomainXMLParserTest.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtKvmAgentHookTest.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtSecretDefTest.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtStoragePoolDefTest.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtStoragePoolXMLParserTest.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDefTest.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtVifDriverTest.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtGetAutoScaleMetricsCommandWrapperTest.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtMigrateCommandWrapperTest.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtNetworkElementCommandWrapperTest.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtReplugNicCommandWrapperTest.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtRevertSnapshotCommandWrapperTest.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtScaleVmCommandWrapperTest.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtUtilitiesHelperTest.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/storage/KVMPhysicalDiskTest.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessorTest.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/storage/LibvirtStoragePoolTest.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/storage/ScaleIOStorageAdaptorTest.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/storage/ScaleIOStoragePoolTest.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/storage/ScaleIOStoragePoolTest.java.bkp
- plugins/hypervisors/kvm/src/test/java/org/apache/cloudstack/kvm/ha/KVMHostHATest.java
- plugins/hypervisors/kvm/src/test/java/org/apache/cloudstack/utils/cryptsetup/CryptSetupTest.java
- plugins/hypervisors/kvm/src/test/java/org/apache/cloudstack/utils/cryptsetup/KeyFileTest.java
- plugins/hypervisors/kvm/src/test/java/org/apache/cloudstack/utils/linux/KVMHostInfoTest.java
- plugins/hypervisors/kvm/src/test/java/org/apache/cloudstack/utils/linux/MemStatTest.java
- plugins/hypervisors/kvm/src/test/java/org/apache/cloudstack/utils/qemu/QemuImgFileTest.java
- plugins/hypervisors/kvm/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
> Remove powermock from kvm hypervisor plugin

- ui/tests/unit/views/AutogenView.spec.js
This PR fixes unit tests for the UI
Run `npm run test:unit` and verified all tests are passing:
````
=============================== Coverage summary ===============================
Statements   : 5.26% ( 1369/26007 )
Branches     : 4.64% ( 667/14381 )
Functions    : 2.39% ( 192/8021 )
Lines        : 5.35% ( 1351/25250 )
================================================================================
Test Suites: 4 passed, 4 total
Tests:       175 passed, 175 total
Snapshots:   0 total
Time:        18.776s
Ran all test suites.
````
> Fix UI unit tests

- test/integration/smoke/test_vm_life_cycle.py
since #7570, The detail 'Host.OS' of centos7 host is changed from 'CentOS' to 'CentOS Linux'
This PR fixes #7786
> test: skip live storage migration on CentOS 7

- server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
- server/src/main/java/com/cloud/api/query/ViewResponseHelper.java
- ui/src/config/section/image.js
This PR shows the url in the iso details...
> UI: Show iso urls

- plugins/affinity-group-processors/non-strict-host-anti-affinity/src/test/java/org/apache/cloudstack/affinity/NonStrictHostAntiAffinityProcessorTest.java
- services/console-proxy/rdpconsole/src/test/java/common/ClientTest.java
- services/console-proxy/rdpconsole/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
- services/console-proxy/server/src/test/java/com/cloud/consoleproxy/ConsoleProxyHttpHandlerHelperTest.java
- services/console-proxy/server/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
- services/secondary-storage/server/src/test/java/org/apache/cloudstack/storage/resource/NfsSecondaryStorageResourceTest.java
- services/secondary-storage/server/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
> Remove powermock from services

- ui/src/views/network/CreateVlanIpRange.vue
- ui/src/views/network/GuestIpRanges.vue
> UI: update ip ranges of shared networks

- ui/public/locales/en.json
While this is documented in our project docs, users must be nudged that deletion of a volume wouldn't delete any snapshots of the volume.
> ui: make it clear that deletion of a volume will not delete any snapshots

- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtReplugNicCommandWrapperTest.java
This PR fixes the unit test error with LibvirtReplugNicCommandWrapperTest
> kvm: fix unit test LibvirtReplugNicCommandWrapperTest

- core/src/test/java/com/cloud/resource/ServerResourceBaseTest.java
- core/src/test/java/com/cloud/storage/template/OVAProcessorTest.java
- core/src/test/java/com/cloud/storage/template/QCOW2ProcessorTest.java
- core/src/test/java/com/cloud/storage/template/VhdProcessorTest.java
- core/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
This PR removes powermock from core
> Remove powermock from core

- engine/storage/configdrive/src/main/java/org/apache/cloudstack/storage/configdrive/ConfigDriveBuilder.java
- engine/storage/configdrive/src/test/java/org/apache/cloudstack/storage/configdrive/ConfigDriveBuilderTest.java
- engine/storage/configdrive/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
This PR removes powermock from `engine/storage/configdrive`.
> Remove powermock from engine/storage/configdrive

- server/src/test/java/com/cloud/resourcelimit/CheckedReservationTest.java
> Fixup CheckedReservationTest

- client/pom.xml
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessorTest.java
- plugins/storage/volume/storpool/pom.xml
- plugins/user-authenticators/ldap/pom.xml
- pom.xml
- utils/src/test/java/org/apache/cloudstack/utils/reflectiontostringbuilderutils/ReflectionToStringBuilderUtilsTest.java
> Remove powermock from pom.xml

- .asf.yaml
Added myself (`BryanMLima`) as a collaborator to be able to report issue with tags, and be assigned to issues and PRs.
> Added BryanMLima to .asf.yaml

- .asf.yaml
Added myself (`SadiJr`) as a collaborator in `.asf.yaml` to be able to report issue with tags, and be assigned to issues and PRs.
> Added SadiJr to .asf.yaml collaborators

- plugins/shutdown/src/main/java/org/apache/cloudstack/api/command/ReadyForShutdownCmd.java
- ui/src/components/page/GlobalLayout.vue
- ui/src/store/getters.js
- ui/src/store/modules/app.js
- ui/src/store/modules/user.js
- ui/src/views/auth/Login.vue
This PR fixes the issue of continuous poll of ReadyForShutdown API even after logout. 
This poll is causing issues after logout with unnecessary login error messages and API calls
Steps to reproduce the issue or test the fix
1. Login into CloudStack
2. Observe the Networks tab in browser development console, observe "readyForShutdown" API calls
3. Logout from CloudStack
Observe that calling "readyForShutdown" API still continues. This PR clears that polling job.
> Fix the poll for the API ReadyForShutdown even after logout

- engine/userdata/pom.xml
Fix version for `cloud-engine-components-api` in `cloud-engine-userdata` sub-project
> mvn: fix userdata dependency version

- ui/public/locales/en.json
- ui/src/config/section/compute.js
- ui/src/views/AutogenView.vue
- ui/src/views/compute/DeployVM.vue
> ui: allow copying password from notification

- test/integration/smoke/test_vm_schedule.py
This PR adds additional checks in test_vm_schedule to avoid intermittent failures
- [] Minor
> Add extra checks for test_vm_schedule to avoid intermittent failures

- systemvm/debian/opt/cloud/bin/setup/cloud-early-config
Occasionally system vms (CPVM/SSVM) took long time (15~20 mins) to be Up, which happened if the network is slow.
/var/log/cloud.log shows
```
root@s-1-VM:~# grep sum /var/log/cloud.log
Fri 08 Sep 2023 10:25:51 AM UTC Scripts checksum detected: oldmd5=da16d6a2533fd19960304152dd78e02c newmd5=da16d6a2533fd19960304152dd78e02c
Fri 08 Sep 2023 10:26:44 AM UTC Scripts checksum detected: oldmd5=da16d6a2533fd19960304152dd78e02c newmd5=d41d8cd98f00b204e9800998ecf8427e
Fri 08 Sep 2023 10:39:09 AM UTC Scripts checksum detected: oldmd5=d41d8cd98f00b204e9800998ecf8427e newmd5=0ec9117c206d7440309ba9d531e59e4d
Fri 08 Sep 2023 10:39:13 AM UTC Scripts checksum detected: oldmd5=d41d8cd98f00b204e9800998ecf8427e newmd5=0ec9117c206d7440309ba9d531e59e4d
```
`d41d8cd98f00b204e9800998ecf8427e` is the md5sum value …
> systemvm: check if patchfile exists and is valid tarball before patching

- ui/src/components/view/EventsTab.vue
- ui/src/views/AutogenView.vue
- ui/src/views/compute/ChangeAffinity.vue
- ui/src/views/compute/ResetSshKeyPair.vue
- ui/src/views/compute/ResetUserData.vue
- ui/src/views/infra/CpuSockets.vue
- ui/src/views/infra/Metrics.vue
This PR fixes sorting in tables by columns in the UI.
> UI: Fix sorter across different components

- ui/public/locales/en.json
- ui/src/views/compute/wizard/TemplateIsoSelection.vue
> ui: update vm deploy form iso label

- utils/src/test/java/com/cloud/utils/SwiftUtilTest.java
> Refactoring swift util test

- ui/src/components/view/ListView.vue
- ui/src/config/section/storage.js
> ui: correctly show volume physical size

- ui/src/views/image/TemplateZones.vue
> ui: fix bulk delete template from zones

- api/src/main/java/com/cloud/offering/NetworkOffering.java
- engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
- plugins/network-elements/nsx/src/main/java/org/apache/cloudstack/agent/api/CreateNsxTier1GatewayCommand.java
- plugins/network-elements/nsx/src/main/java/org/apache/cloudstack/agent/api/DeleteNsxTier1GatewayCommand.java
- plugins/network-elements/nsx/src/main/java/org/apache/cloudstack/resource/NsxResource.java
- plugins/network-elements/nsx/src/main/java/org/apache/cloudstack/service/NsxApiClient.java
- plugins/network-elements/nsx/src/main/java/org/apache/cloudstack/service/NsxElement.java
- plugins/network-elements/nsx/src/main/java/org/apache/cloudstack/service/NsxGuestNetworkGuru.java
- plugins/network-elements/nsx/src/main/java/org/apache/cloudstack/service/NsxServiceImpl.java
- plugins/network-elements/nsx/src/main/java/org/apache/cloudstack/utils/NsxControllerUtils.java
- plugins/network-elements/nsx/src/main/java/org/apache/cloudstack/utils/NsxHelper.java
- plugins/network-elements/nsx/src/test/java/org/apache/cloudstack/resource/NsxResourceTest.java
- server/src/main/java/com/cloud/server/ConfigurationServerImpl.java
Allow creating NSX isolated networks (not as VPC tiers)
> [NSX] Allow NSX isolated networks

- .asf.yaml
Added myself as a collaborator in .asf.yaml to be able to report issues with tags, and be assigned to issues and PRs.
> Add winterhazel to .asf.yaml collaborators

- .asf.yaml
Maximum 10 collaborators are supported by ASF infra.
soreana is already a committer now and can be removed from this list.
> reduce collaborators count to 10

- api/src/main/java/org/apache/cloudstack/api/command/admin/vlan/CreateVlanIpRangeCmd.java
- plugins/network-elements/nsx/src/main/java/org/apache/cloudstack/service/NsxApiClient.java
- plugins/network-elements/nsx/src/main/java/org/apache/cloudstack/service/NsxElement.java
> NSX: fix LB member addition and deletion and add defensive checks

- api/src/main/java/com/cloud/network/IpAddress.java
- api/src/main/java/org/apache/cloudstack/api/command/user/address/ListPublicIpAddressesCmd.java
- api/src/main/java/org/apache/cloudstack/api/response/IPAddressResponse.java
- engine/components-api/src/main/java/com/cloud/network/addr/PublicIp.java
- engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
- plugins/network-elements/nsx/src/main/java/org/apache/cloudstack/service/NsxPublicNetworkGuru.java
- server/src/main/java/com/cloud/api/ApiResponseHelper.java
- server/src/main/java/com/cloud/server/ManagementServerImpl.java
- server/src/main/java/org/apache/cloudstack/network/router/deployment/RouterDeploymentDefinition.java
- server/src/main/java/org/apache/cloudstack/network/router/deployment/RouterDeploymentDefinitionBuilder.java
- server/src/main/java/org/apache/cloudstack/network/router/deployment/VpcRouterDeploymentDefinition.java
- server/src/test/java/com/cloud/server/ManagementServerImplTest.java
> NSX: Router Public nic to get IP from systemVM Ip range

- .pre-commit-config.yaml
https://github.com/pre-commit/pre-commit-hooks#check-symlinks
https://github.com/pre-commit/pre-commit-hooks#destroyed-symlinks
This PR adds two more hooks to our pre-commit framework basically just another two tests we can run.
> Add two more pre-commit hooks

- plugins/ca/root-ca/src/main/java/org/apache/cloudstack/ca/provider/RootCAProvider.java
During deployment, ACS creates a Root CA and stores it in the database. From this Root CA, ACS generates a self-signed certificate for the management servers and other components. The MS certificate is stored in memory and is generated every time the MS is restarted.
Currently, the MS adds as alternative name only the IP of its default network, therefore, if the network used for communication between the MSs is different from their default network, the certificate will never be accepted and the communication will not take place.
This PR adds the MS's IP in the `management.network.cidr` network as an alternative name in the self-signed certificate. 
With `ca.plugin.root.auth.strictness` turned on and `management.network.cidr` configured to the MGMT network. I changed the default network in …
> Add MGMT IP in management.network.cidr as alternate name in their self-signed certificate

- plugins/network-elements/nsx/src/main/java/org/apache/cloudstack/service/NsxApiClient.java
> Nsx add lb route adv

- ui/src/components/view/ListView.vue
This PR fixes the UI bug with CKS cluster size
Prior to this PR
With this PR
> CKS: fix wrong format of cluster size on UI

- framework/spring/module/src/main/java/org/apache/cloudstack/spring/module/model/impl/DefaultModuleDefinitionSet.java
ACS bootstrap process contains code that might cause exceptions, which are not logged; thus, it can make it hard for developers and operators to understand what is happening to the system and breaking the boot of the application. This PR intends to improve and add new logs to this process in order to facilitate troubleshooting.
I applied the changes in a local lab and checked if the messages were being correctly logged.
> Add and improve logs in ACS bootstrap process

- .github/workflows/build.yml
- .github/workflows/ci.yml
- .github/workflows/codecov.yml
- .github/workflows/docker-cloudstack-simulator.yml
- .github/workflows/linter.yml
- .github/workflows/main-sonar-check.yml
- .github/workflows/rat.yml
- .github/workflows/sonar-check.yml
- .github/workflows/ui.yml
https://github.com/actions/checkout
This PR updates our workflows to use `v4` of `actions/checkout`
> Bump the `actions/checkout` action to `v4`

- ui/src/components/view/ListView.vue
> indent issue in list view after merge forward of 4.18

- plugins/network-elements/nsx/src/main/java/org/apache/cloudstack/service/NsxApiClient.java
> Nsx : lb route advertisement

- ui/src/views/compute/ScaleVM.vue
> UI: fix scale vm if first disk offering is dymamic

- PULL_REQUEST_TEMPLATE.md
This PR fixes a single spelling mistake.  I see it every time I create a pull request :)
> PULL_REQUEST_TEMPLATE.md: fix spelling

- engine/schema/src/main/resources/META-INF/db/schema-41810to41900.sql
Fixes OAuth(2) schema changes removed in Database VIEW Management improvement #7417
> schema: revert incorrect removal of oauth changes in #7417

- engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
- plugins/network-elements/nsx/src/main/java/org/apache/cloudstack/agent/api/CreateNsxDistributedFirewallRulesCommand.java
- plugins/network-elements/nsx/src/main/java/org/apache/cloudstack/agent/api/DeletedNsxDistributedFirewallRulesCommand.java
- plugins/network-elements/nsx/src/main/java/org/apache/cloudstack/resource/NsxNetworkRule.java
- plugins/network-elements/nsx/src/main/java/org/apache/cloudstack/resource/NsxResource.java
- plugins/network-elements/nsx/src/main/java/org/apache/cloudstack/service/NsxApiClient.java
- plugins/network-elements/nsx/src/main/java/org/apache/cloudstack/service/NsxElement.java
- plugins/network-elements/nsx/src/main/java/org/apache/cloudstack/service/NsxServiceImpl.java
- plugins/network-elements/nsx/src/main/java/org/apache/cloudstack/utils/NsxControllerUtils.java
- plugins/network-elements/nsx/src/test/java/org/apache/cloudstack/service/NsxApiClientTest.java
- plugins/network-elements/nsx/src/test/java/org/apache/cloudstack/service/NsxElementTest.java
- server/src/main/java/com/cloud/server/ConfigurationServerImpl.java
This PR:
- Creates a group for the NSX segment on its creation
- Adds a Distributed Firewall policy for a segment along with its rules
- Removes the Distributed Firewall policy for the segment before its deleted
> [NSX] Add ACL types support

- framework/spring/module/src/main/java/org/apache/cloudstack/spring/module/model/impl/DefaultModuleDefinitionSet.java
This PR reduces loglevel on non fatal errors and removes stacktraces above debug level.
> lower level and no stack traces at info or higher

- plugins/network-elements/nsx/src/main/java/org/apache/cloudstack/service/NsxElement.java
This PR fixes ACL rules creation on VPC tier implementation
> [NSX] Fix ACL rules creation

- ui/src/views/network/AclListRulesTab.vue
> Acl export acls with proper tags encoding

- client/pom.xml
- pom.xml
This PR fixes that code coverage is not updated in some modules
The following modules should have better code coverage with this PR
- cloud-agent
- cloud-api
- cloud-core
- cloud-framework-cluster
- cloud-framework-config
- cloud-framework-db
- cloud-framework-events
- cloud-framework-jobs
- cloud-framework-managed-context
- cloud-framework-security
- cloud-usage
- cloud-utils
> client/pom.xml: fix code coverage is not updated in some modules

- api/src/main/java/org/apache/cloudstack/api/command/admin/network/CreateNetworkOfferingCmd.java
- api/src/main/java/org/apache/cloudstack/api/command/admin/vpc/CreateVPCOfferingCmd.java
- api/src/main/java/org/apache/cloudstack/api/command/user/address/ListPublicIpAddressesCmd.java
- plugins/network-elements/nsx/src/main/java/org/apache/cloudstack/resource/NsxResource.java
- plugins/network-elements/nsx/src/main/java/org/apache/cloudstack/service/NsxApiClient.java
- plugins/network-elements/nsx/src/main/java/org/apache/cloudstack/service/NsxGuestNetworkGuru.java
- plugins/network-elements/nsx/src/main/java/org/apache/cloudstack/service/NsxPublicNetworkGuru.java
This PR fixes Sonar Cloud issues for NSX integration PR #7919
> [NSX] Address SonarCloud Bugs

- engine/components-api/src/main/java/com/cloud/network/security/SecurityGroupManager.java
- plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java
- plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterActionWorker.java
- server/src/main/java/com/cloud/network/security/SecurityGroupManagerImpl.java
This PR fixes #7684 
The security groups contain the same rules for port 22 and 6443, no need to recreate for each CKS cluster.
> CKS: create Security Groups for CKS clusters of each account

- test/integration/smoke/test_image_store_object_migration.py
This PR fixes failure seem in https://github.com/apache/cloudstack/pull/7344#issuecomment-1862107631
> Fixup test_image_store_object_migration.py

- server/src/main/java/com/cloud/server/StatsCollector.java
This simply improves the log statement that prints debug statements during beginning of a stats collector run for hosts or VMs.
> server: improve stats collector logs to state what the collector does

- engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
This PR fixes the debug message when expunge a vm
> server: fix debug message when expunge a vm

- .asf.yaml
This PR changes the contributers list.
> contributers: change of the guard

- ui/public/locales/en.json
- ui/src/config/section/compute.js
- ui/src/views/infra/zone/IpAddressRangeForm.vue
- ui/src/views/infra/zone/ZoneWizard.vue
- ui/src/views/infra/zone/ZoneWizardLaunchZone.vue
- ui/src/views/network/VpcTiersTab.vue
This PR fixes  NSX Zone creation bug for public networks
> Nsx UI zone bug

- plugins/network-elements/nsx/src/main/java/org/apache/cloudstack/service/NsxApiClient.java
- plugins/network-elements/nsx/src/main/java/org/apache/cloudstack/utils/NsxControllerUtils.java
- plugins/network-elements/nsx/src/main/java/org/apache/cloudstack/utils/NsxHelper.java
- plugins/network-elements/nsx/src/test/java/org/apache/cloudstack/resource/NsxResourceTest.java
- plugins/network-elements/nsx/src/test/java/org/apache/cloudstack/service/NsxServiceImplTest.java
- plugins/network-elements/nsx/src/test/java/org/apache/cloudstack/utils/NsxControllerUtilsTest.java
This PR adds more unit tests for NSX integration
> [NSX] Add more unit tests

- ui/src/components/view/ObjectStoreBrowser.vue
This PR fixes the ssl in image store browser.
> Fix ssl check in object store browser

- plugins/network-elements/nsx/src/main/java/org/apache/cloudstack/service/NsxElement.java
> CKS: Add action to during firewall rule creation

- api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
- api/src/main/java/org/apache/cloudstack/api/command/admin/network/CreateNetworkOfferingCmd.java
- api/src/main/java/org/apache/cloudstack/api/command/admin/vpc/CreateVPCOfferingCmd.java
- ui/public/locales/en.json
- ui/src/views/offering/AddNetworkOffering.vue
- ui/src/views/offering/AddVpcOffering.vue
This PR...
VPC Offering:
Network Offering:
> NSX: Make LB service selectable in network offering

- framework/direct-download/pom.xml
- plugins/affinity-group-processors/non-strict-host-anti-affinity/pom.xml
- plugins/pom.xml
- vmware-base/pom.xml
This PR fixes the POM dependencies from a hardcoded value to the project.version property on dependencies
> Use project version on pom dependencies

- api/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterHelper.java
- plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterHelperImpl.java
- plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/dao/KubernetesClusterVmMapDao.java
- plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/dao/KubernetesClusterVmMapDaoImpl.java
- plugins/network-elements/nsx/src/main/java/org/apache/cloudstack/service/NsxElement.java
- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
- server/src/main/resources/META-INF/cloudstack/core/spring-server-core-managers-context.xml
> NSX: Cleanup NSX resources during k8s cluster cleanup

- ui/src/views/compute/CreateKubernetesCluster.vue
Fixes #8536
https://github.com/apache/cloudstack/assets/153340/f9f26f0f-b8ed-44ff-8fda-6cf2f8da8b0d
> ui: fix create k8s cluster networks listing

- server/src/main/java/com/cloud/network/firewall/FirewallManagerImpl.java
> NSX: Add check for ICMP code / type for NSX zones

- debian/changelog
- tools/docker/Dockerfile
- tools/docker/Dockerfile.marvin
Fixes next version in files that were not updated by the setnextversion script.
> tools,changelog: fix nextversion

- api/src/main/java/org/apache/cloudstack/alert/AlertService.java
- server/src/main/java/com/cloud/alert/AlertManagerImpl.java
- server/src/main/java/com/cloud/alert/ClusterAlertAdapter.java
- server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
- usage/src/main/java/com/cloud/usage/UsageAlertManagerImpl.java
> Fix typo in alert name

- .asf.yaml
> remove @alexandremattiioli from contributors as he is a committer now

- .github/workflows/build.yml
- .github/workflows/ci.yml
This PR bumps `actions/setup-python` to `v5`
https://github.com/actions/setup-python
> Bump `actions/setup-python` to `v5`

- ui/src/components/view/DetailsTab.vue
- ui/src/config/section/offering.js
> add compute offering details in UI

- test/integration/smoke/test_guest_os.py
This PR is related to #8586 
on xenserver-71, supported Debian OSes are
```
name-label ( RW): Debian Squeeze 6.0 (32-bit)
name-label ( RW): Debian Jessie 8.0
name-label ( RW): Debian Wheezy 7.0 (32-bit)
name-label ( RW): Debian Squeeze 6.0 (64-bit)
name-label ( RW): Debian Wheezy 7.0 (64-bit)
```
on xcpng82, supported Debian OSes are
```
name-label ( RW): Debian Jessie 8.0
name-label ( RW): Debian Buster 10
name-label ( RW): Debian Stretch 9.0
```
> test: fix test_guest_os.py failure on xcpng82

- ui/src/config/section/storage.js
This PR removed duplicated section for backup
it was added in PR #7752 by mistake.
> UI: remove duplicated section for backup

- api/src/main/java/org/apache/cloudstack/api/command/admin/vlan/DeleteVlanIpRangeCmd.java
This PR updates `deleteVlanIpRange` API description
> Fixed deleteVlanIpRange API description

- ui/public/config.json
- ui/public/index.html
This PR...
- I have added a Script in index.html, which picks the Title, and favicon from the config.json file in the same directory.
- Enhancement (improves an existing feature and functionality)
- Minor
> Added JS Script to pick Favicon, Title from config file

- .github/workflows/build.yml
- .github/workflows/ci.yml
- .github/workflows/codecov.yml
- .github/workflows/main-sonar-check.yml
- .github/workflows/rat.yml
- .github/workflows/sonar-check.yml
This PR updates `actions/setup-java` from `v3` to `v4` (https://github.com/actions/setup-java/releases)
> Update actions/setup-java from v3 to v4

- ui/src/config/section/compute.js
This PR allows detach ISO from instance toolbar when ISO is attached.
Fixes #8711
Manually tested attach & detach ISO from instance toolbar.
> [UI] Allow detach ISO from instance toolbar when ISO is attached

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtDomainXMLParser.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtDomainXMLParserTest.java
This PR fixes NPE while import VMs from kvm host.
> kvm: fix NPE while import KVM VMs from other hosts

- engine/schema/src/main/java/com/cloud/network/security/dao/SecurityGroupVMMapDaoImpl.java
This PR fixes https://github.com/apache/cloudstack/issues/8595
```
2024-02-01 16:23:52,473 INFO  [c.c.n.s.SecurityGroupManagerImpl] (AgentManager-Handler-16:null) (logid:) Network Group full sync for agent 1 found 3 vms out of sync
2024-02-01 16:23:52,473 DEBUG [c.c.n.s.SecurityGroupManagerImpl] (AgentManager-Handler-16:null) (logid:) Security Group Mgr v2: scheduling ruleset updates for 3 vms  (unique=3), current queue size=0
2024-02-01 16:23:52,473 DEBUG [c.c.n.s.SecurityGroupManagerImpl] (AgentManager-Handler-16:null) (logid:) Security Group Mgr v2: done scheduling ruleset updates for 3 vms: num new jobs=3 num rows insert or updated=0 time taken=0
2024-02-01 16:23:52,478 ERROR [c.c.n.s.SecurityGroupManagerImpl] (SecGrp-Worker-20:ctx-0aa3885d) (logid:472b30d2) Problem during SG work …
```
> SG: fix SQL exception when add security group rule with allowed account/group

- ui/src/views/dashboard/CapacityDashboard.vue
> UI: Fix Virtual router count in Capacity dashboard

- engine/schema/src/main/java/org/apache/cloudstack/storage/datastore/db/PrimaryDataStoreDaoImpl.java
This PR fixes the simulator CI failure with `main` branch
> fix simulator CI failure test_04_list_storage_pools_keyword_filter

- ui/src/views/network/GuestIpRanges.vue
> Fix missing actions on Guest IP ranges for networks

- .asf.yaml
Adds myself (`gpordeus`) as a collaborator in .asf.yaml to be able to report issue with tags, be assigned to issues and PRs and so GitHub Actions will run without the need of manual approval every time.
> Add gpordeus to .asf.yaml collaborators

- .asf.yaml
Added myself (`hsato03`) as a collaborator to be able to report issue with tags, and be assigned to issues and PRs.
> Add hsato03 to .asf.yaml collaborators

- .asf.yaml
This PR removes some collaborators that have been granted comitter status...
> cleanup collaborators

- agent/conf/agent.properties
- agent/src/main/java/com/cloud/agent/properties/AgentProperties.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtConnection.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtDomainListener.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtScaleVmCommandWrapper.java
- plugins/hypervisors/kvm/src/main/java/org/apache/cloudstack/utils/linux/KVMHostInfo.java
- plugins/hypervisors/kvm/src/test/java/org/apache/cloudstack/utils/linux/KVMHostInfoTest.java
This PR marks libvirt events experimental, and adds agent property `libvirt.events.enabled` to enable/disable libvirt events.
> Mark libvirt events experimental, add properties flag

- engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/VolumeOrchestrator.java
This PR fixes the build issue on 4.19
> Fixup 4.19 build issue

- api/src/main/java/com/cloud/deploy/DeploymentClusterPlanner.java
- server/src/main/java/com/cloud/configuration/Config.java
- server/src/main/java/com/cloud/deploy/FirstFitPlanner.java
- server/src/test/java/com/cloud/vm/FirstFitPlannerTest.java
To make the `vm.allocation.algorithm` setting more intuitive, its description has been updated.
Furthermore, the configuration has been adapted to `ConfigKey`.
In the UI, I accessed the `Global Settings` tab and filtered for `vm.allocation.algorithm`. So I checked that the description was up to date.
> Improve vm.allocation.algorithm global setting description

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStoragePool.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDefTest.java
This PR allows KVM storage plugin an opportunity to customize the libvirt disk XML.
The new interface method customizeLibvirtDiskDef facilitates plugin-specific config without having to add new methods for each specific thing that may need customizing. Existing plugins should be unaffected because of default implementation in interface.
Additionally, this adds the capability to define geometry in the libvirt disk definition.
> Allow kvm storage plugin to customize diskdef, add geometry

- plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java
- systemvm/debian/etc/logrotate.d/haproxy
This PR...
Fixes: #8747
This is not re-produced bug. The fix is fairly simple. I have no idea how to reproduce but it resulted in data loss in a production VM. I think the best we can do is test upgrades from different versions. and see if anything happens.
> protect against null-path

- server/src/main/java/com/cloud/network/IpAddressManagerImpl.java
> add logs to ipallocation attempt

- test/integration/smoke/test_vm_life_cycle.py
This PR fixes the error message
```
Received unknown parameters for command listHosts. Unknown parameters : hostid
```
> test: fix unknown parameter hostid in test_vm_life_cycle.py

- framework/jobs/src/main/java/org/apache/cloudstack/framework/jobs/impl/AsyncJobManagerImpl.java
> sanatise trace logging of async jobs

- .asf.yaml
This PR adds myself (`bernardodemarco`) as a collaborator in `.asf.yaml` in order to be able to report issue with tags and to be assigned to issues and PRs.
> Add bernardodemarco to .asf.yaml collaborators

- server/src/main/java/org/apache/cloudstack/storage/volume/VolumeImportUnmanageManagerImpl.java
This PR fixes a compile issue on main
> fix log4j to log4j2 issue

- client/pom.xml
- plugins/network-elements/juniper-contrail/pom.xml
- plugins/pom.xml
This PR moves juniper-contrail to noredist and removes the repository for it.
> packaging: move juniper-contrail network plugin to noredist build

- server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
This PR fixes listing of service offering & stroagepools with tags.
1. Add 2 tags to a storage pool. The list operation fails.
2. List services offerings for a VM with service offering tags.
> Fixup listing of serivce offering & storagepools with tags

- api/src/main/java/com/cloud/user/ResourceLimitService.java
- api/src/main/java/com/cloud/vm/UserVmService.java
- api/src/main/java/org/apache/cloudstack/api/command/user/vm/RebootVMCmd.java
- engine/api/src/main/java/com/cloud/vm/VirtualMachineManager.java
- engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
- server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
- server/src/main/java/com/cloud/resourcelimit/ResourceLimitManagerImpl.java
- server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
- server/src/test/java/com/cloud/vm/UserVmManagerImplTest.java
- server/src/test/java/com/cloud/vpc/MockResourceLimitManagerImpl.java
This PR fixes missing updates to resource limit tags during different VM & disk operations.
1. Scale VM - Both stopped and running
2. Restore VM with different template & offerings
3. Resize Disk
4. Change Disk offering
> Fixup resource limit checks

- .asf.yaml
Remove `kiranchavala` now a committer
https://github.com/kiranchavala
This PR cleans up one line.
> Clean up `.asf.yaml` collaborators

- engine/api/src/main/java/org/apache/cloudstack/engine/orchestration/service/VolumeOrchestrationService.java
- engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/VolumeOrchestrator.java
- engine/storage/volume/src/main/java/org/apache/cloudstack/storage/volume/VolumeServiceImpl.java
- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
This PR updates the volume's passphrase to null if diskOffering doesn't support encryption
> Update volume's passphrase to null if diskOffering doesn't support encryption

- .github/workflows/ci.yml
- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
- test/integration/smoke/test_restore_vm.py
- ui/src/views/compute/ReinstallVm.vue
This PR fixes the following issues
1. Try to restore a VM twice in stopped state, it will throw an error. 
2. Fix the default template selection in reinstallVM modal.
> Fix restore VM with allocated root disk

- server/src/main/java/com/cloud/api/ApiServer.java
> sanatise log in case multiple passwords have been passed

- ui/src/config/section/compute.js
This PR hides the destroy/expunge option for CloudManaged CKS cluster
prior to this change
with this change
> UI: hide Cleanup/Expunge when delete a CloudManaged CKS cluster

- pom.xml
> Upgrade org.json:json version

- ui/src/views/AutogenView.vue
This PR fixes https://github.com/apache/cloudstack/issues/8773
> UI: Fix the Add / Remove Vmware DC button on Zone detail view

- engine/api/src/main/java/org/apache/cloudstack/engine/subsystem/api/storage/EndPointSelector.java
- engine/storage/src/main/java/org/apache/cloudstack/storage/endpoint/DefaultEndPointSelector.java
> Use parameter dcId as wrapper to prevent NPE

- plugins/storage/volume/linstor/src/main/java/org/apache/cloudstack/storage/datastore/driver/LinstorPrimaryDataStoreDriverImpl.java
Linstor primary storage forgot to make sure
the volume download/copy target has a Linstor resource available.
Tested on hyperconverged and non-hyperconverged 4.19.0 Cloudstack.
> linstor: Fix volume download and make resource available on copy target

- test/integration/smoke/test_restore_vm.py
This PR fixes e2e test for restore_vm
> Fixup e2e test_restore_vm

- engine/components-api/src/main/java/com/cloud/configuration/ConfigurationManager.java
- engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
- server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
- server/src/test/java/com/cloud/vpc/MockConfigurationManagerImpl.java
This PR fixes the below error log on deleting a shared network.
```java
2024-04-24 18:24:33,831 ERROR [o.a.c.f.m.MessageBusBase] (API-Job-Executor-14:ctx-63de092f job-2044 ctx-d00db98a) (logid:107d5ed5) NO EVENT PUBLISH CAN BE WRAPPED WITHIN DB TRANSAC
TION!
com.cloud.utils.exception.CloudRuntimeException: NO EVENT PUBLISH CAN BE WRAPPED WITHIN DB TRANSACTION!
at org.apache.cloudstack.framework.messagebus.MessageBusBase.publish(MessageBusBase.java:167)
at com.cloud.configuration.ConfigurationManagerImpl.deleteVlanAndPublicIpRange(ConfigurationManagerImpl.java:5345)
at …
```
> Fix message publish in transaction

- ui/src/config/section/compute.js
The existing link directs to an older documentation.
> ui: fix documentation link for VM autoscaling

- framework/config/src/test/java/org/apache/cloudstack/framework/config/ConfigKeyScheduledExecutionWrapperTest.java
This PR fixes the test failure with ConfigKeyScheduledExecutionWrapperTest
see 
https://github.com/apache/cloudstack/actions/runs/9171106108/job/25214722629
https://github.com/apache/cloudstack/actions/runs/9171320792/job/25215400678
https://github.com/apache/cloudstack/actions/runs/9180519825/job/25261374756
> Fix failure test with ConfigKeyScheduledExecutionWrapperTest

- api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
- api/src/main/java/org/apache/cloudstack/api/response/UserVmResponse.java
- engine/schema/src/main/resources/META-INF/db/views/cloud.user_vm_view.sql
- server/src/main/java/com/cloud/api/query/dao/UserVmJoinDaoImpl.java
- server/src/main/java/com/cloud/api/query/vo/UserVmJoinVO.java
- server/src/test/java/com/cloud/api/query/dao/UserVmJoinDaoImplTest.java
- ui/src/components/view/InfoCard.vue
Fixes #9084
https://github.com/apache/cloudstack/assets/153340/190e05a8-b6dc-45cc-9ba1-6f16bd9af8a7
> api,ui: vm template format, fix vm info link

- ui/src/config/section/image.js
- ui/src/views/image/RegisterOrUploadIso.vue
- ui/src/views/image/UpdateISO.vue
Register/List/Update iso APIs already support isdynamicallyscalable parama. This PR makes them available in the UI.
> ui: support isdynamicallyscalable param for iso

- .pre-commit-config.yaml
https://github.com/pre-commit/pre-commit-hooks?tab=readme-ov-file#detect-aws-credentials
https://github.com/pre-commit/pre-commit-hooks?tab=readme-ov-file#forbid-submodules
This PR adds two more checks or tests to our pre-commit framework.
The two hooks are from the official pre-commit organization.
No changes to the codebase but having extra checks stops regressions.
Ran `pre-commit run --all-files`
> Add two more `pre-commit` hooks

- .github/linters/.markdown-lint.yml
- .pre-commit-config.yaml
https://github.com/DavidAnson/markdownlint/tree/main?tab=readme-ov-file#rules--aliases
https://github.com/igorshubovych/markdownlint-cli?tab=readme-ov-file#use-with-pre-commit
This PR adds some checking for Markdown files with pre-commit.
I have added a markdownlint config file which sets a basic standard to start with.
markdownlint is a popular tool and helps improve readability and the portability of the Markdown files. 
If needed further clean ups of the Markdown files can be done in future PRs.
Ran `pre-commit run --all-files`
> Add `markdownlint` with `pre-commit`

- server/src/main/java/com/cloud/network/NetworkServiceImpl.java
- server/src/main/java/com/cloud/user/AccountManagerImpl.java
- systemvm/debian/opt/cloud/templates/conntrackd.conf.templ
- test/integration/component/maint/testpath_disable_enable_zone.py
- test/integration/component/test_acl_sharednetwork.py
- test/integration/component/test_acl_sharednetwork_deployVM-impersonation.py
- test/integration/component/test_advancedsg_networks.py
- test/integration/component/test_project_limits.py
- test/integration/component/test_resource_limits.py
- test/integration/component/test_snapshots_improvement.py
- test/integration/smoke/test_attach_multiple_volumes.py
- test/integration/smoke/test_enable_account_settings_for_domain.py
- tools/ngui/static/js/lib/angular.js
This PR cleans up the codebase by fixing spelling.
Fixed grammar and removed whitespace.
Used the correct case of some terms.
> Fix spelling in docs, logs, exception messages etc

- ui/src/views/network/AclListRulesTab.vue
> ui: fix columns for exportacls csv

- ui/src/core/lazy_lib/icons_use.js
- ui/src/views/network/AclListRulesTab.vue
Adds button for moving a rule to top/bottom of the list
Addresses https://github.com/apache/cloudstack/issues/8865
https://github.com/apache/cloudstack/assets/153340/ef301d21-41e4-4038-9786-53ded0ca6c61
> ui: add move to top/bottom for acl rules list

- server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
> server: honor listall param for listiso api

- ui/src/components/header/CreateMenu.vue
> ui: fix create menu item access

- ui/src/config/section/infra/hosts.js
- utils/src/main/java/org/apache/cloudstack/utils/process/ProcessRunner.java
- utils/src/test/java/org/apache/cloudstack/utils/process/ProcessRunnerTest.java
> utils,ui: obfuscate sensitive log info, use POST for configureOutOfBandManagement

- plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageProcessor.java
- plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java
- plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterResourceModifierActionWorker.java
- plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterStartWorker.java
- plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/utils/KubernetesClusterUtil.java
This PR fixes some log messages encountered during troubleshooting.
> log messages

- api/src/main/java/com/cloud/user/ResourceLimitService.java
- api/src/main/java/org/apache/cloudstack/api/command/user/resource/UpdateResourceCountCmd.java
- api/src/main/java/org/apache/cloudstack/user/ResourceReservation.java
- engine/schema/src/main/java/org/apache/cloudstack/reservation/ReservationVO.java
- engine/schema/src/main/java/org/apache/cloudstack/reservation/dao/ReservationDao.java
- engine/schema/src/main/java/org/apache/cloudstack/reservation/dao/ReservationDaoImpl.java
- engine/schema/src/main/resources/META-INF/db/schema-41910to42000.sql
- server/src/main/java/com/cloud/resourcelimit/CheckedReservation.java
- server/src/main/java/com/cloud/resourcelimit/ResourceLimitManagerImpl.java
- server/src/test/java/com/cloud/resourcelimit/CheckedReservationTest.java
Some entries are left over in `resource_reservation` table if there is a breach in resource limits or if the management server crashes.
This PR fixes that and also adds additional information in `resource_reservation` table to track when was a reservation created and who created it.
We also cleanup any stale entries (older than `resource.reservation.cleanup.delay`, defaults to 3600 seconds) as part of the recalculate resource count method.
1. Define 2 resource limit host tags - t1, t2
2. Set overall user_vm limit to some higher value - 10
3. Set t1 user_vm limit to a higher value - 5
4. Set t2 user_vm limit to 1Now you'll be able to deploy one VM with t2 tag. When you will try to deploy another VM with t2 tag it should leave some leftover reservations for null and t1 …
> server: fix resource reservation leakage

- engine/schema/src/main/resources/META-INF/db/schema-41910to42000.sql
> engine-schema: make adding/dropping indexes idempotent

- ui/src/components/header/CreateMenu.vue
Refactors global create menu code to make it visible only when any menu is accessible.
Admin:
Read-only user:
Custom role user:
> ui: refactor global createmenu

- plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/version/KubernetesVersionManagerImpl.java
- plugins/integrations/kubernetes-service/src/test/java/com/cloud/kubernetes/version/KubernetesVersionManagerImplTest.java
- ui/src/views/compute/CreateKubernetesCluster.vue
> cks,ui: fix npe and check for disable zone

- server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
- server/src/main/java/com/cloud/storage/StorageManagerImpl.java
This PR fixes issue #8914
Issue is when using a compute offering which is associated with a disk offering having vsphere storage policy defined.
When a VM is created with such a compute offering, vsphere storage policy defined on the disk offering should be applied to the root volume.
1. Assign a tag on the storage on vcenter and create a storage policy with the same tag 
2. Create a disk offering with a storage policy selected
3. Create a compute offering and associate the above created disk offering in that compute offering
4. Create an instance using the above compute offering
5. The VM's root disk created on the storage pool associated with policy
> Fix vsphere storagepolicy

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtGetRemoteVmsCommandWrapper.java
- server/src/main/java/org/apache/cloudstack/vm/UnmanagedVMsManagerImpl.java
This PR improves error messaging / logs when listing VMs on the remote KVM host (for import).
Addresses appropriate messages aa per the comments on #8704.
Manually tested list VMs on the remote KVM host.
> Improve error messaging / logs when listing VMs on the remote KVM host (for import)

- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
Fixes #9095 
Test1:
1. create a VM based off a password enabled template on a L2 network with configdrive support
2. mounted the configdrive iso and verified the password in the password file
3. reinstalled the VM with the same password-enabled template
4. mounted the configdrive iso and verified the password in the password file
Test2:
1. create a VM based off a password enabled template on a L2 network with configdrive support
2. mounted the configdrive iso and verified the password in the password file
3. reinstalled the VM with another template that isn't password enabled
4. mounted the configdrive iso and verified that password file is not present
> Configure config drive ISO with password file on reinstallation of VM  with password-enabled template

- api/src/main/java/org/apache/cloudstack/api/command/user/volume/ListVolumesCmd.java
- server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
- ui/src/components/view/SearchView.vue
- ui/src/config/section/storage.js
Fixes #8646 
This PR allows listing of volumes by service offering id. If both service offering id and disk offering id are passed, service offering id is ignored.
UI is also updated to allow filtering of volumes by service offering id and disk offering id.
> List volumes by service offering id

- agent/conf/cloudstack-agent.logrotate.in
- agent/conf/log4j-cloud.xml.in
- client/conf/log4j-cloud.xml.in
- debian/rules
- packaging/centos7/cloud.spec
- packaging/centos8/cloud.spec
- packaging/systemd/cloudstack-agent.service
- packaging/systemd/cloudstack-management.service
- packaging/systemd/cloudstack-usage.service
- server/conf/cloudstack-management.logrotate.in
- server/conf/log4j-cloud.xml.in
- usage/conf/cloudstack-usage.logrotate.in
- usage/conf/log4j-cloud_usage.xml.in
As of now, logs which get logged to journalctl also get logged to file. In one of the environments, we saw some logs which were present in journalctl but not in management-server.log file. This PR disables the logging to stdout and logs which are not getting captured will be logged to a file.
After this change,
1. stdout of cloudstack services is logged to files
2. Disable log4j logs from stdout to prevent duplication of logs
3. Add log rotation for stdout logs
> Disable logs to stdout and capture remaining stdout logs to a file

- ui/src/views/dashboard/CapacityDashboard.vue
Fixes warnings on admin dashboard in console.
Without change
> ui: fix admin dashboard vue warnings

- plugins/metrics/src/test/java/org/apache/cloudstack/response/HostMetricsResponseTest.java
This test case tests the various if branches inside CpuAllocation that can result in null pointer exceptions. It is important to ensure that all arguments inside the cpu test within a host are allocated correctly, otherwise processes and tasks should not be runnable on the cloud system.
This has been tested with the standard maven install lifecycle that includes all the tests
> Add unit tests for null cpu for null parameters for set allocated cpu

- services/secondary-storage/server/src/main/java/org/apache/cloudstack/storage/resource/HttpUploadServerHandler.java
> logging: httpupload do not warn with exception trace

- api/src/main/java/org/apache/cloudstack/api/command/user/vm/CreateVMScheduleCmd.java
Small naming fix for api docs
- Bug fix (non-breaking change which fixes an issue)
-  Minor
-  Trivial
> fix createVMSchedule action name

- agent/src/test/java/com/cloud/agent/AgentShellTest.java
This pull requests tests that we are able to get the next connected host in terms of the VM. This is important in making sure that a list of hosts. 
This test has been tested using the standard maven install lifecycle.
> test update and get connected hosts

- ui/src/views/compute/wizard/MultiNetworkSelection.vue
- ui/src/views/tools/ImportUnmanagedInstance.vue
Fixes #8612
https://github.com/apache/cloudstack/assets/153340/72a8a553-2ba3-4dea-8596-fe9157d5a7e9
> ui: list only accessible networks during import

- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
This PR fixes the issue #8077 with some related error message
Trying to publish the exact error message is bit complicated in this scenario. Operator has anyway need to check the logs, but here tried to keep the appropriate error message to check further.
Case 1:
If the service offering has more CPU number or speed than the whole host's CPU and speed.
Case 2:
If the host does not have free CPU/RAM as requested from the compute offering. The proper error message depends on the over commit ratios and whether or not to consider the reserved capacity of the host, so checking of the logs is needed. 
case 1:
1. Create a service offering with more than the CPU than the host
2. Create an instance with that offering by selecting the host
case 2: 
1. Create a service offering so that the host …
> Fix error message if specific host does not have capacity

- test/integration/smoke/test_register_userdata.py
This PR fixes part of #8586 
by moving the test under new domain/account instead of ROOT account
> test: fix test/integration/smoke/test_register_userdata.py which caused networks not to be deleted

- api/src/main/java/com/cloud/storage/VolumeApiService.java
- engine/api/src/main/java/org/apache/cloudstack/engine/subsystem/api/storage/VolumeService.java
- engine/storage/volume/src/main/java/org/apache/cloudstack/storage/volume/VolumeServiceImpl.java
- engine/storage/volume/src/test/java/org/apache/cloudstack/storage/volume/VolumeServiceTest.java
- server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
- server/src/test/java/com/cloud/vm/UserVmManagerImplTest.java
This PR fixes the issue #9190 
Encryption type change is not allowed for the root volume during the scaleVM and upgradeVM operations. Same check should be made for the ChangeOfferingVolume API.
1. Created two volumes with disk offering types one Encryption enabled and other non-encrypted
2. Tried changing the volume disk offerings to these two volumes to a different typed encryption offerings
3. Operations failed with appropriate errors.
> Add volume encryption checks during the disk offering change

- api/src/main/java/com/cloud/storage/StorageService.java
- api/src/main/java/org/apache/cloudstack/api/command/admin/storage/UpdateImageStoreCmd.java
- api/src/main/java/org/apache/cloudstack/api/response/ImageStoreResponse.java
- engine/components-api/src/main/java/com/cloud/storage/StorageManager.java
- server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
- server/src/main/java/com/cloud/server/StatsCollector.java
- server/src/main/java/com/cloud/storage/StorageManagerImpl.java
- ui/src/config/section/infra/secondaryStorages.js
- ui/src/views/AutogenView.vue
This PR partly ...
Fixes: #8391
By allowing operators to update the capacity of image stores
> Extra parameter for UpdateImageStore

- test/integration/smoke/test_service_offerings.py
This PR fixes the smoke test failure test_service_offering.py on Ubuntu 24.04
```
======================================================================
ERROR: Test CPU Cap on KVM
File "/usr/local/lib/python3.6/site-packages/marvin/lib/decoratorGenerators.py", line 30, in test_wrapper
return test(self, *args, **kwargs)
File "/marvin/tests/smoke/test_service_offerings.py", line 1049, in test_01_service_offering_cpu_limit_use
host_cpu_usage_before = round(float(host_cpu_usage_before_str))
ValueError: could not convert string to float: "top: unknown option 'n'"
-------------------- >> begin captured stdout << ---------------------
=== TestName: test_01_service_offering_cpu_limit_use | …
```
> test: fix test failure on ubuntu 24.04: "top: unknown option 'n'"

- plugins/hypervisors/simulator/src/main/java/com/cloud/agent/manager/MockVmManagerImpl.java
If we stop and start the VM again on another host, simulator doesn't update the host id in simulator database. This PR updates the host id and other parameters which might change for a VM.
1. Start a VM. (Let's say the VM started on host H1)
2. Stop the above VM and start it on any other host (let's say H2).
3. VM gets started on the specified host H2.
4. After some time, host for the VM changes back to H1.
> Fixup startVM on simulator

- server/src/main/java/com/cloud/consoleproxy/AgentBasedConsoleProxyManager.java
- server/src/main/java/com/cloud/consoleproxy/AgentHookBase.java
- server/src/main/java/com/cloud/consoleproxy/ConsoleProxyManager.java
- server/src/main/java/com/cloud/consoleproxy/ConsoleProxyManagerImpl.java
- server/src/main/java/com/cloud/consoleproxy/StaticConsoleProxyManager.java
This PR adds global setting consoleproxy.sslEnabled
without this patch
with this patch
> server: add global setting consoleproxy.sslEnabled

- server/src/main/java/com/cloud/network/guru/PublicNetworkGuru.java
- services/secondary-storage/controller/src/main/java/org/apache/cloudstack/secondarystorage/SecondaryStorageManagerImpl.java
> set isSystem for SVM IPs

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/LibvirtStorageAdaptor.java
I encountered a situation, where libvirt/CloudStack believed a nfs/secondary storage was correctly mounted
and the agent wrote images without any problem into it.
It turned out, that it just wrote everything into a a local /mnt/<uuid> directory and later was only found, because
we couldn't create instances(on a other agent) of the just created template.
I don't know yet how the agent/node got into this state, thinking everything was mounted ok, but instead
writing into a local directory.
This should check after creating the mount that it is really mounted and fail if not.
> libvirtstorage: Make sure netfs storage was really mounted

- plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesServiceHelperImpl.java
- plugins/integrations/kubernetes-service/src/test/java/com/cloud/kubernetes/cluster/KubernetesServiceHelperImplTest.java
The user might create the cluster manually. And since the cluster is being managed by some external provider, it's possible that provider doesn't have context of CKS and deletes the VM. This can lead to failures.
This PR allows deletion of CKS node if the CKS cluster is Externally managed.
> Allow deletion of external managed cks nodes

- engine/storage/datamotion/src/main/java/org/apache/cloudstack/storage/motion/StorageSystemDataMotionStrategy.java
This PR fixes: https://github.com/apache/cloudstack/issues/8827
Importing a VM from a remote host uses a dummy VM template which is not present on the secondary store, leading to NPEs when migrating the VM. This PR enables migrating oly the volume (not the template)
> Support migration of VM imported from a remote host

- api/src/main/java/com/cloud/network/NetworkModel.java
- api/src/main/java/com/cloud/network/guru/NetworkGuru.java
- engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
- server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
- server/src/main/java/com/cloud/network/NetworkModelImpl.java
- server/src/main/java/com/cloud/network/NetworkServiceImpl.java
- server/src/test/java/com/cloud/network/MockNetworkModelImpl.java
- server/src/test/java/com/cloud/network/NetworkModelTest.java
- server/src/test/java/com/cloud/vpc/MockNetworkModelImpl.java
This PR makes changes to allow shared networks to have ipv6 cidr size other than 64. For now, it let's network guru decide whether this is possible or not. Network Orchestrator relies on the return value of `isSlaacV6Only` method of the network guru.
> Let network guru decide if ipv6 cidr size can't be equal to 64

- plugins/integrations/kubernetes-service/src/main/resources/conf/k8s-control-node-add.yml
- plugins/integrations/kubernetes-service/src/main/resources/conf/k8s-control-node.yml
- plugins/integrations/kubernetes-service/src/main/resources/conf/k8s-node.yml
This PR fixes part of #6637 
Command to create the ISO for calico:
```
cd scripts/util
./create-kubernetes-binaries-iso.sh ./ 1.30.1 1.5.0 1.30.0 https://raw.githubusercontent.com/projectcalico/calico/v3.28.0/manifests/calico.yaml https://raw.githubusercontent.com/kubernetes/dashboard/v2.7.0/aio/deploy/recommended.yaml  setup-1.30.1-calico-3.28.0
```
> CKS/calico: set arp_ignore and arp_announce to 0 in k8s controller/nodes

- ui/src/views/infra/zone/ZoneWizardLaunchZone.vue
This PR fixes #8597 
note
- I cannot reproduce the same issue that host is "already in the database". (https://github.com/apache/cloudstack/issues/9034#issuecomment-2092819989)
- I was able to reproduce the issue that "Unable to add host" by renaming /usr/sbin/kvm-ok on ubuntu 22.04 host. when I changed the string in this PR, the issue is ignored.
> UI: ignore error host is already in the database when create a zone

- server/src/main/java/com/cloud/api/query/dao/SnapshotJoinDaoImpl.java
This PR adds the OS type UUID in the list snapshot/snapshots response
> Added ostypeid in the snapshot response

- agent/src/main/java/com/cloud/agent/Agent.java
This PR fixes #8517 
see the steps to reproduce the issue in the description of #8517
> agent: reconnect after waiting 5 seconds

- engine/schema/src/main/java/com/cloud/storage/dao/VolumeDao.java
- engine/schema/src/main/java/com/cloud/storage/dao/VolumeDaoImpl.java
- engine/schema/src/main/java/org/apache/cloudstack/storage/datastore/db/PrimaryDataStoreDao.java
- engine/schema/src/main/java/org/apache/cloudstack/storage/datastore/db/PrimaryDataStoreDaoImpl.java
- plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/guru/VMwareGuru.java
This PR fixes some issues when restore veeam backup (including #8939)
- The storage pool uses PreSetup or VMFS
- The backend use DVS, not standard virtual switch
- The storage pool use Solidfire storage
It has been tested
> veeam: fix issues with PreSetup and DVS and Solidfire

- plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/driver/ScaleIOPrimaryDataStoreDriver.java
This PR fixes src datastore on copy check for PowerFlex/ScaleIO storage driver.
Tested volume migration from pool NFS -> PowerFlex and PowerFlex -> PowerFlex. NFS -> PowerFlex fails with not suitable error.
> Fixed src datastore on copy check for PowerFlex/ScaleIO storage driver

- plugins/backup/veeam/src/main/java/org/apache/cloudstack/backup/veeam/VeeamClient.java
- plugins/backup/veeam/src/test/java/org/apache/cloudstack/backup/veeam/VeeamClientTest.java
- plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/guru/VMwareGuru.java
- vmware-base/src/main/java/com/cloud/hypervisor/vmware/util/VmwareHelper.java
> Fixup main build error

- ui/src/views/network/VnfAppliancesTab.vue
This PR fixes the "Request failed" error when open the "VNF appliances" tab of network
> UI: fix "Request failed." error when open vnf appliances tab of network

- test/integration/smoke/test_cluster_drs.py
> test: fix simulator CI failure test_cluster_drs

- .github/workflows/linter.yml
- .github/workflows/main-sonar-check.yml
- .github/workflows/sonar-check.yml
https://github.com/actions/cache
This PR bumps actions/cache to version 4.
> Bump actions/cache to `v4`

- .github/linters/.flake8
- plugins/hypervisors/ovm/src/main/scripts/vm/hypervisor/ovm/ConfigFileOps.py
- python/lib/cloudutils/configFileOps.py
- scripts/vm/network/security_group.py
- systemvm/debian/opt/cloud/bin/passwd_server_ip.py
- test/integration/component/test_assign_vm.py
- test/integration/component/test_egress_fw_rules.py
- test/integration/plugins/storpool/TestStorPoolVolumes.py
- test/integration/plugins/storpool/sp_util.py
- test/integration/testpaths/testpath_vmlc.py
- tools/marvin/marvin/deployDataCenter.py
There should be only one space before a keyword.
https://www.flake8rules.com/rules/E272.html
This PR cleans up and standardizes the Python code.
Ran locally:
> pre-commit: enable Python flake8 rule `E272`

- server/src/test/java/com/cloud/event/ActionEventInterceptorTest.java
Try to intercept test class methods in new CallContext to prevent getting any leftover data during assertions.
> test: refactor ActionEventInterceptorTest to prevent failures

- engine/schema/src/main/java/com/cloud/usage/dao/UsageDaoImpl.java
This PR fixes removal of usage records
> Fix removal of usage records

- ui/src/views/compute/KubernetesServiceTab.vue
This PR fixes a small UI regression to display FW, PF and LB tabs for CKS on isolated networks
Before Fix:
After fix:
> UI: Display Firewall, LB and Port Forwading rules tab for CKS clusters deployed on isolated networks

- plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java
- ui/src/components/view/ListView.vue
- ui/src/views/compute/KubernetesServiceTab.vue
> Fixup CKS UI for external managed clusters

- test/integration/component/test_acl_sharednetwork_deployVM-impersonation.py
- tools/marvin/marvin/cloudstackException.py
> test: fix component test test_acl_sharednetwork_deployVM-impersonation.py

- engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
The code snippet has been removed in the merge forward of PR #9240 in commit 90fe1d5fdcc2909130b5de6803b57feeff194f54
This PR adds the code back.
> NSX: add back removed code for NSX

- ui/src/components/view/ListView.vue
- ui/src/config/section/infra/routers.js
This PR fixes https://github.com/apache/cloudstack/issues/8008
Before patch:
<details><summary>Details</summary>
<p>
</p>
</details> 
After patch:
<details><summary>Details</summary>
<p>
</p>
</details>
> UI: Improve router listing page

- api/src/test/java/org/apache/cloudstack/api/command/test/ImportRoleCmdTest.java
- plugins/storage/volume/linstor/src/main/java/com/cloud/hypervisor/kvm/storage/LinstorStorageAdaptor.java
This PR fixes issues on main branch after the merge commit: https://github.com/apache/cloudstack/commit/5bf81cf00233efe4478552e7bb13f3e96dc58ed1
> Fix main branch issues

- server/src/main/java/com/cloud/template/HypervisorTemplateAdapter.java
This PR adds the missing events when uploading templates and ISOs.
Fixes: #8052 
Tested uploading templates, ISOs and volumes for comparisson
> Fix Template and ISO upload events

- plugins/affinity-group-processors/host-anti-affinity/src/main/java/org/apache/cloudstack/affinity/HostAntiAffinityProcessor.java
this fixes the exception in smoke test test_affinity_groups
```
2024-08-19T08:34:15,132 ERROR [c.c.a.ApiAsyncJobDispatcher] (API-Job-Executor-87:[ctx-f7804a8e, job-9232]) (logid:b71ddec8) Unexpected exception while executing org.apache.cloudstack.api.command.admin.vm.DeployVMCmdByAdmin com.cloud.utils.exception.CloudRuntimeException: Unable to find on DB, due to: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')  FOR UPDATE' at line 1
at com.cloud.utils.db.GenericDaoBase.searchIncludingRemoved(GenericDaoBase.java:441)
at com.cloud.utils.db.GenericDaoBase.searchIncludingRemoved(GenericDaoBase.java:368)
at com.cloud.utils.db.GenericDaoBase.search(GenericDaoBase.java:357)
at …
```
> server: do not check affinity groups if no vm group mappings

- api/src/main/java/org/apache/cloudstack/api/command/user/vm/UpdateVMCmd.java
> allow users to apply extraconfig on updating VMs

- test/integration/component/test_acl_isolatednetwork.py
- test/integration/component/test_acl_isolatednetwork_delete.py
This PR fixes the component test failures
> test: fix component tests test_acl_isolatednetwork and test_acl_isolatednetwork_delete

- ui/src/views/AutogenView.vue
This PR adds project toggle for buckets, in UI.
Fixes #8422 
Manually verified project toogle in buckets section.
> [UI] Add project toggle for buckets

- ui/src/components/view/InfoCard.vue
This PR Fixes [!9615](https://github.com/apache/cloudstack/issues/9615)
<details>
<summary>
Before
</summary>
</details>
<details>
<summary>
After
</summary>
</details>
> Fixed incorrect label in VRs and  SVMs

- tools/appliance/systemvmtemplate/scripts/configure_systemvm_services.sh
> Update Debian version to 12 in systemvm welcome message

- systemvm/debian/opt/cloud/bin/cs/CsFile.py
- systemvm/debian/opt/cloud/bin/cs_vpnusers.py
This PR fixes #9512 
Prior to this PR
```
root@r-663-VM:/var/cache/cloud# gzip -dk vpn_user_list.json.aae73e2c-32ba-44f3-bf47-426933a67bcb.gz
root@r-663-VM:/var/cache/cloud# /opt/cloud/bin/update_config.py vpn_user_list.json.aae73e2c-32ba-44f3-bf47-426933a67bcb
{'id': 'vpnuserlist', 'test': {'add': True, 'password': 'test', 'user': 'test'}}
{'vpn_users': [{'user': 'test', 'password': 'test', 'add': True}], 'type': 'vpnuserlist', 'delete_from_processed_cache': False}
line = # Secrets for authentication using CHAP
line = # client	server	secret			IP addresses
line =
line =
line = test * test *
```
with this PR
```
root@r-663-VM:/var/cache/cloud# gzip -dk vpn_user_list.json.aae73e2c-32ba-44f3-bf47-426933a67bcb.gz
root@r-663-VM:/var/cache/cloud# /opt/cloud/bin/update_config.py …
```
> VR: remove vpn user info when apply vpn users list

- .asf.yaml
Added FelipeM525(me) as a collaborator in .asf.yaml
>  Add FelipeM525 to .asf.yaml as a collaborator

- deps/install-non-oss.sh
> Fix PR lint error caused by deps/install-non-oss.sh

- ui/src/views/storage/AttachVolume.vue
This PR fixes an UI issue that listing vm takes long time when attach a vm
> UI: list vms with details=min when attach a volume to vm

- engine/schema/src/main/java/com/cloud/storage/dao/DiskOfferingDaoImpl.java
- server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
- server/src/main/java/com/cloud/api/query/dao/DiskOfferingJoinDaoImpl.java
- server/src/main/java/com/cloud/api/query/dao/ServiceOfferingJoinDao.java
- server/src/main/java/com/cloud/api/query/dao/ServiceOfferingJoinDaoImpl.java
- ui/src/components/view/ListView.vue
- ui/src/views/AutogenView.vue
This PR...
Fixes: #9595 
Note that is only fixes the regression reported in #9595, not enhancing it or fixing any ordering bugs that were already present before 4.19, except that the renumbering now only takes place within the page displayed.
both with API (cmk) and UI
> propagate sort order through retrieval sequence

- ui/src/components/view/ListView.vue
- ui/src/components/view/SettingsTab.vue
- ui/src/utils/plugins.js
- ui/src/views/setting/ConfigurationValue.vue
Follow up from https://github.com/apache/cloudstack/pull/9628#discussion_r1743492807
> ui: refactor config update/reset notification

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java
ScaleIO plugin fails to migrate encrypted DATA Volume between clusters:
```
Unable to convert/copy from <REDACTED> to <REDACTED>, due to: qemu-img: Could not open 'file.filename=/dev/disk/by-id/emc-vol-<REDACTED>': Parameter 'encrypt.key-secret' is required for cipher].
at org.apache.cloudstack.engine.orchestration.VolumeOrchestrator.migrateVolume(VolumeOrchestrator.java:1382)
at org.apache.cloudstack.engine.orchestration.VolumeOrchestrator.storageMigration(VolumeOrchestrator.java:1493)
```
Added change to provide passkey not only for ROOT but for DATA Volume as well.
> Provide encryption key for DATA volume type (in addition to ROOT) to copy volume.

- server/src/main/java/com/cloud/network/IpAddressManagerImpl.java
- server/src/main/java/com/cloud/network/vpc/VpcManagerImpl.java
> Fix resource count discrepancy while associating IP address to a network

- core/src/main/java/com/cloud/network/HAProxyConfigurator.java
This PR fixes an issue reproduced by steps below
- create a LB with algorithm=Source (not `source`)
- add a vm to the lb
- check cloudstack VR, haproxy fails
```
Sep 18 06:52:12 r-721-VM haproxy[2042]: [NOTICE]   (2042) : haproxy version is 2.6.12-1+deb12u1
Sep 18 06:52:12 r-721-VM haproxy[2042]: [NOTICE]   (2042) : path to executable is /usr/sbin/haproxy
Sep 18 06:52:12 r-721-VM haproxy[2042]: [WARNING]  (2042) : config : 'stats' statement ignored for proxy 'cloud-default' as it requires HTTP mode.
Sep 18 06:52:12 r-721-VM haproxy[2042]: [WARNING]  (2042) : config : 'option forwardfor' ignored for proxy 'cloud-default' as it requires HTTP mode.
Sep 18 06:52:12 r-721-VM haproxy[2042]: [NOTICE]   (2042) : New worker (2069) forked
Sep 18 06:52:12 r-721-VM haproxy[2042]: [NOTICE]   (2042) : …
```
> lb: fix haproxy cannot start if algorithm is not lowercase

- api/src/main/java/com/cloud/network/NetworkModel.java
- server/src/main/java/com/cloud/network/NetworkModelImpl.java
- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
- server/src/test/java/com/cloud/network/MockNetworkModelImpl.java
- server/src/test/java/com/cloud/vpc/MockNetworkModelImpl.java
This PR filters out networks without access while getting networks with SG with free IPs. Otherwise a VM deployment could fail.
1. Setup a zone with SG
2. Create two accounts A1, A2
3. For both accounts create a network with SG. The network should allow access only to the current account.
4. Launch a VM in account A2 without specifying the network.
If network is not specified, ACS picks up a network with Free IPs in the zone. In this case, the network picked up is from account A1.
If the VM gets deployed for some reason, try the above step again with the other account.
**Expected:** VM should be launched successfully with network in account A2.
**Actual:** VM is not launched because the network is not in the same account as the VM.
> Fix: Filter out networks without access while getting networks with SG with free IPs

- ui/src/config/section/compute.js
Reverts apache/cloudstack#8503
see [9719/comment](https://github.com/apache/cloudstack/pull/9719#issuecomment-2367526084)
> Revert "list VMs by displayname instead of name"

- server/src/main/java/org/apache/cloudstack/network/topology/AdvancedNetworkTopology.java
This PR fixes an issue with network ACL
- create a new ACL list (without any rule) in a VPC
- check current iptables rules in VPC VR
- replace VPC tier with the new ACL list
expected:
- the iptables rules are replaced (to same rules as `default_deny`)
actual:
- the iptables rules are not changed.
- in management-server.log, it shows
```
DEBUG [c.c.n.v.NetworkACLManagerImpl]  Applying NetworkACL for network: 517 with Network ACL service provider
DEBUG [o.a.c.n.t.BasicNetworkTopology] No network ACLs to be applied for network 517
```
> server: apply network ACL even if there is no network ACLs rules in the ACL list

- server/src/main/java/com/cloud/server/ManagementServerImpl.java
This PR fixes https://github.com/apache/cloudstack/issues/9686
> API: Fix listing Userdata by keyword or name

- debian/control
- packaging/el8/cloud.spec
> packaging: add libvirt-daemon-driver-storage-rbd as cloudstack-agent dependency

- pom.xml
This PR reverts systemvm template version to 4.20.0.0
> pom.xml: revert systemvm template version to 4.20.0.0

- framework/db/src/main/java/com/cloud/utils/crypt/EncryptionSecretKeyChanger.java
> sql AND added

- systemvm/agent/scripts/_run.sh
> Remove SNI option in _run.sh, as it is correct as default.

- ui/src/config/section/network.js
> UI: remove duplicated Instance Name in Public IP details page

- server/src/main/java/com/cloud/storage/snapshot/SnapshotManager.java
This PR fixes a typo
No testing required for a typo fix.
N/A
> fix typo in SnapshotManager.java

- ui/src/views/network/StaticRoutesTab.vue
This PR fixes the issue that "Edit tags" dialog cannot be opened for static routes.
> UI: fix cannot open 'Edit tags' modal for static routes

- .github/linters/.markdown-lint.yml
- .pre-commit-config.yaml
- tools/marvin/marvin/misc/build/CI.md
and fix license header
https://github.com/DavidAnson/markdownlint/blob/main/doc/md009.md
https://github.com/DavidAnson/markdownlint/blob/main/doc/md019.md
This PR...
> pre-commit update markdownlint; enable rules MD009,MD019

- .pre-commit-config.yaml
- setup/dev/advancedsg.cfg
- setup/dev/basic.cfg
- tools/devcloud-kvm/devcloud-kvm-advanced-fusion.cfg
- tools/devcloud-kvm/devcloud-kvm-advanced.cfg
- tools/devcloud-kvm/devcloud-kvm.cfg
- tools/devcloud4/advanced/marvin.cfg
- tools/devcloud4/basic/marvin.cfg
- tools/marvin/marvin/config/Baremetal_AdvZone_Vmware.cfg
- tools/marvin/marvin/config/setup.cfg
- tools/marvin/marvin/misc/build/asf_test.cfg
- tools/marvin/marvin/misc/build/kvm.cfg
- tools/marvin/marvin/misc/build/xen.cfg
https://github.com/pre-commit/pre-commit-hooks?tab=readme-ov-file#trailing-whitespace
This hook auto trims trailing whitespace
This PR...
> pre-commit check `.cfg` files with the trailing whitespace hook

- server/src/main/java/com/cloud/deploy/DeploymentPlanningManagerImpl.java
This PR fixes a bug introduces when merging forward #9037 from 4.18 to 4.19. Two lines were added where they shouldn't have.
see https://lists.apache.org/thread/ty756jn3vr7vmltr95087g9vjxm8sqbx
> merge bug fix for #9037; no retrieval of null hosts

- ui/src/components/view/ListView.vue
- ui/src/components/widgets/Status.vue
This PR fixes #9674 
screenshot
> UI: set redundant state as N/A for non-redundant routers

- .asf.yaml
This PR adds myself as a collaborator in `.asf.yaml` in order to be able to add, remove and edit tags to issues/PRs, and to be assigned to issues.
> Add lucas-a-martins as a project collaborator

- README.md
> Revert Holiday season Apache logo

- systemvm/debian/opt/cloud/bin/cs/CsAddress.py
> VPC VR: fix ACL between tier and private gateway

- plugins/storage/volume/linstor/src/main/java/com/cloud/hypervisor/kvm/storage/LinstorStorageAdaptor.java
This is found in some PRs
plugins/storage/volume/linstor/src/main/java/com/cloud/hypervisor/kvm/storage/LinstorStorageAdaptor.java:510: poperties ==> properties
This PR...
> LinstorStorageAdaptor: fix lint error

- .asf.yaml
This PR adds myself as a collaborator in `.asf.yaml` in order to be able to add, remove and edit tags to issues/PRs, and to be assigned to issues.
> Add nicoschmdt as a project collaborator

- server/src/main/java/com/cloud/server/ManagementServerImpl.java
Fixes: https://github.com/apache/cloudstack/issues/9981
This PR attempts to list only those hosts that match source host architecture in a multi-arch zone
> List only those hosts matching source host arch in multi-arch zones

- setup/bindir/cloud-setup-databases.in
This PR fixes the mode and group of `key` file, which should have same setting as db.properties file
see issue below:
```
-rw-r-----. 1 root cloud 4802 Feb  8 13:50 /etc/cloudstack/management/db.properties
-rw-r--r--. 1 root root     8 Feb  8 13:50 /etc/cloudstack/management/key
```
> cloudstack-setup-databases: fix mode and group of key file

- test/integration/plugins/linstor/test_linstor_volumes.py
Fix lint error in the file - test/integration/plugins/linstor/test_linstor_volumes.py
> lint: fix test_linstor_volumes.py

- tools/marvin/marvin/config/test_data.py
This PR fixes: https://github.com/apache/cloudstack/issues/10541 
Test seems to fail due to :
> Update ubuntu image link for template download

- .asf.yaml
Added myself as a collaborator in .asf.yaml to be able to report issues with tags, and be assigned to issues and PRs.
> Add sudo87 as project collaborator

- .asf.yaml
> added: rosi as a contributor

- .github/workflows/ci.yml
This PR fixes the issue with simulator CI
```
elif isfunction(test) and self.selector.wantFunction(test):
File "/home/runner/.local/lib/python3.10/site-packages/nose/selector.py", line 149, in wantFunction
plug_wants = self.plugins.wantFunction(function)
File "/home/runner/.local/lib/python3.10/site-packages/nose/plugins/manager.py", line 99, in __call__
return self.call(*arg, **kw)
File "/home/runner/.local/lib/python3.10/site-packages/nose/plugins/manager.py", line [167](https://github.com/apache/cloudstack/actions/runs/14532936308/job/40775972427#step:14:168), in simple
result = meth(*arg, **kw)
File "/home/runner/.local/lib/python3.10/site-packages/nose/plugins/attrib.py", line 278, in wantFunction
return self.validateAttrib(function)
File …
```
> .github: fix simulator CI caused by imcompatibility between python3.10 and nosetests

- ui/public/locales/en.json
This PR fixes the description of load balancer rule for autoscaling group.
When the autoscaling group is Enabled, the LB can be updated, including the name, sticky policy, algorithm
But the vm instance cannot be removed from the load balancer rule.
> UI: Update message of load balancer for autoscaling group

- INSTALL.md
This PR fixes the broken/outdated Maven download link in `install.md`. The previous URL was either outdated or incorrect.
Download link has been taken from the official Apache Maven [website](https://maven.apache.org/download.cgi).
> docs: correct outdated Maven link in install.md

- server/src/main/java/com/cloud/storage/snapshot/SnapshotManagerImpl.java
This PR corrects a typo in exception message.
> Correct typo in an exception message

- .github/workflows/main-sonar-check.yml
- .github/workflows/sonar-check.yml
This PR fixes sonar checks
```
[Sonar JaCoCo Coverage](https://github.com/apache/cloudstack/actions/runs/15131120112/job/42532247309#step:9:1)
The template is not valid. .github/workflows/sonar-check.yml (Line: 59, Col: 16): hashFiles('**/pom.xml') failed. Fail to hash files under directory '/home/runner/work/cloudstack/cloudstack'
```
> .github: fix sonar checks

- ui/src/components/view/InfoCard.vue
- ui/src/views/compute/CreateAutoScaleVmGroup.vue
- ui/src/views/compute/DeployVM.vue
- ui/src/views/compute/DeployVnfAppliance.vue
- ui/src/views/compute/wizard/DeployButtons.vue
Move Deploy/Create and Cancel button to right info panel in deploy wizards for VM, autoscale grou, vnf appliance
> ui: show deploy/create button on right info pane

- ui/src/components/view/InfoCard.vue
Fixes UI build after 4.20 forward merge
> ui: fix build after forward merge

- server/src/main/java/com/cloud/template/TemplateAdapterBase.java
This PR fixes https://github.com/apache/cloudstack/issues/10945
> Improve error when a template to owned by non root-admin is registered for all zones.

- core/src/main/java/org/apache/cloudstack/direct/download/HttpsDirectTemplateDownloader.java
This PR improves how  HTTP headers are set in the request. Replacing headers.keySet() with headers.entrySet().
This change enhances efficiency by directly accessing both the key and value in a single iteration, rather than fetching the key first and then looking up the value in the map.
Fixes: #10529 
- Ensured that HTTP requests are still correctly setting headers.
- Verified that functionality remains unchanged with test cases.
> Inefficient use of a for loop

- api/src/main/java/org/apache/cloudstack/api/response/BackupScheduleResponse.java
This PR fixes a left over from #11222 (see https://github.com/apache/cloudstack/pull/11222#discussion_r2222437262)
> add since parameter to BackupScheduleResponse

- .pre-commit-config.yaml
- requirements-dev.txt
Also create separate requirements-dev.txt for the pre-commit package
This PR...
fixes #11275
> Fix pre-commit warnings for deprecated stage names

- plugins/user-authenticators/ldap/src/main/java/org/apache/cloudstack/api/command/LdapListUsersCmd.java
- plugins/user-authenticators/ldap/src/main/java/org/apache/cloudstack/ldap/LdapAuthenticator.java
- plugins/user-authenticators/ldap/src/main/java/org/apache/cloudstack/ldap/LdapManagerImpl.java
This PR marks the LDAP user query timeout as incorrect login instead of disabling user immediately.
Fixes #11199
> Mark LDAP user query timeout as incorrect login instead of disabling user immediately

- ui/src/views/infra/network/TrafficTypesTab.vue
Currently wrong parameter - 'itemd' is passed to the `deleteTrafficType` method.
> ui: fix delete traffic type

- ui/src/components/widgets/InfiniteScrollSelect.vue
Earlier it was always using HTTP POST. Ideally, it will always be some list API.
> ui: fix api type in InfiniteScrollSelect

- api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
- api/src/main/java/org/apache/cloudstack/network/RoutedIpv4Manager.java
- plugins/network-elements/netris/src/main/java/org/apache/cloudstack/api/command/AddNetrisProviderCmd.java
- plugins/network-elements/netris/src/main/java/org/apache/cloudstack/api/response/NetrisProviderResponse.java
- plugins/network-elements/netris/src/main/java/org/apache/cloudstack/service/NetrisProviderServiceImpl.java
- server/src/main/java/com/cloud/network/vpc/VpcManagerImpl.java
- server/src/main/java/org/apache/cloudstack/network/RoutedIpv4ManagerImpl.java
- server/src/test/java/com/cloud/network/vpc/VpcManagerImplTest.java
- ui/public/locales/en.json
- ui/src/views/infra/network/ServiceProvidersTab.vue
- ui/src/views/infra/zone/ZoneWizardLaunchZone.vue
- ui/src/views/infra/zone/ZoneWizardNetworkSetupStep.vue
> Netris: Fix Netris provider parameter name and response

- plugins/storage/volume/adaptive/src/main/java/org/apache/cloudstack/storage/datastore/adapter/ProviderAdapter.java
- plugins/storage/volume/adaptive/src/main/java/org/apache/cloudstack/storage/datastore/driver/AdaptiveDataStoreDriverImpl.java
- plugins/storage/volume/flasharray/src/main/java/org/apache/cloudstack/storage/datastore/adapter/flasharray/FlashArrayAdapter.java
- plugins/storage/volume/primera/src/main/java/org/apache/cloudstack/storage/datastore/adapter/primera/PrimeraAdapter.java
Enhanced the Primera storage adapter's volume copy functionality to implement copy method selection based on volume size requirements. The adapter now automatically determines whether to use online copy (fast clone) or offline copy to optimize performance and resource utilization.
Key Changes:
•	Added automatic copy method detection based on source and target volume size comparison
•	Implemented online copy for same-size volumes (immediate cloning with deduplication)
•	Implemented offline copy for volume resize operations (background task with high priority)
•	Enhanced logging with detailed copy method selection rationale and operation progress
•	Added proper task monitoring and completion handling for offline copy operations
•	Optimized copy parameters (provisioning type settings)
N/A - …
> added online/offline copy method for Primera storage adapter

- agent/src/main/java/com/cloud/agent/Agent.java
- core/src/main/java/com/cloud/agent/api/ReadyCommand.java
- engine/orchestration/src/main/java/com/cloud/agent/manager/AgentManagerImpl.java
- engine/orchestration/src/main/java/com/cloud/agent/manager/ConnectedAgentAttache.java
- framework/agent-lb/src/main/java/org/apache/cloudstack/agent/lb/IndirectAgentLB.java
- server/src/main/java/org/apache/cloudstack/agent/lb/IndirectAgentLBServiceImpl.java
This PR improves the handling of agent connections.
Noticed LB check interval is not sent during ready command when MS list and LB algorithm matches from the Startup Command, which is stopping preferred host checker task in the Agent. Fixed this as well.
> Agent connection improvements

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtMigrateCommandWrapper.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStoragePoolManager.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/LibvirtStorageAdaptor.java
This PR fixes live migration of VM with config drive, on KVM.
Fixes #11425 
Tested live migration of VM (with config drive) on KVM hypervisor (OL8).
> Fix for live migration of VM with config drive, on KVM

- api/src/main/java/org/apache/cloudstack/api/response/StatsResponse.java
This PR fixes simulator CI failures
```
Starting Advanced Zone DataCenter deployment
File "/home/runner/work/cloudstack/cloudstack/tools/marvin/marvin/deployDataCenter.py", line 28, in <module>
from marvin import configGenerator
File "/home/runner/.local/lib/python3.10/site-packages/marvin/configGenerator.py", line 21, in <module>
from . import jsonHelper
File "/home/runner/.local/lib/python3.10/site-packages/marvin/jsonHelper.py", line 20, in <module>
from marvin.cloudstackAPI import *
File "/home/runner/.local/lib/python3.10/site-packages/marvin/cloudstackAPI/listVirtualMachinesUsageHistory.py", line 95
""""the time when the VM stats were collected. The format is "yyyy-MM-dd hh:mm:ss""""
^
SyntaxError: unterminated string literal (detected at line 95) …
```
> api: use single quote instead of double quote in StatsResponse

- ui/src/config/section/offering.js
This PR fixes https://github.com/apache/cloudstack/issues/11509
Both the APIs deleteServiceOffering and updateServiceOffering with state value "Inactive" does the same job of setting state to Inactive state. Here the fix is to use the update API as the UI option is to make the offering inactive (not delete).
> [UI] Use update offering APIs to disable compute and disk offerings
