- server/src/main/java/com/cloud/storage/StorageManagerImpl.java
- ui/src/views/infra/AddPrimaryStorage.vue
This PR allows adding zone-wide primary storage on simulator
Before it was not possible to add a zone-wide storage pool on the simulator
After the changes:
Add zone wide primary storage, select Simulator on Hypervisor when Scope = 'Zone'
> [Simulator] Add zone wide storage

- server/src/main/java/com/cloud/deploy/DeploymentPlanningManagerImpl.java
This PR reapply #4338, which is reverted by #3600
> server: reapply checkVmProfileAndHost to check guest os preference

- plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java
This PR fixes https://github.com/apache/cloudstack/issues/5934
(1) create isolated network
(2) add new public IP range
(3) acquire public IP in new IP range
(4) create firewall rule. a new NIC is added to the network VR
(5) release the public IP. - if it is the only IP on the NIC, the nic will be removed
Test 1:
Initial output of `ip a` with default NIC:
Acquired an IP in another Public IP range and added a firewall rule: New nic was added
On deletion of the firewall rule on the NIC, the nic is removed:
Test2:
Add another Public IP range in the same VLAN as the one before 
Acquire & add firewall rule for 2 IPs belonging to 2 different Public IP ranges but the same VLAN, such that there are 2 IPs on a NIC (check eth3)
Remove the rule from one of the IPs, and verify that the IP is …
> [VMware] Support for removal of NIC on IP disassociation on the VR

- ui/src/components/header/ProjectMenu.vue
This PR fixes an issue noticed during listing projects in the Project Menu on the Dashboard view, to swap between projects.
> UI: Fix issue while listing projects in the Project Menu - DashBoard

- engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
- server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
- server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
This PR addresses https://github.com/apache/cloudstack/issues/5512
With the global setting - `match.storage.pool.tags.with.disk.offering` set to true, scaling a VM to an offering with a different storage tag isn't possible. 
Fails with the following exception (tried via cmk):
```
(localcloud) 🐱 > scale virtualmachine id=ce2897f9-90c0-46de-b3b5-0478175c8d0f serviceofferingid=d5b68cac-415d-4343-bef2-36b4b9787abf 
{
"accountid": "138951c3-8e39-11ec-a631-1e00fb00013b",
"cmd": "org.apache.cloudstack.api.command.admin.vm.ScaleVMCmdByAdmin",
"completed": "2022-02-15T09:20:06+0000",
"created": "2022-02-15T09:20:06+0000",
"jobid": "faa4faf1-83c5-4927-b135-89431c110782",
"jobresult": {
"errorcode": 431,
"errortext": "Unable to upgrade virtual machine; the current service …
```
> Allow scaling VM to a service offering having different storage tags

- ui/src/utils/request.js
- ui/src/views/compute/AssignInstance.vue
This PR fixes the issue that the network list when assign vm to other accounts in project view
the issue is found when tested the feature for #5248 
new UI
old /wrong UI
> UI: fix network list when assign vm to other accounts in project view

- plugins/affinity-group-processors/host-anti-affinity/src/main/java/org/apache/cloudstack/affinity/HostAntiAffinityProcessor.java
> server: fix host anti-affinity when start batch vms

- ui/public/locales/en.json
- ui/src/store/getters.js
- ui/src/store/modules/app.js
- ui/src/store/modules/user.js
- ui/src/store/mutation-types.js
- ui/src/views/AutogenView.vue
Fixes https://github.com/apache/cloudstack/issues/5555
Allows users to customize columns to display in the listView
> ui: Adding option to select columns to display

- server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
This PR fixes #6013 
system_use is used to be in disk_offering table before 4.17 which is only applicable to the system service offering. This column is now moved from disk_offering table to service_offering table.
There is a leftover usage of system_use when a user tries to list disk offering. Now we deleted that reference to fix the issue when a user tries to list disk offering.
1. From a user account, tried listing the disk offerings on volume creation wizard and in VM deployment wizard for data disk
2. User could list the disk offerings.
> system_use column is not part of disk offering

- ui/public/locales/en.json
This PR simply rewords the warning on the setting panel which was outdated
Old:
New:
> UI: Reword the setting panel warning

- engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/IscsiAdmStorageAdaptor.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStoragePoolManager.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/LinstorStorageAdaptor.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/ScaleIOStorageAdaptor.java
This PR addresses the changes to disconnect the volumes with the proper storage adaptor.
Fixes #6026 
Tested some VM operations (mainly stop and migrate) with NFS and PowerFlex storage pools.
> [KVM] Disconnect the volumes with the proper storage adaptor.

- engine/components-api/src/main/java/com/cloud/storage/StorageManager.java
- server/src/main/java/com/cloud/storage/StorageManagerImpl.java
- services/secondary-storage/controller/src/main/java/org/apache/cloudstack/secondarystorage/PremiumSecondaryStorageManagerImpl.java
This PR addresses the SSVM scaling issue noticed on VMware.
When active cmds i.e., no of entries in cmd_exec_log table is 0 and the SSVM standby capacity - `secstorage.capacity.standby` is higher than the max sessions an SSVM can handle `secstorage.session.max`, then the no of SSVMs get scaled up. However, when there aren't any active commands, a logic is added to scale down the SSVMs.
Fixes: https://github.com/apache/cloudstack/issues/6038
> [vmware, ssvm] Scale down of ssvm

- scripts/vm/hypervisor/kvm/kvmheartbeat.sh
When an NFS primary storage pool is created, Libvirt mounts the pool with the default NFS configurations (that can be customized by ADMINS via `/etc/nfsmount.conf`)
This would be a typical mounted NFS pool:
```
~# mount -v | grep <pool_path>
<pool_addr>:/<pool_path> on /mnt/a58cd909-77b7-3c48-b355-f9aeddf1a215 type nfs4 (rw,nosuid,nodev,noexec,relatime,vers=4.2,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=<clientAddress>,local_lock=none,addr=<pool_addr>)
```
However, in case the pool is umounted (for whatever reason) `kvmheartbeat.sh` remounts with `timeo=133` and `retrans=10`:
```
~# mount -v | grep <pool_path>
<pool_addr>:/<pool_path> on /mnt/a58cd909-77b7-3c48-b355-f9aeddf1a215 type nfs4 …
```
> Use default timeout and retransmission values for the NFS mount.

- ui/public/locales/en.json
This PR fixes a missing display message when networks are not found on the Vmware import unmanaged instanced dialog
- Import unmanaged instances without creating a network for the VM
> UI: Missing message on VMware VM import for not found networks

- pom.xml
This PR upgrades Tomcat embed version to the closest patched version according to the CVE
Fixes: #5969
> Upgrade Tomcat embed version

- utils/src/main/java/com/cloud/utils/net/NetUtils.java
This PR fixes an NPE thrown at system VMs start (raised on simulator) when the CIDR list is null
````
WARN  [c.c.v.SystemVmLoadScanner] (consoleproxy-1:ctx-8fa500b9) (logid:221dd6d6) Unexpected exception null
at com.cloud.utils.net.NetUtils.isValidCidrList(NetUtils.java:1185)
at com.cloud.consoleproxy.ConsoleProxyManagerImpl.finalizeVirtualMachineProfile(ConsoleProxyManagerImpl.java:1257)
at com.cloud.vm.VirtualMachineManagerImpl.orchestrateStart(VirtualMachineManagerImpl.java:1186)
at com.cloud.vm.VirtualMachineManagerImpl.orchestrateStart(VirtualMachineManagerImpl.java:5307)
at …
```
> Fix NPE on CIDR list check

- api/src/main/java/org/apache/cloudstack/api/command/user/volume/ChangeOfferingForVolumeCmd.java
- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
- ui/src/views/compute/ScaleVM.vue
- ui/src/views/compute/wizard/DiskSizeSelection.vue
This PR fixes the issue noticed when trying to scale a VM to an offering with custom disk offering. 
UI doesn't provide an option to pass the disk size & iops values
Post Fix:
> Allow specifying disk size, min/max iops for offering linked with custom disk offering

- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
This PR checks the network access when deploying VM in Advanced Security Group.
Fixes #6049 
- Before fix, able to deploy VM with ROOT account, in Domain02 using network on Domain01 (in  Advanced Security Group)
- After fix, deploy VM failed with '_Unable to use network with id= 031a45f3-8522-4265-a145-6a647df20d27, permission denied_'
> Check the network access when deploying VM in Advanced Security Group.

- ui/src/views/AutogenView.vue
This PR fixes an issue observed at the volume snapshot operation under the following conditions:
- Take volume snapshot of volume (click OK on the wizard)
- While the operation is still in progress, click Take volume snapshot again
- Wait until the first operation finishes
- Try taking volume snapshot -> ERROR: missing parameter volumeid
Explained on the PR description
> UI: Fix issue on volume snapshots wizard

- engine/schema/templateConfig.sh
This PR fixes: https://github.com/apache/cloudstack/issues/6060
Bash version 3 does not have support for associative arrays. Hence during the packaging phase the metadata.ini file created (on osx) isn't in proper format as the script used to generate it i.e., templateConfig.sh made use of associative arrays - which is supported from bash v4 onward. This eventually leads failure to deploy DB on OSX.
This PR modifies the script to work on systems using bash v3. 
Ran the script with bash v3 ( bash -x engine/schema/templateConfig.sh 4.16.1.0 )and verified the metadata.ini file
> Adapt script to bash version 3

- ui/src/components/view/DedicateData.vue
- ui/src/components/view/ListView.vue
This PR fixes an issue on the navigation to domains, displaying the domain details when clicking on it through different views:
Before the fix:
After the fix:
Navigate to a domain through different views: Accounts, Events
> UI: Fix navigation to domains

- ui/src/components/view/DedicateData.vue
This PR fixes UI issue seen when dedicating an infra component - zone, pod, host, cluster to a domain
Currently, even when the resource is dedicated, it doesn't reflect on the UI - leading to the following state:
On dedicating a zone to a domain - it appears as follows:
> UI: Fix Dedicating resource to a domain

- api/src/main/java/com/cloud/storage/snapshot/SnapshotApiService.java
- engine/storage/volume/src/main/java/org/apache/cloudstack/storage/volume/VolumeServiceImpl.java
- server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
- server/src/main/java/com/cloud/storage/snapshot/SnapshotManagerImpl.java
when delete a volume in QCOW2 format, if volume snapshot does not exist on primary and secondary storage, mark the snapshot as Destroyed.
This fixes #5433
> server: mark volume snapshots as Destroyed if it does not exist on primary and secondary storage when delete a volume

- api/src/main/java/org/apache/cloudstack/api/command/user/template/GetUploadParamsForTemplateCmd.java
This PR an NPE on getUploadTemplateParams for template upload
Fixes: #6071 
````
(localcloud) 🐱 > get uploadparamsfortemplate name=test displaytext=test format=ova hypervisor=vmware ostypeid=6413d8a6-a06a-11ec-86fc-1e003900042d zoneid=17923b3f-5f1a-4098-8277-50adb4e7e909 
{
"getuploadparams": {
"expires": "2022-03-10T13:33:08.844Z",
"id": "a7fc1eea-ad80-4105-8a79-8e628e2571d2",
"metadata": "nEUT1wgt9S2Bh1B7wKLq1yVOSvGnQzF+Q2esSrTZ6Q6ZDXlFZfMkyviE/RfH16pUXHBhLubLVNUCydT+IGBudRJ0re5IEct4n0X3b0/v96rjyz0dLjjaXUGcNNRhs1ZC/vOs3CEfcAeSTyhC2Tq17XCiUWkK4jKOWk3+po0gfSTzEU1/9lIE/JHaXdaZbP5E2ykuoICO6/kb/3RjNfivBqg9rJP6U+KTsVJBbd09xVmD7og/5cqtZsSZt6b6C7Vgqgg+chaQcSsKbNyrHjxOMuNCTOlCqJH5QZg7q1TVvrsz22IW+RmgF/EkVaRNLcI8ioVWOcMwAhfo9RBgTADfvWNu1GeqEiixMYcfK2S3NxwVlzwKGq59uOv/PRqjTzOpHcN5v3ebfpLBQMW1D9lVWG …
```
> Fix get upload params NPE

- ui/src/views/infra/AddPrimaryStorage.vue
This PR fixes the label for the Protocol field on the Add primary storage wizard
Before:
After:
Add Storage Pool -> Verify label
> UI: Fix storage pool label for protocol

- ui/src/components/header/ProjectMenu.vue
This PR improves clarity to the user concerning the project list view component. The current behavior disables the project view menu when an Account does not have permission to list projects. However, that can be a bit confusing for users, if they have no permission to list projects, then, the expected behavior would be to hide the component that the user does not have access to (that is what happens with other components). Therefore, this PR aims to hide the project view when the user does not have the permission list projects.
**Before:**
**After:**
This was tested in a local lab.
Login with an Account that had the permission to the api `listProjects`:
It displayed the Project Menu view as expected.
Login with an Account that didn't have the permission to the api `listProjects`:
The …
> [UI] Dont show project view menu when user doesn't have permission

- ui/src/views/offering/AddNetworkOffering.vue
Fixes default visibility of MAC learning warning
Before
After
> ui: fix mac learning warning visibility in add network offering

- ui/src/views/infra/network/IpRangesTabGuest.vue
Fixes icon
Fixes object change
Before
After
> ui: fix physical network guest traffic type tab

- tools/travis/script.sh
> travis: run nosetests-3.4

- ui/src/views/compute/CreateKubernetesCluster.vue
Fixes the issue of always sending 2 control plan nodes in the CreateKubernetesCluster vue
> ui: Fix CreateKubernetesCluster for ha

- tools/marvin/marvin/cloudstackException.py
This PR fixes a subset of travis test failures as indicated in: https://github.com/apache/cloudstack/issues/6115
They include:
component/test_acl_sharednetwork_deployVM-impersonation:
- test_deployVM_in_sharedNetwork_as_regularuser_scope_all_anotherusersamedomain
- test_deployVM_in_sharedNetwork_as_regularuser_scope_all_crossdomain
component/test_acl_isolatednetwork
- test_19_deployvm_user_foruserinsamedomain
- test_20_deployvm_user_foruserincrossdomain
- test_29_restartNetwork_user_foruserinsamedomain
- test_30_restartNetwork_user_foruserinotherdomain
component/test_acl_isolatednetwork_delete
- test_deleteNetwork_user_foruserinotherdomain
- test_deleteNetwork_user_foruserinsamedomain
> Travis - fix test failures observed

- server/src/main/java/com/cloud/ha/HighAvailabilityManagerImpl.java
When ha is performed on vm's send the alert for it so that
its for admins to know which vm's got ha'ed else its time
consuming to get those details from logs
> alert: Send alert for ha'ed vm's

- engine/schema/pom.xml
- packaging/centos7/cloud.spec
- packaging/centos8/cloud.spec
- packaging/package.sh
- packaging/suse15/cloud.spec
As I pointed on thread [[VOTE] Apache Cloudstack 4.16.0.0 RC1](https://lists.apache.org/thread.html/rc061a4da7bd50b49ff99b41f059cb4088b998929033755e4b87f631d%40%3Cdev.cloudstack.apache.org%3E), regarding the auto upgrading `systemvms-templates`; the code will  `autoupgrade` the `systemvm-templates` if the templates are found locally. To generate the template during the build, one has to activate the `noredist profile` when building the packages, which is necessary (normally used to) only to VMWare.
Some people, might not want the noredist JARs from VMware, and therefore will not build with this profile. Furthermore, package `cloudstack-management` goes from **~100Mb** to more than **1.5Gb** when using the `noredist` while executing the 4.16.0.0 build. It happens due to …
> Create profiles to download systemvm-templates

- engine/storage/datamotion/src/main/java/org/apache/cloudstack/storage/motion/KvmNonManagedStorageDataMotionStrategy.java
This PR attempts to fix: https://github.com/apache/cloudstack/issues/6114
> Fix migration of VM with volume on Ubuntu

- ui/src/views/network/LoadBalancing.vue
This PR fixes the icon for assigning LB rule to a VM .
> ui: Fix icon on Load Balancing view tab

- server/src/main/java/com/cloud/network/element/VirtualRouterElement.java
- server/src/main/java/com/cloud/network/element/VpcVirtualRouterElement.java
- server/src/main/java/com/cloud/network/router/NetworkHelper.java
- server/src/main/java/com/cloud/network/router/NetworkHelperImpl.java
- server/src/main/java/com/cloud/network/router/NicProfileHelper.java
- server/src/main/java/com/cloud/network/router/NicProfileHelperImpl.java
- server/src/main/java/com/cloud/network/router/VirtualNetworkApplianceManagerImpl.java
- server/src/main/java/com/cloud/network/router/VpcNetworkHelperImpl.java
- server/src/main/java/org/apache/cloudstack/network/router/deployment/RouterDeploymentDefinition.java
- server/src/main/java/org/apache/cloudstack/network/router/deployment/RouterDeploymentDefinitionBuilder.java
- server/src/main/java/org/apache/cloudstack/network/router/deployment/VpcRouterDeploymentDefinition.java
- server/src/main/resources/META-INF/cloudstack/core/spring-server-core-managers-context.xml
- server/src/test/java/com/cloud/network/element/VirtualRouterElementTest.java
- server/src/test/java/org/apache/cloudstack/network/router/deployment/RouterDeploymentDefinitionTest.java
- server/src/test/java/org/apache/cloudstack/network/router/deployment/RouterDeploymentDefinitionTestBase.java
- server/src/test/java/org/apache/cloudstack/network/router/deployment/VpcRouterDeploymentDefinitionTest.java
This PR fixes NPE by initializing diskOfferingDao.
```
at org.cloud.network.router.deployment.RouterDeploymentDefinition.verifyServiceOfferingByUuid(RouterDeploymentDefinition.java:411)
at org.cloud.network.router.deployment.RouterDeploymentDefinition.findAccountServiceOfferingId(RouterDeploymentDefinition.java:400)
at org.cloud.network.router.deployment.RouterDeploymentDefinition.findServiceOfferingId(RouterDeploymentDefinition.java:423)
at org.cloud.network.router.deployment.RouterDeploymentDefinition.executeDeployment(RouterDeploymentDefinition.java:378)
at org.cloud.network.router.deployment.RouterDeploymentDefinition.findOrDeployVirtualRouter(RouterDeploymentDefinition.java:242)
at org.cloud.network.router.deployment.RouterDeploymentDefinition.deployVirt …
```
> server: fix NPE when router.service.offering is set due to service/disk offering refactoring

- server/src/main/java/com/cloud/projects/ProjectManagerImpl.java
This PR cleans up and restructures the code that checks and applies invites on update.
should be tested by the project smoke tests.
> account check made explicit - cleanup

- ui/src/views/compute/DeployVM.vue
This PR prevents boot type & boot mode being passed for a template is registered as deploy-as-is
Successfully deploys a VM from a template registered as deploy-as-is without passing boot mode & type
> UI: Prevent passing boottype/bootmode when template is deploy-as-is

- ui/src/components/view/SearchView.vue
Fixes the wrong label in the annotations search view
> ui: Fix wrong label entity.type

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java
This PR fixes #5987 
The steps to support multiple storage pools
(1) if zone does not support local storage, go to zone details and edit zone, check "Enable local storage for User VMs"
(2) create local directories on kvm hosts
(3) edit /etc/cloudstack/agent/agent.properties, add extra directories and UUIDs (can be generated by `uuidgen`)
local.storage.uuid=a43943c1-1759-4073-9db1-bc0ea19203aa,f5b1220b-4446-42dc-a872-cffd281f9f8c
local.storage.path=/var/lib/libvirt/images,/var/lib/libvirt/images2
(4) restart cloudstack-agent
> kvm: support multiple local storage pools

- engine/orchestration/src/main/java/com/cloud/agent/manager/AgentManagerImpl.java
Sometimes when host isput into maintenance, the connection get
disconnected and as result vm's are stopped. So check for extra state
before considering host as down and stopping the vm's
> Prevent vm's from stopping while enabling maintenance mode

- api/src/main/java/org/apache/cloudstack/api/command/user/vm/ListVMsCmd.java
- server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
This PR removes the redundant api parameters listed under listVirtualMachines API. The parameters are already defined in `ListVMsCmdByAdmin` class
```
(localcloud) 🐱 > list virtualmachines -h
listVirtualMachines: List the virtual machines owned by the account.
API Params               Type     Description
==========               ====     ===========
account                  string   list resources by account. Must be used w
ith the domainId parameter.
...
hostid                   uuid     the host ID
hostid                   uuid     the host ID
...
podid                    uuid     the pod ID
podid                    uuid     the pod ID
...
storageid                uuid     the storage ID where vm's volumes belong 
to
storageid                uuid     the storage ID where vm's volumes …
```
> api: Remove redundant API parameters

- ui/src/views/offering/AddNetworkOffering.vue
This PR fixes the UI issue that creating network offering for L2 networks fails with error "Service UserData is not enabled for the network offering, can't add a provider to it"
> UI: fix create l2 network offering with userdata

- api/src/main/java/com/cloud/hypervisor/Hypervisor.java
Use map to avoid multiple if else statement. This will support
more types in future mithout much code change
> Avoid multiple if else

- server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
This PR fixes issue with resetConfiguration for settings defined in Config.java
Before Fix:
Post Fix:
Successfully able to reset config
> api: Fix reset configuration

- server/src/main/java/com/cloud/network/element/ConfigDriveNetworkElement.java
This PR fixes the issue observed when trying to expunge a VM created using config drive userdata service (with startVM=false) and the env has no secondary stores.  
1. On an env with no secondary store, set the global setting: `vm.configdrive.primarypool.enabled` to true
2. Deploy a VM with a network offering with configDrive userdata service, but do not start it
3. Attempt deleting(expunge) the VM - the VM deletes successfully without NPE 
Performed the above test with  `vm.configdrive.primarypool.enabled` set to false and was also able to expunge the VM
> configDrive: Fix failure to delete (unstarted) VM

- ui/src/views/compute/ScaleKubernetesCluster.vue
This PR fixes the issue with scale Kubernetes cluster form:
Form loads properly post fix:
> ui: Fix scale kubernetes (cks) cluster form

- ui/src/components/header/HeaderNotice.vue
- ui/src/components/menu/SMenu.vue
- ui/src/components/page/GlobalLayout.vue
- ui/src/components/page/PageHeader.vue
- ui/src/components/page/PageLayout.vue
- ui/src/components/view/ActionButton.vue
- ui/src/components/view/InfoCard.vue
- ui/src/components/view/ListView.vue
- ui/src/components/widgets/Breadcrumb.vue
- ui/src/components/widgets/TooltipButton.vue
- ui/src/core/lazy_lib/icons_use.js
- ui/src/layouts/UserLayout.vue
- ui/src/style/vars.less
- ui/src/views/AutogenView.vue
- ui/src/views/auth/Login.vue
- ui/src/views/compute/DeployVM.vue
- ui/src/views/compute/DestroyVM.vue
- ui/src/views/dashboard/UsageDashboard.vue
- ui/src/views/dashboard/UsageDashboardChart.vue
- ui/src/views/infra/InfraSummary.vue
- ui/src/views/project/AccountsTab.vue
- ui/src/views/project/InvitationsTemplate.vue
This PR fixes https://github.com/apache/cloudstack/issues/6107
> UI - Fixes UI bugs

- ui/src/components/view/ResourceView.vue
- ui/src/views/network/VpcTiersTab.vue
When redirecting to VPC tier from VPC view, details tab should be active by default
Before:
After:
> ui: fix vpc tier redirect to show details

- api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
- api/src/main/java/org/apache/cloudstack/api/command/user/network/UpdateNetworkCmd.java
- ui/public/locales/en.json
updateinsequence param for updateNetwork API wasn't have correponding label in UI.
Before:
After:
> ui,refactor: fix missing label in update network form

- engine/components-api/src/main/java/com/cloud/storage/StorageManager.java
- server/src/main/java/com/cloud/storage/StorageManagerImpl.java
- server/src/main/java/com/cloud/storage/listener/StoragePoolMonitor.java
Add a global setting so that disabled pools will be mounted
again on host reboot
1. Disable the storage pool
2. Set the global setting `mount.disabled.storage.pool` to true
3. The pool will still be mounted in the host.
4. Reboot the host.
5. The pool will still be mounted
6. Change the setting to false
7. Reboot the host
8. The disabled pool will not be mounted
> Mount disabled storage pool on host reboot

- core/src/main/java/com/cloud/agent/api/ReadyAnswer.java
- engine/orchestration/src/main/java/com/cloud/agent/manager/AgentManagerImpl.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtReadyCommandWrapper.java
- plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/VmwareServerDiscoverer.java
- plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java
- plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/discoverer/XcpServerDiscoverer.java
- plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/CitrixResourceBase.java
- plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/wrapper/xenbase/CitrixReadyCommandWrapper.java
- server/src/main/java/com/cloud/hypervisor/kvm/discoverer/LibvirtServerDiscoverer.java
Fixes https://github.com/apache/cloudstack/issues/6087
Adds support to detect existing hosts with UEFI capability
- Bring up a 4.13 env with VMware 6.5 (anything that supports UEFI)
- Upgrade to latest main 
- Try to deploy a VM with UEFI
- Deployment now passes Previously failed to find a suitable host as none were UEFI compatible
```
MariaDB [cloud]> select * from host_details where name = 'host.uefi.enable' \G
Empty set (0.00 sec)
```
```
MariaDB [cloud]> select * from host_details where name = 'host.uefi.enable' \G
id: 34
host_id: 1
name: host.uefi.enable
value: true
*************************** 2. row ***************************
id: 40
host_id: 2
name: host.uefi.enable
value: true
2 rows in set (0.00 sec)
```
> agent: Detect existing hosts with UEFI support

- systemvm/debian/opt/cloud/bin/configure.py
This PR fixes missing "-m tcp" or "-m udp" which cause some networking issues.
> VR: add '-m <protocol>' for tcp or udp protocol

- ui/src/api/index.js
This PR calls the logout API before login, to cleanup any duplicate sessionkey, as it was done on the legacy UI: https://github.com/apache/cloudstack/pull/4326
Fixes: #6127
> UI: Logout before login

- .asf.yaml
This is to re-kick an integration issue, following Daniel's advice on asf-infra slack;
> .asf.yaml: dummy fix to re-kick asf-infra integration

- api/src/main/java/org/apache/cloudstack/api/command/admin/backup/UpdateBackupOfferingCmd.java
- server/src/main/java/org/apache/cloudstack/backup/BackupManagerImpl.java
- server/src/test/java/org/apache/cloudstack/backup/BackupManagerTest.java
This PR aims to add a new field to the `updateBackupOffering` API, allowing users to change the `allowuserdrivenbackups` parameter of a Backup Offering. Some unit tests were adapted/fixed as well.
This was tested in a local lab, by calling the `updateBackupOffering` API multiple times and changing a Backup Offering's parameters back and forth.
> Added new field to updateBackupOffering API.

- server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
- server/src/main/java/com/cloud/storage/StorageManagerImpl.java
Allow storage.overprovisioning.factor to be <1 which allows underprovisiong of pools
By setting the value to 0.5 (example) we can underprovision a storage pool. This is useful in
cases with Ceph where it reports the raw size of the cluster where the replication factor is
not taken into account.
Fixes: ##6205
> Allow storage.overprovisioning.factor to be <1

- engine/schema/src/main/java/com/cloud/upgrade/dao/Upgrade41610to41700.java
This PR fixes the value set for `minreq.sysvmtemplate.version` when upgrading to 4.17. Because of the value being hard-coded to 4.16.0 at  https://github.com/apache/cloudstack/blob/main/engine/schema/src/main/java/com/cloud/upgrade/dao/Upgrade41610to41700.java#L73 it doesn't pick the right value, i.e., 4.16.1
Upgrade from 4.16 to 4.17 and validate the global setting minreq.sysvmtemplate.version value
> upgrade: update minreq.sysvmtemplate.version to the latest template version

- server/src/main/java/org/apache/cloudstack/vm/UnmanagedVMsManagerImpl.java
Fixes #6121
deviceId for a volume/disk is never used by CloudStack VMware hypervisor plugin. Still it would be correct to increment value for each data volume/disk, behaviour similar to adding data volumes/disks.
> server: increment deviceid while importing vm data volumes

- systemvm/debian/root/health_checks/gateways_check.py
The output always returns 1 since all gateways are present in one line
but the actual output should be the number of gateways present
in that line
Before the fix
```
gw is [{u'gatewaysIps': u'10.135.126.254 169.254.0.1'}]
gwsList is [u'10.135.126.254', u'169.254.0.1']
All 1 gateways are reachable via ping
```
After the fix
```
gw is [{u'gatewaysIps': u'10.135.126.254 169.254.0.1'}]
gwsList is [u'10.135.126.254', u'169.254.0.1']
All 2 gateways are reachable via ping
```
> Display proper gateway length in health check result

- ui/src/views/infra/AddSecondaryStorage.vue
This PR fixes the Add secondary storage wizard failing due to a missing parameter
Fixes: #6239 
Tested on simulator -> Add secondary storage working as expected
> UI: Fix Add secondary storage

- server/src/main/java/com/cloud/network/element/ConfigDriveNetworkElement.java
This PR fixes an issue observed during expunging a VM deployed on a network using COnfigDrive userdata service and host cache
```
2022-04-08 07:24:14,834 ERROR [c.c.a.ApiAsyncJobDispatcher] (API-Job-Executor-8:ctx-e4d333b0 job-78) (logid:a6b8b1aa) Unexpected exception while executing org.apache.cloudstack.api.command.admin.vm.DestroyVMCmdByAdmin
com.cloud.utils.exception.CloudRuntimeException: Unable to get an answer to handle config drive deletion for vm: i-2-8-VM on host: 1
at com.cloud.network.element.ConfigDriveNetworkElement.deleteConfigDriveIsoOnHostCache(ConfigDriveNetworkElement.java:569)
at com.cloud.network.element.ConfigDriveNetworkElement.deleteConfigDriveIso(ConfigDriveNetworkElement.java:638)
at com.cloud.network.element.ConfigDriveNetworkElement.postStateTransitionEvent(Conf …
```
> Allow expunging a VM on a deleted host when using host cache and ConfigDrive userdata service

- ui/src/views/infra/AddPrimaryStorage.vue
This PR fixes the Add primary storage wizard: protocol got reset to always 'NFS' after changing the provider
Tested on KVM env - Add primary storage
> UI: Fix protocol reset after changing provider on Add Primary Storage

- ui/src/views/infra/InfraSummary.vue
This PR fixes 2 issues:
1. despite providing the privateKey i.e., pkcs form field, it isn't recognized
2. on submitting the form, the handler function isn't invoked
Successfully submits the form
> ui: Fix uploadCustomCertificate form in infraSummary view

- server/src/main/java/com/cloud/network/router/NetworkHelperImpl.java
This PR fixes https://github.com/apache/cloudstack/issues/6084
The global setting system.vm.default.hypervisor will be the first option when deploy VRs.
If it is not set, use the hypervisor type of cluster as 2nd option.
> server: honor global setting system.vm.default.hypervisor as first option when deploy VRs

- agent/conf/agent.properties
- agent/src/main/java/com/cloud/agent/properties/AgentProperties.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
This PR fixes #6252 
When using advanced virtualization, the IO Driver is not supported. The admins will decide if they want to enable/disable this configuration from `agent.properties` file. It's enabled by default
> Extract the IO_URING configuration into the agent.properties

- server/src/main/java/com/cloud/configuration/Config.java
- server/src/main/java/com/cloud/user/AccountManagerImpl.java
- server/src/test/java/com/cloud/user/AccountManagerImplTest.java
This PR allows disabling the login attempts mechanism to disable users after a number of failed login attempts
Fixes: #6251
> Fix: Allow disabling the login attempts mechanism for disabling users

- api/src/main/java/com/cloud/storage/snapshot/SnapshotApiService.java
- server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
- server/src/main/java/com/cloud/storage/snapshot/SnapshotManagerImpl.java
If `kvm.snapshot.enabled` is set to false then we cant create snapshot from
VM snapshot. With this change, its possible to create snapshot from VM
snapshot even when the global setting is set to false.
Note that you still cant directly create a snapshot from volume though
> Allow creating snapshot from VM snapshot

- server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
- server/src/test/java/com/cloud/storage/VolumeApiServiceImplTest.java
This PR fixes #6263.
The issue is that an Exception is thrown when scaling a customized offering, changing the CPU/Memory but keeping the same disk offering.
This PR proposes a fix for this issue by skipping the volume "upgrade" process in such situations, avoiding any operations and also the thrown exception.
Considering that the disk offering is the same, there is no need to run all actions of the respective method.
The skipped actions are, in summary:
1. run DB updates matching the "new offering";
2. publish EVENT_VOLUME_RESIZE;
3. if volume migration is required (and allowed), find a suitable pool to migrate volume in case the current pool does not match the new offering needs;
4. return a "Volume" object containing all the changes.
- Scale (via UI or API) a VM with the custom …
> Fix #6263 Cannot scale VM with custom offering

- ui/src/components/view/ListView.vue
- ui/src/views/AutogenView.vue
This PR fixes the incorrect column listed in the filter columns drop-down menu in secondary store list view
> ui: Incorrect column key specified in secondary store column filter

- plugins/user-authenticators/saml2/src/main/java/org/apache/cloudstack/saml/SAMLUtils.java
This change will set the sessionkey under the /client/api path. This commit should prevent duplicate sessionkey cookies from being set on both /client (incorrect) and /client/api (correct). Prior to this commit, the /client version was being set while the /client/api version remained unchanged with an invalid sessionkey. As a result, subsequent requests after the SAML2 authentication would immediately fail with an invalid session and results in the user being logged out. 
The sessionkey is now set explicitly for the /client/api path which should fix this issue, regardless of the SSO URL and path that's being used.
Fixes: #6127
I've built 4.16.1.0 with this change and SAML2 auth is now working as expected again.
> Update SAML2 auth sessionkey cookie path

- ui/src/views/image/RegisterOrUploadTemplate.vue
- ui/src/views/image/UpdateTemplate.vue
This PR removes the requirement to pass a root disk controller while either registering a template or while updating a template
Legacy UI did not enforce root disk controller to be passed:
Registered / Attempted editing a template without passing root disk controller & deployed VM with the template
> ui: remove mandatory rule on root disk controller field while registering / updating a template

- ui/src/views/compute/DeployVM.vue
This PR fixes an issue in UI in which CPU speed is not displayed for custom unconstrained offerings for a specific zone (specified on the offering creation)
- Create custom unconstrained offering selecting a zone
- Deploy VM selecting offering -> CPU speed is visible after the fix
> UI: Fix custom unconstrained for a zone does not show CPU speed

- server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
This PR updates reset configuration, to return the updated config value in its initial response.
Tested reset configuration from UI / API (cmk).
**List config before reset =>**
```
(cloud) 🐱 > list configurations name="storage.pool.disk.wait"
{
"configuration": [
{
"category": "Storage",
"component": "StorageManager",
"defaultvalue": "60",
"description": "Timeout (in secs) for the storage pool disk (of managed pool) to become available in the host. Currently only supported for PowerFlex.",
"displaytext": "Storage pool disk wait",
"group": "Storage",
"isdynamic": true,
"name": "storage.pool.disk.wait",
"subgroup": "Storage",
"type": "Number",
"value": "65"
}
],
"count": 1
}
```
**Before Fix =>**
```
(cloud) 🐱 > reset configuration name="storage.pool.disk.wait"
{
"configuration": { …
```
> Fixed reset configuration response, to return the updated config value.

- ui/src/config/section/compute.js
- ui/src/views/AutogenView.vue
This PR fixes the issue observed during bulk deletion of ssh key pairs where in it doesn't actually invoke the delete operation.
> ui: Fix bulk deletion of ssh key pairs

- ui/src/views/image/RegisterOrUploadTemplate.vue
This PR fixes the UI issue that `checksum` field is required on UI.
this is a regression of #5151
> UI: checksum field is optional for direct-download templates on kvm

- ui/public/locales/en.json
- ui/src/components/view/ListView.vue
This PR displays the load balancer rule in the internal LB list view which appears as an empty column, while the details view shows it.
vs 
Also, there is a missing translation for a param field in the Add Internal LB form:
Goto http://<IP>:8080/#/ilb
1. And view the list view - where the lb rule is displayed:
2. Missing translation added:
> ui: Fix Internal LB LB rule column and missing translation

- server/src/main/java/com/cloud/api/ApiDBUtils.java
This PR fixes an NPE while listing VMs - has been found while testing detach ROOT volume from VM on PR #6201 (which simply adds a UI option for this operation, it can be replicated by the API)
````
2022-04-19 15:17:37,061 DEBUG [c.c.a.m.AgentManagerImpl] (AgentManager-Handler-8:null) (logid:) SeqA 3-6270: Processing Seq 3-6270:  { Cmd , MgmtId: -1, via: 3, Ver: v1, Flags: 11, [{"com.cloud.agent.api.ConsoleProxyLoadReportCommand":{"_proxyVmId":"2","_loadInfo":"{
"connections": []
}","wait":"0","bypassHostMaintenance":"false"}}] }
2022-04-19 15:17:37,064 DEBUG [c.c.a.m.AgentManagerImpl] (AgentManager-Handler-8:null) (logid:) SeqA 3-6270: Sending Seq 3-6270:  { Ans: , MgmtId: 32988268069116, via: 3, Ver: v1, Flags: 100010, [{"com.cloud.agent.api.AgentControlAnswer":{"result":"true","wait":"0" …
```
> Fix: Prevent NPE on disk offering search while listing VMs

- api/src/main/java/org/apache/cloudstack/api/command/user/volume/AttachVolumeCmd.java
- ui/src/config/section/storage.js
- ui/src/views/storage/AttachVolume.vue
It was already possible via API to attach and detach ROOT disks as well as DATADISKs. However, it was only possible to call these methods on DATADISKs through the UI. This PR implements this functionality on the ROOT disks via UI as well with the use of the `deviceid` parameter. Moreover, the API description for `attachVolume` was improved for a better understanding.
This was tested on a local lab with the following scenarios:
VM1 with ROOT disk and DATA disk:
- Attach DATADISK with deviceid = 0 gives error, as expected.
- Attach DATADISK with deviceid = 1 gives error, as expected.
- Attach DATADISK with deviceid = 2 with success, as expected.
VM2 without ROOT disk:
- Attach DATADISK with deviceid = 0. The DATADISK was recognized as ROOT disk, as expected.
- Attach DATADISK with deviceid …
> [UI] Added attach and detach features to UI for ROOT disks

- ui/src/permission.js
This PR toggle to default view when logging in after having logged out from project view.
1. Project View:
2. Logout when in project view and re-login:
Dark theme still persists
Logout from project view & login again, and the UI loads with light theme
> ui: Toggle Theme to default(light) on login

- ui/src/views/network/CreateSharedNetworkForm.vue
This PR fixes the issue that ip4 netmask is not passed to cloudstack api when create a shared network.
> UI: fix netmask is not passed to api when create share network

- agent/src/main/java/com/cloud/agent/AgentShell.java
This PR enables SSL in kvm agent if keystore exists.
This fixes the issue in URL check of direct-download templates
> KVM: Enable SSL if keystore exists

- engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/snapshot/SnapshotObject.java
- test/integration/smoke/test_list_ids_parameter.py
This PR fixes the constant test failure noticed on test_list_ids_parameter.py on xenserver :
https://github.com/apache/cloudstack/pull/5811#issuecomment-1104053583
The reason for the failure is that on 4.17, when attempting to delete a snapshot that has child snapshots, it fails deletion of the snapshot altogether. In addition to this, an NPE occurs when displaying the details of the child snapshot due to incorrect snapshot id used to get the details.
```
2022-04-21 04:47:42,145 DEBUG [o.a.c.s.s.DefaultSnapshotStrategy] (API-Job-Executor-47:ctx-ef3948e6 job-63 ctx-144c6c26) (logid:a43f2bcd) Deleting SnapshotTO[datastore=com.cloud.agent.api.to.NfsTO@75866c9d|volume=volumeTO[uuid=c1aaba2a-396e-4979-9793-8d54b906ecf5|path=7e848981-a142-4b6f-8ed8-ec8ab4f84f26|datastore=PrimaryDataStoreTO[uuid= …
```
> xen: Fix volume snapshot deletion when it has child snapshots

- server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
This PR fixes an issue if format is not properly passed in uppercase.
Note: this issue is applicable only to API when format value is lowercase, UI passes the format in uppercase to the uploadVolume API
````
2022-04-21 19:48:57,569 ERROR [c.c.a.ApiAsyncJobDispatcher] (API-Job-Executor-23:ctx-319bdf84 job-425147) (logid:864904bb) Unexpected exception while executing org.apache.cloudstack.api.command.admin.volume.UploadVolumeCmdByAdmin
java.lang.IllegalArgumentException: No enum constant com.cloud.storage.Storage.ImageFormat.ova
at java.base/java.lang.Enum.valueOf(Enum.java:240)
at com.cloud.storage.Storage$ImageFormat.valueOf(Storage.java:25)
at com.cloud.storage.VolumeApiServiceImpl$2.doInTransaction(VolumeApiServiceImpl.java:559)
at …
```
> Fix upload volume format

- ui/src/views/infra/Metrics.vue
This PR fixes the display format for the last successful job for the usage statistics:
Before:
After:
List DB/Usage stats
> UI: Fix Usage Server stats date display

- ui/src/components/view/UploadResourceIcon.vue
This PR fixes an issue on the upload resource icon dialog if no image is selected:
The Upload button is disabled unless an image is selected
Upload resource icon -> try uploading without providing image -> select image -> upload
> UI: Fix upload resource icon button

- server/src/main/java/com/cloud/api/ApiSessionListener.java
This PR fixes (some of) the excessive log sizes caused by #5588
> remove superfluent counter and fix log message

- plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageLayoutHelper.java
Using the VMWare (version 6.5), when trying to detach a volume, vCenter detaches it successfully; however, ACS throws an exception. It already was reported in VMWare and ACS' communities, but it hasn't been fixed yet. For more information about this error, please check this links ([1], [2], [3]).
To know why ACS tries to check folder content, please check these links ([4], [5]). This error apparently only occurs with datastores that use the NFS protocol and  n specific versions of VMWare. Users using VMFS or VMWare versions greater than 6.7 have not reported this error. If the operation performed is a volume detach, it was successful. If you want to know why this error occurs in VMWare, please contact VMWare's technical support.
It was tested in a local lab:
1. I created a new VM with two …
> [VMWare] error when detaching volume

- api/src/main/java/org/apache/cloudstack/api/command/user/ipv6/CreateIpv6FirewallRuleCmd.java
- api/src/main/java/org/apache/cloudstack/api/command/user/ipv6/DeleteIpv6FirewallRuleCmd.java
- api/src/main/java/org/apache/cloudstack/api/command/user/ipv6/UpdateIpv6FirewallRuleCmd.java
- core/src/main/java/com/cloud/agent/api/routing/SetIpv6FirewallRulesCommand.java
- core/src/main/java/com/cloud/agent/resource/virtualnetwork/facade/SetIpv6FirewallRulesConfigItem.java
- core/src/main/java/com/cloud/agent/resource/virtualnetwork/model/FirewallRule.java
- engine/schema/src/main/java/com/cloud/offerings/dao/NetworkOfferingDao.java
- engine/schema/src/main/java/com/cloud/offerings/dao/NetworkOfferingDaoImpl.java
- server/src/main/java/com/cloud/api/ApiResponseHelper.java
- server/src/main/java/com/cloud/api/query/dao/NetworkOfferingJoinDaoImpl.java
- server/src/main/java/com/cloud/api/query/dao/VpcOfferingJoinDaoImpl.java
- server/src/main/java/com/cloud/network/router/CommandSetupHelper.java
- systemvm/debian/opt/cloud/bin/configure.py
- systemvm/debian/opt/cloud/bin/cs/CsNetfilter.py
- systemvm/debian/opt/cloud/bin/setup/bootstrap.sh
- systemvm/debian/opt/cloud/bin/setup/common.sh
- systemvm/debian/opt/cloud/bin/setup/router.sh
Fixes following with IPv6 networks:
- Event resource for IPv6 firewall rules
- radvd not running in single VR isolated network
- IPv6 Firewall rules not added on the correct chain
- IPv6 VPC tier ACL rules not added on the correct chain
> network: fix event, acl, firewall for ipv6 nw

- server/src/main/java/com/cloud/event/dao/EventJoinDaoImpl.java
- ui/src/views/dashboard/UsageDashboard.vue
For user and project dashborad event resource details were not showing as shown in admin dashboard.
API, UI shows name of the resource as event resourcename. Changed it to displaytext of the resource for consistency.
Before:
After:
> ui,api: fix api resourcename and user/project event resource

- plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/collector/StorPoolAbandonObjectsCollector.java
- plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/datastore/driver/StorPoolPrimaryDataStoreDriver.java
- plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/snapshot/StorPoolSnapshotStrategy.java
There is no need to create log files for the StorPool driver when there
isn't a StorPool primary storage
> Disable creating StorPool logs when there isn't StorPool primary storage

- ui/src/views/AutogenView.vue
This PR fixes the Filter display to fix the options length (tested on different views and Instances options were not properly displayed):
Before:
After:
> UI: Fix filter width to display options

- ui/src/config/section/network.js
- ui/src/utils/plugins.js
Fixes https://github.com/apache/cloudstack/issues/6330
Shows cleanup when restarting a network in group action irrespective of the type of network
Also throws an error notification when a group action fails
> ui: Fix groupaction for nw cleanup and Notify when groupaction fails

- utils/src/main/java/com/cloud/utils/FileUtil.java
This PR improves error log message when scp fails during system VM live patching
Before Fix:
```
2022-04-27 12:02:22,647 ERROR [c.c.s.ManagementServerImpl] (API-Job-Executor-1:ctx-f000200b job-40 ctx-161ff677) (logid:52d49a16) Failed to patch systemVM v-1-VM due to Failed to scp files to system VM, retrying, retrying, retrying
```
After Fix:
```
2022-04-27 13:15:16,189 ERROR [c.c.s.ManagementServerImpl] (API-Job-Executor-1:ctx-4cfd7ab1 job-62 ctx-23bea220) (logid:dffe10d7) Failed to patch systemVM s-2-VM due to Failed to scp files to system VM due to, Remote scp terminated with error (scp: /tmp//agent.zip: No space left on device).
```
> Improve log when live patching fails

- test/integration/smoke/test_network_ipv6.py
Default ACS Xenserver template, CentOS 5.6, has IPv6 disabled.
/etc/modeprobe.conf shows "options ipv6 disable=1"
To run IPv6 network test successfully on Xenserver smoketest run get_test_template will be used instead of get_template while deploying guest VM in the IPv6 guest network.
VM with default Xenserver CentOS 5.6 template
Ran test with changes in a Xenserver env:
```
[root@pr5811-t4060-xenserver-71-marvin ~]# cat /marvin/MarvinLogs/test_network_ipv6_2Z56GX/results.txt
Test to create network offering ... === TestName: test_01_create_ipv6_network_offering | Status : SUCCESS ===
ok
Test to create network offering ... === TestName: test_02_create_ipv6_network_offering_fail | Status : SUCCESS ===
ok
Test to create network offering ... === TestName: test_03_create_ipv6_vpc_offering | …
```
> test: fix ipv6 network test for xenserver

- ui/src/components/view/DetailSettings.vue
- ui/src/components/widgets/TooltipButton.vue
This PR fixes the alignment of the details settings bar:
After:
> UI: Fix detail settings

- engine/schema/pom.xml
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtPatchSystemVmCommandWrapper.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtStartCommandWrapper.java
- plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java
- plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/wrapper/xenbase/CitrixPatchSystemVmCommandWrapper.java
- plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/wrapper/xenbase/CitrixStartCommandWrapper.java
- scripts/vm/hypervisor/xenserver/vmops
- systemvm/debian/opt/cloud/bin/setup/bootstrap.sh
- systemvm/debian/opt/cloud/bin/setup/cloud-early-config
- systemvm/patch-sysvms.sh
- utils/src/main/java/com/cloud/utils/FileUtil.java
This PR updates the location where the new software packages are temporarily copied during live patching.
This will allow livePatching of ACS 4.14, however versions <= 4.13 will not be supported for live patching due to the change in JDK version
> Change patch path during live patching of systemVMs 

- ui/src/views/network/CreateIsolatedNetworkForm.vue
This PR fixes #6334 which is caused by empty startip and endip.
> UI: show startip and endip if network offering support specified ip ranges

- ui/src/views/image/TemplateZones.vue
This PR fixes the redirection to the templates view after a delete template job succeeds only if the user/admin stays on the same page.
> UI: Fix navigation after delete template job is finished

- ui/public/locales/en.json
- ui/src/config/section/infra/routers.js
This PR fixes the invocation of wrong API in case a router of a VPC network is being live patched
> ui: Fix live patch of routers

- ui/src/views/network/CreateIsolatedNetworkForm.vue
- ui/src/views/network/CreateL2NetworkForm.vue
This PR fixes https://github.com/apache/cloudstack/issues/6350, where in when an account Role doesn't have listVPCs in its list  of allowed APIs, it fails to list any network offering when attempting to create a network.
1. Create a role from Domain Admin role and remove listVPCs from the set of allowed APIs
2. Create an account using the above custom role, and login with that user
3. Opened the create network form and was able to list the network offerings.
> ui: Network offerings not listed if listVPCs not available in the account Role

- test/integration/smoke/test_gateway_on_shared_networks.py
- tools/marvin/marvin/lib/base.py
This PR add a test to verify that the right gateways and netmasks are set on updates of IPs from a different range on shared networks. This was fixed in #5105
integration test only
> Gateways after Nic update on Shared Network tests

- engine/schema/src/main/resources/META-INF/db/schema-41610to41700.sql
This PR adds initial support for XCPng 8.2.1 for a minimal working version based on the workaround found on #6349
> Bugfix: no support for XCPng 8.2.1

- server/src/main/java/com/cloud/network/router/CommandSetupHelper.java
This PR fixes an issue we found in the smoke test `test/integration/smoke/test_network_ipv6.py`.
sometimes the test failed with error below
```
FAIL: Test to verify IPv6 network
File "/usr/local/lib/python3.6/site-packages/marvin/lib/decoratorGenerators.py", line 30, in test_wrapper
return test(self, *args, **kwargs)
File "/marvin/test_network_ipv6.py", line 1215, in test_01_verify_ipv6_network
self.checkNetworkRouting()
File "/marvin/test_network_ipv6.py", line 1060, in checkNetworkRouting
"Ping from VM %s of network %s to VM %s of network %s is unsuccessful" % (self.routing_test_vm.id, self.routing_test_network.id, self.virtual_machine.id, self.network.id))
AssertionError: False is …
```
> ipv6: set default_egress_policy for ingress rules

- scripts/util/create-kubernetes-binaries-iso.sh
This PR fixes the error below when create K8S ISO using scripts/util/create-kubernetes-binaries-iso.sh
```
+ echo 'Downloading image weaveworks/weave-kube:latest ---'
Downloading image weaveworks/weave-kube:latest ---
+ [[ weaveworks/weave-kube:latest == kubernetesui* ]]
+ [[ weaveworks/weave-kube:latest == apache* ]]
+ sudo ctr image pull weaveworks/weave-kube:latest
INFO[0000] trying next host                              error="failed to do request: Head https://weaveworks/v2/weave-kube/manifests/latest: dial tcp: lookup weaveworks: no such host" host=weaveworks
ctr: failed to resolve reference "weaveworks/weave-kube:latest": failed to do request: Head https://weaveworks/v2/weave-kube/manifests/latest: dial tcp: lookup weaveworks: no such host
```
> CKS: fix error with pulling weaveworks images when create k8s ISO

- ui/src/views/AutogenView.vue
This PR fixes an issue seen when trying to add / update tags on hosts or storage pools using the update Host / update storage pool forms respectively.
> ui: Allow editing host and storage tags in updateHost & updatStoragePool forms

- agent/src/main/java/com/cloud/agent/AgentShell.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
This PR fixes the issue that template cannot be downloaded from https site in 4.17.0.0 RC2.
> agent: enable ssl only for kvm agent (not in system vms)

- ui/src/views/image/RegisterOrUploadTemplate.vue
This PR fixes an error on the hypervisor menu when registering a template and the zone validation triggers
> UI: Fix hypervisor list after zone validation when registering a template

- ui/public/locales/en.json
- ui/src/views/offering/AddComputeOffering.vue
This PR adds the missing tooltips helpers to fields in the service offering creation: 'Compute only disk offering' and 'Disk offering stricteness'
> UI: Add missing tooltips on service offering creation

- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
This PR fixes the Vmware import unmanaged instances process, was failing due to a null detail value for SSHPublicKey:
Verified fix by importing VM successfully
> Fix: Cannot import Vmware instances

- api/src/main/java/org/apache/cloudstack/api/command/user/vmsnapshot/CreateVMSnapshotCmd.java
- server/src/main/java/com/cloud/vm/snapshot/VMSnapshotManagerImpl.java
This PR throws a more descriptive error on KVM in case the snapshot type is not supported (tested on KVM + snapshot memory = false):
Before:
After:
> Reword KVM VM snapshot without memory error message

- api/src/main/java/com/cloud/server/ManagementService.java
- api/src/main/java/org/apache/cloudstack/api/command/user/volume/ChangeOfferingForVolumeCmd.java
- server/src/main/java/com/cloud/server/ManagementServerImpl.java
- server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
- server/src/main/java/org/apache/cloudstack/vm/UnmanagedVMsManagerImpl.java
This PR fixes #6372 
1. Deploy a VM
2. Create a DATA disk, say DATA01, with Shared Pool disk offering (or Shared Pool disk offering)
3. Create a Local Pool disk offering, say LocalDisk (or Use any default Shared Pool disk offering)
4. Change Disk Offering of the DATA disk (DATA01), to Local Pool disk offering LocalDisk (or Local Data disk to Shared Pool disk offering)
> Fix changeOfferingForVolume API to consider storage type in the disk offering

- test/integration/smoke/test_vm_life_cycle.py
- test/integration/smoke/test_vm_lifecycle_unmanage_import.py
- tools/marvin/marvin/lib/base.py
- tools/marvin/marvin/lib/vcenter.py
Refactored smoke test for unmanaging a  VM and then importing it.
Moved the test class to anew file to prevent Trillian re-running them in case of failures of other tests in `test_vm_life_cycle.py`.
Tested with a VMware env having changes from #6384 
```
[root@pr6385-t4175-vmware-67u3-marvin marvin]# nosetests --with-xunit --xunit-file=results.xml --with-marvin --marvin-config=./pr6385-t4175-vmware-67u3-advanced-cfg -s -a tags=advanced --hypervisor=VMware tests/smoke/test_vm_life_cycle_unmanage_import.py 
/usr/local/lib/python3.6/site-packages/paramiko/transport.py:33: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
from cryptography.hazmat.backends …
```
> test: add test for importUnmanagedInstance

- plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java
Fixes https://github.com/apache/cloudstack/issues/6344
Passes the caller's API keys if the cluster is part of a project
autoscaler logs :
```
I0516 08:57:51.486442       1 static_autoscaler.go:235] Starting main loop
I0516 08:57:51.487030       1 client.go:169] NewAPIRequest API request URL:http://10.0.32.136:8080/client/api?apiKey=***&command=listKubernetesClusters&id=a5e617a3-6d95-410c-9d3a-306274ee8b11&response=json&signature=***
I0516 08:57:51.515655       1 client.go:175] NewAPIRequest response status code:200
I0516 08:57:51.518415       1 cloudstack_manager.go:88] Got cluster : &{a5e617a3-6d95-410c-9d3a-306274ee8b11 cluster 1 2 1 1 [0xc000716f90 0xc000716fc0] map[cluster-control-180cc02282f:0xc000716f90 cluster-node-180cc025111:0xc000716fc0]}
```
> cks: Get caller user keys if cluster belongs to project

- utils/src/main/java/com/cloud/utils/component/ComponentContext.java
Currently when ACS fails to load the beans for some component, such as cloud-usage, an exception will be thrown but it is not logged, making the system restart indefinitely. Without any logs, it can be hard to figure out what is happening; to fix that, a try-catch block and a new log were added in the bootstrap of the agent.
This was tested in a local lab, by injecting a class into `UsageManagerImpl` without mapping its bean and checking if the log would appear and if the component would stop.
> Log load bean exception

- engine/schema/src/main/java/com/cloud/vm/UserVmVO.java
- server/src/main/java/com/cloud/api/query/dao/UserVmJoinDaoImpl.java
- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
This PR prevents an NPE on VM reboot when the VM is not in Running state.
Also addresses the output of the startVirtualMachine API with null displayname:
````
(isc-uat) 🐱 > start virtualmachine id=5e549d97-f6c6-4109-9416-ed6eb7c8b912
{
"accountid": "53c6e98d-bc37-11ec-ba86-02000252074f",
"cmd": "org.apache.cloudstack.api.command.admin.vm.StartVMCmdByAdmin",
"completed": "2022-05-17T21:50:25+0000",
"created": "2022-05-17T21:50:24+0000",
"jobid": "0ea90ce5-2af2-4268-baed-e189134aad78",
"jobinstanceid": "5e549d97-f6c6-4109-9416-ed6eb7c8b912",
"jobinstancetype": "VirtualMachine",
"jobresult": {
"errorcode": 431,
"errortext": "The virtual machine 5e549d97-f6c6-4109-9416-ed6eb7c8b912 (null) is already running"
},
"jobresultcode": 530,
"jobresulttype": "object",
"jobstatus": …
```
> Prevent NPE on reboot stopped VM and startVM output with null displayname

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java
This PR backports #6244 to 4.16
(This PR truncates the vnc password of kvm vms to 8 chars to support latest versions of libvirt.)
> Backport: kvm: truncate vnc password to 8 chars (#6244)

- ui/src/views/infra/zone/ZoneWizardLaunchZone.vue
This PR fixes the error caused by missing Secret property when setting up RBD Primary Storage in Zone Wizard.
(Related by #5167)
> [UI] Zone Wizard - fix secret property when setting RBD primary storage

- ui/src/config/section/network.js
- ui/src/views/network/VpcTab.vue
This PR fixes ui issues in the form to create vpc private gateway by regular user
This also contains other ui bug fixes below
UI: display 'egree/ipv6/publicip' tabs only for domain/root admin and the owner
please note
(1) isolated networks only .
(2) networks in project are not impacted. the tabs are always visible.
(3) 'network permission' tab is also only visible for domain/root admin and the owner. but not visible in project view.
> UI: fix create vpc private gateway for regular user

- agent/conf/agent.properties
- agent/src/main/java/com/cloud/agent/properties/AgentProperties.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
This PR enables IO_URING only when it is available on the hosts, as being discussed on https://github.com/apache/cloudstack/pull/6253#issuecomment-1131216926
> [KVM] Enable IOURING only when it is available on the host

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtMigrateCommandWrapper.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtMigrateCommandWrapperTest.java
This PR fixes a VM migration issue described on https://github.com/apache/cloudstack/pull/6402#issuecomment-1133602561
- Initial state: CS 4.16.1 / 2 KVM hosts running OpenSUSE 15.3 - libvirt 7.1.0 and QEMU 5.2.0
- Create 3 VMs
- Put host 2 on maintenance
- Upgrade host packages from: https://software.opensuse.org/download/package?package=libvirt&project=Virtualization to libvirt 8.3.0 and QEMU 6.2.0
- Cancel maintenance on host 2
- Attempt migrating any VM to host 2 -> FAILURE:
````
2022-05-22 03:56:07,297 DEBUG [c.c.c.CapacityManagerImpl] (Work-Job-Executor-8:ctx-77987975 job-41/job-42 ctx-91220c68) (logid:c4ad92ef) VM instance {id: "5", name: "i-2-5-VM", uuid: 
"6a2339af-5236-49aa-b9a0-65a2c9ce3952", type="User"} state transited from [Migrating] to [Running] with event …
```
> [KVM] Fix VM migration error due to VNC password on libvirt limiting versions

- api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
- plugins/user-authenticators/saml2/src/main/java/org/apache/cloudstack/api/command/ListIdpsCmd.java
- server/src/main/java/com/cloud/api/ApiServlet.java
- server/src/main/java/com/cloud/api/ApiSessionListener.java
- server/src/main/java/com/cloud/api/auth/DefaultLoginAPIAuthenticatorCmd.java
- server/src/main/java/com/cloud/api/auth/DefaultLogoutAPIAuthenticatorCmd.java
This PR removes the request handlin from the ApiSessionListener. This causes sessions to be invalidated. API calling from cmk would fail and succeed on and off due to this.
manually tested by listing accounts with cloudmonkey.
> remove request listener to prevent untimely session invalidation

- server/src/main/java/com/cloud/server/StatsCollector.java
This PR fix logic check error for update GPU groupDetails.
It should update GPU groupDetails when there are non-empty infos.
> Fix logic check error for update GPU groupDetails

- ui/src/views/compute/UpgradeKubernetesCluster.vue
This PR fixes the issue observed when trying to upgrade cks cluster via UI: Doesn't show the drop down menu of available versions
> UI: Fix Upgrade kubernetes form

- ui/src/views/compute/CreateKubernetesCluster.vue
Fixes the issue of ha kubernetes clusters not coming up with the specified control plane nodes
> ui: Fix create kubernetes cluster with ha enabled

- ui/src/views/compute/wizard/NetworkSelection.vue
This PR prints the vpc name to which the isolated network is associated 
before fix:
After fix:
Also tested in project view
> ui: Display associated VPC network name against vpc tiers - deploy VM form

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtReadyCommandWrapper.java
- server/src/main/java/com/cloud/deploy/DeploymentPlanningManagerImpl.java
This PR fixes 2 issues:
- Prevent UEFI deployments on non UEFI enabled hosts (do not assume the host detail will always be present in case of not enabled)
- Fix the UEFI detection on KVM (uefi.properties file check was missing)
Tested on KVM - one UEFI enabled host, one disabled
> Fix UEFI detection on KVM and prevent deployments on non UEFI enabled hosts

- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
This PR fixes deploy from ISO with a custom disk offering, the size parameter is not honoured
Fixes: #6440 
Deploy VM from ISO - select custom disk offering
Deploy VM from template - select custom data disk offering
> Fix deploy from ISO with custom disk offering

- ui/src/views/network/VpcTab.vue
This PR fixes an regression issue of #6400 
Ths issue is, the associated network is always required, even when a network is selected from the drop down, which cause regular users arenot able to create private gateway with associated network.
> UI: fix create vpc private gw by regular users

- test/integration/broken/test_vpc_vm_life_cycle.py
- test/integration/component/test_host_ha.py
- test/integration/component/test_rootvolume_resize.py
This PR is a continuation of work in #5082. aiming to have a full set of component tests running on all hypervisors. see #6391 for an inventory of all work to be done.
included:
> some  component tests fixes

- api/src/main/java/org/apache/cloudstack/api/response/NicResponse.java
- server/src/main/java/com/cloud/api/ApiResponseHelper.java
- server/src/main/java/com/cloud/api/query/dao/UserVmJoinDaoImpl.java
This PR adds vpc info to the nics response as part of list VMs response and list nics response
Addresses: https://github.com/apache/cloudstack/issues/6452
listed VMs and nics for a VM belonging to a VPC network:
```
(localcloud) 🐱 > list virtualmachines id=9c762cf8-7742-48df-bc57-43bf126d3471 filter=nic,
{
"count": 1,
{
"nic": [
{
"broadcasturi": "vlan://167",
"deviceid": "0",
"extradhcpoption": [],
"gateway": "10.10.10.1",
"id": "a703d827-4b5a-46e4-b9ea-8cd2aaafbc26",
"ipaddress": "10.10.10.66",
"isdefault": true,
"isolationuri": "vlan://167",
"macaddress": "02:00:28:aa:00:01",
"netmask": "255.255.255.0",
"networkid": "02ad6bac-1cd6-461a-a951-8934bffd4eb9",
"networkname": "n1",
"secondaryip": [],
"traffictype": "Guest",
"type": "Isolated",
"vpcid": …
```
> api: Add vpc name and uuid to VMs list response (nics) and nics response

- ui/src/config/section/infra/routers.js
This PR fixes https://github.com/apache/cloudstack/issues/6466
> UI: Fixes ui error when upgrade virtual routers from virtual router list

- ui/src/views/infra/zone/StaticInputsForm.vue
- ui/src/views/infra/zone/ZoneWizardAddResources.vue
- ui/src/views/infra/zone/ZoneWizardLaunchZone.vue
This PR fixes https://github.com/apache/cloudstack/issues/6088
> UI: add a provider for primary storage when adding zone wizard

- pom.xml
Reference: https://gitlab.com/libvirt/libvirt-java/-/issues/6
> kvm: upgrade libvirt-java to v0.5.3

- ui/src/views/infra/AddPrimaryStorage.vue
- ui/src/views/infra/zone/ZoneWizardLaunchZone.vue
If Linstor protocol is selected it makes no sense to show other
providers as Linstor only works with the Linstor provider.
And also the install wizard doesn't use the correct provider for linstor.
This changes were already merged for 4.16.1.0 see: https://github.com/apache/cloudstack/pull/5672
But I don't know why they weren't merged to `main` back than, maybe I don't know how cloudstack's
merge/PR's work.
But this should be definitely merged to 4.17.* and main
Clicked through local served vui ui -> add primary storage
> UI primarystorage linstor fixes

- ui/src/views/compute/CreateKubernetesCluster.vue
- ui/src/views/image/AddKubernetesSupportedVersion.vue
- ui/src/views/image/RegisterOrUploadIso.vue
- ui/src/views/offering/AddComputeOffering.vue
- ui/src/views/offering/AddDiskOffering.vue
Fixes UI hang issue when offering is created when there is no zone.
Console errors when creating offering
> ui: fix ui hang on offering creation with no zone

- engine/schema/src/main/resources/META-INF/db/schema-41700to41710.sql
This PR updates the config values for `network.disable.rpfilter` and `consoleproxy.disable.rpfilter` to meet the boolean type set on #6380.
Fixes: #6390 
Upgrade from 4.16.1 successfully:
Before upgrade: Changed only one value, leave the other as default
````
MariaDB [cloud]> select name, value from configuration where name like '%rpfilter';
+-------------------------------+-------+
| name                          | value |
+-------------------------------+-------+
| consoleproxy.disable.rpfilter | 2     |
| network.disable.rpfilter      | true  |
+-------------------------------+-------+
2 rows in set (0.00 sec)
MariaDB [cloud]> select * from version order by id desc limit 1;
+----+----------+---------------------+----------+
| id | version  | updated             | step     | …
```
> Fix rpfilter config values from integer to boolean on upgrade path

- core/src/main/java/com/cloud/agent/api/ModifyStoragePoolAnswer.java
- core/src/main/java/com/cloud/agent/api/ModifyStoragePoolCommand.java
- engine/components-api/src/main/java/com/cloud/storage/StorageManager.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtModifyStoragePoolCommandWrapper.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/IscsiAdmStorageAdaptor.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/IscsiAdmStoragePool.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStoragePool.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStoragePoolManager.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/LibvirtStorageAdaptor.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/LibvirtStoragePool.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/LinstorStorageAdaptor.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/LinstorStoragePool.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/ManagedNfsStorageAdaptor.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/ScaleIOStorageAdaptor.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/ScaleIOStoragePool.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/StorageAdaptor.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/storage/ScaleIOStoragePoolTest.java
- plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/client/ScaleIOGatewayClient.java
- plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/client/ScaleIOGatewayClientImpl.java
- plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/driver/ScaleIOPrimaryDataStoreDriver.java
- plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/lifecycle/ScaleIOPrimaryDataStoreLifeCycle.java
- plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/provider/ScaleIOHostListener.java
- plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/util/ScaleIOUtil.java
- plugins/storage/volume/scaleio/src/test/java/org/apache/cloudstack/storage/datastore/lifecycle/ScaleIOPrimaryDataStoreLifeCycleTest.java
- plugins/storage/volume/storpool/src/main/java/com/cloud/hypervisor/kvm/storage/StorPoolStorageAdaptor.java
- plugins/storage/volume/storpool/src/main/java/com/cloud/hypervisor/kvm/storage/StorPoolStoragePool.java
- server/src/main/java/com/cloud/storage/StorageManagerImpl.java
- server/src/test/java/com/cloud/storage/listener/StoragePoolMonitorTest.java
This PR enhances the existing PowerFlex/ScaleIO storage plugin to support separate (storage) network for Hosts(KVM)/Storage connection, mainly the SDC (ScaleIo Data Client) connection.
Manually tested VM/Volume operations on PowerFlex/ScaleIO storage.
> Updated PowerFlex/ScaleIO storage plugin to support separate (storage) network for Hosts(KVM)/Storage connection.

- ui/src/views/AutogenView.vue
While trying to update a disk offering through the UI, the tag fields are always sent, even when they are not changed. This causes a bug when active volumes are using a disk offering in storage pools with tags. As ACS would interpret this as an update on the tags as well. This PR aims to fix this problem, only sending the tags if they are different from the current tags, allowing the user to update the name and/or description of disk offerings, as it is already allowed through CloudMonkey.
On a local lab, I tried updating the disk offering with the following use cases:
- updating only the name
- updating only the description
- updating only the name and description fields
All of the tests worked as expected, the UI only sent the the fields that were changed.
Then, while trying to update …
> Add check for update only name and/or description of disk offering

- ui/public/locales/en.json
- ui/src/views/storage/ResizeVolume.vue
This PR fixes https://github.com/apache/cloudstack/issues/6501
> UI: Change notification title when resizing volume

- ui/src/views/network/CreateVpnCustomerGateway.vue
- ui/src/views/network/VpcTab.vue
As 4.17.0.0,when catched error, we changed message.success.add.vpn.customer.gateway to
message.add.vpn.customer.gateway.failed.
fix UI VPC add ACL without required input close ui
Without any input, click ok button then close the ui . We need display ui to confirm all required input.
changed the base branch of the PR to 4.17 and rebase your PR branch to the 4.17 branch
link  #6489
> UI fix message.add.vpn.customer.gateway.failed when catched error

- api/src/main/java/org/apache/cloudstack/api/response/DiskOfferingResponse.java
- server/src/main/java/com/cloud/api/query/dao/DiskOfferingJoinDaoImpl.java
- server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
Similar to service offering details, allow details to be provided and
displayed. Can be used for classification of offerings, etc.
Signed-off-by: Marcus Sorensen <mls@apple.com>
This PR relaxes the disk offering details to match the way the service offering details work. With Service offering details, any arbitrary values provided can be saved and displayed, which can be used as metadata to tag, classify, or organize offerings by higher level consumers.  With disk offerings, any detail that isn't recognized is ignored, so this PR relaxes that and persists arbitrary details as well.
Note that with both disk offerings and service offerings, there are a few 'special' detail keys that are marked `display=false` when they are persisted, and this functionality remains intact.
Tested locally, …
> Allow for arbitrary disk offering details to be saved/displayed

- api/src/main/java/com/cloud/user/ResourceLimitService.java
- core/src/main/java/org/apache/cloudstack/storage/command/TemplateOrVolumePostUploadCommand.java
- server/src/main/java/com/cloud/configuration/Config.java
- server/src/main/java/com/cloud/resourcelimit/ResourceLimitManagerImpl.java
- server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
- server/src/main/java/com/cloud/template/HypervisorTemplateAdapter.java
- services/secondary-storage/server/src/main/java/org/apache/cloudstack/storage/resource/NfsSecondaryStorageResource.java
This PR fixes issue #6411 
There are two global settings max.account.secondary.storage and max.project.secondary.storage to specify maximum secondary storage space (in GiB) that can be used for an account and project respectively.
But during upload template from project is not considering max.project.secondary.storage but uses max.account.secondary.storage.
We have fixed this here to use max.project.secondary.storage in case of project.
1. Uploaded a template from both account and project and observed using appropriate global settings.
> Fix global setting reference for max secondary storage

- plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java
- plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/version/KubernetesSupportedVersion.java
- plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/version/KubernetesSupportedVersionVO.java
- plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/version/KubernetesVersionManagerImpl.java
- plugins/integrations/kubernetes-service/src/main/java/org/apache/cloudstack/api/response/KubernetesClusterResponse.java
- plugins/integrations/kubernetes-service/src/main/java/org/apache/cloudstack/api/response/KubernetesSupportedVersionResponse.java
- ui/src/config/section/compute.js
- ui/src/config/section/image.js
This PR adds `created` info to the response of kubernetes clusters and kubernetes supported version.
> CKS: add created to k8s cluster and k8s version

- api/src/main/java/org/apache/cloudstack/api/command/user/volume/AttachVolumeCmd.java
This is in the workflow of attaching and detaching a root volume of a VM. We can detach the root volume from a VM and Cloudstack marks it as datadisk. We can reattach the volume to make it root volume again. During attach Device ID 0 has to be passed so that the volume will be converted back to ROOT again
Added a small information in the DeviceID section in Attach volume form.
> Added information about device id 0 for root volume while attaching to VM

- plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/guru/VMwareGuru.java
- plugins/hypervisors/vmware/src/test/java/com/cloud/hypervisor/guru/VMwareGuruTest.java
This PR fixes issue #6270 where VMmigration along with volumes API fails in case of local storage in VMware.
1. Create a VM with root disk and data disk, make sure disks are created in local storage
2. Stop the VM
3. From UI/API migrate the VM along with disks to a different local storage.
4. Migration is successful after this fix.
> Fix for VMware VM migration with volume in local storage

- engine/schema/src/main/java/com/cloud/network/dao/NetworkDaoImpl.java
- engine/schema/src/test/java/com/cloud/network/dao/NetworkDaoImplTest.java
While deleting a traffic type, ACS validates if there is any VM related to it. However, if we have several physical networks containing a traffic type, ACS does not filter the physical network to do the validation. For instance, if we have two (2) physical networks containing the traffic type Guest, the first one having VMs related, and the second not having VMs related, if we try to remove the second traffic type, ACS give us the message `The Traffic Type is not deletable because there are existing networks with this traffic type:Guest`.
The API `deleteTrafficType` was designed to filter the physical network where the traffic type is, however, due to a typo this filtering was not been applied correctly. This PR intends to fix this typo to honor the API behavior.
In an advanced zone I …
> Fix API deleteTrafficType not filtering physical network

- .github/workflows/linter.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: neilnaveen <42328488+neilnaveen@users.noreply.github.com>
> chore: Set permissions for GitHub actions

- plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java
Currently memory usage statistics in VMware are inverted. It was discovered that during statistics collection, memory usage was collected and passed as free memory, so the memory usage graphs were inverted. The free memory calculation has been fixed and the memory statistics are now consistent with what is observed in VMware.
This was tested in a local lab, by creating a VM with VMware as its hypervisor and checking memory statistics in both vCenter and ACS.
> Fix VMware memory retrieval

- scripts/util/keystore-setup
This PR fixes the issue https://github.com/apache/cloudstack/issues/6471 where in keystore setup does not exclude link-local addresses.
We have fixed the keystore setup process to exclude the  fe80 or link local addresses
> Excluded fe80 or link local address in keystore setup

- plugins/user-authenticators/saml2/pom.xml
- plugins/user-authenticators/saml2/src/main/java/org/apache/cloudstack/saml/SAMLUtils.java
- plugins/user-authenticators/saml2/src/test/java/org/apache/cloudstack/SAMLUtilsTest.java
- pom.xml
This PR fixes the issue #6427 -> SAML request must be appended to an IdP URL as a query param with an ampersand, if the URL already contains a question mark, as opposed to always assume that IdP URLs don't have any query params.
Google's IdP URL for instance looks like this: `https://accounts.google.com/o/saml2/idp?idpid=<ID>`, therefore the expected redirect URL would be `https://accounts.google.com/o/saml2/idp?idpid=<ID>&SAMLRequest=<SAMLRequest>`
This code change is backwards compatible with the current behaviour.
> Fix SAML SSO plugin redirect URL

- ui/src/views/infra/zone/StaticInputsForm.vue
- ui/src/views/infra/zone/ZoneWizardAddResources.vue
- ui/src/views/infra/zone/ZoneWizardLaunchZone.vue
This PR for fixes https://github.com/apache/cloudstack/issues/6499
> UI: Add authmethod field allowing to choose password or ssh key when adding host

- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java
This fixes the build issue on M1 mac/osx.
> kvm: skip test that can't run and pass on M1 mac

- server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
Fixes #6533
This adds the option returned in API which in turn shows the option and possible values in the UI.
> kvm: add support nicAdapter detail for vm and template settings for KVM

- ui/src/locales/index.js
- ui/src/views/infra/ClusterAdd.vue
- ui/src/views/infra/zone/ZoneWizardAddResources.vue
- ui/src/views/infra/zone/ZoneWizardPhysicalNetworkSetupStep.vue
This PR for fixes some issues from zone wizard with VMWare hypervisor (https://github.com/apache/cloudstack/issues/6479)
1. Hide the warning HTML in the message when using vue-i18n
2. Hide IP address step with VMWare hypervisor
3. Fill the value of input on the edit tariff label form
4. Close edit tariff label modal when clicking icon-close
5. Auto change cluster name if submit error with VMWare hypervisor
> UI: Fixes some issues from zone wizard with VMWare hypervisor

- engine/schema/src/main/java/com/cloud/vm/dao/UserVmDaoImpl.java
When we remove the NIC of a network from a VM and add a new NIC of the same network, we will have two registers in the database for the same VM and network, one of them being marked as `removed`. In API `listLoadBalancerRuleInstances`, specifically in the method `LoadBalancingRulesManagerImpl#listLoadBalancerInstances`, ACS retrieves the instances according to the user's account and the network where the LB is being created; however, it lists all the NICs, even the marked as `removed`, which causes the following error while listing the VMs:
```
2022-05-16 14:06:32,859 ERROR [c.c.a.ApiServer] (qtp365590665-27:ctx-5ce79f30 ctx-9de90969) (logid:a3518976) unhandled exception executing api command: [Ljava.lang.String;@55d45499
java.lang.IndexOutOfBoundsException: Index 2 out of bounds for …
```
> Filter removed nics while listing LB vm instances

- api/src/main/java/org/apache/cloudstack/acl/APIChecker.java
- engine/schema/src/main/java/com/cloud/projects/ProjectVO.java
- engine/schema/src/main/java/com/cloud/user/AccountVO.java
- engine/schema/src/main/java/com/cloud/user/UserVO.java
- engine/schema/src/main/java/org/apache/cloudstack/acl/RoleVO.java
- plugins/acl/dynamic-role-based/src/main/java/org/apache/cloudstack/acl/DynamicRoleBasedAPIAccessChecker.java
- plugins/acl/dynamic-role-based/src/test/java/org/apache/cloudstack/acl/DynamicRoleBasedAPIAccessCheckerTest.java
- plugins/acl/project-role-based/src/main/java/org/apache/cloudstack/acl/ProjectRoleBasedApiAccessChecker.java
- plugins/acl/project-role-based/src/main/test/java/org/apache/cloudstack/acl/ProjectRoleBasedApiAccessCheckerTest.java
- plugins/acl/static-role-based/src/main/java/org/apache/cloudstack/acl/StaticRoleBasedAPIAccessChecker.java
- plugins/api/discovery/src/main/java/org/apache/cloudstack/discovery/ApiDiscoveryServiceImpl.java
- plugins/api/discovery/src/test/java/org/apache/cloudstack/discovery/ApiDiscoveryTest.java
- plugins/api/rate-limit/src/main/java/org/apache/cloudstack/ratelimit/ApiRateLimitServiceImpl.java
The API `listApis` currently has too many redundant calls to the DB, which causes slowness on the ACS login. This PR aims to improve the time of login on ACS by refactoring the classes that implement the `APIChecker` interface. In my local lab, the login usually took 13 seconds, without login cache. With this new version, the login took around 2 seconds, with no login cache as well.
Fixes: #5266
I created multiple accounts with the roles based on the following table. I compared this PR with a version with the unmodified `APIChecker`. And the number of APIs were returned as expected, as the table shows.
| Role Type | 4.16.0.6 version | PR version |
| ------ | ------ | ------ | 
| Root Admin | 624 | 624 |
| Domain Admin | 180 | 180 |
| Read-Only Admin | 312 | 312 |
| Support Admin | 202| …
> Improve login time

- engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/snapshot/SnapshotServiceImpl.java
- engine/storage/snapshot/src/test/java/org/apache/cloudstack/storage/snapshot/SnapshotServiceImplTest.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtRevertSnapshotCommandWrapper.java
- plugins/storage/volume/datera/src/main/java/org/apache/cloudstack/storage/datastore/driver/DateraPrimaryDataStoreDriver.java
- plugins/storage/volume/default/src/main/java/org/apache/cloudstack/storage/datastore/driver/CloudStackPrimaryDataStoreDriverImpl.java
This PR fixes the issue https://github.com/apache/cloudstack/issues/6209 where the snapshot revert operation fails after certain volume operations like Migrate VM with volume / migrate volume / reinstall VM.
The root cause of the issue after these volume operations, the primary storage entry is getting deleted for that volume. We have fixed it here to get the primary datastore entry wrt volume and continue the operation.
1. Create a VM and stop the VM on a KVM environment
2. Create snapshot of the volume
3. migrate VM with volume or volume to a different storage.
4. Create another snapshot of the same volume
5. Performed revert operations on these two snapshots and they are successful
> [KVM] Fix for Revert volume snapshot

- api/src/main/java/org/apache/cloudstack/api/command/admin/systemvm/ScaleSystemVMCmd.java
- api/src/main/java/org/apache/cloudstack/api/command/admin/systemvm/UpgradeSystemVMCmd.java
- api/src/main/java/org/apache/cloudstack/api/command/user/vm/ScaleVMCmd.java
- api/src/main/java/org/apache/cloudstack/api/command/user/vm/UpgradeVMCmd.java
This PR...
Updates API documentation regarding resizing commands. It informs the user of the actually needed parameters.
```
(localcloud) 🐱 > change serviceforvirtualmachine id=5568b625-0012-429c-82b4-da3e177e166e serviceofferingid=b4b7e9ca-45cd-4c8e-b9d8-0c7ff0f79fc2 details[0].cpu=2 details[1].cpuspeed=2000 details[2].ram=1024
🙈 Error: (HTTP 431, error code 4350) Invalid cpu cores value, specify a value between 1 and 2147483647
```
```
change serviceforvirtualmachine id=5568b625-0012-429c-82b4-da3e177e166e serviceofferingid=b4b7e9ca-45cd-4c8e-b9d8-0c7ff0f79fc2 details[0].cpunumber=2 details[0].cpuspeed=2000 details[0].memory=1024
```
> Update API documentation for resizing

- api/src/main/java/com/cloud/agent/api/storage/OVFHelper.java
- api/src/main/java/com/cloud/agent/api/storage/OVFParser.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtDomainXMLParser.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtStoragePoolXMLParser.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtStorageVolumeXMLParser.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtXMLParser.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtMigrateCommandWrapper.java
- plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/CitrixResourceBase.java
- plugins/network-elements/cisco-vnmc/src/main/java/com/cloud/network/cisco/CiscoVnmcConnectionImpl.java
- plugins/network-elements/juniper-srx/src/main/java/com/cloud/network/resource/JuniperSrxResource.java
- plugins/network-elements/palo-alto/src/main/java/com/cloud/network/resource/PaloAltoResource.java
- plugins/user-authenticators/saml2/src/main/java/org/apache/cloudstack/api/command/GetServiceProviderMetaDataCmd.java
- server/src/main/java/com/cloud/test/DatabaseConfig.java
- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
- utils/src/main/java/com/cloud/utils/UriUtils.java
- utils/src/main/java/com/cloud/utils/cisco/n1kv/vsm/VsmResponse.java
- utils/src/main/java/com/cloud/utils/xmlobject/XmlObjectParser.java
- utils/src/main/java/org/apache/cloudstack/utils/security/ParserUtils.java
- utils/src/test/java/org/apache/cloudstack/utils/security/ParserUtilsTest.java
- vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/HypervisorHostHelper.java
This addresses SonarQube/SonarCloud quality checks to use safer xml parser.
https://sonarcloud.io/organizations/apache/rules?open=java%3AS2755&rule_key=java%3AS2755
> utils: use safer parsing utility across codebase

- server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
Removes psudo job results from the response of the listAsyncJobs API
```
(localhost) 🐱 > list asyncjobs listall=true filter=jobid,jobinstancetype,
{
"asyncjobs": [
{
"jobid": "27ed55c7-419d-4c69-acfc-496e6f85266a"      <- Psudo job
},
{
"jobid": "3d616d8f-f8ca-413d-a622-25f579137f14"      <- Psudo job
},
{
"jobid": "202fed87-fde7-476e-a829-8d3b39167019"      <- Psudo job
},
{
"jobid": "202fed87-5f85-4767-a622-ee39be729451"      <- Psudo job
}
{
"jobid": "ae46b9e7-d315-4795-bc24-a1fb4bd4ec73",
"jobinstancetype": "VirtualMachine"
}
],
"count": 5
}
```
```
(localhost) 🐱 > list asyncjobs listall=true filter=jobid,jobinstancetype,
{
"asyncjobs": [
{
"jobid": "eba01225-7029-4730-96e1-b9d38c916657",
"jobinstancetype": "VirtualMachine"
}
],
"count": 1
}
```
> Remove psudo jobs from listAsyncJobs API

- ui/src/views/infra/network/ServiceProvidersTab.vue
This PR fixes an issue on the input fields for new network service providers, could not enter data on them.
Go to Zone -> Physical network -> Network providers -> Pick a provider and try to add a new provider
> UI: Fix new network service provider dialog

- .travis.yml
- server/src/main/java/com/cloud/network/NetworkServiceImpl.java
- test/integration/component/test_network_permissions.py
- test/integration/smoke/test_network_permissions.py
This PR fixes #6544 where it could not list networks in a project even after network permissions are set.
1. Created multiple networks N1, N2
2. Created a project P1
3. Created a user U1
4. Under network permissions in N1, added the project P1
5. Under network permissions in N2, added the user account U1
6. When switched to project view P1, I see only network N1
7. When logged in as U1, I see only N2
> Fixed list networks in projects after setting network permissions

- api/src/main/java/org/apache/cloudstack/api/command/user/ipv6/CreateIpv6FirewallRuleCmd.java
- api/src/main/java/org/apache/cloudstack/api/command/user/ipv6/DeleteIpv6FirewallRuleCmd.java
- api/src/main/java/org/apache/cloudstack/api/command/user/ipv6/ListIpv6FirewallRulesCmd.java
- api/src/main/java/org/apache/cloudstack/api/command/user/ipv6/UpdateIpv6FirewallRuleCmd.java
- test/integration/component/test_network_ipv6.py
- test/integration/smoke/test_network_ipv6.py
- ui/src/config/section/network.js
Fixes default roles permissions for IPv6 firewall related APIs
Refactors related marvin tests to call deploy, update, restart network and VM APIs as user instead of the admin
Fixes #6575
> api: fix ipv6 firewall apis default role permissions

- api/src/main/java/com/cloud/storage/VolumeApiService.java
- server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
- server/src/main/java/com/cloud/template/TemplateManagerImpl.java
- services/secondary-storage/controller/src/main/java/org/apache/cloudstack/secondarystorage/SecondaryStorageManagerImpl.java
- systemvm/debian/etc/apache2/vhost.template
- systemvm/debian/opt/cloud/bin/setup/common.sh
- systemvm/debian/opt/cloud/bin/setup/secstorage.sh
- utils/src/main/java/org/apache/cloudstack/utils/imagestore/ImageStoreUtil.java
- utils/src/test/java/org/apache/cloudstack/utils/imagestore/ImageStoreUtilTest.java
CloudStack has the functionality to upload volumes, templates, and local ISOs. To execute the process, ACS generates a link to the secondary storage (using its public IPs), where the resource must be sent. The *links* are always generated with the HTTPS protocol and the environment has to be configured to handle HTTPS, requiring us to have SSL certificates. However, for environments that do not need to use certificates (such as staging ones), via the UI, we need a workaround (get the URL generated by the API for generating upload links, open it in a new tab, and accept an insecure connection with the application).  
The ACS was changed so that it also handles HTTP to upload volumes/images/ISOs according to the global configuration `use.https.to.upload`; then operators can choose whether …
> externalizes used protocol to upload isos, volumes and templates

- server/src/main/java/org/apache/cloudstack/backup/BackupManagerImpl.java
- server/src/test/java/org/apache/cloudstack/backup/BackupManagerTest.java
Using the VMWare hypervisor, with the Veeam plugin active, ACS tries to find, in Veeam, VBRViDatastore using the UUID of this storage in ACS, and VBRServer using the IP of the host in ACS. But, in some scenarios, the VBRViDatastore/VBRServer, in Veeam, can use the name of this component, which causes an exception in ACS. This PR aims to fix this behavior, improving the search of VBRViDatastore and VBRServer by using the name.
It was tested in a local lab:
1. I added new storage and host in my lab, and make sure the component, in Veeam, are identified by their names;
2. I created a VM (the volume is in the new storage, and VM is in the new host) and added this VM to a backup offering;
3. I make some manual backups;
4. I tried to restore a backed-up volume of this VM;
5. Before, an …
> [Veeam] Find VBRViDatastore and VBRServer by name

- tools/apidoc/gen_toc.py
Through analysis, it was found that the Cloudstack API documentation (https://cloudstack.apache.org/api/apidocs-4.17) does not present the document for the quotaSummary API. This error has been present since the creation of this API.
The present patch corrects this behavior, exposing the documentation for this API to the user.
To generate the documentation and verify the correction, you can run `mvn clean install` inside the `tools/apidoc` project and check the content of the page present in `tools/apidoc/target/xmldoc/html/index.html`. Or run the `build-apidoc.sh` script:
```
`./build-apidoc.sh 4.17.0.0 ../../client/target//cloud-client-ui-4.17.0.0.jar ../../client/target//cloud-client-ui-4.17.00.jar ./myout
```
and check the page content available in myout/xmldoc/html/index.html
> Shows quotaSummary in API documentation

- ui/src/views/storage/RestoreAttachBackupVolume.vue
When restoring and attaching a backup volume, the UI waits for the successfful response of the API to close the formulary. However, letting the form open after sending the command can confuse users, that might try to send the command again.
Note: other formularies (like volume or snapshot creation) always are closed after sending the command to the backend.
With this PR, we intend to close the formulary right after sending the command, as done with others.
It was tested in a local lab.
Before the changes, I tried to restore and attach a backup volume. After clicking the button `Ok`, the command was sent, but the formulary was kept open. After the changes, when clicking the button `Ok`, the command is sent and the formulary is closed.
> Close restore and attach form right after receiving the job id

- ui/src/views/image/IsoZones.vue
This PR fixes the navigation for ISOs after deletion. The following issues are addressed:
- After removal of an ISO without bulk operation -> The view keeps displaying the data of the removed ISO
- After removal of an ISO selecting bulk operation -> The view redirects to the 404 exception view
The following scenarios were tested on a single zone:
- Delete ISO without selecting any zone -> After removal, the ISO view is displayed
- Delete ISO selecting the zone and clicking on 'Bulk operation' -> After removal, the ISO view is displayed
> UI: Fix delete ISO navigation after job is finished

- server/src/main/java/com/cloud/user/AccountManagerImpl.java
- server/src/main/java/com/cloud/user/PasswordPolicy.java
- server/src/main/java/com/cloud/user/PasswordPolicyImpl.java
- server/src/main/resources/META-INF/cloudstack/core/spring-server-core-managers-context.xml
- server/src/test/java/com/cloud/user/AccountManagerImplTest.java
- server/src/test/java/com/cloud/user/PasswordPolicyImplTest.java
Currently, ACS does not have a feature to manage user password policies. New domain-scoped settings were created to allow operators to define password policies. Configured password policies will be applied whenever a user changes their password or a new user is created. The following settings were created:
| Setting | Purpose |
| ------ | ------ |
|`password.policy.minimum.length`| Minimum password length |
|`password.policy.minimum.lowercase.letters`| Minimum number of lower case letters|
|`password.policy.minimum.uppercase.letters`| Minimum number of upper case letters|
|`password.policy.minimum.special.characters`| Minimum number of special characters|
|`password.policy.minimum.digits`| Minimum number of digits|
|`password.policy.allowPasswordToContainUsername`| If the password may …
> Password policies

- ui/src/views/infra/zone/ZoneWizardLaunchZone.vue
Fixes: #6593
Before fix UI was setting vlan to 'null' when no value was passed. Now it just leaves the vlan value empty in the trafficlabel.
> ui: fix hypervisortrafficlabel for phy nw traffic

- engine/schema/src/main/resources/META-INF/db/schema-41700to41710.sql
- server/src/main/java/com/cloud/api/ApiDBUtils.java
- server/src/main/java/com/cloud/api/ApiResponseHelper.java
- server/src/main/java/com/cloud/api/query/dao/DomainRouterJoinDaoImpl.java
- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
- ui/src/config/section/infra/routers.js
- ui/src/config/section/infra/systemVms.js
Release 4.16.0.0 introduced a feature for migrating system VM volumes (#4385). However, it was enabled only for VMWare.
This PR intends to enable the feature for KVM too.
- [ x] Minor
It was tested in a local lab.
(I tested the process for each system VM type)
To test the SSVM and CPVM, I enabled a zone to create them. When they were created, I disabled the zone. I accessed the system VMs and created files to validate later. I stopped them and migrated the volumes. I checked the references in database and storage and then I started the system VMs. After that, I accessed them again and verified the files. The migration performed successfully, the data was kept and the system VMs were working fine.
To test the VR, I created a network. I accessed the VR and created a file to validate later. …
> Enable system VM volume migration for KVM

- test/integration/component/test_network_permissions.py
- test/integration/smoke/test_attach_multiple_volumes.py
- test/integration/smoke/test_network_permissions.py
- test/integration/smoke/test_volumes.py
Few of the smoke tests fail on XCP-ng8 with PV drivers not installed for the VM.
This PR makes changes to use get_suitable_test_template instead of get_template to use the appropriate template for the VM deployed during the test.
After volume migration VM becomes unusable for attach/detach volume action.
A new template could be used in future. For workaround right now, tests are ordered in a way that migrate volume test run at the end.
> test,xcp-ng: fix tests for VM PV driver issue

- server/src/main/java/com/cloud/network/NetworkModelImpl.java
- server/src/main/java/org/apache/cloudstack/network/lb/ApplicationLoadBalancerManagerImpl.java
- server/src/test/java/com/cloud/network/NetworkModelTest.java
While checking network access for creating load-balancer use `AccessType.OperateEntry`
Refactor variable name in `NetworkModelImpl::checkNetworkPermissions`
Fixes: #6590
> vpc,network: fix createLoadBalancer access on user network

- api/src/main/java/com/cloud/storage/Storage.java
- engine/schema/src/main/java/com/cloud/upgrade/dao/Upgrade41700to41710.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
- plugins/storage/volume/storpool/src/main/java/com/cloud/hypervisor/kvm/storage/StorPoolStorageAdaptor.java
- plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/datastore/driver/StorPoolPrimaryDataStoreDriver.java
- plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/datastore/lifecycle/StorPoolPrimaryDataStoreLifeCycle.java
This PR fixes #6455 
The default storage adaptor - `LibvirtStorageAdaptor` - is used by different storage types and doesn't use the annotation `@StorageAdaptorInfo`. In this case, a storage plugin that wants to adopt one of the predefined storage pool types will override the default behaviour. If fixing the issue in general (for new storage plugins or current ones that want to reuse the existing storage pool types) would affect all volume/snapshot/VM cases. This will lead to the need of extensive testing for each storage plugin for which we don't have the resources to do it. That's why this patch fixes the old behaviour for the SharedMountPoint by adding a new storage pool type for the StorPool plugin.
- [] Breaking change (fix or feature that would cause existing functionality to change) …
> removed the use of SharedMountPoint storage type for the StorPool plugin

- plugins/backup/veeam/src/main/java/org/apache/cloudstack/backup/VeeamBackupProvider.java
This PR fixes the issue https://github.com/apache/cloudstack/issues/6465 where listing backup restore points are failing with Veeam version v11.0.1.1261. 
Though this version is not fully supported for backup and recovery, existing backups, restore points for the VMs can continue to work with the Veeam version v11.0.1.1261. I've created a separate ticket here to fully support the version https://github.com/apache/cloudstack/issues/6554
1. Setup Veeam v11.0.1.1261 with CloudStack
2. Added a back offering to the volume
3. Created a backup to the VM
4. Wait for the back sync to trigger in CloudStack
5. Restore points listed and saved in the database in the table "backups"
> Fixed Veeam listing restore points

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
This PR ensures that when `getMemStat()` is called in KVM environments, the hosts actual used memory is returned, and not a static value that was retrieved when the cloudstack-agent was started.
We have applied this patch into our own environment, built the packages and installed them on the managers and hosts. We then migrated VMs between hosts and saw the host memory usage being updated, instead of remaining static until the cloudstack-agent was restarted.
> Fixes #6621 - Update host memory stats

- api/src/main/java/com/cloud/configuration/Resource.java
- engine/storage/volume/src/main/java/org/apache/cloudstack/storage/volume/VolumeObject.java
- server/src/main/java/com/cloud/api/query/dao/AccountJoinDaoImpl.java
- server/src/main/java/com/cloud/api/query/dao/DomainJoinDaoImpl.java
- server/src/main/java/com/cloud/resourcelimit/ResourceLimitManagerImpl.java
- server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
This PR updates primary_storage resource counter to include correct size after volume creation/resize and other improvements.
- Recalculate resource counters for root domain in the periodic task
- Update correct size in the primary_storage resource counter after volume creation/resize
- Some code improvements
Manually tested VM/Volume operations using ScaleIO/PowerFlex pool and checked the primary_storage resource counters for different domains.
Before fix (_primarystorageavailable_ counter is not shown appropriately for unlimited):
```
(testenv) 🐱 > list domains filter=name,primarystoragetotal,primarystoragelimit,primarystorageavailable
{
"count": 3,
"domain": [
{
"name": "ROOT",
"primarystorageavailable": "Unlimited",
"primarystoragelimit": "Unlimited",
"primarystoragetotal": -5
},
{ …
```
> Updated resource counter to include correct size after volume creation/resize and other improvements

- plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java
- plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageProcessor.java
- vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/HypervisorHostHelper.java
Fixes #4314
Failure in attaching k8s ISO is seen when VMware DRS is enabled. Log reported VM is not found. This fix tries to find VM on peer hosts when the VM is not found on the given host.
> vmware,cks: fix attachiso failure with vmware drs

- engine/schema/src/main/java/com/cloud/dc/dao/VlanDao.java
- engine/schema/src/main/java/com/cloud/dc/dao/VlanDaoImpl.java
- server/src/main/java/com/cloud/network/Ipv6ServiceImpl.java
- server/src/test/java/com/cloud/network/Ipv6ServiceImplTest.java
Fixes #6584
Tested locally on a simulator env with separate physical network for guest traffic
```
(local) 🦂 > list physicalnetworks 
{
"count": 2,
"physicalnetwork": [
{
"broadcastdomainrange": "ZONE",
"id": "4e3a8e0d-9d4e-4de5-bda0-17fb83b1b173",
"isolationmethods": "VLAN",
"name": "Physical Network 1",
"state": "Enabled",
"vlan": "220-240",
"zoneid": "78e1da67-04e5-4683-9d52-346ef6cd7472",
"zonename": "z1"
},
{
"broadcastdomainrange": "ZONE",
"id": "78e3c74b-7def-40c2-b1d4-49e8d61fcc1b",
"isolationmethods": "VLAN",
"name": "Physical Network 2",
"state": "Enabled",
"vlan": "1220-1240",
"zoneid": "78e1da67-04e5-4683-9d52-346ef6cd7472",
"zonename": "z1"
}
]
}
(local) 🍀 > list traffictypes 
💩 Missing required parameters:  physicalnetworkid
(local) 🐺 > list traffictypes …
```
> server: fix ipv6 network deployment with separate guest nw

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDefTest.java
This PR provides constructors and the associated changes to use LibvirtVMDef for creating user mode network interfaces.
While this isn't used directly in the CloudStack KVM agent today, it could be used in the future for e.g. pod networking/management networks without needing to assign a pod IP. The VIF driver used by the CloudStack Agent is also pluggable, so this allows plugin code to create user mode network interfaces as well.
Note that the user mode network already exists in the GuestNetType enum, but wasn't usable prior to this change.
Also included unit test to ensure we continue to create the expected XML.
Additionally, this uncovered a null pointer on `_networkRateKBps` and this PR fixes it. The decision to add bandwidth throttling assumes this field is not null and simply checks …
> Add usermode interface option to Libvirt Domain XML builder

- engine/schema/src/main/java/com/cloud/upgrade/dao/Upgrade41610to41700.java
> Fix SQL query for uuid wrong format

- server/src/main/java/com/cloud/network/NetworkServiceImpl.java
Fixes #6620
Remove resource tags when public IP is disassociated
> server: remove resource tags for disassociated public ip

- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
This PR allows VM details wrt root & data disk controller passed via details parameter of deployVMCmd to take precedence over template settings, i.e., the order of precedence for determining VM disk controller is : VM details passed during deployment > template settings > global setting `vmware.root.disk.controller` .
> api, vmware: Allow VM setting/detail for disk controller (root/data) to override template details

- server/src/main/java/com/cloud/network/NetworkServiceImpl.java
Fixes #6663
```
(localcloud) 🐱 > list vpcs id=d02c8c5b-6b29-4ea9-a54f-80ede983dc30 filter=id,name,state,
{
"count": 1,
"vpc": [
{
"id": "d02c8c5b-6b29-4ea9-a54f-80ede983dc30",
"name": "testvpc",
"state": "Enabled"
}
]
}
(localcloud) 🐱 > list publicipaddresses vpcid=d02c8c5b-6b29-4ea9-a54f-80ede983dc30
{
"count": 1,
{
"allocated": "2022-08-23T12:13:37+0000",
"domainid": "096a1c2e-123b-11ed-994f-1e002e00010c",
"fordisplay": true,
"forvirtualnetwork": true,
"id": "e9f0591d-a089-4ce5-a1c6-89923405eee8",
"ipaddress": "10.0.57.25",
"isportable": false,
"issourcenat": true,
"isstaticnat": false,
"networkid": "3a41afc5-e204-4a1e-b679-e730600eca9b",
"physicalnetworkid": …
```
> vpc: prevent sourcenat ip disassociation for an active vpc

- server/src/main/java/com/cloud/network/NetworkServiceImpl.java
- server/src/test/java/com/cloud/network/DedicateGuestVlanRangesTest.java
Fixes #6648 
If any of the VLAN from the given range is not found in the database (`cloud.op_dc_vnet_alloc`) then an InvalidParameterValueException will be thrown.
Also, refactors and fixes account check.
> server: fix error when dedicatingguestvlanrange for physical nw without vlan range

- ui/src/views/compute/DeployVM.vue
This PR is used to fix the error that an unknown API call appeared when initializing the deploy VM page.
> UI: Remove incorrect API calls when initializing the deploy VM page

- engine/schema/src/main/java/com/cloud/host/HostVO.java
- engine/schema/src/main/java/com/cloud/service/ServiceOfferingVO.java
- engine/schema/src/main/java/com/cloud/vm/VMInstanceVO.java
- server/src/main/java/com/cloud/resource/ResourceManagerImpl.java
- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
Currently, ACS does not validate host tags on running VMs that have their computing resources increased via Scale VM command. Therefore, if a service offering with host tags deploys on a host with the same host tags, it is permitted to live scale this VM to another service offering with another host tags. This PR aims to fix this bug, verifying the host tags on a VM live scaling.
This was tested in a local lab with the following scenario:
1. VM deployed with a service offering with host tags `hdd`.
2. Tried to live scale the VM with another service offering with host tags `ssd`.
3. An error occurred while scaling the VM, as expected.
> Validate host tags on VM live scale

- core/src/main/java/org/apache/cloudstack/storage/to/PrimaryDataStoreTO.java
- engine/api/src/main/java/org/apache/cloudstack/engine/subsystem/api/storage/PrimaryDataStore.java
- engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/vmsnapshot/DefaultVMSnapshotStrategy.java
- engine/storage/snapshot/src/test/java/org/apache/cloudstack/storage/vmsnapshot/DefaultVMSnapshotStrategyTest.java
- engine/storage/snapshot/src/test/java/org/apache/cloudstack/storage/vmsnapshot/VMSnapshotStrategyTest.java
- engine/storage/volume/src/main/java/org/apache/cloudstack/storage/datastore/PrimaryDataStoreImpl.java
- plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/manager/VmwareHostService.java
- plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/manager/VmwareStorageManagerImpl.java
- plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java
- plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareSecondaryStorageResourceHandler.java
- plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageProcessor.java
> vmware: fix vm snapshot with datastore cluster, drs

- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
Fixes #6679
Fixes behaviour when the VM is scaled to a new compute offering which has the same disk offering associated as the earlier compute offering.
**Service offering and VM**
```
(localcloud) 🐱 > list serviceofferings id=1892001d-1d4c-4467-937d-a35415bc1093 
{
"count": 1,
{
"created": "2022-08-31T10:35:00+0000",
"diskofferingdisplaytext": "Medium Disk, 20 GB",
"diskofferingid": "0bae8790-1c97-43f6-b0d4-777023377ec8",
"diskofferingname": "Medium",
"displaytext": "co1",
"id": "1892001d-1d4c-4467-937d-a35415bc1093",
"iscustomized": false,
"memory": 512,
"name": …
```
> server: fix scale vm with compute offering having same disk offering

- pom.xml
Commit f27de6364402569fd3c2d1286ed5c749b9bd6e12 introduced a new version of opensaml. That version brought `jcl-over-slf4j-1.7.5.jar`, `jul-to-slf4j-1.7.5.jar`, and `log4j-over-slf4j-1.7.5.jar` as dependencies, which causes Agents and Usages to not generate _logs_: 
In order to make the logs to work again, this PR intends to exclude these dependencies while building the packages.
After applying the commit f27de6364402569fd3c2d1286ed5c749b9bd6e12, the logs on the Agents and Usages stopped being written. After applying this PR, the logs started to be written again.
> Ignore opensaml's slf4j dependencies

- ui/src/views/infra/network/IpRangesTabPublic.vue
Fixes 'Set reservation' toggle not getting updated on value change.
> ui: fix set reservation toggle in add public ip range

- server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
Fixes incorrect check for verifying IPv6 ranges overlap. This causes the inability to add multiple IPv6 ranges.
Without change error is seen while creating shared networks when zone has an IPv6 public range added,
```
> list vlanipranges 
{
"count": 2,
"vlaniprange": [
{
"account": "system",
"cidr": "10.1.48.0/20",
"domainid": "6d9bb269-29c9-11ed-9e50-1e00a4000983",
"endip": "10.1.54.220",
"forsystemvms": false,
"forvirtualnetwork": true,
"gateway": "10.1.48.1",
"id": "8c99a3eb-eb31-4de1-a7cf-aaba3754a5bf",
"netmask": "255.255.240.0",
"networkid": "8c89748a-ab07-4393-a669-87fd74072a87",
"physicalnetworkid": "aced8f04-89af-460b-80b7-df08b249ae86",
"startip": "10.1.54.201",
"vlan": "vlan://51",
"zoneid": "89386d1e-9e03-40f0-bb91-7190ea2a9b58"
},
{
"account": "system", …
```
> server: fix check for ipv6 range overlap

- plugins/hypervisors/kvm/src/main/java/org/apache/cloudstack/utils/linux/KVMHostInfo.java
- plugins/hypervisors/kvm/src/test/java/org/apache/cloudstack/utils/linux/KVMHostInfoTest.java
Fixes #6680
While finding CPU speed for KVM host following methods will be used in the same order:
1. lscpu
2. value in /sys/devices/system/cpu/cpu0/cpufreq/base_frequency
3. libvirt host capabilities
4. libvirt nodeinfo
This will allow the correct value for AMD-based hosts when the first two methods don't give a value
Tested with an AMD-based KVM host,
```
2022-09-05 18:02:17,633 INFO  [utils.linux.KVMHostInfo] (Agent-Handler-1:null) (logid:) Fetching CPU speed from command "lscpu".
2022-09-05 18:02:17,633 DEBUG [utils.script.Script] (Agent-Handler-1:null) (logid:) Executing: /bin/bash -c lscpu | grep -i 'Model name' | head -n 1 | egrep -o '[[:digit:]].[[:digit:]]+GHz' | sed 's/GHz//g' 
2022-09-05 18:02:17,636 DEBUG [utils.script.Script] (Agent-Handler-1:null) (logid:) Executing while …
```
> kvm: add libvirt host capabilities method for cpu speed retrieval

- ui/src/config/section/project.js
This PR fixes an UI issue that `cleanup` parameter is not passed when bulk-delete projects.
> UI: fix bulk delete project with cleanup

- systemvm/debian/opt/cloud/bin/setup/dhcpsrvr.sh
Fixes #6700
When VR is a DHCP server system VM type then stop radvd.
Tested IPv6 shared network VR.
_List an IPv6 shared network and its VR which is already rebooted:_
```
(localcloud) 🐱 > list networks id=4dcaae55-80b7-4a41-8d52-c6971d34959c 
{
"count": 1,
"network": [
{
"acltype": "Domain",
"broadcastdomaintype": "Vlan",
"broadcasturi": "vlan://1245",
"canusefordeploy": true,
"cidr": "10.9.9.0/24",
"created": "2022-09-06T10:20:13+0000",
"details": {},
"displaynetwork": true,
"displaytext": "sh",
"dns1": "10.1.32.1",
"dns2": "8.8.8.8",
"domainid": "a2f1cc09-2dc0-11ed-b0f7-1e00d6000ca0",
"gateway": "10.9.9.1",
"id": "4dcaae55-80b7-4a41-8d52-c6971d34959c",
"ip6cidr": "fd17:ac56:1234:2000::/64",
"ip6gateway": "fd17:ac56:1234:2000::1", …
```
> systemvm,vr: disable radvd for non-applicable VRs

- plugins/api/discovery/pom.xml
- plugins/api/rate-limit/pom.xml
- plugins/api/solidfire-intg-test/pom.xml
- plugins/api/vmware-sioc/pom.xml
- plugins/metrics/pom.xml
- plugins/network-elements/juniper-contrail/pom.xml
- server/pom.xml
According to https://www.eclemma.org/jacoco/trunk/doc/prepare-agent-mojo.html
we need to add "@{argLine}" to argLine if it exists in pom.xml
This PR fixes missing jacoco coverage report in some modules
> Jacoco: fix no coverage result in server and some other modules

- engine/schema/src/main/resources/META-INF/db/schema-41610to41700.sql
This PR tries to fix a problem with a privately backported feature. The columns added for the feature are not added idem potent so people can not backport them. I propose that all DB alteration from here on in will be done with the `IDEM_POTENT_...()` set of stored procedures that we have to prevent these kind of issues for users.
So far this has only been done with one feature but I propose to regirously do this for all code.
> upgrade a backported patch

- server/src/main/java/com/cloud/network/Ipv6ServiceImpl.java
- server/src/test/java/com/cloud/network/Ipv6ServiceImplTest.java
Fixes network update for IPv6 offering upgrade
Before fix:
```
Test to verify IPv6 network ... === TestName: test_01_verify_ipv6_network | Status : SUCCESS ===
ok
Test to verify redundant IPv6 network ... === TestName: test_02_verify_ipv6_network_redundant | Status : SUCCESS ===
ok
Test to verify IPv4 network upgraded to IPv6 network ... === TestName: test_03_verify_upgraded_ipv6_network | Status : EXCEPTION ===
ERROR
Test to verify redundant IPv4 network upgraded to redundant IPv6 network ... === TestName: test_04_verify_upgraded_ipv6_network_redundant | Status : EXCEPTION ===
ERROR
2022-09-12 09:02:13,776 - CRITICAL - EXCEPTION: test_03_verify_upgraded_ipv6_network: ['Traceback (most recent call last):\n', '  File "/usr/lib64/python3.6/unittest/case.py", line 60, in testPartExecutor\n …
```
> server: fix network upgrade for IPv6

- framework/db/src/main/java/com/cloud/utils/db/ConnectionConcierge.java
This PR...
When the management service detects a broken database connection, it didn't do anything about it.  It already has code to reset the connection, but that doesn't get used.  This change causes the connection to be reset after it's found to be unusable.
See https://github.com/apache/cloudstack/issues/6724 for repro steps
Fixes: 6724
The instructions in INSTALL.md are incomplete or outdated.  I was able to get the project to build, but I haven't been able to test my change.  See https://github.com/apache/cloudstack/issues/6726.
> Reset unusable db connections

- ui/Dockerfile
Node versions >14 throw errors when building and thus do not allow to build the UI.
Pinning to v14 allows us to build and run the UI Docker container.
Fixes:  #6709
> UI: Build Dockerfile with Node v14

- plugins/database/quota/src/main/java/org/apache/cloudstack/api/command/QuotaCreditsCmd.java
This PR aims to fix the current behavior of the `min_balance` parameter of the `quotaCredits` API. This parameter is considered optional in the API documentation; however, when using the API, it is not possible to add credits without specifying the minimum balance for the account. Therefore, this behavior was fixed. If the minimum balance is not specified it is considered as 0.
This was tested in a local lab using the API `quotaCredits` without specifying the `min_balance` field. The API was executed with no errors.
> Fix min balance for API quotaCredits to be optional

- engine/schema/src/main/java/com/cloud/upgrade/DatabaseUpgradeChecker.java
This needs checking if it's even needed at all cc @shwstppr @DaanHoogland 
This PR...
> DatabaseUpgradeChecker: add upgrade path from 4.17.0.1 to 4.17.1.0

- engine/components-api/src/main/java/com/cloud/storage/StorageManager.java
Currently the description of the configuration `max.data.migration.wait.time` does not specify which time unity is used (minutes). The goal of this PR is to add this information to the description.
I built the code with the changes and applied it in a local lab. After starting cloudstack-management.service, the configuration description changed to the new one.
> fix description of configuration `max.data.migration.wait.time`

- api/src/main/java/org/apache/cloudstack/api/command/user/vm/ListVMsCmd.java
- api/src/main/java/org/apache/cloudstack/api/response/UserVmResponse.java
- server/src/main/java/com/cloud/api/ApiDBUtils.java
- server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
- server/src/main/java/com/cloud/api/query/ViewResponseHelper.java
- server/src/main/java/com/cloud/api/query/dao/UserVmJoinDao.java
- server/src/main/java/com/cloud/api/query/dao/UserVmJoinDaoImpl.java
- ui/src/utils/util.js
- ui/src/views/compute/DeployVM.vue
- ui/src/views/compute/EditVM.vue
This PR extends PR #6051 by making the `listVirtualMachines` API return the VMs' userdata, so that when the editVM form is opened in the UI, the existing userdata will be shown. 
A new optional boolean parameter called `userdata` was added to the `listVirtualMachines` API, that controls whether the API should return userdata or not. The default value is false.
The `sanitizeReverse` function was also moved to util.js to prevent duplicated code.
This was tested in a local lab by creating a new VM and editing it's userdata through the UI. After the form was closed it was reopened to check if the userdata that was added before would be shown.
> Return vm userdata

- pom.xml
Bumps version of specific dependency to latest ahead of the next major release 4.18.
> mvn: bump version ahead of next major release

- api/src/main/java/com/cloud/template/VirtualMachineTemplate.java
- server/src/main/java/com/cloud/template/TemplateManagerImpl.java
This PR...
Fixes: #6766
registere a template with the name `thisIsAVerySmallTemplateWithAnExtremelyLongNameThatIsExcesiveInGivingInformationThatIsEitherUsefulOrUtterlyUselessAboutTheTemplateWhichIsReallyNotBigEnoughToSpendTheNameMiniOn` and deployed it.
When deployed stop it
From the Root Volume create a template with the name
`thisIsAVerySmallTemplateWithAnExtremelyLongNameThatIsExcesiveInGivingInformationThatIsEitherUsefulOrUtterlyUselessAboutTheTemplateWhichIsReallyNotBigEnoughToSpendTheNameMiniOnEither`
The last step would fail in without this fix.
> Allow template names upto 255 chars

- engine/schema/src/main/java/com/cloud/capacity/dao/CapacityDao.java
- engine/schema/src/main/java/com/cloud/capacity/dao/CapacityDaoImpl.java
- engine/schema/src/main/java/com/cloud/user/dao/AccountDao.java
- engine/schema/src/main/java/com/cloud/user/dao/AccountDaoImpl.java
- engine/schema/src/main/java/com/cloud/vm/dao/UserVmDao.java
- engine/schema/src/main/java/com/cloud/vm/dao/UserVmDaoImpl.java
- engine/schema/src/main/java/com/cloud/vm/dao/VMInstanceDao.java
- engine/schema/src/main/java/com/cloud/vm/dao/VMInstanceDaoImpl.java
- plugins/integrations/prometheus/src/main/java/org/apache/cloudstack/metrics/PrometheusExporterImpl.java
- plugins/integrations/prometheus/src/main/java/org/apache/cloudstack/metrics/PrometheusExporterServer.java
- plugins/integrations/prometheus/src/main/java/org/apache/cloudstack/metrics/PrometheusExporterServerImpl.java
- systemvm/debian/root/version
In this pull request, I added new functionality to Cloudstack prometheus exporter. To see the differences please check the testing section.
This pull request contains seven commits. Except for the dfb35e5224 commit, they are all added new functionality to the Prometheus. In the subsequent sections, I will describe every commit functionality. I tested them in my test environment with three management servers, one DB node (MySQL), and two KVM hypervisor.
1. Enable Prometheus.
2. Add tag to the host.
3. Run `curl http://127.0.0.1:9595/metrics | grep cloudstack_hosts_total`
Output Before Changes:
```
cloudstack_hosts_total{zone="mgt122-60",filter="online"} 2
cloudstack_hosts_total{zone="mgt122-60",filter="offline"} 0
cloudstack_hosts_total{zone="mgt122-60",filter="total"} 2
```
Output After …
> Prometheus exporter enhancement

- plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/driver/ScaleIOPrimaryDataStoreDriver.java
Signed-off-by: Marcus Sorensen <mls@apple.com>
This PR Fixes #6739 (for PowerFlex/ScaleIO only, Datera still needs to be addressed), which can occur if the last host the VM ran on is deleted from CloudStack. At the point the VM is deleted, cloudstack attempts to make a final call to revoke access to volumes, passing the last host the VM ran on. If this host is gone, we get an error and are unable to delete the VM.
It's possible that there may be a more holistic fix to this by identifying all of the places where `revokeAccess()` is called and checking for null host. It's possible other storage plugins don't even need host information to revoke access to volumes and may need this call to revoke. Therefore I'm only applying this fix to the ScaleIOPrimaryDataStoreDriver to skip revoking …
> Ignore calls to PowerFlex for host revocation when host is null

- server/src/main/java/com/cloud/template/TemplateManagerImpl.java
Currently, ACS does not allow the user to download System VM Templates,  even though it may be usefull as it can speed up the registration process of the template for production once the homologation is done beforehand. This PR changes this, allowing the user to download said VM Templates
I built the code with the respective changes in a local lab. After that, I copied the Uuid from one of the System VM templates. Then, using CloudMonkey, I utilized the command 'extract template' with the copied Uuid. CloudMonkey then generated a link for the download of the template, confirming that the alteration was successful.
> Allow download of system vm templates

- plugins/hypervisors/kvm/src/main/java/org/apache/cloudstack/utils/qemu/QemuImageOptions.java
- plugins/hypervisors/kvm/src/test/java/org/apache/cloudstack/utils/qemu/QemuImageOptionsTest.java
This PR fixes the issue that volume snapshot fails on RBD storage with the following error
qemu-img: Could not open 'driver=raw,file.filename=rbd:cloudstack/test_wei.img:mon_host=10.0.32.254:auth_supported=cephx:id=cloudstack:key=AQDwHTNjjHXRKRAAJb+AToFr6x4a1AvKUc4Ksg==:rbd_default_format=2:client_mount_timeout=30': Could not open 'rbd:cloudstack/test_wei.img:mon_host=10.0.32.254:auth_supported=cephx:id=cloudstack:key=AQDwHTNjjHXRKRAAJb+AToFr6x4a1AvKUc4Ksg==:rbd_default_format=2:client_mount_timeout=30': No such file or directory
However, it works without using image options
Therefore, do not pass the image options if the image format is not QCOW2 and LUKS.
> kvm: fix backup volume snapshot fails on RBD storage

- server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
If you had an disk-offer which would compute-only == false,
it wouldn't apply the iop settings of the new disk-offer and instead
use null for the settings.
Manually switching between the default 5GB disk offer and a self created IOP limiting disk offer.
> change-diskoffer: iops settings from new disk-offer should always used

- api/src/main/java/org/apache/cloudstack/api/response/HypervisorCapabilitiesResponse.java
The `hypervisorCapabilitiesResponse` does not set an object name, returning a null object name instead. This PR adds an object name to the response. 
This was tested in a local lab, by calling the API via CloudMonkey and checking the object name value.
Before:
```
{
"null": {
"hypervisor": "VMware",
"hypervisorversion": "5.0",
"id": "11",
"maxdatavolumeslimit": 12,
"maxguestslimit": 127,
"maxhostspercluster": 31,
"securitygroupenabled": true,
"storagemotionenabled": true,
"vmsnapshotenabled": false
}
}
```
After:
```
{
"hypervisorcapabilities": {
"hypervisor": "VMware",
"hypervisorversion": "5.0",
"id": "11",
"maxdatavolumeslimit": 12,
"maxguestslimit": 127,
"maxhostspercluster": 31,
"securitygroupenabled": true,
"storagemotionenabled": true,
"vmsnapshotenabled": false
}
}
```
> Return object name in the listHypervisorCapabilities API

- ui/public/locales/en.json
- ui/public/locales/pt_BR.json
- ui/src/views/offering/AddNetworkOffering.vue
This PR aims to improve the user experience upon creation of Network Offerings warning the user of the scenarios in which a VR is created. For this, the service offering field is always shown in the form and a warning message is displayed if the user's configuration does not require the creation of a VR. These scenarios include a network offering with guest type L2, and a with a guest type Shared or Isolated when none of the following services are enabled: (VPN, DHCP, DNS, Firewall, LB, UserData, SourceNat, StaticNat and/or PortForwarding). Finally, the message for the Isolated and Shared networks disappear when one of the aforementioned services are selected.
Message if the guest type is **Isolated or Shared**:
Message if the guest type is **L2**:
This was tested in a local lab using the …
> Add message upon network offering creation to warn user of VR creation

- engine/storage/integration-test/src/test/java/org/apache/cloudstack/storage/test/TestHttp.java
FIX #6673
This PR removes the catch block with the `e.printStackTrace()`, which suppressed the Exceptions to be thrown in the CI\CD's final report.
These catch blocks will only print the the Exception information and will not raise any failure in the testing process. This behavior will lead the developer harder to notice the issue in the CI\CD reports.
I suggest removing the try-catch structure and adding some additional assertion(if possible). This will improve the readability of the test cases, and avoid missing the test failure. Even if the exception does not raise by the component that we are testing here, we can still know that we need to fix the outside conditions first to make sure the test case running under stable and consistent conditions.
Local cluster environment (KVM, UBUNTU …
> Refactor TestHttp.testHttpclient to avoid the Exception Suppression

- api/src/main/java/com/cloud/storage/VolumeApiService.java
- server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
- server/src/test/java/com/cloud/storage/VolumeApiServiceImplTest.java
When a volume is removed, ACS inserts a `VOLUME.DELETE` record into the `cloud.usage_event` table. If the volume is removed without the expunge option, it can still be restored. 
When the volume is restored, ACS does not insert a new record in the `cloud.usage_event` stating that it has been recreated. Thus, the volume continues to be used without being accounted for.
This PR adds an event in the volume restore process that indicates the volume was recreated. So it will be accounted for.
This PR was tested in a local lab, by destroying and recreating volumes and checking the DB to see if the event was added.
Some unit tests were also added.
> Fix to make recovered volumes be accounted for by Usage

- api/src/main/java/org/apache/cloudstack/api/ApiArgValidator.java
- engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
- plugins/event-bus/inmemory/src/test/java/org/apache/cloudstack/mom/inmemory/InMemoryEventBusTest.java
- plugins/network-elements/juniper-contrail/src/main/java/org/apache/cloudstack/network/contrail/model/VirtualMachineModel.java
- plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/util/ScaleIOUtil.java
- server/src/main/java/com/cloud/api/dispatch/ParamProcessWorker.java
- server/src/test/java/com/cloud/user/DomainManagerImplTest.java
- utils/src/main/java/com/cloud/utils/UuidUtils.java
- utils/src/test/java/com/cloud/utils/UuidUtilsTest.java
This PR renames the method `validateUUID` to `isUuid` and everywhere it's called.
The current name of the method (`validateUUID`) gives the impression that if the validation fails, an exception will be thrown, when in fact it just returns a boolean value, and that's why I think that `isUuid` is more appropriate.
As the PR only renames the method, I tested it (the PR) building it locally:
> Rename validateUUID method to isUuid

- ui/src/views/compute/CreateSnapshotWizard.vue
Fixes: #6795 
Take volume snapshots for user VMs from the instance view as admin, the volume is correctly displayed and snapshot operation succeeded
> UI: Fix Volume Snapshot from user VM as admin

- engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/snapshot/DefaultSnapshotStrategy.java
- engine/storage/snapshot/src/test/java/org/apache/cloudstack/storage/snapshot/DefaultSnapshotStrategyTest.java
ACS + Xenserver works with differential snapshots. ACS takes a volume full snapshot and the next ones are referenced as a child of the previous snapshot until the chain reaches the limit defined in the global setting `snapshot.delta.max`; then, a new full snapshot is taken. PR #5297 introduced disk-only snapshots for KVM volumes. Among the changes, the delete process was also refactored. Before the changes, when one was removing a snapshot with children, ACS was marking it as `Destroyed` and it was keeping the `Image` entry on the table `cloud.snapshot_store_ref` as `Ready`. When ACS was rotating the snapshots (the max delta was reached) and all the children were already marked as removed; then, ACS would start removing the whole hierarchy, completing the differential snapshot cycle. …
> Fix delete parent snapshot

- api/src/main/java/org/apache/cloudstack/api/command/user/backup/DeleteBackupCmd.java
- api/src/main/java/org/apache/cloudstack/backup/BackupManager.java
- api/src/main/java/org/apache/cloudstack/backup/BackupProvider.java
- plugins/backup/dummy/src/main/java/org/apache/cloudstack/backup/DummyBackupProvider.java
- plugins/backup/veeam/src/main/java/org/apache/cloudstack/backup/VeeamBackupProvider.java
- plugins/backup/veeam/src/main/java/org/apache/cloudstack/backup/veeam/VeeamClient.java
- plugins/backup/veeam/src/test/java/org/apache/cloudstack/backup/VeeamBackupProviderTest.java
- server/src/main/java/org/apache/cloudstack/backup/BackupManagerImpl.java
Using the VMWare hypervisor, with the Veeam plugin active, it is not possible to remove backups. Instead, an exception is thrown in ACS, and the only procedure that allows the removal of backups is to remove the VM from the Backup Offering, which causes all backups for that VM to be removed.
Through Veeam's documentation and user forum, it was discovered that it does not allow the removal of specific restore points. Instead, the entire backup chain is removed, leaving only the job in Veeam.
To address this limitation, a new parameter has been added to the `deleteBackup` API to allow users to remove the complete Veeam backup chain. So, when removing a backup, users can pass the `forced` parameter as `true`, to remove all the backup chain, but keeping the VM in the Backup Offering. …
> [Veeam] Improve remove backup process

- debian/control
- packaging/centos7/cloud.spec
- packaging/centos8/cloud.spec
- packaging/suse15/cloud.spec
This PR changes the EL8 packaging to depend on `rng-tools` instead of the deprecated `haveged` that was inadvertently added previously. There is no `haveged` provided in EL8.
cloudstack-management EL8 RPM previously would not install as no dependency was found in standard repos. Now it does. Also confirmed `rngd` running after install.
> EL8 uses rng-tools for entropy, not haveged

- core/src/main/java/com/cloud/agent/api/storage/CreateDatadiskTemplateCommand.java
- engine/schema/src/main/java/com/cloud/storage/dao/GuestOSHypervisorDaoImpl.java
- engine/storage/src/main/java/org/apache/cloudstack/storage/image/deployasis/DeployAsIsHelperImpl.java
- services/secondary-storage/server/src/main/java/org/apache/cloudstack/storage/resource/NfsSecondaryStorageResource.java
This PR allows for downloading OVA with the read properties from OVF flag when the OVF does not contain a minimum hardware version.
Fixes: #6736
by uploading an OVA that does not provide a minimum hardware version and making sure it is accepted.
> Ova download fix

- server/src/main/java/com/cloud/network/vpc/VpcManagerImpl.java
The configuration `vpc.max.networks` is mentioned in the error message shown when attempting to exceed the network limit in a VPC; however, the final user should not be able to visualize such structural information. Therefore, this detail was removed from the message.
In a local lab I applied this patch and the error message was successfully updated.
> Remove environment information from exceeding network limit error message

- engine/schema/src/main/resources/META-INF/db/schema-41710to41800.sql
- ui/src/views/compute/CreateSnapshotWizard.vue
This PR fixes an issue where isolated networks without services created in version before 4.17 and in state 'Setup' could not be used even though they require no further implementation
implemented in an upgraded environment from 4.15 to 4.17 with a network in setup state
before: a new VM could not be started in the network (as it was in state 'Setup'
after a vm could be started in the network
> Set network state to implemented when no services

- api/src/main/java/com/cloud/deploy/DataCenterDeployment.java
- engine/components-api/src/main/java/com/cloud/vm/VirtualMachineProfileImpl.java
- engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/VolumeOrchestrator.java
- engine/storage/src/main/java/org/apache/cloudstack/storage/allocator/AbstractStoragePoolAllocator.java
- engine/storage/src/main/java/org/apache/cloudstack/storage/allocator/ClusterScopeStoragePoolAllocator.java
- engine/storage/src/main/java/org/apache/cloudstack/storage/allocator/LocalStoragePoolAllocator.java
- engine/storage/src/main/java/org/apache/cloudstack/storage/allocator/ZoneWideStoragePoolAllocator.java
- engine/storage/volume/src/main/java/org/apache/cloudstack/storage/datastore/PrimaryDataStoreImpl.java
- plugins/storage-allocators/random/src/main/java/org/apache/cloudstack/storage/allocator/RandomStoragePoolAllocator.java
This PR fixes a NPE that occurs when trying to create a volume from a snapshot. This happens because when trying to log the `virtualMachineProfile` in the `AbstractStoragePoolAllocator#logStartOfSearch` method, its `toString()` method will throw a NPE since the `_vm` attribute is null.
Some `toString()`s were also created in classes that had objects being logged during the volume creation process, as they were being logged as memory addresses since they had no `toString()` implementation.
This was tested in a local lab, before this patch every time I tried to create a volume from a snapshot, a NPE was thrown. After the patch the volume creation from snapshot was fixed.
> Fixed NPE on volume creation from snapshot

- plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/CitrixResourceBase.java
According to https://docs.citrix.com/en-us/citrix-hypervisor/monitor-performance.html The metrics "memory_internal_free" is already in KiB, no need to convert.
"Memory used as reported by the guest agent (KiB). Enabled by default"
This fixes #6848
> XenServer/XCP-ng: fix vm memory usage is always 99.9x%

- plugins/deployment-planners/implicit-dedication/src/test/java/org/apache/cloudstack/implicitplanner/ImplicitPlannerTest.java
Fix #6659 
This PR introduces Hamcrest API to simplify assertion in [`ImplicitPlannerTest.checkStrictModeWithCurrentAccountVmsPresent`](https://github.com/Codegass/cloudstack/blob/71056191f2bdad4be1a7eaf9bb73a7dcee3516f2/plugins/deployment-planners/implicit-dedication/src/test/java/org/apache/cloudstack/implicitplanner/ImplicitPlannerTest.java#L199), [`ImplicitPlannerTest.checkStrictModeHostWithCurrentAccountVmsFull`](https://github.com/Codegass/cloudstack/blob/71056191f2bdad4be1a7eaf9bb73a7dcee3516f2/plugins/deployment-planners/implicit-dedication/src/test/java/org/apache/cloudstack/implicitplanner/ImplicitPlannerTest.java#L233), and [`ImplicitPlannerTest.checkPreferredModePreferredHostAvailable`](https://github.com/Codegass/cloudstack/blob/71056191f2bdad4be1a7eaf9bb73a7dcee3516f2/plugins …
> Introducing Hamcrest API to simplify assertion in ImplicitPlannerTest

- framework/quota/src/main/java/org/apache/cloudstack/quota/activationrule/presetvariables/PresetVariableHelper.java
- framework/quota/src/test/java/org/apache/cloudstack/quota/activationrule/presetvariables/PresetVariableHelperTest.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtScaleVmCommandWrapper.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtScaleVmCommandWrapperTest.java
- server/src/main/java/com/cloud/hypervisor/KVMGuru.java
- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
- server/src/test/java/com/cloud/hypervisor/KVMGuruTest.java
- utils/src/main/java/org/apache/cloudstack/utils/bytescale/ByteScaleUtils.java
- utils/src/test/java/org/apache/cloudstack/utils/bytescale/ByteScaleUtilsTest.java
PR #5909 introduced a class to convert bytes through the scales (B, KiB, KB, MiB, MB...); however, there are some typos in the javadocs and method names. This PR intends to fix those typos and improve the javadocs.
> Fix typos and improve javadocs on ByteScaleUtils

- test/integration/component/test_network_vpc_custom_dns.py
- test/integration/smoke/test_register_userdata.py
flake8 --select=W291,W292,W293,W391 .
./test/integration/smoke/test_register_userdata.py:766:1: W391 blank line at end of file
./test/integration/component/test_network_vpc_custom_dns.py:732:1: W391 blank line at end of file
This PR fixes the `flake8` test
> gha(python): fix `W391` blank line at end of file

- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
VOLUME.DETACH, created during VM removal, has type VirtualMachine instead of Volume and has "Vm Id: XXX" in the description.
1. Create Volume
2. Create VM
3. Attach Volume to VM
4. Delete VM
5. Check Volume events page, VOLUME.DETACH is missing there
6. Check Events page, VOLUME.DETACH available, but has description "Vm Id: XXX" and resource is VM instead of Volume
The root cause: @actionevent uses CallContext information for event details, and in this case CallContext contains VM information.
Before this change (see VOLUME.DETACH event):
After this change:
> VOLUME.DETACH, created during VM removal has type VirtualMachine instead of Volume and has "Vm Id: XXX" in the description.

- ui/src/views/infra/zone/AdvancedGuestTrafficForm.vue
Fixes VLAN input while adding guest traffic type for the physical network in the zone wizard.
When adding a zone physical network is not updated with the guest traffic vlan, resulting in network, vm deployments failures.
Using UI,
- Deploy a new zone with zone deployment wizard
- Verify VLAN for guest traffic type in the physical network is updated
- Deploy VM in the zone and it shouldn't show any errors.
> ui: fix guest traffic vlan input

- engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
Fixes incorrect call of using service offering's ID while trying to retrieve linked disk offering.
> orchestration: fix diskoffering for vr rootdisk

- server/src/main/java/com/cloud/acl/DomainChecker.java
Fixes #6885
Fixes the incorrect inverted check.
Using API with two accounts in two different domains,
```
(local) 🕷 > list domains filter=id,name,path,
{
"count": 3,
"domain": [
{
"id": "02c03550-6a40-11ed-adb6-645d8651f45a",
"name": "ROOT",
"path": "ROOT"
},
{
"id": "a6df78e8-d16f-4b75-b2a9-e7e21bf1458b",
"name": "d1",
"path": "ROOT/d1"
},
{
"id": "9d7e43a1-4055-4de7-886f-bcf7b75a6509",
"name": "d2",
"path": "ROOT/d2"
}
]
}
(local) 🐕 > list accounts id=c39c1bed-77a2-40e2-9574-3cc0099152d4 filter=id,name,roletype,domainid,domainpath,
{
"account": [
{
"domainid": "a6df78e8-d16f-4b75-b2a9-e7e21bf1458b",
"domainpath": "ROOT/d1",
"id": "c39c1bed-77a2-40e2-9574-3cc0099152d4",
"name": "d1user",
"roletype": "User"
}
],
"count": 1
}
(local) 🍀 > list accounts …
```
> server: fix domain shared public template check

- server/src/test/java/org/apache/cloudstack/network/lb/ApplicationLoadBalancerTest.java
Fix: #6660 
This PR Simplify the test case [`ApplicationLoadBalancerTest.searchForNonExistingLoadBalancer`](https://github.com/apache/cloudstack/blob/ddb11b1b966cc2b3443ef4d2eeb55c1d64ff3fb9/server/src/test/java/org/apache/cloudstack/network/lb/ApplicationLoadBalancerTest.java#L189-L205) and try to imporve its readability.
The test case checks that when retrieving a non-existing lb, an InvalidParameterValueException should be raised. However, the intention is not explicit in the current implementation of the test case. See below the current implementation:
**Before Refactoring**
```java
@Test
//Negative test - try to retrieve non-existing lb
public void searchForNonExistingLoadBalancer() {
boolean notFound = false;
ApplicationLoadBalancerRule rule = null;
try {
rule = …
```
> Simplify Test Case ApplicationLoadBalancerTest.searchForNonExistingLoadBalancer

- server/src/test/java/org/apache/cloudstack/ca/CABackgroundTaskTest.java
Fix: #6203 
This PR introduces JUnit Assume API to the five test cases of `CABackgroundTaskTest`:
[`testNullCert`](https://github.com/apache/cloudstack/blob/4c5a2ba3a6eb6399390c2f8963cb26e0e35fc058/server/src/test/java/org/apache/cloudstack/ca/CABackgroundTaskTest.java#L94-L99), [`testNullHost`](https://github.com/apache/cloudstack/blob/4c5a2ba3a6eb6399390c2f8963cb26e0e35fc058/server/src/test/java/org/apache/cloudstack/ca/CABackgroundTaskTest.java#L102-L108), [`testAutoRenewalEnabledWithExceptionsOnProvisioning`](https://github.com/apache/cloudstack/blob/main/server/src/test/java/org/apache/cloudstack/ca/CABackgroundTaskTest.java#L122), [`testAutoRenewalEnabledWithNoExceptionsOnProvisioning`](https://github.com/apache/cloudstack/blob/main/server/src/test/java/org/apache/cloudstack/ca/CABac …
> Bring in the JUnit Assume Feature to `CABackgroundTaskTest`

- api/src/main/java/com/cloud/server/ManagementService.java
- server/src/main/java/com/cloud/server/ManagementServerImpl.java
- server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
- server/src/main/java/com/cloud/vm/UserVmManager.java
- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
- server/src/main/java/org/apache/cloudstack/vm/UnmanagedVMsManagerImpl.java
- test/integration/smoke/test_scale_vm.py
Fixes #6701
When volume migration is initiated by system, account check is not needed.
Introduces a new global setting - `allow.diskOffering.change.during.scale.vm`
Determines whether to allow or disallow disk offering change for root volume during scaling of a stopped or running VM. Default value is `true`
> server: fix volume migration on user vm scale

- plugins/network-elements/opendaylight/src/test/java/org/apache/cloudstack/network/opendaylight/api/test/NeutronNetworkAdapterTest.java
- plugins/network-elements/opendaylight/src/test/java/org/apache/cloudstack/network/opendaylight/api/test/NeutronNodeAdapterTest.java
- plugins/network-elements/opendaylight/src/test/java/org/apache/cloudstack/network/opendaylight/api/test/NeutronPortAdapterTest.java
The tests below in `NeutronNetworkAdapterTest.java`, `NeutronNodeAdapterTest.java` and `NeutronPortAdapterTest.java` were found flaky because of the ordering of JSON objects. The orders of elements in the JSON objects were not the same every time the test being called. In this case, JsonParser from Gson was applied to ensure the orders do not cause the flakiness. This code change is trying to fix the [flaky tests](https://docs.gitlab.com/ee/development/testing_guide/flaky_tests.html) mentioned above, because they sometimes fail (as the picture showed) and sometimes pass. The failure could be reproduced by the commands below by using the tool of [NonDex](https://github.com/TestingResearchIllinois/NonDex). The code change is to make sure the tests will always pass in this case.
- …
> Fix flaky tests in NeutronNetworkAdapterTest.java, NeutronNodeAdapterTest.java and NeutronPortAdapterTest.java

- systemvm/debian/opt/cloud/bin/configure.py
PR #5375, introduced in version 4.15.2.0, removed parameter `%any` of VPNs client-to-site (C2S) IPSec secrets:
- structure before PR #5375:
`<IP> %any : PSK "<PSK>"`
- structure after PR #5375:
`<IP> : PSK "<PSK>"`
Because of that, when a VPN site-so-site (S2S) is created in parallel to a VPN C2S in the same network, the C2S will not handle any IP (`%any`) anymore and, as the network is being tunneled to the other VPN, the connection will be handled by the final peer. This way, when a VPN S2S is created in parallel to a VPN C2S in the same network, it is only possible to connect to the C2S with the S2S PSK.
As ACS is only able to implement a single C2S per network (ACS allows setting more than one IP of the network as VPN, however, only the first will be implemented) and every S2S has its …
> Fix C2S VPN in parallel to S2S VPN

- engine/schema/src/main/java/com/cloud/storage/dao/VolumeDao.java
- engine/schema/src/main/java/com/cloud/storage/dao/VolumeDaoImpl.java
- server/src/main/java/com/cloud/storage/StorageManagerImpl.java
- server/src/main/java/com/cloud/vm/UserVmManager.java
- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
- server/src/test/java/com/cloud/vm/UserVmManagerImplTest.java
When a user removes a VM, ACS puts it in a `Destroy` state and stops counting it towards the user resource limit. However, the VM root volume remains in `Ready` state and consuming resources until the VM cleanup task runs on ACS. 
The `destroy.root.volume.on.vm.destruction` setting was created so that when it is set to true, when destroying a VM its root volume will also be placed in the `Destroy` state, no longer counting towards the user resource limit.
Also, while this setting is active, root volumes in the destroy state will not be removed by the ACS volume cleanup task, so that it is possible to restore the VM again. However, the VM cleanup task will still remove the VMs along with their respective volumes.
This was tested in a local lab.
| Nº | Test | Result |
| ------ | ------ | …
> Set root volume as destroyed when destroying a VM

- client/bindir/cloud-setup-management.in
This PR is for changing the line printed as : "Please ensure the following ports are open for the management server to function properly : 8080 8250 8443 9090"  to more understandable lines. The above line was misleading , so it was changed to new lines  :   
print("Please ensure ports 8080, 8250, 8443, and 9090 are opened and not fire walled for the management server and not in use by other processes on this host.")
This happens after the management server is setup. Behaviour functionally has not changed at all. Only,meaning of the lines printed has changed.
The behavior Functionally has not changed at all.
- [**yes**] Trivial
This has been tested on local environment.  
Trivial Normal tests were done , that is usually done when source code is compiled and management server is started.
> Fixed the management server setup line

- plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/manager/VmwareStorageManagerImpl.java
- plugins/hypervisors/vmware/src/test/java/com/cloud/hypervisor/vmware/manager/VmwareStorageManagerImplTest.java
Fixes #6894
Fixes NPE observed when VM volume is present on the same child datastore.
> vmware: fix vmware vm snapshot operations for datastorecluster

- ui/src/views/compute/DeployVM.vue
Fixes #6756
Pass hypervisor parameter for `deployVirtualMachine` API only when ISO is selected and not for a template.
> ui: fix incorrect hypervisor on deploy VM wizard submit

- api/src/main/java/org/apache/cloudstack/context/CallContext.java
- engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
- engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/VolumeOrchestrator.java
- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
When VM is created and ROOT volume is created it should emit a VOLUME.CREATE event.
1. Create VM
2. Check events
3. VOLUME.CREATE for the ROOT volume is not present
After the fix (see highlighted VOLUME.CREATE event)
> When VM is created and ROOT volume is created it should emit a VOLUME.CREATE event

- server/src/main/java/org/apache/cloudstack/vm/UnmanagedVMsManagerImpl.java
Fixes #6951
Adds deviceid for NICs of an imported VM. Device Id will be set 0..n in the order in which they are returned by hypervisor.
https://user-images.githubusercontent.com/153340/206171296-b806f11f-b661-4cd9-a1da-e4868091d9de.mp4
> server: fix nic device id for imported vm

- systemvm/debian/opt/cloud/bin/setup/init.sh
- systemvm/debian/opt/cloud/bin/setup/vpcrouter.sh
This PR fixes that the /etc/network/interfaces is misconfigured in VPC VR startup, which causes VPC VR to be stuck for 1 minute and continue working.
The issue is because `ifup eth0` and `ifdown eth0` do not work when `/etc/network/interfaces` is not correct in VPC VR.
severity: to be discussed.
This requires a new systemvm template.
> VPC VR: fix /etc/network/interfaces is misconfigured

- test/integration/smoke/test_vm_lifecycle_unmanage_import.py
PR #6964 added some changes for VM import test which are causing exceptions on non-VMware environments. This PR fixes those error and correctly skips unmanage and import tests for non-VMware env.
**On KVM** - tests are skipped without errors
```
[root@pr6803-t5409-kvm-centos7-marvin marvin]# nosetests --with-xunit --xunit-file=results.xml --with-marvin --marvin-config=./pr6803-t5409-kvm-centos7-advanced-cfg -s -a tags=advanced --hypervisor=KVM tests/smoke/test_vm_lifecycle_unmanage_import.py 
/usr/local/lib/python3.6/site-packages/paramiko/transport.py:33: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
from cryptography.hazmat.backends import …
```
> test: fix failure on non-VMware env

- plugins/metrics/src/main/java/org/apache/cloudstack/api/ListVMsMetricsCmd.java
- plugins/metrics/src/main/java/org/apache/cloudstack/api/ListVMsMetricsCmdByAdmin.java
- plugins/metrics/src/main/java/org/apache/cloudstack/metrics/MetricsServiceImpl.java
- server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
Fixes #6786
listVirtualMachinesMetrics does not support some of the params that are supported by admin API call for listVirtualMachines. These parameters are used in UI.
> api,server: fix listing vm metrics for infra resources

- engine/schema/src/main/java/com/cloud/upgrade/DatabaseUpgradeChecker.java
There's no DB upgrade path b/w 4.17.1.0 and 4.17.2.0, this adds the same upgrade path of 4.17.1.0 when source version is 4.17.2.0.
> schema: Add upgrade path from 4.17.2.0 same as 4.17.1.0

- plugins/backup/veeam/src/main/java/org/apache/cloudstack/backup/veeam/VeeamClient.java
PR #5774 introduced a functionality to allow operators to choose in which Veeam's repository, if more than one is configured, ACS' clone job will be executed. However, a change was missing in the PR and caused the errors reported in #6599. 
This PR addresses the fix for #6599.
It was tested in a local laboratory:  
- I assigned three VMs to three Backup Offerings;
- Before, the assign fails, with the same message reported in issue #6599;
- Now the assign works.
> [Veeam] Fix escape powershell comand when listing Veeam repository names

- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
- server/src/test/java/com/cloud/user/AccountManagerImplVolumeDeleteEventTest.java
- server/src/test/java/com/cloud/user/AccountManagetImplTestBase.java
This PR fixes a double declaration of ServiceOfferingDao in UserVmManagerImpl.
I applied the changes in a local lab, and checked if commands associated to UserVmManagerImpl were correctly executed.
> Fix ServiceOfferingDao duplication

- plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/datastore/driver/StorPoolPrimaryDataStoreDriver.java
Remove the Iops limits when resizing a volume with disk offering without iops limits or with a custom Iops limits in offerings
Test resizing volume with different disk offerings by providing/removing iops limits on StorPool volumes
> fix of removing the Iops limits on StorPool volumes

- api/src/main/java/org/apache/cloudstack/ca/CAManager.java
- core/src/main/java/com/cloud/agent/api/routing/NetworkElementCommand.java
- engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
- engine/orchestration/src/test/java/com/cloud/vm/VirtualMachineManagerImplTest.java
- server/src/main/java/org/apache/cloudstack/ca/CAManagerImpl.java
There are some networking setups where system VM communications are proxied off of the hypervisor host on which the system VM is running. For example, if the KVM management network is a NAT bridge, or the network plugin employs user mode network for system VM management interfaces, then system VM agent comms look as though they come form the hypervisor host. Admittedly, these configurations are bespoke, which is why a configuration is provided and it's disabled by default.
In such a setup, the certificate authentication for agents fails because the source IP is that of the host of the system VM, rather than the system VM itself, and this IP is not in the connecting certificate presented. This PR adds a configuration value that allows the system VM cert to contain the host IP that the …
> Allow ssvm agent certs to contain host IP for NAT situations

- plugins/metrics/src/main/java/org/apache/cloudstack/api/ListVMsMetricsCmd.java
- test/integration/smoke/test_metrics_api.py
Fixes #6983
In case of multiple command classes for an API, ApiServer returns an API command class for User role only when ResponseView is set to Restricted in the annotation. This PR set Restricted ResponseView for ListVMsMetrics class. It also adds a smoke test for User role account for the listVirtualMachinesMetrics API.
```
⇒  nosetests --with-xunit --xunit-file=results.xml --with-marvin --marvin-config=./setup/dev/advanced.cfg -s -a tags=advanced --hypervisor=Simulator test/integration/smoke/test_metrics_api.py 
==== Log Folder Path: /tmp/MarvinLogs/Dec_14_2022_00_24_06_9HK9RV All logs will be available here ====
==== Marvin Init …
```
> api,server,metrics: fix listVirtuaMachinesMetrics API for user

- scripts/vm/hypervisor/update_host_passwd.sh
When adding a KVM host via ACS UI, it is necessary to provide a username and password for ACS to connect via SSH to the host. When using the `updateHostPassword` API, ACS updates the password in the metadata. When the update_passwd_on_host parameter is specified as true, ACS sends a command to the host that causes it to run a script to change the user's password on the host.
During some internal tests, it was observed that the script was not changing the password and returned an error. Adjustments were made to this script to make it work again.
After executing the `updateHostPassword` API, an attempt was made to access the host via ssh using the user and the new password as a parameter. The expected result is that the password for that user has been updated, and this was the result …
> Fixes script that perform change password on hosts

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
Fixes: #6807
When a custom offering is used max vCPU value may differ from the actual vCPU value therefore while applying CPU topology correct value must be used.
Using a custom constrained offering with CPU range 1-6 and VM deployed with CPU=4
```
> list serviceofferings id=bbe6c987-b609-42ab-a6a6-9268d8bd35a7 
{
"count": 1,
{
"cacheMode": "none",
"created": "2022-11-04T07:20:41+0000",
"displaytext": "CustomConstrained",
"id": "bbe6c987-b609-42ab-a6a6-9268d8bd35a7",
"iscustomized": true,
"name": "CustomConstrained",
"offerha": false,
"provisioningtype": "thin",
"rootdisksize": 0, …
```
> kvm: correctly set vm cpu topology

- utils/src/main/java/com/cloud/utils/nicira/nvp/plugin/NiciraNvpApiVersion.java
This PR removes unnecessary logging on VMware deployments in which the NVP plugin is not enabled. On each StartCommand a similar line is logged even if the NVP plugin is not configured:
````
2022-12-14 15:05:33,375 INFO  [c.c.u.n.n.p.NiciraNvpApiVersion] (DirectAgent-434:ctx-979662ea esxi2.michikusa.local, job-2738/job-2739, cmd: StartCommand) (logid:5a621e44) NSX API VERSION:  NOT PRESENT
````
> [VMware] Remove unnecessary logs on VM deployments

- engine/schema/pom.xml
- engine/schema/src/main/java/com/cloud/upgrade/DatabaseVersionHierarchy.java
- engine/schema/src/test/java/com/cloud/upgrade/DatabaseUpgradeCheckerTest.java
- engine/schema/src/test/java/com/cloud/upgrade/DatabaseVersionHierarchyTest.java
- pom.xml
This PR...
Fixes: #6760
unit tests (so far)
> allow a new upgrade version without DB changes to be inserted

- setup/bindir/cloud-sysvmadm.in
Fixes #6220
```
[root@ref-trl-3339-v-M7-abhishek-kumar-mgmt1 ~]# /usr/bin/cloudstack-sysvmadm
The tool stopping/starting running system vms and domain routers 
Usage: cloudstack-sysvmadm: [-d] [-u] [-p] [-m] [-s] [-r] [-a] [-t] [-n] [-z] [-i] [-j] [-v] [-i] [-j]
-d - cloud DB server ip address, defaulted to localhost if not specified 
-u - user name to access cloud DB, defaulted to root if not specified 
-p - cloud DB user password, defaulted to no password if not specified 
-m - the ip address of management server, defaulted to localhost if not specified
-s - stop then start all running SSVMs and Console Proxies 
-r - stop then start all running Virtual Routers
-a - stop then start all running SSVMs, Console Proxies, and Virtual Routers 
-n - restart all Guest networks 
-t - number of …
```
> scripts: parametrize systemvm, router restart

- test/integration/component/test_network_ipv6.py
- test/integration/component/test_vpc_ipv6.py
- test/integration/smoke/test_network_ipv6.py
- test/integration/smoke/test_vpc_ipv6.py
When using admin=True in account creation with domain it creates a domain admin. It would be better to run tests as normal user.
> test: use normal user for creating networks, vpcs

- api/src/main/java/org/apache/cloudstack/consoleproxy/ConsoleAccessManager.java
- server/src/main/java/org/apache/cloudstack/consoleproxy/ConsoleAccessManagerImpl.java
- ui/src/components/widgets/Console.vue
This PR adds a few improvements on the console access, by:
- Removing the `consoleproxy.extra.security.validation.enabled` configuration introduced on the main branch (not yet on any release), in favour of the optional parameter `token` on the `createConsoleEndpoint`.
- Improving the error message when trying to access the console of a virtual machine that is not running
- Access console for virtual machines on the UI
- Using cmk, generate a console endpoint without the token parameter -> verify connection to the URL
- Using cmk, generate a console endpoint with the token parameter -> verify connection to the URL
- Using cmk, generate a console endpoint for a stopped VM -> check descriptive error message
> Minor console access refactor and improvements

- plugins/integrations/prometheus/src/main/java/org/apache/cloudstack/metrics/PrometheusExporterImpl.java
Previously, only the domain name (last part of the full path) was exposed as a label for prometheus metrics. This ensures that the full path is exposed instead, to allow domains that have the same name (e.g. /ROOT/A/NAME, /ROOT/B/NAME) to be reported in different groups.
Fixes #6859
Compiler only
> Metrics plugin: expose full domain path instead of name

- ui/src/components/view/BulkActionProgress.vue
- ui/src/components/view/BulkActionView.vue
- ui/src/components/widgets/TooltipLabel.vue
- ui/src/views/network/LoadBalancing.vue
PR #6460 reimplemented the `cidrlist` in API `createLoadBalancerRule`; However, this parameter was not implemented in the UI. This PRs intends to implement the `cidrlist` field in the create load balancer rule form.
This PR also fixes the `BulkActionView.vue`, which currently throws an exception when used.
This was tested in a local lab, by running `npm run serve` and creating/deleting load balancer rules with `cidrlists`. The BulkActionView was also tested: before this change it was throwing an exception and was not opening the form. After the changes, it worked fine.
> Support for parameter `cidrlist` added to the UI

- engine/schema/src/main/resources/META-INF/db/schema-41720to41800.sql
- test/integration/smoke/test_vm_autoscaling.py
This PR fixes the smoke test as per Daan's comments (see https://github.com/apache/cloudstack/pull/6571#pullrequestreview-1204572347).
This PR also fixes an issue that "supports_vm_autoscaling" needs to be updated only if all network offerings has supports_vm_autoscaling = 0 .
(this might be an issue if upgrade from a fork to community version)
> AutoScaling: update smoke test and consider db upgrade from a fork

- pom.xml
- tools/appliance/systemvmtemplate/scripts/configure_systemvm_services.sh
- tools/appliance/systemvmtemplate/template.json
This fixes packer systemvmtemplate build and uses latest Debian ISO URL and checksum.
> systemvmtemplate: update Debian ISO URL and checksum

- ui/src/views/compute/wizard/MultiNetworkSelection.vue
In import VM form, shared network is not showing when it is in Setup state which should not be the case. This PR fixes that.
Before:
After:
> ui: fix suitable shared network not showing while import

- plugins/integrations/prometheus/src/main/java/org/apache/cloudstack/metrics/PrometheusExporterImpl.java
This PR...
Fixes: #7000
It makes prometheus integration returns the same value ("0") when a capacity is explicitly "Disabled" or non-existent. 
Set a host in maintenance.
Restart the cloudstack-management service.
Capacities are set to Disabled in table "op_host_capacity".
```
MariaDB [cloud]> SELECT id,host_id,used_capacity,reserved_capacity,total_capacity,capacity_type,capacity_state FROM op_host_capacity WHERE `host_id`=1;
+----+---------+---------------+-------------------+----------------+---------------+----------------+
| id | host_id | used_capacity | reserved_capacity | total_capacity | capacity_type | capacity_state |
+----+---------+---------------+-------------------+----------------+---------------+----------------+
| 11 |       1 |        196640 |                 0 | …
```
> Ensure Prometheus doesn't return values when the capacity_state is disabled

- test/integration/component/test_acl_sharednetwork.py
This PR reverts changes that broke the gh action for test_acl_sharednetworks.py
> revert cleanup of test_acl_sharenetworks

- engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
When scaling a VM, the new details of the compute resources (memory, CPU speed, and CPU cores) are updated in the database after generating the usage event. This way, the usage events are generated with outdated details. Usage uses those events while generating entries in `cloud_usage.usage_vm_instance` and `cloud_usage.cloud_usage`, however, as in the scaling the details are updated after generating the events, the entries for the VM in `cloud_usage.usage_vm_instance` are always outdated after the scaling, as well the entries in `cloud_usage.cloud_usage`. In order to make Usage generate the proper entries, operators must stop and start the VM again (generating events of stop and start with the current VM compute resources' state).
This PR intends to fix this behavior by updating the …
> Update usage when scaling vms

- ui/src/views/infra/zone/AdvancedGuestTrafficForm.vue
This PR fixes #6727 
The start of guest vlan range is a must. 
if end is not set, the vlan range is start-start
otherwise, the vlan range is start-end
Start and end are not set.
Start is set
wrong range
correct range
> UI: user must specify the start of guest vlan range for advanced zone

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtDomainXMLParser.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java
When taking a snapshot of a volume in a VM with an ISO attached, ACS attempts to define the label of the target associated with the ISO by its ID. However, this ID may not be correctly mapped to the label, which causes the snapshot to fail.
This PR fixes this by using the defined label, instead of defining it during the snapshot process by its ID.
In a local lab, I created 3 VMs with ISOs attached: VM1, VM2 and VM3. VM1 had 1 volume, VM2 had 2 volumes, and VM3 had 3 volumes.  The label of the target associated to the ISO was `hdc` for all of them. 
When taking a snapshot for the volume in VM1, the label was incorrectly generated as `hdb`, which caused the snapshot to fail.
When taking snapshots for the volumes in VM2, the label was correctly generated as `hdc`, and the snapshots …
> Fix volume snapshot in a VM with an ISO attached

- ui/src/config/section/image.js
The [PR#6750](https://github.com/apache/cloudstack/pull/6750) allowed Root Admins to download system VM templates through the API. This function was extended to the UI.
Before:
After:
Before applying the changes:
1. I opened the instance menu and checked that I was unable to download the template.
After applying the changes:
1. I opened the instance menu with a Root Admin account and checked that the download button was available.
2. I opened the instance menu with a non-Root Admin account and checked that the download button was not available.
> Allow download of System VM templates through the  UI

- ui/src/views/AutogenView.vue
Currently the ordering of backup offerings is done based on their IDs. This ordering was altered to be made based on their names, in order to enhance its organization.
Before:
After:
1. Before applying the changes I opened the 'assign VM to backup offering' window and checked that the offerings where ordered based on their ID.
2. After applying the changes I reopened the same window and verified that now the offerings were ordered alphabetically.
> alter ordering of backup offerings

- utils/src/main/java/com/cloud/utils/HumanReadableJson.java
- utils/src/test/java/com/cloud/utils/HumanReadableJsonTest.java
When an API response parameter which is expected by HumanReadableJson utility to return a number value is not returning a number value it results in API failure. This change makes API return the value as it is when there is a NumberFormatException with one of the API response param which is listed in HumanReadableJson.
Failure seen without change (A new API added which returns a param size as SMALL, BIG, HUGE),
```
(local) 🦑 > create something
{
"accountid": "b009bced-803a-11ed-87cc-645d8651f45a",
"cmd": "org.apache.cloudstack.api.command.CreateSomethingCmd",
"completed": "2022-12-21T12:46:06+0530",
"created": "2022-12-21T12:45:20+0530",
"jobid": "c12b240b-bded-4c4e-bbd2-7c62959a8d60",
"jobinstancetype": "None",
"jobresult": {
"errorcode": 530,
"errortext": "For input …
```
> utils: fix human-readable parsing failures

- api/src/main/java/org/apache/cloudstack/api/BaseCmd.java
- api/src/main/java/org/apache/cloudstack/api/command/user/job/ListAsyncJobsCmd.java
- server/src/main/java/com/cloud/api/dispatch/ParamProcessWorker.java
- ui/src/components/view/StatsTab.vue
Although ACS stores all dates in the DB with the UTC timezone, all APIs that have parameters of type date are handled according to the server's timezone. In this case, if the server's timezone is in UTC-3, for instance, and user is in UTC-2 and inform `yyyy-MM-dd 09:00:00` in the parameter, the Date object will be `yyyy-MM-dd 09:00:00` (UTC-3) and ACS will convert it to `yyyy-MM-dd 12:00:00` while querying the database. This way, if the final users want to retrieve data from date `09:00:00`, they must know the server's timezone in order to inform the correspondent date (in this example, `yyyy-MM-dd 06:00:00`).
This situation is very clear when calling the `listvirtualmachinesusagehistory` API. If the data was collected at `yyyy-MM-dd 12:00:00` (UTC), final user must know that the server …
> Allow users to inform timezones on APIs that have the date parameter

- plugins/user-authenticators/ldap/src/main/java/org/apache/cloudstack/ldap/OpenLdapUserManagerImpl.java
This PR fixes a theoretical issue n the ldap authentication plugin
tested in a lab env making sure the same imports could still be done.
> escapes for injection protection

- api/src/main/java/com/cloud/configuration/ConfigurationService.java
- api/src/main/java/org/apache/cloudstack/api/command/admin/offering/IsAccountAllowedToCreateOfferingsWithTagsCmd.java
- api/src/main/java/org/apache/cloudstack/api/command/admin/offering/UpdateDiskOfferingCmd.java
- api/src/main/java/org/apache/cloudstack/api/command/admin/offering/UpdateServiceOfferingCmd.java
- api/src/main/java/org/apache/cloudstack/api/response/IsAccountAllowedToCreateOfferingsWithTagsResponse.java
- engine/schema/src/main/resources/META-INF/db/schema-41720to41800.sql
- server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
- server/src/main/java/com/cloud/server/ManagementServerImpl.java
- server/src/test/java/com/cloud/vpc/MockConfigurationManagerImpl.java
- ui/src/views/offering/AddComputeOffering.vue
- ui/src/views/offering/AddDiskOffering.vue
ACS only allows root admins to enter tags during the creation of service, disk, and network offerings; however, in private cloud environments, domain admin accounts may have autonomy and knowledge of the infrastructure, being able to direct resources according to their needs. 
To enable this behavior, a new account-level setting (`allow.domain.admins.to.create.offerings.with.tags`) has been created. When disabled (default), the previous behavior is maintained; when enabled, the domain admin account can enter tags when creating disk and service offerings. As we did not see a use case for network offering tags, these were not touched, that is, this new configuration will not affect network offering creation.
In addition, the UI has been changed to allow domain admins to inform these fields …
> Allow domain admins to inform tags when creating offerings

- plugins/storage/volume/storpool/pom.xml
- plugins/storage/volume/storpool/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/StorPoolDownloadTemplateCommandWrapper.java
- plugins/storage/volume/storpool/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/StorPoolModifyStorageCommandWrapper.java
- plugins/storage/volume/storpool/src/main/java/com/cloud/hypervisor/kvm/storage/StorPoolStorageAdaptor.java
- plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/datastore/driver/StorPoolPrimaryDataStoreDriver.java
- plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/datastore/provider/StorPoolHostListener.java
- plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/datastore/util/StorPoolUtil.java
- plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/snapshot/StorPoolVMSnapshotStrategy.java
- plugins/storage/volume/storpool/src/test/java/org/apache/cloudstack/storage/datastore/driver/StorPoolPrimaryDataStoreDriverTest.java
- server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
- test/integration/plugins/storpool/MigrateVolumeToStorPool.py
- test/integration/plugins/storpool/sp_util.py
- tools/marvin/marvin/lib/base.py
- Enable live volume migration between StorPool primary storage. Migrating volumes live between two StorPool's primary storages doesn't make changes in the XML of the domain. It only updates the information into StorPool
- removed unnecessary logging to storpool-agent.log when there isn't StorPool primary storage
- fix the first download of the system VM template
CS version - main branch
hypervisors - KVM
primary storage - 2 Zone-wide StorPool's primary storages
> Enable live volume migration for StorPool and small fixes

- test/integration/component/test_tags.py
This PR skips the tagging tests that fail due an ISO not uploading (which is not part of the functionality being tested)
relates to #7021
> assess prerequisite before doing the actual test

- tools/docker/Dockerfile
This PR updates the docker image for ubuntu 20.04 to ubuntu 22.04.
> simulator: use ubuntu 22.04 in Dockerfile

- api/src/main/java/com/cloud/server/ResourceTag.java
- server/src/main/java/com/cloud/tags/ResourceManagerUtilImpl.java
Use hashmap to search for resource type rather than iterating over
all of them
> Search for resource type efficiently

- ui/public/locales/en.json
- ui/src/views/offering/AddComputeOffering.vue
> UI: fix diskofferingstrictness is not passed when create compute offering

- vmware-base/src/main/java/com/cloud/hypervisor/vmware/util/VmwareContext.java
Fixes: #6992
During disk operations, the VMware plugin tries to connect to the VMware datacenter datastore using a URL based on the disk path and datastore name. This PR encodes the disk path to prevent any failure from the server due to a bad URL.
Without change,
```
2022-12-14 12:04:34,963 ERROR [c.c.s.r.VmwareStorageProcessor] (DirectAgent-482:ctx-38e8658a 10.0.34.64, job-169/job-170, cmd: DettachCommand) (logid:e6c5c585) Failed to detach volume!
java.io.IOException: Server returned HTTP response code: 400 for URL: https://10.0.33.178/folder/space test/space test_30.vmdk?dcPath=Trillian&dsName=fd54f3559fe43f60b8694fe4ccac777f
at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1924)
at …
```
> vmware: encode disk path for URL based access

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtReadyCommandWrapper.java
Small fix to also support UEFI check on agent connect. Refer: https://github.com/apache/cloudstack/pull/6139/files
> kvm: make UEFI host check to support both Ubuntu and EL

- api/src/main/java/com/cloud/storage/VolumeApiService.java
- server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
This PR fixes #6774
set global setting
- custom.diskoffering.size.max = 20
- custom.diskoffering.size.min = 10
resize volume
- size too big
- size too small
> storage: validate disk size range of custom disk offering when resize volume

- scripts/util/keystore-setup
- server/src/main/java/com/cloud/hypervisor/kvm/discoverer/LibvirtServerDiscoverer.java
This PR fixes #6716
If a KVM host has been added to cloudstack environment before, then we reset agent.properties to original file (./agent/conf/agent.properties), and add the host to cloudstack again, we will face the following error:
2023-01-11 20:54:03,734 DEBUG [c.c.h.k.d.LibvirtServerDiscoverer] (qtp1647766367-13:ctx-17f9aff7 ctx-47c881cb) (logid:49819f17)  can't setup agent, due to com.cloud.utils.exception.CloudRuntimeException: Failed to setup keystore on the KVM host: 10.0.32.229 - Failed to setup keystore on the KVM host: 10.0.32.229 com.cloud.utils.exception.CloudRuntimeException: Failed to setup keystore on the KVM host: 10.0.32.229
at com.cloud.hypervisor.kvm.discoverer.LibvirtServerDiscoverer.setupAgentSecurity(LibvirtServerDiscoverer.java:178)
at …
> KVM: revert libvirtd config and retry if fail to add a host

- engine/schema/src/main/resources/META-INF/db/schema-41720to41800.sql
- pom.xml
- vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/VirtualStorageObjectManagerMO.java
Adds basic support to bump VMware vim sdk to 8.0, enable in hypervisor capabilties and copy guest mappings from the previous version.
May be a quick one to accept this, to have early access/support for 8.0 in ACS. Later any integration that requires changes in ACS for support in Trillian/BO can be done as separate PR.
> Add support for vSphere 8.0

- api/src/main/java/org/apache/cloudstack/api/command/user/vpc/ListVPCOfferingsCmd.java
- engine/schema/src/main/java/com/cloud/domain/dao/DomainDao.java
- engine/schema/src/main/java/com/cloud/domain/dao/DomainDaoImpl.java
- server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
- server/src/main/java/com/cloud/network/vpc/VpcManagerImpl.java
Fixes #6745
Using API with cmk,
```
(local) 🍂 > create domain name=d1
{
"domain": {
"haschild": false,
"id": "afd89eeb-da02-4701-8b87-df0701d8c4a8",
"level": 1,
"name": "d1",
"parentdomainid": "fcb3da55-37e0-11ed-b99e-645d8651f45a",
"parentdomainname": "ROOT",
"path": "ROOT/d1",
"secondarystoragetotal": 0
}
}
(local) 🐷 > create domain name=d2
{
"domain": {
"haschild": false,
"id": "e52fe7a9-0f29-4463-84c4-21bcadf0b99f",
"level": 1,
"name": "d2",
"parentdomainid": "fcb3da55-37e0-11ed-b99e-645d8651f45a",
"parentdomainname": "ROOT",
"path": "ROOT/d2",
"secondarystoragetotal": 0
}
}
(local) 🙉 > create networkoffering name=n1 displaytext=n1 domainid=fcb3da55-37e0-11ed-b99e-645d8651f45a,fcb3da55-37e0-11ed-b99e-645d8651f45a guestiptype=Isolated traffictype=Guest
{
"networkoffering": { …
```
> server: fix listnetworkofferings with domain, refactor listvpofferings

- engine/schema/src/main/resources/META-INF/db/schema-41720to41800.sql
This PR fixes a blocker issue in 4.18/main branch.
- deploy 4.17.2.0 environment
- create VPC and deploy vm
- upgrade to 4.18.0.0 nightly
- restart VPC with cleanup or restart VPC router
error logs
```
{"com.cloud.agent.api.PlugNicAnswer":{"result":"true","details":"success","wait":"0","bypassHostMaintenance":"false"}},{"com.cloud.agent.api.routing.GroupAnswer":{"results":["null - success: ","null - failed: Traceback (most recent call last):
File "/opt/cloud/bin/update_config.py", line 144, in <module>
process_file()
File "/opt/cloud/bin/update_config.py", line 53, in process_file
qf.load(None)
File "/opt/cloud/bin/merge.py", line 309, in load
updateDataBag(self)
File "/opt/cloud/bin/merge.py", line 92, in __init__
self.process()
File …
```
> vpc/network: set mtu of networks/vpcs/nics during 4.18 upgrade

- tools/marvin/setup.py
On EL7 and EL8, when Marvin is installed and if newer mysql-connector-python is installed leads to errors which aren't compatible with python 2.7 and 3.6.
> marvin: install mysql-connector-python version 8.0.31

- python/lib/cloudutils/serviceConfig.py
- python/lib/cloudutils/syscfg.py
- python/lib/cloudutils/utilities.py
This masks sockets such as virtqemud.socket virtqemud-ro.socket virtqemud-admin.socket, and services virtqemud virtnetworkd virtstoraged that block libvirtd to be used a monolithic service. Useful for both EL9 and existing Ubuntu 22.04, and newer distros.
Didn't test with these changes, but after setting up a local RHEL9+KVM env I had to run these to block them from interfering with the libvirtd process.
> cloudstack-setup-agent: mask libvirt non-monolithic services

- tools/marvin/mvn-setup.py
Newer python setuptools doesn't like -SNAPSHOT in marvin version. This has been reported such as https://github.com/pypa/setuptools/issues/3772
The fix is to either downgrade or fix the version string to use something that setuptools likes.
Tested on mbx. Found that when setuptools is upgraded to v66+, this breaks Marvin installation. Refer: https://github.com/pypa/setuptools/issues/3772
> marvin: newer python setuptools doesn't like -SNAPSHOT in marvin version

- engine/schema/src/main/resources/META-INF/db/schema-41720to41800.sql
Add support for specific/available version 8.0.0.1 (8.0a). Without this, most of the lifecycle works except for vMotion (VM migration) which complains about missing VMware version hypervisor capabilities.
Tested with https://github.com/shapeblue/mbx on Ubuntu 22.04 host using vmware 8.0.0.1 template.
> vmware: support vsphere 8 specific version

- api/src/main/java/com/cloud/deploy/DeployDestination.java
- engine/schema/src/main/java/com/cloud/host/dao/HostDao.java
- engine/schema/src/main/java/com/cloud/host/dao/HostDaoImpl.java
- server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
- server/src/test/java/com/cloud/storage/VolumeApiServiceImplTest.java
- test/integration/smoke/test_vm_life_cycle.py
This PR fixes a memory leak issue observed when attaching more than 10 volumes on a stopped VM and try to start it.
Could be reproduced by:
- Create a VM without starting it
- Create 14 data disks and attach them to the VM
- Start VM
````
{
"accountid": "cdd3f51c-9862-11ed-8965-1e00dc0000f6",
"cmd": "org.apache.cloudstack.api.command.admin.vm.StartVMCmdByAdmin",
"completed": "2023-01-24T15:19:50+0000",
"created": "2023-01-24T15:19:47+0000",
"jobid": "da7e88d1-a8c4-4d44-91b3-21cef885769f",
"jobinstanceid": "d4fed850-c112-489a-84dd-8bb875ba0e10",
"jobinstancetype": "VirtualMachine",
"jobresult": {
"errorcode": 530,
"errortext": "Java heap space"
},
"jobresultcode": 530,
"jobresulttype": "object",
"jobstatus": 2,
"userid": "cdd4db33-9862-11ed-8965-1e00dc0000f6"
}
🙈 Error: …
```
> Fix: memory leak on volume allocation

- api/src/main/java/com/cloud/network/NetworkService.java
- server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
- server/src/main/java/com/cloud/network/NetworkServiceImpl.java
- server/src/main/java/com/cloud/network/vpc/VpcManagerImpl.java
- server/src/test/java/com/cloud/network/NetworkServiceImplTest.java
- server/src/test/java/com/cloud/network/vpc/VpcManagerImplTest.java
- server/src/test/java/com/cloud/vpc/MockNetworkManagerImpl.java
During the creation of a VPC offering, any type of service offering can be informed. However, selecting an improper service offering type can lead to a VR boot failure. Furthermore, during VPC or network offering creation, it is possible to provide an inactive service offering. 
This PR allows the creation of VPC offerings only with VR service offerings, and blocks the creation of new VPC and network offerings with inactive service offerings. Any offering already created will maintain current behavior. 
I applied the changes in a local lab and attempted to create network offerings and VPC offerings with inactive service offerings. Additionally, I attempted to create VPC offerings with offerings in which the System VM type is not `domainrouter`. All attempts failed.
Attempts where the …
> Allow VPC offering creation only with active VR service offerings 

- ui/src/views/network/VpcTiersTab.vue
This PR fixes an UI bug that zoneid/networkid is missing when add a instance from vpc network.
This is a regression of vue3 upgrade.
> UI: fix missing networkid and zoneid when add instance from vpc network

- server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
This PR fixes two issues including #7139 
(1) if vm is created with specific rootdisksize, resize datadisk will update the user vm details for rootdisksize
(2) if vm is not created with specific rootdisksize, resize rootdisk will not add user vm details for new rootdisksize, which causes #7139 
(1) create vm with root disk size=10 GB, datadisk =5 GB, check user_vm_details
```
| 4129 |   433 | rootdisksize          | 10    |       1 |
```
Prior to this change, when resize data disk to 6GB
```
| 4133 |   433 | rootdisksize                       | 6     |       1 |
```
with this change, detail is NOT changed when resize data disk.
(2) create vm without specific root disk size. resize root disk to 11GB, 
Prior to this change, there is NO details for new root disk size
with this change, 
```
| …
```
> server: add/update user vm details for new root disk size (issue 7139)

- plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterActionWorker.java
- plugins/integrations/kubernetes-service/src/main/resources/script/deploy-cloudstack-secret
Fixes https://github.com/apache/cloudstack/issues/6987
When a CKS cluster is created in a project, the project-id is now passed as part of the cloud-config used in the cloud provider
When a cluster is created in a project
```
kubectl --kubeconfig kube.conf get secrets -n kube-system cloudstack-secret -o json | jq '.data."cloud-config"' | tr -d '"' | base64 -d
[Global]
api-url = http://xxxxxxxxx:8080/client/api
api-key = xxxxxxxxxxxxxxx
secret-key = xxxxxxxxxxxxxxxxxxxxx
project-id = xxxxxxxxxxxxxxxxx
kubectl --kubeconfig kube.conf -n ingress-nginx get services -o wide -w ingress-nginx-controller
NAME                       TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)                      AGE     SELECTOR
ingress-nginx-controller   LoadBalancer   10.99.51.184   xxxxxxxxxx …
```
> cks: Fix provider deployment when cluster is in a project

- plugins/database/quota/src/main/java/org/apache/cloudstack/api/command/QuotaTariffCreateCmd.java
- plugins/database/quota/src/main/java/org/apache/cloudstack/api/command/QuotaTariffDeleteCmd.java
- plugins/database/quota/src/main/java/org/apache/cloudstack/api/command/QuotaTariffListCmd.java
- plugins/database/quota/src/main/java/org/apache/cloudstack/api/command/QuotaTariffUpdateCmd.java
PR #5909 was created during the release 4.17.0.0 and the parameter `since` in APIs was written as `4.17.0.0`; however, #5909 was really introduced only in 4.18.0.0.
This PR intends to adjust the `since` in the introduced APIs and parameters and also:
- improve the parameters documentation;
- adjust parameters length, according to the field in the database;
- rename parameter `UUID` of `quotaTariffDelete` to `ID`, to follow the pattern we use along other APIs;
- cleanup some unused/unnecessary code in the Cmd classes;
I retested the whole tariff CRUD, as follows:
<details><summary>Creating a tariff</summary>
```
(lab)  > quota tariffcreate name='test-aadjusts' usagetype=12 value=0 description="a long description that will describe the tariff's purpose | a long description that will …
```
> Adjusts/fixes in quota tariff APIs

- api/src/main/java/org/apache/cloudstack/usage/UsageUnitTypes.java
- engine/schema/src/main/resources/META-INF/db/schema-41720to41800.sql
- framework/quota/src/main/java/org/apache/cloudstack/quota/QuotaManagerImpl.java
- framework/quota/src/main/java/org/apache/cloudstack/quota/constant/QuotaTypes.java
- framework/quota/src/test/java/org/apache/cloudstack/quota/QuotaManagerImplTest.java
Currently, the quota plugin ignores the tariff calculation for the types below:
* VM_DISK_IO_READ
* VM_DISK_IO_WRITE
* VM_DISK_BYTES_READ
* VM_DISK_BYTES_WRITE
The code was changed as to now calculate the quota tariff for these types. Moreover, the unit types were changed as well, as shown in the table below. It is noteworthy that the raw values for these types are not modified; therefore, the calculation of the tariff for them are: `TARIFF * CONSUMPTION`.
| Type | Unit |
| ------ | ------ |
| VM_DISK_IO_READ | IOPS |
| VM_DISK_IO_WRITE | IOPS |
| VM_DISK_BYTES_READ | Bytes |
| VM_DISK_BYTES_WRITE | Bytes |
This was tested in a local lab creating a quota tariff for each type. Then, I reinstalled a previously created VM and generated a quota statement.
Creating a quota tariff with type …
> Quota VM_DISK tariff calculation

- engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
- engine/orchestration/src/test/java/com/cloud/vm/VirtualMachineManagerImplTest.java
- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
- server/src/main/java/org/apache/cloudstack/network/router/deployment/RouterDeploymentDefinition.java
- server/src/test/java/com/cloud/vm/UserVmManagerImplTest.java
This PR fixes #6740 
The deleted service offering is not removed , but changed to Inactive state.
Therefore the state needs to be checked when deploy/create new vm or upgrade vm.
Similar check is added to router service offering as well.
```
(localcloud) 🐱 > deploy virtualmachine zoneid=7c9769a1-ba70-4f3a-a976-5a6ae7d946bb templateid=936f5eda-6be2-11ed-a030-1e0066000350 networkids=e7d3308c-03fc-4411-998d-ff45a2c1fccc  serviceofferingid=c1ebd091-57a6-427a-99a9-6c482de84a4f
{
...
}
}
(localcloud) 🐱 > delete serviceoffering id=c1ebd091-57a6-427a-99a9-6c482de84a4f
{
"success": true
}
(localcloud) 🐱 > deploy virtualmachine zoneid=7c9769a1-ba70-4f3a-a976-5a6ae7d946bb templateid=936f5eda-6be2-11ed-a030-1e0066000350 …
```
> server: do not deploy or upgrade vm with inactive service offering

- api/src/main/java/org/apache/cloudstack/api/command/user/network/CreateNetworkCmd.java
- api/src/test/java/org/apache/cloudstack/api/command/user/network/CreateNetworkCmdTest.java
- test/integration/smoke/test_create_network.py
- ui/src/views/network/CreateIsolatedNetworkForm.vue
- ui/src/views/network/CreateL2NetworkForm.vue
- ui/src/views/network/CreateSharedNetworkForm.vue
This is a improvement change to make displayText field optional for createNetwork as mentioned in issue #6855.
> Make displayText in createNetwork optional

- tools/docker/README.md
This PR updates the README.md file in directory tools/docker/
We should use the offical docker image for Apache Cloudstack simulator https://hub.docker.com/r/apache/cloudstack-simulator
The community build of the simulator https://registry.hub.docker.com/r/cloudstack/simulator/tags  is showing as 4 years old.
The offical docker image from Apache contains the latest build and is having the tags as well for a particular builds
❯ docker search --format "{{.Name}}: {{.StarCount}}" apache/cloudstack
apache/cloudstack-cloudmonkey: 0
apache/cloudstack-kubernetes-autoscaler: 0
apache/cloudstack-kubernetes-provider: 0
apache/cloudstack-primate: 0
apache/cloudstack-ec2stack: 0
apache/cloudstack-simulator: 0
❯ docker search --format "{{.Name}}: {{.StarCount}}" cloudstack/
cloudstack/simulator: 14 …
> Added steps to get the offical docker image for cloudstack simulator

- server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
This PR fixes #7165 
old:
```
(localcloud) 🐱 > list users keyword=ADMIN
🙈 Error: (HTTP 530, error code 4250) Caught: com.mysql.cj.jdbc.ClientPreparedStatement: SELECT user_view.id, user_view.uuid, user_view.username, user_view.password, user_view.firstname, user_view.lastname, user_view.email, user_view.state, user_view.api_key, user_view.secret_key, user_view.created, user_view.removed, user_view.timezone, user_view.registration_token, user_view.is_registered, user_view.incorrect_login_attempts, user_view.account_id, user_view.account_uuid, user_view.account_name, user_view.account_type, user_view.account_role_id, user_view.domain_id, user_view.domain_uuid, user_view.domain_name, user_view.domain_path, user_view.job_id, user_view.job_uuid, user_view.job_status, user_view.default, …
```
> server: fix exception while list users with keyword

- scripts/vm/hypervisor/versions.sh
On Oracle Linux 9.0, version shows as undefined and even Host.OS shows as "Red". This change fixes the script to use `/etc/os-release` ins such cases.
Before change
After changer, after re-adding the host
Before changes,
```
[root@ref-trl-4390-k-Mol9-abhishek-kumar-kvm1 ~]# /usr/share/cloudstack-common/scripts/vm/hypervisor/versions.sh
Host.OS=Red
Host.OS.Version=
Host.OS.Kernel.Version=5.15.0-1.43.4.1.el9uek.x86_64
```
After change,
```
[root@ref-trl-4390-k-Mol9-abhishek-kumar-kvm1 ~]# /usr/share/cloudstack-common/scripts/vm/hypervisor/versions.sh
Host.OS=Oracle Linux Server
Host.OS.Version=9.0
Host.OS.Kernel.Version=5.15.0-1.43.4.1.el9uek.x86_64
```
> scripts: fix kvm host undefined version

- ui/src/views/infra/zone/ZoneWizard.vue
Fixes #7194
https://user-images.githubusercontent.com/153340/218449970-d2df73be-c284-4ffa-bb48-1dce8af1d149.mp4
> ui: fix add zone dialog for fix errors

- ui/public/locales/en.json
- ui/src/views/infra/zone/IpAddressRangeForm.vue
> UI: fix 'Next' button is stuck if no public ip range

- test/integration/smoke/test_deploy_vm_extra_config_data.py
- test/integration/smoke/test_vm_deployment_planner.py
- tools/marvin/marvin/lib/base.py
> integration test fixes for 4.18

- services/console-proxy/server/src/main/java/com/cloud/consoleproxy/vnc/NoVncClient.java
- services/console-proxy/server/src/main/java/com/cloud/consoleproxy/vnc/RfbConstants.java
This PR fixes the console access on XCPng/XenServer observed on the 4.18 RC1 (fixing the RFB protocol version for tunnel connection after PR #7015 was merged) 
View any VM console
> Fix console access on XCPng/Xen

- engine/schema/src/main/resources/META-INF/db/schema-41720to41800.sql
On centos7 with mysql 5.5, it looks good
```
MariaDB [cloud]> CALL `cloud`.`IDEMPOTENT_ADD_FOREIGN_KEY`('cloud.volumes', 'passphrase', 'id');
Query OK, 0 rows affected, 2 warnings (0.03 sec)
MariaDB [cloud]> CALL `cloud`.`IDEMPOTENT_ADD_FOREIGN_KEY`('cloud.volumes', 'passphrase', 'id');
Query OK, 0 rows affected, 2 warnings (0.02 sec)
```
However, it throws an error on ubuntu 22 or rocky8, with mariadb 8
```
mysql> CALL `cloud`.`IDEMPOTENT_ADD_FOREIGN_KEY`('cloud.volumes', 'passphrase', 'id');
ERROR 1826 (HY000): Duplicate foreign key constraint name 'fk_passphrase_id'
mysql> CALL `cloud`.`IDEMPOTENT_ADD_FOREIGN_KEY`('cloud.volumes', 'passphrase', 'id');
ERROR 1826 (HY000): Duplicate foreign key constraint name 'fk_passphrase_id'
```
With this PR, everything looks good
```
mysql> CALL …
```
> engine/schema: fix IDEMPOTENT_ADD_FOREIGN_KEY procedure does not work on mysql8

- ui/src/views/offering/AddComputeOffering.vue
This PR allows domain admins to create service offerings, allowing them to select the domain when creating the service offering
Fixes: #7259 
The domain admins have the option to select the domain on the service offering creation
Login as domain admin, create service offering
> UI: Fix domain admins cannot create service offerings

- engine/schema/src/main/resources/META-INF/db/schema-41720to41800.sql
This PR fixes the issue of user_data table sql queries to use procedures to avoid duplicates
> Userdata MySQL changes to use procedures to avoid duplicates

- ui/src/views/compute/DeployVM.vue
This PR fixes the Default option for Pod, Cluster and Hosts on the VM deployment wizard
Fixes: #7204 
Deploy Instance wizard, select a host, then click Default. Same with Pod and Cluster
> Fix select default host option on deployment wizard

- engine/schema/src/main/resources/META-INF/db/schema-41720to41800.sql
> SQL: Remove snapshot references if primary storage pool has been removed

- plugins/database/quota/src/main/java/org/apache/cloudstack/api/response/QuotaResponseBuilderImpl.java
- plugins/database/quota/src/test/java/org/apache/cloudstack/api/response/QuotaResponseBuilderImplTest.java
This PR aims to fix a feature introduced in PR[#6690](https://github.com/apache/cloudstack/pull/6690). It was added the parameter `quotaenabled` to the response of the Quota Summary  API. However, this parameter was not set, and thus, always returned false. This PR fix this behavior, returning the correct value according to the configuration value.
This was tested in a local lab with user `dom01`  with the Quota plugin enabled and with user `dom02` with the plugin disabled. The image below presents the correct behavior for Quota summary response.
> Fix Quota plugin state on QuotaSummaryResponse

- core/src/main/resources/META-INF/cloudstack/core/spring-core-registry-core-context.xml
- server/src/main/java/com/cloud/user/AccountManagerImpl.java
This is related to the new improvement for 2FA in CloudStack #6924
In this PR we are changing the plugin related global setting names to be more relevant.
> Change 2FA plugin related global setting names

- engine/schema/src/main/java/com/cloud/upgrade/GuestOsMapper.java
- engine/schema/src/main/java/com/cloud/upgrade/dao/Upgrade41720to41800.java
This PR tries to avoid problems with guest os hypervisor mapping that we see in some DBs. If site specific entries were added the mapping may break on this.
> avoid hard coded guest OS IDs

- services/console-proxy/server/src/main/java/com/cloud/consoleproxy/ConsoleProxyNoVncClient.java
- services/console-proxy/server/src/main/java/com/cloud/consoleproxy/vnc/NoVncClient.java
This PR fixes the console access for Vmware 6.7 which offers SecurityType = 1 (None) - Reference: https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst#721none
The CPVM access uses the RFB protocol 3.8 since #7015 (previously it used version 3.3). From the link above:
````
Version 3.8 onwards
The protocol continues with the SecurityResult message.
Version 3.3 and 3.7
The protocol passes to the initialisation phase ([Initialisation Messages](https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst#initialisation-messages)).
````
This PR fixes the behavior of the security type None, continuing with the SecurityResult message instead of the Initialisation Phase as it was on version 3.3
Vmware 6.7 environment
Access any VM console before the fix -> Observe that the console is …
> Fix VNC SecurityType None on RFB v3.8

- api/src/main/java/com/cloud/agent/api/to/VirtualMachineTO.java
This PR turns logging off for the VNC password on VirtualMachineTO
> Don't log VNC password in VirtualMachineTO

- engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/VolumeOrchestrator.java
- engine/schema/src/main/java/org/apache/cloudstack/secret/PassphraseVO.java
- plugins/hypervisors/kvm/src/test/java/org/apache/cloudstack/utils/cryptsetup/CryptSetupTest.java
This PR fixes #7299 
This is proposed by @mlsorensen
> Move PassphraseVO to use String instead of byte[] to support Encrypt annotation

- scripts/util/keystore-cert-import
This PR fixes an issue on KVM environments where the user and group set on the /etc/libvirt/qemu.conf file is not root:root.
- A common user and group to be used is qemu:qemu. 
- This PR allows different user within the qemu group to access the certificates for the VNC TLS encryption on the VM console access
On KVM hosts, edit the /etc/libvirt/qemu.conf file and set user="qemu" and group="qemu", then restart the libvritd service. Try to deploy a new VM.
Before the fix -> ERROR: cannot access the certificates
> Fix VNC TLS for non-root linux users on the QEMU configuration

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/LibvirtStorageAdaptor.java
- plugins/hypervisors/ovm/src/main/java/com/cloud/ovm/hypervisor/OvmResourceBase.java
- plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java
- plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/XenServerConnectionPool.java
- server/src/main/java/com/cloud/alert/ConsoleProxyAlertAdapter.java
- server/src/main/java/com/cloud/alert/SecondaryStorageVmAlertAdapter.java
- server/src/main/java/com/cloud/api/ApiServer.java
- server/src/main/java/com/cloud/network/ExternalLoadBalancerDeviceManagerImpl.java
- server/src/main/java/com/cloud/servlet/ConsoleProxyServlet.java
- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
- server/src/main/java/org/apache/cloudstack/outofbandmanagement/OutOfBandManagementServiceImpl.java
- services/secondary-storage/server/src/main/java/org/apache/cloudstack/storage/resource/NfsSecondaryStorageResource.java
This PR fixes the [bugs and vulnerabilities](https://sonarcloud.io/summary/new_code?id=apache_cloudstack&pullRequest=7131) found by SonarCloud in PR https://github.com/apache/cloudstack/pull/7131.
> Fix PR 7131 bugs and vulnerabilities

- client/src/main/java/org/apache/cloudstack/ServerDaemon.java
This PR implements Jetty's hot certificate reload per https://github.com/eclipse/jetty.project/pull/5042
When the keystore changes, the API server begins using the new certificate. Note that this functionality doesn't support live change of keystore password, only certificate.
Tested locally with self-signed certs.  Changed the cert in the keystore while management server was running, reloaded the website, and inspected the https certificate.
Tested against `cmk`, which continued to function after the cert change.  Also tested against UI - website needed to be refreshed due to browser security. Perhaps a future enhancement would catch these errors and auto-refresh?
Here you can see the local cloudstack management server using a new cert after it is loaded into a keystore:
``` …
```
> Support Jetty's live cert reload on HTTPS frontend

- ui/src/views/compute/DeployVM.vue
This PR fixes a critical issue on UI that the default network is not passed to deployvm API, so the default network is always the first network.
This line was changed in #5080, but reverted in #5151
This issue exists in 4.17, 4.18 and main
workaround
- create a vm on default network (do not start it)
- add vm to other networks
- start the vm
> UI: fix default network is not passed to deployvm API

- server/src/main/java/com/cloud/deploy/DeploymentPlanningManagerImpl.java
This PR fixes the issue #7357 where VM deployment is failing when storage tags are used in certain way with multiple clusters, though a proper cluster to deploy VM is available.
Root cause is the usage of certain variables to figure out the final avoid pools set in the deployment planner.
because of this, "originalAvoidPoolSet" is getting updated whenever avoid.getPoolsToAvoid() is updated and this should not be the case.
> Fixed avoid set variables which is causing deployment failures

- test/integration/smoke/test_register_userdata.py
Adds smoke test for CRUD operations as a normal user
> test: add smoke test for user role for userdata crud api

- ui/public/locales/en.json
- ui/src/components/view/ActionButton.vue
- ui/src/components/view/InfoCard.vue
- ui/src/components/widgets/Console.vue
This PR adds a new button that allows the user to copy the VM console URL to the clipboard. VM consoles have a security mechanism that allows for a one-time use per URL (see #6577). Therefore, if the same URL is accessed again, an error message is displayed. When access to the console is requested via the UI button, a new tab is opened which automatically connects to the VM console.  However, for the purpose of obtaining only the URL for later use or sharing, it is more convenient to copy the URL rather than opening it directly in a new tab. The new button appears alongside the existing button that opens the console in a new tab
I conducted manual testing in a local lab environment. During the testing process, I clicked the new added button and then accessed the copied URL. This allowed …
> UI: Add button to copy VM console URL to clipboard

- plugins/user-authenticators/saml2/src/main/java/org/apache/cloudstack/api/command/SAML2LoginAPIAuthenticatorCmd.java
There are multiple ways in which a SAML response can be formatted, especially when encryption is enabled.  This PR removes the hardcoding of `EncryptedKeyResolver`= `InlineEncryptedKeyResolver` in favor of using a `ChainingEncryptedKeyResolver` which will try multiple resolvers. It preserves the `InlineEncryptedKeyResolver` as the first option but adds `EncryptedElementTypeEncryptedKeyResolver` to the chain of resolvers to try.
`ChainingEncryptedKeyResolver` is a bit finicky in that you can't provide it a list of resolvers, you can only fetch its internal list and add to it.
Theoretically we could add all of the resolver types to the chain, but for now just preserving the ones known to be in use.
Tested locally against an installed IDP that provides the `EncryptedElementType` of XML …
> Add EncryptedElementType key resolver to SAML plugin

- server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
- server/src/test/java/com/cloud/storage/VolumeApiServiceImplTest.java
This PR fixes the issue #7325 where root disk is not getting considered for resize in some cases of ScaleVM operation.
While Scaling VM if the compute offering has the root disk size change (for any type of compute offering whether it is normal/constrained/unconstrained) CS should do the resize operation.
We already have a check here (https://github.com/apache/cloudstack/blob/2149e82856f4f658dcec5200430a2ac175b07c91/server/src/main/java/com/cloud/vm/UserVmManagerImpl.java#L2102-L2108) whether to skip the disk offering change or not. So here in this PR I've removed the checks if the compute offering is customized or not which I think irrelavant for root disk resize.
> Fix ScaleVM to consider resize volume in any type of service offering

- ui/public/locales/en.json
- ui/src/config/section/plugin/quota.js
This PR fixes the description column output in the ui for the quota Tariff page
The following PR #5909 changed the response for the  quotaTariffList api call 
https://cloudstack.apache.org/api/apidocs-4.18/apis/quotaTariffList.html
In 4.17 the response for the quotaTariffList api call contains the "description" feild
```
<quotatariff>
<usageType>1</usageType>
<usageName>RUNNING_VM</usageName>
<usageUnit>Compute-Month</usageUnit>
<usageDiscriminator/>
<tariffValue>0.00000</tariffValue>
<effectiveDate>2010-05-04T00:00:00+0000</effectiveDate>
<description>Running Vm Usage</description>
<currency>$</currency>
</quotatariff>
```
Screenshot
In 4.18 the response for the quotaTariffList api call contains the "usageTypeDescription" field due to that there is no response in the Description coloumn …
> Fixed the Description coloumn in the UI for Quota traffic page

- ui/src/views/AutogenView.vue
> ui: allow clearing dns during zone update

- engine/storage/src/main/java/org/apache/cloudstack/storage/image/db/TemplateDataStoreDaoImpl.java
- engine/storage/src/test/java/org/apache/cloudstack/storage/image/db/TemplateDataStoreDaoImplTest.java
This PR fixes an issue observed on multiple zones and direct download templates on KVM, in which a template gets multiple records on the `template_store_ref` table. When this happens, the template cannot be used as direct download. In case of a system VM template using direct download, system VM deployments fail
````
mysql> select id,store_id,template_id,created,download_state,state from template_store_ref where template_id=233 and state="Ready" and download_state="BYPASSED" and store_id is null;
+----+----------+-------------+---------------------+----------------+-------+
| id | store_id | template_id | created             | download_state | state |
+----+----------+-------------+---------------------+----------------+-------+
| 37 |     NULL |         233 | 2022-10-25 14:08:04 | …
```
> Fix for direct download templates with multiple bypassed references

- engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
This PR fixes the issue #7285 
Like the reproduction steps mentioned in the issue, applying VM userdata is failing when VR is in migrating state.
Root cause:
At the end of successful or unsuccessful VM migration, hypervisor host name is set on the Virtual Router or config drive.
When VR is in wrong state then applying userdata is failing but by then migration is successful and DB is updated.
Solution:
update hypervisor hostname only if the account.allow.expose.host.hostname and global.allow.expose.host.hostname are set to true and do not mark VM migration as failed as it is already successful.
> Set hypervisor hostname via userdata only when the global settings are allowed

- engine/schema/src/main/java/com/cloud/service/ServiceOfferingVO.java
- framework/quota/src/main/java/org/apache/cloudstack/quota/vo/ServiceOfferingVO.java
Fixes #7389
Steps
- Create a custom compute offering with `disk_offering_strictness=true`
- Deploy a VM using it
- Stop the VM
- Try to scale VM using UI
Without fix - all other supported offerings are listed UI
With fix - only those supported offerings are listed in UI which use the same disk offering as the current one
> server,engine-schema: fix listing service offering for vm scale

- debian/control
This PR supports cloudstack packaging on ubuntu 22.04
> debian/control: build packages on ubuntu 22.04

- api/src/main/java/org/apache/cloudstack/annotation/AnnotationService.java
- api/src/main/java/org/apache/cloudstack/api/ApiCommandResourceType.java
- api/src/main/java/org/apache/cloudstack/management/ManagementServerHost.java
- framework/cluster/src/main/java/com/cloud/cluster/ManagementServerHostVO.java
- server/src/main/java/org/apache/cloudstack/annotation/AnnotationManagerImpl.java
- test/integration/smoke/test_annotations.py
- tools/marvin/marvin/lib/common.py
- ui/src/components/view/AnnotationsTab.vue
- ui/src/config/section/infra/managementServers.js
This PR adds support for annotations to be added for the management server as a resource/type.
As an operator I want to be able to leave a comment for my colleagues concerning one of the management servers in our system. (i.E. an annotation needs to be enabled for mshosts)
Added support in UI/API to facilitate this.
> Allow admin/users to add comments to Management Servers

- server/src/main/java/com/cloud/network/NetworkServiceImpl.java
> server: dedicate vxlan range to account

- .github/workflows/main-sonar-check.yml
- .github/workflows/sonar-check.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
> GitHub Workflows security hardening

- server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
- server/src/test/java/com/cloud/configuration/ConfigurationManagerImplTest.java
Fixes #6958
Using cmk passing valid and invalid IP range,
```
(local) 🍀 > list configurations name="remote.access.vpn.client.iprange"
{
"configuration": [
{
"category": "Network",
"component": "RemoteAccessVpnService",
"defaultvalue": "10.1.2.1-10.1.2.8",
"description": "The range of ips to be allocated to remote access vpn clients. The first ip in the range is used by the VPN server",
"displaytext": "Remote access vpn client iprange",
"group": "Miscellaneous",
"isdynamic": false,
"name": "remote.access.vpn.client.iprange",
"subgroup": "Others",
"type": "String",
"value": "10.1.2.1-10.1.2.8"
}
],
"count": 1
}
(local) 🐃 > update configuration name="remote.access.vpn.client.iprange" value="10.1.2.1-10.1.2"
🙈 Error: (HTTP 431, error code 4350) Invalid IP address value(s) specified for the …
```
> server: validate ip address value on update config

- ui/src/views/tools/ImportUnmanagedInstance.vue
Fixes #7420
Fixes CPU speed param value when using custom compute offering during VM import
https://user-images.githubusercontent.com/153340/231072144-f360de75-951d-4617-a3b6-a91b348cb0a2.mp4
> ui: fix custom offering cpuspeed during vm import

- core/src/main/java/com/cloud/agent/api/MigrateCommand.java
- core/src/main/java/org/apache/cloudstack/storage/to/TemplateObjectTO.java
- engine/storage/datamotion/src/main/java/org/apache/cloudstack/storage/motion/KvmNonManagedStorageDataMotionStrategy.java
- engine/storage/datamotion/src/main/java/org/apache/cloudstack/storage/motion/StorageSystemDataMotionStrategy.java
- engine/storage/datamotion/src/test/java/org/apache/cloudstack/storage/motion/KvmNonManagedStorageSystemDataMotionTest.java
- engine/storage/datamotion/src/test/java/org/apache/cloudstack/storage/motion/StorageSystemDataMotionStrategyTest.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtMigrateCommandWrapper.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtMigrateCommandWrapperTest.java
This PR fixes live local storage migration for VMs created with "Direct Download" images. 
Currently, the local storage driver has no special handling for direct download templates during live storage migration. The workflow is something like 1) check to see if root volume's backing template exists on destination primary storage 2) if not, then send a CopyCommand to copy template to destination storage 3) create new destination volume on destination primary storage against the backing template. 4) send destination volume info during MigrateCommand so we can rewrite the volume path in the VM XML during migration 5) migrate VM.  In step 2 - CopyCommand is not the right thing to do for putting a "Direct Download" template onto primary storage, it should instead be a type of …
> Support local storage live migration for direct download templates

- systemvm/agent/noVNC/core/rfb.js
This PR slows down the console paste text function in the console ever so slightly, adding 25ms between each character. It was found that when large text is pasted, say an SSH key or something over 100 characters, it would stop somewhere in the 100-200 character range, and if the last character was capitalized it would be stuck with left shift held down. 
In debugging, I ran noVNC locally with websockify against a Qemu VNC and took the whole console proxy out of the equation and was still able to reproduce it. I traced the websocket packets and we were clearly firing off all of the keypresses just fine, but the ones on the end were getting dropped VNC server side. It seems we are overloading a keyboard buffer, or something along those lines when we send all of the keypress messages at …
> Send console text slower to avoid overloading remote keyboard buffer

- agent/bindir/libvirtqemuhook.in
This PR checks that the NodeList returned from grabbing "source" element on a network interface actually returns items before trying to use the first element.
Not all network interface XML has a "source" field, so this would break qemu hooks from processing in some cases. The index out of bounds exception is silently swallowed, because I guess we don't want this to be fatal.
Ran a few different types of VM XML through the script via:
```
cat vm.xml | /etc/libvirt/hooks/qemu vm-name migrate begin -
```
Previously no output would be returned, with patch we get VM XML. Not sure if there is an existing test framework for these scripts to add some example XML to run through it at packaging/build time.
> Qemu migration hook: check for source length before using element 0

- server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
This PR fixes a null pointer edge case where a PowerFlex volume is attached to a VM.
In this edge case, a VM has been created, started, stopped, and then reimaged. VM has a last host ID but the newly attached volume does not yet have a storage pool assigned, it will be assigned on the VM start.  However, we assume that if the VM's host is not null, we need to try to revoke access to the volume for the host. Since there is no storage pool yet for the volume, we hit a null pointer when checking to see if the volume's pool is PowerFlex.
This was affecting all storage types, I could reproduce it with local storage, since the null pointer is at the check for pool's type.
Verified but was reproducible with a local storage dev environment. Applied patch and confirmed it fixed the issue.
> Fix null pointer on PowerFlex attach volume edge case

- server/src/main/java/org/apache/cloudstack/direct/download/DirectDownloadManagerImpl.java
This PR adjusts the DirectDownload certificate check initial delay. Since the time unit is in hours, I think it was a mistake to schedule the initial check to be in 60 hours after management servers start - the intention was likely 60 seconds.  We had turned this feature on to run hourly, not realizing we would have to wait 2.5 days to see it first run!
> Fix direct download certificate check initial delay

- test/integration/component/test_configdrive.py
- test/integration/component/test_deploy_vm_userdata_multi_nic.py
- test/integration/component/test_deploy_vm_userdata_reg.py
- tools/marvin/marvin/cloudstackConnection.py
- tools/ngui/requester.py
> python 3.9 comptibility fixes

- systemvm/debian/opt/cloud/bin/cs/CsHelper.py
- systemvm/debian/opt/cloud/bin/cs/CsRedundant.py
- systemvm/debian/opt/cloud/bin/setup/common.sh
This PR fixes #6702 
The service `conntrackd` will be started by the script `/opt/cloud/bin/cs/CsRedundant.py`, therefore add it to disabled_svcs so it is not started automatically when VR is started.
> VR: do not restart conntrackd if no guest networks 

- api/src/main/java/org/apache/cloudstack/api/command/user/vm/DeployVMCmd.java
- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
Fixes #6697
Allows the server to generate started and completed events for VM.CREATE event type when VM is deployed with startvm=false.
https://user-images.githubusercontent.com/153340/231080758-4de924a6-f7c1-4eb3-bbcb-db9030b3fa58.mp4
Without fix (tested deplovm with and without start. VM.CREATE is not published as completed when startvm=false):
```
(local) 🦇 > deploy virtualmachine zoneid=104ca6f0-0a0f-4be7-ab4d-2ce1e091bb54 templateid=9f4b9f63-ed72-11ed-a4b9-645d8651f45a serviceofferingid=fca539e1-5b51-4b2f-a162-19a0594ca1fc name=no-fix-start
{
"bootmode": "legacy",
"boottype": "Bios",
"created": "2023-05-08T13:26:12+0530",
"details": {},
"displayname": "no-fix-start",
"displayvm": true, …
```
> api,server: fix VM.CREATE events on vm deploy without start

- engine/schema/src/main/java/org/apache/cloudstack/reservation/dao/ReservationDaoImpl.java
- server/src/main/java/com/cloud/resourcelimit/ResourceLimitManagerImpl.java
In troubleshooting ops issues we see logs like:
Maximum domain resource limits of Type 'user_vm' for Domain Id = 763 is exceeded: Domain Resource Limit = (1 bytes) 1, Current Domain Resource Amount = (0 bytes) 0, Requested Resource Amount = (1 bytes) 1."
However there is one missing value (currentResourceReservation) that is used in the calculation of limit check but it is not logged, which leads to confusion. Above we see we are using “0” and requested 1, with our limit being 1, but was rejected. Without logging all the values used in the calculation we don’t understand why it failed.
Additionally, if we had this log above it would be clearer that a second bug is occurring. When we query for domain level resource reservations in “getDomainReservation” the actual SearchBuilder is the …
> increase log detail for limit checking, fix getDomainReservation()

- engine/storage/image/src/main/java/org/apache/cloudstack/storage/image/TemplateServiceImpl.java
- engine/storage/image/src/test/java/org/apache/cloudstack/storage/image/TemplateServiceImplTest.java
Fixes #7342
When MS is restarted, failed non-public, non-featured, user templates are set to Active as their redownload is not attempted. This PR fixes the case.
> engine-storage: fix errored template becomes active

- ui/.env.primate-qa
- ui/src/components/view/InfoCard.vue
- ui/src/config/router.js
- ui/src/config/section/offering.js
- ui/src/config/section/zone.js
- ui/src/utils/plugins.js
Show common information such as zone and offerings to users for their use with Terraform, CAPC etc. without having to use cmk for getting the IDs.
> ui: show zones and offerings to users

- server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
- server/src/test/java/com/cloud/storage/VolumeApiServiceImplTest.java
Fixes #7525 
CloudStack may not keep the VM associated to any host when there is offline migration across cluster or pod. In such cases, CloudStack should be able to send the AttachCommand or DetachCommand to any available host in the current VM cluster.
> server: fix volume detach operation when no vm host

- server/src/main/java/com/cloud/storage/StorageManagerImpl.java
VolumeDao has been injected twice. This PR removes and refactors duplicate injection.
> refactor: remove duplicate inject

- engine/schema/src/main/java/com/cloud/vm/ConsoleSessionVO.java
- engine/schema/src/main/java/com/cloud/vm/dao/ConsoleSessionDaoImpl.java
This PR fixes the VM console display on the main branch
Fixes: #7550 
Before the fix:
````
2023-05-24 19:03:06,005 DEBUG [c.c.c.AgentHookBase] (AgentManager-Handler-8:null) (logid:) Acquiring session [cbc024b7-209a-4518-b582-7cc45272a29b] as it was just used.
2023-05-24 19:03:06,007 DEBUG [c.c.u.d.T.Transaction] (AgentManager-Handler-8:null) (logid:) Rolling back the transaction: Time = 1 Name =  -ClusteredAgentManagerImpl$ClusteredAgentHandler.doTask:624-Task.call:83-Task.call:29-FutureTask.run:264-ThreadPoolExecutor.runWorker:1128-ThreadPoolExecutor$Worker.run:628-Thread.run:829; called by -TransactionLegacy.rollback:888-TransactionLegacy.removeUpTo:831-TransactionLegacy.close:655-TransactionContextInterceptor.invoke:36-ReflectiveMethodInvocation.proceed:175-ExposeInvocationInterceptor.i …
```
> Fix acquire console session issue

- plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java
- plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterResourceModifierActionWorker.java
- plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterScaleWorker.java
- plugins/integrations/kubernetes-service/src/test/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImplTest.java
- ui/src/config/section/compute.js
- ui/src/views/compute/ScaleKubernetesCluster.vue
Fixes #7454
- Allows changing compute offering for a stopped cluster
- Allows compute offering change when the cluster has autoscaling enabled
Using cmk:
Service offerings:
```
(localcloud) 🐱 > list serviceofferings id=5b9471db-0f98-4ad4-8e27-d31935c1d5fe 
{
"count": 1,
{
"cacheMode": "none",
"cpunumber": 2,
"created": "2023-05-22T08:22:32+0000",
"displaytext": "CKS Instance",
"encryptroot": false,
"id": "5b9471db-0f98-4ad4-8e27-d31935c1d5fe",
"iscustomized": false,
"memory": 2048,
"name": "CKS Instance",
"offerha": false,
"provisioningtype": "thin",
"rootdisksize": 0, …
```
> cks,ui: allow changing stopped cluster offering, improvements

- api/src/test/java/org/apache/cloudstack/api/command/user/network/CreateNetworkCmdTest.java
- api/src/test/java/org/apache/cloudstack/api/command/user/network/UpdateNetworkCmdTest.java
- plugins/affinity-group-processors/non-strict-host-affinity/src/test/java/org/apache/cloudstack/affinity/NonStrictHostAffinityProcessorTest.java
JaCoCo used for code coverage calculation in the project doesn't support PowerMockito classes. This PR attemps to reduce usage of PowerMockito.
> test: reduce PowerMock usage for code coverage

- services/secondary-storage/server/src/main/java/org/apache/cloudstack/storage/resource/NfsSecondaryStorageResource.java
- services/secondary-storage/server/src/test/java/org/apache/cloudstack/storage/resource/NfsSecondaryStorageResourceTest.java
Fixes #7516
When a backed-up snapshot is deleted and the snapshot file is present in the same name directory (probably only for VMware), the whole directory can be deleted.
**Tested deleting a backedup volume snapshot on VMware**
Logs:
```
2023-05-12 09:45:49,879 DEBUG [cloud.agent.Agent] (agentRequest-Handler-4:null) Request:Seq 5-731553464470994956:  { Cmd , MgmtId: 32988117074588, via: 5, Ver: v1, Flags: 100011, [{"org.apache.cloudstack.storage.command.DeleteCommand":{"data":{"org.apache.cloudstack.storage.to.SnapshotObjectTO":{"path":"snapshots/2/10/900f3dd1-5be2-4036-ae08-b93548d9e5c8/900f3dd1-5be2-4036-ae08-b93548d9e5c8","volume":{"uuid":"56730834-50ec-45be-b1e0-2040a271a1c3","volumeType":"ROOT","dataStore":{"org.apache.cloudstack.storage.to.PrimaryDataStoreTO":{"uuid":"e13a6bdb-50ff …
```
> secondary-storage: delete backedup snapshot dir on delete

- plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageProcessor.java
This PR may fix #7148 , solidfire users are requested to test it.
> vmware: do not create vm datastore when attach an existing volume on solidfire

- server/src/main/java/com/cloud/storage/StorageManagerImpl.java
- server/src/test/java/com/cloud/storage/StorageManagerImplTest.java
Storage GC deletes volumes that are in Destroy state. This PR adds a check in this action that is if two volume records (one in Destroy state and one in Ready state) point to exactly the same disk file then skip doing GC on such Destroy state volume record.
> server: improve storage GC to skip expunging possible duplicate volumes

- test/integration/smoke/test_vpc_vpn.py
- tools/marvin/marvin/config/test_data.py
This PR moves the test_data from the specific test to the central location - test_data.py and also changes the network cidr from 10.1.0.0/16 to 10.2.0.0/16 as it conflicts with the IP range of the lab where trillian jobs runs - thus leading to failures, which could be confusing
```
est Site 2 Site VPN Across redundant VPCs ... === TestName: test_01_redundant_vpc_site2site_vpn | Status : SUCCESS ===
ok
Test Site 2 Site VPN Across VPCs ... === TestName: test_01_vpc_site2site_vpn_multiple_options | Status : SUCCESS ===
ok
Test Remote Access VPN in VPC ... === TestName: test_01_vpc_remote_access_vpn | Status : SUCCESS ===
ok
Test Site 2 Site VPN Across VPCs ... === TestName: test_01_vpc_site2site_vpn | Status : SUCCESS ===
ok
-------------------------------------------------------------------- …
```
> Refactor test and change IP range

- tools/marvin/marvin/config/test_data.py
PR #6512 seems to have broken the `test_data.py`. This PR reverts test_data to the previous commit and adds only the new keys from the PR.
Verified there are no issues with parsing,
```
shwstppr@shwstppr-ThinkPad:~/lab/shapeblue/cloudstack|fix-test-data
⇒  sudo cp /home/shwstppr/lab/shapeblue/cloudstack/tools/marvin/marvin/config/test_data.py /usr/local/lib/python3.8/dist-packages/marvin/config/test_data.py                               
shwstppr@shwstppr-ThinkPad:~/lab/shapeblue/cloudstack|fix-test-data
⇒  nosetests --with-xunit --xunit-file=results.xml --with-marvin --marvin-config=./setup/dev/advanced.cfg -s -a tags=advanced --hypervisor=Simulator test/integration/smoke/test_vpc_vpn.py
=== Marvin Setting TestData …
```
> marvin: fix test_data for parsing failure

- pom.xml
- utils/src/test/java/com/cloud/utils/FileUtilTest.java
- utils/src/test/java/com/cloud/utils/TestProfiler.java
- utils/src/test/java/com/cloud/utils/UriUtilsParametrizedTest.java
- utils/src/test/java/com/cloud/utils/net/NetUtilsTest.java
- utils/src/test/java/com/cloud/utils/ssh/SshHelperTest.java
- utils/src/test/java/com/cloud/utils/validation/ChecksumUtilTest.java
- utils/src/test/java/org/apache/cloudstack/utils/jsinterpreter/JsInterpreterTest.java
- utils/src/test/java/org/apache/cloudstack/utils/reflectiontostringbuilderutils/ReflectionToStringBuilderUtilsTest.java
- utils/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
This PR upgrades the mockito version and removes powermockito from `utils` module.
Moving to Mockito to mock static methods (available since 3.4.0) instead of powermockito since it hasn't had any release since 2020 and is not compatible with newer versions of mockito.
I will create separate PRs for other modules overtime and eventually remove powermockito.
> Upgrade mockito

- plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterService.java
This change will allow CKS to be enabled by default on new installs. It should not affect the server or performance but would help to highlight k8s support in CloudStack.
> cks: enable by default

- server/src/main/java/com/cloud/hypervisor/kvm/discoverer/LibvirtServerDiscoverer.java
> [AGENT] host os accepted if only the first word is defined for the cluster

- utils/src/main/java/com/cloud/utils/UriUtils.java
> utils: fix check for metalink url

- agent/src/test/java/com/cloud/agent/AgentShellTest.java
- agent/src/test/java/com/cloud/agent/properties/AgentPropertiesFileHandlerTest.java
- agent/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
This PR removes usage of powermock from agent's tests.
After this change, this is the remaining usage of powermock left.
```bash
$ git grep "PowerMockito" | tr "/" " "| awk '{print $1, $2, $3, $4}' | sort | uniq -c 
76 api src test java
51 core src test java
37 engine schema src test
68 engine storage configdrive src
9 engine storage snapshot src
11 plugins acl project-role-based src
3 plugins database quota src
150 plugins hypervisors kvm src
3 plugins hypervisors vmware src
40 plugins hypervisors xenserver src
5 plugins integrations kubernetes-service src
2 plugins network-elements nicira-nvp src
96 plugins network-elements tungsten src
1 plugins storage volume storpool
17 plugins user-authenticators ldap src
196 server src test java
4 services console-proxy server src
2 services …
```
> agent: remove powermock from tests

- systemvm/debian/etc/logrotate.d/haproxy
This PR fixes #7576
Change tested by modifiying the logrotation config directly on the SystemVM
> Fix haproxy log rotation in VR system VM

- engine/api/src/main/java/com/cloud/vm/VirtualMachineManager.java
- engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
- engine/orchestration/src/test/java/com/cloud/vm/VirtualMachineManagerImplTest.java
- plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/guru/VMwareGuru.java
- plugins/hypervisors/vmware/src/test/java/com/cloud/hypervisor/guru/VMwareGuruTest.java
This PR enables the hypervisor strategy for VM migration when a VM is to be started in a different cluster for VMware.
> engine-orchestration,vmware: hypervisor migration during start vm migration

- ui/src/components/header/UserMenu.vue
This PR is related to the issue #7056.
backgroundColor of user-menu-avatar was hardcoded to primary color value instead of accessing it from @primary-color in config.json file. 
This PR resolves #7056.
backgroundColor of user-menu-avatar was hardcoded to primary color value instead of accessing @primary-color in config.json file.
> Updated the code to access the primary color from config.json.

- server/src/main/java/com/cloud/network/element/ConfigDriveNetworkElement.java
This PR adds a check on host's status. Without this if the agent is not in Up or Connecting state, expunging of a VM fails.
1. Enable `vm.configdrive.force.host.cache.use` in `Global Configuration`.
2. Create a L2 network with config drive
3. Deploy  a vm with the L2 network created in previous step
4. Stop the vm and destroy vm (not expunge it)
5. Stop the cloudstack-agent on the VM's host
6. Expunge the vm
Fixes: #7428 
Setup an environment using mbx and following the steps above to reproduce it.
> Add check on host's status while deleting config drive on host cache

- engine/schema/src/main/java/com/cloud/storage/dao/VolumeDao.java
- engine/schema/src/main/java/com/cloud/storage/dao/VolumeDaoImpl.java
- server/src/main/java/com/cloud/resource/ResourceManagerImpl.java
- server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
- server/src/test/java/com/cloud/resource/ResourceManagerImplTest.java
- server/src/test/java/com/cloud/storage/VolumeApiServiceImplTest.java
This PR fixes the following:
- When destroying a local storage pool during host force deletion: then also destroy the volumes on the pool from DB
- When expunging a destroyed volume: check if the volume's storage pool exists (not removed). In case its removed, skip the volume removal from storage
- Create a local storage KVM zone
- Deploy a VM to local storage
- Force remove the host
- Delete the VM -> This succeeds but its volumes remain forever in "Destroy" (before the fix) -> After the fix: volumes are destroyed
> Fix: Volumes on lost local storage cannot be removed

- plugins/storage/image/default/pom.xml
- plugins/storage/image/sample/pom.xml
- plugins/storage/image/swift/pom.xml
- plugins/storage/volume/cloudbyte/pom.xml
- plugins/storage/volume/datera/pom.xml
- plugins/storage/volume/default/pom.xml
- plugins/storage/volume/default/src/test/java/org/apache/cloudstack/storage/datastore/lifecycle/CloudStackPrimaryDataStoreLifeCycleImplTest.java
- plugins/storage/volume/linstor/pom.xml
- plugins/storage/volume/nexenta/pom.xml
- plugins/storage/volume/nexenta/src/test/java/org/apache/cloudstack/storage/datastore/util/NexentaStorApplianceTest.java
- plugins/storage/volume/sample/pom.xml
- plugins/storage/volume/scaleio/src/test/java/org/apache/cloudstack/storage/datastore/lifecycle/ScaleIOPrimaryDataStoreLifeCycleTest.java
This PR fixes and disables skipTests for storage plugins
> Fix and enable tests for storage plugins

- api/src/main/java/com/cloud/storage/Storage.java
- engine/schema/src/main/java/com/cloud/host/dao/HostDao.java
- engine/schema/src/main/java/com/cloud/host/dao/HostDaoImpl.java
- plugins/storage/volume/storpool/README.md
- plugins/storage/volume/storpool/src/main/java/com/cloud/agent/api/storage/StorPoolSetVolumeEncryptionAnswer.java
- plugins/storage/volume/storpool/src/main/java/com/cloud/agent/api/storage/StorPoolSetVolumeEncryptionCommand.java
- plugins/storage/volume/storpool/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/StorPoolSetVolumeEncryptionCommandWrapper.java
- plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/datastore/driver/StorPoolPrimaryDataStoreDriver.java
- plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/motion/StorPoolDataMotionStrategy.java
- server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
- test/integration/plugins/storpool/TestEncryptedVolumes.py
- test/integration/plugins/storpool/sp_util.py
Support of volume encryption for the StorPool plugin
Supported Virtual machine operations:
- live migration of VM to another host
- virtual machine snapshots (group snapshots without memory)
- revert VM snapshot
- delete VM snapshot
Supported Volume operations:
- attach/detach volume
- live migrate volume between two StorPool primary storages
- volume snapshot
- delete snapshot
- revert snapshot
Environment: 
CS mgmt - Rocky Linux
2 KVM hypervisors - Rocky
Smoke and manual tests
> Volume encryption support for StorPool plug-in

- engine/schema/src/main/resources/META-INF/db/schema-41800to41810.sql
- plugins/network-elements/tungsten/src/main/java/org/apache/cloudstack/network/tungsten/api/command/ConfigTungstenFabricServiceCmd.java
> Tungsten: change conserve_mode of default network offering to 0

- plugins/acl/project-role-based/src/test/java/org/apache/cloudstack/acl/ProjectRoleBasedApiAccessCheckerTest.java
- plugins/acl/project-role-based/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
- plugins/user-authenticators/ldap/src/test/java/org/apache/cloudstack/api/command/LdapCreateAccountCmdTest.java
- plugins/user-authenticators/ldap/src/test/java/org/apache/cloudstack/api/command/LdapImportUsersCmdTest.java
- plugins/user-authenticators/ldap/src/test/java/org/apache/cloudstack/api/command/LdapListUsersCmdTest.java
- plugins/user-authenticators/ldap/src/test/java/org/apache/cloudstack/api/command/LinkAccountToLdapCmdTest.java
- plugins/user-authenticators/ldap/src/test/java/org/apache/cloudstack/api/command/LinkDomainToLdapCmdTest.java
- plugins/user-authenticators/ldap/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
This PR removes powermock from tests & fixes the path for tests of project-role-based plugin.
Pending powermock usage after this PR
```bash
git grep -i "PowerMockito" | tr "/" " "| awk '{print $1, $2, $3, $4, $5}' | sort | uniq -c       
76 api src test java org
51 core src test java com
37 engine schema src test java
68 engine storage configdrive src test
9 engine storage snapshot src test
3 plugins database quota src test
150 plugins hypervisors kvm src test
3 plugins hypervisors vmware src test
40 plugins hypervisors xenserver src test
5 plugins integrations kubernetes-service src test
2 plugins network-elements nicira-nvp src test
96 plugins network-elements tungsten src test
1 plugins storage volume storpool src
194 server src test java com
2 server src test java org
4 services …
```
> Remove powermock from ldap & project-role-based plugin

- ui/src/views/compute/wizard/MultiNetworkSelection.vue
Fixes #7578 
L2 networks created using offerings that allow using custom VLAN can remain in Setup state. Allow importing of VMs with such networks when VLAN matches with unmanaged instances.
Using UI
Network:
Before fix:
After fix:
> ui: fix vm import for L2 n/w in Setup state

- api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
- api/src/main/java/org/apache/cloudstack/api/BaseListRetrieveOnlyResourceCountCmd.java
- api/src/main/java/org/apache/cloudstack/api/command/user/address/ListPublicIpAddressesCmd.java
- api/src/main/java/org/apache/cloudstack/api/command/user/network/ListNetworksCmd.java
- api/src/main/java/org/apache/cloudstack/api/command/user/vm/ListVMsCmd.java
- api/src/main/java/org/apache/cloudstack/api/command/user/volume/ListVolumesCmd.java
- server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
- ui/src/views/dashboard/UsageDashboard.vue
The user's dashboard presents the user's amount of running VMs, stopped VMs, total VMs, volumes, networks, and public IP addresses. The APIs `listVirtualMachines`, `listVolumes`, `listNetworks`, and `listPublicIpAddresses` process and return the whole data, which can be slow when dealing with a great number of resources. However, for the user's dashboard context, we just need the count of resources.
This PR intends to create a new parameter (`retrieveonlyresourcecount`) in those APIs to skip the data processing and return only the resource count.
I created several VMs in my environment, logged in with a domain admin, and observed how much time the dashboard was taking to completely load. Before the changes, it was taking more than 30 seconds to load and the time would increase according …
> Retrieve only resource count on user dashboard

- api/src/main/java/org/apache/cloudstack/api/command/user/volume/ResizeVolumeCmd.java
- server/src/main/java/com/cloud/api/ApiAsyncJobDispatcher.java
This PR resource throws exception with the correct error code and logs the error message when a resource allocation failure is encountered during resize volume operation.
> api: correct error on resize volume resource allocation failure

- plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/provider/ScaleIOHostListener.java
This PR fixes an intermittent issue where SDC id (local_path) is getting deleted and not getting populated when host connects back again.
Fix is to remove the code to delete the records from storage_pool_host_ref table. We are anyways updating the entry if the SDC ID is changed during agent restart which is anyways required inorder to get the new connections. I've quickly verified the host delete scenario to check the storage_pool_host_ref entries behavior, entries are getting deleted.
> Fix ScaleIO/Powerflex SDC id deletion on host disconnect

- engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/VolumeOrchestrator.java
- engine/orchestration/src/test/java/org/apache/cloudstack/engine/orchestration/VolumeOrchestratorTest.java
Fixes case of account/domain having negative storage count when there is a volume size difference while deploying volumes on certain stroages. In case of Powerflex volume size results in a multiple of 8. If user deploys a volume of 12GB it will result in 16GB in size. But currently CloudStack will not update resource count after deployment.
> engine-orchestration: fix volume size resource count mismatch

- server/src/main/java/com/cloud/resourcelimit/ResourceLimitManagerImpl.java
Added try/catch to log the issue, continue processing of the next resources and running again according to the schedule.
Tested manually
> If ResourceCountCheckTask throws an exception the scheduled task is not going to run again until the management servers are restarted.

- server/src/main/java/com/cloud/template/HypervisorTemplateAdapter.java
- server/src/test/java/com/cloud/template/HypervisorTemplateAdapterTest.java
This PR fixes the error while deleting a direct-download template when there is no secondary storage added (probably only in Edge zones).
> server: do not check zone imagestores for directdownload template delete

- server/src/main/java/com/cloud/servlet/ConsoleProxyPasswordBasedEncryptor.java
- services/console-proxy/server/src/main/java/com/cloud/consoleproxy/ConsoleProxyPasswordBasedEncryptor.java
- utils/src/main/java/com/cloud/utils/crypt/AeadBase64Encryptor.java
This PR fixes #4694
key will be used as password of AeadBase64Encryptor
iv will be used as aad of AeadBase64Encryptor
This need testing, at least:
- patch systemvm (cpvm)
- recreate systenvm (destroy and then recreate automatically)
> console proxy: use AeadBase64Encryptor instead of AES/CBC/PKCS5Padding

- engine/schema/src/main/java/com/cloud/upgrade/dao/DatabaseAccessObject.java
- engine/schema/src/main/java/com/cloud/upgrade/dao/DbUpgradeUtils.java
- engine/schema/src/main/java/com/cloud/upgrade/dao/Upgrade41800to41810.java
- engine/schema/src/main/resources/META-INF/db/schema-41720to41800.sql
- engine/schema/src/main/resources/META-INF/db/schema-41800to41810.sql
This PR fixes #7370 where same foreign key names are used for multiple tables which causes issues with different MySQL versions.
I've updated the procedure to be more precise and altered the problematic foreign keys in upgrade files. This way we can log the errors and resume the upgrade. 
Also removed the mysql statements related to foreign key procedure creation and usage from 4.18.0 schema files (those are moved to 4.18.1 java upgrade files) to avoid errors caused in #7370 for certain MySQL versions.
> Fix foreign key constraints and the mysql procedure that is used

- core/src/main/java/com/cloud/storage/JavaStorageLayer.java
- core/src/test/java/com/cloud/storage/JavaStorageLayerTest.java
This PR addresses a static analysis concern with temp file creation. It is not a security issue but an improvement nonetheless.
unit test added
> use `Files.createTempDirectory()` instead of `new File()`

- engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
When deploying a VM is failed during the allocation process it may leave the resources that have been already allocated before the failure. They will get removed from the database as the whole code block is wrapped inside a transaction twice but the server would not inform the network or storage plugins to clean up the allocated resources. This PR removes Transactions during VM allocation which results in the allocated VM and its resource records being persisted in DB even during failures. When failure is encountered VM is moved to Error state. This helps VM and its resources to be properly deallocated when it is expunged either by a server task such as ExpungeTask or during manual expunge.
> server,engine-orchestration: allocate vm without transaction

- core/src/main/java/com/cloud/agent/api/GetUnmanagedInstancesCommand.java
- plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java
Currently, ACS can continue to show an imported instance/VM as an unmanaged instance if the name and internalCSName (custom attribute, cloud.vm.internal.name) is different for the instance/VM on vCenter. This PR while filtering managed instances from the instance list received from ESXi host also checks if the internal name for the instance is not in the managed instance names list.
> vmware: fix unmanaged instance listing when different name & internal CS name

- api/src/main/java/org/apache/cloudstack/api/command/user/network/CreateNetworkCmd.java
- api/src/test/java/org/apache/cloudstack/api/command/user/network/CreateNetworkCmdTest.java
- engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
- ui/src/views/network/CreateL2NetworkForm.vue
- ui/src/views/network/CreateNetwork.vue
Currently, it is not possible to create a raw L2 network within an advanced zone with security groups enabled.
It is expected that Cloudstack does not have any control over the security in an L2 network, by the definition itself of such network.
The fact that security groups are enabled or disabled should not be a blocker for L2 networks. Especially as these L2 can be useful when used as secondary networks (with no services) in a zone with existing shared networks protected by security groups.
This PR doesn't add a new feature per se, but rather prevent cloudstack from blocking the creation of L2 networks.
> Add L2 networks to Zones with SG

- test/integration/smoke/test_kubernetes_clusters.py
- test/integration/smoke/test_set_sourcenat.py
- Fixes k8s test failure on the simulator
- Fixes VPC testcase failures for `test_set_sourcenat.py`
> test: fix ci failures on main branch

- api/src/main/java/com/cloud/network/NetworkModel.java
- engine/orchestration/src/main/java/org/apache/cloudstack/engine/datacenter/entity/api/db/dao/EngineDataCenterDao.java
- engine/orchestration/src/main/java/org/apache/cloudstack/engine/datacenter/entity/api/db/dao/EngineDataCenterDaoImpl.java
- engine/schema/src/main/java/com/cloud/dc/dao/DataCenterDao.java
- engine/schema/src/main/java/com/cloud/dc/dao/DataCenterDaoImpl.java
- engine/schema/src/main/java/com/cloud/network/dao/NetworkDaoImpl.java
- engine/schema/src/main/java/com/cloud/vm/dao/NicDao.java
- engine/schema/src/main/java/com/cloud/vm/dao/NicDaoImpl.java
- framework/db/src/main/java/com/cloud/utils/db/SequenceFetcher.java
- plugins/hypervisors/hyperv/src/main/java/com/cloud/hypervisor/hyperv/guru/HypervGuru.java
- plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/guru/VmwareVmImplementer.java
- plugins/network-elements/netscaler/src/main/java/com/cloud/network/vm/NetScalerVMManagerImpl.java
- server/src/main/java/com/cloud/network/NetworkModelImpl.java
- server/src/main/java/com/cloud/network/guru/ControlNetworkGuru.java
This PR makes sure a new MAC is unique by
- using zone DB ID as default ZoneMacIdentifyer
- checking if the mac exists in the nics table
if the mac exists a new one will be generated untill a free one is found.
This is a fix that will not generate duplicate MAC addresses in the future and prevent duplicates if prior versions generated randon MACs before.
Fixes: #7633
The testing of this feature is dependend on randomly generated MAC addresses that are in the way when generating logicly deterministic. Any testing suggestions are appreciated.
> guarantee MAC uniqueness

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStoragePoolManager.java
This PR unpates the reflective construction of storage adaptors (initiated by #6794, but it does not solve it)
> new (java11) style storage construction

- core/src/main/java/com/cloud/storage/template/TemplateConstants.java
- services/secondary-storage/controller/src/main/java/org/apache/cloudstack/secondarystorage/SecondaryStorageManagerImpl.java
- systemvm/agent/scripts/ipfirewall.sh
This PR fixes #5678 
Normally SSVMs in multiple zones communicate via the public IPs.
In some cases, the public IPs are in the internal allowed sites. There are some routes in SSVMs which causes the communication to use the private IPs. We need to add the private IP of other SSVM to /var/www/html/copy/.htaccess if the public IP is in secstorage.allowed.internal.sites
Without this PR, SSVM contains only public IP of another SSVM
```
root@s-8-VM:~# cat /var/www/html/copy/.htaccess
Options -Indexes
order deny,allow
deny from all
allow from 10.0.17.55
```
With this PR, it has both private and public IP of another SSVM
```
root@s-8-VM:~# cat /var/www/html/copy/.htaccess
Options -Indexes
order deny,allow
deny from all
allow from 10.0.17.55
allow from 10.0.40.129
```
The SSVM has route to all …
> SSVM: 'allow from' private IP in other SSVMs if the public IP is in allowed internal sites cidrs

- api/src/main/java/org/apache/cloudstack/context/CallContext.java
- server/src/main/java/com/cloud/resourcelimit/CheckedReservation.java
- server/src/main/java/com/cloud/resourcelimit/ResourceLimitManagerImpl.java
This PR addresses rare cases of potential overlap of resource reservation and resource count. For different resource types there could be some delay between incrementing of the resource count and clearing of the earlier done reservation. This may result in failures when there are parallel deployments happening.
> server: clear resource reservation and increment resource count in a transaction

- server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
- server/src/test/java/com/cloud/storage/VolumeApiServiceImplTest.java
This PR fixes the regression which added the check to stop encrypted volume migration.
Fixed it now to allow encrypted volume migration for PowerFlex/Scaleio storage.
Tested on Powerflex storage and it is allowing encrypted volume migration.
> Allow encrypted volume migration for PowerFlex volumes

- ui/src/utils/plugins.js
- ui/src/views/compute/AutoScaleVmProfile.vue
- ui/src/views/compute/CreateAutoScaleVmGroup.vue
- ui/src/views/compute/DeployVM.vue
- ui/src/views/compute/EditVM.vue
- ui/src/views/compute/RegisterUserData.vue
- ui/src/views/compute/ResetUserData.vue
Fixes #7748
https://github.com/apache/cloudstack/assets/153340/7ab4e749-8840-4735-9975-522d980b7074
> ui: fix userdata base64 encoding

- test/integration/smoke/test_safe_shutdown.py
Smoke tests for test_safe_shutdown is failing and the management server doesn't come back up. This leads to all the remaining tests to get skipped.
This PR fixes that by restarting the management server on test's `tearDown`.
This PR...
> Fix smoketest: safe shutdown

- server/src/main/java/com/cloud/server/StatsCollector.java
This fixes a case wherein for some reason the /proc/cpuinfo isn't returning expected output, such as in case of experimental ARM64 M1 Mac Mini host. Found this over the weekend, tested the fix.
> Fix NPE in management server logs due to /proc/cpuinfo output

- ui/src/views/compute/DeployVM.vue
This PR fixes an issue in the deploy vm instance wizard.
(1) register template with userdata and userdatapolicy=APPEND
(2) deploy vm, check the "Userdata append", choose another userdata or input userdata manually
(3) uncheck "Userdata append"
(4) create a vm
expected: the additional userdata id or content are NOT passed (as  "Userdata append" is unchecked)
actual:  the additional userdata id or content are passed
> UI: fix userdataid or userdata content is passed when userdata append or override is unchecked

- packaging/centos7/cloud.spec
- packaging/centos8/cloud.spec
When install cloudstack on latest rocky8 server with java-11-openjdk-11.0.20.0.8-2.el8.x86_64, management server cannot be started due to error
```
Caused by: java.lang.Error: java.io.FileNotFoundException: /usr/lib/jvm/java-11-openjdk-11.0.20.0.8-2.el8.x86_64/lib/tzdb.dat (No such file or directory)
```
It is because the package `tzdata-java` is not automatically installed. (It was installed with java-11-openjdk-11.0.18.0.10-2.el8_7.x86_64, but not with latest java-11-openjdk-11.0.20.0.8-2.el8.x86_64)
> packaging: install tzdata-java on centos7/centos8

- ui/src/views/AutogenView.vue
> UI: fix 404 error when list volumes of system vms

- server/src/main/java/com/cloud/resourcelimit/CheckedReservation.java
This PR fixes a bug that broke a test in [CheckedReservationTest](https://github.com/apache/cloudstack/blob/9b41e7dec9e3421f804026186c9d3606534dba5d/server/src/test/java/com/cloud/resourcelimit/CheckedReservationTest.java#L65).  Not sure why it didn't show before (on merge and healthcheck).
unit test passes:
```
[INFO] Running com.cloud.resourcelimit.CheckedReservationTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.055 s - in com.cloud.resourcelimit.CheckedReservationTest
```
> server: get id from persisted object ReservationVO

- python/lib/cloudutils/configFileOps.py
This PR fixes the issue while adding rocky9 host failure due to missing /etc/sysconfig/libvirtd
> cloudutils: fix adding rocky9 host failure due to missing /etc/sysconfig/libvirtd

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDefTest.java
- server/src/main/java/com/cloud/hypervisor/KVMGuru.java
This PR bypasses overprovisioning settings on memory for SSVMs to make sure these can always start.
In addition this PR adds autodeflate to memballoon on KVM VMs and sets the memory to `memory` instead of `currentMemory`. It implement sugestions by @rajujith at https://github.com/apache/cloudstack/issues/7430#issuecomment-1600245780. This solution seems not to fixs overprovisioning issues in VMs and a new PR will have to be created for a definite solution on that.
Fixes: #7430
> KVM: fix SSVM starting when overprovisioning memory

- plugins/network-elements/nicira-nvp/src/main/java/com/cloud/network/nicira/NiciraRestClient.java
- plugins/network-elements/nicira-nvp/src/test/java/com/cloud/network/nicira/NiciraRestClientTest.java
- plugins/network-elements/nicira-nvp/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
This PR removes powermock from nicira nvp plugin's tests
> Remove powermock from nicira nvp

- ui/src/config/section/compute.js
- ui/src/views/AutogenView.vue
This PR...
Fixes: #7560 
Tested manually in the UI on and environment with two zones with different hypervisors.
An alternative way of testing could be testing in a single zone with two different hypervisor types or in two zones with the same hypervisor type. In both cases the list of available templates to choose from should be restricted to the current zone and hypervisor type. I.E. and template that is of a different hypervisortype or not available in the zone the VM is in should not be offered as a choice in the drop-down.
> Filter templates in vue

- engine/schema/src/main/java/com/cloud/upgrade/DatabaseUpgradeChecker.java
This PR adds systemvm upgrade check to the noop upgrade
Fixes: #6980
> make NoopDbUpgrade do a systemvm template check

- packaging/centos8/cloud.spec
> packaging: unalias cp before package upgrade

- ui/src/views/compute/EditVM.vue
With PR #7749, we are able to update userdata with some characters (e.g. Chinese).
when edit the vm again, the userdata is not displayed correctly
with this PR, it works well
> UI: decode userdata in EditVM dialog

- ui/src/components/view/DetailSettings.vue
This PR...
~~Fixes: #6937~~
Fixes: #7700
> UI: allow new keys for VM details

- server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
- server/src/main/java/com/cloud/user/AccountManagerImpl.java
This PR makes so that when `project=-1` and `listall=true`, `listVMsMetricsCmd` returns all VMs for the user, the same as for admin.
Fixes: #7642
> include all VMs when projects selected not just for admins

- engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
Remove nic allocation txn during Vm deploy during deploy Vm failure, entries for nics will remain in DB. This will allow cleanup of any allocated nics.
Create 2 networks. One of the with a small IP range (/29 or /30)
Deploy Vms with both networks until IPs in smaller network are exhausted
Without fix, there won't be any nic entries for failed VM. UserVm Scavenger will not find any nics to cleanup.
With the fix nic will be removed during Vm cleanup
`DEBUG [o.a.c.e.o.NetworkOrchestrator] (UserVm-Scavenger-2:ctx-ddff4ea8) (logid:48d79c3c) Removed nic id=27`
- [ X] Bug fix (non-breaking change which fixes an issue)
> Remove nic allocation txn during Vm deploy

- api/src/main/java/org/apache/cloudstack/api/command/admin/guest/AddGuestOsCmd.java
This PR fixes a issue reported in the user mail list: https://lists.apache.org/thread/clsoyz3kgp47ppbhtqp8m0o2fkczqrmk
> Details on add guest os optional

- plugins/hypervisors/xenserver/src/test/java/com/cloud/hypervisor/xenserver/resource/CitrixResourceBaseTest.java
- plugins/hypervisors/xenserver/src/test/java/com/cloud/hypervisor/xenserver/resource/Xenserver625StorageProcessorTest.java
- plugins/hypervisors/xenserver/src/test/java/com/cloud/hypervisor/xenserver/resource/wrapper/xenbase/CitrixRequestWrapperTest.java
- plugins/hypervisors/xenserver/src/test/java/com/cloud/hypervisor/xenserver/resource/wrapper/xenbase/XcpServerWrapperTest.java
- plugins/hypervisors/xenserver/src/test/java/com/cloud/hypervisor/xenserver/resource/wrapper/xenbase/XenServer56FP1WrapperTest.java
- plugins/hypervisors/xenserver/src/test/java/com/cloud/hypervisor/xenserver/resource/wrapper/xenbase/XenServer56WrapperTest.java
- plugins/hypervisors/xenserver/src/test/java/com/cloud/hypervisor/xenserver/resource/wrapper/xenbase/XenServer610WrapperTest.java
- plugins/hypervisors/xenserver/src/test/java/com/cloud/hypervisor/xenserver/resource/wrapper/xenbase/XenServer620SP1WrapperTest.java
- plugins/hypervisors/xenserver/src/test/java/com/cloud/hypervisor/xenserver/resource/wrapper/xenbase/XenServer620WrapperTest.java
- plugins/hypervisors/xenserver/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
This PR removes powermock from xenserver hypervisor plugin
> Remove powermock from xenserver hypervisor plugin

- engine/schema/src/main/resources/META-INF/db/schema-41800to41810.sql
CPU cap limitation was enabled as part of
https://github.com/apache/cloudstack/pull/6420 that changes behaviour for existing environments.
The CPU cap limitation on KVM causes systemvms to not start or be really slow in nested and virtualised environments. We shouldn't change the defaults, but this could be documented or an operator can create new system offerings and use them.
In KVM env, post upgrade SSVM operations were slow and a couple of times SSVM didn't start. By setting the value to false, no cpu share/limitation was put on new SSVMs and they could start and work. On git history check, found this to be a recent change introduced between 4.17->4.18 via #6420. This should be reverted.
> engine/schema: fix CPU cap limitation for upgraded environment

- test/integration/smoke/test_vm_deployment_planner.py
This PR...
This doesn't fix #7717 , but removes the abundant requirement from test_vm_deployment_planner, which looks for a specific template using the wrong hypervisor. The described issue in #7717 remains that the testclient doesn't have the right type of hypervisor configured.
> smoke test: fixes test_vm_deployment_planner

- server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
- server/src/main/java/com/cloud/user/AccountManagerImpl.java
- server/src/main/java/com/cloud/user/DomainManagerImpl.java
- server/src/test/java/com/cloud/user/DomainManagerImplTest.java
> server: clean network offerings for domain on remove

- plugins/integrations/prometheus/src/main/java/org/apache/cloudstack/metrics/PrometheusExporterImpl.java
This PR fixes the prometheus exporter issue that reports used memory instead of allocated memory.
Closes [#7625  ](https://github.com/apache/cloudstack/issues/7625)
The prometheus exporter output now matches the `cmk` output. Check out the #7625 for more details:
```
root@mgt01:~# curl http://127.0.0.1:9595/metrics | grep cloudstack_host_memory_usage_mibs_total
cloudstack_host_memory_usage_mibs_total{zone="Zone1",hostname="node01",ip="10.1.2.5",overprovisioningfactor="1.0",filter="allocated",dedicated="0",tags=""} 512.00
cloudstack_host_memory_usage_mibs_total{zone="Zone1",hostname="node01",ip="10.1.2.5",overprovisioningfactor="1.0",filter="total",dedicated="0",tags=""} 2907.71
cloudstack_host_memory_usage_mibs_total{zone="Zone1",hostname="node02",ip="10.1.2.6",overprovisioningfactor="1.0" …
```
> Prometheus exporter fix cpu/memory usage labels

- packaging/README.md
This PR adds documentation for generating debian builds for ubuntu-22.04
docker command for ubuntu 22.04 to build the Cloudstack debian builds.
made sure to inlude the node installation for the new UI 
Tested manually 
~~~
docker run -ti -v /tmp:/src ubuntu:22.04 /bin/bash -c "apt-get update && apt-get install -y software-properties-common && apt-add-repository universe --yes && apt-get update && apt-get install -y dpkg-dev debhelper lsb-release devscripts  openjdk-11-jdk libws-commons-util-java genisoimage libcommons-codec-java libcommons-httpclient-java liblog4j1.2-java maven python3 python3-mysql.connector python3-setuptools python-setuptools python3-openssl python3-dev libffi-dev build-essential libssl-dev libffi-dev fakeroot  python-is-python3 && curl -sL …
> added docker command for ubuntu 22.04 to  Building DEB packages

- test/integration/smoke/test_kubernetes_clusters.py
- test/integration/smoke/test_kubernetes_supported_versions.py
- tools/marvin/marvin/config/test_data.py
This PR updates k8s verison in smoke tests
> test: upgrade kubernetes versions to 1.25.0/1.26.0

- plugins/storage/volume/storpool/pom.xml
This PR fixes the issue which can be reproduced by steps below:
- git clone https://github.com/apache/cloudstack.git
- cd cloudstack
- rm -rf .git/
- run `mvn -P developer,systemvm clean install`
Without this PR, it fails with error
```
> [ 8/10] RUN mvn -Pdeveloper -Dsimulator -DskipTests clean install:
668.1 [ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:4.9.10:revision (get-the-git-infos) on project cloud-plugin-storage-volume-storpool: .git directory is not found! Please specify a valid [dotGitDirectory] in your pom.xml -> [Help 1]
```
> storpool: fix pom.xml which caused docker image build failures

- pom.xml
- tools/appliance/systemvmtemplate/scripts/configure_systemvm_services.sh
- tools/appliance/systemvmtemplate/template.json
Use new 4.18.1.0 systemvmtemplate, that addresses many new pkgs with security/improvement fixes.
> cloudstack: bump to use 4.18.1.0 systemvmtemplate

- plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java
> CKS: check access when get kubernetescluster config

- plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/guru/VMwareGuru.java
After a backup is successfully restored in Veeam, CloudStack tries to synchronize the restored VM; however, during the NIC synchronization process, all NIC devices are cast to `VirtualE1000`, whether they are an `E1000` or not, resulting in a casting exception being thrown and the process failing when they are not.
This PR addresses the fix for this issue.
This was tested in a local lab. 
Before the changes, whenever I tried to restore a backup of a VM that had a network adapter of types `PCNet32`, `Vmxnet2` or `Vmxnet3`, I would receive the following error message:
```
(<vm_name>) Error during vm backup restoration and import: class com.vmware.vim25.VirtualPCNet32 cannot be cast to class com.vmware.vim25.VirtualE1000 (com.vmware.vim25.VirtualPCNet32 and com.vmware.vim25.VirtualE1000 are …
```
> Fix casting exception during backup NIC synchronization

- server/src/main/java/com/cloud/network/IpAddressManagerImpl.java
- server/src/test/java/com/cloud/network/IpAddressManagerTest.java
After #6046 changes, CloudStack stopped incrementing the number of public IPs an account has allocated when a user acquires a new IP for a guest network, allowing them to allocate more public IPs than their account's limit.
This PR intends to fix the behavior and honor the account's IP address limit. On top of that, the method `updateIpResourceCount` was refactored and renamed to `checkIfIpResourceCountShouldBeUpdated`.
Everything has been tested in a local lab.
Tests related to the public IPs count:
- I acquired a public IP for a guest network and verified that the account's number of allocated public IPs was incremented;
- I acquired a public IP for a VPC and verified that the account's number of allocated public IPs was incremented.
Tests related to the feature that introduced the bug: …
> Fix allocation of more public IPs than the account's limit

- services/console-proxy/server/src/main/java/com/cloud/consoleproxy/ConsoleProxyNoVncClient.java
On a VMware ESXi 7 environment the Console VM would always use 100% cpu after one connection and it would not stop until a VM restart (or well cloud service restart inside of the VM).
This PR fixes this issue by adding a Thread.sleep(1).
> cpvm: fix cpu usage for console vm when using vnc over websockets

- api/src/main/java/org/apache/cloudstack/api/command/admin/internallb/StopInternalLBVMCmd.java
- api/src/main/java/org/apache/cloudstack/api/command/admin/router/StopRouterCmd.java
- api/src/main/java/org/apache/cloudstack/api/command/admin/systemvm/StopSystemVmCmd.java
- api/src/main/java/org/apache/cloudstack/api/command/user/vm/StopVMCmd.java
- plugins/network-elements/netscaler/src/main/java/com/cloud/api/commands/StopNetScalerVMCmd.java
> api: Force-stop descriptions

- ui/src/views/image/RegisterOrUploadIso.vue
- ui/src/views/image/RegisterOrUploadTemplate.vue
This PR allows passing the optional parameters `domainid` and `account` to the registerTemplate/registerISO/uploadISO/uploadTemplate APIs (was only possible to pass these parameters through the API):
- Register a template as an admin to another account in other domain -> verify domainid and account parameters are passed correctly
- Register a template as an admin without setting any domain or account -> verify domainid and account parameters are not passed
- Login as a user, verify the domain dropdown is not displayed
> UI: Add domain and account fields to Register/Upload Template/ISO view

- plugins/acl/static-role-based/src/main/java/org/apache/cloudstack/acl/StaticRoleBasedAPIAccessChecker.java
While checking an account access to prevent the role escalation, the `checkAccess` method is using both `DynamicRoleBasedAPIAccessChecker` and `StaticRoleBasedAPIAccessChecker` (legacy) classes and that is causing some inconsistences in the validations, consequently allowing the role escalation.
For this reason, the `StaticRoleBasedAPIAccessChecker` was disabled if `DynamicRoleBasedAPIAccessChecker` is enabled.
- I have created a domain admin custom role (DA2) and allowed all API's to it using the `*` regex;
- Removed an API that it had in common with default domain admin role;
- Tried to create a default domain admin account using a DA2 account;
- Received an exception from the role eslacation prevention.
> Fix role escalation prevention

- server/src/main/java/com/cloud/network/security/SecurityGroupManagerImpl.java
- server/src/main/java/com/cloud/network/security/SecurityGroupManagerImpl2.java
We have discovered that when securitygroups firewall rules are created, they use the MAC address from VM's private_mac_address field. However, if a VM has multiple NICs, then the same MAC address is issued to securitygroup.py which in some cases caused a trouble for the firewall rules.
This patch makes Cloudstack use the NIC's MAC address instead of VM's private MAC address.
> replace vm.getPrivateMacAddress() with nic.getMacAddress()

- plugins/metrics/src/main/java/org/apache/cloudstack/metrics/MetricsServiceImpl.java
- plugins/metrics/src/main/java/org/apache/cloudstack/response/HostMetricsResponse.java
The `listHostsMetrics` API returns the number of user VMs on the host. Although it doesn't return any data from the system VM instances on it.
Due to this, the `systeminstances` field was created in the `listHostsMetrics` API, which returns how many system VMs are running on the host and how many system VMs the host has in total.
I called the `listHostsMetrics` API via CloudMonkey and the `systeminstances` field was filled with the number of system VMs running on the host and the total of system VMs on the host.
> System VMs in listHostsMetrics API

- api/src/main/java/org/apache/cloudstack/api/command/user/network/CreateNetworkCmd.java
- api/src/main/java/org/apache/cloudstack/api/command/user/snapshot/CreateSnapshotCmd.java
- api/src/main/java/org/apache/cloudstack/api/command/user/vm/DeployVMCmd.java
- api/src/main/java/org/apache/cloudstack/api/command/user/volume/CreateVolumeCmd.java
- api/src/main/java/org/apache/cloudstack/api/command/user/volume/UploadVolumeCmd.java
- api/src/main/java/org/apache/cloudstack/api/response/UserVmResponse.java
- plugins/api/rate-limit/src/main/java/org/apache/cloudstack/api/command/admin/ratelimit/ResetApiLimitCmd.java
- plugins/network-elements/tungsten/src/main/java/org/apache/cloudstack/network/tungsten/api/command/ListTungstenFabricTagCmd.java
- plugins/storage/volume/cloudbyte/src/main/java/org/apache/cloudstack/storage/datastore/util/ListElastistorVolumeResponse.java
- plugins/user-authenticators/ldap/src/main/java/org/apache/cloudstack/api/response/LdapConfigurationResponse.java
- plugins/user-authenticators/ldap/src/main/java/org/apache/cloudstack/api/response/LinkAccountToLdapResponse.java
- plugins/user-authenticators/ldap/src/main/java/org/apache/cloudstack/api/response/LinkDomainToLdapResponse.java
- server/src/main/java/com/cloud/api/auth/DefaultLoginAPIAuthenticatorCmd.java
This PR fixes the issue #7776 and the spelling issues mentioned in: https://github.com/apache/cloudstack-go/pull/64
This PR doesn't need specific testing, it only changes some api call descriptions.
> Api: update command domainId/account descriptions

- .pre-commit-config.yaml
https://github.com/pre-commit/pre-commit-hooks#detect-private-key
The "exclude" list is the list of "keys" currently found by this hook
This PR adds another pre-commit hook or "test" to check for "keys" in the codebase
You can test locally with pre-commit from the repo root:
To just test this hook run:
`pre-commit run detect-private-key --all-files`
> pre-commit: add hook to check for the existence of private keys

- ui/src/views/image/RegisterOrUploadIso.vue
- ui/src/views/image/RegisterOrUploadTemplate.vue
This PR adds missing tooltips on the Register/Upload Template/ISO views:
- Register Template form
- Upload Template form
- Register ISO form
- Upload ISO form
> UI: Add missing tooltips to Register/Upload Templates/ISOs views

- server/src/main/java/com/cloud/user/AccountManagerImpl.java
- server/src/test/java/com/cloud/user/AccountManagerImplTest.java
Admins should be able to disable the 2FA of users that lost their second factor; however, the `setupUserTwoFactorAuthentication` API only allows them to disable the 2FA of users in the same domain. This means that, if the root admin wants to disable the 2FA of a user in ROOT/test, he must create a domain admin account in ROOT/test and log into that account to do this.
This PR addresses this issue by allowing admins to disable the 2FA of users in their subdomains.
I did the following tests in a local lab:
| Number | Test | Previous result | New result | New result was expected (Y/N)? |
| - | - | - | - | - |
| 1 | Disable your own 2FA as the root admin | Success | Success | Y |
| 2 | Disable the 2FA of a user in ROOT as the root admin | Success | Success | Y |
| 3 | Disable the 2FA of a …
> Allow admins to disable the 2FA of users in subdomains

- tools/apidoc/build-apidoc.sh
This PR keeps the same `sed` flags as Linux build hosts, if the end user has installed GNU sed rather than the one shipping with MacOS.
Tested locally
> API doc build fix

- ui/src/views/image/TemplateZones.vue
This PR hides the Delete Template button when a template is installing
Fixes: #7865
> UI: Fix hide delete button for templates that are in Installing template state

- engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/VolumeOrchestrator.java
This fixes #7834
- create service offering and disk offering with local storage
- create a vm with local storage, and stop it
- create volume with local storage
- attach volume to vm
sometimes the volume is allocated to other host than root disk in the attach process, and an exception is thrown
```
com.cloud.utils.exception.CloudRuntimeException: Failed to attach local data volume data-001 to VM local-001 as migration of local data volume is not allowed
at com.cloud.storage.VolumeApiServiceImpl.orchestrateAttachVolumeToVM(VolumeApiServiceImpl.java:2234)
at com.cloud.storage.VolumeApiServiceImpl.orchestrateAttachVolumeToVM(VolumeApiServiceImpl.java:4697)
```
> server: check hostId when attach disk to a Stopped vm with local storage

- api/src/main/java/com/cloud/storage/GuestOS.java
- api/src/main/java/org/apache/cloudstack/api/command/admin/guest/AddGuestOsCmd.java
- api/src/main/java/org/apache/cloudstack/api/command/admin/guest/UpdateGuestOsCmd.java
- api/src/main/java/org/apache/cloudstack/api/command/user/guest/ListGuestOsCmd.java
- api/src/main/java/org/apache/cloudstack/api/response/GuestOSResponse.java
- engine/schema/src/main/java/com/cloud/storage/GuestOSVO.java
- engine/schema/src/main/java/com/cloud/storage/dao/GuestOSDao.java
- engine/schema/src/main/java/com/cloud/storage/dao/GuestOSDaoImpl.java
- engine/schema/src/main/java/com/cloud/storage/dao/GuestOSHypervisorDao.java
- engine/schema/src/main/java/com/cloud/storage/dao/GuestOSHypervisorDaoImpl.java
- engine/schema/src/main/java/com/cloud/upgrade/GuestOsMapper.java
- engine/schema/src/main/java/com/cloud/upgrade/dao/Upgrade41800to41810.java
- engine/schema/src/main/resources/META-INF/db/schema-41720to41800.sql
- engine/schema/src/main/resources/META-INF/db/schema-41800to41810.sql
- plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/guru/VMwareGuru.java
- server/src/main/java/com/cloud/api/ApiDBUtils.java
- server/src/main/java/com/cloud/api/ApiResponseHelper.java
- server/src/main/java/com/cloud/server/ManagementServerImpl.java
- server/src/main/java/org/apache/cloudstack/vm/UnmanagedVMsManagerImpl.java
This PR fixes #7783 and #7781
(Need to merge duplicated guest OSes, and keep only one of them)
> engine/schema: fix duplicated guest OSes in 4.18.0.0

- ui/src/components/header/ProjectMenu.vue
- ui/src/store/getters.js
- ui/src/store/modules/app.js
- ui/src/views/AutogenView.vue
Issue: https://github.com/apache/cloudstack/issues/7181
Added a new getter 'allProjects' and mutation 'RELOAD_ALL_PROJECTS' to centralize the tracking of available projects in the state. 
This eliminates direct manipulation of the Project list in separate components and improves data consistency across the application. 
A watcher in ProjectMenu.vue has been implemented to handle changes to the 'allProjects' getter. 
The 'RELOAD_ALL_PROJECTS' mutation was also added where necessary to ensure the projects list is updated in the state whenever changes occur.
Before fix: 
https://github.com/apache/cloudstack/assets/2192264/65c7d88b-21ba-409c-aae6-bd1b667afe05
After Fix: 
https://github.com/apache/cloudstack/assets/2192264/b7ac990d-abd0-454e-b3e2-9c12efc50cb4
https://youtu.be/Ba63mpnie28
> UI: Add central project store and watch functionality

- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
- server/src/test/java/com/cloud/vm/UserVmManagerImplTest.java
- test/integration/component/test_update_vm.py
This PR fixes the case where someone updates the VM details via API and the non-displayable details that cloudstack uses for managing config internally get deleted.  An example of a non-displayable detail is `configDriveLocation`. If a user is using host based config drive, then configDriveLocation = "HOST".  If any detail is updated/changed, then this non-displayable detail is wiped. It was never visible via the API, so there's no chance someone could preserve it during a detail update.
In the case that the VM is stopped, a detail is updated, and then the VM delete is attempted, VM deletion can fail because it can't find the proper config drive location. A workaround for this specific situation is to start the VM, which will rewrite the missing detail. However, this surfaced the issue …
> Don't allow inadvertent deletion of hidden details via API

- engine/components-api/src/main/java/com/cloud/network/IpAddressManager.java
- server/src/main/java/com/cloud/network/IpAddressManagerImpl.java
- server/src/main/java/com/cloud/server/ManagementServerImpl.java
This fixes #7817
- deploy vm with specific IP
- change nic IP address to specific IP
- add specific IP as secondary IP
> server: allow user to list available IPs on shared networks

- server/src/main/java/com/cloud/network/IpAddressManagerImpl.java
If the original value is `false`, and search build is configured without the condition. 
Now change the value to `true`, it will not get effective due to missing condition.
> server: fix global setting system.vm.public.ip.reservation.mode.strictness is not really dynamic

- server/src/main/java/com/cloud/api/ApiResponseHelper.java
- server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
- server/src/main/java/com/cloud/network/IpAddressManagerImpl.java
- test/integration/smoke/test_public_ip_range.py
- ui/public/locales/en.json
- ui/src/views/infra/network/IpRangesTabPublic.vue
> server: fix cannot get systemvm ips in dedicated ranges

- server/src/main/java/com/cloud/network/router/NetworkHelperImpl.java
This PR fixes #7433 
It was a bit strange that cloudstack only tries to deploy VRs with at most two hypervisors. If there are more than 2 hypervisors (e.g. kvm/vmware/xen) on the environment, the VR deployment might fail.
- create an env with 3 hosts (1 kvm,1 vmware,1 xen)
- create a vm on isolated network on each hypervisor (3 networks and 3 vms in total)
- restart networks with cleanup, all work
- disable 2 of 3 hypervisors. for example, kvm is enabled, vmware/xen are disabled.
- restart networks with cleanup, all work
- disable kvm/xen host, and enable vmware
- restart networks with cleanup, all work
- disable kvm/vmware host, and enable xen
- restart networks with cleanup, all work
> server: try with all supported hypervisors (ordered, no duplications) when deploy a virtual router

- ui/src/utils/request.js
- ui/src/views/AutogenView.vue
This introduces change in AutogenView to do the following:
- Cancel old list API requests when the route is changed (between different list view or list and resource views)
- In the handler of an API call made in the fetchData(), to check if the json received is for the current route/id (API)
- Add console log for debugging which may be removed if this passes code review and testing
Fixes #7840
How was this tested?
- In my env the listVirtualMachines API takes time to complete, so I go to the instances page and go quick back/forth other views; for example, go to instances page that doesn't load and click on 2nd VM (or go to instance page and search something that returns faster than the whole list API and go the VM). When the original list API call completes, the current VM is replaced by …
> ui: Fix refresh and re-route behaviour

- ui/src/config/section/compute.js
- ui/src/store/mutation-types.js
- ui/src/views/AutogenView.vue
The default listVirtualMachinesMetrics APIs assumings details=all which isn't really used in the list view. By changing this to a subset of details, we can see gains upto 10x in listing speed in the UI. When moving to the resource/detail view of the UI, don't pass state or details so `all` the details of the instance are returned.
Possibly fixes #7910
In the screenshot below, we can see passing details=min, and other combinations show significant reduction in network time (from 300-400ms to 20-40ms)
> ui: speed up compute instance listing

- ui/src/views/compute/DeployVM.vue
In the deploy VM wizard, the settings inherited from a template (`iothreads`, `iothreads`, `io.policy`, `keyboard`, `UEFI` and dynamically scalable) are not automatically inferred after selecting the template. This would not matter for most of these settings if the user did not change the fields, since they would still be inherited when the parameters were null; however, the boot type and mode would always default to BIOS and LEGACY, even when set to something else in the template.
This PR aims to address this issue by making the deploy VM wizard automatically infer the settings inherited from a template.
In the deploy VM wizard:
1. I selected a template with dynamic scaling enabled and the settings `keyboard=jp`, `io.policy=io_uring`, `UEFI=LEGACY` and `iothreads=enabled`. Then, I …
> UI: Infer template settings in the deploy VM wizard

- engine/schema/src/main/java/com/cloud/upgrade/SystemVmTemplateRegistration.java
- server/src/main/java/com/cloud/storage/StorageManagerImpl.java
This PR fixes #7309 
We need to always update the size and state of systemvm template during registration
> systemvm: update size and state of systemvm template during registration

- api/src/main/java/org/apache/cloudstack/api/command/user/vm/DeployVMCmd.java
- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
This PR fixes #7115 
- create a service offering with "Custom Disk", "Disk offering strictness" is also enabled.
- deploy a vm with the new service offering, but not "Override root disk size"
Before this PR:
With this PR:
> server: throw new exception when rootdisksize is required but not set

- test/integration/smoke/test_vm_autoscaling.py
This PR fixes the smoke test `test_vm_autoscaling.py` which failed at the setup stage , because the autoscale vm profile uses a userdata which does not have a header.
it worked with 4.18, but not with main due to #7918
> test: fix test_vm_autoscaling.py which does not work due to userdata improvement

- engine/schema/src/main/java/com/cloud/upgrade/dao/DatabaseAccessObject.java
- engine/schema/src/main/java/com/cloud/upgrade/dao/DbUpgradeUtils.java
- engine/schema/src/main/java/com/cloud/upgrade/dao/Upgrade41800to41810.java
- engine/schema/src/test/java/com/cloud/upgrade/dao/DatabaseAccessObjectTest.java
This PR addresses slowness in FirstFitPlanner, looking for a cluster with capacity for new VM.
Adding an index to `cluster_details.name` yields a ~10x speed improvement in this query, and 2-3x improvement in overall time to create 1000 VMs in parallel during scale testing.  The performance of this query is dependent on number of clusters, so one environment is not directly comparable to another.
Using slow query logging, creating 1000 VMs with 100 parallel workers on a 100 cluster zone:
```
SELECT DISTINCT capacity.cluster_id  FROM `cloud`.`op_host_capacity` capacity INNER JOIN `cloud`.`cluster` cluster on (cluster.id = capacity.cluster_id AND cluster.removed is NULL)   INNER JOIN `cloud`.`cluster_details` cluster_details ON (cluster.id = cluster_details.cluster_id ) WHERE …
```
> Add index on cluster_details.name for FirstFitPlanner speedup

- plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/client/ScaleIOGatewayClientImpl.java
This PR allows the PowerFlex plugin to gracefully handle the case where volume has already been removed from the backend PowerFlex storage and a user attempts to expunge volume.  
Without this, attempting to also clean up in cloudstack results in volumes that are stuck in `Destroy` state, unless an admin manually edits the database.  If the volume is missing on the back end and admins want to recover, they can still attempt to fix this in some way and the record would be preserved in CloudStack as long as a volume expunge is not attempted.
```
Failed to expunge the volume Vol[37950|name=testvol|vm=null|DATADISK] in Primary data store : Unable to delete PowerFlex volume: xxxxx:xxxxx due to API failed due to: {"message":"Could not find the volume","httpStatusCode":500,"errorCode":79}
```
We …
> PowerFlex: Handle missing volumes gracefully during delete volume

- api/src/main/java/org/apache/cloudstack/api/AbstractGetUploadParamsCmd.java
- api/src/main/java/org/apache/cloudstack/api/command/user/iso/GetUploadParamsForIsoCmd.java
The `getUploadParamsForIso` API has duplicate zoneId and name parameters, as the `GetUploadParamsForIsoCmd` class declares these two attributes and extends from `AbstractGetUploadParamsCmd` which already has these attributes. To address that the attributes declared in the `GetUploadParamsForIsoCmd` class were removed, keeping only the inherited attributes.
Called the `getUploadParamsForIso` API via Cloudmonkey passing no parameters. Before the changes, the "Missing required parameters" returned name and zoneId twice. After the changes, it returned once as expected.
> Remove GetUploadParamsForIsoCmd API duplicate parameters

- core/src/main/java/org/apache/cloudstack/direct/download/HttpsDirectTemplateDownloader.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtCheckUrlCommand.java
- services/secondary-storage/server/src/main/java/org/apache/cloudstack/storage/template/DownloadManagerImpl.java
- utils/src/main/java/com/cloud/utils/storage/QCOW2Utils.java
- utils/src/test/java/com/cloud/utils/storage/QCOW2UtilsTest.java
This PR fixes an issue on direct download while registering HTTPS compressed files
Fixes: #7929
> Fix direct download https compressed qcow2 template checker

- debian/rules
- packaging/centos7/cloud.spec
- packaging/centos8/cloud.spec
- utils/pom.xml
This PR builds two jars for utils project
- `cloud-utils-4.19.0.0-SNAPSHOT.jar` : will be built into `cloudstack-4.19.0.0-SNAPSHOT.jar` (installed on management server) and `systemvm/target/agent.zip` (copied into system vms).
- `cloud-utils-4.19.0.0-SNAPSHOT-SHADED.jar` , will be installed as `/usr/share/cloudstack-common/lib/cloudstack-utils.jar`
> utils: build both SHADED and original jars

- ui/src/views/AutogenView.vue
This would fix the case of multiple items return in API response for a resource such as a template or ISO in case of multi-zone env.
> ui: don't skip if dataview has multiple items in response

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtConnection.java
> kvm: fix live vm migration between local storage pools

- plugins/network-elements/vxlan/src/main/java/com/cloud/network/guru/VxlanGuestNetworkGuru.java
- server/src/main/java/com/cloud/network/guru/ExternalGuestNetworkGuru.java
- server/src/main/java/com/cloud/network/guru/GuestNetworkGuru.java
Fixes #7926
Tested dualstack isolated network deployment with an advanced zone (*simulator*) having VXLAN isolation
> server: fix dualstack ipv6 networks for vxlan

- debian/rules
- packaging/centos7/cloud.spec
- packaging/centos8/cloud.spec
- utils/pom.xml
This PR fixes the build error on MacOS
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:3.0.0:shade (rebuild-war) on project cloud-utils: Error creating shaded jar: Could not replace original artifact with shaded artifact!: /Users/nicolas/cloudstack/utils/target/cloud-utils-4.19.0.0-SNAPSHOT-shaded.jar (No such file or directory) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can …
```
> utils: rename cloud-utils-*-SHADED.jar to cloud-utils-*-bundled.jar to fix the build error on Mac

- api/src/main/java/org/apache/cloudstack/api/command/user/config/ListCapabilitiesCmd.java
- api/src/main/java/org/apache/cloudstack/api/response/CapabilitiesResponse.java
- server/src/main/java/com/cloud/server/ManagementServerImpl.java
- ui/src/store/modules/user.js
This PR fixes the user role login in the UI on the main branch, bug introduced by the PR: #7692 
- As administrator, add 'Custom' to the 'hypervisor.list'
- Restart management server
- Create a Custom hypervisor zone
- Attempt login as a user -> verify it works
- As a user check the custom hypervisor is listed as a hypervisor on the new zone when trying to register a template
> UI: Fix user role login due to missing API access on custom hypervisor name

- ui/src/config/section/offering.js
CloudStack allows you to change host tags and storage tags of system offerings through the API, but it was missing from the UI. This just added the fields so the UI window is the same as the compute offering's window.
I created a system offering without host or storage tags, added them through the edit window and verified they were added. I then created another offering with tags, deleted one of them and changed the other to a different one.
> Allow editing of host and storage tags of system offerings in the UI

- .github/workflows/ci.yml
- .github/workflows/codecov.yml
- .github/workflows/ui.yml
- ui/jest.config.js
This PR generates coverage for Simulator based integration tests in github actions workflow and uploads the report to codecov.
> Generate coverage for Simulator based integration tests & ui tests in github actions

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/ScaleIOStorageAdaptor.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/storage/ScaleIOStorageAdaptorTest.java
This PR increases the overhead calculated for ScaleIO encrypted volumes slightly from 32MB to 128MB, due to edge cases found with lots of small writes over many weeks causing excessive fragmentation.  Ideally discard/fstrim is being issued in the guest to free some meaningful amount of space occasionally, but this should help for situations where that isn't guaranteed.
Tested locally, and updated the unit tests to verify the return value is as expected.
> Increase reserve on ScaleIO disk formatting for fragmentation

- server/src/main/java/org/apache/cloudstack/vm/schedule/VMScheduleManagerImpl.java
- server/src/main/java/org/apache/cloudstack/vm/schedule/VMScheduler.java
- server/src/main/java/org/apache/cloudstack/vm/schedule/VMSchedulerImpl.java
- server/src/test/java/org/apache/cloudstack/vm/schedule/VMSchedulerImplTest.java
- test/integration/smoke/test_vm_schedule.py
When there is not enough CPU or it takes more than 1 minute of time for poll to complete, scheduled jobs are not processed or scheduled jobs are not scheduled.
This PR fixes the above issues in VM Scheduler.
> Fix issues in VM Scheduler

- engine/schema/src/main/java/com/cloud/upgrade/DatabaseUpgradeChecker.java
- engine/schema/src/main/java/com/cloud/upgrade/DatabaseVersionHierarchy.java
- engine/schema/src/test/java/com/cloud/upgrade/DatabaseUpgradeCheckerTest.java
The uprgade from 4.18.1.0 to 4.18.2.0-SNAPSHOT failed with error
```
2023-09-12 16:12:19,003 INFO  [c.c.u.DatabaseUpgradeChecker] (main:null) (logid:) DB version = 4.18.1.0 Code Version = 4.18.2.0
2023-09-12 16:12:19,004 INFO  [c.c.u.DatabaseUpgradeChecker] (main:null) (logid:) Database upgrade must be performed from 4.18.1.0 to 4.18.2.0
2023-09-12 16:12:19,036 DEBUG [c.c.u.DatabaseUpgradeChecker] (main:null) (logid:) Running upgrade Upgrade41800to41810 to upgrade from 4.18.0.0-4.18.1.0 to 4.18.1.0
...
2023-09-12 16:12:19,041 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- Schema upgrade from 4.18.0.0 to 4.18.1.0
...
2023-09-12 16:12:21,602 DEBUG [c.c.u.d.DatabaseAccessObject] (main:null) (logid:) Statement: CREATE INDEX i_cluster_details__name on cluster_details (name)
2023-09-12 …
```
> upgrade: fix upgrade from 4.18.1.0 to 4.18.2.0-SNAPSHOT

- plugins/user-authenticators/ldap/src/main/java/org/apache/cloudstack/ldap/LdapManagerImpl.java
- server/src/main/java/com/cloud/user/AccountManagerImpl.java
- server/src/main/java/com/cloud/user/DomainManagerImpl.java
- server/src/test/java/com/cloud/user/DomainManagerImplTest.java
> ldap trust map cleanup on domain delete

- server/src/main/java/com/cloud/storage/snapshot/SnapshotSchedulerImpl.java
- server/src/test/java/com/cloud/storage/snapshot/SnapshotSchedulerImplTest.java
This PR adds and improves logs in the snapshot scheduling process in order to facilitate troubleshooting, as current logs are scarce.
I applied the changes in a local lab and checked if the messages were being correctly logged.
> Add and improve logs in snapshot scheduling

- engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
This PR publishes an action event for VM.STOP when the power state processor detects a VM is gone from hypervisor. Currently only a power state event is published on the message bus. This allows events to be seen and processed when VM is detected to be stopped out of band.
Additionally, it was discovered that the existing missing VM code is triggered when a VM is taking awhile to start. For example if we are waiting on the router VM to come up, the report can possibly see no VM when one is expected. The VM is assigned to the host, but doesn't exist yet, and triggers the missing VM code.  A check was added to ignore the VM if it is still in "Starting" state.
Tested out of band stop by shutting down guest within the VM, confirmed new event triggered.
Tested startup of VM where power state …
> Publish event for VM.STOP when out of band stop is detected

- engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
This PR attempts to live-patch VPC VRs even when the tier networks are not in the implemented state, i.e., there are no records in the router_network_ref table. Currently when they are in any other state than Implemented, live-patch fails 
1. Create a few VPC networks in say a 4.15.2 env 
2. Create a tier network in one of the VPCs such that it is in allocated state
3. Create a tier network in another VPC, create a VM and either destroy / shutdown the VM such that the n/w garbage collector will put the network tier in Shutdown state
4. Upgrade to main branch and then live-patch these VPCs
It should successfully have patched
> VR live patching: Allow live patch of VPC VRs even if networks are in allocated / shutdown state

- server/src/main/java/com/cloud/user/AccountManagerImpl.java
During the 2FA setup, the user must input a code in order to verify the configuration. If the user inserts the wrong code, an error message is shown; however, 2FA still gets enabled.
This PR fixes this behavior and prevents 2FA from becoming enabled if the user inserts the wrong code.
In a local lab:
- In a user of the root admin account, I opened the 2FA setup, selected static PIN, provided the wrong PIN and verified that 2FA did not get enabled;
- In a user of the root admin account, I opened the 2FA setup, selected static PIN, provided the correct PIN and verified that 2FA was enabled;
- In a user of a non-admin account belonging to domain `test/test2`, I opened the 2FA setup, selected static PIN, provided the wrong PIN and verified that 2FA did not get enabled.
- In a user of a …
> Fix 2FA becoming enabled when the user inputs the wrong code during setup

- engine/api/src/main/java/org/apache/cloudstack/engine/orchestration/service/VolumeOrchestrationService.java
- engine/schema/src/main/resources/META-INF/db/schema-301to302.sql
This PR...
Change units from Gigabyte to Gibibyte for maximum size for a volume
> fix units labels for max storage of volume

- systemvm/debian/opt/cloud/bin/cs/CsAddress.py
- systemvm/debian/opt/cloud/bin/cs/CsApp.py
This PR fixes #7968
- create vpc with redundant VRs (cidr: 172.24.0.0/20)
- create vpc tier1 with 172.24.1.0/24, create vm1 on it
- create vpc tier2 with 172.24.2.0/24, create vm2 on it
- destroy vm2, delete vpc tier2
- create vpc tier2-new1 with 172.24.2.0/24, create vm2-new1 on it
- destroy vm2-new1, delete vpc tier2-new1
- create vpc tier2-new2 with 172.24.2.0/24, create vm2-new2 on it
- check apache2 config files in /etc/apache2/site-enabled
expected: there are only config files for tier1 and tier2-new2 
actual: there are config files for tier1, tier2, tier2-new1, tier2-new2
> VR: remove apache2 config for removed VPC tiers

- .asf.yaml
Added myself (`JoaoJandre`) as a collaborator to be able to report issue with tags, and be assigned to issues and PRs.
> Added JoaoJandre to .asf.yaml

- agent/src/main/java/com/cloud/agent/resource/consoleproxy/ConsoleProxyResource.java
- core/src/main/java/com/cloud/resource/ServerResourceBase.java
- core/src/test/java/com/cloud/resource/ServerResourceBaseTest.java
- plugins/hypervisors/hyperv/src/main/java/com/cloud/hypervisor/hyperv/resource/HypervDirectConnectResource.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtVifDriverTest.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtNetworkElementCommandWrapperTest.java
This PR refactors variable names for LibvirtComputingResource according to new style standards.  It also refactors the variables in classes that were dependent on these variable names, to try to improve consistency.
It compiles without missing any symbols. Let's see how smoke tests do :-)
> Fix style for LibvirtComputingResource variable names and its dependencies

- plugins/storage/volume/scaleio/src/test/java/org/apache/cloudstack/storage/datastore/client/ScaleIOGatewayClientImplTest.java
I didn't have time to investigate the change in Mockito rules,  but after the upgrade of Mockito the maven build without skipping the tests is failing (if there is a running CS mgmt) with:
> [ERROR] Tests run: 5, Failures: 0, Errors: 5, Skipped: 0, Time elapsed: 0.329 s <<< FAILURE! - in org.apache.cloudstack.storage.datastore.client.ScaleIOGatewayClientImplTest
> [ERROR] testCreateSingleVolume(org.apache.cloudstack.storage.datastore.client.ScaleIOGatewayClientImplTest)  Time elapsed: 0.257 s  <<< ERROR!
> com.github.tomakehurst.wiremock.common.FatalStartupException: java.lang.RuntimeException: java.net.BindException: Address already in use
> Caused by: java.lang.RuntimeException: java.net.BindException: Address already in use
> Caused by: java.net.BindException: Address already in use
> Fix tests on CS build when cloudstack-management service is running

- server/src/main/java/com/cloud/hypervisor/discoverer/CustomServerDiscoverer.java
- server/src/main/java/com/cloud/hypervisor/kvm/discoverer/LibvirtServerDiscoverer.java
This PR keeps `LibvirtServerDiscoverer` from attempting to push direct download certs to other hosts when `addHost` API is used to add direct agent hosts and direct download certs are installed.
Tested locally by adding simulator hosts via API after adding direct download certs to zone.
> LibvirtServerDiscoverer should only process added hosts relevant to hypervisor type

- core/src/main/java/org/apache/cloudstack/agent/directdownload/CheckUrlCommand.java
- core/src/main/java/org/apache/cloudstack/direct/download/DirectDownloadHelper.java
- core/src/main/java/org/apache/cloudstack/direct/download/HttpDirectTemplateDownloader.java
- core/src/main/java/org/apache/cloudstack/direct/download/HttpsDirectTemplateDownloader.java
- core/src/main/java/org/apache/cloudstack/direct/download/MetalinkDirectTemplateDownloader.java
- core/src/test/java/org/apache/cloudstack/direct/download/BaseDirectTemplateDownloaderTest.java
- core/src/test/java/org/apache/cloudstack/direct/download/MetalinkDirectTemplateDownloaderTest.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtCheckUrlCommand.java
- server/src/main/java/com/cloud/template/HypervisorTemplateAdapter.java
This PR allows the direct download timeout configurations to apply to the URL check during registerTemplate. 
There is already support in the Downloader classes for these configurations for the actual download of templates, and the ConfigKeys already exist, so just needed to pass these in the CheckUrlCommand
Tested locally, confirmed config items are passed along.
mgmt server:
```
2023-09-06 14:41:09,340 DEBUG [c.c.a.m.ClusteredAgentAttache] (qtp1911152052-21:ctx-09dfd07c ctx-600dfd34) (logid:1083f2be) (extid:) Seq 43-7668222790528401454: Forwarding Seq 43-7668222790528401454:  { Cmd , MgmtId: 31239355356821, via: 43(kvmlab2), Ver: v1, Flags: 100011, [{"org.apache.cloudstack.agent.directdownload.CheckUrlCommand":{"format":"QCOW2","url":"https://download.fedoraproject.org/pub/fedora/linux/r …
```
> Use direct download timeout configs for URL check during registerTemplate

- agent/src/main/java/com/cloud/agent/Agent.java
- core/src/main/java/com/cloud/agent/api/PingCommand.java
- core/src/main/java/com/cloud/resource/AgentStatusUpdater.java
- core/src/main/java/com/cloud/resource/ResourceStatusUpdater.java
- engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
- engine/orchestration/src/main/java/com/cloud/vm/VirtualMachinePowerStateSync.java
- engine/orchestration/src/main/java/com/cloud/vm/VirtualMachinePowerStateSyncImpl.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
Pushing this to get some feedback, trying to provide a feature and reusing some functionality like the existing VM power state reporting, rather than inventing whole new messaging.
This PR allows KVM to detect guests that stop or crash, and immediately trigger a power state report to update the VM state in CloudStack.
In current design, Agent is responsible for sending pings on interval. These pings contain a state report for each VM. If something changes in between these pings, it can potentially take a long time for discovery of VM state change.
When Agent first starts, it loads the `ServerResource` (implementation is `LibvirtComputingResource` in the shipping agent) and initializes it. Then later it calls the ServerResource `getCurrentStatus()` to collect the host and VM status to send …
> Trigger out of band VM state update via libvirt event when VM stops

- server/src/main/java/com/cloud/user/PasswordPolicy.java
Some operators interpret "minimum digits" as "minimum number of characters" and confuse the setting password.policy.minimum.digits with password.policy.minimum.length. This PR changes the description of password.policy.minimum.digits and three other related settings to make the distinction clearer.
I applied the changes in a local lab and verified the descriptions were updated through the UI.
> Improve the description of config password.policy.minimum.digits

- api/src/main/java/org/apache/cloudstack/api/response/SystemVmResponse.java
- server/src/main/java/com/cloud/api/ApiResponseHelper.java
- test/integration/smoke/test_ssvm.py
- ui/src/components/view/InfoCard.vue
The API call `listSystemVMs` does not return the VM's service offering like `listVirtualMachines` does and, as such, the system VM page in the UI doesn't have that information like a user VM page has. This PR adds the fields `serviceOfferingId` and `serviceOfferingName` to the `SystemVmResponse` class.
It also changes the link to the offering in the VR page from `client/#/computeoffering/<uuid>?issystem=true` to `/client/#/systemoffering/<uuid>` for consistency (since it was the only place with such a way to access the system offering).
I accessed the SSVM and CPVM pages in the UI and saw the field "Compute offering" with the name and link to their respective offerings. If the offering does not exist, it returns 404 in the same way a missing template does.
On the VR page, the link to its …
> Add Service Offering to listSystemVMs and fix link from VR to its offering

- engine/schema/src/main/java/com/cloud/projects/dao/ProjectDaoImpl.java
When deleting a project, its name is always set to `null`. To maintain the integrity of the project's database history, this behavior was removed.
I created and deleted a project. Then, I created a SELECT SQL query for the `projects` table and the deleted project's name was there.
> Keep deleted projects name

- api/src/main/java/com/cloud/user/Account.java
- engine/schema/src/main/resources/META-INF/db/schema-41810to41900.sql
- server/src/main/java/com/cloud/user/AccountManagerImpl.java
When deleting an account, its state is maintained as `Enabled` even if it is removed.
Accordingly the `Removed` state for accounts was created, which is always set when an account is deleted.
I created and deleted an account. Then, I created a SELECT SQL query for the `account` table and the account state was `Removed`.
> Removed state for removed accounts

- services/secondary-storage/server/src/main/java/org/apache/cloudstack/storage/resource/NfsSecondaryStorageResource.java
This PR removes the directory of snapshot if it's empty after removal of snapshot.
> fix: cleanup directory if empty after removal of snapshot

- ui/src/views/iam/AddAccount.vue
- ui/src/views/network/CreateIsolatedNetworkForm.vue
This PR attempts to load items (PoC for domains on the network creation tab) in case there is more to load than the default 500 maximum.
This should be generalised to a mechanism that applies to any dropdown UI item, but is now only for a particular instance.
Fixes: #7780
create loads of domains 26*((26*3)+26)+1 and in the network create dialog add one by typing a partial name that is beyond the 500 mark. I create domains a-z with subdomain <x>a through <x>z  and sub-sub-domain 1st, 2nd and 3rd
What is still missing is searching for the last 3rd for instance. There are 26*26 (676) domains named 3rd, and if I want to select the last one. A thing that may also be missing in the domain overview search and in the results of #7766 , this does address the comment in …
> load (domains) continuously in dropdown boxes

- server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
This fixes the mysql error when list Shared templates for projects
without this PR
```
(localcloud) 🐱 > list templates listall=true templatefilter=shared showunique=true projectid=-1
🙈 Error: (HTTP 530, error code 4250) DB Exception on: com.mysql.cj.jdbc.ClientPreparedStatement: SELECT DISTINCT(template_view.id) FROM template_view WHERE template_view.account_type = 5  AND template_view.lp_account_id IN )  AND template_view.hypervisor_type='KVM' AND template_view.format != 'ISO'  AND template_view.template_state IN ('Active','UploadAbandoned','UploadError','NotUploaded','UploadInProgress')  AND template_view.removed IS NULL  ORDER BY template_view.sort_key ASC , template_view.temp_zone_pair ASC  LIMIT 0, 500
```
with this PR, it returns empty result
> server: fix mysql error when list Shared templates for projects

- PULL_REQUEST_TEMPLATE.md
- framework/config/src/main/java/org/apache/cloudstack/framework/config/ConfigKey.java
- framework/config/src/test/java/org/apache/cloudstack/framework/config/impl/ConfigDepotAdminTest.java
- framework/db/src/main/java/com/cloud/dao/EntityManagerImpl.java
- framework/db/src/main/java/com/cloud/utils/db/DbUtil.java
- framework/db/src/main/java/com/cloud/utils/db/DriverLoader.java
- framework/db/src/main/java/com/cloud/utils/db/EcInfo.java
- framework/db/src/main/java/com/cloud/utils/db/GenericDaoBase.java
- pom.xml
- utils/src/main/java/com/cloud/utils/SerialVersionUID.java
- utils/src/main/java/com/cloud/utils/events/SubscriptionMgr.java
- utils/src/test/java/com/cloud/utils/net/NetUtilsTest.java
- utils/src/test/java/org/apache/cloudstack/utils/redfish/RedfishClientTest.java
This PR applies errorprone as in below diff and applies the suggested changes for the first few projects. The permanent application of errorProne is removed within the scope of this PR as most projects will give positives.
```
commit 9f9a2b6b7e094537fea75f633d355f983d4c15d7
Author: Daan Hoogland <daan@onecht.net>
Date:   Thu Jan 12 19:32:35 2023 +0100
errorprone
diff --git a/pom.xml b/pom.xml
index 204c74cc76..13c46d7521 100644
--- a/pom.xml
+++ b/pom.xml
@@ -817,6 +817,32 @@
</execution>
</executions>
</plugin>
+            <plugin>
+                <groupId>org.apache.maven.plugins</groupId>
+                <artifactId>maven-compiler-plugin</artifactId>
+                <version>${cs.compiler-plugin.version}</version>
+                <configuration>
+ …
```
> cleanups as suggested by errorprone

- agent/conf/agent.properties
- agent/src/main/java/com/cloud/agent/properties/AgentProperties.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
- plugins/hypervisors/kvm/src/main/java/org/apache/cloudstack/utils/linux/KVMHostInfo.java
- plugins/hypervisors/kvm/src/test/java/org/apache/cloudstack/utils/linux/KVMHostInfoTest.java
This PR allows an admin to reserve some hypervisor host CPUs for system use. Another way to think of it is limiting the number of CPUs allocatable to VMs.  This can be useful if the admin wants to do other things with the hypervisor's CPU, for example reserve some cores for running hyperconverged storage processes.
Unit test provided, tested locally as well by setting `host.reserved.cpu.count` to various settings, restarting agent, confirming at UI that host's CPU count has changed.
> KVM Agent config to reserve dom0 CPUs

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessorTest.java
This PR address issue #8034.
While taking the volume snapshot on KVM, we call the method `copySnapshotToPrimaryStorageDir`. This method copies the base snapshot file to another directory, to enable the block commit for the delta of the disk right after taking the snapshot and avoid creating chains in the primary storage. However, copying a file (via the operating system) with a backing store will also copy the reference; therefore, it causes problems when the volume is not consolidated yet (which is always executed in KVM in volume migration process). If we create a template from the snapshot, and the deployment destination does not have access to the backing store file, the template will not be usable, as it would have a backing store pointing to the template that generated the volume. …
> Fix: Convert volume to another directory instead of copying it while taking volume snapshots on KVM

- plugins/integrations/prometheus/src/main/java/org/apache/cloudstack/metrics/PrometheusExporterImpl.java
This PR ensures getCapacityState() is not called for hosts in maintenance.
When a host is in maintenance, the relevant rows are removed from the op_host_capacity table. In this case, getCapacityState() triggers a nullpointer exception.
Fixes: #8024
> Ensure getCapacityState() is not called for hosts in maintenance

- server/src/main/java/org/apache/cloudstack/direct/download/DirectDownloadManagerImpl.java
This PR...
Improves the error messages to more accurately describe the reasons for failure to download a template. This is done via surfacing the underlying reason for the failure in the error message. This will facilitate troubleshooting.
This improved error messages are only shown to the admin role, for the rest of the users there is no change in error message details (tested with non-admin account).
Manual testing via setting up a development environment and triggering failures. Two scenarios were tested with below resulting error messages. Several other failure reasons will be surfaced as well.
-Example: Template checksum mismatch
Before:
Unable to orchestrate start VM instance {id: "3112", name: "i-2-3112-VM", uuid: "db19b8af-00e0-4f7a-803b-a6c3b022ba5d", type="User"} due to …
> Improve template download error message

- .pre-commit-config.yaml
Check for files that contain merge conflict strings.
https://github.com/pre-commit/pre-commit-hooks#check-merge-conflict
Another check or test we can have that can run automatically locally with `git commit`.
This PR adds another pre-commit hook expanding our framework and coverage.
The new hook `check-merge-conflict` is from the official pre-commit repos.
We do already have a GitHub Action that checks for merge conflicts but this new hook is better
since it runs both locally and on CI with pre-commit. 
If the check or test can run locally then there is faster feedback to the developer before opening a pr.
Just run the new hook:
`pre-commit run check-merge-conflict --all-files`
Run all hooks:
> pre-commit: add hook `check-merge-conflict`

- systemvm/debian/opt/cloud/bin/setup/init.sh
the service `user@0.service` fails in system vms and virtual routers
This PR removes a change to fix memory leak of SSH connections in the systemvm templates with old linux kernel.
> systemvm: remove config in /etc/pam.d/systemd-user to fix user@0.service

- api/src/main/java/org/apache/cloudstack/api/command/user/template/DeleteTemplateCmd.java
- test/integration/smoke/test_templates.py
Default value of force should be false for the template delete operation
> Default value of force should be false for template delete operation

- .github/workflows/sonar-check.yml
> .github: run Sonar Check only on PRs from apache/cloudstack branches

- plugins/network-elements/nsx/src/main/java/org/apache/cloudstack/agent/api/DeleteNsxSegmentCommand.java
- plugins/network-elements/nsx/src/main/java/org/apache/cloudstack/resource/NsxResource.java
- plugins/network-elements/nsx/src/main/java/org/apache/cloudstack/service/NsxElement.java
- plugins/network-elements/nsx/src/main/java/org/apache/cloudstack/service/NsxServiceImpl.java
This PR fixes the DHCP relay config deletion
> [NSX] Fix delete DHCP relay on segment deletion was missing zone name

- ui/src/views/dashboard/UsageDashboard.vue
If a user (non-admin) logs out from a session, then login page is not loading completely. Few starter APIs like listIds are failing and showing unauthorised access notification in Login Page. Also if SAML is enabled, it is not getting enabled since the corresponding API are failed. User needs to refresh the browser to get it back.
Login and logout with non admin users and you dont see any errors in the login page and all applicable login options will be enabled
> Fix non admin logouts

- engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/vmsnapshot/StorageVMSnapshotStrategy.java
This removes the conditional logic which is recommended in comments to remove it after PR #5297 is merged, and that is certainly applicable for ACS 4.18+. Only when the global setting is enabled and memory isn't selected, VM snapshot could be allowed for VMs on KVM that have qemu-guest-agent running.
Refer:
https://github.com/apache/cloudstack/pull/3724
https://github.com/apache/cloudstack/pull/5297
Doc improvement PR - https://github.com/apache/cloudstack-documentation/pull/353
1. After applying this fix on a 4.18.1 env, I could take a disk-only snapshots on VM with root/data disks and having qemu-guest-agent installed (and the global setting enabled):
2. On taking a disk-only snapshot of a running VM, I see snapshot (external) files created on the storage directory on the primary …
> storage: allow VM snapshots without memory for KVM when global setting allows

- server/src/main/java/com/cloud/deploy/FirstFitPlanner.java
This PR fixes the issue #8056 
Followed the steps mentioned in the issue and did not face NPE after the fix
> Fix NPE if global setting implicit.host.tags is set to null

- api/src/main/java/org/apache/cloudstack/api/command/user/vm/DeployVMCmd.java
- server/src/main/java/com/cloud/network/as/AutoScaleManagerImpl.java
- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
- server/src/test/java/com/cloud/network/as/AutoScaleManagerImplTest.java
- server/src/test/java/com/cloud/vm/UserVmManagerImplTest.java
This PR allows users to define the password of a virtual machine when deploying the VM (`deployVirtualMachine` API). If no password is informed, current ACS behavior is maintained: a random password is generated, injected into the VM, and returned to the user.
I applied the changes in a local lab, called the `deployVirtualMachine` API defining a password, and successfully accessed the VM with the password I have defined. Additionally, I called the `deployVirtualMachine` API without defining a password, and successfully accessed the VM with the random password generated.
> Allow password definition during VM deploy

- api/src/main/java/org/apache/cloudstack/api/command/user/vm/ResetVMPasswordCmd.java
- ui/src/config/section/compute.js
This PR allows users to define the password of a virtual machine when redefining the VM password (`resetPasswordForVirtualMachine` API). If no password is informed, current ACS behavior is maintained: a random password is generated, injected into the VM, and returned to the user. 
I applied the changes in a local lab, called the `resetPasswordForVirtualMachine` API defining a password, and successfully accessed the VM with the password I have defined. Additionally, I called the `resetPasswordForVirtualMachine` API without defining a password, and successfully accessed the VM with the random password generated.
> Add option to define password during password reset

- pom.xml
Addresses bug described in reflections 0.9.12 https://github.com/ronmamo/reflections/issues/273
While developing new code against CloudStack, I ran into the bug described above in Reflections 0.9.12. Upgrading seems to resolve the issue.
> Update pom.xml reflections version

- core/src/main/java/org/apache/cloudstack/direct/download/HttpsDirectTemplateDownloader.java
- utils/src/main/java/com/cloud/utils/UriUtils.java
- utils/src/main/java/com/cloud/utils/storage/QCOW2Utils.java
- utils/src/main/java/org/apache/cloudstack/utils/imagestore/ImageStoreUtil.java
- utils/src/test/java/com/cloud/utils/UriUtilsTest.java
> kvm: fix direct download template size

- engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/snapshot/SnapshotServiceImpl.java
- server/src/main/java/com/cloud/storage/StorageManagerImpl.java
The snapshot removal and storage cleanup logs have few information about these processes, which makes troubleshooting difficult.
This PR intends to add new log messages and rewrite the old ones to make troubleshooting easier.
I decreased the value of the `storage.cleanup.interval` configuration and deleted a snapshot. Then I checked the management server logs.
> Snapshot removal and storage cleanup logs

- test/integration/component/test_project_resources.py
Use super class method for cleanup of the resources.
Fixes simulator CI failures observed on different PRs lately.
> test,refactor: fix test_project_resources cleanup

- plugins/storage/volume/linstor/src/main/java/com/cloud/hypervisor/kvm/storage/LinstorStorageAdaptor.java
A TODO was overseen and never implemented,
which could trigger the following bug:
If Linstor didn't create a resource (diskless or diskfull) on the cloudstack choosen node, it would not be able to copy the template data there, it even seems no error was
triggered and the new template file silently just became empty/corrupt.
Local Linstor test cluster, fix is very isolated to Linstor primary storage
> linstor: Fix template volume missing on copy node

- plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java
This PR fixes the issue #7999 
While putting the storage pool datastore cluster in maintenance mode, then there are chances that the cloud.uuid gets updated with UUID without hyphens ('-') which causes issue with sync storage pool.
In my case this is happening if there any hosts in the clusters which does not have access to the storage pool.
In this PR we are making sure that the UUID does not change to uuid without hyphens
Before and after putting the storage pool in maintenance mode, cloud.uuid has not changed
Before the fix, this UUID has changed to UUID without hyphens
1. Prepare a datastore cluster with 2 child datastores
2. Add datastore cluster as primary storage in CloudStack
3. Put the datastore cluster in maintenance mode or restart management server (as part of the fix, make …
> Fix UUID for child datastores in all cases

- engine/schema/src/main/java/com/cloud/storage/dao/VolumeDaoImpl.java
This PR fixes the issue #8054 
1. created a VM with one root (2GB) and data (5GB) disks
2. create VM snapshot and the primary storage usage looks like below 
3. After this is fixed, usage considered 5GB data disk size as well
> Fix VM snapshot size during storage capacity check

- test/integration/smoke/test_snapshots.py
Fixes #8034
Adds the following test for a backed-up snapshot (original template and VM deleted beforehand):
- Create volume from snapshot
- Create a template from the snapshot and deploy a VM using it
> test: add test for standalone snapshot

- plugins/storage/volume/linstor/src/main/java/com/cloud/hypervisor/kvm/storage/LinstorStorageAdaptor.java
Making a diskful resource was meant as an optimization, but cannot work on non hyperconverged setups,
as the storage nodes (diskful) are not part of the cloudstack cluster.
This was introduced with 4a86a0d2339bbd809d87e7179f510e018030cbbc, so it isn't in any released version yet.
Tested on a new non hyperconverged cluster setup
> linstor: fix template copy on non hyperconverged setups

- test/integration/smoke/test_templates.py
- tools/marvin/marvin/lib/base.py
During failure while deploying a VM with the wrong checksum template, VM may be left in Error state. This PR adds code to delete such VM. Before wrong checksum test was not running correctly as the checksum parameter was not even passed while registering the template.
Fixes failures reported in https://github.com/apache/cloudstack/pull/7345#issuecomment-1760648666
> marvin,test: fix directdownload template checksum test

- server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
- server/src/main/java/com/cloud/api/query/dao/TemplateJoinDao.java
- server/src/main/java/com/cloud/api/query/dao/TemplateJoinDaoImpl.java
- server/src/test/java/com/cloud/api/query/QueryManagerImplTest.java
After the changes in #4774, when an account other than the root admin lists templates/ISOs with pagination, count gets set to the number of items returned in that page. For example, when the user lists 10 templates/ISOs and 15 entries are found, in the first page, count is set to 10 (the number of items being returned), as opposed to 15 (the total number of items). As a result, the deploy VM wizard only shows the first page of templates/ISOs.
This PR fixes this behavior and makes count return the correct number of found entries.
Everything has been tested in a local lab.
In the tested scenario, the following domains have templates:
- `ROOT`: 13 public and featured templates;
- `ROOT/test`: 4 public and featured templates.
<details>
<summary>
CloudMonkey command used to list templates. …
> Fix templates and ISOs listing pagination

- engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
- ui/public/locales/en.json
- ui/public/locales/pt_BR.json
- ui/src/views/tools/ImportUnmanagedInstance.vue
ACS allows you to add NICs to a VM without them, although it is not possible to set them as default since the `updateDefaultNicForVirtualMachine` API only updates the default NIC if a default NIC already exists, otherwise an exception is thrown.
For this reason, when a NIC is added and the VM that the NIC is being created for has no default NIC, the NIC will be marked as default.
Imported a VM without NICs, added some NICs and the first one was set as default.
> server: set Default NIC when VM has no default NIC

- ui/src/views/compute/DeployVM.vue
This PR fixes the vApp properties values sent as part of the deployVirtualMachine API through the UI
Fixes: #7998 
Tested with vApps containing properties registered as 'Read settings from OVA' templates on Vmware env
> UI: Fix deploy VM wizard vApp properties

- api/src/main/java/org/apache/cloudstack/api/response/GuestOSResponse.java
- server/src/main/java/com/cloud/api/ApiResponseHelper.java
This PR resolves issue #8127. Changing the datatype of isUserDefined of class GuestOSResponse from String to Boolean.
Fixes: #8127
> Fix os type response isuserdefined

- ui/src/views/dashboard/CapacityDashboard.vue
This improves the function to not show the red-dot status on host icon when there are no hosts in alert state. Instead a colour/theme matching exclaimation is show next to the host icon.
Minor polish issue, show host icon with red-dot when there are hosts in alert state:
Or, just the colour-icon matching exclaimation when no hosts are in alert state:
> dashboard: on admin dashboard use red-dot icon when hosts are in alert

- server/src/main/java/org/apache/cloudstack/vm/schedule/VMSchedulerImpl.java
This PR registers `VMScheduledJobExpireInterval`.
> Fixup: register vmscheduler configkey

- api/src/main/java/com/cloud/storage/Snapshot.java
- engine/storage/datamotion/src/main/java/org/apache/cloudstack/storage/motion/AncientDataMotionStrategy.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java
- server/src/main/java/com/cloud/storage/snapshot/SnapshotManagerImpl.java
This PR fixes #8078 
The volume snapshot will be created only on secondary storage.
Hypervisor KVM
Primary storage NFS
- take volume snapshot from VM snapshot without memory
- create volume from that snapshot
- crate template from the snapshot and deploy a VM
> Create snapshot from VM snapshot without memory for NFS/Local storage

- server/src/main/java/com/cloud/storage/snapshot/SnapshotManagerImpl.java
- server/src/test/java/com/cloud/storage/snapshot/SnapshotManagerImplTest.java
> Fixup updateSnapshotInfo failure due to forward merging

- agent/src/main/java/com/cloud/agent/Agent.java
- core/src/main/java/com/cloud/agent/api/PingAnswer.java
- engine/orchestration/src/main/java/com/cloud/agent/manager/AgentManagerImpl.java
- test/integration/smoke/test_host_ping.py
Depending on the agents' configuration, restarting a management server (preferred MS for the agent) will make the agent connect to another management server (non preferred MS). When the preferred MS comes back up, agent will try to disconnect with non-preferred MS and connect with the preferred MS. A race condition can happen during this process in which disconnection from non-preferred MS completes after the connection with preferred MS. This leads to agent to go into an `Alert` state. During this time, agent is still sending Ping to the preferred MS.
This PR solves this issue by:
* Taking a lock in database which ensures that for a host, only connection or disconnection can happen across different MS.
* While processing the `Ping` command if the Host is not in `Up` state, we request the …
> Fix failure on agent reconnection

- ui/src/components/view/SearchView.vue
- ui/src/views/AutogenView.vue
This is a followup for the PR https://github.com/apache/cloudstack/pull/7434, here we are making some more improvements
from
to
Along the with search box allignment, fixed the font sizes and check box sizes
> Fix allignment on layout on right panel

- utils/src/main/java/com/cloud/utils/script/Script.java
This PR adds and improves existing logs when executing scripts and commands, since current information is not sufficient to enable troubleshooting. 
I applied the changes in a local lab and checked if the updated logs were successfully logged.
> Add logs to script and command execution

- plugins/network-elements/nsx/src/main/java/org/apache/cloudstack/service/NsxApiClient.java
- server/src/main/java/com/cloud/network/router/VpcVirtualNetworkApplianceManagerImpl.java
This PR fixes VR public NIC allocation and remove tier 1 only when it exists
> [NSX] Fix for VR public NIC

- ui/src/views/storage/SnapshotZones.vue
Fixes Snapshot copy, zone delete option not showing in UI for non-rootadmin roles.
We already use param in API call to filter backed up snapshot copies.
> ui: fix snapshot copy actions for non-rootadmins

- api/src/main/java/org/apache/cloudstack/api/command/admin/acl/CreateRoleCmd.java
- ui/src/config/section/role.js
- ui/src/views/iam/CreateRole.vue
- ui/src/views/iam/ImportRole.vue
The concept of public roles was introduced in the PR [#6960](https://github.com/apache/cloudstack/pull/6960), however this resource was not extended to the UI. Thus, a field was added in the role creation, update and import form that allows you to choose whether the role is public or not.
I created, imported and updated some roles, then I checked the result of these operations in the database.
| N° | Test | isPublic | Expected result |
| ------ | ------ | ------ | ------ |
| 1 | Create a role with `isPublic` field checked | True | Y |
| 2 | Create a role with `isPublic` field unchecked | False | Y |
| 3 | Update a role with `isPublic` field checked | True | Y |
| 4 | Update a role with `isPublic` field unchecked | False | Y |
| 5 | Import a role with `isPublic` field checked | True | Y | …
> ui: extend role isPublic parameter

- pom.xml
- tools/appliance/systemvmtemplate/scripts/configure_systemvm_services.sh
- tools/appliance/systemvmtemplate/template.json
- Bumps ACS systemvmtemplate version
- Bumps systemvmtemplate version used in pom.xml
- Uses Debian 11.8.0 iso
> appliance: use Debian 11.8.0 and systemvm version to 4.19.0

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtDomainXMLParser.java
This PR fixes the issue #8040 
we are now handling any exception while setting up the memory balloon stats period
> Fix KVM cloudstack-agent start if there is vm not managed by cloudstack on the host

- server/src/main/java/com/cloud/network/NetworkModelImpl.java
The CloudStack coding conventions specify org.apache.commons.lang3.StringUtils as the default alternative for string operations, and com.cloud.utils.StringUtils for operations not covered by the former. 
Since org.apache.commons.lang3.StringUtils is seen as the default alternative and is used more often in NetworkModelImpl.java, this PR inverts how these two classes are referenced in this file in order to standardize it.
> Standardize StringUtils usages in NetworkModelImpl

- plugins/network-elements/juniper-contrail/src/test/java/org/apache/cloudstack/network/contrail/model/InstanceIpModelTest.java
- plugins/network-elements/juniper-contrail/src/test/java/org/apache/cloudstack/network/contrail/model/MockNetworkVO.java
- plugins/network-elements/juniper-contrail/src/test/java/org/apache/cloudstack/network/contrail/model/VMInterfaceModelTest.java
- plugins/network-elements/juniper-contrail/src/test/java/org/apache/cloudstack/network/contrail/model/VirtualMachineModelTest.java
- plugins/network-elements/juniper-contrail/src/test/java/org/apache/cloudstack/network/contrail/model/VirtualNetworkModelTest.java
This PR addresses a problem similar to the one mentioned in Issue #8087 by adopting the same solution approach used in PR #8098. Specifically, it refactors the mock object creation for `NetworkVO` across test suites of four classes: `InstanceIpModelTest.java`, `VirtualMachineModelTest.java`, `VirtualNetworkModelTest.java`, and the `testCreateVMInterface` method in another class. The central concern is the repetitive mock object creations for `NetworkVO`.
Following the methodology from PR #8098, I've introduced a new and reusable `MockNetworkVO` class. This class is designated for creating `NetworkVO` mock objects with consistent behavior, aiming to eliminate redundancy.
- **This refactoring leads to a cleaner codebase, streamlining the test cases and enhancing maintainability.**
- …
> refactor MockNetworkVO

- plugins/network-elements/nicira-nvp/src/test/java/com/cloud/network/nicira/NiciraNvpApiIT.java
This PR refactors the case [testCRUDAcl](https://github.com/apache/cloudstack/blob/6125886f3d0b64ff3d0a743d00bf414774e7e2e3/plugins/network-elements/nicira-nvp/src/test/java/com/cloud/network/nicira/NiciraNvpApiIT.java#L107).
Fix #6665 
- Extracted shared ACL setup logic into a private helper method, setupAcl().
- Split original testCRUDAcl into two separate tests: testCRUDAclReadAll and testCRUDAclReadOne.
- Each test case now represents a unique scenario for better readability and maintainability.
- Replaced assertTrue(false) with fail() in catch blocks for better test failure indication.
These changes aim to enhance the clarity and maintainability of the test suite, and ensure each test case checks only one scenario.
The local cluster environment (KVM, UBUNTU 18.04) runs the test …
> Refactor testCRUDAcl to Separated Case to Improve the Test Experience

- plugins/network-elements/nicira-nvp/src/main/java/com/cloud/network/nicira/NiciraRestClient.java
- plugins/network-elements/nicira-nvp/src/test/java/com/cloud/network/nicira/NiciraRestClientTest.java
- utils/src/main/java/com/cloud/utils/rest/HttpUriRequestBuilder.java
This PR is to fix a few tests whose results are non deterministic/flaky in the module plugins/network-elements/nicira-nvp. 
Java version: 11.0.20.1  
Maven version: 3.8.8   
The test `com.cloud.network.nicira.NiciraRestClientTest#testExecuteLiveLockWhenControllerAllowsLoginAndFollowsWithUnauthorizedButDoesNotRediect` assumes the order of keys to be maintained by a `HashMap`. This issue was verified using the [NonDex plugin](https://github.com/TestingResearchIllinois/NonDex). 
```
git clone https://github.com/apache/cloudstack.git
cd cloudstack
mvn install -pl plugins/network-elements/nicira-nvp -am -DskipTests
mvn -pl plugins/network-elements/nicira-nvp edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=com.cloud.network.nicira.NiciraRestClientTest#testExecuteLiveLockWhenControllerAllows …
```
> Make authentication request parameter order to be deterministic

- api/src/main/java/com/cloud/network/nsx/NsxProvider.java
- api/src/main/java/com/cloud/network/nsx/NsxService.java
- engine/schema/src/main/java/com/cloud/network/element/NsxProviderVO.java
- plugins/network-elements/nsx/src/main/java/org/apache/cloudstack/agent/api/CreateOrUpdateNsxTier1NatRuleCommand.java
- plugins/network-elements/nsx/src/main/java/org/apache/cloudstack/api/command/AddNsxControllerCmd.java
- plugins/network-elements/nsx/src/main/java/org/apache/cloudstack/api/response/NsxControllerResponse.java
- plugins/network-elements/nsx/src/main/java/org/apache/cloudstack/resource/NsxResource.java
- plugins/network-elements/nsx/src/main/java/org/apache/cloudstack/service/NsxProviderService.java
- plugins/network-elements/nsx/src/main/java/org/apache/cloudstack/service/NsxProviderServiceImpl.java
- plugins/network-elements/nsx/src/main/java/org/apache/cloudstack/service/NsxPublicNetworkGuru.java
- plugins/network-elements/nsx/src/main/java/org/apache/cloudstack/service/NsxServiceImpl.java
- plugins/network-elements/nsx/src/main/java/org/apache/cloudstack/utils/NsxHelper.java
- plugins/network-elements/nsx/src/main/resources/META-INF/cloudstack/core/spring-nsx-core-managers-context.xml
- plugins/network-elements/nsx/src/test/java/org/apache/cloudstack/service/NsxProviderServiceImplTest.java
- server/src/main/java/com/cloud/network/vpc/VpcManagerImpl.java
This PR updates Source NAT IP for NSX VPCs
> [NSX] Fix update source NAT IP

- engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
- engine/orchestration/src/test/java/com/cloud/vm/VirtualMachineManagerImplTest.java
In case of a failure while deploying VM, we reset the host_id for the failed VM to null but not the pod_id. This results in failure when there is enough capacity in another pod, but not in the existing pod.
This needs an environment with 2 pods to reproduce the issue and test the fix.
1. On management server, set a debugger here:
https://github.com/apache/cloudstack/blob/9df580cef457cdb767aa5bea926500fa8b1263ca/server/src/main/java/com/cloud/capacity/CapacityManagerImpl.java#L383
2. Deploy a VM. When the debugger reaches the line above, do the following:
1) Run `SELECT id, state, pod_id, host_id, last_host_id FROM vm_instance ORDER BY id DESC LIMIT 1;` on the `cloud` database.
2) Get the pod_id from the above and run this query for that pod_id `UPDATE host_pod_ref SET allocation_state = …
> Fix: Select another pod if all hosts in the pod becomes unavailable

- plugins/integrations/kubernetes-service/src/main/java/org/apache/cloudstack/api/command/user/kubernetes/cluster/CreateKubernetesClusterCmd.java
This PR fixes the issue that 4.18 cmk/api to create CKS cluster does not work in 4.19
> CKS: make clustertype optional to keep backwards compatibility

- ui/public/locales/en.json
- ui/src/components/widgets/ChartCard.vue
- ui/src/components/widgets/Drawer.vue
- ui/src/config/router.js
- ui/src/core/lazy_lib/components_use.js
- ui/src/style/dark-mode.less
- ui/src/utils/device.js
- ui/src/views/dashboard/CapacityDashboard.vue
- ui/src/views/dashboard/UsageDashboard.vue
This backports only the dashboard changes from
https://github.com/apache/cloudstack/pull/7956 and 5d9ae31f1b0dcf74dae722c2f22f895b85083002
> ui: Admin, account and project dashboard improvements

- engine/orchestration/src/test/java/com/cloud/vm/VirtualMachineManagerImplTest.java
- engine/orchestration/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
> Remove powermock form VM Manager test

- client/pom.xml
- plugins/storage/volume/linstor/pom.xml
- plugins/storage/volume/linstor/src/main/java/com/cloud/api/storage/LinstorBackupSnapshotCommand.java
- plugins/storage/volume/linstor/src/main/java/com/cloud/api/storage/LinstorRevertBackupSnapshotCommand.java
- plugins/storage/volume/linstor/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LinstorBackupSnapshotCommandWrapper.java
- plugins/storage/volume/linstor/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LinstorRevertBackupSnapshotCommandWrapper.java
- plugins/storage/volume/linstor/src/main/java/com/cloud/hypervisor/kvm/storage/LinstorStorageAdaptor.java
- plugins/storage/volume/linstor/src/main/java/org/apache/cloudstack/storage/datastore/driver/LinstorPrimaryDataStoreDriverImpl.java
- plugins/storage/volume/linstor/src/main/java/org/apache/cloudstack/storage/datastore/provider/LinstorPrimaryDatastoreProviderImpl.java
- plugins/storage/volume/linstor/src/main/java/org/apache/cloudstack/storage/datastore/util/LinstorConfigurationManager.java
- plugins/storage/volume/linstor/src/main/java/org/apache/cloudstack/storage/datastore/util/LinstorUtil.java
- plugins/storage/volume/linstor/src/main/resources/META-INF/cloudstack/storage-volume-linstor/spring-storage-volume-linstor-context.xml
- pom.xml
This PR adds an config option for the Linstor primary storage driver, that allows you to automatically backup
volume snapshots to the secondary storage.
Additionally it will not mangle the need `java-linstor` dependency into the client.jar, but instead just copy
the `java-linstor.jar` into `lib`.
Config option is called: `lin.backup.snapshots` and is default `false`
The scope of this change should be limited, as it only touches the Linstor driver and a part of `copyAsync`
was implemented with 2 new Linstor specific commands.
Tested on 2 different Linstor clusters, one running LVM the other ZFS.
Additionally send this PR to a PoC tester, who requested this feature.
> Linstor backup snaphots

- ui/src/views/image/RegisterOrUploadTemplate.vue
This PR Fixes: #7864 
debugged in local UI against lab environment.
Note that this is a pure UI change but is dependend on the template being for vmware and thus can not be tested in the qa env (which is simulator only).
> make sure vmware adapter detail for nic is passed during registering template

- api/src/main/java/org/apache/cloudstack/api/command/admin/network/CreateNetworkOfferingCmd.java
- api/src/main/java/org/apache/cloudstack/api/command/admin/network/UpdateNetworkOfferingCmd.java
…workOffering
This PR fixes #7510 
- [ X ] Bug fix (non-breaking change which fixes an issue)
- [ X ] Minor
- [ X ] Trivial
> updated the api documentation for createNetworkOffering and updateNetworkOffering

- framework/quota/src/main/java/org/apache/cloudstack/quota/QuotaManagerImpl.java
- framework/quota/src/main/java/org/apache/cloudstack/quota/activationrule/presetvariables/PresetVariableHelper.java
- framework/quota/src/main/java/org/apache/cloudstack/quota/activationrule/presetvariables/Value.java
- framework/quota/src/test/java/org/apache/cloudstack/quota/QuotaManagerImplTest.java
- framework/quota/src/test/java/org/apache/cloudstack/quota/activationrule/presetvariables/PresetVariableHelperTest.java
- framework/quota/src/test/java/org/apache/cloudstack/quota/activationrule/presetvariables/ValueTest.java
- utils/src/main/java/org/apache/cloudstack/utils/jsinterpreter/JsInterpreter.java
- utils/src/test/java/org/apache/cloudstack/utils/jsinterpreter/JsInterpreterTest.java
This PR adds two new preset variables into the Quota activation rules: hypervisor type and volume format. This allows operators to customize tariffs based on these two properties.
The respective preset variable will be injected into tariffs with the following usage types:
- RUNNING_VM: `value.hypervisorType`;
- ALLOCATED_VM: `value.hypervisorType`;
- VM_SNAPSHOT: `value.hypervisorType`;
- SNAPSHOT: `value.hypervisorType`;
- VOLUME: `value.volumeFormat`;
- VOLUME_SECONDARY: `value.volumeFormat`.
Example of an activation rule using `value.hypervisorType`:
```js
if (value.hypervisorType=='KVM') {
1
} else {
2
}
```
Example of an activation rule using `value.volumeFormat`:
```js
if (value.volumeFormat=='QCOW2') {
3
} else {
4
}
```
Furthermore, this PR also fixes the preset variable …
> Inject hypervisor type and volume format on Quota tariffs

- server/src/main/java/com/cloud/template/HypervisorTemplateAdapter.java
This PR fixes the issue #7970 
Fix is to keep the template deploy as is details even after the template is deleted. VM start need to know whether the vapp property is password or not which are saved in template_deploy_as_is_details table.
1. Registered a VMware template with "Read VM settings from OVA" enabled
2. Created a VM with it
3. Force delete the template
4. Stop and start the VM => succeeded
> Fix deploy as is VM start after template deletion

- plugins/network-elements/tungsten/src/test/java/org/apache/cloudstack/network/tungsten/service/TungstenApiTest.java
This PR fixes the non deterministic behaviour of 2 tests. This happens as the tests assume the return value of an API to be ordered when it is actually not guaranteed. This has been detected using [NonDex](https://github.com/TestingResearchIllinois/NonDex) tool.
1. `mvn install -pl plugins/network-elements/tungsten`
2. `mvn -pl plugins/network-elements/tungsten edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=org.apache.cloudstack.network.tungsten.service.TungstenApiTest#listTungstenNetworkTest -DnondexMode=ONE`
Failure log:
```
[INFO] Running org.apache.cloudstack.network.tungsten.service.TungstenApiTest
[ERROR] Tests run: 77, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 1.35 s <<< FAILURE! - in org.apache.cloudstack.network.tungsten.service.TungstenApiTest
[ERROR] …
```
> Fix flaky tungsten test using comparator

- api/src/main/java/org/apache/cloudstack/api/command/user/offering/ListDiskOfferingsCmd.java
- api/src/main/java/org/apache/cloudstack/api/command/user/offering/ListServiceOfferingsCmd.java
- server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
This PR fixes #8206 
```
(local) 🐵 > list serviceofferings storagetype=local
{
"count": 1,
{
"created": "2023-11-10T11:41:02+0200",
"displaytext": "Medium Instance",
"encryptroot": false,
"id": "045f2740-1570-481c-9a65-cc2ce3a44c63",
"iscustomized": false,
"memory": 1024,
"name": "Medium Instance",
"offerha": false,
"provisioningtype": "thin",
"rootdisksize": 0,
"storagetype": "local"
}
]
}
(local) 🐵 > list serviceofferings storagetype=shared
{
"count": 1,
{
"created": "2023-11-10T11:41:02+0200",
"defaultuse": …
```
> storagetype API param in list service/disk offerings

- plugins/integrations/prometheus/src/main/java/org/apache/cloudstack/metrics/PrometheusExporterServerImpl.java
This PR fixes a bug where the length of the httpresponse was set to the length of the contents before unicode conversion. Any non english  character would break this.
Fixes: #8203
- [x ] Minor
in simulator,
- the prometheus exporter was enabled
- domains with names ééñ and 中文 were created
- a curl done
```
cloudstack_domain_resource_count{domain="/", type="memory"} 0
cloudstack_domain_resource_count{domain="/", type="cpu"} 0
cloudstack_domain_resource_count{domain="/", type="primary_storage"} 0
cloudstack_domain_resource_count{domain="/", type="secondary_storage"} 4294967296
cloudstack_domain_resource_count{domain="/ééñ/", type="memory"} 0
cloudstack_domain_resource_count{domain="/ééñ/", type="cpu"} 0
cloudstack_domain_resource_count{domain="/ééñ/", type="primary_storage"} 0 …
```
> Let Prometheus exporter plugin support utf8 characters

- agent/conf/agent.properties
- agent/src/main/java/com/cloud/agent/properties/AgentProperties.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/KVMHABase.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/KVMHAMonitor.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStoragePool.java
Currently, the heartbeat frequency of the KVM HA is fixed at 60,000 milliseconds. This property was externalized as `kvm.heartbeat.update.frequency` in `agent.properties`.
I applied the changes in a local lab, changed the frequency, and checked if heartbeats were occurring at the frequency I specified.
> Externalize KVM HA heartbeat frequency

- agent/src/main/java/com/cloud/agent/dao/impl/PropertiesStorage.java
This PR... changed the '+' operator for concatenation to .concat method for concatenation because '+' operator takes more time then .concat method.
[Optimisation].
> Improved concatenation way in PropertiesStorage.java

- api/src/main/java/org/apache/cloudstack/api/command/user/template/CreateTemplateCmd.java
- api/src/test/java/org/apache/cloudstack/api/command/user/template/CreateTemplateCmdTest.java
This PR introduces domainid and account as optional parameter for createTemplate API. It will allow admin to create templates for specified domain belonging to specific account.
Fixes: https://github.com/apache/cloudstack/issues/5793#issuecomment-1792003872
It's tested using 2 different users belonging to separate domains, 
- Create two domains - d1 and d2
- Create normal user accounts in both domains - u1 and u2, associated them to d1 and d2 respectively
- Deploy a VM, vm1, with u1,  stop it; repeat steps with u2 account
- Using ROOT admin try creating template using vol_u1, passing account u1 and domain d1
- Using ROOT admin try creating template using vol_u1, passing account u2 and domain d2
- Using ROOT admin try creating template using vol_u2, passing account u2 and domain d2
- Using …
> Introduce domainid and account parameter in createTemplate API

- engine/schema/src/test/java/com/cloud/network/as/AutoScaleVmProfileVOTest.java
The PR fixes the following tests which could produce non-deterministic/flaky pass/fail result
`com.cloud.network.as.AutoScaleVmProfileVOTest#tstSetOtherDeployParamsForUpdate`
`com.cloud.network.as.AutoScaleVmProfileVOTest#testCounterParamsForUpdate`
Java version: 11.0.20.1
Maven version: 3.8.8
The tests compares the keys and values of hashmap (based on index) with hardcoded string and asserts if they are equal. However, the order of key value pairs within hashmap is not gauranteed. Hence the test can fail. This issue was verified using the [NonDex plugin](https://github.com/TestingResearchIllinois/NonDex).
```
git clone https://github.com/apache/cloudstack.git
cd cloudstack
mvn install -pl engine/schema -am -DskipTests
mvn -pl engine/schema edu.illinois:nondex-maven-plugin:2.1.1:nondex …
```
> Fixed Hashmap Key value comparision

- framework/quota/src/main/java/org/apache/cloudstack/quota/QuotaManagerImpl.java
- framework/quota/src/test/java/org/apache/cloudstack/quota/QuotaManagerImplTest.java
- utils/src/main/java/com/cloud/utils/DateUtil.java
The Quota usage value for monthly usage types uses the cost per hour to calculate the total tariff value in a particular period. In order to define the cost per hour, it takes into account the total number of hours in each month. However, this value is currently fixed at 720 hours for every month. 
This causes incorrect values when calculating the cost per hour, resulting in costs being higher than expected. Therefore, this PR aims to calculate the number of hours in each month based on the actual number of days of each month.
For example, if the tariff value is 100 per month, the current cost per hour is 0.138888889 for every month. For 1 hour per month the total cost in a year would be 1.666666668.
With the adjustments to the cost per hour of this PR, the costs per hour would be: …
> Set number of hours per month with actual number in Quota

- api/src/main/java/org/apache/cloudstack/api/response/AcquireIPAddressResponse.java
- api/src/main/java/org/apache/cloudstack/api/response/IPAddressResponse.java
- api/src/main/java/org/apache/cloudstack/api/response/PortableIpResponse.java
This PR just fixes spelling and adding missing states to responses
> Fixed spelling and added missing states to response

- api/src/main/java/com/cloud/network/NetworkService.java
- api/src/main/java/org/apache/cloudstack/api/command/user/address/DisassociateIPAddrCmd.java
- server/src/main/java/com/cloud/network/NetworkServiceImpl.java
- server/src/test/java/com/cloud/vpc/MockNetworkManagerImpl.java
- test/integration/smoke/test_network.py
- tools/marvin/marvin/lib/base.py
This PR adds argument 'ipadress' to the disassociateIpAddress api. IP address can be disassociated by directly giving the address instead of ID.
Fixes: #8125 
Tested to see that disassociateIpAddress cmd passes with 'ipaddress' argument. And throws an error if neither Id nor ipadress is provided.  Added testcase in test_network.py to disassociate using ipaddress.
```
> Added ipaddress argument to disassociateIPAddress api (#8125)

- server/src/main/java/com/cloud/deploy/DeploymentPlanningManagerImpl.java
- server/src/test/java/com/cloud/deploy/DeploymentPlanningManagerImplTest.java
- server/src/test/java/com/cloud/storage/StorageManagerImplTest.java
When there is outage in storage API coincides with a VM start, the volume could be stuck in "Allocated" state but with a pool Id assigned in DB. It blocked the ability to start the VM  during planDeployment process,  in the method storagePoolCompatibleWithVolumePool() shown below when validating a volume with a storage pool, if the volume's pool Id is not null and state is Allocated, it would always return false for any storage pools. As a result, the allocator cannot find a suitable pool and it blocks the VM start process.
```
@Override
public boolean storagePoolCompatibleWithVolumePool(StoragePool pool, Volume volume) {
if (pool == null || volume == null) {
return false;
}
if (volume.getPoolId() == null) {
// Volume is not allocated to any pool. Not possible to check compatibility with …
```
> Clear pool id if volume allocation fails

- systemvm/agent/scripts/ssvm-check.sh
This PR fixes a typo, which causes an incorrect check for the NFS connection.
```
ERROR: Storage nfs is not currently mounted
Verifying if we can at least ping the storage
Storage address is empty, trying to ping storage network gateway instead ()
ping: missing host operand
Try 'ping --help' or 'ping --usage' for more information.
WARNING: Cannot ping nfs storage network gateway
```
> Fix typo in ssvm check script

- ui/src/config/section/storage.js
- ui/src/views/storage/CreateTemplate.vue
This PR includes Domain and Account parameter in CreateTemplate form in UI for Admin account.
It will expose optional parameters domainId and account in UI supported by  createTemplate API https://github.com/apache/cloudstack/pull/8210
- Created u1 and u2 user under d1 and d2 domain respectively.
- Create template form allows Admin user to provide domain and accountid 
- Template got created for right user account under correct domain
> Include domain and account field for createTemplate UI form

- server/src/main/java/com/cloud/network/vpc/VpcManagerImpl.java
- server/src/test/java/com/cloud/network/vpc/VpcManagerImplTest.java
When creating a private gateway, if an ACL verification error occurs, the changes made up to that point are not rolled back, resulting in inconsistent records in the database.
This PR intends to fix this bug and, if an error occurs during the creation of the private gateway, the changes will be rolled back.
I followed the same steps from `How did you try to break this feature and the system with this change?` and verified in the database that the network created to the private gateway was rolled back.
1. Create 2 VPCs (VPC1 and VPC2);
2. Create an ACL for VPC2;
3. Using CloudMonkey, try to create a private gateway in VPC1 using the ACL from VPC2 (an exception will be thrown: `Private gateway and network acl are not in the same vpc`);
4. Check the `networks` table in the database and the …
> Fix rollback while creating a private gateway

- engine/schema/src/main/java/com/cloud/vm/dao/NicDao.java
- engine/schema/src/main/java/com/cloud/vm/dao/NicDaoImpl.java
- server/src/main/java/com/cloud/network/NetworkModelImpl.java
> server: check if there are active nics before network GC

- ui/src/views/network/PortForwarding.vue
This PR removes redundant IP Address column
Link to the issue: https://github.com/apache/cloudstack/issues/8273 
Before fix:
After fix:
> UI: Removed redundant IP Address Column

- api/src/main/java/org/apache/cloudstack/api/command/user/iso/GetUploadParamsForIsoCmd.java
- api/src/main/java/org/apache/cloudstack/api/command/user/template/GetUploadParamsForTemplateCmd.java
displaytext parameter for registerTemplate/Iso API has been optional sometime back. For upload APIs the param is not optional which creates inconsistency in the UI. This PR fixes the behaviour.
Before change,
> api: make displaytext form upload template/iso optional

- plugins/storage/volume/linstor/src/main/java/org/apache/cloudstack/storage/datastore/driver/LinstorPrimaryDataStoreDriverImpl.java
- plugins/storage/volume/linstor/src/main/java/org/apache/cloudstack/storage/datastore/util/LinstorConfigurationManager.java
On no access to the storage nodes, we now create a temporary resource from the snapshot and copy that data into the secondary storage. Revert works the same, just that we now also look additionally for any Linstor agent node.
Also enables now backup snapshot by default.
This whole BackupSnapshot functionality was introduced in 4.19,
so I would be happy if this still could be merged.
Tested on a Linstor hyper-converged and non hyper-converged setup.
> Linstor: Allow snapshot backup also to work on non hyperconverged setups

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
This PR fixes ide controller for rocky/alma vms. virtio devices should be used.
> kvm: fix ide controller for rocky/alma vms

- server/src/main/java/com/cloud/network/vpc/VpcManagerImpl.java
> NSX: Fix Creation of VPCs

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtConnection.java
The KVM Agent has the `hypervisor.uri` configuration to define the connection with Libvirt; however, this property is ignored and a hardcoded value is used in many parts of the code.
This PR intends to prioritize the `hypervisor.uri` property in Libvirt connections and use the hypervisor default URI only when this configuration is not defined.
I followed the same steps from `How did you try to break this feature...` and verified that the host was only using the URI defined in the `hypervisor.uri` property.
1. Add the `hypervisor.uri` property to a host's agent.properties, `hypervisor.uri=qemu:///session` for example;
2. Check the agent logs;
3. Although the `hypervisor.uri` property is defined, the agent is still using the hypervisor default URI in many connections;
> Prioritize hypervisor.uri configuration

- ui/src/config/section/role.js
This PR addresses the problem of not being possible to edit the Public property of a default role through the UI, since it sets the other fields as parameters of the API call and results in a `Default roles cannot be updated (with the exception of making it private/public).` error. 
It solves this by simply limiting the available fields for default roles, since they are not possible to be edited in the first place and should not show up anyway. It does not change the window for non-default roles.
In the User default role, I verified that only the Public field showed up. I unchecked it and verified `ispublic` became false. 
I created a new role. In its editing window, I verified all the original fields were there (Name, Description, Type and Public). I changed the fields and verified they …
> Change available fields when editing a default role in the UI

- plugins/storage/volume/linstor/src/main/java/com/cloud/hypervisor/kvm/storage/LinstorStorageAdaptor.java
- plugins/storage/volume/linstor/src/main/java/org/apache/cloudstack/storage/datastore/util/LinstorUtil.java
If Linstor doesn't return storage pool info, certain values are null.
Now we assume the values are 0 if we get null values.
This should also be merged into `4.18`
Linstor cluster with one node down.
> linstor: Fix possible NPE if Linstor storage-pool data missing

- plugins/integrations/prometheus/src/main/java/org/apache/cloudstack/metrics/PrometheusExporterImpl.java
Sometimes the hostStats object of the agents becomes null in the management server. It is a rare situation, and we haven't found the root cause yet, but it occurs occasionally in our CloudStack deployments with many hosts.
The hostStat is null, even though the agent is UP and hosting multiple VMs. It is possible to access the VM consoles and execute tasks on them.
This pull request doesn't address the issue directly; rather it displays those hosts in Prometheus so we can restart the agent and get the necessary information.
1. Set `prometheus.exporter.enable` to `true`.
2. Execute `curl localhost:9595/metrics` on management server to make sure that prometheus is working.
3. Stop any agent.
4. Run `curl localhost:9595/metrics | grep cloudstack_host_missing_info` you get nothing in output …
> Add missing hosts info to the prometheus exporter output.

- api/src/main/java/org/apache/cloudstack/api/command/user/loadbalancer/ListLoadBalancerRuleInstancesCmd.java
- server/src/main/java/com/cloud/network/lb/LoadBalancingRulesManagerImpl.java
The listLoadBalancerRuleInstances API does not have any logs providing useful information. This PR adds logs to this API in order to facilitate troubleshooting.
This PR was based on the changes in #6357.
- I created a Load Balancer rule and called the listLoadBalancerRuleInstances API through CloudMonkey. Then, I verified that the command returned the expected response and that the correct messages were logged;
- I created a VM, added it to the rule and called the listLoadBalancerRuleInstances API through CloudMonkey. Then, I verified that the command returned the expected response and that the correct messages were logged.
> Add logs to listLoadBalancerRuleInstances API

- plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterUpgradeWorker.java
- plugins/integrations/kubernetes-service/src/main/resources/script/upgrade-kubernetes.sh
- test/integration/smoke/test_kubernetes_clusters.py
- ui/src/views/compute/CreateKubernetesCluster.vue
This PR fixes the test failures with CKS HA-cluster upgrade.
In production, the CKS HA cluster should have at least 3 control VMs as well.
The etcd cluster requires 3 members to achieve reliable HA. The etcd daemon in control VMs uses RAFT protocol to determine the roles of nodes. During upgrade of CKS with HA, the etcd become unreliable if there are only 2 control VMs.
> CKS: create HA cluster with 3 control VMs instead 2

- .asf.yaml
This enables Github Discussions feature for Apache CloudStack repository. Several tech-savvy users are already using CloudStack issues to report bugs, improvements and ideas, and finding using mailing list old-school. The discussions feature presents a forum and can help community have both users (including non-technical users) and developers on the same platform. Further, the discussions feature is proposed to be connected to the users@ mailing list so traditional users can benefit from discussions happening on Github Discusssions forum.
This PR MUST NOT be merged without consensus, for which please chime in at: https://lists.apache.org/thread/hs0295hw9rnmhoh9l2qo5hc4b62hhvk8
Other Apache TLPs are using this feature already, that you can check here for example: …
> .asf.yaml: Enable Github Discussions for CloudStack

- server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
- server/src/test/java/com/cloud/storage/VolumeApiServiceImplTest.java
ResourceType.volume stores the count of the volume and not the size so increment decrement should be just 1 when assigning a volume to a different account.
> server: fix resource count during assign volume

- plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterResourceModifierActionWorker.java
- plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterScaleWorker.java
This PR fixes the issue #7920 
Issue #7920 happened because of the unhandled CloudRuntime Exception, I've replicated the same scenario even when Global setting enable.dynamic.scale.vm is set to false.
Tested the same before and after fix
Before fix, state stuck in "scaling"
After fix, state first changed to "Alert" and then moved to "Running"
Also tested multiple other operations on the K8s cluster
1. Scale up the cluster with node count
2. Scale down the cluster with node count
3. Combinations of node count and service offering change
Those are all worked fine.
> Handle errors while scaling kubernetes cluster

- engine/schema/src/main/java/com/cloud/upgrade/dao/DatabaseAccessObject.java
- engine/schema/src/main/java/com/cloud/upgrade/dao/DbUpgradeUtils.java
- engine/schema/src/main/java/com/cloud/upgrade/dao/Upgrade41810to41900.java
- engine/schema/src/test/java/com/cloud/upgrade/dao/DatabaseAccessObjectTest.java
This PR adds missing indexes on `alerts` & `events` tables.
For alerts table, some of the queries are part of a couple of APIs and some operations. I have added the index for the same. Ref: 
https://github.com/apache/cloudstack/blob/8f390873772ef59c3ba81c837fffe707ebd80e72/engine/schema/src/main/java/com/cloud/alert/dao/AlertDaoImpl.java#L40-L45
For Events table, we query for `resource_id` & `resource_type` in the UI for a resource's events. Indexes were missing, so I have added those.
**Events** 
`24309` rows
Query:
```sql
SELECT * FROM event_view WHERE event_view.account_type != 5 AND event_view.archived = FALSE AND event_view.resource_id = 3686 AND event_view.resource_type = 'VirtualMachine' ORDER BY event_view.created DESC , event_view.id  LIMIT 0 , 10
```
Before 0.04ms
After 0.004ms
> events,alerts: Add missing indexes

- plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java
- ui/src/views/tools/ImportUnmanagedInstance.vue
- vmware-base/src/main/java/com/cloud/hypervisor/vmware/util/VmwareHelper.java
This PR fixes the failing smoke test for `test_vm_lifecycle_unmanage_import.py` for Vmware and adds a small UI fix on the import wizard
> Fix unmanage VM marvin tests and small UI fixes for import

- core/src/main/java/com/cloud/agent/api/MigrateCommand.java
- core/src/main/java/com/cloud/agent/api/PrepareForMigrationAnswer.java
- engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
- engine/storage/datamotion/src/main/java/org/apache/cloudstack/storage/motion/StorageSystemDataMotionStrategy.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtMigrateCommandWrapper.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtPrepareForMigrationCommandWrapper.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtScaleVmCommandWrapper.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtMigrateCommandWrapperTest.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtPrepareForMigrationCommandWrapperTest.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtScaleVmCommandWrapperTest.java
In Apache CloudStack (ACS), when a VM is deployed in a host with the KVM hypervisor, an XML file is created in the assigned host, which has a property <code>shares</code> that defines the weight of the VM to access the host CPU. The value of this property has no unit, and it is a relative measure to calculate how much CPU a given VM will have in the host. However, this value has a limit, which depends on the version of cgroup utilized by the host's kernel. The problem lies at the range value of shares that varies between both versions: [2, 264144] for cgroups version 1; and [1, 10000] for cgroups version 2. Currently, ACS calculates the value of <code>shares</code> using Equation 1, presented below, where <code>CPU</code> is the number of cores and <code>speed</code> is the CPU frequency; …
> kvm: Add support for cgroupv2

- server/src/main/java/com/cloud/storage/StorageManagerImpl.java
- server/src/test/java/com/cloud/storage/StorageManagerImplTest.java
Fixes #8352
Some managed storages may not need a valid URL to be passed. We can skip check and extraction of host or path from url of such storages.
> server: fix url check for storages without a valid url

- engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
- plugins/hypervisors/simulator/src/main/java/com/cloud/api/commands/ConfigureSimulatorHAProviderState.java
- plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java
- plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageProcessor.java
- test/integration/component/test_escalations_instances.py
- usage/src/main/java/com/cloud/usage/UsageManagerImpl.java
This PR removes some unneeded duplicate words.
> Remove unneeded duplicate words

- ui/src/components/view/ListView.vue
- ui/src/config/section/compute.js
- ui/src/config/section/event.js
- ui/src/config/section/image.js
- ui/src/config/section/network.js
- ui/src/config/section/storage.js
- ui/src/views/AutogenView.vue
The Default View has a `projects` toggle button that allows users to see which resources belong to projects, but there is nothing to indicate which project they belong to.
For this reason, a `project` column was added if the `projects` button is enabled, indicating the name of the project to which the resource belongs.
I created the resources that can be listed outside of a project (instance, guest network, VPC, etc.). Then, I enabled the `projects` button in the Default View and verified that the `project` column was filled with the name of the project that the resources belong to.
> UI: Project column in Default View

- engine/schema/src/main/resources/META-INF/db/schema-41810to41900.sql
- server/src/main/java/com/cloud/network/vpc/VpcManagerImpl.java
- test/integration/component/test_vpc_network.py
This PR updates the conserve mode of default vpc tier offering to conserve_mode=1
so we can create both port forwarding and load balancing rules on a public IP in vpc tiers.
This fixes #8313
> VPC: update default network offering for vpc tier to conserve_mode=1

- test/integration/smoke/test_host_ping.py
Failures seen in #7344 were debugged and it was seen since one of the hosts is in Alert state. VM deployment fails with affinity group.
> test: fix test_host_ping.py to restore original host state

- .github/workflows/ci.yml
- setup/dev/advdualzone.cfg
- test/integration/component/test_affinity_groups_projects.py
- test/integration/smoke/test_list_accounts.py
- test/integration/smoke/test_list_disk_offerings.py
- test/integration/smoke/test_list_domains.py
- test/integration/smoke/test_list_hosts.py
- test/integration/smoke/test_list_service_offerings.py
- test/integration/smoke/test_list_storage_pools.py
- test/integration/smoke/test_list_volumes.py
- test/integration/smoke/test_metrics_api.py
- test/integration/smoke/test_secondary_storage.py
- test/integration/smoke/test_templates.py
This PR adds e2e tests for listing resources
> Add e2e tests for listing resources

- test/integration/smoke/test_vm_life_cycle.py
With this change, a fix is added for failures seen with test_08_migrate_vm or other migration-related tests because the target host is in `Connecting` state,
https://github.com/apache/cloudstack/pull/8356#issuecomment-1865422925
https://github.com/apache/cloudstack/pull/8374#issuecomment-1865028605
and more
> test: additional check to ensure hosts are left in up state

- server/src/main/java/com/cloud/user/PasswordPolicy.java
- server/src/main/java/com/cloud/user/PasswordPolicyImpl.java
This PR changes the `password.policy.regex` default value to empty. With an empty value for the configuration, it is skipped during the password policy check, only when the configuration is set to something different than a blank string, the regex will get checked.  
This way, when creating a user on `org.apache.cloudstack.ldap.LdapAuthenticator#authenticate()`  we won't get an error by default, as a empty value for the password is passed.
> server: skip password policies check on empty password

- framework/spring/module/src/main/java/org/apache/cloudstack/spring/module/model/impl/DefaultModuleDefinitionSet.java
During management server initialization, some `EmptyStackException` and `BeansException` exceptions are always thrown; These exceptions do not affect ACS, however, they can cause confusion when observing the management server startup logs with DEBUG level on. The causes of the exceptions have been addressed.
Without the change, I started the MGMT server with debug logs on and saw the exceptions being logged.
With the change, I started the MGMT server and saw that no exceptions were happening on bootstrap, furthermore, the MGMT server started correctly.
> Fix bootstrap exceptions

- ui/src/views/image/RegisterOrUploadTemplate.vue
Fixes layout for the action buttons on register template form
Before:
After:
> ui: fix layout for action button for template form

- ui/src/views/iam/AddAccount.vue
Fixes setting domainid param default value which was being set to 0.
Before:
After:
> ui: fix default domainid for add account

- server/src/main/java/org/apache/cloudstack/vm/UnmanagedVMsManagerImpl.java
- ui/src/views/tools/ImportUnmanagedInstance.vue
This PR fixes the template selection regression for VMware Ingestion in the UI on 4.19.0 RC1 and adds back the default template selection for VMware
Fixes: #8428 #8432 
Unmanage VM -> Import VM
> Fix VMware VM ingestion template selection and default template failure

- engine/schema/src/main/java/com/cloud/storage/dao/GuestOSHypervisorDaoImpl.java
> engine-schema: fix finding guestos mapping with parent version

- ui/src/components/page/GlobalLayout.vue
Non-admin accounts may not have access to the readyForShutdown API therefore UI should not schedule the job.
Without fix errors can be seen for the readyForShutdown API call when logged in as normal account,
> ui: prevent scheduling readyforshutdown job when api inaccessible

- engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
- engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
- plugins/network-elements/nsx/src/main/java/org/apache/cloudstack/service/NsxApiClient.java
- server/src/main/java/com/cloud/network/vpc/VpcManagerImpl.java
- server/src/main/java/com/cloud/server/ManagementServerImpl.java
- ui/src/views/network/VpcTiersTab.vue
This PR fixes more reported code smells
> NSX: Fix code smells

- engine/schema/src/main/java/com/cloud/hypervisor/dao/HypervisorCapabilitiesDaoImpl.java
- engine/schema/src/main/resources/META-INF/db/schema-41810to41900.sql
Fixes https://github.com/apache/cloudstack/issues/8412
Add support for 8.0.0.2 explicitly to prevent falling over to the parent version
Adds log when hypervisor capabilities falling over to the parent version
> schema,engine-schema: explicit VMware 8.0.0.2, 8.0.0.3 support, logs

- plugins/storage/object/minio/src/main/java/org/apache/cloudstack/storage/datastore/driver/MinIOObjectStoreDriverImpl.java
- plugins/storage/object/minio/src/test/java/org/apache/cloudstack/storage/datastore/driver/MinIOObjectStoreDriverImplTest.java
To prevent error during multi-user access, use account UUID to create/access user on the procider side. Also, update existing secret key for a user that already exist.
1. Create a new account `testuser`
2. Create a minio bucket for the account
3. Delete the account
4. Again create account with the same name
5. Try creating a minio bucket and observe the failure,
```
2024-01-03 12:34:27,976 DEBUG [o.a.c.s.o.BucketApiServiceImpl] (API-Job-Executor-83:ctx-8824ed0d job-95 ctx-1ec9d7a6) (logid:5741e607) Failed to create bucket with name: bucket2
com.cloud.utils.exception.CloudRuntimeException: Bucket access credentials unavailable for account: testuser
at org.apache.cloudstack.storage.datastore.driver.MinIOObjectStoreDriverImpl.createBucket(MinIOObjectStoreDriverImpl.java:103)
at …
```
> minio: fix store user creation

- ui/src/views/compute/RegisterUserData.vue
This PR allows to register managed user data using POST call from UI (to support user data content > 4096 bytes).
Partially fixes #8415 
Manually tested managed user data (content > 4096 bytes) registration from UI.
> Register managed user data using POST call from UI (to support user data content > 4096 bytes)

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtGetUnmanagedInstancesCommandWrapper.java
- server/src/main/java/org/apache/cloudstack/vm/UnmanagedVMsManagerImpl.java
This PR fixes part (issues 2 and3) of #8439 and depends on #8433
1 - Fix of VM insert for VMs with StorPool volumes
2 - Fix of the list/insert unmanaged VMs with RBD volumes
manually tested
> Fix KVM import and list unmanaged VMs

- engine/api/src/main/java/org/apache/cloudstack/engine/orchestration/service/NetworkOrchestrationService.java
- engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
- engine/orchestration/src/test/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestratorTest.java
- engine/schema/src/main/java/com/cloud/network/dao/IPAddressDao.java
- engine/schema/src/main/java/com/cloud/network/dao/IPAddressDaoImpl.java
- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
- server/src/main/java/org/apache/cloudstack/vm/UnmanagedVMsManagerImpl.java
- server/src/test/java/com/cloud/vpc/MockNetworkManagerImpl.java
- server/src/test/java/org/apache/cloudstack/vm/UnmanagedVMsManagerImplTest.java
This PR fixes import unmanaged instances on KVM basic zones, on top of #8433 
Fixes: #8439: point 1
> Fix KVM import unmanaged instances on basic zone

- api/src/main/java/org/apache/cloudstack/cluster/ClusterDrsAlgorithm.java
- plugins/drs/cluster/balanced/src/test/java/org/apache/cloudstack/cluster/BalancedTest.java
- plugins/drs/cluster/condensed/src/test/java/org/apache/cloudstack/cluster/CondensedTest.java
- server/src/main/java/org/apache/cloudstack/cluster/ClusterDrsServiceImpl.java
This PR makes changes to use cluster's free metrics instead of used while computing imbalance for the cluster. This allows DRS to run for clusters where hosts doesn't have the same amount of metrics.
> DRS: Use free metrics instead of used for computation

- engine/schema/src/main/java/com/cloud/storage/dao/VolumeDaoImpl.java
- engine/schema/src/test/java/com/cloud/storage/dao/VolumeDaoImplTest.java
- engine/storage/src/test/java/org/apache/cloudstack/storage/allocator/AbstractStoragePoolAllocatorTest.java
This PR fixes reorder/list pools when cluster details are not set, while deploying vm / attaching volume.
Problem:
Attach volume to a VM fails, on infra with zone-wide pools & vm.allocation.algorithm=userdispersing as the cluster details are not set (passed as null) while reordering / listing pools by volumes.
Solution:
Ignore cluster details when not set, while reordering / listing pools by volumes.
Manually tested Deploy VM, and Attach Volume operations on infra with zone-wide pools & vm.allocation.algorithm=userdispersing
> Fix reorder/list pools when cluster details are not set, while deploying vm / attaching volume

- ui/public/locales/en.json
- ui/src/views/tools/ManageInstances.vue
- ui/src/views/tools/SelectVmwareVcenter.vue
Fixes #8474
Renames labels when importing from VMware
https://github.com/apache/cloudstack/assets/153340/e94578cd-f5fa-40ea-b0e7-a5298066d890
> ui: fix labels when migrating instances from vmware

- server/src/main/java/org/apache/cloudstack/vm/UnmanagedVMsManagerImpl.java
This PR fixes the Vmware to KVM migration issue on main branch
Fixes: #8473 
- Deploy mixed env Vmware + KVM zone
- Install virt-v2v in a KVM host
- Create VM in Vmware
- Unmanage VM
- Import VM selecting source hypervisor = Vmware, action = Migrate existing instances to KVM, migration host = the host with virt-v2v installed -> import succeeds
> Fix Vmware to KVM migration issue

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtGetUnmanagedInstancesCommandWrapper.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtGetUnmanagedInstancesCommandWrapperTest.java
This PR fixes the volumes path on KVM import unmanaged instances
Fixes: #8479 
- Create VM on KVM
- Unmanage VM
- Import unmanaged VM from the same template
- Verify disks path
- Destroy/expunge VM and verify there are no leftover disks
> Fix KVM imported unmanaged VMs disks path
