api/src/org/apache/cloudstack/api/command/user/iso/DeleteIsoCmd.java, ui/scripts/templates.js
Signed-off-by: René Moser <mail@renemoser.net>
=> CLOUDSTACK-8154: Fix typo in response name string: there is an extra 's'

server/src/com/cloud/api/ApiServer.java, server/src/com/cloud/api/ConstantTimeComparator.java, server/src/com/cloud/servlet/ConsoleProxyServlet.java, server/src/com/cloud/user/AccountManagerImpl.java, utils/src/com/cloud/utils/ConstantTimeComparator.java
This limits the likeliness of timing attacks against the API.
See http://codahale.com/a-lesson-in-timing-attacks/ for the
full rationale.
=> Use constant-time comparison functions when checking signatures

setup/db/create-schema-premium.sql
This should fix the problem some people are seeing with cloudstack-setup-databases complaining about 'No database selected'
=> CLOUDSTACK-8157: Add absolute schema references to support MySQL 5.6 better

utils/src/org/apache/cloudstack/utils/auth/SAMLUtils.java
Changed to java.util.Calendar which is a bit more straight forward to use.
Tested and verified that the new certificate is valid for 3 years
=> CLOUDSTACK-8215: SAML changing date calculation

api/src/com/cloud/vm/VirtualMachine.java
When shutting down an instance from the OS, no VM.STOP usage record is being inserted. From usage perspective, instance is still considered as running
https://issues.apache.org/jira/browse/CLOUDSTACK-8262
=> CLOUDSTACK-8262: Missing usage event on FollowAgentPowerOffReport (Instance shutdown from OS)

ui/scripts/system.js
CLOUDSTACK-8245: Scrolling down the network service providers list from the UI never ends
CLOUDSTACK-8246: Add Cluster - Guest traffic label displayed Incorrectly
=> CLOUDSTACK-8245 and CLOUDSTACK-8246

test/integration/smoke/test_regions.py
needs looking into but for now i want the jenkins jobs running
=> test fails unexplicalby while functionality is ok

packaging/centos63/cloud.spec, packaging/centos7/cloud.spec, packaging/fedora20/cloud.spec, packaging/fedora21/cloud.spec, packaging/package.sh
Add distribution fedora21 in packaging/package.sh, help to build rpm for fedora21.
Fix cloud.spec for building management rpm, need not create agent dir but agetn rpm (kvm host agent). When user install management and agent in the same host, it causes yum problem about agent dir recover by another.
=> Add distribution fedora21 in packaging.sh and delete the agent dir in cloud.spec

tools/apidoc/gen_toc.py
These small changes allow the build to succeed on all versions of python from 2.6 up (2.5 will break). This covers all serious candidate platforms for running cloudstack.
=> Support all pythons from 2.6 up.

api/src/org/apache/cloudstack/api/command/user/vm/ListVMsCmd.java
The name parameter causes a substring match, not an exact match, which needs to be documented.
=> modify description for name parameter in ListVMsCmd.java

plugins/hypervisors/ovm3/src/main/java/com/cloud/hypervisor/ovm3/objects/StoragePlugin.java, plugins/hypervisors/ovm3/src/main/java/com/cloud/hypervisor/ovm3/objects/Xen.java, plugins/hypervisors/ovm3/src/main/java/com/cloud/hypervisor/ovm3/resources/Ovm3StorageProcessor.java, plugins/hypervisors/ovm3/src/main/java/com/cloud/hypervisor/ovm3/resources/helpers/Ovm3StoragePool.java, plugins/hypervisors/ovm3/src/main/java/com/cloud/hypervisor/ovm3/resources/helpers/Ovm3VmSupport.java, plugins/hypervisors/ovm3/src/test/java/com/cloud/hypervisor/ovm3/objects/StoragePluginTest.java
Some of the unit tests fail on Windows as File.separator was used, using it might seem like a good idea as suggested by Sonarcube, but all the paths generated with it are actually only run on Linux hosts as the agent for OVM3 runs on linux. So using the File.seperator is a real bad idea, not just for the tests but also for someone running the manager on a windows host.
=> Ovm3firefix: fixes for unit tests on Windows and for running management on Windows.

core/src/com/cloud/agent/api/CheckRouterAnswer.java, core/src/com/cloud/agent/api/SetupGuestNetworkCommand.java, core/test/com/cloud/agent/resource/virtualnetwork/VirtualRoutingResourceTest.java, engine/schema/src/com/cloud/upgrade/dao/Upgrade451to460.java, engine/schema/src/com/cloud/vm/DomainRouterVO.java, plugins/hypervisors/simulator/src/com/cloud/agent/manager/MockVmManager.java, plugins/hypervisors/simulator/src/com/cloud/agent/manager/MockVmManagerImpl.java, plugins/hypervisors/simulator/src/com/cloud/agent/manager/SimulatorManagerImpl.java, plugins/network-elements/elastic-loadbalancer/src/com/cloud/network/lb/LoadBalanceRuleHandler.java, plugins/network-elements/internal-loadbalancer/src/org/apache/cloudstack/network/lb/InternalLoadBalancerVMManagerImpl.java, plugins/network-elements/internal-loadbalancer/test/org/apache/cloudstack/internallbvmmgr/InternalLBVMManagerTest.java, plugins/network-elements/internal-loadbalancer/test/org/apache/cloudstack/internallbvmmgr/InternalLBVMServiceTest.java, server/src/com/cloud/network/router/CommandSetupHelper.java, server/src/com/cloud/network/router/NetworkHelper.java, server/src/com/cloud/network/router/NetworkHelperImpl.java, server/src/com/cloud/network/router/VirtualNetworkApplianceManagerImpl.java, server/src/org/cloud/network/router/deployment/RouterDeploymentDefinition.java, server/test/com/cloud/network/element/VirtualRouterElementTest.java, server/test/org/cloud/network/router/deployment/RouterDeploymentDefinitionTest.java, systemvm/patches/debian/config/opt/cloud/bin/checkrouter.sh, systemvm/patches/debian/config/opt/cloud/templates/checkrouter.sh.templ
- With the changes added by the rVPC work, the bump priority became deprecated.
This commit includes a refactor to get it removed from the following resources:
* Java classes
* domain_router table - removing the is_priority_bumpup column
* Fixing unit tests
All changes were tested with:
XenServer 6.2 running under our VMWare zone
CloudStack Management Server running on MacBook Pro
MySql running on MackBook Pro
Storage Type: Local
Test Create Account and user for that account ... === TestName: test_01_create_account | Status : SUCCESS ===
ok
Test Sub domain allowed to launch VM  when a Domain level zone is created ... === TestName: test_01_add_vm_to_subdomain | Status : SUCCESS ===
ok
Test delete domain without force option ... === TestName: test_DeleteDomain | Status : SUCCESS ===
ok
Test …
=> Bump priority stragety is no longer used for redundant virtual routers

scripts/vm/hypervisor/kvm/kvmheartbeat.sh
The recent discussed improvement has the risk that if 'sync' hangs, the reboot may be delayed in the same way as the 'reboot' command would do. To work around, we're adding a 5 second timeout. If it cannot sync in 5 seconds, it will not succeed anyway and we should proceed the reset.
@snuf: As a future improvement: Could we use your OVM3 heartbeat script for other hypervisors as well? One way to do it seems like a nice idea :-)
=> KVM: make sure sync cannot block reboot

ui/scripts/accounts.js, ui/scripts/accountsWizard.js, ui/scripts/configuration.js, ui/scripts/events.js, ui/scripts/instances.js, ui/scripts/network.js, ui/scripts/projects.js, ui/scripts/regions.js, ui/scripts/sharedFunctions.js, ui/scripts/storage.js, ui/scripts/system.js
As recently discussed on the dev list:
This sorts the domain lists based on their path. Especially handy when having a lot of domains,like in a public cloud.
=> CLOUDSTACK-6543 Sort domain lists in UI

systemvm/patches/debian/config/etc/rc.local, systemvm/patches/debian/config/opt/cloud/bin/configure.py, systemvm/patches/debian/config/opt/cloud/bin/cs/CsHelper.py
- After configuration save the ipdated in files
* /etc/iptables/router_rules.v4 and /etc/iptables/router_rules.v6
* Reload the configuration on reboot via the /etc/rc.local using iptables-restore
- All the information about the router VMs is now persisted due to the work on the rVPC/Persistent SystemVM done in the few months ago. The missing bit was the iptables configuration, which was not surviving a crash or reboot not done via the management server. 
- Manual tests
* Create single VPC, 3 Tiers, 3 VMs, 3 pub IPs
* Connect to router and reboot it
* Wait for the router to come back and check IPtables/connect to VMs
* Create redundant VPC, 3 Tiers, 3 VMs, 3 pub IPs
* Connect to router and reboot it
* Wait for the router to come back and check IPtables/connect to VMs
* Create isolated …
=> Make the routers iptables config persistent through reboot/crash

api/src/org/apache/cloudstack/api/response/RemoteAccessVpnResponse.java, scripts/vm/hypervisor/xenserver/vmops, server/src/com/cloud/api/ApiResponseHelper.java, systemvm/patches/debian/config/opt/cloud/bin/firewall_egress.sh, systemvm/patches/debian/vpn/opt/cloud/bin/vpn_l2tp.sh
This fixes the issue of Security Groups not working in case of XenServer 6.5;
- Uses nethash ipset data-structure to store CIDRs (efficient than iphash and
avoids overflow errors in case users add /8 /4 ingress/egress cidrs)
- Support for ipset versions both on 6.2 and 6.5, both have different outputs. This
fixes the issue of destroy_network_rules_for_vm failing
- Implements defensive filtering of list, instead of popping last item without
checking if it's None or empty
- Greps using names that are 'quoted' to avoid bash errors
- Before setting up new network rule, tries to clean and remove old ipset entry
- Idents, whitespace and naming fixes
PS. This is my 1000th commit to the :monkey_face: project :)
=> CLOUDSTACK-8395: vmops plugin should work on both XS 6.5 and 6.2

server/src/com/cloud/ha/AbstractInvestigatorImpl.java
When a full cluster is down or unreachable,
CloudStack currently reports everything the
same as the last known state, which is usually
Up. When it cannot reach a host and cannot
reach another host in the same cluster either,
it returns null and says "I don't know". This
prevents it from reporting the problem. Now,
we return an Alert or Disconnected state so
proper action can be taken.
Also logging was added, so we know what part
of the code put it to Alert or Disconnected.
When the host is available again, it goes
from Alert state back to Up and CloudStack
starts HA work to recover the VMs. I tested
it on 4.6/master and it works fine now.
As this is a nasty bug, we might want to fix
this also in 4.5 and 4.4.
Thanks to @dahn and @snuf for their
help solving this issue.
=> return a state instead of null in AbstractInvestigatorImpl

plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/MigrateKVMAsync.java
- New class is MigrateKVMAsync
I added the license header and execute a full build:
[INFO] Total time: 09:48 min
[INFO] Finished at: 2015-05-13T11:56:34+02:00
[INFO] Final Memory: 124M/849M
=> Fixing license header in a file added during the LibVirt refactor

tools/appliance/definitions/systemvmtemplate/configure_systemvm_services.sh
The console-setup service brings a nice font to the console, but why would we want to use it. In most cases it takes a <10 seconds to set it up. When using nested hypervising, I found this takes much longer time that causes tests to time-out. I'd suggest turning off these unused services. They are not required for the services the systemvm provides.
=> Systemvm: Disable services that slow down boot

plugins/hypervisors/kvm/test/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java
@bhaisaab and @DaanHooglan, there goes another one.
It has only unit tests changes, so not a big deal with integration tests. The Libvirt tests are running in 2.889 sec in the KVM environment, instead of  257.879 sec
Removing real IPs from the tests because they cause a long running time for LibvirtComputingResourceTest
- In a local machine it takes 1.977s, but in a KVM test environment it's taking 257.879 sec
=> CLOUDSTACK-8486

api/src/org/apache/cloudstack/api/command/user/vm/DeployVMCmd.java, engine/orchestration/src/org/apache/cloudstack/engine/orchestration/VolumeOrchestrator.java, server/src/com/cloud/vm/UserVmManagerImpl.java
The new behavior (since 4.4) rootdisksize for KVM hyperviser when you deploy a new VM use GB value. Update Docs Api to indicate the value type.
Cherry-pick to 4.5 and 4.4 should be done
=> CLOUDSTACK-6181 Specify GB for the value of rootdisksize parameter. Add some Bytes/GB for log or exception messages. Fix Gb->GB.

plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
We don't need an external script to investigate the format of the RBD volume,
we only have to ask Libvirt to resize the volume and that will ask librbd to
do so.
Backport for 4.4, original commit: 173909e99d85cfcc85b017bc426950f9f16fddf0
Requested by Andrija Panić http://markmail.org/thread/gau2xngqjpq5cza7
=> CLOUDSTACK-6181: Allow RBD volumes to be resized

pom.xml, server/pom.xml
This fixes a big performance issue with random number generation with more recent kernels and java versions in linux, the impact is specially higher on VMs
Some tests (that use random number generation) in some environments take randomly 1 - 20 mins to perform tests that should take only seconds to run.
This PR is just intended for fixing it on the tests.
=> Change tests random number generator to /dev/urandom

plugins/user-authenticators/ldap/src/org/apache/cloudstack/api/command/LdapCreateAccountCmd.java, plugins/user-authenticators/ldap/src/org/apache/cloudstack/api/command/LdapImportUsersCmd.java, plugins/user-authenticators/ldap/test/groovy/org/apache/cloudstack/ldap/LdapCreateAccountCmdSpec.groovy
byte[].toString() would give reference to the array (ex: [B@6c521576 )
but not the original string.  used new String() to get the text.
added a unittest to validate
=> Fixed CLOUDSTACK-8551 Findbugs warning in LdapCreateAccountCmd.java

tools/travis/before_install.sh
Output status of disk and memory on build host for some extra info on build environment before start
This should fix the travis problem made visible in this run:
https://travis-ci.org/apache/cloudstack/jobs/68291716
=> Cleanup stale files in /tmp which is filling up during some runs

plugins/user-authenticators/ldap/pom.xml, plugins/user-authenticators/ldap/resources/META-INF/cloudstack/ldap/spring-ldap-context.xml, plugins/user-authenticators/ldap/src/org/apache/cloudstack/ldap/ADLdapUserManagerImpl.java, plugins/user-authenticators/ldap/src/org/apache/cloudstack/ldap/LdapConfiguration.java, plugins/user-authenticators/ldap/src/org/apache/cloudstack/ldap/LdapManagerImpl.java, plugins/user-authenticators/ldap/src/org/apache/cloudstack/ldap/LdapUserManager.java, plugins/user-authenticators/ldap/src/org/apache/cloudstack/ldap/LdapUserManagerFactory.java, plugins/user-authenticators/ldap/src/org/apache/cloudstack/ldap/OpenLdapUserManagerImpl.java, plugins/user-authenticators/ldap/test/groovy/org/apache/cloudstack/ldap/ADLdapUserManagerImplSpec.groovy, plugins/user-authenticators/ldap/test/groovy/org/apache/cloudstack/ldap/LdapConfigurationSpec.groovy, plugins/user-authenticators/ldap/test/groovy/org/apache/cloudstack/ldap/LdapCreateAccountCmdSpec.groovy, plugins/user-authenticators/ldap/test/groovy/org/apache/cloudstack/ldap/LdapManagerImplSpec.groovy, plugins/user-authenticators/ldap/test/groovy/org/apache/cloudstack/ldap/LdapUserManagerFactorySpec.groovy, plugins/user-authenticators/ldap/test/groovy/org/apache/cloudstack/ldap/OpenLdapUserManagerSpec.groovy
added a new configuration to select the appropriate ldap implementation
incase of microsoft AD enabled nested querying of group members
moved LdapUserManager to an interface and added separate implementations
for openLdap and microsoft AD
Added unit tests for the new code
=> CLOUDSTACK-8596 ability to query nested groups for Microsoft AD

pom.xml, utils/src/com/cloud/utils/S3Utils.java
The newer SDKs API changed which causes our S3 Template Downloader to never complete.
Although we should fix the Template Downloader we can revert to the old AWS SDK for now.
The fix on the longer run will be rewriting the S3 Template Downloader.
Two methods had to be disabled for now since the old SDK does not support them. They can
be re-enabled when the Template Downloader has been fixed.
=> CLOUDSTACK-8640: Revert to AWS SDK 1.3.22

utils/src/com/cloud/utils/S3Utils.java
It would only return objectSummaries when the anwser from the S3 System was truncated. Due to: debcbcc1454789936407583fe0aba8e158b16cad
=> CLOUDSTACK-8703: Fixed issue when listing directory on S3.

plugins/storage/volume/solidfire/src/org/apache/cloudstack/storage/datastore/driver/SolidFirePrimaryDataStoreDriver.java
If the admin specifies a hypervisor snapshot reserve value that is below a particular number, we want to just use that number.
For example, if the admin specifies 5% for hypervisor snapshot reserve, we want to use - at least - 10% now (it used to be 50%, but that can make the backend volume overly large in certain situations).
This only impacts the SolidFire storage plug-in.
=> Reduce the lowest hypervisor snapshot reserve value from 50% to 10%

setup/db/db/schema-452to460.sql
'id' in the region table should not be an autoincrement unlike other
tables. This is because, region ids must be in sync across installs and
hence is accepted as input to the addRegions api.
It is not a good practise to override id for this purpose. another
column 'regionId' has to be created and used(CLOUDSTACK-8706). until it
is fixed, id should never be autoincrement in regions table.
@kishankavala @bhaisaab @DaanHoogland please review
=> CLOUDSTACK-8696: Create Region fails with exception

server/src/com/cloud/network/router/VirtualNetworkApplianceManagerImpl.java
This prevents the out-of-band migrate alerts being generated for non-routers.
=> CLOUDSTACK-8709 No out of band migrate alert for non-routers

server/src/com/cloud/template/TemplateManagerImpl.java
..... using updateTemplatePermissions API
Consider this scenario :
In a domain, there are three User Accounts UA1, UA2,UA3
A private template is registered by UA1
Through the updateTemplatePermissions API, UA1 gives permission to both UA2 and UA3
Now, UA2, having been shared the template, can remove the permission of UA3(or add permissions to another account).
EXPECTED BEHAVIOR :
UA2 should not be able to to add/remove permissions of other accounts.
=> Implemented condition that only admin or owner of the template can change its permissions

scripts/storage/secondary/cloud-install-sys-tmplt
The script that you run to initially setup secondary storage, had some errors. As it now depends on /etc/cloudstack/management/db.properties, it did not work any more on my development environment.
I defined some defaults that work in development environments (those are sane defaults anyway), then check if the /etc/cloudstack/management/db.properties file exists. If so, it reads from there and gets the vars just like before. If not, it keeps the defaults unless of course someone overrides them on the command line.
While working on the script, I also fixed the indentation and found a query that was not yet using the -P mysql port variable.
I tested it both on my development environment as well as in an environment installed from RPM (where you'd have …
=> Improve cloud-install-sys-tmplt to work in dev environment again

test/integration/testpaths/testpath_same_vm_name.py
-Adding "cls.hypervisor = cls.testClient.getHypervisorInfo()"
-Fixed pep8 issues
=> CLOUDSTACK-8693-Adding-missing-code-in-testpath_same_vm_name.py_testpath

systemvm/patches/debian/config/opt/cloud/bin/configure.py
@remibergsma @wilderrodrigues 
Moved applying iptables rules apply after vpn configuration so that vpn specific rules also get applied
=> CLOUDSTACK-8710: Fixed applying iptables rules for s2s vpn

systemvm/patches/debian/config/opt/cloud/bin/configure.py, systemvm/patches/debian/config/opt/cloud/bin/cs/CsFile.py
This is work done together with @jayapalu on fixing the site2site VPN. The first part was done in PR #690 by @jayapalu. On top of that, some other fixes were needed and those are added in this PR. It made sense to make a new PR which includes all fixes so we can actually test it. 
The original PR #690 is already merged into this one, so can be closed. Since the commit ids are kept the same, merging this will close both.
I closely compared the 4.4/4.5 implementation with the new 4.6 one. I did not only make it work, but also added some security improvements (some of which were also in 4.4/4.5). I noticed the pre shared key was being logged, so removed that as well.
This is how I tested and verified it:
https://github.com/schubergphilis/MCT-shared/tree/master/helper_scripts/cloudstack/vpn_te …
=> Fix site-to-site VPN feature

utils/src/com/cloud/utils/StringUtils.java, vmware-base/src/com/cloud/hypervisor/vmware/util/VmwareContext.java, vmware-base/test/com/cloud/hypervisor/vmware/util/VmwareContextTest.java
Added a new private method getCharSetFromConnection() which checks if
the connection charset is null and if it is null, returns
StringUtils.getPreferredCharset
regression caused by commit f03411ca0436c8b52f5e60b0c8820fd1d1ba2ff6
=> CLOUDSTACK-8669: create volume failed due to null charset

ui/scripts/accounts.js
See Cloudstack issue CLOUDSTACK-8742 & CLOUDSTACK-8649 for information.
=> Removed double encoding of Public Key from JS.

test/integration/component/maint/testpath_disablestoragepool.py, tools/marvin/marvin/lib/base.py
CLOUDSTACK-8738: Added Maintenance mode related fixes into base.py for test_disablestoragepool.
Also fixed pep8 issues in script, most of them for E501 (long lines) with max-line-length set to default
Test Result:
Test Steps: ... === TestName: test_01_disable_enable_pool_1_host | Status : SUCCESS ===
ok
Test Steps: ... === TestName: test_01_disable_enable_pool_2_CLUSTER | Status : SUCCESS ===
ok
Test Steps: ... SKIP: No ZONE  storage pools found
Test Steps: ... === TestName: test_02_vm_operations_on_disabled_pool_1_host | Status : SUCCESS ===
ok
Test Steps: ... === TestName: test_02_vm_operations_on_disabled_pool_2_CLUSTER | Status : SUCCESS ===
ok
Test Steps: ... SKIP: No ZONE wide storage pools found
Test Steps: ... === TestName: test_01_cross_cluster_attach_disk | Status : SUCCESS === …
=> Disablestorage pep8

api/src/com/cloud/template/TemplateApiService.java, api/src/org/apache/cloudstack/api/command/admin/template/PrepareTemplateCmd.java, server/src/com/cloud/template/TemplateManagerImpl.java, server/test/com/cloud/template/TemplateManagerImplTest.java
Update prepare template api to seed/prepare a template only on a given primary storage. Currently, the prepare template api will seed/prepare a given template on all the primary storage pools in a zone. If however, a user wishes to prepare a template only a particular storage pool, it isn't possible. Updated the api to take storage pool id as an optional parameter. If the pool id is provided then the template is prepared only on the given primary storage pool. Also added unit tests to validate the functionality
=> CLOUDSTACK-8687: Prepare template only on a given storage pool

scripts/vm/hypervisor/kvm/setup-cgroups.sh
The RHEL 7 version string is hard coded and misses CentOS 7.
=> Apply RHEL 7 fix for comounted cgroups to CentOS 7 KVM hypervisors as well

tools/git/git-fwd-merge, tools/git/git-pr
As it is now, additions to CloudStack need to go through a GitHub PR and, if accepted, merged to the Apache remote (not in GitHub). This means that merging a PR for CloudStack is a bit more involved than merging a normal GitHub PR. In addition to that, a PR that fixes something in an older release needs to be merged against a release branch, and then forward merged up to master (if applicable).
To help with these two kinds of merges, @remibergsma, @karuturi, @DaanHoogland and myself, have created two scripts (contributed in this PR).
One script (**git-pr**) helps in merging a PR from GitHub to the Apache remote. The script will read the PR info using GitHub's API and will create a merge commit that contains the same commit message a normal GitHub PR merge commit, plus, as extra info, a …
=> Add scripts to merge PRs and release fixes forward

plugins/hypervisors/xenserver/src/com/cloud/hypervisor/xenserver/resource/CitrixResourceBase.java, plugins/hypervisors/xenserver/src/com/cloud/hypervisor/xenserver/resource/XcpOssResource.java, plugins/hypervisors/xenserver/src/com/cloud/hypervisor/xenserver/resource/XcpServerResource.java, plugins/hypervisors/xenserver/src/com/cloud/hypervisor/xenserver/resource/XenServer56FP1Resource.java, plugins/hypervisors/xenserver/src/com/cloud/hypervisor/xenserver/resource/XenServer56Resource.java, plugins/hypervisors/xenserver/src/com/cloud/hypervisor/xenserver/resource/XenServer56SP2Resource.java, plugins/hypervisors/xenserver/src/com/cloud/hypervisor/xenserver/resource/XenServer600Resource.java, plugins/hypervisors/xenserver/src/com/cloud/hypervisor/xenserver/resource/XenServer650Resource.java, plugins/hypervisors/xenserver/src/com/cloud/hypervisor/xenserver/resource/Xenserver625Resource.java, plugins/hypervisors/xenserver/test/com/cloud/hypervisor/xenserver/resource/XcpOssResourcePathTest.java, plugins/hypervisors/xenserver/test/com/cloud/hypervisor/xenserver/resource/XcpServerResourcePathTest.java, plugins/hypervisors/xenserver/test/com/cloud/hypervisor/xenserver/resource/XenServer56FP1ResourcePathTest.java, plugins/hypervisors/xenserver/test/com/cloud/hypervisor/xenserver/resource/XenServer56ResourcePathTest.java, plugins/hypervisors/xenserver/test/com/cloud/hypervisor/xenserver/resource/XenServer56SP2ResourcePathTest.java, plugins/hypervisors/xenserver/test/com/cloud/hypervisor/xenserver/resource/XenServer600ResourcePathTest.java, plugins/hypervisors/xenserver/test/com/cloud/hypervisor/xenserver/resource/XenServer625ResourcePathTest.java, plugins/hypervisors/xenserver/test/com/cloud/hypervisor/xenserver/resource/XenServer650ResourcePathTest.java
Removed unnecessary duplicated code by having the body of the getPatchFiles method only in the CitrixResourceBase superclass. Given that all of its implementations consisted of the same code except for the path which contains the necessary file for that implementation. An abstract method getPatchFilePath was created in the CitrixResourceBase superclass so that each implementation may return the path containing the specific file needed by that implementation.
Test cases were created for each implementation, simple as they may be. One assert is made to verify that the path returned by each implementation corresponds to the path that was previously specified on each getPatchFiles implementation.
=> Removed duplicate code in CitrixResourceBase and its subclasses

engine/orchestration/src/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java, engine/schema/src/com/cloud/vm/NicVO.java, plugins/network-elements/internal-loadbalancer/test/org/apache/cloudstack/internallbvmmgr/InternalLBVMManagerTest.java, server/src/com/cloud/network/guru/ExternalGuestNetworkGuru.java, server/src/com/cloud/network/router/VpcVirtualNetworkApplianceManagerImpl.java, server/src/com/cloud/network/rules/NicPlugInOutRules.java, server/src/com/cloud/vm/UserVmManagerImpl.java
Renamed set*() methods to correct naming.
=> Fix for the NicVO.java regression.

framework/cluster/src/com/cloud/cluster/ClusterServiceServletAdapter.java, framework/cluster/test/com/cloud/cluster/ClusterServiceServletAdapterTest.java, framework/jobs/src/org/apache/cloudstack/framework/jobs/impl/SyncQueueManagerImpl.java
This is happening as ClusterServiceServletAdapter is started after ClusteredAgentManagerImpl.
Fix is to start ClusterServiceServletAdapter before ClusteredAgentManagerImpl.
Also added a log message in SyncQueueManagerImpl.
=> CLOUDSTACK-8733: Host stuck in rebalancing state during agent LB

framework/cluster/src/com/cloud/cluster/ClusterManagerImpl.java
We got a lot of debugging information in management server log because of this.
=> CLOUDSTACK-8761: Replace some profiler.getDuration with profiler.getDurationInMillis fter commit 5557ad55

plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/BridgeVifDriver.java
Based on @jburwell's comment on PR #718
=> CLOUDSTACK-8749: Add checks to prevent malformed/unexpected input

engine/orchestration/src/com/cloud/vm/VirtualMachineManagerImpl.java, engine/orchestration/src/com/cloud/vm/VmWorkMigrateForScale.java
This is caused by serialization failure for VmWorkMigrateForScale object. Replaced DeployDestination member present in VmWorkMigrateForScale with serializable types.
Haven't added any unit test as couldn't find a clean way to do it. Simply adding a test to do (de)serialization won't help catch any new member addition to the type which breaks serializability.
=> CLOUDSTACK-8754: VM migration triggered by dynamic scaling is failing

plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtResizeVolumeCommandWrapper.java
This relates to [CLOUDSTACK-8732](https://issues.apache.org/jira/browse/CLOUDSTACK-8732)
Before this commit the call to `getResizeScriptType` would throw an exception (earlier versions returned `null`, which was fine) - this caused the RBD case to fail. By changing the default to notify only we fix the case for any non-CLVM and non-QCOW cases, too.
This is RBD for now, but this should extend to new storage types supported by Libvirt natively in future.
This is my first attempted contribution: I can see a case for adding RBD logic to the actual getResizeScriptType call, too, but I felt that putting it `LibvirtResizeVolumeCommandWrapper.java` kept the special-casing of RBD (and comments about that) in one place.
With Libvirt 1.2.2 this actually doesn't do the right thing - but it does do …
=> Default to notify only script to handle non-CLVM/QCOW cases.

utils/src/test/java/com/cloud/utils/TestProfiler.java
- The difference between 2 consecutive calls to System.nanoTime() returns a resolution that depends on the OS implementation. Due to that, the test was failing in an intermittent manner.
- Today we decided to remove the test since it was not testing a direct feature of ACS
I did not create an issue on Jira because it's only about removing an unit test. There is no bug fix involved or feature developed.
@miguelaferreira @remibergsma @bhaisaab @DaanHoogland 
Could you have a look at this change, please?
Cheers,
Wilder
=> Removing unit test that was failing to cover the resolution of the nano time

services/console-proxy-rdp/rdpconsole/src/test/java/rdpclient/MockServerTest.java
The ciphersuite could be different on os. 
Sometimes the MockServerTest fails due to the ciphersuite does not work (for instance misconfiguration).
SSL_DH_anon_WITH_3DES_EDE_CBC_SHA has 168-bit encryption and anonymous auth, which is suitable for SSL testing.
=> CLOUDSTACK-8783: specify ciphersuite SSL_DH_anon_WITH_3DES_EDE_CBC_SHA in MockServerTest.java

server/src/com/cloud/api/ApiResponseHelper.java
This is in continuation with the PR #618.
=> Coverity Issue: Null pointer dereferencing fixed

utils/src/test/java/com/cloud/utils/rest/BasicRestClientTest.java
BasicRestClientTest will fail if the port 443 is open on localhost.
use fakelocalhost instead of localhost can fix it.
Please see the latest discussion in https://github.com/apache/cloudstack/pull/737
=> use fakelocalhost in BasicRestClientTest

plugins/hypervisors/simulator/src/com/cloud/agent/manager/MockVmManager.java, plugins/hypervisors/simulator/src/com/cloud/agent/manager/MockVmManagerImpl.java, plugins/hypervisors/simulator/src/com/cloud/agent/manager/SimulatorManagerImpl.java, server/src/com/cloud/vm/UserVmManagerImpl.java, setup/dev/advanced.cfg, test/integration/smoke/test_scale_vm.py
- Support for ScaleVmCommand/NetworkRulesVmSecondaryIpCommand in resource layer
- Added support for scaling up a running VM in simulator
- Fixed some method names not following convention
In order to test PR https://github.com/apache/cloudstack/pull/725 using simulator some of these changes are needed.
Based on the way HV check is present in the scale VM API, had to explicitly put simulator related check to allow support. The ideal way would be to remove all these HV specific check from code and made them some configuration (by putting them in hypervisor_capabilities table in DB). But that will be a bigger effort outside the scope of this PR.
=> Made following fixes in simulator

utils/src/main/java/com/cloud/utils/log/CglibThrowableRenderer.java, utils/src/test/java/com/cloud/utils/log/CglibThrowableRendererTest.java
Following our discussions on mailing list, here is a PR with a proposal for an improvement on “CglibThrowableRenderer”. We would still have to define a number to limit the stack traces of causes (I randomly chose 3, just to get the code running). The test case is also not good in my opinion, but I ran out of ideas (waiting for suggestions on that).
=> Proposal for an improved CglibThrowableRenderer

plugins/hypervisors/hyperv/src/com/cloud/ha/HypervInvestigator.java
Commit 6a4927f660f776bcbd12ae45f4e63ae2c2e96774 made the HyperV investigator return false instead of null.
Returning false means the VM is NOT running, returning null means "I don't know". In 4.4 I experienced corruption because of HyperV returning false, instead of null.
Tonight I experienced corruption when one of our management servers went down (out-of-memory, not root caused yet). While all hypervisors that were connected to this management server were connecting the other, HA work started as well with investigators. HyperV happily reported everything as down (while it was still running), causing a mess.
In 4.5 and master this was already fixed. If you know a better way to fix this, please let me know!
This may cause another FindBugs alert, not sure how to resolve that. I just want …
=> Have HyperV behave in 4.4 and return null instead of false

plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtMigrateCommandWrapper.java, plugins/hypervisors/kvm/test/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java
https://issues.apache.org/jira/browse/CLOUDSTACK-8792
A flag being passed to Libvirt assumes v1.0.0 or later.
We need to put a check in the code to pass in a different flag if the version of Libvirt is < 1.0.0.
=> Support live migration on older version of Libvirt

agent/conf/agent.properties, plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java, utils/src/org/apache/cloudstack/utils/hypervisor/HypervisorUtils.java, utils/test/org/apache/cloudstack/utils/hypervisor/HypervisorUtilsTest.java
Implements a VM volume/disk file activity checker that checks if QCOW2 file
has been changed before starting the VM. This is useful as a pessimistic
approach to save VMs that were running on faulty hosts that CloudStack could
try to launch on other hosts while the host was not cleanly fenced. This is
optional and available only if you enable the settings in agent.properties
file, on per-host basis.
=> CLOUDSTACK-8762: Check to confirm disk activity before starting a VM

server/src/com/cloud/network/router/NetworkHelperImpl.java, test/integration/component/test_vpc_router_nics.py
How to reproduce the problem:
1. Stop/Destroy the VPC router
2. Add a virtual machine to one of the VPC tier - it will trigger a VPC router creation
3. Router is created, but the NICs are not configured
How to recover without this fix:
1. Stop/destroy the VPC router and restart the VPC
Side effects: private gateways could be misconfigured.
Root cause:
In the VpcNetworkHelperImpl.configureDefaultNics() method, the guest network nic was added in the map prior to the control and public NICs. The order in the map should not matter, however in the LibvirtComputingResource.createVifs() method, there is a logic that relies on the device index - the array index - in order to create the  control nic. I advise a refactor on the data model in order to be able to identify the NIC type instead of …
=> CLOUDSTACK-8759 - Destroying VPC router results in a new unusable VPC router

ui/dictionary2.jsp
due to missing comma in the jsp, all the labels below it are broken leading to showing keys instead of strings in UI
=> Fixed issue: UI labels are display with key. ex: label.yes

debian/control
A few dependencies have been updated to their latest version and some
have been removed.
The ordering for some dependencies has been changed so that we will
depend on Java 8 over Java 7 when doing a new install.
=> debian: Updated dependencies for Packages

server/src/com/cloud/server/ManagementServerImpl.java, server/test/com/cloud/server/ManagementServerImplTest.java, setup/db/db/schema-452to460.sql
Currently the user can register same key with different names. Upon listing the VM's the name which got registered first is being returned and not the actual one. Anyhow this behavior is rare and not good. I have added a UNIQUE constraint on the ssh_keypairs table and also made sure that the previous registered keys(with duplicates) get deleted.
=> CLOUDSTACK-8727: API call listVirtualMachines returns same keypair

plugins/hypervisors/ovm/scripts/vm/hypervisor/ovm/OvmSecurityGroupModule.py, scripts/vm/network/security_group.py
To configure firewall rules, CloudStack modifies `/etc/sysctl.conf` and
execute those modifications. This may be harmful for several reasons:
1. `/etc/sysctl.conf` may be managed by some configuration management
system. Such a system will constantly restore the previous version.
2. `/etc/sysctl.conf` may contain additional properties that have been
changed later by some system administrator (for example, once a
firewall has been configured, forwarding may have been activated
while it is disabled in `/etc/sysctl.conf`). Executing the file
again at a later time may disrupt the system.
3. Entries are added again and again. `/etc/sysctl.conf` will contain
the same directives repeated several times.
Using a configuration file is not needed as `sysctl` is able to directly
modify sysctl values …
=> sysctl: don't modify /etc/sysctl.conf

server/src/com/cloud/network/router/NetworkHelperImpl.java, server/src/com/cloud/network/router/VpcNetworkHelperImpl.java
Hi there,
I refactored the configureDefaultNics() method in order to split the implementations for Routers and VPC Routers.
The following tests were executed:
* test_vm_life_cycle
* test_routers
* test_vpc_router_nics
* test_vpc_routers
* test_vpc_offerings
@remibergsma @bhaisaab @koushik-das @miguelaferreira @DaanHoogland @karuturi , could you please have a look/test this PR?
Thanks in advance.
Cheers,
Wilder
=> CLOUDSTACK-8814 - Refactoring the configuration of Routers and VPC routers nics

api/src/org/apache/cloudstack/api/response/FirewallResponse.java, server/src/com/cloud/api/ApiResponseHelper.java
This is my first contribution to Apache CloudStack. The return values for endpoint and startpoint have now been changed to Integer instead of String. Please let me know if this is the only change that is required or if there are additional files which will be impacted by this change which require modification also.
=> This is the fix for the JIRA issue CLOUDSTACK-8817.

api/src/com/cloud/event/EventTypes.java, api/src/org/apache/cloudstack/api/command/admin/account/DeleteAccountCmd.java, api/src/org/apache/cloudstack/context/CallContext.java, engine/orchestration/src/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java, server/src/com/cloud/api/ApiDispatcher.java, server/src/com/cloud/api/ApiServer.java, server/src/com/cloud/api/dispatch/ParamProcessWorker.java, server/src/com/cloud/event/ActionEventInterceptor.java, server/src/com/cloud/event/ActionEventUtils.java, server/src/com/cloud/projects/ProjectManagerImpl.java, server/src/com/cloud/server/ManagementServerImpl.java, server/src/com/cloud/storage/snapshot/SnapshotManagerImpl.java, server/src/com/cloud/vm/UserVmManagerImpl.java
In some of the events generated, entity uuid was missing making it difficult to find the entity. Fixed the same.
Tested it on rabbitmq instance.
There are the events before after the fix:
Before
--------------------------------------------------------------------------------
routing_key: management-server.ActionEvent.ACCOUNT-DELETE.Account.*
exchange: cloudstack-events
message_count: 2
payload:
{"eventDateTime":"2015-09-04 17:59:24 +0530","status":"Scheduled","description":"deleting User test4 (id: 28) and accountId \u003d 28","event":"ACCOUNT.DELETE","Account":"c09e2e81-8edc-4c27-b072-25005b522b63","account":"bd73dc2e-35c0-11e5-b094-d4ae52cb9af0","user":"bd7ea748-35c0-11e5-b094-d4ae52cb9af0"}
payload_bytes: 304
payload_encoding: string
redelivered: False …
=> Cloudstack 8816 entityuuid missing in some of the events

server/src/com/cloud/template/TemplateManagerImpl.java
We were listing image stores by zone id which was resulting in listing of only one image store
If in that image store its download state is not DOWNLOADED then download template is failing
=> CLOUDSTACK-8834: Fixed unable to download Template , when in multi zones

tools/appliance/definitions/systemvmtemplate/definition.rb
7.8.0 url is not available(404 Error)
This fixes the jenkins http://jenkins.buildacloud.org/job/build-systemvm-master/624/console which is failing with the below error
```
Checking if isofile iso-cd/debian-7.8.0-i386-netinst.iso already exists.
Full path: /home/jenkins/acs/workspace/build-systemvm-master/tools/appliance/iso/iso-cd/debian-7.8.0-i386-netinst.iso
There was an error downloading http://cdimage.debian.org/cdimage/archive/7.8.0/i386/iso-cd/debian-7.8.0-i386-netinst.iso:
404 Not Found
```
This is tested and build is successful at http://jenkins.buildacloud.org/view/parameterized/job/parameterized-sytemvm/1/
=> changed the systemvm base iso file from debian-7.8.0 to debian-7.9.0

agent/src/com/cloud/agent/Agent.java, utils/src/main/java/com/cloud/utils/nio/NioConnection.java
Hi!
@wilderrodrigues by implementing Callable you switched a couple of methods and fields. I switched them some more!
The reason why the Agent wouldn't reconnect was due to two facts.
Problem 1: Selector was blocking.
In the while loop at [1] _selector.select(); was blocking when the connection was lost. This means at [2] _isStartup = false; was never excecuted. Therefore at [3] the call to isStartup() always returned true resulting in an infinite loop.
Resolution 1: Move the call to cleanUp() [4] before checking if isStartup() has turned to false. cleanUp() will close() the _selector resulting in _isStartup to be set to false.
Problem 2: Setting _isStartup & _isRunning to true when init() throwed an unchecked exception (ConnectException).
The exception was nicely caught, but only logged. …
=> [4.6][BLOCKER]CLOUDSTACK-8883: Resolved connect/reconnect issue.

engine/schema/src/com/cloud/dc/dao/DataCenterIpAddressDao.java, engine/schema/src/com/cloud/dc/dao/DataCenterIpAddressDaoImpl.java, engine/schema/src/com/cloud/network/dao/IPAddressDao.java, engine/schema/src/com/cloud/network/dao/IPAddressDaoImpl.java, engine/schema/src/com/cloud/storage/dao/VolumeDao.java, engine/schema/src/com/cloud/storage/dao/VolumeDaoImpl.java, engine/schema/src/com/cloud/vm/dao/VMInstanceDaoImpl.java, server/src/com/cloud/configuration/ConfigurationManagerImpl.java, server/test/com/cloud/configuration/ConfigurationManagerTest.java
Instead of having both checkIfPodIsDeletable() and checkIfZoneIsDeletable have there own SQL query, I've refactored them so they use DAO SQL Queries.
This resolves the SQL Exception thrown by both classes.
Test to confirm working order:
- deploy ACS
- Add zones / pods. -> Try to delete without resources. -> Direct success.
- Add resources to zones / pods. -> Try to delete with resources in the pod / zone. -> Correct exception thrown. (Error message is why it cannot remove the zone / pod. IE: There is still a hosts or vm or .... )
=> [4.6][BLOCKER]CLOUDSTACK-8763: Resolved POD/ZONE deletion failure.

plugins/network-elements/elastic-loadbalancer/src/com/cloud/network/lb/LoadBalanceRuleHandler.java, plugins/network-elements/internal-loadbalancer/src/org/apache/cloudstack/network/lb/InternalLoadBalancerVMManagerImpl.java, plugins/network-elements/juniper-contrail/src/org/apache/cloudstack/network/contrail/management/ServiceManagerImpl.java, server/src/com/cloud/network/router/NetworkHelperImpl.java, server/src/com/cloud/vm/UserVmManagerImpl.java
Check if the list is empty before trying to get the first entry. If the list is empty, in example when dealing with projects, it will user the caller user id.
Tests to verify working order:
1. Deploy ACS
2. Create project
3. Create resource in project -> Should succeed!
=> [4.6][BLOCKER]CLOUDSTACK-8890: Added isEmpty() check to prevent nullPointerException.

core/test/com/cloud/storage/template/LocalTemplateDownloaderTest.java
Small fix to have the tests also work on other platforms
=> Use java.io.tmpdir instead of hardcoded /tmp

systemvm/patches/debian/config/opt/cloud/bin/cs/CsNetfilter.py
On basic zone share network VR default iptables rules are not applied correctly. Due to this ssh to VR got failed.
In shared network the VR type is 'dhcpsrvr' not router. So corrected it in the ''del_standard' method to select the correct type.
Testing:
1. VR is deployed correctly.
2. Tested restart, stop, start VR.
3. New VM deployment is success.
4. ssh to VR from the host is successful.
5. iptables rules on the VR came up correctly.
below is the output from the VR:
iptables -L INPUT -nv
Chain INPUT (policy DROP 16 packets, 1056 bytes)
pkts bytes target     prot opt in     out     source               destination
0     0 ACCEPT     all  --  *      *       0.0.0.0/0            224.0.0.18
0     0 ACCEPT     all  --  *      *       0.0.0.0/0            225.0.0.50
104  9800 ACCEPT     all …
=> CLOUDSTACK-8843: Fixed issue in default iptables rules on shared network VR

systemvm/patches/debian/config/opt/cloud/bin/configure.py, systemvm/patches/debian/config/opt/cloud/bin/cs/CsAddress.py, systemvm/patches/debian/config/opt/cloud/bin/cs/CsNetfilter.py
VR default iptables rules in INPUT chain are configured partially.
In CsAddress.py rules are configured while configuring public interface, guest interface post configuration is missed. Fixed to configure guest post configuration so that iptables rules are configured.
Testing:
1. Deployed vm in the network.
2.iptables rules on the VR configured correctly.
3.VM got the dhcp ip address from the VR.
=> CLOUDSTACK-8891: Fixed default iptables rules on VR  for guest traffic

systemvm/patches/debian/config/etc/dnsmasq.conf.tmpl, systemvm/patches/debian/config/etc/init.d/cloud-early-config
1. Dnsmasq is not listening on the ppp+ interfaces due to this remote access vpn clients dns requests are  dropped.
2. Configured the dnsmasq to listen on all the interfaces except public. There is firewall to allow only specific cidr to allow the dns requests.
Tested from windows client nslookup.
=> Configured dnsmasq to listen on all interfaces so that vpn  client gets dns

systemvm/patches/debian/config/opt/cloud/bin/configure.py
Added hooking the FIREWALL_EGRESS_RULES chain into FW_OUTBOUND chain.
With this egress rules will effective.
=> CLOUDSTACK-8905: Fixed hooking egress rules

core/src/com/cloud/storage/template/OVAProcessor.java, core/src/com/cloud/storage/template/QCOW2Processor.java, core/src/com/cloud/storage/template/TemplateLocation.java, core/src/com/cloud/storage/template/VhdProcessor.java, core/test/com/cloud/storage/template/OVAProcessorTest.java, core/test/com/cloud/storage/template/QCOW2ProcessorTest.java, core/test/com/cloud/storage/template/VhdProcessorTest.java, services/secondary-storage/server/src/org/apache/cloudstack/storage/template/DownloadManagerImpl.java
We have multiple file processors to process different types of image
formats. The processor interface has two methods getVirtualSize() and
process().
1.  getVirtualSize() as the name says, returns the virtual size of
the file and is used at get the size while copying files from NFS to s3
2.  process() returns FormatInfo struct which has fileType, size,
virutalSize, filename.  on successfully downloading a template, each
file is passed to all the processors.process() and whichever returns a
FormatInfo, that will be used to create template.properties file.  If
process() throws an InternalErrorException, template installation fails.
But, if process() returns null, template registration is successful with
template.properties missing some attributes like virtualSize, file
format etc. which …
=> CLOUDSTACK-8808: Successfully registered VHD template is downloaded again due to missing virtualsize property in template.properties

systemvm/patches/debian/config/opt/cloud/bin/configure.py, systemvm/patches/debian/config/opt/cloud/bin/cs/CsAddress.py, systemvm/patches/debian/config/opt/cloud/bin/cs/CsHelper.py, systemvm/patches/debian/config/opt/cloud/bin/cs/CsRedundant.py, systemvm/patches/debian/config/opt/cloud/bin/cs/CsRoute.py, test/integration/component/test_routers_iptables_default_policy.py, test/integration/component/test_routers_network_ops.py, test/integration/component/test_vpc_redundant.py, test/integration/component/test_vpc_router_nics.py
In order to reproduce the problem, I did the following
* Create a Redundant VPC
* Add a tier
* Add a new VM to the tier
* Add an ACL, open port 22 and associate the ACL with the tier
* Acquire a pub IP
* Add a PF rule to port 22 towards the VM
* Try to SSH to the VM through the Pub IP
It failed with "No route to host".
This PR contains the following:
* Fix for the keepalived (vrrp) configuration;
* Refactor the default router code for both isolated and [r]VPC routers
* Revert CsRedundant changes
* Add default route tests
* Add logging to tests - so we see what's happening during test execution.
=> CLOUDSTACK-8915 - Cannot SSH into VMs deployed Redundant VPC routers

plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtBackupSnapshotCommandWrapper.java, plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/storage/LibvirtStorageAdaptor.java, pom.xml
This should fix the CloudStack Agent from crashing when it has to
handle more then 16 RBD snapshots on one Volume.
=> CLOUDSTACK-8879: Depend in rados-java 0.2.0

engine/orchestration/src/com/cloud/vm/VirtualMachinePowerStateSyncImpl.java, engine/schema/src/com/cloud/vm/dao/VMInstanceDao.java, engine/schema/src/com/cloud/vm/dao/VMInstanceDaoImpl.java
=> [4.5] CLOUDSTACK-8848: ensure power state is up to date for missing PowerState handling

systemvm/patches/debian/config/opt/cloud/bin/configure.py, systemvm/patches/debian/config/opt/cloud/bin/cs/CsLoadBalancer.py, systemvm/patches/debian/config/opt/cloud/bin/cs/CsNetfilter.py, systemvm/patches/debian/config/opt/cloud/bin/cs/CsProcess.py, test/integration/smoke/test_loadbalance.py
This PR fixes the Load Balance feature by adding iptables rules for the public IP and port of the LB.
In order to cover the changes, I improved and executed the smoke/test_loadbalance.py. In addition, I also executed many other tests to make sure the main network/VM functionalities are working as expected.
Test report will follow.
=> CLOUDSTACK-8947 - Load Balancer not working with Isolated Networks

server/src/com/cloud/network/StorageNetworkManagerImpl.java
This is a regression from commit 0cd8c06f7dceaf999acf202862c5d1d580e7aa0e
try-with-resource used at https://github.com/apache/cloudstack/blob/master/server/src/com/cloud/network/StorageNetworkManagerImpl.java#L107 is closing the transaction.
At later point when the transaction is actually committed, it doesn't find the transaction and hence the exception.
testing:
manually tested that create storage network api succeeds.
```
cloudmonkey🐵 > create storagenetworkiprange gateway=192.168.200.67 netmask=255.255.255.0 startip=192.168.200.200 endip=192.168.200.202 podid=544e3be0-9bc6-428f-9237-bf777053ab2e
\
accountid = 120b521c-725c-11e5-9244-7278fd1d2943
cmd = org.apache.cloudstack.api.command.admin.network.CreateStorageNetworkIpRangeCmd
created = 2015-10-15T09:31:22+0000
jobid = …
```
=> [4.6][BLOCKER] CLOUDSTACK-8923: Create storage network IP range failed

tools/marvin/pom.xml
When building the developer tools, if the build is sequential then the marvin module always gets build after the apidoc module. However, it the build is parallelised (-Tn option in maven) it sometimes happens that maven tries to build the marvin module before building the apidoc module. That difference in the order makes it impossible to build marvin because it depends on the artefacts of the apidoc module.
This PR makes the dependency between marvin an apidoc explicit.
=> Marvin module depends on APIdoc module

test/integration/smoke/test_privategw_acl.py
- Read cofiguration from the zone: template id; template id; and domain id
- Create Account and VPC Offering
- Add cleanup resources
=> CLOUDSTACK-8971 - Improve the current test_privategw_acls.py

tools/marvin/marvin/config/test_data.py
Replace URLs related to templates and ISOs with the ones accessbile to everybody in the community.
I have copied all the templates and ISOs to my webspace at http://people.apache.org/~sanjeev/ so they can be accessible from anywhere.
=> CLOUDSTACK-8960: Remove Citrix Resources from test_data.py

systemvm/patches/debian/config/etc/init.d/cloud-early-config, test/integration/smoke/test_ssvm.py
This closes PR #930 as well.
I Rebased @bvbharat's PR with latest Master and tested the SSVM/CPVM and the routers: rVPC; VPC; VR; and RVR.
=> CLOUDSTACK-8933 SSVm and CPVM do not survive a reboot from API

tools/apidoc/pom.xml
When building the cloud-apidoc module a script called `./build-apidoc.sh` is executed with an argument that points to `../../client/target/cloud-client-ui-${project.version}/WEB-INF/lib`. The script uses that argument to build a Java classpath. However, since the cloud-apidoc module does not explicitly depend on cloud-client-ui, a parallel maven build will often fail because the required jars are not present when needed.
Error message when build fails:
```
Error: Could not find or load main class com.cloud.api.doc.ApiXmlDocWriter
```
This PR makes the dependency explicit.
Resulting build:
```
mvn clean install -T4 -Pdeveloper,systemvm
....
[INFO] …
```
=> cloud-apidoc module depends on cloud-client-ui

packaging/centos63/cloud-ipallocator.rc, packaging/centos63/cloud-management.rc, packaging/centos7/cloud-ipallocator.rc, packaging/fedora20/cloud-ipallocator.rc, packaging/fedora20/cloud-management.rc, packaging/fedora21/cloud-ipallocator.rc, packaging/fedora21/cloud-management.rc
When a management server is halted or rebooted, the cloudstack-management init script does not successfully kill the associated java process. There will always be an error about "Cannot find PID file". The script should be reworked so that there are no errors and java is killed correctly.
This appears to be due to the script using the basename of the script:
NAME="$(basename $0)"
To look for the pid file:
if [ -f /var/run/$
{NAME}
.pid ]; then
This does work correctly if the script is run directly (basename will be "cloudstack-management", so "cloudstack-management.pid" file is found). However when a server is halted or rebooted, the script is not run directly but via the symlinks in /etc/rc.d/rc0.d/ and /etc/rc.d/rc0.d/, respectively. The symlinks are named "K20cloudstack-management" so …
=> CLOUDSTACK-8815 : Issues with cloudstack-management init script

api/src/org/apache/cloudstack/api/command/user/vm/DeployVMCmd.java, core/src/com/cloud/agent/transport/Request.java
Before change:
2015-10-15 12:55:34,268 DEBUG [c.c.a.t.Request] (RouterStatusMonitor-1:ctx-d2b917a4) Seq 20-2693152577167557361: Sending  { Cmd , MgmtId: 345051313197, via: 20(KVM015), Ver: v1, Flags: 100011, [{"com.cloud.agent.api.routing.GetRouterAlertsCommand":{"previousAlertTimeStamp":"1970-01-01 00:00:00","accessDetails":{"router.ip":"169.254.3.13"},"wait":0}}] }
2015-10-15 12:55:34,416 DEBUG [c.c.a.t.Request] (AgentManager-Handler-7:null) Seq 20-2693152577167557361: Processing:  { Ans: , MgmtId: 345051313197, via: 20, Ver: v1, Flags: 10, [{"com.cloud.agent.api.GetRouterAlertsAnswer":{"result":true,"wait":0}}] }
2015-10-15 12:55:34,416 DEBUG [c.c.a.t.Request] (RouterStatusMonitor-1:ctx-d2b917a4) Seq 20-2693152577167557361: Received:  { Ans: , MgmtId: 345051313197, via: 20, Ver: v1, …
=> Add agent name in received response

utils/src/test/java/com/cloud/utils/rest/BasicRestClientTest.java
test fails when port is reachable so prevent it as much as possible
making sure that all kinds of weird developers can work with it
=> CLOUDSTACK-8981 coded a more obscure host and clear failure message

systemvm/patches/debian/config/opt/cloud/bin/cs/CsDhcp.py, systemvm/patches/debian/config/opt/cloud/bin/cs/CsGuestNetwork.py, test/integration/component/test_vpc_offerings.py, test/integration/smoke/test_network.py
This PR fixes the "sequence item 0: expected string, NoneType found" error found in the CsDhcp.py file when attempting to remo a network from a VPC.
=> CLOUDSTACK-8935 - Cannot remove [r]VPC networks due to RTNETLINK error

test/integration/component/test_routers_network_ops.py
While running test_isolate_network_FW_PF_default_routes it is expected
that SSH'ing into a VM does not work immediately. However, when it fails
(as expected) witht he follwoing error
====Trying SSH Connection: Host:192.168.23.12 Uer:root
Port:22 RetryCnt:1===
File "/home/jenkins/workspace/mccloud/mct-run-marvin-tests@2/venv/lib/python2.7/site-packages/marvin/sshClient.py", line 121, in createConnection timeout=self.timeout)
File "/home/jenkins/workspace/mccloud/mct-run-marvin-tests@2/venv/lib/python2.7/site-packages/paramiko/client.py", line 251, in connect retry_on_signal(lambda: sock.connect(addr))
File /home/jenkins/workspace/mccloud/mct-run-marvin-tests@2/venv/lib/python2.7/site-packages/paramiko/util.py", line 270, in retry_on_signal return …
=> Fix error message in test_isolate_network_FW_PF_default_routes

plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
This will allow KVM users to utilize teamd nic teaming devices named team*.
=> Added support for KVM teamd devices to LibvirtComputingResource.java

engine/storage/volume/src/org/apache/cloudstack/storage/volume/VolumeDataFactoryImpl.java
This issue happens on KVM as well.
This is because the volume info is missing in the CopyCommand once the volume has been removed.
When the KVM agent tries to process the command, it will throws a NPE.
=> CLOUDSTACK-8964: Can't create volume from snapshot of a removed volume

framework/db/src/com/cloud/utils/db/GenericDao.java, framework/db/src/com/cloud/utils/db/GenericDaoBase.java, framework/db/src/com/cloud/utils/db/SqlGenerator.java, server/src/com/cloud/api/query/QueryManagerImpl.java
modified sql that is used for retrieving vm count .
In load test environment listVirtualmachine takes 8-11 sec to load. This environment has around 12k active VMs. Total number of rows is 190K.
Performance bottleneck in listVirtualmachine command is fetching the count and distinct vms.
{noformat}
// search vm details by ids
Pair<List<UserVmJoinVO>, Integer> uniqueVmPair = _userVmJoinDao.searchAndCount(sc, searchFilter);
Integer count = uniqueVmPair.second();
{noformat}
This takes 95% of the total time.
To fetch the count and distinct vms we are using below sqls.
Query 1: 
{noformat}
SELECT DISTINCT(user_vm_view.id) FROM user_vm_view WHERE user_vm_view.account_type != 5  AND user_vm_view.display_vm = 1  AND user_vm_view.removed IS NULL  ORDER BY user_vm_view.id ASC  LIMIT 0, 20
{noformat} …
=> CLOUDSTACK-8917 : Instance tab takes long time to load with 12K Vms

api/src/org/apache/cloudstack/api/ApiCommandJobType.java, api/src/org/apache/cloudstack/api/command/user/network/DeleteNetworkCmd.java, api/src/org/apache/cloudstack/context/CallContext.java, api/test/org/apache/cloudstack/context/CallContextTest.java, server/src/com/cloud/api/ApiDBUtils.java, server/src/com/cloud/user/AccountManagerImpl.java, server/src/com/cloud/vm/UserVmManagerImpl.java
The key objects in the context map are sometimes String and sometimes object. This causes missing uuids when an entity put in the context map with key entity.toString is queried with key entity
Testing:
manually tested by deploying a vm and checked that the created events in rabbitmq now has uuids.
events before and after the change are update at https://issues.apache.org/jira/browse/CLOUDSTACK-8816?focusedCommentId=14805239
unittests
```
$ mvn -pl :cloud-api test -Dtest=CallContextTest
-------------------------------------------------------
T E S T S
-------------------------------------------------------
Running org.apache.cloudstack.context.CallContextTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.152 sec - in org.apache.cloudstack.context.CallContextTest …
```
=> Cloudstack-8816 some of the events do not have resource uuids

test/integration/component/test_ps_limits.py
The tests in the test_ps_limits.py file can all be run on a "basic" setup. This PR adds that functionality.
```
nosetests --with-marvin --marvin-config=/data/shared/marvin/mct-zone1-kvm1-basic.cfg -s -a tags=basic,required_hardware=false smoke/test_vm_life_cycle.py
```
```
==== Log Folder Path: /tmp//MarvinLogs//Oct_26_2015_09_55_20_4UDZRZ. All logs will be available here ====
=== TestName: test_deploy_vm | Status : SUCCESS ===
=== TestName: test_deploy_vm_multiple | Status : SUCCESS ===
=== TestName: test_01_stop_vm | Status : SUCCESS ===
=== TestName: test_02_start_vm | Status : SUCCESS ===
=== TestName: …
```
=> [4.6] CLOUDSTACK-8989 test_ps_limits.py tests can also be run on a "basic" setup.

engine/orchestration/src/com/cloud/vm/VirtualMachineManagerImpl.java
This is because the pod_id is set to NULL at the first time when I migrate the instance to a zone-wide pool (not cluster-wide).
=> CLOUDSTACK-8941: fix NPE when migrate vm to other zone-wide pools the second time

setup/db/db/schema-452to460.sql
Added 32 disks to a VM, booted the VM, formatted all disks and mounted them all. Also created volume group and wrote all disks full. Also checked UI for glitches, which weren't present.
=> [4.6] CLOUDSTACK-8992 Allow 32 disks to be attached to a KVM VM.

python/lib/cloudutils/serviceConfig.py
If a custom resource (kvm/libvirt implementation) is defined in agent.properties
don't override with the default, but check and fallback to the default if
resource property not defined
A simple if-else fix, cc @remibergsma @wido @wilderrodrigues @borisroman and others
=> [master/4.6] CLOUDSTACK-8999: Don't override resource if provided by agent.properties

systemvm/patches/debian/config/opt/cloud/bin/cs/CsAddress.py, systemvm/patches/debian/config/opt/cloud/bin/cs_ip.py, test/integration/smoke/test_network.py
This PR fixes the Public IP removal form the virtual routers. It also improves the existing test_network.py.
=> CLOUDSTACK-8991 - IP address is not removed from VR even after disabling static NAT

systemvm/patches/debian/config/opt/cloud/bin/configure.py, test/integration/component/test_password_server.py
This PR implements the update of the password as it use to be done with the bash file, but using the Python code for it.
A new integration test was added in order to cover the fix. The test can be found at component/test_password_server.py and does the following:
* Creates an Account
* Creates a Service Offering
* Creates a Network Offering
* Creates a Network
* Creates two Virtual Machines
* Creates two FW rules
* Creates two PF rules
* SSH into each VM and checks the default routes (by pinging 8.8.8.8)
* SSH to the host and executes a command in the router to check the password-[gateway] file
- The file is under /var/cache/cloud/passwords-[gateway]
The [gateway] is replaced by the gateway from each virtual machine NIC.
=> CLOUDSTACK-8957 - VR password server feature is broken

ui/scripts/configuration.js
This is a regression from commit af2f21894ce061faadc8cec29b901719303a29dc
added vpcofferings to the select list
Before the change (from the bug):
After the change:
=> [4.6] CLOUDSTACK-8984: VPC Network offerings tab missing from UI

test/integration/component/test_router_dhcphosts.py
This PR contains a test that will cover the fix on PR #981 
The tests does the following:
* Creates account, service offering, network offering, network
* Deploys two virtual machines
- Each machine with a pre-assigned IP
* Creates two FW and PF rules
* Checks that SSH into the VMs works
* Checks default routes from both VMs
* Checks that the /etc/dhcphosts.txt contains 1 entry per VM IP
* Destroys/Expunges 1 VM
* Creates a new VM with the same IP as the destroyed one
* Checks that the /etc/dhcphosts.txt contains 1 entry per VM IP
=> CLOUDSTACK-9007 - Write test to check that the /etc/dhcphosts.txt doesn't contain duplicate IPs

server/src/com/cloud/deploy/DeploymentPlanningManagerImpl.java, server/test/com/cloud/vm/DeploymentPlanningManagerImplTest.java
Earlier the deployment planner was not handling the case of virtual routers.(In Explicit Dedication)
It was only handling for all instance VMs/user VMs.
Added code for checking the case of Virtual Routers.
=> CLOUDSTACK-8962: Dedicated cluster is used for virtual routers that belong to non-dedicated account

api/src/com/cloud/agent/api/to/LoadBalancerTO.java, core/src/com/cloud/network/HAProxyConfigurator.java, core/test/com/cloud/network/HAProxyConfiguratorTest.java, server/src/com/cloud/network/element/VirtualRouterElement.java, server/src/com/cloud/network/router/CommandSetupHelper.java
This will let us specify a new load balancer protocol (tcp-proxy) which enables HAProxy's `send-proxy` functionality.
`send-proxy` / [the PROXY protocol][1] will send the real connection origin IP through to the servers behind HAProxy, without requiring any protocol specific changes (such as HTTP header rewriting).
[1]: http://www.haproxy.org/download/1.5/doc/proxy-protocol.txt
This is also inline with what [Amazon ELB now supports][2].
[2]: http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/enable-proxy-protocol.html
=> Pass LbProtocol down to the HAProxyConfigurator

agent/conf/cloudstack-agent.logrotate, agent/pom.xml, debian/rules, packaging/centos63/cloud.spec, packaging/centos7/cloud.spec, packaging/fedora20/cloud.spec, packaging/fedora21/cloud.spec
Adds logrotate rules for cloudstack-agent.{err,out}, jsvc err/out log files may fill up disk. This adds a logrotate config in the rpm packages
cc @remibergsma @wido @wilderrodrigues and others
=> [master/4.6] CLOUDSTACK-9000: logrotate cloudstack-agent out and err logs

agent/pom.xml, debian/cloudstack-agent.install, debian/rules, packaging/centos63/cloud.spec
Adds logrotate rules for cloudstack-agent.{err,out} log files
cc @remibergsma @wido @wilderrodrigues and others
=> [4.5] CLOUDSTACK-9000: logrotate cloudstack-agent out and err logs

setup/db/db/schema-452to460.sql
The user_vm_view displayes the keypair information by joining vm_details with ssh_keypairs on the key value exclusively. 
We found a scenario in which this can cause information leakage. If there are two accounts using the same key, but create a different key name for it, and then a vm is created using one of the keys, the view will list both keypairs as belonging to the vm, which can in turn cause confusion to the users who see a keypair name which they did not create. 
The fix simply limits the view to displaying keypairs which belong to vm's account. 
I added it to the latest schema migration only; should I also include it in the previous ones?
=> Fixed user_vm_view to only display keypairs belonging to the account.

framework/jobs/src/org/apache/cloudstack/framework/jobs/impl/AsyncJobMBeanImpl.java
Status : in preogress instead of in progress and some other small typos .
=> another typo that appears when monitoring the java process via JMX

engine/schema/src/com/cloud/network/dao/NetworkVO.java, server/src/com/cloud/network/NetworkServiceImpl.java
Problem: Moving a RVR network offering to standalone makes the status of VR's as UNKNOWN and Redundant Router marked with YES. 
Fix: The network's isRedundant was not getting updated.
=> Fixed: Network Update from RVR offering to Standalone offering fails

systemvm/patches/debian/config/opt/cloud/bin/configure.py
This fix a typo of commit 4a177031b055f3649e3b4a00c80eddb5cafa1dd7
=> CLOUDSTACK-9013: Virtual router failed to start on KVM

plugins/hypervisors/ovm3/src/main/java/com/cloud/hypervisor/ovm3/resources/Ovm3HypervisorGuru.java, plugins/hypervisors/ovm3/src/main/java/com/cloud/hypervisor/ovm3/resources/Ovm3StorageProcessor.java, plugins/hypervisors/xenserver/src/com/cloud/hypervisor/XenServerGuru.java
some clean up of code after the fix from #975
=> CLOUDSTACK-8964: Ovm3HypervisorGuru answer fix and snapshot to volume implementation.

ui/scripts/network.js
While calling the listNics API, instead of sending the default nic id as parameter, it should send the network id as a parameter.
So, replaced that nicid parameter as networkid parameter.
=> CLOUDSTACK-8928: While adding VMs to LB rule, default NIC IP is always displayed rather than the IP corresponding to the NIC where LB is being created

server/src/com/cloud/network/IpAddressManagerImpl.java, test/integration/component/test_vpc.py
bug link https://issues.apache.org/jira/browse/CLOUDSTACK-9016.
CS doe not allocate the ip of the form x.x.x.1 to a guest VM. We seem to incorrectly assume that the first ip in the subnet belongs to the gateway.
=> CLOUDSTACK-9016 Fail to create VM instance within VPC

test/integration/smoke/test_ssvm.py
The test now check the IP taking into account the right interface for VMware/HyperV (eth1).
@karuturi could you please have a look? Unfortunately, I do not have HyperV/VMware test environment.
=> CLOUDSTACK-9021 - Add right interface when test is executed against HyperV/VMware

server/src/com/cloud/network/ExternalLoadBalancerDeviceManagerImpl.java
The restart network was failing when using external loadbalencer. The failure was because of a number format exception. When BroadcastDomainType.getValue(guestConfig.getBroadcastUri() is executed this returns a string untagged. We were trying to parse this as long so there was a number pointer exception.
This happens only when the vlan uri is vlan://untagged. in other cases were there is a number instead of untagged (vlan tag) this used to succeed. Although we were trying to convert the number to long we were not really using it. we were converting the number to long and then back to string when creating the IpAddressTo. so I removed this unnecessary conversion in this case for fixing the issue at hand.
I did a manual restart of the network and checked for this number format exception in …
=> CLOUDSTACK-8902 Restart Network fails in EIP/ELB zone

setup/dev/basic.cfg
Simulator setup uses the config file from following location:
tools/marvin/marvin/config/setup.cfg
Added global setting parameter "enable.dynamic.scale.vm" to above config file, so that dynamic scale vm tests can be run on simulator.
=> CLOUDSTACK-8924: Enable dynamic scaling to run test_scale_vm.py test on simulator

systemvm/patches/debian/config/opt/cloud/bin/configure.py, test/integration/component/test_routers_network_ops.py, tools/marvin/marvin/config/test_data.py
This PR fixes the router default policy for egress. When the default is DENY, the router still allows outgoing connections.
The test component/test_routers_network_ops.py was improved to cover that case as well. The results were:
Test redundant router internals ... === TestName: test_01_isolate_network_FW_PF_default_routes_egress_true | Status : SUCCESS ===
ok
Test redundant router internals ... === TestName: test_02_isolate_network_FW_PF_default_routes_egress_false | Status : SUCCESS ===
ok
Test redundant router internals ... === TestName: test_01_RVR_Network_FW_PF_SSH_default_routes_egress_true | Status : SUCCESS ===
ok
Test redundant router internals ... === TestName: test_02_RVR_Network_FW_PF_SSH_default_routes_egress_false | Status : SUCCESS ===
ok …
=> CLOUDSTACK-8925 - Default allow for Egress rules is not being configured properly in VR iptables rules

engine/schema/src/com/cloud/upgrade/dao/Upgrade452to460.java, setup/db/db/schema-452to460.sql
This PR fixes the upgrade path from 4.4.x/4.5.x to 4.6.0. We introduced the logic to update the database with the correct information about the SystemVMs.
We tested this PR with by doing an upgrade from 4.4.4 to 4.6.0 and it works as expected.
=> CLOUDSTACK-9046 - Fix upgrade path from 4.4 and 4.5 to 4.6

debian/control
Use Tomcat6 for Debian packages.
How to test:
Package debian packages and install them. Will depend specifically on tomcat6 for now.
Error log before:
```
DEBUG:root:execute:uname -r
DEBUG:root:execute:uname -m
DEBUG:root:execute:hostname -f
DEBUG:root:execute:iptables-save|grep INPUT|grep -w 8080
DEBUG:root:Failed to execute:
DEBUG:root:execute:ufw allow 8080/tcp
DEBUG:root:execute:iptables-save|grep INPUT|grep -w 8250
DEBUG:root:Failed to execute:
DEBUG:root:execute:ufw allow 8250/tcp
DEBUG:root:execute:iptables-save|grep INPUT|grep -w 9090
DEBUG:root:Failed to execute:
DEBUG:root:execute:ufw allow 9090/tcp
DEBUG:root:execute:rm -f /etc/cloudstack/management/server.xml
DEBUG:root:execute:rm -f /etc/cloudstack/management/tomcat6.conf
DEBUG:root:execute:ln -s …
```
=> CLOUDSTACK-9040: Use Tomcat6 for Debian packages.

tools/docker/Dockerfile, tools/docker/Dockerfile.centos6, tools/docker/README.md, tools/docker/init.sh_centos6, tools/docker/systemtpl.sh
This PR replace PR#910 which include fix from comments in PR#910.
This PR simplify download of systemvm templates, work with docker-compose and enable integration-api port and use of localstorage without reconfiguration of cloudstack.
Rebased on Oct28.
=> squashed commit for dockerfiles part#2 including comments from PR#910

engine/schema/src/com/cloud/upgrade/DatabaseUpgradeChecker.java, engine/schema/src/com/cloud/upgrade/dao/Upgrade460to461.java, setup/db/db/schema-460to461-cleanup.sql, setup/db/db/schema-460to461.sql
The 4.6 branch needs an upgrade path to 4.6.1. I looked at how this was done before and think this will do. Can you give it a second pair of eyes please @DaanHoogland ?
When this is indeed OK, I'll do the same for master for the 4.6.0 -> 4.7.0 path.
I've tried a build and that works: `mvn clean install`
```
[INFO] Total time: 07:33 min
[INFO] Finished at: 2015-11-15T13:45:58+01:00
[INFO] Final Memory: 120M/1591M
```
Once this is a PR, I'll try an actual upgrade from 4.6.0 to 4.6.1-SNAPSHOT.
=> implement upgrade path from 4.6.0 to 4.6.1

build/replace.properties, engine/schema/src/com/cloud/upgrade/dao/Upgrade460to461.java, setup/db/db/schema-460to461-cleanup.sql, setup/db/db/schema-460to461.sql, tools/marvin/marvin/deployAndRun.py, tools/marvin/setup.py
Initial merge of 4.6 to master
ignored pom.xml version number changes and changes to debian/changelog and engine/schema/src/com/cloud/upgrade/DatabaseUpgradeChecker.java
Following commands were executed
```
1. git checkout 4.6
2. git pull --rebase
3. git checkout master
4. git pull --rebase
5. git fwd-merge 4.6
6. git diff --name-only | grep pom.xml | xargs git checkout --ours
7. git diff --name-only | grep pom.xml | xargs git add
8. git checkout --ours engine/schema/src/com/cloud/upgrade/DatabaseUpgradeChecker.java
9. git add engine/schema/src/com/cloud/upgrade/DatabaseUpgradeChecker.java
10. git checkout --ours debian/changelog
11. git add debian/changelog
12. # manually edited version number in tools/marvin/marvin/deployAndRun.py and tools/marvin/setup.py
13. git commit
14. git …
```
=> Merge 4.6 release branch to master

systemvm/patches/debian/config/opt/cloud/bin/passwd_server_ip.py
The password server on the virtual router should respond with "saved_password" if no password is to be issued. This allows for backwards compatibility with Windows Guest VMs which require the "saved_password" response.
=> CLOUDSTACK-9058 - Respond with "saved_password" if no password is to be issued.

deps/install-non-oss.sh, plugins/hypervisors/vmware/src/com/cloud/hypervisor/vmware/resource/VmwareResource.java, plugins/network-elements/nicira-nvp/src/main/java/com/cloud/network/nicira/ControlClusterStatus.java, plugins/network-elements/nicira-nvp/src/main/java/com/cloud/network/resource/NiciraNvpResource.java, pom.xml, utils/src/main/java/com/cloud/utils/nicira/nvp/plugin/NiciraNvpApiVersion.java, vmware-base/src/com/cloud/hypervisor/vmware/mo/HostMO.java, vmware-base/src/com/cloud/hypervisor/vmware/mo/HypervisorHostHelper.java, vmware-base/src/com/cloud/hypervisor/vmware/mo/VirtualDiskManagerMO.java, vmware-base/src/com/cloud/hypervisor/vmware/util/VmwareHelper.java
JIRA Ticket: https://issues.apache.org/jira/browse/CLOUDSTACK-8956
Prior to version 4.2. Nicira/VmWare NSX used a variation of Open vSwitch as means of integrating SDN into hypervisor layer. Cloudstack NiciraNVP plugin was written to support OVS as a bridge to NSX.
In version 4.2 VMware introduced NSX vSwitch as a replacement for OVS in ESX hypervisors. It is a fork of distributed vSwitch leveraging one of the recent features of ESX called opaque networks. Because of that change the current version of NiciraNVP plugin doesn’t support versions of NSX-MH above 4.2 specifically in Vsphere environment. Proposed fix will analyze a version of NVP/NSX API and use proper support for ESX hypervisors.
vSphere hypervisor mode operations when NV is deployed onto NSX managed network changes:
* Current …
=> CLOUDSTACK-8956: NSX/Nicira Plugin does not support NSX v4.2.1

pom.xml
cloustack is not vulnerable but as the classes are in they might
be used in the future so we upgrade to prevent accidental
vulnerabilities.
unit tests in master succeeded. unit tests on 4.6 passed. integration tests going on.
=> CLOUDSTACK-9053 security upgrade as per COLLECTIONS-580

server/src/com/cloud/network/router/VirtualNetworkApplianceManagerImpl.java
This issue happened when the KVM nodes is down.It might also happen when the cloudstack-agent is killed unexpectedly.
=> CLOUDSTACK-9055: fix NPE in updating Redundant State of VPC networks

packaging/package.sh
In package.sh
* lint
* adjust exit codes (1 for usage, 2 for maven, 3 for rpmbuild)
* fix variable naming for consistency
* add option for package release version
* revise synopsis and usage
=> CLOUDSTACK-9065: Packaging RPM, add option for package release version, cleanup and lint

utils/src/main/java/com/cloud/utils/PasswordGenerator.java, utils/src/test/java/com/cloud/utils/PasswordGeneratorTest.java
Related to CLOUDSTACK-9052.
I am shuffling the characters in the password, to avoid having a certain char type in fixed positions. I modified the tests accordingly to only check that the different character types are present. 
I think it would be good to remove the hard requirement to have at least one of digits, upper-case, and  lowercase chars, as it reduces the number of possible combinations passwords can take. What do you think?
=> Shuffling the password to avoid having a subset of characters in fixed positions.

systemvm/patches/debian/config/opt/cloud/bin/edithosts.sh
in /etc/dhcpentries.txt we had:
02:00:1e:07:01:53,set:10_102_92_5,10.102.92.5,songlog-1,infinite
02:00:0b:a2:00:3d,set:10_102_92_234,10.102.92.234,log-1,infinite
This sed matched unexpectetly "songlog-1" as well when "log-1" was processed, resulting
missing dhcp entry for songlog-1.
Also fixed other potenials problems relating to sed matching.
=> [4.5] CLOUDSTACK-9042: VR: DHCP: fix missing DHCP host enties

server/src/com/cloud/configuration/ConfigurationManagerImpl.java
throwing error for value < 8 and value > 256
right now, 8, 256 are hardcoded in the code. They should be moved to a
constant and has to be reused everywhere.
will update with test cases/testing later.
=> [4.7] CLOUDSTACK-8951: validation for config param "remote.access.vpn.psk.length"

api/src/com/cloud/serializer/Param.java, api/src/org/apache/cloudstack/api/response/CreateSSHKeyPairResponse.java, api/src/org/apache/cloudstack/api/response/GetVMPasswordResponse.java, api/src/org/apache/cloudstack/api/response/LoginCmdResponse.java, api/src/org/apache/cloudstack/api/response/RegisterResponse.java, api/src/org/apache/cloudstack/api/response/RemoteAccessVpnResponse.java, api/src/org/apache/cloudstack/api/response/Site2SiteCustomerGatewayResponse.java, api/src/org/apache/cloudstack/api/response/Site2SiteVpnConnectionResponse.java, api/src/org/apache/cloudstack/api/response/UserResponse.java, api/src/org/apache/cloudstack/api/response/UserVmResponse.java, plugins/network-elements/bigswitch/src/com/cloud/api/response/BigSwitchBcfDeviceResponse.java, plugins/user-authenticators/ldap/src/org/apache/cloudstack/api/response/LDAPConfigResponse.java, server/src/com/cloud/api/ApiResponseGsonHelper.java, server/src/com/cloud/api/ApiServer.java, server/src/com/cloud/api/ApiServlet.java, server/src/com/cloud/api/response/ApiResponseSerializer.java
- Removed regex. based search/replace of sensitive data on API response introduced as part of commit b0c6d4734724358df97b6fa4d8c5beb0f447745e
- Added new response serializer to skip sensitive data from getting logged based on annotation present in resposne object fields
- Added annotation (@LogLevel(Log4jLevel.Off)) to sensitive response object fields
Ran the following tests on simulator:
test_vm_life_cycle.py
Test advanced zone virtual router ... === TestName: test_advZoneVirtualRouter | Status : SUCCESS ===
ok
Test Deploy Virtual Machine ... === TestName: test_deploy_vm | Status : SUCCESS ===
ok
Test Multiple Deploy Virtual Machine ... === TestName: test_deploy_vm_multiple | Status : SUCCESS ===
ok
Test Stop Virtual Machine ... === TestName: test_01_stop_vm | Status : SUCCESS ===
ok …
=> CLOUDSTACK-8485: listAPIs are taking too long to return results

packaging/package.sh
Fixes this:
```
$ bash -x package.sh -p noredist -d centos63
(...)
+ rpmbuild --define '_topdir /home/david/cloudstack/packaging/../dist/rpmbuild' '-D_ver 4.6.1' '-D_rel SNAPSHOT' '-D_prerelease 1' -D_ossnoss noredist -bb SPECS/cloud.spec
error: Macro %_ossnoss has empty body
error: Macro %_ossnoss has empty body
error: failed to stat /home/david/cloudstack/dist/rpmbuild/noredist: No such file or directory
+ '[' 1 -ne 0 ']'
+ echo 'RPM Build Failed '
RPM Build Failed
+ exit 3
```
It was missing quotes around the rpmbuild argument '-D_ossnoss noredist'.
=> CLOUDSTACK-9065: fix bug when creating packaging with noredist flag

plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java, plugins/hypervisors/kvm/test/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java
little fix to make sure for instance "eth" is not regarded as interface when it is part of "methamfetamine"
=> CLOUDSTACK-9037 patterns can be more elaborate then prefixes.

server/src/com/cloud/event/ActionEventUtils.java, server/test/com/cloud/event/ActionEventUtilsTest.java
Same as pull request #1111, but this time on the 4.6 branch for forward merging in accordance with [the wiki](https://cwiki.apache.org/confluence/display/CLOUDSTACK/Release+principles+for+Apache+CloudStack+4.6+and+up#ReleaseprinciplesforApacheCloudStack4.6andup-HowtomergeaPullRequest?).
The fixing of CLOUDSTACK-8816 introduced a regression that removed the first class entities in the event bus description property. This is because everything was changed to use the Class as a key... Everything but the populateFirstClassEntities method in ActionEventUtils.
This commit tries to load the class key instead of the String key, which re-enables the populateFirstClassEntities method.
Likely this was not caught because of the trace exception handling... maybe some better logging/unit tests would be …
=> Fix event UUIDS missing on event bus

ui/scripts/ui/widgets/multiEdit.js
For setting the width of each data item for each row of Port Forwarding rules, it was processing all rules.
Basically for each data item, it was searching in all rules, which is un-necessary.
If there are N-Rules, It was processing N-times.
Now, it only processes one time by taking all N-rules at a time.
The previous solution was of O(NxN). Now its changed to O(N).
=> CLOUDSTACK-9068: Listing Port Forwarding Rules take too much time to load

services/secondary-storage/server/src/org/apache/cloudstack/storage/template/DownloadManagerImpl.java
coverity reported this as new last week. It has been in the code for ever, i.e. since initial git commit. Minor issue, easy fix.
=> CID-1339965 handle return value on failure

core/src/com/cloud/agent/api/MigrateWithStorageReceiveAnswer.java, core/src/com/cloud/agent/api/MigrateWithStorageSendCommand.java, plugins/hypervisors/xenserver/src/com/cloud/hypervisor/xenserver/resource/wrapper/xen610/XenServer610MigrateWithStorageReceiveCommandWrapper.java, plugins/hypervisors/xenserver/src/com/cloud/hypervisor/xenserver/resource/wrapper/xen610/XenServer610MigrateWithStorageSendCommandWrapper.java, plugins/hypervisors/xenserver/test/com/cloud/hypervisor/xenserver/resource/wrapper/xenbase/XenServer610WrapperTest.java
Storage motion of vm across clusters/xenserver-pools fails in a
clustered management server setup. In xen storage motion we have to send
a migrate_receive command to the destination host, followed by
migrate_send command to the source host. The sr and network detials of
the destination host have to be passed in migrate_send command on the
source. While migrating across clusters the source and destination
resources are seperate objects. To pass this information across
resources we have to send seperate migrate with storage receive and send
commands to the resource. In a clustered ms setup these commands may
have to be forwarded to another ms as the resource may be owned by it.
The serilization of the command and answer objects fails in such case as
it doesn't understand the xapi sr and …
=> CLOUDSTACK-9081 Migration of vm across clusters fails in clustered MS setup

api/src/com/cloud/configuration/ConfigurationService.java, api/src/org/apache/cloudstack/api/command/admin/vlan/DedicatePublicIpRangeCmd.java, engine/components-api/src/com/cloud/configuration/ConfigurationManager.java, engine/schema/resources/META-INF/cloudstack/core/spring-engine-schema-core-daos-context.xml, engine/schema/src/com/cloud/dc/DomainVlanMapVO.java, engine/schema/src/com/cloud/dc/dao/DomainVlanMapDao.java, engine/schema/src/com/cloud/dc/dao/DomainVlanMapDaoImpl.java, engine/schema/src/com/cloud/dc/dao/VlanDaoImpl.java, server/src/com/cloud/api/ApiDBUtils.java, server/src/com/cloud/api/ApiResponseHelper.java, server/src/com/cloud/configuration/ConfigurationManagerImpl.java, server/src/com/cloud/network/IpAddressManagerImpl.java, server/src/com/cloud/network/NetworkServiceImpl.java, server/test/com/cloud/configuration/ConfigurationManagerTest.java, server/test/com/cloud/vpc/MockConfigurationManagerImpl.java, server/test/com/cloud/vpc/VpcTestConfiguration.java, server/test/org/apache/cloudstack/networkoffering/ChildTestConfiguration.java, setup/db/db/schema-460to470.sql, setup/db/db/schema-461to470.sql, ui/scripts/system.js
For now, we dedicate ip pool to account, however, other accounts in the same domain cannot fetch the ip from this ip pool.
By dedicating ip pool to domain, accounts in the domain can fetch the public ip from same ip pool.
=> [4.7] CLOUDSTACK-8958: add dedicated ips to domain (account for now)

server/src/com/cloud/server/ManagementServerImpl.java
Before change:
cloudmonkey> list vlanipranges  keyword=118
: Caught: com.mysql.jdbc.JDBC4PreparedStatement@18f36b6e: SELECT vlan.id, vlan.vlan_id, vlan.vlan_gateway, vlan.vlan_netmask, vlan.ip6_gateway, vlan.ip6_cidr, vlan.data_center_id, vlan.description, vlan.ip6_range, vlan.network_id, vlan.physical_network_id, vlan.vlan_type, vlan.uuid, vlan.removed, vlan.created FROM vlan WHERE  ( OR vlan.description LIKE ** NOT SPECIFIED ** )  AND vlan.removed IS NULL  ORDER BY vlan.id ASC  LIMIT 0, 500
After change:
cloudmonkey> list vlanipranges  keyword='118'
count = 1
vlaniprange:
id = 0d80fd9c-cd6b-4f99-96c6-261420e75f58
account = system
domain = ROOT
domainid = 2044762d-c4a5-11e3-8379-005056ac4490
......
=> [4.6] Cannot list vlanipranges by keyword

plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java, plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java, plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java, plugins/hypervisors/kvm/test/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java
Adds disk serial ids based on volume uuids to the virt xml. This may be useful
for appliances/software that needs some serial ids on the VM disks. This does not
impact existing/running VMs, the vm virt xmls will be updates for running VMs
the next time they are stopped/started.
For testing, disk serial (of debian based systemvm) in the virt xml matched that
in /sys/devices/pci0000:00:0000:00:07.0/virtio4/block/vda/serial.
We currently don't support scsi-blcok devices for which serial is not supported,
for this we've added a DeviceType (LUN) which may be used in future and a check
to not add the serial to the xml if disk type is LUN.
Refer: https://libvirt.org/formatdomain.html#elementsDisks
=> [4.6] CLOUDSTACK-9083: Add disk serial to kvm virt xml

plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java, plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java, plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java, plugins/hypervisors/kvm/test/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java
Adds disk serial ids based on volume uuids to the virt xml. This may be useful
for appliances/software that needs some serial ids on the VM disks. This does not
impact existing/running VMs, the vm virt xmls will be updates for running VMs
the next time they are stopped/started.
For testing, disk serial (of debian based systemvm) in the virt xml matched that
in /sys/devices/pci0000:00:0000:00:07.0/virtio4/block/vda/serial.
We currently don't support scsi-blcok devices for which serial is not supported,
for this we've added a DeviceType (LUN) which may be used in future and a check
to not add the serial to the xml if disk type is LUN.
Refer: https://libvirt.org/formatdomain.html#elementsDisks
JIRA: https://issues.apache.org/jira/browse/CLOUDSTACK-9083
=> [4.5] CLOUDSTACK-9083: Add disk serial to kvm virt xml

engine/orchestration/src/com/cloud/agent/manager/AgentManagerImpl.java
Before:
<pre>DEBUG [c.c.a.m.AgentManagerImpl] (AgentManager-Handler-4:null) Ping from 66</pre>
After:
<pre>DEBUG [c.c.a.m.AgentManagerImpl] (AgentManager-Handler-4:null) Ping from 66 (n01)</pre>
Makes it easier to search for hosts in the logs. Most loglines contain both the hostId and hostName.
=> Show Agent name in Ping response

client/WEB-INF/classes/resources/messages.properties, ui/dictionary2.jsp, ui/scripts/ui-custom/accountsWizard.js
fixed two strings on the "Add LDAP Account page"
After the change: (with a test string in messages_ja_JP.properties file)
=> CLOUDSTACK-9092: L10n fix in "Add LDAP Account page"

test/integration/component/test_tags.py
Please go through bug https://issues.apache.org/jira/browse/CLOUDSTACK-9084 for more details.
Testcreation, adding and removing tag on public IP address ... === TestName: test_24_public_IP_tag | Status : SUCCESS ===
ok
Ran 1 test in 254.724s
OK
=> Add marvin test to verify if DomainAdmin is able to delete the tags on public ip address

engine/orchestration/src/org/apache/cloudstack/engine/datacenter/entity/api/db/dao/EngineHostDao.java, engine/orchestration/src/org/apache/cloudstack/engine/datacenter/entity/api/db/dao/EngineHostDaoImpl.java
After analysing the code within the EngineHostDaoImpl class, we noticed that methods:
countBy;
findByGuid;
findAndUpdateDirectAgentToLoad;
findAndUpdateApplianceToLoad;
markHostsAsDisconnected;
listAllUpAndEnabledNonHAHosts;
findLostHosts;
getRunningHostCounts;
getNextSequence;
countRoutingHostsByDataCenter;
updateResourceState;
findByTypeNameAndZoneId;
findHypervisorHostInCluster;
lockOneRandomRow;
And variables:
status_logger;
state_logger;
Have no usage. Thus, in order to clean up the code, we decided to remove them from EngineHostDaoImpl and its interface (EngineHostDao).
All of EngineHostDaoImpl's attributes were set to private, given that they are not accessed by any other class.
=> Removed unused code from the EngineHostDao Implementation 

server/src/com/cloud/storage/VolumeApiServiceImpl.java, test/integration/component/test_ps_resource_limits_volume.py
primary store resource limit check is not performed while attaching a
volume to a vm. Added them same.
Also added a marvin test case to verify the same.
Testing:
BEFORE
No error is shown in UI when trying to attach a volume even after reaching the resource limits.
```
mysql> select * from resource_limit where type="primary_storage";
+----+-----------+------------+-----------------+-------------+
| id | domain_id | account_id | type            | max         |
+----+-----------+------------+-----------------+-------------+
| 10 |      NULL |          4 | primary_storage | 21474836480 |
+----+-----------+------------+-----------------+-------------+
mysql> select * from resource_count where account_id=4 and type='primary_storage'; …
```
=> CLOUDSTACK-9080: Resource limits for Primary arent respected during attach

server/src/com/cloud/configuration/Config.java, server/src/com/cloud/configuration/ConfigurationManagerImpl.java, server/src/com/cloud/server/ConfigurationServerImpl.java, server/src/com/cloud/server/ManagementServerImpl.java, server/test/com/cloud/server/ConfigurationServerImplTest.java
generateRandomPassword() is supposed to create root user passwords. Right now it is only used on the guest VMs. The format of the passwords it creates are of the form "random 3-character string with a lowercase character, uppercase character, and a digit" + random n-character string with only lowercase characters".
For whatever reason it was that we use generateRandomPassword() for guest VM root user passwords(maybe more secure?) we should use the same function for system VM root user passwords.
Tests:
manually tested that password is generated in proper format and am able to login to cpvm with the new password. ex: zD2ztm, tR8snbwhq
```
$ mvn -pl server test -Dtest=ConfigurationServerImplTest#testUpdateSystemvmPassword
-------------------------------------------------------
T E S T S …
```
=> CLOUDSTACK-8868: use PasswordGenerator.generateRandomPassword() to generate systemvm passwords

plugins/hypervisors/xenserver/src/com/cloud/hypervisor/xenserver/resource/CitrixResourceBase.java, plugins/hypervisors/xenserver/test/com/cloud/hypervisor/xenserver/resource/CitrixResourceBaseTest.java, plugins/hypervisors/xenserver/test/com/cloud/hypervisor/xenserver/resource/XcpOssResourceTest.java, plugins/hypervisors/xenserver/test/com/cloud/hypervisor/xenserver/resource/XcpServerResourceTest.java, plugins/hypervisors/xenserver/test/com/cloud/hypervisor/xenserver/resource/XenServer56FP1ResourceTest.java, plugins/hypervisors/xenserver/test/com/cloud/hypervisor/xenserver/resource/XenServer56ResourceTest.java, plugins/hypervisors/xenserver/test/com/cloud/hypervisor/xenserver/resource/XenServer56SP2ResourceTest.java, plugins/hypervisors/xenserver/test/com/cloud/hypervisor/xenserver/resource/XenServer600ResourceTest.java, plugins/hypervisors/xenserver/test/com/cloud/hypervisor/xenserver/resource/XenServer625ResourceTest.java, plugins/hypervisors/xenserver/test/com/cloud/hypervisor/xenserver/resource/XenServer650ResourceTest.java
In this commit we created tests cases for the respective classes in package  “com.cloud.hypervisor.xenserver.resource”.
We added test cases to check the implementation of  “com.cloud.hypervisor.xenserver.resource.CitrixResourceBase.getPatchFiles”. Therefore, we test in a more comprehensive way the tests that already exist to check the code of “com.cloud.hypervisor.xenserver.resource.CitrixResourceBase.getPatchFilePath”.
We added a new abstract class, called com.cloud.hypervisor.xenserver.resource.CitrixResourceBaseTest.java
This class has two tests methods:
* com.cloud.hypervisor.xenserver.resource.CitrixResourceBaseTest.testGetPathFilesExeption(CitrixResourceBase), this method tests if the getPatchFilePath() method throws the com.cloud.utils.exception.CloudRuntimeException.CloudRuntimeExc …
=> Create test cases to getPatchFilePath method and class names changed 

server/test/async-job-component.xml
I was looking the file /cloud-server/test/async-job-component.xml, and I found an adapter configuration that seems to have no use. The reason for that is explained as follows.
The adapter configuration is the following:
<*adapters key="com.cloud.agent.manager.allocator.StorageAllocator"*>
<*adapter name="Storage"
class="com.cloud.agent.manager.allocator.impl.FirstFitStorageAllocator"*>
<*param name="storage.overprovisioning.factor"*>2<*/param*>
<*/adapter*>
<*adapter name="
class="com.cloud.agent.manager.allocator.impl.RandomStoragePoolAllocator"*>
<*param name="storage.overprovisioning.factor"*>2<*/param*>
<*/adapter*>
<*/adapters*>
•	class="com.cloud.agent.manager.allocator.impl.FirstFitStorageAllocator"
The class "com.cloud.agent.manager.allocator.impl.FirstFitStorageAllocator" does …
=> CLOUDSTACK-8988: Removed unused adapters from async-job-component.xml.

server/src/com/cloud/network/router/VirtualNetworkApplianceManagerImpl.java, systemvm/patches/debian/config/opt/cloud/bin/configure.py, systemvm/patches/debian/config/opt/cloud/bin/cs_staticroutes.py, systemvm/patches/debian/config/opt/cloud/bin/merge.py, test/integration/smoke/test_privategw_acl.py, tools/marvin/marvin/lib/common.py
This PR fixes the issue we faced with Private Gateways on single VPC when using ACS 4.6.0 and onwards.
The root cause: during the VR refactor, the static routes configuration was left unimplemented.
This PR also improves the existing Replace ACL test and adds a new test, that cover the Private Gateway in a more complete way.
The new test does the following:
1. Create 2 VPCs
2. Create 2 Tiers - 1 per VPC
3. Deploy 2 VMs - 1 per Tier
4. Acquire 2 pub IPs - 1 per VPC
5. Create 2 PF rules - 1 per pub IP
6. Create 2 ACLs + rules - 1 per VPC
7. Assign new ACLs to Tiers
8. Create 2 Private GWs - 1 per VPC
9. Replace the Pvt GWs ACLs
10. Create 2 Static routes - 1 per Pvt GW
11. SSH into VM1 (VPC1) and from there ping VM2 (VPC2)
There is also a test for Private Gateways on Redundant VPCs. But I …
=> [4.6] CLOUDSTACK-9075 - As a Developer I want the Private GW feature fixed on single VPCs

api/src/org/apache/cloudstack/affinity/AffinityGroupResponse.java, api/src/org/apache/cloudstack/affinity/AffinityGroupService.java, api/src/org/apache/cloudstack/api/command/user/affinitygroup/CreateAffinityGroupCmd.java, api/src/org/apache/cloudstack/api/command/user/affinitygroup/DeleteAffinityGroupCmd.java, api/src/org/apache/cloudstack/api/command/user/affinitygroup/ListAffinityGroupsCmd.java, api/src/org/apache/cloudstack/query/QueryService.java, engine/orchestration/src/org/apache/cloudstack/engine/cloud/entity/api/VMEntityManagerImpl.java, engine/schema/src/org/apache/cloudstack/affinity/dao/AffinityGroupDao.java, engine/schema/src/org/apache/cloudstack/affinity/dao/AffinityGroupDaoImpl.java, plugins/dedicated-resources/src/org/apache/cloudstack/dedicated/DedicatedResourceManagerImpl.java, plugins/network-elements/juniper-contrail/test/org/apache/cloudstack/network/contrail/management/IntegrationTestConfiguration.java, server/src/com/cloud/acl/AffinityGroupAccessChecker.java, server/src/com/cloud/api/query/QueryManagerImpl.java, server/src/com/cloud/api/query/vo/AffinityGroupJoinVO.java, server/src/com/cloud/configuration/ConfigurationManagerImpl.java, server/src/com/cloud/user/AccountManagerImpl.java, server/src/org/apache/cloudstack/affinity/AffinityGroupServiceImpl.java, server/test/org/apache/cloudstack/affinity/AffinityGroupServiceImplTest.java, setup/db/db/schema-460to461.sql, test/integration/component/test_affinity_groups.py, test/integration/component/test_affinity_groups_projects.py, test/integration/smoke/test_affinity_groups_projects.py, tools/marvin/marvin/lib/base.py
With some contributions from @resmo and @ustcweizhou.
This closes https://github.com/apache/cloudstack/pull/508
To test manually (need at least 2 hosts):
Create a project
Create an affinity group in that project
Deploy a vm with that affinity group
Deploy a second vm with that affinity group
They should be on different hosts
Ran old and new tests for affinity groups on the simulator
Test create affinity group as admin in project ... === TestName: test_01_admin_create_aff_grp_for_project | Status : SUCCESS ===
ok
Test create affinity group as domain admin for projects ... === TestName: test_02_doadmin_create_aff_grp_for_project | Status : SUCCESS ===
ok
Test create affinity group as user for projects ... === TestName: test_03_user_create_aff_grp_for_project | Status : SUCCESS ===
ok
Test …
=> CLOUDSTACK-6276 Fixing affinity groups for projects

debian/rules
Only now debian builds can be noredist etc.
Old PR: https://github.com/apache/cloudstack/pull/1149
cc @remibergsma
=> debian: allow rules to pick ACS_BUILD_OPTS from env

systemvm/patches/debian/config/opt/cloud/bin/cs/CsAddress.py
We need to send an Unsolicited ARP to the gateway, instead of our own address. We now encounter problems when people deploy/destroy/deploy and get the same public ip.
Packets arrive, but with incorrect / cached mac and are ignored by the routervm kernel.
Run arping manually to update the arp-cache on the gateway and things start to work.
Then we discovered the `arping` is actually done, but sent to its own address. Therefore the gateway doesn't pick it up. We only saw this happening when rapid deploy tools are used, like Terraform that do deploy/destroy/deploy and might get the same ip but on a new router having a new mac.
```
2015-12-03 18:07:25,589  CsHelper.py execute:160 Executing: arping -c 1 -I eth1 -A -U -s 192.168.23.8 192.168.23.1
```
The integration tests seem happy, although …
=> Send arping to the gateway instead of our own address

plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java, plugins/hypervisors/kvm/test/com/cloud/hypervisor/kvm/resource/LibvirtVMDefTest.java
Add function to set vapic, spinlock and retries
Add function to get retry value
Modify toString to output appropriate XML for spinlock value if set
=> [4.7] CLOUDSTACK-9004: Add features to HyperVEnlightenmentFeatureDef

ui/scripts/instanceWizard.js
Simple change to sort the security groups in alphabetical order within the instance creation wizard. 
This makes it much easier to find a security group when the user is presented with a long list.
=> CLOUDSTACK-8976 - Sorting of security groups

engine/storage/snapshot/src/org/apache/cloudstack/storage/snapshot/StorageSystemSnapshotStrategy.java
Some users encounter an exception when listSnapshots.
We should set the isRevertable of snapshot to false if the original volume is removed, without checking if the snapshot is stored in primary store (the exception was thowned during the checking).
=> CLOUDSTACK-8845: set isRevertable of snapshot to false if the volume is removed

plugins/hypervisors/ovm3/src/main/java/com/cloud/hypervisor/ovm3/resources/Ovm3HypervisorGuru.java
This PR can only be applied after PR #1176 
The CopyCommand on Ovm3 should be handled by Ovm3StorageProcessor, not SSVM.
Hence, I revert two commits on Ovm3HypervisorGuru, and add the hypervisorType check so that only the this guru will only handle Ovm3 (not KVM)
=> CLOUDSTACK-8964: Ovm3HypervisorGuru handle only srcData with HypervisorType is Ovm3

plugins/hypervisors/xenserver/src/com/cloud/hypervisor/XenServerGuru.java, server/src/com/cloud/hypervisor/HypervisorGuruManagerImpl.java
https://issues.apache.org/jira/browse/CLOUDSTACK-9025
Fix also reverts below commit as below solution making assumption about hypervisor which are not applicable in case of XenServer and VmWare
Revert "CLOUDSTACK-8964: Can't create template or volume from snapshot"
This reverts commit ccf5d75cfbe769b34c021ab3653ed318cae25933.
Testing:
Able to deploy VM successfully from template created from linked clone snapshot on XenServer.
=> CLOUDSTACK-9025: Fixed can't create usable template from snapshot in Xenserver and Vmware

plugins/api/rate-limit/pom.xml
Enables forkmode for surefire plugin and increases memory opts for JVM
for rate-limit tests. This tries to fix intermittent Jenkins failures
which look like:
multipleClientsCanAccessWithoutBlocking(org.apache.cloudstack.ratelimit.ApiRateLimitTest):
unable to create new native thread
Previous PR (again master by mistake) -- #1171
=> [4.6/master] rate-limit: increase JVM memory and enable fork mode for unit tests

plugins/api/rate-limit/pom.xml
Enables forkmode for surefire plugin and increases memory opts for JVM
for rate-limit tests. This tries to fix intermittent Jenkins failures
which look like:
multipleClientsCanAccessWithoutBlocking(org.apache.cloudstack.ratelimit.ApiRateLimitTest):
unable to create new native thread
=> [4.5] rate-limit: increase JVM memory and enable fork mode for unit tests

ui/scripts/accounts.js
Before change:
error message: ProjectId and account/domainId can't be specified together
After change:
SSH keypairs can be removed
=> [UI] fix bug: Cannot delete SSH keypairs in projects

client/bindir/cloud-setup-management.in, python/lib/cloudutils/globalEnv.py, python/lib/cloudutils/serviceConfigServer.py
This adds an option to the cloud-setup-management script to not start the management server after a successful configuration of it. 
The primary motivation for this is to avoid circular dependency issues on systems that use systemd. When calling cloud-setup-management from a unit with a Before= directive on a service depending on
cloudstack-management, the process will deadlock because /usr/bin/service will delegate to systemd, which is waiting for the Before service to start.
Executing the cloud-setup-management script with this new `--no-start` option will simply leave the management server stopped after a successful configuration. systemd can then be bypassed with `export _SYSTEMCTL_SKIP_REDIRECT=1` and using the init.d script.
=> Add support for not (re)starting server after cloud-setup-management.

plugins/network-elements/ovs/src/com/cloud/network/element/OvsElement.java, server/src/com/cloud/network/element/VirtualRouterElement.java, server/src/com/cloud/network/element/VpcVirtualRouterElement.java, server/src/com/cloud/network/router/NicProfileHelper.java, server/src/com/cloud/network/router/NicProfileHelperImpl.java, server/src/com/cloud/network/router/VpcNetworkHelperImpl.java, server/src/com/cloud/network/rules/PrivateGatewayRules.java, server/src/com/cloud/server/StatsCollector.java, server/src/org/apache/cloudstack/network/topology/AdvancedNetworkTopology.java, server/src/org/apache/cloudstack/network/topology/BasicNetworkTopology.java, server/src/org/apache/cloudstack/network/topology/NetworkTopology.java, server/src/org/apache/cloudstack/network/topology/NetworkTopologyContext.java, server/test/com/cloud/network/element/VpcVirtualRouterElementTest.java, systemvm/patches/debian/config/opt/cloud/bin/cs/CsAddress.py, test/integration/smoke/test_privategw_acl.py
This PR contains the same fixes from PR #1179, which was created against the master branch.
In addition, the points mentioned by @DaanHoogland were handled in this new PR:
* Made the code more consistent
- result = result && methodCall(), instead of throwing exceptions in some places or not checking 2 consecutive returns - in case of rVPC.
* Added an unit test to cover changes in the VpcRouterElementImpl.applyVpnUsers() method. The method returns an array of String, so I had to make sure it would contain the users from 2 consecutive calls. There are 2 tests to cover negative scenarios.
=> CLOUDSTACK-9106 - As a Developer I want the Redundant VPC private gateway feature fixed

systemvm/patches/debian/config/opt/cloud/bin/checkrouter.sh, systemvm/patches/debian/config/opt/cloud/templates/checkrouter.sh.templ, test/integration/component/test_routers_network_ops.py
This PR fixes the RVR routers state information retrieved by the Management Server via the ```checkrouter.sh``` script.
In order to cover the changes, a new test has been added to the component/test_routers_network_ops.py test suite: test_03_RVR_Network_check_router_state
=> CLOUDSTACK-9118 - As a Developer I want the checkrouter.sh script to report the right information about RVR routers state

test/integration/smoke/test_internal_lb.py
This PR make the test_internal_lb.py work with other Hypervisors types.
- Get hypervisor information from testClient.getHypervisorInfo()
- Adds XenServer, HyperV and VMware hypervisors
- Makes sure the OS type is "Other PV (64-bit)"
=> CLOUDSTACK-9123 - As a Developer I want the test_internal_lb.py to work with multiple hypervisors

api/src/org/apache/cloudstack/api/response/DomainRouterResponse.java, server/src/com/cloud/api/query/QueryManagerImpl.java, server/src/com/cloud/api/query/dao/DomainRouterJoinDaoImpl.java, server/src/com/cloud/api/query/vo/DomainRouterJoinVO.java, setup/db/db/schema-461to470.sql, ui/scripts/system.js
and two more changes:
(1) add network name/vpc name in the listRouters response
(2) add network name/vpc id, vpc name in the router details page
=> [4.7] CLOUDSTACK-9129: list vpc routers by keyword in Infrastructure -> Virtual Routers

systemvm/patches/debian/config/etc/init.d/cloud-early-config
Setup general route for RFC 1918 space, as otherwise it will be sent to the public gateway and likely to be dropped (internet providers do not route ip space that is meant for internal use). More specific routes that may be set have preference over this generic routes so this works even with private ranges used for public ip space (as shown below).
When using an internal DNS server some hosts may resolve to an RFC 1918 ip address. The SSVM has a default gw to public so if it has no route for this ip address space, it will not work. This PR makes generic RFC 1918 (so all internal ip adresses like 10.0.0.10 etc) to the local management gateway. This makes them reachable. Without this fix, it is sent upstream and it is dropped there.
Should there be a more generic route (smaller prefix), …
=> CLOUDSTACK-9143 Setup routes for RFC 1918 ip space

server/src/com/cloud/network/vpc/VpcManagerImpl.java
- It is need and already allowed/used in the current implementation. For example, the Default [redundant] VPC offerings use two LB providers. If we cannot create offerings with 2 LB providers, the whole internal loadbalancer implementation won't work.
=> CLOUDSTACK-9138 - Adds multiple providers back to VPC implementation

server/src/com/cloud/network/router/NetworkHelperImpl.java
This PR fixes the issue we were facing with crashed redundant routers not being picked up by the HA monitor due to an IF statement in the code.
* Redundant Routers are not the same as Haigh Available. Having a router HA is actually saying that the given router will be controlled by the High Availability monitor. Hence fix any problem we might face.
=> CLOUDSTACK-4374 - As a Developer I want to have HA enabled for routers that are part or a redundant network or VPC

tools/git/git-fwd-merge, tools/git/git-pr
This shows the diff in commits after using `git-pr` and `git-fwd-merge` tools, like this:
```
44e8c92 Merge pull request #1226 from borisroman/CLOUDSTACK-9148
0554610 Removed .pydevproject from plugin kvm hypervisor.
```
That helps in quickly seeing what change is applied and whether it makes sense. It doesn't touch the actual code base. I'm using this patch for some time already.
=> Show actual diff in commits after merge with git-pr / git-fwd-merge

plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtGetVmDiskStatsCommandWrapper.java, plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtGetVmStatsCommandWrapper.java
on KVM, if there is a vm has inconsistent state between hypervisor and db, the getVmStat will terminate and return null, all vm stats will not be updated.
we should skip the vm which has inconsistent state, and continue on others.
=> [4.6] CLOUDSTACK-9113: skip vm with inconsistent state when getVmStats/getVmDiskStats

api/src/com/cloud/vm/VmDetailConstants.java, core/src/org/apache/cloudstack/storage/command/AttachCommand.java, plugins/hypervisors/vmware/src/com/cloud/hypervisor/guru/VMwareGuru.java, plugins/hypervisors/vmware/src/com/cloud/hypervisor/vmware/manager/VmwareManager.java, plugins/hypervisors/vmware/src/com/cloud/hypervisor/vmware/manager/VmwareManagerImpl.java, plugins/hypervisors/vmware/src/com/cloud/hypervisor/vmware/resource/VmwareResource.java, plugins/hypervisors/vmware/src/com/cloud/storage/resource/VmwareStorageProcessor.java, server/src/com/cloud/configuration/Config.java, server/src/com/cloud/storage/VolumeApiServiceImpl.java, server/src/com/cloud/vm/UserVmManagerImpl.java, ui/scripts/templates.js, vmware-base/src/com/cloud/hypervisor/vmware/mo/ClusterMO.java, vmware-base/src/com/cloud/hypervisor/vmware/mo/DiskControllerType.java, vmware-base/src/com/cloud/hypervisor/vmware/mo/HostMO.java, vmware-base/src/com/cloud/hypervisor/vmware/mo/HypervisorHostHelper.java, vmware-base/src/com/cloud/hypervisor/vmware/mo/ScsiDiskControllerType.java, vmware-base/src/com/cloud/hypervisor/vmware/mo/VirtualMachineMO.java, vmware-base/src/com/cloud/hypervisor/vmware/mo/VmdkAdapterType.java, vmware-base/src/com/cloud/hypervisor/vmware/mo/VmdkFileDescriptor.java, vmware-base/src/com/cloud/hypervisor/vmware/mo/VmwareHypervisorHost.java, vmware-base/src/com/cloud/hypervisor/vmware/util/VmwareHelper.java
Same as #1131 (see this for screenshots etc)
=> [4.6] CLOUDSTACK-4787 - vmware diskcontrollers

ui/scripts/vpc.js
Only the owner or domain admin/admin can access the page (vpc->Network ACL Lists), they are also able to remove the network ACL lists, which is not allowed on UI.
=> [UI] bug fix: Delete added ACL lists is not available for Domain Admin and normal users

tools/marvin/marvin/deployDataCenter.py
When a marvin definition contains a primary storage definition at zone level it will default to zone scope. A test run is underway.
using marvin config:
```
{
"zones": [
{
"name": "MCCT-SHARED-1",
"guestcidraddress": "10.1.1.0/24",
"dns1": "8.8.8.8",
"physical_networks": [
{
"broadcastdomainrange": "Zone",
"vlan": "100-200",
"name": "mcct-pnet",
"traffictypes": [
{
"typ": "Guest"
},
{
"typ": "Management"
},
{
"typ": "Public"
}
],
"providers": [
{
"broadcastdomainrange": "ZONE",
"name": "VirtualRouter"
},
{
"broadcastdomainrange": "ZONE",
"name": "VpcVirtualRouter"
},
{
"broadcastdomainrange": "ZONE",
"name": "InternalLbVm"
}
],
"isolationmethods": [
"VLAN"
]
}
],
"ipranges": [
{
"startip": "192.168.23.2",
"endip": "192.168.23.20",
"netmask": "255.255.255.0",
"vlan": "50",
"gateway": …
```
=> CLOUDSTACK-9139 make zwps default when defined on zone level

engine/schema/src/com/cloud/upgrade/DatabaseUpgradeChecker.java
test build:
```
[INFO] Total time: 13:45 min
[INFO] Finished at: 2015-12-12T22:15:56+01:00
[INFO] Final Memory: 121M/914M
✔ ~/cloudstack/cloudstack [master-4.6.1 ↓·2↑·1|⚑ 18]
```
=> 4.6.2 -> 4.7.0 upgrade does not use any scripts above 4.6.1

systemvm/patches/debian/config/opt/cloud/bin/cs/CsRedundant.py
This PR fixes a blocker issue! 
- Just like with RVRs, use the VRID 51 instead of making it dependent on the VPCID
- Reason: arbitary unique number 0..255 used to differentiate multiple instances of vrrpd running on the same NIC (and hence same socket). virtual_router_id 51
=> CLOUDSTACK-9151 - As a Developer I want the VRID to be set within the limits of KeepaliveD

systemvm/patches/debian/config/etc/logrotate.d/cloud
Many processes on the VRs log to cloud.log. When log rotate kicks in, the file is rotated but the scripts still write to the old inode (cloud.log.1 after rotate). Tis quickly fills up the tiny log partition.
Using 'copytruncate' is a small tradeoff, there is a slight change of missing a log entry, but in the old situation nothing ended up in cloud.log after rotate (except for stuff that was (re)started) so I think this is the best solution until we properly rewrite the script to either use their own script or syslog.
More details: https://issues.apache.org/jira/browse/CLOUDSTACK-9155
=> CLOUDSTACK-9155 make sure logrotate is effective for cloud.log

engine/orchestration/src/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java, engine/schema/src/com/cloud/vm/dao/NicDao.java, engine/schema/src/com/cloud/vm/dao/NicDaoImpl.java
when we restart vpc tiers, the old nics will be removed, and create a new nic.
however, the device_id was set to the nic count, which may be already used.
this commit get the first device_id not in use as the device_id of new nic.
This issue also happen when we add multiple networks to a vm and remove them.
=> CLOUDSTACK-9134: set device_id as the first device_id not in use instead of nic count

tools/build/build_asf.sh
The script already adds a new entry so we shouldn't replace the
previous one. That is done only in the next version script.
As discussed with @DaanHoogland
=> build_asf.sh: fix debian changelog altering

plugins/database/quota/src/org/apache/cloudstack/api/command/QuotaBalanceCmd.java, plugins/database/quota/src/org/apache/cloudstack/api/response/QuotaResponseBuilderImpl.java, plugins/database/quota/src/org/apache/cloudstack/quota/QuotaServiceImpl.java
When querying db we use start of next day to query quota usage for
today, but while displaying it to user we still need to show it as
todays date
=> QUOTA: Ensuring that the dates displayed are as per user expectations

setup/db/db/schema-461to470.sql
Added suitable db entries in tables hypervisor_capabilities and guest_os_hypervisor to support VMware 6.0 by copying from 5.5 and excluding few depricated guest os.And also added entries for guest os RHEL 7 for vmware 5.5 and 6.0.
=> CLOUDSTACK-9103 : Missing OS Mappings for VMware 6.0

api/src/com/cloud/vm/VmDetailConstants.java, core/src/org/apache/cloudstack/storage/command/AttachCommand.java, plugins/hypervisors/vmware/src/com/cloud/hypervisor/guru/VMwareGuru.java, plugins/hypervisors/vmware/src/com/cloud/hypervisor/vmware/manager/VmwareManager.java, plugins/hypervisors/vmware/src/com/cloud/hypervisor/vmware/manager/VmwareManagerImpl.java, plugins/hypervisors/vmware/src/com/cloud/hypervisor/vmware/resource/VmwareResource.java, plugins/hypervisors/vmware/src/com/cloud/storage/resource/VmwareStorageProcessor.java, server/src/com/cloud/configuration/Config.java, server/src/com/cloud/storage/VolumeApiServiceImpl.java, server/src/com/cloud/vm/UserVmManagerImpl.java, ui/scripts/templates.js, vmware-base/src/com/cloud/hypervisor/vmware/mo/ClusterMO.java, vmware-base/src/com/cloud/hypervisor/vmware/mo/DiskControllerType.java, vmware-base/src/com/cloud/hypervisor/vmware/mo/HostMO.java, vmware-base/src/com/cloud/hypervisor/vmware/mo/HypervisorHostHelper.java, vmware-base/src/com/cloud/hypervisor/vmware/mo/ScsiDiskControllerType.java, vmware-base/src/com/cloud/hypervisor/vmware/mo/VirtualMachineMO.java, vmware-base/src/com/cloud/hypervisor/vmware/mo/VmdkAdapterType.java, vmware-base/src/com/cloud/hypervisor/vmware/mo/VmdkFileDescriptor.java, vmware-base/src/com/cloud/hypervisor/vmware/mo/VmwareHypervisorHost.java, vmware-base/src/com/cloud/hypervisor/vmware/util/VmwareHelper.java
https://issues.apache.org/jira/browse/CLOUDSTACK-4787
Allows users to configure (root and data) disk controllers for vm and vm templates.
Select disk controller while registering VM in UI:
Verified custom disk controller on vCenter/vSphere client:
=> [4.5] CLOUDSTACK-4787 - vmware diskcontrollers

test/integration/component/test_invalid_gw_nm.py
Automation for CLOUDSTACK-9214
This script automates the validation of  network address or broadcast address given for gateway or wrong netmask is given during network creation,
=> Automation for CLOUDSTACK-9214 , detect wrong GW or NM

ui/scripts/network.js
On commit a902443708ee10acb9f68fff74af346a6a9fb370 the 'listAll=true' is removed. On some places the domainid and accountid are added but not on these. I added them now.
It's either doing this, or readding listAll is true. I've seeing other folks doing that so let's see what performs best.
=> CLOUDSTACK-9221 Allow admin to see user VMs on port forwarding page

utils/src/test/java/com/cloud/utils/TestProfiler.java
The time diff measurement by the class Profiler, is done by System.nanoTime().
System.nanoTime() is not 100% accurate (lots of info on this on the web). The inaccurance seems to vary/depend with different dependencies (multi-core/OS/kernels).
Problem:
In my case the code which measures `Thread.sleep(ONE_SECOND);` ~~takes~~ measures 999 milliseconds, which breaks the test expecting the sleep of 1000 milliseconds to ~~take~~ measure at least 1000 milliseconds.
Solution:
A `MARGIN` (of 100 milliseconds) is already present to factor in some time for overhead/surrounding code which adds time. Another margin could be added to factor in the possible time measurement error.
To limit additional lines of code, the constant `ONE_SECOND`, which is used by the testcase (sleep), is increased from 1000 …
=> Factor in inaccurancy of System.nanoTime in class Profiler

setup/db/db/schema-471to480.sql
255 characters is to small for various URLs like S3 pre-signed URLs.
This causes one or more characters to be chopped of the end of the URL
and this renders them useless.
Internally in the code all URLs are passed as Strings and they are not
sized limited. This was purely in the database.
Other URL fields in the database were already 2048 characters.
This limit was introduced in the 4.1 to 4.2 upgrade when Object storage
like S3 and Swift was introduced in CloudStack for Secondary Storage.
=> CLOUDSTACK-9238: Increase URL fields to 2048 charachters from 255

api/src/com/cloud/network/Site2SiteCustomerGateway.java, api/src/org/apache/cloudstack/api/ApiConstants.java, api/src/org/apache/cloudstack/api/command/user/vpn/CreateVpnCustomerGatewayCmd.java, api/src/org/apache/cloudstack/api/command/user/vpn/UpdateVpnCustomerGatewayCmd.java, api/src/org/apache/cloudstack/api/response/Site2SiteCustomerGatewayResponse.java, api/src/org/apache/cloudstack/api/response/Site2SiteVpnConnectionResponse.java, client/WEB-INF/classes/resources/messages.properties, client/WEB-INF/classes/resources/messages_nl_NL.properties, core/src/com/cloud/agent/api/routing/Site2SiteVpnCfgCommand.java, core/src/com/cloud/agent/resource/virtualnetwork/facade/Site2SiteVpnConfigItem.java, core/src/com/cloud/agent/resource/virtualnetwork/model/Site2SiteVpn.java, core/test/com/cloud/agent/resource/virtualnetwork/VirtualRoutingResourceTest.java, engine/schema/src/com/cloud/network/dao/Site2SiteCustomerGatewayVO.java, server/src/com/cloud/api/ApiResponseHelper.java, server/src/com/cloud/network/router/CommandSetupHelper.java, server/src/com/cloud/network/vpn/Site2SiteVpnManagerImpl.java, setup/db/db/schema-470to471.sql, systemvm/patches/debian/config/opt/cloud/bin/configure.py, tools/marvin/marvin/lib/base.py, ui/dictionary2.jsp, ui/scripts/docs.js, ui/scripts/network.js, ui/scripts/vpc.js
This PR adds the option to enable forced UDP encapsulation of ESP packets during a setup of a site2site vpn. This options enforces the 'forceencaps' option in the openswan ipsec config: 
https://wiki.strongswan.org/projects/strongswan/wiki/ConnSection
=> [4.7] ADD Force UDP encapsulation option to Site2Site VPN

ui/scripts/vpc.js
Issue:
=====
Root admin cannot see LB rules and Public LB IP addresses created by domain-admin in UI therefore root admin cannot manage those.
Reproducible Steps:
Log in as a Domain-Admin account and create a VPC with vpc virtual router as public load balancer provider
click on the newly created VPC -> click on the VPC tier -> click internal LB
Add internal LB,
Logoff domain-admin and login as root admin
Navigate the VPC created previously and click internal LB, internal lb is not showing up.
Same steps for Public LB IP addresses except select the correct Network offering while creating a tier.
Root admin should be able to manage VPC created by Domain admin user .
==============
Root admin cannot see VPC created by …
=> CLOUDSTACK-9186: Root admin cannot see VPC created by Domain admin user

ui/scripts/network.js
Reproducible Steps:
1.Create a customer gateway for a VPC.
2.Edit it using UI(API call is UpdateVpnCustomerGateway).
3.When we try to update the customer vpn gateway with connection state is not in "Error", we see the API error but that won't be reflected to the user in UI.
==============
The API throws error. But UI doesn't show it to user.
The UI should show the error to user.
Fix:
===
TypeError: json.updatecustomergatewayresponse is undefined
The response name was wrong so corrected it.
It should be json.updatevpncustomergatewayresponse.
Added the error function.
=> CLOUDSTACK-9192: UpdateVpnCustomerGateway is failing

server/src/com/cloud/network/vpc/VpcManagerImpl.java
Prevent ipaddress asignment of gateway to gateway-interface on vpc router by setting vpcid to null in network. This was fixed in 4.4 by 1f209ff226a24979cf3a43ce0c02e05c84dd4dc2, reimplemented for 4.7
=> CLOUDSTACK-6485 prevent ip asignment of private gw iface

systemvm/patches/debian/config/opt/cloud/bin/cs_staticroutes.py
When deleting a static route fails because it isn't there any more (KeyError), it should succeed instead.
Error seen:
```
[INFO] Processing JSON file static_routes.json.1451560145
File "/opt/cloud/bin/update_config.py", line 140, in <module>
process_file()
File "/opt/cloud/bin/update_config.py", line 52, in process_file
qf.load(None)
File "/opt/cloud/bin/merge.py", line 258, in load
proc = updateDataBag(self)
File "/opt/cloud/bin/merge.py", line 91, in _init_
self.process()
File "/opt/cloud/bin/merge.py", line 131, in process
dbag = self.process_staticroutes(self.db.getDataBag())
File "/opt/cloud/bin/merge.py", line 179, in process_staticroutes
return cs_staticroutes.merge(dbag, self.qFile.data)
File "/opt/cloud/bin/cs_staticroutes.py", line 26, in merge …
```
=> CLOUDSTACK-9204 Do not error when staticroute is already gone

systemvm/patches/debian/config/opt/cloud/bin/checkrouter.sh
Added quotes to prevent syntax errors in weird situations.
Error seen in mgt server:
```
2015-12-15 14:30:32,371 DEBUG [c.c.a.m.AgentManagerImpl] (RedundantRouterStatusMonitor-7:ctx-0dd8ef3e) Details from executing class com.cloud.agent.api.CheckRouterCommand: Status: UNKNOWN
/opt/cloud/bin/checkrouter.sh: line 28: [: =: unary operator expected
/opt/cloud/bin/checkrouter.sh: line 31: [: =: unary operator expected
```
Cause:
```
root@r-1191-VM:/opt/cloud/bin# ./checkrouter.sh
./checkrouter.sh: line 28: [: =: unary operator expected
./checkrouter.sh: line 31: [: =: unary operator expected
Status: UNKNOWN
```
Somehow a nic was missing.
After fix the script can handle this:
```
root@r-1191-VM:/opt/cloud/bin# ./checkrouter.sh
Status: UNKNOWN
```
The other states are also reported fine:
``` …
```
=> CLOUDSTACK-9181 Prevent syntax error in checkrouter.sh

utils/src/main/java/com/cloud/utils/ssh/SSHCmdHelper.java, utils/src/main/java/com/cloud/utils/ssh/SshHelper.java
It seems the VR needs more time for some of its commands. Until we figured out the root cause, this allows the VRs to start again.
Error seen:
```
2015-12-28 14:35:18,201 ERROR [c.c.n.r.VirtualNetworkApplianceManagerImpl] (Work-Job-Executor-1:ctx-34ff7f80 job-39723/job-39726 ctx-d63de41b) Timed out in waiting SSH execution result
2015-12-28 14:35:18,201 WARN [c.c.n.r.VirtualNetworkApplianceManagerImpl] (Work-Job-Executor-1:ctx-34ff7f80 job-39723/job-39726 ctx-d63de41b) Command: com.cloud.agent.api.Command failed while starting virtua
l router
2015-12-28 14:35:18,201 INFO [c.c.v.VirtualMachineManagerImpl] (Work-Job-Executor-1:ctx-34ff7f80 job-39723/job-39726 ctx-d63de41b) The guru did not like the answers so stopping VM[DomainRouter|r-1534-VM] …
```
=> CLOUDSTACK-9202 Bump ssh timeout for VR commands

server/src/com/cloud/network/router/VirtualNetworkApplianceManagerImpl.java, systemvm/patches/debian/config/opt/cloud/bin/configure.py, systemvm/patches/debian/config/opt/cloud/bin/cs_site2sitevpn.py, test/integration/smoke/test_vpc_vpn.py
This PR:
- fixes the inability to setup more than one Site2Site VPN connection from a VPC
- fixes starting of Site2Site VPN on redundant VPC
- fixes Site2Site VPN state checking on redundant VPC
- improves the vpc_vpn test to allow multple hypervisors
- adds an integration test for Site2Site VPN on redundant VPC
Tested it on 4.7 single Xen server zone:
command:
```
nosetests --with-marvin --marvin-config=/data/shared/marvin/mct-zone1-xen1.cfg -a tags=advanced,required_hardware=true /tmp/test_vpc_vpn.py
```
results:
```
Test Site 2 Site VPN Across redundant VPCs ... === TestName: test_01_redundant_vpc_site2site_vpn | Status : SUCCESS ===
ok
Test Remote Access VPN in VPC ... === TestName: test_01_vpc_remote_access_vpn | Status : SUCCESS ===
ok
Test Site 2 Site VPN Across VPCs ... === …
```
=> [4.7] FIX Site2SiteVPN on redundant VPC

systemvm/patches/debian/config/etc/logrotate.d/cloud
Delay Compress results in more space usage than needed. Since we have copy truncate we don't need it.
=> CLOUDSTACK-9222 Prevent cloud.log.1 filling up the disk

server/src/com/cloud/network/router/NicProfileHelperImpl.java, test/integration/smoke/test_privategw_acl.py
When a VPC has a private gateway, and one would like to restart the VPC with **cleanup** it would fail.
This PR adds a NullPointer check and verifies it with an integration test.
```
test_01_vpc_privategw_acl (integration.smoke.test_privategw_acl.TestPrivateGwACL) ... === TestName: test_01_vpc_privategw_acl | Status : SUCCESS ===
ok
test_02_vpc_privategw_static_routes (integration.smoke.test_privategw_acl.TestPrivateGwACL) ... === TestName: test_02_vpc_privategw_static_routes | Status : SUCCESS ===
ok
test_03_vpc_privategw_restart_vpc_cleanup (integration.smoke.test_privategw_acl.TestPrivateGwACL) ... === TestName: test_03_vpc_privategw_restart_vpc_cleanup | Status : SUCCESS ===
ok
test_04_rvpc_privategw_static_routes (integration.smoke.test_privategw_acl.TestPrivateGwACL) ... === …
```
=> NicProfileHelperImpl NullpointerException when ipVO is null

engine/orchestration/src/com/cloud/agent/manager/AgentManagerImpl.java, plugins/network-elements/nicira-nvp/src/main/java/com/cloud/network/resource/wrapper/NiciraCheckHealthCommandWrapper.java, plugins/network-elements/nicira-nvp/src/test/java/com/cloud/network/resource/wrapper/NiciraCheckHealthCommandWrapperTest.java
The NSX plugin does not support the HeathCheckCommand. Instead it fakes a PingCommand as a call tot he control cluster status API.
However, we have seen in production that the management server will sometimes find the NSX controller to be behind on ping and that will trigger a HealthCheckCommand which will return with an unsupported command answer.
Once this happens the controller is put into Alert state and will not recover until the management sever is restarted.
In addition, during the investigation, there will be a null pointer exception due tot he fact that the NSX controllers do not live in a pod.
This PR tries to address those two issues.
=> Add Health Check Command to NSX plugin

scripts/vm/network/security_group.py
This is a mandatory argument but it was NOT passed which caused the
re-programming of security groups to fail.
Simple fix to just add the argument since the variable is available
there.
=> CLOUDSTACK-9210: Pass secondary IPs to default_network_rules() function

scripts/storage/secondary/createtmplt.sh, scripts/storage/secondary/createvolume.sh
Both createvolume.sh and createtmplt.sh have a 40GB hardcoded limit for the size of the template that gets created. I could not find any justification of that. I am just removing them as they caused us a huge headache when we tried to create bigger templates and they failed without any good error.
This closes #1223 (This PR was against master, made a new one against 4.7)
Thanks Syed <syed1.mushtaq@gmail.com>
=> CLOUDSTACK-9240 remove 40GB filesize limit from SSVM scripts

tools/marvin/marvin/lib/base.py
In create_from_snapshot function of Template class there is no parameter to accept if the template is public hence default it is creating private templates 
Hence adding this parameter.
=> CLOUDSTACK-9041: Modifying template creation from snapshot function 

test/integration/testpaths/testpath_snapshot_limits.py
Modifying tearDown function to check if data volume is in detached state before deleting the volume
=> CLOUDSTACK-9005: Modifying tearDown function

test/integration/testpaths/testpath_uuid_event.py
Currently snapshots results validation is based on length of snapshot result but if snapshot creation fails then None type object will not have "len" attribute hence modifying the validation.
=> CLOUDSTACK-9001: Modifying snapshot results validation 

ui/scripts/cloudStack.js
Removed the unnecessary return statement.
The statement is never reached.
=> CLOUDSTACK-9230: Remove unnecessary return statement from cloudStack.js

plugins/network-elements/nicira-nvp/src/main/java/com/cloud/network/nicira/ExecutionCounter.java, plugins/network-elements/nicira-nvp/src/test/java/com/cloud/network/nicira/ExecutionCounterTest.java
The NSX plugin has a execution counter to prevent infinite recursion (and as a result a stack overflow exception). However, the thread safeness of this counter are not as desired. The counter was implemented with an AtomicInteger which make it safe for multiple threads to update and read it. The desired property would be to have a counter per thread.
This PR addresses that issue.
=> Implement a NSX API request execution counter per thread

core/src/com/cloud/agent/api/MigrateWithStorageCommand.java, core/src/com/cloud/agent/api/MigrateWithStorageReceiveAnswer.java, core/src/com/cloud/agent/api/MigrateWithStorageReceiveCommand.java, core/src/com/cloud/agent/api/MigrateWithStorageSendCommand.java, plugins/hypervisors/xenserver/src/com/cloud/hypervisor/xenserver/resource/wrapper/xen610/XenServer610MigrateWithStorageReceiveCommandWrapper.java, plugins/hypervisors/xenserver/src/com/cloud/hypervisor/xenserver/resource/wrapper/xen610/XenServer610MigrateWithStorageSendCommandWrapper.java, plugins/hypervisors/xenserver/src/org/apache/cloudstack/storage/motion/XenServerStorageMotionStrategy.java, plugins/hypervisors/xenserver/test/com/cloud/hypervisor/xenserver/resource/wrapper/xenbase/XenServer610WrapperTest.java
EXPECTED BEHAVIOUR:
====================
Root Volume migration within cluster should work.
ACTUAL BEHAVIOUR:
Root volume migration within cluster failed.
This situation arises when there are two management server accessing the same database.
When the migration request comes the command is forwarded from one management server to another because the host is owned by the second management server. So, serialisation of map from one to another fails.
Fix:
===
This is fixed by converting the maps to lists.
=> CLOUDSTACK-9231: Root volume migration from one primary to another primary storage within the same cluster is failing

ui/scripts/metrics.js, ui/scripts/ui-custom/metricsView.js
- Implement Search boxes in all Metrics views
- Fix threshold calculations for host and storage pool metrics view
- Consider overcommit ratios for calculation allocated thresholds
- Save/pass context while navigating across resources and metrics view
cc @remibergsma @DaanHoogland
=> ui: improve metrics view implementation

api/src/org/apache/cloudstack/api/command/user/volume/CreateVolumeCmd.java, server/src/com/cloud/storage/VolumeApiServiceImpl.java, server/test/com/cloud/storage/VolumeApiServiceImplTest.java, ui/scripts/docs.js, ui/scripts/storage.js
Create a volume using createVolume API where parameter name is empty.
It creates a volume with empty name.
But the name parameter is mandatory.(Issue)
It shouldn't create a volume with an empty name. Error should be returned.
Solution:
=======
Added a condition to check in case of empty string. If the name is an empty string, it generates a random name for the volume. Made the name field optional in UI as well as in API.
=> CLOUDSTACK-9132: API createVolume takes empty string for name parameter

plugins/hypervisors/kvm/test/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtUtilitiesHelperTest.java
This test failed on Windows, using the File.separator it should run fine on Windows.
=> test: Fix Libvirt test so that it works on Windows

ui/scripts/network.js
Load balancing health check option / button should only be displayed when a NetScaler based networking offering is being used. 
If you try to use the health check option when NetScaler is not being used as the load balancing technology the UI throws an error stating that the health check option is not supported. 
This button / option should be removed from the UI if NetScaler is not included in the network offering as customers will be confused. 
Fix:
===
This button will be shown only when the load balancer is NetScaler.
Otherwise it is hidden.
=> CLOUDSTACK-9236: Load Balancing Health Check button displayed when non-NetScaler offering is used

systemvm/patches/debian/config/etc/init.d/cloud-early-config
Public ip var was empty so routes were always set. Corrected this.
=> CLOUDSTACK-9244 Fix setting up RFC1918 routes

api/src/org/apache/cloudstack/api/command/admin/account/LockAccountCmd.java
an API call to LockAccount fails silently with a 200 return and no contents. client are responsible to check and will find that no locking has actually occured. This way they may be lured to a sense of false security.
Throwing an exption makes the failure explicit.
cloudmonkey lock account name=<name> domainid=<id>
now errors out with an http result of 530
=> CLOUDSTACK-9239 throw exception on deprecated command

plugins/event-bus/rabbitmq/pom.xml, plugins/event-bus/rabbitmq/src/org/apache/cloudstack/mom/rabbitmq/RabbitMQEventBus.java
When rabbitmq connections are blocked(for example when rabbitmq is
server is out of space), all the cloudstack threads which does any
action and publishes to rabbitmq(for example login, launch vm etc.) are
all blocked.
Added a blocked connection listener to handle this and unblock the
parent thread.
also updated rabbitmq amqp client to 3.5.4 from 3.4.2 
Testing:
I didnt find a way to write tests for this change as of now. 
manually tested that login and other cloudstack apis work when the configured rabbitmq server goes out of space and publish actions are blocked.
=> Cloudstack-8885 added blocked connection listener for rabbitmqeventbus 

server/src/com/cloud/network/lb/LoadBalancingRulesManagerImpl.java, ui/scripts/ui-custom/healthCheck.js
Browser - Chrome Version 47.0.2526.106 m
Steps to Repro:
============
Open up - Network-Guest Networks -> IP Addresses-> IP<Static NAT> -> Load Balancing
- click on the "Configure" button below the healthcheck, 
- opens a "label.heath.check.wizard"
Issues:
======
(1) Please see the snapshot attached
- leave the default values as is and click on the "Create" 
- opens a "Status" dialog with an error message
(2) Message on the dialog goes outside the window
Fix:
===
Increased the size of width of dialog box.
Json response parsing was missing. Added it.
Snapshot for Error Message Issue:
===========================
Snapshot of the fix:
Snapshot for out of window issue:
==========================
Snapshot of the fix:
=> CLOUDSTACK-9237: Create LB Healthcheck issues - button alignment and error message goes outside the window

ui/scripts/network.js
Autoscale button is missing. This should not be the case since we are able to add NS as the external LB provider in VPC.
Steps:
=====
1. Create a VPC offering with NS as the external LB provider
2. Create a VPC and configure the public tier with the above offering
3. Acquire an IP address and try to configure Load Balancing rule
Result:
======
Autoscale option is not visible at all for the LB.
Expected Result:
=============
Autoscale option should be available and should work exactly like the way it works for a normal isolated network with NS. If we choose NS as service provider for LB, autoscale should also be visible. If VR is chosen, only then we should not display autoscale.
Fix:
===
In case of VPC, it checks the services available.
If LB is there, It checks the provider is Netscaler …
=> CLOUDSTACK-9235: Autoscale button is missing in VPC

ui/scripts/autoscaler.js, ui/scripts/ui-custom/autoscaler.js
Autoscale policy creation is failing on VPC while creating autoscalevmprofile since zoneid parameter is missing.
1. Create VPC Network offering with NS as service provider for LB
2. Create VPC using offering which has NetScaler as LB provider
3. Add a tier using the network offering created in Step1
4. Launch a VM
5. Acquire a public IP
6. Create an auto scale policy with all required parameters on an LB rule
Result:
======
Fails during autoscalevmprofile creation with the following error:
GET  command=createAutoScaleVmProfile&response=json&serviceofferingid=05ac866f-604c-43e2-a48b-47e83ef7c4f1&templateid=3cdd83c4-ad27-11e5-9eaf-42407779c24b&destroyvmgraceperiod=30&counterparam%5B0%5D.name=snmpcommunity&counterparam%5B0%5D.value=public&counterparam%5B1% …
=> CLOUDSTACK-9229: Autoscale policy creation failing in VPC due to zone id missing in createAutoScaleVmProfile

systemvm/patches/debian/config/opt/cloud/bin/configure.py
Ping @remibergsma 
Integration tests runnning now!
=> More VR performance!

ui/css/cloudstack3.css, ui/scripts/ui/core.js
The arrow always fell off when I log in ;-)
Before change it looked like this:
Now also longer names display nicely:
Ping @borisroman
=> CLOUDSTACK-9254: Make longer names display pretty in UI

api/src/com/cloud/network/vpc/NetworkACLService.java, server/src/com/cloud/network/vpc/NetworkACLManagerImpl.java, server/src/com/cloud/network/vpc/NetworkACLServiceImpl.java, server/src/com/cloud/network/vpc/VpcManagerImpl.java, server/test/com/cloud/vpc/NetworkACLManagerTest.java
This PR fixes the issue when trying to delete ACL lists which contain item. 
It seemed it was not thought of when the ACS project started, when most user were relying on the UI to execute those tasks. Nowadays, with automation all over the place and ACL lists containing hundreds of items, it's very hard to have to delete them 1 by 1 either via the UI. Writing scripts to do so might be a solution, but it would be much simpler to just delete non-attached ACLs with all its items in one go.
Also, destroying a VPC that contains ACL lists was "succeeding", but after that the ACL list/items were messing up:
```
list networkacls aclid=920d74b6-4d15-454f-b3a6-61e7a6ffd1a4
Error 431: Unable to find VPC associated with acl
{
"cserrorcode": 4350,
"errorcode": 431,
"errortext": "Unable to find VPC …
```
=> CLOUDSTACK-9245 - Cannot delete non-attached ACL that contains items

systemvm/patches/debian/config/opt/cloud/bin/cs_staticroutes.py
Static routes that are being set do not show up in the static_routes.json file. The reason for this is that the index that is used, is the gateway address, which is not unique. Hence stuff is overwritten and lost.
Ping @borisroman @wilderrodrigues @DaanHoogland
=> CLOUDSTACK-9256 add unique key for static routes in json

framework/quota/src/org/apache/cloudstack/quota/QuotaManagerImpl.java, framework/quota/src/org/apache/cloudstack/quota/vo/QuotaBalanceVO.java, plugins/database/quota/src/org/apache/cloudstack/api/response/QuotaResponseBuilderImpl.java, test/integration/plugins/test_quota.py, tools/marvin/marvin/config/setup.cfg
1. Create a dummy user, as existing user may already have stale quota
data
2. fix the tests to use the dummy user
3. a boundary condition was revealed and fixed for a new user where
quota service has never run and created bootstrap entries
=> CLOUDSTACK-9161: fix the quota marvin test

engine/orchestration/src/com/cloud/vm/VirtualMachineManagerImpl.java
Summary: The target "ClusteredVirtualMachineManagerImpl.HandlePowerStateReport" invoked during the VM power state sync is not found as HandlePowerStateReport was not implemented in ClusteredVirtualMachineManagerImpl and was private in VirtualMachineManagerImpl, which was resulting in InvocationTargetException. Changed HandlePowerStateReport() in VirtualMachineManagerImpl to protected.
=> CLOUDSTACK-9185: [VMware DRS] VM sync failed with exception due to out-of-band changes

server/src/com/cloud/api/query/dao/VolumeJoinDaoImpl.java
CLOUDSTACK-8858: listVolumes API fails for a particular domain with NPE.
Summary: listVolumes API fails when volume associated vm instance has NULL or invalid state. Fix the code to guard this situation since this should not block volume listing.
=> CLOUDSTACK-8858: listVolumes API fails for a particular domain with NPE.

server/src/com/cloud/consoleproxy/AgentBasedStandaloneConsoleProxyManager.java
The AgentBasedStandaloneConsoleProxyManager class is neither manually
instatiated anywhere in the code nor via Spring. Further checking in the
interface which the class implements, shows that the use for classes
implementing the EventBus interface relies on instances generated by the
Spring framework, which discards the possibility of the class being
created by EJB. Being the class useless, it was discarded.
=> Removal of class AgentBasedStandaloneConsoleProxyManager

engine/api/src/org/apache/cloudstack/engine/subsystem/api/storage/DataMotionStrategy.java, engine/storage/datamotion/src/org/apache/cloudstack/storage/motion/AncientDataMotionStrategy.java, engine/storage/datamotion/src/org/apache/cloudstack/storage/motion/StorageSystemDataMotionStrategy.java, engine/storage/integration-test/test/org/apache/cloudstack/storage/test/MockStorageMotionStrategy.java, plugins/hypervisors/hyperv/src/org/apache/cloudstack/storage/motion/HypervStorageMotionStrategy.java, plugins/hypervisors/simulator/src/org/apache/cloudstack/storage/motion/SimulatorDataMotionStrategy.java, plugins/hypervisors/vmware/src/org/apache/cloudstack/storage/motion/VmwareStorageMotionStrategy.java, plugins/hypervisors/xenserver/src/org/apache/cloudstack/storage/motion/XenServerStorageMotionStrategy.java
The main changes are:
-	Changing methods “Void” to “void”.
-	Removal of the method “Void copyAsync(DataObject srcData, DataObject
destData, AsyncCompletionCallback<CopyCommandResult> callback)” that was
never used.
We noticed that methods form that class are using the return type Void
with capital V. This way that method has to return a null value at the
end. 
Removed trim lines from XenServerStorageMotionStrategy.
The trim lines were removed from XenServerStorageMotionStrategy.
=> Fixed return type Void to void in  DataMotionStrategy.

setup/bindir/cloud-set-guest-sshkey.in
For now, if we add the ssh key inside the vm (not on cloudstack UI), the sshkey will be removed if we reset the sshkey on cloudstack UI.
After this commit, the sshkey (added by cloudstack) will end with cloudstack@apache.org.
We will only control the sshkeys with cloudstack@apache.org.
This will be used for multiple sshkey support for vm in the future.
=> CLOUDSTACK-5822: keep user-added sshkeys in authorized_keys

engine/components-api/src/com/cloud/network/NetworkStateListener.java, engine/orchestration/src/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java, server/src/com/cloud/network/IpAddressManagerImpl.java
We removed the following variables from "com.cloud.network.NetworkStateListener"
. UsageEventDao _usageEventDao
. NetworkDao _networkDao
We changed the EventBus s_eventBus variable to private, the constructor not to use those variables and applied this change in classes “com.cloud.network.IpAddressManagerImpl” and “org.apache.cloudstack.engine.orchestration.NetworkOrchestrator”
=> Removed unused variables from "NetworkStateListener" class

engine/orchestration/src/com/cloud/vm/VirtualMachineManagerImpl.java
https://issues.apache.org/jira/browse/CLOUDSTACK-9196
NullPointerException can occur if XenServer reports non-existing VM in cloud DB.
=> CLOUDSTACK-9196: Fixing null pointer exception when vm meta data is synced on upgraded setup

ui/plugins/plugins.js, ui/plugins/quota/quota.js, ui/scripts/accounts.js, ui/scripts/cloudStack.js, ui/scripts/instances.js, ui/scripts/metrics.js, ui/scripts/system.js
According to SonarQube this is a bug on internet explorer. It is the only 'blocker' level issue in cloudstack. @abhinandanprateek (@agneya2001) @bhaisaab @miguelaferreira should we enforce this or, as alternative, have it disabled in SonarQube?
=> trailing commas in javascripts removed

server/test/com/cloud/event/ActionEventUtilsTest.java
The test class was merged without the license header. This commit fixes that problem.
Also note that the license header exists on the master branch only as a result of commit 8a5fc16. The commit seems to be on the master branch and the 4.7 branch only. So there may be some conflicts when forward merging.
=> Add missing license header to ActionEventUtilsTest.

setup/db/db/schema-481to490.sql
When there are many events in the cloud.event table, the UI throws an SQL exception and the management server spikes at 100% CPU for minutes. That causes other API calls to fail with 530 errors.
It seems an index on the 'archived' field is missing (since it is used in the WHERE clause).
We have 1.4M events in the table:
`select count(*) from event;`
1497838
This PR adds the index to the `archived` field and the `state` field.
=> CLOUDSTACK-8300: Set indexes on event table

ui/scripts/network.js
The hostname a router is running on is only displayed on Infra tab and not on the VPC page (the link local is mentioned though). That is now corrected, so you have the correct details to login to the router straight away.
Before:
After:
So the option 'Host' was added and displays the hypervisor the VPC runs on.
=> Display hostname the VPC router runs on

systemvm/patches/debian/config/opt/cloud/bin/configure.py
Static routes for private gateways that were /32 failed because the `route` command used had `-net` in it and a `/32` requires `-host` instead. I rewrote it to `ip` commands.
=> CLOUDSTACK-9264: Make /32 static routes for private gw work

systemvm/patches/debian/config/opt/cloud/bin/cs_staticroutes.py
The to-be-deleted static routes were removed from the json file, instead of putting them there with revoke=true. The script that parses the json now doesn't find it and thus does not delete it.
Example after adding/removing some:
```
root@r-3-VM:/var/cache/cloud# cat /etc/cloudstack/staticroutes.json 
{
"1.2.3.0/24": {
"gateway": "172.16.0.1", 
"ip_address": "172.16.0.2", 
"network": "1.2.3.0/24", 
"revoke": true
}, 
"1.2.3.4/32": {
"gateway": "172.16.0.1", 
"ip_address": "172.16.0.2", 
"network": "1.2.3.4/32", 
"revoke": true
}, 
"1.2.33.3/32": {
"gateway": "172.16.0.1", 
"ip_address": "172.16.0.2", 
"network": "1.2.33.3/32", 
"revoke": true
}, 
"1.22.2.2/32": {
"gateway": "172.16.0.1", 
"ip_address": "172.16.0.2", 
"network": "1.22.2.2/32", 
"revoke": true
}, 
"10.1.2.1/32": { …
```
=> CLOUDSTACK-9266: Make deleting static routes in private gw work

test/integration/testpaths/testpath_revert_snap.py
In testpath_revert_snap.py, there was no code to check if VM snapshot is created or not hence adding code for snapshot validation.
=> CLOUDSTACK-9121: Adding VmSnapshot validation in testpath_revert_snap.py

test/integration/component/test_coreos.py, tools/marvin/marvin/config/test_data.py, tools/marvin/marvin/lib/base.py
https://issues.apache.org/jira/browse/CLOUDSTACK-9012
Automated a full scenario of coreos guest OS support:
it includes registering coreos templates present at http://dl.openvm.eu/cloudstack/coreos/x86_64/
1. based on hypervisor types of zone
2. creating ssh key pair
3. creating a sample user data
4. creating a coreos virtual machine using this ssh keypair and userdata
5. verifying ssh access to coreo os machine using keypair and core username
6. verifying userdata is applied on virtual machine and the service asked in sample data is actually running
7. Verifying userdata in router vm as well
=> CLOUDSTACK-9012 :automation of cores feature test path

test/integration/testpaths/testpath_restore_vm.py
On setup with two cluster wide primary storage verify restoring a running instance.(As while restoring instance root disk may get created on another primary storage.)
=> CLOUDSTACK-8717: Failed to start instance after restoring the running instance 

test/integration/testpaths/testpath_volume_snapshot.py
In testpath_volume_snapshot testpath creating volume from snapshot function is passing zonid parameter to function in base class but there it doesn't take as separate parameter it takes it from "services" so updating it.
=> CLOUDSTACK-9091: Update testpath for parameter issues

test/integration/testpaths/testpath_storage_migration.py
Adding service_offering creation in testpath_storage_migration.py testpath which is missing right now
=> CLOUDSTACK-9026: Modifying testpath for adding missing parameter

plugins/hypervisors/vmware/src/com/cloud/hypervisor/vmware/resource/VmwareResource.java, plugins/hypervisors/vmware/test/com/cloud/hypervisor/vmware/resource/VmwareResourceTest.java
JIRA TICKET: 
https://issues.apache.org/jira/browse/CLOUDSTACK-9211 
CS support passing hypervisor options by creating entries in <code>vm_template_details</code> or <code>user_vm_details</code>
To enable software 3D GPU 4 options needs to be added:
| name| value |
|:-------------:|:-------------:|
|mks.enable3d|true|
|mks.use3dRenderer|automatic|
|svga.autodetect|false|
|svga.vramSize|(size in KB) e.g. 131072|
Currently all options except <code>svga.vramSize</code> works, VMs always get configured with default 64Mb videoRAM instead of the one provided on the option.
=> CLOUDSTACK-9211: Support passing vRAM size to support 3D GPU on Vmware

test/integration/testpaths/testpath_snapshot_hadrning.py
In testpath_snapshot_hardning.py testpath account was getting cleared prior to VM's of that account hence while cleaning up the account the VM's in that account also gets deleted hence while clearing VM's it gives exception as "No VM found".
=> CLOUDSTACK-9066: Update testpath to delete account after deleting VM's of that account 

api/src/org/apache/cloudstack/api/command/user/vpn/CreateVpnCustomerGatewayCmd.java, api/src/org/apache/cloudstack/api/command/user/vpn/UpdateVpnCustomerGatewayCmd.java
According to:
http://linux.die.net/man/5/ipsec.secrets
A preshared secret is most conveniently represented as a sequence of characters, delimited by the double-quote character ("). The sequence cannot contain a newline or double-quote.
=> ADD be explicit about the underlying limitation - OpenSwan

api/src/com/cloud/vm/VmDetailConstants.java, plugins/hypervisors/vmware/src/com/cloud/hypervisor/guru/VMwareGuru.java, plugins/hypervisors/vmware/src/com/cloud/hypervisor/vmware/resource/VmwareResource.java, plugins/hypervisors/vmware/src/com/cloud/storage/resource/VmwareStorageProcessor.java, server/src/com/cloud/storage/VolumeApiServiceImpl.java, server/src/com/cloud/vm/UserVmManagerImpl.java
Change com.cloud.vm.VmDetailConstants variable name from "ROOK_DISK_CONTROLLER" to "ROOT_DISK_CONTROLLER". The ROOK_DISK_CONTROLLER variable stores the "rootDiskController" String; thus, this PR changes the name to "ROOT_DISK_CONTROLLER".
=> Change variable "ROOK_DISK_CONTROLLER" to "ROOT_DISK_CONTROLLER"

agent/src/com/cloud/agent/Agent.java
Per Daan's request, here is a pull request for the 4.7.x release.
=> CLOUDSTACK-9285 for 4.7.x

services/secondary-storage/server/src/org/apache/cloudstack/storage/resource/NfsSecondaryStorageResource.java
Fix new find bug error that was introduced in PR #1361 
Report: http://jenkins.buildacloud.org/job/build-master-slowbuild/3455/findbugsResult/new/
It is the same fix as the one proposed in #1427; the difference is that this PR tried to change only the code that was strictly needed. However, I took the liberty to remove a dead code and few lines of code (annotations) that were not needed
=> Fix new error found in findbugs slow build #3455

api/src/org/apache/cloudstack/api/BaseResponseWithTagInformation.java, api/src/org/apache/cloudstack/api/response/ResourceTagResponse.java, api/src/org/apache/cloudstack/api/response/TemplateResponse.java, api/src/org/apache/cloudstack/api/response/UserVmResponse.java, api/src/org/apache/cloudstack/api/response/VolumeResponse.java, framework/db/src/com/cloud/utils/db/SqlGenerator.java, server/src/com/cloud/api/query/dao/GenericDaoBaseWithTagInformation.java, server/src/com/cloud/api/query/dao/TemplateJoinDaoImpl.java, server/src/com/cloud/api/query/dao/UserVmJoinDaoImpl.java, server/src/com/cloud/api/query/dao/VolumeJoinDaoImpl.java, server/src/com/cloud/api/query/vo/BaseViewWithTagInformationVO.java, server/src/com/cloud/api/query/vo/ResourceTagJoinVO.java, server/src/com/cloud/api/query/vo/TemplateJoinVO.java, server/src/com/cloud/api/query/vo/UserVmJoinVO.java, server/src/com/cloud/api/query/vo/VolumeJoinVO.java, server/test/com/cloud/api/query/dao/GenericDaoBaseWithTagInformationBaseTest.java, server/test/com/cloud/api/query/dao/TemplateJoinDaoImplTest.java, server/test/com/cloud/api/query/dao/UserVmJoinDaoImplTest.java, server/test/com/cloud/api/query/dao/VolumeJoinDaoImplTest.java, setup/db/db/schema-481to490.sql
JIRA TICKET: https://issues.apache.org/jira/browse/CLOUDSTACK-9298 
When retrieving a large number of resources which have tags associated with, retrieval methods took too long. Our goal is to improve performance of this methods avoiding query the database for each tag, managing that information in memory.
API methods to improve: <code>listTemplates</code>, <code>listVolumes</code>, <code>listVirtualMachines</code>
To achive it, it's necessary to include new columns in <code>template_view</code>, <code>volume_view</code> and <code>user_vm_view</code>:
* tag_account_name
* tag_domain_name
* tag_domain_uuid
=> CLOUDSTACK-9298: Improve performance of resource retrieval that have tags associated and target volumes, VMs and templates

plugins/storage/image/swift/src/org/apache/cloudstack/storage/datastore/driver/SwiftImageStoreDriverImpl.java, server/src/com/cloud/template/TemplateManagerImpl.java, utils/src/main/java/com/cloud/utils/SwiftUtil.java, utils/src/test/java/com/cloud/utils/SwiftUtilTest.java
This PR adds the ability to download templates when using Swift as a secondary storage. Uses the "temp_url" feature of Swift so that tempates can be downloaded without authenticaiton.
=> Add ability to download templates in Swift

framework/quota/src/org/apache/cloudstack/quota/QuotaAlertManagerImpl.java, framework/quota/src/org/apache/cloudstack/quota/QuotaManagerImpl.java, framework/quota/src/org/apache/cloudstack/quota/QuotaStatementImpl.java, plugins/database/quota/src/org/apache/cloudstack/api/command/QuotaSummaryCmd.java, plugins/database/quota/src/org/apache/cloudstack/api/response/QuotaResponseBuilderImpl.java, ui/plugins/quota/quota.js
When an account is deleted from cloudstack for which quota is still
being calculated and if the quota reaches minimum threshold then
quota service will try to alert the user. This results in NPE and is
fixed by excluding such accounts from alerting and other quota related
mechanisms.
=> CLOUDSTACK-9174: A deleted account results in NPE

engine/components-api/src/com/cloud/capacity/CapacityManager.java, engine/storage/src/org/apache/cloudstack/storage/endpoint/DefaultEndPointSelector.java, server/src/com/cloud/capacity/CapacityManagerImpl.java, setup/db/db/schema-481to490.sql
JIRA TICKET: https://issues.apache.org/jira/browse/CLOUDSTACK-9333 
In some environments there is a need to exclude certain VMware clusters from performing OVF operations. This operations are part of: 
* create template
* create volume snaphsot
* copy template, volume, images from primary storage to secondary storage
* migrate volume 
* participate when a template gets cached over to primary storage.
In ESX/ESXi, OVF operations are low priority and bound to a single CPU and most likely get throttled to certain IOPS and network limits. 
If the hypervisor chosen for OVF operations is weak or overloaded this results in significantly longer execution of such OVF command and therefore degraded performance of underlying CloudStack API call.
It is proposed to add a way to exclude hosts from …
=> CLOUDSTACK-9333: Exclude clusters from OVF operations

tools/travis/install.sh
Outputs for modules that fail or succeed with unit tests results.
Based on the issue raised in https://github.com/apache/cloudstack/pull/1466 this PR aims at increasing Travis build output so we can know which unit test fail.
/cc @swill @nvazquez -- let me know if we just allow outputting everything will help? I had restricted the output as including all of them would disallow viewing the tabular final integration/marvin tests at the end (only possible by viewing raw output of each travis job).
=> travis: increase build verbosity

engine/storage/snapshot/src/org/apache/cloudstack/storage/snapshot/StorageSystemSnapshotStrategy.java, engine/storage/snapshot/src/org/apache/cloudstack/storage/snapshot/XenserverSnapshotStrategy.java
The ticket this PR fixes was opened because KVM-specific code had been added to the StorageSystemSnapshotStrategy class and that class' canHandle method was only prepared to handle managed storage being used with XenServer (and a case was hit for KVM that triggered a CloudRuntimeException to be thrown).
To solve the problem, I moved the KVM logic to the default snapshot strategy class, which is (unfortunately) named XenserverSnapshotStrategy.
I plan to rename XenserverSnapshotStrategy to something like DefaultSnapshotStrategy in 4.9.
My guess is that when XenserverSnapshotStrategy was originally written, it was written only for XenServer, but has since that time had its usage increased to support other hypervisors (with non-managed storage).
=> CLOUDSTACK-9297 - Reworked logic in StorageSystemSnapshotStrategy and XenserverSnapshotStrategy

ui/scripts/network.js
The field we use most are now on the top:
- name
- state
- hypervisor
- link local ip
- redundant state
The other fields are nice, but not needed most of the time.
Result:
Before:
=> Improve ordering of fields of VPC router detail tab

agent/src/com/cloud/agent/Agent.java
After discussion with @miguelaferreira on the previous PR related to Cloudstack-9285, we decided on adding additional exception logging for this issue.
After adding it, the logs look like this in our lab:
2016-04-07 15:44:03,298 WARN  [cloud.agent.Agent] (Agent-Handler-1:null) (logid:7225632a) NIO Connection Exception com.cloud.utils.exception.NioConnectionException: Connection closed with -1 on reading size.  <<-- new exception logging
2016-04-07 15:44:03,298 INFO  [cloud.agent.Agent] (Agent-Handler-1:null) (logid:7225632a) Attempted to connect to the server, but received an unexpected exception, trying again... << --original logging from previous PR.
=> Cloudstack-9285 exception log addition

systemvm/patches/debian/config/opt/cloud/bin/configure.py
-- This PR is replacing speedup iptables setup #1449 
-- Squashing commits and cleanup
PR against 4.7 as discussed with Remi Bergsma. This will speed up the iptables creation on the virtual router.
Testing showed the following:
with current code:
root@kvm704:~# time /usr/share/cloudstack-common/scripts/network/domr/router_proxy.sh vr_cfg.sh 169.254.1.176 -c /var/cache/cloud/VR-12f28879-de7e-44d2-8dbe-b93a04bd3ba4.cfg
real 2m56.401s
user 0m0.012s
sys 0m0.012s
modified version:
root@kvm704:~# time /usr/share/cloudstack-common/scripts/network/domr/router_proxy.sh vr_cfg.sh 169.254.1.176 -c /var/cache/cloud/VR-12f28879-de7e-44d2-8dbe-b93a04bd3ba4.cfg
real 1m35.762s
user 0m0.020s
sys 0m0.004s
=> speedup iptables by prefetching the variables

utils/src/main/java/com/cloud/utils/Profiler.java, utils/src/test/java/com/cloud/utils/TestProfiler.java
The TestProfiler class was using Java Thread methods to test the
Profiler's functionality. That was causing the tests to fail sometimes
since the JVM's thread priority could be low on some OS. 
Using PowerMockito to mock the System calls, the threads could be
removed. This makes the tests considerably faster, OS independent and
still guarantees the correct implementation of the Profiler class.
The changes on the Profiler's class was only to shorten the class's line
size by not assigning the return value to a variable returning it
straight out.
=> Fixed Profiler's unit tests bugs.

api/src/org/apache/cloudstack/api/ApiServerService.java, server/src/com/cloud/api/ApiServer.java, server/src/com/cloud/api/ApiServlet.java, server/test/com/cloud/api/ApiServletTest.java
**Removed “\_” from variables names**: private variables with “\_” at the beginning is common in C++ but not in Java.
**Removed unused code from ApiServer:**
- com.cloud.api.ApiServer.getPluggableServices(): unused method;
- com.cloud.api.ApiServer.getApiAccessCheckers(): unused method;
**Methods and variables access level reviewed:**
- com.cloud.api.ApiServer.handleAsyncJobPublishEvent(String, String ,Object): this method was private but the annotation @MessageHandler requests public methods, as can be seen in org.apache.cloudstack.framework.messagebus.MessageDispatcher.buildHandlerMethodCache(Class\<?\>), which searches methods with the @MessageHandler annotation and changes
it to be accessible (“setAccessible(true)”). Thus, there is no reason for handleAsyncJobPublishEvent be a private …
=> Removed unused code from com.cloud.api.ApiServer

plugins/hypervisors/xenserver/src/com/cloud/hypervisor/xenserver/resource/CitrixResourceBase.java, plugins/hypervisors/xenserver/src/com/cloud/hypervisor/xenserver/resource/XcpOssResource.java, plugins/hypervisors/xenserver/test/com/cloud/hypervisor/xenserver/resource/CitrixResourceBaseTest.java, plugins/hypervisors/xenserver/test/com/cloud/hypervisor/xenserver/resource/XcpOssResourceTest.java, plugins/hypervisors/xenserver/test/com/cloud/hypervisor/xenserver/resource/XcpServerResourceTest.java, plugins/hypervisors/xenserver/test/com/cloud/hypervisor/xenserver/resource/XenServer56FP1ResourceTest.java, plugins/hypervisors/xenserver/test/com/cloud/hypervisor/xenserver/resource/XenServer56ResourceTest.java, plugins/hypervisors/xenserver/test/com/cloud/hypervisor/xenserver/resource/XenServer56SP2ResourceTest.java, plugins/hypervisors/xenserver/test/com/cloud/hypervisor/xenserver/resource/XenServer600ResourceTest.java, plugins/hypervisors/xenserver/test/com/cloud/hypervisor/xenserver/resource/XenServer625ResourceTest.java, plugins/hypervisors/xenserver/test/com/cloud/hypervisor/xenserver/resource/XenServer650ResourceTest.java
Considering that all mapping of Guest OS Names to their respective hypervisor compatible types is made thorugh accessing a database, we've decided to remove a bit of code in the XcpOssResource class which was doing that same thing for 2 different OS's (both of which ARE in the database). That has led us to a bunch of unused parameters in the getGuestOsType method from its superclass, which we've also decided to remove. Test cases were added for four different possibilities for the platformEmulator String: one for a null String, one for a blank String, one for an empy String and one for a random case with a valid String.
=> Removed unnecessary code from getGuestOsType in CitrixResourceBase

ui/scripts/ui/widgets/multiEdit.js
Steps of Repro:
=============
1:Create VMs 
2:Make LoadBalancing rule in GUI 
　Name:WWW 
　PrivatePort:80 
　PublicPort:80 
　Add VMs:some VMs
Expected Result:
==============
The VMs which has been already assigned is should not be listed when you add the VM to an existing rule.
Actual Result:
===========
The VMs which has been already assigned is still being listed when you add the VM to an existing rule.
Fix:
===
Added jsonObj to newly created row in multiedit.js to stop listing the same VM again.
=> CLOUDSTACK-9268: Display VM in Load balancing rule in UI

ui/css/cloudstack3.css
Steps to Repro:
============
Please see the snapshots attached. 
Fix:
===
Now it breaks into two lines once the word goes out of the box.
Fixed the advanced search field issue.
Network Section:
=============
Adding VM to LB Rule:
Affinity Group Section:
Fixed Affinity Group Section:
======================
=> CLOUDSTACK-9270: UI alignment gone bad in multiple places - VM Instance, Network, Egress rules

ui/scripts/regions.js
Steps to Repro:
============
Go to Regions -> Local -> View GSLB -> Add GSLB
Click on the service type dropdown
Observe http is missing. Please see the attached snapshot.
As it supports http also, So http should be in the list.
==============
http is missing from the list.
Fix:
===
It supports http also. Added http to the list.
Snapshot:
========
=> CLOUDSTACK-9272: No option in UI to add GSLB with service type "HTTP"

systemvm/patches/debian/config/opt/cloud/bin/configure.py
Check the existence of 'forceencap' parameter before use.
Error seen:
```
File "/opt/cloud/bin/update_config.py", line 140, in <module>
process_file()
File "/opt/cloud/bin/update_config.py", line 54, in process_file
finish_config()
File "/opt/cloud/bin/update_config.py", line 44, in finish_config
returncode = configure.main(sys.argv)
File "/opt/cloud/bin/configure.py", line 1003, in main
vpns.process()
File "/opt/cloud/bin/configure.py", line 488, in process
self.configure_ipsec(self.dbag[vpn])
File "/opt/cloud/bin/configure.py", line 544, in configure_ipsec
file.addeq(" forceencaps=%s" % CsHelper.bool_to_yn(obj['encap']))
KeyError: 'encap'
```
=> Check the existence of 'forceencap' parameter before use

packaging/centos63/cloud-management.rc, packaging/centos7/cloud-management.service, scripts/vm/systemvm/injectkeys.sh
- In injectkeys.sh which is used to inject new public keys everytime cloudstack
starts; while copying files preserve the mode/ownership. This ensures the
scripts have same mode bits as originally configured in the iso file
- The default umask of 0022 is set in Ubuntu and other packages. Set the same
in case of CentOS startup scripts
cc @abhinandanprateek @wido @remibergsma @DaanHoogland @jburwell
=> systemvm: preserve file permissions, set default umask

ui/scripts/templates.js
Added a check to ignore the zoneid, in the delete template UI, if the template is cross zones.
reference : CLOUDSTACK-9172
=> CLOUDSTACK-9172 Added cross zones check to delete template and iso

test/integration/component/test_redundant_router_cleanups.py
Please refer CLOUDSTACK-9218 for more details
Test Results:
===========
Test restarting RvR network without cleanup after destroying master VR ... === TestName: test_restart_ntwk_MVR_destroyed | Status : SUCCESS ===
ok
Ran 1 test in 581.194s
OK
=> [CLOUDSTACK-9218]Test to verify restart network after master VR destroyed

test/integration/component/test_add_remove_network.py
Please refer bug CLOUDSTACK-9219 for more details.
Test Results:
==========
Test to verify vm start after NIC removal and reattach ... === TestName: test_30_remove_nic_reattach | Status : SUCCESS ===
ok
Ran 1 test in 277.478s
OK
=> New test to validate starting vm after nic removal and attach

tools/marvin/marvin/lib/base.py
This fixes the following ticket: https://issues.apache.org/jira/browse/CLOUDSTACK-9354
The problem was that Marvin was requiring you to pass in the "ispublic" parameter when creating a template from a snapshot.
As the ticket notes, this issue was introduced by the following commit: https://git-wip-us.apache.org/repos/asf?p=cloudstack.git;a=commit;h=bbe0fc4be9527d51820b067a602886003991db4d
The solution I've provided is simply to check if the "ispublic" property is in the dictionary before referencing it.
=> Fixing an issue in Marvin around creating a template from a snapshot

test/integration/component/test_vpc.py
While adding vpn customer gateway for site to site vpn connection, cs should also accept host name apart from gateway ip address. It should not be restricted to just ip address.
=> Test to create vpn customer gateway with hostname

utils/src/main/java/com/cloud/utils/ssh/SshHelper.java, utils/src/test/java/com/cloud/utils/ssh/SshHelperTest.java
Continuing the work started by @likitha, I did not cherry-picked the 
commit (b9181c689e0e7b5f1e28c81d73710196dfabd0ba) from PR <https://github.com/apache/cloudstack/pull/561> due to the fact that the path of that SshHelper class was different of the current SshHelper; that is because the fact that by cherry-picking it would seem that I had changed all the class as the code is from another file.
I made some changes from the cherry-picked commit adding @wilderrodrigues suggestions (create simple methods to have reusable code, make unit tests and create the `WAITING_OPEN_SSH_SESSION` variable to manipulate with the delay of 1000 milliseconds).
Also, I tried to simplify the logic by assuming that ....
if ((conditions & ChannelCondition.EXIT_STATUS) != 0) {
if ((conditions & …
=> CLOUDSTACK-8611:Handle SSH if server "forget" to send exit status

test/integration/component/maint/test_ha_pool_maintenance.py
put storage in maintenance mode and start ha vm and check usage ... === TestName: test_ha_with_storage_maintenance | Status : SUCCESS ===
ok
Ran 1 test in 842.294s
OK
=> CLOUDSTACK-8745 : verify usage after root disk migration

systemvm/js/ajaxviewer.js
https://issues.apache.org/jira/browse/CLOUDSTACK-9164
To test:
In Firefox open any VM conosle, and try typing "/". 
It should be typed in VM console and quick search of firefox should not open.
=> CLOUDSTACK-9164: Prevent firefox's quick search from opening in VM console

utils/src/test/java/com/cloud/utils/SwiftUtilTest.java
**Problem:**
File separator in windows ("\") is different from the expected in the test ("/"); thus, the test *com.cloud.utils.SwiftUtilTest.testSplitSwiftPath()* will fail in Windows systems.
The problem is that the input of the test is "*container/object*" but the tested method uses the *File.separator* (that depends from the OS), in windows systems the tested method (*com.cloud.utils.SwiftUtil.splitSwiftPath(String)*) looks for a "\", as the string does not contain "\" it returns an empty string and consequently results in a test failure.
**Solution:**
Create a string `String input = "container" + File.separator + "object";`, with that the test will validate the tested method verifying if the method splits the string around matches of the given regular expression (in this case …
=> CLOUDSTACK-9352: Test fails in Widows as the file separator "/" is different from "\"

plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtMigrateCommandWrapper.java, plugins/hypervisors/kvm/test/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java, plugins/hypervisors/kvm/test/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtMigrateCommandWrapperTest.java
The problem arises when the origin hypervisor has an ip addres that ends with 1, like '10.10.10.1' and the qemu VM description is containing an address that has that as part of its address, '10.10.10.100' for instance.
now migrating to '10.10.10.10' will change both addresses in the xml description file for qemu. It is fixed and unit tests are added. I am not sure yet how to integration test this. Regression will probably work so creating a PR now.
=> CLOUDSTACK-9142 Migrate VM changes xmlDesc in a safe way

client/pom.xml, engine/api/pom.xml, engine/service/pom.xml, framework/quota/src/org/apache/cloudstack/quota/QuotaStatementImpl.java, framework/quota/test/org/apache/cloudstack/quota/QuotaStatementTest.java, framework/rest/pom.xml, plugins/event-bus/kafka/pom.xml, plugins/event-bus/rabbitmq/pom.xml, plugins/hypervisors/hyperv/pom.xml, plugins/network-elements/globodns/pom.xml, plugins/network-elements/juniper-contrail/pom.xml, plugins/network-elements/netscaler/pom.xml, plugins/storage/volume/cloudbyte/pom.xml, plugins/user-authenticators/ldap/pom.xml, plugins/user-authenticators/saml2/pom.xml, pom.xml, server/pom.xml, services/console-proxy-rdp/rdpconsole/pom.xml, services/secondary-storage/server/pom.xml, tools/checkstyle/pom.xml, tools/whisker/LICENSE, tools/whisker/descriptor-for-packaging.xml, usage/pom.xml, utils/pom.xml
Upgrades maven dependencies versions that can be safely upgraded without breaking console-proxy/crypto usage.
Bisected changes from: https://github.com/apache/cloudstack/pull/1397
cc @swill @DaanHoogland
=> 4.9 mvn version safeupgradeonly

server/src/com/cloud/api/ApiServer.java
Currently API responses for synchronous calls are logged, but asynchronous call responses are not.  This pull request makes a minor modification that logs the response including the JobId of all asynchronous requests.
As an example, here is what a stopVirtualMachine request looked like in the logs:
2016-04-27 10:43:11,084 INFO  [a.c.c.a.ApiServer] (catalina-exec-3:ctx-37d9f693 ctx-d2368de3) (logid:3a0fad97) (userId=2 accountId=2 sessionId=AF8B1F726ACB5C3A637B8B300AA218A7) 10.103.0.207 -- GET command=stopVirtualMachine&id=f63b6fcc-e0b0-480f-8f7a-cba329634ba1&forced=false&response=json&_=1461771791036 200 
After this modification, here is what the logs look like:
2016-04-27 13:37:11,338 INFO  [a.c.c.a.ApiServer] (catalina-exec-6:ctx-915b5c84 ctx-a03152fa) (logid:66249df0) (userId=2 …
=> Log asynchronous responses in the api log

server/src/com/cloud/storage/VolumeApiServiceImpl.java, test/integration/component/test_volumes.py, tools/marvin/marvin/lib/base.py
This PR addresses the KVM detach/attach ROOT disks from VMs (CLOUDSTACK-9349).  In short, this allows the KVM Hypervisor, and I added the Simulator as a valid hypervisor for ease of development and testing of marvin, to detach a root volume and the reattach a root volume using the deviceid=0 flag to the attachVolume API.  I have also written a marvin integration test that verifies this feature works for both KVM and the Simulator.
Below is the marvin results files of the full marvin test_volumes.py.  All tests pass, including the new root detach/attach, on our KVM lab running with the patches in this PR.
[test_volumes_KIR4G3.zip](https://github.com/apache/cloudstack/files/223799/test_volumes_KIR4G3.zip)
=> CLOUDSTACK-9349: Enable root disk detach for KVM with new Marvin tests

engine/schema/src/com/cloud/upgrade/dao/Upgrade410to420.java
Found this issue when using MySQL 5.7 with Ubuntu 16.04. The upgrade path fix removes an invalid `IGNORE` param that is deprecated now, in the upgrade path we run the alter statement to add an index only if it does not exist so we're good.
For MySQL 5.7, we'll also need to update the docs at some point to include `server-id` along with other parameters. Some of the SQL statements used throughout engine/schema don't adhere to SQL 99 standard which is enforced by default in MySQL 5.7, therefore the following sql-mode (for backward compatibility with mysql 5.6 modes) will be necessary for anyone willing to use MySQL 5.7 (until we fix codebase wide raw and generated sql statements to be SQL99 compliant):
sql-mode="STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION,ERROR_FOR_DIVISION_BY_ZERO,NO_ZERO_DA …
=> engine/schema: fix upgrade path to work with MySQL 5.7

packaging/systemd/cloudstack-usage.service
cloudstack-usage fails to start throwing Integer exception during PID retrieval, and the service keeps restarting after 10s (as defined in the systemd service definition).
Adding the pid to the java arguments in the systemd service definition makes it stop looping in centos7
=> CLOUDSTACK-9283: add pid to java arguments in cloudstack-usage.service

engine/orchestration/src/com/cloud/vm/VirtualMachineManagerImpl.java, engine/orchestration/test/com/cloud/vm/VirtualMachineManagerImplTest.java, server/src/com/cloud/api/query/QueryManagerImpl.java
When calling listServiceOfferings with VM id as parameter. It is returning incompatible tagged offerings. It should only list all compatible tagged offerings. Compatible means the new service offering should contain all the tags of the existing service offering(Existing offering SUBSET of new offering). If that is the case It should list in the result and can be upgraded to that offering.
=> CLOUDSTACK-8847: ListServiceOfferings is returning incompatible tagged offerings when called with VM id

test/integration/smoke/test_loadbalance.py
No more false positives after this change.
```
[root@cs1 integration]# cat /tmp//MarvinLogs/test_loadbalance_TR5RJD/results.txt
Test to create Load balancing rule with source NAT ... === TestName: test_01_create_lb_rule_src_nat | Status : SUCCESS ===
ok
Test to create Load balancing rule with non source NAT ... === TestName: test_02_create_lb_rule_non_nat | Status : SUCCESS ===
ok
Test for assign & removing load balancing rule ... === TestName: test_assign_and_removal_lb | Status : SUCCESS ===
ok
Ran 3 tests in 930.418s
OK
```
=> Bump ssh retries to prevent false positives of test_loadbalance

debian/control
If you do not install bzip2, then installing templates that are bzip2 compressed will result in Cloudstack not being able to extract the contents and ending up copying the template in compressed form.  This will result in VMs not being able to start.
=> Installing bzip2 since it is required for extracting templates

plugins/user-authenticators/ldap/src/org/apache/cloudstack/api/command/LinkDomainToLdapCmd.java, plugins/user-authenticators/ldap/src/org/apache/cloudstack/ldap/LdapAuthenticator.java
The 10th field of `createUserAccount` is `networkDomain` (See `AccountService.java`) and it is set to a var named `admin`, which is the user name.
So, the first user that is created in a domain that links to LDAP, creates the account within the domain, and sets the `networkDomain` field to the username. All next users are created in the same account.
Then we have the situation that in domain SBP we have a user `rbergsma` that logs in first, gets an account created and then (unless you override) all VMs started in the SBP domain will have network domain `rbergsma`. That is highly confusing and not what is should be.
The `linkDomainToLdap` api call has no `networkDomain` field, so I propose to make this field empty (set it to null). It's a sting and null / empty is allowed.
One can also …
=> Set default networkDomain to empty instead of username

packaging/systemd/cloudstack-usage.service
With DB HA enabled in db.properties, the cloudstack-usage service restarts every 10 seconds.  Making the suggested change has fixed it for me.  Cloudstack 4.8 on Centos7
=> CLOUDSTACK-9305: Cloudstack Usage Breaks if DB HA enabled

engine/storage/snapshot/pom.xml, engine/storage/snapshot/src/org/apache/cloudstack/storage/snapshot/XenserverSnapshotStrategy.java, plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java
Snapshot removing implemented if primary datastore is RBD
https://issues.apache.org/jira/browse/CLOUDSTACK-8302
=> CLOUDSTACK-8302: Removing snapshots on RBD

engine/orchestration/src/com/cloud/agent/manager/ClusteredAgentManagerImpl.java, utils/pom.xml, utils/src/main/java/com/cloud/utils/nio/Link.java, utils/src/main/java/com/cloud/utils/nio/NioClient.java, utils/src/main/java/com/cloud/utils/nio/NioConnection.java, utils/src/main/java/com/cloud/utils/nio/NioServer.java, utils/src/test/java/com/cloud/utils/testcase/NioTest.java
- Uses non-blocking socket config in NioClient and NioServer/NioConnection
- Scalable connectivity from agents and peer clustered-management server
- Removes blocking ssl handshake code with a non-blocking code
- Protects from denial-of-service issues that can degrade mgmt server responsiveness
due to an aggressive/malicious client
- Uses separate executor services for handling connect/accept events
Changes are covered the NioTest so I did not write a new test, advise how we can improve this. Further, I tried to invest time on writing a benchmark test to reproduce a degraded server but could not write it deterministic-ally (sometimes fails/passes but not always). Review, CI testing and feedback requested /cc @swill @jburwell @DaanHoogland @wido @remibergsma @rafaelweingartner …
=> CLOUDSTACK-9348: Use non-blocking SSL handshake in NioConnection/Link

scripts/vm/network/security_group.py
It could happen that when multiple instances are starting at the same
time on a KVM host the Agent spawns multiple instances of security_group.py
which both try to modify iptables/ebtables rules.
This fails with on of the two processes failing.
The instance is still started, but it doesn't have any IP connectivity due
to the failed programming of the security groups.
This modification lets the script aqcuire a exclusive lock on a file so that
only one instance of the scripts talks to iptables/ebtables at once.
Other instances of the script which start will poll every 500ms if they can
obtain the lock and otherwise execute anyway after 15 seconds.
=> kvm: Aqcuire lock when running security group Python script

utils/src/main/java/com/cloud/utils/nio/Link.java, utils/src/main/java/com/cloud/utils/nio/NioConnection.java, utils/src/test/java/com/cloud/utils/testcase/NioTest.java
- Reduces SSL handshake timeout to 15s, previously this was only 10s in
commit debfcdef788ce0d51be06db0ef10f6815f9b563b
- Adds an aggresive explicit wakeup to save the Nio main IO loop/handler from
getting blocked
- Fix NioTest to fail/succeed in about 60s, previously this was 300s
- Due to aggresive wakeup usage, NioTest should complete in less than 5s on most
systems. On virtualized environment this may slightly increase due to thread,
CPU burst/scheduling delays.
/cc @swill  please review and merge.
Sorry about the previous values, they were not optimized for virtualized env. The aggressive selector.wakeup will ensure main IO loop does not get blocked even by malicious users, even for any timeout (ssl handshake etc).
=> CLOUDSTACK-9348: Optimize NioTest and NioConnection main loop

engine/api/src/org/apache/cloudstack/engine/subsystem/api/storage/EndPointSelector.java, engine/storage/src/org/apache/cloudstack/storage/endpoint/DefaultEndPointSelector.java, plugins/hypervisors/ovm3/src/main/java/com/cloud/hypervisor/ovm3/resources/Ovm3HypervisorGuru.java, plugins/hypervisors/xenserver/src/com/cloud/hypervisor/XenServerGuru.java, server/src/com/cloud/hypervisor/HypervisorGuruBase.java
Following the discussions and analysis presented on PR #1056 create by @DaanHoogland
This PR is intended to push those changes that were discussed there regarding the of endPointSelector.selectHypervisorHost method.
=> CID-1338387: Deletion of method endPointSelector.selectHypervisorHost

.travis.yml, api/src/org/apache/cloudstack/api/ApiConstants.java, api/src/org/apache/cloudstack/api/command/user/snapshot/ListSnapshotsCmd.java, api/src/org/apache/cloudstack/api/command/user/template/ListTemplatesCmd.java, api/src/org/apache/cloudstack/api/command/user/vmsnapshot/ListVMSnapshotCmd.java, api/src/org/apache/cloudstack/api/command/user/volume/ListVolumesCmd.java, server/src/com/cloud/api/query/MutualExclusiveIdsManagerBase.java, server/src/com/cloud/api/query/QueryManagerImpl.java, server/src/com/cloud/storage/snapshot/SnapshotManagerImpl.java, server/src/com/cloud/vm/snapshot/VMSnapshotManagerImpl.java, server/test/com/cloud/api/query/MutualExclusiveIdsManagerBaseTest.java, test/integration/smoke/test_list_ids_parameter.py
A new parameter is added in each method, its type a list of IDs of the entity, it will be mutually exclusive with id. (Similar to <code>id</code> and <code>ids</code> parameters in <code>listVirtualMachines</code> method)
* <code>listTemplates</code>: new parameter **<code>ids</code>**, mutually exclusive with <code>id</code>
* <code>listVolumes</code>: new parameter **<code>ids</code>**, mutually exclusive with <code>id</code>
* <code>listSnapshots</code>: new parameter **<code>ids</code>**, mutually exclusive with <code>id</code>
* <code>listVMSnapshots</code>: new parameter **<code>vmsnapshotids</code>**, mutually exclusive with <code>vmsnapshotid</code>
=> CLOUDSTACK-9351: Add ids parameter to resource listing API calls

client/bindir/cloud-update-xenserver-licenses.in, debian/control, packaging/centos63/cloud.spec, packaging/centos7/cloud.spec, packaging/fedora20/cloud.spec, packaging/fedora21/cloud.spec, python/lib/cloudutils/db.py, setup/bindir/cloud-migrate-databases.in
MySQLdb has been deprecated and is also not supported in Python 3.
mysql.connector is a connector written in Python which talks the
native MySQL protocol without any external code.
https://dev.mysql.com/doc/connector-python/en/
=> CLOUDSTACK-8818: Use MySQL native connector with Python

agent/src/com/cloud/agent/AgentShell.java
IPv4 is still preferred, so if the hostname of the Management Server
returns a A and AAAA-record the Agent will still connect to the
server over IPv4.
This situation will however allow to use a hostname which only has
a AAAA-record. In that case the Agent will connect to the Management
Server over IPv6.
=> agent: Enable IPv6 connectivity for KVM Agent to Management Server

tools/marvin/marvin/codes.py, tools/marvin/marvin/lib/base.py
https://issues.apache.org/jira/browse/CLOUDSTACK-9374
From the ticket:
In the base.py file, there is a Host class with a delete instance method.
This method first attempts to transition the host into the maintenance resource state.
The first step in this process is to transition the host into the prepare-for-maintenance resource state.
A while later, the host can be transitioned completely into the maintenance resource state.
In an attempt to wait for this transition to occur, the delete method has a timer.sleep(30) call.
The hope is that the host will have transitioned from the prepare-for-maintenance resource state to the maintenance resource state within 30 seconds, but this does not always happen.
We should correct this problem by putting in logic to query the management server for …
=> Marvin: Replace a timer.sleep(30) with pulling logic

engine/components-api/src/com/cloud/template/TemplateManager.java, server/src/com/cloud/template/TemplateManagerImpl.java
The thread pool was hardcoded to use 8 threads,
com.cloud.template.TemplateManagerImpl.configure(String, Map<String, Object>):
_preloadExecutor = Executors.newFixedThreadPool(8, new NamedThreadFactory("Template-Preloader"));
Added the change to pick threadpool size from configuration.
=> CLOUDSTACK-8901: PrepareTemplate job thread hard-coded to max 8 threads

ui/scripts/templates.js
When a zone name is available, the previous behaviour is still there:
When there is no zone name, it used to display an empty name (where you had to click on to see details):
With this change, a default name `All` is displayed (because this happens when S3 storage is used that is region wide aka all zones):
Region wide S3:
FYI: Screenshot shows 'All', later renamed to 'All Zones', see code.
=> When no zone name is available display a default

server/src/com/cloud/network/element/VirtualRouterElement.java, server/src/com/cloud/network/element/VpcVirtualRouterElement.java, server/src/com/cloud/network/router/CommandSetupHelper.java, server/src/com/cloud/network/router/NicProfileHelperImpl.java, server/src/com/cloud/network/router/VpcVirtualNetworkApplianceManagerImpl.java, server/src/com/cloud/network/vpc/NetworkACLManagerImpl.java, server/src/org/apache/cloudstack/network/topology/AdvancedNetworkTopology.java, systemvm/patches/debian/config/opt/cloud/bin/configure.py, systemvm/patches/debian/config/opt/cloud/bin/cs/CsAddress.py, systemvm/patches/debian/config/opt/cloud/bin/cs/CsHelper.py, systemvm/patches/debian/config/opt/cloud/bin/cs/CsRedundant.py, test/integration/smoke/test_privategw_acl.py
This is work by @wilderrodrigues, see PR #1413 It contains important fixes and I think it needs to be included so I send the PR again.
=> CLOUDSTACK-9287 - Fix unique mac address per rVPC router

systemvm/patches/debian/config/opt/cloud/bin/configure.py, systemvm/patches/debian/config/opt/cloud/bin/cs/CsRedundant.py, systemvm/patches/debian/config/opt/cloud/bin/cs/CsStaticRoutes.py
Refactored static routes for private gateways so they also get loaded when the router switches to master state. Otherwise they're lost and connections drop after fail over.
=> Apply static routes on change to master state

tools/marvin/marvin/lib/base.py
We have some methods in base.py that are named the same.
Per my findings below, Python methods in a class should not be named the same even if one is a class method and the other is an instance method.
The solution discussed on dev@ is to remove the instance versions (reason listed in e-mail text, which is listed in JIRA ticket).
https://issues.apache.org/jira/browse/CLOUDSTACK-9373
=> CLOUDSTACK-9373: Class methods over-shawdowing instance methods

engine/storage/integration-test/test/org/apache/cloudstack/storage/test/TestHttp.java, framework/cluster/src/com/cloud/cluster/ClusterServiceServletHttpHandler.java, plugins/network-elements/brocade-vcs/src/com/cloud/network/brocade/BrocadeVcsApi.java, plugins/network-elements/brocade-vcs/test/com/cloud/network/brocade/BrocadeVcsApiTest.java, plugins/network-elements/nicira-nvp/src/test/java/com/cloud/network/nicira/NiciraNvpApiTest.java
some cleanup done
- replaced HttpStatus from org.apache.commons.httpclient with that from org.apache.http
- removed unthrown HttpException
- left auto reformat in place
=> CLOUDSTACK-9265 cleanup around httpclient versions

utils/pom.xml
Historically NioTest has caused issue in CI environment and several developer machines due to network requirements which could be disabled by firewall or security enforcers such as selinux. This disables the test once again using a historic commit 881a6e1
Signed-off-by: Rohit Yadav <rohit.yada
To build and just run this test: mvn clean install -pl utils -Dtest=NioTest
=> Disable NioTest

systemvm/patches/debian/config/opt/cloud/bin/cs/CsConfig.py, systemvm/patches/debian/config/opt/cloud/bin/cs/CsDatabag.py
This patch addresses two issues:
On redundant VR setups, the primary resolver being handed out to instances is the guest_ip (primary IP for the VR). This might lead to problems upon failover, at least while the DHCP lease doesn't update (because the primary resolver will be checked first until times out, however it'll be gone upon failover).
If Global Setting use_ext_dns is true, we don't want the VR to be the primary resolver at all.
=> Honour GS use_ext_dns and redundant VR VIP

plugins/outofbandmanagement-drivers/ipmitool/test/org/apache/cloudstack/outofbandmanagement/driver/ipmitool/IpmitoolWrapperTest.java, test/integration/component/test_acl_listvolume.py, test/integration/smoke/test_outofbandmanagement.py, utils/src/main/java/com/cloud/utils/nio/Link.java, utils/src/main/java/com/cloud/utils/nio/NioConnection.java, utils/src/test/java/org/apache/cloudstack/utils/process/ProcessTest.java
- Reverts ea2286 that introduced a wakeup on each connection loop run.
- In SSL handshake code removes delegated tasks to be run in separate threads.
/cc @kiwiflyer @swill @jburwell and others for review
@kiwiflyer please help me test this fix and share if it makes the NioConnection robust now, without having the selector consume a lot of CPU. Thanks.
=> Fix Nio/CPU issue and CI failures

api/src/org/apache/cloudstack/api/command/user/vm/DeployVMCmd.java
https://issues.apache.org/jira/browse/CLOUDSTACK-9199
To test:
-------------
Deploy VM by providing cpuNumber, cpuSpeed or memory for static/ non dynamic service offering
Deployment should fail.
API example:
------------------
http://10.220.135.6/client/api?command=deployVirtualMachine&name=olotwo&response=&zoneid=ab6e4154-62a3-42a8-9627-3cbdc66bcbb6&templateid=3aaaace6-91b4-11e5-b6fc-e26c2aa1d1d0&hypervisor=XenServer&serviceofferingid=39643075-4b45-489d-afac-88f09d536bdd&details[0].cpuNumber=1&details[0].cpuSpeed=1000&details[0].memory=1000&securitygroupids=60844698-91b4-11e5-b6fc-e26c2aa1d1d0&_=1448277187743
=> CLOUDSTACK-9199: Fixed deployVirtualMachine API does not throw an error when cpunumber is specified for static compute offering

plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
CPU socket count reporting correction
From https://github.com/MissionCriticalCloud/cosmic-plugin-hypervisor-kvm/pull/16
=> CPU socket count reporting correction

packaging/centos63/cloud.spec, packaging/centos7/cloud.spec, packaging/fedora20/cloud.spec, packaging/fedora21/cloud.spec, python/lib/cloudutils/serviceConfigServer.py, server/conf/cloudstack-catalina.logrotate
rebased and squashed
replacement for PR: https://github.com/apache/cloudstack/pull/1087
Remove extraneous log directory (/var/log/cloudstack-management)
and adds catalina.out log rotation
=> Remove extraneous log directory and add catalina.out log rotation

framework/db/src/com/cloud/utils/db/GenericDaoBase.java
I came along this part of the code and I don't see any reason why the cache should not be used when fetching with the "removed" ones. It will help decrease the number of DB queries.
*It can be merged in many CS versions*
=> DAO: Hit the cache for entity flagged as removed too

debian/control
Required to run perl scripts that configure networking for VMs.
=> Add perl-modules as install dependency for cloudstack-agent

systemvm/patches/debian/config/opt/cloud/bin/configure.py, systemvm/patches/debian/config/opt/cloud/bin/cs/CsAddress.py, systemvm/patches/debian/config/opt/cloud/bin/cs/CsDhcp.py, systemvm/patches/debian/config/opt/cloud/bin/cs/CsLoadBalancer.py, systemvm/patches/debian/config/opt/cloud/bin/cs/CsNetfilter.py, systemvm/patches/debian/config/opt/cloud/bin/cs_iptables_save.py
This makes handling the firewall rules about 50-60 times faster because it is generated in memory and then loaded once. It's work by @borisroman see PR #1400. Reopened it here because I think this is a great improvement.
=> Restore iptables at once using iptables-restore instead of calling iptables numerous times

server/src/com/cloud/network/router/VirtualNetworkApplianceManagerImpl.java, systemvm/patches/debian/config/opt/cloud/bin/cs/CsDatabag.py, systemvm/patches/debian/config/opt/cloud/bin/cs/CsFile.py, systemvm/patches/debian/config/opt/cloud/bin/cs/CsRedundant.py
Global setting `router.redundant.vrrp.interval` is not used any more and it is now set to a hardcoded 1. 
This results in a failover from master->backup when the backup doesn't hear from the master in ~3.6sec. This is a bit too tight, as we've seen failovers during live migrations. We could reproduce it in about half of the cases. Setting this to setting to 2 (tested it by hardcoding it in the systemvms) gives twice as much time and we didn't see issues any more. Instead of updating the hardcoded setting from 1 to 2, I reimplemented the global setting by sending it to the router with the cmd_line, as the non-VPC router also does.
Background:
Why is the maximum failover time in the example 3.6 seconds? This comes from the advertisement interval and the skew time. The default advertisement …
=> Reimplement router.redundant.vrrp.interval setting

engine/storage/src/org/apache/cloudstack/storage/datastore/ObjectInDataStoreManagerImpl.java, server/src/com/cloud/test/TestAppender.java, services/secondary-storage/server/pom.xml, services/secondary-storage/server/src/org/apache/cloudstack/storage/resource/NfsSecondaryStorageResource.java, services/secondary-storage/server/test/org/apache/cloudstack/storage/resource/LocalNfsSecondaryStorageResourceTest.java, services/secondary-storage/server/test/org/apache/cloudstack/storage/resource/NfsSecondaryStorageResourceTest.java
When using Swift as a secondary storage, we create a template.properties file which stores the metadata about the template. Currently the data which is present in the file is incorrect which leads to templates becoming unavailable after they are downloaded. This fix makes sure that the template.properties has the correct "path" set so that templates are available. 
I've also done a bit of cleanup and made the code bit more clean.
=> Fix Sync of template.properties in Swift

agent/bindir/libvirtqemuhook.in
From the [JIRA issue](https://issues.apache.org/jira/browse/CLOUDSTACK-9362):
> https://github.com/apache/cloudstack/commit/bb8f7c652e42caacff5adce1ce60342603677605
> 
> The above commit introduces rewriting of bridge device names when migrating a virtual machine from one host to another. However, it also matches bridges called "brvx-1234" and rewrites them to (in my case) "brem1-1234" - this doesn't match the bridge name on the destination and causes the migration to fail with the error:
> 
> error : virNetDevGetMTU:397 : Cannot get interface MTU on 'brem1-1234': No such device
> 
> I have flagged this as major because it's not possible to migrate VMs using VXLANs for maintenance, which seems important (it's certainly important to me!).
This is a version of #1508 based against 4.8 …
=> CLOUDSTACK-9362: Skip VXLANs when rewriting the bridge name for migrations (4.8-2)

ui/scripts/metrics.js
Fixes listing of clusters and host to list all clusters/hosts by passing
pagesize=-1.
/cc @koushik-das @swill @DaanHoogland -- fixes the issue raised on dev@ ML by Rashmi
=> CLOUDSTACK-9377: Fix metrics pagesize issue

engine/schema/src/org/apache/cloudstack/acl/dao/RolePermissionsDaoImpl.java, packaging/centos63/cloud.spec, packaging/centos7/cloud.spec, packaging/fedora20/cloud.spec, packaging/fedora21/cloud.spec, scripts/util/migrate-dynamicroles.py
On some MySQL server envs, this may cause a SQL statement error, though
I was unable to reproduce it. Since it's not needed, an order by 'sort_order'
is enough, we can safely remove it.
/cc @swill @anshulgangwar @DaanHoogland and others
=> dynamic-roles: packaging improvements

engine/schema/src/com/cloud/capacity/dao/CapacityDao.java, engine/schema/src/com/cloud/capacity/dao/CapacityDaoImpl.java, server/src/com/cloud/resource/ResourceManagerImpl.java, test/integration/component/maint/test_capacity_host_delete.py
Disable and Remove Host operation disables the primary storage capacity.
Steps to replicate:
Base Condition: There exists a host and storage pool with same id
Steps:
1. Find a host and storage pool having same id
2. Disable the host
3. CPU(1) and MEMORY(0) capacity in op_host_capacity for above host is disabled
4. STORAGE(3) capacity in op_host_capacity for storage pool with id same as above host is also disabled
RCA:
'host_id' column in 'op_host_capacity' table used for storing both storage pool id (for STORAGE capacity) and host id (MEMORY and CPU). While disabling a HOST we also disable the capacity associated with host.
Ideally while disabling capacity we should only disable MEMORY and CPU capacity, but we are not doing so.
Code Path:
ResourceManagerImpl.doDeleteHost() -> …
=> CLOUDSTACK-9366: Capacity of one zone-wide primary storage ignored

engine/components-api/src/com/cloud/storage/StorageManager.java, engine/orchestration/src/org/apache/cloudstack/engine/orchestration/VolumeOrchestrator.java, plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java, server/src/com/cloud/storage/StorageManagerImpl.java, server/src/com/cloud/storage/VolumeApiServiceImpl.java
Disk IO throttling (for KVM) is not applied in the merge of 4.2.
Tests passed:
(1) start vm
(2) attach volume
(3) start vm with volume
(4) migrate vm (with volume)
=> CLOUDSTACK-6928: fix issue disk I/O throttling not applied

systemvm/patches/debian/config/opt/cloud/bin/cs/CsDhcp.py
Rebase of PR #1509 against the 4.7 branch as requested by @swill 
One LGTM from @ustcweizhou carried from previous PR. Previous PR will be closed.
Description from PR #1509:
CLOUDSTACK-6975 refers to service monitoring bringing up dnsmasq but this is no-longer accurate, as service monitoring is not active on the post-4.6 routers. These routers still suffer an essentially identical issue, however, because "dnsmasq needs to be restarted each time configure.py is called in order to avoid lease problems." As such, dnsmasq is still running on backup RvRs, causing the issues described in CLOUDSTACK-6975.
This PR is based on a patch submitted by @ustcweizhou. The code now checks the redundant state of the router before restarting dnsmasq.
RvR networks without this patch have dnsmasq running on …
=> CLOUDSTACK-6975: Prevent dnsmasq from starting on backup redundant RvR

engine/schema/src/com/cloud/host/dao/HostDao.java, engine/schema/src/com/cloud/host/dao/HostDaoImpl.java, server/src/com/cloud/network/ExternalDeviceUsageManagerImpl.java, server/test/com/cloud/network/ExternalLoadBalancerDeviceManagerImplTest.java
external network device usage monitor thread that runs every 5mins by default (based on global config external.network.stats.interval) and runs coalesce query to acquire a lock. When there are no external devices exist, there is no need to run usage collection.
Added test case to verify that usage collection task is not run when there are no External LB or External FW
=> Bug-ID: CLOUDSTACK-8870: Skip external device usage collection if no external devices exist

api/src/org/apache/cloudstack/api/command/user/vm/DeployVMCmd.java, api/src/org/apache/cloudstack/api/command/user/vm/SecurityGroupAction.java, api/src/org/apache/cloudstack/api/command/user/vm/UpdateVMCmd.java, server/src/com/cloud/vm/UserVmManager.java, server/src/com/cloud/vm/UserVmManagerImpl.java
cherry-picked from a exoscale internal fix
Conflicts:
api/src/org/apache/cloudstack/api/command/user/vm/UpdateVMCmd.java
server/src/com/cloud/vm/UserVmManager.java
server/src/com/cloud/vm/UserVmManagerImpl.java
=> CLOUDSTACK-9203 Implement security group move on updateVM API call

server/src/com/cloud/consoleproxy/ConsoleProxyManagerImpl.java, server/test/com/cloud/consoleproxy/ConsoleProxyManagerTest.java, services/secondary-storage/controller/src/org/apache/cloudstack/secondarystorage/SecondaryStorageManagerImpl.java, services/secondary-storage/controller/test/org/apache/cloudstack/secondarystorage/SecondaryStorageManagerTest.java
Two small commits which moves the retrieval of the default network for the console proxy and the SSVM into a separate protected method. It's a small change that makes the code more readable/maintainable and also makes the class more suitable for overriding should one want to do this. It's forward-ported from our 4.2 branch.
No new tests since this should not change any functionality, and thus should be covered by the existing unit tests.
Now on the master branch (#1359 was on the wrong branch).
=> Refactor system VM default network creation

server/src/com/cloud/api/ApiResponseHelper.java, server/src/com/cloud/template/TemplateManagerImpl.java, server/test/com/cloud/template/TemplateManagerImplTest.java
=> [CLOUDSTACK-8973] Fix create template from snapshot returning null in case of region store

server/src/com/cloud/api/ApiServer.java
Fixes JSON deserialization of `cmdInfo` (current process fails with `StringIndexOutOfBoundsException` when `cmdEventType` is the last parameter in the JSON string).
A `StringIndexOutOfBoundsException` is thrown in some cases during event publication.
Example: a stopVirtualMachine API request is executed, and fails with:
```
2016-04-15 09:24:43,080 ERROR [o.a.c.f.m.MessageDispatcher] (catalina-exec-1:ctx-840cbaa7 ctx-8daf0e9c ctx-f63af073) Unexpected exception when calling com.cloud.api.ApiServer.handleAsyncJobPublishEvent
java.lang.reflect.InvocationTargetException
at sun.reflect.GeneratedMethodAccessor307.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at …
```
=> CLOUDSTACK-9358: StringIndexOutOfBoundsException on events

server/src/com/cloud/api/query/dao/DomainJoinDaoImpl.java
The issue happens if volumeTotal is NULL in database.
This is caused by commit 0407fb334f3a79f570217f35636b47076b06d500 for CLOUDSTACK-7847.
=> CLOUDSTACK-9380: fix NPE in listDomains API for a mistake

setup/bindir/cloud-set-guest-sshkey.in
Add `/var/lib/dhcp/*` to the search path for Ubuntu; tested under Ubuntu Precise, Trusty and Xenial.
=> add DHCP lease folders for Ubuntu

build/replace.properties, client/tomcatconf/db.properties.in, engine/storage/snapshot/test/resources/db.properties, framework/db/src/com/cloud/utils/db/TransactionLegacy.java, framework/db/test/db.properties, framework/jobs/test/resources/db.properties, packaging/centos63/replace.properties, packaging/centos7/replace.properties, packaging/centos7/tomcat7/db.properties, packaging/debian/replace.properties, packaging/fedora20/replace.properties, packaging/fedora21/replace.properties, plugins/network-elements/globodns/test/resources/db.properties, plugins/network-elements/juniper-contrail/test/resources/db.properties, server/test/resources/db.properties, services/iam/plugin/test/resources/db.properties, services/iam/server/test/resources/db.properties, tools/devcloud-kvm/pom.xml, tools/devcloud/pom.xml, tools/devcloud4/pom.xml, usage/conf/db.properties.in, usage/test/resources/db.properties, utils/conf/db.properties
Solution to the mailing thread titled "MySQL : No suitable driver found for jdbc:mysql".
It doesn't harm that we explicitely load the MySQL driver, and for those which would use a commons-dbcp version < 1.4 this would fix it as well. Since JDBC 4.0, the JDBC driver can auto-register itself, but for some weird cases (like ours), it's not working. Therefore we need to explicitly load the JDBC driver.
=> Dynamically load drivers before creating our DB connections

systemvm/patches/debian/config/opt/cloud/bin/cs/CsAddress.py
Waiting for interfaces is tricky. They might never appear.. for example when we have entries in `/etc/cloudstack/ips.json` that haven't been plugged yet. Waiting this long makes everything horribly slow (every vm, interface, static route, etc, etc, will hit this wait, for every device). We've seen CloudStack send an `ip_assoc.json` command for `eth1` public nic only and then the router goes crazy waiting for all other interfaces that were there before reboot and aren't there. If only the router would return to the mgt server a success of `eth1`, it would get the command for `eth2` etc etc. Obviously, a destroy works much faster because no state services, so no knowledge of previous devices so no waits :-)
After a stop/start the router has state in `/etc/cloudstack/ips.json` and every …
=> Lower the time we wait for interfaces to appear

test/integration/component/test_blocker_bugs.py
Remove string convertion in Assertion statement, since the start port parameter in listFirewallAPI response is of type integer
Test Result:
=========
"Checking firewall rules deletion after static NAT disable ... === TestName: test_01_firewall_rules_port_fw | Status : SUCCESS ===
ok
Ran 1 test in 153.974s
OK
=> CLOUDSTACK-9388: Remove string conversion in assertion statement

server/src/com/cloud/template/HypervisorTemplateAdapter.java, server/test/com/cloud/template/HypervisorTemplateAdapterTest.java
New version of #1378 for the 4.7b branch instead of 4.6.
=> Emit template UUID and class type over event bus when deleting templates

debian/control
New version of #1412, based on the 4.7 branch.
=> Add lsb-release dependency to mgmt server and agent on Debian/Ubuntu.

systemvm/patches/debian/config/opt/cloud/bin/configure.py, test/integration/component/test_vpn_service.py
This fix starts the IPSEC daemon when enabling client side vpn
=> [CLOUDSTACK-9296] Start ipsec for client VPN

framework/db/src/com/cloud/utils/db/DriverLoader.java, framework/db/src/com/cloud/utils/db/TransactionLegacy.java
I've digged deeper, and found out that Tomcat is really specific in how it loads the JDBC drivers apparently.
If we would be using the standard JDBC connection pooling of Tomcat (tomcat-jdbc) instead of commons-dbcp, we would have the option to specify a "driverClassName" when creating our connection.
This is not the case for commons-dbcp, which we are using within ACS.
If you check an official example of Tomcat : 
https://tomcat.apache.org/tomcat-7.0-doc/jdbc-pool.html#Plain_Ol'_Java 
or
https://tomcat.apache.org/tomcat-7.0-doc/jdbc-pool.html#As_a_Resource
As you can see in the above examples, both of them specify the driverClassName.
In the underlying implementation of Tomcat, Tomcat will do ```Class.forName(driverClassName)``` which will trigger the auto-registration of the Driver. …
=> Make sure that the DB drivers are loaded before creating connections

engine/schema/src/com/cloud/upgrade/dao/Upgrade481to490.java, engine/schema/src/com/cloud/usage/dao/UsageDaoImpl.java
Adds role_id column to cloud_usage.account, fixes UsageDaoImpl to insert
Accounts with role_id from account table. Without the fix, usage server fails to work.
This fixes a *blocker* for 4.9.0 reported by @nvazquez (thanks!)
/cc @swill @nvazquez for review and merge thanks.
=> [BLOCKER][FIX] CLOUDSTACK-9409: Add role_id to cloud_usage.account

server/src/com/cloud/resource/ResourceManagerImpl.java, test/integration/plugins/nuagevsp/nuageTestCase.py, test/integration/plugins/nuagevsp/test_nuage_password_reset.py, test/integration/plugins/nuagevsp/test_nuage_vpc_internal_lb.py, test/integration/plugins/nuagevsp/test_nuage_vpc_network.py, test/integration/plugins/nuagevsp/test_nuage_vsp.py, ui/scripts/system.js
In most network plugins, there's a Resource class which will handle the communication with the actual device / underlaying client / ... They're configured as a host, so ACS is able to send commands towards it. 
When they're configured as a host, the clusterId is not filled in since it's not relevant. Hence, the NPE while deleting this host because of ```long clusterId = host.getClusterId();```
=> CLOUDSTACK-9399 : NPE during deletion of host when clusterId is null

core/src/com/cloud/agent/api/routing/SetNetworkACLCommand.java, core/test/com/cloud/agent/api/routing/SetNetworkACLCommandTest.java
The comparator was inverted.
Issue: https://issues.apache.org/jira/browse/CLOUDSTACK-9404
In this example, I created rules with the port numbers the same as the rule numbers.
Chain ACL_INBOUND_eth2 (1 references)
target     prot opt source               destination
ACCEPT     all  --  anywhere             225.0.0.50
ACCEPT     all  --  anywhere             vrrp.mcast.net
DROP       tcp  --  anywhere             anywhere             tcp dpt:netstat
DROP       tcp  --  anywhere             anywhere             tcp dpt:10
DROP       tcp  --  anywhere             anywhere             tcp dpt:5
DROP       tcp  --  anywhere             anywhere             tcp dpt:3
DROP       tcp  --  anywhere             anywhere             tcp dpt:2
DROP       all  --  anywhere             anywhere
We can …
=> CLOUDSTACK-9404 Fixed ordering of network ACL rules being sent to the VR.

systemvm/patches/debian/config/opt/cloud/bin/configure.py
Bug in code set PFS to the same value (yes/no) as DPD.
file.addeq(" pfs=%s" % CsHelper.bool_to_yn(obj['dpd']))
=> CLOUDSTACK-9342: Site to Site VPN PFS not being set correctly

ui/scripts/storage.js
The resize volume is support on all major hypervisors (Xen, VMware, KVM).
The hypervisor key is returned by the list volumes response only for admins
but not for users or domain admin users. This removes the check, as the operation
is supported on all major hypervisors that CloudStack supports.
With this bug fix all users would see resize volume button in the UI.
/cc @swill
=> ui: show resize volume button to all users

utils/src/main/java/com/cloud/utils/nio/NioConnection.java
This reduced the Nio loop selector wait time, this way the selector will
check frequently (as much as 100ms per iteration) and handle any pending
connection/tasks. This would make reconnections very quick at the expense of
some CPU usage.
/cc @swill @kiwiflyer guys can you please apply this fix in your env and test if you're still able to produce any Nio related error b/w mgmt server(s) and kvm agent(s) not being able to connect quickly. Please also watch out for any increased CPU usage (there should not be any significant change), in which case we may increase the timeout from 100ms to 200-400ms.
=> CLOUDSTACK-9348: Reduce Nio selector wait time

plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java, plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/storage/LibvirtStorageAdaptor.java
We noticed that when an exception occurs within the cleanup loop inside
the deletePhysicalDisk routine that the previously allocated contexts
are not cleaned up.  This seemed to cause an eventual crash of the host
agent after multiple exceptions within the loop.
In addition to ensuring the contexts are always freed we also improved
the logging when exceptions do occur to include the actual return code
from the underlying library in deletePhysicalDisk and deleteSnapshot.
=> Cleanup RBD contexts after exceptions to prevent potential agent crash

debian/cloudstack-management.postinst, packaging/centos63/cloud.spec, packaging/centos7/cloud.spec
This is required afther the upgrade to 4.9.0 and for convience we
add this to the configuration so our users do not have to.
=> packaging: Add db.X.driver=jdbc:mysql to db.properties on upgrade

engine/orchestration/src/com/cloud/vm/VirtualMachineManagerImpl.java, server/src/com/cloud/vm/UserVmManagerImpl.java
JIRA TICKET: https://issues.apache.org/jira/browse/CLOUDSTACK-9407
It was found out that in production environments `vm_network_map` table entries were slowly growing. It was investigated how this entries were cleaned up.
On vm creation, vm mappings are inserted on `vm_network_map`.
On vm stop, mappings are deleted from `vm_network_map` for vm, as a result of the release of its nics.
If created vm is stopped from hypervisor side (at least on vSphere in which we tested it), when CloudStack realizes vm is stopped it doesn't clean up `vm_network_table,` and, as cleanup is made during vm stop, when vm is eventually destroyed and expunged it won't clean up their entries in that table.
We propose to move `vm_network_map` table cleanup to expunge command instead of stop command.
=> CLOUDSTACK-9407: vm_network_map table doesnt get cleaned up properly

engine/schema/src/com/cloud/upgrade/DatabaseUpgradeChecker.java, engine/schema/src/com/cloud/upgrade/dao/Upgrade490to4100.java, server/pom.xml, setup/db/db/schema-490to4100-cleanup.sql, setup/db/db/schema-490to4100.sql
This adds an upgrade to master since the recent 4.9 cut, adds an upgrade path to the new code version 4.10. Without this PR all PRs to master are failing due to missing upgrade path. Please merge this on priority.
Code review and Travis results should be enough to validate the changes.
/cc @karuturi @wido @ProjectMoon @abhinandanprateek
=> [blocker] cloudstack: fix upgrade paths to 4.10.0

debian/changelog
debian build is broken due to the changelog changes in commit 3315eb5. Fixed the same.
To test, do a debian following the instructions at http://docs.cloudstack.apache.org/projects/cloudstack-installation/en/4.8/building_from_source.html#building-deb-packages
cc: @pdion891 @rhtyd Please review.
=> Fix debian build error due to commit 3315eb5

client/WEB-INF/classes/resources/messages.properties, server/src/org/apache/cloudstack/outofbandmanagement/OutOfBandManagementServiceImpl.java, ui/dictionary.jsp, ui/scripts/system.js
- Simplifies change password transactional logic without using pessmistic locks
- Adds a re-enter password field in the UI to valid ipmi/oobm password
=> oobm: simply change password transactional logic

scripts/util/migrate-dynamicroles.py
The old commands.properties format included the full class name such as:
createAccount=com.cloud.api.commands.CreateAccountCmd;1
The migration script did not consider this format and fails. With this fix
the migration script will process both the formats, including processing a
commands.properties file with mixed format, for example:
$ cat commands.properties
createAccount=1
deleteAccount=2
markDefaultZoneForAccount=com.cloud.api.commands.MarkDefaultZoneForAccountCmd;3
$ python scripts/util/migrate-dynamicroles.py -d -f commands.properties
Apache CloudStack Role Permission Migration Tool
(c) Apache CloudStack Authors and the ASF, under the Apache License, Version 2.0
Running this migration tool will remove any default-role permissions from cloud.role_permissions. Do you want to continue? …
=> CLOUDSTACK-9463: Fix dynamic-roles migrate script for old format

packaging/centos63/cloud.spec, packaging/centos7/cloud.spec, plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
The patchviasocket script was rewritten in Python from PR #1533 and made
assumptions that Python 2.7 would be available. In case of CentOS, python 2.7
may not be available or installed. This change ensures that python-argparse
is installed which is used by this script.
/cc @wido @sverrirab @karuturi @jburwell 
=> [blocker] CLOUDSTACK-9452: add python-argparse dependency on el6,7 rpms

engine/schema/src/com/cloud/upgrade/dao/Upgrade410to420.java
In the 4.1.0-4.2.0 db upgrade path, it creates new tables to store secondary
(nfs) storage in image_store table and volumes in volume_store_ref table. In
the upgrade path, it first tries to migrate NFS storage pool where it excludes
storage pools which have been removed, but it migrates all the volumes without
checking if their storage pools have been removed. This causes fk constraint
failure as the volume/row being inserted refers to a storage pool which does
not exist in the image_store table.
The fix migrates all the nfs storage pools to image_store including removed
storage pools and in doing so migrates with the 'removed' field. This fixes
db upgrade for old pre-4.0 and 4.0/4.1 CloudStack clouds.
/cc @jburwell @PaulAngus @karuturi @abhinandanprateek @murali-reddy
=> CLOUDSTACK-9466: Fix fk constraint failure in upgrade path

packaging/centos63/cloud.spec, packaging/centos7/cloud.spec
On fresh installation, the usage server fails to start if the `key` file does
not exist in its classpath. The issue is reproducible in environments (such as Trillian)
where the usage server is installed before cloudstack-setup-databases has been called.
Before the cloudstack db has been setup, the key file does not exist at its
default location and installation of usage-server fails to add a symlink to the
key file.
This fix adds a default symlink to `/etc/cloudstack/management/key` if a
symlink/file does not already exist in the /etc/cloudstack/usage directory.
On new installation, in the post-installation steps it checks if the symlink
or file exists, and adds a symlink if it does not exist. On existing
installations, if symlink or file exists then it will skip adding symlink.
/cc …
=> [lts/blocker] CLOUDSTACK-9467: Add symlink to key file for usage server

test/integration/component/test_acl_listsnapshot.py, test/integration/component/test_acl_listvm.py, test/integration/component/test_acl_listvolume.py
test/integration: fix tearDown order in list_acl_ tests
In several of the list_acl_tests, the tests run for simulator only where
in the (class) setup domains and accounts are created for the test. When the
tests end the (class) teardown methods would delete and remove these resources.
Due to dependence of one of the resources on the other, domain2 on domain1,
domain2 needs to be removed/cleaned up before domain1. Due to this issue,
several Travis test runs have failed in the past such as:
https://travis-ci.org/apache/cloudstack/jobs/152610967
https://travis-ci.org/apache/cloudstack/jobs/152610968
Changing the order of cleanup fixes the tests.
/cc @jburwell @karuturi 
The fix is specific to tests that run 'only' on simulator with Travis. A passing Travis run should be enough to validate …
=> test/integration: fix tearDown order in list_acl_ tests

systemvm/patches/debian/config/opt/cloud/bin/cs/CsAddress.py, test/integration/smoke/test_router_dns.py, tools/marvin/marvin/sshClient.py, tools/marvin/setup.py
CLOUDSTACK-6432: Prevent DNS reflection attacks
DNS on VR should not be publically accessible as it may be prone to DNS
amplification/reflection attacks. This fixes the issue by only allowing VR
DNS (port 53) to be accessible from guest network cidr, as per the fix in:
https://issues.apache.org/jira/browse/CLOUDSTACK-6432
- Only allows guest network cidrs to query VR DNS on port 53.
- Includes marvin smoke test that checks the VR DNS accessibility checks from
guest and non-guest network.
- Fixes Marvin sshClient to avoid using ssh agent when password is provided,
previous some environments may have seen 'No existing session' exception without
this fix.
- Adds a new dnspython dependency that is used to perform dns resolutions in the
tests.
Due to repository commit issues I've created this …
=> [LTS/blocker] CLOUDSTACK-6432: Prevent DNS reflection attacks

utils/src/main/java/com/cloud/utils/ssh/SshHelper.java
JIRA TICKET:
https://issues.apache.org/jira/browse/CLOUDSTACK-9470
In a Vmware environment, running `test_network_acl` we examined why it was failing, it was discovered an issue on `VmwareResource`:
```java
private int findRouterEthDeviceIndex(String domrName, String routerIp, String mac) throws Exception {
VmwareManager mgr = getServiceContext().getStockObject(VmwareManager.CONTEXT_STOCK_NAME);
s_logger.info("findRouterEthDeviceIndex. mac: " + mac);
// TODO : this is a temporary very inefficient solution, will refactor it later
Pair<Boolean, String> result = SshHelper.sshExecute(routerIp, DefaultDomRSshPort, "root", mgr.getSystemVMKeyFile(), null, "ls /proc/sys/net/ipv4/conf");
...
}
```
Command sent to router returned a pair which its first parameter was always true but second parameter …
=> CLOUDSTACK-9470: [BLOCKER] Bug in SshHelper affecting interaction with vRouter in VmwareResource and HypervDirectConnectResource

api/src/com/cloud/vm/VmDetailConstants.java, plugins/hypervisors/vmware/src/com/cloud/hypervisor/vmware/resource/VmwareResource.java, plugins/hypervisors/vmware/test/com/cloud/hypervisor/vmware/resource/VmwareResourceTest.java, test/integration/smoke/test_deploy_vgpu_enabled_vm.py
JIRA TICKET: https://issues.apache.org/jira/browse/CLOUDSTACK-9428
On #1310 passing vRAM size to support 3D GPU problem was addressed on VMware. It was found out that it could be improved to increase performance by reducing extra API calls, as we'll describe later
On WMware, `VmwareResource` manages execution of `StartCommand.` Before sending power on command to ESXi hypervisor, vm is configured by calling `reconfigVMTask` web method on vSphere's client `VimPortType` web service.
It was found out that we were using this method 2 times when passing vRAM size, as it implied creating a new vm config spec only editing video card specs and making an extra call to `reconfigVMTask.`
We propose reducing the extra web service call by adjusting vm's config spec. This way video card gets properly …
=> CLOUDSTACK-9428: Fix for CLOUDSTACK-9211 - Improve performance of 3D GPU support in cloud-plugin-hypervisor-vmware

packaging/build-deb.sh
Please note: No need to wait the results of Jenkins or Travis, this fix only add the missing packages in the docker command line to build CloudStack with Docker (for Ubuntu 14.04 and 16.04)
cc @wido
=> In comment, Add missing packages for Docker Ubuntu builds

server/src/com/cloud/api/doc/ApiXmlDocReader.java
The original TXT diff format is very hard to work with if you are trying to programmatically use the output to generate documentation.  Previously, @pdion891 spent a lot of time trying to manually reformat this output in order for it to be represented in the Release Notes.
This pull request adds JSON as an output format as well as the existing TXT to simplify the ability for parsers and generators to use the output.
This new JSON format was used to generate the 4.9.0 release notes (that code will be contributed separately).
Old manually formatted output: 
http://docs.cloudstack.apache.org/projects/cloudstack-release-notes/en/4.7.0/api-changes.html
New auto-formatted output using this new JSON output: 
http://docs.cloudstack.apache.org/projects/cloudstack-release-notes/en/4.9.0/api-changes. …
=> Added an additional JSON diff output to the ApiXmlDocReader

plugins/hypervisors/vmware/src/com/cloud/hypervisor/vmware/resource/VmwareResource.java, plugins/hypervisors/vmware/test/com/cloud/hypervisor/vmware/resource/VmwareResourceTest.java
JIRA TICKET: https://issues.apache.org/jira/browse/CLOUDSTACK-9386
In some production environments with multiple clusters it was noticed that unused templates were consuming too much storage. It was discovered that template cleanup was not deleting marked templates on ESXi.
Suppose we have multiple clusters `(c1, c2,...,cN)` on a data center and template `T` from which we deploy vms on `c1.`
Suppose now that we expunge those vms, and there's no other vm instance from template `T,` so this was the actual workflow:
1. CloudStack marks template for cleanup after `storage.cleanup.interval` seconds, by setting `marked_for_gc = 1` on `template_spool_ref` table, for that template.
2. After another `storage.cleanup.interval` seconds a `DestroyCommand` will be sent, to delete template from primary …
=> CLOUDSTACK-9386: DS template copies don’t get deleted in VMware ESXi with multiple clusters and zone wide storage

api/src/com/cloud/storage/StoragePool.java, core/src/com/cloud/agent/api/MigrateWithStorageReceiveCommand.java, core/test/org/apache/cloudstack/api/agent/test/BackupSnapshotCommandTest.java, core/test/org/apache/cloudstack/api/agent/test/CheckNetworkAnswerTest.java, core/test/org/apache/cloudstack/api/agent/test/SnapshotCommandTest.java, engine/api/src/org/apache/cloudstack/engine/subsystem/api/storage/PrimaryDataStoreDriver.java, engine/orchestration/src/com/cloud/vm/VirtualMachineManagerImpl.java, engine/schema/src/org/apache/cloudstack/storage/datastore/db/StoragePoolVO.java, plugins/hypervisors/xenserver/src/com/cloud/hypervisor/xenserver/resource/wrapper/xen610/XenServer610MigrateWithStorageReceiveCommandWrapper.java, plugins/hypervisors/xenserver/src/com/cloud/hypervisor/xenserver/resource/wrapper/xenbase/CitrixCreateStoragePoolCommandWrapper.java, plugins/hypervisors/xenserver/src/com/cloud/hypervisor/xenserver/resource/wrapper/xenbase/CitrixDeleteStoragePoolCommandWrapper.java, plugins/hypervisors/xenserver/src/org/apache/cloudstack/storage/motion/XenServerStorageMotionStrategy.java, plugins/hypervisors/xenserver/test/com/cloud/hypervisor/xenserver/resource/wrapper/xenbase/XenServer610WrapperTest.java, plugins/storage/volume/solidfire/src/org/apache/cloudstack/storage/datastore/driver/SolidFirePrimaryDataStoreDriver.java, server/src/com/cloud/server/ManagementServerImpl.java, test/integration/plugins/solidfire/TestAddRemoveHosts.py, test/integration/plugins/solidfire/TestSnapshots.py, test/integration/plugins/solidfire/TestVMMigrationWithStorage.py, test/integration/plugins/solidfire/TestVMSnapshots.py, test/integration/plugins/solidfire/TestVolumes.py, test/integration/plugins/solidfire/util/sf_util.py
This PR adds support for cross-cluster storage migration of VMs that make use of managed storage with XenServer.
Managed storage is when you have a 1:1 mapping between a virtual disk and a volume on a SAN (in the case of XenServer, an SR is placed on this SAN volume and a single virtual disk placed in the SR).
Managed storage allows features such as storage QoS and SAN-side snapshots to work (sort of analogous to VMware VVols).
This PR focuses on enabling VMs that are using managed storage to be migrated across XenServer clusters.
I have successfully run the following tests on this branch:
TestVolumes.py
TestSnapshots.py
TestVMSnapshots.py
TestAddRemoveHosts.py
TestVMMigrationWithStorage.py (which is a new test that is being added with this PR)
=> Adding support for cross-cluster storage migration for managed storage when using XenServer

server/src/com/cloud/configuration/ConfigurationManagerImpl.java
Action events have support for exporting their "first class entities" over the event bus, if it's turned on. This works mostly for BaseAsyncCmds and any synchronous command that operates on already-existing entities. They are populated by the ApiServer and found by ActionEventUtils.
Where it tends to falter is when dealing with synchronous creation commands. This commit makes createZone export the zone UUID over the event bus once the zone has been created.
=> Export UUID for zone creation event completion.

systemvm/patches/debian/config/opt/cloud/bin/configure.py, test/integration/component/test_egress_fw_rules.py
When 'default egress policy' is set to 'allow' in the network offering, any egress rule that is added will 'deny' the traffic overriding the default behaviour.
Conversely, when 'default egress policy' is set to 'deny' in the network offering, any egress rule that is added will 'allow' the traffic overriding the default behaviour.
While this works for 'tcp', 'udp' as expected, for 'icmp' protocol its always set to ALLOW. This patch keeps all protocols behaviour consistent.
Results of running test/integration/component/test_egress_fw_rules.py.  With out the patch test_02_egress_fr2 test was failing. This patch fixes the test_02_egress_fr2  scenario. 
-----------------------------------------------------------------------------------------------------
Test By-default the communication from …
=> CLOUDSTACK-9480,  CLOUDSTACK-9495 fix egress rule incorrect behavior

core/src/org/apache/cloudstack/storage/to/PrimaryDataStoreTO.java, engine/components-api/src/com/cloud/capacity/CapacityManager.java, engine/orchestration/src/org/apache/cloudstack/engine/orchestration/VolumeOrchestrator.java, engine/schema/src/com/cloud/vm/UserVmCloneSettingVO.java, engine/schema/src/com/cloud/vm/dao/UserVmCloneSettingDaoImpl.java, engine/storage/datamotion/src/org/apache/cloudstack/storage/motion/AncientDataMotionStrategy.java, engine/storage/datamotion/test/org/apache/cloudstack/storage/motion/AncientDataMotionStrategyTest.java, plugins/hypervisors/vmware/src/com/cloud/hypervisor/vmware/resource/VmwareResource.java, plugins/hypervisors/vmware/src/com/cloud/storage/resource/VmwareStorageProcessor.java, plugins/hypervisors/vmware/src/com/cloud/storage/resource/VmwareStorageSubsystemCommandHandler.java, plugins/hypervisors/vmware/test/com/cloud/hypervisor/vmware/resource/VmwareResourceTest.java, server/src/com/cloud/capacity/CapacityManagerImpl.java, server/src/com/cloud/vm/UserVmManagerImpl.java
For VMware, It is possible to decide creating VMs as full clones on ESX HV, adjusting `vmware.create.full.clone` global setting. We would like to introduce this property as a primary storage detail, and use its value instead of global setting's value.
We propose introducing `fullCloneFlag` on `PrimaryDataStoreTO` sent on `CopyCommand`. This way we can reconfigure `VmwareStorageProcessor` and `VmwareStorageSubsystemCommandHandler` similar as it was done for `nfsVersion` but refactoring it to be more general.
=> CLOUDSTACK-9422: Granular 'vmware.create.full.clone' as Primary Storage setting

test/integration/smoke/test_deploy_vgpu_enabled_vm.py
JIRA TICKET: https://issues.apache.org/jira/browse/CLOUDSTACK-9505
Cleanup resources after running `test_deploy_vgpu_enabled.py`. Although test passes, resources are left and need to be cleaned up
=> CLOUDSTACK-9505: Fix test_deploy_vgpu_enabled tests cleanup

setup/db/db/schema-490to4910.sql
Adds Ubuntu 16.04 as a supported guest os. This allows users to select
the OS when creating a template etc.
SQL queries tested and adapted from https://issues.apache.org/jira/browse/CLOUDSTACK-9364
=> [4.9/lts] CLOUDSTACK-9364: Add Ubuntu 16.04 as a guest OS

api/src/com/cloud/vm/snapshot/VMSnapshotService.java, api/src/org/apache/cloudstack/api/command/user/vmsnapshot/ListVMSnapshotCmd.java, server/src/com/cloud/api/ApiResponseHelper.java, server/src/com/cloud/vm/snapshot/VMSnapshotManagerImpl.java
- Include missing fields in response: `account`, `domain`, `domainid`, `zoneid`
- Display total count of snapshots, not depending on page size
After creating 2 vm snapshots for a given vm, and making this API call: `command=listVMSnapshot&listAll=true&virtualmachineid=c8531ef8-8502-4b42-b1c5-c52ace0e7801&_=1475516598524&pagesize=1&page=1` we get this response:
```
<listvmsnapshotresponse cloud-stack-version="4.9.1.0-SNAPSHOT">
<count>2</count>
<vmSnapshot>
<id>88f7416a-8799-4245-99c6-c707cfbe6f47</id>
<name>i-2-10482-VM_VS_20161003174340</name>
<state>Ready</state>
<description>2</description>
<displayname>testsnap2</displayname>
<zoneid>0d074f25-ed31-482f-8bc5-44c9314fc417</zoneid>
<virtualmachineid>c8531ef8-8502-4b42-b1c5-c52ace0e7801</virtualmachineid> …
```
=> CLOUDSTACK-9535: [API] listVMSnapshots improvement

tools/marvin/marvin/lib/vcenter.py
These changes have been made to support vmware deployments in CI. 
For CI to create cloudstack setup with vmware, it is required to create datacenter, cluster and hosts in vcenter server before adding in cloudstack. Added few methods in vcenter.py to perform these tasks.
Please refer to CLOUDSTACK-9337 for more details.
=> [CLOUDSTACK-9337]Enhance vcenter.py to create data center in vcenter server automatically

agent/conf/agent.properties, plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java, plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/LibvirtDomainXMLParser.java, plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java, plugins/hypervisors/kvm/test/com/cloud/hypervisor/kvm/resource/LibvirtDomainXMLParserTest.java, plugins/hypervisors/kvm/test/com/cloud/hypervisor/kvm/resource/LibvirtVMDefTest.java
By adding a Random Number Generator device to Instances we can prevent
entropy starvation inside guest.
The default source is /dev/random on the host, but this can be configured
to another source when present, for example a hardware RNG.
When enabled it will add the following to the Instance's XML definition:
<rng model='virtio'>
<backend model='random'>/dev/random</backend>
</rng>
If the Instance has the proper support, which most modern distributions have,
it will have a /dev/hwrng device which it can use for gathering entropy.
=> CLOUDSTACK-9395: Add Virtio RNG device to Instances when configured

server/src/com/cloud/user/AccountManagerImpl.java, server/test/com/cloud/user/AccountManagerImplTest.java, server/test/com/cloud/user/AccountManagerImplVolumeDeleteEventTest.java, server/test/com/cloud/user/AccountManagetImplTestBase.java, server/test/com/cloud/user/MockUsageEventDao.java
New version of #1491.
**Original Description**
New version of #1373, but updated for the 4.7 branch with another fix that allows it to properly find expunged root volumes. This is a bug fix, which is why we target the 4.7 branch.
Original pull request:
Fixes regarding usage event emission.
UsageEventUtils was previously not checking deleted accounts, which meant that if an account was deleted that had some resources running on it, those resources would get destroyed without emitting any events.
Furthermore, the VOLUME_DELETE event of ROOT volumes is the responsibility of the UserVmManager, which gets circumvented when expunging resources following the account deletion. Added a check to the AccountManager which catches the ROOT volumes that need to be deleted and emits events for them.
To …
=> Fixes regarding VOLUME_DELETE events resulting from account deletion

core/src/com/cloud/agent/resource/virtualnetwork/VirtualRoutingResource.java
From the [JIRA issue](https://issues.apache.org/jira/browse/CLOUDSTACK-9319):
> The timeout parameter is not passed down to `applyConfigToVR` inside `VirtualRoutingResource` in all cases.
> 
> This timeout is worked out as 3 seconds per command or 120 seconds (whichever is larger), but because it's not passed to the first invocation, the default (120 seconds, DEFAULT_EXECUTEINVR_TIMEOUT) is used.
> 
> In a recent upgrade of our Virtual Routers, the timeout was being hit and increasing `router.aggregation.command.each.timeout` had no effect. I built a custom 4.8 agent with the timeout increased to allow the upgrade to continue.
=> CLOUDSTACK-9319: Use timeout when applying config to virtual router

plugins/storage/volume/solidfire/src/org/apache/cloudstack/storage/datastore/driver/SolidFirePrimaryDataStoreDriver.java, plugins/storage/volume/solidfire/src/org/apache/cloudstack/storage/datastore/lifecycle/SolidFirePrimaryDataStoreLifeCycle.java, server/src/com/cloud/configuration/ConfigurationManagerImpl.java, server/src/com/cloud/storage/StorageManagerImpl.java, test/integration/plugins/solidfire/TestManagedSystemVMs.py, ui/scripts/configuration.js
This PR makes it easier to spin up system VMs on managed storage.
Managed storage is when you have a dedicated volume on a SAN for a particular virtual disk (making it easier to deliver QoS).
For example, with this PR, you'd likely have a single virtual disk for a system VM. On XenServer, that virtual disk resides by itself in a storage repository (no other virtual disks share this storage repository).
It was possible in the past to spin up system VMs that used managed storage, but this PR facilitates the use case by making changes to the System Service Offering dialog (and by putting in some parameter checks in the management server).
JIRA ticket: https://issues.apache.org/jira/browse/CLOUDSTACK-9504
=> CLOUDSTACK-9504: System VMs on Managed Storage

test/integration/smoke/test_outofbandmanagement.py
Fixes intermittent integration smoke test failures caused in
test_oobm_zchange_password test.
The scope is limited to the integration test only, and full integration test suite is not necessary. We can only consider code reviews and merge on basis of Travis results.
=> CLOUDSTACK-9565: Fix intermittent failure in test_oobm_zchange_password

api/src/org/apache/cloudstack/api/command/admin/config/ListCfgsByCmd.java, api/src/org/apache/cloudstack/api/command/admin/config/UpdateCfgCmd.java, engine/components-api/src/com/cloud/capacity/CapacityManager.java, engine/schema/resources/META-INF/cloudstack/core/spring-engine-schema-core-daos-context.xml, engine/schema/src/org/apache/cloudstack/storage/datastore/db/ImageStoreDaoImpl.java, engine/schema/src/org/apache/cloudstack/storage/datastore/db/ImageStoreDetailVO.java, engine/schema/src/org/apache/cloudstack/storage/datastore/db/ImageStoreDetailsDao.java, engine/schema/src/org/apache/cloudstack/storage/datastore/db/ImageStoreDetailsDaoImpl.java, engine/storage/integration-test/test/resource/fakeDriverTestContext.xml, engine/storage/integration-test/test/resources/storageContext.xml, engine/storage/src/org/apache/cloudstack/storage/image/NfsImageStoreDriverImpl.java, engine/storage/src/org/apache/cloudstack/storage/image/datastore/ImageStoreHelper.java, framework/config/src/org/apache/cloudstack/framework/config/ConfigKey.java, framework/config/src/org/apache/cloudstack/framework/config/impl/ConfigDepotImpl.java, plugins/network-elements/juniper-contrail/test/org/apache/cloudstack/network/contrail/management/IntegrationTestConfiguration.java, server/src/com/cloud/capacity/CapacityManagerImpl.java, server/src/com/cloud/configuration/ConfigurationManagerImpl.java, server/src/com/cloud/server/ManagementServerImpl.java, server/src/com/cloud/storage/ImageStoreDetailsUtil.java, server/test/com/cloud/storage/ImageStoreDetailsUtilTest.java, server/test/org/apache/cloudstack/networkoffering/ChildTestConfiguration.java, setup/db/db/schema-481to490.sql, test/integration/smoke/test_ssvm.py, ui/scripts/system.js
JIRA TICKET: https://issues.apache.org/jira/browse/CLOUDSTACK-9438
From #1361 it was possible to configure NFS version for secondary storage mount. 
However, changing NFS version requires inserting an new detail on `image_store_details` table, with `name = 'nfs.version'` and `value = X` where X is desired NFS version, and then restarting management server for changes to take effect.
Our improvement aims to make NFS version changeable from UI, instead of previously described workflow.
Basically, NFS version is defined as an image store ConfigKey, this implied:
* Adding a new Config scope: **ImageStore**
* Make `ImageStoreDetailsDao` class to extend `ResourceDetailsDaoBase` and `ImageStoreDetailVO` implement `ResourceDetail`
* Insert `'display'` column on `image_store_details` table
* …
=> CLOUDSTACK-9438: Fix for CLOUDSTACK-9252 - Make NFS version changeable in UI

server/src/com/cloud/user/AccountManagerImpl.java, test/integration/component/test_accounts.py
This is to merge Marc's fix on 4.8+ branches.
Tests run:
$ nosetests --with-xunit --xunit-file=test-results.xml --with-marvin --marvin-config=../marvin-cfgs/adv-kvm.cfg  -s -a tags=role --zone=Sandbox-simulator --hypervisor=Simulator  test/integration/component/test_accounts.py
==== Log Folder Path: /tmp//MarvinLogs//Oct_27_2016_22_44_32_GVC833. All logs will be available here ====
=== TestName: test_user_cannot_renew_other_keys | Status : SUCCESS ===
=== TestName: test_user_key_renew_same_account | Status : SUCCESS ===
=== TestName: test_updateAdminDetails | Status : SUCCESS ===
=== TestName: …
=> CLOUDSTACK-9544: Check access on account trying to generate user API keys

ui/scripts/system.js
This allows us to destroy a VR that is in running state from the UI. This action is possible via cloudmonkey/APIs, and would be useful for anyone who wants to simply destroy a VR from the UI without having to stop it first.
As this is a pure UI fix, manual testing would be needed but no regression integration testing is necessary.
/cc @jburwell @karuturi 
Screenshot:
=> CLOUDSTACK-9534: Allow VR to be destroy in UI when in running state

ui/scripts/metrics.js
Use available context to filter a metrics view based on zone, cluster, host
in the context object. This fixes metrics view filtering when metrics view is
viewed via Zone->Compute and Storage-> for a resource.
/cc @jburwell @karuturi -- this is a pure UI fix, one manual test LGTM would be required.
=> CLOUDSTACK-9550: Use context to filter items in a metrics view

engine/orchestration/test/com/cloud/agent/manager/AgentManagerImplTest.java, server/src/com/cloud/storage/listener/StoragePoolMonitor.java, server/test/com/cloud/storage/listener/StoragePoolMonitorTest.java
KVM hosts on shared storage failure was accepted by mgmt server with the
host state as Up, even though there was no primary/shared storage available on
it. This patch offers a quick fix by throwing an exception in the storage monitor
which connects storage pool on host. The failure is trapped by agent manager
that disconnects the agent without any investigation.
Based on Lab tests, KVM agent may take upto 2 minutes to attempt NFS mount when
the storage is inaccessible (firewalled, or shutdown) before returning back with
an error. It is safe to assume that this won't add pressure on mgmt server due to
several reconnection attempts, and KVM agent would retry reconnection every 2
minutes.
For such KVM hosts, where failure happens due to storage issues; they will be
briefly put in Alert state …
=> CLOUDSTACK-9509: Host Connects Without Storage

packaging/centos63/cloud-agent.rc, packaging/debian/cloudstack-agent.init
Move java tmp dir to cloudstack-agent's path to avoid noexec on /tmp
=> CLOUDSTACK-9551: Move java tmp dir to cloudstack-agent's path to avoid

core/src/com/cloud/storage/template/HttpTemplateDownloader.java
New version of #1607, opened against 4.9 so it can be forward merged.
**Original Description**
Previously it was using the HttpClient to make an initial request to an ISO. This would follow redirects. Then it would make another request using built-in Java URL and InputStream, which doesn't follow redirects. This results in the ISO getting stuck at 0% forever and also causing DOS effects.
=> SSVM downloader now handles redirects properly.

scripts/vm/network/security_group.py
Allow DNS queries over TCP when egress filtering is configured.
When using DNSSEC more and more queries are done over TCP and this
requires 53/TCP to be allowed.
Signed-off-by: Wido den Hollander wido@widodh.nl
=> CLOUDSTACK-9552: Allow egress TCP/53 implicitly in Basic Networking

systemvm/patches/debian/config/opt/cloud/bin/cs/CsAddress.py
In some cases the UDP checksums in packets from DHCP servers are
incorrect. This is a problem for some DHCP clients that ignore
packets with bad checksums. This patch inserts an iptables rule
to ensure DHCP servers always send packets with correct checksums.
Due to this bug DHCP offers are sometimes not accepted by Instances.
The end-result without this fix is no connectivity for the Instance
due to the lack of a IPv4 address.
=> CLOUDSTACK-8326: Always fill UDP checksums in DHCP replies in VR

packaging/systemd/cloudstack-agent.service
While forward merging PR #1728, and resolving merge issues a semi-colon was
not added causing cloudstack-agent to fail to start. This fixes the
issue of running agent on centos7.
Since, this is failing testing against centos7/kvm and an urgent merge is necessary. This affects both 4.9 and master branches.
=> systemd: Fix semicolon missing in b75e69

server/src/com/cloud/server/StatsCollector.java
Both host and path could have been NULL which causes the StatsCollector
no to start properly.
By checking if the Strings are not Empty or Null we make sure the StatsCollector
always runs and does not prevent the Management Server from starting.
=> CLOUDSTACK-9071: Properly parse stats.output.uri in StatsCollector

api/src/org/apache/cloudstack/api/response/AlertResponse.java
Updating codes per values present here: https://github.com/apache/cloudstack/blob/4.8/api/src/org/apache/cloudstack/alert/AlertService.java#L39
=> Updating Alert codes

systemvm/patches/debian/config/opt/cloud/bin/cs/CsDhcp.py
The VR executes a ip route flush command as part of configurations. This command performs a
DNS lookup on the VR hostname. Since the VR does not have a DNS entry, the ip command would
wait 5 seconds before timing out and executing the flush operation. This fix adds the VR
hostname to /etc/hosts mapped to 127.0.0.1 to answer the DNS lookup – reducing the
execution time.
=> CLOUDSTACK-9583: VR: In CsDhcp.py preseed both hostaname and localhost to resolve to 127.0.0.1

plugins/hypervisors/vmware/src/com/cloud/hypervisor/vmware/resource/VmwareResource.java
In VmwareResource, findRouterEthDeviceIndex() method find ethernet interface index given
the mac address. This method is used, once a nic is plugged to determine ethernet interface.
"/proc/sys/net/ipv4/conf" from the VR and looped through the devices to find the right
ethernet interface. Howver current logic read it once, and loops through the device list.
Its observerd device may not show up '/proc/sys/net/ipv4/conf' immediatly once NIC is plugged
in the VM from vCenter.
Fix ensured, while waiting for 15 sec in the loop, read the latest content from /proc/sys/net/ipv4/conf
, so that right device list is processed.
Manual tested VPC scenarios of adding new tiers which uses findRouterEthDeviceIndex, to find the guest/public network ethernet index.
=> CLOUDSTACK-9491: incorrect parsing of device list to find ethernet index of plugged NIC

plugins/hypervisors/vmware/src/com/cloud/hypervisor/guru/VMwareGuru.java, plugins/hypervisors/vmware/src/com/cloud/hypervisor/vmware/resource/VmwareResource.java, plugins/hypervisors/vmware/test/com/cloud/hypervisor/guru/VMwareGuruTest.java, plugins/hypervisors/vmware/test/com/cloud/hypervisor/vmware/resource/VmwareResourceTest.java, server/src/com/cloud/configuration/Config.java, test/integration/smoke/test_nested_virtualization.py
[JIRA TICKET](https://issues.apache.org/jira/browse/CLOUDSTACK-9379)
It is desired to support nested virtualization at VM level for VMware hypervisor. Current behaviour supports enabling/desabling global nested virtualization by modifying global config `'vmware.nested.virtualization'`. It is wished to improve this feature, having control at VM level instead of a global control only.
A new global configuration is added, to enable/disable VM nested virtualization control: `'vmware.nested.virtualization.perVM'`. Default value=false
After a vm deployment or start command, vm params include `'nestedVirtualizationFlag'` key and its value is:
- true -> nested virtualization enabled
- false -> nested virtualization disabled
**We will determinate nested virtualization enabled/disabled by examining …
=> CLOUDSTACK-9379: Support nested virtualization at VM level on VMware Hypervisor

systemvm/patches/debian/config/opt/cloud/bin/cs/CsDhcp.py, test/integration/smoke/test_router_dhcphosts.py
when guest VM has nic's in more than one guest network set the tag for each host in /etc/dhcphosts.txt, and use the tag to add exception in /etc/dhcpopts.txt to prevent sending default route, dns server in case if the nic is in non-default network
this was the behaviour with edithosts.sh prior to 4.6
=>  CLOUDSTACK-9598: wrong defaut gateway for the nic in non-default network

engine/schema/src/com/cloud/storage/dao/VolumeDaoImpl.java
While deleting the UserAccount Cleanup for the removed VMs/volumes are not happening. For the removed VMs, snapshots doesn't get cleaned. Only for running VMs(volumes in ready state) the cleanup happens. 
When the VM is desroyed, the volume is marked as destroyed and later storage garbage collector perform the cleanup. But if we try delete domain/account before storage garbage collector runs, then it fails.
=> CLOUDSTACK-9561 After domain/account deletion, snapshot taken by the domain/account remains undeleted

agent/conf/agent.properties, plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java, plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/LibvirtDomainXMLParser.java, plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java, plugins/hypervisors/kvm/test/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java, plugins/hypervisors/kvm/test/com/cloud/hypervisor/kvm/resource/LibvirtDomainXMLParserTest.java, plugins/hypervisors/kvm/test/com/cloud/hypervisor/kvm/resource/LibvirtVMDefTest.java, systemvm/patches/debian/config/etc/init.d/cloud-early-config, tools/appliance/definitions/systemvmtemplate/install_systemvm_packages.sh
This commit adds a additional VirtIO channel with the name
'org.qemu.guest_agent.0' to all Instances.
With the Qemu Guest Agent the Hypervisor gains more control over the Instance if
these tools are present inside the Instance, for example:
- Power control
- Flushing filesystems
- Fetching Network information
In the future this should allow safer snapshots on KVM since we can instruct the
Instance to flush the filesystems prior to snapshotting the disk.
More information: http://wiki.qemu.org/Features/QAPI/GuestAgent
Keep in mind that on Ubuntu AppArmor still needs to be disabled since the default
AppArmor profile doesn't allow libvirt to write into /var/lib/libvirt/qemu
This commit does not add any communication methods through API-calls, it merely
adds the channel to the Instances and …
=> CLOUDSTACK-8715: Add channel to Instances for Qemu Guest Agent

plugins/hypervisors/baremetal/src/com/cloud/baremetal/networkservice/BaremetalPxeManagerImpl.java
There is difference in instance-id metadata across baremetal and other hypervisors.  
On Baremetal
[root@ip-172-17-0-144 ~]# curl http://8.37.203.221/latest/meta-data/instance-id
6021
on Xen
[root@ip-172-17-2-103 ~]# curl http://172.17.0.252/latest/meta-data/instance-id
cbeb517a-e833-4a0c-b1e8-9ed70200fbbf
In both cases it should be vm's uuid.
=> CLOUDSTACK-9566 instance-id metadata for baremetal VM returns ID

ui/scripts/ui-custom/projectSelect.js
[Base 4.9, forward to 4.10 too]
The label Project isn't localized.
Sample with chinese UI:
Current:
With this PR:
cc @rhtyd
=> CLOUDSTACK-9622 Localisation for 'Project' label on the top of Web UI

setup/db/db/schema-490to4910.sql
**JIRA ticket** 
CLOUDSTACK-9624 Incorrect hypervisor mapping of guest os Windows 2008 Server R2 (64-bit) for VMware
**Issue**
Guest OS Windows Server 2008 R2 (64-bit) is being mapped to incorrect guest os at hypervisor, which is winLonghorn64Guest, same as that of Windows Server 2008 (64-bit).
Due to this the VM's guest os type was set to "Other (64-bit)", which would not represent the guest OS accurately on hypervisor.
**Solution**
Fix is to update incorrect guest_os_name field value in DB table cloud.guest_os_hypervisor.
Th query is,
UPDATE IGNORE `cloud`.`guest_os_hypervisor` SET guest_os_name = 'windows7Server64Guest' WHERE guest_os_id IN (SELECT id FROM guest_os WHERE display_name LIKE 'windows%2008%r2%64%') AND hypervisor_type = 'VMware' AND hypervisor_version != 'default';
After …
=> CLOUDSTACK-9624 Incorrect hypervisor mapping of guest os Windows 2008 Server R2 (64-bit) for VMware

test/integration/smoke/test_router_dhcphosts.py
marvin, VirtualMachine object's, nic attribute does not have nic's in any
particualr order in the array. so check isdefault attribute to the get non-default nic
earlier test made assumption that nic[0] is default nic, which is not true always
=> fix marvin test failure test_router_dhcp_opts

tools/travis/before_install.sh
This aims at fixing recent Travis failures.
=> travis: cleanup apt before installing packages

test/integration/smoke/test_privategw_acl.py
ensure VLAN used for createPrivateGateway is determined after the guest
networks in the VPC is created, so that we skip VLAN allocated for guest
network for the private network of vpc gateway
=> CLOUDSTACK-9635: fix test_privategw_acl.py

plugins/hypervisors/vmware/src/com/cloud/hypervisor/vmware/resource/VmwareContextFactory.java, plugins/hypervisors/vmware/src/com/cloud/hypervisor/vmware/resource/VmwareResource.java, plugins/hypervisors/vmware/src/com/cloud/storage/resource/VmwareSecondaryStorageContextFactory.java, plugins/hypervisors/vmware/src/com/cloud/storage/resource/VmwareSecondaryStorageResourceHandler.java, vmware-base/src/com/cloud/hypervisor/vmware/util/VmwareContext.java, vmware-base/src/com/cloud/hypervisor/vmware/util/VmwareContextPool.java, vmware-base/test/com/cloud/hypervisor/vmware/util/VmwareContextPoolTest.java
In a recent management server crash, it was found that the largest contributor
to memory leak was in VmwareContextPool where a registry is held (arraylist)
that grows indefinitely. The list itself is not used anywhere or consumed. There
exists a hashmap (pool) that returns a list of contexts for existing poolkey
(address/username) that is used instead.
This fixes the issue by removing the arraylist registry, and limiting the
length of the context list for a given poolkey.
=> CLOUDSTACK-9564: Fix memory leaks in VmwareContextPool

tools/build/build_asf.sh
This fixes build_asf.sh release script to update checkstyle pom.xml with the
provided new version.
=> CLOUDSTACK-9648: Fix release script to update checkstyle pom

vmware-base/test/com/cloud/hypervisor/vmware/util/VmwareContextPoolTest.java
The test assertion on a pool object may return a null object, as objects
can be randomly expired/tombstoned. This will fix a NPE sometimes seen due
to recently merge for the fix for CLOUDSTACK-9564.
(we can merge this if Travis passes)
/cc @abhinandanprateek @murali-reddy
=> CLOUDSTACK-9564: Fix NPE due to intermittent test assertion

core/src/com/cloud/agent/resource/virtualnetwork/facade/IpAssociationConfigItem.java, core/src/com/cloud/agent/resource/virtualnetwork/model/IpAddress.java, core/test/com/cloud/agent/resource/virtualnetwork/ConfigHelperTest.java, plugins/hypervisors/ovm3/src/test/java/com/cloud/hypervisor/ovm3/resources/Ovm3VirtualRoutingResourceTest.java, systemvm/patches/debian/config/opt/cloud/bin/configure.py, systemvm/patches/debian/config/opt/cloud/bin/cs/CsAddress.py, systemvm/patches/debian/config/opt/cloud/bin/cs/CsRoute.py, systemvm/patches/debian/config/opt/cloud/bin/cs/CsRule.py, systemvm/patches/debian/config/opt/cloud/bin/cs_ip.py, test/integration/component/test_multiple_public_interfaces.py
As pointed out in CLOUDSTACK-9339, in case of multiple public IP's from different public IP ranges are associated with VR, VR functionality is broken from 4.6. Below are the brief list of problems specific to non-VPC networks addressed in the PR. This PR handles both VPC and non-VPC scenarios.
- reverse traffic for the connections accepted on the eth3 and above public interfaces are getting blocked. Need a rule for e.g "-A FORWARD -i  eth3 -o eth0 -m state --state RELATED,ESTABLISHED -j ACCEPT" in the FORWARD chain of filter table to permit reverse path traffic for established connections.
- outbound public traffic from eth0 to eth3 (or for interfaces above like eth4 eth5 etc) needs rule to run through FW_OUTBOUND chain in the filter table
- network stats on public interfaces eth3 are …
=> CLOUDSTACK-9339 Virtual Routers don't handle Multiple Public Interfaces correctly

server/src/com/cloud/storage/ImageStoreUploadMonitorImpl.java
published usage events on successful upload of template or volume.
=> CLOUDSTACK-9646: No usage is generated for uploaded templates/volumes from local

python/lib/cloudutils/serviceConfigServer.py
New version against #1330, opened against master.
```
Moving stop of management in config inside if statement.
It will only run the stop command when --no-start is specified.
```
=> [CLOUDSTACK-9645] Followup fix for #1162: Add support for not (re)starting server after cloud-setup-management.

api/src/org/apache/cloudstack/api/response/TemplateResponse.java, server/src/com/cloud/api/query/dao/TemplateJoinDaoImpl.java
This pull request adds a bits field for template size, and sets it equal to ISO size.
=> [CLOUDSTACK-9644] Adding missing bits field to TemplateResponse

engine/storage/image/src/org/apache/cloudstack/storage/image/TemplateServiceImpl.java, services/secondary-storage/server/src/org/apache/cloudstack/storage/resource/NfsSecondaryStorageResource.java
When using a region store like Swift or S3 as secondary storage,
the `zoneId` can be null. This causes an exception when we try
to convert it to a `long`. This fix guards against that.
Before this fix, if you restart the management server, all the templates
would change to "NOT READY" because the code which syncs the NFS cache
and the object store crashes due to the above mentioned issue.
This PR fixes that.
=> CLOUDSTACK-9627 Fix template sync for region store.

systemvm/patches/debian/config/opt/cloud/bin/cs_ip.py
As part of the bug 'CLOUDSTACK-9339 Virtual Routers don't handle Multiple Public Interfaces correctly'
issue of mismatch of traffic type represented by 'nw_type' in config sent by management server in
ip_associations.json and how it is persisted in the ips.json data bag are differnet,
is addressed, however missed the change in final merge.
this bug is to add the functionality in cs_ip.py, to lower the traffic type sent by management server before persisting in the ips.json databag
=> CLOUDSTACK-9659: mismatch in traffic type in ip_associations.json and ips.json

test/integration/component/test_volumes.py
The component/test_volume failures happen when disk offering is random selected to be a custom one. This fixes that.
=> CLOUDSTACK-9584: Fix intermittent test failure in `test_volumes`

ui/scripts/ui-custom/zoneWizard.js
Create an Advanced zone(VMware).
Configure physical network.
Edit traffic type (Management or Storage)
Observe the switch type dropdown list is missing.
If we choose Guest or Public the dropdown is visible. See the below snapshots.
The list should be shown in case of Management and storage.
The list is missing in case of management and storage.
Showing vswitchtype for all traffic types in case of VMware.
=> CLOUDSTACK-9269: Missing field for Switch type for Management and Storage traffic types

engine/schema/src/com/cloud/usage/dao/UsageDaoImpl.java
https://issues.apache.org/jira/browse/CLOUDSTACK-9656
This is a workaround to avoid NPE when using the usage server with Projects
To reproduce bug:
Create project
Add account to project
Create VM within that project
Run the usage server
Same steps to test resolution
=> CLOUDSTACK-9656 Preventing autoboxing NPE in Usage by setting a default role when not found

server/src/com/cloud/api/query/QueryManagerImpl.java, test/integration/component/test_escalation_listTemplateDomainAdmin.py
API "list templates templatefilter=all" reveals all templates.
Using a "list templates templatefilter=all" API call any domain admin can see all templates of all domains in ACS. Information returned includes the account and domain of the template's owner.
The template data shows what that VM is using and any hints from the label. This would give an advantage in what attack vectors to use. The account and domain can possibly be used in brute force attack to guess the password and login information.
Test Scenario:
created two accounts in different domain.
```
mysql> select account_id,username,api_key from user where id in (4,5);
+------------+-----------+----------------------------------------------------------------------------------------+
| account_id | username  | api_key …
```
=> CLOUDSTACK-9594: API "list templates templatefilter=all" reveals all

tools/build/build_asf.sh, tools/build/setnextversion.sh, tools/docker/Dockerfile, tools/docker/Dockerfile.centos6, tools/docker/Dockerfile.marvin, tools/docker/README.md
CLOUDSTACK-9651
Fix Docker images build for 4.10.0.0:
- simulator
- marvin
- management_centos6
Squashed version of #1435.
=> Fix docker image build for cloudstack-management

server/src/com/cloud/vm/UserVmManagerImpl.java
ISSUE
============
Instance fails to start after unsuccesful compute offering upgrade.
TROUBLESHOOTING
We observed VM instance get compute values "cpuNumber","cpuSpeed","memory" removed from table "user_vm_details", which cause instance fail to startup next time on XenServer
`mysql> select * from user_vm_details where vm_id=10;
--------------------------------------------------------------------------------------------------
id 	vm_id 	name 	value 	display
--------------------------------------------------------------------------------------------------
218 	10 	platform 	viridian:true;acpi:1;apic:true;pae:true;nx:true 	1
219 	10 	hypervisortoolsversion 	xenserver56 	1
220 	10 	Message.ReservedCapacityFreed.Flag 	true 	1 …
=> CLOUDSTACK-9626: Instance fails to start after unsuccesful compute

setup/db/db/schema-481to490.sql, setup/db/db/schema-4910to41000.sql
- Fixes issue of failing upgrade paths
- Moves schema changes from PR #1615 in the 4.9.1.0 to 4.10.0.0 sql path
=> CLOUDSTACK-9671: Fix sql change to corresponding version paths

plugins/hypervisors/xenserver/src/com/cloud/hypervisor/xenserver/discoverer/XcpServerDiscoverer.java, plugins/hypervisors/xenserver/src/com/cloud/hypervisor/xenserver/resource/CitrixHelper.java, scripts/vm/hypervisor/xenserver/cloudstack_pluginlib.py, scripts/vm/hypervisor/xenserver/setup_heartbeat_sr.sh, setup/db/db/schema-490to4910.sql, setup/db/db/schema-4910to4920.sql, tools/marvin/marvin/lib/utils.py, ui/scripts/system.js
This PR adds support for XenServer 7. I have manually done the following tests
- Create a new cluster with XenServer7
- Add Primary storage: Should create an SR on XS7
- Add another XS7 host to the Pool 
- Add host2 to Cloudstack
- Create VM1 from template 
- Create VM2 from template 
- Ping/SSH VM1 to VM2 and vice-versa
- Stop/Delete/Expunge VM2
- Create Data disk 
- Attach it to VM1
- Create VM snaphsot of VM1
- Restore VM snapshot of VM1
- Delete VM snapshot of VM1
- Create Volume snapshot of Datadisk
- Create volume snapshot of Root disk
- Create new template from snapshot of root disk
- Create volume from snapshot of datadisk
- Detach datadisk volume
- Delete datadisk volume
- Aquire a public IP
- Create a static nat to VM1
- Live migrate VM1 while traffic on VM
- Delete VM1
=> XenServer 7 Support

systemvm/patches/debian/config/opt/cloud/bin/configure.py
When ingress rule is applied without ports (port start and port end params are not passed) then API/UI is showing rule got applied but in the VR, iptables rule not got applied.
Fixed this issue in the VR script.
=> CLOUDSTACK-9615: Fixd applying ingress rules without ports

engine/schema/src/com/cloud/configuration/dao/ResourceCountDaoImpl.java
Fetch the number of resourceCount by domain and account excluding the removed ones.
=> CLOUDSTACK-9597: Should not fetch resource count for removed entity

server/src/com/cloud/configuration/ConfigurationManagerImpl.java
Description:
=========
Create shared network fails with Error.
While creating a shared network it fails to create with Error "The new IP range you have specified has overlapped with the guest network in the zone: XYZ. Please specify a different gateway/netmask"
1. Create an isolated network with a subnet eg: 10.1.1.0/24
2. Create a shared network with the same subnet but different VLAN, we should observe this issue.
It shouldn't restrict the creation of the guest network with the same subnet as long as they are segmented by VLAN.
ACTUAL BEHAVIOR:
It doesn't allow the creation of shared guest networks if there is any isolated guest network using the same subnet although it allows using the same subnet …
=> CLOUDSTACK-9639: Unable to create shared network with vLan isolation

plugins/hypervisors/vmware/src/com/cloud/hypervisor/vmware/resource/VmwareResource.java, vmware-base/src/com/cloud/hypervisor/vmware/mo/HostMO.java, vmware-base/src/com/cloud/hypervisor/vmware/mo/HypervisorHostHelper.java
Jira
===
CLOUDSTACK-9673 : Exception occured while creating the CPVM in VMware setup over standard vSwitches
Issue
====
Exception occured while creating the CPVM in the VmWare Setup using standard vswitches.
```
StartCommand failed due to Exception: com.vmware.vim25.AlreadyExists
message: [] com.vmware.vim25.AlreadyExistsFaultMsg: The specified key, name, or identifier already exists
```
Fix
===
Ensure synchronization while attempting to create port group such that simultaneous attempts are not made with same port group name on same ESXi host.
Testing
======
Successfully ran manual tests (deploy user instance) on top of latest master commit `17653a86fad67447a4f13e455e336694ad5c1735`.This code change is involved in virtual network creation over VMware standard vSwitches. Existing …
=> CLOUDSTACK-9673 : Exception occured while creating the CPVM in VMware setup over standard vSwitches

plugins/network-elements/nuage-vsp/pom.xml, test/integration/plugins/nuagevsp/nuageTestCase.py, test/integration/plugins/nuagevsp/test_nuage_internal_dns.py, test/integration/plugins/nuagevsp/test_nuage_static_nat.py
CloudStack root pom change to use Amazon WS 11.1.16
caused our client to fail, as it was depending on classes,
which are not not present anymore.
Latest client version uses Gson instead.
BUG-ID: CLOUDSTACK-9729
Bugfix-for: master
=> CLOUDSTACK-9729: Use latest Nuage client.

engine/storage/datamotion/src/org/apache/cloudstack/storage/motion/StorageSystemDataMotionStrategy.java, engine/storage/snapshot/src/org/apache/cloudstack/storage/snapshot/StorageSystemSnapshotStrategy.java, engine/storage/volume/src/org/apache/cloudstack/storage/volume/VolumeServiceImpl.java, plugins/hypervisors/xenserver/src/com/cloud/hypervisor/xenserver/resource/Xenserver625StorageProcessor.java, plugins/storage/volume/solidfire/src/org/apache/cloudstack/storage/datastore/util/SolidFireUtil.java, test/integration/plugins/solidfire/TestManagedSystemVMs.py, test/integration/plugins/solidfire/TestVMMigrationWithStorage.py, test/integration/plugins/solidfire/TestVMSnapshots.py, test/integration/plugins/solidfire/util/sf_util.py
This PR is to address a few issues in #1600 (which was recently merged to master for 4.10).
In StorageSystemDataMotionStrategy.performCopyOfVdi we call getSnapshotDetails. In one such scenario, the source snapshot in question is coming from secondary storage (when we are creating a new volume on managed storage from a snapshot of ours that’s on secondary storage).
This usually “worked” in the regression tests due to a bit of "luck": We retrieve the ID of the snapshot (which is on secondary storage) and then try to pull out its StorageVO object (which is for primary storage). If you happen to have a primary storage that matches the ID (which is the ID of a secondary storage), then getSnapshotDetails populates its Map<String, String> with inapplicable data (that is later ignored) and you …
=> CLOUDSTACK-9619: Updates for SAN-assisted snapshots

README.md
While reading the README file of Apache CloudStack repository on Github I noticed that we have a section called “News and Events”. This section was pointing to a website for conferences, which was not updated in years. I changed the link to send the users to http://cloudstackcollab.org/ hot site.
Moreover, I removed the reference for http://planet.apache.org/cloudstack; this system was shut down and is no longer available (http://markmail.org/message/wcdqncr6vr4lk6a7?q=planet%2Eapache%2Eorg#query:planet.apache.org+page:1+mid:6g76gvitxhlyee4n+state:results).
=> Change the README link for event page to the current ACS CCCs website

tools/docker/Dockerfile
Fix current broken build introduce with JDK upgrade from #1888 of docker simulator because of missing dependencies and JDK8. This PR upgrade the distro to Ubuntu 16.04 and use default jdk version 8.
I've quickly test the build locally, no error in the UI and logs.
=> Dockerfile: Upgrade base distro to Ubuntu 16.04, fix support for JDK8

systemvm/patches/debian/config/opt/cloud/bin/cs/CsAddress.py
The password server in RVRs has wrong parameters as the gateway of guest nics is None.
In this case, we should get the gateway from /var/cache/cloud/cmdline.
This issue is caused by commit 45642b83821ce0ecd6d4cddb76a77a2481e54d9a
=> [4.9] CLOUDSTACK-9692: Fix password server issue in redundant VRs

systemvm/patches/debian/config/opt/cloud/bin/configure.py
Way to reproduce the issue
(1) enable remote access vpn
root@r-8349-VM:~# cat /etc/ipsec.d/ipsec.any.secrets
: PSK "mVSx5KDXCPYX7X5DGb2W8yNW"
(2) disable/enable vpn
root@r-8349-VM:~# cat /etc/ipsec.d/ipsec.any.secrets
: PSK "mVSx5KDXCPYX7X5DGb2W8yNW"
: PSK "HeV3dHZpZXt4chhfvhx8D83C"
Expected configuration:
root@r-8349-VM:~# cat /etc/ipsec.d/ipsec.any.secrets
: PSK "HeV3dHZpZXt4chhfvhx8D83C"
=> [4.9] CLOUDSTACK-9712: FIX issue on preshared key if we disable/enable remote access vpn

server/src/com/cloud/user/DomainManagerImpl.java
Handled the '%' case by replacing that with a literal character rather than a wildcard character.
=> CLOUDSTACK-8805: Domains become inactive automatically.

api/src/org/apache/cloudstack/api/ApiConstants.java, api/src/org/apache/cloudstack/api/BaseUpdateTemplateOrIsoCmd.java, api/src/org/apache/cloudstack/api/command/user/vm/UpdateVMCmd.java, engine/schema/src/com/cloud/storage/VMTemplateDetailVO.java, engine/schema/src/com/cloud/vm/UserVmDetailVO.java, server/src/com/cloud/api/query/dao/UserVmJoinDaoImpl.java, server/src/com/cloud/template/TemplateManagerImpl.java, server/src/com/cloud/vm/UserVmManagerImpl.java, server/test/com/cloud/template/TemplateManagerImplTest.java, ui/scripts/instances.js, ui/scripts/templates.js, ui/scripts/ui-custom/granularSettings.js
JIRA TICKET: https://issues.apache.org/jira/browse/CLOUDSTACK-9457
This PR proposes list/add/update/delete user vm and vm template details via API and UI.
Setting tab is added on Instances page. Actions allowed are: Add/Edit/Remove
Settings tab is only shown if instance is Stopped:
Setting tab is added on Templates page. Actions allowed are: Add/Edit/Remove:
=> CLOUDSTACK-9457: Allow retrieval and modification of VM and template details via API and UI

api/src/com/cloud/vm/UserVmService.java, api/src/com/cloud/vm/snapshot/VMSnapshotService.java, engine/api/src/com/cloud/vm/VirtualMachineManager.java, engine/api/src/org/apache/cloudstack/engine/cloud/entity/api/VirtualMachineEntity.java, engine/api/src/org/apache/cloudstack/engine/subsystem/api/storage/VMSnapshotStrategy.java, engine/orchestration/src/com/cloud/vm/VirtualMachineManagerImpl.java, engine/orchestration/src/org/apache/cloudstack/engine/cloud/entity/api/VMEntityManager.java, engine/orchestration/src/org/apache/cloudstack/engine/cloud/entity/api/VMEntityManagerImpl.java, engine/orchestration/src/org/apache/cloudstack/engine/cloud/entity/api/VirtualMachineEntityImpl.java, engine/storage/snapshot/src/org/apache/cloudstack/storage/vmsnapshot/DefaultVMSnapshotStrategy.java, plugins/hypervisors/vmware/src/com/cloud/storage/resource/VmwareStorageProcessor.java, server/src/com/cloud/ha/HighAvailabilityManagerImpl.java, server/src/com/cloud/network/as/AutoScaleManagerImpl.java, server/src/com/cloud/resource/ResourceManagerImpl.java, server/src/com/cloud/user/AccountManagerImpl.java, server/src/com/cloud/vm/UserVmManagerImpl.java, server/src/com/cloud/vm/snapshot/VMSnapshotManagerImpl.java, server/test/com/cloud/user/AccountManagerImplVolumeDeleteEventTest.java
It was noticed that expunging instances with many vm snapshots took a look of time, as hypervisor received as many tasks as vm snapshots instance had, apart from the delete vm task. We propose a way to optimize this process for instances with vm snapshots by sending only one delete task to hypervisor, which will delete vm and its snapshots
1. deleteVMsnapohsot-> no changes to current behavior
2. destroyVM with expunge=false ->  no actions to VMsnaphsot is performed at the moment. When VM cleanup thread is executed it will perform the same sequence as (3). If instance is recovered before expunged by the cleanup thread it will remain intact with VMSnapshot chain present
3. destroyVM with expunge=true:
* Vmsnaphsot is marked with removed timestamp and state = Expunging in DB
* VM is deleted …
=> CLOUDSTACK-9738: [Vmware] Optimize vm expunge process for instances with vm snapshots

systemvm/patches/debian/config/opt/cloud/bin/cs/CsAddress.py
In network VR, the routes to current subnets are missing in corresponding ip route Table.
It is a typo in commit 6749785caba78a9379e94bf3aaf0c1fbc44c5445
In VPC VR, it works fine.
=> [4.9] CLOUDSTACK-9770: fix missing ip routes in VR

server/src/com/cloud/template/TemplateAdapterBase.java
Any string is allowed as hypervisor type from the api.
HypervisorType.getType() tries to validates with the enums and if nothing
matches sets the type as None.
Added a check to not allow None hypervisor type when registering.
will update test results and testing done later.
=> CLOUDSTACK-8950 Hypervisor Parameter check is not performed for registerTemplate and getUploadParamsForTemplate API's

client/tomcatconf/classpath.conf.in
Now that PR-1888 is merged, Java8 is required.  Unfortunately, the file pushed to `/etc/cloudstack/management/classpath.conf` on ACS install will default the version to Java7 instead of Java8 if JAVA_HOME is unset.  This fix sets the default to Java8 if JAVA_HOME is not set.
=> CLOUDSTACK-9780: Fixed the default JAVA_HOME value to be Java8 if not set

server/src/com/cloud/storage/StorageManagerImpl.java
This issue occurs when a volume in Ready state is moved across storage
pools.
While finding if the storage pool has enough space, it has a check to
consider the size of non Ready volumes only. This is true if the volume
to be attached to a vm is in the same storage pool. But, if the volume
is in another storage pool and has to be moved to a vm's storage pool,
the size of the volume should be considered in doing the space check.
computing the asking size when volume is not in ready state or when the 
volume is on a different storage pool.
Testing:
I couldnt write unittests for it. This class is not in a unittestable state.
manually tested in the below environment
1. xenserver 6.5 setup with 2 clusters and a host each in each of them.
2. added storage tags for the primary storage.
3. …
=> CLOUDSTACK-8896: allocated percentage of storage pool going beyond 100%

server/src/com/cloud/network/vpn/Site2SiteVpnManagerImpl.java, systemvm/patches/debian/config/etc/logrotate.conf, systemvm/patches/debian/config/opt/cloud/bin/checks2svpn.sh, systemvm/patches/debian/config/opt/cloud/bin/configure.py, systemvm/patches/debian/config/opt/cloud/bin/cs_ip.py, systemvm/patches/debian/vpn/etc/ipsec.conf, systemvm/patches/debian/vpn/etc/ipsec.d/l2tp.conf, systemvm/patches/debian/vpn/etc/ipsec.secrets, test/integration/component/maint/test_vpc.py, test/integration/component/test_vpc.py, tools/appliance/definitions/systemvmtemplate/configure_systemvm_services.sh, tools/appliance/definitions/systemvmtemplate/install_systemvm_packages.sh, ui/scripts/network.js, utils/src/main/java/com/cloud/utils/net/NetUtils.java, utils/src/test/java/com/cloud/utils/net/NetUtilsTest.java
This PR is a merge of @jayapalu changes in #872 and the changes I had to make to get the functionality working.
I have done pretty extensive testing of this code so far and we are looking to be in pretty good shape.  One thing to note is that a `Diffie-Hellman` group **is required** in order for this feature to work correctly.  It is not highlighted in the tests below, but I have shown that the `PFS` is not required for this feature to work.  In #872 I have shown a more exhaustive set of tests of this code, but I have limited this set of tests to a recommended `IKE` and `ESP` configuration in order to reduce the noise and test the other areas of functionality.
**Test Results**
I am testing this functionality by creating two VPCs with VMs in each and creating a S2S VPN connection between …
=> Updated StrongSwan VPN Implementation

ui/scripts/templates.js
added extra warning message if it's a cross-zone template ("This is a
cross zone template and will be deleted from all the zones. Are you sure
you want to proceed?").
=> CLOUDSTACK-9655 The template which is registered in all zones will be deleted by deleting 1 template on any zone

api/src/org/apache/cloudstack/api/response/ImageStoreResponse.java, engine/schema/resources/META-INF/cloudstack/core/spring-engine-schema-core-daos-context.xml, engine/schema/src/com/cloud/storage/StoragePoolTagVO.java, engine/schema/src/com/cloud/storage/dao/StoragePoolTagsDao.java, engine/schema/src/com/cloud/storage/dao/StoragePoolTagsDaoImpl.java, server/src/com/cloud/api/query/dao/ImageStoreJoinDaoImpl.java, server/src/com/cloud/api/query/vo/ImageStoreJoinVO.java, server/src/com/cloud/storage/StorageManagerImpl.java, setup/db/db/schema-4920to41000.sql, ui/scripts/system.js
Primary storage tags are being saved as an entry on `storage_pool_details` with:
* name = TAG_NAME
* value = "true"
When a boolean property is defined in {{storage_pool_details}} and has value = "true", it is displayed as a tag.
Redesign `Storage Tags` for Primary Storage view, to list only tags, as it is done in Host Tags (Hosts view).
In Secondary Storage view we propose removing `Details` field, as `Setting` tab list details for a given image store. We also remove details from response on `listImageStores` API method
=> CLOUDSTACK-9574: Redesign storage views

api/src/com/cloud/vm/snapshot/VMSnapshot.java, engine/schema/src/com/cloud/vm/snapshot/VMSnapshotVO.java, server/src/com/cloud/vm/UserVmManagerImpl.java, server/src/com/cloud/vm/snapshot/VMSnapshotManagerImpl.java, server/test/com/cloud/vm/snapshot/VMSnapshotManagerTest.java, setup/db/db/schema-4920to41000.sql, test/integration/smoke/test_vm_snapshots.py
CloudStack doesn't support changing service offering for vm instances which have vm snapshots, they should be removed before changing service offering.
Extend actual behaviour by supporting changing service offering for vms which have vm snapshots. In that case, previously taken snapshots (if reverted) should use previous service offering, future snapshots should use the newest.
1. Adding `service_offering_id` column on `vm_snapshots` table: This way snapshot can be reverted to original state even though service offering can be changed for vm instance.
NOTE: Existing vm snapshots are populated on update script by:
`UPDATE vm_snapshots s JOIN vm_instance v ON v.id = s.vm_id SET s.service_offering_id = v.service_offering_id;`
2. New vm snapshots will use instance vm service offering id as …
=> CLOUDSTACK-9539: Support changing Service offering for instance with VM Snapshots

plugins/hypervisors/vmware/src/com/cloud/storage/resource/VmwareStorageProcessor.java
This optimization aims to reduce volume attach slowness due to vmdk files search on datastore before creating the volume (search for `.vmdk`, `-flat.vmdk` and `-delta.vmdk` files to delete them if they exist). This search is not necessary when attaching a volume in Allocated state, due to volume files don't exist on datastore.
On large datastores, this search can cause volume attachness to be really slow, as we can see in this log lines:
````
13-mgmt.log:2016-11-02 10:16:33,136 INFO  [vmware.mo.DatastoreMO] (DirectAgent-931:ctx-5687d68e uscrlpdcsesx240.ads.autodesk.com, job-8675314/job-8675315, cmd: CreateObjectCommand) Searching file 9ce7731fd38b4045afbb7ce9754abbc1.vmdk in [b5ebda046d613e079b5874b169cd848f]
13-mgmt.log:2016-11-02 10:19:42,567 WARN …
```
=> CLOUDSTACK-9752: [Vmware] Optimization of volume attachness to vm

server/src/com/cloud/configuration/ConfigurationManagerImpl.java
This PR fixes the creation of a basic zone.
https://issues.apache.org/jira/browse/CLOUDSTACK-9790
=> CLOUDSTACK-9790: fix NPE in case of Basic zone.

server/src/com/cloud/api/ApiResponseHelper.java, test/integration/smoke/test_snapshots.py
@mike-tutkowski After support for snapshots on solidifire there are many places which are prone to these NullPointer exceptions resulting in various issues. Root cause for these issues is that we get the primary storage associated with snapshot and then figure out how to handle but if that store is deleted then it results in NullPointer exceptions. Without solidfire we don't need to access primary storage.
Should we handle that as issues are found or could there be other way to fix all of these issues?
=> CLOUDSTACK-9691: Fixed unhandeled excetion in list snapshot command when a primary store is deleted related to it

plugins/network-elements/netscaler/src/com/cloud/network/element/NetscalerElement.java
If we create an isolated network with NetScaler published service offering for Load balancing service, then the load balancing configuration UI does not show "Source" as one of the supported LB methods in the drop down list. It only shows "Round-Robin" and "LeastConnection" methods in the list. However, It successfully creates LB rule with "Source" as the LB method using API.
=> CLOUDSTACK-9618: Load Balancer configuration page does not have "Source" method in the drop down list.

api/src/com/cloud/network/vpn/RemoteAccessVpnService.java, api/src/org/apache/cloudstack/api/command/user/vpn/AddVpnUserCmd.java, api/src/org/apache/cloudstack/api/command/user/vpn/RemoveVpnUserCmd.java, server/src/com/cloud/network/vpn/RemoteAccessVpnManagerImpl.java
If configuring vpn user in one of the network fails the failure is ignored, failure should be shown in API response.
=> CLOUDSTACK-9711: Fixed error reporting while adding vpn user

api/src/org/apache/cloudstack/api/ApiConstants.java, api/src/org/apache/cloudstack/api/response/LoginCmdResponse.java, server/src/com/cloud/api/ApiServer.java, ui/scripts/cloudStack.js
Time displayed for events in UI is incorrect. Let's say, when we login using Japanese language the time displayed in the events is GMT instead of JST. However with English language the time is JST, as expected.
Example: 
Time is displayed in the event is 10:40, if you are logged in using English language. 
Whereas, time in the event shows 19:40 If you login with Japanese language.
=> CLOUDSTACK-9768: Time displayed for events in UI is incorrect

services/secondary-storage/server/src/org/apache/cloudstack/storage/resource/NfsSecondaryStorageResource.java
Cloudstack incorrectly uses the physical size as the size of the
template. Ideally, the size should refelct the virtual size. This
PR fixes that issue.
=> CLOUDSTACK-9628: Fix Template Size in Swift as Secondary Storage

server/src/com/cloud/api/query/dao/AccountJoinDaoImpl.java
listProjects doesn't return tags vmstopped or vmrunning when their value is zero
added the the appropriate tags to response.
tested this manually by creating projects, launching vms from project accounts and then listing the projects.
=> CLOUDSTACK-8857 listProjects doesn't return tags vmstopped or vmrunning when their value is zero

engine/orchestration/src/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
Without this information a NPE might be triggered when starting a VR, SSVM or CP
as this information is read from the 'nics' table and causes a NPE.
During deployment we should set the IPv6 Gateway and CIDR for the NIC object so that
it is persisted to the database.
=> ipv6: Set IPv6 CIDR and Gateway in 'nic' profile

systemvm/patches/debian/config/etc/init.d/cloud-early-config
moved logrotate from cron.daily to cron.hourly for vpcrouter in cloud-early-config.  This brings 'vpcrouter' inline with 'router'.  We are having issues with cloud.log not rotating fast enough, which filled up /var/log and ultimately caused the VR to stop functioning in such a way that it prevented new VMs from being deployed.
=> CLOUDSTACK-9795: moved logrotate from cron.daily to cron.hourly for vpcrouter

systemvm/patches/debian/config/opt/cloud/bin/cs/CsAddress.py
This change removes the conversion from IPNetwork to list in one of the router scripts. This makes the router faster at processing static NAT rules, which can prevent timeouts when attaching or detaching IPs.
With the `list` conversion, it has to potentially check a list of 65536 IP strings multiple times. We assume that the comparison implemented in the IPNetwork is far more efficient. We have seen speed-up from 218 seconds to enable static NAT with 18 IPs on the router to 2 or 3 seconds by removing this cast. This also fixes a potential bug where adding IPs to a router time out because the scripts are taking too long. 218 seconds, for example, is beyond the timeout on the KVM agent for script execution, and then all enableStaticNat operations will fail.
=> [CLOUDSTACK-9793] Faster IP in subnet check

systemvm/patches/debian/config/etc/logrotate.d/apache2, systemvm/patches/debian/config/etc/logrotate.d/cloud, systemvm/patches/debian/config/etc/logrotate.d/conntrackd, systemvm/patches/debian/config/etc/logrotate.d/dnsmasq, systemvm/patches/debian/config/etc/logrotate.d/haproxy, systemvm/patches/debian/config/etc/logrotate.d/ppp, systemvm/patches/debian/config/etc/logrotate.d/rsyslog
* rotate both daily and by size by using maxsize in stead of size
* decrease the max size to 10M for rsyslog files
* remove delaycompress for rsyslog files
* increase rotate to 10 for cloud.log
=> CLOUDSTACK-9746 system-vm: logrotate config causes critical failures

plugins/hypervisors/xenserver/src/com/cloud/hypervisor/xenserver/resource/CitrixResourceBase.java
Here is the longer description of the problem:
By default XenServer limits HVM guests to only 4 disks. Two of those are reserved for the ROOT disk (deviceId=0) and CD ROM (device ID=3) which means that we can only attach 2 data disks. This limit however is removed when Xentools is installed on the guest. The information that a guest has Xentools installed and can handle more than 4 disks is stored in the VM metadata on XenServer. When a VM is shut down, Cloudstack removes the VM and all the metadata associated with the VM from XenServer. Now, when you start the VM again, even if it has Xentools installed, it will default to only 4 attachable disks.
Now this problem manifests itself when you have a HVM VM and you stop and start it with more than 2 data disks attached. The VM fails to start …
=> CLOUDSTACK-9363: Fix HVM VM restart bug in XenServer

plugins/hypervisors/xenserver/src/com/cloud/hypervisor/xenserver/resource/CitrixResourceBase.java, plugins/hypervisors/xenserver/src/com/cloud/hypervisor/xenserver/resource/XenServerStorageProcessor.java, plugins/hypervisors/xenserver/src/com/cloud/hypervisor/xenserver/resource/Xenserver625StorageProcessor.java, server/src/com/cloud/storage/VolumeApiServiceImpl.java, server/src/com/cloud/vm/snapshot/VMSnapshotManagerImpl.java
snapshots to exist together
Reverting VM to disk only snapshot in Xenserver corrupts VM
Stale NFS secondary storage on XS leads to volume creation failure from snapshot
Fixed various concerns raised in #672
=> CLOUDSTACK-8663: Fixed various issues to allow VM snapshots and volume

server/src/com/cloud/network/router/CommandSetupHelper.java, systemvm/patches/debian/config/opt/cloud/bin/cs/CsAddress.py
Acquire ip from additional public subnet and configure nat on that ip.
After this pick any from that network and access additional public subnet from this vm. Traffic is supposed to go via additional public subnet interface in the VR.
=> CLOUDSTACK-9757: Fixed issue in traffic from additional public subnet

systemvm/patches/debian/config/opt/cloud/bin/cs/CsAddress.py
This PR replaces #1706.  It does not remove the IP from the database, but it does deprovision the IP correctly from the VR when the public IP is removed.
=> Fix public IPs not being removed from the VR when deprovisioned

scripts/vm/hypervisor/xenserver/vmops
There is issue with the xenserver 6.2 ipset type nethash. Fixed it by adding nethash for ipset version 6 which is xenserver 6.5. For ipset version 4.x use iptreemap. 
1. Tested configuring egress/ingress rules.
2. Tested the traffic for the configured rules from the VM.
=> Security group ingress/egress issues with xenserver 6.2

server/src/com/cloud/vm/UserVmManagerImpl.java
Removed Host version check in API. Because 
Case 1:(Lower to Higher Version)
Migration from lower version to higher version is valid.
Case 2:(Higher to Lower Version)
In this case system(Host) will not allow.
So no need to check version in API. Additionally,  CLOUDSTACK User Interface(UI) does  not allow  migration between different version of hyper-visors. But sometimes user wants to do migration from  Lower to Higher Version. Now he can do it via API.
ACS Link ==>
https://issues.apache.org/jira/browse/CLOUDSTACK-8841
=> CLOUDSTACK-8841: Storage XenMotion from XS 6.2 to XS 6.5 fails.

engine/schema/src/com/cloud/upgrade/DatabaseUpgradeChecker.java
For going from version A to version D, it uses to run the SQL files in
that order: A -> B -> C -> D -> A-cleanup -> B-cleanup -> C-cleanup ->
D-cleanup. If you had upgraded each version separatively you would have
run A -> A-cleanup -> B -> B-cleanup -> C -> C-cleanup -> D ->
D-cleanup.
This change the logic to follow the same path if you are jumping over
versions.
=> CLOUDSTACK 9601: Upgrade: change logic for update path for files

ui/scripts/system.js
ISSUE
When GPU tab of the host is selected on the management server UI, no GPU detail is displayed.
RESOLUTION
In the javascript file "system.js" while fetching the GPU details, sort functionality in dataprovider is returning value as undefined and hence it throwing an exception. So handled the output as undefined gracefully to avoid exception.
=> CLOUDSTACK-9784 : GPU detail not displayed in GPU tab of management server UI.

engine/schema/src/com/cloud/upgrade/dao/Upgrade452to460.java, engine/schema/src/com/cloud/upgrade/dao/Upgrade4920to41000.java
Removed systemvm template upgrade code in 4.6 upgrade. Added 4.10 system vm template upgrade changes with new urls and md5sum
Manual testing results:
Updated min req version:
mysql> select name, value from configuration where name = 'minreq.sysvmtemplate.version';
+------------------------------+----------+
| name                         | value    |
+------------------------------+----------+
| minreq.sysvmtemplate.version | 4.10.0.0 |
+------------------------------+----------+
Update template for KVM:
mysql> select * from vm_template where name = 'systemvm-kvm-4.10'\G
id: 201
unique_name: 201-2-badc363a-507d-3802-942f-205d35c3b575
name: systemvm-kvm-4.10
uuid: 3526258d-d9a4-4c3d-8f15-3137eb5d7ab8 …
=> CLOUDSTACK-9807/CLOUDSTACK-9808 - Added upgrade changes for 4.10 system vm template

scripts/vm/hypervisor/xenserver/vmops
Fixed issue in deploying vm in basic zone. 
There is issue in ipset command with xenserver 6.5. In util.pread2 ipset and -N is passed as single string and it caused the issue in command failure.
util.pread2(['/bin/bash', '-c', 'ipset', '-N ',  tmpname , type])
=> CLOUDSTACK-9821: Fixed issue in deploying vm in basic zone

plugins/hypervisors/vmware/src/com/cloud/hypervisor/vmware/manager/VmwareManager.java, plugins/hypervisors/vmware/src/com/cloud/hypervisor/vmware/manager/VmwareManagerImpl.java, plugins/hypervisors/vmware/src/com/cloud/hypervisor/vmware/resource/VmwareResource.java
Jira
===
CLOUDSTACK-9698 [VMware] Make hardcoded wait timeout for NIC adapter hotplug as configurable
Description
=========
Currently ACS waits for 15 seconds (hard coded) for hot-plugged NIC in VR running on VMware to get detected by guest OS.
The time taken to detect hot plugged NIC in guest OS depends on type of VMware NIC adapter like (E1000, VMXNET3, E1000e etc.)
and guest OS itself. In uncommon scenarios the NIC detection may take longer time than 15 seconds,
in such cases NIC hotplug would be treated as failure which results in VPC tier configuration failure.
Alternatively making the wait timeout for NIC adapter hotplug as configurable will be helpful for admins in such scenarios. This is specific to VR running over VMware hypervisor.
Also in future if VMware introduces new NIC …
=> CLOUDSTACK-9698 [VMware] Make hardcorded wait timeout for NIC adapter hotplug as configurable

plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java, plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtStartCommandWrapper.java, plugins/hypervisors/kvm/test/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java
With memory over-provisioning set to 1, when mgmt server starts VMs in parallel on one host, then the memory allocated on that kvm can be larger than the actual physcial memory of the kvm host.
Fixed by checking free memory on host before starting Vm.
Added test case to check memory usage on Host.
Verified Vm deploy on Host with enough capacity and also without capacity
=> Bug-ID: CLOUDSTACK-8880: calculate free memory on host before deploying Vm.  free memory = total memory - (all vm memory)

packaging/centos63/cloud.spec, packaging/centos7/cloud.spec
Related to 6051fa503a2da7b96256f21e6b7c42aa1f3cb01e
/cc @rhtyd (shapeblue)
=> CLOUDSTACK-9765: centos: packaging: fix missing path in spec file

systemvm/patches/debian/config/opt/cloud/bin/cs_ip.py
Defend against the specified dev not being in the databag.
=> CLOUDSTACK-9811: fixed an issue if the dev is not in the databag

engine/storage/volume/src/org/apache/cloudstack/storage/datastore/manager/PrimaryDataStoreProviderManagerImpl.java, test/integration/smoke/test_snapshots.py, tools/marvin/marvin/config/test_data.py
Fix for marvin test failure introduced in #1847 
Cc: @borisstoyanov @rhtyd @karuturi
=> Fix for test_snapshots.py using nfs2 instead of nfs template

server/src/com/cloud/storage/VolumeApiServiceImpl.java
Fixed travis CI failures happening after merge of PR#1953.
Also fixed root volume detach that was broken after merge of PR#1953.
I found following logs with root volume attach. 
`
2017-03-24 23:19:48,380 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (API-Job-Executor-27:ctx-7c53d1bc job-44) (logid:f3b54257) Executing AsyncJobVO {id:44, userId: 2, accountId: 2, instanceType: Volume, instanceId: 3, cmd: org.apache.cloudstack.api.command.admin.volume.AttachVolumeCmdByAdmin, cmdInfo: {"apiKey":"PYHMg5HhOkmTQvlmZSe1dIDfTxl8uwreeFoqfj0a4zPCC-1XTuwH7H5I8Ac9fyvPbtNO1eN9THi72q8ATfs8hg","signature":"DD+ljbVWpWQw6FCl1tCDSYe5Ui0\u003d","httpmethod":"GET","deviceid":"0","ctxAccountId":"2","uuid":"2db57cd8-c96c-48f9-83c5-b9a79c852cc5","cmdEventType":"VOLUME.ATTACH","virtualmachineid":"9cb6a944-8775-4e11-961b- …
=> CLOUDSTACK-9851 travis CI build failure after merge of PR#1953 & CLOUDSTACK-9850

test/integration/smoke/test_primary_storage.py
Fix for test_primary_storage integration tests on simulator.
When finding storage pool migration options for volume on running vm, API returns None as hypervisor doesn't support live migration.
````
2017-03-28 06:07:55,958 - DEBUG - ========Sending GET Cmd : findStoragePoolsForMigration=======
2017-03-28 06:07:55,977 - DEBUG - Response : None
2017-03-28 06:07:55,983 - CRITICAL - EXCEPTION: test_03_migration_options_storage_tags: ['Traceback (most recent call last):\n', '  File "/opt/python/2.7.12/lib/python2.7/unittest/case.py", line 329, in run\n    testMethod()\n', '  File "/home/travis/.local/lib/python2.7/site-packages/marvin/lib/decoratorGenerators.py", line 30, in test_wrapper\n    return test(self, *args, **kwargs)\n', '  File …
```
=> CLOUDSTACK-9854: Fix test_primary_storage test failure due to live migration

plugins/metrics/pom.xml
master is broken after fwd-merging metrics PR #1944 from 4.9
This is due to the incorrect parent version number in the metrics pom.
Corrected the same to reflect master version number.
=> CLOUDSTACK-9783: corrected the version number in metrics pom

engine/schema/src/com/cloud/upgrade/dao/Upgrade4920to41000.java
The PR fixes the error in restart network:
2017-04-04 10:27:39,217 DEBUG [c.c.n.r.NetworkHelperImpl] (API-Job-Executor-2:ctx-08904854 job-29417 ctx-3405d3f2) (logid:19bbd6e6) Router requires upgrade. Unable to send command to router:9784, router template version : Cloudstack Release 4.10.0 Wed Feb 15 05:42:18 UTC 2017, minimal required version : 4.10.0.0
It works after changing minreq.sysvmtemplate.version from 4.10.0.0 to 4.10.0
=> [4.10-blocker] Fix error in restart network in 4.10.0.0 RC

engine/schema/src/com/cloud/upgrade/dao/Upgrade4920to41000.java
`
> mysql> select id,unique_name,name,type,url,updated,created from vm_template where type='SYSTEM';
> +----+-------------+-------------------------------+--------+-----------------------------------------------------------------------------------------------+---------+---------------------+
> | id | unique_name | name                          | type   | url                                                                                           | updated | created             |
> +----+-------------+-------------------------------+--------+-----------------------------------------------------------------------------------------------+---------+---------------------+
> |  1 | routing-1   | SystemVM Template (XenServer) | SYSTEM | …
=> BUG-ID: CLOUDSTACK-9808 Added system Vm upgrade path for LXC and OVM

api/src/org/apache/cloudstack/api/command/admin/network/DedicateGuestVlanRangeCmd.java, ui/scripts/system.js
Description:
=========
Trying to dedicate a guest VLAN range to an account fails. Either API documentation is wrong or code path needs to be corrected. If we pass both account and projectId parameters to the dedicateGuestVlanRange (which are not mentioned as mutually exclusive in API description) the API layer throws error saying both are mutually exclusive.
Create an account. Create a project in that account.
Go to Admin account and change the view to the above project.
Navigate to Infrastructure -> Zone -> Physical Network -> Guest -> Dedicate Guest VLAN range.
Try to dedicate the guest VLAN range from the project view for the account associated with the project.
It fails with error saying "accountName and projectId are mutually exclusive".
Expected: …
=> CLOUDSTACK-9611: Dedicating a Guest VLAN range to Project does not work.

plugins/pom.xml
Recently there have been two threads asking and discussing the “midonet” integration with Apache CloudStack (ACS) [1-2].
After quite some discussions, we noticed that despite having some people willing to use it, the plugin has never been fully developed by its vendor (Midokura). Further, nobody else has put the effort on fully testing and finishing its implementation. It seems that the plugin was incorporated into our code base without being fully finished. Moreover, I have asked around at the Midonet community, and the java client they use has changed quite a bit from the one we use.
It begs the question if it does not work, why do we advertise such integration? [3]. 
Following the component retirement process defined in [4], a vote thread was started in [5]. The community decided to …
=> [CLOUDSTACK-9858] Retirement of midonet plugin (build disabling)

ui/index.jsp, ui/scripts/network.js, ui/scripts/system.js
Displays a VR tab that lists VRs for the network in the detail views. This has come up several times, and useful for admins when they want to reboot/destroy or view VR associated with a network.
Pinging for review - @abhinandanprateek @borisstoyanov @DaanHoogland @PaulAngus @karuturi @koushik-das
=> CLOUDSTACK-9805: Display VR list in network details

server/src/com/cloud/user/DomainManagerImpl.java, server/test/com/cloud/user/DomainManagerImplTest.java
It was noticed in production environments that `deleteDomain` task failed for domains with multiple accounts and resources. Examining logs it was found out that if Account Cleanup Task got executed after domain (and all of its subchilds) got marked as Inactive; and before delete domain task finishes, it produces a failure.
`AccountCleanupTask` gets executed every `account.cleanup.interval` seconds looking for:
* Removed accounts
* Disabled accounts
* Inactive domains
As `deleteDomain` marks domain to delete (and its subchilds) as Inactive before deleting them, when `AccountCleanupTask` is executed, it removes marked domains. When there are resources to cleanup on domain accounts, domain is not found throwing exception: `com.cloud.exception.InvalidParameterValueException: Please specify a …
=> CLOUDSTACK-9764: Delete domain failure due to Account Cleanup task

server/src/com/cloud/network/vpn/RemoteAccessVpnManagerImpl.java
This happens if VPC has redundant VRs.
The results from VRs are combined in commit 13eb789.
This PR simply separates the results to two parts and check them if there are two VRs.
=> [4.9] CLOUDSTACK-9356: FIX Cannot add users in VPC VPN

engine/orchestration/src/com/cloud/vm/VirtualMachineManagerImpl.java
This checks the work variable for NULL in all cases where it is
used.  Fixes CLOUDSTACK-9796.
=> CLOUDSTACK-9796 - Fix NPE in VirtualMachineManagerImpl.java

server/src/com/cloud/network/vpn/RemoteAccessVpnManagerImpl.java
VPN Users search functionality broken
If you try to search VPN users with it’s user name, you will not be able to search.
Fixed the same.
Parent PR : https://github.com/apache/cloudstack/pull/1910
=> CLOUDSTACK-9748:VPN Users search functionality broken

server/src/com/cloud/network/IpAddressManagerImpl.java
This PR closes PR #907 
Reproducing steps:
1. Create an account
2. Dedicate public ip range to this account.
Infrastructure > physicalnetwork>physicalnet -> public:
select Add account and add account created in step1
3. Create a shared network scope domain.
Network->Add guest network
4. login to the account
5.Deploy Vm in the shared network.
6. Deploy vm is failing.
=> CLOUDSTACK-8931: Fail to deploy VM instance when use.system.public.ips=false

engine/components-api/src/com/cloud/network/IpAddressManager.java, server/src/com/cloud/network/IpAddressManagerImpl.java, server/src/com/cloud/network/firewall/FirewallManagerImpl.java, server/src/com/cloud/network/lb/LoadBalancingRulesManagerImpl.java, server/src/com/cloud/network/router/VirtualNetworkApplianceManagerImpl.java, server/src/com/cloud/network/rules/RulesManagerImpl.java
On failure of ip assoc in back end (In VR), added config option to ignore or not to ignore failure. Using this failures won't be ignored and ip address will not set to free in DB.
=> CLOUDSTACK-9756: Configure to  ignore the ipassoc failure

plugins/hypervisors/vmware/src/com/cloud/hypervisor/vmware/VmwareServerDiscoverer.java, plugins/hypervisors/vmware/src/com/cloud/hypervisor/vmware/resource/VmwareResource.java, vmware-base/src/com/cloud/hypervisor/vmware/mo/ClusterMO.java, vmware-base/src/com/cloud/hypervisor/vmware/mo/HostMO.java, vmware-base/src/com/cloud/hypervisor/vmware/mo/VmwareHypervisorHost.java
[VMware] VR loses DHCP settings and VMs cannot obtain IP after HA recovery.
Fix: Set high restart priority for the VR.
Test scenarios:
- Enable cluster HA after VR is created. Now stop and start VR and check its restart priority, should be High.
- Enable cluster HA before VR is created. Now create some VM and verify that VR created must have High restart priority.
Issue validation steps:
- Create a VMware setup with a cluster having 2 ESXi hosts and Enable HA at cluster level in vCenter.
- Creat a Network offering with DHCP and source NAT
- Create few VMs using network created above and Ensure that router VM is created with restart priority set to High.
- Make the ESXi host (where router VM is running) unreachable.
- Verified that router VM is first migrated to other host and VMs acquire …
=> CLOUDSTACK-9719: [VMware] VR loses DHCP settings and VMs cannot obtain IP after HA recovery - Set high restart priority for the VR.

engine/schema/src/com/cloud/capacity/dao/CapacityDaoImpl.java
When listCapacity is used with the sortBy=usage option, the capacity was not getting calculated correctly.
Root Cause: The group by options for pod and zone was incorrectly specified. Results were additionally added up. Result was incorrect.
Once the correct group by clause is specified, only the results of the query need to be returned.
=> CLOUDSTACK-9653 The system capacity was not getting calculated correctly

server/src/com/cloud/api/auth/DefaultLoginAPIAuthenticatorCmd.java
Ldap auto creation of accounts is broken due to the security fix for
CLOUDSTACK-9369.
There was an explicit check to not allow login incase the
user doesnt exist.  removed the same.
=> CLOUDSTACK-9369 Fixed Ldap regression

engine/schema/src/com/cloud/network/dao/LoadBalancerDao.java, engine/schema/src/com/cloud/network/dao/LoadBalancerDaoImpl.java, server/src/com/cloud/network/NetworkServiceImpl.java, server/test/org/apache/cloudstack/networkoffering/CreateNetworkOfferingTest.java, server/test/resources/createNetworkOffering.xml
ISSUE
Releasing secondary guest IP fails with error VM nic Ip x.x.x.x is mapped to load balancing rule
REPRO STEPS
Create two isolated guest networks with same CIDR
Deploy VMs on both networks
Acquire secondary IP on NICs of both VMs and make sure they have the same value, user can input the IP address.
Configure Loadbalancing rule on one of the secondary IP address and try releasing the other secondary IP address.
The operation would fail
EXPECTED BEHAVIOR
Secondary IP address should be released if there are no LB rules associated with it.
ACTUAL BEHAVIOR
Not releasing secondary IP address even if there are no LB rules associated with it.
=> CLOUDSTACK-9779 : Releasing secondary guest IP fails with error VM nic Ip x.x.x.x is mapped to load balancing rule

server/src/com/cloud/api/ApiResponseHelper.java, test/integration/component/test_list_nics.py
listNics API for a VM, "type" was not returned within API response.
EXPECTED BEHAVIOR
The listNics API response return type of NIC (type), as specified in https://cloudstack.apache.org/api/apidocs-4.8/user/listNics.html
ACTUAL BEHAVIOR
The listNics API response does not return type of NIC.
(local) 🐵 > list nics virtualmachineid=a69edaf5-8f21-41ff-8c05-263dc4bd5354
count = 1
nic:
id = 211e0d46-6b94-4425-99f7-e8e9efea2472
deviceid = 0
gateway = 10.1.1.1
ipaddress = 10.1.1.45
isdefault = True
macaddress = 02:00:06:f6:00:01
netmask = 255.255.255.0
networkid = c08fddf1-fd77-4810-a062-ea9d03c5c7e6
virtualmachineid = a69edaf5-8f21-41ff-8c05-263dc4bd5354
Solution:
added "type" details for listNics API response.
After Fix:
(local) 🐵 > list nics …
=> CLOUDSTACK-9630: Cannot use listNics API as advertised

ui/scripts/instances.js, ui/scripts/ui/dialog.js
Refer to [CLOUDSTACK-9695](https://issues.apache.org/jira/browse/CLOUDSTACK-9695) for more details.
=> CLOUDSTACK-9695: VM snapshot is disabled if the VM Instance is off

client/tomcatconf/db.properties.in, packaging/centos7/tomcat7/db.properties, utils/conf/db.properties
MySQL 5.7 has a more strict SQL mode by default with which CloudStack
is not compatible.
By setting the SQL Mode to a more relaxed mode on run-time we can
run without changing any SQL server settings.
Admins could also apply this to the [mysqld] section of their my.cnf:
sql_mode = 'STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
=> CLOUDSTACK-9871: Set SQL Mode in SQL Session for MySQL 5.7 compatibility

packaging/build-deb.sh
We do not need to build a tarball before building the DEB packages
Saves a few minutes on building DEB packages
=> deb: Only build binary packages

test/integration/smoke/test_deploy_virtio_scsi_vm.py
Fix issue where unsupported hypervisors were not skipping tests
Fix issue where the template referenced no longer existed on openvm.eu
@karuturi @DaanHoogland @serg38 @kiwiflyer
=> CLOUDSTACK-9893 / CLOUDSTACK-8239 fix test_deploy_virtio_scsi_vm.py

server/src/com/cloud/network/IpAddressManagerImpl.java
In Basic zone, while deploying a VM it fails with an unexpected exception.
This is reproducible only when java asserts are enabled.
=> CLOUDSTACK-9623: Deploying virtual machine fails due to "Couldn't find vlanId" in Basic Zone

engine/orchestration/src/com/cloud/vm/VirtualMachineManagerImpl.java
**Issue** - Consecutive VM cold migration fails.
**Root Cause Analysis** - In case of VMware, if VM is being cold migrated between clusters belonging to two different VMware DCs, Cloudstack unregisters the VM from the source host and cleans up the associated VM files. The check if a VM is being cold migrated across DCs is made using the source host id. In case of consecutive cold migrations since the source host id of a VM is NULL and no VM exists, Cloudstack should skip the check
**Proposed Solution** - Attempt to unregister a VM in another DC, only if there is a host associated with a VM.
=> CLOUDSTACK-8829 : Consecutive cold migration fails.

engine/orchestration/src/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java, utils/src/main/java/com/cloud/utils/net/NetUtils.java, utils/src/test/java/com/cloud/utils/net/NetUtilsTest.java
Add the CGN network to the list of allowed netblocks for guest networks.  Additionally convert the previous strings to a list to allow easier modification/expansion in the future if needed.
=> Allow CGN (RFC6598) to be used within a VPC

plugins/metrics/src/org/apache/cloudstack/response/ClusterMetricsResponse.java, plugins/metrics/src/org/apache/cloudstack/response/ZoneMetricsResponse.java
HostStats returns cpu usage in percentage while memory usage in bytes.
This fixes a regression in maximum CPU usage deviation that did not
assume the values to be in percentage and multiple the final ratios
with 100 which leads to 100x the actual deviation value.
Pinging for review - @karuturi @DaanHoogland @abhinandanprateek @borisstoyanov @rashmidixit 
=> [4.9+] CLOUDSTACK-9900: Fix high CPU deviation issues seen in metrics view

server/src/com/cloud/storage/VolumeApiServiceImpl.java, server/test/com/cloud/storage/VolumeApiServiceImplTest.java
The Primary Storage resource counts is considered twice: Once while creating the volume and next while attaching it. This results in failure while Attaching the volume, if the primary storage resource limit is set.
**Following are the steps to reproduce the issue:**
1. Create a Domain
2. Create an Account.
3. Allocate 11 GB Primary storage limit to the domain.
4. Deploy a VM sized 8GB (Primary storage resource count is now 8GB )
5. Create a 2GB custom disk by using the option 'Add Volume' link.(Primary storage resource count is now 10GB). The Volume state is 'Allocated'
6. Now try to Attach the data-disk created above to a VM. At this point the resource count limit is again checked, and the attachment fails, because it is expected to be 12GB, but, which exceeds the limit of 11GB.
7. This …
=> CLOUDSTACK-9824:Resource count for Primary storage is considered twice - while creating and while attaching the disk

plugins/hypervisors/xenserver/src/com/cloud/hypervisor/xenserver/resource/Xenserver625StorageProcessor.java
removed the host uuid from SR label so that any host which has access to
the SR(all the hosts in the same pool) can reuse the same SR
=> CLOUDSTACK-9834: prepareTemplate API call doesn't work well with XenServer & Local SR (Db_exn.Uniqueness_constraint_violation)

plugins/hypervisors/hyperv/pom.xml
This fixes log4j xml to have @AGENTLOG@ replaced with values defined
in build/replace.properties.
Without the fix, spurious log files with names such as @AGENTLOG@ are seen.
=> CLOUDSTACK-9904: Fix log4j to have @AGENTLOG@ replaced

server/src/com/cloud/network/router/CommandSetupHelper.java, systemvm/patches/debian/config/opt/cloud/bin/cs/CsDhcp.py
when a shared network is secondary the default gateway gets overwritten by a bogus one
dnsmasq does the right thing and replaces it with its own default which is not good for us
so check for '0.0.0.0'
=> CLOUDSTACK-9887 ignore bogus default gateway

utils/pom.xml, utils/src/main/java/com/cloud/utils/nio/NioConnection.java
The first PR #1493 re-enabled the NioTest but not the new PR #1549.
@rhtyd the test fails locally on my laptop. Is there any special configuration requirements?
=> CLOUDSTACK-9918: Activate NioTest following changes in CLOUDSTACK-9348 PR #1549

engine/orchestration/src/com/cloud/vm/VirtualMachineManagerImpl.java
Previous pod_id still remains in the vm_instance table after VM migration with migrateVirtualMachineWithVolume
```
Previous pod_id still remains in the vm_instance table after VM migration with migrateVirtualMachineWithVolume
Before migrateVirtualMachineWithVolume
mysql> select v.id,v.instance_name,h.name,v.pod_id as pod_id_from_instance_tb,h.pod_id as pod_id_from_host_tb from vm_instance v, host h where v.host_id=h.id and v.id=2;
------------------------------------------------------------------------------------------------------
id 	instance_name 	name 	pod_id_from_instance_tb 	pod_id_from_host_tb
------------------------------------------------------------------------------------------------------
2 	i-2-2-VM 	testVM 	1 	1
--------------------------------------------------------------- …
```
=> CLOUDSTACK-9831: Previous pod_id still remains in the vm_instance table

api/src/com/cloud/network/NetworkModel.java, engine/api/src/com/cloud/vm/VirtualMachineGuru.java, engine/components-api/src/com/cloud/network/addr/PublicIp.java, engine/schema/src/com/cloud/network/dao/NetworkDao.java, engine/schema/src/com/cloud/network/dao/NetworkDaoImpl.java, server/src/com/cloud/configuration/ConfigurationManagerImpl.java, server/src/com/cloud/network/Ipv6AddressManager.java, server/src/com/cloud/network/Ipv6AddressManagerImpl.java, server/src/com/cloud/network/NetworkModelImpl.java, server/src/com/cloud/network/guru/PodBasedNetworkGuru.java, server/src/com/cloud/network/guru/PrivateNetworkGuru.java, server/src/com/cloud/network/guru/StorageNetworkGuru.java, server/src/com/cloud/network/router/NicProfileHelperImpl.java, server/test/com/cloud/vpc/dao/MockNetworkDaoImpl.java, utils/src/main/java/com/cloud/utils/net/NetUtils.java, utils/src/test/java/com/cloud/utils/net/NetUtilsTest.java
Enable unique mac address across different deployments and networks.
If there two networks in two different deployment zones then this feature will avoid mac address collision.
=> CLOUDSTACK-9723: Enable unique mac address across the zones

engine/storage/image/src/org/apache/cloudstack/storage/image/TemplateServiceImpl.java
store ref table so builtin template is never downloaded completely
In handleSysTemplateDownload method creating template only if there exists no entry
handleTemplateSync will take care of other scenario
=> CLOUDSTACK-9686: Fixed multiple entires for builtin template in template

server/src/com/cloud/vm/UserVmManagerImpl.java
It fixes the bug https://issues.apache.org/jira/browse/CLOUDSTACK-8894.
Steps:
1.Install and configure XenServer 6.5 with vGPU enabled . Enabled dynamic scaliing 
2. Deploy VM using K160Q type windows 7 template with PV tools installaed and dynamic scaling enabled 
3. Tried dynamic scaling with offering which has K180Q defined.
Observation: 
1. Currently vGPU resource dynamic scaling is not supported. But CloudStack returns success and updating the VM details with new offering details including new vGPU type. 
2. But from Xenserver , There is no change with vGPU type and it remains with old vGPU type. This is not correct
Expected Result:
Dynamic scaling should be restricted when source/destination offering has vGPU type on a vGPU enabled VM
=> CLOUDSTACK-8894: Restrict vGPU enabled VMs dynamic scaling if new service offering has different vGPU type

test/integration/component/test_migrate_vol_to_maintained_pool.py
This script automates the below functionality: 
CloudStack should block migration to a Storage pool which is in maintenance mode.
=> Automation for CLOUDSTACK-9217 script to test block volume migration to a pool in maintenance mode

api/src/org/apache/cloudstack/api/ApiServerService.java, server/src/com/cloud/api/ApiServer.java, server/src/com/cloud/api/ApiServlet.java, server/src/com/cloud/configuration/Config.java, server/src/com/cloud/storage/snapshot/SnapshotManager.java, server/src/com/cloud/storage/snapshot/SnapshotManagerImpl.java, utils/src/main/java/com/cloud/utils/HttpUtils.java
Following parameters are moved from config.java to configdepot.
This will make the management of configuration parameter easy during upgrade and avoid inconsistency of values of parameters for fresh setup and upgraded setup.
snapshot.max.hourly
snapshot.max.daily
snapshot.max.weekly
snapshot.max.monthly
enable.secure.session.cookie
json.content.type
=> CLOUDSTACK-9833: Move configuration parameters from Config.java to use configdepot

api/src/com/cloud/network/IpAddress.java, core/src/com/cloud/agent/api/routing/NetworkElementCommand.java, engine/components-api/src/com/cloud/network/addr/PublicIp.java, engine/schema/src/com/cloud/network/dao/IPAddressVO.java, plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java, plugins/hypervisors/xenserver/src/com/cloud/hypervisor/xenserver/resource/CitrixResourceBase.java, server/src/com/cloud/network/IpAddressManagerImpl.java, server/src/com/cloud/network/router/CommandSetupHelper.java, server/src/com/cloud/network/rules/RulesManagerImpl.java, server/test/com/cloud/network/IpAddressManagerTest.java, setup/db/db/schema-4920to41000.sql
FIxed issue in disabling multiple static  nat simultaneously.
This patch has taken changes from the PR 1450 and added the missing parts
https://github.com/apache/cloudstack/pull/1450
=> CLOUDSTACK-9317: Fixed disable static nat on leaving ips on interface

test/integration/component/test_acl_isolatednetwork.py
issue:
=======
ERROR:  Validate that Admin should be able to create network for himself
**Traceback (most recent call last):
CloudstackAPIException: Execute cmd: createnetwork failed, due to: errorCode: 431, errorText:Can't specify vlan; corresponding offering says specifyVlan=false****
Reason:
============
Default isolated network offering with SourceNat service has "Specify Vlan" parameter set to No. When specify vlan is "No" we can't pass vlan number for network creation api. Three tests are passing vlan id. Hence setting it to None.
Test Result
-----------
Validate that Admin should not be able deploy VM for a user in a network that does not belong to the user ... === TestName: test_13_1_deployvm_admin_foruserinotherdomain_crossnetwork | Status : SUCCESS 
ok
Validate that Admin should …
=> Changing vlan to None since network offering being used has Specify Vlan set to False

test/integration/component/test_ldap_auto_import.py, tools/marvin/marvin/config/test_data.py
As of now, CloudStack can automatically import LDAP users based on the
configuration to a domain or an account. However, any new users in LDAP
aren't automatically reflected. The admin has to manually import them
again.
This feature enables admin to map LDAP group/OU to a CloudStack domain
and any changes are reflected in ACS as well.
=> CLOUDSTACK-8647 : LDAP: Auto Import and Trust AD Automation of test cases

scripts/vm/hypervisor/xenserver/vmops, scripts/vm/network/security_group.py
ipset set name  max length allowed is  31 char. If the vm name has longer name then the trimming of set has done in this fix. Also cleanup of rules are taken care.
=> CLOUDSTACK-9657: Fixed security group ipset issues with long vm name

engine/schema/src/com/cloud/upgrade/DatabaseUpgradeChecker.java, engine/schema/src/com/cloud/upgrade/dao/Upgrade4920to4930.java, setup/db/db/schema-4920to4930-cleanup.sql, setup/db/db/schema-4920to4930.sql
This adds an upgrade path from 4.9.2.0 to 4.9.3.0, this also includes changes from PR https://github.com/apache/cloudstack/pull/1928 that adds missing hypervisor capability in 4.9/4.10+. This also fixes a db-cleanup path sequence issues, with that puts 4.10 after 4.1.0, and before 4.2.0.
Once validated I can help merge this on master, since this will cause merge conflicts on fwd-merging.
Ping - @syed @karuturi @borisstoyanov @DaanHoogland @abhinandanprateek
=> CLOUDSTACK-9792: Add upgrade path for 4.9.3.0

engine/schema/src/com/cloud/storage/dao/VolumeDao.java, engine/schema/src/com/cloud/storage/dao/VolumeDaoImpl.java, server/src/com/cloud/storage/StorageManagerImpl.java
A root volume can be replaced by a different root volume without the VM it belongs to being expunged.
From dev@:
For example: Let’s say we have a system VM running on NFS primary storage. We then put this primary storage into maintenance mode, which creates the system VM (with the same name) on a different primary storage (we do not create a new row in the cloud.vm_instance table for this VM). While this VM works, the original root disk of the system VM remains on the original primary storage and is not destroyed by the code in StorageManagerImpl.cleanupStorage(boolean) in 4.10 because 4.10 (as shown above) only asks for non-root volumes to consider for deletion. In the 4.9 version of the code, the original root disk is cleaned up in StorageManagerImpl.cleanupStorage(boolean). The problem …
=> Fix for CLOUDSTACK-9660

systemvm/patches/debian/config/etc/vpcdnsmasq.conf, systemvm/patches/debian/config/opt/cloud/bin/cs_dhcp.py
REPRO STEPS
1. Deploy a vm to a VPC having more than one tier, selecting one of the tier .
2. Attach the second tier to the VM as second NIC.
3. Stop and start the VM or restart the network service to retrieve the IP addresses from DHCP server.
EXPECTED BEHAVIOR
IP addresses should be assigned to all the tiers even if it is the same VM connected to the tiers of same VPC.
ACTUAL BEHAVIOR
In VMs associated with 2 tiers of the same VPC, one of the NIC can't receive IP address over DHCP
=> CLOUDSTACK-9017 : VPC VR DHCP broken for multihomed guest VMs

engine/storage/volume/src/org/apache/cloudstack/storage/volume/VolumeServiceImpl.java, framework/jobs/src/org/apache/cloudstack/framework/jobs/impl/AsyncJobManagerImpl.java, test/integration/component/test_concurrent_create_volume_from_snapshot.py
Existing CloudStack supports volume provisioning from a backed volume snapshot only with sequential job execution. It does n't support for multiple volume create request concurrently.
Snapshot has derived entity(s) in snapshot_store_ref table. While creating volume from the snapshot request , state transition processed on this derived entity instead of Actual Entity.  However the state transition happening on this derived entity is not observable in UI(Browser). Since this transition has no specific usage across the product, truncated the transition. 
There after parallel volume(s) creation is supported in ACS. Also in this feature added, inserting VOLUME_DETAILS table (meta-data for parallel volume creation request information) to support other operation like MS failover case , Cluster …
=> CLOUDSTACK-9895 : Added support for parallel volume(s) creation from a volume snapshot

plugins/dedicated-resources/src/org/apache/cloudstack/api/commands/DedicateClusterCmd.java
ISSUE
1. dedicateCluster API did not return correct details in response when executed although API itself worked fine.
2. As per documentation, response for dedicateCluster API should have affinity group id, cluster id, cluster name, etc. but none of those were included response.
=> CLOUDSTACK-9937 : dedicateCluster API response does not return correct detail in response

api/src/org/apache/cloudstack/api/command/user/vm/StopVMCmd.java, core/src/com/cloud/agent/api/StopCommand.java, engine/orchestration/src/com/cloud/vm/VirtualMachineManagerImpl.java, plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java, plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtStopCommandWrapper.java, plugins/hypervisors/vmware/src/com/cloud/hypervisor/vmware/resource/VmwareResource.java, plugins/hypervisors/xenserver/src/com/cloud/hypervisor/xenserver/resource/CitrixResourceBase.java, plugins/hypervisors/xenserver/src/com/cloud/hypervisor/xenserver/resource/wrapper/xenbase/CitrixStopCommandWrapper.java, test/integration/smoke/test_vm_life_cycle.py
The 'force' option provided with the stopVirtualMachine API command is
often assumed to be a hard shutdown sent to the hypervisor, when in fact
it is for CloudStacks' internal use. CloudStack should be able to send
the 'hard' power-off request to the hosts.
When forced parameter on the stopVM API is true, power off (hard shutdown)
a VM. This uses initial changes from #1635 to pass the forced parameter
to hypervisor plugin via the StopCommand, and fixes force stop (poweroff)
handling for KVM, VMware and XenServer.
This will speed up VM stops with forced=true. Useful for CI-like environments.
The global setting `vm.destroy.forcestop` is now also honoured to force stop VMs while destroying them, if it is set to true.
Pinging for review @DaanHoogland @abhinandanprateek @nathanejohnson …
=> [4.9+] CLOUDSTACK-9860: Power off VMs when force stop is provided

framework/config/src/org/apache/cloudstack/config/Configuration.java, framework/config/src/org/apache/cloudstack/framework/config/impl/ConfigurationVO.java, server/src/com/cloud/api/ApiResponseHelper.java, test/integration/smoke/test_internal_lb.py
secure and hidden config values are first unencrypted before returning
them in the api. This is not desired as they are secure configs
returning encrypted strings for secure and hidden configs if encryption
is enabled.
=> CLOUDSTACK-9901 secure and hidden config values are returned as plaintext string

plugins/hypervisors/xenserver/src/com/cloud/hypervisor/xenserver/resource/Xenserver625StorageProcessor.java
Summary: CLOUDSTACK-8921
snapshot_store_ref table should store actual size of back snapshot in secondary storage
Calling SR scan to make sure size is updated correctly
This scenario is tested with this bug fix. Unit tests are not added as the methods that are fixed are too long to add unit tests and there is no existing unit test to change
=> BUG-ID:CLOUDSTACK-8921 snapshot_store_ref table should store actual size of backup snapshot in secondary storage

server/src/com/cloud/network/vpn/Site2SiteVpnManagerImpl.java
CLOUDSTACK-9905 : VPN Gateway with Public Subnet
When we attempt to use a /24 subnet with a public IP ranges, for example,153.97.140.0/24. VPN Customer Gateways can be created with this type of CIDR, but cannot be updated, for example to 153.97.181.0/24 . Attempting to do so produces the error "The customer gateway cidr list 153.97.181.0/24 contains invalid guest cidr!"
REPRO STEPS
Created a new VPN Customer Gateway
Attempted to change the CIDR list entry from 153.97.180.0/24 to 153.97.181.0/24
The UI became unresponsive
The Management-server log shows the following:
2017-03-31 17:10:42,471 WARN [c.c.u.n.NetUtils] (API-Job-Executor-9:ctx-ed9b5816 job-172 ctx-32369258) (logid:3a16f24b) cidr 153.97.181.0/24 is not RFC 1918 compliant
153.97.181.0/24
Users should be able to …
=> CLOUDSTACK-9905:VPN Gateway with Public Subnet

utils/src/main/java/com/cloud/utils/ssh/SshHelper.java, utils/src/test/java/com/cloud/utils/ssh/SshHelperTest.java
A delay of 1 sec has been introduced in SSHHelper Class. This is a fail safe code. Removing this will improves the performance of deployVm by 4 sec, createFirewallRule by 1 sec and createPortForwardingRule by 1 sec.
We have not faced any issues after removing the delay. This was introduced when we were using older version of Trilead library.
=> CLOUDSTACK-9843 : Performance improvement of SSHHelper

engine/schema/src/com/cloud/storage/dao/VolumeDaoImpl.java, server/src/com/cloud/api/query/QueryManagerImpl.java
If a VM is cold migrated the vm_instance_id and uuid of volume is nullified. So there is no link between volume and vm.
With this the ROOT volume usage can not be mapped to a VM.
```
mysql>  select id,name,uuid,created,removed,state from cloud.volumes where name="ROOT-88" ;
+-----+------------+--------------------------------------+---------------------+---------------------+----------+
| id  | name       | uuid                                 | created             | instance_id         | state    |
+-----+------------+--------------------------------------+---------------------+---------------------+----------+
| 89  | ROOT-88   | NULL                                 | 2015-08-31 06:14:01 | NULL                | Expunged |
| 96  | ROOT-88   | a32e70e7-9869-49c8-92fa-5acd45abc94e | …
```
=> CLOUDSTACK-9842: Unable to map root volume usage to VM

server/src/com/cloud/resource/ResourceManagerImpl.java, server/src/com/cloud/storage/StorageManagerImpl.java
…al storage in op_host_capacity is still enabled
Description
=========
When a host is disabled or removed, local storage related capacity data for the corresponding local storage of the host is still in enabled state.
This may not directly impact deploy VM functionality (for example) but it does show incorrect capacity calculations.
Steps
=====
1. Enable local storage for zone
2. Disable host or remove host (after adding it to maintenance mode)
3. Check op_host_capacity (capacity_state=9)
In either of the cases, the local storage related capacity is still enabled for the host.
```
mysql> select id, name, uuid, status,resource_state, type, removed from host where type = 'Routing';
+----+--------------------+--------------------------------------+--------+----------------+---------+--------- …
```
=> CLOUDSTACK-9701: Local storage capacity is not handled properly

plugins/hypervisors/vmware/src/com/cloud/hypervisor/vmware/resource/VmwareResource.java
Jira
===
CLOUDSTACK-9704 Remove dependency on VmwareContext object to fetch system VM key file
Description
========
While remote executing commands/scripts through SSH in VR, ACS uses system vm keyfile.
ACS is fetching this key file using VMwareContext object which encapsulates vCenter connection handle.
This is inefficient because of dependency on getServiceContext() which means a vCenter connection
handle which is not required just to fetch a file in name space in management server.
Fix
===
Implement a method to fetch system vm key file by using Script class instead of VmwareManagerImpl. Ensure this implementation is not present in VmwareManagerImpl itself because fetching the manager object from VmwareContext object unnecessarily adds dependency on session object just to search for …
=> CLOUDSTACK-9704 Remove dependency on VmwareContext object to fetch systemVM keyfile

engine/schema/src/com/cloud/network/dao/IPAddressDaoImpl.java, test/integration/component/maint/test_ip_resource_count_for_vpc.py
Unable to limit the Public IPs in VPC.
In VPC network, while acquiring the IP addresses, in the resource_count table, count for the domain is getting increased. However, when the resource count is updated at Domain level, resource count is getting reverted to only non-vpc ip count.
1. Create a VPC
2. Create a VPC tier.
3. Check resource_count table and note the ip address count. (say 1)
4. Keep acquiring the IP addresses, (say 4 IP addresses). Now new ip address count resource_count table is 5.
5. update the resource count at domain level.
6. the resource_count is updated back 1
Root Cause: Update resource count command recalculates the resource count. While computing public IP we are not considering the ips allocated to VPC.
ResourceLimitManagerImpl.java -> …
=> CLOUDSTACK-9694: Unable to limit the Public IPs in VPC

plugins/hypervisors/vmware/src/com/cloud/hypervisor/vmware/manager/VmwareManagerImpl.java
Issue
=====
While listing datacenters associated with a zone, only zone Id validation is required.
There is no need to have additional checks like zone is a legacy zone or not.
Fix
===
Removed unnecessary checks over zone ID and just checking if zone with specified ID exists or not.
Signed-off-by: Sateesh Chodapuneedi <sateesh.chodapuneedi@accelerite.com>
=> CLOUDSTACK-9684 Invalid zone id error while listing vmware zone

server/src/com/cloud/configuration/ConfigurationManagerImpl.java, test/integration/component/test_concurrent_snapshots_limit.py
'concurrent.snapshots.threshold.perhost' is a  global and cluster level setting. It should accept only integer values but without this fix it is accepting string  as well.  For complete description please refer -> [CLOUDSTACK-9603](https://issues.apache.org/jira/browse/CLOUDSTACK-9603)
=> CLOUDSTACK-9603: 'concurrent.snapshots.threshold.perhost' parameter should not accept String.

ui/scripts/instances.js, ui/scripts/sharedFunctions.js, ui/scripts/storage.js, ui/scripts/templates.js
UI doesn't give an option to select the xentools version while registering template for any user other than ROOT admin. Templates registered by other users are marked as 'xenserver56' and results in unsusable VMs due to the device_id:002 issue with windows if the template is having xentools version higher than 6.1 .
Repro Steps
Select register template as any other user than ROOT domain admin and UI doesn't give an option to select the xentools version.
=> CLOUDSTACK-9585 UI doesn't give an option to select the xentools version

server/src/com/cloud/network/vpn/Site2SiteVpnManagerImpl.java
ISSUE
============
Using the search field in Network - VPN Customer Gateway results in all VPN customer gateways being listed. Results are not narrowed down to what you searched.
REPRO STEPS
Created two VPN customer gateways named Test1 and Test2 and try to  search for Test1. Both VPN customer gateways were displayed after hitting the search button.
EXPECTED BEHAVIOR
Searching should narrow down the results.
ACTUAL BEHAVIOR
All VPN customer gateways are listed after searching.
=> CLOUDSTACK-9935 : Search in VPN Customer Gateway not working

api/src/com/cloud/network/NetworkService.java, api/src/org/apache/cloudstack/api/command/user/vm/ListNicsCmd.java, api/src/org/apache/cloudstack/api/response/NicSecondaryIpResponse.java, engine/api/src/org/apache/cloudstack/engine/orchestration/service/NetworkOrchestrationService.java, engine/orchestration/src/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java, engine/schema/src/com/cloud/vm/dao/NicDao.java, engine/schema/src/com/cloud/vm/dao/NicDaoImpl.java, engine/schema/src/com/cloud/vm/dao/NicSecondaryIpDao.java, engine/schema/src/com/cloud/vm/dao/NicSecondaryIpDaoImpl.java, server/src/com/cloud/network/NetworkServiceImpl.java, server/test/com/cloud/vpc/MockNetworkManagerImpl.java, ui/scripts/network.js
Search for secondary IP of NIC that is attached to an instance is not working.
If instance has more than one secondary IP assigned and administrator attempts to search that list, all IPs are displayed instead of being filtered by the search string.
in web UI:
Dashboard -> Instances -> -> NICs -> ”View Secondary IPs” -> Search for a IP, but the search returns all the IPs in the list
=> CLOUDSTACK-9740 : Search for secondary IP of NIC that is attached to an instance is not working

server/src/com/cloud/storage/snapshot/SnapshotManager.java, server/src/com/cloud/storage/snapshot/SnapshotManagerImpl.java, usage/src/com/cloud/usage/UsageManagerImpl.java
Physical size of the snapshot is considered for the usage generation. This will have a huge impact on customer billiing after the  FIX(https://issues.apache.org/jira/browse/CLOUDSTACK-7825).
As part of the above fix size column now has the physical size of the snapshot and the virtual_size column has the virtual size of the volume. 
Now when the usage is processed it is taking the size ( which is physical size of the snapshot). But It should take Virtual size for existing customers.
So as part of fix providing option for customers to choose between virtual and physical size.
=> CLOUDSTACK-9907 Physical size of snapshot is considered for usage

systemvm/patches/debian/config/opt/cloud/bin/cs/CsConfig.py, systemvm/patches/debian/config/opt/cloud/bin/merge.py, systemvm/patches/debian/config/opt/cloud/bin/update_config.py, systemvm/patches/debian/config/opt/cloud/bin/vr_cfg.sh
This PR:
* lowers logging on the vRouters; specifically by not dumping the full databag every time it is loaded and saved; this helps with log partitions filling up like there's no tomorrow
* defers configuring the daemons (Apache, DNSmasq et al) until after vr_cfg has parsed through the entire config. 
Without these patches, the VR in a pod containing 5 instances in a zone with 2.000 will load in ~8.002.000 config entries in about 8.000 restarts/reloads of dnsmasq and apache.
This takes hours, hitting several timeout and other bugs along the way.
This PR, combined with @wido 's PR's, brings that down to 5 config entries and 1 restart/reload.
In aforementioned scenario our VR's loading times were brought down from 3+ hours to 3+ minutes.
https://github.com/apache/cloudstack/pull/1451 …
=> vRouters fixes & performance improvement

.travis.yml
Adds group to travis yml file based on:
https://blog.travis-ci.com/2017-06-19-trusty-updates-2017-Q2
This can be accepted if Travis passes. Pinging for review - @DaanHoogland @borisstoyanov @wido @karuturi @PaulAngus and others
=> Travis: Fix usage of sudo enable Trusty images

plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
Libvirt / Qemu (KVM) does not collect statistics about these either.
On some systems it might even yield a 'internal error' from libvirt
when attempting to gather block statistics from such devices.
For example Ubuntu 16.04 (Xenial) has a issue with this.
Skip them when looping through all devices.
=> CLOUDSTACK-9929: Do not gather statistics for CDROM or FLOPPY devices

.python-version
This aims at fixing recent Travis failures
Pinging - @DaanHoogland @borisstoyanov @wido and others
Refer:
https://travis-ci.org/apache/cloudstack/builds
Most failures due to failing apidocs build:
```
[[1;34mINFO[m] [1mBuilding Apache CloudStack apidocs 4.11.0.0-SNAPSHOT[m
log4j:WARN No appenders could be found for logger (org.reflections.Reflections).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
pyenv: version `cloudstack' is not installed (set by /home/travis/build/apache/cloudstack/.python-version)
...
[[1;34mINFO[m] Apache CloudStack apidocs .......................... [1;31mFAILURE[m [  9.127 s]
```
=> python-version: Use default to system provided version

api/src/org/apache/cloudstack/api/response/ClusterResponse.java
This removes username and passwords details from the listClusters
response. The details are usually seen in VMware environments only.
With dynamic roles features, the listClusters API may be provided
to a read-only root-admin user role/type which should not be able to get
the credentials.
/cc @borisstoyanov @PaulAngus
=> [4.9+] CLOUDSTACK-9983: Hide credentials in listClusters response

systemvm/patches/debian/config/opt/cloud/bin/configure.py, systemvm/patches/debian/config/opt/cloud/bin/cs/CsAddress.py, systemvm/patches/debian/config/opt/cloud/bin/cs/CsRoute.py
This enables the firewall/mangle tables rules to ACCEPT instead of RETURN, which
is the same behaviour as observed in ACS 4.5. By accepting the traffic, guest
VMs will be able to communicate tcp traffic between each other over snat public
IPs.
This is a regression from ACS 4.5, observed in ACS 4.9.2.0.
Pinging for review - @PaulAngus @borisstoyanov @DagSonsteboSB @abhinandanprateek @DaanHoogland and others
=> [4.9+][network blocker] CLOUDSTACK-9838: Allow ingress traffic between guest VMs via snat IPs

packaging/centos63/cloud.spec, packaging/centos7/cloud.spec
$1 is "2" during package upgrade in %post section, this fixes the
handling of $1 as per https://fedoraproject.org/wiki/Packaging:Scriptlets
This improves handling of $1 during %post upgrade step. Some of the
command/code are idempotent such as enabling and starting a service
and can be run without any $1 checks.
Pinging for review - @wido @DaanHoogland @abhinandanprateek @DagSonstebo and others
=> packaging: Improve post-upgrade processing

plugins/storage/volume/solidfire/src/org/apache/cloudstack/storage/datastore/provider/SolidFireHostListener.java
This happens when you have a stopped VM which has a managed volume attached to it. The host that the VM was originally running on was removed. So, the `last_host_id` of the instance is set to a non-existing host which causes an NPE here. 
cc: @mike-tutkowski
=> [CLOUDSTACK-10008] Check for host before adding it to storagepaths

api/src/com/cloud/capacity/Capacity.java, api/src/org/apache/cloudstack/api/command/admin/resource/ListCapacityCmd.java, api/src/org/apache/cloudstack/api/response/CapacityResponse.java, engine/schema/src/com/cloud/capacity/CapacityVO.java, engine/schema/src/com/cloud/capacity/dao/CapacityDaoImpl.java, server/src/com/cloud/api/ApiResponseHelper.java, server/src/com/cloud/capacity/CapacityManagerImpl.java, server/src/com/cloud/server/ManagementServerImpl.java, ui/scripts/dashboard.js, ui/scripts/sharedFunctions.js, ui/scripts/ui-custom/zoneChart.js
This commit contains following changes
(1) add CPU CORE information in op_host_capacity
(2) add capacity name in the CapacityResponse
(3) add allocatedCapacity for CPU/MEMORY/CPU CORE for zones
(4) sort CapacityResponse by zonename and CapacityType
=> CLOUDSTACK-9997: Add cpu cores information in CapacityResponse

framework/quota/test/org/apache/cloudstack/quota/QuotaAlertManagerImplTest.java
Replace the use of joda with Calendar, set explicitly to UTC when
doing date manipulation.
This fixes an issue where when running this test on a machine set to a local timezone that is about to switch to DST, the difference returns 0 versus 1.
=> CLOUDSTACK-9830 Fix DST bug in QuotaAlertManagerTest

server/src/com/cloud/network/router/VpcVirtualNetworkApplianceManagerImpl.java
The "start" method of VirtualNetworkApplianceManagerImpl schedules several period checks, including stats updates, alert updates, and VR checks including S2S vpn checks.
VpcVirtualNetworkApplianceManagerImpl extends VirtualNetworkApplianceManagerImpl. Thus when VpcVirtualNetworkApplianceManagerImpl is used, it re-runs the "start" method and once again schedules all the various jobs. Thus all the jobs run twice at each scheduled run. This is easily seen in the mangement-server.log (this is one of the checks that is doubled-up):
`cat /var/log/cloudstack/management/management-server.log | grep "routers to update status"`
Before (runs twice every 30 seconds):
```
2017-04-10 21:48:12,879 DEBUG [c.c.n.r.VirtualNetworkApplianceManagerImpl] (RouterStatusMonitor-1:ctx-5f7bc584) (logid:4d5b1031) …
```
=> CLOUDSTACK-9873: VR related periodic jobs are scheduled twice and run twice on management servers

systemvm/patches/debian/config/opt/cloud/bin/checkbatchs2svpn.sh
The checkbatchs2svpn.sh VR script returns ("via echo") that status of each requested S2S VPN check one-at-a-time.  If there is even a slight delay between VPN checks, the sshExecutor stops monitoring stdout and assumes it has all of the output.
When checking the management server logs, we see a request to check _X_ number of VPNs, but the response is occasionally less than _X_ number... The rest of the Cloudstack code assumes "isConnected" as false if the VPN is not included in the response.
We've noticed that if an account had more than 3 site-to-site VPNs, that there are many errors per day stating that a S2S VPN is down.
This is exacerbated by Issue CLOUDSTACK-9873, because that issues causes the S2S VPN check (and many others) to run twice as often as intended.
I set this PR to 4.7, …
=> CLOUDSTACK-9872: Gather all S2S vpn statuses before outputting

server/src/com/cloud/server/ManagementServerImpl.java, server/src/com/cloud/user/AccountManagerImpl.java, server/test/com/cloud/user/AccountManagerImplTest.java, server/test/com/cloud/user/AccountManagetImplTestBase.java
We also allow ROOT Admin to remove remained ssh keypairs of removed account
=> [4.9] CLOUDSTACK-9136: remove ssh keypairs along with removing account

systemvm/patches/debian/config/opt/cloud/bin/configure.py
This fix is similar to the 4.10 fix found here: https://github.com/apache/cloudstack/pull/2062
**NOTE:** I have not tested this fix since I do not have a 4.9 environment.  We need confirmation from the people who raised the concern that this does in-fact fix their issue before this is merged.
@borisstoyanov can you run trillian tests against this please?
=> do not take down the VPN on public IP config changes

api/src/com/cloud/vm/UserVmService.java, api/src/com/cloud/vm/VmNetworkStats.java, core/src/com/cloud/agent/api/GetVmNetworkStatsAnswer.java, core/src/com/cloud/agent/api/GetVmNetworkStatsCommand.java, core/src/com/cloud/agent/api/VmNetworkStatsEntry.java, engine/orchestration/src/com/cloud/vm/VirtualMachineManagerImpl.java, plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java, plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtGetVmNetworkStatsCommandWrapper.java, plugins/hypervisors/vmware/src/com/cloud/hypervisor/vmware/resource/VmwareResource.java, plugins/hypervisors/xenserver/src/com/cloud/hypervisor/xenserver/resource/wrapper/xenbase/CitrixGetVmNetworkStatsCommandWrapper.java, server/src/com/cloud/api/ApiResponseHelper.java, server/src/com/cloud/configuration/Config.java, server/src/com/cloud/server/StatsCollector.java, server/src/com/cloud/storage/VolumeApiServiceImpl.java, server/src/com/cloud/vm/UserVmManager.java, server/src/com/cloud/vm/UserVmManagerImpl.java, setup/db/db/schema-480to481.sql
For now we can get network traffic statistics from virtual router for isolated network.
For nics on shared networks, we need to collect the traffic as well. 
It is useful for utility billing, especially for basic zone or advanced zone with security groups.
This supports KVM until now.
=> [4.10] CLOUDSTACK-7984: Collect network statistics for VMs on shared network (KVM implementation)

test/integration/smoke/test_deploy_vm_root_resize.py, tools/marvin/marvin/config/test_data.py
…ng attribute
Due to using default template and removing management restart 5 mins sleep current execution time has been reduced to 5mins
=== TestName: test_00_deploy_vm_root_resize | Status : SUCCESS ===
=== TestName: test_01_deploy_vm_root_resize | Status : SUCCESS ===
=== TestName: test_02_deploy_vm_root_resize | Status : SUCCESS ===
=> CLOUDSTACK-10009: fix test_data.py remove item "templateregister", and fix tests to use default template

test/integration/smoke/test_volumes.py
This is a test fix of the create_volume test. This test was failing was in Trillian.
=> CLOUDSTACK-9979 - Fix test_volumes.py test

api/src/org/apache/cloudstack/api/command/user/template/RegisterTemplateCmd.java
When an environment is upgraded to 4.10, then while registering template for a zone from cloudstack UI will fail if it is created in older version(before 3.x). 
This bug got introduced with the PR#1894 for CLOUDSTACK-9700. In this PR a new parameter ‘zoneIds’ was added to the registerTemplate api and is marked with the ‘since’ attribute as ‘4.10.0.0’. since attribute is suppose to provide version for the containing data, not about when parameter was introduced. Although the parameter was introduced in 4.10, but it can contain the information from earlier version, thus it is wrongly marked here as ‘4.10.0.0’.  
This issue occurs because zones from older version have UUID parameter value as Integer, whereas higher version zones have fixed format. So while fetching the ZoneIds for installing …
=> CLOUDSTACK-9981 : Regression occurs after upgrading to 4.10 while registering a template.

api/src/org/apache/cloudstack/api/response/TemplateResponse.java, server/src/com/cloud/api/query/dao/TemplateJoinDaoImpl.java, server/src/com/cloud/api/query/vo/TemplateJoinVO.java, setup/db/db/schema-41000to41100.sql
Introduce PhysicalSize as response in listTemplates API
=> CLOUDSTACK-9982: Introduce PhysicalSize as response in listTemplates API

plugins/metrics/src/org/apache/cloudstack/metrics/MetricsServiceImpl.java, plugins/metrics/src/org/apache/cloudstack/response/ClusterMetricsResponse.java, plugins/metrics/src/org/apache/cloudstack/response/HostMetricsResponse.java
Consider the CPU and memory overcommit ratios with total cpu/ram values
or thresholds for host and cluster metrics. This will fix incorrect
notification (cells turning yellow/red) in the metrics view.
Pinging for review - @borisstoyanov @DaanHoogland and others.
=> CLOUDSTACK-9986: Consider overcommit ratios with total/threshold values

server/src/org/apache/cloudstack/acl/RoleManagerImpl.java
This allows admins to create roles with names of previously deleted
roles.
- Create a role with a name
- Delete the role
- Create a new role with the same name, you'll hit error.
=> CLOUDSTACK-9985: Allow creation of roles with names of deleted roles

scripts/vm/network/security_group.py
ip6tables no longer takes '--icmpv6-type any' as a argument.
To allow all ICMPv6 traffic with ip6tables it has to be invoked this way:
$ ip6tables -I i-2-14-VM -p icmpv6 -s ::/0 -j ACCEPT
All ICMPv6 traffic is now allow into the Instance.
=> ipv6: Allow all ICMPv6 traffic if -1 is provided as a ICMP type

test/integration/component/test_accounts.py
…_same_account: remove secret key checks since it was removed from the API response
Removing secret key as it's not part of the api response any more. The changed test is passing:
Ping @rhtyd @DaanHoogland @PaulAngus @jayapalu for review
=> CLOUDSTACK-10014: Fix test accounts remove secret key check

server/src/com/cloud/api/query/dao/DataCenterJoinDaoImpl.java
Currently any user with an access to the API can read the full capacities but that information should not be disclosed to normal user.
=> [CLOUDSTACK-9910] API: display zone capacity data only to admin

services/console-proxy/server/src/com/cloud/consoleproxy/ConsoleProxySecureServerFactoryImpl.java, systemvm/scripts/_run.sh, utils/src/main/java/org/apache/cloudstack/utils/security/SSLUtils.java, utils/src/test/java/com/cloud/utils/security/SSLUtilsTest.java
Current SSL protocol and ciphers used in SystemVMs are not the recommended. One can verify this with tests such as the one from SSL Labs (https://www.ssllabs.com/ssltest/). The grade was capped to C because of SSL ciphers and protocol. The grade was capped to B because it was allowed to use Diffie-Hellman keys with size lesser than 2048 bits. This commit changes the grade from C to A-.
The following image shows the test result before any changes.
After including the changes from this commit the test result was A-.
=> CLOUDSTACK-9977: Enhance SSL protocol used by Console Proxy

api/src/org/apache/cloudstack/api/command/user/address/AssociateIPAddrCmd.java
Going through the code & implementation, it seems like either of the parameters are not required while accessing the API : associateIpAddress.
There are 3 cases for which this api works. 1) networkId 2) vpcId 3) zoneId. Either of these can be provided to achieve the same functionality. If neither of them is provided, there is an error text shown.
E.g.
[root@CCP ~]# curl -s 'http://10.66.43.37:8096/client/api?command=associateIpAddress&listall=true' | xmllint --format - -o
```
<?xml version="1.0" encoding="UTF-8"?>
<associateipaddressresponse cloud-stack-version="4.5.1.0">
<errorcode>431</errorcode>
<cserrorcode>4350</cserrorcode>
<errortext>Unable to figure out zone to assign ip to. Please specify either zoneId, or networkId, or vpcId in the call</errortext>
</associateipaddressresponse> …
```
=> CLOUDSTACK-9786:API reference guide entry for associateIpAddress needs additional information

systemvm/js/ajaxviewer.js
Mozilla Firefox displays white tile in place of cursor. The reason - function isImageLoaded() always returns true after first load and function checkUpdate() reloads too fast. 
Suggested fix - in refresh() method state imageLoaded should be reverted to false. This ensures that function checkUpdate() processes only when tile image is loaded.
=> Fix ajaxviewer.js to solve console on Firefox

api/src/org/apache/cloudstack/api/response/StoragePoolResponse.java, server/src/com/cloud/api/query/dao/StoragePoolJoinDaoImpl.java
It would be useful if we return the provider name in the list storage pools response. This will be useful for example to identify different storages that are in use and their scope.
=> [CLOUDSTACK-10015] Return storage provider with response to list storage pools

systemvm/patches/debian/config/etc/vpcdnsmasq.conf
When enabling remote access VPN, a new interface is created upon client connecting via VPN. The DNS service (dnsmasq) is set only to listen on interfaces that are active when it starts. Thus VPN users are provided the VR's IP address for DNS resolution, but it is not actually listening for DNS requests.
=> CLOUDSTACK-10016: VPC VR doesn't respond to DNS requests from remote access vpn clients

api/src/org/apache/cloudstack/api/command/user/affinitygroup/UpdateVMAffinityGroupCmd.java, test/integration/component/test_affinity_groups.py
Return an exception if both parameter are missing.
This fix an NPE in AffinityGroupServiceImpl.updateVMAffinityGroups() when the list was null.
=> CLOUDSTACK-9631: API: affinitygroupids or affinitygroupnames must be given

plugins/network-elements/nuage-vsp/src/com/cloud/network/guru/NuageVspGuestNetworkGuru.java, plugins/network-elements/nuage-vsp/src/com/cloud/util/NuageVspEntityBuilder.java, plugins/network-elements/nuage-vsp/test/com/cloud/util/NuageVspEntityBuilderTest.java
Public IP state wasn't passed to the vsp client, making it ignore the apply public ip.
Bugfix-for: 4.9
Bug-ID: CLOUDSTACK-9751
Reported-By: Raf Smeets <raf.smeets@nuagenetworks.net>
=> [4.9] CLOUDSTACK-9751: Fix public ip not applied, when added while VR is starting

plugins/api/solidfire-intg-test/src/org/apache/cloudstack/solidfire/SolidFireIntegrationTestManagerImpl.java, plugins/api/solidfire-intg-test/src/org/apache/cloudstack/util/solidfire/SolidFireIntegrationTestUtil.java
Guard from cases where we pass an invalid `accountID` or `storagePoolID` in the API.
CC: @mike-tutkowski
=> Add NULL checks for various objects in SolidFire integration test API

api/src/org/apache/cloudstack/api/command/admin/account/CreateAccountCmd.java
This PR provide fix for the issue: 
Account name is giving null in event tab after successful creation of account. 
Earlier AccountName was used for populating event description. Replaced with UserName for constructing event description.
=> CLOUDSTACK-9990 : Account name is giving null in event tab after successful creation of account

server/src/com/cloud/configuration/ConfigurationManagerImpl.java
Unable to create service offering with networkrate=0(Unlimited network throttling) with an error "Failed to create service offering xxxxxxx: specify the network rate value more than 0".
=> CLOUDSTACK-9954 Unable to create service offering with networkrate=0

server/src/com/cloud/storage/listener/SnapshotStateListener.java
Include the timezone in datetime format of snapshot events, to be consistent with every other events.
"eventDateTime" was added by @chipchilders in commit 14ee684ce3 and was updated the same day to add the timezone (commit bf967eb622f) except for Snapshots.
=> [CLOUDSTACK-9840] Fix datetime format of snapshots events

server/src/com/cloud/api/ApiResponseHelper.java
There is no cpuspeed, cpunumber or memory details in the listUsageRecords output as documented
In DB (cloud_usage table) we have cpu_speed, cpu_cores and ram fileds, but these are not populated for all the VM's. These fields are only populated for the VM's which are deployed with custom service offerings.
=> CLOUDSTACK-9950:listUsageRecords doesnt return required fields

framework/quota/src/org/apache/cloudstack/quota/constant/QuotaTypes.java
The quota memory tariff description in the CloudStack UI is wrong when defines that the value is for "using 1MB or RAM for 1 hour". The quota currency values reflect the value of a resource used per month, not an hour.
Quota divides the tariff value by the number of hours a month has (30 days - 720 hours); then it calculates the credits used by a client based on the amount of resources used per hour. The memory tariff description in the interface is wrong and can guide users to configure values for an hour.
=> CLOUDSTACK-9925: Quota memory tariff value is for 1MB of RAM used per month (not hour)

scripts/vm/hypervisor/xenserver/logrotate, scripts/vm/hypervisor/xenserver/setupxenserver.sh, scripts/vm/hypervisor/xenserver/xenserver60/patch, scripts/vm/hypervisor/xenserver/xenserver62/patch, scripts/vm/hypervisor/xenserver/xenserver65/patch
After integrating XS with CCP the following folder gets created: /var/log/cloud/ however the logs in that are not rotated resulting in root file system fill up. It was a known issue and link http://support.citrix.com/article/CTX138064 describes the issue and solution. Used the article and added corresponding changes to Cloudstack.
=> CLOUDSTACK-8906: /var/log/cloud/ doesn't get logrotated on xenserver

api/src/org/apache/cloudstack/api/command/admin/outofbandmanagement/ChangeOutOfBandManagementPasswordCmd.java, api/src/org/apache/cloudstack/api/command/admin/outofbandmanagement/ConfigureOutOfBandManagementCmd.java, api/src/org/apache/cloudstack/api/command/admin/outofbandmanagement/IssueOutOfBandManagementPowerActionCmd.java, api/src/org/apache/cloudstack/outofbandmanagement/OutOfBandManagementService.java, api/src/org/apache/cloudstack/poll/BackgroundPollManager.java, api/src/org/apache/cloudstack/poll/BackgroundPollTask.java, developer/developer-prefill.sql, engine/orchestration/src/com/cloud/agent/manager/ClusteredAgentManagerImpl.java, engine/schema/src/org/apache/cloudstack/outofbandmanagement/dao/OutOfBandManagementDaoImpl.java, server/resources/META-INF/cloudstack/core/spring-server-core-managers-context.xml, server/src/com/cloud/server/StatsCollector.java, server/src/org/apache/cloudstack/outofbandmanagement/OutOfBandManagementServiceImpl.java, server/src/org/apache/cloudstack/outofbandmanagement/PowerOperationTask.java, server/src/org/apache/cloudstack/poll/BackgroundPollManagerImpl.java, server/test/org/apache/cloudstack/poll/BackgroundPollManagerImplTest.java, setup/dev/advanced.cfg, test/integration/smoke/test_outofbandmanagement.py
CloudStack has several background polling tasks that are spread across
the codebase, the aim of this work is to provide a single manager to
handle submission, execution and handling of background tasks. With
the framework implemented, existing oobm background task has been
refactored to use this manager.
The work has been split from a bigger host-ha pr: https://github.com/apache/cloudstack/pull/1960
=> CLOUDSTACK-9782: New Background Polling Task Manager

systemvm/patches/debian/config/etc/init.d/cloud-early-config, systemvm/patches/debian/config/opt/cloud/bin/passwd_server_ip
Fix cloud-password-srvr correctly.
Made sure it runs on VPC VR, but not on Internal LB
=> CLOUDSTACK-9749: Disable password service on ilb systemvm

systemvm/patches/debian/config/opt/cloud/bin/configure.py
After a vRouter is recreated  (e.g. reboot via CloudStack UI) and Remote Access VPN enabled, VPN won't work anymore. Here is the abbreviated output of "ipsec auto -status" while we were having the issue:
```
root@r-10-VM:~# ipsec auto --status
000 using kernel interface: netkey
000 interface lo/lo 127.0.0.1
000 interface lo/lo 127.0.0.1
000 interface eth0/eth0 169.254.1.45
000 interface eth0/eth0 169.254.1.45
000 %myid = (none)
```
After this commit, the following occurs and VPNs work:
```
root@r-10-VM:~# ipsec auto --status
000 using kernel interface: netkey
000 interface lo/lo 127.0.0.1
000 interface lo/lo 127.0.0.1
000 interface eth0/eth0 169.254.1.45
000 interface eth0/eth0 169.254.1.45
000 interface eth1/eth1 xxx.xxx.xxx.172
000 interface eth1/eth1 xxx.xxx.xxx.172
000 interface …
```
=> CLOUDSTACK-9801: IPSec VPN does not work after vRouter reboot or recreate

server/src/com/cloud/api/query/QueryManagerImpl.java
ISSUE
============
Featured Templates/Iso's created by Root/admin user are not visible to Domain Admin users.
STEPS TO REPRODUCE
Mark a template as featured and try to view it from a domain admin user
The issue occurs for both templates and iso's registered before and after upgrade
Templates,ISO's whose owner is ROOT admin, public: Yes, featured: Yes
Log in to UI (as a domain admin, such as an admin of “TEST/TEST1” domain)
Choose “Templates”.
Error message will be shown on UI
=> CLOUDSTACK-9955 : Featured Templates/Iso's created by Root/admin user are not visible to Domain Admin users

debian/control, plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/storage/LibvirtStorageAdaptor.java
Since libvirt 1.2.2 libvirt will properly create volumes
using RBD format 2.
We can use libvirt to creates the volumes which strips a bit of
code from the CloudStack Agent's responsbility.
RBD format 2 is already used by all volumes created by CloudStack.
This format is the most recent format of RBD and is still actively
being developed.
This removes the support for Ubuntu 12.04 as that does not have the
proper libvirt version available.
=> rbd: Use libvirt to create new volumes and not rados-java

engine/components-api/src/com/cloud/vm/snapshot/VMSnapshotManager.java, server/src/com/cloud/storage/snapshot/SnapshotManager.java, server/src/com/cloud/storage/snapshot/SnapshotSchedulerImpl.java, server/src/com/cloud/vm/snapshot/VMSnapshotManagerImpl.java
Default value of the account level global config vmsnapshot.expire.interval is -1 that conforms to legacy behaviour
A positive value will expire the VM snapshots for the respective account in that many hours
=> CLOUDSTACK-9861: Expire VM snapshots after configured duration

ui/scripts/network.js
A simple if-statement would fail if either the type or code were 0
as that if-statement failed them.
By checking if they are defined and casting them to a String afterwards
this makes the if-statement properly resolve and show the rule as it should.
=> CLOUDSTACK-10042: Properly show ICMP SecGroup Rules

engine/components-api/src/com/cloud/configuration/ConfigurationManager.java, engine/schema/src/com/cloud/domain/DomainVO.java, server/src/com/cloud/configuration/ConfigurationManagerImpl.java, server/src/com/cloud/user/DomainManagerImpl.java, server/test/com/cloud/user/DomainManagerImplTest.java, server/test/com/cloud/vpc/MockConfigurationManagerImpl.java
We are able to assign didacated vlan ip ranges after the merge of CLOUDSTACK-8958.
These ip ranges need to be released automatically when we delete a domain.
=> [4.9] CLOUDSTACK-8958: release dedicated ip range in domain removal

systemvm/patches/debian/config/opt/cloud/bin/merge.py
In the VR, deviceid of eth1X should be 1X (eth10->10, eth11->11), not 1.
=> CLOUDSTACK-9999: vpc tiers do not work if vpc has more than 8 tiers

engine/schema/src/com/cloud/host/dao/HostDaoImpl.java
ISSUE
============
Failed to change cluster to managed state.
STEPS TO REPRODUCE
1. Create an environment having zone with 2 Clusters and atleast 1 host associated with each cluster.
2. Verify that all clusters are in managed state and all hosts are in up state.
3. Change the value of global setting "direct.agent.load.size" to 1.
4. Restart management server.
5. Check "id" of both clusters.
6. Change state of both the clusters to Unmanaged state.
7. Try to change the cluster which has higher "id" to managed state. Cluster will come to manage state.
8. But host associated with it will never come to UP state, till the time cluster with lower "id" is changed to manage state.
**Screenshot of DB before applying fix :**
**Screenshot of DB after applying fix :**
=> CLOUDSTACK-9992 : Failed to change cluster to managed state

server/src/com/cloud/api/ApiServer.java
=> [CLOUDSTACK-9773] API: don't break API output with non-printable characters

framework/jobs/src/org/apache/cloudstack/framework/jobs/impl/AsyncJobManagerImpl.java
This PR provides solution for the Bug : Volumes stuck in Creating state while restarting the Management Server when the volume creation is in progress
=> CLOUDSTACK-9939 : Volumes stuck in Creating state while restarting the Management Server when the volume creation is in progress

server/src/com/cloud/vm/UserVmManagerImpl.java
When VM is assigned to another account , snapshots related to VM were deleted(soft delete) in db but not in physical storage.It will be no use of the untracked files in file storage if the snapshot is deleted in cloud stack db. 
This PR provide solution for removing the snapshot permanently in db as well as from storage whenever a VM is assigned to another user.
=> CLOUDSTACK-9964 : Snapahots are not getting deleted properly, if VM is assigned to another user

engine/orchestration/src/com/cloud/vm/VirtualMachineManagerImpl.java
This is a specific case when vm state gets updated by the vmsync before it can be updated by the api-job-executor thread. 
I could see following logs. 
```
2015-10-28 02:03:21,590 DEBUG [jobs.impl.AsyncJobManagerImpl] (API-Job-Executor-5:ctx-5fe7b795 job-3056226 ctx-49b11835) Sync job-3056236 execution on object VmWorkJobQueue.845336
2015-10-28 02:03:23,563 DEBUG [vm.dao.VMInstanceDaoImpl] (API-Job-Executor-5:ctx-5fe7b795 job-3056226 ctx-49b11835) Unable to update VM[User|i-3702-845336-VM]: DB Data={Host=null; State=Stopped; updated=6; time=Wed Oct 28 02:03:23 PDT 2015} New Data: {Host=null; State=Destroyed; updated=6; time=Wed Oct 28 02:03:23 PDT 2015} Stale Data: {Host=null; State=Stopped; updated=5; time=Wed Oct 28 02:03:18 PDT 2015}
```
I don't see any other traces of sync job queued …
=> Bug-ID: CLOUDSTACK-9734 Destroy VM Fails sometimes

engine/schema/src/com/cloud/vm/dao/NicDao.java, engine/schema/src/com/cloud/vm/dao/NicDaoImpl.java, plugins/hypervisors/vmware/src/com/cloud/hypervisor/guru/VMwareGuru.java, plugins/hypervisors/vmware/src/com/cloud/hypervisor/vmware/resource/VmwareResource.java, plugins/hypervisors/vmware/test/com/cloud/hypervisor/vmware/resource/VmwareResourceTest.java
Problem:
[VMware] RVRs have mismatching MAC addresses for extra public NICs.
Root Cause:
MAC addresses for extra public NICs were assigned randomly for the routers. Network Orchestrator is unaware of the extra NICs info of the peer router as they are not persisted in the cloud database and so peer router MAC addresses info is not at all considered in case of RVR when assigning MAC addresses for extra public NICs.
Solution:
When RVR is enabled and Peer Router is available, get the MAC addresses of the extra public NICs from the Peer Router and set them to the router.
=> CLOUDSTACK-9717: [VMware] RVRs have mismatching MAC addresses for extra public NICs.

systemvm/patches/debian/config/opt/cloud/bin/configure.py
If a public IP is assigned to a VPC, a VM running inside that VPC cannot ping that public IP. This is due to the IPtables Nat rules set in such a way that drop any requests to the public IP from internal interfaces. I am fixing this so that internal hosts can also reach the public IP.
Reproduction:
Create a VPC
Create a network inside the VPC
Allocate a public IP
Create a VM in the network
Create a port forwarding rule enabling ICMP
ping the public IP inside the VM (this will fail)
=> [CLOUDSTACK-10030] - Make publicips reachable inside VPC

api/src/org/apache/cloudstack/api/command/admin/domain/CreateDomainCmd.java, api/src/org/apache/cloudstack/api/command/admin/domain/DeleteDomainCmd.java, ui/scripts/domains.js
This change allows a domain admin to create and delete subdomains; the domain admin cannot delete its own domain.
To do that, two files have been changed:
(i) _schema-41000to41100.sql:_ two rows were added in table _role_permissions_, allowing the Domain Admin role (id: 3) to execute API commands 'createDomain' and 'deleteDomain';
(ii) _domains.js:_ enable buttons for creating and deleting domain in the CloudStack UI.
=> CLOUDSTACK-10022: Allow domain admin to create and delete subdomains

engine/schema/src/com/cloud/upgrade/dao/Upgrade481to490.java, server/src/org/apache/cloudstack/acl/RoleManagerImpl.java, utils/src/main/java/com/cloud/utils/PropertiesUtil.java
This fixes issue of enabling dynamic roles based on the global setting
only. This also fixes application of the default role/permissions mapping
on upgrade from 4.8 and previous versions to 4.9+.
Previously, it would make additional check to ensure commands.properties
is not in the classpath however this creates confusion for admins who
may skip/skim through the rn/docs and assume that mere changing the
global settings was not enough.
Pinging for review @PaulAngus @nvazquez @borisstoyanov @wido @pdion891 and others
=> CLOUDSTACK-10052: Simplify dynamic roles enable checking [upgrade-bug]

engine/schema/src/com/cloud/network/dao/NetworkVO.java, server/src/com/cloud/network/NetworkServiceImpl.java
Reproduction Steps:
Create a network with redundant router capability.
Create instances with the above network.
Update the network to Default Offering(DefaultIsolatedNetworkOfferingWithSourceNAT).
After successful update, one router is created which is as expected.
Try to restart the network with cleanup=true.
Observation:
=========
Two routers are created with redundant state UNKNOWN.
Note: - The similar behavior is seen when we update RVR to default.
Expectation:
=========
After successful restart, only one router should be created.
FS:
==
https://cwiki.apache.org/confluence/display/CLOUDSTACK/Persistent+Configuration+for+Virtual+Routers
Resolution:
========
The setter name is different from what it should be used by update call.
JIRA Ticket:
========= …
=> CLOUDSTACK-10002: Restart network with cleanup spawns Redundant Routers(In Default Network Offering)

setup/db/db/schema-41000to41100-cleanup.sql
**Summary:** this commit alters column currency_value from table cloud_usage.quota_tariff to support values up to 5 decimal places. The current implementation allows up to 2 decimal places.
**Issue:** need to use more than 2 decimal places to define resources values in Quota tariff.
**Solution:** modify column currency_value from table cloud_usage.quota_tariff to support values up to 5 decimal places. Values with more than 5 decimal places will be displayed with scientific notation in the user interface.
**SQL command:** "ALTER TABLE cloud_usage.quota_tariff MODIFY currency_value DECIMAL(15,5) not null"
=> CLOUDSTACK-9914: update Quota plugin to support currency values up to 5 decimal places

tools/docker/supervisord.conf
the container sometimes doesn't come up as it timesout
=> increased jetty timeout

services/secondary-storage/server/src/org/apache/cloudstack/storage/resource/NfsSecondaryStorageResource.java
**ISSUE**
**This issue occurs only with KVM hypervisor**. Database entries for templates created from snapshots disappear after management-server service restart
**STEPS TO REPRODUCE**
1. Create a ACS setup and add KVM hypervisor as host.
2. Create snapshot of any disk (root or data disk) of an instance.
3. Create template using disk snapshot.
4. Verify that template got downloaded completely and is in Ready state.
5. Also, verify that entry for this template is present in template_store_ref table in database.
6. Now restart management server.
7. Once management server is restarted completely and web UI is available, check the template status. It will be in Active state instead of downloaded.
8. Also, entry for this template vanishes from template_store_ref table in database.
**Fix for …
=> CLOUDSTACK-10032 : Database entries for templates created from snapshots disappear after management-server service restart

api/src/com/cloud/network/rules/RulesService.java, api/src/org/apache/cloudstack/api/command/user/firewall/UpdatePortForwardingRuleCmd.java, server/src/com/cloud/network/rules/RulesManagerImpl.java, test/integration/smoke/test_portforwardingrules.py, tools/marvin/marvin/config/test_data.py, tools/marvin/marvin/lib/base.py
Configure a PF rule Private port : Start port ; 20 ENd POrt 25 || Public Port : Start port 20 ; ENd Port : 25.
Trigger UpdatePortForwardingRule api
ApI fails with following error : " Unable to update the private port of port forwarding rule as the rule has port range "
Solution-
Port range gets modified
=> CLOUDSTACK-9812:Update "updatePortForwardingRule" api to include additional parameter to update the end port in case of port range

ui/scripts/dashboard.js
Description:
=========
https://issues.apache.org/jira/browse/CLOUDSTACK-10059
Root Cause:
=========
The API returns the percentage value as floating point number but In UI it is converted to floor value of that number.
Hence for values less than 1%, the value is being converted to 0% and it doesn't show the value in the UI.
Solution:
=======
Removed the conversion, now it represents as it is(Floating point value).
Snapshots:
========
Before
After
=> CLOUDSTACK-10059: Dashboard ignores resource value that is less than 1%

plugins/hypervisors/xenserver/src/com/cloud/hypervisor/xenserver/resource/CitrixResourceBase.java, plugins/hypervisors/xenserver/src/com/cloud/hypervisor/xenserver/resource/wrapper/xenbase/CitrixCreateVMSnapshotCommandWrapper.java, plugins/hypervisors/xenserver/src/com/cloud/hypervisor/xenserver/resource/wrapper/xenbase/CitrixDeleteVMSnapshotCommandWrapper.java
Fixing the error  with snapshot size calculation  in a vm with memory
=> CLOUDSTACK-8939 VM Snapshot size with memory correctly calculated in cloud.usage_event (XenServer)

engine/storage/src/org/apache/cloudstack/storage/image/db/SnapshotDataStoreDaoImpl.java
Snapshots are not deleted resulting unexpected storage consumption in case of VMware.
**Steps to reproduce this issue :** 
1. In VMware setup, create a snapshot of volume say Snap1.
2. After successful creation of snapshot Snap1, create new snapshot of same volume say Snap2.snapshots
3. While Snap2 is in BackingUp state, delete Snap1.
4. Snap1 will disappear from Web UI, but when we check secondary storage, files associated with Snap1 still persists even after cleanup job is performed.
5. In snapshot_store_ref table in DB, Snap1 will be in ready state instead of Destroyed.
6. Also, in snapshots table, status of Snap1 will be Destroyed but removed column will be null and will never change to the date of snapshot removal.
**Fix for this issue :** 
1. In VMware, snapshot chain is not …
=> CLOUDSTACK-10004 : On deletion, Vmware volume snapshots are left behind with message 'the snapshot has child, can't delete it on the storage'

framework/config/src/org/apache/cloudstack/framework/config/ConfigKey.java, server/src/com/cloud/server/ManagementServerImpl.java
Issue Description:
=============
https://issues.apache.org/jira/browse/CLOUDSTACK-10058
Root Cause:
=========
Some global parameters contains NULL value, where the code doesn't handle NULL check.
So it fails with an exception. Hence nothing appears on the field(ERROR).
Solution:
=======
Added required NULL check.
Snapshots:
========
Before
After
=> CLOUDSTACK-10058: Error while opening the Settings tab in Secondary storage

tools/build/build_asf.sh
Per http://www.apache.org/dev/release-distribution#sigs-and-sums
This will add `.sha512` to the SHA 512 checksum file in the
release/candidate tarball.
Pinging for review @wido @swill @DaanHoogland @karuturi and others.
No trilian tests required, the changes are in build/release scripts.
=> CLOUDSTACK-10069: Add sha512 suffix to SHA 512 checksum

plugins/hypervisors/vmware/src/com/cloud/hypervisor/vmware/resource/VmwareResource.java, vmware-base/src/com/cloud/hypervisor/vmware/mo/VirtualMachineMO.java, vmware-base/test/com/cloud/hypervisor/vmware/mo/VirtualMachineMOTest.java
Created a VM with Windows8.1 template with root disk controller value as lsilogicsas.when migrating this VM to another host the root disk controller value is changing.
Repro steps:
Two clusters with one host each.
One Zone wide primary storage
1. Put one Host in Maintenance mode.
2. Register a windows template with rootdiskcontroller value as lsisas
3. Update the rootdiskcontroller values in database for vm_template_details to lsisas.
7. Deploy a VM from the above template.
8. Stop the VM
9. Cancel maintenance on the host and update in Db max guest limit to 2 under 'hypervisor capabilities' table.
10. Start the VM
11. see the VM settings and check root disk Controller value .
=> CLOUDSTACK-9963 Root Disk controller value is changing while migrating VM

server/src/com/cloud/network/vpn/Site2SiteVpnManagerImpl.java
When we have VPN customer gateway which is resolved by a hostname , we should be able to register the VPN customer gateway with its hostname instead of the IP address, this would be useful in case where the remote device IP is dynamically assigned , where customers use DDNS to resolve it.
=> CLOUDSTACK-8969 VPN customer gateway can't be registered with hostname

engine/schema/src/com/cloud/host/dao/HostDaoImpl.java, test/integration/component/test_host.py
Problem Statement
--------------------------
Hosts take time to reconnect after the restart of the management server.  Time goes up proportional to the value of  ping.interval*ping.timeout
Root Cause
-----------------
During the processing of Down event of management server, last ping time out gets reset. It is getting reset to a hardcoded 600 sec behind current time.  when ever the admin configures ping.interval, ping.timeout values such that  ping.interval*ping.timeout value crosses 600, the hosts misses the first few ping cycles creating this problem.
Solution
-----------
The hardcoded value of 600 is changed to make use of ping.interval*ping.timeout value
=> CLOUDSTACK-9886 : After restarting cloudstack-management , It takes time to connect hosts

services/secondary-storage/server/src/org/apache/cloudstack/storage/resource/NfsSecondaryStorageResource.java
template.properties file created after creating template from snapshot has hardcoded id = 1
id should have templateId
=> CLOUDSTACK-10019:template.properties has hardcoded id

api/src/com/cloud/network/Network.java, api/src/com/cloud/network/NetworkModel.java, api/src/com/cloud/vm/NicProfile.java, api/src/org/apache/cloudstack/api/ApiConstants.java, api/src/org/apache/cloudstack/api/command/user/vm/AddNicToVMCmd.java, api/src/org/apache/cloudstack/api/command/user/vm/DeployVMCmd.java, engine/schema/src/com/cloud/vm/dao/NicDao.java, engine/schema/src/com/cloud/vm/dao/NicDaoImpl.java, server/src/com/cloud/network/IpAddressManagerImpl.java, server/src/com/cloud/network/NetworkModelImpl.java, server/src/com/cloud/vm/UserVmManagerImpl.java, server/test/com/cloud/network/MockNetworkModelImpl.java, server/test/com/cloud/vpc/MockNetworkModelImpl.java, test/integration/smoke/test_nic.py, tools/marvin/marvin/lib/base.py, utils/src/main/java/com/cloud/utils/net/NetUtils.java, utils/src/test/java/com/cloud/utils/net/NetUtilsTest.java
Added ability to specify mac in deployVirtualMachine and
addNicToVirtualMachine api endpoints.
Validates mac address to be in the form of:
aa:bb:cc:dd:ee:ff , aa-bb-cc-dd-ee-ff , or aa.bb.cc.dd.ee.ff.
Ensures that mac address is a Unicast mac.
Ensures that the mac address is not already allocated for the
specified network.
=> CLOUDSTACK-9949 - add ability to specify mac address

setup/bindir/cloud-set-guest-sshkey-configdrive.in, setup/bindir/cloud-set-guest-sshkey.in
Fix a case where a user 'ro' or 'roo' exists on the system or other variants, like 'cen' and 'centos'.
If one sets user=roo, this will return two directories (/root /home/roo) and then it will fail.
Also, if user 'ro' or 'roo' does not exist, this will happily put the sshkey to the authorized_keys of the root account, which is not the intended place.
As another slightly less improbable example, if we have two users in our company named lars, then we could end up with lars's sshkey in larsb's authorized_keys.
The binary getent should be available on most Linux platforms, including ones using uClibc.
=> CLOUDSTACK-10067: Fix a case where a user 'ro' or 'roo' exists on the system

setup/db/db/schema-41000to41100.sql
This adds the missing global configuration parameter consoleproxy.sslEnable required for enabling SSL on the console proxy VM.
=> CLOUDSTACK-9902: add consoleproxy.sslEnable toggle

plugins/hypervisors/vmware/src/com/cloud/hypervisor/guru/VMwareGuru.java, plugins/hypervisors/vmware/src/com/cloud/hypervisor/vmware/manager/VmwareManager.java, plugins/hypervisors/vmware/src/com/cloud/hypervisor/vmware/manager/VmwareManagerImpl.java, plugins/hypervisors/vmware/src/com/cloud/hypervisor/vmware/manager/VmwareStorageManagerImpl.java, plugins/hypervisors/vmware/src/com/cloud/hypervisor/vmware/resource/VmwareResource.java, plugins/hypervisors/vmware/src/com/cloud/storage/resource/VmwareStorageLayoutHelper.java, plugins/hypervisors/vmware/src/com/cloud/storage/resource/VmwareStorageProcessor.java, vmware-base/src/com/cloud/hypervisor/vmware/mo/DatastoreMO.java, vmware-base/test/com/cloud/hypervisor/vmware/mo/DatastoreMOTest.java
if there are multiple files with the same name on vmware datastore, search operation may select any one file during volume related operations. This involves volume attach/detach, volume download, volume snapshot etc.
While using NetApp as the backup solution. This has .snapshot folder on the datastore and sometimes files from this folder gets selected during volume operations and the operation fails. Because of wrong selection of file following exception can be observed while volume deletion. 
2017-02-23 19:39:05,750 ERROR [c.c.s.r.VmwareStorageProcessor] (DirectAgent-304:ctx-a1dbf5d8 ac.local) delete volume failed due to Exception: java.lang.RuntimeException
Message: Cannot delete file [4cbcd46d44c53f5c8244c0aad26a97e1] .snapshot/hourly.2017-02-23_1605/r-97-VM/ROOT-97.vmdk
To fix this …
=> CLOUDSTACK-9956 File search on the vmware datastore may select wrong file if there are multiple files with same name.

engine/orchestration/src/com/cloud/vm/VirtualMachineManagerImpl.java, server/src/com/cloud/vm/UserVmManagerImpl.java
CLOUDSTACK-9182: Some running VMs turned off on manual migration when auto migration failed while host preparing for maintenance.
Fix: Block VMOperations if Host in PrepareForMaintenance mode. VM operations (Stop, Reboot, Destroy, Migrate to host) are not allowed when Host in PrepareForMaintenance mode.
=> CLOUDSTACK-9182: Some running VMs turned off on manual migration when auto migration failed while host preparing for maintenance.

agent/conf/agent.properties, plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java, plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/LibvirtDomainXMLParser.java, plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java, plugins/hypervisors/kvm/test/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java, plugins/hypervisors/kvm/test/com/cloud/hypervisor/kvm/resource/LibvirtDomainXMLParserTest.java, plugins/hypervisors/kvm/test/com/cloud/hypervisor/kvm/resource/LibvirtVMDefTest.java
The watchdog timer adds functionality where the Hypervisor can detect if an
instance has crashed or stopped functioning.
When the Instance has the 'watchdog' daemon running it will send heartbeats
to the /dev/watchdog device.
If these heartbeats are no longer received by the HV it will reset the Instance.
If the Instance never sends the heartbeats the HV does not take action. It only
takes action if it stops sending heartbeats.
This is supported since Libvirt 0.7.3 and can be defined in the XML format as
described in the docs: https://libvirt.org/formatdomain.html#elementsWatchdog
To the 'devices' section this will be added:
<watchdog model='i6300esb' action='reset'/>
In the agent.properties the action to be taken can be defined:
vm.watchdog.action=reset
The same goes for the model. The …
=> CLOUDSTACK-9397: Add Watchdog timer to KVM Instance

server/src/com/cloud/network/guru/DirectNetworkGuru.java, server/src/com/cloud/network/guru/DirectPodBasedNetworkGuru.java
This will prevent DirectNetworkGuru from designing and implementing a network it is not supposed to but, as discussed with @fmaximus, the  commit "remove hardcoded exemptions on directnetworkguru" will still allow it to implement a network if it supports one of the services from the offering so several gurus can still end up implementing a single network.
Solutions could include:
- only canHandle() if all required services are supported
- link a guru to a physical network and not ask for any guru if they canHandle()
- retrospecively check what guru implements the best set of services.
=> CLOUDSTACK-10007 Isolation method claim

agent/conf/agent.properties, plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
The PR introduces new cloudstack agent KVM property
host.overcommit.mem.mb
which allows increasing KVM host RAM more than physical RAM exists. It is necessary to utilize KSM and ZSwap features which extend RAM with deduplication and compression.
=> CLOUDSTACK-10073: KVM host RAM overprovisioning

ui/scripts/instances.js
Fix for CLOUDSTACK-10099, which concerns the GUI not invoking the migrateVirtualMachineWithVolume API command when it should.
=> CLOUDSTACK-10099

.travis.yml
This rearranges a project related component test that is likely failing (in Travis) due
to env/state changes by other project related tests groupped in the
same job.
Pinging for review - @GabrielBrascher @DaanHoogland @nvazquez @borisstoyanov and others
=> CLOUDSTACK-9584: Re-arrange failing project_limits test
