apache/cloudstack

api/src/com/cloud/network/VirtualNetworkApplianceService.java, engine/api/src/org/apache/cloudstack/engine/orchestration/service/NetworkOrchestrationService.java, engine/orchestration/src/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java, plugins/hypervisors/simulator/src/com/cloud/agent/manager/MockVmManagerImpl.java, server/src/com/cloud/api/query/dao/DomainRouterJoinDaoImpl.java, server/src/com/cloud/network/router/NetworkHelperImpl.java
move is complete. testing isn't and is invited as not all possible use-cases are clear yet
=> CLOUDSTACK-8197 create MinVRVersion config item

packaging/fedora20/cloud-agent.rc, packaging/fedora20/cloud-ipallocator.rc, packaging/fedora20/cloud-management.rc, packaging/fedora20/cloud-management.sysconfig, packaging/fedora20/cloud-usage.rc, packaging/fedora20/cloud.spec, packaging/fedora20/cloudstack-agent.te, packaging/fedora20/cloudstack-sccs, packaging/fedora20/replace.properties, packaging/fedora20/tomcat.sh, packaging/fedora21/cloud-agent.rc, packaging/fedora21/cloud-ipallocator.rc, packaging/fedora21/cloud-management.rc, packaging/fedora21/cloud-management.sysconfig, packaging/fedora21/cloud-usage.rc, packaging/fedora21/cloud.spec, packaging/fedora21/cloudstack-agent.te, packaging/fedora21/cloudstack-sccs, packaging/fedora21/replace.properties, packaging/fedora21/tomcat.sh, packaging/package.sh
Basic packaging for Fedora 20 and Fedora 21
The agent works, the management is not yet functional
=> Cloudstack 8210

core/src/com/cloud/agent/api/routing/SetFirewallRulesCommand.java, core/test/com/cloud/agent/resource/virtualnetwork/VirtualRoutingResourceTest.java
Fixes for [CLOUDSTACK-8279](https://issues.apache.org/jira/browse/CLOUDSTACK-8279) and two minor cleanups
=> Cloudstack 8279

plugins/network-elements/nicira-nvp/test/com/cloud/network/nicira/NiciraNvpApiTest.java
The test testFindSecurityProfileByUuid built an assumptio on the order of the arguments after transforming through a HashMap.
Signed-off-by: Laszlo Hornyak <laszlo.hornyak@gmail.com>
=> CLOUDSTACK-8294: fix for java 1.8 build

plugins/hypervisors/kvm/test/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java
Refactored to use the XPath expressions to check the generated domain xml rathern than string comparison.
Signed-off-by: Laszlo Hornyak <laszlo.hornyak@gmail.com>
=> CLOUDSTACK-8292: fix for java 1.8 build

engine/storage/src/org/apache/cloudstack/storage/image/db/VolumeDataStoreDaoImpl.java
When we download volume then we create entry in volume_store_ref table.
We mark the volume entry to ready state once download_url gets generated.
When we migrate that volume, then again one more entry is created with same volume id.
Its state is marked as allocated. Later we try to list only one dataobject in datastore
for state transition during volume migration. If the listed volume's state is allocated
then migration passes otherwise it fails.
Below fix will remove the randomness and give priority to volume entry which is made for
migration (download_url/extracturl will be null in case of migration). Giving priority to
download volume case is not needed as there will be only one entry in that case so no randomness.
=> CLOUDSTACK-6900: This fixes volume migration failing after that volume is downloaded

test/integration/component/test_accounts.py, test/integration/component/test_blocker_bugs.py, test/integration/component/test_multiple_ips_per_nic.py, test/integration/component/test_vpc.py, test/integration/component/test_vpc_network.py, test/integration/component/test_vpc_vm_life_cycle.py, test/integration/smoke/test_network.py, test/integration/smoke/test_routers.py
Tagging test case with "dvs" tag which should be run with Vmware DVS configuration.
=> CLOUDSTACK-8330: Tagging test cases which should be run with vmware dvs configuration

tools/marvin/marvin/lib/vcenter.py, tools/marvin/setup.py
https://issues.apache.org/jira/browse/CLOUDSTACK-8352
=> Vcenter marvin library 

CONTRIBUTING.md
Added instructions for how contributors should submit code changes via GitHub Pull Requests.
=> Added the CONTRIBUTING.md doc to the project root

services/secondary-storage/server/src/org/apache/cloudstack/storage/resource/HttpUploadServerHandler.java, services/secondary-storage/server/src/org/apache/cloudstack/storage/resource/NfsSecondaryStorageResource.java, utils/src/com/cloud/utils/EncryptionUtil.java
HttpUploadServerHandler.java:142, DM_BOXED_PRIMITIVE_FOR_PARSING
NfsSecondaryStorageResource.java:2630, DM_BOXED_PRIMITIVE_FOR_PARSING
NfsSecondaryStorageResource.java:2775, DM_DEFAULT_ENCODING
EncryptionUtil.java:59, DM_DEFAULT_ENCODING
=> Fixed a few findbugs issues after the merge 0b83559

systemvm/patches/debian/config/opt/cloud/bin/configure.py
Fixes a missing iptables rule that would prevent port forwarding from working.
Tested against (with hardware) smoke tests.
=> Allow forward to fix port forwarding rules

systemvm/patches/debian/config/opt/cloud/bin/configure.py
Fixes up a bunch of pep8 failure (trying to get rid of some jenkins failures)
Also the first steps to a unit testing framework for the python code in the systemvm
=> Pep8 and some unit tests

ui/scripts/accounts.js, ui/scripts/configuration.js, ui/scripts/docs.js, ui/scripts/network.js, ui/scripts/storage.js, ui/scripts/system.js, ui/scripts/templates.js, ui/scripts/ui-custom/instanceWizard.js, ui/scripts/ui-custom/login.js, ui/scripts/zoneWizard.js
All of them are trailing comma in array or object
more details @
https://analysis.apache.org/component_issues?id=org.apache.cloudstack%3Acloudstack#resolved=false|severities=BLOCKER|languages=js
=> Fixed blocker issues reported by sonarqube in js files

server/src/com/cloud/configuration/ConfigurationManagerImpl.java, utils/src/com/cloud/utils/net/NetUtils.java, utils/test/com/cloud/utils/net/NetUtilsTest.java
Hi @bhaisaab and @DaanHoogland
Could you please have a look at this PR and also at the RFC 3021?
It allows us to have something like this:
// RFC 3021 - 31-Bit Prefixes on IPv4 Point-to-Point Links
//     GW              Netmask         Stat IP        End IP
// 192.168.24.0 - 255.255.255.254 - 192.168.24.0 - 192.168.24.1
// https://tools.ietf.org/html/rfc3021
Email thread: https://www.mail-archive.com/dev@cloudstack.apache.org/msg45035.html
Manual tests:
I created the following public networks successfully:
GW                 - Netmask             - Start IP          - End IP
192.168.24.0 - 255.255.255.254 - 192.168.24.0 - 192.168.24.1
192.168.10.0 - 255.255.255.254 - 192.168.10.0 - 192.168.10.1
Automated tests:
Environments:
Centos7 + KVM + Qemu
MySQL/MariaDB 5.5.41
Management Server …
=> CLOUDSTACK-8506 - Make ACS compliant with the RFC 3021

test/integration/component/test_stopped_vm.py
Tested
Test Deploy Virtual Machine with startVM=true parameter ... === TestName: test_02_deploy_vm_startvm_true | Status : SUCCESS ===
ok
Test Deploy Virtual Machine with startVM=false and attach volume already attached to different machine ... === TestName: test_08_deploy_attached_volume | Status : SUCCESS ===
ok
Test Deploy Virtual Machine with startVM=false & enabledpassword in ... === TestName: test_deploy_vm_password_enabled | Status : SUCCESS ===
ok
=> CLOUDSTACK-8583 :fixing issue related to script test_stopped_vm

utils/test/com/cloud/utils/TestProfiler.java
a lot of validation pull requests are failing over this test. It should pass but it's failure is environmental in any observed case so far.
=> unittesting: test resolution is not guaranteed to be exact

server/src/org/apache/cloudstack/region/RegionsApiUtil.java
Resource leak fixed. Please review.
=> Coverity Issue: Resource Leak fixed

engine/schema/src/com/cloud/upgrade/dao/Upgrade410to420.java, engine/schema/src/com/cloud/upgrade/dao/Upgrade420to421.java, engine/schema/src/com/cloud/upgrade/dao/Upgrade450to451.java
Assorted try-with-resource solutions to resource leaks.
=> coverity: bring down all high impact issue in upgrade code, so we can trigger on this while reviewing

engine/schema/src/com/cloud/upgrade/dao/Upgrade218to22.java
a lot of issues in this file so doing some iterations on it.
some unused, lot of resource leakage.
=> coverity issues in old upgrade code

server/src/com/cloud/storage/VolumeApiServiceImpl.java
This PR addresses https://issues.apache.org/jira/browse/CLOUDSTACK-8698.
=> CLOUDSTACK-8698: Retrieve a new device ID, if needed

server/src/com/cloud/deploy/DeploymentPlanningManagerImpl.java
.....later fails to start up VM too
Author: Prachi Damle
Changes:
- Try to use the last_host if it has free capacity but no reserved capacity
Signed-off-by: Maneesha.P <maneesha.papireddygari@citrix.com>
=> CLOUDSTACK-8714 Restore VM (Re-install VM) with enable.storage.migration set to false fails

server/src/com/cloud/configuration/ConfigurationManagerImpl.java
Problem:
--------------------------
When you add an IP range and associate it to an account then resource count of public_ip will be updated to the range length.
After some time try to delete this range and the resource count of public_up for this account is not descremented and is causing account not to add any more public IPs to it once it reaches the resource limit.
RCA:
----------------
We were not decrement the count while deleting the IP range that was associated to an account.
Fix:
-------------
Up on deletion we are decrementing the resource count for public_up now.
=> CLOUDSTACK-8711: public_ip type resource count for an account is not decremented upon IP range deletion

engine/schema/src/com/cloud/upgrade/dao/Upgrade30xBase.java, framework/db/src/com/cloud/utils/db/DbUtil.java
Not all are in here, the db upgrade code seems to stay the main pitfall.
=> Coverity regressions per 10 aug 2015

api/src/org/apache/cloudstack/api/command/user/config/ListCapabilitiesCmd.java, api/src/org/apache/cloudstack/api/response/CapabilitiesResponse.java, server/src/com/cloud/server/ManagementServerImpl.java, ui/scripts/cloudStack.js, ui/scripts/instances.js, ui/scripts/sharedFunctions.js
See issue CLOUDSTACK-8580 and individual commits.
=> Interface changes related to CLOUDSTACK-8580

plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtCreateCommandWrapper.java
Fixed Coverity issue "Dereference null return value"
=> Fixed Coverity issue "Dereference null return value"

scripts/storage/secondary/cloud-install-sys-tmplt, server/src/com/cloud/deploy/DeploymentPlanningManagerImpl.java
Spotted this using Elasticsearch .
=> Fixed typo

server/src/com/cloud/deploy/DeploymentPlanningManagerImpl.java
=> Typo correction

api/src/org/apache/cloudstack/api/command/user/autoscale/CreateAutoScalePolicyCmd.java, engine/schema/src/com/cloud/network/dao/VpnUserDao.java, plugins/user-authenticators/ldap/test/groovy/org/apache/cloudstack/ldap/LdapContextFactorySpec.groovy, plugins/user-authenticators/ldap/test/groovy/org/apache/cloudstack/ldap/LdapUserResponseSpec.groovy, scripts/vm/hypervisor/xenserver/cloudlog, server/src/com/cloud/ha/RecreatableFencer.java, services/console-proxy-rdp/rdpconsole/README.txt, services/console-proxy-rdp/rdpconsole/src/main/java/common/Client.java, test/integration/component/test_escalations_ipaddresses.py, test/integration/component/test_ldap.py
Some more typos that I've found .
=> More typos

tools/git/git-pr
Processed feedback from @bhaisaab and (a colleague of) @karuturi 
- make the help message better (I also updated Confluence)
- make sure we can use it on other repo's as well (Documentation and such)
Tested it and works fine for me.
=> Git PR merge script improvements

test/integration/component/test_escalations_routers.py
check bug 8757 for more details .
=> CLOUDSTACK-8757:FTP modules are not loaded in VR

test/integration/testpaths/testpath_multiple_snapshot.py, tools/marvin/marvin/codes.py
On VMWare with a Zone wide primary storage and more than two clusters verify successful creation of snapshot multiple times.
=> CLOUDSTACK-8716: Verify creation of snapshot from volume when the task is performed repeatedly in zone wide primary Storage

test/integration/testpaths/testpath_usage.py
After restoring a running VM current ROOT disk gets destroyed and new ROOT disk gets created.
This testcase is to check if volume usage of this newly created volume is listed in listUsageRecords API.
=> CLOUDSTACK-8723: Verify API call "listUsageRecords" returns usage of new volume created after restore VM

debian/rules
PR#737 add lines  in pom.xml which break debian build.
This fix debian package build issue.
=> fix debian package after addition of license header in pom.xml

setup/db/db/schema-421to430.sql
@remibergsma @wido Can you test it?
=> Fix schema-421to430.sql issue after MariaDB upgrade

.gitignore, utils/src/main/java/com/cloud/utils/log/CglibThrowableRenderer.java
Also removing the entry 'log/' from .gitignore since that was the culprit for the removal of the file.
This was detected in #714
=> Putting CglibThrowableRenderer.java back after it was removed in 83fd8f6

systemvm/patches/debian/config/opt/cloud/bin/cs/CsHelper.py, systemvm/patches/debian/config/opt/cloud/bin/cs/CsRedundant.py
conntrackd fails to start.
Rebased with master. This closes #692
=> CLOUDSTACK-8725 RVR functionality is broken in case of isolated networks

plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
Use host.reserved.ram.mb agent property to modify total system RAM
before reporting to management server.
=> CLOUDSTACK-8678: Reserve RAM for KVM host OS

plugins/user-authenticators/ldap/src/org/apache/cloudstack/ldap/ADLdapUserManagerImpl.java
issue: Boxing/unboxing to parse a primitive
=> Fixing findbugs error due to PR #755 merge

systemvm/patches/debian/config/opt/cloud/bin/configure.py, systemvm/patches/debian/config/opt/cloud/bin/cs/CsFile.py, systemvm/patches/debian/config/opt/cloud/bin/cs/CsHelper.py, systemvm/patches/debian/config/opt/cloud/bin/cs_remoteaccessvpn.py, systemvm/patches/debian/config/opt/cloud/bin/cs_vpnusers.py, systemvm/patches/debian/config/opt/cloud/bin/merge.py, systemvm/patches/debian/config/opt/cloud/bin/update_config.py
@remibergsma  @wilderrodrigues 
Added the VR configuration changes for 
1. Remote access vpn
2. Remote access vpn users.
=> CLOUDSTACK-8690:Added remote access vpn and vpn users configuration

client/WEB-INF/classes/resources/messages.properties, ui/dictionary.jsp, ui/scripts/network.js
It provides appropriate message in the UI when configuring the firewall rules in Network page.
If the default egress policy is allow, then it says to block traffic. If the default egress policy is deny, then it says to allow traffic.
=> CLOUDSTACK-8821: UI Change while configuring firewall rule.

core/src/com/cloud/storage/template/LocalTemplateDownloader.java, core/test/com/cloud/storage/template/LocalTemplateDownloaderTest.java
Removed main() method from LocalTemplateDownloader.java
=> Removal of test/debug code.

agent/src/com/cloud/agent/Agent.java, engine/orchestration/src/com/cloud/agent/manager/AgentManagerImpl.java, engine/orchestration/src/com/cloud/agent/manager/ClusteredAgentManagerImpl.java, utils/src/main/java/com/cloud/utils/SerialVersionUID.java, utils/src/main/java/com/cloud/utils/exception/NioConnectionException.java, utils/src/main/java/com/cloud/utils/exception/TaskExecutionException.java, utils/src/main/java/com/cloud/utils/nio/NioClient.java, utils/src/main/java/com/cloud/utils/nio/NioConnection.java, utils/src/main/java/com/cloud/utils/nio/NioServer.java, utils/src/main/java/com/cloud/utils/nio/Task.java, utils/src/test/java/com/cloud/utils/testcase/NioTest.java
That's the first part of the refactor, which will touch the ManagedContextRunnable and all its subclasses. However, in order to reduce impact, the first part comprises the Agent and Nio related classes (NioConnection, NioServer and NioClient).
* All the sub-classes were also updated according to the changes in the super-classes
* Improved exception handling
* There were also code formatting changes
Changes were structural and the NioTest covered them without need to modify the unit test.
This PR is quite extensive. Please, wait for the Test Report in order to proceed with further review.
ping @remibergsma @miguelaferreira @bhaisaab @karuturi @wido @DaanHoogland @borisroman @K0zka 
Cheers,
Wilder
=> CLOUDSTACK-8822 - Replacing Runnable by Callable

api/src/org/apache/cloudstack/alert/AlertService.java, engine/storage/image/src/org/apache/cloudstack/storage/image/TemplateServiceImpl.java, engine/storage/src/org/apache/cloudstack/storage/image/BaseImageStoreDriverImpl.java, server/src/com/cloud/alert/AlertManagerImpl.java, server/src/com/cloud/storage/ImageStoreUploadMonitorImpl.java
Authored-By: @sanjaytripathi 
Reviewed-By: @devdeep
=> CLOUDSTACK-8835: Added alerts incase of template download failure

core/src/com/cloud/storage/template/S3TemplateDownloader.java, services/secondary-storage/server/src/org/apache/cloudstack/storage/template/DownloadManagerImpl.java, utils/src/main/java/com/cloud/utils/S3Utils.java, utils/src/main/java/com/cloud/utils/storage/QCOW2Utils.java, utils/src/test/java/com/cloud/utils/storage/QCOW2UtilsTest.java
- Cleaned up S3TemplateDownloader
- Created static QCOW2 utils class.
- Reformatted some parts of DownloadManagerImpl
=> CLOUDSTACK-8819: Added QCOW2 virtual size checking for S3.

plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/storage/LibvirtStorageAdaptor.java
A simple commit which changes a couple of log lines.
=> CLOUDSTACK-8645: Improve logging of RBD functionality in KVM

vmware-base/src/com/cloud/hypervisor/vmware/util/VmwareClient.java
CLOUDSTACK-8820: Showing error when try to add advance zone using VMware ESXi 6.0 host
Summary: In vCenter 6.0, response headers need to be fetched after service login for server cookie unlike previous versions of vCenter.
=> CLOUDSTACK-8820: Support for VMware vCenter 6 data center

engine/schema/src/com/cloud/upgrade/DatabaseUpgradeChecker.java, engine/schema/src/com/cloud/upgrade/dao/Upgrade452to453.java, engine/schema/src/com/cloud/upgrade/dao/Upgrade453to460.java, setup/db/db/schema-452to453-cleanup.sql, setup/db/db/schema-452to453.sql
=> 4.5.3 upgradepath for master branch

test/integration/smoke/test_vm_snapshots.py
Please check https://issues.apache.org/jira/browse/CLOUDSTACK-8893 for more details.
=> CLOUDSTACK-8893: Fixing script as per the latest functionality

test/integration/component/test_simultaneous_volume_attach.py
Attach multiple Volumes simultaneously to a Running VM ... === TestName: test_attach_multiple_volumes | Status : SUCCESS ===
ok
Ran 1 test in 196.931s
OK
=> CLOUDSTACK-8726 : Automation for Quickly attaching multiple data disks to a new VM

tools/devcloud4/advanced/Vagrantfile, tools/devcloud4/basic/Vagrantfile, tools/devcloud4/binary-installation-advanced/Vagrantfile, tools/devcloud4/binary-installation-basic/Vagrantfile
The centos-6.5 is no longer available
=> Fixed box location on vagrant files for devcloud4 (CLOUDSTACK-8898)

systemvm/patches/debian/config/opt/cloud/bin/configure.py
1. For static nat filter rules are not configured in VR.
2. Corrected vm ip in PF rule.
=> CLOUDSTACK-8881: Fixed Static and PF configuration issue

test/integration/smoke/test_scale_vm.py
Please go through CS-8924 for more details.
=> CLOUDSTACK-8924: Removed duplicate test from test_scale_vm.py

engine/orchestration/src/com/cloud/vm/VirtualMachinePowerStateSyncImpl.java, engine/schema/src/com/cloud/vm/dao/VMInstanceDao.java, engine/schema/src/com/cloud/vm/dao/VMInstanceDaoImpl.java
added a null guard to @resmo's #885 A unit test or two would be nice as well but as this is a blocker I want to get it to review asap.
@koushik-das @wilderrodrigues @anshul1886 @karuturi @remibergsma you all commented on the original, please have a look. @bhaisaab welcome to comment as well.
=> CLOUDSTACK-8848 ensure power state is up to date for missing PowerState handling

client/WEB-INF/classes/resources/messages.properties
Corrected the sentence as the previous one didn't make sense
=> Corrected sentence

test/integration/smoke/test_internal_lb.py
Added 1VPC 2TIER internal lb roundrobin test
Added 1VPC 1TIER internal lb admin stats test
Refactored existing test
Thanks @wilderrodrigues for examples and advice!
=> CLOUDSTACK-8697 - Refactored & Added Internal LB smoke test

test/integration/smoke/test_vpc_vpn.py, tools/marvin/marvin/lib/base.py
Add optional fields: iprange and fordisplay to Marvin base.py class method Vpn.create
Add optional field: passive to Marvin base.py class method Vpn.createVpnConnection
=> Improve marvin test site2site VPN

setup/db/db/schema-452to460.sql
@borisroman @NuxRo could you test it?
=> CLOUDSTACK-8979: add virtio support for CentOS/RHEL 7 on KVM

ui/index.jsp
Signed-off-by: Laszlo Hornyak <laszlo.hornyak@gmail.com>
=> CLOUDSTACK-8977: remove session creation from index.jsp

test/integration/smoke/test_internal_lb.py
Add wait for template download
Refactored template section of services
Added some extra logging in the setup phase
=> smoke/test_internal_lb.py:  Fix template not ready error

server/src/com/cloud/storage/VolumeApiServiceImpl.java
Primary Storage count for an account does not decrease when a Data Disk
is deleted belonging to the account unless the VM to which volume
belonged is destroyed
The resource counts are updated even before the disk is actually deleted
resulting in the same value.
Moved the resource counts updation to after the expunge operation as
thats when the disk is actually deleted.
Testing:
Earlier, test_create_multiple_volumes in test/integration/component/test_ps_limits.py failed  with error AssertionError: Resource count 37 should match with the expected resource count 32
Before
Test create multiple volumes ... === TestName: test_create_multiple_volumes_1_root_domain_admin | Status : FAILED ===
FAIL
Test create multiple volumes ... === TestName: test_create_multiple_volumes_2_child_domain_admin | …
=> CLOUDSTACK-8889: delete volume doesnt decrement primary store resource count

plugins/storage/volume/solidfire/src/org/apache/cloudstack/storage/datastore/driver/SolidFirePrimaryDataStoreDriver.java
I found this issue when a SolidFire integration test yesterday wasn't able to delete primary storage because it claimed there were still volumes using the primary storage in question (this was due to the removed column not being updated appropriately).
I decided to go with a solution where the delete logic would pass in a volume ID to ignore when computing the used space of the primary storage in question.
=> CLOUDSTACK-8985: Deleted volume's removed column not updated

packaging/centos7/cloud-management.service, packaging/centos7/cloud-management.sysconfig, packaging/centos7/cloud.spec
Here are a few adjustments for the packaging in centos7. With these changes I was able to start the service. Please review. Thank you.
=> CLOUDSTACK-9010: adjust packaging for centos7

engine/schema/src/com/cloud/capacity/dao/CapacityDaoImpl.java
Fixed following issues if vm.allocation.algorithm is set to firstfitleastconsumed
1. VM deployment failure if thre is only ZWPS in setup
2. VM migration is impossible from UI
To test
1. Create setup with ZWPS only
2. set vm.allocation.algorithm to firstfitleastconsumed in global settings
3. deploy virtual machine
observation: vm deployment will fail
After this fix it will pass
second scenario
1. Create Cloudstack Setup with two hosts (As it needs setup for migration)
2. Try migrating VM from UI 
Observation: There will be error response in logs with nothing available in UI
After fix it will pass
Regarding BVT I am not sure whether there exists tests for firstfitleastconsumed vm allocation algorithm.
=> CLOUDSTACK-8825, CLOUDSTACK-8824 : Fixed issues if vm.allocation.algorithm is set to firstfitleastconsumed

plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtCopyVolumeCommandWrapper.java, plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtCreatePrivateTemplateFromSnapshotCommandWrapper.java, plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtUtilitiesHelper.java, plugins/hypervisors/kvm/test/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java, plugins/hypervisors/kvm/test/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtUtilitiesHelperTest.java, utils/src/main/java/com/cloud/utils/script/Script.java
These were lacking, but this helper is used in various places
inside the KVM code.
Some simple tests to verify the helper is doing what we expect it
to do.
=> kvm: Add UnitTests for LibvirtUtilitiesHelper

plugins/hypervisors/ovm3/src/main/java/com/cloud/hypervisor/ovm3/resources/Ovm3HypervisorGuru.java, plugins/hypervisors/ovm3/src/main/java/com/cloud/hypervisor/ovm3/resources/Ovm3StorageProcessor.java, plugins/hypervisors/xenserver/src/com/cloud/hypervisor/XenServerGuru.java
Fixes the wrong answer that is given for host delegation related to CLOUDSTACK-8964. The snapshot to volume is implemented and a small logger is added to the XenServerGuru to make host delegation visible.
=> CLOUDSTACK-8964: Ovm3HypervisorGuru wrong answer and snapshot to volume implementation.

plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/storage/LibvirtStoragePool.java, plugins/hypervisors/kvm/test/com/cloud/hypervisor/kvm/storage/KVMPhysicalDiskTest.java, plugins/hypervisors/kvm/test/com/cloud/hypervisor/kvm/storage/LibvirtStoragePoolTest.java
These classes were not covered by Unit Tests and this commit
adds some tests for their basic functionality.
=> Add Unit Tests for Libvirt/KVM storage code

ui/scripts/network.js
Instead of searching for each network, now it is searching for each zone.
For basic zone, it will show the security group directly because by default securitygroupsenabled is true.
For advanced zone, check the securitygroupsenabled option in each zone. If any one has value true, then show.
=> CLOUDSTACK-8919: Slow UI response while loading the list of networks in network tab.

ui/css/cloudstack3.css
Increased the margin and padding to accomodate all the boxes inside toolbar.
=> CLOUDSTACK-8913: Search box in Templates tab out of alignment

test/integration/smoke/test_vpc_vpn.py
- Added a wait for template download as the test was failing in some environments
- Removed debug timer in setup and teardown
- Increased time.sleep before ssh connection from 10 to 20 seconds
- PEP8
- Changed required_hardware tag to true
=> smoke/test_vpc_vpn: Add template wait & refactor

ui/scripts/system.js
Making parallel asynchronous calls to speed up the infrastructure page.
=> CLOUDSTACK-9038 - Infrastructure tab is slow because of synchronous API calls

python/lib/cloud_utils.py, python/lib/cloudutils/utilities.py, scripts/vm/hypervisor/versions.sh
https://issues.apache.org/jira/browse/CLOUDSTACK-9029
=> CLOUDSTACK-9029: Proper support to identify CentOS 7 version number

python/lib/cloudutils/serviceConfig.py, python/lib/cloudutils/serviceConfigServer.py
Fix paths for logging Ubuntu Management.
How to test:
Install via DEB packages...
=> CLOUDSTACK-9039: Fix paths for logging Ubuntu Management

ui/scripts/zoneWizard.js
Added to option to use RBD as primary storage in the Zone Wizard.
Pure UI change.
=> CLOUDSTACK-9044: Add RBD Primary Storage to the Zone Wizard.

server/src/com/cloud/api/query/dao/DomainRouterJoinDaoImpl.java, ui/css/cloudstack3.css, ui/index.jsp, ui/scripts/instanceWizard.js, ui/scripts/vpc.js
[UI] fix typo for user data field
[UI] Private Cloud VPC always shows 0 in Site-to-Site VPN, even when one is configured
[UI] change the Icon for changing ACL's for a tier in a VPC
[UI] Network names are not being displayed in Infra » VRs » router » NICS
=> Fix some small UI bugs

client/bindir/cloud-setup-management.in, packaging/centos7/cloud.spec, packaging/centos7/tomcat7/db.properties, python/lib/cloudutils/globalEnv.py, python/lib/cloudutils/serviceConfigServer.py
CLOUDSTACK-9049: Fix Centos7 with Tomcat7 packaging and python libs
=> CLOUDSTACK-9049: fix Centos7 with Tomcat7 packaging and python libs

api/src/org/apache/cloudstack/api/command/admin/resource/UploadCustomCertificateCmd.java, utils/src/main/java/com/cloud/utils/StringUtils.java
tested off-line but rebased afterwards!
=> CLOUDSTACK-9023 filtering privatekey info from logging

systemvm/patches/debian/config/opt/cloud/bin/configure.py, systemvm/patches/debian/config/opt/cloud/bin/cs/CsAddress.py, systemvm/patches/debian/config/opt/cloud/bin/cs/CsRedundant.py, systemvm/patches/debian/config/opt/cloud/bin/master.py, systemvm/patches/debian/config/opt/cloud/templates/keepalived.conf.templ, test/integration/component/test_vpc_redundant.py
This PR closes #1064
All the details can be found in the original PR, which won't be merged because it was created agains master. Once this PR is closed, the original one will be also closed.
=> [4.6.1] CLOUDSTACK-9015 - Redundant VPC Virtual Router's state is BACKUP & BACKUP or MASTER & MASTER

engine/schema/src/com/cloud/upgrade/dao/Upgrade442to450.java
replacing #1061 on release branch for 4.6
=> CLOUDSTACK-9057 remove old system vm upgrade code

server/src/com/cloud/storage/StoragePoolAutomationImpl.java
change comment 
//if the instance is of type ssvm, call the ssvm manager
to
//if the instance is of type domain router vm, call the network manager
=> update for comment in cancelMaintin on start VR

plugins/network-elements/bigswitch/src/com/cloud/network/bigswitch/BigSwitchBcfApi.java
=> findbugs: ! equals instead of !=

ui/scripts/accounts.js, ui/scripts/cloudStack.js, ui/scripts/instances.js
simple change in several locations
=> javascript:TrailingComma sonacube issue considered blocker removed

plugins/network-elements/juniper-srx/src/com/cloud/network/element/JuniperSRXExternalFirewallElement.java, plugins/network-elements/nuage-vsp/src/com/cloud/network/element/NuageVspElement.java
I am having troubles getting this to work but it passes the point at which the master slowbuild is broken.
=> PR1102 regression fix; half the annotation was removed

scripts/vm/systemvm/injectkeys.sh
Fix regression from commit 3381154fafb7fa4f0a61d538f7c2550e48247787
The error seen on CentOS 7:
```
2015-11-20 21:51:16,161 DEBUG [c.c.s.ConfigurationServerImpl] (localhost-startStop-1:null) No loop device found, skipping ssh key insertion in systemvm.iso
```
Instead of detecting `/dev/loop0` this checks if we run inside Docker.
Tested on CentOS 7 and that now works again as expected.
```
2015-11-23 16:20:16,777 DEBUG [c.c.s.ConfigurationServerImpl] (localhost-startStop-1:null) Executing: /bin/bash /var/lib/tomcat/webapps/client/WEB-INF/classes/scripts/vm/systemvm/injectkeys.sh /home/cloud/.ssh/id_rsa.pub /home/cl
oud/.ssh/id_rsa /var/lib/tomcat/webapps/client/WEB-INF/classes/vms/systemvm.iso
2015-11-23 16:20:16,821 DEBUG [c.c.s.ConfigurationServerImpl] (localhost-startStop-1:null) …
```
=> CLOUDSTACK-9077 Fix injectkeys.sh to work on CentOS7

ui/scripts/instances.js
(fix is already included in the https://github.com/apache/cloudstack/pull/1106 for 4.6 as well)
=> [master] ui: Fix undefined check in instances.js, regression from 459d638

server/src/com/cloud/ha/HighAvailabilityManagerImpl.java
The frequency at which Cloudstack tries to migrate the VMs is currently controlled by the global parameter "restart.retry.interval" which has a default value of 600 seconds or 10 minutes.This has to be changed to use "migrate.retry.interval" which by default is 120 seconds or 2 minutes . Cloudstack uses restart.retry.interval for all operations-migrate,restart,stop,destroy.
=> CLOUDSTACK-8866 : restart.retry.interval is being used instead of migrate.retry.interval during host maintenance

services/secondary-storage/server/src/org/apache/cloudstack/storage/resource/NfsSecondaryStorageResource.java
Original PR and discussion at #1112
=> Fix secondary storage not working with swift

tools/build/build_asf.sh, tools/build/setnextversion.sh
During the previous release I had to edit these manually. This will fix that so all versions get updated.
=> make sure all files are updates with new version

scripts/storage/qcow2/resizevolume.sh, server/src/com/cloud/storage/VolumeApiServiceImpl.java, ui/scripts/storage.js
(1) fix issue: volume size is not updated even if the operation succeed
(2) Add ui support for root volume resize
(3) resize on qcow2 type ROOT volume of stopped vm does not really work
see https://issues.apache.org/jira/browse/CLOUDSTACK-9101
=> CLOUDSTACK-9101: fix some issues in resize volume

api/src/com/cloud/gpu/GPU.java, api/src/com/cloud/vm/NicIpAlias.java, engine/orchestration/src/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java, engine/schema/src/com/cloud/vm/dao/NicIpAliasDao.java, engine/schema/src/com/cloud/vm/dao/NicIpAliasDaoImpl.java, engine/schema/src/com/cloud/vm/dao/NicIpAliasVO.java, plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/LibvirtNetworkDef.java, plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/LibvirtSecretDef.java, plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/LibvirtStoragePoolDef.java, plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/LibvirtStoragePoolXMLParser.java, plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/LibvirtStorageVolumeDef.java, plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/LibvirtStorageVolumeXMLParser.java, plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/storage/LibvirtStorageAdaptor.java, plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/storage/ManagedNfsStorageAdaptor.java, plugins/hypervisors/kvm/test/com/cloud/hypervisor/kvm/resource/LibvirtSecretDefTest.java, plugins/hypervisors/kvm/test/com/cloud/hypervisor/kvm/resource/LibvirtStoragePoolDefTest.java, server/src/com/cloud/api/ApiResponseHelper.java, server/src/com/cloud/configuration/ConfigurationManagerImpl.java, server/src/com/cloud/network/router/CommandSetupHelper.java, server/src/com/cloud/network/router/VirtualNetworkApplianceManagerImpl.java, server/src/com/cloud/network/rules/DhcpSubNetRules.java, server/src/com/cloud/server/StatsCollector.java
make enums adhere to best practice naming conventions
=> CLOUDSTACK-9047 rename enums

server/test/com/cloud/ha/HighAvailabilityManagerImplTest.java
final few ignored exceptions supplied with log messages.
=> CLOUDSTACK-8656: tests ignoring exceptions

client/tomcatconf/commands.properties.in, plugins/database/quota/src/org/apache/cloudstack/api/command/QuotaBalanceCmd.java, plugins/database/quota/src/org/apache/cloudstack/api/command/QuotaCreditsCmd.java, plugins/database/quota/src/org/apache/cloudstack/api/command/QuotaEmailTemplateListCmd.java, plugins/database/quota/src/org/apache/cloudstack/api/command/QuotaEmailTemplateUpdateCmd.java, plugins/database/quota/src/org/apache/cloudstack/api/command/QuotaEnabledCmd.java, plugins/database/quota/src/org/apache/cloudstack/api/command/QuotaStatementCmd.java, plugins/database/quota/src/org/apache/cloudstack/api/command/QuotaSummaryCmd.java, plugins/database/quota/src/org/apache/cloudstack/api/command/QuotaTariffListCmd.java, plugins/database/quota/src/org/apache/cloudstack/api/command/QuotaTariffUpdateCmd.java, plugins/database/quota/src/org/apache/cloudstack/api/response/QuotaEnabledResponse.java, plugins/database/quota/src/org/apache/cloudstack/quota/QuotaService.java, plugins/database/quota/src/org/apache/cloudstack/quota/QuotaServiceImpl.java, ui/plugins/quota/quota.js
Adding a new command to check if the quota plugin is enabled.
Also changed the command version to 4.7.
=> CLOUDSTACK-9131: Create a new API to check if the plugin is enabled.

plugins/database/quota/src/org/apache/cloudstack/api/response/QuotaResponseBuilder.java, plugins/database/quota/src/org/apache/cloudstack/api/response/QuotaResponseBuilderImpl.java, plugins/database/quota/src/org/apache/cloudstack/quota/QuotaService.java, plugins/database/quota/src/org/apache/cloudstack/quota/QuotaServiceImpl.java, plugins/database/quota/test/org/apache/cloudstack/api/response/QuotaResponseBuilderImplTest.java
When negative credits are added to an account the balance credits can become negative for that account. This will fix will lock the account if quota is enforced.
=> CLOUDSTACK-9153: When negative credits are added to an account the

plugins/hypervisors/xenserver/test/com/cloud/hypervisor/xenserver/resource/CitrixHelperTest.java
With my last PR#1196, I missed to place the license disclaimer into CitrixHelperTest.java. Updated the file with the disclaimer.
=> CLOUDSTACK-9166:Build failed in Jenkins: cloudstack-rat-master #7038

framework/quota/test/org/apache/cloudstack/quota/QuotaStatementTest.java
QuotaStatementTest: fix the method invocation verification
=> 4.7 quota test

README.md
cc @remibergsma 
Based on https://github.com/apache/cloudstack/pull/1281#issuecomment-169275052
=> README: revert back to the normal cloudstack logo

core/src/com/cloud/agent/api/routing/SetNetworkACLCommand.java
This PR fixes a problem with iptables when creating ACL items using a comma separated value list of CIDRs. Please refer to the details in the Jira issue.
=> CLOUDSTACK-9213 - As a user I want to be able to use multiple ip's/cidrs in an ACL

engine/schema/src/com/cloud/capacity/dao/CapacityDaoImpl.java
type bigint(20) with type  varchar does not work well on MariaDB
So forcing it to type decimal
=> Fix mariadb related listCapacity bug (CLOUDSTACK-8966)

ui/scripts/domains.js
The list of domains was unsorted and that annoyed me so I sorted it :-)
=> CLOUDSTACK-9220 Sort list of domains on Domain tab in UI

systemvm/patches/debian/config/opt/cloud/bin/configure.py, systemvm/patches/debian/config/opt/cloud/bin/cs/CsDhcp.py, systemvm/patches/debian/config/opt/cloud/bin/update_config.py
Will post integration test results soon!
Ping @wilderrodrigues @remibergsma
=> Enhance VR performance

api/src/org/apache/cloudstack/api/command/user/vm/DeployVMCmd.java, engine/orchestration/src/com/cloud/vm/VirtualMachineManagerImpl.java, server/src/com/cloud/vm/UserVmManagerImpl.java
improved the error messages in vm deployment code path. added some more data to the error messages and also fixed some errors using internal ids to use uuids.
=> CLOUDSTACK-8860: improve error messages in VM deployment code path.

ui/css/cloudstack3.css
Giving a little more space to fix new line, see [after and before](https://photos.google.com/share/AF1QipP6ZeMO4B_fSLCBocr0MQmgbbq3gAf0vDY8Hy4YjUgqLH_VY8vpP2y5U6RMWL9Vfw?key=ZFVxcjUxcXZvVmZGTTQzOER6VUxYWENVODJfXzhB)
=> UI: improve filter dropdown width

framework/quota/src/org/apache/cloudstack/quota/QuotaStatementImpl.java, framework/quota/src/org/apache/cloudstack/quota/vo/ServiceOfferingVO.java, plugins/database/quota/src/org/apache/cloudstack/api/response/QuotaResponseBuilderImpl.java, plugins/database/quota/test/org/apache/cloudstack/api/response/QuotaResponseBuilderImplTest.java
Findbug fixes for cloud-framework-quota and cloud-plugin-database-quota.
=> Quota: findbug fixes

api/src/org/apache/cloudstack/api/command/user/snapshot/RevertSnapshotCmd.java
Updating the documentation before the api is actually supported
=> CLOUDSTACK-8850: revertSnapshot command does not work

test/integration/component/test_persistent_networks.py
checking usage event for delete volume. I have incorporated all the suggested changes.
=> CLOUDSTACK-8731-checking usage event for delete volume

test/integration/testpaths/testpath_attach_disk_zwps.py
Test case to verify if data volume uploaded in a storage pool(Cluster wide storage pool) is available for attachment to a Virtual Machine.and also check that after attachment the volume is in correct storage pool.
=> CLOUDSTACK-8895: Verify if storage on storage pool can be attached to VM

test/integration/smoke/test_routers.py
Testcase to check if VR's IP changes if it is destroyed and re-created in basic zone.
=> CLOUDSTACK-8728: Testcase to Verify if VRs IP 

test/integration/testpaths/testpath_restore_vm.py
CLOUDSTACK-8717: Failed to start instance after restoring the running instance
-Modified code to add tag to aonly one cluster wide SP
-Added validateList function
-Added code to clear tags in tearDown class
=> Squashing two commits in to single commit

test/integration/testpaths/testpath_snapshot_limits.py
Verify if physical_size attribute of snapshot_store_ref table stores actual physical size of the snapshot
=> CLOUDSTACK-9128: Testcase to verify physical_size attribute of snapshot_store_ref table 

ui/scripts/network.js, ui/scripts/ui-custom/instanceWizard.js, ui/scripts/ui-custom/projects.js
Repro Steps: 
==========
1. Setup basic environments as normal.
2. Open a browser, go to Web Console.
3. Upload a iso template.
4. Go to "Instances" page and add new instance.
5. Check the strings on create instance wizards.
Expected Result:
=============
All the strings should be localized on create instance wizards.
Actual Result:
===========
Some strings are not localized on create instance wizards.
Language:
========
JA -> Fail
SC -> Fail
Fix:
===
Fixed the hard coded string.
=> CLOUDSTACK-9267: String is not localized on create instance wizards.

.travis.yml, developer/developer-prefill.sql, setup/db/templates.simulator.sql, setup/dev/advanced.cfg, tools/travis/before_install.sh, tools/travis/before_script.sh, tools/travis/install.sh, tools/travis/script.sh, tools/travis/xunit-reader.py
- Migrate to trusty based Travis VMs
- Increase tests across five build matrices
- Fix xunit-reader output, include time
- Fix pip/python usage, pkg installation
- Build CloudStack in parallel with -T4
- Deploy database with optimized global settings
cc @runseb @swill @wido @DaanHoogland
=> travis: Fix simulator tests and optimize default global configs

test/integration/component/maint/test_vpc.py
Please check bug CLOUDSTACK-9215 for more details.
Test Results:
==========
Test to create vpc tier with nic type as Vmxnet3 ... === TestName: test_01_create_tier_Vmxnet3 | Status : SUCCESS ===
ok
Ran 1 test in 591.630s
OK
=> [CLOUDSTACK-9215]Test to verify vm deployment in vpc tier if nic type is Vmxnet3

ui/scripts/dashboard.js
cc @swill @terbolous @runseb @wido @abhinandanprateek
=> CLOUDSTACK-9335: fix typo in dashboard's fetchlatest usage

api/src/org/apache/cloudstack/api/command/user/vm/ScaleVMCmd.java, api/src/org/apache/cloudstack/api/command/user/vm/UpgradeVMCmd.java
This reverts commit 9c4162ac7f451fc3e2155418dcfff224c8c08a4a and 16baa1289b7de383e98d0070717b3f1873fa2db3
Before change: exception when change compute offering (to dynamic service offering) on UI
After change: succeed
=> CLOUDSTACK-9251: Fix issue in scale VM to dynamic service offering

api/src/org/apache/cloudstack/api/command/admin/vm/MigrateVirtualMachineWithVolumeCmd.java
https://issues.apache.org/jira/browse/CLOUDSTACK-9088
=> CLOUDSTACK-9088: Update the description for migrateVirtualMachineWithVolume api

ui/scripts/ui/widgets/detailView.js
https://issues.apache.org/jira/browse/CLOUDSTACK-9194
To test:
Open any VM console in IE, and try resizing the browser window of console
It should be resizable.
=> CLOUDSTACK-9194:  Making the console popup window resizable in IE to make sure the focus is not lost

api/src/com/cloud/vm/VmDetailConstants.java, plugins/hypervisors/vmware/src/com/cloud/hypervisor/guru/VMwareGuru.java, plugins/hypervisors/vmware/src/com/cloud/hypervisor/vmware/resource/VmwareResource.java, plugins/hypervisors/vmware/src/com/cloud/storage/resource/VmwareStorageProcessor.java, pom.xml, server/src/com/cloud/storage/VolumeApiServiceImpl.java, server/src/com/cloud/vm/UserVmManager.java, server/src/com/cloud/vm/UserVmManagerImpl.java, server/test/com/cloud/storage/VolumeApiServiceImplTest.java, server/test/com/cloud/vm/UserVmManagerTest.java, utils/src/main/java/org/apache/cloudstack/utils/volume/VirtualMachineDiskInfo.java, utils/src/test/java/org/apache/cloudstack/utils/volume/VirtualMachineDiskInfoTest.java, vmware-base/src/com/cloud/hypervisor/vmware/mo/VirtualMachineDiskInfoBuilder.java, vmware-base/src/com/cloud/hypervisor/vmware/mo/VirtualMachineMO.java
- Improve disk chain usage while attaching, migrating disks
- Gets root disk controller based diskDeviceBusName from volume's chain info
=> [4.7] vmware: improve support for disks

framework/quota/src/org/apache/cloudstack/quota/QuotaAlertManagerImpl.java, framework/quota/src/org/apache/cloudstack/quota/QuotaManager.java, framework/quota/src/org/apache/cloudstack/quota/QuotaManagerImpl.java, framework/quota/src/org/apache/cloudstack/quota/dao/QuotaBalanceDaoImpl.java, framework/quota/test/org/apache/cloudstack/quota/QuotaManagerImplTest.java, plugins/database/quota/src/org/apache/cloudstack/api/command/QuotaCreditsCmd.java, plugins/database/quota/src/org/apache/cloudstack/api/response/QuotaResponseBuilder.java, plugins/database/quota/src/org/apache/cloudstack/api/response/QuotaResponseBuilderImpl.java, plugins/database/quota/src/org/apache/cloudstack/quota/QuotaServiceImpl.java, plugins/database/quota/test/org/apache/cloudstack/api/command/QuotaCreditsCmdTest.java, plugins/database/quota/test/org/apache/cloudstack/api/response/QuotaResponseBuilderImplTest.java
Added unit tests to check lockablity of various accounts.
Currently normal user and domain admin accounts are eligible for locking.
=> Quota: consolidated lockable account check to a method. 

plugins/hypervisors/kvm/src/com/cloud/ha/KVMInvestigator.java, pom.xml, server/src/com/cloud/ha/HighAvailabilityManagerImpl.java, server/test/com/cloud/ha/HighAvailabilityManagerImplTest.java, test/integration/component/test_host_ha.py, test/integration/component/test_host_ha.sh, tools/marvin/marvin/lib/utils.py
- KVM-HA- Fix CheckOnHost for Local storage   
- Also skip HA on VMs that are using local storage
=> CLOUDSTACK-9350: KVM-HA- Fix CheckOnHost for Local storage

setup/db/db/schema-481to490-cleanup.sql, setup/db/db/schema-481to490.sql
In some production environments there were being experimented delays in most of the jobs. A search for DB optimization was taken and some deficiencies were discovered, we can group them in 4 groups:
* Incorrect PRIMARY key
* Duplicate PRIMARY KEY
* Missing indexes (Add indexes to avoid full table scans)
* Some views query (Change view to improve account retrieval speed)
=> CLOUDSTACK-9340: General DB Optimization

engine/orchestration/src/com/cloud/agent/manager/ClusteredAgentManagerImpl.java, utils/src/main/java/com/cloud/utils/nio/Link.java, utils/src/main/java/com/cloud/utils/nio/NioClient.java, utils/src/main/java/com/cloud/utils/nio/NioConnection.java, utils/src/main/java/com/cloud/utils/nio/NioServer.java, utils/src/test/java/com/cloud/utils/testcase/NioTest.java
Reopened PR with squashed changes for a re-review and testing after https://github.com/apache/cloudstack/pull/1493 and sub-sequent PRs got reverted
=> CLOUDSTACK-9348: NioConnection improvements

systemvm/scripts/config_ssl.sh
=> Add Java Default Certificat Authorities into the keystore if using a custom cert SSL

core/src/com/cloud/agent/api/ModifyStoragePoolAnswer.java, core/src/com/cloud/agent/api/ModifyStoragePoolCommand.java, core/src/com/cloud/agent/api/ModifyTargetsCommand.java
Change variable names back to fix communication with Hyper-V Agent:
https://issues.apache.org/jira/browse/CLOUDSTACK-9383
=> Hyper-V communication broken by change in variable names

deps/install-non-oss.sh
fix noredist build for new vmware lib
=> fix noredist build because of missing maven dependency of vmware 6.0 lib

plugins/hypervisors/xenserver/src/com/cloud/hypervisor/xenserver/resource/wrapper/xen610/XenServer610MigrateWithStorageCommandWrapper.java
In turn this also fixes VM migration with local storage
This PR is created against 4.7 and can be forward merged to future branches also.
=> CLOUDSTACK-9353: [XenServer] Fixed VM migration with storage

test/integration/smoke/test_privategw_acl.py
Please refer to CLOUDSTACK-9328 for the details.
Test Results:
==========
test_01_vpc_privategw_acl (integration.smoke.test_privategw_acl.TestPrivateGwACL) ... === TestName: test_01_vpc_privategw_acl | Status : SUCCESS ===
ok
Ran 1 test in 108.273s
OK
=> [CLOUDSTACK-9328]: Fix vlan issues from test suite test_privategw_acl.py in BVT

systemvm/patches/debian/config/opt/cloud/bin/cs/CsNetfilter.py
BUG: https://issues.apache.org/jira/browse/CLOUDSTACK-9430
The issue occurred because all of the ACL rules get inserted before the old ones. Then, the cleanup deletes the duplicate rows, and leaves any new rule in front of the old ones.
Here is an example with a simplified iptables view for ACL
Ex: adding a rule 4
before add:
1,2,3
during add:
1',2',3',4',1,2,3
after add:
4',1,2,3
After fix:
before add:
1,2,3
during add:
1,2,3,1',2',3',4'
after add:
1',2',3',4'
=> [CLOUDSTACK-9430] Added fix for adding/editing Network ACL rule ordering

server/src/com/cloud/vm/UserVmManagerImpl.java
JIRA TICKET: https://issues.apache.org/jira/browse/CLOUDSTACK-9436
This PR replaces #1594 
Due to error on `test/integration/smoke/test_vpc_redundant.py` it was found out that `vm_network_map` table should be less aggresive on vm stop
=> CLOUDSTACK-9436: vm_network_map table cleanup, release network resources on expunge command

debian/changelog
Initial merge of 4.9 to master
=> Merge 4.9 to master

engine/schema/src/com/cloud/upgrade/dao/Upgrade410to420.java
the try's catch block was shortening the preparedstatement's life resulting in bad resultset when used outside of try catch.
=> CLOUDSTACK-9459: the try's catch block was shortening the preparedstatement's life

ui/scripts/projects.js
Display the project ID on the details view of a project.
=> Add projectid to project details page

tools/marvin/marvin/codegenerator.py
This fixes Marvin cloudstackAPI generator to work with a live running mgmt server's api discovery.
=> Marvin: Fix codegenerator to work with API discovery

api/src/com/cloud/network/Network.java, api/src/com/cloud/network/NetworkService.java, api/src/com/cloud/network/element/RedundantResource.java, api/src/com/cloud/network/router/VirtualRouter.java, api/src/com/cloud/network/vpn/RemoteAccessVpnService.java, api/src/org/apache/cloudstack/api/ApiConstants.java, api/src/org/apache/cloudstack/api/command/admin/network/UpdateNetworkCmdByAdmin.java, api/src/org/apache/cloudstack/api/command/user/network/UpdateNetworkCmd.java, api/src/org/apache/cloudstack/api/command/user/vpn/DeleteRemoteAccessVpnCmd.java, engine/api/src/org/apache/cloudstack/engine/orchestration/service/NetworkOrchestrationService.java, engine/orchestration/src/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java, engine/schema/src/com/cloud/vm/DomainRouterVO.java, server/src/com/cloud/network/IpAddressManagerImpl.java, server/src/com/cloud/network/NetworkServiceImpl.java, server/src/com/cloud/network/element/VirtualRouterElement.java, server/src/com/cloud/network/router/VirtualNetworkApplianceManagerImpl.java, server/src/com/cloud/network/router/VpcVirtualNetworkApplianceManagerImpl.java, server/src/com/cloud/network/vpn/RemoteAccessVpnManagerImpl.java, server/src/com/cloud/user/AccountManagerImpl.java, server/src/org/cloud/network/router/deployment/RouterDeploymentDefinition.java, server/src/org/cloud/network/router/deployment/RouterDeploymentDefinitionBuilder.java, server/test/com/cloud/network/element/VirtualRouterElementTest.java, server/test/com/cloud/vpc/MockNetworkManagerImpl.java, server/test/org/cloud/network/router/deployment/RouterDeploymentDefinitionTest.java, server/test/org/cloud/network/router/deployment/RouterDeploymentDefinitionTestBase.java, setup/db/db/schema-452to460.sql, setup/db/db/schema-4910to41000.sql, test/integration/component/maint/test_redundant_router.py
more info in the bug link below.
https://issues.apache.org/jira/browse/CLOUDSTACK-8751
=> CLOUDSTACK-8751 minimise downtime of network when network update is in progress.

requirements.txt, test/integration/plugins/solidfire/TestAddRemoveHosts.py, test/integration/plugins/solidfire/TestManagedSystemVMs.py, test/integration/plugins/solidfire/TestSnapshots.py, test/integration/plugins/solidfire/TestVMMigrationWithStorage.py, test/integration/plugins/solidfire/TestVMSnapshots.py, test/integration/plugins/solidfire/TestVolumes.py, test/integration/plugins/solidfire/util/sf_util.py
SolidFire has recently released an official SDK for Python.
I have converted all of the SolidFire integration tests over to making use of this new SDK.
For testing, I re-ran each test and observed success.
https://pypi.python.org/pypi/solidfire-sdk-python/1.1.0.92
=> Switched to the official SolidFire SDK for Python

setup/db/db/schema-4910to41000.sql
added guest_os and guest_os_hypervisor mappings for windows10 and xenserver 6.5.0
=> CLOUDSTACK-9525 add support for windows 10 guest os in xenserver 6.5

plugins/storage/volume/solidfire/pom.xml, plugins/storage/volume/solidfire/src/org/apache/cloudstack/storage/datastore/driver/SolidFirePrimaryDataStoreDriver.java, plugins/storage/volume/solidfire/src/org/apache/cloudstack/storage/datastore/lifecycle/SolidFirePrimaryDataStoreLifeCycle.java, plugins/storage/volume/solidfire/src/org/apache/cloudstack/storage/datastore/lifecycle/SolidFireSharedPrimaryDataStoreLifeCycle.java, plugins/storage/volume/solidfire/src/org/apache/cloudstack/storage/datastore/util/SolidFireUtil.java, test/integration/plugins/solidfire/TestAddRemoveHosts.py, test/integration/plugins/solidfire/TestManagedSystemVMs.py, test/integration/plugins/solidfire/TestSnapshots.py, test/integration/plugins/solidfire/TestVolumes.py, test/integration/plugins/solidfire/util/sf_util.py
SolidFire has recently released an official SDK for Java.
I have converted the SolidFire storage plug-ins to make use of this new SDK.
http://search.maven.org/#artifactdetails%7Ccom.solidfire%7Csolidfire-sdk-java%7C1.2.0.29%7Cjar
=> Switched to the official SolidFire SDK for Java

engine/orchestration/src/com/cloud/agent/manager/AgentManagerImpl.java, engine/orchestration/src/com/cloud/vm/VirtualMachineManagerImpl.java, plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/KVMHAChecker.java
CLOUSTACK-9465 Several log refactoring/improvement suggestions.
There are two scenarios of logging which needs refactoring/improvement: 
Method invocation replaced by variable
This means that in the logging code, the method invocation is pre-defined as a variable. for simplicity,          the method invocation should be replaced by the variable.
Delete variable which must be null
The variable in the logging code is null, there is no need to put the variable there.
=> Made the changes to improve logging.

plugins/hypervisors/vmware/src/com/cloud/hypervisor/vmware/manager/VmwareStorageManagerImpl.java
Continuing work by @maneesha-p in #798 
This closes #798
=> CLOUDSTACK-8830 - [Vmware] VM snapshot fails for 12 min after instance creation (Targeted for 4.9)

framework/db/src/com/cloud/utils/db/TransactionLegacy.java
timed out by the mysql server then refresh it
=> CLOUDSTACK-9460: For long running transactions, if the connection is

engine/api/src/com/cloud/vm/VirtualMachineManager.java, engine/api/src/org/apache/cloudstack/engine/cloud/entity/api/VirtualMachineEntity.java, engine/orchestration/src/com/cloud/vm/VirtualMachineManagerImpl.java, engine/orchestration/src/org/apache/cloudstack/engine/cloud/entity/api/VMEntityManager.java, engine/orchestration/src/org/apache/cloudstack/engine/cloud/entity/api/VMEntityManagerImpl.java, engine/orchestration/src/org/apache/cloudstack/engine/cloud/entity/api/VirtualMachineEntityImpl.java, server/src/com/cloud/vm/UserVmManagerImpl.java
https://issues.apache.org/jira/browse/CLOUDSTACK-9451
Re-doing against 4.8 since this is a bug, not a feature.
=> CLOUDSTACK-9451

systemvm/patches/debian/config/opt/cloud/bin/cs/CsDhcp.py
Fixes merge conflict issue incorrectly fixed during a fwd-merge in 825935
from PR #1766.
=> systemvm: Fix regression from fwd-merging PR #1766

plugins/hypervisors/xenserver/src/com/cloud/hypervisor/xenserver/resource/Xenserver625StorageProcessor.java
The race condition will happen whenever there are multiple primary storages and the CS tries to mount the secondary store to xenserver host simultaneously.
Due to synchronised block one mount will be successful and other thread will get the already mounted SR. Without the fix the two thread will try to mount it parallely and one will fail on Xenserver.
=> Cloudstack 9586: When using local storage with Xenserver prepareTemplate does not work with multiple primary store

test/integration/component/test_templates.py
Fixes regression in component test `test_templates.py`
=> CLOUDSTACK-9594: Fix regression in test_templates

engine/schema/src/com/cloud/usage/dao/UsageStorageDaoImpl.java, engine/schema/test/com/cloud/usage/dao/UsageStorageDaoImplTest.java, engine/schema/test/resources/db.properties
This is happening as the zone id is not part of the query.  Zone id is added to the query and unit tests are also added
=> CLOUDSTACK-8908 After copying the template charging for that template is getting stopped

server/src/com/cloud/template/TemplateManagerImpl.java
Fixes failing smoke tests due to enviroment issues or corner cases:
- Fixes NPE in Template Manager
=> CLOUDSTACK-9688: Fix failing smoke tests

engine/schema/src/com/cloud/upgrade/DatabaseUpgradeChecker.java, engine/schema/src/com/cloud/upgrade/dao/Upgrade4910to4920.java, engine/schema/test/com/cloud/upgrade/DatabaseUpgradeCheckerTest.java, setup/db/db/schema-4910to4920-cleanup.sql, setup/db/db/schema-4910to4920.sql
Upgrade paths added so PRs such as #1711 can use it.
=> schema: Upgrade path from 4.9.1.0 to 4.9.2.0

README.md
Here's a screenshot to confirm the UI change:
Pinging for review -- @abhinandanprateek @chipchilders @chiradeep @DaanHoogland  @imduffy15 @K0zka @PaulAngus @nvazquez @terbolous @murali-reddy @NuxRo @wido @mike-tutkowski @swill @resmo @sebgoa @wilderrodrigues @kiwiflyer  @pyr @pdion891 @koushik-das @JayapalUradi  @karuturi @kishankavala @milamberspace @mlsorensen @serverchief @jlk @pdube @syed and many others!
Since this a text/UI change, please accept this without explicit integration test results, of course as long as Travis is green :)
Happy holidays everyone!
=> README: Happy Christmas, happy holidays!

server/src/com/cloud/network/router/VirtualNetworkApplianceManagerImpl.java
ISSUE
============
In the management server log there is an error
2016-10-01 00:07:31,670 ERROR [c.c.h.v.r.VmwareResource] (DirectAgent-417:ctx-e8c89b3f strmg-esx-01, cmd: GetRouterAlertsCommand) (logid:7beb3819) Command failed due to Exception: java.io.IOException
Message: There was a problem while connecting to 0.0.0.0:3922 
In case of basic zone and VMWare ESXi host, the NIC 2 always gets 0.0.0.0 as IP address. Looks like we are generating an error for connecting through this invalid IP.
2016-10-01 04:37:31,680 DEBUG [c.c.a.m.AgentManagerImpl] (RouterStatusMonitor-1:ctx-8880f9c8) (logid:946838b8) Details from executing class com.cloud.agent.api.routing.GetRouterAlertsCommand: Command failed due to Exception: java.io.IOException
Message: There was a problem while connecting to …
=> CLOUDSTACK-9649: In the management server log there is an error

engine/schema/src/com/cloud/configuration/dao/ResourceCountDaoImpl.java, engine/schema/src/com/cloud/network/dao/NetworkVO.java, plugins/hypervisors/vmware/src/com/cloud/hypervisor/vmware/resource/VmwareResource.java, server/src/com/cloud/configuration/ConfigurationManagerImpl.java, server/src/com/cloud/network/firewall/FirewallManagerImpl.java, server/src/com/cloud/network/router/VirtualNetworkApplianceManagerImpl.java, systemvm/patches/debian/config/opt/cloud/bin/configure.py, test/integration/smoke/test_volumes.py, test/integration/smoke/test_vpc_vpn.py, vmware-base/src/com/cloud/hypervisor/vmware/mo/HostMO.java, vmware-base/src/com/cloud/hypervisor/vmware/mo/HypervisorHostHelper.java, vmware-base/src/com/cloud/hypervisor/vmware/mo/VirtualMachineMO.java
This merges several PRs in this PR, this is for speeding up test efforts.
=> 4.9 multiplex testing

scripts/vm/hypervisor/xenserver/setup_heartbeat_sr.sh
=> Smoke tests xen:iscsi fix

ui/scripts/ui-custom/zoneWizard.js
Hardcoded label (label.remove.this.physical.network) appears on the Add zone wizard
=> CLOUDSTACK-9731: Hardcoded label appears on the Add zone wizard

test/integration/testpaths/testpath_restore_vm.py
Changing PR title and commit message 
In continuation with PR #1411  and  #667
=> CLOUDSTACK-8717: Failed to start instance after restoring the running instance 

test/integration/component/test_vpn_users.py
Please refer to JIRA ticket for more details
https://issues.apache.org/jira/browse/CLOUDSTACK-9117
Following is the result info:
Test to add TCP Port Forwarding rule for specific ports(500,1701 and 4500) in VPN ... === TestName: test_08_add_TCP_PF_Rule_In_VPN | Status : SUCCESS ===
ok
---
Ran 1 test in 166.799s
OK
=> Marvin test to verify that adding TCP ports 500,4500 and 1701 in vpn should not fail

systemvm/patches/debian/config/etc/sysctl.conf
Updated the somaxconn value to detault value 65535
=> CLOUDSTACK-9715: Update somaxconn value to default value

setup/db/db/schema-4920to41000.sql
centos 6.6, centos 6.7, rhel 6.6, rhel 6.7, windows server 2016, rhel
7.2, centos 7.2
This closes #1244
=> added more guest os

server/src/com/cloud/configuration/ConfigurationManagerImpl.java
listNetworkOfferings API is listing all the offerings which has same prefix in their name
=> BUG-ID:CLOUDSTACK-9678

setup/bindir/cloud-get-vm-data-configdrive.in, setup/bindir/cloud-set-guest-password-configdrive.in, setup/bindir/cloud-set-guest-sshkey-configdrive.in, setup/bindir/cloud-set-windows-guest-password-configdrive.bat.in
Added the guest vm scripts for set/get the vm data, password and ssh keys
=> CLOUDSTACK-8324: config drive data set/get scripts for the guest vm

plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java, server/src/com/cloud/storage/VolumeApiServiceImpl.java
Updated hardcoded value with max data volumes limit from hypervisor capabilities.
=> CLOUDSTACK-9794: Unable to attach more than 14 devices to a VM

plugins/hypervisors/vmware/src/com/cloud/storage/resource/VmwareStorageProcessor.java
Updated the template_spool_ref table with the correct template (VMware - OVA file) size.
=> CLOUDSTACK-9720: [VMware] template_spool_ref table is not getting updated with correct template physical size in template_size column.

.gitignore, debian/cloudstack-management.install, debian/cloudstack-management.postinst, debian/control, debian/rules, packaging/build-deb.sh, packaging/systemd/cloudstack-management.default.ubuntu, packaging/systemd/cloudstack-management.service.ubuntu, python/lib/cloudutils/serviceConfigServer.py
This extends work from @ustcweizhou from https://github.com/apache/cloudstack/pull/1950 by fixing some build issues to make this work with Ubuntu 14.04 and 16.04.
This closes #1950
=> [master/4.10+] CLOUDSTACK-9462: Support for Ubuntu 14.04/16.04 with tomcat6/tomcat7

client/pom.xml, python/lib/cloudutils/serviceConfigServer.py
This fixes packaging/build regression from #2036
Pinging for review - @wido @rafaelweingartner @DaanHoogland 
=> CLOUDSTACK-9858: remove midonet plugin dependency on client packaging

plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java, plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java, plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java, setup/db/db/schema-4920to41000.sql, test/integration/smoke/test_deploy_virtio_scsi_vm.py, tools/marvin/marvin/lib/base.py, ui/scripts/templates.js
This is an initial implementation that we have working in the lab.
[win_virtio_scsi.xml.zip](https://github.com/apache/cloudstack/files/788014/win_virtio_scsi.xml.zip)
@wido @syed Would love to get some feedback on this approach.
=> CLOUDSTACK-8239 Add VirtIO SCSI support for KVM hosts

core/src/com/cloud/network/resource/TrafficSentinelResource.java
Url generated by CCP to request traffic sentinel for usage stats is too long causing HTTP 414 Request-URI Too Long error response. This is because we are using the GET request to send the data to the traffic sentinel instance and url size exceeds the max length of GET request.
Changing the request method to POST
This PR closes PR #1418
=> CLOUDSTACK-9728: Fixed traffic sentinel HTTP 414 error response

plugins/hypervisors/vmware/src/com/cloud/hypervisor/vmware/resource/VmwareResource.java
VMware CPU Utilised  value is in Mhz , in MS value is displayed directly.
If CPU utilised is 500Mhz,  UI value is displayed as 500 %
Planned to restrict changes in resource layer VmwareResource.java, but cpu allocated to VM by VMware is not same as  allocated in the service offering.
If CPU limit flag is set to false in  service offerings  the Allocated CPU can go beyond what is assigned.
So picking actual user assigned Total CPU from database for calculating percentage.  
It is expected that percentage would go beyond 100 percent.
so changes are made in UserVmJoinDaoImpl.java
=> Management Server UI (VM statistics page) CPU Utilized value is incorrect.

api/src/org/apache/cloudstack/api/command/user/vpn/CreateVpnCustomerGatewayCmd.java
Also see 110f66ff13a81671dadd9b2c527d232ceb2d5411 and https://github.com/apache/cloudstack/pull/879
=> follow-up CLOUDSTACK-8793: fix missing doc when projectid was added

engine/orchestration/src/com/cloud/vm/VirtualMachineManagerImpl.java
=> CLOUDSTACK-9208: Assertion Error in VM_POWER_STATE handler- Fixed

engine/schema/src/org/apache/cloudstack/storage/datastore/db/VolumeDataStoreDao.java, engine/storage/src/org/apache/cloudstack/storage/image/db/VolumeDataStoreDaoImpl.java, engine/storage/volume/src/org/apache/cloudstack/storage/volume/VolumeServiceImpl.java
Update the volume id in volume_store_ref table to newly created volume for migration
=> CLOUDSTACK-8833: Fixed  Generating url and migrate volume to another storage , resulting two entry in UI and listvolume is not working for that volume

test/integration/component/maint/test_escalations_instances.py, test/integration/component/test_escalations_instances.py, test/integration/component/test_escalations_vmware.py, test/integration/component/test_project_resources.py, test/integration/component/test_project_usage.py, test/integration/component/test_usage.py, tools/marvin/marvin/config/test_data.py, tools/marvin/marvin/lib/base.py
Addressed all review comments. Changed all URL to pubic available url where ever possible . For few  tests needing rhel7 template or windows server templates added a comment in test case to provide a valid urls for those templates before executing those test cases
=> Automated Cloudstack bugs 9277 9276 9275 9274 9273 9179 9178 9177 

systemvm/patches/debian/config/opt/cloud/bin/configure.py
I have removed unnecessary VPN disconnects when updating the VPN configuration (or any configuration which changes public IP addresses).  I have verified the functionality still behaves as expected with these changes to the Remote Access VPN config.
In addition, I have also added a fix to the S2S VPN to not make it drop the VPN connection when other networking config is changed.  I was not able to reproduce the problem described in https://github.com/MissionCriticalCloud/cosmic/pull/339 manually, but we have experienced similar issues in our production environment which makes me think this is a worthwhile change.  I have tested that the functionality still behaves as expected with this change, so I have added it to this PR as well.
=> CLOUDSTACK-9878: remove unnecessary VPN drops

engine/schema/src/com/cloud/vm/dao/UserVmDaoImpl.java
Description:
=========
Please see the description in https://issues.apache.org/jira/browse/CLOUDSTACK-9708
Resolution:
========
- The  SearchBuilder instance is a class scope variable that should be instantiated in the constructor.
- Since it was being instantiated in the scope of the method, parallel calls to the method will overwrite the class variable.
=> CLOUDSTACK-9708: Router deployment failed due to two threads start VR simultaneously.

systemvm/patches/debian/config/opt/cloud/bin/configure.py, systemvm/patches/debian/config/opt/cloud/bin/cs/CsAddress.py, systemvm/patches/debian/config/opt/cloud/bin/cs/CsHelper.py, systemvm/patches/debian/config/opt/cloud/bin/cs/CsNetfilter.py
Added the checking exist status of iptables command.
On exception return error so that it will be populated to management server.
Also cleaned some of the repeated iptables commands.
=> CLOUDSTACK-9848: Added  exit status checking for the iptables commands

vmware-base/src/com/cloud/hypervisor/vmware/mo/DistributedVirtualSwitchMO.java
Jira
===
CLOUDSTACK-3223 Exception observed while creating CPVM in VMware Setup with DVS
Issue
=====
Exception observed while creating CPVM in VMware Setup with DVS.
Observed error `"StartCommand failed due to Exception: com.vmware.vim25.AlreadyExists."`
This is due to concurrent attempts to create same dv portgroup on same dvSwitch by
manager threads of CPVM and SSVM when both are started at same time.
Fix
===
Synchronize api calls to create/update dvportgroup.
Also maintaing local cache to avoid multiple fetch api calls to vCenter
when multiple threads try to create same object.
Signed-off-by: Sateesh Chodapuneedi <sateesh.chodapuneedi@accelerite.com>
=> CLOUDSTACK-3223 Exception observed while creating CPVM in VMware Setup with DVS

test/integration/testpaths/testpath_netmask.py
CLOUDSTACK-9168: Updates automation testscript 'testpath_netmask.py'.
Reference to #1245
=> CLOUDSTACK-9168: TestPath to check if wrong value is inserted into nics table netmask field when creating a VM.

services/secondary-storage/controller/src/org/apache/cloudstack/secondarystorage/SecondaryStorageManagerImpl.java, systemvm/patches/debian/config/etc/init.d/cloud-early-config
Added a new configuration paremetar "ntp.server.list" to configure NTP server ip in NTP settings of SSVM
=> CLOUDSTACK-9835 : To make management server and SSVM to be in time sync

api/src/com/cloud/user/AccountService.java, api/src/org/apache/cloudstack/api/command/admin/user/GetUserKeysCmd.java, api/src/org/apache/cloudstack/api/response/UserResponse.java, plugins/network-elements/juniper-contrail/test/org/apache/cloudstack/network/contrail/management/MockAccountManager.java, server/src/com/cloud/api/ApiDBUtils.java, server/src/com/cloud/server/ManagementServerImpl.java, server/src/com/cloud/user/AccountManager.java, server/src/com/cloud/user/AccountManagerImpl.java, server/test/com/cloud/user/AccountManagerImplTest.java, server/test/com/cloud/user/MockAccountManagerImpl.java, tools/marvin/marvin/cloudstackTestClient.py, ui/scripts/accounts.js
=> CLOUDSTACK-9099: SecretKey is returned from the APIs

api/src/org/apache/cloudstack/api/Parameter.java, api/src/org/apache/cloudstack/api/command/admin/user/UpdateUserCmd.java, server/src/com/cloud/api/ApiServer.java
Now, Updating the password via UpdateUser API is not allowed via integration port
=> CLOUDSTACK-9705: Unauthenticated API allows Admin password reset

plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
Fixes issue caused to a PR-refactoring from #2108, reported by
@borisstoyanov
Pinging - @karuturi @borisstoyanov and others for a quick review
=> [BLOCKER] CLOUDSTACK-9860: Fix stackoverflow issue

engine/storage/volume/src/org/apache/cloudstack/storage/volume/VolumeServiceImpl.java, plugins/hypervisors/vmware/src/com/cloud/hypervisor/vmware/resource/VmwareResource.java
This PR is a rebase of PR #2147 by @mike-tutkowski 
The target branch is changed to master from the release branch.
=> Two fixes for RC3 by @mike-tutkowski

systemvm/patches/debian/config/opt/cloud/bin/vr_cfg.sh, test/integration/plugins/nuagevsp/test_nuage_internal_dns.py
Executing /opt/cloud/bin/configure.py without parameters, gives IndexError: Index out of range
May not be necessary to configure everything, as only these 2 are deferred.
=>  	CLOUDSTACK-9980: Fix for DNS after network restart with clean up.

.travis.yml
Issue: https://github.com/travis-ci/travis-ci/issues/8075
Pinging for review/merge - @karuturi @wido @DaanHoogland 
This can be accepted if Travis passes.
=> Travis: use oraclejdk8 for 4.10+

test/integration/component/test_escalations_vmware.py
#ISSUE
VM snapshot fails for 12 min after instance creation
#FIX 
This PR adds a marvin test case for the fix at #1677
Test case add to check whether VMSnapshot is successful from the moment the VM is ready
=> CLOUDSTACK-8830 : VM snapshot creation fails for 12 min 

api/src/org/apache/cloudstack/api/ApiConstants.java, api/src/org/apache/cloudstack/api/command/admin/domain/ListDomainsCmd.java, server/src/com/cloud/api/ApiDBUtils.java, server/src/com/cloud/api/query/QueryManagerImpl.java, server/src/com/cloud/api/query/ViewResponseHelper.java, server/src/com/cloud/api/query/dao/DomainJoinDao.java, server/src/com/cloud/api/query/dao/DomainJoinDaoImpl.java, ui/scripts/accounts.js, ui/scripts/configuration.js, ui/scripts/system.js
The resource limitation causes long time while execute listDomains API. The resources are not needed in some cases so that the execution time will be reduced.
=> CLOUDSTACK-9405: add details parameter in listDomains API to reduce the execution time

api/src/org/apache/cloudstack/api/response/LoadBalancerResponse.java, server/src/com/cloud/api/ApiResponseHelper.java
add zonename in response for consistency.
=> CLOUDSTACK-8873: add zonename in load balancer response

core/src/com/cloud/agent/api/SecStorageVMSetupCommand.java
=> CLOUDSTACK-9891 no password log for copy user in ssvm setup

engine/schema/src/com/cloud/storage/dao/VMTemplateDaoImpl.java, framework/db/pom.xml, framework/db/src/com/cloud/utils/db/GenericDaoBase.java
this also fixes the issue in PR #1716
=> CLOUDSTACK-8186: make setRemoved to null possible

tools/cli/README
=> repo has moved

ui/scripts/system.js
When the page for internal LB VM's is opened, it is continuously loading but not giving list of internal LB VM's
=> CLOUDSTACK-10026 Page for Internal LB VM stucking while loading

ui/scripts/vpc.js
In VPC while scrolling down the Internal LB's list it is continuously giving the Internal LB's by repeating the same list.
=> CLOUDSTACK-10027 Repeating the same list for Internal LB in VPC

plugins/hypervisors/xenserver/src/com/cloud/hypervisor/xenserver/resource/XenServerStorageProcessor.java
Remove unused code from "com.cloud.hypervisor.xenserver.resource.XenServerStorageProcessor" class and modify some methods access level.
Remove unused methods:
- com.cloud.hypervisor.xenserver.resource.XenServerStorageProcessor.getSRByNameLabel(Connection,
String)
- com.cloud.hypervisor.xenserver.resource.XenServerStorageProcessor.getNfsSR(Connection,
StorageFilerTO)
- com.cloud.hypervisor.xenserver.resource.XenServerStorageProcessor.directDownloadHttpTemplate(CopyCommand,
DecodedDataObject, DecodedDataObject)
- com.cloud.hypervisor.xenserver.resource.XenServerStorageProcessor.execute(AttachPrimaryDataStoreCmd)
change access level:
- from public to private:
com.cloud.hypervisor.xenserver.resource.XenServerStorageProcessor.swiftUpload(Connection,
SwiftTO, String, String, String, Boolean, …
=> CLOUDSTACK-9314 - Remove unused code from XenServerStorageProcessor and change methods access level

engine/orchestration/src/org/apache/cloudstack/engine/orchestration/VolumeOrchestrator.java
This can happen when you stop a VM in one cluster and start a VM in another cluster. When the VM starts in a new cluster, we don't add a new VAG and hence it fails to start. This PR ensures that we call `grantAccess` to the VM that gets started which will fix the access issue.
cc: @mike-tutkowski
=> [CLOUDSTACK-10061][Managed Storage] When starting a VM, make sure it has the correct volume access group

test/integration/smoke/test_hostha_kvm.py
Fixes some intermittent host-ha KVM failures seen in recent trillian test runs.
=> CLOUDSTACK-9782: Fix intermittent host-ha KVM test failures

api/src/com/cloud/vm/VmDetailConstants.java, server/src/com/cloud/vm/UserVmManagerImpl.java, server/src/com/cloud/vm/snapshot/VMSnapshotManagerImpl.java
fix bug where disk controller specified via vm details throws
a NumberFormatException, since "scsi" is not a number.
=> CLOUDSTACK-10056

client/src/org/apache/cloudstack/ServerDaemon.java
- add option to allow loading another webapp (cloudstack-ui for example)
- remove `jetty` in param keywords as it's better to stay agnostic
=> CLOUDSTACK-10012: ServerDaemon customization

engine/orchestration/src/org/apache/cloudstack/engine/orchestration/VolumeOrchestrator.java
Simply remove unrelated text from error message
=> CLOUDSTACK-10122: Unrelated error message

pom.xml, services/console-proxy/server/src/com/cloud/consoleproxy/ConsoleProxyAjaxHandler.java, services/console-proxy/server/src/com/cloud/consoleproxy/ConsoleProxyClientBase.java, services/console-proxy/server/src/com/cloud/consoleproxy/ConsoleProxyVncClient.java, services/console-proxy/server/src/com/cloud/consoleproxy/InputEventType.java, systemvm/js/ajaxviewer.js, systemvm/js/jquery.flot.navigate.js
When mouse is scrolled in VM Console it is not working.
=> CLOUDSTACK-10051 Mouse Scrolling is not working in instance VM console

server/src/com/cloud/network/vpn/Site2SiteVpnManagerImpl.java
Added accepting domain for the s2s vpn customer vpn gateway.
=> CLOUDSTACK-9961: Fixed adding domain in vpn customer gateway

api/src/com/cloud/storage/Storage.java
a customer needs support for overprovisioning for ext file system
=> CLOUDSTACK-10133 Local storage overprovisioning for ext file system

debian/cloudstack-agent.postinst, packaging/systemd/cloudstack-agent.service
The implementation does check and fix during installation process (Ubuntu 14.04/16.04)
=> CLOUDSTACK-10138: Load br_netfilter in security_group management script

.travis.yml, test/integration/component/test_affinity_groups_projects.py, test/integration/component/test_allocation_states.py, test/integration/component/test_cpu_domain_limits.py, test/integration/component/test_organization_states.py, test/integration/component/test_project_resources.py, test/integration/component/test_vpc.py, tools/marvin/marvin/config/test_data.py
ping @rhtyd @DaanHoogland @nvazquez @PaulAngus for review
=> CLOUDSTACK-10070: Fixing some component tests and adding them in travis

plugins/network-elements/nuage-vsp/src/com/cloud/network/manager/NuageVspManagerImpl.java, ui/scripts/network.js
https://issues.apache.org/jira/browse/CLOUDSTACK-10164
=> CLOUDSTACK-10164: bugfix allow users to create a VPC through the UI.

server/src/com/cloud/resource/ResourceManagerImpl.java
1. Create a cluster with three hosts, two of them with GPU cards NVIDIA GRID K1 and GRID K2 and one normal host.
2. Deploy a VM with GRID K2 vGPU.
3. Stop the VM and try starting it on a different host. (Expect it to fail as there is only one host supporting that particular vGPU type)
4. The log shows it as failed operation, VM remains in the stopped state, yet the notification shows "Start Instance" as successful and no error message displays.
Root Cause:
=========
Earlier, it was failing with ArrayIndexOutOfBoundsException, when the list is empty and accessing the first element.
The error was only observed in Log, but was not showing in UI as it was not throwing any exception.
Hence the API call was in turn successful.
Solution:
=======
Added the …
=> CLOUDSTACK-10157: Wrong notification while migration.

engine/schema/src/com/cloud/network/dao/Site2SiteCustomerGatewayDao.java, engine/schema/src/com/cloud/network/dao/Site2SiteCustomerGatewayDaoImpl.java, server/src/com/cloud/network/vpn/Site2SiteVpnManagerImpl.java
See https://issues.apache.org/jira/browse/CLOUDSTACK-10077
=> CLOUDSTACK-10077: allow to have different VPN customer gateway configs for same gateway IP

plugins/metrics/src/org/apache/cloudstack/metrics/MetricsServiceImpl.java
The host_view may contain duplicate entries when hosts have tags.
Changing the host_view may cause unseen regressions so
to fix the issues we've modified the zone/cluster metrics code to use
the `host` table (hostdao) to iterate through the list of hosts in a
cluster during zone/cluster metrics listing.
=> CLOUDSTACK-9986: Use host table to iterate for zone/cluster metrics

plugins/network-elements/netscaler/src/com/cloud/network/element/NetscalerElement.java, ui/scripts/configuration.js
NetScaler can work in inline mode also along with other Firewall devices. Enabled netscaler inline mode capability
=> Bug-Id: CLOUDSTACK-9800 Enabled netscaler inline mode. Added corresponding changes in UI

README.md
Happy holidays, requesting a review!
=> README: Happy Holidays, may the cloud be with you in 2018!

core/pom.xml, plugins/event-bus/rabbitmq/pom.xml, plugins/outofbandmanagement-drivers/nested-cloudstack/pom.xml, plugins/storage/volume/cloudbyte/pom.xml, plugins/user-authenticators/ldap/pom.xml, pom.xml, usage/pom.xml
Upgrades spring, jetty and misc dependencies
Pinging for review - @marcaurele @rafaelweingartner @borisstoyanov @nvazquez @DaanHoogland @wido and others
=> CLOUDSTACK-9456: Upgrade spring, jetty and misc dependencies

server/src/com/cloud/tags/TaggedResourceManagerImpl.java
This fixes the issue that a non-root user cannot tag a network ACL item
and after the fix a non-root user still cannot tag a globally defined
ACL item and only the ACLs they have access to.
=> CLOUDSTACK-10166: Get accountId and domainId from VPC when tagging a NetworkACL as a user

api/src/org/apache/cloudstack/api/command/admin/network/MigrateNetworkCmd.java, api/src/org/apache/cloudstack/api/command/admin/network/MigrateVPCCmd.java, plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtReplugNicCommandWrapper.java, plugins/network-elements/nuage-vsp/src/com/cloud/api/commands/AssociateNuageVspDomainTemplateCmd.java, plugins/network-elements/nuage-vsp/src/com/cloud/api/commands/ListNuageVspDomainTemplatesCmd.java, plugins/network-elements/nuage-vsp/src/com/cloud/api/commands/ListNuageVspGlobalDomainTemplateCmd.java, test/integration/plugins/nuagevsp/test_nuage_network_migration.py, test/integration/smoke/test_migration.py, tools/marvin/marvin/config/test_data.py
Tackles review comments given on #2259 after the merge.
Co-Authored-By: Raf Smeets <raf.smeets@nuagenetworks.net>
Co-Authored-By: Kris Sterckx <kris.sterckx@nuagenetworks.net>
=> CLOUDSTACK-10024: Network Migration: Tackle review comments

framework/db/src/com/cloud/utils/db/GenericDao.java, framework/db/src/com/cloud/utils/db/GenericDaoBase.java, framework/db/src/com/cloud/utils/db/SqlGenerator.java, server/src/com/cloud/api/query/QueryManagerImpl.java, server/test/com/cloud/user/MockUsageEventDao.java
**Description:**
The db queries in listTemplateAPI could be optimized to get unique results from the database which could help in reducing the listTemplate API response time.
=> CLOUDSTACK-10065: Optimize SQL queries in listTemplate API to improve performance

api/src/com/cloud/user/ResourceLimitService.java, server/src/com/cloud/api/ApiDBUtils.java, server/src/com/cloud/api/query/QueryManagerImpl.java, server/src/com/cloud/api/query/ViewResponseHelper.java, server/src/com/cloud/api/query/dao/DomainJoinDaoImpl.java, server/src/com/cloud/api/query/vo/DomainJoinVO.java, server/src/com/cloud/resourcelimit/ResourceLimitManagerImpl.java, server/test/com/cloud/vpc/MockResourceLimitManagerImpl.java, test/integration/smoke/test_accounts.py
**Description:**
While creating the response object for the 'listDomain' API, several database calls are triggered to fetch details like parent domain, project limit, IP limit, etc. These database calls are triggered for each record found in the main fetch query, which is causing the response to slow down.
**Fix:**
The database transactions are reduced to improve response of the Listdomain API
=> CLOUDSTACK-10104:Optimize database transactions in ListDomain API to improve performance

plugins/dedicated-resources/src/org/apache/cloudstack/dedicated/DedicatedResourceManagerImpl.java, server/src/com/cloud/dc/dao/DedicatedResourceDao.java, server/src/com/cloud/dc/dao/DedicatedResourceDaoImpl.java, server/src/com/cloud/deploy/DeploymentPlanningManagerImpl.java
=> CLOUDSTACK-9896: API: listDedicatedXXX should respect pagination

engine/schema/src/com/cloud/storage/dao/SnapshotDao.java, engine/schema/src/com/cloud/storage/dao/SnapshotDaoImpl.java, server/src/com/cloud/vm/UserVmManagerImpl.java, test/integration/component/test_assign_vm.py
Steps to reproduce issue
1. Deploy a VM
2. Take snapshot of the root volume
3. Delete the snapshot
4. Before the garbage collector has run, shutdown the VM and assign the VM to other user.
5. When garage collector executes NPE shows in the logs.
=> CLOUDSTACK-9921: NPE when storage garbage collector is running.

plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtMigrateCommandWrapper.java
This is an issue that was introduced in the code-review process of #2298.
What is probably the simplest solution (and what this PR does) is to store the result of MapUtils.isNotEmpty(mapMigrateStorage) before passing mapMigrateStorage to the replaceStorage method.
The replaceStorage method can mutate the data in the passed-in map, thus leading to a different result for MapUtils.isNotEmpty(mapMigrateStorage) later on (and causing an issue for online storage migration).
If we just store the value up front and refer to it later, we, of course, get the same (boolean) result and online storage migration works properly.
A more long-term solution (and one that I plan on implementing for 4.12) would be to make a shallow copy of the map inside of replaceStorage so that replaceStorage does not …
=> CLOUDSTACK-10244: KVM online storage migration fails

server/src/main/java/com/cloud/network/NetworkModelImpl.java, server/src/main/java/com/cloud/network/NetworkServiceImpl.java
Hi, 
Just fixing a trivial typo in exception message.
Cheers
Bruno
=> Fix exception message typos

agent/src/com/cloud/agent/direct/download/HttpsDirectTemplateDownloader.java
JIRA Ticket: https://issues.apache.org/jira/browse/CLOUDSTACK-10251
Failure on HTTPS downloader for Direct Download templates on KVM.
Reason: Incorrect request caused NullPointerException getting the response InputStream
=> CLOUDSTACK-10251: HTTPS downloader for Direct Download templates failure

plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtMigrateCommandWrapper.java
JIRA Ticket: https://issues.apache.org/jira/browse/CLOUDSTACK-10305
There is a race condition in the monitoring of the migration process on KVM. If the monitor wakes up in the tight window after the migration succeeds, but before the migration thread terminates, the monitor will get a LibvirtException “Domain not found: no domain with matching uuid” when checking on the migration status. This in turn causes CloudStack to sync the VM state to stop, in which it issues a defensive StopCommand to ensure it is correctly synced.
Fix: Prevent `LibvirtException: "Domain not found"` caused by the call to `dm.getInfo()`
=> CLOUDSTACK-10305: Rare race condition in KVM migration

systemvm/debian/etc/rsyslog.conf, systemvm/debian/etc/systemd/system/cloud-postinit.service, tools/appliance/systemvmtemplate/scripts/finalize.sh
Minor fixes for new VR template after testings.
=> [4.11] VR: minor fixes

engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
Since CloudStack 4.10 Basic Networking supports IPv6 and thus
should be allowed to be specified when creating a network.
=> CLOUDSTACK-10221: Allow IPv6 when creating a Basic Network

server/src/main/java/com/cloud/api/dispatch/ParamProcessWorker.java
The description of the problem:
https://issues.apache.org/jira/browse/CLOUDSTACK-10334
I just added stack traces information to those two logging statements, so that the exception type can be generated to the logs.
=> CLOUDSTACK-10334: Fix inadequate information for handling catch clauses

server/src/main/java/com/cloud/test/PodZoneConfig.java
=> Fix Successfully typo

packaging/centos7/cloud.spec
=> CLOUDSTACK-10287 package require open jdk 1.8

PULL_REQUEST_TEMPLATE.md
In cloudstack no-one person or organisation will ever be able to run all tests involving all kinds of hardware. make the checklist more realistic in this perspective.
=> indicate scope of tests in checklist

ui/css/cloudstack3.css
The host/alert dashboard panels are on the top side, the dashboard
statistics page gets less room. This increases the panel by 100px for
zone dashboard and decreases the host/alert panels by 100px.
UI changes + refresh.
Testing
=> ui: Make zonal dashboard larger

api/src/main/java/org/apache/cloudstack/api/command/user/firewall/CreateFirewallRuleCmd.java, api/src/main/java/org/apache/cloudstack/api/command/user/firewall/CreatePortForwardingRuleCmd.java, engine/schema/src/main/java/com/cloud/usage/dao/UsageDaoImpl.java, plugins/event-bus/rabbitmq/src/main/java/org/apache/cloudstack/mom/rabbitmq/RabbitMQEventBus.java, plugins/hypervisors/hyperv/src/main/java/com/cloud/ha/HypervInvestigator.java, plugins/hypervisors/ovm/src/main/java/com/cloud/ovm/hypervisor/OvmFencer.java, plugins/hypervisors/simulator/src/main/java/com/cloud/ha/SimulatorFencer.java, plugins/hypervisors/xenserver/src/main/java/com/cloud/ha/XenServerFencer.java, plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/CitrixResourceBase.java, server/src/main/java/com/cloud/ha/KVMFencer.java, server/src/main/java/com/cloud/server/ConfigurationServerImpl.java
The description of the problem:
https://issues.apache.org/jira/browse/CLOUDSTACK-10315
I modified some stack traces information to those logging statements with the same log messages, make their stack trace consistent.
Testing
=> Update inconsistent debugging info in catch block

ui/scripts/accountsWizard.js, ui/scripts/cloudStack.js, ui/scripts/globalSettings.js, ui/scripts/instanceWizard.js, ui/scripts/instances.js, ui/scripts/sharedFunctions.js, ui/scripts/storage.js, ui/scripts/system.js, ui/scripts/vpc.js, ui/scripts/zoneWizard.js
While executing the find/replace, I found some blocks of duplicated code. Therefore, I extracted the duplicated part to an utils file, and then removed the duplicated blocks.
Locally
Testing
=> Remove 'todb' in favor of 'encodeURIComponent'.

plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/BridgeVifDriver.java, plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/IvsVifDriver.java
The two methods are named as "setXXX",
actually, they are not setter but getter.
Thus, they should be renamed as "getXXX".
=> CLOUDSTACK-10364: Change the "setXXX" method names to "getXXX".

server/src/main/java/com/cloud/user/AccountManagerImpl.java
While working on other PRs I noticed that the singleton AccountManagerImpl had a reference for itself. That is not needed. Therefore, I removed it.
Smoke tests
Testing
=> Remove "self-injection" of AccountManagerImpl

ui/scripts/accounts.js
If the Request Header Size grows (for instance a cert chain of 8kb) it will fail to upload the SSL Cert.
This problem was raised on the issue [2558](https://github.com/apache/cloudstack/issues/2558)
Testing
=> Make uploadSslCert a POST request instead of a GET

ui/scripts/accounts.js
=> ui: Fixes #2558 use POST for uploadSslCert API request (#2661)

plugins/network-elements/nuage-vsp/src/com/cloud/network/manager/NuageVspManager.java, plugins/network-elements/nuage-vsp/src/com/cloud/network/manager/NuageVspManagerImpl.java
Nuage Plugin currently creates a Network Offering on startup.
We stop creating this as it is unused.
Ran regression test on a Nuage KVM setup.
Testing
=> CLOUDSTACK-10375: Don't create DefaultNuageVspSharedNetworkOfferingWithSGService

server/src/com/cloud/capacity/CapacityManagerImpl.java
This fixes and ensures that every VM has its capacity individually
calculated, with the initial override of 1.0f as overcommit ratio.
Testing
=> server: Calculate fresh capacity per VM

server/src/com/cloud/network/IpAddressManagerImpl.java
this supposedly fixes #2545, as reported by the issuer. Testing will need to be added as of now. 
Fixes: #2545
Testing
=> revert dedicate vlan code removal

ui/scripts/instanceWizard.js
Fixes: #2666
see #2666
Testing
=> conditional template filter

plugins/hypervisors/hyperv/src/com/cloud/hypervisor/hyperv/resource/HypervDirectConnectResource.java, vmware-base/src/com/cloud/hypervisor/vmware/mo/HostMO.java
I corrected two typos (from uanble to unable).
Testing
=> Fix two typos (from uanble to unable).

api/src/com/cloud/offering/NetworkOffering.java, engine/orchestration/src/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java, engine/schema/src/com/cloud/offerings/dao/NetworkOfferingDao.java, engine/schema/src/com/cloud/offerings/dao/NetworkOfferingDaoImpl.java, server/src/com/cloud/server/ConfigurationServerImpl.java
Add default L2 network offerings
Testing
=> Add default L2 network offerings

plugins/hypervisors/xenserver/src/org/apache/cloudstack/storage/motion/XenServerStorageMotionStrategy.java
Use the storage pool UUID rather than it's path to find it on XenServer hosts.
Fixes: #2685 
* Live migration between two XenServer hosts with local storage (different clusters)
* Live migration between two XenServer clusters with DefaultPrimary PreSetup shared SRs
Testing
=> Fixes #2685: broken SXM support

agent/src/com/cloud/agent/Agent.java
In some environments running the keystore cert renewal (as root user)
over an already connected agent connection may cause exception
such as: `sudo: sorry, you must have a tty to run sudo`. Since, all
agents - KVM, CPVM and SSVM run as root user, we don't need to run
the renewal scripts with sudo.
With this patch, created a KVM environment and ran `provisionCertificate` API on ssvm, cpvm and KVM agent to confirm that it worked as expected without the `sudo` since the owner process is `root`.
Testing
=> agent: Avoid sudo, renew certificates assuming root

server/src/com/cloud/network/element/ConfigDriveNetworkElement.java
Let ConfigDriveElement remember the new password, 
so it can be put on the ConfigDrive iso while vm is starting.
Testing
=> CLOUDSTACK-10381: Fix password reset / reset ssh key with ConfigDrive

engine/schema/resources/META-INF/db/schema-41100to41110.sql, engine/schema/src/com/cloud/upgrade/dao/Upgrade41100to41110.java, engine/schema/src/com/cloud/upgrade/dao/Upgrade421to430.java, plugins/user-authenticators/ldap/src/org/apache/cloudstack/ldap/LdapConfiguration.java
=> remove old config artifacts from update path

server/src/com/cloud/user/AccountManagerImpl.java
moveUser only works for users without API keys which beats the (one of the two) main purpose(s) of the moveUser API.
Fixes: #2707 
Testing
=> comply with api key constraint

debian/changelog, services/console-proxy/plugin/pom.xml, services/iam/plugin/pom.xml, services/iam/server/pom.xml, tools/marvin/setup.py
=> Fixes: #2725

CONTRIBUTING.md, PendingReleaseNotes
Also update the CONTRIBUTING file with a description of how to work
with this file.
=> Add a PendingRelease notes file

pom.xml
This bumps up the vmware jar dependency to 6.7.
Testing
=> maven: bump up vmware sdk jar to 6.7

engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
This PR fixes a typo in VirtualMachineManagerImpl.java
`Successfully cleanued up resources` -> `Successfully cleaned up`
Testing
=> Fix typo in VirtualMachineManagerImpl.java

plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
Found some variables throughout the code which are not being used.
They can be removed.
=> cleanup: Remove unused variables

client/conf/server.properties.in, client/src/main/java/org/apache/cloudstack/ServerDaemon.java
This is to have the possibility to completely disable
HTTP and only use HTTPS.
Testing
=> Make HTTP handler of embedded server to be configured

tools/appliance/builtin/template.json, tools/appliance/systemvmtemplate/template.json
Update ISO URLs to the latest as the old URLs are borken.
Testing
=> systemvm: Update ISO URLs to the latest

engine/orchestration/src/main/java/com/cloud/vm/VirtualMachinePowerStateSyncImpl.java, engine/schema/src/main/java/com/cloud/usage/dao/UsageDaoImpl.java, plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/XenServerStorageProcessor.java, plugins/network-elements/netscaler/src/main/java/com/cloud/network/resource/NetScalerControlCenterResource.java, plugins/network-elements/opendaylight/src/main/java/org/apache/cloudstack/network/opendaylight/api/resources/Action.java, plugins/network-elements/ovs/src/main/java/com/cloud/network/element/OvsElement.java, plugins/network-elements/ovs/src/main/java/com/cloud/network/guru/OvsGuestNetworkGuru.java, plugins/network-elements/ovs/src/main/java/com/cloud/network/ovs/OvsTunnelManagerImpl.java, plugins/user-authenticators/saml2/src/main/java/org/apache/cloudstack/saml/SAMLUtils.java, server/src/main/java/com/cloud/network/firewall/FirewallManagerImpl.java, server/src/main/java/com/cloud/network/router/VpcVirtualNetworkApplianceManagerImpl.java, server/src/main/java/com/cloud/resource/ResourceManagerImpl.java, server/src/main/java/org/apache/cloudstack/ca/CAManagerImpl.java
There are some possible copy and paste errors in the log messages (The logging statement was copied from an old place to a new place, but the message wasn't changed to adapt to the function of the new place).  I changed the logging messages to make them more adaptive to record the actual behaviours.
Testing
=> Fix some log messages that do not match with their function

server/src/com/cloud/vm/UserVmManagerImpl.java
I corrected a typo in server/src/com/cloud/vm/UserVmManagerImpl.java (presnt -> present)
Testing
=> Fix a typo in server/src/com/cloud/vm/UserVmManagerImpl.java

developer/pom.xml, engine/schema/src/com/cloud/upgrade/DatabaseCreator.java, framework/db/pom.xml, framework/db/src/com/cloud/utils/db/TransactionLegacy.java, pom.xml
Backport #2718 to 4.11.2
Testing
=> Backport Update DBCP version to 4.11

server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
Removing UserVmDetailsDao duplicate field;
Found the following repeated field in the UserVmManagerImpl class
@Inject
private UserVmDetailsDao _vmDetailsDao;
@Inject
private UserVmDetailsDao _uservmDetailsDao;
Refactored to a single field;
@Inject
private UserVmDetailsDao userVmDetailsDao;
Similar to this PR: https://github.com/apache/cloudstack/pull/2750/files
Testing
=> Remove UserVmDetailsDao duplicate field

packaging/build-deb.sh, packaging/package.sh, plugins/network-elements/netscaler/src/main/java/com/cloud/api/commands/RegisterServicePackageCmd.java, server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
Trivial typo, fixed in script and java files. Not sure if checked the right check boxes in this issue description. Thanks!
- [ x ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ x ] My code follows the code style of this project.
- [ x ] My change requires a change to the documentation.
- [ x ] I have updated the documentation accordingly.
Testing
=> Trivial typo s/pacakge/package

ui/scripts/events.js
The title is self-explanatory; for more details, please check the screenshot.
Locally and manually
Testing
=> Add user information on the Event-View in the UI

ui/scripts/ui-custom/recurringSnapshots.js
Fix UI overlay issue in snapshot view on master with new jquery and other changes. This problem was created because of the jQuery-UI upgrade.
This fixes: #2830
Manually
Testing
=> Fix Overlay issue in snapshot view

api/src/main/java/com/cloud/network/NetworkModel.java, api/src/main/java/com/cloud/network/NetworkService.java, api/src/main/java/org/apache/cloudstack/api/command/user/vm/AddIpToVmNicCmd.java, api/src/main/java/org/apache/cloudstack/api/command/user/vm/RemoveIpFromVmNicCmd.java, api/src/test/java/org/apache/cloudstack/api/command/test/AddIpToVmNicTest.java, engine/components-api/src/main/java/com/cloud/network/IpAddressManager.java, engine/schema/src/main/java/com/cloud/vm/dao/NicIpAliasDaoImpl.java, engine/schema/src/main/java/com/cloud/vm/dao/NicSecondaryIpDao.java, engine/schema/src/main/java/com/cloud/vm/dao/NicSecondaryIpDaoImpl.java, server/src/main/java/com/cloud/api/ApiResponseHelper.java, server/src/main/java/com/cloud/api/query/dao/UserVmJoinDaoImpl.java, server/src/main/java/com/cloud/network/IpAddressManagerImpl.java, server/src/main/java/com/cloud/network/Ipv6AddressManager.java, server/src/main/java/com/cloud/network/Ipv6AddressManagerImpl.java, server/src/main/java/com/cloud/network/NetworkModelImpl.java, server/src/main/java/com/cloud/network/NetworkServiceImpl.java, server/src/main/java/com/cloud/network/guru/DirectNetworkGuru.java, server/src/test/java/com/cloud/api/ApiResponseHelperTest.java, server/src/test/java/com/cloud/network/IpAddressManagerTest.java, server/src/test/java/com/cloud/network/Ipv6AddressManagerTest.java, server/src/test/java/com/cloud/network/MockNetworkModelImpl.java, server/src/test/java/com/cloud/vpc/MockNetworkManagerImpl.java, server/src/test/java/com/cloud/vpc/MockNetworkModelImpl.java, ui/lib/jquery.validate.additional-methods.js, ui/scripts/network.js, utils/src/main/java/com/cloud/utils/net/NetUtils.java, utils/src/test/java/com/cloud/utils/net/NetUtilsTest.java
This PR allows the addition of IPv6 address to the secondary NIC through API. It was tested with the basic and the advanced network.
Some use cases are illustrated with the following screenshots:
- the given IP address is checked in the UI :
- it acquires multiple IP addresses:
- fails to acquire an allocated IP:
- releases the IP addresses:
Testing
=> CLOUDSTACK-10328: Add Secondary IPv6 address through API

.gitignore
just an annoyance in ide and maybe on automated checkins if we finally work to a real cd 🙏 🤞 . probably #2692 is better. we must choose, i think.
Testing
=> remove replace properties from ignore list

api/src/org/apache/cloudstack/api/command/admin/network/MigrateNetworkCmd.java
Fix issue #2851
Made networkofferingid required in migrateNetwork
Fixes: ##2851
Testing
=> Make networkofferingid required in migrateNetwork

PULL_REQUEST_TEMPLATE.md
This removes the section from the pull request template that is not very
popular or filled by the PR author.
This is only change to the github PR template, no need of smoketests.
=> PULL_REQUEST_TEMPLATE: simplify and remove unpopular sections

agent/conf/log4j-cloud.xml.in
Avoid logging bytes on direct download on KVM
Testing
=> Set http level to INFO as default

api/src/main/java/org/apache/cloudstack/api/response/TemplateResponse.java, server/src/main/java/com/cloud/api/query/dao/TemplateJoinDaoImpl.java
Added requireshvm key in the response of list template API.
Fixes #2821
=> template: Return requireshvm key in list template response

scripts/vm/network/vnet/modifyvlan.sh
Improved perfomance on creating VM for KVM virtualization.
Also for 4.11. Read details here: https://github.com/apache/cloudstack/pull/2918
More than 500VMs orchestration on the same host (1 x VCPU, 384 Mb ram, Linux).
Created 500 VMs using python scripts. Measured time.
2 x Xeon E5 CPU + 256Gb RAM + 2 x SSDs.
Managment, Database, baremetal agent on the same server. ZFS filesystem pool for NFS share (primary/secondary). KVM virtualization on the host.
No affects. Just replaced ifconfig with ip.
=> Improved perfomance on creating VM (KVM)

core/src/org/apache/cloudstack/storage/to/TemplateObjectTO.java, plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java, server/src/com/cloud/template/TemplateManagerImpl.java
Prevents errors while migrating VM from ISO:
- Test 1: Deploy VM from ISO -> Live migrate VM to another host -> ERROR
- Test 2: Register ISO using Direct Download on KVM -> Deploy VM from ISO -> Live migrate VM to another host -> ERROR
Local environment: 2 KVM CentOS 7 hosts.
Repeated tests described above and pass successfully
=> Migrating VM from ISO failures

ui/scripts/ui-custom/affinity.js
=> Fix set affinity for user overlay problem (Fixes #2986)

utils/src/test/java/com/cloud/utils/DateUtilTest.java
=> make sure no time skew can interfere with comparison

python/lib/cloudutils/serviceConfig.py
Since RHEL7 / CentOS7 starting a process in control group has changed. 
i dont think we need it anymore but if we want something like that we could add it for a RHEL7 / CentOS7 section. we should remove it. its possible that this error will stop the service in the future. 
ERROR journalctl
Ignoring invalid environment assignment 'export CGROUP_DAEMON='cpu:/virt'': /etc/sysconfig/libvirtd
Testing
=> add exitcode / distribution detection and remove export CGROUP_DAEMON for RHEL7/CentOS7

tools/marvin/marvin/config/test_data.py
This add missing test data for one of the keys for a recently added
migration test.
=> marvin: add missing default test data

utils/src/main/java/com/cloud/utils/net/MacAddress.java, utils/src/test/java/com/cloud/utils/net/MacAddressTest.java
=> Macaddresses

README.md
Merry Christmas and happy holidays! :monkey: :cloud: :santa: :christmas_tree:
/cc alphabetically-ish @andrijapanic @anuragaw @borisstoyanov @bwsw @chiradeep @csquire @DaanHoogland @DagSonsteboSB @dhlaluku @fmaximus @GabrielBrascher @gsirett @glennwagner @harikrishna-patnala @jayapalu @K0zka @karuturi @kiwiflyer @khos2ow @PaulAngus @marcaurele @mike-tutkowski @milamberspace @msinhore @nitin-maharana @NuxRo @nvazquez @pdion891 @pyr @rafaelweingartner @RPDiep @resmo @steveroles @sureshanaparti @svenvogel @swill @syed @ustcweizhou @wido and so many others!
=> README: Ho ho ho!

server/src/com/cloud/server/ManagementServerImpl.java
Adds support for keyword search that was ignored by listsshkeypairs command.
Fixes: #2920
=> Add support for keyword in listSSHKeyPairs command search (#2920)

packaging/centos63/cloud-management.rc, packaging/centos63/cloud-usage.rc, packaging/systemd/cloudstack-management.default
This PR is an extension of #2535. By doing this, we also create an easy method to enable remote debug in CentOS63 as well.
Locally
=> Extend PR#2535 to enable remote debugging for CentOS63

plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java, scripts/vm/network/security_group.py
This PR enhances the security group Python script. It refactors old code, removes deprecated code and fixes many bugs.
- PEP-8 styling
- Remove old LXC code from Python script
- Remove deprecated optparse from Python
- Use proper calls to iptables
I have tested this on a Local Cloud we have running with the master branch.
Tested both IPv4 and IPv6 in a Advanced Zone using VXLAN L2 isolation.
=> kvm: Security Group enhancements and refactor old code

engine/schema/src/main/resources/META-INF/db/schema-41120to41200.sql
As described in the issue #3123 the certificate endpoint throws an exception when a request is made to create the certificate.
Before the SQL change:
After the SQL change:
Via UI:
~~~
1) Login with admin user
2) Go to the accounts menu
3) Select the tab "SSL Certificates"
4) Click in "Add Certificate"
5) Fill in the field "Name"
6) Fill in the field "Certificate"
7) Fill in the field "Private Key"
~~~
Via PHP code (pseudo code using https://github.com/PCextreme/cloudstack-php):
```php
// Not that I am sending the certificate and the 
// private key content instead of the absolute path to the file
$client->uploadSslCert( [
'certificate' => file_get_contents('my.cert')),
'privatekey' => file_get_contents('cstest.key'),
'password' => 'test',
]);
````
=> changed column fingerprint from varchar(62) to text #3123

api/src/main/java/org/apache/cloudstack/api/command/user/address/AssociateIPAddrCmd.java, server/src/main/java/com/cloud/network/IpAddressManagerImpl.java, server/src/test/java/com/cloud/network/IpAddressManagerTest.java, test/integration/component/test_tags.py, test/integration/smoke/test_network.py, test/integration/smoke/test_portforwardingrules.py
Recreating this PR from the one mentioned below as I do not have write permissions to the previous branch. This PR fixes the build failures experienced on mentioned PR because of failing unit tests that are caused by a duplicate Mock object. The code has also been rebased against latest master.
https://github.com/apache/cloudstack/pull/2382/files
#2382
=> IP address acquired with associate ip address is marked as source nat

.dockerignore, api/src/main/java/org/apache/cloudstack/api/command/admin/account/UpdateAccountCmd.java, server/src/main/java/com/cloud/user/AccountManagerImpl.java, server/src/test/java/com/cloud/user/AccountManagerImplTest.java, test/integration/smoke/test_accounts.py, tools/docker/Dockerfile.smokedev, tools/docker/docker_run_tests.sh, tools/marvin/marvin/lib/base.py
Existing 'updateAccount' API call now can update role as well as account name and network domain. During the implementation 'newname' attribute was marked as optional, previously in the API was annotated as required, which is not a right behavior.
New Dockerfile was added Dockerfile.smokedev which is convenient if you develop smoke tests.
Helper script was added to deploy datacenter and run tests from the same docker image which guarantees a predictable environment.
```bash
docker run -v ~/dev/tmp:/tmp \
-v ~/IdeaProjects/cloudstack/test/integration/smoke:/root/test/integration/smoke \
-it \
--name simulator -p 8080:8080 -p8096:8096 simulator:4.12
docker exec -it simulator bash
bash /root/docker_run_tests.sh advanced smoke
```
Implements #3049 
- The code was tested with cloudmonkey
- …
=> CLOUDSTACK-3049: update dynamic role for an account

api/src/main/java/org/apache/cloudstack/api/command/admin/usage/ListUsageRecordsCmd.java, api/src/main/java/org/apache/cloudstack/usage/UsageService.java, api/src/test/java/org/apache/cloudstack/api/command/test/UsageCmdTest.java, server/src/main/java/com/cloud/api/dispatch/ParamProcessWorker.java, server/src/main/java/com/cloud/server/ManagementServerImpl.java, server/src/main/java/com/cloud/usage/UsageServiceImpl.java
Refactor file name to be consistent with the API name.
=> api: rename ListUsageRecords file name to ListUsageRecordsCmd

ui/scripts/instances.js
This adds a start button on top of the instance list view which makes it possible to start multiple instances at once.
Deployed to our test environment and tested functionality.
=> Add start button for multiple instances in list view

test/integration/smoke/test_deploy_virtio_scsi_vm.py, test/integration/smoke/test_hostha_kvm.py, test/integration/smoke/test_vm_life_cycle.py, tools/marvin/marvin/lib/base.py
Fixes for test_deploy_virtio_scsi_vm.py which throws an exception if the hypervisor does not support the tests.
And test_vm_life_cycle.py and test_vm_life_cycle.py which fail when the environment hasn't fully recovered from the previous test.
- [ x ] Bug fix (non-breaking change which fixes an issue)
Tested by patching tests and then running them against a virtualized environment
Testing
- [ x ] All relevant new and existing integration tests have passed.
=> Fix some Marvin smoke tests

engine/schema/src/main/java/com/cloud/upgrade/DatabaseUpgradeChecker.java, engine/schema/src/main/java/com/cloud/upgrade/dao/Upgrade41200to41300.java, engine/schema/src/main/resources/META-INF/db/schema-41200to41300-cleanup.sql, engine/schema/src/main/resources/META-INF/db/schema-41200to41300.sql
This adds empty empty upgrade path from 4.12.0.0 to 4.13.0.0.
=> schema: add empty DB upgrade path from 4.12.0.0 to 4.13.0.0

server/src/main/java/com/cloud/server/ConfigurationServerImpl.java
Fixes: [#CLOUDSTACK-10406](https://issues.apache.org/jira/browse/CLOUDSTACK-10406)
- [x ] Bug fix (non-breaking change which fixes an issue)
=> [CLOUDSTACK-10406] fix bugs that may cause program crash, change mkdir to mkdirs

server/src/main/java/com/cloud/server/ConfigurationServerImpl.java
Fixes: [#CLOUDSTACK-10406](https://issues.apache.org/jira/browse/CLOUDSTACK-10406)
=> fix bugs that may cause program crash, change mkdir to mkdirs (#3249)

packaging/centos7/cloud.spec
This may slow down CI and release, but ensures that unit tests always
run as part of the packaging build process.
=> packaging: don't skip unit tests while building packages

pom.xml, server/pom.xml, server/src/main/java/com/cloud/server/StatsCollector.java
The InfluxDB Java client supports Batch Mode at versions 2.9+ [1]. Thus, this PR updated to the latest InfluxDB (2.15), adding support to Batch Mode
[1] https://github.com/influxdata/influxdb-java
=> Update to latest InfluxDB (2.15), adding support to Batch Mode

server/src/main/java/com/cloud/storage/snapshot/SnapshotSchedulerImpl.java
While checking the state of all currently executing snapshots we also include those async jobs for the snapshots which have a 'removed' flag. Due to the fact that the snapshot scheduler need to find its related job to check its state and update the snapshot_schedule table accordingly.
=> Include 'removed' async jobs to check recurring snapshots

pom.xml, ui/css/cloudstack3-ie7.css, ui/css/cloudstack3.css, ui/css/cloudstack3.hu.css, ui/css/cloudstack3.ja_JP.css, ui/css/custom.css, ui/css/src/.sass-lint.yml, ui/css/src/Gulpfile.js, ui/css/src/package-lock.json, ui/css/src/package.json, ui/css/src/readme.md, ui/css/src/scss/cloudstack3-ie7.scss, ui/css/src/scss/cloudstack3.hu.scss, ui/css/src/scss/cloudstack3.ja_JP.scss, ui/css/src/scss/cloudstack3.scss, ui/css/src/scss/custom.scss, ui/css/src/scss/token-input-facebook.scss, ui/css/token-input-facebook.css
_Copy of https://github.com/apache/cloudstack/pull/3301 because I run into troubles after changing my username_
This adds an gulp tasks, to build existing css files out of scss files and enables advantages for working with style rules. 
Also this will reduce the complexibility of heavy css files **in all future css changes**.
- Using CSS is no longer the common standard for complex pages like cloudstack
- SASS (https://sass-lang.com/) or SCSS are preprocessors of CSS. Similar to ES6 or TypeScript for JavaScript.
- SCSS files are compiled to CSS files ones while development or deployment, and not on every page request
- SCSS provides us many logical functions and advantages to organise CSS rules more easily and less redundand with features like variables and so called mixins
- SCSS let us …
=> Feature add scss to css compiler

pom.xml
=> slf4j version

scripts/storage/secondary/cloud-install-sys-tmplt, scripts/storage/secondary/createtmplt.sh
* remove unused old vars and functions e.g. today, chksum...
* add function to calculate the virtual size of template for managed storage (netapp solidfire) so that the copy process is working from NFS to iSCSI correctly
* refactor cloud-install-sys-tmplt creates all settings of template.properties
* refactor createtmplt.sh shall create only the templates e.g. uncompress and install ...
tested manually in our production environment with different files like vhd, qcow2 and ova
=> Fix template size for managed storage / refactor cloud-install-sys-tmplt and createtmplt.sh

server/src/main/java/com/cloud/hypervisor/kvm/discoverer/LibvirtServerDiscoverer.java
When a KVM host is added to a cluster, the cluster GUID is null. In case
the KVM host fails to be added, the GUID is null and if any
other hosts are added an exception is thrown by the resource manager
that does not allow addition of hosts to a cluster with existing hosts
whose GUID is null.
In case of KVM, other hosts may be added in parallel therefore this
restriction can be safely removed.
Issue references:
http://mail-archives.apache.org/mod_mbox/cloudstack-users/201604.mbox/%3Cloom.20160415T120602-157@post.gmane.org%3E
http://mail-archives.apache.org/mod_mbox/cloudstack-users/201306.mbox/%3C1F7751C3-DB29-4639-9E67-9760B07C9A5B@gmail.com%3E
Tested in a local centos7.6+kvm env:
Deployed mgmt server
Made sys.exit(1) in the cloudstack-setup-agent script
Deployed zone, added the host
Host …
=> server: save GUID for KVM cluster

ui/scripts/instances.js, ui/scripts/ui/dialog.js, ui/scripts/ui/widgets/listView.js
* Fixed a bug, where after sorting a column of the instance list view the multi select action buttons wouldn't show up after selecting one ore more entries of the table.
* Added a behavior, so that an already starting/running/stopped/stopping instance of the instance view will (when multi selected alone or together with other instances) not create an API request if it already has the desired state.
Deployed to local environment and tested functionality.
=> ui: fix instance and functionality

ui/css/cloudstack3.css, ui/css/src/scss/cloudstack3.scss, ui/css/src/scss/components/blocking-overlay.scss, ui/css/src/scss/components/dashboard.scss, ui/css/src/scss/components/list-view.scss, ui/css/src/scss/components/multi-wizzard.scss, ui/css/src/scss/components/quick-view-tooltip.scss
- Moved some recently made CSS changes (46a32795bcbefd7475d62421a71fbdeff0e2c407 / 2020bfb6a3bf597d762e162a355ea3dfd26857eb) to their newly introduced respective SCSS files 
- Aligned the dashboard containers properly (see screenshots [1](#screenshot1) and [2](#screenshot2))
- Restored the original quick view tooltip background color (see screenshots [3](#screenshot3) and [4](#screenshot4))
- Fixed the height of the toolbar in dialog views and also stretched it in width (see screenshots [5](#screenshot5) and [6](#screenshot6)
1. <span name="screenshot1">Unaligned dashboard containers</span>
2. <span name="screenshot2">Aligned dashboard containers</span>
3. <span name="screenshot3">Old quick view tooltip</span>
4. <span name="screenshot4">New quick view tooltip</span>
5. <span …
=> ui: adaptations

api/src/main/java/org/apache/cloudstack/api/command/user/snapshot/CreateSnapshotCmd.java, api/src/test/java/org/apache/cloudstack/api/command/test/CreateSnapshotCmdTest.java, server/src/main/java/com/cloud/storage/snapshot/SnapshotSchedulerImpl.java, ui/scripts/storage.js
Add more details in console logs and event details
Also show popup on successful completition of snapshots
Fixes: #3327
=> Add more info for creating volume snapshots

ui/index.html
As discussed in #3385, the translation code does not work with self closing translate tags when there is other content at the same level, e.g. `<div><translate key="foo"/>: Something</div>` - it will remove the "`: Something`".  This PR changes the affected tags to non-self closing, e.g. `<translate key="foo"></translate>: Something`
This fixes the Zone names not being displayed on the capacity graphs on the dashboard, plus some minor missing labels elsewhere.
Fixes: #3385 
Before:
After:
Verified that missing labels appear in UI.
=> Fix labels broken by translation code

.gitignore
=> Minor: Add .vscode to .gitignore

api/src/main/java/org/apache/cloudstack/api/command/user/loadbalancer/CreateLoadBalancerRuleCmd.java
This fixes the API arg description to advise the user the possible
protocol options they can provide to the createLoadBalancerRule API.
Fixes #3090
=> api: Fix API argument documentation to list supported protocols

ui/config.js
This is a purely documentation change of config file. The cleanup was needed post merge of PR #3258
=> Update config file with tables that users can see

ui/l10n/en.js, ui/scripts/network.js
Fixes #3252
This fixes labels for missing LB protocol(s).
=> ui: fix LB protocol bug

api/src/main/java/org/apache/cloudstack/api/command/user/account/ListAccountsCmd.java, api/src/main/java/org/apache/cloudstack/api/command/user/project/ListProjectsCmd.java, server/src/main/java/com/cloud/api/ApiDBUtils.java, server/src/main/java/com/cloud/api/ApiResponseHelper.java, server/src/main/java/com/cloud/api/query/QueryManagerImpl.java, server/src/main/java/com/cloud/api/query/ViewResponseHelper.java, server/src/main/java/com/cloud/api/query/dao/AccountJoinDao.java, server/src/main/java/com/cloud/api/query/dao/AccountJoinDaoImpl.java, server/src/main/java/com/cloud/api/query/dao/ProjectJoinDao.java, server/src/main/java/com/cloud/api/query/dao/ProjectJoinDaoImpl.java, test/integration/smoke/test_create_list_domain_account_project.py, ui/scripts/accounts.js, ui/scripts/instances.js, ui/scripts/lbCertificatePolicy.js, ui/scripts/projects.js, ui/scripts/sharedFunctions.js, ui/scripts/system.js
If there are many projects and accounts, listing projects/accounts will take long time getting the resource limitation and resource count in the process. However resource count/limitation are not needed sometimes. 
Add an option 'details' to listProjects and listAccounts. If you do not need the resource count/limitation, please add details=min to api call. The api execution time will be reduced significantly.
create projects
list projects with details=all
list projects with details=min
create accounts
list accounts with details=all
list accounts with details=min
=> api/server: Add option 'details' to listProjects and listAccounts

pom.xml, systemvm/debian/opt/cloud/bin/configure.py, tools/travis/install.sh
This tries to fix build failures seen in job 1 of Travis.
Changes are only towards travis CI, this can be merged when Travis job 1 passed.
=> travis: use explicit change directory and use -pl to build rat check

ui/scripts/storage.js
Removed duplicate code for diskOffering field.
Fixes #3001 
UI
=> ui: fix custom offerings selection in upload volume form

api/src/main/java/org/apache/cloudstack/api/command/admin/vm/DeployVMCmdByAdmin.java, api/src/main/java/org/apache/cloudstack/api/command/user/vm/DeployVMCmd.java, api/src/main/java/org/apache/cloudstack/api/command/user/vm/StartVMCmd.java, server/src/main/java/com/cloud/vm/UserVmManager.java, server/src/main/java/com/cloud/vm/UserVmManagerImpl.java, test/integration/smoke/test_vm_deployment_planner.py, ui/css/cloudstack3.css, ui/index.html, ui/l10n/en.js, ui/scripts/instanceWizard.js, ui/scripts/instances.js, ui/scripts/ui-custom/instanceWizard.js
Currently an admin can choose which host a VM is to be started on. They should be able to 'override' the allocation algorthm to a greater or lesser extent at will, and be able to choose the pod, cluster or host
that they wish a new VM to be deployed in.
DeployVirtualMachine API has been extended with additional, optional parameters podid and clusterid that will be passed to and used in the deployment planner, when selecting a viable host. If the user supplies a pod, a suitable host in the given pod will be selected. If the user supplies a cluster, a suitable host in the given cluster will be selected.
Based on the parameter supplied and on passing validation, the VM will then be deployed on the selected host, cluster or pod.
=> Add support for new heuristics based VM Deployement for admins

engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/snapshot/CephSnapshotStrategy.java, engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/snapshot/StorageSystemSnapshotStrategy.java, engine/storage/snapshot/src/main/resources/META-INF/cloudstack/storage/spring-engine-storage-snapshot-storage-context.xml, engine/storage/snapshot/src/test/java/org/apache/cloudstack/storage/snapshot/CephSnapshotStrategyTest.java, plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtRevertSnapshotCommandWrapper.java, pom.xml, server/src/main/java/com/cloud/storage/snapshot/SnapshotManagerImpl.java
Add CephSnapshotStrategy to handle RBD revert (rollback) snapshot. In order to support RBD revert (rbd_rollback), this PR adds a CephSnapshotStrategy class to handle Ceph/RBD snapshot actions.
(i) set `snapshot.backup.to.secondary` to false and restart ACS, ensuring that snapshots are stored directly on primary storage (Ceph/RBD)
(ii) create multiple snapshots with changes (e.g. new files) and stop the VM
(iii) revert to a given snapshot
(iv) assert that rbd_snap_rollback is successfuly executed (remote debug evaulating the code)
(v) start the VM and check that the VM disk content is as expected
=> Rbd snapshot rollback

api/src/main/java/com/cloud/agent/api/storage/OVFHelper.java
Fix error on template registration:
Caused by:
````
2019-07-23 12:23:09,674 DEBUG [c.c.a.t.Request] (AgentManager-Handler-6:null) (logid:) Seq 4-4903012619322916910: Processing:  { Ans: , MgmtId: 32987630602057, via: 4, Ver: v1, Flags: 10, [{"com.cloud.agent.api.storage.DownloadAnswer":{"jobId":"ef37e03c-ef79-42da-9a34-47d3f41ba88b","downloadPct":100,"errorString":"Failed post download script: com.cloud.exception.InternalErrorException: OVA package has bad ovf file null","downloadStatus":"DOWNLOAD_ERROR","downloadPath":"/mnt/SecStorage/a9751ac5-94ed-35c4-bff1-42f61b3c8b18/template/tmpl/2/202/dnld5595547545501326400tmp_","installPath":"template/tmpl/2/202/95d1f7c7-d6b6-3387-bdc6-9c8ab170e702.ova","templateSize":0,"templatePhySicalSize":0,"checkSum":"5cc9bedfb202cd88f4b9abed33f38f0d","result …
```
=> [Vmware] Fix bad ovf null error when registering template

tools/marvin/pom.xml
Removing deprecated pip option --allow-external
=> remove depcrecated pip option --allow-external

engine/api/src/main/java/org/apache/cloudstack/engine/subsystem/api/storage/DataStoreManager.java, engine/storage/cache/src/main/java/org/apache/cloudstack/storage/cache/allocator/StorageCacheRandomAllocator.java, engine/storage/datamotion/src/main/java/org/apache/cloudstack/storage/motion/AncientDataMotionStrategy.java, engine/storage/datamotion/src/main/java/org/apache/cloudstack/storage/motion/KvmNonManagedStorageDataMotionStrategy.java, engine/storage/datamotion/src/test/java/org/apache/cloudstack/storage/motion/KvmNonManagedStorageSystemDataMotionTest.java, engine/storage/image/src/main/java/org/apache/cloudstack/storage/image/manager/ImageStoreProviderManagerImpl.java, engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/snapshot/SnapshotServiceImpl.java, engine/storage/src/main/java/org/apache/cloudstack/storage/datastore/DataStoreManagerImpl.java, engine/storage/src/main/java/org/apache/cloudstack/storage/image/datastore/ImageStoreProviderManager.java, plugins/hypervisors/hyperv/src/main/java/com/cloud/hypervisor/hyperv/manager/HypervManagerImpl.java, plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/manager/VmwareManager.java, plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/manager/VmwareManagerImpl.java, plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java, server/src/main/java/com/cloud/network/element/ConfigDriveNetworkElement.java, server/src/main/java/com/cloud/server/StatsCollector.java, server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java, server/src/main/java/com/cloud/storage/upload/UploadMonitorImpl.java, server/src/main/java/com/cloud/template/HypervisorTemplateAdapter.java, server/src/main/java/com/cloud/template/TemplateManagerImpl.java, server/src/test/java/com/cloud/network/element/ConfigDriveNetworkElementTest.java, services/secondary-storage/controller/src/main/java/org/apache/cloudstack/secondarystorage/SecondaryStorageManagerImpl.java
Retrieval of an image store using ImageStoreProviderManager has been refactored by introducing three different methods,
`DataStore getRandomImageStore(List<DataStore> imageStores);`
To get an image store for reading purpose. Threshold capacity check will not be used here.
`DataStore getImageStoreWithFreeCapacity(List<DataStore> imageStores);`
To get an image store for reading purpose. Threshold capacity check will be used here and the store with max free space will be returned. If no store with filled storage less than the threshold is found, the NULL value will be returned.
`List<DataStore> listImageStoresWithFreeCapacity(List<DataStore> imageStores);`
To get a list of image stores for writing purpose which fulfills threshold capacity check.
Correspondingly DataStoreManager methods have …
=> engine, server, services: fix for respecting secondary storage threshold limit

engine/schema/src/main/resources/META-INF/db/schema-41200to41300.sql
=> add vSphere 6.7.3 and update 6.7.2 & 6.7.1

engine/schema/src/main/resources/META-INF/db/schema-41200to41300.sql
- Bug fix (non-breaking change which fixes an issue)
=> fix xenserver 7.0.1 os mapping typo

agent/bindir/cloud-guest-tool.in, debian/rules, packaging/centos63/cloud.spec, packaging/centos7/cloud.spec
Using this tool on a hypervisor admins can query KVM Instances running
on that hypervisor if they have the Qemu Guest Agent installed.
All System VMs have this and they can be queried.
For example:
$ cloudstack-guest-tool i-2-25-VM
This will print some information about network and filesystem status.
root@hv-138-a05-23:~# ./cloudstack-guest-tool s-11-VM --command info|jq
{
"network": [
{
"ip-addresses": [
{
"prefix": 8,
"ip-address": "127.0.0.1",
"ip-address-type": "ipv4"
}
],
"name": "lo",
"hardware-address": "00:00:00:00:00:00"
},
{
"ip-addresses": [
{
"prefix": 16,
"ip-address": "169.254.242.169",
"ip-address-type": "ipv4"
}
],
"name": "eth0",
"hardware-address": "0e:00:a9:fe:f2:a9"
},
...
...
"filesystem": [
{
"mountpoint": "/var",
"disk": [
{
"bus": 0,
"bus-type": "virtio",
"target": …
=> kvm/cloudstack-guest-tool: Tool to query Qemu Guest Agent

.gitignore
=> ignore patches and unzipped logs

engine/storage/datamotion/src/main/java/org/apache/cloudstack/storage/motion/AncientDataMotionStrategy.java
Diagnostics are hard when a snapshot fails if a null pointer occurs. This is because no stack trace or location of the error is logged. I.E.
`2019-10-21 12:55:00,056 DEBUG [o.a.c.s.m.AncientDataMotionStrategy] (Work-Job-Executor-131:ctx-80420156 job-10033827/job-10033828 ctx-4864e2f5) (logid:21454564) copy snasphot failed: java.lang.NullPointerException`
=> snapshot failure diagnostics unhidden

debian/cloudstack-usage.postinst
- [x ] Cleanup (Code refactoring and cleanup, that may add test cases)
About to be tested!
=> debian: fix symlink issue post install/upgrade

ui/css/cloudstack3.css
this fixes: https://github.com/apache/cloudstack/issues/3697
- [ * ] Bug fix (non-breaking change which fixes an issue)
This fixes times when long names are truncated, despite there being much more space available
=> increase width of field in UI

ui/scripts/instances.js
Add some more detail to the VM statistics. Added the Memory Used detail
=> Enhance VM Statistics to add more detail

engine/schema/src/main/resources/META-INF/db/schema-41300to41400.sql
SQL was tested to fix the issue - otherwise, nothing to test really.
=> Fix OS category for some OS-es added in 4.13

README.md
That time of the year :christmas_tree: - let's merge this without tests?
=> README: that time of the year!

debian/control, packaging/centos7/cloud.spec, scripts/storage/secondary/cloud-install-sys-tmplt, scripts/storage/secondary/createtmplt.sh
Reverts apache/cloudstack#3371
=> Revert "Fix virtual template size for managed storage for KVM / refactor cloud-install-sys-tmplt"

engine/components-api/src/main/java/com/cloud/ha/HighAvailabilityManager.java, server/src/main/java/com/cloud/ha/HighAvailabilityManagerImpl.java
Reverts apache/cloudstack#3737
issues has been noticed and a fix has been proposed in PR 3773 from 3737
we need to revert this PR.
=> Revert "Add missing HA config keys"

engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
When adding a nic to a vm, the network offiring details were ignored. This change passes the network offering details to vsphere.
Fixes: #3565 
This was tested by creating 2 instances on separate networks. Adding a nic to one of the instances and then verifying if promiscuous mode was not changed on vsphere.
=> Honour promiscuous mode from networkOffering

engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
=> Honour promiscuous mode from networkOffering (#3765)

server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
revert b13acc6459fe5c824206ae77885600404368c476
to once again allow a VM to be on multiple networks from VPCs
Fixes: #3702
=> Once again allow a VM to be on multiple networks from VPCs

ui/scripts/network.js
Remove the empty item from the free IP list when we click on "Acquire New IP" in the networks section.
If we dont select any IP address from the list and click ok, it sends "ipaddress=-1" as the parameter which is not back compatible.
This fix ensures that no empty item is displayed and by default one valid ip selected. So when we click ok, "ipaddress=-1" wont be sent as a parameter to the api call.
1 . Navigate to "Networks" section in the main UI
2 . Select any network from the list.
3 . Click on "View IP address" button.
4 . Now click on "Acquire New IP" button on the top right. This will open up a new pop up window with drop down list of all IP address belonging to that network
5 . Select any of the IP address.
=> Bug fix: Dont display empty item in free ip list

test/integration/smoke/test_privategw_acl.py
in test_privategw_acl.py, we need to check connectivity not only vpc1 to vpc2, but also vpc2 to vpc1.
Related to: #3859
=> test: check more connectivity in test_privategw_acl.py

ui/scripts/network.js
Display drop-down list for VPN customer gateway selection in UI so that it can be searched according to domains
Before the change, there was no drop down list for domains
After the change there is a drop down and the domains are displayed in the sorted order
=> UI: Display drop down list for VPN customer gateway selection

engine/schema/src/main/resources/META-INF/db/schema-41300to41400-cleanup.sql
=> remove duplicate index region

systemvm/debian/opt/cloud/bin/cs/CsDhcp.py
The previous setup of many hours would not work, due to some internal dnsmasq issues - lease was set correclty, but dnsmasq was setting the dhcp-renew-time (and rebind time) to less than 2 years from the date the lease was issued.
Using "infinite" as the value (instead of the number) works as expected - and (atm) the renew date is set to year 2088, etc..
Confirmation inside user VM of correct renew/rebind/expire time
Configuration inside VRs
Different one:
See screenshot above
=> Fix dhcp infinite lease time

plugins/user-authenticators/ldap/pom.xml, pom.xml
Updates few maven dependencies
=> maven: update dependencies

server/src/main/java/com/cloud/network/router/VirtualNetworkApplianceManagerImpl.java, utils/src/main/java/com/cloud/utils/ssh/SshHelper.java
VR health check throws EOFException due to malformed/Invalid JSON.
Addresses issue: https://github.com/apache/cloudstack/issues/3893
=> Handle EOFException during VR Health Check

setup/dev/advanced.cfg, setup/dev/dualsim.cfg, test/integration/smoke/test_accounts.py, test/integration/smoke/test_projects.py, test/integration/smoke/test_templates.py, tools/marvin/marvin/lib/base.py
pertaining to #3693 (only fixes part)
=> cleanup for resources left by test_accounts and test_project

pom.xml
Reverts apache/cloudstack#2446
fails when network causes CVE DB not being able to be downloaded
=> Revert "CLOUDSTACK-10271 maven plugin for owasp dependency check added"

utils/src/main/java/org/apache/cloudstack/utils/imagestore/ImageStoreUtil.java
This PR fixes an error where raw template files are not being downloaded
Fixes: #2820 
This was tested by adding a raw template to be downloaded from the UI
=> Fixes raw templates not downloading

engine/storage/datamotion/src/main/java/org/apache/cloudstack/storage/motion/AncientDataMotionStrategy.java
rebase of #3959 to apply on 4.13 first
Fixes: #3958
=> Volume migration

systemvm/debian/opt/cloud/bin/cs/CsDhcp.py
=> python format

server/src/main/java/com/cloud/user/AccountManagerImpl.java
entity ownership is already being verified at line 508
=> cleanup of redundant check for sameOwner

tools/appliance/build.sh
This Pull request updates the system VM template build script to use vmware hardware version 11 instead of 8.
This was tested by running the build script before and after the change. No errors.
=> Updated vmware virtual hardware version in systemvmtemplate build script

api/src/main/java/org/apache/cloudstack/api/response/ImageStoreResponse.java, server/src/main/java/com/cloud/api/query/dao/ImageStoreJoinDaoImpl.java
Display image store disk size used and total disk size in list imagestore api response
Before the change, this is the api response
```
(local) 🐵 > list imagestores
{
"count": 1,
"imagestore": [
{
"id": "4c2886-191f-4bcf-b73d-b822a3f67",
"name": "nfs://10.1.1.1:/data/secondary1",
"protocol": "nfs",
"providername": "NFS",
"scope": "ZONE",
"url": "nfs://10.1.1.1:/data/secondary1",
"zoneid": "864a09-8c64-4da4-a56b-e6adsfs17d4de",
"zonename": "zone1"
}
]
}
```
This is the api response after the change
```
(local) 🐵 > list imagestores
{
"count": 1,
"imagestore": [
{
"disksizetotal": 527370027008,             <<<<<<<<<<<<<<<<<<<<<<
"disksizeused": 9650569216,                <<<<<<<<<<<<<<<<<<<<<<
"id": "4sdf886-191f-4bcf-b7dsd-b8sdf213f67",
"name": "nfs://10.1.1.1:/data/secondary1",
"protocol": …
```
=> Display image store disk size used and total disk size stats

core/src/main/java/com/cloud/agent/api/CheckVMActivityOnStoragePoolCommand.java
Fixes #4045 
* Create an HA instance on 1 of 3 HA hosts configured with out of band management in a cluster.
* Stop the instance
* Migrate storage
* Start the instance
* Shut down the host.
* Wait for the host to transition to "Fenced" state.
* Wait for the VM to be migrated automatically.
=> Fixed HA migrated storage error

ui/scripts/zoneWizard.js
Advanced Network with Security Groups is a great option for deploying a Zone with IPv6 address support. However, it is not possible to set **IPv6 DNS** + **IPv6 CIDR** + **IPv6 gateway** via the zoneWizard UI.
Currently, the workaround is to either (i) create a new network (the default guest network would not support IPv6), (ii) deploy a zone via API, or (iii) to run a MySQL update query to set the default guest network IPv6 config.
This PR adds a small enhancement on the UI Zone deployment to allow deploying a Zone with Advanced Network with Security Groups + IPv6 CIDR, IPv6 gateway, and IPv6 DNS.
Note that API [[1]](https://cloudstack.apache.org/api/apidocs-4.13/apis/createNetwork.html) offers full support for such action, therefore there is no need for changing the API. It is just a …
=> Allow set IPv6 when deploying advanced network  Zone with SG via UI

plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/dpdk/DpdkDriverImpl.java
Update to support trunk interfaces for DPDK enabled hosts.
=> Update DpdkDriverImpl.java to support DPDK trunk interfaces

tools/docker/Dockerfile
upgrade dockerfile to use ubuntu 18.04 instead of ubuntu 16.04 because we use java 11 in 4.14.
meanwhile, fix an issue due to mysql change in ubuntu 18.04, and fix NPE by installing iproute2.
=> docker: upgrade to ubuntu 18.04 and fix some issues

api/src/main/java/org/apache/cloudstack/api/response/IPAddressResponse.java, server/src/main/java/com/cloud/api/ApiResponseHelper.java
In the list publicipaddress api call ,display the network
name if ip is associated to shared network. The network
name is displayed as of now only if Ip is associated with
isolated network
Before the patch
```
(local) 🐵 > list publicipaddresses ipaddress=10.1.1.1 listall=true forvirtualnetwork=false
{
"count": 1,
{
"fordisplay": true,
"forvirtualnetwork": false,
"id": "eb38235f-e478-476a-bccd-bd4c95d92c8c",
"ipaddress": "10.1.1.1",
"isportable": false,
"issourcenat": false,
"isstaticnat": false,
"networkid": "791432-089-4bac-8a12-0c1efb",
"state": "Allocated",
}
]
}
```
After the patch
```
(local) 🐵 > list publicipaddresses ipaddress=10.1.1.1 listall=true forvirtualnetwork=false
{
"count": 1,
{
"domain": …
```
=> Display network name for IP in shared networks

engine/schema/src/main/java/com/cloud/user/dao/AccountDao.java, engine/schema/src/main/java/com/cloud/user/dao/AccountDaoImpl.java, framework/quota/src/main/java/org/apache/cloudstack/quota/dao/QuotaAccountDao.java, framework/quota/src/main/java/org/apache/cloudstack/quota/dao/QuotaAccountDaoImpl.java, framework/quota/src/main/java/org/apache/cloudstack/quota/dao/QuotaTariffDao.java, framework/quota/src/main/java/org/apache/cloudstack/quota/dao/QuotaTariffDaoImpl.java, plugins/database/quota/src/main/java/org/apache/cloudstack/api/command/QuotaSummaryCmd.java, plugins/database/quota/src/main/java/org/apache/cloudstack/api/command/QuotaTariffListCmd.java, plugins/database/quota/src/main/java/org/apache/cloudstack/api/response/QuotaResponseBuilder.java, plugins/database/quota/src/main/java/org/apache/cloudstack/api/response/QuotaResponseBuilderImpl.java, plugins/database/quota/src/main/java/org/apache/cloudstack/api/response/QuotaSummaryResponse.java, plugins/database/quota/src/test/java/org/apache/cloudstack/api/command/QuotaTariffListCmdTest.java
Adds pagination and keyword search support to quotaSummary and quotaTariffList
Fixes: #4181  
```
(localcloud) SBCM5> > quota summary listall=true page=1 pagesize=2 keyword=a
{
"count": 3,
"summary": [
{
"account": "ACSUser",
"accountid": 4,
"balance": 0,
"currency": "$",
"domainid": 1,
"enddate": "2020-07-02T00:00:00+0000",
"quota": 0,
"startdate": "2020-07-01T00:00:00+0000",
"state": "enabled"
},
{
"accountid": 2,
"balance": 0,
"currency": "$",
"domainid": 1,
"enddate": "2020-07-02T00:00:00+0000",
"quota": 0,
"startdate": "2020-07-01T00:00:00+0000",
"state": "enabled"
}
]
}
```
```
(localcloud) SBCM5> > quota tarifflist pagesize=3 page=7
{
"count": 25,
"quotatariff": [
{
"currency": "$",
"description": "VM Disk usage(I/O Write)", …
```
=> Adding pagination for quotaSummary and quotaTariffList

plugins/integrations/prometheus/src/main/java/org/apache/cloudstack/metrics/PrometheusExporterServer.java
=> Set prometheus.exporter.enable as not dynamic

engine/schema/src/main/java/com/cloud/storage/dao/VMTemplateDao.java, engine/schema/src/main/java/com/cloud/storage/dao/VMTemplateDaoImpl.java, plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java, plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterActionWorker.java, plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterDestroyWorker.java, plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterResourceModifierActionWorker.java, plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterStartWorker.java, plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/version/KubernetesVersionManagerImpl.java, plugins/integrations/kubernetes-service/src/main/java/org/apache/cloudstack/api/command/user/kubernetes/version/ListKubernetesSupportedVersionsCmd.java, plugins/integrations/kubernetes-service/src/test/java/com/cloud/kubernetes/version/KubernetesVersionServiceTest.java
Fixes #4056 
Fixes #4107
Fixes #4113
Fixes #4133 
Check for compute offering host tags while finding suitable host/deployment destination for k8s cluster node VM during deploy and scale cluster.
Check for k8s cluster template's hypervisor type during scale as the template is tied to the k8s cluster therefore new node VM must be deployed in the same hypervisor host.
Fixes template checks
=> cks: fix template, deployment issues

plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterResourceModifierActionWorker.java, plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterStartWorker.java, server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
Fixes #4241, failure to deploy VM when vm.instancename.flag is set to true
=> cks: fix for null hypervisor type

server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
This PR fix some wrongs comparison using nullable objects. Preventing null pointer exception
=> Fix comparison using nullable objects

test/integration/smoke/test_human_readable_logs.py
The test was failing due to a time out, changed it to a warning instead.
Fixes: #4261 
This was tested by running the smoke test
=> Changed test failure to warning

server/src/main/java/com/cloud/configuration/Config.java
Fixes: https://github.com/apache/cloudstack/issues/4318
Tested by changing the Global setting value on the UI
=> Change Global setting type for allow.user.create.projects

api/src/main/java/org/apache/cloudstack/api/response/NetworkACLItemResponse.java, api/src/main/java/org/apache/cloudstack/api/response/NetworkResponse.java, api/src/main/java/org/apache/cloudstack/api/response/PrivateGatewayResponse.java, server/src/main/java/com/cloud/api/ApiResponseHelper.java
Adding acl name to listNetworkAcl, listNetwork, listPrivateGateway, listVpcs responses
```
(localhost) 🐱 > list vpcs
{
"count": 1,
"vpc": [
{
"network": [
{
"aclid": "4a8a6365-f329-11ea-9aba-50eb71576f75",
"aclname": "default_allow",
..........
}
]
}
(localhost) 🐱 > list networks
{
"count": 1,
"network": [
{
"aclid": "4a8a6365-f329-11ea-9aba-50eb71576f75",
"aclname": "default_allow",
..........
}
]
}
(localhost) 🐱 > list networkacls 
{
"count": 4,
"networkacl": [
{
"aclid": "4a8a6365-f329-11ea-9aba-50eb71576f75",
"aclname": "default_allow",
..........
}
]
}
(localhost) 🐱 > list privategateways 
{
"count": 1,
"privategateway": [
{
"aclid": "4a8a4c78-f329-11ea-9aba-50eb71576f75",
"aclname": "default_deny",
..........
}
]
}
=> Adding acl name to listNetworkAcl, listNetwork, listPrivateGateway, listVpcs responses

engine/schema/src/main/resources/META-INF/db/schema-41310to41400.sql, engine/schema/src/main/resources/META-INF/db/schema-41400to41500.sql, services/secondary-storage/server/src/main/java/org/apache/cloudstack/storage/resource/NfsSecondaryStorageResource.java
Change upgrade path for image store table
Test Output:
Before migrate:
```
MariaDB [cloud]> select * from volume_store_ref\G
id: 8
store_id: 2
volume_id: 3
zone_id: 0
created: 2020-09-17 10:49:23
last_updated: NULL
job_id: NULL
download_pct: 0
size: 52428800
physical_size: 0
download_state: NULL
checksum: NULL
error_str: NULL
local_path: NULL
install_path: volumes/2/3/365df8ed-b414-4311-af46-82043ee056af.qcow2
url: NULL
download_url: NULL
state: Ready
...
*************************** 5. row ***************************
id: 22
store_id: 2
template_id: 202
created: 2020-09-17 10:49:26
last_updated: NULL
job_id: NULL
download_pct: 100
size: 52428800
store_role: Image
physical_size: 43646976
download_state: DOWNLOADED
error_str: …
```
=> change upgrade path to 4.14 (from 4.13) and intensify check

debian/cloudstack-agent.install
This tool was not added to the cloudstack-agent DEB package while it is added
to the RPM packages.
=> packaging/deb: Include cloudstack-guest-tool into cloudstack-agent DEB package

plugins/metrics/src/main/java/org/apache/cloudstack/response/HostMetricsResponse.java
Fixes the description for memory related fields
=> Fixing misleading HostMetricsResponse param description

framework/jobs/src/main/java/org/apache/cloudstack/framework/jobs/impl/AsyncJobManagerImpl.java
This PR fixes [CLOUDSTACK-10425](https://issues.apache.org/jira/browse/CLOUDSTACK-10425).
The patch remove the  password from resultObject and make it be humanreadable.
=> CLOUDSTACK-10425:Potential sensitive information disclosure

engine/schema/src/main/resources/META-INF/db/schema-410to420.sql, engine/schema/src/main/resources/META-INF/db/schema-41120to41200.sql
I faced an old issue when I upgrade cloudstack which database is restored from backup, and got the error in upgrade
```
2020-12-10 06:36:22,252 ERROR [c.c.u.d.ScriptRunner] (main:null) (logid:) java.sql.SQLSyntaxErrorException: Access denied; you need (at least one of) the SUPER privilege(s) for this operation
2020-12-10 06:36:22,255 ERROR [c.c.u.DatabaseUpgradeChecker] (main:null) (logid:) Unable to execute upgrade script
java.sql.SQLSyntaxErrorException: Access denied; you need (at least one of) the SUPER privilege(s) for this operation
at com.cloud.utils.db.ScriptRunner.runScript(ScriptRunner.java:185)
at com.cloud.utils.db.ScriptRunner.runScript(ScriptRunner.java:87)
at com.cloud.upgrade.DatabaseUpgradeChecker.runScript(DatabaseUpgradeChecker.java:201)
at …
```
=> db upgrade: use "create or replace view" instead of "alter view"

api/src/main/java/org/apache/cloudstack/api/command/user/template/GetUploadParamsForTemplateCmd.java, core/src/main/java/org/apache/cloudstack/storage/command/UploadStatusAnswer.java, engine/storage/src/main/java/org/apache/cloudstack/storage/image/deployasis/DeployAsIsHelperImpl.java, server/src/main/java/com/cloud/storage/ImageStoreUploadMonitorImpl.java, server/src/main/java/com/cloud/template/TemplateAdapterBase.java, server/src/main/java/org/apache/cloudstack/storage/image/deployasis/DeployAsIsHelper.java, services/secondary-storage/server/src/main/java/org/apache/cloudstack/storage/resource/NfsSecondaryStorageResource.java, services/secondary-storage/server/src/main/java/org/apache/cloudstack/storage/template/UploadEntity.java
This PR fixes the template upload from local on VMware
Go to Images -> Templates -> Upload from local
Select a template on VMware and upload it
=> VMware: Fix template upload from local

README.md
That time of the year :christmas_tree: - let's merge this without tests?
=> README: that time of the year! 🎄

engine/schema/src/main/java/com/cloud/upgrade/DatabaseUpgradeChecker.java, engine/schema/src/main/java/com/cloud/upgrade/dao/Upgrade41400to41410.java
This PR adds the upgrade path from 4.14.0.0 to 4.14.1.0
=> engine/schema: add upgrade path from 4.14.0.0 to 4.14.1.0

ui/src/components/view/ListView.vue
This PR is used to fix the Quick access menu bar missing for VM Snapshots
Fixes https://github.com/apache/cloudstack/issues/4607
UI
After fixed:
=> vmsnapshot: Add quickview to the list of VM Snapshot

ui/README.md
This PR fixes the path of screenshot on README of /ui directory. It was broken probably after the merge from the original repository of [cloudstack-primate](https://github.com/apache/cloudstack-primate) project.
Before:
After:
Navigate to the /ui directory and check if the screenshot appears on top of README file.
=> Fix screenshot path on README of /ui directory

plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
The bus type to `data disk` volumes is hardcoded to `virtio` or `scsi`, when using virtio-scsi (or, based on the template type). Therefore, there is no way to specify the bus type to data disk volumes (as we have for root disks). 
This PR intends to replicate the `rootDiskController` behavior to `dataDiskController`, allowing the definition of the controller.
It has been tested locally.
=> Replicate `rootDiskController` behavior to `dataDiskController`.

INSTALL.md
=> doc: fix typo in install notes

ui/src/config/section/account.js, ui/src/config/section/domain.js
Display creation date for account and domain
**NOTE: backend change is in https://github.com/apache/cloudstack/pull/4649**
=> Display creation date for domain and account

ui/src/views/infra/network/IpRangesTabPublic.vue
If account is null then "undefined" is displayed in ui
Before fix
After fix
=> Display account name only if its not null

tools/build/build_asf.sh
This PR changes the format of the md5 and sha512 files so they can be used with
```
md5sum --check <releasefile>.md5
```
and
```
sha512sum --check <releasefile>.sha512
```
respectively. 
on the command line
=> format of checksum files convenient for automated checking

packaging/README.md
Adds newer distros support for which added in #4068
=> packaging: update Requirements in README

ui/src/core/lazy_lib/components_use.js
Fixes https://github.com/apache/cloudstack/issues/4724
After fix:
- Autocomplex:
- Slider:
=> UI: add component was missing

ui/src/config/section/network.js, ui/src/views/infra/network/IpRangesTabGuest.vue, ui/src/views/infra/network/TrafficTypesTab.vue, ui/src/views/network/CreateVlanIpRange.vue, ui/src/views/network/GuestIpRanges.vue
Fixes https://github.com/apache/cloudstack/issues/4697
=> ui: Add guest IP ranges

ui/src/core/lazy_lib/components_use.js, ui/src/views/network/LoadBalancing.vue, ui/src/views/network/PortForwarding.vue, ui/src/views/network/VpcTiersTab.vue
Fixes https://github.com/apache/cloudstack/issues/4632
=> ui: FIX error in "Port forward" and "Load Balancing"

ui/src/config/section/compute.js
Adds displayname in the compute list view
=> ui: Show displayname in compute list view

ui/src/components/view/InfoCard.vue, ui/src/views/compute/DeployVM.vue
This PR shows the name of the VM in the info card next to the avatar rather than in the title
=> ui: Show vm name in info card in deployvm

python/lib/cloudutils/serviceConfig.py
This PR fixes the issue of libvirtd service not starting successfully, which leads to failure in setting up of cloudstack-agent
Addresses: https://github.com/apache/cloudstack/issues/4754
Issue noticed when cloudstack-setup-agent is run (while adding hosts):
```
[root@ref-trl-2525-k-M8-pearl-dsilva-kvm1 ~]# cloudstack-setup-agent  -m XX.XX.XX.XX -z 1 -p 1 -c 1 -g 4fe04fea-515c-4c4c-9c78-798554b483b2 -a -s  --pubNic=cloudbr1 --prvNic=cloudbr0 --guestNic=cloudbr1 --hypervisor=kvm
Starting to configure your system:
Configure SElinux ...         [OK]
Configure Network ...         [OK]
Configure Libvirt ...         [Failed]
Configuration failed for service Libvirt
Try to restore your system:
Restore SElinux ...           [OK]
Restore Network ...           [OK]
Restore Libvirt ... …
```
=> Mask libvirtd sockets which prevents cloudstack-agent from being setup

ui/src/views/iam/AddAccount.vue
Fixes https://github.com/apache/cloudstack/issues/4558
=> ui: change createAccount to use post

ui/src/components/view/ActionButton.vue
Adds a tooltip for the console action button
=> ui: Show label for view console action

ui/src/views/infra/zone/ZoneWizardZoneDetailsStep.vue, ui/src/views/network/CreateIsolatedNetworkForm.vue, ui/src/views/network/CreateL2NetworkForm.vue, ui/src/views/network/CreateNetwork.vue, ui/src/views/network/CreateSharedNetworkForm.vue, ui/src/views/network/VpcTiersTab.vue
Related https://github.com/apache/cloudstack-primate/pull/844
This PR to fix show display text instead of the name
=> UI: Network offering selection - Show display text instead of the name

ui/src/config/section/compute.js, ui/src/views/compute/EditVM.vue
Edit instance - offer existing Groups
This PR for fix https://github.com/apache/cloudstack-primate/issues/743
=> UI: Edit instance - offer existing Groups

ui/src/components/view/ListView.vue, ui/src/config/router.js, ui/src/views/AutogenView.vue
This PR for fix list view router-link goto account info instead of list account
After fixed:
=> UI: Fix list view router-link goto account info instead of list account

ui/src/components/view/ActionButton.vue
The button and the search part are different on the list view page
Before:
After:
=> UI: Fix the style action button

systemvm/debian/opt/cloud/bin/setup/router.sh, systemvm/debian/opt/cloud/bin/setup/vpcrouter.sh
Load necessary modules so that VPN connection works properly
=> Load modules to support NAT traversal in VR

ui/src/views/auth/Login.vue
Disables the login button while discovering features to prevent a double login / repetitive API calls
=> ui: Disable login button until redirected

utils/src/main/java/org/apache/cloudstack/utils/redfish/RedfishClient.java, utils/src/test/java/org/apache/cloudstack/utils/redfish/RedfishClientTest.java
Reverts apache/cloudstack#4846
=> Revert "Add 'break' at RedifshClient request re-try loop"

ui/src/views/image/UpdateTemplateIsoPermissions.vue
Fixes https://github.com/apache/cloudstack/issues/4031
=> UI: Fix update template permission with different domain

utils/src/test/java/com/cloud/utils/backoff/impl/ConstantTimeBackoffTest.java
=> tests: Extend wait time after interrupt (#4815)

ui/public/config.json, ui/src/views/infra/zone/ZoneWizardZoneTypeStep.vue
Fixes https://github.com/apache/cloudstack/issues/4863
=> UI: Restored the Basic Networking

ui/src/views/infra/zone/ZoneWizardLaunchZone.vue, ui/src/views/infra/zone/ZoneWizardPhysicalNetworkSetupStep.vue
Fixes https://github.com/apache/cloudstack/issues/4877
- physical Interface 1 to bridge cloudbr01, label for management traffic (cloudbr01)
- physical Interface 2 to bridge cloudbr03, label for guest traffic (cloudbr03guest)
- physical Interface 3 to bridge cloudbr02, label for storage traffic (cloudbr02100)
RESULT:
=> UI: Physical Network Setup in Zone Wizard

engine/schema/src/main/java/com/cloud/host/HostVO.java, plugins/hypervisors/kvm/src/main/java/org/apache/cloudstack/kvm/ha/KVMHostActivityChecker.java
This PR intends to improve logging in the class `KVMHostActivityChecker` to facilitate troubleshooting.
=> Improve logs on KVMHostActivityChecker

ui/src/views/network/IngressEgressRuleConfigure.vue
Fixes https://github.com/apache/cloudstack/issues/4919
BEFORE:
AFTER:
=> UI: Fixes security group egressrule and ingressrule mistake

ui/src/config/section/offering.js, ui/src/views/AutogenView.vue
added support to update tags of disk and network offerings from UI
fix for delete the last tag
manually tested
=> Support to update disk/network offering tags from UI

ui/src/views/compute/DeployVM.vue
Fixes https://github.com/apache/cloudstack/issues/4930
=> UI: Disabled root disk size customization if Service Offering has a fixed size

ui/src/views/infra/zone/PhysicalNetworksTab.vue
This PR shows the traffic types along in the physical networks tab
=> ui: Show traffic type in physical networks tab

debian/control
This PR...
Fixes #4928 
This has been tested by creating a cloudstack env on ubuntu 20 with 2 management servers.
=> Adding net tools as a dependency

tools/apidoc/gen_toc.py
This PR...
cloudstack/tools/apidocs/gen_toc.py changed variable name to avoid namecollision with reserved name.
=> changed variable name to avoid collision in python3

ui/src/components/view/DetailsTab.vue, ui/src/components/view/InfoCard.vue, ui/src/components/view/ListView.vue, ui/src/config/section/compute.js
Fixes https://github.com/apache/cloudstack/issues/4844
=> UI: Show IPv6 address of Instance

ui/src/components/view/ResourceView.vue, ui/src/views/network/PublicIpResource.vue, ui/src/views/plugins/quota/QuotaSummaryResource.vue
Fixes https://github.com/apache/cloudstack/issues/4961
=> UI: Save the tab and re-activate it after submitting the form.

ui/src/views/network/AclListRulesTab.vue
Fixes https://github.com/apache/cloudstack/issues/4973
=> ui: rename acl reason to description

ui/src/views/offering/AddComputeOffering.vue, ui/src/views/offering/AddDiskOffering.vue, ui/src/views/offering/AddNetworkOffering.vue, ui/src/views/offering/AddVpcOffering.vue, ui/src/views/offering/UpdateOfferingAccess.vue
Displays domain path instead of domain name,
=> ui: show domain paths for offering domain selection

ui/src/views/network/VpcTiersTab.vue
Fixes https://github.com/apache/cloudstack/issues/4985
=> UI: Prevent listing network offering with external LB for VPC tiers if a n/w already exists

ui/src/views/iam/DomainActionForm.vue
Fixes https://github.com/apache/cloudstack/issues/4984
=> ui: Adding success message for DomainActionForm

setup/bindir/cloud-setup-databases.in
This PR will allow reserved Linux shell characters to be passed to the setup databases script for the database secret key.
Fixes #4925
This can be tested by executing the script something like this
`cloudstack-setup-databases cloud:"password"@localhost --deploy-as=root:"password" -m "password" -k "Some&Crazy&Password"`
=> Fixed error when passing shell reserved characters to setup databases 

api/src/main/java/org/apache/cloudstack/api/command/user/vpn/CreateVpnCustomerGatewayCmd.java, api/src/main/java/org/apache/cloudstack/api/command/user/vpn/UpdateVpnCustomerGatewayCmd.java
This PR updates since and validations  attributes for the ikeversion and splitconnections parameters in vpn customer gateway cmd(s)
...
=> Updated since and validations attributes for the ikeversion and splitconnections parameters in vpn customer gateway cmd(s)

ui/src/components/view/TreeView.vue, ui/src/views/iam/DomainActionForm.vue, ui/src/views/iam/DomainView.vue
Fixes https://github.com/apache/cloudstack/issues/4975
When a domain is generated by another client, the treeview is modified when clicking the refresh button.
After fixes:
=> UI: Update treeview when click the refresh button

engine/schema/src/main/java/com/cloud/dc/DataCenterVO.java, engine/schema/src/main/java/com/cloud/vm/VMInstanceVO.java, services/secondary-storage/controller/src/main/java/org/apache/cloudstack/secondarystorage/SecondaryStorageManagerImpl.java, services/secondary-storage/controller/src/test/java/org/apache/cloudstack/secondarystorage/SecondaryStorageManagerTest.java
This PR intends to improve logging in the class `SecondaryStorageManagerImpl` to facilitate troubleshooting and refactor a few process.
=> Improve logs on SecondaryStorageManagerImpl and few refactors

server/src/main/java/org/apache/cloudstack/ha/HAManagerImpl.java
This PR intends to improve logging in the class `HAManagerImpl` to facilitate troubleshooting.
=> Improve logs on HAManagerImpl

scripts/vm/hypervisor/kvm/kvmvmactivity.sh
This PR intends to improve logging in the file `kvmvmactivity.sh` to facilitate troubleshooting.
=> Improve logs on kvmvmactivity.sh

plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/KVMHABase.java, plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/KVMHAChecker.java, plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/KVMHAVMActivityChecker.java
This PR intends to improve logging in the class `KVMHAVMActivityChecker` to facilitate troubleshooting.
=> Improve logs on KVMHAVMActivityChecker

engine/components-api/src/main/java/com/cloud/network/IpAddressManager.java, server/src/main/java/com/cloud/network/IpAddressManagerImpl.java, server/src/main/java/com/cloud/network/rules/DhcpSubNetRules.java, server/src/main/java/com/cloud/server/ManagementServerImpl.java, systemvm/debian/opt/cloud/bin/configure.py
This PR fixes #4943
This PR contains two changes
(1) assign ip in new subnet as alias of guest IP in first subnet.
If there are free IPs in first subnet, cloudstack acquires a IP from them as alias, which is obviously wrong(dhcp does not work).
Java code changes in this PR fixes it.
(2) add missing iptables rules for port 80(apache2/metadata) and port 8080 (password server).
The rules are added in python but not applied in VR, which cause password server and metadata/userdata not work in new subnet. 
Python code changes in this PR fixes it.
=> network/VR: fix dhcp/password/metadata issues on shared networks with multiple subnets

api/src/main/java/com/cloud/resource/ResourceState.java, engine/components-api/src/main/java/com/cloud/ha/HighAvailabilityManager.java, engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java, server/src/main/java/com/cloud/ha/HighAvailabilityManagerImpl.java, server/src/main/java/com/cloud/resource/ResourceManagerImpl.java
This PR fixes two issues. see description of each commit
=> forceha: fix two issues when (1)stop vm from inside (2) force remove host

setup/bindir/cloud-setup-databases.in
Fixes issue of passing password and management secret key with special
characters.
=> setup: pass password in quotes for cloudstack-setup-databases

ui/public/locales/en.json, ui/src/views/network/VpcTab.vue, ui/src/views/network/VpcTiersTab.vue
This PR improves the user experience of ‘ACL’ field in the dialog of creating a new VPC tier on UI.
'ACL' is a mandatory field (no selection by default).
warning message is displayed for in-built ACL policies (default_allow and default_deny)
=> UI: Make 'ACL' field as mandatory and add warning message for default_allow and default_deny

ui/src/config/section/image.js
When an ISO is not marked as extractable, the download button should not be displayed in the UI.
Fixes: #4535 
This was tested by uploading an iso as a user with and without the extractable switch enabled.
Tested extraction of ISO by calling the API and by using the UI.
Tested extraction by Admin.
Tested extraction by a user in a project.
=> Removed download icon when ISO is not extractable for users

plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java, plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageLayoutHelper.java, plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageProcessor.java, vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/DatastoreMO.java, vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/HostMO.java, vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/HypervisorHostHelper.java
This PR fixes the issue of missing fcd folder in local storage in case of VMware vSphere.
with this fix, a folder with name fcd is created whenever local storage is initiated.
1. Created local storage on vSphere and enabled local storage in zone. Restarting MS recognised local storage and created fcd folder in the local storage
2. Tested on existing local storage which does not have fcd folder. restarting MS created missing folder fcd in the local storage
3. Created a VM with root disk on local storage
4. Created a VM with root disk and data disk on local storage
5. Created a VM with root disk on local storage and data disk on shared storage
=> Create fcd folder on local storage in VMware vSphere

ui/src/views/iam/AddUser.vue
AddUser form wrongly shows the account dropdown when adding a user for an account. Account dropdown remains empty in the form.
When an account is not selected prior to opening the form, the account input should be required.
Without change:
With change:
=> ui: fix adduser form

ui/src/views/compute/wizard/ComputeOfferingSelection.vue, ui/src/views/compute/wizard/NetworkConfiguration.vue
=> ui: fix focus in deployvm form

engine/schema/src/main/java/com/cloud/network/VpnUserVO.java, engine/schema/src/main/java/com/cloud/user/AccountVO.java, server/src/main/java/com/cloud/network/vpn/RemoteAccessVpnManagerImpl.java, server/src/test/java/com/cloud/network/vpn/RemoteAccessVpnManagerImplTest.java
This PR intends to improve logging in the class `RemoteAccessVpnManagerImpl` to facilitate troubleshooting and refactor a few process.
=> Improve logs on RemoteAccessVpnManagerImpl

ui/src/views/image/RegisterOrUploadTemplate.vue
=> ui: show read from ova only for ova format

engine/components-api/src/main/java/com/cloud/storage/StorageManager.java, plugins/storage/volume/scaleio/pom.xml, plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/client/ScaleIOGatewayClient.java, plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/client/ScaleIOGatewayClientConnectionPool.java, plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/client/ScaleIOGatewayClientImpl.java, plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/lifecycle/ScaleIOPrimaryDataStoreLifeCycle.java, plugins/storage/volume/scaleio/src/test/java/org/apache/cloudstack/storage/datastore/client/ScaleIOGatewayClientImplTest.java, server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java, server/src/main/java/com/cloud/storage/StorageManagerImpl.java, server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
This PR updates the PowerFlex/ScaleIO gateway client with the following improvements.
- Added connection manager to the gateway client.
- Renew the client session on '401 Unauthorized' response.
- Refactored the gateway client calls, for GET and POST methods.
- Consume the http entity content after login/(re)authentication and close the content stream if exists.
- Updated storage pool client connection timeout configuration 'storage.pool.client.timeout' to non-dynamic (It's value is picked by the ScaleIO client when it is created, which is either on the primary storage addition or management server (re)start for existing pools. In order to apply the updated config value for existing pools, it is required to restart the management server).
- Added storage pool client max connections …
=> Updated PowerFlex/ScaleIO gateway client with some improvements.

server/src/main/java/com/cloud/vm/UserVmManagerImpl.java, server/src/test/java/com/cloud/vm/UserVmManagerTest.java
This PR fixes the issue that nic has wrong gateway after updating vm nic.
(1) create shared network (in advanced zone or advanced zone with sg)
(2) create new shared network (with same startip/endip/netmask, but different gateway).
(3) create a vm in new network
(4) stop vm and update vm nic ip address
Expected result:
The vm has correct gateway and netmask (of second network)
Actual result:
The vm has wrong gateway and netmask (of first network)
=> server: set correct gateway when update vm nic on shared networks

ui/src/components/view/InfoCard.vue, ui/src/views/compute/DeployVM.vue
Shows default next to the default network / nic
=> ui: Show default nic/network in infocard

plugins/hypervisors/kvm/src/main/java/org/apache/cloudstack/utils/linux/KVMHostInfo.java, server/src/main/java/com/cloud/resource/ResourceManagerImpl.java
This PR intends to improve logging on agent start to facilitate troubleshooting.
=> Improve logs on agent start

plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java, test/integration/smoke/test_volumes.py
Fixes #3290
After detach device is executed we are checking into XML description that the device isn't there
- [X ] Bug fix (non-breaking change which fixes an issue)
- [ X] Minor
Manual tests according to the  steps to reproduce
=> fix of detach volume while OS is in boot state

systemvm/debian/opt/cloud/bin/configure.py
This PR fixes https://issues.apache.org/jira/browse/CLOUDSTACK-10075
by reverting a line in a previous commit 
https://github.com/apache/cloudstack/commit/065fa1c849dd09dd734778913bc50c844aa0aee3#diff-c78f7f699938cf529cbcef26bda2ed93630b58f336986fd0753fbfa1a6adbc43L103-R103
1. create advanced zone with isolated networks,
2. create vm
3. add egress rules with protocol=all, source cidr is  <ip>/32  (not vm ip), dest cidr is 8.8.8.8/32
prior result: ping 8.8.8.8 works in vm
with this pr: ping 8.8.8.8 does not work in vm
4. add egress rules with protocol=icmp, source cidr is empty (therefore whole network), dest cidr is 8.8.8.8/32
ping 8.8.8.8 works in vm
=> VR: fix source cidr of egress rules are not applied

ui/src/components/view/QuickView.vue
Fixes https://github.com/apache/cloudstack/issues/5126
Destroy a systemVM and press the refresh button until a new one comes up. Quickview option will display when resource running.
=> UI: SystemVM - Enabling Quickview for newly resource

ui/src/components/view/SearchView.vue
TooltipButton was not added as Vue component. It was leading to error in page load.
Before (logs in console):
After (SearchView shows button with tooltip):
UI
=> ui: fix missing component in SearchView

packaging/centos7/cloud.spec, packaging/centos8/cloud.spec
This PR creates the cloud group as well as the user if not present. Prevents errors / permission issues during setting up the MS
=> packaging: Create cloud user and group if not present

api/src/main/java/org/apache/cloudstack/api/ApiConstants.java, api/src/main/java/org/apache/cloudstack/api/command/admin/router/ListRoutersCmd.java, api/src/main/java/org/apache/cloudstack/api/response/DomainRouterResponse.java, server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
=> server: list routers by healthchecksfailed

test/integration/smoke/test_volumes.py
This PR fixes recent travis failures in travis job 5
run in lab env (similar to trillian)
```
Test Volume creation for all Disk Offerings (incl. custom) ... === TestName: test_01_create_volume | Status : SUCCESS ===
ok
Attach a created Volume to a Running VM ... === TestName: test_02_attach_volume | Status : SUCCESS ===
ok
Download a Volume attached to a VM ... === TestName: test_03_download_attached_volume | Status : SUCCESS ===
ok
Delete a Volume attached to a VM ... === TestName: test_04_delete_attached_volume | Status : SUCCESS ===
ok
Detach a Volume attached to a VM ... === TestName: test_05_detach_volume | Status : SUCCESS ===
ok
Download a Volume unattached to an VM ... === TestName: test_06_download_detached_volume | Status : SUCCESS ===
ok
Test resize (negative) non-existent …
```
=> (auto) formatting and cleanup fixes for test_volumes

test/integration/smoke/test_direct_download.py, test/integration/smoke/test_domain_network_offerings.py, test/integration/smoke/test_domain_vpc_offerings.py, test/integration/smoke/test_primary_storage.py, test/integration/smoke/test_vm_life_cycle.py
This PR skips / fixes tests in Local storage and SG enabled zones
TODO
=> tests: Fix test failures for Local storage and Basic zones

debian/cloudstack-management.postinst, packaging/centos7/cloud.spec, packaging/centos8/cloud.spec
The following DB parameters are already updated as part of inclusivity changes (Refer: commit fe4a5b6e938e2f677d5d78cb5e6a12dce60a4a00 [1]). The new options 'secondsBeforeRetrySource', 'queriesBeforeRetrySource' works with mysql connector 8.0 [2][3] and supported for MySQL Server 5.6, 5.7 and 8.0.
- db.cloud.slaves => db.cloud.replicas
- db.cloud.secondsBeforeRetryMaster =>	db.cloud.secondsBeforeRetrySource
- db.cloud.queriesBeforeRetryMaster => db.cloud.queriesBeforeRetrySource
- db.usage.slaves => db.usage.replicas
- db.usage.secondsBeforeRetryMaster => db.usage.secondsBeforeRetrySource
- db.usage.queriesBeforeRetryMaster => db.usage.queriesBeforeRetrySource
This PR replaces these DB properties having master and slave(s), with source and replica(s) respectively on upgrade (for …
=> On Upgrade, Replace the DB properties having master and slave(s), with source and replica(s) respectively for inclusiveness

plugins/hypervisors/kvm/src/main/java/com/cloud/ha/KVMInvestigator.java
This PR fixes vm ha on zone-storage poools. this is part of PR #4708 
Fixes #2708
=> kvm: fix VM HA on zone-wide storage pools

ui/src/views/infra/zone/ZoneWizardLaunchZone.vue
Fixes https://github.com/apache/cloudstack/issues/5166
=> UI - zone wizard - fix undefined property when setting RBD primary storage

plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java, plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtMigrateCommandWrapper.java, plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtPlugNicCommandWrapper.java, scripts/storage/secondary/createvolume.sh, server/src/main/java/com/cloud/network/rules/RulesManagerImpl.java, setup/bindir/cloud-set-guest-sshkey-configdrive.in, test/integration/component/test_configdrive.py
This PR fixes a series of bug when test test_configdrive.py
(1) detachAnd Attach ConfigDrive ISO on kvm, in some cases configdrive ISO is updated, for example, plug a new nic, or migrate vm.
(2) use "copy" instead of "mv" when create configdrive ISO in SSVM, as configdrive ISO will disappear in VM if "mv" is used.
(3) fix two exceptions when enable/disable static nat on vms with configdrive ISO. (public IP in configdrive ISO is updated in these two cases)
(4) fix two issues in setup/bindir/cloud-set-guest-sshkey-configdrive.in 
(5) fix few bugs in test/integration/component/test_configdrive.py
(6) build and use centos55 with both sshkey and configdrive support for testing.
tested on with kvm.
=> configdrive: fix some failures in tests/component/test_configdrive.py

ui/src/views/infra/zone/ZoneWizardPhysicalNetworkSetupStep.vue
Fixes https://github.com/apache/cloudstack/issues/5177
=> [UI] zone wizard: change edit traffic type form of VMware

api/src/main/java/org/apache/cloudstack/api/command/user/firewall/CreateFirewallRuleCmd.java, api/src/main/java/org/apache/cloudstack/api/command/user/loadbalancer/CreateLoadBalancerRuleCmd.java, api/src/main/java/org/apache/cloudstack/api/command/user/nat/CreateIpForwardingRuleCmd.java
This is a follow-up to #4037 .
The CIDR_LIST parameter was only deprecated for CreateIpForwardingRule, CreateLoadBalancerRule and CreatePortForwardingRule. It is still supported for CreateFirewallRule.
This PR documents the deprecation in all these API calls, and reverts the deprecation for CreateFirewallRule.
@weizhouapache 
N/A
=> Fix deprecation of CIDR_LIST parameter

server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
This PR includes the changes to remove volume only on expunge.
Manually tested destroy and recover volumes.
=> Do remove volume only on expunge

ui/src/views/image/IsoZones.vue, ui/src/views/image/TemplateZones.vue, ui/src/views/network/EgressRulesTab.vue, ui/src/views/network/FirewallRules.vue, ui/src/views/network/IpAddressesTab.vue, ui/src/views/network/LoadBalancing.vue, ui/src/views/network/PortForwarding.vue
Uses the appropriate icon for delete
Amongst others :
=> ui: Replace bulk delete icons

ui/src/views/compute/MigrateVMStorage.vue, ui/src/views/network/EgressRulesTab.vue, ui/src/views/network/FirewallRules.vue, ui/src/views/network/IpAddressesTab.vue, ui/src/views/network/LoadBalancing.vue, ui/src/views/network/PortForwarding.vue
Continuation of https://github.com/apache/cloudstack/pull/4782 after merging with main
=> ui: Fix async poll job

ui/src/utils/plugins.js, ui/src/views/AutogenView.vue
Fixes page not refreshing on sync API calls
=> ui: Fix refresh issue

ui/src/config/section/compute.js
This PR fixes the issue on ui that scalevm button is disabled when vm is stopped.
prior this fix
with this fix
=> ui bug fix: scalevm is disabled when vm is Stopped

ui/public/locales/en.json, ui/src/components/view/ListView.vue, ui/src/components/widgets/Status.vue
Now shows the value of current in vmsnapshot listview
=> ui: Fix current for vmsnapshots

ui/src/utils/sort.js
Fixes the error thrown when trying to sort boolean values in listview
Head on over to /vmsnapshots
Before :
=> ui: Fix comparator for boolean

ui/src/utils/plugins.js
Fixes the header showing progress for a job that failed
Before :
After :
=> ui: Update header notice if job failed

ui/src/views/AutogenView.vue
Skip only empty strings while submitting UI form.
Fixes #5223
=> ui: submit form with false boolean params

engine/schema/src/main/java/com/cloud/vm/ConsoleProxyVO.java, server/src/main/java/com/cloud/consoleproxy/ConsoleProxyManagerImpl.java, server/src/test/java/com/cloud/consoleproxy/ConsoleProxyManagerTest.java
This PR intends to improve logging in the class `ConsoleProxyManagerImpl` to facilitate troubleshooting and refactor a few process.
=> Improve logs on ConsoleProxyManagerImpl and refactor a few process

ui/src/views/tools/ImportUnmanagedInstance.vue
Wrong key 'title' was used instead of 'label'
Before:
.
.
.
.
After:
=> ui: fix import instance form root disk label

ui/src/views/infra/zone/ZoneWizardLaunchZone.vue
This PR for fix zone launch - change the argument params.ipv6dns2 of createZone
=> UI -  zone wizard - change the argument of params.ipv6dns2

server/src/main/java/com/cloud/network/router/VirtualNetworkApplianceManagerImpl.java
This PR fixes VR heallth check error in vmware basic zone (#4158).
=> server: fix VR health check in vmware basic zone

ui/src/utils/plugins.js, ui/src/views/AutogenView.vue, ui/tests/unit/views/compute/MigrateWizard.spec.js
Fixes the error when building the UI
```
⇒  npm run serve                                        
> cloudstack-ui@1.0.0 serve /home/shwstppr/lab/shapeblue/cloudstack/ui
> vue-cli-service lint --no-fix && vue-cli-service serve
error: 'originalPage' is assigned a value but never used (no-unused-vars) at src/utils/plugins.js:59:9:
57 |         action = null,
58 |         bulkAction = false,
> 59 |         originalPage = null
|         ^
60 |       } = options
61 | 
62 |       store.dispatch('AddHeaderNotice', {
error: Parsing error: Unexpected token
810 | 
811 |         return resolve(false)
> 812 |       })
|        ^
813 |     },
814 |     execSubmit (e) {
815 |       e.preventDefault() at src/views/AutogenView.vue:1191:7:
1189 | 
1190 |         return resolve(false)
> 1191 |       })
| …
```
=> ui: Fix failing UI

plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/KVMHAChecker.java, scripts/vm/hypervisor/kvm/kvmheartbeat.sh
This PR intends to improve some logging in the HA process to facilitate troubleshooting.
=> Improve HA logs

ui/src/views/compute/DeployVM.vue, ui/src/views/compute/wizard/ComputeSelection.vue, ui/src/views/tools/ImportUnmanagedInstance.vue, ui/src/views/tools/ManageInstances.vue
7123269 and 535761b introduced changes that are affecting Import Instance form.
Custom compute selection was not showing properly.
On import error was seen in UI.
=> ui: fix import instance form for recent changes

ui/src/components/widgets/Status.vue
Fixes https://github.com/apache/cloudstack/issues/5255
Adds 'On' to the success case of the status icon
=> ui: Add 'on / off' to status icon and make it case insensitive

ui/src/views/AutogenView.vue
Fixes #5284
Fix for handling action API response
=> ui: fix handle action API response

ui/src/components/view/DedicateModal.vue, ui/src/components/view/ResourceLimitTab.vue, ui/src/views/network/CreateSharedNetworkForm.vue, ui/src/views/network/CreateVlanIpRange.vue, ui/src/views/network/CreateVpc.vue, ui/src/views/network/FirewallRules.vue, ui/src/views/network/PortForwarding.vue, ui/src/views/network/VpcTiersTab.vue, ui/src/views/network/VpnDetails.vue, ui/src/views/offering/AddDiskOffering.vue, ui/src/views/offering/AddNetworkOffering.vue, ui/src/views/plugins/quota/EditTariffValueWizard.vue
Related https://github.com/apache/cloudstack/pull/4766#issuecomment-895102015
Fix error not found ref in submit button when pressing Ctrl+Enter
=> UI - Fixes - Ctrl+Enter events error

ui/src/views/tools/ImportUnmanagedInstance.vue
This PR fixes the issue encountered while listing projects to which the VM is to be imported to.
Provides a list of projects present to select, to which the VM is to be imported which wasn't being displayed prior to the fix
=> ui (importUnmanagedInstance) : Show project list to which the instance is to be imported

ui/src/views/compute/MigrateWizard.vue
Fixes https://github.com/apache/cloudstack/issues/5322
=> UI - systemVM - Fix error message `jobid` not found when moving to another host

ui/docker.sh
This PR adds the possibility to choose between docker and podman to run the docker.sh script from the command line. From now on you are able to add a flag after the script (-p) to run the script with podman. @weizhouapache For backwardwards compatibility, docker is used by default.
=> Possiblity to choose between docker and podman from the command line

plugins/metrics/src/test/java/org/apache/cloudstack/response/HostMetricsResponseTest.java
This PR fixes jenkins build failures due to missing license header.
=> add license header in HostMetricsResponseTest.java

scripts/vm/network/security_group.py, test/integration/component/test_multiple_nic_support.py
This PR fixes component test failure with test_multiple_nic_support.py, in advanced zone with security groups.
manually run the component test, all passed.
```
Create Vm with multiple NIC's ... === TestName: test_01_create_vm_with_multiple_nics | Status : SUCCESS ===
ok
Create VM with single NIC and then add additional NIC ... === TestName: test_02_add_nic_to_vm | Status : SUCCESS ===
ok
Add secondary IP's to the VM ... === TestName: test_03_add_ip_to_default_nic | Status : SUCCESS ===
ok
Add secondary IP's to remaining NIC's ... === TestName: test_04_add_ip_to_remaining_nics | Status : SUCCESS ===
ok
Stop and Start a VM with Multple NIC ... === TestName: test_05_stop_start_vm_with_multiple_nic | Status : SUCCESS ===
ok
Migrate a VM with Multple NIC ... === TestName: …
```
=> security group: fix component test test_multiple_nic_support.py failures 

server/src/main/java/com/cloud/resource/ResourceManagerImpl.java
Currently it is possible to add the same tag several times. This PR remove the doubles for api and ui input.
In own Vmware env.
=> remove doubles before save

plugins/user-authenticators/ldap/pom.xml
Updates maven missing dependency
=> updated maven dependency due to #5363

plugins/storage/volume/default/src/main/java/org/apache/cloudstack/storage/datastore/driver/CloudStackPrimaryDataStoreDriverImpl.java, server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
This PR fixes the issue that volume is removed from cloudstack DB but not removed from primary storage or secondary storage.
steps to reproduce the issue on kvm
(1) create a volume, attach to a vm, detach it
(2) stop all cloudstack-agent
(3) remove the volume.
=> server: do not remove volume from DB if fail to expunge it from primary storage or secondary storage

ui/src/views/compute/DeployVM.vue
Fixes https://github.com/apache/cloudstack/issues/5389
=> ui: Refresh page on deployvm result

plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/manager/VmwareStorageManagerImpl.java, plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java, plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageProcessor.java, vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/HypervisorHostHelper.java, vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/VirtualMachineMO.java, vmware-base/src/main/java/com/cloud/hypervisor/vmware/util/VmwareClient.java
This PR cancels the pending tasks for a worker VM (in VMware hypervisor) before destroying it.
Fixes: #3408
Set following global settings:
job.expire.minutes : 1
job.cancel.threshold.minutes : 1
vmware.clean.old.worker.vms : true
- Create a big size DATA disk, and add some dummy files (after creating file system) to it.
- Take volume snapshot
=> [VMware] Cancel the pending tasks for a worker VM before destroying it

engine/schema/src/main/java/com/cloud/upgrade/DatabaseUpgradeChecker.java, engine/schema/src/main/java/com/cloud/upgrade/dao/Upgrade41510to41520.java, engine/schema/src/main/resources/META-INF/db/schema-41510to41520-cleanup.sql, engine/schema/src/main/resources/META-INF/db/schema-41510to41520.sql
Add upgrade path and schema for 4.15.2
=> Add 4.15.2 schema and upgrade path

ui/legacy/scripts/projects.js
=> Legacy UI: Display Accounts Tab to Project Admins

server/src/main/java/com/cloud/network/element/ConfigDriveNetworkElement.java, server/src/main/java/com/cloud/vm/UserVmManagerImpl.java, server/src/test/java/com/cloud/vm/UserVmManagerImplTest.java
This PR fixes the issue that reset sshkey is broken in master/4.16 branch.
It is a regression issue of #4819
=> server: fix reset sshkey is broken in master/4.16

plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStoragePoolManager.java
Discussed here, https://github.com/apache/cloudstack/issues/5309#issuecomment-898330887
Log is not actually an ERROR level log.
=> cleanup: kvm-storage - fix misleading error log

ui/src/views/image/RegisterOrUploadTemplate.vue
NIC Adapter type option is missing in Register/Upload template form.
This PR fixes the behaviour
Before:
After:
=> ui: show nicAdapter selection for VMware non-readfromova template

ui/src/views/AutogenView.vue
This PR fixes the action buttons for IP addresses, needed a refresh before the fix
=> Fix public IP actions buttons not working unless refreshing the page

ui/src/views/compute/DeployVM.vue
Sends the deployVM api call as POST since the userdata can be extremely long and result in an URI too long exception
=> ui: Send deployvm api call as post

server/src/main/java/com/cloud/capacity/CapacityManagerImpl.java
=> server: skip max guest limit check for KVM host

ui/src/components/view/DetailsTab.vue
Fixes https://github.com/apache/cloudstack/issues/5444
BEFORE
AFTER
=> UI - Remove white space after detail string in Firefox

engine/schema/src/main/java/com/cloud/usage/dao/UsageNetworkDaoImpl.java, engine/schema/src/main/resources/META-INF/db/schema-41520to41600.sql, usage/src/main/java/com/cloud/usage/UsageManagerImpl.java, usage/src/main/java/com/cloud/usage/parser/NetworkUsageParser.java
If vm has multiple nics belonging to different shared networks then
wrong statistics will be collected since network id is not considred
as primary key. Make the change so that primary key contains network
id so that traffic belonging to that corresponding network is shown
If network id is not added to primary key then all the traffic of all
shared networks will show up in one nic.
=> VM has wrong network statistics with multiple nics in shared networks

server/src/main/java/com/cloud/vm/UserVmManagerImpl.java, ui/public/locales/en.json, ui/src/config/section/compute.js, ui/src/views/compute/EditVM.vue
This PR attempts to fix: https://github.com/apache/cloudstack/issues/5120 - which updates DNS on changing the hostname of a 'Running' VM 
Created 2 VMs (say, VM1 and VM2) in an Isolated network, updated the hostname of one of the VMs (VM1 ->  VM1-newName) and attempted pinging the VM1-newName from VM2
dhcophosts.txt details on Router of network1
=> api: Update DNS on changing VM name

agent/conf/agent.properties, engine/orchestration/src/main/java/com/cloud/agent/manager/AgentManagerImpl.java, plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java, plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtMigrateCommandWrapper.java, server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
=> kvm: honor migrate.wait and abort vm migration job

python/lib/cloudutils/serviceConfig.py, python/lib/cloudutils/syscfg.py
Fixes https://github.com/apache/cloudstack/issues/4063
Adds a check whether the kvm host meets the minimum system requirements based on http://docs.cloudstack.apache.org/en/latest/installguide/overview/_requirements.html#host-hypervisor-system-requirements
```
Starting to configure your system:
Configure Host ...            [Failed]
Configuration failed for service Host
Try to restore your system:
Restore Host ...              [OK]
```
```
DEBUG:root:execute:awk '/MemTotal/ { printf "%.3f \n", $2/1024 }' /proc/meminfo
DEBUG:root:CloudStack requires a minimum of 4096 MB and more than 9000 MB memory since 9000 MB is reserved
```
=> kvm: Add check if host meets the minimum requirements

server/src/main/java/com/cloud/api/ApiSerializerHelper.java, server/src/main/java/com/cloud/api/ApiServer.java
This PR updates the event message with proper json format for cmd info and job result, so that the published message can be properly parsed with json.
Fixes: #4468 
Manually verified the published messages in RabbitMQ server queue. Some messages before & after changes below.
**Before Changes:**
VM START =>
`{"jobId":"c60b3175-07fb-41ce-bc30-b5613cb3367f","commandEventType":"VM.START","processStatus":"0","cmdInfo":"{\"response\":\"json\",\"ctxUserId\":\"2\",\"httpmethod\":\"GET\",\"ctxStartEventId\":\"189\",\"id\":\"02131cb7-267e-4243-b84d-db1c372ada1d\",\"ctxDetails\":\"{\\\"interface com.cloud.vm.VirtualMachine\\\":\\\"02131cb7-267e-4243-b84d-db1c372ada1d\\\"}\",\"ctxAccountId\":\"2\",\"uuid\":\"02131cb7-267e-4243-b84d-db1c372ada1d\",\"cmdEventType\":\"VM.START\"}","instanceType":"Virtual …
=> Updated the event message with proper json format for cmd info and job result

ui/src/components/view/InfoCard.vue
Display link for acl id which is associated
with the private gateway
=> Display ACL id for the private gateway

ui/src/views/network/StaticRoutesTab.vue
This PR fixes the issue that nothing is displayed on UI when list static route in a VPC which belongs to other accounts.
=> UI: list static routes with listall=true

engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
This PR allows cleaning up nics in case there are nicExpunge commands to be sent
Fixes: #5308
=> [Vmware] Add missing condition to cleanup nics if there are commands to send

ui/src/components/view/ListView.vue
This PR moves the resource icon to the first column - VM Name - in the Instance List View. With the following change https://github.com/apache/cloudstack/commit/413d10dd8106af9b3c369c1a393fbcca5e7217ce#diff-93b52572e13887859e26011826bd9744351c29e7a0de514ea308d503113a13e3L41-R41 the icon now appears on the second column, which looks odd.
- [X ] Minor
Prior Fix:
Post Fix:
=> ui: Move resource icon to first column for VM list view

server/src/main/java/com/cloud/server/ManagementServerImpl.java
This PR fixes the issue that "Free" public ip addresses are listed twice in api response.
there is no issue with api if domainid, account or allocatedonly=true is passed.
there is no issue on UI.
```
(localcloud) SBCM5> > list publicipaddresses forvirtualnetwork=true allocatedonly=false filter=ipaddress,state,
{
"count": 36,
{
"ipaddress": "10.0.55.9",
"state": "Free"
},
{
"ipaddress": "10.0.55.8",
"state": "Free"
},
{
"ipaddress": "10.0.55.7",
"state": "Free"
},
{
"ipaddress": "10.0.55.6",
"state": "Free"
},
{
"ipaddress": "10.0.55.5",
"state": "Free"
},
{
"ipaddress": "10.0.55.4",
"state": "Free"
},
{
"ipaddress": "10.0.55.3",
"state": "Allocated"
},
{
"ipaddress": "10.0.55.20",
"state": "Free"
},
{
"ipaddress": "10.0.55.2",
"state": "Allocated"
},
{
"ipaddress": …
```
=> server: fix list public ip returns duplicated records

engine/schema/src/main/java/com/cloud/upgrade/dao/Upgrade410to420.java
=> change logging during upgrade

ui/src/views/compute/EditVM.vue
Fixes passing accountid and projectid while fetching instance groups while editing a VM in a project
=> ui: Fix editVM in projectview

server/src/main/java/com/cloud/api/ApiResponseHelper.java
Display some properties (eg RedundantRouter) in listNetworks response which are initializd in VirtualRouterElement.setCapabilities()
listNetworks response for ```StaticNat``` service before the change
```
{
"name": "StaticNat"
},
```
listNetworks response for ```StaticNat``` after the change
```
{
"capability": [
{
"canchooseservicecapability": false,
"name": "ElasticIp",
"value": "false"
},
{
"canchooseservicecapability": false,
"name": "AssociatePublicIP",
"value": "true"
}
],
"name": "StaticNat",
"provider": [
{
"name": "VirtualRouter"
}
]
},
```
=> Display capability info in listNetwork response

ui/src/components/view/ListView.vue
=> UI: Fix VM state column

plugins/backup/veeam/src/main/java/org/apache/cloudstack/backup/VeeamBackupProvider.java, plugins/backup/veeam/src/main/java/org/apache/cloudstack/backup/veeam/VeeamClient.java, server/src/main/java/org/apache/cloudstack/backup/BackupManagerImpl.java
This PR intends to improve logs in Veeam Backup Plugin, to help troubleshooting. Also, I removed some duplicated code.
- I maked a new build with this alterations and test in a local lab;
- I run some tests, like import a backup offering, assign VM to backup offering, try listing backups, etc;
- And I readed the logs to verify if the new informations appears.
=> Improve Veeam Plugin logs

plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/CitrixResourceBase.java, server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
=> server: add vm boot details for start vm api

ui/src/config/section/event.js
This PR fixes: https://github.com/apache/cloudstack/issues/5519. Users unable to archive / delete their events.
Was able to delete / archive events  when logged in with user account role.
=> Allow users (User account Role) to delete / archive events

ui/src/views/infra/zone/ZoneWizardAddResources.vue, ui/src/views/infra/zone/ZoneWizardLaunchZone.vue
This PR add datastore cluster protocol in zone wizard for vmware.
At the moment, I've no option to add a new zone in my test environment therefore i couldn't test this.
=> merge main

ui/src/components/view/ListView.vue, ui/src/components/view/QuickView.vue, ui/src/views/AutogenView.vue, ui/src/views/plugins/quota/EditTariffValueWizard.vue, ui/src/views/plugins/quota/QuotaTariff.vue, ui/tests/common/index.js, ui/tests/mock/mockStore.js, ui/tests/unit/views/AutogenView.spec.js, ui/tests/unit/views/compute/MigrateWizard.spec.js
Fixes https://github.com/apache/cloudstack/issues/5524
After fixes:
=> UI - Fixes modal width by device screen

ui/src/views/network/CreateSharedNetworkForm.vue
Fixes https://github.com/apache/cloudstack/issues/5529
AFTER fix:
=> UI - Remove duplicate endipv6 item in shared network

engine/schema/src/main/java/com/cloud/storage/dao/VolumeDao.java, engine/schema/src/main/java/com/cloud/storage/dao/VolumeDaoImpl.java, server/src/main/java/com/cloud/deploy/DeploymentPlanningManagerImpl.java, server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
This PR fixes #4406  (probably)
In some cases, the disk offering of ROOT disk is not same as service offering of VM.
for example
(1) create a vm but not start it, then scale vm to another service offering
(2) reinstall vm, then scale vm to another service offering
These two issues are fixed by this PR.
The issue might exist in some other scenarios, so it would be better to always update ROOT disk offering tags to the tags of vm service offering in DeploymentPlanningManagerImpl.java.
=> server: check service offering (storage) tags when reallocate a ROOT disk

systemvm/debian/etc/dnsmasq.conf.tmpl, systemvm/debian/opt/cloud/bin/cs/CsDhcp.py
=> VR: fix data-server if shared network has multiple ip ranges

server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
This PR fixes a small regression as can be seen in https://github.com/apache/cloudstack/pull/5201#issuecomment-933030293
It has been showing in lots of PRs lately
=> an inject annotation short

ui/src/views/compute/MigrateVMStorage.vue
Fixes jobid param when migrateVirtualMachine API is used for VM storage migration
=> ui: fix jobid param for migrate VM storage

usage/src/main/java/com/cloud/usage/UsageSanityChecker.java
This PR fixes an issue with usage sanity check.
=> usage: updateNewMaxId after sanity check

engine/schema/src/main/java/com/cloud/upgrade/SystemVmTemplateRegistration.java
This PR fixes build error after #5642 is merged.
=> engine/schema: fix build error in #5642

ui/src/config/section/compute.js
Enabled UI button for Dynamic scaling of VM which are on KVM. API support is already here https://github.com/apache/cloudstack/pull/4878
There are few constraints with KVM support for dynamic scaling like it has to be custom compute offering and need to set maxmemory, but showing it in UI adds value. It fails with an appropriate error when fixed compute offering is used, so it is worth adding to UI. We can also disable the button in such cases but it may confuse users why it is disabled.
=> UI: show button for dynamic Scaling for VM in case of KVM hypervisor
