apache/cloudstack

- engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
- engine/orchestration/src/test/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestratorTest.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtGetUnmanagedInstancesCommandWrapper.java
- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
This PR fixes a regression caused by #8465 on advanced zones, import fails with:
````
2024-01-10 12:13:33,234 DEBUG [o.a.c.e.o.NetworkOrchestrator] (API-Job-Executor-3:ctx-991bbe9f job-128 ctx-f49517d4) (logid:d7b8e716) Allocating nic for vm 142272e8-9e2e-407b-9d7e-e9a03b81653c in network Network {"id": 204, "name": "Isolated", "uuid": "9679fac5-e3ac-4694-a57b-beb635340f39", "networkofferingid": 10} during import
2024-01-10 12:13:33,239 ERROR [o.a.c.v.UnmanagedVMsManagerImpl] (API-Job-Executor-3:ctx-991bbe9f job-128 ctx-f49517d4) (logid:d7b8e716) Failed to import NICs while importing vm: i-2-31-VM
com.cloud.exception.InsufficientVirtualNetworkCapacityException: Unable to acquire Guest IP  address for network Network {"id": 204, "name": "Isolated", "uuid": …
```
> Fixes for KVM unmanaged instances import on advanced network and VNC password

- engine/api/src/main/java/org/apache/cloudstack/engine/orchestration/service/VolumeOrchestrationService.java
- engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/VolumeOrchestrator.java
- server/src/main/java/org/apache/cloudstack/vm/UnmanagedVMsManagerImpl.java
This PR tries to deal with on of the leftovers from https://github.com/apache/cloudstack/pull/8465 as reported in https://github.com/apache/cloudstack/issues/8439
when root size is 0 it is set to 1 to allow for creation of a disk.
Also, fixes the issue reported in https://github.com/apache/cloudstack/pull/8488#issuecomment-1886966407
Refactors importDisk methods to not do repeated byte to GiB and GiB to byte conversions.
Manually tested:
**KVM with advanced zone VM import**: https://github.com/apache/cloudstack/pull/8500#issuecomment-1888852070
1. VM with 50MiB root disk
2. VM with 8GiB root disk and a 20 GiB data disk
**VMware with advanced zone VM import**: https://github.com/apache/cloudstack/pull/8500#issuecomment-1888888777
1. VM with 50MiB root disk
2. VM with 8GiB root disk and a …
> vm-import: kvm import and fix volume size when lesser than 1GiB

- engine/orchestration/src/main/java/com/cloud/agent/manager/AgentManagerImpl.java
- engine/storage/volume/src/main/java/org/apache/cloudstack/storage/datastore/provider/DefaultHostListener.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtReadyCommandWrapper.java
There are a lot of test failures due to `test_vm_life_cycle.py` in multiple PRs due to host not available for migration of VMs.
https://github.com/apache/cloudstack/pull/8438#issuecomment-1886990285
https://github.com/apache/cloudstack/pull/8433#issuecomment-1878406524
https://github.com/apache/cloudstack/pull/7344#issuecomment-1886811369
While debugging I noticed that the hosts get stuck in `Connecting` state because MS is waiting for a response of the `ReadyCommand` from the agent. Since we take a lock on connection and disconnection, restarting the agent doesn't work. To fix this, we have to restart the MS or wait for ~1 hour (default timeout).
On the agent side, it gets stuck waiting for a response from the Script execution.
To reproduce, run `smoke/test_vm_life_cycle.py` …
> Fix host stuck in connecting state

- api/src/main/java/com/cloud/storage/Volume.java
- engine/api/src/main/java/org/apache/cloudstack/engine/orchestration/service/NetworkOrchestrationService.java
- engine/api/src/main/java/org/apache/cloudstack/engine/subsystem/api/storage/VolumeInfo.java
- engine/api/src/main/java/org/apache/cloudstack/engine/subsystem/api/storage/VolumeService.java
- engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
- engine/storage/volume/src/main/java/org/apache/cloudstack/storage/volume/VolumeObject.java
- engine/storage/volume/src/main/java/org/apache/cloudstack/storage/volume/VolumeServiceImpl.java
- framework/jobs/src/main/java/org/apache/cloudstack/framework/jobs/impl/AsyncJobManagerImpl.java
- framework/jobs/src/test/java/org/apache/cloudstack/framework/jobs/impl/AsyncJobManagerImplTest.java
- server/src/test/java/com/cloud/vpc/MockNetworkManagerImpl.java
This PR fixes moves resources stuck in transition state during async job cleanup
Problem:
During maintenance of the management server, other servers in the cluster or the same server after a restart initiate async job cleanup. However, this process leaves resources in a transitional state. The only recovery option currently available is to make direct database changes.
Solution:
This PR introduces a resolution by changing  Volume, Virtual Machine, and Network resources from their transitional states. This adjustment enables the reattempt of failed operations without the need for manual database modifications.
Tested manually and with unit tests
> CleanUp Async Jobs after mgmt server maintenance

- plugins/network-elements/nsx/src/main/java/org/apache/cloudstack/service/NsxApiClient.java
> NSX: Add retry logic with sleep to delete segments

- agent/conf/agent.properties
- agent/src/main/java/com/cloud/agent/properties/AgentProperties.java
- engine/api/src/main/java/org/apache/cloudstack/engine/subsystem/api/storage/HypervisorHostListener.java
- engine/components-api/src/main/java/com/cloud/agent/AgentManager.java
- engine/orchestration/src/main/java/com/cloud/agent/manager/AgentManagerImpl.java
- engine/storage/volume/src/main/java/org/apache/cloudstack/storage/datastore/provider/DefaultHostListener.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtReadyCommandWrapper.java
- utils/src/main/java/com/cloud/utils/script/Script.java
This PR fixes bug introduced in #8502. Timeout for script execution was set to 60 ms instead of 60s which resulted in host not getting UEFI enabled. This is a blocker for 4.19 release.
We do this by introducing a new agent parameter `agent.script.timeout` (default - 60 seconds) to use as a timeout for the script checking host's UEFI status.
We also externalize the timeout for the ReadyCommand by introducing a new global setting `ready.command.wait` (default - 60 seconds).
For ModifyStoragePoolCommand, we don't externalize the timeout to avoid confusion for the user. Since, the required timeout can vary depending on the provider in use and we are only setting the wait for default host listener for now. Instead, we reuse the global `wait` setting by dividing it by `5` making the default …
> Externalise a few timeouts & fix timeout for hostSupportsUefi in libvirt ready command wrapper

- plugins/backup/veeam/src/main/java/org/apache/cloudstack/backup/VeeamBackupProvider.java
- plugins/backup/veeam/src/main/java/org/apache/cloudstack/backup/veeam/VeeamClient.java
- plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/guru/VMwareGuru.java
- plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageLayoutHelper.java
- plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageProcessor.java
- test/integration/smoke/test_backup_recovery_veeam.py
This PR fixes the issue below
- Volumes are left over on datastore when restore a volume from backup and attach to another VM (more information below )
- unable to detach volume when restore backup and attach to vm then detach the volume (more infomation below)
More information
- Steps to reproduce the issue that Volumes are left over on datastore when restore a volume from backup and attach to another VM
1. create a VM (A) with ROOT and DATA disk
2. assign to a backup offering
3. create backup
4. create another VM (B)
5. restore the DATA disk of VM A, and attach to VM B
6. When operation is done, check the datastore
Without this change, the ROOT image is not removed and left over on the datastore.
```
[root@ref-trl-5933-v-Mr8-wei-zhou-esxi2:/vmfs/volumes/5f60667d-18d828eb] ls -l …
```
> veeam: fix some issues with restoring volume from backup and attaching it to VM

- plugins/hypervisors/kvm/src/main/java/org/apache/cloudstack/utils/cryptsetup/CryptSetup.java
Currently, when starting the Agent, ACS checks if the `cryptsetup` command can be used by using the command's `help`; the output of the command is printed in the logs. However, this output is too verbose and can be confusing.
This PR addresses this issue by using the utility version to check the command, instead of `help`, which is much less verbose.
-  Before changes:
-  After changes:
I checked the logs before and after changes. As shown in the screenshots above, the logs became more intuitive.
> Change the check for the existence of `cryptsetup` command

- api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
- api/src/main/java/org/apache/cloudstack/api/command/user/network/ListNetworkProtocolsCmd.java
- api/src/main/java/org/apache/cloudstack/api/response/NetworkProtocolResponse.java
- api/src/test/java/org/apache/cloudstack/api/command/user/network/ListNetworkProtocolsCmdTest.java
- client/pom.xml
- pom.xml
- server/src/main/java/com/cloud/network/security/SecurityGroupManagerImpl.java
- server/src/main/java/com/cloud/network/vpc/NetworkACLServiceImpl.java
- server/src/main/java/com/cloud/server/ManagementServerImpl.java
- server/src/test/java/com/cloud/network/vpc/NetworkACLServiceImplTest.java
- ui/src/views/network/AclListRulesTab.vue
- ui/src/views/network/EgressRulesTab.vue
- ui/src/views/network/FirewallRules.vue
- ui/src/views/network/IngressEgressRuleConfigure.vue
- utils/src/main/java/com/cloud/utils/net/NetUtils.java
- utils/src/main/java/com/cloud/utils/net/NetworkProtocols.java
- utils/src/test/java/com/cloud/utils/net/NetUtilsTest.java
- utils/src/test/java/com/cloud/utils/net/NetworkProtocolsTest.java
This PR contains the following changes
- adds a new API to list network procotols and details/types/codes, etc
- get network protocols on UI and add dropdowns for procotol numbers and icmp types/codes
- validate icmp types/codes when add network ACL
- etc
> api/utils/ui: List protocol numbers and icmp types

- engine/schema/src/main/java/com/cloud/upgrade/DatabaseUpgradeChecker.java
- engine/schema/src/main/java/com/cloud/upgrade/dao/Upgrade41900to42000.java
- engine/schema/src/main/resources/META-INF/db/schema-41900to42000-cleanup.sql
- engine/schema/src/main/resources/META-INF/db/schema-41900to42000.sql
Adds an empty 4.19.0.0 to  4.20.0.0 upgrade path
> engine-schema: upgrade path 4.19.0.0 to 4.20.0.0

- engine/components-api/src/main/java/com/cloud/vm/VmWork.java
- engine/components-api/src/main/java/com/cloud/vm/VmWorkJobHandlerProxy.java
- engine/orchestration/src/main/java/com/cloud/vm/VmWorkReboot.java
- engine/orchestration/src/main/java/com/cloud/vm/VmWorkStart.java
- engine/orchestration/src/test/java/com/cloud/vm/VmWorkRebootTest.java
- engine/orchestration/src/test/java/com/cloud/vm/VmWorkStartTest.java
The VM's password & other details sent via VM Details Map during VmWorkStart are logged as base64 encoded strings.
```
2024-01-22 11:22:53,879 DEBUG [c.c.v.VmWorkJobHandlerProxy] (Work-Job-Executor-4:ctx-8c25a1bb job-4690/job-4691 ctx-18a45cc5) (logid:76180ad6) Execute VM work job: com.cloud.vm.VmWorkStart{"dcId":1,"podId":1,"clusterId":1,"hostId":2,"rawParams":{"ConsiderLastHost":"rO0ABXQABHRydWU","VmPassword":"rO0ABXQADnNhdmVkX3Bhc3N3b3Jk"},"userId":2,"accountId":2,"vmId":415,"handlerName":"VirtualMachineManagerImpl"}
...
2024-01-22 11:22:59,456 DEBUG [c.c.v.VmWorkJobHandlerProxy] (Work-Job-Executor-4:ctx-8c25a1bb job-4690/job-4691 ctx-18a45cc5) (logid:76180ad6) Done executing VM work job: com.cloud.vm.VmWorkStart{"dcId":1,"podId":1,"clusterId":1,"hostId":2,"rawParams":{"ConsiderLastHost …
```
> Remove sensitive params (VmPassword, etc) from VMWork log

- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
- server/src/test/java/com/cloud/vm/UserVmManagerImplTest.java
restoreVirtualMachine resulted in two ROOT disks due to resource count increment error. Resource count increment is performed after ROOT volume is duplicated/allocated, and the failure here leaves VM with two ROOT volumes, and there is no cleanup of it after that.
This PR allocates new ROOT volume (on restore virtual machine operation) only when resource count increment succeeds.
Log:
```
2023-12-07 20:15:01,460 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (API-Job-Executor-18:ctx-6b2d5fb9 job-5403241 ctx-f3e2e390) (logid:4e54320f) Sync job-5403242 execution on object VmWorkJobQueue.525393
2023-12-07 20:15:02,198 INFO  [o.a.c.f.j.i.AsyncJobMonitor] (Work-Job-Executor-103:ctx-755903a6 job-5403241/job-5403242) (logid:3d510e9e) Add job-5403242 into job monitoring
2023-12-07 20:15:02,202 DEBUG …
```
> Allocate new ROOT volume (on restore virtual machine operation) only when resource count increment succeeds

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtConnection.java
This PR fixes the libvirt event processing to handle changes in Libvirt domains (and other events if registered).
There is some history around this. Initially it seems there was an event loop initialization added in an earlier [PR](https://github.com/apache/cloudstack/pull/7408) that supports live block copy. This introduced `Library.initEventLoop();` to `LibvirtConnection`, however it never polled for events, and this caused the keepalive issue warned about by libvirt doc [here](https://libvirt.org/html/libvirt-libvirt-event.html#virEventRegisterDefaultImpl):
```
For proper event handling, it is important that the event implementation is registered before a connection to the Hypervisor is opened.
Once registered, the application has to invoke …
```
> Fix libvirt domain event listener by properly processing events

- server/src/main/java/com/cloud/server/ConfigurationServerImpl.java
RSA has been considered as insecure and 'ssh-rsa' signature algorithm has been deprecated in OpenSSH.
> server: use ed25519 instead of rsa when generate public/private keys

- ui/src/views/network/AclListRulesTab.vue
> UI: fix icmp code/type of ACL rule are not display if the value is -1

- api/src/main/java/com/cloud/event/EventTypes.java
- server/src/main/java/com/cloud/storage/StorageManagerImpl.java
- ui/src/components/view/ListView.vue
This PR fixes the issue https://github.com/apache/cloudstack/issues/8441
- Access details of image store isn't visible 
- No events present for update to image store access status
> Image Store: View Access status of the image store and view events

- api/src/main/java/org/apache/cloudstack/api/command/admin/user/MoveUserCmd.java
The description of the API `moveUser` parameters does not match its functionalities. Furthermore, the description of the API itself does not clearly state the limitation of only moving users between accounts within the same domain.
This PR addresses this issue by changing those descriptions to align with the API functionality.
-  Before changes:
- After changes:
I tested by using CloudMonkey to list the command's description and its parameters.
> Fix API `moveUser` parameters descriptions

- plugins/storage/volume/storpool/README.md
- plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/datastore/util/StorPoolUtil.java
This PR provides another option to create StorPool primary storage with a valid URL in cases the old format is not accepted. The user will be able to use the old and new format
Old format `SP_API_HTTP=address:port;SP_AUTH_TOKEN=token;SP_TEMPLATE=template_name`
New format `storpool://{SP_AUTH_TOKEN}@{SP_API_HTTP}:{SP_API_HTTP_PORT}/{SP_TEMPLATE}`
Manual and smoke tests
> Option to create StorPool primary storage with a valid URL

- ui/src/config/section/offering.js
When listing disk offerings through the UI, IOPS and read/write data for these offerings is not presented, making it difficult to access information about them.
For this reason, `Disk Read Rate (IOPS)`, `Disk Write Rate (IOPS)`, `Disk Read Rate (BPS)`, `Disk Write Rate (BPS)` and `Max IOPS` data has been added to the disk offering details.
1. I created a disk offering with customized write and read rate values using the `hypervisor` QoS type in the creation form;
2. I created a disk offering with max IOPS using the `storage` QoS type in the creation form;
3. I accessed these disk offerings and verified that the `Disk Read Rate (IOPS)`, `Disk Write Rate (IOPS)`, `Disk Read Rate (BPS)`, `Disk Write Rate (BPS)` data were in the disk offering created in the step 1 and the `Max IOPS` data was …
> Add IOPS to disk offerings details

- packaging/centos7/cloud.spec
- packaging/centos8/cloud.spec
The cloudstack-ui package contains a copy of the webapp. However, the package (for both CentOS 7 and CentOS 8) have two issues:
1. Bad permissions on directories. The 'cloud' user cannot read and serve assets from subdirectories
2. WEB-INF/web.xml is missing. This breaks the API as the web routes are not defined.
Fixes #8558
Rebuilt the RPM packages under Rocky Linux 8 / CentOS 8 using Docker.
New cloudstack-ui packages now have the proper permissions:
```
54793 blocks         
total 524                                                                                                   
drwxr-xr-x 7 root root    181 Jan 25 18:00 .                                                                
drwxr-xr-x 4 root root     38 Jan 25 18:00 .. …
```
> Fix cloudstack-ui package: bad directory permissions and missing WEB-INF

- plugins/storage/volume/linstor/src/main/java/com/cloud/hypervisor/kvm/storage/LinstorStorageAdaptor.java
- plugins/storage/volume/linstor/src/main/java/org/apache/cloudstack/storage/datastore/util/LinstorUtil.java
If a Linstor node is down while migrating resource, allow-two-primaries
setting will fail because we can't reach the downed node. But it will
still set the property on the other nodes and migration should work.
We now just report an error instead of completely failing.
This PR also containes a cherry-picked commit from the main branch f176e7d122be0a9fa448dea547aa2d2e0e867352
Nested Linstor cluster with a non hyperconverged setup and a node evicted.
> Linstor fix migration while node offline

- plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/datastore/driver/StorPoolPrimaryDataStoreDriver.java
- plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/datastore/util/StorPoolUtil.java
- plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/snapshot/StorPoolVMSnapshotStrategy.java
- test/integration/plugins/storpool/TestTagsOnStorPool.py
- tools/marvin/marvin/lib/base.py
This PR removes the VolumeCare policy and the VM's UUID tags when a VM has attached data disks and during the destruction of the VM those volumes remain active
manual and smoke tests
> remove StorPool tags from detached volumes

- api/src/main/java/com/cloud/storage/Storage.java
- api/src/test/java/com/cloud/storage/StorageTest.java
ACS does not allow operators to set the configuration `storage.overprovisioning.factor` for `SharedMountPoint` primary storages, presenting the following message when one tries to change it:
Also, the global setting does not impact `SharedMoundPoint` primary storages, which means that the over-provisioning is not applied properly for this storage type. 
Furthermore, the metric presents that the `SharedMountPoint` has the global over-provisioning applied; however, in a scenario where the over-provision factor is 2, the allocation threshold is 80%, and the metrics show that storage has 40% allocated, one cannot allocate to it anymore.
This PR intends to enable over-provisioning for `SharedMountPoint` primary storages.
In an environment where the global over-provision factor was 1, the …
> Enable over provisioning for SharedMountPoint primary storages

- plugins/storage/volume/linstor/src/main/java/com/cloud/hypervisor/kvm/storage/LinstorStorageAdaptor.java
As described in issue #8310 some older distributions don't have hostname in /usr/bin so rely on PATH resolving
This PR Fixes: #8310 on 4.18 branch
local linstor cluster and was working before see changes in #6682
> linstor: use relative hostname path

- debian/cloudstack-management.install
- debian/rules
- packaging/centos7/cloud.spec
- packaging/centos8/cloud.spec
This bundles latest cmk release in cloudstack-management package, so admins won't need to install it for typical first-install use.
> packaging: bundle cmk in cloudstack-management package

- server/src/main/java/org/apache/cloudstack/backup/BackupManagerImpl.java
This PR reverts some changes in #7238
When restore backup of a VM and attach the volume to another VM, the original VM is not changed/touched, therefore the VM state should not be updated.
With this change, all the smoke tests for veeam (https://github.com/apache/cloudstack/blob/main/test/integration/smoke/test_backup_recovery_veeam.py) succeed.
> Veeam: revert unnecessary VM state change if restore backup and attach to another VM

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java
> kvm:  ITCO watchdog added

- server/src/main/java/com/cloud/network/router/VirtualNetworkApplianceManagerImpl.java
- server/src/main/java/com/cloud/network/router/VpcVirtualNetworkApplianceManagerImpl.java
- systemvm/debian/opt/cloud/bin/cs/CsAddress.py
- systemvm/debian/opt/cloud/bin/cs/CsDatabag.py
This PR fixes #8562 
If there are mutliple public subnets in a VR, there should be iptables rules like
```
-A POSTROUTING -o eth1 -j SNAT --to-source <Source NAT IP>
-A POSTROUTING -o eth3 -j SNAT --to-source <Source NAT IP>
-A POSTROUTING -o ethX -j SNAT --to-source <Source NAT IP>
```
in VR of isolated networks, these rules do exist.
Howver in VPC VR, only the first rule exists, the other rules are missing
> VR: fix issue between VPC VMs and other Public IPs in the same subnet as additional Public IPs

- ui/src/components/view/SearchView.vue
The GUI allows filtering volumes in several states; however, the `Migrating` state is not presented. For this reason, this PR adds the `Migrating` state to the volume filtering.
I called the `migrateVolume` API, accessed the volumes tab in the UI and using the `Migrating` state filter all volumes in the `Migrating` state were returned.
> UI: Add Migrating state in volume filtering

- plugins/storage/volume/linstor/src/main/java/com/cloud/hypervisor/kvm/storage/LinstorStorageAdaptor.java
- plugins/storage/volume/linstor/src/main/java/com/cloud/hypervisor/kvm/storage/LinstorStoragePool.java
- plugins/storage/volume/linstor/src/main/java/org/apache/cloudstack/storage/datastore/driver/LinstorPrimaryDataStoreDriverImpl.java
- plugins/storage/volume/linstor/src/main/java/org/apache/cloudstack/storage/datastore/provider/LinstorHostListener.java
- plugins/storage/volume/linstor/src/main/java/org/apache/cloudstack/storage/datastore/provider/LinstorPrimaryDatastoreProviderImpl.java
- plugins/storage/volume/linstor/src/main/java/org/apache/cloudstack/storage/datastore/util/LinstorUtil.java
This PR add HA support for Linstor primary storage.
It checks output of drbd event and drbd status output, to check if it has quorum or connections to other hosts,
which in turn reveals if this node is isolated or not.
Nested HA Linstor cluster with virtualBMC IPMI:
* Simulated node crash (kernel panic)
* Blocking of drbd incoming and outgoing connections
> Linstor: add HA support and small cleanups

- api/src/main/java/org/apache/cloudstack/cluster/ClusterDrsAlgorithm.java
- api/src/main/java/org/apache/cloudstack/cluster/ClusterDrsService.java
- api/src/test/java/org/apache/cloudstack/cluster/ClusterDrsAlgorithmTest.java
- plugins/drs/cluster/balanced/src/main/java/org/apache/cloudstack/cluster/Balanced.java
- plugins/drs/cluster/balanced/src/test/java/org/apache/cloudstack/cluster/BalancedTest.java
- plugins/drs/cluster/condensed/src/main/java/org/apache/cloudstack/cluster/Condensed.java
- plugins/drs/cluster/condensed/src/test/java/org/apache/cloudstack/cluster/CondensedTest.java
- plugins/metrics/src/main/java/org/apache/cloudstack/metrics/MetricsServiceImpl.java
- plugins/metrics/src/main/java/org/apache/cloudstack/response/ClusterMetricsResponse.java
- server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
- server/src/main/java/org/apache/cloudstack/cluster/ClusterDrsServiceImpl.java
- server/src/test/java/org/apache/cloudstack/cluster/ClusterDrsServiceImplTest.java
- ui/public/locales/en.json
- ui/src/components/view/ListView.vue
- ui/src/config/section/infra/clusters.js
- ui/src/views/infra/ClusterDRSTab.vue
Doc PR: https://github.com/apache/cloudstack-documentation/pull/374
This PR addresses two issues:
1. Allow DRS to work as expected in clusters with hosts of different capacities - We do this by using ratio of free/total metric. This is controlled using a new setting `drs.metric.use.ratio`.
2. Imbalance can be greater than 1. For condensed algorithm, migrations don't take place when this happens. - This happens when the distribution of metrics is skewed. We fix this by filtering out values where ratio is less than `drs.imbalance.condensed.skip.threshold` if `drs.metric.type` is `free` and greater than `drs.imbalance.condensed.skip.threshold` if `drs.metric.type` is `used` to remove the skew and check if we need drs or not.
> Add advance settings to fine tune DRS imbalance calculation

- server/src/main/java/com/cloud/network/vpc/NetworkACLServiceImpl.java
- server/src/test/java/com/cloud/network/vpc/NetworkACLServiceImplTest.java
An ICMP ACL rule should not be able to have code and type null. This PR fixes an edge case, that can be reproduced by:
- Creating a VPC and an ACL.
- Creating a TCP rule.
- Calling the API with `updateNetworkACLItem` and parameters `protocol=icmp`, `partialupgrade=false`, `cidrlist=""` and `traffictype=ingress`.
It will then set the rule with null ICMP code and type and the VR will face problems. 
This PR just extends the validation made when `partialupgrade` is false.
By following the steps mentioned in the description:
- With `protocol=icmp`, code and type became -1.
- With `protocol=tcp` and `protocol=all`, the rule was changed and the attributes were reset accordingly.
> Fix ICMP ACL rule edge case

- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
- server/src/test/java/com/cloud/vm/UserVmManagerImplTest.java
The API  `scaleVirtualMachine`  requires the specification of both vCPU quantity and memory amount, resulting in an error if either was omitted. This means that if an operator wants to increase the quantity of vCPUs while maintaining the existing memory, they were obligate to provide the current memory value as well.
An alteration has been introduced to the API to allow operators to input only the parameters they intend to modify while retaining the current values for the rest.
I applied the changes in a local lab and verified that if I used the API while inputting only one of the parameters, the scale was successful, and the  others kept the current value.
> Allow altering only either CPU or memory during VM live scale

- test/integration/smoke/test_metrics_api.py
This PR fixes the smoke test failure with `test_list_volumes_metrics_history` on xcpng 81/82
According to below code snippet, it is not supported yet
https://github.com/apache/cloudstack/blob/main/plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/wrapper/xenbase/CitrixGetVmDiskStatsCommandWrapper.java
> test: skip check for volume stats history on xenserver

- api/src/main/java/com/cloud/server/ManagementService.java
- api/src/main/java/org/apache/cloudstack/api/command/admin/storage/FindStoragePoolsForMigrationCmd.java
- engine/api/src/main/java/org/apache/cloudstack/engine/subsystem/api/storage/StoragePoolAllocator.java
- engine/schema/src/main/java/org/apache/cloudstack/storage/datastore/db/PrimaryDataStoreDao.java
- engine/schema/src/main/java/org/apache/cloudstack/storage/datastore/db/PrimaryDataStoreDaoImpl.java
- engine/storage/src/main/java/org/apache/cloudstack/storage/allocator/AbstractStoragePoolAllocator.java
- engine/storage/src/main/java/org/apache/cloudstack/storage/allocator/ClusterScopeStoragePoolAllocator.java
- engine/storage/src/main/java/org/apache/cloudstack/storage/allocator/GarbageCollectingStoragePoolAllocator.java
- engine/storage/src/main/java/org/apache/cloudstack/storage/allocator/LocalStoragePoolAllocator.java
- engine/storage/src/main/java/org/apache/cloudstack/storage/allocator/ZoneWideStoragePoolAllocator.java
- engine/storage/src/test/java/org/apache/cloudstack/storage/allocator/AbstractStoragePoolAllocatorTest.java
- plugins/storage-allocators/random/src/main/java/org/apache/cloudstack/storage/allocator/RandomStoragePoolAllocator.java
- server/src/main/java/com/cloud/server/ManagementServerImpl.java
When utilizing the `findStoragePoolsForMigration` API, ACS disregards the specified parameters `keyword`, `page`, and `pagesize`, returning all compatible storages for the volume. This issue also affected the UI, causing every available result to be shown during a migration, regardless of the filters or pagination applied.
To address this, modifications were implemented in the API to ensure the provided parameters are respected, guaranteeing that only the appropriate results are exhibited.
<details><summary>UI before</summary>
</details>
<details><summary>UI after</summary>
</details>
I tried migrating volumes both through the API and the UI and both worked accordingly.
> Fix filter and pagination on API findStoragePoolsForMigration

- server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
- server/src/test/java/com/cloud/configuration/ConfigurationManagerImplTest.java
This PR intends to refactor the `updateDiskOffering` API due to its size. 
This method was separated into others in order to improve the readability of the disk offering update process.
I called the `updateDiskOffering` API and it is working as it did before the refactoring. I also created some unit tests to maintain the current behavior and avoid regressions in the future.
> Refactor updateDiskOffering API

- server/src/main/java/com/cloud/network/router/VirtualNetworkApplianceManagerImpl.java
- server/src/main/java/com/cloud/network/router/VpcVirtualNetworkApplianceManagerImpl.java
This PR moves an expensive getRouterHealthChecksConfig() upper the execution stack during VPC restart. So this way it is only executed once instead of tens or hundreds times (depending on VPC tiers amount). 
This is done by introducing a `Map<String, String> routerHealthCheckConfig` argument to createMonitorServiceCommand() method that accepts pre-computed health check config.
Fixes #8055
1. Prepared a test VPC: 
- 10 tiers
- redundant offering (2 VRs)
- each tier has 1 running VM in it. 
2. Performed VPC restart with clean up. Took 61 minutes to fully restart in my case
3. Applied these changes
4. Performed VPC restart with clean up. Took 9 minutes to fully restart.
> vpc: optimize createMonitorServiceCommand() execution

- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
- server/src/test/java/com/cloud/vm/UserVmManagerImplTest.java
This PR renames some `UserVmManagerImpl`'s methods and improve their javadocs to make them more intuitive.
> Improve some UserVmManagerImpl's methods name and docs

- server/src/main/java/com/cloud/network/router/VirtualNetworkApplianceManagerImpl.java
This PR optimizes the query in getRouterHealthChecksConfig by moving the state filter from for loop to the query itself.
Possibly related issues: #8055 , #8201
> Fixup: Optimize getRouterHealthChecksConfig method

- scripts/storage/secondary/swift
- scripts/vm/hypervisor/xenserver/swift
- server/src/main/java/com/cloud/network/NetworkServiceImpl.java
- systemvm/debian/etc/vpcdnsmasq.conf
- test/integration/component/test_deploy_vm_userdata_multi_nic.py
- test/integration/smoke/test_migration.py
- test/metadata/func/loadbalancers.xml
- tools/marvin/marvin/lib/base.py
This PR fixes spelling in the comments section of the code only.
A small PR perhaps we can merge in more quickly.
Really just a clean up.
> docs: fix spelling in code comments

- plugins/integrations/kubernetes-service/src/main/resources/script/deploy-cloudstack-secret
This PR fixes the typos in deploy-cloudstack-secret script.
> CKS: fix /opt/bin/deploy-cloudstack-secret in CKS control nodes

- engine/schema/src/main/resources/META-INF/db/views/cloud.domain_view.sql
Fixes cloud.domain_view.sql added in #8647
View source is taken from `schema-41520to41600.sql`
> engine-schema: fix wrong cloud.domain_view

- services/console-proxy/server/src/main/java/com/cloud/consoleproxy/ConsoleProxyNoVncClient.java
> console proxy client sleep more generic

- api/src/main/java/org/apache/cloudstack/api/command/admin/user/DeleteUserCmd.java
- server/src/main/java/com/cloud/user/AccountManagerImpl.java
- server/src/test/java/com/cloud/user/AccountManagerImplTest.java
Currently, ACS allows users to delete themselves by calling the `deleteUser` API via CLI. Fixing this behavior has been previously suggested in this [comment](https://github.com/apache/cloudstack/pull/7242#issuecomment-1433260909), as it leaves room for errors if users don't pay enough attention (e.g., when using the console's autocomplete feature), since the parameter passed is the user's `UUID` and it's not easily identifiable to whom this `UUID` belongs. Furthermore, there's already a feature to prevent a user from deleting themselves via the UI; however, slower environments create a small window where it's possible for the user to click the button before it's disabled, allowing deletion even through the UI (see this [comment](https://github.com/apache/cloudstack/pull/7242#issuecomment- …
> Fix `deleteUser` API to prevent deletion of the caller

- ui/src/config/section/infra/phynetworks.js
- ui/src/views/infra/network/IpRangesTabPublic.vue
This PR fixes #8080 by allowing user to list down public IPs by physical network or per vlanid.
Adds "View Public IP Addresses" button for physical network
Adds "View Public IP Addresses" button for vlan IP ranges
> UI: Add button to show public IPs associated with vlanid

- ui/public/locales/en.json
This PR changes the error message in zone wizard as mentioned here: https://github.com/apache/cloudstack/pull/8625#issuecomment-1955115729
> UI: Fix error message in zone wizard

- server/src/main/java/com/cloud/server/StatsCollector.java
This PR syncs the pool stats in DB with the actual stats from stats collector if there are any discrepancies with in-memory or DB stats - both  capacity (`disksizetotal`) and used (`disksizeused`) bytes.
Checked the pool stats after updating capacitybytes for the pool - DB sync-ed with the actual capacitybytes from stats collector.
> Sync the storage pool stats in DB with the actual stats from stats collector

- engine/orchestration/src/test/java/com/cloud/vm/VirtualMachineManagerImplTest.java
- engine/schema/src/main/java/org/apache/cloudstack/reservation/dao/ReservationDaoImpl.java
- server/src/test/java/com/cloud/api/query/QueryManagerImplTest.java
The SearchBuilder listDomainAndTypeAndNoTagSearch in [ReservationDaoImpl.java](https://github.com/apache/cloudstack/pull/8725/files#diff-05b28ef8ea684a62e68734298af706bfb34eb8924e004ae5c7150315b569f944) is wrongly created by adding ACCOUNT_ID as part of the search param. Instead it should be DOMAIN_ID.
Additional fixes in test cases to:
- add assert
- add spacing
> engine-schema,test: fix domain reservation searchbuilder, test fixes

- server/src/main/java/com/cloud/server/ConfigurationServerImpl.java
This PR replaces ed25519 with ecdsa.
PR #8549 replaced RSA with ed25519. Unfornately, ed25519 keys is unsupported in FIPS mode
```
$  ssh-keygen -t ed25519 -m PEM -N '' -f key1
ED25519 keys are not allowed in FIPS mode
$  ssh-keygen -t ecdsa -m PEM -N '' -f key1
Generating public/private ecdsa key pair.
Your identification has been saved in key1
Your public key has been saved in key1.pub
The key fingerprint is:
.........
```
> server: use ecdsa instead of ed25519 when generate public/private keys

- api/src/main/java/com/cloud/event/EventTypes.java
- api/src/main/java/org/apache/cloudstack/api/ApiCommandResourceType.java
- api/src/main/java/org/apache/cloudstack/quota/QuotaTariff.java
- framework/db/src/main/java/com/cloud/utils/db/GenericDaoBase.java
- framework/quota/src/main/java/org/apache/cloudstack/quota/dao/QuotaTariffDaoImpl.java
- framework/quota/src/main/java/org/apache/cloudstack/quota/vo/QuotaTariffVO.java
- plugins/database/quota/src/main/java/org/apache/cloudstack/api/command/QuotaTariffCreateCmd.java
- plugins/database/quota/src/main/java/org/apache/cloudstack/api/command/QuotaTariffDeleteCmd.java
- plugins/database/quota/src/main/java/org/apache/cloudstack/api/command/QuotaTariffUpdateCmd.java
- plugins/database/quota/src/main/java/org/apache/cloudstack/api/response/QuotaResponseBuilderImpl.java
- ui/src/components/view/SearchView.vue
- ui/src/components/widgets/ResourceLabel.vue
- ui/src/utils/plugins.js
While creating, updating or removing a quota tariff there are no events for any of these actions.
To address that, every time a quota tariff is created, updated or removed, a new event is created containing some details of these operations.
I created, updated and removed a quota tariff. Then I accessed the `Events` tab and all the operations were there.
> Quota tariff events

- engine/schema/src/main/java/com/cloud/upgrade/DatabaseUpgradeChecker.java
- engine/schema/src/main/java/com/cloud/upgrade/dao/Upgrade41900to41910.java
- engine/schema/src/main/resources/META-INF/db/schema-41900to41910-cleanup.sql
- engine/schema/src/main/resources/META-INF/db/schema-41900to41910.sql
The PR #7152 changed the unit of the Quota types `VM_DISK_IO_READ`, `VM_DISK_IO_WRITE`, `VM_DISK_BYTES_READ` and `VM_DISK_BYTES_WRITE`. However, the pre-populated tariffs were not considered, and their unit type is still with the old value. The unit was only displayed incorrectly, as the calculation utilizes the correct unit. Their unit types were updated to the correct ones.
<details><summary>Update script</summary>
```log
2024-02-05 14:42:03,890 INFO  [c.c.u.DatabaseUpgradeChecker] (main:null) (logid:) DB version = 4.19.0.0 Code Version = 4.19.1.0
2024-02-05 14:42:03,894 INFO  [c.c.u.DatabaseUpgradeChecker] (main:null) (logid:) Database upgrade must be performed from 4.19.0.0 to 4.19.1.0
2024-02-05 14:42:03,949 DEBUG [c.c.u.DatabaseUpgradeChecker] (main:null) (logid:) Running upgrade …
```
> [Quota] Update pre-populated Quota tariffs' type

- plugins/storage/volume/linstor/src/main/java/org/apache/cloudstack/storage/datastore/driver/LinstorPrimaryDataStoreDriverImpl.java
- plugins/storage/volume/linstor/src/main/java/org/apache/cloudstack/storage/datastore/util/LinstorUtil.java
This PR fixes template copy and other operations while there are nodes in the cluster under maintenance or disabled.
It was simply forgotten to check the host state is not in any none enabled state.
Additionally delete the created resource definition from Linstor if something went wrong copying.
Linstor cluster, copying a new template into primary storage and also do volume snapshots (with maintenance hosts)
> Linstor 4.19 fix selecting non enabled hosts

- ui/src/views/compute/DeployVM.vue
- ui/src/views/compute/wizard/DiskOfferingSelection.vue
This PR fixes four issues related to the disk offering override in the VM deployment wizard:
1. When a user selects a compute offering associated to a disk offering, enables root disk offering override and selects an offer other than the default one, the UI freezes. This only happens when the UI is not running locally;
2. When a user enables root disk offering override and selects an offer by clicking inside its radio button, the radio button becomes checked, but the selected root disk offering is not updated and the VM gets deployed with the default offering;
3. When a user enables root disk offering override, selects an offer, disables the override and deploys a VM, the root disk offering still gets overridden and the VM is deployed with the selected offer;
4. When a user deploys a VM …
> Fix disk offering override in VM deployment wizard

- server/src/main/java/org/apache/cloudstack/vm/UnmanagedVMsManagerImpl.java
This PR addresses an issue during VM import on VMFS storage, storage pool cannot be found during import operation and it fails:
````
2024-03-08 00:49:57,086 DEBUG [c.c.s.d.GuestOSHypervisorDaoImpl] (API-Job-Executor-1:ctx-8d3d66e6 job-37 ctx-2c2f3dfe) (logid:0dfa2610) Mapping for guest OS ID: windows2019srvNext_64Guest for hypervisor: VMware with version: 8.0.0.2 can not be found. Trying to find one for the parent version: 8.0
2024-03-08 00:49:57,099 DEBUG [o.a.c.v.UnmanagedVMsManagerImpl] (API-Job-Executor-1:ctx-8d3d66e6 job-37 ctx-2c2f3dfe) (logid:0dfa2610) Trying to import VM [{"name":"Mig01","internalCSName":"Mig01","powerState":"PowerOn","cpuCores":8,"cpuCoresPerSocket":8,"memory":32768,"cpuSpeed":0,"operatingSystemId":"windows2019srvNext_64Guest","operatingSystem":"Microsoft Windows …
```
> VM Import: Use datastore name when datastore path is not set to search for pools on DB

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStoragePool.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDefTest.java
This PR allows a given KVM storage implementation to decide if it wants to override the Libvirt disk XML's physical/logical IO size.  For now all in-tree implementations will default to not using this.
In the future it may also be possible to extend the disk offerings to provide more granular control.
Note that using a *logical* sector size other than 512 would require the image to be built to support it, so this may be better suited as a property of the image at some point. Physical sector size can be changed as desired. This at least puts the XML definitions in place as a start.
Tested locally by modifying an in-tree plugin, but didn't commit that change to avoid changing upstream behavior.
Also added unit test to test XML generation.
> Support KVM storage implementations controlling logical/physical block io size

- server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
When removing tags from a network offering, whether through the UI or API, they are currently defined as an empty string (`""`) instead of being definitively deleted.
This PR addresses this issue by enabling the complete removal of network offering tags.
Through CloudMonkey:
I removed a network offering's tag using the `updateNetworkOffering` API. Then, I verified that the `tags` field, which previously held an empty string (`""`), had completely disappeared.
```bash
> updateNetworkOffering id=bdf5fb44-916d-4ba8-971f-f52d76ab3bc5 tags=
{
"networkoffering": {
"availability": "Optional",
"conservemode": true,
"created": "2024-02-19T16:58:53+0000",
"details": {
"internetProtocol": "IPv4"
},
"displaytext": "description",
"egressdefaultpolicy": true,
"fortungsten": false,
"forvpc": false, …
```
> Fix the removal of network offering tags

- server/src/main/java/com/cloud/network/router/VirtualNetworkApplianceManager.java
This PR fixes the issue that the DNS is exposed publicly by default.
related to:
https://github.com/apache/cloudstack/commit/6a72e6e9f83145f20364c00e95c4d918f0de86e0
https://github.com/apache/cloudstack/pull/1663
> server: update default value of setting 'expose.dns.externally' to 'false"

- ui/src/views/dashboard/VerifyTwoFa.vue
Every time a user is redirected to the 2FA screen, the input lacks `autofocus` and the user has to click in the input before being able to type the authentication PIN.
This pull request addresses this issue by adding the `autofocus` whenever the user is redirected to the 2FA page.
By using a user with 2FA enabled, I made the following tests:
By opening the UI for the first time, I logged in. Then, I logged off and logged in again. After being redirected to the 2FA screen, I returned to the login screen and logged in again.
After each login, I was redirected to the 2FA screen and the `autofocus` worked as expected.
> Add autofocus to input in the 2FA screen

- ui/src/views/compute/AssignInstance.vue
In a project's view, after assigning an instance belonging to the project to a user account through the instance's page, the UI tries to refresh the information about the instance. However, as the project does not have permission to view instances from other accounts, the user is redirected to a 404.
This PR adds a check in the UI to avoid showing this 404.
In the root admin account, I made the following tests:
| Number | Test | Previous result | New result | Expected result? (Y/N) |
| - | - | - | - | - |
| 1 | In a project's view, I assigned an instance belonging to the project to a user account | UI gets redirected to a 404 | UI gets redirected to the instance listing | Y |
| 2 | In a project's view, I tried to assign an instance belonging to the project to the project itself | An error …
> Fix 404 when moving a VM to out of a project

- server/src/main/java/com/cloud/storage/snapshot/SnapshotSchedulerImpl.java
When management server starts, it starts the snapshot scheduler. In case there is a volume snapshot policy which exists for a volume which does not exist, it can cause SQL constraint issue and cause the management server to break from starting its various components and cause HTTP 503 error.
> snapshot: don't schedule next snapshot job for a removed volume

- systemvm/debian/opt/cloud/bin/setup/postinit.sh
> VPC VR: fix empty iptables if there is no vpc tier

- engine/schema/src/main/java/com/cloud/upgrade/DatabaseUpgradeChecker.java
- engine/schema/src/main/java/com/cloud/upgrade/dao/Upgrade41900to41910.java
Fixes #8775 
This PR adds index on `vm_id` column of `vm_stats` table.
> Add indexes for vm_stats

- plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/CitrixResourceBase.java
- plugins/hypervisors/xenserver/src/main/java/org/apache/cloudstack/hypervisor/xenserver/ExtraConfigurationUtility.java
This PR fixes a problem when trying to boot up a XenServer VM with a template through an ISO. 
- Enable `enable.additional.vm.configuration` and add `HVM-boot-params:order` to `allow.additional.vm.configuration.list.xen`.
- Create a XenServer VM with a template.
- Attach an ISO to it.
- Call `updateVirtualMachine` with parameter `extraconfig=HVM-boot-params:order%3Ddcn`
- Start up the VM.
It will not finish, with the following log message:
```
INFO  [c.c.h.x.r.XenServer650Resource] (DirectAgent-71:[ctx-6c7bfe3d]) (logid:faabbafa) Appending user extra configuration settings to VM
ERROR [o.a.c.h.x.ExtraConfigurationUtility] (DirectAgent-71:[ctx-6c7bfe3d]) (logid:faabbafa) Exception caught while setting VM configuration. exception: null
```
After fixing the exception …
> Fix XenServer nested extra configuration

- engine/schema/src/main/resources/META-INF/db/schema-41900to42000.sql
- plugins/hypervisors/ovm3/src/test/resources/scripts/create_pool_cluster.py
- server/src/main/java/com/cloud/api/ApiSessionListener.java
- server/src/main/java/com/cloud/network/vpc/NetworkACLManagerImpl.java
- server/src/main/java/com/cloud/resource/ResourceManagerImpl.java
- ui/README.md
- ui/docs/development.md
This PR fixes spelling in the docs only
> Fix spelling in docs and code comments only

- api/src/main/java/org/apache/cloudstack/api/response/UserDataResponse.java
- server/src/main/java/com/cloud/api/ApiResponseHelper.java
- ui/src/config/section/compute.js
- ui/src/views/AutogenView.vue
> api,server,ui: add project ID and name to UserDataResponse

- ui/src/components/view/StatsTab.vue
The Network metrics segment of the UI displays the amount of data downloaded/uploaded by a specific instance. However, when the instance is a system VM (VR, CPVM or SSVM), this segment is not shown.
This behaviour has been fixed, allowing network metrics for System VMs to be viewed via UI.
<details><summary>Before</summary>
Console Proxy:
Secondary Storage:
Virtual Router:
</details>
<details><summary>After</summary>
Console Proxy:
Secondary Storage:
Virtual Router:
</details>
> Show network metrics for System VMs

- agent/src/main/java/com/cloud/agent/Agent.java
- agent/src/main/java/com/cloud/agent/AgentShell.java
- agent/src/main/java/com/cloud/agent/dao/impl/PropertiesStorage.java
- agent/src/main/java/com/cloud/agent/mockvm/MockVmMgr.java
- agent/src/main/java/com/cloud/agent/properties/AgentPropertiesFileHandler.java
- agent/src/main/java/com/cloud/agent/resource/consoleproxy/ConsoleProxyResource.java
With the new version of Log4j there is some space for improving log readability using the new features. This PR refactors the logs from the cloud-agent module.
It was tested in a local lab:
- I have done some operations on cloudstack to induce the generation of the logs
- No problems or changes to the log output were found
> Refactor cloud-agent module logs for Log4j2

- utils/src/main/java/com/cloud/utils/script/OutputInterpreter.java
- utils/src/test/java/com/cloud/utils/ScriptTest.java
This PR enabled draining on the `AllLinesParser` so `Script.execute()` doesn't timeout if it has to read larger data.
Right now commands with larger output and `AllLinesParser` won't finish, because noone is emptying the stdout buffer
and the process will never exit until killed by the timeout "interrupt".
Tested with local `Script` executions and an added unittest.
> Linstor 4.19 fix script alllines

- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
This PR fixes a scenario in tagged limits checking. When user provides `overriderootdiskoffering` during `deployVirtualMachine`, the limits for this root disk aren't checked.
Can be reproduced in Simulator. Begin by setting up a new Simulator zone, ready to deploy VMs.
1. create a test domain and account
2. create an NFS storage pool with a tag, e.g. "fast"
3. enable `resource.limit.storage.tags` for "fast" storage
4. create a disk offering with custom size, and storage tag "fast"
5. set primary storage limit for test domain and storage tag "fast", e.g. 5 GiB limit
6. launch a VM, using override root disk offering pointing to the "fast" offering, and size that goes beyond user's "fast" limit.
Applied this patched and tried to reproduce the issue with different scenarios.
> Fix: check root disk offering tagged limits during VM deploy

- engine/schema/src/main/resources/META-INF/cloudstack/core/spring-engine-schema-core-common-daos-between-management-and-usage-context.xml
- engine/schema/src/main/resources/META-INF/cloudstack/core/spring-engine-schema-core-daos-context.xml
The Quota processing occurs on the Management Server (via API) and Usage Server (via task). It uses the class `PresetVariableHelper` to retrieve data from the database and inject it into the Quota tariff's activation rules. To retrieve the data, some DAOs are mapped as dependencies for the Usage Server and injected in that class. 
PR #8302 injected `org.apache.cloudstack.reservation.dao.ReservationDao` in `com.cloud.storage.dao.VolumeDao` (which is also injected in `PresetVariableHelper`); however, `org.apache.cloudstack.reservation.dao.ReservationDao` was not added as dependency for the Usage Server, causing errors to start the Usage Server: 
<details><summary>Logs</summary>
```
04:51:35,224  INFO Transaction:1030 - Is Data Base High Availiability enabled? Ans : false
04:51:35,224  INFO …
```
> Add ReservationDao as dependency for the Usage Server

- engine/schema/src/test/java/com/cloud/upgrade/DatabaseUpgradeCheckerTest.java
This PR adds three unit tests
- upgrade from 4.18.0.0 to a release which is NOT in the upgrade hierarchy
- upgrade to latest version from a release which is NOT in the upgrade hierarchy
- upgrade from a release to another release which are both NOT in the upgrade hierarchy
This is a followup of #7959
> upgrade: add unit tests from/to a security release

- server/src/main/java/com/cloud/network/router/VirtualNetworkApplianceManagerImpl.java
- server/src/main/java/com/cloud/network/router/VpcVirtualNetworkApplianceManagerImpl.java
This PR fixes #8745 
1. create vpc with 2 tiers
2. create lb in each vpc tier
3. check vpc vr, `/etc/haproxy/haproxy.cfg` contains the load balancer configuration of both 2 tiers.
4. restart vpc with cleanup. check the new vpc vr
* expected: `/etc/haproxy/haproxy.cfg` in new vpc vr should be same as before (step 3)
* actual without this PR: `/etc/haproxy/haproxy.cfg` in new vpc vr  contains the load balancer configuration for only 1 tier.
* with this PR: works as expected
> server: fix haproxy misconfiguration after VPC VR start

- api/src/main/java/com/cloud/vm/VirtualMachineProfile.java
- engine/components-api/src/main/java/com/cloud/vm/VirtualMachineProfileImpl.java
- server/src/main/java/org/apache/cloudstack/vm/UnmanagedVMsManagerImpl.java
- server/src/test/java/org/apache/cloudstack/vm/UnmanagedVMsManagerImplTest.java
> Fix VM import & VM delete with custom offering

- plugins/storage/volume/linstor/src/main/java/com/cloud/hypervisor/kvm/storage/LinstorStorageAdaptor.java
Excerpt PR from #8790, that only fixes Linstor adaptor pretending handling paths that don't belong to Linstor.
Manual with a Linstor cluster.
> linstor: Do not pretend handling disconnect paths that are non Linstor

- api/src/main/java/com/cloud/storage/VolumeApiService.java
- api/src/main/java/com/cloud/vm/UserVmService.java
- api/src/main/java/org/apache/cloudstack/api/command/user/vm/RestoreVMCmd.java
- engine/api/src/main/java/com/cloud/vm/VirtualMachineManager.java
- engine/api/src/main/java/org/apache/cloudstack/engine/orchestration/service/VolumeOrchestrationService.java
- engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
- engine/orchestration/src/main/java/com/cloud/vm/VmWorkRestore.java
- engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/CloudOrchestrator.java
- engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/VolumeOrchestrator.java
- server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
- server/src/main/java/org/apache/cloudstack/vm/UnmanagedVMsManagerImpl.java
- server/src/test/java/com/cloud/vm/UserVmManagerImplTest.java
- ui/src/config/section/compute.js
- ui/src/views/compute/ReinstallVm.vue
This PR allows overriding root diskoffering id & size, and expunge old root disk  while restoring VM. This is useful when you have to restore a VM with a new template but the newer template's size is smaller than the existing one.
New parameters for `restoreVirtualMachine`:
1. `diskofferingid` - Override root volume's diskoffering
2. `rootdisksize` - Override root volume's size (in GB)
3. `expunge` - Option to expunge old volumes after restore
4. `details` - Option to specify custom parameters for the selected disk offering
Tested Manually
> Allow overriding root disk offering & size, and expunge old root disk while restoring a VM

- framework/db/src/main/java/com/cloud/utils/db/GenericDaoBase.java
This PR fixes `listStoragePoolsMetricsCmd` when there are no search results.
To reproduce the error
```
cmk list storagepoolsmetrics keyword=zxcvbn
__ Error: (HTTP 530, error code 4250) DB Exception on: com.mysql.cj.jdbc.ClientPreparedStatement: SELECT cluster.id, cluster.name, cluster.guid, cluster.data_center_id, cluster.pod_id, cluster.hypervisor_type, cluster.cluster_type, cluster.allocation_state, cluster.managed_state, cluster.removed, cluster.uuid FROM cluster WHERE cluster.uuid IN )  AND cluster.removed IS NULL 
```
After applying the patch, error disappears.
> Fix listStoragePoolsMetricsCmd

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtMigrateCommandWrapper.java
When a migration error occurs on KVM, the message `Migration was refused connection to destination: <destination Uri>. Please check libvirt configuration compatibility and firewall rules on the source and destination hosts.` is presented to the user. This discloses infrastructure information which should not be available to the end user.
This message was substituted by a generic message, to avoid exposing infrastructure information. A new log was also added, containing the previous content of the message, in order to enable debugging.
> Limit infrastructure details revealed to the end user after a failed migration on KVM

- server/src/main/java/com/cloud/network/element/VirtualRouterElement.java
In a situation where there is a stopped user VM and this VM's network VR is also stopped, starting the user VM will also cause the VR to start. However, in this situation, the VR is inheriting the user VM's boot parameters, causing it to not start when the user VM has the UEFI boot type.
Because of this, the inheritance of user VM boot parameters has been removed from VR and other boot parameters have been defined in their place.
Fixes: #8734
I followed the same steps from `How did you try to break this feature and the system with this change?` and verified that the user's VM and VR started correctly.
1. Using VMware, I created an isolated network (`isolated`);
2. I deployed a VM (`test`) using the `isolated` network and started it;
3. After implementing the `isolated` network, I stopped …
> Fix VR inheriting boot settings from user's VM

- ui/src/components/view/DetailsTab.vue
- ui/src/components/view/InfoCard.vue
In the backup details page, the properties `Size` and `Virtual Size` are being displayed in bytes, and the property `Disk size (in GB)` is being displayed in kilobytes.
This PR converts these values into a more readable format, so that they match the displayed units. Thus, a pop-up has been added to each one of the properties to display their values in bytes.
<details>
<summary>
Before the changes
</summary>
</details>
<details>
<summary>
After the changes with closed pop-ups
</summary>
</details>
<details>
<summary>
After the changes with opened pop-ups
</summary>
</details>
1. I created a VM backup with a `DummyBackupProvider`.
2. I accessed the backup details page and verified that the properties values were converted correctly.
> Fix display of properties related to backup size

- engine/schema/src/main/java/com/cloud/configuration/dao/ResourceCountDao.java
- engine/schema/src/main/java/com/cloud/configuration/dao/ResourceCountDaoImpl.java
- engine/schema/src/main/java/org/apache/cloudstack/reservation/dao/ReservationDao.java
- engine/schema/src/main/java/org/apache/cloudstack/reservation/dao/ReservationDaoImpl.java
- server/src/main/java/com/cloud/resourcelimit/ResourceLimitManagerImpl.java
This PR fixes the issues which occur when increment/decrement methods are waiting for a lock on domain tables and `ResourceCountCheckTask` is running at the same time. This issue appears when innodb_lock_wait_timeout is many times less than the time it takes for `recalculateDomainResourceCount` to complete. (Check steps below on how to reproduce the error).
```java
com.cloud.utils.exception.CloudRuntimeException: DB Exception on: com.mysql.cj.jdbc.ClientPreparedStatement: SELECT resource_count.id, resource_count.type, resource_count.account_i
d, resource_count.domain_id, resource_count.count, resource_count.tag FROM resource_count WHERE resource_count.id IN (33,4785,3513,4845)  FOR UPDATE 
at com.cloud.utils.db.GenericDaoBase.searchIncludingRemoved(GenericDaoBase.java:438)
at …
```
> Speedup resource count calculation

- api/src/main/java/com/cloud/user/ResourceLimitService.java
- framework/config/src/main/java/org/apache/cloudstack/framework/config/ConfigKeyScheduledExecutionWrapper.java
- framework/config/src/test/java/org/apache/cloudstack/framework/config/ConfigKeyScheduledExecutionWrapperTest.java
- server/src/main/java/com/cloud/resourcelimit/ResourceLimitManagerImpl.java
This PR adds the ability for a Scheduled execution timing to be adjusted dynamically. Normally, adjusting the interval that these run requires a restart of the management services, which can be problematic for experimenting with intervals or just making adjustments without downtime.
Introduces `ConfigKeyScheduledExecutionWrapper` that can read a `Long` from a `ConfigKey` and dynamically adjust execution interval. The current implementation only supports emulating the behavior of `scheduleAtFixedRate` - meaning if the first run is at `N`, the next is at `N + configKey.value()`, ignoring the run time of the task itself. If the task takes longer than `configKey.value()`, the next run occurs immediately.
This PR also converts `ResourceCountCheckTask` to run on dynamic interval.
Unit tests and …
> Introduce scheduled executor wrapper with dynamic interval

- server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
This PR fixes the error message shown when the `checkVolume` command fails.
Before:
```json
{
"accountid": "f7a7493c-ecd7-11ee-a883-1e00a700045b",
"cmd": "org.apache.cloudstack.api.command.user.volume.CheckAndRepairVolumeCmd",
"completed": "2024-03-28T10:34:49+0000",
"created": "2024-03-28T10:34:47+0000",
"jobid": "6f452658-b61d-4983-9528-87fd4b2f9f29",
"jobinstanceid": "2090adf0-5889-4299-95ea-e104074d9e9a",
"jobinstancetype": "Volume",
"jobresult": {
"errorcode": 530,
"errortext": "Unexpected exception"
},
"jobresultcode": 530,
"jobresulttype": "object",
"jobstatus": 2,
"userid": "f7a84e5a-ecd7-11ee-a883-1e00a700045b"
}
```
After:
```json
{
"accountid": "f7a7493c-ecd7-11ee-a883-1e00a700045b",
"cmd": "org.apache.cloudstack.api.command.user.volume.CheckAndRepairVolumeCm …
```
> Fix error message for checkVolume command

- usage/src/main/java/com/cloud/usage/UsageManagerImpl.java
This PR...
Fixes: #8590
by adding a shutdown hook that removes the last planned usage job on exit, if owned by the current process.
- start the usage server
- see the job record being created for the running process
- stop the server
- check that the record is no longer in the DB
> Add a shutdownhook to remove jobs owned by the process

- ui/src/components/widgets/Status.vue
This PR fixes #8783. Status widget changes the tooltip message based on the url. To fix this, before returning the tooltip message, we check if there is no string available in locale and set the message to state.
> UI: Fix missing locale strings for Status widget

- usage/src/main/java/com/cloud/usage/UsageManagerImpl.java
> merge forward error in logger name

- server/src/test/java/com/cloud/event/ActionEventInterceptorTest.java
This fixes test failures in some PRs against main/4.20 branch
```
Error:  Failures:
Error:    ActionEventInterceptorTest.testInterceptComplete:247
Error:    ActionEventInterceptorTest.testInterceptException:261
Error:    ActionEventInterceptorTest.testInterceptStartAsync:234 expected:<Starting VM[.  Id: 0 Name: null]> but was:<Starting VM[]>
```
This PR...
> test: fix test failures in ActionEventInterceptorTest

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java
This fixes a limitation for arm64/aarch64 KVM hosts to correctly export the product name via sysconfig attribute. Without this `cloud-init` doesn't function correctly on arm64 platforms.
Tested this on a ARM64 KVM host, before the fix cloud-init enabled template didn't work and I was not able to ssh into the instances; with this fix I was able to ssh into cloud-init enabled templates such as https://cloud-images.ubuntu.com/releases/22.04/release/ubuntu-22.04-server-cloudimg-arm64.img
> kvm: export sysinfo for arm64 domains for cloud-init to work

- plugins/storage/volume/linstor/src/main/java/com/cloud/hypervisor/kvm/storage/LinstorStorageAdaptor.java
- plugins/storage/volume/linstor/src/main/java/org/apache/cloudstack/storage/datastore/util/LinstorUtil.java
For live migrate we need the allow-two-primaries option,
but we don't know exactly if we are called for a migration operation.
Now also check if at least any of the resources is in use somewhere and
only then set the option.
Also applies to 4.19
Fresh linstor test cluster. Creating systemvms, templates and live migrating VM's
> linstor: Only set allow-two-primaries if resource is already in use

- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
This PR fixes null pointer exception in restore VM.
```
2024-04-16T17:32:47,596 ERROR [c.c.a.ApiAsyncJobDispatcher] (API-Job-Executor-50:[ctx-969d6ccf, job-1648]) (logid:4eaa9a49) Unexpected exception while executing org.apache.cloudstack.api.command.user.vm.RestoreVMCmd java.lang.NullPointerE
xception
at com.cloud.vm.UserVmManagerImpl.restoreVM(UserVmManagerImpl.java:7855)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflect …
```
> Fix null pointer exception in restore VM

- ui/src/components/view/DetailSettings.vue
VMs and templates settings can only be manipulated through UI if the user's account role has permission to `updateVirtualMachine` and `updateTemplate` APIs. If the role does not have permission to both APIs simultaneously the interface blocks the manipulation of VMs and templates settings.
This PR addresses this issue by making those APIs permissions independent from each other.
I've manipulated `updateVirtualMachine` and `updateTemplate` APIs permissions and I've gathered the following results:
| Test number | `updateVirtualMachine` | `updateTemplate` | Can manipulate VM settings? (Y/N) | Can manipulate template settings? (Y/N) | Expected results? (Y/N) | 
| :---: | :---: | :---: | :---: | :---: | :---: |
| 1 | `Allow` | `Allow` | Y | Y | Y |
| 2 | `Allow` | `Deny`  | Y | N | Y |
| 3 | …
> Fix permission to manipulate VMs and templates settings through UI

- server/src/main/java/com/cloud/template/HypervisorTemplateAdapter.java
- server/src/test/java/com/cloud/template/HypervisorTemplateAdapterTest.java
> server: fix duplicated records for templates if there are multiple zones

- services/secondary-storage/server/src/main/java/org/apache/cloudstack/storage/resource/NfsSecondaryStorageResource.java
> log sanitation on output of jobs

- server/src/main/java/com/cloud/network/NetworkModelImpl.java
- server/src/test/java/com/cloud/network/NetworkModelImplTest.java
This PR fixes #8598 
with this change
```
root@r-575-VM:~# cat /etc/dnsmasq.d/cloud.conf
dhcp-hostsfile=/etc/dhcphosts.txt
listen-address=127.0.0.1,172.17.1.1,172.17.2.1,172.17.3.1
dhcp-range=set:interface-eth2-0,172.17.1.1,static
dhcp-option=tag:interface-eth2-0,15,cs2cloud.internal
dhcp-option=tag:interface-eth2-0,6,172.17.1.1,10.0.32.1,8.8.8.8
dhcp-option=tag:interface-eth2-0,3,172.17.1.1
dhcp-option=eth2,26,1500
dhcp-option=tag:interface-eth2-0,1,255.255.255.0
dhcp-range=set:interface-eth3-1,172.17.2.1,static
dhcp-option=tag:interface-eth3-1,15,cs2cloud.internal
dhcp-option=tag:interface-eth3-1,6,172.17.2.1,8.8.8.8,1.1.1.1
dhcp-option=tag:interface-eth3-1,3,172.17.2.1
dhcp-option=eth3,26,1500
dhcp-option=tag:interface-eth3-1,1,255.255.255.0 …
```
> vpc: create vpc tiers with dns server of vpc instead of zone

- api/src/main/java/com/cloud/vm/VmDetailConstants.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtDomainXMLParser.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtCpuTopologyTest.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtDomainXMLParserTest.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDefTest.java
- server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
This PR adds a second config option for VM CPU topology and implements it for KVM. This can be useful when there is out of band pinning at the hypervisor host and the admin wants to ensure the guest view of L1/2/3 cache among cores matches the physical host.
Eventually it may be nice extend this to the front end and make it available via service offerings, for now it is only available as VM detail.
Added and updated several unit tests, I found it difficult to implement the threads setting with the existing implementation of `cpu.corespersocket` so the logic is reworked quite a bit.  Also maintains the default topology grouping of 4 or 6 cores per socket when none is provided.  It will ignore custom topology if the result doesn't make sense (e.g. service offering's core count doesn't …
> Add ability to set cpu.threadspercore similar to existing cpu.corespersocket

- engine/schema/src/main/java/com/cloud/upgrade/SystemVmTemplateRegistration.java
This PR should fix #8388 
The fix ensures that when you have at least one Zone with a specific hypervisor type (e.g. KVM), then when adding a new Zone with the same hypervisor type, even if the systemVM template for that hypervisor (when registered in the original Zone) is not marked as cross_zone=1 (in vm_template table) - i.e. when it's not marked for "ALL ZONES" - CloudStack will created the record in the template_zone_ref table, and the rest of the work will be done by the automatic systemVM template installation script (that runs when a first Secondary Storage is added inside a new Zone)
> systemvm: add template_zone_ref record when add a new zone with same hypervisor type

- ui/src/views/compute/InstanceTab.vue
In any instance's page, the volumes tab always gets shown, even if the account does not have permission to list the instance's volumes.
This PR adds a check in the UI in order to hide the volumes tab if the current account does not have permission to use the `listVolumes` API.
Before, a user without permission could access the volumes tab, but the volumes would not get listed. With these changes, the volumes tab does not get shown.
1. I created a role that had access to `listVolumes`;
2. I created an account using the role;
3. I created a VM using the account;
4. In the created account, I accessed the VM's page and verified that the volumes tab was shown;
5. I removed the access to `listVolumes` from the role created in step 1;
6. In the created account, I accessed the VM's page again and …
> Hide volumes tab in instance page when user does not have permission to list volumes

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/MigrateKVMAsync.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtMigrateCommandWrapper.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/MigrateKVMAsyncTest.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtMigrateCommandWrapperTest.java
Using KVM as the hypervisor, when migrating a VM that has volumes on NFS storage, if any volume of it is migrated, all volumes that are on NFS must be migrated, otherwise, the migration will fail with the error `unable to execute QEMU command 'block- export-add': Block node is read-only`. 
This situation occurs because, during the migration of VMs with volumes, the ACS does not inform which volumes should be migrated, causing Libvirt to assume that they will all be migrated, even if their path does not change, leading the hypervisor to try to overwrite the volumes of the VM during migration, resulting in the aforementioned error.
This PR changes the migration API used so that ACS informs which volumes should be migrated.
A VM with 3 volumes on NFS storage was created and used for the …
> Fix KVM live migration with NFS volumes

- server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
> explanatory error message on delete attempt of default system offering

- plugins/network-elements/nsx/pom.xml
This excludes indirect dependencies of vapi-authentication to allow build to work, with mvn 3.9 on Darwin environments.
Fixes #8820 
Tested as a local build on this env:
```
Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)
Maven home: /opt/homebrew/Cellar/maven/3.9.6/libexec
Java version: 11.0.16.1, vendor: Homebrew, runtime: /opt/homebrew/Cellar/openjdk@11/11.0.16.1_1/libexec/openjdk.jdk/Contents/Home
Default locale: en_IN, platform encoding: UTF-8
OS name: "mac os x", version: "14.4.1", arch: "aarch64", family: "mac"
```
> plugin: fix nsx build failure with mvn 3.9

- plugins/storage/volume/linstor/src/main/java/com/cloud/hypervisor/kvm/storage/LinstorStorageAdaptor.java
If disconnect is running on a diskless node, try to cleanup the resource.
Moving/Stopping resources on a hyperconverged and non hyperconverged linstor cluster
> linstor: cleanup diskless nodes on disconnect

- ui/src/config/router.js
- ui/src/store/modules/permission.js
As reported in https://github.com/apache/cloudstack/pull/8713#issuecomment-1969866705, the Storage section in the sidebar is not displayed to users when they do not have permission to the API `listVolumesMetrics`. However, roles can have permissions to other APIs, such as `listBackups` and `listSnapshots`, in which case the section should be displayed. This situation is not exclusive to the Storage section.
This PR fixes this issue by changing how the routes are filtered. Now, sections will be shown if they have at least one visible child. For other routes, the previous logic is still applied.
Closes #8730.
Here's how the menu looks like before (left) and after the changes (right) for a user that does not have permission for `listVolumesMetrics`:
1. I created a role `v`, based on the role …
> Show menu section if user has access to at least one of its pages

- utils/src/main/java/com/cloud/utils/net/MacAddress.java
- utils/src/test/java/com/cloud/utils/net/MacAddressTest.java
Cleanup old mac address handling code to use JDK11 lib instead of hacks. Also really strange to see some basic string parsing code was written by hand, replaced with Long.parseValue(str, 16) to convert hex string to long.
Fixes #8174
> utils: cleanup MacAddress and MacAddressTest

- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
This PR fixes the below issue:
1. Register two VM templates, small and large.
2. Deploy VM using smaller template while overriding the rootdisksize
3. Start VM if not started
4. Stop VM
5. Reinstall VM to larger VM template
6. Observe new root is the size of old volume. This is happening because the `rootdisksize` detail for VM overrides the template's size.
> Fix: Update rootdisksize detail on restore VM

- ui/src/config/section/infra/systemVms.js
This adds changes to show the systemvm agent version in the list and resource view.
Fixes #6831
Saw this in a test env:
> ui: show systemvm agent version in the list and resource view

- ui/public/locales/en.json
- ui/src/config/section/account.js
This allow admins to change role of an account via UI by changing the `roleid` param to the updateAccount API/form.
This fixes #7756
> ui: add support to change Account role for admins

- ui/src/config/section/image.js
- ui/src/views/image/RegisterOrUploadIso.vue
- ui/src/views/image/UpdateISO.vue
The parameter `passwordenabled` is available on the APIs that register and update ISOs, however, it had not been added to the UI yet.
This parameter was added to the UI, making it possible to specify it when registering/updating ISOs.
<details><summary>Before</summary>
</details>
<details><summary>After</summary>
</details>
> Add password enabled during ISO register and update

- plugins/storage/volume/linstor/src/main/java/com/cloud/hypervisor/kvm/storage/LinstorStorageAdaptor.java
disconnectPhysicalDisk(String, KVMStoragePool) seems to calls the plugin with the resource name instead of the device path, so we also have to search for resource names, while cleaning up.
6 Node CloudStack cluster, non hyperconverged.
> linstor: disconnect-disk also search for resource name in Linstor

- plugins/network-elements/juniper-contrail/src/test/java/org/apache/cloudstack/network/contrail/management/MockAccountManager.java
- server/src/main/java/com/cloud/user/AccountManager.java
- server/src/main/java/com/cloud/user/AccountManagerImpl.java
- server/src/main/java/org/apache/cloudstack/acl/RoleManagerImpl.java
- server/src/test/java/com/cloud/user/MockAccountManagerImpl.java
- server/src/test/java/org/apache/cloudstack/acl/RoleManagerImplTest.java
When calling the `listRoles` API, users can see roles with more permissions than theirs.
Therefore, the behavior of the `listRoles` API was changed so that users can only see roles that their role has permission to access (roles with same and less permissions).
1. I created a custom role based on User role and added the `listRoles` API to it.
2. I created an account using the role from step 1 and logged into it.
3. I called the `listRoles` API via CloudMonkey and verfied that the roles with more permissions than mine were not listed, such as default admin roles.
> Limit `listRoles` API visibility

- ui/src/views/compute/EditVM.vue
> ui: fix haenable in edit vm form

- api/src/main/java/com/cloud/user/ResourceLimitService.java
- engine/api/src/main/java/org/apache/cloudstack/engine/orchestration/service/VolumeOrchestrationService.java
- engine/api/src/main/java/org/apache/cloudstack/engine/subsystem/api/storage/DataStoreDriver.java
- engine/api/src/main/java/org/apache/cloudstack/engine/subsystem/api/storage/PrimaryDataStoreDriver.java
- engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
- engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/VolumeOrchestrator.java
- plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/driver/ScaleIOPrimaryDataStoreDriver.java
- plugins/storage/volume/scaleio/src/test/java/org/apache/cloudstack/storage/datastore/driver/ScaleIOPrimaryDataStoreDriverTest.java
- server/src/main/java/com/cloud/resourcelimit/ResourceLimitManagerImpl.java
- server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
- server/src/test/java/com/cloud/vm/UserVmManagerImplTest.java
- server/src/test/java/com/cloud/vpc/MockResourceLimitManagerImpl.java
- test/integration/component/test_resource_limit_tags.py
- test/integration/smoke/test_restore_vm.py
- tools/marvin/marvin/lib/base.py
Because we have the condition that a powerflex/scaleio volume can be a size /8 the user can exploit this and request a smaller number without exceeding the limit, but eventually PF will deploy a volume of size [req-size ]< and /8, thus allowing the user to break the limit
1. Set a tag limit of 6GB 
2. Deploy a volume with the offering of the tag limit and override the size to '5' 
3. Cloudstack will consider correctly that request is within the tag limit 5<6, but will eventually deploy a volume with 8 GB exceeding the limit
4. After syncing resource counts this the error becomes evident.
> Fix exceeding of resource limits with powerflex

- ui/public/locales/en.json
- ui/src/components/page/GlobalFooter.vue
Many users are using the footer link to create Github issues about CloudStack that are usually discussed on the users@ mailing list. This created a large number of bogus issues that aren't bugs. We want to encourage engagement but not create non-issue issues.
This fixes that behaviour by diverting them to Github Discussions which are linked with the user@ ML, smart users can still report actual bugs/issues via the issues tab. Any user starting a discussions would encourage that interaction and such queries are sent to users@ ML for others to help the user.
> ui: change reporting link to Github Discussions

- ui/src/views/dashboard/UsageDashboard.vue
An undefined variable `item` was used.
Before:
After:
> ui: fix dashboard limit format

- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
- test/integration/smoke/test_events_resource.py
Destroys old ROOT volume for the VM to be restored in its own context to allow event to be published with resourceid. Fixes exception in test_event_resources.py
Fixes failures seen in:
https://github.com/apache/cloudstack/pull/8601#issuecomment-2078654228
https://github.com/apache/cloudstack/pull/8601#issuecomment-2079018980
https://github.com/apache/cloudstack/pull/8601#issuecomment-2079141241
> server,test: fix resourceid for VOLUME.DESTROY in restore VM

- framework/config/src/main/java/org/apache/cloudstack/framework/config/ConfigKey.java
- framework/config/src/test/java/org/apache/cloudstack/framework/config/ConfigKeyScheduledExecutionWrapperTest.java
This adds a NPE check on the s_depot.global() which can cause NPE in
case of unit tests, where s_depot is not null but the underlying config
dao is null (not mocked or initialised) via `s_depot.global()` becomes
null.
Related to:
#9103
#8916
> framework/config: make logic in ::value() defensive

- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
This PR fixes three instances of a typo 'keyparis' instead of 'keypairs' in InvalidParameterValueException
> Fix typo keyparis -> keypairs in InvalidParameterValueException

- server/src/main/java/com/cloud/network/as/AutoScaleManagerImpl.java
fixes #9042 
https://github.com/apache/cloudstack/assets/153340/71d5ea98-f156-4951-a2f9-a305df2e3790
> api,server: list autoscalevmgroups with keyword

- engine/schema/src/main/java/com/cloud/user/UserDataVO.java
- engine/schema/src/main/resources/META-INF/db/schema-41900to41910.sql
Adds removed column for `cloud.user_data` table.
Fixes deletion of userdata when template is removed.
Fixes #8703
- Added a userdata
- Added a template using the userdata
- Deployed a VM using template
- Deleted both VM and template
- Tested userdata deletion
Before:
After:
https://github.com/apache/cloudstack/assets/153340/fc89ea1f-86e0-4765-ba53-5e655b59f2fb
> engine-schema: add removed column for cloud.user_data, fix delete op

- api/src/main/java/org/apache/cloudstack/api/command/user/vm/ListVMsCmd.java
- api/src/main/java/org/apache/cloudstack/api/response/UserVmResponse.java
- api/src/main/java/org/apache/cloudstack/query/QueryService.java
- plugins/metrics/src/main/java/org/apache/cloudstack/api/ListVMsMetricsCmd.java
- plugins/metrics/src/main/java/org/apache/cloudstack/metrics/MetricsServiceImpl.java
- plugins/metrics/src/main/java/org/apache/cloudstack/response/VmMetricsResponse.java
- server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
- server/src/main/java/com/cloud/api/query/ViewResponseHelper.java
- ui/src/config/router.js
- ui/src/config/section/compute.js
- ui/src/views/AutogenView.vue
For both the `listVirtualMachines` and `listVirtualMachineMetrics` APIs, by default, ACS queries all VM details (the `details` parameter is default `all`) and consequently queries the `cloud.vm_stats` table for each VM, creating a summary of statistics. Therefore, every process carried out in the UI that uses the `listVirtualMachines` API also loads the VM statistics, which can cause slowdowns depending on the number of records.
A new configuration `return.vm.stats.on.vm.list` (with default true), was added, when it is false, the `listVirtualMachines` API will not list the VM's metrics by default.
Called listVirtualMachines API, without any parameters:
- before this PR, the all the VM's details were returned;
- with this PR and `return.vm.stats.on.vm.list` as true (default), all the …
> Do not retrieve VM's stats on normal VM listing

- plugins/storage/volume/linstor/src/main/java/com/cloud/hypervisor/kvm/storage/LinstorStorageAdaptor.java
- plugins/storage/volume/linstor/src/main/java/org/apache/cloudstack/storage/datastore/driver/LinstorPrimaryDataStoreDriverImpl.java
- plugins/storage/volume/linstor/src/main/java/org/apache/cloudstack/storage/datastore/util/LinstorUtil.java
Before we only asked the first resource for the device path, if those resource was down or broken, we wouldn't get a device path at all. Now we go through all resource and use the first device path we find, as device path are always equal for all resources.
Tested on a 2 Linstor clusters
> linstor: make getDevicePath more robust

- ui/src/components/view/ListResourceTable.vue
When accessing the `Backups` or `Instance snapshots` tabs through the VM details, there are some columns that show no data (created column for example).
This PR aims to fix this and populate these columns with their respective data.
I followed the same steps from `How did you try to break this feature and the system with this change?` then I verified that all columns presented data.
1. In the UI, create a backup and a VM snapshot to a VM;
2. Access the `Backups` and `Instance snapshots` tabs in the VM page;
3. Some columns in these tabs will be blank.
> Fix columns in VM details tabs

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/LibvirtStorageAdaptor.java
> kvm: consider provisioning type for local data volumes

- ui/src/views/infra/zone/ZoneWizardLaunchZone.vue
In the UI, during zone creation, if a new host is created without specifying host tags, ACS adds the `null` tag to it automatically.
This behaviour has been fixed, making it so that no host tags are added in this situation 
I created a zone through the UI without specifying host tags and verified that no tags were added.
I also created while specifying host tags and verified that they were added accordingly
> Fix null host tags while creating a zone

- ui/src/views/project/AddAccountOrUserToProject.vue
This PR fixes https://github.com/apache/cloudstack/issues/7216
> UI: Update AddAccountOrUserToProject to show a drop down for account & user

- api/src/main/java/org/apache/cloudstack/api/response/VolumeResponse.java
- engine/schema/src/main/resources/META-INF/db/views/cloud.volume_view.sql
- server/src/main/java/com/cloud/api/query/dao/VolumeJoinDaoImpl.java
- server/src/main/java/com/cloud/api/query/vo/VolumeJoinVO.java
> api,server: encryptformat in volume response

- plugins/api/discovery/src/main/java/org/apache/cloudstack/api/response/ApiDiscoveryResponse.java
- plugins/api/discovery/src/main/java/org/apache/cloudstack/api/response/ApiParameterResponse.java
- plugins/api/discovery/src/main/java/org/apache/cloudstack/discovery/ApiDiscoveryServiceImpl.java
API params can be marked accessible to selected role types using  `authorized` values in API command class.
The existing behaviour of lisApis API was to return all parameters of the API irrespective of the caller's role type. This PR fixes it by adding checks to filter params.
Tested by setting an API param as,
```
@Parameter(name = ApiConstants.SCOPE, type = BaseCmd.CommandType.STRING, description = "Scope of the Webhook",
authorized = {RoleType.Admin, RoleType.DomainAdmin})
private String scope;
```
Using cmk,
```
(localcloud) 🐱 > set username admin
(localcloud) 🐱 > sync
Discovered 766 APIs
(localcloud) 🐱 > list apis name=createWebhook filter=name,params
{
"api": [
{
"name": "createWebhook",
"params": [
{
"description": "an optional domainId for the Webhook. If the account parameter is …
```
> api: listApis should return params based on caller

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/StorageAdaptor.java
This PR addresses the issue #8789 
The original issue is disconnectPhysicalDiskByPath() implementation in FibreChannelAdaptor always returns true irrespective of the success of the operation. This was already fixed in the PR #8889 .
Ideally this method has to be called after choosing the right adapter based on the storage pool type of the volume path, but currently it is just called in a loop. 
https://github.com/shapeblue/cloudstack/blob/05b9b6e2e77b9b633f0fe22aff5f9f3c047b2303/plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStoragePoolManager.java#L200-L212
while trying to fix the case of running into the loop of all adapters by somehow passing the storage pool type to that caller cleanup() method but this is touching all over the code (which I fear it creates …
> Update the java doc for the method disconnectPhysicalDiskByPath

- server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
> server: search template name and display text if keyword is passed

- server/src/main/java/com/cloud/deploy/DeploymentPlanningManagerImpl.java
This PR doesn't load host tags/details for the last host when it doesn't exist, while starting VM with 'considerlasthost' enabled.
Fixes #9033
> While starting VM with 'considerlasthost' enabled, don't load host tags/details for the last host when it doesn't exist

- ui/public/locales/en.json
- ui/public/locales/pt_BR.json
- ui/src/views/compute/AssignInstance.vue
- ui/src/views/compute/DeployVM.vue
- ui/src/views/compute/wizard/OwnershipSelection.vue
- ui/src/views/network/CreateIsolatedNetworkForm.vue
- ui/src/views/network/CreateL2NetworkForm.vue
This PR adds a new component (`OwnershipSelection`) to specify the account/project when creating a VM and networks (can also be used for other resources in the future). This component makes it easy for operators with roles Admin and Domain Admin to create VMs for any account and/or project that it has permission.
I deployed a number of VMs using different accounts and projects in different domains.
I tried to verify that the UI only showed the permissions according to the account/project selected.
> [UI] Add option to specify account/project while deploying VMs and creating networks

- api/src/main/java/com/cloud/network/vpc/VpcService.java
- api/src/main/java/org/apache/cloudstack/api/command/user/vpc/CreateVPCCmd.java
- api/src/test/java/org/apache/cloudstack/api/command/user/vpc/CreateVPCCmdTest.java
- server/src/main/java/com/cloud/network/vpc/VpcManagerImpl.java
> vpc,event: fix events for createVpc

- core/src/main/java/com/cloud/agent/api/GetVolumeStatAnswer.java
- core/src/main/java/com/cloud/agent/api/GetVolumeStatCommand.java
- core/src/main/java/org/apache/cloudstack/storage/to/VolumeObjectTO.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtGetVolumeStatCommandWrapper.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtMigrateVolumeCommandWrapper.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStoragePool.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/ScaleIOStorageAdaptor.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/ScaleIOStoragePool.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/StorageAdaptor.java
- plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/driver/ScaleIOPrimaryDataStoreDriver.java
- plugins/storage/volume/scaleio/src/test/java/org/apache/cloudstack/storage/datastore/driver/ScaleIOPrimaryDataStoreDriverTest.java
This PR improves the ScaleIO volume live migration, uses usable bytes from source disk to format the destination disk.
Tested PowerFlex/ScaleIO volume live migration across storage clusters, with volumes of varied sizes, normal & encrypted volumes (with 32MB & 128MB reserve), with/without data.
> PowerFlex/ScaleIO volume live migration - use usable bytes from source disk to format the destination disk

- server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
This PR checks the upload volume format with the supported hypervisor,  fail if supported hypervisor not found on zone.
Fixes #8652 
Manually tested upload RAW volume from local.
> Upload volume format check with the supported hypervisor, fail if supported hypervisor not found on zone

- api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
- api/src/main/java/org/apache/cloudstack/api/command/user/volume/ListVolumesCmd.java
- api/src/main/java/org/apache/cloudstack/api/response/VolumeResponse.java
- engine/schema/src/main/java/com/cloud/storage/dao/VolumeDao.java
- engine/schema/src/main/java/com/cloud/storage/dao/VolumeDaoImpl.java
- server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
- server/src/main/java/com/cloud/api/query/dao/VolumeJoinDaoImpl.java
- server/src/main/java/com/cloud/api/query/vo/VolumeJoinVO.java
This PR...
Fixes: #8635 
very much a PoC on this.
> list by isEncrypted

- engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
Using KVM as a hypervisor, when performing a live migration of a VM with its datadisks, the ROOT volume is also migrated, even if the user has not requested this action. Since this migration of the root volume is unnecessary and causes greater latency for the live migrate process, this behavior has been changed. Now, when migrating a VM and its datadisks, only the volumes selected for migration will actually be migrated.
A new VM was created with a root and a data volume for testing; Several live migration scenarios were tested. The cases are described below.
The following migrations occurred successfully, in each case, when only the datadisk was moved, a dump of the VM XML was performed to verify that the ROOT volume had not been moved.
| Volume | Origin | Destination |
| ------ | ------ …
> Removed unnecessary migration of `ROOT` volumes with KVM

- engine/schema/src/main/java/org/apache/cloudstack/storage/datastore/db/ImageStoreDaoImpl.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtMigrateCommandWrapper.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtMigrateCommandWrapperTest.java
This PR fixes #8901 
- create env with 2 image store
- create a vm
- register an ISO
- attach the ISO to the vm
- migrate the vm to another host
expected result: migration succeeds.
actually result: sometimes migration works, sometimes not
> kvm: replace ISO path in vm XML configuration during vm migration

- engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
- server/src/main/java/com/cloud/deploy/DeploymentPlanningManagerImpl.java
This PR doesn't load host tags/details for the last host when it doesn't exist, while starting VM with 'considerlasthost' enabled. It addresses https://github.com/apache/cloudstack/issues/9033, in main
> While starting VM with 'considerlasthost' enabled, don't load host tags/details for the last host when it doesn't exist [main]

- tools/marvin/mvn-setup.py
Fixes #7927 
We replace the first occurence of `-` with `+` to make the marvin version PEP440 compliant
1. Built the deb packages.
2. Extracted the marvin tar from the deb package
3. pip install the package 
For testing, use pip version 24.0. Able to reproduce the bug mentioned in the link with this version of pip.
> Ensure marvin package version is PEP440 compliant

- plugins/user-authenticators/saml2/src/main/java/org/apache/cloudstack/api/command/SAML2LoginAPIAuthenticatorCmd.java
- plugins/user-authenticators/saml2/src/main/java/org/apache/cloudstack/saml/SAML2AuthManager.java
- plugins/user-authenticators/saml2/src/main/java/org/apache/cloudstack/saml/SAML2AuthManagerImpl.java
- plugins/user-authenticators/saml2/src/test/java/org/apache/cloudstack/api/command/SAML2LoginAPIAuthenticatorCmdTest.java
Adminstrators should ensure that IDP configuration has signing certificate for the actual signature check to be performed. In addition to this, this change introduces a new global setting `saml2.check.signature` which can deliberately fail a SAML login attempt when the SAML response has missing signature.
Fixes #4519
> saml: introduce saml2.check.signature

- engine/schema/src/main/resources/META-INF/db/views/cloud.user_vm_view.sql
The user_vm_view can end up not picking the right index to join against the user_ip_address table causing full table scan on the user_ip_address table. This could be related to a MySQL bug
https://bugs.mysql.com/bug.php?id=41220
In a test environment with 20k shared networks and over 20M IPs, the listVirtualMachines API was found to take over 17s to return list of just 10 VMs. However, with this fix it would now take under 200ms to return the list. (MySQL Server: 8.0.36)
MySQL slow query logging showed ~nearly 20M table scans of the IP address table:
```
SET timestamp=1715410270;
SELECT user_vm_view.id, user_vm_view.name /*snipped*/ FROM user_vm_view
WHERE user_vm_view.id IN (4,6,7,8,9,10,11,12,13,14,15,16);
```
Visual explain:
This may not be worse than what it already is, I'm open to …
> engine/schema: force index in user_vm_view to speed up instance listing

- api/src/main/java/org/apache/cloudstack/api/command/admin/offering/CreateServiceOfferingCmd.java
This PR adds to the `cpuSpeed` parameter of `CreateServiceOfferingCmd` a description how it will be interpreted in the case cgroups are being used on KVM.
Fixes: #6743
> add to cpu speed parameter a description of the cgroup2 case

- plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java
- plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/version/KubernetesVersionManagerImpl.java
- plugins/integrations/kubernetes-service/src/test/java/com/cloud/kubernetes/version/KubernetesVersionServiceTest.java
Fixes count value in listKubernetesClusters and listSupportedKubernetesVersions APIs response.
Currently, it returns items count of the response
> cks: fix list apis response count

- engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/VolumeOrchestrator.java
Fixes #8450
When a primary storage on which volumes of system VMs are present is put on maintenance, CloudStack recreates the volume on the other available store. When such recreation is done between stores of different scopes, there are cases in which old volume entries remain in `Destroy` state. This PR expunges such volumes.
> engine-orchestration: expunge destroyed system vm volume

- ui/src/views/dashboard/UsageDashboard.vue
Fixes #9233
Retrieves and shows dashboard details if they are allowed
- Created a role with some permissions denied (listKubernetesClusters, listVPCs, listEvents)
- Created an account with the role
- Logged in with new account to observe elements for above APIs are not shown
- Created another account with a role which has permissions for above APIs
- Logged in with the account to observe all UI elements are shown
> ui: fix dashboard retrievals based on permissions

- ui/src/views/infra/AddPrimaryStorage.vue
Fixes Linstor related fields not showing in add primary storage, while using custom protocol.
Fixes: #8550 
created linstor primary storage with different protocol/provider settings
> linstor: ui show Server and resource-group fields with custom protocol

- plugins/storage/volume/linstor/src/main/java/org/apache/cloudstack/storage/datastore/driver/LinstorPrimaryDataStoreDriverImpl.java
- plugins/storage/volume/linstor/src/main/java/org/apache/cloudstack/storage/datastore/util/LinstorUtil.java
- plugins/storage/volume/linstor/src/main/java/org/apache/cloudstack/storage/snapshot/LinstorVMSnapshotStrategy.java
- plugins/storage/volume/linstor/src/main/resources/META-INF/cloudstack/storage-volume-linstor/spring-storage-volume-linstor-context.xml
- pom.xml
This adds VM-Instance disk snapshot support for
Linstor primary storage. Instance snapshots are stored on
the used Linstor storage pool backend and can be converted
into regular volume snapshots and also reverted.
Instance VM snapshots are not fully atomic but with the
create multi snapshot feature as good as it gets.
Snapshots are done over multiple volumes in the same devicemanager run.
Tested on hyper and non hyper-converged cluster, with LVM and ZFS as Linstor primary storage backend.
* Making a VM-Snapshot with multiple disks
* Snapshot from VM-Snapshot disk
* Revert to VM-Snapshot
> linstor: Support VM-Instance Disk snapshots

- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtConvertInstanceCommandWrapperTest.java
This PR fixes a unit test failure in LibvirtConvertInstanceCommandWrapperTest.
Before this patch, `testGetUnmanagedInstanceDisks` calls the `getNfsStoragePoolHostAndPath` method which then calls `mount | grep null`. If the system running test has some mounts with the text `null` in them, the test fails.
This PR fixes this by mocking the return value for `getNfsStoragePoolHostAndPath`.
> Fix unit test failure in LibvirtConvertInstanceCommandWrapperTest

- api/src/main/java/org/apache/cloudstack/api/command/user/vm/ListVMsCmd.java
- api/src/main/java/org/apache/cloudstack/query/QueryService.java
- engine/schema/src/main/resources/META-INF/db/schema-41900to41910-cleanup.sql
- server/src/main/java/com/cloud/server/StatsCollector.java
- ui/src/config/section/compute.js
- ui/src/views/AutogenView.vue
Followup from https://github.com/apache/cloudstack/pull/8782
- Changes behaviour of details param handling via global setting:
- listVirtualMachines API: when the details param is not provided, it returns whether stats are returned controlled by a new global setting `list.vm.default.details.stats`
- listVirtualMachinesMetrics API: when the details param is not provided, it uses `all` details including `stats`
- Users who are affected slow performance of the listVirtualMachines API response time can set `list.vm.default.details.stats` to `false`
- Remove ConfigKey vm.stats.increment.metrics.in.memory which was renamed to `vm.stats.increment.metrics` in #5984 and also remove unused/unnecessary global settings via upgrade path
- Changes default value of VM stats accumulation setting …
> api: listVM API improvement followup, change returning of stats detail

- ui/src/utils/sort.js
This improves the UI sorting utility to check for metrics data and sort after cleaning the string data.
Fixes #8663
> ui: improve sort utility for metrics

- engine/schema/src/main/java/com/cloud/service/dao/ServiceOfferingDao.java
- engine/schema/src/main/java/com/cloud/service/dao/ServiceOfferingDaoImpl.java
- server/src/main/java/com/cloud/api/ApiDBUtils.java
- server/src/main/java/com/cloud/api/query/dao/VolumeJoinDaoImpl.java
> protect against missing service offering

- plugins/host-allocators/random/src/main/java/com/cloud/agent/manager/allocator/impl/RandomAllocator.java
- server/src/main/java/com/cloud/agent/manager/allocator/impl/FirstFitAllocator.java
- server/src/main/java/com/cloud/agent/manager/allocator/impl/RecreateHostAllocator.java
- server/src/main/java/com/cloud/deploy/DeploymentPlanningManagerImpl.java
- server/src/main/java/com/cloud/deploy/FirstFitPlanner.java
- server/src/main/java/com/cloud/server/ManagementServerImpl.java
This PR fixes a scenario where if the first cluster verified by ACS does not have any compatible hosts, an exception is thrown, ignoring the verification of possible compatible hosts in other clusters.
- Cluster 1: Host A
- Cluster 2: Host B
Using the environment above, I added the flexible host tag `false` to Host A, and tried to deploy a VM; which would always result on an incompatible host for Cluster 1. Prior to this patch, the `CloudRuntimeException` is thrown with the message `No suitable host found for vm [...].` and Host B is not verified.
After applying this patch, the message `No suitable host found for VM [%s] in %s.` is still logged, however, Host B is verified for compatibility and the VM is deployed as expected.
> Fix allocation of VMs with multiple clusters

- ui/src/components/view/ResourceLimitTab.vue
If the user configured a limit to 0 on the Domain's "Configure Limits" tab,  after submitting, the value would return to -1. This was only a bug in the UI as the value was actually saved in the back-end.
Before the changes:
After changing the value to 0 and submitting, the value returned to -1:
After the UI fix, the value 0 keeps being shown after submission:
Before the changes made, after creating a test domain and accessing the limit settings in the Configure limits tab, when changing some default setting from -1 to 0 and clicking the submit button, the resource limit would return to -1 on the UI.
With the changes, changing a limit value from -1 to 0 and pressing the Submit button, 0 was shown in the UI. The information in the resource preview tab was also checked, confirming that the …
> fix: domain limits tab ui is now able to present 0 to the user

- framework/quota/src/main/java/org/apache/cloudstack/quota/QuotaManagerImpl.java
- test/integration/plugins/quota/test_quota_balance.py
- usage/src/main/java/com/cloud/usage/UsageManagerImpl.java
This PR aims to improve the overall Quota balance calculation by breaking into separate methods and calculating based on the period dates rather than the Quota usage records for a better understanding of its flow. This PR also introduces smoke test for Quota balance and normalized the aggregation usage calculation when it is not daily or hourly.
1. Create a quota tariff with the usage type `6` (i.e. volume).
2. Created an account.
3. Added credits to the account.
4. Created a volume assigned to the newly created account.
5. Verified that the account balance was consistent with the tariff value.
```sql
id   |account_id|domain_id|credit_balance|credits_id|updated_on         |
-----+----------+---------+--------------+----------+-------------------+
12876|        47|        1|  100.00000000| …
```
> [Quota] Improve Quota balance calculation flow

- plugins/user-authenticators/oauth2/src/main/java/org/apache/cloudstack/oauth2/OAuth2AuthManagerImpl.java
- ui/src/config/section/config.js
Fixes: https://github.com/apache/cloudstack/issues/8501
1. Action button to enable/disable Oauth2 provider
2. Trim extra spaces from clientid, uri and secretkey
> Add action button to enable/disable Oauth provider

- engine/schema/src/main/java/com/cloud/domain/dao/DomainDetailsDao.java
- engine/schema/src/main/java/com/cloud/domain/dao/DomainDetailsDaoImpl.java
- engine/schema/src/main/java/com/cloud/user/AccountDetailsDao.java
- engine/schema/src/main/java/com/cloud/user/AccountDetailsDaoImpl.java
This PR fixes an issue when using the LDAP integration with ACS. PR #6812 normalized the account and domain configurations to only encrypt the values with configurations in the `Hidden` and `Secure` categories. However, that PR failed to address the use of these configurations. This resulted in using the encrypted value of the configuration, when it should decrypt it first, as observed in issue #8637.
This problem was fixed by adding the method `getActualValue()` that checks if the configurations in the Account and Domain are in the `Hidden` and `Secure` categories, and decrypting it, if needed.
**NOTE:** For users that manually set the configurations `ldap.bind.password` and `ldap.truststore.password` to a plain value in order to fix the faulty behaviour, it is required to store them …
> Decrypt account and domain configurations when needed

- api/src/main/java/com/cloud/network/VpcVirtualNetworkApplianceService.java
- core/src/main/java/com/cloud/agent/api/ManageServiceCommand.java
- core/src/main/java/com/cloud/agent/resource/virtualnetwork/VRScripts.java
- core/src/main/java/com/cloud/agent/resource/virtualnetwork/VirtualRoutingResource.java
- core/src/main/java/org/apache/cloudstack/agent/routing/ManageServiceCommand.java
- server/src/main/java/com/cloud/network/element/VpcVirtualRouterElement.java
- server/src/main/java/com/cloud/network/router/VpcVirtualNetworkApplianceManagerImpl.java
- server/src/test/java/com/cloud/vpc/MockVpcVirtualNetworkApplianceManager.java
- systemvm/debian/opt/cloud/bin/manage_service.sh
This PR fixes https://github.com/apache/cloudstack/issues/8108
As of now, on adding a new network tier to a VPC, results in a small network disruption because of keepalived's config reload on both the VRs. This patch fixes this by doing operations in this order:
1. Stop keepalived on all the backup VRs. This prevents the backup VR from becoming master when keepalived on the PRIMARY VR is getting reloaded.
2. Update the config and reload on all primary VRs.
3. Update the config and restart on all backup VRs.
Logs before patch on Primary VR
```
tail -f /var/log/messages | grep keepalived
Jun 13 11:53:31 systemvm Keepalived_vrrp[10528]: (inside_network) Entering BACKUP STATE
Jun 13 11:54:55 systemvm Keepalived_vrrp[10528]: (inside_network) Backup received priority 0 advertisement
Jun 13 …
```
> Prevent network disruption on adding a VPC tier for redundant VRs

- api/src/main/java/org/apache/cloudstack/api/command/user/autoscale/CreateAutoScaleVmProfileCmd.java
- api/src/main/java/org/apache/cloudstack/api/command/user/autoscale/UpdateAutoScaleVmProfileCmd.java
- api/src/main/java/org/apache/cloudstack/api/command/user/userdata/RegisterUserDataCmd.java
- api/src/main/java/org/apache/cloudstack/api/command/user/vm/DeployVMCmd.java
- api/src/main/java/org/apache/cloudstack/api/command/user/vm/ResetVMUserDataCmd.java
- api/src/main/java/org/apache/cloudstack/api/command/user/vm/UpdateVMCmd.java
- api/src/main/java/org/apache/cloudstack/api/response/AutoScaleVmProfileResponse.java
- api/src/main/java/org/apache/cloudstack/api/response/VMUserDataResponse.java
- api/src/main/java/org/apache/cloudstack/userdata/UserDataManager.java
- engine/components-api/src/main/java/com/cloud/configuration/ConfigurationManager.java
- engine/userdata/src/main/java/org/apache/cloudstack/userdata/UserDataManagerImpl.java
- server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
- server/src/main/java/com/cloud/network/as/AutoScaleManagerImpl.java
- server/src/main/java/com/cloud/vm/UserVmManager.java
- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
- server/src/test/java/com/cloud/network/as/AutoScaleManagerImplTest.java
- ui/src/views/compute/RegisterUserData.vue
This PR validates the user data with actual length only, and has some code improvements.
Fixes #8415
Manually tested managed user data registration, and instance creation from UI.
> User data content size validation, and related code improvements

- plugins/hypervisors/xenserver/src/main/java/org/apache/cloudstack/hypervisor/xenserver/ExtraConfigurationUtility.java
- plugins/hypervisors/xenserver/src/test/java/org/apache/cloudstack/hypervisor/xenserver/ExtraConfigurationUtilityTest.java
This PR updates extraconfig for platform param in xen/xcpng. Also, fixed map param key, not to replace '-' with '_' (replace only applicable to param / map-param).
Fixes #8847 
Before Fix:
After Fix:
[Dev] VM is_a_template param check (in recordMap):
Deployed VM with platform extraconfig after setting the global config.
- **enable.additional.vm.configuration** to **true**
- **allow.additional.vm.configuration.list.xenserver** to **platform:exp-nested-hvm**
```
(testenv) 🐱 > deploy virtualmachine templateid=da64d661-2991-11ef-81fa-1e001600014a serviceofferingid=3c6ff3e9-4cb2-4aa6-81a1-5733272a5a4f zoneid=e6ff5d2b-46b4-4d41-b28b-704365edcf3b name=TestVM04 extraconfig=platform%3Aexp-nested-hvm%3Dtrue
```
```
[ref-trl-6837-x-M7-suresh-anaparti-xs1 ~]# xe vm-list params=platform …
```
> Update extraconfig for platform param in xen/xcpng

- plugins/network-elements/vxlan/src/main/java/com/cloud/network/guru/VxlanGuestNetworkGuru.java
> vxlan: do not create duplicated network for private gateway

- ui/src/config/section/storage.js
> ui: fix user create featured template from volume

- core/src/main/java/com/cloud/agent/api/storage/CreateEntityDownloadURLCommand.java
- engine/api/src/main/java/org/apache/cloudstack/engine/subsystem/api/storage/DataObject.java
- plugins/storage/image/default/src/main/java/org/apache/cloudstack/storage/datastore/driver/CloudStackImageStoreDriverImpl.java
- server/src/main/java/com/cloud/storage/upload/UploadMonitorImpl.java
- server/src/main/java/org/apache/cloudstack/diagnostics/to/DiagnosticsDataObject.java
- services/secondary-storage/server/src/main/java/org/apache/cloudstack/storage/template/UploadManagerImpl.java
This PR addresses the improvement #6949 
Previously when a template or volume or ISO is downloaded then the file name generated for the downloaded file is a random URL, with this PR we have improved to use the name of the object to set as the file name.
During the preparation of URL, MS uses only alphanumeric characters and replaces others with Hyphen (-).
For example 
Downloaded multiple templates, volumes with various names.
> User friendly name of Downloaded Templates Volumes and ISOs

- api/src/main/java/org/apache/cloudstack/api/command/admin/vm/ListVnfAppliancesCmdByAdmin.java
- api/src/main/java/org/apache/cloudstack/api/command/user/vm/ListVnfAppliancesCmd.java
- server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
- server/src/main/java/org/apache/cloudstack/storage/template/VnfTemplateManagerImpl.java
- ui/src/config/section/image.js
- ui/src/config/section/network.js
- ui/src/views/network/VnfAppliancesTab.vue
> VNF: add API listVnfAppliances

- PULL_REQUEST_TEMPLATE.md
- test/integration/smoke/test_cluster_drs.py
> assertion improvement on cluster DRS

- plugins/storage/volume/linstor/src/main/java/org/apache/cloudstack/storage/datastore/driver/LinstorPrimaryDataStoreDriverImpl.java
revertSnapshot uses currently the UUID instead of the path, which defines the resource group on linstor and is set matching to the path when creating a snapshot. This PR just replaces the UUID by path of a snapshot.
This PR is done against 4.19 as 4.18 has been refactored in between.
* linstor cluster running on same nodes as KVM-Hosts used for ACS.
* Ubuntu 22.04, compiled 4.19 as package, used a non productive cluster to test
* Previous situation: create volume snapshot, create a file in running instance, shutdown instance, try to restore via GUI: Failure as volume cannot be found (which happens if volume has not been initially created in linstor)
* Fixed sitation: same actions, but restore works and disk is verified in state of snapshot after starting instance.
> [linstor] Fix revertSnapshot

- plugins/shutdown/src/main/java/org/apache/cloudstack/shutdown/ShutdownManagerImpl.java
Earlier the triggerShutdown API would immediately shutdown the MS and if it is the same MS on which API is called and there are no pending jobs it would lead to error in the API call. This change adds a delay to the process so the MS would be able to send response to the API.
This should fix test failure seen in PR wrt test_safe_shutdown.py,
https://github.com/apache/cloudstack/pull/8601#issuecomment-2177437854https://github.com/apache/cloudstack/pull/8601#issuecomment-2177479552
Without fix: 
```
localcloud) 🐱 > trigger shutdown managementserverid=1
🙈 Error: Get "http://1.2.3.4:8080/client/api?apiKey=LIN6rqXuaJwMPfGYFh13qDwYz5VNNz1J2J6qIOWcd3oLQOq0WtD4CwRundBL6rzXToa3lQOC_vKjI3nkHtiD8Q&command=triggerShutdown&managementserverid=1&response=json&signature=7PpZ8vp4jKIbTe41HqhNwfjVp4g%3D": …
```
> plugins/shutdown: fix triggerShutdown scheduling and response

- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
This PR changes the checkAccess of when assigning a VM to check for the template itself instead of the account owner of the template. In this way, there is no need for checking if the template is public (it already does so inside checkAccess) and it gives a better message when the assigning fails because of it:
```
Failed to move vm due to Account [...] does not have permission to launch instances from template [...]
```
Instead of:
```
Failed to move vm due to Account [{"accountName":"[...]","id":[...],"uuid":"[...]"}] does not have permission to operate with resource
```
Also, current ACS lets you assign a VM with a public template of domain B to an account of domain A even if `share.public.templates.with.other.domains` is false. This also fixes it.
In a local lab with:
- In domain /A, …
> Fix assignVirtualMachine template checkAccess

- engine/schema/src/main/java/org/apache/cloudstack/storage/datastore/db/ImageStoreDaoImpl.java
This PR reverts a change in #9212 
Got an exception when delete a zone
```
com.cloud.utils.exception.CloudRuntimeException: The zone cannot be deleted because there are Secondary storages in this zone
```
> server: fix additional zones cannot be removed

- engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
- engine/orchestration/src/test/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestratorTest.java
This PR removes duplicate network state checks before shutdown network (seems these checks again are not required, maybe added while resolving conflicts),and adds unit tests for the network state checks in shutdown network.
Keeping this checks after acquiring lock, removed others.
https://github.com/apache/cloudstack/blob/3f9dd4dc07ff40a4e0216014715e4fe37fc46d28/engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java#L3042-L3049
> Remove duplicate network state checks before shutdown network

- server/src/main/java/com/cloud/api/query/dao/VolumeJoinDaoImpl.java
This PR fixes the bug introduced in https://github.com/apache/cloudstack/pull/9235 . This resulted in volume response not having diskofferingid in the response for a service offering with a disk offering.
> Fix volume response for service offering with disk offering

- api/src/main/java/org/apache/cloudstack/api/command/admin/vm/ImportUnmanagedInstanceCmd.java
- core/src/main/java/com/cloud/agent/api/CheckVolumeAnswer.java
- core/src/main/java/com/cloud/agent/api/CheckVolumeCommand.java
- core/src/main/java/com/cloud/agent/api/CopyRemoteVolumeAnswer.java
- core/src/main/java/com/cloud/agent/api/CopyRemoteVolumeCommand.java
- core/src/main/java/com/cloud/agent/api/GetRemoteVmsAnswer.java
- core/src/main/java/com/cloud/agent/api/GetRemoteVmsCommand.java
- core/src/main/java/com/cloud/agent/api/GetUnmanagedInstancesAnswer.java
- core/src/main/java/com/cloud/agent/api/GetUnmanagedInstancesCommand.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtGetRemoteVmsCommandWrapper.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtGetUnmanagedInstancesCommandWrapper.java
- server/src/main/java/org/apache/cloudstack/vm/UnmanagedVMsManagerImpl.java
This PR improves logs while importing vm from remote/external KVM host.
Fixes #8779 
Manually tested import vm operation and checked the import logs in MS / KVM host.
**MS logs =>**
```
2024-06-21 19:45:11,411 DEBUG [c.c.a.t.Request] (qtp1866850137-19:ctx-7f9bf2bb ctx-a94593d9) (logid:a066305c) Seq 1-168603511049682964: Sending  { Cmd , MgmtId: 32986204471710, via: 1(ref-trl-6881-k-M7-suresh-anaparti-kvm1), Ver: v1, Flags: 100011, [{"com.cloud.agent.api.GetRemoteVmsCommand":{"remoteIp":"10.x.x.x","username":"root","wait":"0","bypassHostMaintenance":"false"}}] }
2024-06-21 19:45:11,467 DEBUG [c.c.a.t.Request] (AgentManager-Handler-15:null) (logid:) Seq 1-168603511049682964: Processing:  { Ans: , MgmtId: 32986204471710, via: 1, Ver: v1, Flags: 10, …
```
> Import VM logging improvements

- debian/control
This PR adds cpu-checker as a dependency for Debian/ubuntu distributions
> debian: add cpu-checker to debian/control

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessorTest.java
- plugins/storage/volume/storpool/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/StorPoolBackupSnapshotCommandWrapper.java
Fix volume snapshot of encrypted NFS volume.
```
2024-04-03 15:39:03,835 ERROR [kvm.storage.KVMStorageProcessor] (agentRequest-Handler-1:null) (logid:7f88a6bf) Failed take snapshot for volume [volumeTO[uuid=2cc4e5b3-37e1-437f-928e-13c00b73
caf7|path=2cc4e5b3-37e1-437f-928e-13c00b73caf7|datastore=PrimaryDataStoreTO[uuid=cc7256f6-831e-3c38-86ec-dc785413ce21|name=nfs|id=3|pooltype=NetworkFilesystem]]], in VM [i-2-21-VM], due to [
Failed to convert volumeTO[uuid=2cc4e5b3-37e1-437f-928e-13c00b73caf7|path=2cc4e5b3-37e1-437f-928e-13c00b73caf7|datastore=PrimaryDataStoreTO[uuid=cc7256f6-831e-3c38-86ec-dc785413ce21|name=nfs|id=3|pooltype=NetworkFilesystem]] snapshot of volume [/mnt/cc7256f6-831e-3c38-86ec-dc785413ce21/2cc4e5b3-37e1-437f-928e-13c00b73caf7] to …
```
> Fix volume snapshot of encrypted NFS/StorPool volume

- server/src/main/java/com/cloud/hypervisor/kvm/discoverer/LibvirtServerDiscoverer.java
- server/src/test/java/com/cloud/hypervisor/kvm/discoverer/LibvirtServerDiscovererTest.java
> kvm: support Rocky/RHEL/OL/Alma in the same cluster

- api/src/main/java/com/cloud/vm/VirtualMachineProfile.java
- engine/components-api/src/main/java/com/cloud/vm/VirtualMachineProfileImpl.java
- engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
During live migration of a VM from between hosts having different cgroup versions (cgroupv2 & cgroup), overcommit ratio is ignored.
This PR fixes the above issue.
1. Set overcommit ratio to 2 for the cluster
2. Launch a VM
3. Check value of shares on the host
```bash
$ virsh dumpxml --domain i-2-9-VM | grep shares
<shares>500</shares>
```
4. Live migrate the VM to another host which has a different cgroup than the existing host of the VM.
5. Live migrate the VM back to the original host. And check the shares again.
```bash
$ virsh dumpxml --domain i-2-9-VM | grep shares
<shares>1000</shares>
```
6. Stopping and starting the VM on the same host will reset the value back to `500`.
This happens only when cgroup is different on the destination hosts during live migration. Possibly introduced …
> fix: Update overcommit ratio during live VM migration

- engine/storage/image/src/main/java/org/apache/cloudstack/storage/image/manager/ImageStoreProviderManagerImpl.java
- plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/manager/VmwareManagerImpl.java
- plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java
This PR improves error messaging / logs when starting non-user VMs in VMware, and secondary storage not available or doesn't have enough capacity. It addresses inappropriate messages part 2, 3 in #8390.
Set the config `secondary.storage.capacity.threshold`to below the available secondary storage capacity, stop SSVM and start it. SSVM will fail to start with the below logs.
```
2024-06-24 21:24:59,152 WARN  [c.c.s.StatsCollector] (DirectAgent-35:ctx-1a4ece48 10.0.35.32, job-65/job-66, cmd: StartCommand) (logid:1c0be4ca) Image storage [1] has not enough capacity. Capacity: total=[1 TB], used=[1 TB], threshold=[20.000000298023224%].
2024-06-24 21:24:59,152 INFO  [c.c.h.v.m.VmwareManagerImpl] (DirectAgent-35:ctx-1a4ece48 10.0.35.32, job-65/job-66, cmd: StartCommand) (logid:1c0be4ca) Secondary …
```
> VMware: Improve error messaging / logs when starting non-user VMs, and secondary storage not available or doesn't have enough capacity

- plugins/backup/veeam/src/main/java/org/apache/cloudstack/backup/veeam/VeeamClient.java
- plugins/backup/veeam/src/test/java/org/apache/cloudstack/backup/veeam/VeeamClientTest.java
Using the VMware hypervisor with the Veeam plugin active, when restoring a backup, ACS only verifies if the restore has finished successfully, ignoring any failure and making the user wait the timeout defined in `backup.plugin.veeam.restore.timeout`. This behavior has been fixed by this PR.
It was tested in a local lab:
1. I created one VM, added this VM to one backup offering, and made one manual backup;
2. I tested restoring this backup, and canceled the restore in Veeam server;
3. Before, I needed to wait for the timeout of the restore process to be reached before I was notified that the restore failed;
4. Now, the ACS notifies me when it receives the failure message from Veeam.
> [Veeam] Check for failures in the restore process

- plugins/user-authenticators/ldap/src/main/java/org/apache/cloudstack/api/command/LinkAccountToLdapCmd.java
- plugins/user-authenticators/ldap/src/main/java/org/apache/cloudstack/ldap/LdapManagerImpl.java
- test/integration/component/test_ldap.py
- test/integration/plugins/ldap/test_ldap.py
This PR implements #3677 
Fixes: #3677
> Accept a role ID on linking an account to LDAP

- server/src/main/java/org/apache/cloudstack/cluster/ClusterDrsServiceImpl.java
- server/src/test/java/org/apache/cloudstack/cluster/ClusterDrsServiceImplTest.java
Fixes https://github.com/apache/cloudstack/issues/8629
This PR ensures that during a DRS run, the destination host is part of the same cluster for which migration is being run.
> DRS: Ensure the destination host is part of the same cluster

- server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
- ui/src/views/compute/DeployVM.vue
- ui/src/views/compute/wizard/TemplateIsoRadioGroup.vue
This PR makes changes to honour listall param for list templates api and also adds the listall parameter to deployVM in the UI.
> Honour listall param for list templates api

- engine/schema/src/main/java/com/cloud/storage/dao/SnapshotDetailsDao.java
- engine/schema/src/main/java/com/cloud/storage/dao/SnapshotDetailsDaoImpl.java
- engine/storage/volume/src/main/java/org/apache/cloudstack/storage/volume/VolumeServiceImpl.java
- plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/datastore/api/StorPoolSnapshotDef.java
- plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/datastore/driver/StorPoolPrimaryDataStoreDriver.java
- plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/datastore/driver/StorPoolStatsCollector.java
- plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/datastore/util/StorPoolUtil.java
- plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/motion/StorPoolDataMotionStrategy.java
- plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/snapshot/StorPoolConfigurationManager.java
- plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/snapshot/StorPoolSnapshotStrategy.java
Sometimes the users delete the volumes by mistake. This enhancement provides a solution to backup the volume before it's deleted. The user will be able to see the snapshot in CloudStack UI/CLI and create only a volume from it.
A task will check (by default every 5mins) if the snapshots are deleted from StorPool
Global settings to enable the delay delete option:
`storpool.delete.after.interval` - The interval (in seconds) after the StorPool snapshot will be deleted `storpool.list.snapshots.delete.after.interval` - The interval (in seconds) to fetch the StorPool snapshots with deleteAfter flag
This doesn't support encrypted volumes or the option to create a template from the snapshot. Only to restore the volume via the `createVolume` from the snapshot API call 
Minor fix when deleting …
> Temporarily backup StorPool volume before expunge

- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
This PR ensures that the resource counts are not decremented twice for a running VM while unmanaging.
Currently, the code does the same operation for a non-stopped VM twice. This could lead to resource count discrepancy for an account or domain.
Before fix:
- Create an account
- Deploy a VM for that account
- Observe the account limits and count
- Unmanage the VM
- Again observe the account limits and count. There will be some negative values for VM, CPU and memory as the resource counts have been decremented twice
```
(localcloud) 🐱 > list virtualmachines account=ACSuser
{
"count": 1,
{
"account": "ACSUser",
"created": "2024-06-12T12:48:59+0000",
"details": {
"cpuOvercommitRatio": "2.0",
"dataDiskController": …
```
> server: fix resource count updated unmanage vm

- plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/CitrixResourceBase.java
- plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/wrapper/xenbase/CitrixStopCommandWrapper.java
Fixes #7902
This PR allows attaching a regular ISO to a VM when it already has the config drive ISO attached.
Config-drive ISO is now attached with the SR name-label `<VM-NAME>-CONFIGDRIVE-ISO`. While regular ISOs continue to attach with SR name-label `<VM-NAME>-ISO`. VM which already have the configdrive ISO attached before this fix will return an appropriate error and will need to be stopped-start.
- Deploy a network with configdrive for userdata service
- Deploy a VM for the network
- Try attaching an ISO to the VM
```
(localcloud) 🐱 > list networks id=9aa54302-2812-426e-bddb-654df195360b 
{
"count": 1,
"network": [
{
"acltype": "Account",
"broadcastdomaintype": "Vlan",
"broadcasturi": "vlan://2158",
"canusefordeploy": true,
"created": "2024-06-11T07:03:14+0000", …
```
> xenserver: attach regular iso with configdrive

- api/src/main/java/org/apache/cloudstack/api/command/user/loadbalancer/AssignToLoadBalancerRuleCmd.java
changed vmidipmap[0].ip to vmidipmap[0].vmip
This PR
the AssignToLoadBalancerRule has vmidipmap[0].vmip as input but in the description mentioned vmidipmap[0].ip incrrectly.
> Fix AssignToLoadBalancerRule input param

- engine/schema/src/main/java/com/cloud/storage/dao/VolumeStatsDao.java
- engine/schema/src/main/java/com/cloud/storage/dao/VolumeStatsDaoImpl.java
- server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
- server/src/main/java/com/cloud/server/StatsCollector.java
This PR changes `vm.stats.remove.batch.size` configuration parameter to `delete.batch.query.size` to make it more generic.
Changes also allow deletion of `volume_stats` in batches using the `delete.batch.query.size` global setting.
For context, please check the conversation in PR: https://github.com/apache/cloudstack/pull/8740
> Change vm.stats.remove.batch.size to delete.batch.query.size & allow delete of volume_stats in batches

- server/src/main/java/com/cloud/network/router/VirtualNetworkApplianceManagerImpl.java
- server/src/main/java/com/cloud/network/router/VpcVirtualNetworkApplianceManagerImpl.java
After re-creating a VR from a domain VPC, ACS will not apply static nat, port forward and load balancer rules to IPs that are not associated to the account that owns the VPC.
An adjustment was made to make sure that these rules are applied for all IPs when performing the following procedures:
* VR restart
* VPC restart
* VPC restart with cleanup
* recreate VR when health-check fails
* recreate VR on failover
In a local lab, I performed the procedures listed in the description and verified that after applying the changes, the IPs owned by accounts different than the VPC owner were having their rules applied accordingly.
> server: apply rules when VR of Domain VPC is recreated

- server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
- ui/src/views/compute/DeployVM.vue
Reverts https://github.com/apache/cloudstack/pull/9064/ . Also reverts the changes done in #9300. And UI changes from this PR https://github.com/apache/cloudstack/pull/9196.
adding listall=true with templatefilter=self is returning templates with account system as well.
```
(mycloud) __ > list templates templatefilter=self filter=name,account
(mycloud) __ > list templates templatefilter=self filter=name,account listall=true 
{
"count": 1,
"template": [
{
"account": "system",
"name": "SystemVM Template (KVM)"
}
]
}
```
> Revert listAll behaviour for templates & iso

- api/src/main/java/com/cloud/vm/NicProfile.java
- engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
- server/src/main/java/com/cloud/network/guru/GuestNetworkGuru.java
Fixes: #7907
This PR fixes the issue where two VMs can be assigned the same IP if they are created at the same time.
`NetworkOrchestrator.allocateNic()` calls `guru.alocate()` which returns a free IP address.
`NetworkOrchestrator.allocateNic()` then calls `_nicDao.persists()`
But `guru.allocate()` can return same IPs to two VMs if the first VM hasn't persisted the nic to the DB yet.
Doing the whole thing in a transaction might be costly.
So the fix is to check if the IP returned by guru.allocate is already assigned just before persisting the NicVO in a transaction.
Check will be done only for cases where Ipv4 allocation might race. 
Wasn't possible to reproduce the actual race, but I tested by manually setting values with debugger and verifying that the code does what it is supposed to.
> Fix for race when automatically assigning IP to Vms

- server/src/main/java/com/cloud/network/NetworkServiceImpl.java
This PR attempts to optimize database queries during listNetworks API call. It should fix pagination-related issues as well while querying desired networks from the database. Only in the following cases, it may query all networks:
- API param `canusefordeploy` is passed as true
- Any service specified with the `supportedservices` API parameter
> server: refactor listNetworks api database retrievals

- ui/src/components/view/InfoCard.vue
When a VM has been created using an ISO, its infocard will label the ISO as `Template`. Additionally, any ISO attached to it will be labeled as `ISO`. This behaviour may cause confusion, causing users to believe the installation ISO is a template, or the attached ISO was the installation media.
To solve this, the label of the installation media has been edited to be either `Template` or `ISO` depending on its format and the label of the attached ISO has been modified to `Attached ISO`.
<details><summary>Before</summary>
</details>
<details><summary>After</summary>
</details>
> Differentiate between instalation ISO and attached ISO

- server/src/main/java/com/cloud/network/IpAddressManagerImpl.java
- server/src/main/java/com/cloud/network/NetworkModelImpl.java
- server/src/main/java/com/cloud/network/firewall/FirewallManagerImpl.java
- server/src/main/java/com/cloud/network/lb/LoadBalancingRulesManagerImpl.java
- server/src/main/java/com/cloud/network/rules/RulesManagerImpl.java
- server/src/main/java/com/cloud/network/vpn/RemoteAccessVpnManagerImpl.java
When executing many operations simultaneously with a public IP, some inconsistencies are being implemented in the environment, such as the duplicate public IP (Fixes: #8967).
For this reason, this PR adds a lock to most APIs that manipulate a public IP, preventing inconsistencies that may occur due to race conditions.
All tests were done following the same steps but using different APIs that create rules for the IP (`createLoadBalancerRule`, `createFirewallRule`, `createPortForwardingRule`, `createIpForwardingRule`):
1. Associate a public IP with a network;
2. Create a rule with one of the APIs;
3. Disassociate the IP (before) and create a rule again (after) at the same time.
To test the `createRemoteAccessVpn` API, I created a firewall rule in step 2 and called the …
> Handle public IP race conditions

- ui/src/views/storage/CreateVolume.vue
This PR allows selecting a target account (or project) during volume creation through the UI, using #8919's `OwnershipSelection`.
**Environment with one domain (`dom`), besides `root`, and a domain admin and an user accounts in both `root` and `dom`, as well as the Root Admin. Every account created one project each.**
Table lists all options shown in UI, when logged as each of the accounts:
(User accounts did not show the selection fields Owner type, Domain and Account/Project. Neither did any of the projects.)
| Logged in as  | Listed domains | Listed accounts | Listed projects |
| ------------- | ------------- | ------------- | ------------- |
| ROOT Admin (`admin`) | - ROOT<br>- ROOT/dom  | - admin, dadm, usr<br>- dom-adm, dom-usr | - admin-proj, dadm-proj, usr-proj<br>- dom-adm-proj, …
> [UI] Add option to select owner of volume when creating it

- plugins/storage/volume/linstor/src/main/java/org/apache/cloudstack/storage/datastore/util/LinstorUtil.java
This PR fixes a race condition with multiple Linstor primary storages and different controller IP's.
The client.setBasePath() would overwrite the Linstor controller IP/host for all current client users. This is basically a race condition that triggered as soon as you had configured 2 different primary storages with different Linstor controllers.
Basic operations on a Linstor cluster with 2 different linstor controllers.
> linstor: do not use the same static ApiClient for all calls

- engine/storage/volume/src/main/java/org/apache/cloudstack/storage/datastore/lifecycle/BasePrimaryDataStoreLifeCycleImpl.java
- plugins/database/quota/src/test/java/org/apache/cloudstack/api/response/QuotaResponseBuilderImplTest.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtCheckConvertInstanceCommandWrapper.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtPrepareStorageClientCommandWrapper.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtUnprepareStorageClientCommandWrapper.java
- plugins/storage/volume/adaptive/src/main/java/org/apache/cloudstack/storage/datastore/lifecycle/AdaptiveDataStoreLifeCycleImpl.java
- plugins/storage/volume/cloudbyte/src/main/java/org/apache/cloudstack/storage/datastore/lifecycle/ElastistorPrimaryDataStoreLifeCycle.java
- plugins/storage/volume/datera/src/main/java/org/apache/cloudstack/storage/datastore/lifecycle/DateraPrimaryDataStoreLifeCycle.java
- plugins/storage/volume/default/src/main/java/org/apache/cloudstack/storage/datastore/lifecycle/CloudStackPrimaryDataStoreLifeCycleImpl.java
- plugins/storage/volume/linstor/src/main/java/org/apache/cloudstack/storage/datastore/lifecycle/LinstorPrimaryDataStoreLifeCycleImpl.java
- plugins/storage/volume/nexenta/src/main/java/org/apache/cloudstack/storage/datastore/lifecylce/NexentaPrimaryDataStoreLifeCycle.java
- plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/lifecycle/ScaleIOPrimaryDataStoreLifeCycle.java
- plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/manager/ScaleIOSDCManagerImpl.java
- plugins/storage/volume/solidfire/src/main/java/org/apache/cloudstack/storage/datastore/lifecycle/SolidFirePrimaryDataStoreLifeCycle.java
- plugins/storage/volume/solidfire/src/main/java/org/apache/cloudstack/storage/datastore/lifecycle/SolidFireSharedPrimaryDataStoreLifeCycle.java
- plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/datastore/lifecycle/StorPoolPrimaryDataStoreLifeCycle.java
This PR fixes build errors on main branch
> Fixup main build errors

- test/integration/smoke/test_primary_storage_scope.py
This PR fixes the smoke failure in test_primary_storage_scope.py when run with XenServer.
#9315 
```
[SF] Trillian test result (tid-10688)
Environment: xenserver-71 (x2), Advanced Networking with Mgmt server 7
Total time taken: 41254 seconds
Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr9315-t10688-xenserver-71.zip
Smoke tests completed. 131 look OK, 1 have errors, 0 did not run
Only failed and skipped tests results shown below:
Test	Result	Time (s)	Test File
test_01_primary_storage_scope_change	Error	0.07	test_primary_storage_scope.py
```
Zone wide storage pools are not supported with Xenserver so storage pool creation was failing during setup, and not cleaning up the created cluster.
This causes cluster create to fail if the test is retried.
> test_primary_storage_scope.py should only run with kvm, vmware and simulator

- ui/src/views/infra/AddPrimaryStorage.vue
url param wasn't set if protocol Linstor is selected.
This was introduced with this PR https://github.com/apache/cloudstack/pull/9138
Adding Linstor primary storage through UI
> linstor-ui: Fix add primary storage if Linstor protocol selected

- plugins/storage/volume/linstor/src/main/java/org/apache/cloudstack/storage/datastore/driver/LinstorPrimaryDataStoreDriverImpl.java
If Linstor resource creation failed before `volume.setPath()` was called/stored, path will be null
and cleanup attempt for that resource from CloudStack will fail (because there is no `cs-null` resource).
This PR now fallback to the volume.uuid if path wasn't set yet.
Partially fixes an issue from #9321 
Tested deleting volumes on a fresh Linstor/CloudStack cluster.
> linstor: deleteAsync fallback to volume UUID if path not set yet

- ui/src/views/network/CreateIsolatedNetworkForm.vue
This PR prevents listing domains for normal users
Before fix:
After fix:
> UI: create network form constantly tries to list domains - which is not permitted for normal users

- plugins/user-authenticators/saml2/src/main/java/org/apache/cloudstack/saml/SAML2AuthManager.java
This improves upon #9219, to make the signature checks mandatory by default but allows for users to relax the setting if they really must.
> saml: make default signature check mandatory

- server/src/main/java/com/cloud/capacity/CapacityManagerImpl.java
This PR fixes NPE issue,  addresses test_hostha_kvm_host_fencing failure.
Noticed exception in log with VM details - "details":{"cpuOvercommitRatio":"2.0"} =>
```
2024-07-08 14:46:33,364 DEBUG [c.c.c.ClusterManagerImpl] (AgentConnectTaskPool-143:ctx-6c029670) (logid:a438af23) Forwarding [{"com.cloud.agent.api.ChangeAgentCommand":{"agentId":1,"event":"AgentDisconnected","contextMap":{},"wait":0,"bypassHostMaintenance":false}}] to 32987747976021
2024-07-08 14:46:33,364 DEBUG [c.c.c.ClusterManagerImpl] (Cluster-Worker-1:ctx-f6bca1ba) (logid:017b7b93) Cluster PDU 32986087031685 -> 32987747976021. agent: 1, pdu seq: 28532, pdu ack seq: 0, json: [{"com.cloud.agent.api.ChangeAgentCommand":{"agentId":1,"event":"AgentDisconnected","contextMap":{},"wait":0,"bypassHostMaintenance":false}}] …
```
> NPE fix, addresses test_hostha_kvm_host_fencing failure

- ui/src/views/network/CreateIsolatedNetworkForm.vue
This PR fixes the CreateIsolatedNetworkForm.vue in main/4.20 branch.
Due to PR #8919 , the PR #9348 should be ignored in main/4.20 branch.
> UI: fix CreateIsolatedNetworkForm.vue

- .github/linters/.flake8
- python/lib/cloud_utils.py
- python/lib/cloudutils/syscfg.py
- python/lib/cloudutils/utilities.py
- systemvm/debian/root/monitorServices.py
- test/integration/component/maint/testpath_vMotion_vmware.py
- test/integration/component/test_interop_xd_ccp.py
- test/integration/component/test_rootvolume_resize.py
- test/integration/smoke/test_kubernetes_clusters.py
- test/integration/smoke/test_privategw_acl.py
- test/integration/smoke/test_privategw_acl_ovs_gre.py
- tools/marvin/marvin/cloudstackException.py
- tools/marvin/marvin/dbConnection.py
- tools/marvin/marvin/lib/ncc.py
E271 Multiple spaces after keyword.
There should be only one space after a keyword.
https://www.flake8rules.com/rules/E271.html
This PR cleans up and standardizes the Python code.
Ran locally:
> pre-commit: enable Python flake8 rule `E271`

- pom.xml
- tools/appliance/systemvmtemplate/scripts/configure_systemvm_services.sh
- tools/appliance/systemvmtemplate/template.json
New systemvmtemplate for 4.19.1 due to openssh CVE and other improvements in Debian bullseye (11).
Template and build log uploaded here - http://download.cloudstack.org/systemvm/4.19/
> systemvmtemplate: bump new systemvmtemplate 4.19.1

- engine/storage/datamotion/src/main/java/org/apache/cloudstack/storage/motion/StorageSystemDataMotionStrategy.java
This PR fixes an issue with storage volume migrations when a storage pool (source or destination) has ScopeType.HOST set.  Prior to this PR, the code in StorageSystemDataMotionStrategy selected any host in the cluster if the source storage pool did not have a cluster ID, or a host in the cluster if it did.  This effectively breaks ScopeType.HOST copies except when the selection resulted in the specific host the other storage pool resides on.
Performed copies between a local KVM storage pool and a FiberChannelAdapter storage pool.
> Copy on pool host when storage pool has ScopeType.HOST

- ui/src/components/view/InfoCard.vue
- ui/src/views/compute/DeployVM.vue
The VM deployment wizard only shows one of the disk offerings that will be used to create the VM's volumes, which corresponds to the data disk if using a template, and the root disk if using a ISO. The disk offering that will be used to create the root disk is not shown when deploying through a template. This confuses users, since the wizard does not explicitly show what offering will be used for each disk. Furthermore, the instance summary often presents an incorrect value for the size of the disks.
This PR makes some changes in the deployment wizard in order to explicitly show what offerings will be used for the root and data disks, and to display their correct size. 
I created one disk offering:
1. Name and description: Associated. Custom disk size: false. Disk size (in GB): 10.
And …
> Improvements on information about disks size and offering in VM deployment wizard's InfoCard

- ui/src/views/compute/MigrateVMStorage.vue
When an operator selects the migration mode in the instance migration pop-up, the corresponding radio button does not get checked. This PR fixes this issue. 
<details>
<summary>
Before the changes
</summary>
</details>
<details>
<summary>
After applying these changes
</summary>
</details>
1. I created a stopped instance and accessed its page.
2. I opened the migration pop-up and verified that the first option was selected by default.
3. I clicked on the second option and verified that its radio button got selected.
4. I clicked on the first option and verified that its radio button got selected.
> Fix radio buttons in instance migration pop-up

- server/src/main/java/com/cloud/storage/StorageManagerImpl.java
This PR ignores non-managed pools for storage pool access preparation.
Fixes #9371
> Ignore non-managed pools for storage pool access preparation

- engine/schema/src/main/java/com/cloud/usage/dao/UsageDaoImpl.java
Executing `removeRawUsageRecords` command results in Management server becoming unavailable and random failure of subsequent requests. This PR fixes the issue by switching back to CLOUD_DB after the records have been removed from the database.
Execute `cmk removeRawUsageRecords interval=1000`. Requests to the management server will start failing after that.
> Fix: Switch back to CLOUD_DB after purging usage records

- api/src/main/java/org/apache/cloudstack/api/command/user/firewall/CreateFirewallRuleCmd.java
- api/src/main/java/org/apache/cloudstack/api/command/user/network/CreateNetworkACLCmd.java
- api/src/main/java/org/apache/cloudstack/api/command/user/vm/StartVMCmd.java
- api/src/main/java/org/apache/cloudstack/api/command/user/volume/ResizeVolumeCmd.java
- plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterResourceModifierActionWorker.java
- server/src/main/java/com/cloud/network/vpc/NetworkACLServiceImpl.java
This PR aims to refactor the class `KubernetesClusterResourceModifierActionWorker`. The main goal is to improve the adherence to object-oriented programming principles, specifically encapsulation. In this class, there were a couple of methods that were using reflection, such as `Field.setAccessible()`, to modify object fields directly, which can be seen as a violation of encapsulation, one of the fundamental principles of object-oriented programming. This issue was fixed by creating setters in the respective classes belonging to the objects where this behavior occurred.
I ran all the tests related to the class `KubernetesClusterResourceModifierActionWorker` and certified none of them were broken.
> Refactor KubernetesClusterResourceModifierActionWorker

- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtOvsFetchInterfaceCommandWrapperTest.java
This PR fixes LibvirtOvsFetchInterfaceCommandWrapperTest (test fails in mac) - skip it if no interfaces with eth and wl.
Ran unit test in local (mac).
**Before change:**
```
[INFO] Running com.cloud.hypervisor.kvm.resource.wrapper.LibvirtOvsFetchInterfaceCommandWrapperTest
[ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.108 s <<< FAILURE! - in com.cloud.hypervisor.kvm.resource.wrapper.LibvirtOvsFetchInterfaceCommandWrapperTest
[ERROR] testGetInterfaceDetailsValidValid(com.cloud.hypervisor.kvm.resource.wrapper.LibvirtOvsFetchInterfaceCommandWrapperTest)  Time elapsed: 0.096 s  <<< ERROR!
[ERROR] Errors: 
[ERROR]   LibvirtOvsFetchInterfaceCommandWrapperTest.testGetInterfaceDetailsValidValid » NullPointer
[ERROR] Tests run: 455, …
```
> LibvirtOvsFetchInterfaceCommandWrapperTest fix (test fails in mac) - skip it if no interfaces with eth and wl

- plugins/user-authenticators/saml2/src/main/java/org/apache/cloudstack/api/command/SAML2LoginAPIAuthenticatorCmd.java
- plugins/user-authenticators/saml2/src/main/java/org/apache/cloudstack/saml/SAML2AuthManager.java
- plugins/user-authenticators/saml2/src/main/java/org/apache/cloudstack/saml/SAML2AuthManagerImpl.java
- plugins/user-authenticators/saml2/src/test/java/org/apache/cloudstack/api/command/SAML2LoginAPIAuthenticatorCmdTest.java
This improves the description of a saml signature checking global setting, and purges the SAML token upon handling the first SAML response.
The community QA server is applied with these changes to test the SAML SSO with the `rick` user https://qa.cloudstack.cloud/simulator
> saml: purge token after first response and improve setting description

- engine/schema/src/main/java/com/cloud/vm/dao/VMInstanceDaoImpl.java
Fixes #9331
Only those VMs should be considered as network VMs which have a NIC entry that is not marked removed.
> engine-schema,cks: fix finding non-removed network vms

- ui/src/config/section/compute.js
This PR fixes backup offering buttons for instances in data view
Image before the changes for a instance with a backup offering
Image after the changes for a instance with a backup offering
Assign a backup offering to an instance and check the buttons in the data view.
> UI: Fix backup offering buttons for instances in data view

- ui/src/config/section/infra/hosts.js
On the hosts details page, icons with distinct functionalities currently share the same image. This PR aims to enhance the user experience by proposing a change to differentiate the icons Start rolling maintenance and Configure out-of-band management on the hosts details page.
Hosts page before changes
Hosts page after changes
After the UI change, the icon for Start rolling maintenance has been updated and is now reflected in the UI as well
> Icon changed for control-outlined

- api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
- api/src/main/java/org/apache/cloudstack/api/response/SnapshotResponse.java
- engine/schema/src/main/resources/META-INF/db/views/cloud.snapshot_view.sql
- server/src/main/java/com/cloud/api/ApiResponseHelper.java
- server/src/main/java/com/cloud/api/query/dao/SnapshotJoinDaoImpl.java
- server/src/main/java/com/cloud/api/query/vo/SnapshotJoinVO.java
- ui/src/components/view/InfoCard.vue
- ui/src/components/view/ListView.vue
- ui/src/utils/links.js
The volume snapshots and the snapshot details page show a link to the snapshotted volume. However, if the volume has been removed, it is not possible to access its page, resulting in a 404 when a user clicks the link.
This PR adds a validation in the UI in order to avoid showing this link when the volume has been removed.
<details>
<summary>
When the volume exists, a link is shown.
</summary>
</details>
<details>
<summary>
If the volume has been removed, the link does not get shown.
</summary>
</details>
1. I created a volume snapshot and verified that the volume snapshots and the snapshot details page showed a link to the volume;
2. I removed the volume and verified that the link was not shown anymore.
> Fix link to removed volumes being shown in info card and list view

- engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
When attempting to start a VM, if an error occurs, the exception displayed to users is the same as what is being logged, which can expose information about the environment.
This PR addresses this issue by keeping the current message to be sent to the logs and adding a new one for the exception shown to users.
<details>
<summary>Exception before the proposed changes</summary>
</details>
<details>
<summary>Exception after the proposed changes</summary>
</details>
Using a stopped VM, I changed the _Compute Offering_ to a offering with `Host Tags` incompatible with every host in my environment in order to force the exception, then I tried to start the VM. An exception was thrown as shown in the screenshots above.
I also checked the logs in both cases and the only changes was log level and the …
> Change exception when orchestrating VM start

- ui/public/locales/en.json
- ui/src/components/view/stats/ResourceStatsInfo.vue
The metrics for VMs and VM disks in CloudStack depend on the hypervisor plugin used for each hypervisor. The behavior can vary across different hypervisors. For VMware, metrics are retrieved as average value for the time interval defined in the global configuration - vmware.stats.time.window.
Related documentation PR: https://github.com/apache/cloudstack-documentation/pull/413
> ui: vm metrics note about behaviour across hypervisors

- api/src/main/java/org/apache/cloudstack/api/response/ClusterResponse.java
- api/src/main/java/org/apache/cloudstack/api/response/HostResponse.java
- api/src/main/java/org/apache/cloudstack/api/response/ManagementServerResponse.java
- api/src/main/java/org/apache/cloudstack/api/response/StoragePoolResponse.java
- api/src/main/java/org/apache/cloudstack/api/response/UserVmResponse.java
- api/src/main/java/org/apache/cloudstack/api/response/VolumeResponse.java
- api/src/main/java/org/apache/cloudstack/api/response/ZoneResponse.java
- server/src/main/java/com/cloud/api/ApiResponseHelper.java
- server/src/main/java/com/cloud/api/query/dao/DataCenterJoinDaoImpl.java
- server/src/main/java/com/cloud/api/query/dao/HostJoinDaoImpl.java
This PR fixes https://github.com/apache/cloudstack/issues/9379
Fix missing keys in `listZonesMetrics`.
We use `BeanUtils.copyProperties` to copy the properties of `ZoneResponse` to `ZoneMetricsResponse`. Fields with missing getters are skipped from the response because of this.
https://github.com/apache/cloudstack/blob/56c661c1dff741ee9f7d741a7751f96504a16388/plugins/metrics/src/main/java/org/apache/cloudstack/metrics/MetricsServiceImpl.java#L930
> API: Fix missing keys in listZonesMetrics response

- test/integration/smoke/test_purge_expunged_vms.py
Failures were seen for during purging of expunged resources via bacground task during different test runs. This PR tries to make sure b/g task execution is not skipped after MS restrat in a multi-MS environment. It also updates expunged.resources.purge.interval to allow running task again in 60s.
https://github.com/apache/cloudstack/pull/9316#issuecomment-2240965788
https://github.com/apache/cloudstack/pull/9316#issuecomment-2241001342
> test: improve purge expunged resources b/g task testcase

- debian/rules
- packaging/centos8/cloud.spec
This uses the latest tag to find and use the latest Github tag from cloudstack-cloudmonkey repo, and use that to bundle the binary CLI in packages.
> packaging: bundle latest cmk x86 build with deb and rpm packages

- engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/snapshot/DefaultSnapshotStrategy.java
Using XenServer as the hypervisor, when deleting a snapshot that has a parent, that parent will also get erased on storage, causing data loss. This behavior was introduced with #7873, where the list of snapshot states that can be deleted was changed to add `BackedUp` snapshots. 
This PR changes the states list back to the original list, and swaps the while loop for a do while loop to account for the changes in #7873.
Fixes #9446 
1. Created a VM
2. Took a volume snapshot (S1).
3. Accessed the VM and wrote some data with: `dd if=/dev/zero of=test bs=1M count=1000`
4. Used `sync` to make sure data is written to disk
5. Took a second volume snapshot (S2).
6. Deleted the last volume snapshot (S2).
Before the change, S1 would be mistakenly deleted from storage as well, and an inconsistent …
> Fix snapshot chain being deleted on XenServer

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/LibvirtStorageAdaptor.java
If the libvirt mount point is still busy and can't be unmounted right now, it was waited 5 seconds and an plain unmount was tried, without cleaning up the libvirt storagepool.
This kept libvirt thinking the storagepool
is active and mounted (which it wasn't).
Now after the plain unmount call, also
the libvirt storagepool will be destroyed.
Linstor cluster with snapshots backuped to secondary storage(NFS).
> libvirtstorageadaptor: better handle failed libvirt storagepool destroy

- api/src/main/java/org/apache/cloudstack/api/ApiArgValidator.java
- api/src/main/java/org/apache/cloudstack/api/command/user/vm/DeployVMCmd.java
- api/src/main/java/org/apache/cloudstack/api/command/user/vm/UpdateVMCmd.java
- engine/schema/src/main/java/com/cloud/upgrade/dao/Upgrade41910to42000.java
- engine/schema/src/main/resources/META-INF/db/schema-41910to42000.sql
- framework/db/src/main/java/com/cloud/utils/db/GenericDaoBase.java
- server/src/main/java/com/cloud/api/dispatch/ParamProcessWorker.java
- server/src/test/java/com/cloud/api/dispatch/ParamProcessWorkerTest.java
- test/integration/smoke/test_resource_names.py
This PR allows the below resource name / display text with unicode / emoji chars, and improves SQL exception msgs (doesn't include any sql stmts). Also, adds a validator for VM host/domain name.
- User VM
- Volume
- Volume Snapshot
- VM Snapshot
- Template
- ISO
- Disk Offering
- Compute Offering
- Network Offering
- VPC Offering
- Backup Offering
- Instance Group
- Affinity Group
- SSH Key
- Userdata
- Guest Network
- VPC
- Kubernetes Cluster
- Autoscale VM Group
- Account
- User
- Project
- Annotation
Manually, tested the name / display names for these resources.
test_resource_names.py
[Checks support for emoji in the resource name for vm, volume, service & disk offering, template, iso, account(first/lastname)]
```
Test for deploy virtual machine ... === TestName: test_01_deploy_vm | …
```
> Support user resource name / displaytext with emoji, unicode chars, and some sql exception msg improvements

- api/src/main/java/org/apache/cloudstack/api/command/user/template/DeleteTemplateCmd.java
- server/src/main/java/com/cloud/template/HypervisorTemplateAdapter.java
Currently, ACS does not allow the deletion of system VM templates. However, it might be of interest to the operator to delete templates from older versions that are no longer in use.
A change was applied to remove the restriction on the deletion of system VM templates, allowing operators to delete such templates.
I applied the changes and successfully deleted old system VM templates
> Allow deletion of system VM templates

- api/src/main/java/org/apache/cloudstack/api/command/admin/storage/heuristics/RemoveSecondaryStorageSelectorCmd.java
This PR fixes the response of `removeSecondaryStorageSelector` for the API docs
- Bug fix (non-breaking change which fixes an issue)
- Minor
- Trivial
> fix removeSecondaryStorageSelector response for docs

- plugins/storage/volume/linstor/src/main/java/com/cloud/hypervisor/kvm/storage/LinstorStorageAdaptor.java
This will set better qemu-img convert options, depending on Linstors used storage pools.
Tell qemu-img that we don't want to use a write cache (we are a block device) and also specify that we have zeroed devices in most cases.
Copy new templates to primary storage on a Linstor cluster.
> linstor: Improve copyPhysicalDisk performance

- ui/public/locales/en.json
- ui/src/components/view/SearchView.vue
- ui/src/config/section/storage.js
This PR fixes: https://github.com/apache/cloudstack/issues/9130
Added toggle button for filtering only encrypted volumes:
When set to true, passes 'isencrypted' parameter to the listVolumes API call:
When set to false, returns all non-encrypted volumes:
> UI: Add filter to list encrypted volumes

- ui/src/config/section/network.js
This PR fixes the issue #9413 
The original fix was to allow user to do actions (update, restart, delete) on the network only if the user owns the network and if user role is of Admin or domain admin.
If the network belongs to a project then the actions can be allowed as it belongs to only to that project.
Before fix with a network in project
After fix with a network in project
1. Create an account of type user
2. Login with that user
3. Create a project and switch to that project
4. Create a new network in that project
5. Before fix user won't be able to do any actions on that network, after fix it is allowed.
> Fix to allow actions on the network if it belongs to a project

- api/src/main/java/com/cloud/agent/api/to/VirtualMachineTO.java
- engine/api/src/main/java/com/cloud/vm/VirtualMachineManager.java
- engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
- engine/orchestration/src/test/java/com/cloud/vm/VirtualMachineManagerImplTest.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java
Fixes #9142
Doc PR: https://github.com/apache/cloudstack-documentation/pull/402
New global settings added to specify VM metadata wrt manufacturer and product:
- `vm.metadata.manufacturer`
- `vm.metadata.product`
> orchestration,hypervisor: allow custom manufacturer, product for vm metadata

- engine/api/src/main/java/org/apache/cloudstack/engine/orchestration/service/NetworkOrchestrationService.java
- engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
- engine/storage/configdrive/src/main/java/org/apache/cloudstack/storage/configdrive/ConfigDriveBuilder.java
- engine/storage/configdrive/src/main/java/org/apache/cloudstack/storage/configdrive/ConfigDriveUtils.java
- engine/storage/configdrive/src/test/java/org/apache/cloudstack/storage/configdrive/ConfigDriveBuilderTest.java
- engine/storage/configdrive/src/test/java/org/apache/cloudstack/storage/configdrive/ConfigDriveUtilsTest.java
- server/src/main/java/com/cloud/network/NetworkModelImpl.java
- server/src/main/java/com/cloud/network/element/ConfigDriveNetworkElement.java
- server/src/test/java/com/cloud/network/element/ConfigDriveNetworkElementTest.java
- server/src/test/java/com/cloud/vpc/MockNetworkManagerImpl.java
- test/integration/smoke/test_network.py
- tools/marvin/marvin/config/test_data.py
This PR fixes https://github.com/apache/cloudstack/issues/2872
PR adds support for Dhcp & Dns capabilities for ConfigDrive network element.
Docs PR: https://github.com/apache/cloudstack-documentation/pull/412
1. Create a network offering with DHCP, DNS & UserData provider with ConfigDrive
2. Create a network with the above offering
3. Launch an instance using a cloud init configured template.
4. Instance gets the assigned IP, DNS & Userdata.
While attaching secondary nics, interface is assigned an IP on boot only if the instance was started for the first time.
Updating of IPs & NICs after first boot doesn't reflect on the instance even after reboot.
> Add support for network data in Config Drive

- server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
After resizing a volume in the `Ready` state, the usage records of that volume are still considering the size prior to the resizing.
Changes were made so that Usage records are created according to the updated volume size.
1. Resize a volume in the `Ready` state;
2. Check the resized volume usage records in the `cloud_usage` table;
**Before the changes**: the usage records are still considering the old size.
**After the changes**: the usage records for the resized volume are being created with the correct size.
> Fix usage volume size after resizing

- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
This PR updates data disk controller (in VMware) same as the root disk controller type when it is not set in the VM detail. This is to ensure the disk controller is available for the data disks, as all the SCSI controllers are created with same controller type.
Fixes #9400 
Manually testing with Paravirtual controller (pvscsi) as the root disk controller.
**Before =>**
**After =>**
> [VMware] Update data disk controller same as the root disk controller type when it is not set in the VM detail

- plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java
- vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/VirtualMachineMO.java
This PR disconnects/detachs config drive ISO (if exists) on stop VM in VMware. This is required for support some VM operations involving export OVF, on stopped VMs.
Root cause: Export OVF fails as there is no config drive file, it is removed when VM is stopped.
Fixes #9453
Manually tested the start,stop,start VM operations and VM instance volume snapshots with config drive on VMware.
**Before =>**
**After =>**
```
2024-07-29T15:56:17,721 DEBUG [c.c.a.t.Request] (Work-Job-Executor-2:[ctx-bd90a732, job-217/job-218, ctx-bd64bbee]) (logid:fd80b170) Seq 1-234468655599976463: Executing:  { Cmd , MgmtId: 32989425697365, via: 1(10.0.34.85), Ver: v1, Flags: 100011, [{"com.cloud.agent.api.StopCommand":{"isProxy":"false","checkBeforeCleanup":"false","forceStop":"false","vlanToPersistenceMap":{"1727": …
```
> [VMware] Disconnect/Detach config drive ISO (if exists) on stop VM

- api/src/main/java/org/apache/cloudstack/api/command/user/account/AddUserToProjectCmd.java
- api/src/main/java/org/apache/cloudstack/api/command/user/account/DeleteUserFromProjectCmd.java
- server/src/main/java/com/cloud/event/ActionEventInterceptor.java
- server/src/main/java/com/cloud/event/ActionEventUtils.java
- server/src/main/java/com/cloud/projects/ProjectManagerImpl.java
This PR updates the project account (which is the resource owner id rather than the calling user account id) for all the events with project account owner, except for create project event.
Project events are not missed, but calling account is added to scheduled events and project account is added to started, completed events. So, some of the events for the operation are in Default view and others in project View, which is confusing. This PR keeps project account for all events with with project account except for create project event.
Fixes #9432 
Manually performed below operations and checked the events before & after fix.
(i) Create project
(ii) Add account to project
(iii) Add user to project from the account in step (ii) - will Fail
(iv) Add user to project from another account. …
> Update project account for all the events with project account owner, except for create project event

- api/src/main/java/org/apache/cloudstack/api/command/admin/account/DeleteAccountCmd.java
- server/src/main/java/com/cloud/user/AccountManagerImpl.java
- server/src/test/java/com/cloud/user/AccountManagerImplTest.java
ACS allows users to delete their own account by calling the `deleteAccount` API via CLI. Fixing this behavior has been previously suggested in this [comment](https://github.com/apache/cloudstack/pull/7242#issuecomment-1433260909). Furthermore, there's already a feature to prevent a user from deleting their own account via UI; however, slower environments create a small window where it's possible for the user to click the button before it's disabled, allowing deletion even through the UI (see this [comment](https://github.com/apache/cloudstack/pull/7242#issuecomment-1444300925)).
This pull request addresses this issue by adding a validation that checks the `UUID` of the caller's account and compares it with the `UUID` of the account they are trying to delete. If they are the same, an …
> Fix `deleteAccount` API to prevent deletion of the caller

- api/src/main/java/org/apache/cloudstack/api/command/user/vm/GetVMPasswordCmd.java
- api/src/test/java/org/apache/cloudstack/api/command/user/vm/CreateVMScheduleCmdTest.java
- api/src/test/java/org/apache/cloudstack/api/command/user/vm/DeleteVMScheduleCmdTest.java
- api/src/test/java/org/apache/cloudstack/api/command/user/vm/ListVMScheduleCmdTest.java
- api/src/test/java/org/apache/cloudstack/api/command/user/vm/UpdateVMScheduleCmdTest.java
- plugins/hypervisors/kvm/src/main/java/org/apache/cloudstack/kvm/ha/KVMHAProvider.java
- plugins/hypervisors/simulator/src/main/java/org/apache/cloudstack/ha/SimulatorHAProvider.java
- plugins/integrations/kubernetes-service/src/main/java/org/apache/cloudstack/api/command/user/kubernetes/cluster/CreateKubernetesClusterCmd.java
- plugins/network-elements/opendaylight/src/main/java/org/apache/cloudstack/network/opendaylight/agent/OpenDaylightControllerResource.java
- plugins/network-elements/tungsten/src/main/java/org/apache/cloudstack/network/tungsten/service/TungstenServiceImpl.java
- plugins/storage/volume/cloudbyte/src/main/java/org/apache/cloudstack/storage/datastore/util/ElastistorUtil.java
- server/src/main/java/com/cloud/network/NetworkModelImpl.java
- server/src/main/java/com/cloud/network/NetworkServiceImpl.java
- server/src/main/java/com/cloud/network/lb/LoadBalancingRulesManagerImpl.java
- vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/HypervisorHostHelper.java
This PR updates invalid parameter/value  error with proper exception, to com.cloud.exception.InvalidParameterValueException (from java.security.InvalidParameterException).
Fixes #9436
> Updated invalid parameter/value error with proper exception

- framework/security/src/main/java/org/apache/cloudstack/framework/security/keystore/KeystoreManager.java
- framework/security/src/main/java/org/apache/cloudstack/framework/security/keystore/KeystoreManagerImpl.java
- server/src/main/java/com/cloud/server/ManagementServerImpl.java
This PR addresses the issue #9004 which is related to the validation of certificate during the upload operation for the start and end lines of the certificate.
In this PR we have added that validation and improved the error message reporting
> Add certificate validation to check headers

- tools/appliance/systemvmtemplate/scripts/install_systemvm_packages.sh
This flips conditional checks to check specifically for x86_64/amd64 to install dependencies in systemvm.
> systemvm: have flags to check x86_64 to install specifics for amd64 arch

- engine/userdata/cloud-init/src/main/java/org/apache/cloudstack/userdata/CloudInitUserDataProvider.java
- engine/userdata/cloud-init/src/test/java/org/apache/cloudstack/userdata/CloudInitUserDataProviderTest.java
- ui/src/utils/plugins.js
This PR fixes the userdata header restrictions on the APPEND operation:
- Allow the second userdata not having a header
- In case the second userdata does not have a header, it uses the first userdata header as its format type
Fixes: #7918
> Fix userdata append header restrictions

- ui/src/components/view/ListView.vue
- ui/src/config/section/network.js
> ui: show guest networks for guest vlans list

- plugins/storage/volume/linstor/CHANGELOG.md
- plugins/storage/volume/linstor/src/main/java/com/cloud/hypervisor/kvm/storage/LinstorStorageAdaptor.java
- plugins/storage/volume/linstor/src/main/java/org/apache/cloudstack/storage/datastore/util/LinstorUtil.java
This changes the way how the linstor plugin sets the correct options to allow live-migration.
Before we set `allow-two-primaries` option on all resources and also don't enable protocol C for that brief time.
Now we explicitly set `allow-two-primaries` and protocol C on the specific resource connection used and
after the live migration is done those options get removed.
This allows live migration to work if you have set protocol A between 2 datacenters (e.g. DR site).
Live migration in a Linstor cluster with protocol C and A configured between nodes.
> linstor: set/unset allow-two-primaries and protocol on rc level

- ui/src/components/view/SearchView.vue
This PR adds the `details: min` parameter to `listDomains`  API call. Since they are used only for ids and names, more details are unnecessary and `listDomains` ends up taking a long time to execute when many domains exist.
In a test environment with 5000 domains, running `time cmk listDomains`  yielded `cmk listDomains 0,31s user 0,11s system 1% cpu 31,200 total`, but `time cmk listDomains details=min` yielded `cmk listDomains details=min 0,14s user 0,04s system 7% cpu 2,521 total`.
Before:
After:
I set up an environment with 5000 domains and unlimited page size. 
I then checked the Network tab on the browser before and after the changes (see Screenshots).
Searching itself worked normally.
> Add minimum details parameter to Search View's listDomains

- server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
Fixes #8645
When a local storage volume is being attached to a stopped VM, volume migration is only needed when it is not present on the last host as the current host ID will be null in the database.
Tested attaching a volume with a localstorage offering to a stopped VM,
```
(localcloud) 🐱 > list serviceofferings id=45770553-e18f-4dfd-ba16-b0106af20dd2 
{
"count": 1,
{
"cacheMode": "none",
"created": "2024-08-23T07:24:45+0000",
"displaytext": "SharedStorage Instance",
"encryptroot": false,
"id": "45770553-e18f-4dfd-ba16-b0106af20dd2",
"iscustomized": false, …
```
> server: fix stopped vm volume migration check on local volume attach

- server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
- services/secondary-storage/controller/src/main/java/org/apache/cloudstack/secondarystorage/SecondaryStorageManagerImpl.java
- ui/src/views/setting/ConfigurationValue.vue
- utils/src/main/java/com/cloud/utils/net/NetUtils.java
- utils/src/test/java/com/cloud/utils/net/NetUtilsTest.java
This PR fixes #9530 by adding validation on update of `secstorage.allowed.internal.sites` to allow only valid CIDRs. This PR also enables logging of WARN messages for the existing wrong configurations.
> Add validation for secstorage.allowed.internal.sites

- engine/storage/image/src/main/java/org/apache/cloudstack/storage/image/TemplateServiceImpl.java
when add a new image store, some templates/ISOs are copied, but some are not.
```
2024-06-10T12:24:50,711 INFO  [o.a.c.s.i.TemplateServiceImpl] (qtp776484396-20:[ctx-eb090c22, ctx-5fa5579c]) (logid:7a783000) Template Sync did not find 211-2-d536fb03-5f89-3e77-8dea-323315bcbfab on image store 3, may request download based on available hypervisor types
...
2024-06-10T12:24:51,043 INFO  [o.a.c.s.i.TemplateServiceImpl] (qtp776484396-20:[ctx-eb090c22, ctx-5fa5579c]) (logid:7a783000) Skip sync downloading private template 211-2-d536fb03-5f89-3e77-8dea-323315bcbfab to a new image store
```
This PR fixes the issue that some template/iso are not copied to new image store
> storage: fix private templates are not copied to new image store

- server/src/main/java/org/apache/cloudstack/snapshot/SnapshotHelper.java
This PR addresses an issue as part of #8946 
The issue I've observed is not while taking the snapshot but while creating the template from the snapshot (stack trace also refers the same).
I could not reproduce the original issue of failed snapshot showing as backedup state rather than error (it might have already fixed after 4.17.2), but I saw another serious issue.
The issue is whenever a snapshot is used to create a template or volume and if there is failure in backing up the snapshot to the secondary store and as part of handling that failure MS is deleting the snapshot in primary storage itself.
These changes are introduced as part of the PR https://github.com/apache/cloudstack/pull/5297
1. Create a snapshot of a volume (set snapshot.backup.to.secondary = False)
2. Create a template …
> Fix snapshot deletion on template creation failure

- pom.xml
This updates the external java-linstor api library dependency.
0.5.1 had a bug while retrieving the bestErrorMessage for an apicall answer.
Tested with a Linstor cluster
> linstor: update java-linstor dependency to 0.5.2

- engine/orchestration/src/test/java/com/cloud/vm/VirtualMachineManagerImplTest.java
- engine/schema/src/main/java/com/cloud/dc/ClusterDetailsDaoImpl.java
- engine/schema/src/main/java/com/cloud/dc/dao/DataCenterDetailsDaoImpl.java
- engine/schema/src/main/java/com/cloud/domain/dao/DomainDetailsDaoImpl.java
- engine/schema/src/main/java/com/cloud/storage/dao/StoragePoolDetailsDaoImpl.java
- engine/schema/src/main/java/com/cloud/user/AccountDetailsDaoImpl.java
- engine/schema/src/main/java/org/apache/cloudstack/storage/datastore/db/ImageStoreDetailsDaoImpl.java
- framework/config/src/main/java/org/apache/cloudstack/framework/config/ConfigDepot.java
- framework/config/src/main/java/org/apache/cloudstack/framework/config/ConfigKey.java
- framework/config/src/main/java/org/apache/cloudstack/framework/config/ScopedConfigStorage.java
- framework/config/src/main/java/org/apache/cloudstack/framework/config/impl/ConfigDepotImpl.java
- framework/config/src/test/java/org/apache/cloudstack/framework/config/impl/ConfigDepotImplTest.java
- pom.xml
- server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
- server/src/test/java/com/cloud/vm/FirstFitPlannerTest.java
- ui/public/locales/en.json
- ui/src/components/view/ListView.vue
- ui/src/components/view/SettingsTab.vue
- ui/src/views/setting/ConfigurationValue.vue
Added caching for ConfigKey value retrievals based on the Caffeine in-memory caching library.
https://github.com/ben-manes/caffeine
Currently, expire time for a cache is 30s and each update of the config key invalidates the cache. On any update or reset of the configuration, the cache automatically invalidates for it.
This useful when there are concurrent operations as it will prevent multiple DB queries within a short span of time.
> framework/config,server: configkey caching

- api/src/main/java/org/apache/cloudstack/storage/browser/DataStoreObjectResponse.java
- server/src/main/java/org/apache/cloudstack/storage/browser/StorageBrowserImpl.java
- ui/src/views/infra/StorageBrowser.vue
This PR adds the resource name for templates, volumes and snapshots on the `listStoragePoolObjects` API response and displays them UI under the Associated Resource column on the Storage Pool Browser section
Before the fix:
After the fix:
Tested for Primary and Secondary Storage pools
> Display associated resource name on storage pools objects

- api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
- api/src/main/java/org/apache/cloudstack/api/command/user/config/ListCapabilitiesCmd.java
- api/src/main/java/org/apache/cloudstack/api/response/CapabilitiesResponse.java
- server/src/main/java/com/cloud/server/ManagementServerImpl.java
- server/src/main/java/com/cloud/vm/UserVmManager.java
- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
- ui/src/config/section/compute.js
> Global setting to allow/disallow users to force stop a vm

- api/src/main/java/com/cloud/event/EventTypes.java
- api/src/main/java/com/cloud/storage/StorageService.java
- api/src/main/java/org/apache/cloudstack/api/command/admin/storage/UpdateStoragePoolCmd.java
- server/src/main/java/com/cloud/storage/StorageManagerImpl.java
This PR addresses the issue #8494 
Fixes the issue of missing Enable, Disable action events when trying to do that using updateStoragePool. Also added new Action event UPDATE.PS to the actual update storage pool event.
> Added update, enable, disable events to the updateStoragePool API

- agent/conf/log4j-cloud.xml.in
- client/conf/log4j-cloud.xml.in
- plugins/hypervisors/hyperv/conf/log4j-cloud.xml.in
- plugins/user-authenticators/ldap/src/test/resources/log4j.xml
- server/conf/log4j-cloud.xml.in
- usage/conf/log4j-cloud_usage.xml.in
- utils/src/test/resources/log4j.xml
Before #7131, the logs' timestamp was in the `2024-04-02 22:04:28,617`, with the upgrade to log4j2, the logs' timestamp was changed to the `2024-04-02T21:55:12,724` format. This PR changes the timestamp back to the previous format.
> Go back to previous timestamp on logging

- server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
- server/src/test/java/com/cloud/storage/VolumeApiServiceImplTest.java
This PR fixes root disk resize - not allowed when service offering has root disk size, only allowed through service offering change.
Fixes #9380
Manually tested the root resize with service offering having root disk size set.
> Fix root disk resize (not allowed) when service offering has root disk size, only allowed through service offering change

- engine/schema/pom.xml
- engine/schema/templateConfig.sh
This handles new systemvmtemplate renames which now includes arch detail in the file name and URL. By default, it continues to use x86_64 for automatic systemvmtemplate seeding and upgrades only.
The systemvmtemplate filenames now have arch flag/substring - https://download.cloudstack.org/systemvm/4.20/ due to which this PR is necessary.
> engine/schema: update url links to match new systemvmtemplate names

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMPhysicalDisk.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/LibvirtStorageAdaptor.java
- plugins/storage/volume/linstor/src/main/java/com/cloud/hypervisor/kvm/storage/LinstorStorageAdaptor.java
- plugins/storage/volume/linstor/src/main/java/org/apache/cloudstack/storage/datastore/driver/LinstorPrimaryDataStoreDriverImpl.java
- plugins/storage/volume/linstor/src/main/java/org/apache/cloudstack/storage/datastore/util/LinstorUtil.java
- plugins/storage/volume/linstor/src/main/java/org/apache/cloudstack/storage/snapshot/LinstorVMSnapshotStrategy.java
This PR fixes migrate primary storage for Linstor primary storage.
Always use RAW as copy sourceFormat for Linstor devices, as all images are stored as RAW on Linstor, but we have to pretend to use qcow2 to be able to use qcow2 as snapshot format. Also use .getPath() for resource names, as they are altered after a primary storage migration.
Fixes: #9176 and #9522
Linstor Cluster with migrating VM volumes between Linstor and NFS primary storage
Migrated from Linstor to NFS and back to NFS, than tried various volume actions like snaphots and revert.
> Linstor: Fix migrate primary storage

- ui/src/config/section/compute.js
When non-root-admin users try to start multiple virtual machines, the form does not provide options to cancel or confirm the operation.
This PR fixes this bug.
---
Fixes #9651
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
- With a non-root-admin user, I selected the option to start multiple virtual machines, and verified that I was able to confirm and cancel the operation.
- With a root admin user, I selected the option to start multiple virtual machines, and verified that the `Consider Last Host` field was rendered correctly.
> UI: Fix starting VMs through group action by non-root-admin users

- api/src/main/java/com/cloud/storage/Volume.java
- api/src/main/java/com/cloud/storage/VolumeApiService.java
- api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
- api/src/main/java/org/apache/cloudstack/api/command/user/vm/UpdateVMCmd.java
- api/src/main/java/org/apache/cloudstack/api/command/user/volume/UpdateVolumeCmd.java
- api/src/main/java/org/apache/cloudstack/api/response/UserVmResponse.java
- api/src/main/java/org/apache/cloudstack/api/response/VolumeResponse.java
- engine/schema/src/main/java/com/cloud/storage/VolumeVO.java
- engine/schema/src/main/java/com/cloud/vm/VMInstanceVO.java
- engine/schema/src/main/java/com/cloud/vm/dao/UserVmDao.java
- engine/schema/src/main/java/com/cloud/vm/dao/UserVmDaoImpl.java
- engine/schema/src/main/resources/META-INF/db/schema-41910to42000.sql
- engine/schema/src/main/resources/META-INF/db/views/cloud.user_vm_view.sql
- engine/schema/src/main/resources/META-INF/db/views/cloud.volume_view.sql
- engine/storage/volume/src/main/java/org/apache/cloudstack/storage/volume/VolumeObject.java
- server/src/main/java/com/cloud/api/query/dao/UserVmJoinDaoImpl.java
- server/src/main/java/com/cloud/api/query/dao/VolumeJoinDaoImpl.java
- server/src/main/java/com/cloud/api/query/vo/UserVmJoinVO.java
- server/src/main/java/com/cloud/api/query/vo/VolumeJoinVO.java
- server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
- server/src/main/java/com/cloud/vm/UserVmManager.java
- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
- server/src/test/java/com/cloud/vm/UserVmManagerImplTest.java
- test/integration/smoke/test_vm_life_cycle.py
- test/integration/smoke/test_volumes.py
- tools/marvin/marvin/lib/base.py
- ui/public/locales/en.json
- ui/src/config/section/compute.js
- ui/src/config/section/storage.js
- ui/src/views/compute/EditVM.vue
Docs PR: https://github.com/apache/cloudstack-documentation/pull/433
This PR allows adding deletion protection for a VM & volume. If the flag is enabled for a VM or a volume, the deletion of that resource fails. This feature helps user prevent deletion of critical resources by mistake.
If the resource is part of an Autoscaling group, CKS or any other plugin/feature, deletion protection flag is ignored. i.e. Deletion protection works only while deletion of resource via `destroyVirtualMachine` & `deleteVolume` command.
As of now, delete protection can be enabled only after the resource has been created/deployed. i.e. only updateVirtualMachine & updateVolume commands can set the deleteprotection for a resource.
> Feature: Allow adding delete protection for VMs & volumes

- server/src/main/java/com/cloud/network/NetworkServiceImpl.java
PR #9184 attempted to optimize the `listNetworks` API by converting the multiple queries that were performed into a single one. This was done by building multiple search criterias for the individual queries, OR-adding them to an intermediary search criteria, and AND-adding the intermediary to a final one. However, this did not work as intended, because the code does not carry the joins' conditions when adding a search criteria into another one.
This PR fixes the issue, making the final query work as intended by #9184. This was done by explicitly adding the join parameters to each query's WHERE clause, which will then be included in the intermediary search criteria and in the final query. I also cleaned up the related code.
My environment had the following domains, accounts, projects and …
> Restore listNetworks behavior & clean up the code

- server/src/main/java/com/cloud/network/vpc/NetworkACLServiceImpl.java
- ui/src/views/network/AclListRulesTab.vue
> Allow more generic searches of ACLs

- server/src/main/java/com/cloud/capacity/CapacityManagerImpl.java
CapacityManagementImpl.updateCapacityForHost(..) use VM update time in capacity calculation.
VM update time is nullable in DB and can cause NullPointerException if record in vm_instance has defined last_host_id and undefined update_time.
Added logic to check whether update_time is null and use created time instead (which is not null).
> Host capacity calculation: use VM creation time if update time is null.

- server/src/main/java/com/cloud/network/NetworkServiceImpl.java
- ui/src/views/network/UpdateNetwork.vue
> allow domain suffix update in shared networks

- server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
- server/src/main/java/com/cloud/event/dao/EventJoinDaoImpl.java
Need to check array empty, because  `com.cloud.utils.db.GenericDaoBase#searchAndCount(SearchCriteria, Filter, boolean)` makes two calls: first to get objects and second to get count.
List events has start date filter, there is highly possible cause where no objects loaded and next millisecond new event added and finally we ended up with count = 1 and no ids.
Finally user gets back response exception:
```
com.mysql.cj.jdbc.ClientPreparedStatement: SELECT event_view.id, event_view.uuid, event_view.type, event_view.state, 
event_view.description, event_view.created, event_view.user_id, event_view.user_name, event_view.level, 
event_view.start_id, event_view.start_uuid, event_view.parameters, event_view.account_id, event_view.account_uuid, 
event_view.account_name, event_view.account_type, …
```
> List Events returns intermittent SQL exception.Fixed listEvents intermittent exception.

- systemvm/agent/noVNC/app/ui.js
When click "Clear" button in the clipboard dialog on vm console, the input area is cleared but the page still focuses on the "Clear" button. 
It is inconvenient for end users as normally users want to re-input after clearing the input. 
This PR moves the focus on the input area after clearing.
> CPVM: move focus on input area after clearing clipboard

- tools/apidoc/gen_toc.py
This PR modifies the categories of the commands API Documentation.
<details><summary>Details</summary>
<p>
|Command|Category before changes|Category after changes|
|---|---|---|
|addAccountToProject|Account|Project|
|addBaremetalHost|Host|Baremetal|
|addGloboDnsHost|Host|Network|
|addImageStoreS3|S3|Image Store|
|addNetscalerLoadBalancer|Load Balancer|Netscaler|
|addNetworkDevice|Network|Network Device|
|addObjectStoragePool|Storage Pool|Object Store|
|addPaloAltoFirewall|Firewall|Palo Alto|
|addSecondaryStorage|Host|Image Store|
|addStratosphereSsp| Stratosphere SSP|Misc Network Service Providers|
|addSwift|Swift|Image Store|
|addTrafficMonitor|Usage|Network|
|addTrafficType|Usage|Network|
|addTungstenFabricNetworkGatewayToLogicalRouter|Router|Tungsten|
|addUserToProject|User|Project| …
> Fix toc generation for api docs

- engine/schema/src/main/resources/META-INF/db/schema-41910to42000.sql
This PR changes two column renames in `schema-41910to42000.sql`. Using MariaDB version `10.3.38-MariaDB`, some lines are not applying the expected changes to the column names in the tables. This issue results in errors during the version transition process.
The modifications made to the schema-41910to42000.sql ensure that changes to the tables are applied correctly. With these fixes, the transition between versions should proceed successfully, without errors.
I made the mentioned changes, and the transition between versions went as expected.
> Update of the schema 41910to42000.sql for compatibility with MariaDB version 10.3.38.

- ui/src/style/objects/form.scss
This PR fixes a pre-commit failure for end of files.
Seen here:
https://github.com/apache/cloudstack/pull/9681
https://github.com/apache/cloudstack/actions/runs/10891026685/job/30240163645
> pre-commit run --all-files; fix end of file

- ui/src/config/section/compute.js
This PR addresses https://github.com/apache/cloudstack/issues/4654#issuecomment-1889174291 TBD
in qa
> list VMs by displayname instead of name

- ui/src/views/network/VpcTiersTab.vue
This PR fixes the VPC network offerings listing on VPC tiers creation
Fixes: #8023 
Create VPC offering with Lb as supported service and VpcVirtualRouter as provider
Create VPC with the selected VPC offering
VPC -> Add new network tier -> verify available network offerings
> UI: Fix VPC network offerings listing on VPC tier creation

- ui/src/components/page/GlobalHeader.vue
This PR shows project menu on mobile devices
> UI: enable project menu on mobile devices

- systemvm/debian/opt/cloud/bin/passwd_server_ip.py
This PR fixes errors appeared in /var/log/daemon.log below
```
Sep 13 12:36:58 systemvm passwd_server_ip.py[2154]: ----------------------------------------
Sep 13 12:36:58 systemvm passwd_server_ip.py[2154]: Exception occurred during processing of request from ('192.168.20.8', 51108)
Sep 13 12:36:58 systemvm passwd_server_ip.py[2154]: Traceback (most recent call last):
Sep 13 12:36:58 systemvm passwd_server_ip.py[2154]:   File "/usr/lib/python3.11/socketserver.py", line 691, in process_request_thread
Sep 13 12:36:58 systemvm passwd_server_ip.py[2154]:     self.finish_request(request, client_address)
Sep 13 12:36:58 systemvm passwd_server_ip.py[2154]:   File "/usr/lib/python3.11/socketserver.py", line 361, in finish_request
Sep 13 12:36:58 systemvm passwd_server_ip.py[2154]: …
```
> VR: fix password server exception when no password is found

- plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java
- plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageProcessor.java
- vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/HypervisorHostHelper.java
- vmware-base/src/main/java/com/cloud/hypervisor/vmware/util/VmwareHelper.java
When both `rootDiskController` and `dataDiskController` details are set to SCSI controllers, the VM creation and start processes prioritize creating and using the controllers specified by `rootDiskController` for all volumes. However, the volume attachment process does not consider this and always tries to attach volumes using the controllers specified for the data disks (even if a root disk is being attached). 
This way, in a scenario where `rootDiskController` is set to `pvscsi` and `dataDiskController` is set to `lsilogic` (one example, as this problem also happens for other combinations) we ignore the `dataDiskController` setting defined by the operator and choose to use only PVSCSI controllers for both the root and data disks on VM creation/start. Then, when a user tries to attach a …
> [VMware] Make disk controller selection on volume attachment consistent with VM creation and start

- vmware-base/src/main/java/com/cloud/hypervisor/vmware/util/VmwareHelper.java
This PR fixes a build error introduced during the last merge with 4.19. Where a few loggers were left with their old names. 
I ran the build script with: mvn clean install -T 4 -DskipTests -Dnoredist
> Fix main build errors

- ui/src/views/iam/DomainActionForm.vue
This PR fixes [!9623](https://github.com/apache/cloudstack/issues/9623)
I tested this PR by typing inside the networkdomain field in the Add domain form and then clearing it, which ended up working as expected after the proposed changes.
> Fixed Unable to create a domain when networkdomain is mentioned and cleared

- client/pom.xml
- plugins/hypervisors/kvm/pom.xml
- plugins/hypervisors/kvm/src/main/java/org/apache/cloudstack/network/tungsten/agent/api/SetupTfRouteCommand.java
- plugins/hypervisors/kvm/src/main/java/org/apache/cloudstack/network/tungsten/agent/api/SetupTungstenVRouterCommand.java
- plugins/hypervisors/kvm/src/main/java/org/apache/cloudstack/network/tungsten/agent/api/UpdateTungstenLoadbalancerSslCommand.java
- plugins/hypervisors/kvm/src/main/java/org/apache/cloudstack/network/tungsten/agent/api/UpdateTungstenLoadbalancerStatsCommand.java
- plugins/network-elements/tungsten/pom.xml
- plugins/pom.xml
- server/pom.xml
- server/src/main/java/com/cloud/network/NetworkServiceImpl.java
This PR moves tungsten plugin from normal packaging to noredist packaging
it also removes the maven repository for juniper-tungsten-api
whoever want to build tungsten, please install the jar manually. please refer to https://github.com/shapeblue/cloudstack-nonoss/
./install-non-oss.sh
> build/packaging: build tungsten plugin only if noredist is passed

- ui/src/components/header/ProjectMenu.vue
This calls listProjects with details=min in the global header menu.
Stole idea/diff from @weizhouapache 's https://github.com/apache/cloudstack/issues/9679#issuecomment-2358596154 :)
Fixes #9679
> ui: load project list with minimum details

- engine/schema/src/main/java/com/cloud/upgrade/SystemVmTemplateRegistration.java
- server/src/main/java/com/cloud/storage/StorageManagerImpl.java
- server/src/main/java/org/apache/cloudstack/diagnostics/DiagnosticsServiceImpl.java
> server: fix nfs version option during mounts

- plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/manager/ScaleIOSDCManagerImpl.java
Added configuration key `powerflex.connect.on.demand`. When set to `false`, then logic in ScaleIO plugin to disconnect Host from the storage pool when there are no volumes and connect Host to storage pool when new volume created will not be used (https://github.com/apache/cloudstack/pull/9268).
The reason for that - plugin's connect/disconnect logic stops and starts `scini` service. If Host connected to multiple storage pools, then it won't be disconnected from unused pools, there will be all or none. Also we observed `scini` stability issue - after multiple start/stop it is not always starting back properly.
For now we would like to have flag to enable/disable this feature.
In addition, as part of the PR, added SQL to update `resource_reservation` table with two new columns. Right now we …
> PowerFlex on demand disable config key

- plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java
> CKS: fix creation on shared network if HA is enabled

- test/integration/smoke/test_usage.py
This PR fixes the test failure with test_usage.py
the site `people.apache.org` has been deprecated.
> Fix ISO url in test_usage.py

- framework/cluster/src/main/java/com/cloud/cluster/ClusterManagerImpl.java
- framework/spring/lifecycle/src/main/java/org/apache/cloudstack/spring/lifecycle/CloudStackExtendedLifeCycle.java
- framework/spring/lifecycle/src/main/java/org/apache/cloudstack/spring/lifecycle/CloudStackExtendedLifeCycleStart.java
- framework/spring/module/src/main/java/org/apache/cloudstack/spring/module/factory/CloudStackSpringContext.java
- server/src/main/java/org/apache/cloudstack/resource/ResourceCleanupServiceImpl.java
This PR shutdowns expunged resources cleanup executor when obj is available (when config expunged.resources.purge.enabled is true), allows other components to configure/start/stop on error, and adds some logs in component lifecycle classes.
Noticed this exception with custom logs, the remaining components fails to stop after this exception.
```
WARN  [o.a.c.s.l.CloudStackExtendedLifeCycleStart] (SpringContextShutdownHook:null) (logid:) Error on stopping beans - null
at org.apache.cloudstack.resource.ResourceCleanupServiceImpl.stop(ResourceCleanupServiceImpl.java:584)
at org.apache.cloudstack.spring.lifecycle.CloudStackExtendedLifeCycle$2.with(CloudStackExtendedLifeCycle.java:105)
at org.apache.cloudstack.spring.lifecycle.CloudStackExtendedLifeCycle.with(Cloud …
```
> Shutdown expunged resources cleanup executor properly, and allow other components to configure/start/stop on error

- debian/control
This PR fixes the cloudstack-management package installation issue on debian12
on Debian12, the package name is `mysql-connector-python-py3`
while the package name is `python3-mysql.connector` on ubuntu 24.04
```
Sorting... Done
Full Text Search... Done
Sorting... Done
Full Text Search... Done
mysql-connector-python-py3/unknown,now 8.4.0-1debian12 amd64 [installed]
MySQL database driver written in pure Python 3
mysql-connector-python-py3-dbgsym/unknown 8.4.0-1debian12 amd64
debug symbols for mysql-connector-python-py3
```
as a workaround, please install the package for ubuntu 24.04
```
wget http://launchpadlibrarian.net/717081070/python3-mysql.connector_8.0.15-4_all.deb
DEBIAN_FRONTEND=noninteractive apt install -y /tmp/python3-mysql.connector_8.0.15-4_all.deb
```
> debian12: update debian/control

- server/src/main/java/com/cloud/network/vpn/Site2SiteVpnManagerImpl.java
- ui/src/views/network/VpcTab.vue
This PR adds a validation when creating a VPN connection in a VPC to make sure the VPN gateway exists.
Fixes: #7250
> cleanup validations for VPN connection creation

- ui/src/views/compute/EditVM.vue
Currently in ACS, when editing a VM, the field userdata will be present even if the VM's network does not support the feature. This PR fixes this issue by not showing the field if the VM does not offer userdata.
I tested this by verifying if the userdata field would still show up in the Edit VM View when editing VMs whose networks did not offer userdata, and it worked as expected. I've also tested cases in which a VM could have more than one network, and for these cases it will consider the default network and disregard the other networks.
> Hide UserData field from the EditVM view for VMs that do not offer it

- framework/db/src/main/java/com/cloud/utils/db/GenericDaoBase.java
- server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
This PR fixes: https://github.com/apache/cloudstack/issues/9486
List VMs without any filter:
Listing VMs with a specific IP:
Listing VMs with a part of an IP used as filter:
Listing VMs with an IP that doesn't match:
> Filter list VMs by IP address

- api/src/main/java/org/apache/cloudstack/api/command/user/backup/ListBackupScheduleCmd.java
This PR fixes the issue with listing backup schedules caused by https://github.com/apache/cloudstack/pull/9451
> Fix Listing backup schedules

- ui/tests/unit/components/view/ActionButton.spec.js
- ui/tests/unit/views/compute/MigrateWizard.spec.js
This PR fixes the UI unit test failures
> UI: fix unit tests

- plugins/user-authenticators/saml2/src/main/java/org/apache/cloudstack/saml/SAML2AuthManager.java
- plugins/user-authenticators/saml2/src/main/java/org/apache/cloudstack/saml/SAML2AuthManagerImpl.java
- plugins/user-authenticators/saml2/src/main/java/org/apache/cloudstack/saml/SAMLUtils.java
> make saml auth request option `forceauthn` configurable

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java
- plugins/storage/volume/linstor/CHANGELOG.md
This PR enables qemu discard support for Linstor storage pools
Tested in a Linstor cluster
> linstor: enable discard for Linstor storage pools

- engine/schema/src/main/java/com/cloud/storage/dao/VolumeStatsDaoImpl.java
- engine/schema/src/main/java/com/cloud/vm/dao/VmStatsDaoImpl.java
- framework/db/src/main/java/com/cloud/utils/db/GenericDao.java
- framework/db/src/main/java/com/cloud/utils/db/GenericDaoBase.java
- server/src/test/java/com/cloud/user/MockUsageEventDao.java
Prior to this change
```
2024-10-17T10:32:55,455 DEBUG [c.c.v.d.VmStatsDaoImpl] (StatsCollector-5:[ctx-ec4b3698]) (logid:708dd27c) Starting to remove all vm_stats rows older than [Wed Oct 16 22:32:55 UTC 2024].
2024-10-17T10:32:55,456 INFO  [c.c.v.d.VmStatsDaoImpl] (StatsCollector-5:[ctx-ec4b3698]) (logid:708dd27c) Removed a total of [0] vm_stats rows older than [Wed Oct 16 22:32:55 UTC 2024].
```
With this change
```
2024-10-17T10:41:33,315 DEBUG [c.c.v.d.VmStatsDaoImpl] (StatsCollector-5:[ctx-dd8d7e09]) (logid:338dd659) Starting to remove all vm_stats rows older than [Wed Oct 16 22:41:33 UTC 2024].
2024-10-17T10:43:03,184 INFO  [c.c.v.d.VmStatsDaoImpl] (StatsCollector-5:[ctx-dd8d7e09]) (logid:338dd659) Removed a total of [1661329] vm_stats rows older than [Wed Oct 16 22:41:33 UTC 2024]. …
```
> server: fix vm_stats records are not removed if batchsize is 0

- ui/src/views/infra/UpdatePrimaryStorage.vue
Fixes the bug described in #9806. The primary storage update form is not showing the existing values of the following fields: tags, is tag a rule, capacity bytes, IOPS total and NFS mount options.
I accessed a NFS primary storage's details page, enabled maintenance mode and edited its name, tags, tag as JS rule, capacity bytes, IOPS total and NFS mount options fields. Then, I opened the edit form again and verified that the updated values were shown.
> Fix primary storage update form not showing existing values

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java
- plugins/storage/volume/linstor/CHANGELOG.md
qemu has a bug versions prior 7.0 with discard enabled and using the IDE bus.
It would crash the qemu process and kill the virtual machine, this is most noticeable on installing a windows guest from the Windows ISO installer.
bug link:
https://bugzilla.redhat.com/show_bug.cgi?id=2029980
Tested in a local Linstor cluster and added unittests to check the combinations.
> linstor/kvm: Workaround a qemu bug and IDE bus discard enabled.

- plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/datastore/util/StorPoolUtil.java
- plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/snapshot/StorPoolSnapshotStrategy.java
This PR fixes the deletion of StorPool snapshots. When a snapshot is deleted, it isn't marked in the DB as such, so when listing the snapshots, the already deleted ones show up.
Manual and smoke tests
> StorPool: fix of delete snapshot

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtOvsFetchInterfaceCommandWrapper.java
This PR fixes the issue below when create a ovs network
```
2024-10-29 16:02:45,089 WARN  [resource.wrapper.LibvirtOvsFetchInterfaceCommandWrapper] (agentRequest-Handler-2:null) (logid:e716722e) Network interface: ''cloudbr1'' not found
```
This is a regression of a previous security release
see "framework/cluster: improve cluster service, integration API server"
since we now use NetworkInterface.getByName to get network interface, we should NOT add single quotes before/after the label.
> kvm: fix ovs network creation issue

- utils/src/main/java/com/cloud/utils/HttpUtils.java
- utils/src/test/java/com/cloud/utils/HttpUtilsTest.java
This PR fixes #9848 
When enable.secure.session.cookie is set to true, use cannot login with error
```
2024-10-25T09:03:33,898 DEBUG [c.c.u.HttpUtils] (qtp384617262-21:[ctx-a3ee3670]) (logid:7c5bfd8d) jsessionidFromCookie = node017ygldpe44nub1frmqafsj0qmc18
2024-10-25T09:03:33,898 DEBUG [c.c.u.HttpUtils] (qtp384617262-21:[ctx-a3ee3670]) (logid:7c5bfd8d) session.getId() = node017ygldpe44nub1frmqafsj0qmc18
2024-10-25T09:03:33,898 ERROR [c.c.u.HttpUtils] (qtp384617262-21:[ctx-a3ee3670]) (logid:7c5bfd8d) JSESSIONID from cookie is invalid.
```
> utils: fix invalid JSESSIONID cookie in https setup

- ui/src/config/section/compute.js
- ui/src/views/compute/KubernetesServiceTab.vue
If a user does not have access to the `scaleKubernetesCluster` API and tries to list Kubernetes clusters through the UI, an error is thrown. Therefore, it is not possible to list and create Kubernetes clusters due to this error, even if the user has permission for such actions.
Since then, changes have been made so that this error no longer occurs and the user can list and manage Kubernetes clusters even if he doesn't have access to the `scaleKubernetesCluster` API.
I created an account from a custom admin role that has the `scaleKubernetesCluster` API as `DENY` and all other APIs as `ALLOW`. Then, I logged into this account and was able to perform some basic operations like creating, listing and deleting a Kubernetes cluster.
> Fix Kubernetes cluster view when user is unable to scale

- plugins/storage/volume/linstor/src/main/java/com/cloud/hypervisor/kvm/storage/LinstorStorageAdaptor.java
- plugins/storage/volume/linstor/src/main/java/org/apache/cloudstack/storage/datastore/util/LinstorUtil.java
In non-hyperconverged setups, diskless nodes don't have a connection to each other, so setting properties there had no effect. Now it is checked if a connection exists,
between the live migration nodes and if not,
it will set the allow-two-primaries on resource-definition level.
Linstor cluster with storage nodes (non hyperconverged) and a hyperconverged Linstor cluster.
> Linstor: fix live migrate on non-hyperconverged setups

- systemvm/debian/opt/cloud/bin/cs/CsFile.py
in some configuration files, the value can be set in multiple times and order matters. 
For example there are two haproxy configurations
```
listen 10_0_xx_yy-22
bind 10.0.xx.yy:22
balance roundrobin
listen 10_0_xx_yy-23
bind 10.0.xx.yy:23
balance source
```
```
listen 10_0_xx_yy-22
bind 10.0.xx.yy:22
balance source
listen 10_0_xx_yy-23
bind 10.0.xx.yy:23
balance roundrobin
```
without this change, they are considered as same configuration, which is obviously wrong.
> VR: fix wrong check when compare two configuration files

- ui/src/views/compute/StartVirtualMachine.vue
This PR fixes the bug presented in the issue #9668, where the `Start instance` dialog  in the UI does not respond to the `Ctrl+Enter` command.
I tested by using the `Ctrl+Enter` command when starting a VM in the instance list view and the VM details view. Worked as intended in both cases.
> Fix Ctrl+Enter command on `Start Instance` dialog

- engine/storage/image/src/main/java/org/apache/cloudstack/storage/image/TemplateServiceImpl.java
This reverts commit e06f80e899127abe45c10ff2d38420a770ceb076.
I have discussed with @NuxRo @rajujith @alexandremattioli  , it seems  it is expected that private template has only 1 copy on the secondary storages.
we all agreed that it should be improved as the template with 1 copy becomes unavailable if the secondary storage is removed. 
ideally there is a global setting to specify the minimum number of  copies on secondary storages.
> Revert "storage: fix private templates are not copied to new image store (#9206)"

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/IscsiAdmStorageAdaptor.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStoragePoolManager.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/LibvirtStorageAdaptor.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/ManagedNfsStorageAdaptor.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/MultipathSCSIAdapterBase.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/ScaleIOStorageAdaptor.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/StorageAdaptor.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/storage/LibvirtStorageAdaptorTest.java
- plugins/storage/volume/linstor/src/main/java/com/cloud/hypervisor/kvm/storage/LinstorStorageAdaptor.java
- plugins/storage/volume/storpool/src/main/java/com/cloud/hypervisor/kvm/storage/StorPoolStorageAdaptor.java
If a storage pool is used by e.g. 2 concurrent snapshot->template actions, if the first action finished it removed the netfs mount point for the other action.
Now the storage pools are usage ref-counted and will only deleted if there are no more users.
Fixes: #8899
Run several snapshot to template actions, that are executed on the same host.
> kvm: ref-count storage pool usage

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtStoragePoolDef.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/LibvirtStorageAdaptor.java
This PR fixes an unintended name change on an enum member for pooltype
Fixes: #9915
> enum name changed for logger update reverted

- ui/src/components/view/DetailSettings.vue
When manipulating VM and template settings, the UI provides a dropdown with the available setting names and values. However, if a user first adds a setting and then tries to add another, the dropdown only shows the previously added setting's name and value.
Furthermore, whenever the user types a character into the setting name input field, a Vue warning is thrown in the console, stating that an incorrect value type has been passed to the `options` prop of the `a-auto-complete` component.
Therefore, this PR improves VM and template settings filtering by always displaying the available setting names and their values, even when a setting has already been added. Besides that, the Vue warning has been properly fixed.
---
Fixes #8074
1. When adding the first setting of a VM/template, I verified …
> UI: Improve filtering of VM and template settings

- ui/src/views/auth/Login.vue
Currently, when all OAuth providers are disabled, the authentication page still displays the section divider below the login form.
This PR addresses this issue by ensuring the section divider is only rendered when at least one OAuth provider is enabled.
- Verified that when at least one OAuth provider is enabled, both the section divider and the OAuth provider sign-in options are rendered correctly.
- Verified that when all OAuth providers are disabled, the section divider is no longer displayed.
> UI: Hide section divider when all OAuth providers are disabled

- engine/schema/src/main/java/com/cloud/storage/VolumeVO.java
- engine/schema/src/main/resources/META-INF/db/schema-41900to41910.sql
- engine/storage/datamotion/src/main/java/org/apache/cloudstack/storage/motion/StorageSystemDataMotionStrategy.java
- engine/storage/volume/src/main/java/org/apache/cloudstack/storage/volume/VolumeServiceImpl.java
In ACS Once a volume is migrated, it duplicates its row in the database and labels the previous one as removed; however, there is no reference to the deleted row, making it so the operator is unable to track the previous volume effectively. This PR aims to change this by adding a new column to the table volumes called `last_id`.
This PR was tested by live migrating VM with storage and also by migrating a volume with the VM turned off; in both cases, the new column was populated accordingly.
> Add new column `last_id` to the table volumes

- ui/src/views/compute/CreateSSHKeyPair.vue
This PR aims to display the label hints in the `CreateSSHKeyPair` form, which are currently not shown, negatively impacting the user experience.
<summary>  Before </summary>
<summary>  After </summary>
The label hints were displayed in the form in question.
> Displaying info of the labels from form CreateSSHKeyPair

- engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/vmsnapshot/DefaultVMSnapshotStrategy.java
When attempting to revert a VM to a VM snapshot, the exception displayed to users can expose some information about the environment.
This PR addresses this issue by keeping the current message to be sent to the logs and adding a new one for the exception shown to users.	
I forced a `CloudRuntimeException` when reverting a VM to a VM snapshot and the new exception was thrown as expected. Then I checked that the current message was still being added to the logs.
> Remove information about the environment from exception when reverting VM snapshot

- ui/src/components/view/ListView.vue
This PR intends to enable the visualization of the amount of CPU/memory allocated in custom constrained compute offerings, which is currently not possible, thus improving the user experience.
<summary>  Before </summary>
<summary>  After </summary>
The CPU/memory ranges appeared in the offerings table under Compute Offerings.
> Added-cpu-core-and-memory-range-fot-type-offers-CustomConstrained

- framework/quota/src/main/java/org/apache/cloudstack/quota/QuotaManagerImpl.java
- server/src/main/java/com/cloud/deploy/DeploymentPlanningManagerImpl.java
Fixes some misformatted logs in the deployment & Quota balance calculation processes.
Before:
```
2024-11-05 12:40:32,643 INFO  [cloudstack.quota.QuotaManagerImpl_EnhancerByCloudStack_281d8029] (Usage-Job-1:[]) (logid:) Processing quota balance for account[{}] between [{}] and [{}].
```
After:
```
2024-11-05 12:40:38,903 INFO  [cloudstack.quota.QuotaManagerImpl_EnhancerByCloudStack_281d8029] (Usage-Job-1:[]) (logid:) Processing quota balance for account [{"accountName":"system","domainId":1,"id":1,"uuid":"60b8ca5a-28b2-11ef-a04e-6ac09c2b3d6b"}] between [2024-11-05T00:13:00.000+0000] and [2024-11-05T12:39:59.000+0000].
```
> Adjust misformatted logs

- engine/components-api/src/main/java/com/cloud/vm/snapshot/VMSnapshotManager.java
- server/src/main/java/com/cloud/configuration/Config.java
- server/src/main/java/com/cloud/vm/snapshot/VMSnapshotManagerImpl.java
- server/src/test/java/com/cloud/vm/snapshot/VMSnapshotManagerTest.java
Currently, the configuration `vmsnapshot.max` isn't dynamic, and it is necessary to restart the Management Server after changing the configuration's value.
This PR intends to change the `vmsnapshot.max` config to the new `ConfigKey` standard for dynamic configurations.
To validate the changes, I performed the following steps without restarting the Management Server:
1. Changed the `vmsnapshot.max` value to 2;
2. Tried to take 3 VM snapshots, but as expected, an exception was thrown on the 3rd snapshot;
3. Changed the `vmsnapshot.max` value to 3;
4. Tried to take the 3rd snapshot again, and it was created successfully;
5. Tried to take a 4th snapshot and got the same exception.
> Change `vmsnapshot.max` configuration to be dynamic

- ui/public/locales/en.json
- ui/src/views/network/NicsTab.vue
Checkbox to make a newly added Network the default one in the Instance's Network tab
This PR adds a checkbox into the Add Network dialogue to make the newly added network the default one in Instance's Network Tab. This will save users from performing an extra step to make the network the default one.
> UI: make a newly added Network the default one

- ui/src/components/view/SearchView.vue
- ui/src/config/section/offering.js
- ui/src/views/AutogenView.vue
Currently, the `listNetworkOfferings` API supports the `forvpc` and `guestiptype` parameters (see [API docs](https://cloudstack.apache.org/api/apidocs-4.19/apis/listNetworkOfferings.html)). The first is used to filter network offerings that can only be used for creating VPC tiers; the second allows filtering by guest network type (available options are: `Isolated`, `Shared` and `L2`).
This PR adds support to these parameters in the UI. The `forvpc` filter has been added as a normal filter (declared in the `filters` property of the network offerings section's object) and the `guestiptype` as a search filter (declared in the `searchFilters` property).
Furthermore, this PR also fixes a bug that caused duplicate options to appear in search filter lists.
---
Fixes #9924
- I checked that when …
> UI: Add UI support for `forvpc` and `guestiptype` parameters of the `listNetworkOfferings` API

- api/src/main/java/org/apache/cloudstack/api/command/user/volume/ResizeVolumeCmd.java
- engine/components-api/src/main/java/com/cloud/capacity/CapacityManager.java
- engine/components-api/src/main/java/com/cloud/storage/StorageManager.java
- server/src/main/java/com/cloud/capacity/CapacityManagerImpl.java
- server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
- server/src/main/java/com/cloud/storage/StorageManagerImpl.java
- server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
- server/src/test/java/com/cloud/storage/StorageManagerImplTest.java
- server/src/test/java/com/cloud/storage/VolumeApiServiceImplTest.java
- ui/src/views/storage/ResizeVolume.vue
Currently, when resize a volume, ACS checks if the current storage pool can accommodate the new size, and simply return true if pool has enough capacity, or false if there are not enough capacity.
This PR
- add global and zone setting volume.resize.allowed.beyond.allocation and pool.storage.allocated.resize.capacity.disablethreshold
- add API parameter automigrate to resizeVolume API.
when resize a volume
- check if the pool capacity (with new volume size) is above disable threshold `pool.storage.allocated.capacity.disablethreshold`
- if  pool capacity is below disable threshold, operation succeeds.
- if  pool capacity is above disable threshold
* if `volume.resize.allowed.beyond.allocation` is `false`, go to migration step
* if `volume.resize.allowed.beyond.allocation` is `true`, it will …
> Resize volume: add pool capacity disablethreshold for resize and allow volume auto migration

- ui/src/views/dashboard/VerifyTwoFa.vue
This PR fixes the password managers autofill functionality in the 2FA OTP code form.
It is caused by double `<form>` element. 
Fixes: #9510
The PR simply removes the outer empty `<form>` element, leaving the inner one intact.
**Steps to reproduce:**
1. Install 1password password manager and the browser extension.
2. Enable 2FA authentication for your Cloudstack user.
3. Save the OTP token for your user in 1password so it now provides OTP passwords.
4. Try to login to Cloudstack UI with 1password autofill. 
Expected behavior:
1password fills all 6 numbers of the OTP token into the input form.
Actual behavior:
1password only fills 3 numbers out of 6 into the input form.
Before:
https://github.com/user-attachments/assets/d5d81734-16a1-434a-b4ef-f71f225ef761
After: …
> fix: remove double <form> element from 2FA form

- ui/src/components/view/InfoCard.vue
This PR proposes adding a `tooltip` that displays the exact frequency (without rounding and described in MHz) of the `cpuspeed` and the `memory` value in MB to three decimal places on Hosts pages. Currently, the InfoCard component treats the CPU frequency to be displayed in GHz to two decimal places. The current way in which computing resources are displayed can mislead the end user.
<summary>  Before </summary>
<summary>  After </summary>
The tooltip with the exact frequency was displayed on the Hosts page.
> UI: Tooltip on the host information card to display the CPU speed in MHz and the memory value in MB (to 3 decimal places)

- ui/public/locales/en.json
- ui/src/views/network/NicsTab.vue
This PR backports #9708 to 4.20
> Backport #9708

- api/src/main/java/com/cloud/hypervisor/Hypervisor.java
- api/src/main/java/org/apache/cloudstack/api/command/user/template/RegisterTemplateCmd.java
- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
- server/src/test/java/com/cloud/vm/UserVmManagerImplTest.java
This PR adds support for functionality in hypervisor class. This solves 2 issues:
1. Allow configuring supported functionality of a hypervisor in Hypervisor class itself and remove custom logic of different hypervisors in the code. For now, we are only functionalities. Rest can be added later.
2. This allows custom hypervisor plugins to define their supported functionalities as well.
> Add support for functionality in hypervisor class

- engine/schema/src/main/java/com/cloud/projects/dao/ProjectAccountDao.java
- engine/schema/src/main/java/com/cloud/projects/dao/ProjectAccountDaoImpl.java
- engine/schema/src/main/java/com/cloud/upgrade/DatabaseUpgradeChecker.java
- engine/schema/src/main/java/com/cloud/upgrade/dao/Upgrade41910to41920.java
- engine/schema/src/main/resources/META-INF/db/schema-41910to41920-cleanup.sql
- engine/schema/src/main/resources/META-INF/db/schema-41910to41920.sql
- server/src/main/java/com/cloud/user/AccountManagerImpl.java
- server/src/test/java/com/cloud/user/AccountManagerImplTest.java
If a user that is associated to a project gets deleted, other users become unable to see who belongs to the project via `listProjectAccounts` due to a NPE. This happens because the removed user is still associated with the project.
This PR fixes the issue by removing the user from all projects before deleting it (as we already do with accounts). To normalize environments that are affected by the bug, the following script will be executed during the upgrade in order to delete project-user associations for users that were removed.
```sql
DELETE FROM `cloud`.`project_account` WHERE `user_id` IN (SELECT `id` FROM `cloud`.`user` WHERE `removed`);
```
Fixes #9974
1. I created a project
2. I added a user to the project
3. I deleted the user
After step 3, I would become unable to list …
> Remove user from project before deletion

- server/src/main/java/com/cloud/user/AccountManagerImpl.java
- server/src/test/java/com/cloud/user/AccountManagerImplTest.java
Currently, CloudStack does not support dual authentication methods for SAML users. If their source is equal to `SAML` or `SAMLDISABLED`, then they're not able to login with a username and password. However, when executing the `updateUser` API to update their password, the password is changed in the database, even though username/password authentication is unsupported for these users.
Regarding LDAP users, password updates directly through CloudStack should also not be allowed. Therefore, this PR addresses these issues by providing a clear error message when SAML or LDAP users attempt to change their password via the `updateUser` API.
---
Fixes #9933
- Verified that attempting to update a SAML or LDAP user's password results in an appropriate error message.
- Verified that attempting to …
> Prevent password updates for SAML and LDAP users

- engine/schema/src/main/resources/META-INF/db/schema-41900to41910.sql
- engine/schema/src/main/resources/META-INF/db/schema-42000to42010.sql
This PR addresses the 4.20.1 part of the changes needed for the upgrades.
see https://github.com/apache/cloudstack/pull/9759#issuecomment-2508482039
> move upgrade code to the right file

- engine/schema/src/main/java/com/cloud/storage/VolumeVO.java
- server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
The class `VolumeVO` lacks access modifiers in its fields. This PR aims to improve adherence to object-oriented programming by adding private access modifiers to all fields in the class mentioned above, along with their respective getters and setters. I've also added a getter to an occurrence in `VolumeApiServiceImpl` where a field belonging to `VolumeVO` was being accessed directly.
I ran all the tests related to `VolumeVO` and `VolumeApiServiceImpl`, checked all usages of both classes, and made sure nothing was broken.
> Add access modifier to `VolumeVO`

- plugins/user-authenticators/saml2/src/main/java/org/apache/cloudstack/saml/SAMLUtils.java
> SAML2: add cookie with HttpOnly too

- ui/public/locales/en.json
- ui/src/components/view/ListView.vue
- ui/src/views/infra/UsageRecords.vue
This PR addresses the following issues related to the Usage UI:
- Usage metrics section is displayed with `null` values to users without access to the `listUsageServerMetrics` API (Fixes #9992);
- Purge usage records action is displayed to users without access to the `removeRawUsageRecords` API (Fixes #9995);
- Generate usage records action is displayed to users without access to the `generateUsageRecords` API (Fixes #9994);
- Vertical scroll overflow in the usage records table (Fixes #9996);
- Usage types input field is displayed to users without access to the `listUsageTypes` API. Since the `usageid` parameter of the `listUsageRecords` API can only be used alongside the `type` parameter, both form fields are now hidden when the caller does not have access to the `listUsageTypes` API.
- …
> UI: Fixes in the Usage UI

- agent/src/main/java/com/cloud/agent/resource/consoleproxy/ConsoleProxyResource.java
- api/src/main/java/org/apache/cloudstack/consoleproxy/ConsoleAccessManager.java
- core/src/main/java/com/cloud/agent/api/ConsoleAccessAuthenticationCommand.java
- engine/schema/src/main/java/com/cloud/upgrade/DatabaseUpgradeChecker.java
- engine/schema/src/main/java/com/cloud/upgrade/dao/Upgrade42010to42100.java
- engine/schema/src/main/java/com/cloud/vm/ConsoleSessionVO.java
- engine/schema/src/main/java/com/cloud/vm/dao/ConsoleSessionDao.java
- engine/schema/src/main/java/com/cloud/vm/dao/ConsoleSessionDaoImpl.java
- engine/schema/src/main/resources/META-INF/db/schema-41910to42000.sql
- engine/schema/src/main/resources/META-INF/db/schema-42010to42100-cleanup.sql
- engine/schema/src/main/resources/META-INF/db/schema-42010to42100.sql
- server/src/main/java/com/cloud/consoleproxy/AgentHookBase.java
- server/src/main/java/org/apache/cloudstack/consoleproxy/ConsoleAccessManagerImpl.java
- services/console-proxy/server/src/main/java/com/cloud/consoleproxy/ConsoleProxy.java
This PR proposes to persist IP addresses related to VM access via CPVM. Specifically, it stores the IP address of the client accessing a VM and the IP address of the console endpoint creator. To achieve this, the `cloud.console_session` table was extended with two new columns: `client_address`, which stores the client's IP address, and `console_endpoint_creator_address`, which captures the IP address of the console endpoint creator.
These IP addresses were already being captured for logging and validation purposes. The console endpoint creator's IP is captured here, at the start of the `CreateConsoleEndpointCmd` execution:
https://github.com/apache/cloudstack/blob/47a6b7011d7e42be86a748af50b87633147b5a90/api/src/main/java/org/apache/cloudstack/api/command/user/consoleproxy/CreateConsoleEnd …
> Persist IP addresses related to VM access via CPVM

- vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/VirtualMachineMO.java
The virtual machine configuration process is used in a lot of VMware workflows, such as instance creation, start and scale. However, there are no logs in this process, which difficults the troubleshooting of errors, specially of those that are returned by VMware.
This PR adds logs to this process in order to make the troubleshooting of errors easier.
In a local lab:
1. I created a VM using only IDE controllers;
2. I stopped the VM;
3. I changed the controllers of the VM from IDE to SCSI;
4. I started the VM, and verified that the logs presented the reconfigurations of the VM in order to remove the disks and NICs, to add the SCSI controllers, and the general VM configuration.
```bash
ubuntu@lab-vmware-mgmt-01:~$ sudo grep 'Reconfiguring virtual machine' $mgmt_log
2024-05-14T11:17:15,122 …
```
> Add logs to VMware instance configuration process

- server/src/main/java/com/cloud/network/element/VirtualRouterElement.java
This PR fixes the typo `removeaccessvpn` which should be `remoteaccessvpn`
> server: fix typo removeaccessvpn in VirtualRouterElement

- ui/src/views/offering/AddNetworkOffering.vue
The default offering for vpc networks has been changed to conserved mode in PR #8309 . It looks good.
This PR enables the option on UI
> UI: create VPC network offering with conserve mode

- plugins/storage/volume/linstor/CHANGELOG.md
- plugins/storage/volume/linstor/src/main/java/com/cloud/hypervisor/kvm/storage/LinstorStorageAdaptor.java
- plugins/storage/volume/linstor/src/main/java/com/cloud/hypervisor/kvm/storage/LinstorStoragePool.java
This improves the heartbeat check done from Linstor primary storage.
If a node doesn't have a DRBD connection to another node, additionally ask Linstor-Controller if the node is alive. Otherwise we would have simply said no and the node might still be alive. This is always the case in a non hyperconverged setup.
Test VM-HA in a Linstor cluster
> linstor: improve heartbeat check with also asking linstor

- api/src/main/java/com/cloud/vm/VmDetailConstants.java
- engine/orchestration/src/main/java/com/cloud/agent/manager/AgentAttache.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStoragePoolManager.java
- server/src/main/java/com/cloud/network/element/ConfigDriveNetworkElement.java
This PR allows config drive deletion of migrated VM, on host maintenance (from it's last source location - host cache/primary/secondary storage).
Fixes below issues identified during host maintenance tests, with VM using config drive on KVM host cache.
1. Old config drive location is overriden in the VM detail, while creating the new one during the migration (config drive location would change here, in case any of the location settings updated after VM is created - vm.configdrive.force.host.cache.use, vm.configdrive.primarypool.enabled, vm.configdrive.use.host.cache.on.unsupported.pool). If so, the rollback or post migration tries to delete the config drive from the new/overriden location in the source host after migration, where the file doesn't exists.
1. Delete config drive command …
> Allow config drive deletion of migrated VM, on host maintenance

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtPrepareForMigrationCommandWrapper.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtStartCommandWrapper.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/IscsiAdmStorageAdaptor.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/IscsiAdmStoragePool.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStoragePoolManager.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/LibvirtStorageAdaptor.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/ManagedNfsStorageAdaptor.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/MultipathSCSIAdapterBase.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/MultipathSCSIPool.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/ScaleIOStorageAdaptor.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/ScaleIOStoragePool.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/StorageAdaptor.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/storage/ScaleIOStoragePoolTest.java
- plugins/storage/volume/linstor/CHANGELOG.md
- plugins/storage/volume/linstor/src/main/java/com/cloud/hypervisor/kvm/storage/LinstorStorageAdaptor.java
- plugins/storage/volume/linstor/src/main/java/com/cloud/hypervisor/kvm/storage/LinstorStoragePool.java
- plugins/storage/volume/storpool/src/main/java/com/cloud/hypervisor/kvm/storage/StorPoolStorageAdaptor.java
- plugins/storage/volume/storpool/src/main/java/com/cloud/hypervisor/kvm/storage/StorPoolStoragePool.java
This PR adds information to the storage adapters if the `connectPhysicalDisk` is running while doing
live VM migration. At least for Linstor this information is very beneficial to only allow two-primaries while
in this environment.
Other storage adapters will currently just ignore this information.
We just found out by a recent incident that this is rather critical for Linstor in the case that
for some reason the CloudStack management server thinks that a host is down or needs to do
VM HA, even tough the Host is still working as expected.
Linstor cluster, basic VM operations
> kvm-storage: provide isVMMigrate information to storage plugins

- packaging/centos7/cloud.spec
- packaging/centos7/filelimit.conf
- packaging/centos8/cloud.spec
- packaging/centos8/filelimit.conf
This PR fixes #9872 
Also see original ticket, set the contents of `/etc/systemd/system/cloudstack-management.service.d/filelimit.conf`
```
```
> set ulimit for server according to redhat spec

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtGetVmIpAddressCommandWrapper.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtSetupDirectDownloadCertificateCommandWrapper.java
- plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/wrapper/xenbase/CitrixGetVmIpAddressCommandWrapper.java
- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
- server/src/main/java/org/apache/cloudstack/direct/download/DirectDownloadManagerImpl.java
- utils/src/main/java/com/cloud/utils/net/NetUtils.java
This PR improves the Certificate and VM hostname validations, during direct download certificate setup and VM IP address check.
Tested upload templatedirectdownloadcertificate with valid and invalid names.
> Certificate and VM hostname validation improvements

- ui/src/views/network/CreateVpc.vue
This PR adds the `OwnershipSelection` component to VPC networks forms, allowing users to specify the account or project that will own the VPC.
Fixes: #10121
In a local lab with the following domain structure:
ROOT
|- dom-A
|- dom-B
\ - subdom-B
With a Root Admin account, I was able to create a VPC for a user in the ROOT, dom-A, dom-B and subdom-B domains. I validated that the account/project owner of the VPC was the one specified in the form, and not the caller account.
With ACS set to Brazilian Portuguese, the VPC was always created to the caller account. With the changes of PR #10052, this situation does not happen.
> Add ownership selection to VPC form

- README.md
To all of the CloudStack contributors - Merry Christmas and Happy Holidays!
/cc alphabetically-ish @abh1sar @alexandremattioli @andrijapanicsb @borisstoyanov @BryanMLima @bernardodemarco @chiradeep @DaanHoogland @GabrielBrascher @GaOrtiga @gsirett @GutoVeronezi @harikrishna-patnala @hsato03 @rajujith @jbampton @JoaoJandre @kiwiflyer @kiranchavala @kishankavala @mlsorensen @msinhore @NuxRo @nvazquez @PeterBackroll @pdion891 @rafaelweingartner  @resmo  @RodrigoDLopez @rohityadavcloud @rp- @SadiJr @shwstppr @slavkap @soreana @steveroles @SadiJr @sureshanaparti @svenvogel @swill @syed @utchoang @vishesh92 @vladimirpetrov @winterhazel @weizhouapache @wido and so many others! (I may have missed quite a few - you're all in my thoughts)
> README: it's that time of the year!

- engine/components-api/src/main/java/com/cloud/ha/HighAvailabilityManager.java
- server/src/main/java/com/cloud/ha/HighAvailabilityManagerImpl.java
- server/src/main/java/com/cloud/resource/ResourceManagerImpl.java
- server/src/test/java/com/cloud/ha/HighAvailabilityManagerImplTest.java
This PR  adds support to enable/disable VM High Availability manager. 
- New config 'vm.ha.enabled'  with Zone scope is added, to enable/disable VM High Availability manager. This is enable by default (for backward compatibilty). When enabled, the VM HA WorkItems (for VM Stop, Restart, Migration, Destroy) can be created and the scheduled items are executed. When disabled, new VM HA WorkItems are not allowed and the scheduled items are retried until max retries configured at 'vm.ha.migration.max.retries' (executed in case HA is re-enabled during retry attempts), and then purged after 'time.between.failures' by the cleanup thread that runs regularly at 'time.between.cleanup'.
- New config 'vm.ha.alerts.enabled' with Zone scope is added, to enable/disable alerts for the VM HA operations. …
> Support to enable/disable VM High Availability manager

- .github/linters/.markdown-lint.yml
- CHANGES.md
- CONTRIBUTING.md
- ISSUE_TEMPLATE.md
- PULL_REQUEST_TEMPLATE.md
- plugins/storage/volume/storpool/README.md
- tools/devcloud4/README.md
- tools/devcloud4/advanced/README.md
- tools/devcloud4/basic/README.md
- tools/docker/README.md
- tools/marvin/marvin/misc/build/CI.md
- tools/marvin/marvin/misc/build/README.md
- ui/docs/development.md
- ui/src/style/README.md
MD012 no-multiple-blanks - Multiple consecutive blank lines
https://github.com/DavidAnson/markdownlint/blob/main/doc/md012.md
This PR cleans up and standardizes the Markdown files.
Ran locally:
> pre-commit: enable markdownlint rule `MD012`

- ui/src/views/compute/DeployVM.vue
- ui/src/views/compute/wizard/OwnershipSelection.vue
- ui/src/views/network/CreateIsolatedNetworkForm.vue
- ui/src/views/network/CreateL2NetworkForm.vue
- ui/src/views/storage/CreateSharedFS.vue
- ui/src/views/storage/CreateVolume.vue
This PR addresses an issue when trying to assign an instance to another account/project when using ACS in another language besides English. To accomplish this fix, the `OwnershipSelection` component was standardized to use logic independent of the language used by the user.
Before this patch, the message `The new account is the same as the old account.` was shown when trying to assign the VM to another account/project.
With this patch, assigning an instance works as intended in different languages, as expected.
I also test the creation of VMs, Isolated networks, L2 networks, shared FS and volumes; all resources were created accordingly to the owner specified.
> UI: Standardize OwnershipSelection to use logic independent of language

- systemvm/debian/opt/cloud/bin/configure.py
This PR fixes the issue that s2s vpn cannot be applied if split-connections is enabled
the issue is because `count` is a build-in method in python3 , `len` should be used instead.
```
>>> aa=[]
>>> aa.count
<built-in method count of list object at 0x76e292158b40>
>>> len(aa)
0
```
> VR: fix site-2-site VPN if split connections is enabled

- ui/src/views/infra/zone/ZoneWizardAddResources.vue
- ui/src/views/infra/zone/ZoneWizardLaunchZone.vue
This PR adds the arch type on the cluster creation step on the zone creation wizard.
Fixes: #10014 
Tested locally KVM on ARM nested virtualization on UTM 4.6.3 on macOs:
- On the cluster step: selected ARM 64
- On the host step: entered the ARM host information
- Result: Zone successfully created
> UI: Add cluster arch type to the zone creation wizard

- server/src/main/java/org/apache/cloudstack/vm/UnmanagedVMsManagerImpl.java
- server/src/test/java/org/apache/cloudstack/vm/UnmanagedVMsManagerImplTest.java
This PR fixes https://github.com/apache/cloudstack/issues/9670
<details><summary>Details</summary>
<p>
This pull request includes several changes to the `UnmanagedVMsManagerImpl` class to enhance the handling of disk offerings during the import and conversion of unmanaged instances. The most important changes include modifications to the `getStoragePool` method, updates to the conversion and import logic, and adjustments to the test cases.
Enhancements to disk offering handling:
* [`server/src/main/java/org/apache/cloudstack/vm/UnmanagedVMsManagerImpl.java`](diffhunk://#diff-b1de8eb3cd6ebc9cdb187e0e4a3ff9674b6c5cf169fe338c059c5e42f70598f0L539-R539): Modified the `getStoragePool` method to accept an additional `diskOfferingTags` parameter and updated the logic to ensure the storage pool …
> check tags while fetching storage pool for importing vm

- .pre-commit-config.yaml
- plugins/integrations/kubernetes-service/src/main/resources/conf/k8s-control-node-add.yml
- plugins/integrations/kubernetes-service/src/main/resources/conf/k8s-control-node.yml
- plugins/integrations/kubernetes-service/src/main/resources/conf/k8s-node.yml
Reverts apache/cloudstack#9133
> Revert "pre-commit: add hook `check-yaml`"

- server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
This PR restricts users from migrating volumes attached to VMs that are in starting state. Migrating volumes while their VMs are starting shouldn't be allowed because sometimes the VM could end up not actually starting, and if ACS starts migrating its volume, this could lead to other issues.
<details><summary>Image</summary>
</details>
I tested this PR by deploying an instance and then trying to migrate its volume while the instance was starting. Before the changes, the volume migration process would start. After the migration, an error is thrown, as expected.
> Restrict the migration of volumes attached to VMs in Starting state

- core/src/main/java/com/cloud/agent/api/CheckOnHostCommand.java
The new CheckOnHostCommand constructor was missing a reasonable timeout value, which meant it would fallback to the wait (1800s) timeout. On a Linstor cluster this resulted in over 15 minutes wait time until a host was recognized as down.
With timeout of 20s (as the other constructor) it takes 4-5 mins for a host to become recognized as down.
Failover tests (force shutdown of a host) in a Linstor cluster.
> CheckOnHostCommand: add missing timeout setting

- engine/schema/src/main/java/com/cloud/upgrade/SystemVmTemplateRegistration.java
- server/src/main/java/com/cloud/storage/StorageManagerImpl.java
This fixes an issue during upgrade in edge case.
- deploy an env with ACS 4.18
- the env has multiple hypervisors: KVM and VMware
- the env has multiple secondary storages: sec1 and sec2
- register the new 4.19.1 systemvm template for VMware (systemvm-vmware-4.19.1), but mistakely as a private template.
- the systemvm template is downloaded to sec2 (not sec1). If it is downloaded to sec1, remove it and re-register the template.
- backup the cloudstack databases by
```
mysqldump -R cloud -p >cloud.db
mysqldump -R cloud_usage -p >cloud_usage.db
```
- install ACS 4.19.1.2 and start mgmt server
Without this PR, got an NPE during mgmt server start
```
2024-10-29 12:46:53,904 ERROR [c.c.u.SystemVmTemplateRegistration] (main:null) (logid:) Failed to register template …
```
> upgrade: consider multiple hypervisors and secondary storages

- systemvm/patch-sysvms.sh
This PR fixes #9086 
- create an env
- check certs in SSVM
keytool -list -keystore /usr/local/cloud/systemvm/certs/realhostip.keystore -storepass vmops.com  |grep entries
- upgrade the env, and then patch the SSVM
- OR, patch the SSVM forcely
- check certs in SSVM again
keytool -list -keystore /usr/local/cloud/systemvm/certs/realhostip.keystore -storepass vmops.com  |grep entries
expect results
- the certs are imported
actual results
- the keystore contains only 4 certs after patching
> systemvm: fix keystore is reset when patch a systemvm

- scripts/vm/network/vnet/modifyvxlan-evpn.sh
This script can be used to use BGP+EVPN for VXLAN instead of multicast.
In order to use the script operators need to manually create a symlink:
cd /usr/share
ln -s modifyvxlan.sh cloudstack-common/scripts/vm/network/vnet/modifyvxlan-evpn.sh
Configuring BGP and EVPN is outside of the scope of CloudStack and is up to the operator to configure.
This commit just adds this script to the main repository and does not change any existing functionality.
> network: Add BGP+EVPN+VXLAN script to main repository and Agent package

- services/secondary-storage/controller/src/main/java/org/apache/cloudstack/secondarystorage/SecondaryStorageManagerImpl.java
- utils/src/main/java/com/cloud/utils/net/NetUtils.java
> consider a valid ipv4 address as a validish ipv4 /32 cidr

- vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/VirtualMachineMO.java
When attaching a volume to an instance, CloudStack calculates the next free unit number of the disk controller that should be associated with the volume. However, for IDE disk controllers, CD/DVD drives associated with the controller are not taken into consideration when calculating the next available unit number. Due to this, an error happens in some situations when trying to attach a volume to an instance over IDE controllers because CloudStack tries to associate the volume to an unit number that is already being used.
The generic method of reproducing this problem is:
1. Deploy a VM
2. Set `dataDiskController` to `ide`
3. If there are any volumes using IDE controllers, detach them
4. Try to attach a volume
This PR fixes the issue by making the code also consider CD/DVD drives. Tests …
> [VMware] Consider CD/DVD drive when calculating next free unit number for volume attachment over IDE controller

- engine/schema/src/main/java/org/apache/cloudstack/network/dao/NetworkPermissionDao.java
- engine/schema/src/main/java/org/apache/cloudstack/network/dao/NetworkPermissionDaoImpl.java
- server/src/main/java/com/cloud/user/AccountManagerImpl.java
- server/src/test/java/com/cloud/user/AccountManagerImplTest.java
- server/src/test/java/com/cloud/user/AccountManagetImplTestBase.java
Currently, if an account with network permissions for guest networks is deleted, CloudStack does not automatically delete these permissions, and operators cannot delete them later through the APIs. The workaround for this scenario is to manually remove the permissions entries from the `cloud.network_permissions` table. Therefore, this PR proposes to clean up the network permissions of an account when it is deleted. 
Additionally, when attempting to delete an account that is a project administrator, an error message is returned. This error message has been enhanced to include instructions on the next steps the operator should perform to properly delete the given account.
---
Fixes #10103
First, I created a domain `ROOT/d1`, a domain admin (`d1`) and two regular users within it (`u1` and …
> Clean up network permissions on account deletion

- ui/src/views/setting/ConfigurationValue.vue
The slider component for global settings of `Range` type is currently not working correctly. Its width is equal to `0px`, and operators can only set the settings values to 0 or 100%. This PR addresses this issue by fixing the slider's behavior, allowing operators to properly adjust the settings values using the component.
- Before:
- After:
I verified that global settings of `Range` type can be modified using the slider component.
> UI: Fix slider component in global settings with `Range` type

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/feature_request.yaml
This PR tries to implement more modern issue templates in github as it seems the old ones are out of date.
It will look like this to users:
when choosing bug:
when choosing new feature:
note that after submitting the issues the descriptions are editable markdown as usual. We might wat to refine these templates a bit, or do that later.
> feature and bug templates

- server/src/main/java/com/cloud/resource/ResourceManagerImpl.java
This PR adds the host preparing for maintenance to the avoid list for the deployment planner.
Without adding the host to the avoid list the deployment planner will return the host preparing for maintenance when a vm has a local storage root disk and has the host preparing for maintenance as the last host.
- Create vm with local storage
- Set host with the vm in maintenance
```
(qa6-4.19-upstream-54bd5b60-kvm-host1) Failed to prepare host for maintenance due to: Migration of the vm VM instance {"id":13,"instanceName":"i-2-13-VM","type":"User","uuid":"209d346b-b2e7-485f-a889-8462dd0078cc"}from host Host {"id":1,"name":"qa6-4.19-upstream-54bd5b60-kvm-host1","type":"Routing","uuid":"224ca458-90e6-4efb-8532-e5efc83df9f4"} to destination host Host …
```
> Maintenance mode: Add host to deployment planner avoid list to fix local storage migration

- server/src/main/java/com/cloud/resource/RollingMaintenanceManagerImpl.java
- server/src/test/java/com/cloud/resource/RollingMaintenanceManagerImplTest.java
This PR fixes NPE issues during host rolling maintenance, due to host tags and custom constrained/unconstrained service offering.
Fixes #9834 & #9836
Tested host rolling maintenance with custom constrained/unconstrained service offering & service offering without host tags, checked the rolling maintenance cmd sent to KVM host without any NPEs.
> Fix NPE issues during host rolling maintenance, due to host tags and custom constrained/unconstrained service offering

- plugins/metrics/src/main/java/org/apache/cloudstack/api/ListSystemVMsUsageHistoryCmd.java
> api: fix access for listSystemVmUsageHistory

- server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
Currently, when listing VMs by network (`networkid`) or VPC (`vpcid`), CloudStack does not check whether the VMs still belong to the specified network or VPC. Therefore, this PR fixes this issue by only filtering the VMs that have non-removed NICs in the specified network or VPC. 
First, I created an isolated network (`nw-01`) and a VPC (`vpc-01`) with two tiers (`tier-01` and `tier-02`). Next, I deployed a VM (`vm-01`) with one NIC in each one of these networks.
After that, I checked that the `listVirtualMachines` API had the same behavior as prior to the PR changes:
<details>
<summary>List VMs that belong to the <code>nw-01</code> network</summary>
```bash
(localcloud) 🌍 > listVirtualMachines networkid="f839708e-a21b-4116-a978-c2b6155fa5db" filter=displayname
{
"count": 1, …
```
> Fix listing of VMs with removed NICs

- plugins/storage/volume/linstor/CHANGELOG.md
- plugins/storage/volume/linstor/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LinstorBackupSnapshotCommandWrapper.java
Linstor plugin used the wrong zfs dataset path to hide/unhide the snapshot device.
Also don't use the full path to the zfs binary.
Fixes: #9360
Linstor cluster with zfs storage backend.
> linstor: Fix ZFS snapshot backup

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java
This PR fixes #7490
According to libvirt code, the units per scsi controller is set to 7
therefore, we need to create scsi controller every 7 disks (including CDROM).
https://github.com/libvirt/libvirt/blob/50cc7a0d9d2b9df085ec073a6d60820a9642158a/src/conf/domain_conf.h#L3007-L3008
https://github.com/libvirt/libvirt/blob/50cc7a0d9d2b9df085ec073a6d60820a9642158a/src/conf/domain_conf.c#L6701-L6704
- register a template or update template guest os type to "Other PV (VirtIO SCSI)"
- create vm
- attach 6 disks. check vm xml dump, it looks good
```
<disk type='file' device='disk'>
<driver name='qemu' type='qcow2' cache='none' discard='unmap'/>
<source file='/mnt/3bdc199b-d6f8-3a19-a139-3b0ae09379d5/e613dd6e-e0df-41ba-bf24-75bc0c5d4771' index='8'/>
<backingStore/> …
```
> kvm: add SCSI controllers based on the number of virtio-SCSI disks

- ui/src/views/network/VpcTiersTab.vue
Currently VLAN was not getting added to API call when offering has specifyVlan as true
Error before the fix,
https://github.com/user-attachments/assets/0b7a2579-b1e9-4ff6-a656-1a8bc99aca0c
> ui: fix passing vlan while creating vpc tier

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtDeleteStoragePoolCommandWrapper.java
- server/src/main/java/com/cloud/storage/StorageManagerImpl.java
This PR addresses the issues raised in https://github.com/apache/cloudstack/issues/9820
Case 0: Documentation admin should not remove the local.storage.uuid. Addressed here https://github.com/apache/cloudstack-documentation/pull/473
Case 1: Delete local storage pool entry even if local storage addition fails.
Case 2: Delete local.storage.uuid and path entries in agent.properties when local storage is deleted from management server. If not deleted then on every agent restart it will be added again in the management server.
Case 0: Doc PR https://github.com/apache/cloudstack-documentation/pull/473
Case 1: 
1. Create local storage with invalid path.
2. Local storage addition fails.
3. Previously there is an active local storage entry even it failed to add, now there won't be any entry.
Case …
> Fix local storage deletion cases

- ui/public/locales/en.json
- ui/src/components/view/ListView.vue
- ui/src/components/view/SearchView.vue
- ui/src/config/section/network.js
- ui/src/views/AutogenView.vue
This PR addresses the issue https://github.com/apache/cloudstack/issues/9386
With this PR, admin will now have the new option in filters section in list networks page. If a network is edited by setting "Display Network" to false, it will still redirect to 404 page, but then have the below option to list those kind of networks.
1. Edit a network (test) and set "Display network" to false, then list networks
2. Update filter option, set "Display network" to false 
3. click Search, Networks to which display networks set to false will be shown
> Added displaynetwork option in filters for listnetwork only for admin

- agent/conf/agent.properties
- agent/src/main/java/com/cloud/agent/properties/AgentProperties.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDefTest.java
This PR allows the value `none` for the property `vm.watchdog.model` on the agent.properties file. When value is set to `none` then no watchdogs are created for the VM deployments
For EL9 hosts on ARM64: VM deployments fail with error:
````
2025-01-17T23:31:51.072699Z qemu-kvm: -device {"driver":"i6300esb","id":"watchdog0","bus":"pci.8","addr":"0x1"}: 'i6300esb' is not a valid device model name
````
> [KVM] Add watchdog model none to disable use of watchdogs on KVM agent

- ui/src/views/dashboard/CapacityDashboard.vue
This PR fixes the UI display of used vs allocated resources. It adds a switch to display allocated or used resources
https://github.com/user-attachments/assets/86ce56cb-6cc3-4303-8d63-b336a03b4769
Fixes: #10185
> [UI] Switch between allocated and used capacity on dashboard

- ui/src/views/network/AclListRulesTab.vue
This PR fixes: https://github.com/apache/cloudstack/issues/10220
Before fix:
```
id,protocol,startport,endport,traffictype,state,cidrlist,tags,aclid,aclname,number,action,fordisplay,reason
63cefab0-e714-4d5c-808c-a438ba27f7c5,tcp,80,80,Ingress,Active,10.0.0.0/24,"",0f8fa3ad-baa5-473c-9431-54a57a7584d8,custom,1,Allow,true,rule 
```
After fix:
```
id,protocol,startport,endport,traffictype,state,cidrlist,tags,aclid,aclname,number,action,fordisplay,reason
63cefab0-e714-4d5c-808c-a438ba27f7c5,tcp,80,80,Ingress,Active,10.0.0.0/24,"",0f8fa3ad-baa5-473c-9431-54a57a7584d8,custom,1,Allow,true,rule #1
5e5a1d56-4546-4fb9-9ca9-fc671ac90468,all,undefined,undefined,Ingress,Active,10.10.10.0/24,"",0f8fa3ad-baa5-473c-9431-54a57a7584d8,custom,2,Allow,true,two
```
> Handle special characters when exporting ACLs

- engine/orchestration/src/main/java/com/cloud/agent/manager/AgentManagerImpl.java
This PR is to investigate and solve #10154
log to see what command is being processed
Fixes: #10154
> deal with NPE during host reconnect

- engine/orchestration/src/main/java/com/cloud/agent/manager/AgentManagerImpl.java
This PR adds an extra null guard in notify monitors
see the discussion in https://github.com/apache/cloudstack/pull/10158#discussion_r1928448081
> extra null guard

- framework/quota/src/main/java/org/apache/cloudstack/quota/activationrule/presetvariables/Account.java
- framework/quota/src/main/java/org/apache/cloudstack/quota/activationrule/presetvariables/PresetVariableHelper.java
- framework/quota/src/test/java/org/apache/cloudstack/quota/activationrule/presetvariables/PresetVariableHelperTest.java
This PR adds the `account.created` preset variable to Quota tariffs, allowing users to consider an account's creation date when defining values to, for instance, grant a discount on the first month.
This variable is injected as a String. Therefore, users need to parse it first: `Date.parse(account.created)`.
In a local lab, the billing of two accounts was compared in relation to the amount of VM snapshots each one has.
- User Account: created on 17 Oct 2024 17:36:46, with 3 VM snapshots
- Root Account: created on 24 Oct 2024 13:51:35, with 1 VM snapshot
The base script for the activation rule used was:
```js
today = new Date(); // current date was 24 Oct 2024
daysDiff = (today-Date.parse(account.created))/(1000*60*60*24);
if (daysDiff <= 5 && daysDiff >= 0) {
20
} else {
0
}
```
When …
> Add account.created preset variable to Quota tariffs

- agent/conf/agent.properties
- agent/src/main/java/com/cloud/agent/properties/AgentProperties.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java
- plugins/hypervisors/kvm/src/main/java/org/apache/cloudstack/utils/linux/KVMHostInfo.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java
- server/src/main/java/com/cloud/hypervisor/HypervisorGuruBase.java
This PR introduces support for cloudstack-agent on KVM on the s390x and cloudstack-management-server on s390x architecture.
KVM is supported on s390x (IBM Z and LinuxONE) architecture, [Linux KVM Processor Support Page](https://www.linux-kvm.org/page/Processor_support#IBM_z).
I have built a new s390x version of the System VM template: [ [Refer: s390x Build instructions and System VM Template guide.](https://github.com/linux-on-ibm-z/docs/wiki/Building-CloudStack)]
I have tested the deployment of VMs and confirmed that the Virtual Router (VR), SSVM, Console Proxy functionalities worked as expected.
Testing was performed with Debian 11 templates that are compatible with s390x in CloudStack.
I have tested with agent and management server on the following distributions:
- RHEL
- Ubuntu
- SLES
> KVM/s390x Support:  Add support for KVM on s390x architecture

- ui/src/views/setting/ConfigurationValue.vue
Currently, when changing the `Decimal`, `Number` and `Range` global settings values through the UI, CloudStack does not validate if the inserted values are numeric. Additionally, when letters are entered in the inputs, a message indicating that the setting value was successfully updated is returned to the operators, which does not effectively happen.
Therefore, this PR proposes to verify the values that are entered in those input fields. If non-numeric values are inserted, they will be ignored. Furthermore, it is still possible to use special keys, such as `Ctrl` and `Alt`, in order to make use of keyboard shortcuts.
- Verified that in `Decimal` and `Range` global settings it is only possible to enter digits and the period (`.`) character.
- Verified that in `Number` global settings it is …
> UI: Validate inserted values in numeric global settings

- ui/src/views/iam/DomainView.vue
This PR fixes #9893
<details><summary>Details</summary>
<p>
This pull request includes updates to the `DomainView.vue` component to improve data fetching and rendering logic. The most important changes include adding a condition to the `tree-view` component and modifying the data fetching mechanism to watch for route parameter changes.
Improvements to data fetching and rendering:
* [`ui/src/views/iam/DomainView.vue`](diffhunk://#diff-696e49432a101dd5b8760562a973b38b65cbd8ccd9916f62945b70f492faa3adR59): Added a `v-else` condition to the `tree-view` component to ensure it only renders when appropriate.
* [`ui/src/views/iam/DomainView.vue`](diffhunk://#diff-696e49432a101dd5b8760562a973b38b65cbd8ccd9916f62945b70f492faa3adL136-R141): Changed the `created` lifecycle hook to watch for changes in …
> UI: Fix domain view when opening details for a specific domainid

- packaging/centos8/cloud.spec
> packaging: support both mysql and mariadb on EL8/EL9

- scripts/util/create-kubernetes-binaries-iso.sh
Currently, if we execute the script (create-kubernetes-binaries-iso.sh) to create the latest CKS iso its fails with the following error
```
+ mkdir -p /tmp/iso//docker
++ /tmp/iso//k8s/kubeadm config images list --kubernetes-version=v1.31.1
/tmp/iso//k8s/kubeadm: line 1: syntax error near unexpected token `<'
/tmp/iso//k8s/kubeadm: line 1: `<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: kubernetes-release/release/v1.31.1/bin/linux/amd64/kubeadm</Details></Error>'
```
On investigating found that kubernetes community recommended to use "dl.k8s.io" instead of "storage.googleapis.com/kubernetes-release"
Blog post
https://kubernetes.io/blog/2023/06/09/dl-adopt-cdn/ …
> changed the kubernetestool url

- engine/storage/src/main/java/org/apache/cloudstack/storage/allocator/AbstractStoragePoolAllocator.java
On the allocation process of VM volumes, the reordering of storage pools by capacity is wrongly identifying whether a pool is shared or not. A pool is considered to be shared when its type (represented by the `Storage.StoragePoolType` enum) is shared; however, as can be observed from the enum options, the `VMFS` storage type is considered to be shared.
https://github.com/apache/cloudstack/blob/35fe19f096dd38987bd1f892c78e9cce42c05c49/api/src/main/java/com/cloud/storage/Storage.java#L138-L159
As a consequence of that, when trying to deploy VMs in `VMFS` local storages, the allocation of the volumes will fail. Based on the current reordering flow, CloudStack will check that the `VMFS` pool type is shared and set the capacity type to be equal to `Capacity.CAPACITY_TYPE_STORAGE_ALLOCATED`. …
> Fix volume allocation on local VMFS storage

- engine/api/src/main/java/org/apache/cloudstack/engine/orchestration/service/NetworkOrchestrationService.java
- engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
- server/src/main/java/com/cloud/network/vpc/VpcManagerImpl.java
This PR fixes the wrong checks on CIDR of static routes
- define global/zone configuration `denied.routes`, which has already added to database some years ago
https://github.com/apache/cloudstack/blob/c94d0abab49a178f4f6e403ed37b8f2f8448fce2/engine/schema/src/main/resources/META-INF/db/schema-41520to41600.sql#L586-L587
- check on the configuration `denied.routes` ,instead of `GuestDomainSuffix`
- check if the route cidr (instead of vpc cidr) is link-local
> Static Routes: fix check on wrong global configuration

- api/src/main/java/org/apache/cloudstack/api/command/user/firewall/CreateFirewallRuleCmd.java
- api/src/test/java/org/apache/cloudstack/api/command/user/firewall/CreateFirewallRuleCmdTest.java
- ui/src/views/network/FirewallRules.vue
> api,ui: fix empty source cidr value for firewall rule

- engine/schema/src/main/java/com/cloud/host/dao/HostDaoImpl.java
- server/src/main/java/com/cloud/server/ManagementServerImpl.java
- server/src/test/java/com/cloud/vm/FirstFitPlannerTest.java
This PR improves listing of HA and non-HA hosts when ha.tag setting is defined and hosts have multiple tags along with ha tag.
Fixes #10070
> Improve listing of HA and non-HA hosts when ha.tag setting is defined and hosts have multiple tags along with ha tag

- ui/src/config/section/compute.js
> UI: list backup offerings by zoneid when assign vm to backup offering

- server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
This PR fixes: https://github.com/apache/cloudstack/issues/9673
When there are multiple physical networks for guest traffic type, the default offerings aren't listed for the tagged physical network. Currently new offerings are needed to be created for tagged physical networks to be able to create (Shared) networks.
> List default network offerings when multiple physical networks for guest traffic type exists

- server/src/main/java/com/cloud/network/NetworkModelImpl.java
- server/src/main/java/com/cloud/network/element/ConfigDriveNetworkElement.java
- server/src/main/java/com/cloud/network/element/VirtualRouterElement.java
This PR fixes NPE issues while checking for user data provider.
Fixes #9847
> Fix NPE while checking for user data provider

- debian/control
Change the Debian packages `Maintainer` attribute to `The Apache CloudStack Team <dev@cloudstack.apache.org>`, once the whole community maintains them, not only a single person.
> Change Debian packages Maintainer attribute

- api/src/main/java/com/cloud/storage/Storage.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java
- plugins/storage/volume/linstor/CHANGELOG.md
- plugins/storage/volume/linstor/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LinstorBackupSnapshotCommandWrapper.java
- plugins/storage/volume/linstor/src/main/java/com/cloud/hypervisor/kvm/storage/LinstorStorageAdaptor.java
- plugins/storage/volume/linstor/src/main/java/org/apache/cloudstack/storage/datastore/driver/LinstorPrimaryDataStoreDriverImpl.java
- plugins/storage/volume/linstor/src/test/java/org/apache/cloudstack/storage/datastore/driver/LinstorPrimaryDataStoreDriverImplTest.java
- plugins/storage/volume/linstor/src/test/java/org/apache/cloudstack/storage/datastore/util/LinstorUtilTest.java
- pom.xml
This PR main purpose is adding encryption support for Linstor, as Linstor handles the encryption layer (LUKS)
to allow DRBD running on top of it, we needed a new mode for encryption in CloudStack.
So that CloudStack knows the volume is encrypted, but the encryption/deencryption is handled by the primary storage.
So qemu only gets the final block device path and opening/closing is handled by Linstor.
Additionally there are a few commits for cleanups and a few unittests for Linstor code.
For this to work at least Linstor 1.30.x is needed, as the new cloning code is needed.
Linstor cluster with encrypted disk offering.
> Linstor: encryption support

- ui/src/views/image/RegisterOrUploadTemplate.vue
Normal users are allowed to register a direct download template via API, but the option is disabled in the UI.
This PR fix the issue #9923 by removing this restriction.
The template registered by a normal user using the direct download option:
I tested by registering a template via UI using an account with the User role. Selecting the KVM hypervisor gave me the direct download option.
> Add direct download option to users in register template form

- server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
- server/src/test/java/com/cloud/storage/VolumeApiServiceImplTest.java
Reverts apache/cloudstack#10267  "server: fix attach uploaded volume"
> Revert test of #10267

- engine/schema/src/main/resources/META-INF/db/schema-42010to42100.sql
This PR fixes Lint error reported by github action 
" pre-commit run --all-files"
> Fix lint error coming up in main

- server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
- server/src/test/java/com/cloud/storage/VolumeApiServiceImplTest.java
Includes changes from #10267 as they've been reverted by #10323 
Fixes issue highlighted in https://github.com/apache/cloudstack/pull/9315#issuecomment-2633353671
A volume in Allocated state can be attached to a stopped VM even when the actual volume is not created in the primary store.
`test_12_start_vm_multiple_volumes_allocated` in test/integration/smoke/test_vm_life_cycle.py does the same.
After changes in #10267, a scenario was failing as a suitable pool was not found for an allocated volume when attached to a VM which has never been started
Verified test_vm_life_cycle.py with changes,
```
[root@pr9315-t7075-kvm-rocky8-marvin marvin]# nosetests --with-xunit --xunit-file=results.xml --with-marvin --marvin-config=./pr9315-t7075-kvm-rocky8-advanced-cfg -s -a tags=advanced …
```
> server: fix pod retrieval during volume attach

- engine/schema/src/main/java/com/cloud/upgrade/SystemVmTemplateRegistration.java
- server/src/main/java/com/cloud/storage/StorageManagerImpl.java
Pre-seeded template storages always had there pre initialized 0 sizes and would never be updated.
This makes later problems, when the primary storage should pre-allocate the volume as it doesn't know the size
and would fail or maybe try to delay the allocation until the agent code knows the size.
This updates the sizes from the template.properties files on the validateIfSeeded check.
The issue was found while reviewing #10132 
Started a fresh KVM cluster with preseeded systemvm template from `cloud-install-sys-tmplt` on Linstor primary storage.
> systemvm-registration: update seeded template_store_ref sizes

- server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
- ui/src/views/network/CreateSharedNetworkForm.vue
This PR attempts to improve https://github.com/apache/cloudstack/pull/10222. 
Before fix:
for default untagged physical network - all shared network offerings are listed, including the tagged ones:
for Physical network with tag: phy2 - all shared offering are listed - default and tagged:
After fix:
for default untagged physical network - only untagged offerings are listed:
for Physical network with tag: phy2 - all shared offering are listed - default and tagged:
> List only untagged offerings for Shared networks when tag isn't passed

- ui/src/views/network/VpcTab.vue
This PR makes Description as optional field in ACL list additional screen, which is optional in API.
Tested on QA server.
> Make Description as optional in network acl list

- ui/src/components/view/ListView.vue
- ui/src/config/section/offering.js
This PR adds a new column to the system offerings listing that shows if HA is enabled or disabled. It includes changes to `ListView.vue`, which adds a template that handles `offerha` value from response, and changes to `offering.js`, that includes the column to the table.
Before the changes:
After the changes:
I've created a test environment with a CloudStack setup, then i built and applied the ui packages to my environment.
> UI: Add offer ha column to system offerings table

- core/src/main/java/com/cloud/agent/api/CleanupVMCommand.java
- plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/guru/VMwareGuru.java
- plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java
The MS sends the destroy/delete command of a VM to vCenter when cleaning up its volumes.  If the VM does not have a root volume, the VM with its folder and metadata files remain in vCenter.
To reproduce, deploy a VM, detach its volume, and delete the VM. Then, check vCenter and the VM will still be there.
This PR fixes it by implementing finalizeExpunge for VMWareGuru, which queues a Cleanup Command that, if the VM still exists, sends a destroy command to vCenter to cleanup whatever remained.
| Deploy VM | Destroy VM | Before PR | After PR |
| ------ | ------ | ------ |  ------ | 
| Without data disks, detach root disk. | With expunge | VM remains on vCenter :x: | VM gone from vCenter :white_check_mark: |
| Without data disks, detach root disk. | Without expunge | VM remains on vCenter …
> Fix VMWare leftovers when deleting VM without root disk

- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
This PR fixes https://github.com/apache/cloudstack/issues/9776#issuecomment-2407890059
- create disk offering
- create service offering 1/2 with same disk offering and strictness=true
- create vm with service offering 1
- stop the vm
- scale vm with service offering 2
expected result: success
actual result: fail
see https://github.com/apache/cloudstack/issues/9776#issuecomment-2407890059 for the screenshot.
> server: fix scale vm with same disk offering id

- ui/src/config/section/compute.js
- ui/src/config/section/image.js
- ui/src/config/section/network.js
- ui/src/config/section/storage.js
This PR fixes the missing buttons in the UI. This bug was introduced in https://github.com/apache/cloudstack/pull/10243
<details><summary>Generated Summary</summary>
<p>
This pull request includes several changes to simplify the codebase by removing unnecessary braces in arrow functions across multiple configuration files. The changes ensure a more concise and consistent code style.
Codebase simplification:
* [`ui/src/config/section/compute.js`](diffhunk://#diff-93b52572e13887859e26011826bd9744351c29e7a0de514ea308d503113a13e3L103-R103): Removed unnecessary braces in the `show` method for multiple components, including `DeployVM`, `CreateKubernetesCluster`, `CreateAutoScaleVmGroup`, and `CreateInstanceGroup`. [[1]](diffhunk://#diff-93b52572e13887859e26011826bd9744351c29e7a0de514ea308d503113 …
> UI: Fixup missing buttons

- systemvm/debian/opt/cloud/bin/cs/CsAddress.py
> Fix private gateway acl on static routes

- ui/public/locales/en.json
- ui/src/components/view/ListView.vue
- ui/src/components/widgets/Status.vue
- ui/src/config/section/storage.js
This PR adds a new column to the volume list view that shows the state of the VM the volume is attached to.
In a local environment, I attached a volume to a VM and changed the VM state multiple times. As expected, the current state of the VM was shown in the volume list view.
> UI: Add VM state to Volume list view

- ui/src/components/view/SearchView.vue
Fixes: https://github.com/apache/cloudstack/issues/10310
This PR fixes the duplicate names appearing in the search filters in drop down menus
Before fix:
After fix:
> UI: Fix all list items appearing twice in search view

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java
This PR validates the direct downloaded template file format (QCOW2) if the template file exists, otherwise skips validation & logs it.
> Validate the direct downloaded template file format (QCOW2) if the template file exists

- ui/src/views/auth/ForgotPassword.vue
- ui/src/views/auth/Login.vue
- ui/src/views/auth/ResetPassword.vue
If the URL params contains `username` or `domain`, it will use the values for the username and domain field in Login, forgot password and reset password page. This feature would be useful if you want to open a page which has prefilled usename and/or domain. To test the forgot password and reset password page, you need to enable the `user.password.reset.enabled` global setting.
e.g. The below url will look like this when opened.
https://qa.cloudstack.cloud/simulator/pr/10291/#/user/login?username=admin&domain=ABC
<details><summary>Generated description</summary>
<p>
This pull request includes changes to the forms in the authentication views to support additional query parameters. The most important changes involve updating the `ForgotPassword`, `Login`, and `ResetPassword` components to …
> UI: Fill username & domain fields in login, forgotPassword and resetPassword page from url

- server/src/main/java/com/cloud/network/element/ConfigDriveNetworkElement.java
This PR fixes: https://github.com/apache/cloudstack/issues/10296
Historically, Configdrive only allowed a single service to be provided - namely, userdata. However, it can be used to provide DHCP and dns service as well.
after fix:
```
(localcloud) 🐱 > update networkserviceprovider id=1f32db86-e7a8-4b38-af32-387049438db9 servicelist=userdata,dns,dhcp
{
"networkserviceprovider": {
"canenableindividualservice": true,
"id": "1f32db86-e7a8-4b38-af32-387049438db9",
"name": "ConfigDrive",
"physicalnetworkid": "5e575189-779f-416b-843a-625e813119b6",
"servicelist": [
"Dhcp",
"Dns",
"UserData"
],
"state": "Enabled"
}
}
(localcloud) 🐱 > list networkserviceproviders name=Configdrive
{
"count": 2,
"networkserviceprovider": [
{
"canenableindividualservice": true,
"id": …
```
> Enable multiple services on configdrive network service provider

- ui/src/components/view/SearchView.vue
Currently, when a domain has associated accounts, it is not possible to select it as a filter option in the `SearchView` component. The following video shows the current UI behavior:
https://github.com/user-attachments/assets/8e337680-d0b0-4f6a-9253-fc485592b005
When the user selects a filter option, the method `onSelectFieldChange` in the `SearchView` component is executed. Then, it checks if the changed field name is equal to `domainid`; if so, it executes the method `fetchDynamicFieldData` to fetch only the accounts of the selected domain.
However, the `fetchDynamicFieldData` method is always executing, in its `finally` block, the `fillFormFieldValues` method:
https://github.com/apache/cloudstack/blob/a7beaaf73b819af51294cc35df0830d2a8a2fbc7/ui/src/components/view/SearchView.vue#L716-L7 …
> UI: Fix selection of domain filters in the `SearchView` component

- systemvm/debian/opt/cloud/bin/configure.py
This PR fixes the duplicated lines with /var/www/html/latest/.htaccess
see https://github.com/apache/cloudstack/issues/10205#issuecomment-2601869131
this issue does not exist with 4.19
> VR: fix duplicated lines in .htaccess

- api/src/main/java/com/cloud/storage/VolumeApiService.java
- server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
- server/src/main/java/org/apache/cloudstack/storage/volume/VolumeImportUnmanageManagerImpl.java
- server/src/main/java/org/apache/cloudstack/vm/UnmanagedVMsManagerImpl.java
- server/src/test/java/com/cloud/storage/VolumeApiServiceImplTest.java
- server/src/test/java/org/apache/cloudstack/storage/volume/VolumeImportUnmanageManagerImplTest.java
- server/src/test/java/org/apache/cloudstack/vm/UnmanagedVMsManagerImplTest.java
This PR checks and updates the pools in the order of disks (avoids update by position, which is the unit number in the disk controller [ide / scsi]).
Fixes #10404
Manually tested VM (Default CentOS VM) import from VMware to KVM using NFS secondary storage.
> VMware import issue fix - check and update pools in the order of disks

- server/src/main/java/com/cloud/alert/AlertManagerImpl.java
- server/src/main/java/com/cloud/bgp/BGPServiceImpl.java
- server/src/test/java/com/cloud/alert/AlertManagerImplTest.java
Fixes:
* NPE when dcId is null or 0L on sending an alert.
* Exception during logging in BGPServiceImpl
<details><summary>Generated summary</summary>
<p>
This pull request includes several changes to the `AlertManagerImpl` and `BGPServiceImpl` classes to improve code clarity and functionality. The most important changes involve the handling of data center IDs and the logging of AS number allocations.
* [`server/src/main/java/com/cloud/alert/AlertManagerImpl.java`](diffhunk://#diff-ee21d4fc280319eeea85172bf682ea914ab4c20c8a8eb2204f9b3c6a02fbdcabR741-R748): Added a new variable `dcId` to handle data center IDs more effectively, replacing direct calls to `dataCenter.getId()`. [[1]](diffhunk://#diff-ee21d4fc280319eeea85172bf682ea914ab4c20c8a8eb2204f9b3c6a02fbdcabR741-R748) …
> Fixup alerting and logging error in BGPServiceImpl

- plugins/backup/veeam/src/main/java/org/apache/cloudstack/backup/VeeamBackupProvider.java
> Veeam: set backed_volumes for each backup

- engine/schema/src/main/java/com/cloud/usage/dao/UsageNetworksDaoImpl.java
- engine/schema/src/main/java/com/cloud/usage/dao/UsageVpcDaoImpl.java
- usage/src/main/java/com/cloud/usage/UsageManagerImpl.java
This PR fixes some inconsistencies which results in Usage generating usage records when it should not, namely:
- Duplicated entries in the networks helper table, resulting in duplicated usage record generation;
- Port forwarding helper entries are never removed, resulting in removed port forwarding rules generating usage records;
- Load balancer helper entries are never removed, resulting in removed load balancer rules generating usage records;
- VM snapshot helper entries are never removed, resulting in removed VM snapshots generating usage records;
- Helper entries for volumes in the secondary storage are never removed after the volume gets attached to a VM, resulting in secondary storage usage records being generated for volumes that are not in the secondary storage anymore.
1. I …
> Fix inconsistencies that result in Usage generating usage records when it should not

- ui/public/locales/en.json
- ui/src/views/tools/SelectVmwareVcenter.vue
- vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/BaseMO.java
This PR...
Fixes: #10412
in local UI pointing to a lab env
> migrate Vmware to KVM ui issues

- plugins/hypervisors/kvm/src/main/java/org/apache/cloudstack/utils/linux/KVMHostInfo.java
This PR ads two additional methods to detect cpu speed on kvm hosts. This will improve the speed detection on AMD Epyc cpu's. For cpu's where the Ghz is in the model name no change will occur. For other cpu's the detected cpu speed ca change to the max Mhz of the cpu. 
1. A match on the `CPU max MHz` value from lscpu
2. An additional sysfs file `scaling_max_freq`
Fixes: #6914 
Tested on a kvm host with an AMD EPYC 7601 cpu. 
* With normal agent start the cpu speed is detected as the expected 2200Mhz.
* Removed the cpu max Mhz line from the lscpu output and restarted agent. The detected speed is still the expected 2200Mhz.
On an kvm centos8 vm without the lscpu matches and neither file the agent still falls back on host capabilities.
> Add cpu speed detection methods

- plugins/outofbandmanagement-drivers/ipmitool/src/main/java/org/apache/cloudstack/outofbandmanagement/driver/ipmitool/IpmitoolOutOfBandManagementDriver.java
- plugins/outofbandmanagement-drivers/ipmitool/src/main/java/org/apache/cloudstack/outofbandmanagement/driver/ipmitool/IpmitoolWrapper.java
This PR fixes a logging of IPMI passwords
> ipmi: extra log sanitation

- engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
In Java, the operator and has a higher precedence than the operator or. This caused the method `handleUnsuccessfulExpungeOperation` to execute even when the `hostId` or `lastHostId` value was `null`, allowing CloudStack to send a command to a host that doesn't exist.
This PR fixes this verification logic adding parenthesis to ensure the method will not execute when the value of the parameter `hostId` is `null`.
To reproduce this error you need to deploy a VM with a tag with no matches and then try to expunge it.
Through debug mode I tested different values for `finalizeExpungeCommands`, `nicExpungeCommands` and `hostId` and I checked that it is not possible to execute the method when `hostId` is null or when both of the command lists are empty.
> Fix hostId verification on unsuccessful expunge operation

- engine/orchestration/src/main/java/com/cloud/vm/VirtualMachinePowerStateSyncImpl.java
- engine/orchestration/src/test/java/com/cloud/vm/VirtualMachinePowerStateSyncImplTest.java
Fixes #10406
VMs were not moving to Stopped state when PowerReportMissing is processed.
> engine/orchestration: fix missing vm powerstate update vm state

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
This PR ensures that the cpu shares value is never < 2 to be compatible with Libvirt versions before 9.1.0.
It turned out that the older libvirt versions, such as Ubuntu 22.04 libvirt 8.0.0 has the hardcoded range of allowed cpu shares values for both cgroupv1 and cgroupv2, which is 2-262144. 
This range enforcement was removed in Libvirt 9.1.0, see: https://github.com/libvirt/libvirt/commit/38af6497610075e5fe386734b87186731d4c17ac
If a host has lots of cores, and the huge CPU overprovisioning factor is set, then the computed shares value can become 1.
In such case, the following exception is generated on the Cloudstack Agent during provisioning:
`org.libvirt.LibvirtException: unsupported configuration: Value of cputune 'shares' must be in range [2, 262144]`
We noticed it when tried to …
> fix: enforce the minimum cgroup cpu shares value to 2

- ui/src/components/view/ListView.vue
- ui/src/config/section/network.js
In the Public IP Addresses UI section, the options to release reserved IPs (`releaseIpAddress` API) and disassociate IPs (`disassociateIpAddress` API) are always available through group actions, regardless of the public IP's state. Additionally, the option to disassociate IPs is available for IPs in use by system VMs, both through group actions and `dataView`.
This PR fixes these UI bugs. Furthermore, a label, similar to the existing ones for `source-nat` and `static-nat`, was created to indicate that a public IP is in use by a system VM. Lastly, the `allocated` column in the `ListView`, that represents the datetime an IP was allocated, is now parsed and formatted according to the user's timezone.
- `disassociateIpAddress` through group actions:
- `releaseIpAddress` through group actions: …
> UI: Fixes and minor enhacements to the Public IP Addresses section

- api/src/main/java/org/apache/cloudstack/backup/BackupProvider.java
- plugins/backup/dummy/src/main/java/org/apache/cloudstack/backup/DummyBackupProvider.java
- plugins/backup/nas/src/main/java/org/apache/cloudstack/backup/NASBackupProvider.java
- plugins/backup/networker/src/main/java/org/apache/cloudstack/backup/NetworkerBackupProvider.java
- plugins/backup/veeam/src/main/java/org/apache/cloudstack/backup/VeeamBackupProvider.java
This PR solves merge problems in the backup framework and providers.
> resolve merge problems in the backup framework

- api/src/main/java/com/cloud/storage/MigrationOptions.java
- engine/storage/datamotion/src/main/java/org/apache/cloudstack/storage/motion/KvmNonManagedStorageDataMotionStrategy.java
- engine/storage/datamotion/src/main/java/org/apache/cloudstack/storage/motion/StorageSystemDataMotionStrategy.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java
> kvm: fix volume migration across cluster-scope pools

- engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
- server/src/main/java/com/cloud/api/ApiDBUtils.java
This PR fixes: #10473 
This seems to be a regression in 4.20, where in we check if the disk offering is suitable for the VM based on the host/cluster/pod it is on. But for a VM that hasn't yet been started, these parameters aren't yet set, as the VM is just created in the DB.
Prior fix:
Post fix:
> Fix listing disk offerings for newly created VMs that haven't yet been started

- ui/public/locales/en.json
- ui/public/locales/pt_BR.json
- ui/src/config/section/infra/hosts.js
- ui/src/views/infra/ChangeHostPassword.vue
Currently is possible to change the host's password by using the `updateHostPassword` API; however, this option is not available in the UI.
This PR adds the option to change the host's password via UI.
In a local environment, I checked that the new option was available and tried to change the password using the new form. Looking the database I verified that the password changed.
I also forced some exceptions, like by using a wrong username as a parameter. Everything worked as expected.
> UI: Add change host password

- test/integration/plugins/linstor/test_linstor_volumes.py
make tests easier to run and without modifying the test to match the correct system. Also add tests for volume and vm instance snapshots. Improve runtime by ~6 minutes.
> linstor: improve integration-tests

- ui/src/config/section/storage.js
- ui/src/views/storage/CreateTemplate.vue
This PR fixes: https://github.com/apache/cloudstack/issues/10301
It attempts to combine the create template Form to be used for both create template from volume as well as snapshot and also lists only those accounts belonging to the domain selected.
> UI: Filter accounts by domain while creating templates - from Volume / Snapshot

- ui/src/views/offering/AddDiskOffering.vue
When a Disk Offering is created through UI, CloudStack passes the `isMirrored` value as a parameter. However, the `createDiskOffering` API does not have this parameter.
Therefore, the UI was changed in order to not send the `isMirrored` parameter to the `createDiskOffering` API.
After the changes, a Disk Offering was created through UI and the `isMirrored` parameter was no longer being send in the request.
> Remove isMirrored parameter when creating a disk offering through UI

- ui/public/index.html
- ui/src/locales/index.js
- ui/src/main.js
This will add a randomised timestamp when fetching config.json and locale i18n files, to avoid using cached `json` resources. This will address cases when the UI has newer json files (pkgs upgraded/updated).
Fixes #9985
Tested by checking UI devtools:
> ui: do not cache config.json and locale files

- server/src/main/java/com/cloud/alert/AlertManagerImpl.java
The method that generates the alert e-mail contains code repeated in many places and is not formatted properly.
This PR intends to refactor this method.
I changed the value of many  notification threshold  global settings to 0% (`zone.vlan.capacity.notificationthreshold` and `cluster.memory.allocated.capacity.notificationthreshold` for example). Then I checked through the logs that the messages were created correctly.
```
2024-03-25T18:22:03,626 WARN  [c.c.a.AlertManagerImpl] (CapacityChecker:[ctx-73e84063]) (logid:0ebef2c9) alertType=[4] dataCenterId=[1] podId=[null] clusterId=[null] message=[System Alert: Number of unallocated virtual network public IPs is low in availability zone [zn-test].].
2024-03-25T18:22:04,487 DEBUG [c.c.a.AlertManagerImpl] (CapacityChecker:[ctx-73e84063]) …
```
> Refactor alert email generation method

- plugins/integrations/prometheus/src/main/java/org/apache/cloudstack/metrics/PrometheusExporterImpl.java
This PR speeds up Prometheus exporter reply generation by ensuring the same host tag is not polled multiple times.
It utilizes `HashSet` instead of `ArrayList` to store the host tags, therefore deduplicates the tags when they are present on multiple hosts.
It fixes two bugs:
1. Prevents duplication of the `cloudstack_vms_total_by_tag{filter="<vm state>", zone="<zonename>", tags="<tagname>"}` in the reply.
2. Speeds up forming Prometheus exporter reply on large Cloudstack installations when multiple hosts with repeating tags are used, for example 200 hosts but only 5 unique host tags. The time to get the Prometheus exporter reply has reduced from 4.5 mins to 26 seconds in my setup.
1. Take a large Cloudstack installation with > 100 hosts
2. Populate these hosts with the several unique tags …
> fix: prometheus: don't poll the same tag multiple times

- ui/public/config.json
- ui/src/layouts/UserLayout.vue
This PR allows setting a custom footer for resetPassword page in the UI.
<details><summary>Generated summary</summary>
<p>
This pull request includes updates to the login and reset password footer configurations in the UI. The changes ensure that the reset password footer is properly displayed when users are on the reset password page.
Changes to footer configurations:
* [`ui/public/config.json`](diffhunk://#diff-bb1687dac7fe3f2df457cdc9d617176931d9f81dd7d815528f6e172da6b3fb89R16): Added a new configuration option `resetPasswordFooter` to the JSON file.
* [`ui/src/layouts/UserLayout.vue`](diffhunk://#diff-2f8a480943dbe219bf6f9ba7d1c2cdbf1fb2a422be95ab474bb09b2552cda75fL40-R42): Updated the footer logic to display the `resetPasswordFooter` when the user is on the reset password page, and …
> UI: Allow custom footer in password reset page

- server/src/main/java/com/cloud/network/NetworkServiceImpl.java
- server/src/test/java/com/cloud/network/NetworkServiceImplTest.java
This PR fixes #10001
- update global setting for public/private mtu from 1500 to 1450
- create vpc, the public/private mtu is 1450/1450
- create vpc tier
expected result: public/private mtu is 1450/1450
actual result: public/private mtu is 1450/1500
> VPC: fix private mtu of vpc tier

- plugins/hypervisors/kvm/src/main/java/com/cloud/ha/KVMInvestigator.java
Currently when kvm host does not have NFS, it is determined as Disconnected during agent/vm investigation.
The other investigators are not performed.
This PR fixes the issue so that the other investigators will be performed.
Below is an example of the investigation process with this PR
(on the kvm host, I added a firewall rule to drop the packets to port 8250 of management server)
> KVM: return null state instead of Disconnected when investigate a host without NFS

- plugins/hypervisors/kvm/src/main/java/com/cloud/ha/KVMInvestigator.java
Currently when investigate a kvm host, it does not consider the state of cluster-wide pools, so the result is not correct.
There is no issue with zone-wide storage pools, as in the method `findZoneWideStoragePoolsByHypervisor` it has
```
sc.and(sc.entity().getStatus(), Op.EQ, Status.Up);
```
> kvm: find cluster-wide pools only in Up state when investigate a host

- plugins/storage/volume/linstor/CHANGELOG.md
- plugins/storage/volume/linstor/src/main/java/org/apache/cloudstack/storage/datastore/driver/LinstorPrimaryDataStoreDriverImpl.java
This PR deletes temporary Linstor -rst resources before trying to do the snapshot backup on non-hyperconverged setups.
If a -rst resource wasn't deleted because of a failed copy, a reoccurring snapshot attempt couldn't be done, because there was still the "old" -rst resource. To prevent this always try to remove the -rst resource before, if it doesn't exist it is a noop.
Linstor cluster  hyperconverged and non hyperconverged, doing snapshots.
> linstor: try to delete -rst resource before snapshot backup

- server/src/main/java/com/cloud/server/StatsCollector.java
Currently, the Stats Collector can throw an arithmetic exception when trying to divide by zero if `interval = 0`.
This PR fixes this issue by setting the `loadHistory.add` value to zero when the `interval` variable is equal to zero.
In debug mode, I tested by setting the `interval` value to zero. Before the changes, an arithmetic exception was thrown. After the changes, I got no exception and could check that the value added to `loadHistory` was equal to `0`.
> Fix Stats Collector to not divide by zero

- plugins/backup/veeam/src/main/java/org/apache/cloudstack/backup/VeeamBackupProvider.java
- server/src/main/java/org/apache/cloudstack/backup/BackupManagerImpl.java
This PR fixes https://github.com/apache/cloudstack/issues/9896
Issue was that veeam /jobs/ api was being sent with 'null' value.
Tested that backup offering was removed without any error logs
> Veeam BnR : Fix for error in remove backup offering

- api/src/main/java/org/apache/cloudstack/api/command/user/vm/ListVMsCmd.java
- server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
- ui/src/config/section/compute.js
This PR fixes issue brought up here: https://github.com/apache/cloudstack/discussions/10549#discussioncomment-12487399
Where currently it's not possible to list all VMs associated to a user data.
Before fix:
Incorrect as the userdata is only associated with 1 VM. The userdata parameter of the listVMs API is to control whether or not to return the userdata as part of the listVms response
After fix:
> List only VMs associated to a userdata

- server/src/main/java/com/cloud/network/router/NetworkHelperImpl.java
DeploymentPlanner.addPod takes long value while
VmInstanceVO.getPodIdToDeployIn returns a Long value which can be null when the VM is never started.
Error seen while doing consecutive VPC restarts with cleanup,
```
at com.cloud.network.router.NetworkHelperImpl.startVirtualRouter(NetworkHelperImpl.java:448)
at com.cloud.network.router.NetworkHelperImpl.startRouters(NetworkHelperImpl.java:384)
at org.apache.cloudstack.network.router.deployment.RouterDeploymentDefinition.deployVirtualRouter(RouterDeploymentDefinition.java:209)
at com.cloud.network.element.VpcVirtualRouterElement.prepare(VpcVirtualRouterElement.java:307)
at org.apache.cloudstack.engine.orchestration.NetworkOrchestrator.prepareElement(NetworkOrchestrator.java:1756)
at …
```
> server: fix npe during start vr edge case

- engine/storage/volume/src/main/java/org/apache/cloudstack/storage/datastore/lifecycle/BasePrimaryDataStoreLifeCycleImpl.java
- plugins/storage/volume/linstor/CHANGELOG.md
- plugins/storage/volume/linstor/src/main/java/org/apache/cloudstack/storage/datastore/lifecycle/LinstorPrimaryDataStoreLifeCycleImpl.java
- plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/lifecycle/ScaleIOPrimaryDataStoreLifeCycle.java
Somehow deleteDatastore was never implemented, that meant: templates haven't been cleaned up on datastore delete and also agents have never been informed about storage pool removal.
Fixes: #10465
Adding/removing Linstor primary storage.
> linstor: implement missing deleteDatastore

- server/src/main/java/com/cloud/resource/ResourceManagerImpl.java
> deal with null return for create deployment plan for maintenance

- server/src/main/java/org/apache/cloudstack/agent/lb/IndirectAgentLBServiceImpl.java
This PR fixes to propagate updated management servers list and lb algorithm in host and indirect.agent.lb.algorithm settings respectively, to systemvm agents.
Noticed updated management servers list is not propagated to the system VMs during testing, it's regression from https://github.com/apache/cloudstack/pull/9840.
Updated management servers list and lb algorithm in host andd indirect.agent.lb.algorithm settings, and checked in the system vm configuration file (/usr/local/cloud/systemvm/conf/agent.properties).
> Fix to propagate updated management servers list and lb algorithm in host and indirect.agent.lb.algorithm settings resp, to systemvm agents

- framework/config/src/main/java/org/apache/cloudstack/framework/config/impl/ConfigDepotImpl.java
- framework/config/src/test/java/org/apache/cloudstack/framework/config/impl/ConfigDepotImplTest.java
Using a simple hyphen as a delimiter for config cache key can lead to ambiguity if the “name” field itself contains hyphens. To address this, a Ternary object of configkey name, scope and scope ID is used as the config cache keys.
> framework-config: improve configkey caching

- framework/quota/src/main/java/org/apache/cloudstack/quota/activationrule/presetvariables/GenericPresetVariable.java
- framework/quota/src/main/java/org/apache/cloudstack/quota/activationrule/presetvariables/Resource.java
- server/src/main/java/org/apache/cloudstack/storage/heuristics/presetvariables/GenericHeuristicPresetVariable.java
- server/src/test/java/org/apache/cloudstack/storage/heuristics/presetvariables/AccountTest.java
- server/src/test/java/org/apache/cloudstack/storage/heuristics/presetvariables/DomainTest.java
- server/src/test/java/org/apache/cloudstack/storage/heuristics/presetvariables/GenericHeuristicPresetVariableTest.java
- server/src/test/java/org/apache/cloudstack/storage/heuristics/presetvariables/SecondaryStorageTest.java
- server/src/test/java/org/apache/cloudstack/storage/heuristics/presetvariables/SnapshotTest.java
- server/src/test/java/org/apache/cloudstack/storage/heuristics/presetvariables/TemplateTest.java
- server/src/test/java/org/apache/cloudstack/storage/heuristics/presetvariables/VolumeTest.java
The secondary storage selectors feature is not working in the 4.20 and main branches.
PR #9873 changed the return of `org.apache.cloudstack.storage.heuristics.presetvariables.GenericHeuristicPresetVariable#toString`; however, as this method is used to build the secondary storage selection script, the changes made it stop working.
Here's how the script looked like before #9873:
```js
secondaryStorages = [{"id":"f7e21c42-f621-4412-8994-36e077f0faec","protocol":"nfs","totalDiskSize":104028176384,"usedDiskSize":47059042304,"name":"sec"}, {"id":"0d88afc2-93eb-4070-8fbf-d8909f62364d","protocol":"nfs","totalDiskSize":104028176384,"usedDiskSize":47059042304,"name":"sec-2"}]; snapshot = {"hypervisorType":"KVM","size":52428800,"name":"e"}; account = …
```
> Fix secondary storage selectors feature

- ui/src/config/section/compute.js
- ui/src/views/compute/StartVirtualMachine.vue
> ui: fix considerlasthost for start vm

- ui/src/views/network/VpcTiersTab.vue
This PR fixes a UI issue when create vpc tier
without this PR, only two offerings are listed
- "Offering for Isolated Vpc networks with Source Nat service enabled and LB service Disabled"
- "Offering for Isolated Vpc networks with Internal LB support"
with this PR, three offerings are listed, the new one is
- "Offering for Isolated Vpc networks with Source Nat service enabled"
> UI: fix list of vpc network offerings

- INSTALL.md
Description
This PR updates INSTALL.md to include essential setup commands for first-time contributors, ensuring a smoother installation process and reducing setup errors.
Changes:
Added mysql_secure_installation to improve MySQL security.
Included steps for setting up the CloudStack UI (npm install, npm build, npm start).
Clarified the requirement to set CS_URL=http://localhost:8080/client in .env.local for API communication.
Explicitly mentioned that the management server runs at http://localhost:5050/.
These improvements will make onboarding easier and reduce setup issues.
#10590 
Types of changes
Breaking change (fix or feature that would cause existing functionality to change)
New feature (non-breaking change which adds functionality)
Bug fix (non-breaking change which fixes an …
> In Install.md->CloudStack UI Commands(npm)

- ui/src/components/view/InfoCard.vue
- ui/src/config/section/account.js
The `InfoCard` component on the account details pages provides several buttons to view the resources associated to an account. However, currently, there isn't a button to view an account's ISOs.
Therefore, this PR, similarly to what has been done on #10425, adds the `View ISOs` button in the accounts `InfoCard` component. Additionally, as mentioned on https://github.com/apache/cloudstack/issues/10393#issuecomment-2666531345, support for filtering templates and ISOs by domain will be handled on separate PRs.
Verified that when selecting the `View ISOs` button in an account's `InfoCard`, the UI redirects the user to the following URL: `/iso?isofilter=self&filter=self&account=<account>&domainid=<domain-uuid>`.
> UI: Add `View ISOs` button to the account details pages

- ui/src/config/section/infra/hosts.js
- ui/src/views/infra/HostEnableDisable.vue
This PR... fixes #10604 When a user disables/Enables a host from the Infrastructure - Host tab (List view), the UI does not refresh automatically to reflect the new disabled state of the host. The API call succeeds, but the user doesn't see the state change until they manually refresh the page.
#10604 
https://github.com/user-attachments/assets/f0b23269-9dbc-4c6e-addb-92a93de55219
> Host status auto refresh

- agent/bindir/cloud-setup-agent.in
- agent/bindir/libvirtqemuhook.in
- client/bindir/cloud-setup-management.in
- python/lib/cloudutils/serviceConfig.py
- python/lib/cloudutils/syscfg.py
- python/lib/cloudutils/utilities.py
This adds support for Fedora 40 and (upcoming) EL10 distro to be used as mgmt/usage server, mysql/nfs & KVM host. Python3 version has changed to 3.12.9 which isn't automatically determining the python-path.
This is experimental tech-preview support to ensure packages & installation works. Actual support & testing is due after EL10's release around mid 2025.
Fixes #10494
See https://github.com/apache/cloudstack/issues/10494#issuecomment-2696680066
> Preview-Experimental Support EL10 as Management Server and KVM host

- plugins/metrics/src/main/java/org/apache/cloudstack/metrics/MetricsServiceImpl.java
This PR optimizes the way the hosts are retrieved from the database to speed up `listZonesMetrics` and `listClustersMetrics` calls on large (and slow) databases.
Instead of retrieving the Host objects by the cluster, and then retrieving HostJoinVO for every host which results to SQL queries `SELECT ... FROM host_view WHERE host.id = <id>`, it retrieves the list of HostJoinVO by cluster and the host type.
Additionally, it removes the method `private Double findRatioValue(final String value)` as it seems to be unused.
Here are the test results for a big loaded platform with 200 hosts:
A mgmt server with vanilla 4.20:
```
... output omitted ..
real	1m51.370s
user	0m0.219s
sys	0m0.026s
```
A mgmt server with these changes applied:
```
... output omitted ...
real	0m2.024s
user	0m0.220s
sys …
```
> enhancement: Optimize listZonesMetrics and listClustersMetrics call performance

- framework/cluster/src/main/java/com/cloud/cluster/ClusterManagerImpl.java
This handles an NPE case for when management server host status is not found in the DB, when stopping the cluster manager.
On Mac OS, the stat collector doesn't run well as the code assumes to be running on Linux. On non-Linux env, this is easily reproducible.
> framework/cluster: fix NPE for ms-host status when mgr stops

- engine/schema/src/main/java/com/cloud/upgrade/SystemVmTemplateRegistration.java
- scripts/storage/secondary/setup-sysvm-tmplt
- server/conf/cloudstack-sudoers.in
This PR updates setup-sysvm-tmplt script, to run cmds accessing destdir with sudo. These cmds in this script are are added to sudoers file, to allow for cloudstack service user 'cloud' to access destdir.
> Updated setup-sysvm-tmplt script, to run cmds accessing destdir with sudo

- api/src/main/java/org/apache/cloudstack/api/response/StoragePoolResponse.java
- engine/storage/volume/src/main/java/org/apache/cloudstack/storage/datastore/provider/DefaultHostListener.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtCreatePrivateTemplateFromVolumeCommandWrapper.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtGetVolumesOnStorageCommandWrapper.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/IscsiAdmStorageAdaptor.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMPhysicalDisk.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStoragePoolManager.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/LibvirtStorageAdaptor.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/LibvirtStoragePool.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/StoragePoolInformation.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/storage/KVMPhysicalDiskTest.java
- plugins/storage/volume/storpool/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/StorPoolDownloadVolumeCommandWrapper.java
- server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
- ui/public/locales/en.json
- ui/public/locales/pt_BR.json
- ui/src/components/view/DetailsTab.vue
- ui/src/config/section/infra/primaryStorages.js
- ui/src/views/infra/AddPrimaryStorage.vue
- ui/src/views/infra/zone/ZoneWizardAddResources.vue
- ui/src/views/infra/zone/ZoneWizardLaunchZone.vue
This PR adds support for Ceph erasure code pools, allowing users to specify the data pool required for using this type of Ceph pool.
Details of the data pool in the UI
The following tests were executed to verify this patch; tests were executed on replicated pools as well to check if this patch would interfere in it.
- Deploy of VM in a Ceph replicated pool
- Deploy of VM in a Ceph erasure code pool
- Volume resize in a Ceph replicated pool
- Volume resize in a Ceph erasure code pool
- Live migration of VM with volume allocated in a Ceph replicated pool
- Live migration of VM with volume allocated in a Ceph erasure code pool
- Attach, mount and utilization of volume in a Ceph replicated pool
- Attach, mount and utilization of volume in a Ceph erasure code pool
- Template creation from a …
> Add support to RBD erasure code pools

- ui/src/views/dashboard/UsageDashboard.vue
Currently, the dashboard for projects faces some inconsistencies for the amount of resources consumed by the project. They can be noticed when accessing the project's view, with an account that is not in the same domain as the project is.
Therefore, in scenarios in which a `RootAdmin` accesses the dashboard of a project that belongs to any subdomain of the `ROOT` domain (e.g. `ROOT/d1`), the dashboard will display the project's storage metrics as `NaN` and `undefined`  and the compute metrics will be omitted:
The root cause of the bug is that, when the project's attributes are fetched from the `listProjects` API, the parameter `listall` is not specified:
https://github.com/apache/cloudstack/blob/ee94ae575b7bb28d3350b049454b0026db85c7d1/ui/src/views/dashboard/UsageDashboard.vue#L461-L469 …
> UI: Fix projects metrics on dashboard

- plugins/storage/volume/adaptive/README.md
- plugins/storage/volume/storpool/README.md
- tools/docker/README.md
- tools/marvin/marvin/misc/build/CI.md
- ui/README.md
- ui/docs/full-test-plan.template.md
- ui/docs/smoke-test-plan.template.md
- ui/src/style/README.md
This PR fixes mainly spelling in Markdown docs files only.
Markdown changes only.  Some good clean ups.  Hoping to get merged quicker than usual.
> docs: fixes grammar and spelling in Markdown files only

- test/integration/component/test_acl_sharednetwork_deployVM-impersonation.py
This PR fixes a typo in one file in many places. Really a docs PR.
> test(python): fix code comment typo; Valiate -> Validate

- ui/src/components/view/ResourceLimitTab.vue
Currently, it is not possible to change the limit of projects that a domain and account can have through the UI. Therefore, this PR proposes to add this field to the `Configure Limits` form of domains and accounts.
- Verified that it was possible to modify the maximum amount of projects that an account can have through the UI
- Verified that it was possible to modify the maximum amount of projects that a domain can have through the UI
- Verified that the `Max. projects` field was not available on the projects `Configure Limits` form:
> UI: Allow setting account and domain maximum amount of projects through the UI

- ui/src/config/section/network.js
This PR fixes a regression on the UI in which the AS Numbers menu tab was removed, caused by the merge commit: https://github.com/apache/cloudstack/commit/34d2a3bc86d89d93fd50973844c13be37d51f374 (check network.js file diff)
Before:
After:
> UI: Restore AS Numbers and IPv4 Subnets menus

- server/src/main/java/com/cloud/api/ApiServer.java
- server/src/main/java/com/cloud/api/ApiServlet.java
This PR 
Fixes: #10565 
started an env and monitorred `/var/log/cloudstack/management/apilog.log`
> undo removal of accessLogger and deal with some warnings

- usage/src/main/java/com/cloud/usage/UsageManagerImpl.java
This PR...
Fixes: #10646 
using
```
zgrep "configs = “ /var/log/cloudstack/usage/usage.log*
```
before: a full config including all parameters
after: no hits
> Usage server: remove logging of prameters including secret keys

- server/src/main/java/com/cloud/storage/snapshot/SnapshotManagerImpl.java
- server/src/test/java/com/cloud/storage/snapshot/SnapshotManagerTest.java
- utils/src/test/java/com/cloud/utils/UriUtilsTest.java
On volume snapshot revert, if its logical size was changed after the snapshot creation, its size is updated to the previous one, yet, no event is launched on the Usage server pointing to this change.
This behavior was modified, so that a RESIZE event is launched on the Usage server, if the volume's size has been changed after a snapshot revert.
1. A volume snapshot was created;
2. The resize operation was done;
3. The snapshot was reverted;
4. On the `usage_event` table the `VOLUME.RESIZE` event was launched with the previous size.
> Launch RESIZE event on volume snapshot revert

- api/src/main/java/org/apache/cloudstack/api/command/user/iso/ExtractIsoCmd.java
- api/src/main/java/org/apache/cloudstack/api/command/user/template/ExtractTemplateCmd.java
- api/src/main/java/org/apache/cloudstack/api/command/user/volume/ExtractVolumeCmd.java
- server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
- server/src/main/java/com/cloud/template/TemplateManagerImpl.java
When the download of templates, ISOs and volumes is finished, a download link is generated and displayed to end users in a notification. However, in situations in which the download process takes a large amount of time, the user's authentication session may be expired by inactivity and, thus, the reference to the link gets lost.
Therefore, this PR proposes to add the templates, ISOs and volumes download links to the details of the `TEMPLATE.EXTRACT`, `ISO.EXTRACT` and `VOLUME.EXTRACT` events, respectively. As a consequence of that, in scenarios that users sessions are expired when downloading such resources, the event details can be accessed by users to retrieve the download link.
- `TEMPLATE.EXTRACT` event details:
- `ISO.EXTRACT` event details:
- `VOLUME.EXTRACT` event details:
- …
> Add download link of volumes, templates and ISOs to the download event details

- plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java
- plugins/hypervisors/vmware/src/main/java/org/apache/cloudstack/storage/motion/VmwareStorageMotionStrategy.java
- server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
This PR fixes https://github.com/apache/cloudstack/issues/9881 by handling the migrate volume answer result properly.
1. Deploy a VM on CloudStack
2. Stop the VM
3. Via the vCenter, remove the VM from the inventory - leaving behind the VM's disk
4. Attempt Volume migration, this operation failed and CS reports the same error.
> Fix volume migration failure handling

- server/src/main/java/com/cloud/network/NetworkServiceImpl.java
> server: check startip and endip of shared network

- ui/src/components/view/InfoCard.vue
- ui/src/views/image/IsoZones.vue
- ui/src/views/image/TemplateZones.vue
This PR moves the creation date of a template to the Zones tab on the template view and removes the zone field on the left side menu. This behavior is changed to support templates on multiple zones, which should display the different creation dates for each zone. These are correctly displayed on the Template view -> Zones tab.
Fixes: #10599
> UI: Move templates creation date to the Zones tab

- engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
- engine/schema/src/main/java/com/cloud/vm/VMInstanceVO.java
- server/src/main/java/com/cloud/ha/HighAvailabilityManagerImpl.java
This PR fixes 3 issues
- set correct hostId of HA work for vm migration
- skip migration job if vm is running on a different host
- wait 10 seconds for all modules are loaded
The issues are found when
- put host to maintenance
- restart management server
> HA: set correct hostId of HA work for vm migration

- server/src/main/java/com/cloud/template/HypervisorTemplateAdapter.java
… on any zone
This PR...
Fixes: #10600
> only clean details and annotations when this template no longer exists

- plugins/shutdown/src/main/java/org/apache/cloudstack/api/response/ReadyForShutdownResponse.java
- plugins/shutdown/src/main/java/org/apache/cloudstack/shutdown/ShutdownManagerImpl.java
Fixes #10669
Creates shutdown response to use management server UUID than internal DB ID.
> plugin/shutdown: use mgmt server uuid in the shutdown response

- systemvm/debian/opt/cloud/bin/cs/CsDhcp.py
This PR fixes #10733 
prior to this change, dnsmasq listens on `0.0.0.0:53`, so other services (e.g haproxy) cannot use port 53 of public IPs.
with this change, dnsmasq listens only on the guest interface
```
root@r-1366-VM:~# netstat -an |grep :53
tcp        0      0 172.16.1.1:53           0.0.0.0:*               LISTEN     
udp        0      0 172.16.1.1:53           0.0.0.0:*    
```
> VR: add bind-interfaces to /etc/dnsmasq.d/cloud.conf

- server/src/main/java/com/cloud/network/IpAddressManagerImpl.java
- server/src/main/java/com/cloud/network/vpc/VpcManagerImpl.java
Currently, when enabling static NAT or adding PF and LB rules to VPC public IPs, Apache CloudStack wrongly validates whether the account reached the limit of consumed public IPs. As a consequence of that, accounts that are with their public IP quota completely used, for example, are unable to execute such operations on VPCs public IPs.
This PR fixes this bug by removing the validation of the amount of acquired public IPs when performing the above-mentioned operations. This validation has been moved to the method `com.cloud.network.IpAddressManagerImpl#markPublicIpAsAllocated`, in which the increment of resource count for public IPs is effectively performed.
---
Fixes #10566
1. Created an `User` account, called `u1`.
2. Configured its limit of public IP addresses to 2.
3. Created a VPC …
> Remove the validation of the amount of acquired public IPs when enabling static NAT, adding PF and LB rules on VPC public IPs

- plugins/host-allocators/random/src/main/java/com/cloud/agent/manager/allocator/impl/RandomAllocator.java
- server/src/main/java/com/cloud/agent/manager/allocator/impl/FirstFitAllocator.java
This PR fixes: #10598 
While https://github.com/apache/cloudstack/pull/8611 seems to have fixed this issue in 4.19.1, I believe it got lost in the process of resolving merge conflicts / forward merging into 4.20.0.
> Fix issue with allocator not considering subsequent clusters

- plugins/hypervisors/ovm/pom.xml
- plugins/hypervisors/xenserver/pom.xml
- plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/discoverer/XcpServerDiscoverer.java
- plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/CitrixResourceBase.java
- plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/XenServerConnectionPool.java
- plugins/hypervisors/xenserver/src/main/java/com/xensource/xenapi/ConnectionNew.java
- pom.xml
> xen-api: use https://mvnrepository.com/artifact/com.citrix.hypervisor/xen-api

- ui/public/locales/en.json
- ui/src/components/view/ListView.vue
- ui/src/components/view/SettingsTab.vue
- ui/src/main.js
- ui/src/utils/plugins.js
- ui/src/views/setting/ConfigurationValue.vue
- ui/tests/common/index.js
Addresses point 1 of #6880
Adds a confirmation dialogue before resetting configurations
> ui: confirm on reset configurations

- plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/datastore/driver/StorPoolPrimaryDataStoreDriver.java
This PR fixes the size of a template downloaded from secondary storage to StorPool.
manually
> Fix the size of a template downloaded from secondary storage

- server/src/main/java/com/cloud/resource/ResourceManagerImpl.java
In the absence of a SYSTEM type template for a zone, listing of templates can break.
Behaviour was change in #9840 but it would be better to find available hypervisors using existing hosts.
> server: fix available hypervisors listing for a zone

- server/src/main/java/com/cloud/network/NetworkServiceImpl.java
This PR... addresses the comments at https://github.com/apache/cloudstack/pull/10704/files#r2048392976
> Don't specify ipv6 ranges for shared network

- test/integration/smoke/test_certauthority_root.py
This PR fixes the simulator CI test test_certauthority_root.py
it does not work with python3
```
2025-04-18T10:43:58.5235913Z 2025-04-18 10:32:20,503 - CRITICAL - EXCEPTION: Failure:: ['Traceback (most recent call last):\n', '  File "/opt/hostedtoolcache/Python/3.10.17/x64/lib/python3.10/unittest/case.py", line 59, in testPartExecutor\n    yield\n', '  File "/opt/hostedtoolcache/Python/3.10.17/x64/lib/python3.10/unittest/case.py", line 591, in run\n    self._callTestMethod(testMethod)\n', '  File "/opt/hostedtoolcache/Python/3.10.17/x64/lib/python3.10/unittest/case.py", line 549, in _callTestMethod\n    method()\n', '  File "/home/runner/.local/lib/python3.10/site-packages/nose/failure.py", line 35, in runTest\n    raise self.exc_val.with_traceback(self.tb)\n', '  File …
```
> test: fix test_certauthority_root.py

- test/integration/smoke/test_scale_vm.py
This PR fixes consistent failure noticed on the test_scale_vm.py test suite:
https://github.com/apache/cloudstack/pull/10668#issuecomment-2800648764
Using the centos template as the Macchinina template registered with "Other Linux (64-bit)" does not have guest_os_details for min and max dynamic memory to be used during scaling by xenserver. Which results in failure of the test as it fails to meet the constraints of
```
0 <= memory-static-min(512MB) <= memory-dynamic-min(1024MB) <= memory-dynamic-max(1024MV) <= memory-static-max(512MB)
```
> Smoke tests: Xenserver - Fix consistent failure noticed on scale VM test

- api/src/main/java/com/cloud/vm/VmDetailConstants.java
- api/src/main/java/org/apache/cloudstack/query/QueryService.java
- engine/schema/src/main/resources/META-INF/db/schema-42000to42010.sql
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDefTest.java
- plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java
- plugins/hypervisors/vmware/src/test/java/com/cloud/hypervisor/vmware/resource/VmwareResourceTest.java
- server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
- ui/src/views/compute/DeployVM.vue
This PR adds the vTPM support for VMs on KVM and VMware.
Trusted Platform Module (TPM) is a standard for a secure cryptoprocessor, which can securely store artifacts used to authenticate the platform, including passwords, certificates, or encryption keys. TPM is required by recent Windows releases.
Virtual Trusted Platform Module (vTPM) is the software-based representation of physical TPM. CloudStack supports vTPM for instances running on KVM and VMware since 4.20.1.0 .
- Boot type and boot mode
On Vmware, the boot type must be set to UEFI. Boot mode can be SECURE (recommended) or LEGACY.
On KVM, it is recommended to set boot type to UEFI, and boot mode to SECURE. UEFI is required for some Windows versions.
- For VMs and templates on KVM
- Improvement: Support CPU mode/model for VMs on …
> vTPM: support KVM and VMware

- test/integration/smoke/test_cluster_drs.py
- test/integration/smoke/test_nonstrict_affinity_group.py
This PR fixes the consistent test failure noticed on the cluster drs test suite on the 4.19 and 4.20 health check PRs for XenServer/XCP-ng versions 8.0+.
https://github.com/apache/cloudstack/pull/10668#issuecomment-2816554283
This is because the template used - namely the built-in centos 5.6 template does not have PV drivers installed i.e., xenserver tools, thus migration of the VM fails with the following exception:
```
2025-04-22 05:13:01,446 DEBUG [c.c.a.m.D.Task] (DirectAgent-428:[ctx-8a11e226]) (logid:b6b3bd33) Seq 2-3585709728317048979: Executing request
2025-04-22 05:13:01,481 WARN  [c.c.h.x.r.XenServer650Resource] (DirectAgent-428:[ctx-8a11e226]) (logid:0348b8ac) Task failed! Task record:                 uuid: 15d12e85-9a6d-0a91-2662-ee82cd6215c2
nameLabel: Async.VM.pool_migrate …
```
> smoke tests: Fix cluster DRS & non-strict host affinity smoke test failures on XenServer / XCP-ng

- engine/components-api/src/main/java/com/cloud/agent/AgentManager.java
- engine/orchestration/src/main/java/com/cloud/agent/manager/AgentManagerImpl.java
- engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
- utils/src/main/java/com/cloud/utils/nio/NioConnection.java
This PR adds new config 'agent.connections.monitor.interval' (non-dynamic) to monitor and cleanup new agent connections, instead of using 'Wait' which is dynamic, and updates the monitor thread timeunit to secs, in sync with the earlier Wait config.
New agent connections monitor thread introduced here: https://github.com/apache/cloudstack/pull/9840
> Add new config (non-dynamic) for  agent connections monitor thread, and keep timeunit to secs (in sync with the earlier Wait config)

- plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/XenServerStorageProcessor.java
This PR fixes: #10756 
Fixes consistent test failure observed on Xenserver / XCP-ng
```
[root@ref-trl-8376-x-mol8-pearl-dsilva-marvin ~]# nosetests --with-xunit --xunit-file=results.xml --with-marvin --marvin-config=/marvin/ref-trl-8376-x-Mol8-pearl-dsilva-advanced-cfg -s -a tags=fix --hypervisor=Xenserver resource_names.py 
/usr/local/lib/python3.6/site-packages/paramiko/transport.py:32: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography will remove support for Python 3.6.
from cryptography.hazmat.backends import default_backend
==== Log Folder Path: …
```
> Xenserver smoke-test: Allow emojis to be accepted in volume name during volume creation

- server/src/test/java/org/apache/cloudstack/resource/ResourceCleanupServiceImplTest.java
This PR fixes ResourceCleanupService test for daylight saving time.
Fixes #10666 
Verified updated test.
> ResourceCleanupService test fix for daylight saving time

- python/lib/cloudutils/networkConfig.py
This PR uses 'ip route' command instead of 'route -n' command in networkConfig.py
`route` is provided by legacy `net-tools` package which is not installed by default in some distributions
`ip` is provided by `iproute2` package which is a dependency of cloudstack-agent package
the two commands have the same result
```
10.0.32.1 cloudbr0
10.0.32.1 cloudbr0
```
> cloudutils: use "ip route" command instead of "route -n" in networkConfig.py

- ui/src/config/section/infra/hosts.js
Currently, the hosts listing displays the number of end-user VMs allocated on each host. This PR proposes to also display the number of system VMs allocated on the hosts.
- Before:
- After:
- Accessed the hosts listing and verified that the number of system VMs allocated on the hosts was correctly displayed.
> UI: Display system VM count in hosts listing

- plugins/storage/object/ceph/src/main/java/org/apache/cloudstack/storage/datastore/driver/CephObjectStoreDriverImpl.java
- plugins/storage/object/ceph/src/test/java/org/apache/cloudstack/storage/datastore/driver/CephObjectStoreDriverImplTest.java
This PR fixes https://github.com/apache/cloudstack/issues/10044
```
AmazonS3 client = AmazonS3ClientBuilder.standard()
.enablePathStyleAccess()
.withCredentials(
new AWSStaticCredentialsProvider(
new BasicAWSCredentials(accessKey, secretKey)))
.withEndpointConfiguration(
new AwsClientBuilder.EndpointConfiguration(url, "auto"))
.build();
```
Using `auto` as the signingRegion in AwsClientBuilder forces the s3 client to infer region from the url and set it as LocationConstraint while sending the request which is not required for ceph and causes the issue.
`requestRegion = AwsHostNameUtils.parseRegion(requestEndpoint.getHost(), "s3");`
Location constraint was being set if the url starts with "s3." So a possible workaround if using this type of endpoint is to not use such kind of name for the …
> Ceph object store: Fix LocationConstraint error 

- ui/src/views/compute/EditVM.vue
This PR allows users to update VM name, etc of a VM in running state deployed in an advanced zone with security groups.
The form isn't pre-populated with the existing SG of the VM as doing so causes the API to send the securitygroupids of what is already set on the VM to the backend and that leads to the editVM operation failing as it believes that the SG is being attempted to be modified.
> UI: Allow editing a Running VM in an Advanced zone with security groups except for security group details

- engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/vmsnapshot/StorageVMSnapshotStrategy.java
- engine/storage/snapshot/src/test/java/org/apache/cloudstack/storage/vmsnapshot/VMSnapshotStrategyKVMTest.java
- server/src/main/java/com/cloud/storage/snapshot/SnapshotManagerImpl.java
- ui/src/config/section/compute.js
- ui/src/views/compute/CreateSnapshotWizard.vue
- ui/src/views/storage/TakeSnapshot.vue
This PR allows quiescevm and asyncbackup flags while taking volume snapshot from UI when these are supported for the volume, addresses #10106.
Also, updated snapshot forms to show quiescevm for VMware & KVM hypervisors.
Changes from ui/src/views/storage/TakeSnapshot.vue were removed in https://github.com/apache/cloudstack/pull/7873, re-added in this PR. Now, ui/src/views/compute/CreateSnapshotWizard.vue and ui/src/views/storage/TakeSnapshot.vue are in sync with respect to quiescevm and asyncbackup flags.
Checked the create snapshot UI from instance and volume.
> [UI] Allow quiescevm and asyncbackup flags while taking volume snapshot from UI when these are supported for the volume

- ui/src/views/storage/CreateVolume.vue
> check for custom offering and trim size

- .github/workflows/ci.yml
This PR fixes the CI failure noticed on the test_outofbandmanagement.py test run: https://github.com/apache/cloudstack/actions/runs/14738890400/job/41371735260?pr=10668
```
$ nosetests --with-xunit --xunit-file=results.xml --with-marvin --marvin-config=setup/dev/advanced.cfg -s -a tags=advanced --hypervisor=simulator test/integration/smoke/test_outofbandmanagement.py 
==== Log Folder Path: /tmp/MarvinLogs/May_02_2025_14_49_52_WEW86D All logs will be available here ====
=== TestName: test_oobm_background_powerstate_sync | Status : SUCCESS ===
=== TestName: test_oobm_configure_default_driver | Status : SUCCESS …
```
> Update dependency required for test_outofbandmanagement.py

- test/integration/smoke/test_vm_strict_host_tags.py
Fixes: https://github.com/apache/cloudstack/issues/10802
This PR fixes the test failure observed with test_vm_strict_host_tags.py both in smoke test runs and CI
https://github.com/apache/cloudstack/pull/10668#issuecomment-2837179220
https://github.com/apache/cloudstack/actions/runs/14738890400/job/41371735755?pr=10668
```
$ nosetests --with-xunit --xunit-file=results.xml --with-marvin --marvin-config=setup/dev/advanced.cfg -s -a tags=advanced --hypervisor=simulator test/integration/smoke/test_vm_strict_host_tags.py
==== Log Folder Path: /tmp/MarvinLogs/May_02_2025_15_57_28_F9LIM7 All logs will be available here ====
==== Marvin Init …
```
> smoke tests / CI : Fix test_vm_stric_host_tags

- engine/orchestration/src/main/java/com/cloud/agent/manager/AgentManagerImpl.java
- server/src/main/java/com/cloud/ha/HighAvailabilityManagerImpl.java
- server/src/main/java/com/cloud/ha/dao/HighAvailabilityDao.java
- server/src/main/java/com/cloud/ha/dao/HighAvailabilityDaoImpl.java
- server/src/test/java/com/cloud/ha/HighAvailabilityManagerImplTest.java
> server: prevent duplicate HA works and alerts

- test/integration/smoke/test_guest_os.py
- tools/marvin/marvin/lib/base.py
Currently test cases in test_guest_os.py creates new guest os and mapping entries which are not always cleared. This PR makes changes to clear all entries created during tests to allow test cases to run multiple times.
Before:
```
[root@pr10773-t13212-kvm-ol8-marvin marvin]# nosetests --with-xunit --xunit-file=results.xml --with-marvin --marvin-config=./pr10773-t13212-kvm-ol8-advanced-cfg -s -a tags=advanced --hypervisor=KVM tests/smoke/test_guest_os.py
/usr/local/lib/python3.6/site-packages/paramiko/transport.py:32: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography will remove support for Python 3.6.
from cryptography.hazmat.backends import default_backend …
```
> test: cleanup test_guest_os.py for multiple execution

- test/integration/smoke/test_hostha_simulator.py
- test/integration/smoke/test_outofbandmanagement.py
this fixes the test failure below
```
======================================================================
FAIL: Tests ha resource ownership expiry across multi-mgmt server
File "/root/test/integration/smoke/test_hostha_simulator.py", line 462, in test_ha_multiple_mgmt_server_ownership
self.fail("Management server failed to turn down or remove fake mgmt server")
AssertionError: Management server failed to turn down or remove fake mgmt server
Ran 19 tests in 277.481s
```
This PR...
> test: fix test_hostha_simulator.py and test_outofbandmanagement.py

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtRestoreBackupCommandWrapper.java
This PR fixes an issue in Nas bnr plugin due to which restore was not working.
Even if no mount options are provided while adding the backup repository, the `-o` flag is added to the mount command (during restore) resulting in an error.
Restore is broken since https://github.com/apache/cloudstack/pull/9666, so this needs to go into 4.20.
> Nas BnR: Fix for restore not working correctly 

- ui/public/locales/en.json
- ui/public/locales/pt_BR.json
- ui/src/views/iam/RolePermissionTab.vue
Adds search bar on the rules of roles
When editing a role's rules, you'll need to scroll until the specific rule you're looking for appears. To make this process easier, a search bar has been added to the role's permissions tab.
For different roles:
* Tested the search, to verify if the results were consistent with the search values.
* Made alterations on the roles from the searched results.
* Tested if the alterations on the rules of the roles are working.
> Add search bar on rules of roles

- engine/schema/src/main/java/com/cloud/usage/dao/UsageNetworksDao.java
- engine/schema/src/main/java/com/cloud/usage/dao/UsageNetworksDaoImpl.java
- engine/schema/src/main/java/com/cloud/usage/dao/UsageVpcDao.java
- engine/schema/src/main/java/com/cloud/usage/dao/UsageVpcDaoImpl.java
- usage/src/main/java/com/cloud/usage/UsageManagerImpl.java
This PR backports #9888 to 4.19, fixing the issue described in #10687 and some other ones.
- Duplicated entries in the networks helper table, resulting in duplicated usage record generation;
- Port forwarding helper entries are never removed, resulting in removed port forwarding rules generating usage records;
- Load balancer helper entries are never removed, resulting in removed load balancer rules generating usage records;
- VM snapshot helper entries are never removed, resulting in removed VM snapshots generating usage records;
- Helper entries for volumes in the secondary storage are never removed after the volume gets attached to a VM, resulting in secondary storage usage records being generated for volumes that are not in the secondary storage anymore.
I still intend to work on a …
> Backport #9888 to 4.19: Fix Usage inconsistencies

- ui/src/components/view/StatsTab.vue
Depending on the Management Server's Locale, `listVirtualMachinesUsageHistory` may return decimal values separated by a comma in the `cpuused` field; however, the UI currently expects that this decimal is separated by a dot. In this situation, the metrics page will not show the CPU utilization graph properly (see #10672).
This PR makes the UI work around the issue by replacing commas with a dot in order to properly display the metrics page. The response formatting issue will be addressed by #10699 for the next major.
<details>
<summary>
Without the patch:
</summary>
</details>
<details>
<summary>
With the patch:
</summary>
</details>
0. Initially, my Locale was set to English
1. I left a VM running for some time, and left the MS collecting utilization metrics 
2. I accessed the VM's …
> UI workaround for the inconsistent formatting of listVirtualMachinesUsageHistory

- core/src/main/java/com/cloud/agent/api/GetVmIpAddressCommand.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtGetVmIpAddressCommandWrapper.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtGetVmIpAddressCommandWrapperTest.java
- plugins/hypervisors/xenserver/src/test/java/com/cloud/hypervisor/xenserver/resource/wrapper/xenbase/CitrixRequestWrapperTest.java
- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
This PR fixes an issue with #10376 , and adds the support to get vm IP for VMs on L2 network via qemu-guest-agent
> server: fetch IP of VMs on L2 networks

- engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
- engine/schema/src/main/resources/META-INF/db/schema-42000to42010.sql
with #8309, he default vpc offering of upgraded environments have been updated to conserve_mode=1. 
but for fresh installation, the default vpc offering still has conserve_mode=0. 
This PR fixes it.
> engine/schema: create default network offering for vpc tier with conserve_mode=1 for fresh installation

- plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/datastore/driver/StorPoolPrimaryDataStoreDriver.java
Fix of resizing volumes when there is a need to notify libvirt for the change
manual and smoke testing
> StorPool notify libvirt when volume is resized

- test/integration/component/test_affinity_groups_projects.py
This PR deals with a cleanup issue on the affinity groups create test-suite.
> cleanup call on super in affinity groups projects component test

- plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/XenServerGuru.java
- plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/wrapper/xenbase/CitrixCleanupVMCommandWrapper.java
Addresses https://github.com/apache/cloudstack/pull/9175#issuecomment-2834546887
Tested on XCP-ng 8.2
Deploy a VM
```
(localcloud) 🐱 > list virtualmachines id=3325d71e-d808-451e-abbe-b923226ebc33 filter=id,name,state,instancename,
{
"count": 1,
{
"id": "3325d71e-d808-451e-abbe-b923226ebc33",
"instancename": "i-2-5-VM",
"name": "VM-3325d71e-d808-451e-abbe-b923226ebc33",
"state": "Running"
}
]
}
```
Check on XCP-ng host that VM is showing as running
```
[14:54 pr10833-t13246-xcpng82-xs1 ~]# xe vm-list name-label=i-2-5-VM
uuid ( RO)           : 318c6cd0-fae7-c095-706e-ec840b2a0787
name-label ( RW): i-2-5-VM
power-state ( RO): running
```
Destroy VM with expunge from ACS
```
(localcloud) 🐱 > destroy virtualmachine expunge=true id=3325d71e-d808-451e-abbe-b923226ebc33 
{ …
```
> xenserver: destroy halted vm on expunge

- server/src/main/java/com/cloud/network/NetworkServiceImpl.java
This PR fixes #10491 #10574
`makeredundant=true` should not work when restart network if 
- source nat is not supported, or
- redundantrouter is not supported
> server: check if redundant router is supported when restart network with makeredundant = true

- core/src/main/java/com/cloud/storage/template/HttpTemplateDownloader.java
Fixes #10658
Fixes download of with chunked transfer encoding for non-directdownload templates and ISOs
Tested download of:
- A non-chunked transfer encoding file
- A chunked transfer encoding file - https://releases.rancher.com/harvester/v1.3.2/harvester-v1.3.2-amd64-net-install.iso
<details>
<summary>SSVM logs - tail -f /var/log/cloud.log | grep -E "HttpTemplateDownloader|DownloadManagerImpl"</summary>
```
2025-05-11T12:53:29,498 INFO  [storage.template.HttpTemplateDownloader] (AgentRequest-Handler-7:[]) No credentials configured for host=10.1.3.130:80
2025-05-11T12:53:29,503 DEBUG [storage.template.HttpTemplateDownloader] (pool-2-thread-2:[]) Remote size for http://10.1.3.130/cks/setup-1.26.0.iso found to be (660.03 MB) 692094976
2025-05-11T12:53:29,505 INFO …
```
> core: support chunked transfer for image files

- server/src/main/java/com/cloud/alert/AlertManagerImpl.java
This PR extracts a method for deciding which alert are allowed to be double.
see #10367
> refactor create duplicate alert check

- engine/storage/configdrive/src/main/java/org/apache/cloudstack/storage/configdrive/ConfigDriveBuilder.java
- engine/storage/configdrive/src/test/java/org/apache/cloudstack/storage/configdrive/ConfigDriveBuilderTest.java
This PR adds the VM password to the vendor_data.json generated when ConfigDrive is used.
This way the ConfigDrive can be used as a full substitute for Virtual Router-based metadata servers, and it works with the ConfigDrive datasource of cloud-init. The existing password file `cloudstack/password/vm-password.txt` is left for compatibility.
- Renamed `writeVendorEmptyJsonFile()` to `writeVendorDataJsonFile()` as it is not always empty anymore
- Overloaded the method with a password parameter
- If `writeVendorDataJsonFile()` is called with the password, then it generates the vendor data containing a cloud-init snippet that contains the password, just as described here: https://cloudinit.readthedocs.io/en/latest/reference/datasources/openstack.html#vendor-data , …
> enhancement: add password to configdrive vendor_data.json

- plugins/storage/volume/linstor/CHANGELOG.md
- plugins/storage/volume/linstor/src/main/java/org/apache/cloudstack/storage/datastore/driver/LinstorPrimaryDataStoreDriverImpl.java
- plugins/storage/volume/linstor/src/main/java/org/apache/cloudstack/storage/datastore/util/LinstorConfigurationManager.java
- plugins/storage/volume/linstor/src/main/java/org/apache/cloudstack/storage/datastore/util/LinstorUtil.java
- pom.xml
Using storage stats not every agent has to query the controller
for current used and capacity storage.
Volume stats will show physical used size for thin volume in Cloudstack.
This volume stats are cached to not query the Linstor controller each
time a volume is asked for.
Fixes: https://github.com/apache/cloudstack/discussions/10142
Fresh Linstor cluster, basic operations
> Linstor:  implement volume and storage stats

- engine/orchestration/src/main/java/com/cloud/agent/manager/ClusteredAgentManagerImpl.java
- engine/orchestration/src/test/java/com/cloud/agent/manager/ClusteredAgentManagerImplTest.java
This PR improves the current direct agents rebalancing activity. Sometimes hypervisor hosts (direct agents) stuck with Disconnect state during agent rebalancing activity across multiple management server nodes. This issue was noticed during frequent restart of the management server nodes in the cluster.
When there are multiple management server nodes in a cluster, if one or more nodes are shutdown/start/restart, CloudStack will rebalance the hosts among the remaining nodes or move the nodes to the newly joined management server nodes. During the rebalancing period multiple operations could happen including:
- DirectAgentScan at interval of configured direct.agent.scan.interval
- AgentRebalanceScan to identify and schedule rebalance agents
- TransferAgentScan to transfer the host from …
> Direct agents rebalance improvements with multiple management server nodes

- server/src/main/java/com/cloud/usage/UsageServiceImpl.java
This PR improves the List usage records API, to list network offering usages (usage type 13) when offering  id is specified in usage id.
Doc PR: https://github.com/apache/cloudstack-documentation/pull/505
Before Fix:
```
(usageenv) 🐱 > list usagerecords startdate=2025-05-11 enddate=2025-05-13 type=13 usageid=bfcb52bf-cb33-4c7d-bd9d-9b4b57d65a77
(usageenv) 🐱 > 
```
After Fix:
```
(usageenv) 🐱 > list usagerecords startdate=2025-05-11 enddate=2025-05-13 type=13 usageid=bfcb52bf-cb33-4c7d-bd9d-9b4b57d65a77
{
"count": 110,
"usagerecord": [
{
"accountid": "a5f9d055-1ea1-11f0-8a38-1e00b50002f5",
"description": "Network offering DefaultIsolatedNetworkOfferingWithSourceNatService (bfcb52bf-cb33-4c7d-bd9d-9b4b57d65a77) usage for VM testvm01 (0c74f18a-2f1b-4bbe-b17e-bd16f4e55d86) …
```
> List usage records for network offering (usage type 13) when offering  id is specified in usage id

- plugins/backup/nas/src/main/java/org/apache/cloudstack/backup/NASBackupProvider.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtRestoreBackupCommandWrapper.java
1. Restore backed-up volume on live instances attaches the qcow2 volume as a Raw image, which causes the instance to not
be able to read it.
2. In the cloudstack db the format of the restored volume is kept as Raw (for both live and stopped VMs). Although it doesn't cause any immediate effects, but it might cause some issue with other subsystems like volume migration.
1.  `virsh attach-disk` command which is used to attach the restored volume to the live instance should include `--subdriver qcow2` argument.
2. NAS backup always converts the disk into Qcow2 format while backing up, so it's safe to set the disk format of the restored volume always to Qcow2 in the db.
1. Create a VM with a data vol
2. Install ext4 fs on the data vol, mount it and create a file
3. Take NAS backup
4. Create …
> NAS BnR: Restore backed-up volume on live instances is not readable

- ui/src/views/AutogenView.vue
This PR fixes a bug where Assign / Remove Backup offering buttons are shown incorrectly in the details view in UI.
List View:
Details View:
This is because the listVirtualMachinesMetrics api sent during detals view doesn't send the `backoff` string in details and does not get backup offering information for the VM.
This is an offshoot of, although not caused directly by https://github.com/apache/cloudstack/pull/9825
Before the above PR, listVirtualMachines api was sent by UI in details view also which had the `backoff` string in details.
> ui: Assign/Remove Backup offering buttons incorrect in details view

- ui/src/views/compute/InstanceTab.vue
When a VM fails to deploy, it remains in `Error` state. Currently, there is no functionality to recover a VM in `Error` state, therefore, the only option is to create a new VM. However, the option `Create and Add Volume` is still presented. This PR disables the `Create and Add Volume`  button for VMs in `Error` state
I made the following tests, in my local lab:
1. Disabled all the hosts in my environment.
2. Tried to deploy a new VM. As expected, the deploy failed and it was set to `Error` state.
3. Validated that when the `Volumes` section was accessed, the Create and Add Volume button was still enabled.
4. Built and installed CloudStack's packages with my fix. 
5. Validated that when the `Volumes` section was accessed again, the button was successfully disabled.
> Disabled Create and Add Volume button for VMs in Error state

- services/secondary-storage/controller/src/main/java/org/apache/cloudstack/secondarystorage/SecondaryStorageManagerImpl.java
Fixes #8103
Added cleanup changes for SSVM that already exist for CPVM
> ssvm: reset fields on destroy

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtConvertInstanceCommandWrapper.java
- utils/src/main/java/com/cloud/utils/script/Script.java
This PR sanitises logs of ovftool cmd during vmware import.
Manually tested, and checked the logs.
> VMware import - logs sanitation

- engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
Prevents data corruption in cases where a VM is started on a new host while it is already running on another host
Scenario: If the host is down and the admin stops a VM with the option `force=true,` the admin will be able to start it on another host. This may lead to data corruption when the issue with the first host is fixed, the volume will be attached to both hosts.
Manual testing and with StorPool's smoke tests
> Prevent data corruption for StorPool volumes

- engine/storage/volume/src/main/java/org/apache/cloudstack/storage/volume/VolumeServiceImpl.java
- plugins/storage/volume/default/src/main/java/org/apache/cloudstack/storage/datastore/driver/CloudStackPrimaryDataStoreDriverImpl.java
This PR resets the pool id when create volume fails on the allocated pool. Also, adds check for endpoint to avoid NPE, while resizing volume and updates the resize error when no endpoint exists.
Noticed an issue during DATA volume re-attach, the pool id is not reverted after first create volume failure during attach operation, thereafter CloudStack couldn't find any suitable pools for volume creation even there are pools available with enough capacity.
The pool id is persisted while creating the volume here: 
https://github.com/apache/cloudstack/blob/55c8138a1a75a19ca61580dd4d610e1a05fc5dea/engine/storage/volume/src/main/java/org/apache/cloudstack/storage/datastore/PrimaryDataStoreImpl.java#L333-L339, the updated pool id id not reverted when volume creation fails. On next create volume …
> Reset the pool id when create volume fails on the allocated pool, and update the resize error when no endpoint exists

- ui/public/locales/en.json
- ui/src/components/header/ProjectMenu.vue
- ui/src/components/widgets/InfiniteScrollSelect.vue
- ui/src/views/network/CreateNetworkPermission.vue
A select component which can retrieve more items from the API when the scroll reaches the end of the list. It will allow selecting options in case of a large number of items.
Currently used only in the following view:
- Project selection on the dashboard.
- Account and project selection in CreateNetworkPermission form.
https://github.com/user-attachments/assets/ce6e890d-d368-4a55-bda4-816a6192c5ce
> ui: add an infinite scroll select component

- ui/src/views/compute/EditVM.vue
This PR is based off: https://github.com/apache/cloudstack/pull/10224 required to be address in 4.19.
The main fix here is the listZones API which incorrectly uses `zoneid` as opposed to `id` in the api params.
> Fix issue with security group selection box display

- plugins/storage/volume/linstor/src/main/java/org/apache/cloudstack/storage/datastore/provider/LinstorHostListener.java
PR #9873 changed the default implementation of hostConnect on the DefaultHostListener, and Linstor tried to call the none existent default implementation. With the change in the PR a recursion was triggered that triggered a StackOverflow and stopped adding Linstor primary storage.
Creating a new cluster with Linstor primary storage
> linstor: fix host connect recursion regression

- plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java
- plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageLayoutHelper.java
- plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageProcessor.java
- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
- test/integration/smoke/test_ssvm.py
- vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/VirtualMachineMO.java
This PR addresses power on & move datastore issues with VMware 80u2 and 80u3, and fixes tests for restore vm (disk cleanup issue), ssvm/cpvm (wait time to disconnect). Following are the details:
- **Power On issue**
lock issue during PowerOn operation (for ROOT disk, which is cloned from seeded template)
https://knowledge.broadcom.com/external/article/316576/troubleshooting-issues-resulting-from-lo.html
Now, PowerOn operation is being tried after lock issue, and succeeds after few attempts.
- **Move datastore file issue**
access issue with move datastore file operation (when creating volume from snapshot)
Now, Move datastore file operation is being tried after access issue, and succeeds after few attempts.
- **Restore VM test behavior/issue**
test checks for old root disk existence and …
> VMware 80u2 and 80u3 updates/fixes

- tools/marvin/marvin/config/test_data.py
This PR fixes
see https://github.com/apache/cloudstack/pull/10668#issuecomment-2882079106
> test: Update test ubuntu template for VMware to deployasis=False

- test/integration/smoke/test_restore_vm.py
- tools/marvin/marvin/config/test_data.py
This PR fixes the test failure below on vmware
> test: fix test_restore_vm failure on vmware

- engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
This PR fixes lots of CI failures like
> test: fix several simulator CI failures

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/LibvirtStorageAdaptor.java
This PR fixes the vm deployment if template is RAW.
```
2025-05-16T09:32:39,205 ERROR [kvm.storage.LibvirtStorageAdaptor] (AgentRequest-Handler-2:[]) (logid:9d528179) Failed to convert [/mnt/71c96d7c-9e42-5184-83e3-0786cfa3e7d2/34cbcd76-aafb-53a9-9ad3-1596ce9389ff.raw] to [/mnt/db98865f-20d0-30d8-bcad-bec75452cb56/e1eceab0-863a-46c2-b0a2-100a2fbf3d09] due to: [qemu-img: Source lacks bitmap support]. org.apache.cloudstack.utils.qemu.QemuImgException: qemu-img: Source lacks bitmap support
at org.apache.cloudstack.utils.qemu.QemuImg.convert(QemuImg.java:477)
at com.cloud.hypervisor.kvm.storage.LibvirtStorageAdaptor.copyPhysicalDisk(LibvirtStorageAdaptor.java:1613)
at com.cloud.hypervisor.kvm.storage.KVMStoragePoolManager.copyPhysicalDisk(KVMStoragePoolManager.java:459)
```
RAW does not …
> kvm: fix vm deployment from RAW template

- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
- server/src/test/java/com/cloud/vm/UserVmManagerImplTest.java
This PR fixes #10825 by moving the creation of the network to outside the transaction, right before the updates start happening. This way, if an error happens while creating the network, nothing will have been updated yet. And, if an error happens while updating the virtual machine, the changes will be rolledback.
Also closes #10854.
I verified that the issue does not happen anymore:
- I tried to assign the VM to an account without any network: ACS created a new isolated network for the VM and assigned it successfully.
Also, I simulated errors during the VM assignment to verify what would happen:
- I tried to assign the VM to an account without any network, and forced an error before the creation of the network: the VM remained in its original state, and no network was created;
- I tried …
> Address `assignVm` regression

- api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
- api/src/main/java/org/apache/cloudstack/api/response/ManagementServerResponse.java
- server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
The PR #9773 changed the `serviceip` to `ipaddress` in the API response, which broke backward compatibility.
Although a test failure has been fixed in #10501 , I think it would be better to add it back.
> mgmt: add back serviceip in ManagementServerResponse

- test/integration/smoke/test_global_acls.py
This PR cleans the acl in test_global_acls.py, so that the test can be executed multiple times without error
Prior to this change, it failed at 2nd run with error
```
======================================================================
FAIL: Test delete global ACL as a normal user, domain admin and root admin users.
File "/marvin/tests/smoke/test_global_acls.py", line 243, in test_delete_global_acl
self.assertEqual(len(number_of_acls), 2)
File "/usr/local/lib/python3.6/site-packages/marvin/cloudstackTestCase.py", line 95, in assertEqual
super(cloudstackTestCase,self).assertEqual(first,second,msg)
AssertionError: 4 != 2
```
now, it succeeds
```
[root@pr10893-t13358-kvm-ol8-marvin ~]# …
```
> test: cleanup acl in test_global_acls.py

- plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/manager/VmwareManagerImpl.java
- server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
- utils/src/main/java/com/cloud/utils/net/NetUtils.java
- utils/src/test/java/com/cloud/utils/net/NetUtilsTest.java
This PR fixes some typos (no logical changes).
VmwareManager - __managemetPortGroupName_ => __managementPortGroupName_
NetUtils - _isNetowrkASubsetOrSupersetOfNetworkB()_ => _isNetworkASubsetOrSupersetOfNetworkB()_
> Fixed some typos

- utils/src/main/java/com/cloud/utils/nio/NioConnection.java
- utils/src/main/java/com/cloud/utils/nio/NioServer.java
This PR improves the closing of the socket whenever the connection is closed in Nioconnection.
> Improve socketChannel closing in NioConnection

- plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/wrapper/xenbase/CitrixStartCommandWrapper.java
This PR fixes issue: https://github.com/apache/cloudstack/issues/10318 where in the config drive ISO isn't attached to the VM.
After fix, we see the configdrive iso present:
> Fix issue with configdrive on XenServer

- plugins/network-elements/vxlan/src/main/java/com/cloud/network/guru/VxlanGuestNetworkGuru.java
- server/src/main/java/com/cloud/network/guru/ExternalGuestNetworkGuru.java
- server/src/main/java/com/cloud/network/guru/GuestNetworkGuru.java
This PR supports Routed network with vxlan isolation
fixes #10855
> Routed: support vxlan networks

- plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/datastore/driver/StorPoolPrimaryDataStoreDriver.java
- plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/datastore/util/StorPoolUtil.java
- test/integration/plugins/storpool/TestTagsOnStorPool.py
This PR adds the device ID as a tag to the attached StorPool volumes. It is needed for the StorPool DR service
manual and smoke tests
> StorPool added device ID tag to the StorPool volumes

- engine/schema/src/main/resources/META-INF/db/schema-42010to42100.sql
Some statements to add new columns to cloud.guest_os_category have been added twice by mistake as part of #10773. These statements are idempotent and won't affect upgrade as such but better to cleanup
> engine-schema: fix duplicate statements in upgrade path

- engine/schema/src/main/resources/META-INF/db/schema-42010to42100.sql
In PR #10773, 'AlmaLinux' was incorrectly written as 'Alma Linux' in the guest OS category name and OS classification. This PR corrects the naming to 'AlmaLinux'.
> engine-schema: fix naming for AlmaLinux

- plugins/storage/volume/storpool/src/main/java/com/cloud/hypervisor/kvm/storage/StorPoolStoragePool.java
Enable the discard option for virtio-blk and virtio-scsi devices for volumes on StorPool storage
manually tested with different controllers and UEFI legacy/secured
deploy a VM
attach volume
> enabled discard option

- engine/storage/src/main/java/org/apache/cloudstack/storage/allocator/ClusterScopeStoragePoolAllocator.java
- engine/storage/src/main/java/org/apache/cloudstack/storage/allocator/ZoneWideStoragePoolAllocator.java
- plugins/storage-allocators/random/src/main/java/org/apache/cloudstack/storage/allocator/RandomStoragePoolAllocator.java
The logs in storage allocation algorithms were displaying incorrect information about the allocation pool. Therefore, the logs were rewritten.
When trying to migrate a volume, the expected log messages were displayed correctly.
> Fix volume allocation logs

- plugins/user-authenticators/ldap/src/main/java/org/apache/cloudstack/ldap/LdapContextFactory.java
- plugins/user-authenticators/ldap/src/main/java/org/apache/cloudstack/ldap/LdapManagerImpl.java
This PR adds validation for the ldap truststore password before adding the ldap server.
> Add check for ldap truststore password

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/LibvirtStorageAdaptor.java
This PR adds support for Direct Downloads on Ceph primary storage. Its logic is replicating the logic added on the Storpool support for Direct download #9833 but adapted to Ceph.
Fixes: #3065 
Tested on KVM env with NFS and Ceph primary pool
Created a service offering containing a storage tag matching the Ceph pool
Registered template using 'Direct download' option
Deploy VM -> Observe the VM is deployed and booted, disk downloaded to temporary location and converted to the Ceph destination
> Support Direct Download on Ceph primary storage

- plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/wrapper/xenbase/CitrixResizeVolumeCommandWrapper.java
- server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
- ui/src/views/storage/ChangeOfferingForVolume.vue
On version `4.16.1.0` PR #5829 blocked volume shrinking via UI when using XenServer. However, this change was not sufficient, as the user may still use the APIs directly to try to shrink their volume. Furthermore, via UI, it is still possible to inform the shrink option when changing disk offerings. This PR removes that option from the UI; also, the `resizeVolume` and `changeOfferingForVolume` APIs were changed to block this type of operation when using XenServer, similar to what is done when using QCOW2.
Here’s the English translation of your Markdown content:
---
Via UI, I validated that the shrink option no longer appears for XenServer volumes:
* Before:
* After:
Via CMK, I validated that both APIs block the use of the parameter for XenServer:
```
(labinterno) 🐱 > change …
```
> Block volume shrink on Xen

- setup/db/create-schema.sql
This PR updates the engine of op_lock and op_nwgrp_work to 'InnoDB' (from 'Memory'), and ensures the initial db schema does not rely on Memory engine (mainly during DB bootstrap). It is not safe for use with asynchronous replication in the case of failovers, and is straight up incompatible with some HA MySQL distributions/extensions such as Galera.
This is already done in 4.9.0.0 to 4.9.1.0 upgrade path here: https://github.com/apache/cloudstack/blob/16c60c7528a3ee731bceaa9113d5e6a76b22a246/engine/schema/src/main/resources/META-INF/db/schema-490to4910.sql#L30-L31
> Do not rely on Memory engine in DB setup scripts

- agent/src/main/java/com/cloud/agent/Agent.java
- api/src/main/java/com/cloud/exception/OperationTimedoutException.java
- api/src/main/java/com/cloud/resource/ResourceState.java
- api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
- api/src/main/java/org/apache/cloudstack/api/command/admin/systemvm/PatchSystemVMCmd.java
- core/src/main/java/org/apache/cloudstack/agent/lb/SetupMSListCommand.java
- engine/components-api/src/main/java/com/cloud/agent/AgentManager.java
- engine/orchestration/src/main/java/com/cloud/agent/manager/AgentManagerImpl.java
- engine/orchestration/src/main/java/com/cloud/agent/manager/ClusteredAgentManagerImpl.java
- engine/schema/src/main/java/com/cloud/host/dao/HostDao.java
- engine/schema/src/main/java/com/cloud/host/dao/HostDaoImpl.java
- framework/agent-lb/src/main/java/org/apache/cloudstack/agent/lb/IndirectAgentLB.java
- plugins/maintenance/src/main/java/org/apache/cloudstack/api/command/CancelMaintenanceCmd.java
- plugins/maintenance/src/main/java/org/apache/cloudstack/api/command/PrepareForMaintenanceCmd.java
- plugins/maintenance/src/main/java/org/apache/cloudstack/maintenance/ManagementServerMaintenanceManager.java
- plugins/maintenance/src/main/java/org/apache/cloudstack/maintenance/ManagementServerMaintenanceManagerImpl.java
- plugins/maintenance/src/main/java/org/apache/cloudstack/maintenance/command/CancelMaintenanceManagementServerHostCommand.java
- plugins/maintenance/src/main/java/org/apache/cloudstack/maintenance/command/PrepareForMaintenanceManagementServerHostCommand.java
- plugins/maintenance/src/test/java/org/apache/cloudstack/maintenance/ManagementServerMaintenanceManagerImplTest.java
- server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
- server/src/main/java/org/apache/cloudstack/agent/lb/IndirectAgentLBServiceImpl.java
- server/src/test/java/org/apache/cloudstack/agent/lb/IndirectAgentLBServiceImplTest.java
- ui/public/locales/en.json
- ui/src/config/section/infra/managementServers.js
- ui/src/views/AutogenView.vue
- ui/src/views/infra/Confirmation.vue
- utils/src/main/java/com/cloud/utils/nio/NioConnection.java
This PR has the following improvements for Management Server - Prepare for Maintenance and Cancel Maintenance.
- Added new setting 'management.server.maintenance.ignore.maintenance.hosts' to ignore hosts in maintenance states  while preparing management server for maintenance. This skips agent transfer and agents count check for hosts in maintenance, and unblocks Management Server in "preparing for maintenance" state when any Host stuck in "prepare for maintenance" (due to connectivity/race condition issues) or in other maintenance states. 
- Rebalance indirect agents after cancel maintenance, using rebalance parameter in cancelMaintenance API, to initiate the rebalancing of the indirect agents immediately instead of waiting for the 'indirect.agent.lb.check.interval' time.
- Force …
> Management Server - Prepare for Maintenance and Cancel Maintenance improvements

- ui/src/utils/quota.js
This PR fixes https://github.com/apache/cloudstack/issues/11082 with right indexes as the usage types
https://github.com/apache/cloudstack/blob/01c721fcda5f70af88750923e98e2359e3640d13/api/src/main/java/org/apache/cloudstack/usage/UsageTypes.java#L47-L50
> Corrected quota type indexes

- server/src/main/java/com/cloud/alert/AlertManagerImpl.java
- server/src/main/java/com/cloud/storage/StorageManagerImpl.java
> server: fix orphan db transaction issue

- api/src/main/java/com/cloud/storage/VolumeApiService.java
- core/src/main/java/com/cloud/agent/api/ConvertInstanceAnswer.java
- core/src/main/java/com/cloud/agent/api/ConvertInstanceCommand.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtConvertInstanceCommandWrapper.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtConvertInstanceCommandWrapperTest.java
- server/src/main/java/org/apache/cloudstack/vm/UnmanagedVMsManagerImpl.java
- server/src/test/java/org/apache/cloudstack/vm/UnmanagedVMsManagerImplTest.java
This PR fixes converted instance NPE issue in VMware to KVM Migration when source VMware instance OVF is exported from management server.
Fixes #10982 
Some of the changes of the below PRs were missing in 4.20, resulting in NPE.
- https://github.com/apache/cloudstack/pull/9787
- https://github.com/apache/cloudstack/pull/9764
- https://github.com/apache/cloudstack/pull/10409
Tested VMware instance migration to KVM, without ovftool installation on KVM hosts. OVF of source VMware instance is downloaded from Management Server.
> [VMware to KVM Migration] Fix for converted instance NPE issue when source VMware instance OVF is exported from management server

- api/src/main/java/com/cloud/event/EventTypes.java
- api/src/main/java/com/cloud/server/ManagementService.java
- api/src/main/java/org/apache/cloudstack/api/command/admin/management/RemoveManagementServerCmd.java
- api/src/main/java/org/apache/cloudstack/api/command/admin/management/RemoveMgmtCmd.java
- server/src/main/java/com/cloud/api/query/vo/ManagementServerJoinVO.java
- server/src/main/java/com/cloud/server/ManagementServerImpl.java
This PR adds a command to mark a Management Server as removed on the database only if its status is marked as `Down`. To execute the command, it is obligatory to inform the `id` of the targeted MS.
In a local lab, I added an MS through the database.
- With State="Down" I executed through CMK `remove managementserver id=<uuid>` and verified that the MS wasn't being listed on the UI and was marked as `Removed` on the database.
- With State="Up" I executed the same command and verified an error was returned informing it wasn't possible to remove an MS which state was marked as "Up".
- With State="Down" I executed through a URL `http://<IP>:8080/client/api?command=removeManagementServer&response=json&id=<UUID>` and verified the MS was marked as removed and wasn't being listed on the UI.
- …
> Add API command remove management server

- plugins/storage/volume/primera/src/main/java/org/apache/cloudstack/storage/datastore/adapter/primera/PrimeraAdapter.java
- tools/marvin/setup.py
This PR adds support to set the priority to high for volume copy operations using the Primera plugin.  
This enhancement allows volume copy tasks handled by the Primera plugin to be prioritized as high, improving performance for critical operations. No changes to existing workflows or APIs; only the priority for copy operations is updated.
---
_N/A_
- Manually tested the volume copy operation using the Primera plugin.
- Verified that the copy operation is executed with high priority.
- Tested with multiple concurrent copy operations to ensure prioritization works as expected.
- Confirmed no impact on unrelated features or plugins.
---
> fix priority for volume copy operation

- ui/src/api/index.js
- ui/src/components/view/ImageDeployInstanceButton.vue
- ui/src/main.js
- ui/src/utils/guiTheme.js
- ui/src/utils/request.js
- ui/src/views/compute/KubernetesAddNodes.vue
- ui/src/views/compute/KubernetesRemoveNodes.vue
This PR fixes the project views for different resources. This bug was introduced in https://github.com/apache/cloudstack/pull/10899
<details><summary>Generated Summary</summary>
<p>
This pull request introduces several changes aimed at improving API request handling and refactoring the codebase for better readability and maintainability. The most significant updates include adjustments to how parameters are handled in API requests, the introduction of helper functions for GET and POST request parameters, and the replacement of the `api` function with `getAPI` across multiple components.
* [`ui/src/api/index.js`](diffhunk://#diff-4e3f9e2a3c02502a979c3797fc68c7afdb535402c7a2de886f7088aec80329ffL50-R50): Simplified the parameter-checking logic in the `postAPI` function by removing checks for …
> UI fix api in project view

- agent/src/main/java/com/cloud/agent/properties/AgentProperties.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtModifyStoragePoolCommandWrapper.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/ScaleIOStorageAdaptor.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/storage/ScaleIOStorageAdaptorTest.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/storage/ScaleIOStoragePoolTest.java
- plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/client/ScaleIOGatewayClient.java
- plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/lifecycle/ScaleIOPrimaryDataStoreLifeCycle.java
- plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/manager/ScaleIOSDCManager.java
- plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/manager/ScaleIOSDCManagerImpl.java
- plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/provider/ScaleIOHostListener.java
- plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/util/ScaleIOUtil.java
- utils/src/main/java/com/cloud/utils/script/Script.java
This PR enhances the PowerFlex/ScaleIO MDM  and host SDC connections, includes the following changes (and some code improvements).
- Introduced timeout configuration 'powerflex.mdm.change.apply.wait' (Default value: 1000 ms) at zone scope, to wait after MDM addition, and before & after MDM removal changes made on Host with ScaleIO SDC. Also, Changes to apply the wait time after making MDM changes for ScaleIO in prepare and unprepare logic.
- Introduced configuration flag 'powerflex.block.sdc.unprepare' (Default is false) at zone scope, to enable/disable blocking unprepare ScaleIO SDC connection when SDC client restart required (upon PowerFlex MDM removal i.e. no support for _--remove_mdm_ in _drv_cfg_ cmd) and there are volumes attached to the Host. Added validation to fail Host …
> PowerFlex/ScaleIO - MDM and host SDC connection enhancements

- agent/src/main/java/com/cloud/agent/properties/AgentProperties.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/ScaleIOStorageAdaptor.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/storage/ScaleIOStorageAdaptorTest.java
- plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/manager/ScaleIOSDCManagerImpl.java
- plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/provider/ScaleIOHostListener.java
- plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/util/ScaleIOUtil.java
This PR adds agent property 'powerflex.sdc.service.wait' for the time (in secs) to wait after SDC service start/restart/stop, and retries to fetch SDC id/guid for PowerFlex/ScaleIO storage.
> PowerFlex/ScaleIO - Wait after SDC service start/restart/stop, and retry to fetch SDC id/guid

- server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
- ui/src/components/view/InfoCard.vue
- ui/src/config/section/domain.js
Currently, it is not possible to list the templates and ISOs of a specific domain. When executing the `listTemplates` and `listIsos` APIs only specifying a `domainid`, all templates/ISOs that the caller has access to are listed; the `domainid` parameter is completely ignored.
Therefore, this PR proposes to add support for listing templates and ISOs by domain. To achieve that, the `listTemplates` and `listIsos` APIs should be called defining the `templatefilter` and `isofilter` parameters to either `self` or `selfexecutable`. Furthermore, the `isrecursive` parameter can be used, to list templates and ISOs recursively by domain.
---
Fixes #10392, #10393
- Verified that domain access validation is correctly performed
- Verified that it is possible to list templates and ISOs by domain when …
> List templates and ISOs by domain

- engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/snapshot/SnapshotObject.java
When removing an incremental snapshot (For both KVM and XenServer), it is checked if the snapshot has a child or not. If it has, then the snapshot is not removed from the storage.
For KVM incremental snapshots, snapshots in the same chain may be on different secondary storages (within the same zone).
However, the child search process only considers snapshots from the same secondary storage as theirs. Therefore, if a snapshot has its parent snapshot on a different secondary storage, it will be completely removed, making the snapshot chain inconsistent.
I created 3 snapshots that were stored in the secondary storage `sec-nfs1`. I then set the storage `sec-nfs1` to read-only and created 2 more snapshots, which were stored in the secondary storage `sec-nfs2`.
Without the changes: when the …
> Fix KVM incremental snapshot removal when using multiple secondary storages

- ui/src/views/compute/DeployVM.vue
- ui/src/views/compute/wizard/OsBasedImageSelection.vue
- ui/src/views/infra/zone/ZoneWizardRegisterTemplate.vue
When deploying an Instance from an ISO in a multi hypervisor env, hypervisor type selection is ignored and it selects the first hypervisor from the list.
This PR fixes the above bug which was introduced in https://github.com/apache/cloudstack/pull/10773
Apart from the above, this PR updates the older api to getAPI & postAPI for `ZoneWizardRegisterTemplate`.
<details><summary>Generated summary</summary>
<p>
This pull request introduces updates to improve the handling of hypervisor changes in the UI and refactors API calls in the `ZoneWizardRegisterTemplate.vue` component for better code clarity and consistency. The most important changes include modifying event handlers for hypervisor updates, refactoring API utility usage, and ensuring proper state updates.
* …
> UI: Fix ISO Hypervisor selection

- client/pom.xml
- plugins/pom.xml
This PR...
Fixes: #10787
actual removal will be in v22 or v23 ...
> OVM deprecation

- plugins/backup/nas/src/main/java/org/apache/cloudstack/backup/NASBackupProvider.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtRestoreBackupCommandWrapper.java
- server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
- server/src/main/java/org/apache/cloudstack/backup/BackupManagerImpl.java
- server/src/test/java/com/cloud/storage/VolumeApiServiceImplTest.java
This PR fixes #11257.
- Libvirt backs up the volumes in the order of their `deviceId`.
- However, during restore, volumes are processed based on their `id` in the `volumes` table.
- If data volume has a lower `id` in the `volumes` table than the root volume, restore mistakenly assumes the data disk to be the root disk.
- Restore fails silently, without any error
Another minor issue exists with Volume attach and detach operations on Instances that have an associated backup offering:
- Attach and Detach operations use different logic when handling Instances with backup offerings.
- **Detach fails** if the Instance was associated with a backup offering but has no backups yet.
- In contrast, **Attach succeeds** under the same conditions.
1. Sorting the volumes list by deviceId before restore …
> Fix restore from NAS backup when datadisk is older than the root disk.

- api/src/main/java/org/apache/cloudstack/api/command/user/config/ListCapabilitiesCmd.java
- api/src/main/java/org/apache/cloudstack/api/response/CapabilitiesResponse.java
- server/src/main/java/com/cloud/server/ManagementServerImpl.java
- ui/src/views/compute/DeployVM.vue
- ui/src/views/compute/DeployVnfAppliance.vue
- ui/src/views/compute/EditVM.vue
This PR fixes https://github.com/apache/cloudstack/issues/10835 issue. 
1. New capability param is included in listCapabilities response:
```
"dynamicscalingenabled": true
``` 
2. Using above to toggle Dynamic scaling for Deploy, Edit instance
> Fix for dynamic scaling toggle for instance

- api/src/main/java/com/cloud/user/AccountService.java
- api/src/main/java/org/apache/cloudstack/api/command/admin/cluster/ListClustersCmd.java
- api/src/main/java/org/apache/cloudstack/api/command/admin/pod/ListPodsByCmd.java
- api/src/main/java/org/apache/cloudstack/api/command/user/zone/ListZonesCmd.java
- api/src/main/java/org/apache/cloudstack/query/QueryService.java
- plugins/network-elements/juniper-contrail/src/test/java/org/apache/cloudstack/network/contrail/management/MockAccountManager.java
- server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
- server/src/main/java/com/cloud/user/AccountManagerImpl.java
- server/src/test/java/com/cloud/user/MockAccountManagerImpl.java
This PR...
Fixes: #10906
By adding a global setting `allow.user.view.all.zone` depending on this setting the resource admin from the issue description will be able to see zones that do not fall withing their dedication domain, or not. The default is `true`, meaning that on `listZones` all zones are shown. If set to `false` the user will only see the zone from their dedication domain.
> list only own zones for resource admin

- engine/api/src/main/java/com/cloud/vm/VirtualMachineGuru.java
- server/src/main/java/com/cloud/consoleproxy/ConsoleProxyManagerImpl.java
- services/secondary-storage/controller/src/main/java/org/apache/cloudstack/secondarystorage/SecondaryStorageManagerImpl.java
- systemvm/debian/opt/cloud/bin/setup/common.sh
- systemvm/debian/opt/cloud/bin/setup/consoleproxy.sh
- systemvm/debian/opt/cloud/bin/setup/secstorage.sh
This PR fixes #11165 
configured NTP servers through global setting: `cpvm.ntp.server.list`
Recreated CPVM
queried ntp servers using: `ntpq -p` and verified content of `/etc/ntpsec/ntp.conf`
> Allow custom NTP servers for CPVM

- ui/src/views/infra/ZoneUpdate.vue
This PR fixes local storage enable/disable toggle in Edit Zone dialog.
Fixes #11305 
Verified the local storage enable/disable from Edit Zone dialog in UI.
> [UI] Fix for local storage enable/disable toggle in edit zone

- server/src/main/java/com/cloud/api/query/dao/HostJoinDaoImpl.java
CPU and RAM values for external resource metrics was showing NaN values. This fixes the behaviour.
Before:
After:
> server: fix NaN metrics for external resources

- api/src/main/java/org/apache/cloudstack/api/command/admin/cluster/UpdateClusterCmd.java
- framework/extensions/src/main/java/org/apache/cloudstack/framework/extensions/manager/ExtensionsManager.java
- framework/extensions/src/main/java/org/apache/cloudstack/framework/extensions/manager/ExtensionsManagerImpl.java
- framework/extensions/src/test/java/org/apache/cloudstack/framework/extensions/manager/ExtensionsManagerImplTest.java
- server/src/main/java/com/cloud/resource/ResourceManagerImpl.java
- ui/src/views/extension/ExternalConfigurationDetails.vue
- ui/src/views/infra/ClusterUpdate.vue
This PR makes changes to allow updating details for an extension resource mapping, as other places where external metadata is added already allow updation. Currently, extensions only support Cluster to be registered therefore, changes have been added to updateCluster functionality.
> api,server,extensions: allow updating extension resource map details

- engine/schema/src/main/java/com/cloud/network/as/dao/AutoScaleVmGroupVmMapDao.java
- engine/schema/src/main/java/com/cloud/network/as/dao/AutoScaleVmGroupVmMapDaoImpl.java
- server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
- server/src/main/java/com/cloud/network/as/AutoScaleManager.java
- server/src/main/java/com/cloud/network/as/AutoScaleManagerImpl.java
This PR intends to fix issue: https://github.com/apache/cloudstack/issues/9318.
New Global config is introduced, to be used as threshold for Error instances count for ASG 
```
autoscale.errored.instance.threshold: 10 (default)
```
If any ASG has Error instances more than threshold, autoscaling will be stopped.
> Prevent infinite autoscaling

- engine/schema/src/main/resources/META-INF/db/schema-42010to42100.sql
- plugins/network-elements/bigswitch/src/main/java/com/cloud/network/element/BigSwitchBcfElement.java
- server/src/main/java/com/cloud/api/ApiResponseHelper.java
- server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
- utils/src/main/java/com/cloud/utils/StringUtils.java
This PR updates the CIDR/Gateway of the Shared Networks from Guest IP ranges.
CIDR/Gateway list are maintained for shared networks in networks table (null when there are no Guest IP ranges), and only the first one would be returned through the list networks response (for backward compatibility).
Created a shared network with gateway/netmask/startip/endip, Checked the network cidr/gateway after the following operations - added more guest ip ranges to the shared network, removed some ranges and added new ranges, removed all ranges and added new ranges. Deployed instances on the shared network.
- Create shared network
- Shared network details
```
(localcloud) 🐱 > list networks id=8a245b01-bf73-44ce-b5eb-b0af5add73fb filter=id,name,traffictype,type,vlan,broadcastdomaintype,broadcasturi,cidr,ga …
```
> Update CIDR/Gateway of the Shared Networks from Guest IP ranges

- server/src/main/java/com/cloud/resource/ResourceManagerImpl.java
Fixes #11293
The change was introduced in #10518 
Thread.currentThread().wait(...) must be called in a synchronized block and on the object.
> server: fix IllegalMonitorStateException on cluster managedstate change

- ui/src/views/compute/CreateAutoScaleVmGroup.vue
Fixes #11269
The current dysfunctional behaviour was introduced in #6571. In advanced settings interface for ssh keypairs, userdata, affinity group, etc are show but the toggle to show/hide them was not working correctly.
> ui: fix advance setting behaviour in autoscale form

- ui/src/components/view/EventsTab.vue
> ui: make events tab selected columns persistent using cache

- api/src/main/java/org/apache/cloudstack/api/command/admin/resource/ListCapacityCmd.java
This PR fixes listCapacity api's sort by usage parameter.
Before:
```
(localhost) 🐱 > list capacity  sortby="usage"                                                                                                                                                                                                                                                                  [21/495]
{                                                                             
"capacity": [                                                               
{                                                                         
"capacitytotal": 6997340160,                                            
"capacityused": 5368709120,                                             
"name": "MEMORY", …
```
> Fix listCapacity sort by usage

- server/src/main/java/com/cloud/network/NetworkServiceImpl.java
- ui/src/views/infra/zone/ZoneWizardLaunchZone.vue
This PR fixes: https://github.com/apache/cloudstack/issues/11108
KVM Zone creation: (no longer shows the NSX public traffic creation)
KVM Zone - Disabled NSX network service provider:
VMware - Tested for regression:
listNetworkServiceProvider - initially shows state of nsp to be disabled
VMware - update operation is performed to enabled to NSP:
> UI: Display NSX Provider only when NSX is the selected Isolation method

- api/src/main/java/org/apache/cloudstack/api/command/user/iso/ListIsosCmd.java
- api/src/main/java/org/apache/cloudstack/api/command/user/template/ListTemplatesCmd.java
- ui/src/views/compute/AttachIso.vue
- ui/src/views/compute/AutoScaleVmProfile.vue
- ui/src/views/compute/CreateAutoScaleVmGroup.vue
- ui/src/views/compute/CreateKubernetesCluster.vue
- ui/src/views/compute/DeployVM.vue
- ui/src/views/compute/DeployVnfAppliance.vue
- ui/src/views/compute/EditVM.vue
- ui/src/views/compute/ReinstallVm.vue
- ui/src/views/compute/ResetUserData.vue
- ui/src/views/compute/ScaleVM.vue
- ui/src/views/tools/ImportUnmanagedInstance.vue
This PR adds support to list templates in ready state (new API parameter 'isready', similar to list ISOs), and UI to display Templates/ISOs in ready state wherever applicable.
The latest UI in main uses templatefilter 'all' and oscategoryid to list the templates, which is listing not ready templates as well. Earlier UI listed the templates using the appropriate templatefilters (featured, executable, selfexecutable) which lists only  ready templates.
Fixes #11339  
- List ISOs
- List ISOs in Deploy Instance Form
- List Templates
- List Templates in Deploy Instance Form
Verified list templates / ISOs call while registering new template / ISO.
```
(localcloud) 🐱 > list isos isofilter=all bootable=true filter=id,name,status,isready,ostypename
{
"count": 2,
"iso": [
{
"id": …
```
> Support to list templates in ready state (new API parameter 'isready', similar to list ISOs)

- ui/src/api/index.js
- ui/src/components/view/ListView.vue
- ui/src/components/view/TreeView.vue
- ui/src/components/widgets/InfiniteScrollSelect.vue
- ui/src/views/AutogenView.vue
- ui/src/views/compute/CreateAutoScaleVmGroup.vue
- ui/src/views/compute/DeployVM.vue
- ui/src/views/compute/DeployVnfAppliance.vue
- ui/src/views/iam/DomainView.vue
- ui/src/views/infra/network/providers/ProviderItem.vue
- ui/src/views/network/tungsten/TungstenFabricTableView.vue
- ui/src/views/tools/ManageInstances.vue
- ui/src/views/tools/ManageVolumes.vue
- ui/tests/unit/views/AutogenView.spec.js
This PR updates UI to use GET request method for list API calls.
Earlier some API calls (in generic methods) from UI are using POST request method for the list calls, added here: https://github.com/apache/cloudstack/pull/10899. This PR updates these call to use the GET request method.
Verified the request method (in browser's inspect window) of some list API calls from the CloudStack UI.
> [UI] Use GET request method for list API calls

- plugins/storage/sharedfs/storagevm/src/main/resources/conf/fsvm-init.yml
This PR about the sharedFS VM not functional while systemvm has been configured to use scsi as rootDiskController, this change added controller detection logic during init state.
Tested on OL9 KVM configuration for systemvm with rootDiskController=scsi configuration
> fix fsvm-init.yml to detect virtio-scsi in kvm

- agent/conf/agent.properties
- agent/src/main/java/com/cloud/agent/properties/AgentProperties.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/LibvirtStorageAdaptor.java
This PR adds a configuration called `create.full.clone` to the agent.properties file. When set to true, all QCOW2 volumes created will be full-clone. If false (default), the current behavior remains, where only FAT and SPARSE volumes are full-clone and THIN volumes are linked-clone.
Without setting the property, I deployed a VM, which used linked-clone to create the volume.
Afterward, I added the `create.full.clone` property to` agent.properties`, restarted the agent service, and created another VM. This time, the volume was full-clone.
> Allow full clone volumes with thin provisioning

- api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
- api/src/main/java/org/apache/cloudstack/api/response/SnapshotResponse.java
- server/src/main/java/com/cloud/api/query/dao/SnapshotJoinDaoImpl.java
- server/src/main/java/com/cloud/storage/snapshot/SnapshotManager.java
- server/src/main/java/com/cloud/storage/snapshot/SnapshotManagerImpl.java
- tools/marvin/setup.py
- ui/public/locales/en.json
- ui/src/components/view/DetailsTab.vue
- ui/src/config/section/storage.js
This PR fixes #9416 
When a parent (full) snapshot of an incremental snapshot is deleted in CloudStack, it is removed from the UI/API but not from disk if it has dependent snapshots. As a result, the physical size reported for the incremental snapshot is very small, even though the actual data resides in its parent, which still consumes disk space. From the user’s perspective, there will be a mismatch between the physical size shown in CloudStack and the actual storage usage on disk.
This PR introduces `chain_size` as a new filed in snapshot response for incremental snapshots. The chain_size represents the total disk usage of the snapshot chain, calculated as the sum of the physical size of the snapshot and all its parent snapshots. This provides a more accurate representation of actual …
> Show chain size in snapshot response for incremental snapshots

- agent/src/main/java/com/cloud/agent/Agent.java
- plugins/hypervisors/kvm/src/main/java/org/apache/cloudstack/utils/linux/KVMHostInfo.java
Increases timeout for agent/host arch retrieval
Without change (getting errors like the following):
```
2025-07-21 11:51:01,233 DEBUG [cloud.agent.Agent] (Agent-Handler-1:[]) (logid:) Successfully executed process [1282816] for command [/usr/bin/arch ].
2025-07-21 11:51:01,234 DEBUG [cloud.agent.Agent] (Agent-Handler-1:[]) (logid:) Executing command [/usr/bin/arch ].
2025-07-21 11:51:01,236 DEBUG [cloud.agent.Agent] (Agent-Handler-1:[]) (logid:) Successfully executed process [1282817] for command [/usr/bin/arch ].
2025-07-21 11:51:03,113 DEBUG [cloud.agent.Agent] (AgentRequest-Handler-2:[]) (logid:1a7aaa2d) Request:Seq 2-6273232805950390281:  { Cmd , MgmtId: 32988452618506, via: 2, Ver: v1, Flags: 100111, [{"com.cloud.agent.api.ReadyCommand":{"dcId":"1","hostId":"2","hostUuid":"cd51c3cc-ea …
```
> agent: increase timeout for host arch retrieval

- ui/src/views/compute/CreateAutoScaleVmGroup.vue
- ui/src/views/compute/DeployVM.vue
- ui/src/views/compute/DeployVnfAppliance.vue
- ui/src/views/compute/ReinstallVm.vue
Regression from #10773
All templates for a category are getting listed initially. This PR fixes by adding pagination correctly
> ui: fix initial pagination for images in deploy forms

- packaging/el8/cloud.spec
This fixes packaging issue where CloudStack rpms cannot find tzdata-java on openSUSE/SLES platforms.
Manual download link: (for SLES SP7)
https://download.opensuse.org/repositories/openSUSE:/Leap:/15.2/standard/noarch/timezone-java-2020a-lp152.2.1.noarch.rpm
> cloud.spec: provide option between tzdata-java and timezone-java

- server/src/main/java/com/cloud/network/NetworkModelImpl.java
> server: fix vm deployment without networkid in a zone with shared networks

- plugins/storage/volume/storpool/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/StorPoolDownloadTemplateCommandWrapper.java
- server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
This PR fixes the deployment of a VM with a snapshot that is copied to another zone.
Fix for creating StorPool volume from a snapshot if the size in the offering is bigger than the snapshot size
Manually tested
> Fix of deployment VM from a copied snapshot in another zone

- ui/src/config/section/offering.js
This PR fixes https://github.com/apache/cloudstack/issues/11416
> Fix edit of compute offering in UI

- server/src/main/java/org/apache/cloudstack/consoleproxy/ConsoleAccessManagerImpl.java
When a VM doesn't provide a local cursor, or provides a fully-transparent (invisible) cursor, a dot is shown in the noVNC console after this change.
The dot in the red box in below image
> noVNC: Show a dot cursor when the cursor is not visible

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/BridgeVifDriver.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/DirectVifDriver.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/IvsVifDriver.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/OvsVifDriver.java
- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/VifDriverBase.java
This PR fixes a minor bug in the libvirt domain xml concering the interface bandwidth. In a libvirt domain xml when nw_rate=5000 the kilobytes per second configured in the interface is 640000 which is 5.12 Gbit/s. Which is more than the configured network rate of 5Gbit/s. So instead multiply by 125 (1 Megabit = 125 Kilobyte). 5000 * 125 = 625000 KB/s = 5Gbit/s
QoS is defined in Kilobytes per second according to libvirt [docs](https://libvirt.org/formatnetwork.html#quality-of-service)
> **average**
> Specifies the desired average bit rate for the interface being shaped (in kilobytes/second).
Untested, but the change is trivial.
N/A
> Network rate must be multiplied by 125 not 128

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtGpuDef.java
- scripts/vm/hypervisor/kvm/gpudiscovery.sh
This PR adds support for nvidia SR-IOV supported vGPUs with Vendor specific VFIO Framework.
> Add support for nvidia vGPU support with vendor specific framework

- engine/schema/src/main/java/com/cloud/dc/dao/ClusterDao.java
- engine/schema/src/main/java/com/cloud/dc/dao/ClusterDaoImpl.java
- engine/schema/src/main/java/com/cloud/upgrade/SystemVmTemplateRegistration.java
- engine/schema/src/test/java/com/cloud/dc/dao/ClusterDaoImplTest.java
- engine/schema/src/test/java/com/cloud/upgrade/SystemVmTemplateRegistrationTest.java
- server/src/main/java/com/cloud/storage/StorageManagerImpl.java
During upgrades while checking for system VM templates, new hypervisor type External needs to be excluded as there are no system VM templates involved for that type.
Note: This will not effect current on going release 4.21 as hypervisor type External is introduced in the same version.
> Exclude External hypervisor type during upgrade for System VM template checks

- plugins/storage/volume/linstor/CHANGELOG.md
- plugins/storage/volume/linstor/src/main/java/org/apache/cloudstack/storage/datastore/driver/LinstorPrimaryDataStoreDriverImpl.java
We didn't account for caching the volume stats for each used Linstor cluster, so the first asked Linstor cluster would prevent caching for all the others and so null was returned.
Now we have invalidate counters for each Linstor cluster and also store the cache result with the Linstor cluster address prefixed.
ACS cluster with 2 different Linstor clusters
> linstor: fix getVolumeStats if multiple Linstor primary storages are used

- extensions/Proxmox/proxmox.sh
This PR fixes an issue when restore snapshot in external provider Proxmox
- add cluster and host for proxmox (refer to https://docs.cloudstack.apache.org/en/latest/adminguide/extensions/builtin_extensions.html#proxmox)
- deploy vm in proxmox
- create snapshot-001 with memory
- create snapshot-002 without memory
- restore snapshot-002, worked as expected
- restore snapshot-001, got an exception
Reason:
- snapshot-002 does not have memory, the vm is stopped when restore snapshot-002, starting worked
- snapshot-001 has memory, the vm is still running when restore snapshot-001, starting failed. No need to start
> Proxmox: fix restore snapshot with memory

- engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/VolumeOrchestrator.java
- server/src/main/java/com/cloud/template/TemplateManagerImpl.java
- server/src/main/java/org/apache/cloudstack/snapshot/SnapshotHelper.java
This PR fixes:
regression from #11452 
- When a snapshot has a copy on StorPool primary storage in another zone, but the original snapshot resides on secondary storage, creating a template from the copied snapshot results in the template being created in the first zone.
- For NFS/Ceph - if the `snapshot.backup.to.secondary` setting is disabled, and a user creates a volume or template from a snapshot, the snapshot is temporarily backed up to secondary storage during the operation. After the operation, this backup should be deleted. However, the snapshot currently remains on both primary and secondary storage.
- When a StorPool's snapshot has a backup to a secondary storage, the user can create a volume from that snapshot, but it will be empty. This is caused by #11452 - it sends a …
> Fix of create a template from a StorPool snapshot on another zone

- extensions/HyperV/hyperv.py
- scripts/vm/hypervisor/external/provisioner/provisioner.sh
The valid states are poweron and poweroff.
> scripts: fix external provision to use correct power state & hyperv powersync

- ui/src/config/section/storage.js
This PR fixes: https://github.com/apache/cloudstack/issues/11437
1. Created custom user role with change serviceoffering role permission allow (which is by default allowed even in user role (though not visible))
2. the option is visible in the UI for a volume in Ready or Allocated state
3. Changed the role permission to deny
4. No longer see the option to change volume offering from UI for the user
> UI: Prevent restriction of changeOfferingForVolume API to Admin role

- systemvm/debian/opt/cloud/bin/checkrouter.sh
This PR fixes #10677 
- create a redundant VPC
- create a vpc tier
- create a vm but do not start it
- check the VR redundant state after a while, both vpc VRs are FAULT state
> VPC VR: return UNKNOWN redundant state if no guest nics

- scripts/util/keystore-setup
This PR adds logging to the `keystore-setup` script, and fixes the regex to check old cloudstack-agent password.
When adding KVM hosts, the `keystore-setup` script may fail with `530: Failed to setup keystore on the KVM host).
On the KVM host` for various reasons (absence of keystore, malformatted agent.properties file, missing permissions...).
This adds logs to almost all actions, and also fixes the regex that gets the password from `agent.properties` in order to not fetch commented-out passwords.
Fixes #10703 
Script has been tested on two AlmaLinux 9.5 KVM hosts with a Cloudstack 4.20 management server.
Script has also been submitted to Shellcheck.
Re-ran the tests on multiple hosts to validate that the script works ;)
Log function from the script has been tested on both RHEL and …
> Add logs to keystore-setup and fix password regex

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java
Fixes #11521
QCOW2 file check is not needed when the image format is ISO
> kvm: fix vm deployment with direct-download iso

- server/src/main/java/org/apache/cloudstack/user/UserPasswordResetManager.java
- server/src/main/java/org/apache/cloudstack/user/UserPasswordResetManagerImpl.java
This PR is a minor change on the `resetLink` generated when users self-serve resetting passwords as described in issue https://github.com/apache/cloudstack/issues/11378
It was not tested.
I did not.
> Remove Domain/IP from Password Reset Link to custom Global Setting

- server/src/main/java/com/cloud/api/query/dao/TemplateJoinDaoImpl.java
> server: remove extra chars when template status is error string

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/BridgeVifDriver.java
- plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/BridgeVifDriverTest.java
> kvm: add ssvm storage nic null uri check during plug

- plugins/user-two-factor-authenticators/totp/src/main/java/org/apache/cloudstack/auth/TotpUserTwoFactorAuthenticator.java
> 2fa: log error on totp mismatch

- engine/orchestration/src/main/java/com/cloud/agent/manager/AgentManagerImpl.java
Change log level
In the method `AgentHandler#processRequest()`, the timeout exception of database requests are logged with level warning, this PR corrects the log level to error.
Running the project, and then stopping the database service, to trigger the exception shown below:
``` 
2025-04-25 16:20:39,356 ERROR [c.c.a.m.AgentManagerImpl] (AgentManager-Handler-1:null) (logid:) Caught: 
com.cloud.utils.exception.CloudRuntimeException: DB Exception on: null
at com.cloud.utils.db.GenericDaoBase.update(GenericDaoBase.java:864)
at com.cloud.utils.db.GenericDaoBase.update(GenericDaoBase.java:819)
at com.cloud.utils.db.GenericDaoBase.update(GenericDaoBase.java:1490)
at com.cloud.vm.dao.ConsoleProxyDaoImpl.update(ConsoleProxyDaoImpl.java:138)
at …
```
> Change log level of AgentHandler#processRequest()

- systemvm/debian/opt/cloud/bin/cs/CsNetfilter.py
The VR's firewall service automatically accepts packets from related and established connections when using IPv4. However, it does not for IPv6. Due to this, even if the egress rules allow a VM to send requests to a machine from outside the isolated network, it will not receive the response unless operators have allowed all ingress for the (sometimes dynamically allocated) port.
This PR adds a rule to the VR's IPv6 forward chain accepting response traffic (ingress from related and established connections), even if the operator has not explicitly allowed all ingress for the ports, thus matching the IPv4 firewall's behavior.
1. I introduced an IPv6 range to my environment.
2. I created a network offering for IPv6.
3. I created an isolated network with the network offering.
4. I added a VM …
> IPv6 firewall: accept packets from related and established connections

- scripts/util/keystore-cert-import
This PR fixes reading the libvirt/qemu group name from the libvirtd qemu config file including spaces and quotes,
which is used during the deployment of Host Security Keys.
This PR fixes [https://github.com/apache/cloudstack/issues/11144](https://github.com/apache/cloudstack/issues/11144)
Tested renewal of Host Security Keys on Ubuntu 24.04 hosts and stopping and starting VMs afterwards.
> Fix for No VMs start after Renew Host Security Keys due to wrong qemu group reading

- api/src/main/java/org/apache/cloudstack/api/command/user/loadbalancer/UpdateLoadBalancerRuleCmd.java
- engine/schema/src/main/java/com/cloud/network/dao/LoadBalancerVO.java
- engine/schema/src/test/java/com/cloud/network/dao/LoadBalancerVOTest.java
- server/src/main/java/com/cloud/network/lb/LoadBalancingRulesManagerImpl.java
This PR will allow  the updating of a loadbalancer rules `CIDR list` via the API.
* Should fix https://github.com/apache/cloudstack/issues/9313
I have tested this code in `4.19`, `4.20`, and `main` branches via simulator and all works
Before, the Source CIDR list was blank (Simulator env)
```
(localcloud) :penguin: > list loadbalancerrules
{
"count": 1,
"loadbalancerrule": [
{
"algorithm": "roundrobin",
"cidrlist": "",
"domainid": "5b6a2947-416b-11f0-9a39-564a8191c23c",
"domainpath": "/",
"fordisplay": true,
"id": "0d8e3cb9-767b-45f3-834d-3f9ce85df901",
"name": "newlbtest",
"networkid": "5bb3ecfb-cde3-4821-8822-0c4c8a8e9559",
"privateport": "3306",
"protocol": "tcp",
"publicip": "192.168.2.10",
"publicipid": "9b2638d7-7330-49c7-9d6e-5b5777f6ca16", …
```
> Allow updating of Load Balancer source CIDR list

- plugins/network-elements/netris/src/main/java/org/apache/cloudstack/service/NetrisApiClientImpl.java
This PR addresses an issue with cleanup of inactive VPCs. For whatever reason, if a VPC isn't found on Netris end either due to some out of band operation or due to some other activity, deletion of the VPC fails reporting that it can't find the resource on Netris. This fix makes the check lenient by not failing the cleanup operation if the resource(VPC) isn't found on Netris end - it just logs it and proceeds to clean it up on CloudStack end.
> Netris: Fix inactive VPCs deletion

- server/src/main/java/com/cloud/server/StatsCollector.java
This PR removes the usage of uptime command which fails on certain OS like open SUSE with the below error.
```bash
uptime -s
uptime: invalid option -- 's'
Try 'uptime --help' for more information.
```
> use /prod/stat to get uptime instead of the uptime command

- CHANGES.md
- INSTALL.md
- README.md
- tools/devcloud4/advanced/README.md
- tools/devcloud4/basic/README.md
- ui/docs/full-test-plan.template.md
- ui/docs/smoke-test-plan.template.md
> chore(markdown): use https on links

- plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtDeleteVMSnapshotCommandWrapper.java
This PR fixes #11673
- deploy vm in kvm environments
- create vm snapshot
- delete the vm snapshot by `qemu-img snapshot -d <snapshot name> <qcow2 image path of vm>
- stop the vm
- delete the vm snapshot on cloudstack GUI
Prior to this PR
```
2025-09-19T12:14:05,455 DEBUG [utils.script.Script] (Script-7:[]) (logid:) Piped commands executed successfully
2025-09-19T12:14:05,455 DEBUG [utils.script.Script] (AgentRequest-Handler-2:[]) (logid:) Executing command [/usr/bin/qemu-img snapshot -d i-2-23-VM_VS_20250919102815 /mnt/92a06402-16ab-35e8-950e-d84499c5e942/57c64582-aa4b-4329-bf18-9bcb14dffd57 ].
2025-09-19T12:14:05,594 WARN  [utils.script.Script] (AgentRequest-Handler-2:[]) (logid:) Execution of process [983177] for command [/usr/bin/qemu-img snapshot -d …
```
> KVM: fix delete vm snapshot if it does not exist with a Stopped vm

- plugins/hypervisors/external/src/main/java/org/apache/cloudstack/hypervisor/external/provisioner/ExternalPathPayloadProvisioner.java
> Extensions: use home directory of cloud user instead of /var/lib/cloudstack/management/

- ui/src/components/widgets/DetailsInput.vue
In DetailInput component when a long value is used, it overflows on some browsers.
Before and after on Firefox browser.
Before:
After:
> ui: fix overflow for value in DetailInput

- plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java
This PR fixes a regression of #11528
> CKS: fix CKS creation on an existing Shared or Routed network

- framework/extensions/src/main/java/org/apache/cloudstack/framework/extensions/api/DeleteExtensionCmd.java
- framework/extensions/src/main/java/org/apache/cloudstack/framework/extensions/manager/ExtensionsManagerImpl.java
- plugins/hypervisors/external/src/main/java/org/apache/cloudstack/hypervisor/external/provisioner/ExternalPathPayloadProvisioner.java
- ui/src/views/extension/CreateExtension.vue
> refactor: remove use of term entry-point from extensions code base
